// ── Materials Science Taxonomy — Families 5-7 (Thermodynamics, Phase Diagrams, Diffusion/Kinetics) ──

import type { Family } from "./data";

// ── Family 5 — Thermodynamics ───────────────────────────────────────────────

const THERMODYNAMICS: Family = {
  slug: "thermodynamics",
  number: 5,
  name: "Thermodynamics of Materials",
  blurb: "Energy, entropy, and equilibrium — predicting which phases are stable and why.",
  section: "B",
  color: "green",
  concepts: [
    {
      name: "Gibbs free energy",
      description: "The thermodynamic potential that determines phase stability at constant T and P.",
      tags: ["thermo", "fundamentals"],
      statement: "The Gibbs free energy $G = H - TS$ determines equilibrium at constant temperature and pressure. A system minimizes $G$; phase transformations occur when one phase's $G$ drops below another's. The temperature dependence is $dG = -SdT + VdP$, so phases with higher entropy are favored at higher temperature.",
      prerequisites: { parents: ["The materials tetrahedron"], divergence: "the thermodynamic criterion for phase stability" },
      keyResults: [
        "At equilibrium, G is minimized — all spontaneous changes decrease G",
        "Phase with lowest G at given T, P is the stable phase",
        "G vs T curves for different phases cross at transformation temperatures",
      ],
      tetrahedron: "property",
      example: "At 912 C the G(T) curves for BCC alpha-Fe and FCC gamma-Fe cross: above this temperature, gamma-Fe (higher entropy due to more vibrational modes) has lower G and is stable.",
    },
    {
      name: "Chemical potential",
      description: "The partial molar Gibbs energy — the thermodynamic driving force for diffusion and phase change.",
      tags: ["thermo", "solutions"],
      statement: "The chemical potential of component $i$ is $\\mu_i = (\\partial G / \\partial n_i)_{T,P,n_{j \\neq i}}$. At equilibrium, $\\mu_i$ must be equal in all phases. Gradients in $\\mu_i$ drive diffusion. For an ideal solution, $\\mu_i = \\mu_i^0 + RT \\ln x_i$.",
      prerequisites: { parents: ["Gibbs free energy"], divergence: "per-component thermodynamic potential" },
      keyResults: [
        "Diffusion occurs down chemical potential gradients, not necessarily down concentration gradients",
        "Phase boundaries are loci where chemical potentials are equal between phases",
        "Activity $a_i = \\exp[(\\mu_i - \\mu_i^0)/RT]$ measures effective concentration",
      ],
      tetrahedron: "property",
      example: "Carbon diffuses uphill in concentration near a weld between low-alloy and stainless steel because the chemical potential of C is lower in the Cr-rich stainless — the driving force is the chemical potential gradient, not concentration.",
    },
    {
      name: "Gibbs phase rule",
      description: "The relationship between degrees of freedom, components, and phases.",
      tags: ["thermo", "phase"],
      statement: "The Gibbs phase rule states $F = C - P + 2$ where $F$ = degrees of freedom (independently variable intensive properties), $C$ = number of components, $P$ = number of phases in equilibrium. For condensed-matter systems at fixed pressure, $F = C - P + 1$.",
      prerequisites: { parents: ["Gibbs free energy"], divergence: "counting constraints on phase equilibria" },
      keyResults: [
        "A pure substance (C=1) in two-phase equilibrium (P=2) has F=1: only T or P is free",
        "A eutectic point (C=2, P=3) has F=0: T and composition are fixed",
        "Allows prediction of phase diagram topology from component count",
      ],
      tetrahedron: "property",
      example: "At the eutectic point in the Pb-Sn system (183 C, 61.9% Sn), three phases coexist (liquid + alpha + beta). F = 2-3+1 = 0, so both temperature and composition are fixed — a unique invariant point.",
    },
    {
      name: "Ideal & regular solutions",
      description: "Models for mixing thermodynamics in alloys.",
      tags: ["thermo", "solutions", "alloys"],
      statement: "An ideal solution has $\\Delta H_{mix} = 0$ and $\\Delta S_{mix} = -R \\sum x_i \\ln x_i$ (purely configurational entropy). A regular solution adds an enthalpy of mixing: $\\Delta H_{mix} = \\Omega x_A x_B$ where $\\Omega$ is the interaction parameter. If $\\Omega > 0$, the system tends toward phase separation (miscibility gap); if $\\Omega < 0$, toward ordering.",
      prerequisites: { parents: ["Gibbs free energy", "Chemical potential"], divergence: "simple models for alloy thermodynamics" },
      keyResults: [
        "Positive $\\Omega$: miscibility gap (Cu-Pb, Cu-Co) — spinodal decomposition possible",
        "Negative $\\Omega$: ordering tendency (Cu-Au, Fe-Al) — intermetallic formation",
        "The regular solution model captures the essential physics of binary phase diagrams",
      ],
      tetrahedron: "property",
      example: "The Cu-Ni system ($\\Omega \\approx +12$ kJ/mol) shows a miscibility gap below ~350 C where Cu-rich and Ni-rich phases separate — the basis of spinodal decomposition hardening in some Cu-Ni alloys.",
    },
    {
      name: "Surface energy",
      description: "The excess free energy associated with creating a surface.",
      tags: ["thermo", "surfaces"],
      statement: "Creating a surface of area $A$ requires energy $\\gamma A$ where $\\gamma$ (J/m$^2$) is the surface energy. For metals, $\\gamma \\approx 1$-$3$ J/m$^2$; for oxides, $\\gamma \\approx 0.5$-$2$ J/m$^2$; for polymers, $\\gamma \\approx 0.02$-$0.05$ J/m$^2$. Surface energy drives grain growth, sintering, Ostwald ripening, and sets the critical nucleus size.",
      prerequisites: { parents: ["Gibbs free energy", "Surfaces & interfaces"], divergence: "thermodynamic cost of interface creation" },
      keyResults: [
        "Critical nucleus radius $r^* = 2\\gamma / \\Delta G_v$ — smaller nuclei shrink, larger ones grow",
        "Young's equation relates surface energies at a triple line: $\\gamma_{SV} = \\gamma_{SL} + \\gamma_{LV} \\cos\\theta$",
        "Nanomaterials have excess surface energy that can depress melting points by hundreds of degrees",
      ],
      tetrahedron: "property",
      example: "Gold nanoparticles melt at 300 C instead of 1064 C when their diameter is below 2 nm, because the surface energy contribution to G becomes comparable to the bulk free energy.",
    },
    {
      name: "Ellingham diagrams",
      description: "Standard free energy of oxide formation vs temperature — predicting reduction reactions.",
      tags: ["thermo", "extractive metallurgy"],
      statement: "An Ellingham diagram plots $\\Delta G^\\circ$ for metal oxide formation (per mole O$_2$) vs temperature. Lines are approximately straight (slope = $-\\Delta S^\\circ$). A metal can reduce any oxide whose line lies above it on the diagram. Breaks in slope occur at phase transitions. The C/CO/CO$_2$ lines cross metal oxide lines, determining smelting temperatures.",
      prerequisites: { parents: ["Gibbs free energy"], divergence: "practical graphical tool for metallurgical thermodynamics" },
      keyResults: [
        "Al2O3 line is very low — aluminum is a powerful reducing agent (thermite reaction)",
        "The C line has positive slope (entropy of CO gas) — C becomes a better reductant at high T",
        "Used to select deoxidizers in steelmaking and predict refractories stability",
      ],
      tetrahedron: "processing",
      example: "Iron ore (Fe2O3) can be reduced by carbon above ~700 C because the C/CO line crosses below the Fe2O3 line at this temperature. This is why blast furnaces operate at 1500-2000 C — thermodynamics permits and kinetics demand it.",
    },
  ],
};

// ── Family 6 — Phase Diagrams ───────────────────────────────────────────────

const PHASE_DIAGRAMS: Family = {
  slug: "phase-diagrams",
  number: 6,
  name: "Phase Diagrams",
  blurb: "Maps of equilibrium phases as functions of temperature, composition, and pressure.",
  section: "B",
  color: "emerald",
  concepts: [
    {
      name: "Phase diagram concept",
      description: "Graphical representations of phase stability fields.",
      tags: ["phase", "fundamentals"],
      statement: "A phase diagram maps the equilibrium phases present as a function of state variables (temperature, composition, pressure). Single-phase regions are areas; two-phase regions contain tie lines connecting coexisting compositions; three-phase equilibria are invariant reactions (horizontal lines in binary T-x diagrams). Phase diagrams are the road maps of materials processing.",
      prerequisites: { parents: ["Gibbs free energy", "Gibbs phase rule"], divergence: "graphical representation of phase equilibria" },
      keyResults: [
        "Each point on the diagram specifies which phase(s) are stable at equilibrium",
        "Two-phase regions allow determination of phase compositions and amounts",
        "Real alloys may not reach equilibrium — kinetics matter (see TTT/CCT diagrams)",
      ],
      tetrahedron: "processing→structure",
      example: "A metallurgist reading the Al-Si phase diagram knows that Al-12.6% Si is the eutectic composition (lowest melting point, 577 C), ideal for casting. Hypo- or hypereutectic compositions solidify over a range.",
    },
    {
      name: "Binary isomorphous system",
      description: "The simplest phase diagram — complete solid solubility between two components.",
      tags: ["phase", "binary"],
      statement: "In an isomorphous system (e.g., Cu-Ni), the two components are completely miscible in both liquid and solid states. The phase diagram shows a lens-shaped two-phase (L+S) region bounded by the liquidus (above which all liquid) and solidus (below which all solid). Solidification is progressive, with the first solid enriched in the higher-melting component.",
      prerequisites: { parents: ["Phase diagram concept"], divergence: "simplest binary phase diagram — complete miscibility" },
      keyResults: [
        "The solid composition at any T is read from the solidus; liquid from the liquidus",
        "Under equilibrium cooling, the last solid to form has composition equal to the overall alloy",
        "Non-equilibrium cooling causes coring (compositional gradients within grains)",
      ],
      tetrahedron: "processing→structure",
      example: "Cu-Ni alloys (complete solid solubility): a Cu-40% Ni alloy begins solidifying at ~1280 C (liquidus) and completes at ~1240 C (solidus). Monel 400 (67Ni-30Cu) is a commercial alloy exploiting this system.",
    },
    {
      name: "Lever rule",
      description: "Calculating the fraction of each phase in a two-phase region.",
      tags: ["phase", "calculation"],
      statement: "In a two-phase region, the mass fraction of each phase is given by the lever rule: $W_\\alpha = (C_\\beta - C_0)/(C_\\beta - C_\\alpha)$ and $W_\\beta = (C_0 - C_\\alpha)/(C_\\beta - C_\\alpha)$, where $C_0$ is the overall composition, $C_\\alpha$ and $C_\\beta$ are the phase compositions read from the ends of the tie line.",
      prerequisites: { parents: ["Phase diagram concept"], divergence: "quantitative phase fraction calculation" },
      keyResults: [
        "The fraction of each phase is inversely proportional to its distance from the overall composition",
        "At the eutectic temperature, the lever rule gives the fraction of primary phase vs eutectic microconstituent",
        "Applies to any two-phase region in any binary diagram",
      ],
      tetrahedron: "structure",
      example: "In Cu-Ni at 1250 C, an alloy of Cu-35% Ni has solidus at 30% Ni and liquidus at 42% Ni. W_solid = (42-35)/(42-30) = 58.3% solid, 41.7% liquid.",
    },
    {
      name: "Eutectic system",
      description: "A system where two components have limited mutual solubility and a lowest-melting composition.",
      tags: ["phase", "binary", "eutectic"],
      statement: "A eutectic reaction is $L \\to \\alpha + \\beta$ at a fixed temperature and composition (the eutectic point). Below this temperature, two solid phases coexist. The eutectic microstructure is typically a fine lamellar or rod mixture of $\\alpha$ and $\\beta$ phases. Eutectic alloys solidify at a single temperature like a pure metal, making them ideal for casting.",
      prerequisites: { parents: ["Phase diagram concept", "Lever rule"], divergence: "the most common invariant reaction in binary systems" },
      keyResults: [
        "Eutectic composition has the lowest melting point of any alloy in the system",
        "Lamellar spacing in eutectic microstructures decreases with faster cooling rate",
        "Hypoeutectic alloys show primary alpha dendrites + eutectic; hypereutectic show primary beta + eutectic",
      ],
      tetrahedron: "processing→structure",
      example: "The Pb-Sn eutectic (61.9% Sn, 183 C) was the traditional solder: low melting point, sharp solidification, and good wetting. Now replaced by Pb-free SAC alloys (Sn-Ag-Cu) for environmental reasons.",
    },
    {
      name: "Peritectic & monotectic reactions",
      description: "Other invariant reactions in binary phase diagrams.",
      tags: ["phase", "binary", "invariant"],
      statement: "A peritectic reaction is $L + \\alpha \\to \\beta$ — liquid reacts with an existing solid to form a new solid. A monotectic is $L_1 \\to \\alpha + L_2$ — one liquid decomposes into a solid and a different liquid. Peritectics are common in Fe-C, Cu-Sn, Cu-Zn systems. Peritectic reactions are sluggish because the product phase coats the reactant solid, blocking further reaction.",
      prerequisites: { parents: ["Phase diagram concept"], divergence: "invariant reactions beyond the eutectic" },
      keyResults: [
        "Peritectic: delta-Fe + L -> gamma-Fe in the Fe-C system at 1495 C and 0.17% C",
        "Peritectic solidification often produces severe microsegregation",
        "Monotectic systems (Cu-Pb) have immiscible liquid regions",
      ],
      tetrahedron: "processing→structure",
      example: "In continuous casting of low-carbon steel, the peritectic reaction at 0.17% C causes a volume contraction that creates air gaps between the steel shell and mold wall, leading to uneven cooling and surface defects.",
    },
    {
      name: "Intermetallic compounds",
      description: "Ordered phases with specific stoichiometry and crystal structure distinct from either component.",
      tags: ["phase", "compounds"],
      statement: "Intermetallic compounds are ordered alloy phases with well-defined stoichiometry (e.g., Ni$_3$Al, TiAl, Fe$_3$C) and crystal structures distinct from either pure component. They appear as line compounds (narrow composition range) or intermediate phases (wider range) on phase diagrams. Properties include high hardness, high melting points, but often low ductility.",
      prerequisites: { parents: ["Phase diagram concept", "Chemical bonding overview"], divergence: "ordered phases between metallic elements" },
      keyResults: [
        "Ni3Al (gamma-prime, L12 structure) strengthens Ni-base superalloys for jet engines",
        "TiAl (gamma phase) is used in low-pressure turbine blades (half the density of Ni alloys)",
        "Fe3C (cementite) is the hard phase in steels — its morphology controls mechanical properties",
      ],
      tetrahedron: "structure→property",
      example: "Ni3Al (gamma-prime) has the remarkable property of increasing in strength with temperature up to ~800 C (anomalous yield stress). This is why Ni-base superalloys can operate at 85% of their melting point in jet engines.",
    },
    {
      name: "Fe-C phase diagram",
      description: "The most important phase diagram in engineering — the basis of all steel metallurgy.",
      tags: ["phase", "steels", "essential"],
      statement: "The Fe-C system has a eutectoid reaction at ~0.76 wt% C and 727 C: $\\gamma \\to \\alpha + \\text{Fe}_3\\text{C}$ (austenite transforms to ferrite + cementite, producing pearlite). The eutectic at 4.3% C and 1148 C divides steels ($< 2.14\\%$ C) from cast irons ($> 2.14\\%$ C). The eutectoid is the basis of all heat treatment of steels.",
      prerequisites: { parents: ["Eutectic system", "Polymorphism & allotropy"], divergence: "the master phase diagram for steel engineering" },
      keyResults: [
        "Hypoeutectoid steels (<0.76% C): primary ferrite + pearlite; hypereutectoid: primary cementite + pearlite",
        "Austenite (gamma-Fe, FCC) dissolves up to 2.14% C; ferrite (alpha-Fe, BCC) only 0.022% C",
        "Alloying elements shift eutectoid temperature and composition (Cr raises, Ni lowers eutectoid T)",
      ],
      tetrahedron: "processing→structure",
      example: "A 1045 steel (0.45% C, hypoeutectoid) slowly cooled from 850 C produces ~43% pearlite and ~57% primary ferrite. Quenched, the same steel forms martensite with hardness ~58 HRC — same composition, vastly different properties.",
    },
    {
      name: "CALPHAD method",
      description: "Computational thermodynamics — calculating phase diagrams from assessed thermodynamic databases.",
      tags: ["phase", "computational"],
      statement: "CALPHAD (CALculation of PHAse Diagrams) uses assessed Gibbs energy functions for each phase, optimized against experimental data, to compute multi-component phase diagrams. Modern databases (e.g., TCFE for steels) cover 20+ elements simultaneously. Software (Thermo-Calc, FactSage, Pandat) minimizes total G at each T and composition to predict equilibrium phases.",
      prerequisites: { parents: ["Gibbs free energy", "Phase diagram concept"], divergence: "computational prediction of multi-component phase equilibria" },
      keyResults: [
        "Extends binary/ternary experimental data to predict 10+ component alloy behavior",
        "Essential for alloy design — reduces the experimental matrix by orders of magnitude",
        "Scheil-Gulliver module predicts non-equilibrium solidification paths",
      ],
      tetrahedron: "processing→structure",
      example: "CALPHAD-based alloy design predicted the composition of a new high-entropy alloy (CoCrFeMnNi) to be single-phase FCC from 600-1400 C — confirmed experimentally. Without CALPHAD, exploring the 5-component space would require thousands of experiments.",
    },
  ],
};

// ── Family 7 — Diffusion & Kinetics ─────────────────────────────────────────

const DIFFUSION_KINETICS: Family = {
  slug: "diffusion-kinetics",
  number: 7,
  name: "Diffusion & Kinetics",
  blurb: "How atoms move and how fast transformations occur.",
  section: "B",
  color: "teal",
  concepts: [
    {
      name: "Diffusion concept",
      description: "Net atomic transport driven by chemical potential gradients.",
      tags: ["kinetics", "fundamentals"],
      statement: "Diffusion is the net transport of atoms or molecules driven by gradients in chemical potential. In most cases this correlates with concentration gradients (Fick's laws), but uphill diffusion occurs when chemical potential gradients oppose concentration gradients. Diffusion is the rate-controlling step in most solid-state transformations.",
      prerequisites: { parents: ["Point defects", "Chemical potential"], divergence: "the kinetic complement to thermodynamic equilibrium" },
      keyResults: [
        "Controls rates of precipitation, oxidation, sintering, creep, and homogenization",
        "Interstitial diffusion is 100-1000x faster than substitutional diffusion",
        "Characteristic diffusion distance scales as $x \\sim \\sqrt{Dt}$",
      ],
      tetrahedron: "processing→structure",
      example: "Carburizing steel at 927 C for 5 hours (D_C ~2x10^-11 m2/s) produces a hardened case ~1 mm deep: $x \\approx \\sqrt{Dt} = \\sqrt{2 \\times 10^{-11} \\times 18000} \\approx 0.6$ mm.",
    },
    {
      name: "Fick's first law",
      description: "Steady-state diffusion flux is proportional to the concentration gradient.",
      tags: ["kinetics", "diffusion"],
      statement: "Fick's first law: $J = -D \\, dC/dx$ where $J$ is the flux (atoms/m$^2\\cdot$s), $D$ is the diffusion coefficient (m$^2$/s), and $dC/dx$ is the concentration gradient. The negative sign indicates flux is down the gradient. Applies to steady-state diffusion (flux constant in time).",
      prerequisites: { parents: ["Diffusion concept"], divergence: "steady-state diffusion" },
      keyResults: [
        "Flux is proportional to gradient — steeper gradient = faster diffusion",
        "D has units of m^2/s and varies from ~10^-5 (gases) to ~10^-20 (solids at low T)",
        "Applies to permeation through membranes, thin-film diffusion barriers",
      ],
      tetrahedron: "processing",
      example: "Hydrogen permeation through a 1 mm steel wall at 400 C with D_H = 10^-8 m^2/s and a concentration drop of 10^3 mol/m^3 gives J = 10^-8 x 10^3/10^-3 = 10^-2 mol/m^2-s.",
    },
    {
      name: "Fick's second law",
      description: "Non-steady-state diffusion — how concentration profiles evolve with time.",
      tags: ["kinetics", "diffusion"],
      statement: "Fick's second law: $\\partial C/\\partial t = D \\, \\partial^2 C/\\partial x^2$ (for constant $D$). This parabolic PDE governs how concentration profiles evolve over time. For a semi-infinite solid with constant surface concentration: $C(x,t) = C_s - (C_s - C_0) \\operatorname{erf}(x / 2\\sqrt{Dt})$.",
      prerequisites: { parents: ["Fick's first law"], divergence: "time-dependent diffusion" },
      keyResults: [
        "The error function solution is the workhorse for carburizing, nitriding, doping calculations",
        "Diffusion distance scales as $\\sqrt{Dt}$ — doubling depth requires 4x time",
        "Superposition applies — complex boundary conditions can be built from simple solutions",
      ],
      tetrahedron: "processing→structure",
      example: "To carburize a gear to a case depth of 1 mm at 927 C (D=2x10^-11 m^2/s), solve for t: 1mm = sqrt(Dt) gives t ~14 hours. Doubling to 2 mm would require ~56 hours (4x).",
    },
    {
      name: "Arrhenius temperature dependence",
      description: "Diffusion coefficient (and most rate constants) increase exponentially with temperature.",
      tags: ["kinetics", "temperature"],
      statement: "The diffusion coefficient follows an Arrhenius relation: $D = D_0 \\exp(-Q_d/RT)$ where $D_0$ is the pre-exponential factor, $Q_d$ is the activation energy (J/mol), $R = 8.314$ J/mol-K, and $T$ is absolute temperature. A plot of $\\ln D$ vs $1/T$ is linear with slope $-Q_d/R$.",
      prerequisites: { parents: ["Diffusion concept"], divergence: "the exponential temperature dependence of kinetic processes" },
      keyResults: [
        "Every ~20 C increase roughly doubles the diffusion rate (for typical activation energies)",
        "Interstitial diffusion has lower Q_d (~50-100 kJ/mol) than substitutional (~100-300 kJ/mol)",
        "Same Arrhenius form governs reaction rates, creep rates, oxidation rates",
      ],
      tetrahedron: "processing",
      example: "C in alpha-Fe: D_0 = 6.2x10^-7 m^2/s, Q_d = 80 kJ/mol. At 500 C: D = 2.4x10^-12 m^2/s; at 900 C: D = 1.7x10^-10 m^2/s — a 70x increase for a 400 C temperature rise.",
    },
    {
      name: "Diffusion mechanisms",
      description: "Atomic mechanisms of diffusion: vacancy, interstitial, and grain boundary.",
      tags: ["kinetics", "mechanisms"],
      statement: "Substitutional atoms diffuse by the vacancy mechanism (swap with an adjacent vacancy). Interstitial atoms jump between interstitial sites without needing a vacancy. Grain boundary diffusion is 100-1000x faster than lattice diffusion because of the disordered boundary structure. Surface diffusion is faster still.",
      prerequisites: { parents: ["Diffusion concept", "Point defects", "Grain boundaries"], divergence: "the atomic-level mechanisms" },
      keyResults: [
        "Vacancy mechanism: D proportional to vacancy concentration (increases with T)",
        "Interstitial: smaller atoms (H, C, N, O) in metals; no vacancy needed",
        "At low temperatures, grain boundary and surface diffusion dominate over lattice diffusion",
      ],
      tetrahedron: "structure→property",
      example: "Hydrogen diffuses through BCC iron ~10^6 times faster than substitutional chromium because H uses interstitial sites and has Q_d ~13 kJ/mol vs Cr's ~250 kJ/mol.",
    },
    {
      name: "Kirkendall effect",
      description: "Net mass flow due to unequal diffusion rates — proof that vacancies mediate diffusion.",
      tags: ["kinetics", "historical"],
      statement: "When two metals with different diffusion rates are joined and heated, the faster diffusor creates a net vacancy flux in the opposite direction. This causes the interface to shift (Kirkendall markers move) and can create Kirkendall voids. Demonstrated by E. Kirkendall in 1947 for Cu-Zn, proving the vacancy mechanism of diffusion.",
      prerequisites: { parents: ["Diffusion mechanisms"], divergence: "experimental proof of the vacancy mechanism" },
      keyResults: [
        "Inert markers at the original interface shift toward the faster-diffusing side",
        "Kirkendall voids form when vacancy supersaturation exceeds a critical level",
        "Now exploited to fabricate hollow nanostructures (nanoscale Kirkendall effect)",
      ],
      tetrahedron: "processing→structure",
      example: "In Cu-Zn diffusion couples, Zn diffuses faster into Cu than Cu into Zn, creating voids on the Zn-rich side. This was the definitive proof against the 'ring mechanism' and for the vacancy mechanism of diffusion.",
    },
    {
      name: "Nucleation & growth",
      description: "How new phases form: overcoming the nucleation barrier, then growing.",
      tags: ["kinetics", "transformation"],
      statement: "Phase transformations occur by nucleation (forming a small region of the new phase) followed by growth. The nucleation barrier arises from the competition between volume free energy gain ($\\propto r^3$) and surface energy cost ($\\propto r^2$): $\\Delta G^* = 16\\pi\\gamma^3 / 3(\\Delta G_v)^2$. Below the critical radius $r^* = 2\\gamma/\\Delta G_v$, nuclei shrink; above it, they grow. Heterogeneous nucleation at defects reduces $\\Delta G^*$.",
      prerequisites: { parents: ["Gibbs free energy", "Surface energy", "Defects overview"], divergence: "the kinetics of phase transformation initiation" },
      keyResults: [
        "Undercooling is needed to provide thermodynamic driving force for nucleation",
        "Heterogeneous nucleation at grain boundaries, dislocations, surfaces requires less undercooling",
        "The nucleation rate is $I \\propto \\exp(-\\Delta G^*/k_BT)$ — extremely sensitive to undercooling",
      ],
      tetrahedron: "processing→structure",
      example: "Water can be supercooled to -40 C before homogeneous nucleation occurs, but a dust particle provides a heterogeneous nucleation site at just -5 C. Same physics applies to solidification of metals.",
    },
    {
      name: "TTT & CCT diagrams",
      description: "Time-temperature-transformation diagrams — predicting microstructure from cooling history.",
      tags: ["kinetics", "steels", "transformation"],
      statement: "TTT (isothermal) diagrams plot the start and finish of transformations as C-curves on time-temperature axes. CCT (continuous cooling) diagrams show the same for constant cooling rates. The nose of the C-curve is where the transformation is fastest (optimal balance of driving force and diffusivity). Cooling faster than the critical rate bypasses the nose, producing martensite.",
      prerequisites: { parents: ["Nucleation & growth", "Fe-C phase diagram"], divergence: "practical maps of transformation kinetics" },
      keyResults: [
        "Above the nose: controlled pearlite/bainite transformation (lower hardness, more ductility)",
        "Below the nose (fast quench): martensite (very hard, brittle, needs tempering)",
        "Alloying elements (Cr, Mo, Ni) shift C-curves to longer times — improved hardenability",
      ],
      tetrahedron: "processing→structure",
      example: "A 4340 steel TTT diagram shows the pearlite nose at ~550 C, 10 seconds. Oil quenching (cooling rate ~150 C/s) passes left of the nose, producing martensite. Air cooling (~5 C/s) passes through it, producing bainite + pearlite.",
    },
    {
      name: "Martensitic transformation",
      description: "Diffusionless, displacive transformation producing a hard, metastable phase.",
      tags: ["kinetics", "steels", "transformation"],
      statement: "Martensitic transformations are diffusionless — atoms move cooperatively by less than one interatomic distance. In steels, quenching austenite (FCC) traps carbon in a body-centered tetragonal (BCT) structure. The $M_s$ (martensite start) temperature depends on composition: $M_s \\approx 539 - 423(\\%C) - 30.4(\\%Mn) - 17.7(\\%Ni) - 12.1(\\%Cr) - 7.5(\\%Mo)$ ($^\\circ$C, Andrews formula).",
      prerequisites: { parents: ["TTT & CCT diagrams", "Fe-C phase diagram"], divergence: "diffusionless transformation — no time for diffusion" },
      keyResults: [
        "Hardness of martensite depends primarily on carbon content (up to ~65 HRC at 0.8% C)",
        "Volume expansion (~4%) during transformation generates residual stresses and potential cracking",
        "Shape memory alloys (NiTi) use a thermoelastic martensitic transformation for shape recovery",
      ],
      tetrahedron: "processing→structure",
      example: "Nitinol (NiTi) shape memory alloy uses a thermoelastic martensitic transformation: deformed martensite recovers its original shape when heated above the austenite finish temperature (~60 C for medical stents).",
    },
    {
      name: "Spinodal decomposition",
      description: "Continuous phase separation without nucleation — inside the spinodal curve.",
      tags: ["kinetics", "transformation"],
      statement: "Inside the spinodal region (where $\\partial^2 G / \\partial C^2 < 0$), any compositional fluctuation grows spontaneously — no nucleation barrier exists. The Cahn-Hilliard equation describes the evolution: $\\partial C / \\partial t = M \\nabla^2 [\\partial f/\\partial C - \\kappa \\nabla^2 C]$. The result is a characteristic interconnected, wavelike modulated structure.",
      prerequisites: { parents: ["Ideal & regular solutions", "Nucleation & growth"], divergence: "barrier-free decomposition inside the spinodal" },
      keyResults: [
        "Produces interconnected, periodic modulated structures (wavelength selected by gradient energy)",
        "No incubation time — transformation begins immediately upon entering the spinodal region",
        "Strengthens by Vegard strain: modulated structure impedes dislocation motion",
      ],
      tetrahedron: "processing→structure",
      example: "Cu-Ni-Fe alloys undergo spinodal decomposition to produce nanoscale Cu-rich and Ni-Fe-rich modulations that increase yield strength by 2-3x while maintaining ductility — used in high-strength marine components.",
    },
    {
      name: "Ostwald ripening",
      description: "Coarsening of precipitates driven by the Gibbs-Thomson effect — large grow at small's expense.",
      tags: ["kinetics", "coarsening"],
      statement: "Ostwald ripening (coarsening) occurs because smaller particles have higher surface energy per unit volume and therefore higher solubility (Gibbs-Thomson effect). Atoms diffuse from smaller to larger particles, causing the average particle radius to grow: $\\bar{r}^3 - \\bar{r}_0^3 \\propto t$ (LSW theory, Lifshitz-Slyozov-Wagner). The number density of particles decreases with time.",
      prerequisites: { parents: ["Surface energy", "Diffusion concept"], divergence: "thermodynamic coarsening of dispersed particles" },
      keyResults: [
        "Particle radius scales as $t^{1/3}$ — very slow coarsening at low temperatures",
        "Reduces strengthening from precipitates over long service times (overaging)",
        "Can be slowed by adding elements that reduce interface energy or diffusivity",
      ],
      tetrahedron: "structure→property",
      example: "Ni-base superalloy turbine blades in jet engines experience gamma-prime precipitate coarsening (rafting) during 10,000+ hour service at 1000 C, gradually reducing creep strength. Alloy design minimizes the lattice misfit to slow this process.",
    },
    {
      name: "Recovery, recrystallization & grain growth",
      description: "Restoration of cold-worked microstructures by thermal annealing.",
      tags: ["kinetics", "annealing"],
      statement: "Cold-worked metals contain stored energy (dislocations). Annealing drives three sequential processes: (1) Recovery — dislocation rearrangement into lower-energy configurations (polygonization), partial restoration of conductivity; (2) Recrystallization — nucleation and growth of new, strain-free grains, restoring ductility; occurs above ~0.4 $T_m$; (3) Grain growth — driven by grain boundary energy reduction, coarsening follows $\\bar{d}^2 - \\bar{d}_0^2 = Kt$.",
      prerequisites: { parents: ["Dislocations", "Grain boundaries", "Nucleation & growth"], divergence: "thermal restoration of cold-worked microstructures" },
      keyResults: [
        "Recrystallization temperature decreases with increasing prior cold work",
        "Grain size after recrystallization is controlled by the amount of prior deformation and annealing temperature",
        "Zener pinning by second-phase particles limits grain growth: $\\bar{d}_{max} \\propto r/f$ (r = particle radius, f = volume fraction)",
      ],
      tetrahedron: "processing→structure",
      example: "Aluminum sheet for beverage cans is cold-rolled 90%, then annealed at 350 C for ~1 hour to recrystallize to ~10 um grain size, restoring formability for deep drawing while maintaining moderate strength.",
    },
  ],
};

export const FAMILIES_5_7: Family[] = [
  THERMODYNAMICS,
  PHASE_DIAGRAMS,
  DIFFUSION_KINETICS,
];
