import type { Family } from "./types";

export const FAMILIES_7_12: Family[] = [
  // ── Family 7 ──────────────────────────────────────────────────────────────
  {
    slug: "functional-analysis-measure-theory",
    number: 7,
    name: "Functional Analysis & Measure Theory",
    blurb: "Measures, integration, Banach and Hilbert spaces, bounded operators, and the foundations of modern analysis.",
    section: "B",
    color: "sky",
    entries: [
      {
        name: "Sigma-algebra",
        description: "The measurable sets.",
        statement: "a collection closed under complements and countable unions, containing $\\varnothing$.",
        keyResults: "the Borel $\\sigma$-algebra; the domain of any measure.",
        prereqs: ["sets"],
        tags: ["measure", "analysis"],
      },
      {
        name: "Measure",
        description: "Assigning size to sets.",
        statement: "$\\mu:\\Sigma\\to[0,\\infty]$ with $\\mu(\\varnothing)=0$ and countable additivity on disjoint sets.",
        keyResults: "the Carathéodory extension theorem.",
        prereqs: ["Sigma-algebra"],
        tags: ["measure"],
      },
      {
        name: "Lebesgue measure",
        description: "Length, area, and volume on $\\mathbb{R}^n$.",
        statement: "the complete, translation-invariant measure giving $[a,b]$ length $b-a$.",
        keyResults: "non-measurable sets exist (with AC; Vitali).",
        prereqs: ["Measure", "Sigma-algebra"],
        tags: ["measure"],
      },
      {
        name: "Measurable function",
        description: "Functions compatible with measurement.",
        statement: "$f:X\\to\\mathbb{R}$ is measurable iff $f^{-1}(B)\\in\\Sigma$ for every Borel set $B$.",
        keyResults: "pointwise limits of measurable functions are measurable.",
        prereqs: ["Sigma-algebra", "Measure"],
        tags: ["measure"],
      },
      {
        name: "Lebesgue integral",
        description: "Integration against a measure.",
        statement: "$\\int_X f\\,d\\mu$, defined first for simple functions then by monotone limits for $f\\ge 0$.",
        keyResults: "monotone and dominated convergence theorems; Fatou's lemma.",
        prereqs: ["Measure", "Measurable function"],
        tags: ["measure", "analysis"],
      },
      {
        name: "Lp spaces",
        description: "Spaces of $p$-integrable functions.",
        statement: "$\\|f\\|_p=\\left(\\int |f|^p\\,d\\mu\\right)^{1/p}$; $L^p$ is where this is finite (modulo null sets).",
        keyResults: "Hölder and Minkowski inequalities; $L^p$ is complete (Riesz–Fischer).",
        prereqs: ["Lebesgue integral", "Normed vector space"],
        tags: ["measure", "analysis"],
      },
      {
        name: "Normed vector space",
        description: "A vector space with a length.",
        statement: "a norm $\\|\\cdot\\|$ with positivity, homogeneity, and the triangle inequality.",
        keyResults: "induces a metric; all norms on a finite-dimensional space are equivalent.",
        prereqs: ["Vector space", "Metric space"],
        tags: ["analysis"],
      },
      {
        name: "Banach space",
        description: "A complete normed space.",
        statement: "a normed space in which every Cauchy sequence converges.",
        keyResults: "open mapping, closed graph, and uniform boundedness theorems.",
        prereqs: ["Normed vector space", "Sequences & convergence"],
        tags: ["analysis"],
      },
      {
        name: "Hilbert space",
        description: "A complete inner-product space.",
        statement: "an inner product space complete in the induced norm; e.g. $L^2$, $\\ell^2$.",
        keyResults: "orthonormal bases; the projection theorem; Riesz representation.",
        prereqs: ["Inner product space", "Banach space"],
        tags: ["analysis"],
      },
      {
        name: "Bounded linear operator",
        description: "Continuous linear maps between normed spaces.",
        statement: "a linear $T$ with $\\|T\\|=\\sup_{\\|x\\|\\le 1}\\|Tx\\|<\\infty$.",
        keyResults: "boundedness equals continuity; the operator norm makes $B(X,Y)$ normed.",
        prereqs: ["Normed vector space", "Linear map"],
        tags: ["analysis"],
      },
      {
        name: "Hahn–Banach theorem",
        description: "Extending functionals without growing the norm.",
        statement: "a bounded linear functional on a subspace extends to the whole space with the same norm.",
        keyResults: "rich dual spaces; separation of convex sets.",
        prereqs: ["Normed vector space", "Bounded linear operator"],
        tags: ["analysis", "theorem"],
      },
      {
        name: "Dual space & Riesz representation",
        description: "Functionals and how to represent them.",
        statement: "the dual $X^{*}$ is the space of bounded functionals; in a Hilbert space every functional is $x\\mapsto\\langle x,y\\rangle$.",
        keyResults: "the Riesz representation theorem; reflexivity.",
        prereqs: ["Bounded linear operator", "Hilbert space"],
        tags: ["analysis", "theorem"],
      },
      {
        name: "Spectral theory of operators",
        description: "Eigenvalue theory in infinite dimensions.",
        statement: "the spectrum $\\sigma(T)=\\{\\lambda:\\ T-\\lambda I\\text{ not invertible}\\}$.",
        keyResults: "the spectral theorem for self-adjoint and compact operators.",
        prereqs: ["Bounded linear operator", "Hilbert space", "Spectral theorem"],
        tags: ["analysis"],
      },
      {
        name: "Distributions (generalized functions)",
        description: "Objects like the Dirac delta.",
        statement: "continuous linear functionals on test functions $C_c^\\infty$; e.g. $\\langle\\delta,\\varphi\\rangle=\\varphi(0)$.",
        keyResults: "weak / distributional derivatives; Sobolev spaces; PDE theory.",
        prereqs: ["Normed vector space", "Lebesgue integral"],
        tags: ["analysis"],
      },
    ],
  },
  // ── Family 8 ──────────────────────────────────────────────────────────────
  {
    slug: "topology",
    number: 8,
    name: "Topology",
    blurb: "Open sets, compactness, connectedness, manifolds, and the algebraic invariants of shape.",
    section: "B",
    color: "cyan",
    entries: [
      {
        name: "Topological space",
        description: "Open-set structure abstracting nearness.",
        statement: "a set $X$ with a family $\\tau$ of \"open\" sets closed under arbitrary unions and finite intersections, containing $\\varnothing,X$.",
        keyResults: "generalizes metric spaces.",
        prereqs: ["sets"],
        tags: ["topology"],
      },
      {
        name: "Open & closed sets",
        description: "The basic vocabulary.",
        statement: "opens are members of $\\tau$; closed sets are their complements; closure, interior, and boundary derive from them.",
        keyResults: "a set is closed iff it contains its limit points.",
        prereqs: ["Topological space"],
        tags: ["topology"],
      },
      {
        name: "Basis for a topology",
        description: "Generating opens from building blocks.",
        statement: "a collection whose unions give every open set.",
        keyResults: "metric balls form a basis; subbasis generation.",
        prereqs: ["Topological space"],
        tags: ["topology"],
      },
      {
        name: "Continuity (topological)",
        description: "Maps that pull back opens to opens.",
        statement: "$f$ is continuous iff $f^{-1}(U)$ is open for every open $U$.",
        keyResults: "unifies the $\\varepsilon$-$\\delta$ notion; composition preserves continuity.",
        prereqs: ["Topological space", "Open & closed sets"],
        tags: ["topology"],
      },
      {
        name: "Homeomorphism",
        description: "Topological equivalence.",
        statement: "a continuous bijection with continuous inverse.",
        keyResults: "homeomorphic spaces share all topological properties (\"coffee cup = donut\").",
        prereqs: ["Continuity (topological)"],
        tags: ["topology"],
      },
      {
        name: "Compactness",
        description: "Finiteness via covers.",
        statement: "every open cover has a finite subcover.",
        keyResults: "Heine–Borel (compact = closed and bounded in $\\mathbb{R}^n$); continuous images of compacts are compact.",
        prereqs: ["Topological space", "Open & closed sets"],
        tags: ["topology"],
      },
      {
        name: "Connectedness",
        description: "Being in one piece.",
        statement: "a space not partitionable into two disjoint nonempty open sets.",
        keyResults: "the intermediate value theorem; path-connectedness.",
        prereqs: ["Topological space", "Open & closed sets"],
        tags: ["topology"],
      },
      {
        name: "Hausdorff & separation axioms",
        description: "Telling points apart.",
        statement: "Hausdorff ($T_2$): distinct points have disjoint neighborhoods.",
        keyResults: "limits are unique; many constructions assume Hausdorff.",
        prereqs: ["Topological space"],
        tags: ["topology"],
      },
      {
        name: "Metric space",
        description: "Distance-based topology.",
        statement: "a set with $d(x,y)$ satisfying positivity, symmetry, and the triangle inequality.",
        keyResults: "induces a topology via open balls; completeness and Cauchy sequences.",
        prereqs: ["sets", "real numbers"],
        tags: ["topology", "analysis"],
      },
      {
        name: "Homotopy",
        description: "Continuous deformation of maps.",
        statement: "$f\\simeq g$ if a continuous $H:X\\times[0,1]\\to Y$ interpolates them.",
        keyResults: "homotopy equivalence; deformation retracts.",
        prereqs: ["Continuity (topological)"],
        tags: ["topology"],
      },
      {
        name: "Fundamental group",
        description: "Loops up to deformation.",
        statement: "$\\pi_1(X,x_0)$, homotopy classes of loops at $x_0$ under concatenation.",
        keyResults: "$\\pi_1(S^1)\\cong\\mathbb{Z}$; a topological invariant.",
        prereqs: ["Homotopy", "Group"],
        tags: ["topology", "algebraic"],
      },
      {
        name: "Covering space",
        description: "Spaces that \"unwrap\" another.",
        statement: "a map $p:\\tilde X\\to X$ that is locally a homeomorphism onto sheets.",
        keyResults: "a Galois-like correspondence with subgroups of $\\pi_1$.",
        prereqs: ["Fundamental group", "Continuity (topological)"],
        tags: ["topology", "algebraic"],
      },
      {
        name: "Homology",
        description: "Counting holes algebraically.",
        statement: "groups $H_n(X)$ from chain complexes detecting $n$-dimensional holes.",
        keyResults: "homotopy invariance; the Euler characteristic $\\chi=\\sum(-1)^n \\mathrm{rank}\\,H_n$.",
        prereqs: ["Group", "Topological space"],
        tags: ["topology", "algebraic"],
      },
      {
        name: "Manifold",
        description: "Locally Euclidean space.",
        statement: "a Hausdorff space locally homeomorphic to $\\mathbb{R}^n$.",
        keyResults: "smooth structures; classification of surfaces.",
        prereqs: ["Topological space", "Homeomorphism", "Hausdorff & separation axioms"],
        tags: ["topology", "geometry"],
      },
      {
        name: "Knot theory",
        description: "Embeddings of circles in space.",
        statement: "studies embeddings $S^1\\hookrightarrow \\mathbb{R}^3$ up to ambient isotopy.",
        keyResults: "knot invariants (Jones polynomial, knot group).",
        prereqs: ["Manifold", "Fundamental group"],
        tags: ["topology"],
      },
    ],
  },
  // ── Family 9 ──────────────────────────────────────────────────────────────
  {
    slug: "geometry",
    number: 9,
    name: "Geometry",
    blurb: "Euclidean, projective, differential, and algebraic geometry — the shapes of space.",
    section: "B",
    color: "blue",
    entries: [
      {
        name: "Euclidean geometry",
        description: "Geometry from Euclid's axioms.",
        statement: "points, lines, and planes governed by five postulates (including the parallel postulate).",
        keyResults: "congruence and similarity; the Pythagorean theorem.",
        prereqs: [],
        tags: ["geometry"],
      },
      {
        name: "Congruence & similarity",
        description: "Same-shape / size relations.",
        statement: "figures are congruent under isometries, similar under scaling plus isometry.",
        keyResults: "triangle criteria (SSS, SAS, ASA); ratios preserved under similarity.",
        prereqs: ["Euclidean geometry"],
        tags: ["geometry"],
      },
      {
        name: "Trigonometry",
        description: "Relations in triangles via ratios.",
        statement: "$\\sin,\\cos,\\tan$ relate angles to side ratios; $\\sin^2\\theta+\\cos^2\\theta=1$.",
        keyResults: "the laws of sines and cosines; angle-addition formulas.",
        prereqs: ["Euclidean geometry"],
        tags: ["geometry"],
      },
      {
        name: "Analytic (coordinate) geometry",
        description: "Geometry via coordinates.",
        statement: "points as tuples in $\\mathbb{R}^n$; lines and curves as equations, e.g. the circle $x^2+y^2=r^2$.",
        keyResults: "the distance formula; conic sections.",
        prereqs: ["Euclidean geometry", "real numbers"],
        tags: ["geometry"],
      },
      {
        name: "Non-Euclidean geometry",
        description: "Dropping the parallel postulate.",
        statement: "geometries where through a point there are zero (elliptic) or many (hyperbolic) parallels.",
        keyResults: "consistency models; angle sums differ from $180^\\circ$.",
        prereqs: ["Euclidean geometry"],
        tags: ["geometry"],
      },
      {
        name: "Hyperbolic geometry",
        description: "Constant negative curvature.",
        statement: "a geometry where triangle angle sums are $<\\pi$ and many lines through a point miss a given line.",
        keyResults: "the Poincaré disk / half-plane models; links to special relativity.",
        prereqs: ["Non-Euclidean geometry"],
        tags: ["geometry"],
      },
      {
        name: "Projective geometry",
        description: "Geometry of incidence and perspective.",
        statement: "adds points at infinity, so any two lines meet.",
        keyResults: "duality; Desargues' and Pappus' theorems; the cross-ratio.",
        prereqs: ["Euclidean geometry", "Linear map"],
        tags: ["geometry"],
      },
      {
        name: "Differential geometry",
        description: "Calculus on curves and surfaces.",
        statement: "studies smooth manifolds and structures such as a curve's curvature and torsion.",
        keyResults: "the Frenet–Serret formulas; first and second fundamental forms.",
        prereqs: ["Manifold", "Derivative", "Linear map"],
        tags: ["geometry", "analysis"],
      },
      {
        name: "Riemannian geometry",
        description: "Manifolds with a metric.",
        statement: "a smooth manifold with a positive-definite metric tensor $g$ giving lengths and angles.",
        keyResults: "geodesics; curvature tensors; Gauss–Bonnet.",
        prereqs: ["Differential geometry", "Manifold"],
        tags: ["geometry"],
      },
      {
        name: "Curvature",
        description: "How space bends.",
        statement: "Gaussian curvature $K=\\kappa_1\\kappa_2$ from principal curvatures; sectional, Ricci, and scalar in higher dimensions.",
        keyResults: "Gauss's Theorema Egregium ($K$ is intrinsic).",
        prereqs: ["Differential geometry"],
        tags: ["geometry"],
      },
      {
        name: "Geodesics",
        description: "Locally shortest paths.",
        statement: "curves with zero tangential acceleration; solutions of the geodesic equation.",
        keyResults: "great circles on a sphere; the paths of general relativity.",
        prereqs: ["Riemannian geometry"],
        tags: ["geometry"],
      },
      {
        name: "Algebraic geometry",
        description: "Geometry of polynomial solution sets.",
        statement: "studies varieties $V(f_1,\\dots,f_k)$ — zero loci of polynomials — and their coordinate rings.",
        keyResults: "Hilbert's Nullstellensatz; schemes (Grothendieck).",
        prereqs: ["Commutative algebra", "Polynomial ring", "Field"],
        tags: ["geometry", "algebra"],
      },
      {
        name: "Convex geometry",
        description: "Geometry of convex sets.",
        statement: "sets containing the segment between any two of their points; supporting hyperplanes.",
        keyResults: "the separating hyperplane theorem; Helly's and Carathéodory's theorems.",
        prereqs: ["Euclidean geometry", "Linear map"],
        tags: ["geometry"],
      },
      {
        name: "Discrete & computational geometry",
        description: "Finite configurations and geometric algorithms.",
        statement: "studies polygons, polytopes, arrangements, and algorithms (e.g. convex hulls).",
        keyResults: "Euler's polyhedron formula $V-E+F=2$; Voronoi / Delaunay diagrams.",
        prereqs: ["Euclidean geometry", "Graph"],
        tags: ["geometry", "computational"],
      },
    ],
  },
  // ── Family 10 ─────────────────────────────────────────────────────────────
  {
    slug: "combinatorics-graph-theory",
    number: 10,
    name: "Combinatorics & Graph Theory",
    blurb: "Counting, recurrences, graphs, networks, and the structure forced by sheer size.",
    section: "B",
    color: "sky",
    entries: [
      {
        name: "Permutations & combinations",
        description: "Counting arrangements and selections.",
        statement: "$P(n,k)=\\dfrac{n!}{(n-k)!}$ and $\\binom{n}{k}=\\dfrac{n!}{k!(n-k)!}$.",
        keyResults: "product and sum rules; bijective counting.",
        prereqs: ["natural numbers", "sets"],
        tags: ["combinatorics"],
      },
      {
        name: "Binomial theorem & coefficients",
        description: "Expanding powers of sums.",
        statement: "$(x+y)^n=\\sum_{k=0}^n \\binom{n}{k}x^{k}y^{n-k}$.",
        keyResults: "Pascal's identity $\\binom{n}{k}=\\binom{n-1}{k-1}+\\binom{n-1}{k}$.",
        prereqs: ["Permutations & combinations"],
        tags: ["combinatorics"],
      },
      {
        name: "Pigeonhole principle",
        description: "More items than boxes forces sharing.",
        statement: "placing $n$ items in $m<n$ boxes puts $\\ge\\lceil n/m\\rceil$ in some box.",
        keyResults: "existence proofs; Erdős–Szekeres.",
        prereqs: ["sets", "natural numbers"],
        tags: ["combinatorics"],
      },
      {
        name: "Inclusion–exclusion",
        description: "Counting unions correctly.",
        statement: "$|A_1\\cup\\cdots\\cup A_n|=\\sum|A_i|-\\sum|A_i\\cap A_j|+\\cdots$.",
        keyResults: "derangements; Euler's totient formula.",
        prereqs: ["sets", "Permutations & combinations"],
        tags: ["combinatorics"],
      },
      {
        name: "Generating functions",
        description: "Encoding sequences as power series.",
        statement: "$G(x)=\\sum_{n\\ge 0} a_n x^n$ turns recurrences into algebra.",
        keyResults: "solving recurrences; Catalan and Fibonacci closed forms.",
        prereqs: ["Series & convergence tests", "Recurrence relations"],
        tags: ["combinatorics"],
      },
      {
        name: "Recurrence relations",
        description: "Defining sequences by earlier terms.",
        statement: "e.g. $a_n=a_{n-1}+a_{n-2}$ (Fibonacci).",
        keyResults: "characteristic-equation solutions for linear recurrences.",
        prereqs: ["Sequences & convergence"],
        tags: ["combinatorics"],
      },
      {
        name: "Graph",
        description: "Vertices joined by edges.",
        statement: "$G=(V,E)$ with $E\\subseteq\\binom{V}{2}$ (or ordered pairs if directed).",
        keyResults: "the handshake lemma $\\sum_v\\deg(v)=2|E|$.",
        prereqs: ["sets"],
        tags: ["graph theory"],
      },
      {
        name: "Tree",
        description: "A connected acyclic graph.",
        statement: "a connected graph with no cycles; $n$ vertices have $n-1$ edges.",
        keyResults: "unique paths; spanning trees; Cayley's formula $n^{n-2}$.",
        prereqs: ["Graph"],
        tags: ["graph theory"],
      },
      {
        name: "Planar graph",
        description: "Graphs drawable without crossings.",
        statement: "embeddable in the plane with no edge crossings.",
        keyResults: "Euler's formula $V-E+F=2$; Kuratowski's theorem.",
        prereqs: ["Graph"],
        tags: ["graph theory"],
      },
      {
        name: "Eulerian & Hamiltonian paths",
        description: "Traversing edges vs vertices.",
        statement: "an Eulerian circuit uses every edge once; a Hamiltonian cycle visits every vertex once.",
        keyResults: "Euler's bridge criterion (even degrees); Hamiltonicity is NP-complete.",
        prereqs: ["Graph"],
        tags: ["graph theory"],
      },
      {
        name: "Graph coloring",
        description: "Coloring vertices to avoid conflicts.",
        statement: "assign colors so adjacent vertices differ; the chromatic number $\\chi(G)$ is the minimum needed.",
        keyResults: "the four-color theorem for planar graphs; Brooks' theorem.",
        prereqs: ["Graph", "Planar graph"],
        tags: ["graph theory"],
      },
      {
        name: "Matching",
        description: "Pairing up vertices via edges.",
        statement: "a set of edges with no shared vertices; perfect if it covers all vertices.",
        keyResults: "Hall's marriage theorem; König's theorem.",
        prereqs: ["Graph"],
        tags: ["graph theory"],
      },
      {
        name: "Ramsey theory",
        description: "Order is unavoidable in large structures.",
        statement: "any 2-coloring of a large enough complete graph contains a monochromatic clique; $R(3,3)=6$.",
        keyResults: "Ramsey's theorem; Van der Waerden's theorem.",
        prereqs: ["Graph", "Pigeonhole principle"],
        tags: ["combinatorics"],
      },
      {
        name: "Extremal combinatorics",
        description: "How large or dense before structure is forced.",
        statement: "bounds the size of structures that avoid a given configuration.",
        keyResults: "Turán's theorem; Erdős–Ko–Rado.",
        prereqs: ["Graph", "Permutations & combinations"],
        tags: ["combinatorics"],
      },
      {
        name: "Design theory & matroids",
        description: "Balanced configurations and abstract independence.",
        statement: "block designs balance incidences; matroids abstract linear and graphic independence.",
        keyResults: "Steiner systems; greedy-algorithm optimality on matroids.",
        prereqs: ["sets", "Linear map", "Graph"],
        tags: ["combinatorics"],
      },
    ],
  },
  // ── Family 11 ─────────────────────────────────────────────────────────────
  {
    slug: "differential-equations-dynamical-systems",
    number: 11,
    name: "Differential Equations & Dynamical Systems",
    blurb: "ODEs, PDEs, flows, bifurcations, chaos — the mathematics of evolution in time.",
    section: "B",
    color: "cyan",
    entries: [
      {
        name: "Ordinary differential equation (ODE)",
        description: "Equations relating a function and its derivatives.",
        statement: "$F(x,y,y',\\dots,y^{(n)})=0$ for unknown $y(x)$.",
        keyResults: "order and linearity classification; general vs particular solutions.",
        prereqs: ["Derivative", "functions"],
        tags: ["differential equations"],
      },
      {
        name: "First-order ODEs",
        description: "Equations with only $y'$.",
        statement: "$y'=f(x,y)$; separable, exact, and integrating-factor methods.",
        keyResults: "explicit solutions in separable and linear cases.",
        prereqs: ["Ordinary differential equation (ODE)", "Riemann integral"],
        tags: ["differential equations"],
      },
      {
        name: "Linear ODEs",
        description: "Linear in $y$ and its derivatives.",
        statement: "$y^{(n)}+a_{n-1}(x)y^{(n-1)}+\\cdots+a_0(x)y=g(x)$.",
        keyResults: "superposition; characteristic-root solutions (constant coefficients).",
        prereqs: ["Ordinary differential equation (ODE)", "Linear map"],
        tags: ["differential equations"],
      },
      {
        name: "Existence & uniqueness (Picard–Lindelöf)",
        description: "When solutions exist and are unique.",
        statement: "if $f$ is Lipschitz in $y$, the IVP $y'=f(x,y),\\ y(x_0)=y_0$ has a unique local solution.",
        keyResults: "the foundation of ODE theory; Peano existence under mere continuity.",
        prereqs: ["First-order ODEs", "Continuity"],
        tags: ["differential equations", "theorem"],
      },
      {
        name: "Partial differential equation (PDE)",
        description: "Equations in functions of several variables.",
        statement: "relations among partial derivatives, e.g. $u_t=u_{xx}$.",
        keyResults: "classification into elliptic, parabolic, hyperbolic.",
        prereqs: ["Ordinary differential equation (ODE)", "Derivative"],
        tags: ["differential equations"],
      },
      {
        name: "Heat equation",
        description: "Diffusion over time.",
        statement: "$u_t=\\alpha\\,\\Delta u$.",
        keyResults: "smoothing; the Gaussian fundamental solution; Fourier-series solutions.",
        prereqs: ["Partial differential equation (PDE)", "Fourier series"],
        tags: ["differential equations", "physics"],
      },
      {
        name: "Wave equation",
        description: "Propagation of waves.",
        statement: "$u_{tt}=c^2\\,\\Delta u$.",
        keyResults: "d'Alembert's 1D solution; finite propagation speed.",
        prereqs: ["Partial differential equation (PDE)"],
        tags: ["differential equations", "physics"],
      },
      {
        name: "Laplace's equation",
        description: "Steady-state and harmonic fields.",
        statement: "$\\Delta u=0$; solutions are harmonic functions.",
        keyResults: "the mean-value property; the maximum principle.",
        prereqs: ["Partial differential equation (PDE)"],
        tags: ["differential equations", "physics"],
      },
      {
        name: "Dynamical system",
        description: "Rules for the time evolution of a state.",
        statement: "a state space with an evolution map or flow $\\phi_t$.",
        keyResults: "fixed points, periodic orbits, invariant sets.",
        prereqs: ["Ordinary differential equation (ODE)"],
        tags: ["dynamical systems"],
      },
      {
        name: "Stability & Lyapunov methods",
        description: "Whether states return to equilibrium.",
        statement: "an equilibrium is stable if nearby trajectories stay near; a Lyapunov function $V$ with $\\dot V\\le 0$ certifies it.",
        keyResults: "linearization via the Jacobian's eigenvalues; Lyapunov's theorems.",
        prereqs: ["Dynamical system", "Eigenvalues & eigenvectors"],
        tags: ["dynamical systems"],
      },
      {
        name: "Phase portrait",
        description: "Geometric picture of trajectories.",
        statement: "the plot of state trajectories in phase space.",
        keyResults: "classification of planar equilibria (node, saddle, focus, center).",
        prereqs: ["Dynamical system", "Linear ODEs"],
        tags: ["dynamical systems"],
      },
      {
        name: "Bifurcation",
        description: "Qualitative change as a parameter varies.",
        statement: "a parameter value where the number or stability of equilibria changes (saddle-node, Hopf, pitchfork).",
        keyResults: "normal forms; routes to complex behavior.",
        prereqs: ["Dynamical system", "Stability & Lyapunov methods"],
        tags: ["dynamical systems"],
      },
      {
        name: "Chaos",
        description: "Deterministic yet unpredictable dynamics.",
        statement: "bounded systems with sensitive dependence on initial conditions (a positive Lyapunov exponent).",
        keyResults: "the Lorenz system; period-doubling (Feigenbaum).",
        prereqs: ["Dynamical system", "Bifurcation"],
        tags: ["dynamical systems"],
      },
      {
        name: "Attractor",
        description: "The set dynamics settle onto.",
        statement: "an invariant set attracting nearby trajectories — a point, cycle, or strange (fractal) attractor.",
        keyResults: "the Lorenz attractor; basins of attraction.",
        prereqs: ["Dynamical system", "Chaos"],
        tags: ["dynamical systems"],
      },
    ],
  },
  // ── Family 12 ─────────────────────────────────────────────────────────────
  {
    slug: "probability-stochastic",
    number: 12,
    name: "Probability & Stochastic Processes",
    blurb: "Probability spaces, limit theorems, Markov chains, martingales, and stochastic calculus.",
    section: "C",
    color: "teal",
    entries: [
      {
        name: "Probability space",
        description: "The formal model of chance.",
        statement: "$(\\Omega,\\mathcal{F},P)$ with $P(\\Omega)=1$ and countable additivity.",
        keyResults: "Kolmogorov's axioms underpin all of probability.",
        prereqs: ["Measure", "Sigma-algebra"],
        tags: ["probability"],
        xref: ["statistics"],
      },
      {
        name: "Random variable",
        description: "A measurable numeric outcome.",
        statement: "a measurable map $X:\\Omega\\to\\mathbb{R}$ with distribution $F_X(x)=P(X\\le x)$.",
        keyResults: "discrete vs continuous; the pushforward law.",
        prereqs: ["Probability space", "Measurable function"],
        tags: ["probability"],
        xref: ["statistics"],
      },
      {
        name: "Expectation",
        description: "The average value.",
        statement: "$E[X]=\\int_\\Omega X\\,dP$ (discrete: $\\sum_i x_i p_i$).",
        keyResults: "linearity; the law of the unconscious statistician.",
        prereqs: ["Random variable", "Lebesgue integral"],
        tags: ["probability"],
        xref: ["statistics"],
      },
      {
        name: "Variance",
        description: "Spread about the mean.",
        statement: "$\\mathrm{Var}(X)=E[(X-E[X])^2]=E[X^2]-E[X]^2$.",
        keyResults: "additivity for independent variables; Chebyshev's inequality.",
        prereqs: ["Expectation"],
        tags: ["probability"],
        xref: ["statistics"],
      },
      {
        name: "Conditional probability",
        description: "Probability given information.",
        statement: "$P(A\\mid B)=\\dfrac{P(A\\cap B)}{P(B)}$ for $P(B)>0$.",
        keyResults: "the multiplication rule; the law of total probability.",
        prereqs: ["Probability space"],
        tags: ["probability"],
        xref: ["statistics"],
      },
      {
        name: "Bayes' theorem",
        description: "Updating beliefs with evidence.",
        statement: "$P(A\\mid B)=\\dfrac{P(B\\mid A)\\,P(A)}{P(B)}$.",
        keyResults: "posterior $\\propto$ likelihood $\\times$ prior; the basis of Bayesian inference.",
        prereqs: ["Conditional probability"],
        tags: ["probability"],
        xref: ["statistics"],
      },
      {
        name: "Independence",
        description: "When events or variables don't inform each other.",
        statement: "$P(A\\cap B)=P(A)P(B)$; for variables the joint law factorizes.",
        keyResults: "simplifies expectations and variances.",
        prereqs: ["Conditional probability"],
        tags: ["probability"],
        xref: ["statistics"],
      },
      {
        name: "Common distributions",
        description: "The standard probabilistic models.",
        statement: "Bernoulli / binomial, Poisson, uniform, exponential, and normal $f(x)=\\dfrac{1}{\\sigma\\sqrt{2\\pi}}e^{-(x-\\mu)^2/2\\sigma^2}$.",
        keyResults: "moment and limiting relationships among them.",
        prereqs: ["Random variable", "Expectation"],
        tags: ["probability"],
        xref: ["statistics"],
      },
      {
        name: "Law of large numbers",
        description: "Sample means converge to the mean.",
        statement: "$\\bar X_n\\to \\mu$ (in probability / almost surely) for i.i.d. integrable $X_i$.",
        keyResults: "justifies the frequentist interpretation of probability.",
        prereqs: ["Expectation", "Independence"],
        tags: ["probability"],
        xref: ["statistics"],
      },
      {
        name: "Central limit theorem",
        description: "Normalized sums tend to normal.",
        statement: "$\\sqrt{n}(\\bar X_n-\\mu)/\\sigma \\xrightarrow{d} N(0,1)$ for finite-variance i.i.d. variables.",
        keyResults: "explains the ubiquity of the normal distribution.",
        prereqs: ["Variance", "Independence", "Common distributions"],
        tags: ["probability"],
        xref: ["statistics"],
      },
      {
        name: "Markov chain",
        description: "Memoryless state transitions.",
        statement: "$P(X_{n+1}\\mid X_n,\\dots,X_0)=P(X_{n+1}\\mid X_n)$.",
        keyResults: "stationary distributions; the ergodic theorem.",
        prereqs: ["Conditional probability", "Random variable"],
        tags: ["probability", "stochastic"],
      },
      {
        name: "Martingale",
        description: "A \"fair game\" process.",
        statement: "$E[X_{n+1}\\mid \\mathcal{F}_n]=X_n$.",
        keyResults: "the optional stopping theorem; martingale convergence.",
        prereqs: ["Expectation", "Conditional probability"],
        tags: ["probability", "stochastic"],
      },
      {
        name: "Brownian motion",
        description: "Continuous random motion.",
        statement: "a process with independent Gaussian increments $W_t-W_s\\sim N(0,t-s)$ and continuous paths.",
        keyResults: "nowhere differentiable; the basis of stochastic calculus.",
        prereqs: ["Common distributions", "Martingale"],
        tags: ["probability", "stochastic"],
      },
      {
        name: "Stochastic calculus (Itô)",
        description: "Calculus for random paths.",
        statement: "Itô's lemma $df=\\left(f_t+\\mu f_x+\\tfrac12\\sigma^2 f_{xx}\\right)dt+\\sigma f_x\\,dW$.",
        keyResults: "stochastic differential equations; Black–Scholes.",
        prereqs: ["Brownian motion", "Derivative"],
        tags: ["probability", "stochastic"],
        xref: ["finance"],
      },
    ],
  },
];
