import type { Family } from "./types";

export const FAMILIES_1_7: Family[] = [
  // ── Family 1 — Cell Biology ───────────────────────────────────────────────
  {
    slug: "cell-biology",
    number: 1,
    name: "Cell Biology",
    blurb: "The cell as the fundamental unit of life — structure, organelles, division, and signaling.",
    section: "A",
    color: "teal",
    entries: [
      {
        name: "Cell theory",
        description: "All living things are composed of cells; the cell is the basic unit of life; all cells arise from pre-existing cells.",
        keyFact: "Schleiden, Schwann, and Virchow formalized cell theory 1838–1855. The third tenet (omnis cellula e cellula) refuted spontaneous generation.",
        evolvedFrom: [],
        tags: ["foundations", "history"],
      },
      {
        name: "Prokaryotic cell",
        description: "Simple cells lacking a membrane-bound nucleus; DNA is in a nucleoid region; include bacteria and archaea.",
        keyFact: "Typically 1–10 µm diameter; no membrane-bound organelles; ribosomes are 70S; cell wall common; reproduce by binary fission.",
        evolvedFrom: ["Cell theory"],
        tags: ["cell structure", "bacteria", "archaea"],
      },
      {
        name: "Eukaryotic cell",
        description: "Complex cells with a membrane-bound nucleus and membrane-bound organelles; include protists, fungi, plants, and animals.",
        keyFact: "Typically 10–100 µm; 80S ribosomes; cytoskeleton; endomembrane system; mitochondria present; plastids in plants and algae.",
        evolvedFrom: ["Prokaryotic cell", "Endosymbiotic theory"],
        tags: ["cell structure", "organelles"],
      },
      {
        name: "Cell membrane",
        description: "The phospholipid bilayer boundary of every cell, controlling what enters and exits.",
        keyFact: "Fluid mosaic model (Singer & Nicolson, 1972): lipids and proteins diffuse laterally; selectively permeable; channels and carriers mediate transport.",
        evolvedFrom: ["Cell theory"],
        tags: ["membrane", "transport", "lipids"],
        xref: ["chemistry"],
      },
      {
        name: "Mitochondria",
        description: "Double-membraned organelles that generate the cell's ATP via oxidative phosphorylation.",
        keyFact: "Have their own circular genome and 70S ribosomes — evidence of endosymbiotic bacterial origin. Inner membrane folded into cristae; ~100 per typical animal cell.",
        evolvedFrom: ["Eukaryotic cell", "Endosymbiotic theory"],
        tags: ["organelle", "ATP", "endosymbiosis"],
        xref: ["chemistry"],
      },
      {
        name: "Nucleus",
        description: "Membrane-bound organelle containing the cell's chromosomal DNA and the site of transcription.",
        keyFact: "Enclosed by a double nuclear membrane with nuclear pores; nucleolus inside produces ribosomal RNA.",
        evolvedFrom: ["Eukaryotic cell"],
        tags: ["organelle", "DNA", "transcription"],
      },
      {
        name: "Endoplasmic reticulum",
        description: "Network of membranes for protein (rough ER) and lipid (smooth ER) synthesis and transport.",
        keyFact: "Rough ER is studded with ribosomes and produces secretory and membrane proteins; smooth ER synthesizes lipids and detoxifies drugs.",
        evolvedFrom: ["Eukaryotic cell"],
        tags: ["organelle", "protein synthesis"],
      },
      {
        name: "Golgi apparatus",
        description: "Stacked membranous cisternae that process, sort, and package proteins destined for secretion or other organelles.",
        keyFact: "Proteins arrive from rough ER, are glycosylated and sorted, then exit in vesicles toward the plasma membrane, lysosomes, or secretion.",
        evolvedFrom: ["Endoplasmic reticulum"],
        tags: ["organelle", "secretion"],
      },
      {
        name: "Cytoskeleton",
        description: "Network of protein filaments — microtubules, actin microfilaments, and intermediate filaments — giving cells shape and enabling movement.",
        keyFact: "Microtubules (tubulin) form the mitotic spindle; actin drives cell motility and division; intermediate filaments resist mechanical stress.",
        evolvedFrom: ["Eukaryotic cell"],
        tags: ["cell structure", "motility", "mitosis"],
      },
      {
        name: "Mitosis",
        description: "Cell division producing two genetically identical daughter cells; the mechanism of growth and tissue repair.",
        keyFact: "Phases: prophase, metaphase, anaphase, telophase; chromosomes duplicated in S phase condense and are segregated by the mitotic spindle.",
        example: "A skin cell divides to replace a shed cell, producing two diploid daughters with identical chromosomes.",
        evolvedFrom: ["Cell theory", "Cytoskeleton"],
        tags: ["cell division", "growth"],
      },
      {
        name: "Meiosis",
        description: "Two successive divisions producing four haploid gametes; generates genetic diversity through recombination.",
        keyFact: "Meiosis I separates homologs; meiosis II separates sister chromatids. Crossing over during prophase I shuffles alleles between homologs.",
        evolvedFrom: ["Mitosis"],
        tags: ["cell division", "reproduction", "recombination"],
      },
      {
        name: "Cell signaling",
        description: "Cells communicate via extracellular ligands binding cell-surface or intracellular receptors, triggering intracellular cascades.",
        keyFact: "Signal transduction: ligand → receptor activation → second messengers (cAMP, Ca2+, DAG/IP3) → kinase cascades → gene expression or metabolic changes.",
        evolvedFrom: ["Cell membrane"],
        tags: ["signaling", "receptors"],
      },
      {
        name: "Apoptosis",
        description: "Programmed cell death: an orderly, energy-dependent dismantling of a cell without inflammation.",
        keyFact: "Intrinsic pathway: mitochondrial release of cytochrome c activates caspases. Extrinsic pathway: death receptor ligation. Essential for development, immunity, and tumor suppression.",
        evolvedFrom: ["Cell signaling"],
        tags: ["cell death", "development", "cancer"],
      },
    ],
  },

  // ── Family 2 — Molecular Biology ──────────────────────────────────────────
  {
    slug: "molecular-biology",
    number: 2,
    name: "Molecular Biology",
    blurb: "The molecular machinery of heredity and gene expression — DNA, RNA, proteins, and how they are made.",
    section: "A",
    color: "emerald",
    entries: [
      {
        name: "DNA structure",
        description: "Deoxyribonucleic acid: an antiparallel double helix of nucleotides encoding genetic information.",
        keyFact: "Watson, Crick, Franklin, and Wilkins (1953): adenine pairs with thymine (2 H-bonds), guanine with cytosine (3 H-bonds); sugar-phosphate backbone on outside.",
        evolvedFrom: [],
        tags: ["DNA", "structure", "history"],
        xref: ["chemistry"],
      },
      {
        name: "RNA types",
        description: "RNA molecules have multiple roles: mRNA carries coding sequence; tRNA adapts codons to amino acids; rRNA catalyzes peptide-bond formation.",
        keyFact: "Additional small RNAs (miRNA, siRNA, lncRNA, snRNA) regulate gene expression, splicing, and genome defense. RNA can be both information carrier and catalyst (ribozyme).",
        evolvedFrom: ["DNA structure"],
        tags: ["RNA", "transcription", "regulation"],
      },
      {
        name: "Central dogma",
        description: "The flow of genetic information: DNA is transcribed to RNA, which is translated to protein. Information does not flow from protein back to nucleic acid.",
        keyFact: "Crick (1958, 1970). Exceptions: retroviruses use reverse transcriptase (RNA → DNA); prions transmit conformational information without nucleic acid.",
        evolvedFrom: ["DNA structure", "RNA types"],
        tags: ["dogma", "gene expression"],
      },
      {
        name: "Transcription",
        description: "The synthesis of an RNA copy from a DNA template by RNA polymerase.",
        keyFact: "Initiation at promoters (TATA box in eukaryotes); elongation 5'→3'; termination at terminators or poly-A signal. Pre-mRNA is capped, spliced, and polyadenylated in eukaryotes.",
        evolvedFrom: ["Central dogma", "DNA structure"],
        tags: ["gene expression", "RNA polymerase"],
      },
      {
        name: "Translation",
        description: "Ribosomes decode mRNA codons into a polypeptide chain using aminoacyl-tRNAs.",
        keyFact: "The genetic code: 64 codons for 20 amino acids + 3 stop codons; code is degenerate (multiple codons per amino acid) and nearly universal.",
        example: "The codon AUG (start/Met), UAA/UAG/UGA (stop). A 300-codon mRNA produces a 100-amino-acid protein.",
        evolvedFrom: ["Central dogma", "RNA types"],
        tags: ["protein synthesis", "ribosome", "genetic code"],
      },
      {
        name: "DNA replication",
        description: "Semi-conservative copying of DNA: each strand serves as a template for a new complementary strand.",
        keyFact: "DNA polymerase III (prokaryotes) / Pol delta/epsilon (eukaryotes) synthesizes 5'→3' only; leading strand continuous, lagging strand in Okazaki fragments; helicase unwinds, primase lays RNA primers.",
        evolvedFrom: ["DNA structure", "Central dogma"],
        tags: ["replication", "semi-conservative"],
      },
      {
        name: "Gene expression regulation",
        description: "Transcription factors, enhancers, silencers, chromatin state, and non-coding RNAs control when and where genes are expressed.",
        keyFact: "Regulation is multilayered: chromatin accessibility, promoter binding, RNA processing, translation efficiency, protein stability. lac operon (Jacob & Monod, 1961) was the first regulatory model.",
        evolvedFrom: ["Transcription", "Epigenetics"],
        tags: ["regulation", "transcription factors", "chromatin"],
      },
      {
        name: "Epigenetics",
        description: "Heritable changes in gene expression that do not involve changes to DNA sequence, mediated by DNA methylation and histone modifications.",
        keyFact: "DNA methylation (CpG sites) typically silences genes; histone acetylation activates; H3K27me3 represses. Patterns can persist through cell division and sometimes across generations.",
        evolvedFrom: ["Gene expression regulation"],
        tags: ["epigenetics", "methylation", "chromatin"],
      },
      {
        name: "CRISPR-Cas9",
        description: "Bacterial adaptive immune system repurposed as a precise gene-editing tool: Cas9 protein guided by a synthetic gRNA cuts double-stranded DNA at a targeted site.",
        keyFact: "Doudna, Charpentier, and Zhang developed CRISPR-Cas9 as a genome editor (2012–2013); Nobel 2020. Repair by NHEJ (mutagenic) or HDR (precise correction).",
        evolvedFrom: ["Bacteriophages", "Horizontal gene transfer"],
        tags: ["gene editing", "CRISPR", "biotechnology"],
      },
      {
        name: "Protein folding",
        description: "Amino acid sequences fold into specific three-dimensional structures that determine protein function.",
        keyFact: "Anfinsen (1972): the amino acid sequence encodes the folded structure (thermodynamic hypothesis). Misfolding underlies Alzheimer's, Parkinson's, and prion diseases. AlphaFold2 (2020) predicts structure from sequence.",
        evolvedFrom: ["Translation"],
        tags: ["protein structure", "folding", "disease"],
        xref: ["chemistry"],
      },
      {
        name: "Enzymes",
        description: "Biological catalysts — mostly proteins — that accelerate reactions by lowering activation energy.",
        keyFact: "Enzyme kinetics: Michaelis-Menten equation; Km is the substrate concentration at half-maximal velocity; kcat is the turnover number. Inhibitors are competitive, uncompetitive, or non-competitive.",
        evolvedFrom: ["Protein folding"],
        tags: ["catalysis", "kinetics"],
        xref: ["chemistry"],
      },
      {
        name: "Non-coding RNA",
        description: "RNA transcripts that do not encode protein; include microRNAs, lncRNAs, siRNAs, snRNAs — regulatory roles once called 'junk'.",
        keyFact: "miRNAs (~22 nt) bind mRNA to repress translation or promote degradation; siRNA drives RNA interference (RNAi); lncRNAs regulate chromatin and transcription. >70% of the human genome is transcribed.",
        evolvedFrom: ["RNA types", "Gene expression regulation"],
        tags: ["ncRNA", "miRNA", "RNAi"],
      },
      {
        name: "Transcription factors",
        description: "Sequence-specific DNA-binding proteins that activate or repress target gene transcription by binding enhancers or promoters.",
        keyFact: "Combinatorial control: different combinations of a limited set of TFs can produce diverse gene expression patterns. Master regulators (e.g., MyoD for muscle, Pax6 for eye) specify entire lineages.",
        evolvedFrom: ["Gene expression regulation"],
        tags: ["transcription factors", "regulation"],
      },
      {
        name: "Post-translational modification",
        description: "Covalent chemical modifications to proteins after translation alter their activity, localization, interactions, and stability.",
        keyFact: "Major modifications: phosphorylation (kinases/phosphatases), ubiquitination (proteasomal degradation), glycosylation, acetylation, methylation, sumoylation. PTMs vastly expand the functional proteome.",
        evolvedFrom: ["Translation", "Cell signaling"],
        tags: ["proteomics", "signaling", "phosphorylation"],
      },
    ],
  },

  // ── Family 3 — Genetics & Genomics ────────────────────────────────────────
  {
    slug: "genetics-genomics",
    number: 3,
    name: "Genetics & Genomics",
    blurb: "Heredity and variation from single genes to whole genomes — Mendel through the sequencing era.",
    section: "A",
    color: "green",
    entries: [
      {
        name: "Mendel's laws",
        description: "Law of segregation: two alleles separate during gamete formation. Law of independent assortment: alleles at different loci segregate independently.",
        keyFact: "Derived from pea experiments 1856–1863, published 1866, ignored until 1900 (de Vries, Correns, Tschermak). Independent assortment applies only to unlinked loci.",
        evolvedFrom: [],
        tags: ["heredity", "Mendel", "history"],
      },
      {
        name: "Alleles",
        description: "Alternative forms of a gene at a given chromosomal locus; diploid organisms carry two alleles per autosomal locus.",
        keyFact: "Alleles arise by mutation; population genetics tracks allele frequencies. Heterozygotes carry two different alleles; homozygotes carry two identical ones.",
        evolvedFrom: ["Mendel's laws"],
        tags: ["alleles", "loci", "population genetics"],
      },
      {
        name: "Dominant and recessive inheritance",
        description: "Dominant alleles mask recessive alleles in heterozygotes; recessives are expressed only in homozygotes.",
        keyFact: "Dominance is a phenotypic relationship, not an intrinsic property of the allele. Incomplete dominance and codominance (e.g., ABO blood groups) are intermediate cases.",
        evolvedFrom: ["Alleles"],
        tags: ["dominance", "recessiveness", "phenotype"],
      },
      {
        name: "Linkage and recombination",
        description: "Genes on the same chromosome tend to be inherited together (linked); crossing over during meiosis recombines linked alleles.",
        keyFact: "Morgan (1911): genetic linkage in Drosophila. Recombination frequency estimates map distance (cM). Loci >50 cM apart behave as unlinked (independent assortment).",
        evolvedFrom: ["Mendel's laws", "Meiosis"],
        tags: ["linkage", "recombination", "mapping"],
      },
      {
        name: "Mutation",
        description: "A heritable change in DNA sequence, ranging from a single base substitution to large chromosomal rearrangements.",
        keyFact: "Point mutations: synonymous (silent), missense (amino acid change), nonsense (stop codon). Indels cause frameshifts. Somatic mutations drive cancer; germline mutations are inherited.",
        evolvedFrom: ["DNA structure", "DNA replication"],
        tags: ["mutation", "variation", "cancer"],
      },
      {
        name: "Hardy-Weinberg equilibrium",
        description: "In an ideal population (large, random mating, no selection/mutation/drift/migration), allele and genotype frequencies remain constant across generations.",
        keyFact: "For two alleles (p, q): p + q = 1; genotype frequencies p^2, 2pq, q^2. Deviations from HWE signal selection, drift, or non-random mating.",
        evolvedFrom: ["Alleles"],
        tags: ["population genetics", "equilibrium"],
      },
      {
        name: "Human genome",
        description: "The complete DNA sequence of Homo sapiens: ~3.1 billion base pairs organized in 23 pairs of chromosomes.",
        keyFact: "Human Genome Project completed 2003 (first draft 2001); ~20,000–25,000 protein-coding genes; only ~1.5% of genome is exonic. Telomere-to-telomere assembly completed 2022.",
        evolvedFrom: ["DNA structure"],
        tags: ["genomics", "HGP", "human"],
      },
      {
        name: "Non-coding DNA",
        description: "The ~98.5% of the human genome that does not encode proteins; includes regulatory sequences, introns, transposable elements, and repetitive DNA.",
        keyFact: "Transposable elements (TEs) make up ~45% of the human genome. Much non-coding DNA is functional (regulatory); the fraction that is 'junk' is genuinely debated.",
        evolvedFrom: ["Human genome"],
        status: "contested",
        tags: ["junk DNA", "regulation", "TE"],
      },
      {
        name: "Genetic drift",
        description: "Random fluctuation in allele frequencies due to chance sampling, most powerful in small populations.",
        keyFact: "Effective population size (Ne) determines drift strength. Founder effects and bottlenecks reduce diversity. Drift can fix neutral or even slightly deleterious alleles.",
        evolvedFrom: ["Hardy-Weinberg equilibrium"],
        tags: ["drift", "population genetics", "neutral"],
      },
      {
        name: "Gene flow",
        description: "The movement of alleles between populations through migration of individuals or gametes.",
        keyFact: "Gene flow homogenizes allele frequencies between populations; counteracts local adaptation. Island model: migrants exchange genes at rate m per generation.",
        evolvedFrom: ["Hardy-Weinberg equilibrium"],
        tags: ["migration", "population genetics"],
      },
      {
        name: "Polygenic traits",
        description: "Traits influenced by many loci, typically showing continuous, bell-shaped phenotypic distributions.",
        keyFact: "Examples: height, skin color, intelligence, disease risk. GWAS (genome-wide association studies) detect thousands of SNPs each explaining a tiny fraction of variance.",
        evolvedFrom: ["Alleles", "Linkage and recombination"],
        tags: ["quantitative genetics", "GWAS", "complex traits"],
      },
      {
        name: "Quantitative genetics",
        description: "Studies the genetic basis of continuously varying traits by partitioning phenotypic variance into genetic and environmental components.",
        keyFact: "Heritability (h^2) = Vg/Vp: fraction of phenotypic variance attributable to genetic differences. Narrow-sense h^2 uses additive variance; relevant for response to selection.",
        evolvedFrom: ["Polygenic traits"],
        tags: ["heritability", "variance", "breeding"],
      },
      {
        name: "Sex chromosomes",
        description: "Heteromorphic chromosome pair (XY in therian mammals, ZW in birds) that differs between sexes and carries sex-determination genes.",
        keyFact: "Mammalian X-inactivation (Lyon hypothesis) silences one X in each female somatic cell, ensuring dosage compensation. Y chromosome highly degenerate; SRY triggers male development.",
        evolvedFrom: ["Linkage and recombination"],
        tags: ["sex chromosomes", "X-inactivation", "dosage"],
      },
      {
        name: "Genetic testing and counseling",
        description: "Diagnostic use of genotype data to assess disease risk, carrier status, or ancestry; paired with counseling on implications.",
        keyFact: "Methods: karyotyping, targeted sequencing, array CGH, whole-exome/genome sequencing, GWAS risk scores. Ethical issues: incidental findings, discrimination, reproductive decisions.",
        evolvedFrom: ["Human genome"],
        tags: ["diagnostics", "ethics", "clinical"],
        xref: ["medicine"],
      },
    ],
  },

  // ── Family 4 — Evolution & Natural Selection ──────────────────────────────
  {
    slug: "evolution",
    number: 4,
    name: "Evolution & Natural Selection",
    blurb: "Descent with modification — the unifying theory of biology, from Darwin through the extended synthesis.",
    section: "A",
    color: "cyan",
    entries: [
      {
        name: "Natural selection",
        description: "Differential survival and reproduction due to heritable variation in fitness-relevant traits; the primary driver of adaptive evolution.",
        keyFact: "Darwin's four conditions: variation exists; variation is heritable; individuals differ in fitness; fitness differences are related to heritable variation. First stated 1858 (Darwin & Wallace).",
        evolvedFrom: [],
        tags: ["selection", "Darwin", "adaptation"],
      },
      {
        name: "Adaptation",
        description: "A heritable trait that increases fitness in a specific environment and evolved by natural selection.",
        keyFact: "Adaptations can be morphological (antifreeze proteins in Antarctic fish), behavioral (bird nest-building), or physiological (altitude hemoglobin variants in Tibetans).",
        evolvedFrom: ["Natural selection"],
        tags: ["adaptation", "fitness"],
      },
      {
        name: "Speciation",
        description: "The formation of new reproductively isolated species from ancestral populations.",
        keyFact: "Allopatric speciation (geographic isolation) is most common; sympatric speciation occurs without isolation (e.g., polyploidy in plants). Reproductive isolation can be pre- or post-zygotic.",
        evolvedFrom: ["Natural selection", "Genetic drift", "Gene flow"],
        tags: ["speciation", "reproductive isolation"],
      },
      {
        name: "Phylogenetics",
        description: "The reconstruction of evolutionary relationships among taxa using morphological or molecular data, represented as phylogenetic trees or networks.",
        keyFact: "Maximum parsimony, maximum likelihood, and Bayesian inference are the main tree-building methods. Molecular clocks estimate divergence times. Bootstrapping measures node support.",
        evolvedFrom: ["Common descent"],
        tags: ["phylogeny", "systematics", "molecular evolution"],
      },
      {
        name: "Common descent",
        description: "All extant life shares a common ancestor (LUCA); life's unity is reflected in universal features: the genetic code, ATP currency, and ribosomal RNA.",
        keyFact: "Supported by universal genetic code, biochemical homology, comparative anatomy (homologous structures), the fossil record, and molecular phylogenetics.",
        evolvedFrom: ["Natural selection"],
        tags: ["common ancestor", "LUCA", "unity of life"],
      },
      {
        name: "Sexual selection",
        description: "Selection acting on traits that increase mating success rather than survival, producing elaborate ornaments, weapons, and displays.",
        keyFact: "Intersexual selection (mate choice) produces traits like peacock tails; intrasexual selection (rival competition) produces antlers and fighting behavior. Darwin 1871.",
        evolvedFrom: ["Natural selection"],
        tags: ["sexual selection", "mate choice"],
      },
      {
        name: "Coevolution",
        description: "Reciprocal evolutionary change between interacting species, driven by their mutual selection pressures.",
        keyFact: "Host-parasite arms races, pollinator-plant mutualism (long-tongued moths and deep-nectared orchids), and predator-prey dynamics are canonical examples.",
        evolvedFrom: ["Natural selection", "Adaptation"],
        tags: ["coevolution", "arms race", "mutualism"],
      },
      {
        name: "Convergent evolution",
        description: "Independent evolution of similar traits in distantly related lineages as a result of similar selective pressures.",
        keyFact: "Examples: wings in birds, bats, and pterosaurs; camera eyes in vertebrates and cephalopods; echolocation in bats and dolphins; C4 photosynthesis evolved >60 times.",
        evolvedFrom: ["Natural selection", "Adaptation"],
        tags: ["convergence", "homoplasy"],
      },
      {
        name: "Evo-devo",
        description: "Evolutionary developmental biology: how changes in developmental gene regulation produce major morphological differences.",
        keyFact: "Small changes in cis-regulatory elements of Hox genes and other transcription factors can produce dramatic body-plan differences without changing protein sequence.",
        evolvedFrom: ["Natural selection", "Hox genes"],
        tags: ["evo-devo", "development", "Hox"],
      },
      {
        name: "Punctuated equilibrium",
        description: "Eldredge and Gould (1972): evolution proceeds as rapid bursts of change (during speciation) interspersed with long periods of morphological stasis.",
        keyFact: "Contrasts with phyletic gradualism. Fossil record shows stasis more often than gradual change; this may reflect developmental constraints rather than absent selection.",
        evolvedFrom: ["Speciation", "Natural selection"],
        tags: ["macroevolution", "paleontology"],
      },
      {
        name: "Neutral theory of molecular evolution",
        description: "Kimura (1968): most molecular variation within and between species is selectively neutral; genetic drift, not selection, dominates at the molecular level.",
        keyFact: "Neutral theory predicts molecular clocks. Nearly neutral theory (Ohta) extends it to slightly deleterious mutations. Debate: what fraction of substitutions are adaptive?",
        evolvedFrom: ["Genetic drift"],
        tags: ["neutral theory", "molecular clock", "drift"],
      },
      {
        name: "Modern evolutionary synthesis",
        description: "Integration of Mendelian genetics, Darwinian natural selection, and population genetics in the mid-20th century (1930s–1950s).",
        keyFact: "Key architects: Fisher, Wright, Haldane (population genetics), Dobzhansky, Mayr (speciation), Simpson (paleontology), Stebbins (botany). Gene-centric view of evolution.",
        evolvedFrom: ["Natural selection", "Hardy-Weinberg equilibrium"],
        tags: ["synthesis", "history", "population genetics"],
      },
      {
        name: "Extended evolutionary synthesis",
        description: "A proposed broadening of the Modern Synthesis to include developmental plasticity, epigenetic inheritance, niche construction, and multilevel selection.",
        keyFact: "Proponents: Pigliucci, Muller, Jablonka, West-Eberhard. Critics argue these phenomena fit within the existing synthesis. Still actively debated (2024).",
        status: "contested",
        evolvedFrom: ["Modern evolutionary synthesis"],
        tags: ["extended synthesis", "plasticity", "evo-devo"],
      },
    ],
  },

  // ── Family 5 — Ecology ────────────────────────────────────────────────────
  {
    slug: "ecology",
    number: 5,
    name: "Ecology",
    blurb: "Organisms in their environments — populations, communities, ecosystems, and the biosphere.",
    section: "B",
    color: "blue",
    entries: [
      {
        name: "Ecosystem",
        description: "All organisms in an area plus their abiotic environment, characterized by energy flow and nutrient cycling.",
        keyFact: "Tansley (1935). Ecosystems are open to energy flow but can be roughly closed to nutrients. Ecosystem services include carbon sequestration, water purification, and pollination.",
        evolvedFrom: [],
        tags: ["ecosystem", "energy flow", "nutrient cycling"],
      },
      {
        name: "Trophic levels",
        description: "Hierarchical positions in a food web: producers (autotrophs), primary consumers (herbivores), secondary and tertiary consumers, and decomposers.",
        keyFact: "~10% of energy passes from one trophic level to the next (10% rule); the rest is lost as heat. Decomposers recycle nutrients back to primary producers.",
        evolvedFrom: ["Ecosystem"],
        tags: ["trophic", "energy", "food chain"],
      },
      {
        name: "Food web",
        description: "The network of feeding relationships in a community; more realistic than a linear food chain.",
        keyFact: "Real webs are complex with many omnivores and links; connectance and diversity affect stability. Removing a node can trigger cascading effects.",
        evolvedFrom: ["Trophic levels"],
        tags: ["food web", "community ecology"],
      },
      {
        name: "Biodiversity",
        description: "The variety of life at genetic, species, and ecosystem levels; a key indicator of ecosystem health and resilience.",
        keyFact: "Alpha (within-site), beta (between-site), and gamma (regional) diversity. Higher biodiversity generally increases ecosystem stability and productivity (but relationship is complex).",
        evolvedFrom: ["Ecosystem"],
        tags: ["biodiversity", "conservation", "species richness"],
      },
      {
        name: "Biome",
        description: "A large-scale ecological zone defined by climate and dominant vegetation type.",
        keyFact: "Major terrestrial biomes: tundra, boreal forest (taiga), temperate forest, grassland, chaparral, desert, tropical forest, savanna. Marine biomes: open ocean, coral reef, estuary.",
        evolvedFrom: ["Ecosystem"],
        tags: ["biome", "climate", "vegetation"],
      },
      {
        name: "Keystone species",
        description: "A species with disproportionately large effects on ecosystem structure relative to its biomass.",
        keyFact: "Paine (1966) coined 'keystone species' after showing sea star removal transformed rocky intertidal communities. Sea otters (kelp forest), wolves (Yellowstone), and elephants (savanna) are classic examples.",
        evolvedFrom: ["Food web"],
        tags: ["keystone", "trophic cascades", "conservation"],
      },
      {
        name: "Ecological succession",
        description: "Progressive, directional change in community composition following a disturbance, from pioneer species toward a climax community.",
        keyFact: "Primary succession on bare rock; secondary succession after disturbance. Facilitation: early species modify the environment to favor later ones. Climax concept now considered idealized.",
        evolvedFrom: ["Ecosystem"],
        tags: ["succession", "community ecology"],
      },
      {
        name: "Population dynamics",
        description: "Changes in population size over time governed by births, deaths, immigration, and emigration.",
        keyFact: "Exponential growth: dN/dt = rN. Logistic growth: dN/dt = rN(1 - N/K). Lotka-Volterra equations model predator-prey oscillations. Age structure and life-history affect dynamics.",
        evolvedFrom: ["Ecosystem"],
        tags: ["population", "growth", "Lotka-Volterra"],
      },
      {
        name: "Carrying capacity",
        description: "The maximum population size that an environment can sustain indefinitely given available resources.",
        keyFact: "Symbol K in logistic model; as N approaches K, growth rate approaches zero. Not fixed: can change with resource availability, climate, and technology (for humans).",
        evolvedFrom: ["Population dynamics"],
        tags: ["carrying capacity", "K", "resources"],
      },
      {
        name: "Ecological niche",
        description: "The functional role a species occupies in its community — resources used, habitat, timing, and biotic interactions.",
        keyFact: "Hutchinson's n-dimensional hypervolume: the fundamental niche is all conditions where a species can persist; realized niche is smaller due to competition and predation.",
        evolvedFrom: ["Ecosystem"],
        tags: ["niche", "Hutchinson", "competition"],
      },
      {
        name: "Competitive exclusion principle",
        description: "Two species competing for identical resources cannot coexist stably at equilibrium; one will exclude the other.",
        keyFact: "Gause (1934) demonstrated with Paramecium in culture. In nature, coexistence is possible via niche partitioning, frequency dependence, or disturbance (intermediate disturbance hypothesis).",
        evolvedFrom: ["Ecological niche"],
        tags: ["competition", "coexistence", "Gause"],
      },
      {
        name: "Symbiosis",
        description: "Close, prolonged interactions between species, classified by effects on each partner.",
        keyFact: "Mutualism (+/+): both benefit (mycorrhizae). Commensalism (+/0): one benefits, other unaffected. Parasitism (+/−): one benefits, other harmed. Amensalism (−/0). Endpoints on a continuum.",
        evolvedFrom: ["Food web"],
        tags: ["symbiosis", "mutualism", "parasitism"],
      },
      {
        name: "Nutrient cycling",
        description: "The biogeochemical cycling of carbon, nitrogen, phosphorus, and other elements between organisms and the abiotic environment.",
        keyFact: "Nitrogen cycle requires microbial fixation (Rhizobium, free-living diazotrophs), nitrification, and denitrification. Human agriculture has roughly doubled reactive nitrogen in the biosphere.",
        evolvedFrom: ["Ecosystem"],
        tags: ["nutrient cycle", "biogeochemistry", "nitrogen"],
      },
      {
        name: "Island biogeography",
        description: "MacArthur and Wilson (1967): species richness on islands reaches a dynamic equilibrium between immigration and local extinction rates.",
        keyFact: "Species-area relationship: S = cA^z. Larger islands and closer islands have more species. The theory is the foundation of habitat patch design in conservation.",
        evolvedFrom: ["Biodiversity", "Population dynamics"],
        tags: ["island biogeography", "conservation", "species-area"],
      },
    ],
  },

  // ── Family 6 — Physiology ─────────────────────────────────────────────────
  {
    slug: "physiology",
    number: 6,
    name: "Physiology",
    blurb: "How organs and organ systems maintain function — homeostasis, integration, and whole-body regulation.",
    section: "B",
    color: "sky",
    entries: [
      {
        name: "Homeostasis",
        description: "The maintenance of a stable internal environment despite external fluctuations — temperature, pH, glucose, ion balance.",
        keyFact: "Claude Bernard (milieu intérieur) and Walter Cannon (homeostasis) developed the concept. Deviation from set point triggers corrective responses via feedback loops.",
        evolvedFrom: [],
        tags: ["homeostasis", "regulation", "internal environment"],
        xref: ["medicine"],
      },
      {
        name: "Negative feedback",
        description: "A regulatory mechanism where a deviation from a set point triggers a response that returns the variable toward the set point.",
        keyFact: "Most common homeostatic mechanism. Examples: blood glucose (insulin/glucagon), body temperature (sweating/shivering), blood CO2 (ventilation rate). Contrasts with positive feedback (amplifying).",
        evolvedFrom: ["Homeostasis"],
        tags: ["feedback", "regulation", "control systems"],
      },
      {
        name: "Endocrine system",
        description: "Hormone-secreting glands that release chemical messengers into the bloodstream to regulate slow, sustained physiological responses.",
        keyFact: "Hypothalamus-pituitary axis coordinates most endocrine glands. Key hormones: insulin (glucose), cortisol (stress), thyroid hormones (metabolism), sex steroids (reproduction).",
        evolvedFrom: ["Homeostasis", "Cell signaling"],
        tags: ["hormones", "endocrine", "pituitary"],
        xref: ["medicine"],
      },
      {
        name: "Cardiovascular system",
        description: "Heart and blood vessels transport oxygen, nutrients, and wastes; maintain blood pressure and immune surveillance.",
        keyFact: "Cardiac output = heart rate × stroke volume (typically ~5 L/min at rest). Starling's law: stroke volume increases with ventricular filling. Oxygen delivered as oxyhemoglobin.",
        evolvedFrom: ["Homeostasis"],
        tags: ["heart", "circulation", "blood pressure"],
        xref: ["medicine"],
      },
      {
        name: "Respiratory system",
        description: "Lungs (or gills, etc.) exchange O2 and CO2 between external environment and blood.",
        keyFact: "Ventilation-perfusion matching. Hemoglobin S-curve: cooperative O2 binding; Bohr effect (CO2 and pH reduce affinity). Tidal volume ~500 mL; vital capacity ~4,500 mL at rest.",
        evolvedFrom: ["Homeostasis"],
        tags: ["lungs", "gas exchange", "hemoglobin"],
        xref: ["medicine"],
      },
      {
        name: "Digestive system",
        description: "Mechanical and chemical breakdown of food, absorption of nutrients, and elimination of wastes.",
        keyFact: "Enzymes: amylase (starch), protease (protein), lipase (fat). Small intestine absorbs most nutrients; large intestine recovers water. Gut microbiome contributes >30% of metabolic capacity.",
        evolvedFrom: ["Homeostasis"],
        tags: ["digestion", "absorption", "gut"],
        xref: ["medicine"],
      },
      {
        name: "Renal system",
        description: "Kidneys filter blood, regulate electrolytes and acid-base balance, and produce urine.",
        keyFact: "Each kidney has ~1 million nephrons. Filtration (~180 L/day) → selective reabsorption → secretion. Renin-angiotensin-aldosterone axis controls blood pressure and sodium balance.",
        evolvedFrom: ["Homeostasis"],
        tags: ["kidney", "filtration", "electrolytes"],
        xref: ["medicine"],
      },
      {
        name: "Musculoskeletal system",
        description: "Skeletal muscle and the skeleton provide support, enable movement, and store minerals.",
        keyFact: "Sliding filament theory: actin and myosin filaments slide past each other powered by ATP hydrolysis. Neuromuscular junction: ACh released from motor neuron triggers action potential in muscle.",
        evolvedFrom: ["Homeostasis"],
        tags: ["muscle", "contraction", "skeleton"],
        xref: ["medicine"],
      },
      {
        name: "Thermoregulation",
        description: "Maintenance of body temperature; endotherms generate metabolic heat; ectotherms rely on behavioral regulation.",
        keyFact: "Human thermostat in the hypothalamus. Heat production: shivering, brown adipose tissue. Heat loss: sweating, vasodilation. Fever is an active immune response, not dysregulation.",
        evolvedFrom: ["Homeostasis", "Negative feedback"],
        tags: ["thermoregulation", "endotherm", "ectotherm"],
      },
      {
        name: "Reproductive physiology",
        description: "Hormonal coordination of gamete production, fertilization, gestation, and birth.",
        keyFact: "In humans: HPG axis (hypothalamus GnRH → pituitary FSH/LH → gonads). Menstrual cycle ~28 days; estrogen peaks at ovulation. Pregnancy maintained by placental hCG then progesterone.",
        evolvedFrom: ["Endocrine system"],
        tags: ["reproduction", "hormones", "HPG axis"],
        xref: ["medicine"],
      },
      {
        name: "Osmoregulation",
        description: "Regulation of water and solute concentrations in body fluids, critical for cell volume and function.",
        keyFact: "Osmoconformers (most marine invertebrates) match the external osmolarity; osmoregulators (teleost fish, mammals) maintain a constant internal osmolarity. ADH (vasopressin) regulates renal water reabsorption.",
        evolvedFrom: ["Homeostasis", "Renal system"],
        tags: ["osmoregulation", "ADH", "water balance"],
      },
    ],
  },

  // ── Family 7 — Neuroscience & Sensory Biology ─────────────────────────────
  {
    slug: "neuroscience",
    number: 7,
    name: "Neuroscience & Sensory Biology",
    blurb: "The nervous system from individual neurons to circuits, perception, memory, and behavior.",
    section: "B",
    color: "indigo",
    entries: [
      {
        name: "Neuron",
        description: "The electrically excitable cell unit of the nervous system; integrates inputs and transmits signals along its axon.",
        keyFact: "Typical neuron: dendrites receive input → soma integrates → axon transmits → terminals release neurotransmitter. Myelination by oligodendrocytes (CNS) or Schwann cells (PNS) speeds conduction.",
        evolvedFrom: [],
        tags: ["neuron", "cell biology", "axon"],
      },
      {
        name: "Action potential",
        description: "An all-or-nothing electrical spike propagated along an axon when the membrane potential exceeds threshold.",
        keyFact: "Hodgkin & Huxley (1952): Na+ influx causes depolarization; K+ efflux causes repolarization. Threshold ~−55 mV; peak ~+40 mV. Speed: 0.5–120 m/s depending on myelination.",
        evolvedFrom: ["Neuron"],
        tags: ["action potential", "electrophysiology"],
      },
      {
        name: "Synaptic transmission",
        description: "Communication between neurons (or neuron and target cell) via chemical messengers (neurotransmitters) or electrical coupling.",
        keyFact: "Chemical synapse: action potential → Ca2+ influx → vesicle fusion → neurotransmitter release → postsynaptic receptor binding. Excitatory (EPSP) or inhibitory (IPSP) postsynaptic potentials summate.",
        evolvedFrom: ["Action potential", "Cell signaling"],
        tags: ["synapse", "neurotransmitter", "vesicle"],
      },
      {
        name: "Neurotransmitters",
        description: "Chemical messengers at synapses: glutamate (excitatory), GABA (inhibitory), dopamine, serotonin, acetylcholine, norepinephrine, and many others.",
        keyFact: "Glutamate is the major excitatory NT; GABA is major inhibitory. Monoamines (dopamine, serotonin, norepinephrine) modulate mood, reward, and attention. Most psychiatric drugs target NT systems.",
        evolvedFrom: ["Synaptic transmission"],
        tags: ["neurotransmitters", "dopamine", "GABA"],
        xref: ["medicine"],
      },
      {
        name: "Brain regions",
        description: "Anatomically and functionally distinct areas: cerebral cortex (cognition), cerebellum (motor coordination), hippocampus (memory), amygdala (emotion), basal ganglia (reward/movement).",
        keyFact: "Cerebral cortex: 4 lobes (frontal, parietal, temporal, occipital). Limbic system (hippocampus, amygdala) mediates emotion and memory. Brainstem controls autonomic functions.",
        evolvedFrom: ["Neuron"],
        tags: ["brain", "cortex", "anatomy"],
        xref: ["medicine"],
      },
      {
        name: "Neural plasticity",
        description: "The brain's capacity to change structurally and functionally in response to experience, learning, and injury.",
        keyFact: "Long-term potentiation (LTP): repeated stimulation strengthens synapses via AMPA receptor insertion and spine growth; cellular basis of learning and memory. Critical periods in development: experience shapes circuits.",
        evolvedFrom: ["Synaptic transmission"],
        tags: ["plasticity", "LTP", "learning"],
      },
      {
        name: "Sensory transduction",
        description: "Conversion of physical stimuli — light, sound, pressure, temperature, chemicals — into electrical nerve signals.",
        keyFact: "Specialized receptor cells: photoreceptors (rhodopsin), hair cells (mechanosensory), olfactory neurons (GPCRs), taste receptor cells, and thermoreceptors. Signal amplified by G-protein cascades.",
        evolvedFrom: ["Neuron", "Cell signaling"],
        tags: ["sensory", "transduction", "receptor"],
      },
      {
        name: "Circadian rhythms",
        description: "Endogenous ~24-hour biological clocks entrained by light-dark cycles, regulating sleep, metabolism, and hormone release.",
        keyFact: "Molecular clock: CLOCK/BMAL1 activate PER/CRY, which feed back to inhibit CLOCK/BMAL1. SCN (suprachiasmatic nucleus) is the master clock in mammals. Disruption increases risk of metabolic and mood disorders.",
        evolvedFrom: ["Homeostasis"],
        tags: ["circadian", "clock genes", "sleep"],
      },
      {
        name: "Memory and learning",
        description: "Acquisition and storage of information; encoded by synaptic changes across multiple memory systems.",
        keyFact: "Declarative memory (hippocampus): episodic and semantic. Non-declarative memory: procedural (striatum, cerebellum), priming, conditioning. Consolidation: hippocampal replay during sleep transfers to cortex.",
        evolvedFrom: ["Neural plasticity"],
        tags: ["memory", "hippocampus", "learning"],
      },
      {
        name: "Glial cells",
        description: "Non-neuronal support cells of the nervous system: astrocytes, oligodendrocytes, microglia, Schwann cells.",
        keyFact: "Astrocytes maintain ionic balance, form the blood-brain barrier, and provide metabolic support. Microglia are the CNS immune cells. Oligodendrocytes myelinate axons in CNS; Schwann cells in PNS.",
        evolvedFrom: ["Neuron"],
        tags: ["glia", "astrocyte", "myelin"],
      },
      {
        name: "Neurodegenerative diseases",
        description: "Progressive loss of neuronal structure and function; includes Alzheimer's, Parkinson's, ALS, and Huntington's disease.",
        keyFact: "Alzheimer's: amyloid-beta plaques + tau tangles. Parkinson's: dopaminergic neuron loss + Lewy bodies (alpha-synuclein). ALS: motor neuron death. All lack curative treatments as of 2026.",
        status: "open",
        evolvedFrom: ["Neuron", "Protein folding"],
        tags: ["neurodegeneration", "Alzheimer's", "Parkinson's"],
        xref: ["medicine"],
      },
      {
        name: "Neuromodulation",
        description: "Diffuse broadcast signaling by monoamines and neuropeptides that sets the excitability of large neural circuits without targeted synaptic specificity.",
        keyFact: "Dopamine signals reward prediction error; serotonin affects mood and impulsivity; norepinephrine drives arousal and attention. Target of SSRIs, antipsychotics, stimulants, and many recreational drugs.",
        evolvedFrom: ["Neurotransmitters"],
        tags: ["neuromodulation", "monoamines", "dopamine"],
        xref: ["medicine"],
      },
    ],
  },
];
