import type { Family } from "./types";

export const FAMILIES_15_20: Family[] = [
  // ── Family 15 — Biotechnology & Synthetic Biology ─────────────────────────
  {
    slug: "biotechnology",
    number: 15,
    name: "Biotechnology & Synthetic Biology",
    blurb: "Engineering biological systems — recombinant DNA, gene therapy, mRNA vaccines, and designed organisms.",
    section: "D",
    color: "amber",
    entries: [
      {
        name: "Recombinant DNA",
        description: "DNA assembled from multiple sources by restriction enzymes and DNA ligases; the foundation of genetic engineering.",
        keyFact: "Cohen & Boyer (1973) first cloned a gene into a plasmid in E. coli. Restriction enzymes cut DNA at specific sequences; compatible 'sticky ends' allow precise joining. Enabled insulin production by bacteria (1982).",
        evolvedFrom: ["DNA structure", "CRISPR-Cas9"],
        tags: ["recombinant DNA", "cloning", "genetic engineering"],
      },
      {
        name: "GMOs (genetically modified organisms)",
        description: "Organisms with deliberately altered genomes using recombinant DNA, CRISPR, or other methods.",
        keyFact: "Approved GMO crops: Bt crops (insecticidal toxin gene from Bacillus thuringiensis), herbicide-tolerant soybeans, virus-resistant papaya, Golden Rice (beta-carotene). GMO insulin and other biologics are widely accepted.",
        evolvedFrom: ["Recombinant DNA"],
        tags: ["GMO", "crops", "transgenic"],
      },
      {
        name: "Gene therapy",
        description: "Delivery of therapeutic genetic material into a patient's cells to treat disease.",
        keyFact: "Vectors: AAV (adeno-associated virus) most common; lentivirus for stable integration. First approved gene therapy: Luxturna (RPE65 mutation, inherited blindness, 2017). CAR-T: gene-modified T cells for cancer. Ex vivo vs in vivo approaches.",
        evolvedFrom: ["Recombinant DNA", "Viral phylogenetics"],
        tags: ["gene therapy", "AAV", "CAR-T"],
        xref: ["medicine"],
      },
      {
        name: "Monoclonal antibodies",
        description: "Identical antibodies derived from a single B cell clone, all binding the same epitope with identical affinity.",
        keyFact: "Kohler & Milstein (1975, Nobel 1984): hybridoma technology. Applications: therapeutic (adalimumab for arthritis; bevacizumab for cancer), diagnostic (pregnancy tests, COVID-19 rapid tests), research. ~170 approved monoclonal antibody drugs (2024).",
        evolvedFrom: ["Antibodies (immunoglobulins)"],
        tags: ["monoclonal antibody", "hybridoma", "therapeutics"],
        xref: ["medicine"],
      },
      {
        name: "PCR",
        description: "Polymerase chain reaction: exponential amplification of a specific DNA sequence using thermostable DNA polymerase and primers.",
        keyFact: "Mullis (1983, Nobel 1993). Taq polymerase from Thermus aquaticus. 30 cycles → 10^9-fold amplification. Transformative in diagnostics (COVID-19, STI, paternity), forensics, ancient DNA, and research.",
        evolvedFrom: ["DNA replication", "Extremophiles"],
        tags: ["PCR", "amplification", "diagnostics"],
      },
      {
        name: "mRNA vaccines",
        description: "Vaccines that deliver synthetic mRNA encoding an antigen; host cells produce the antigen and mount an immune response.",
        keyFact: "Karikó and Weissman (Nobel 2023): pseudouridine-modified mRNA evades innate immune sensing. Pfizer-BioNTech and Moderna COVID-19 vaccines: ~70% effectiveness against original strain. Rapid platform: new antigen designed in days.",
        evolvedFrom: ["Vaccines", "RNA types"],
        tags: ["mRNA vaccine", "COVID-19", "immunology"],
        xref: ["medicine"],
      },
      {
        name: "Tissue engineering",
        description: "Growing functional tissues or organs in vitro using scaffolds, stem cells, and bioreactors for transplantation or drug testing.",
        keyFact: "Skin grafts (approved): first engineered tissue in clinical use. Trachea, bladder, cartilage, cornea transplants demonstrated. Organoids: 3D mini-organs in culture for disease modeling. Bioprinting: layer-by-layer deposition of cell-laden bioink.",
        evolvedFrom: ["Stem cells", "Cellular differentiation"],
        tags: ["tissue engineering", "organoids", "bioprinting"],
        xref: ["medicine"],
      },
      {
        name: "Synthetic biology",
        description: "Design and construction of novel biological parts, circuits, and systems — applying engineering principles to biology.",
        keyFact: "BioBricks standard: interchangeable genetic parts. JCVI synthetic cell (2010): first cell with entirely synthetic genome. Minimal cell (2016): JCVI-syn3.0, 473 genes. Applications: biosensors, living medicines, metabolic engineering.",
        evolvedFrom: ["Recombinant DNA"],
        tags: ["synthetic biology", "BioBricks", "minimal cell"],
      },
      {
        name: "CRISPR applications",
        description: "Beyond basic editing: gene drives, base editing, prime editing, epigenome editing, and RNA targeting.",
        keyFact: "Gene drives use CRISPR to spread a trait through a wild population; tested against malaria-carrying mosquitoes. Base editing converts one DNA base to another without double-strand breaks. Prime editing: like find-and-replace for DNA.",
        status: "open",
        evolvedFrom: ["CRISPR-Cas9"],
        tags: ["CRISPR", "gene drive", "base editing"],
      },
      {
        name: "Biofuels",
        description: "Fuels derived from biological material: bioethanol from fermentation, biodiesel from oils, and advanced fuels from algae or cellulosic waste.",
        keyFact: "First-generation: sugar/starch fermentation (corn, sugarcane ethanol). Second-generation: cellulosic biomass (lignocellulose). Third-generation: algae (higher yield/acre, no food competition). Challenges: energy balance and land use.",
        evolvedFrom: ["Fermentation biotechnology"],
        tags: ["biofuels", "ethanol", "algae"],
      },
      {
        name: "Fermentation biotechnology",
        description: "Industrial use of microorganisms to produce ethanol, organic acids, amino acids, antibiotics, enzymes, and therapeutic proteins.",
        keyFact: "Oldest biotechnology: beer/wine fermentation >7,000 years. Industrial fermentation: penicillin (WWII scale-up), MSG, citric acid, lysine, insulin (E. coli), erythropoietin (CHO cells). Global market >$50 billion.",
        evolvedFrom: ["Bacteria"],
        tags: ["fermentation", "industrial biology", "antibiotics"],
      },
      {
        name: "Diagnostic biotechnology",
        description: "Molecular and immunological tools for pathogen detection, disease diagnosis, and genotyping.",
        keyFact: "ELISA: antibody-based quantitative detection. Next-generation sequencing (NGS): complete pathogen genome in hours. CRISPR diagnostics (SHERLOCK, DETECTR): programmable, field-deployable detection at attomolar sensitivity. Clinical metagenomics: culture-free pathogen ID.",
        evolvedFrom: ["PCR", "Monoclonal antibodies"],
        tags: ["diagnostics", "NGS", "CRISPR diagnostics"],
        xref: ["medicine"],
      },
    ],
  },

  // ── Family 16 — Conservation & Environmental Biology ──────────────────────
  {
    slug: "conservation",
    number: 16,
    name: "Conservation & Environmental Biology",
    blurb: "Protecting biodiversity and ecosystems in the face of the sixth mass extinction.",
    section: "D",
    color: "teal",
    entries: [
      {
        name: "Biodiversity loss and the sixth mass extinction",
        description: "Current extinction rates are estimated at 100–1,000 times the background rate due to habitat loss, overexploitation, invasive species, pollution, and climate change.",
        keyFact: "Five previous mass extinctions in Earth history; current one (Anthropocene) is the first driven by a single species. ~1 million species threatened as of the 2019 IPBES global assessment. Vertebrate populations declined 69% on average 1970–2018 (WWF Living Planet Index).",
        evolvedFrom: [],
        tags: ["mass extinction", "biodiversity loss", "Anthropocene"],
      },
      {
        name: "Habitat fragmentation",
        description: "The breaking of continuous habitat into isolated patches by human land use, reducing population viability.",
        keyFact: "Fragmentation reduces population size (inbreeding), increases edge effects (altered microclimate, predation), and impedes dispersal. Minimum viable population (MVP) and population viability analysis (PVA) guide management.",
        evolvedFrom: ["Island biogeography", "Biodiversity"],
        tags: ["fragmentation", "edge effects", "MVP"],
      },
      {
        name: "Invasive species",
        description: "Non-native species introduced to new ranges that cause ecological or economic harm by outcompeting or consuming native species.",
        keyFact: "Second-leading cause of extinction after habitat loss. Examples: cane toad in Australia, brown tree snake in Guam (extinguished most native birds), zebra mussels in Great Lakes. Cost: ~$423 billion/year globally (IPBES 2023 estimate).",
        evolvedFrom: ["Competitive exclusion principle"],
        tags: ["invasive species", "biological invasion", "extinction"],
      },
      {
        name: "Conservation genetics",
        description: "Application of genetic tools to the management of endangered species: kinship, population structure, adaptive variation, inbreeding.",
        keyFact: "Genetic rescue: introducing migrants to inbred populations can dramatically increase fitness (e.g., Florida panther, Isle Royale wolves). Genomic tools now enable individual-level kinship, sex ID, and population of origin from environmental DNA.",
        evolvedFrom: ["Quantitative genetics", "Genetic drift"],
        tags: ["conservation genetics", "inbreeding", "eDNA"],
      },
      {
        name: "IUCN Red List",
        description: "The global standard for assessing species threat status, from Least Concern to Extinct.",
        keyFact: "Categories: LC → NT → VU → EN → CR → EW → EX. Criteria: population size, decline rate, range, quantitative extinction probability. >44,000 species threatened as of 2023 assessment (of >157,000 assessed). Updated annually.",
        evolvedFrom: ["Biodiversity loss and the sixth mass extinction"],
        tags: ["IUCN", "Red List", "threatened species"],
      },
      {
        name: "Protected areas",
        description: "Formally designated areas managed for biodiversity conservation: national parks, marine reserves, wildlife refuges.",
        keyFact: "Kunming-Montreal Global Biodiversity Framework (2022): 30×30 target (protect 30% of land and ocean by 2030). As of 2025: ~17% land, ~8% ocean protected — below target. Effectiveness varies widely; 'paper parks' a concern.",
        evolvedFrom: ["Island biogeography"],
        tags: ["protected areas", "30x30", "marine reserves"],
      },
      {
        name: "Rewilding",
        description: "Restoring ecological processes and missing keystone species to allow self-regulating ecosystems to re-establish.",
        keyFact: "Wolf reintroduction in Yellowstone (1995): trophic cascade reduced elk overgrazing, restored riparian vegetation, changed river geomorphology. Pleistocene rewilding: reintroducing megafauna analogs. Ambitious proposals include de-extinction (Colossal Biosciences).",
        evolvedFrom: ["Keystone species", "Trophic levels"],
        tags: ["rewilding", "trophic cascade", "wolves"],
      },
      {
        name: "One Health",
        description: "An integrated approach recognizing the interconnection of human, animal, and environmental health.",
        keyFact: "~60% of emerging infectious diseases are zoonotic. COVID-19, Ebola, HIV, and influenza all have animal origins. One Health frameworks coordinate veterinary, medical, and environmental surveillance to prevent pandemics.",
        evolvedFrom: ["Human microbiome", "Ecology"],
        tags: ["One Health", "zoonosis", "pandemic prevention"],
        xref: ["medicine"],
      },
      {
        name: "Climate change and biology",
        description: "Anthropogenic warming is shifting species ranges, disrupting phenological synchrony, bleaching coral reefs, and increasing extinction risk.",
        keyFact: "1.5°C target (Paris Agreement): at 2°C, >18% of species face high extinction risk. Coral bleaching threshold exceeded annually in most reefs since 2016. Phenological mismatch (e.g., peak caterpillar emergence before bird hatching) disrupts food webs.",
        status: "open",
        evolvedFrom: ["Ecosystem"],
        tags: ["climate change", "phenology", "coral bleaching"],
      },
      {
        name: "Trophic cascades",
        description: "Indirect ecological effects that propagate downward through a food web when a top predator is added or removed.",
        keyFact: "Sea otter removal → sea urchin explosion → kelp forest collapse. Shark fin fishing → ray population growth → shellfish population collapse. Positive trophic cascades (with predator): wolves, sea otters, sharks as ecosystem engineers.",
        evolvedFrom: ["Keystone species", "Food web"],
        tags: ["trophic cascades", "top-down control", "predator"],
      },
    ],
  },

  // ── Family 17 — Bioinformatics & Systems Biology ──────────────────────────
  {
    slug: "bioinformatics",
    number: 17,
    name: "Bioinformatics & Systems Biology",
    blurb: "Computational approaches to biological data — from sequence alignment to deep learning and whole-system models.",
    section: "D",
    color: "sky",
    entries: [
      {
        name: "Sequence alignment",
        description: "Identifying regions of similarity between DNA, RNA, or protein sequences to infer function or evolutionary relationships.",
        keyFact: "Pairwise algorithms: Needleman-Wunsch (global, 1970) and Smith-Waterman (local, 1981). Multiple sequence alignment (Clustal, MAFFT, MUSCLE). Scoring matrices: BLOSUM62 for proteins, match/mismatch for DNA.",
        evolvedFrom: [],
        tags: ["sequence alignment", "bioinformatics", "BLAST"],
        xref: ["computer-science"],
      },
      {
        name: "BLAST",
        description: "Basic Local Alignment Search Tool: rapidly finds sequences similar to a query in large databases using heuristic methods.",
        keyFact: "Altschul et al. (1990); most-cited biology paper of all time. E-value: expected number of hits by chance; E < 0.001 typically significant. NCBI GenBank: >4 trillion nucleotides (2024). BLASTn (DNA), BLASTp (protein), BLASTx (translated).",
        evolvedFrom: ["Sequence alignment"],
        tags: ["BLAST", "database search", "homology"],
        xref: ["computer-science"],
      },
      {
        name: "Phylogenomics",
        description: "Inference of evolutionary relationships from genome-scale data, resolving ambiguities intractable with single genes.",
        keyFact: "Concatenation and coalescent-based methods for species tree estimation. Resolves deep relationships: placement of turtles (with archosaurs, not lepidosaurs); animals as closer to fungi than to plants.",
        evolvedFrom: ["Molecular phylogenetics", "Sequence alignment"],
        tags: ["phylogenomics", "species tree", "genomics"],
      },
      {
        name: "Proteomics",
        description: "Genome-wide characterization of protein expression levels, post-translational modifications, interactions, and structures.",
        keyFact: "Mass spectrometry (MS): proteins fragmented into peptides → m/z ratios identify sequence. Quantitative proteomics: SILAC, iTRAQ, label-free. Human Proteome Project: aims to characterize all ~20,000 proteins at least once.",
        evolvedFrom: ["Translation", "Post-translational modification"],
        tags: ["proteomics", "mass spectrometry", "HPA"],
        xref: ["chemistry"],
      },
      {
        name: "Single-cell RNA sequencing (scRNA-seq)",
        description: "Transcriptomics at single-cell resolution, revealing cell-type diversity and developmental trajectories.",
        keyFact: "Enables clustering of cells by expression profile without prior knowledge of cell types. Human Cell Atlas project: map every cell type in the human body. Trajectory analysis infers differentiation paths. Drop-seq, 10x Chromium common platforms.",
        evolvedFrom: ["Transcription", "BLAST"],
        tags: ["scRNA-seq", "single cell", "cell atlas"],
      },
      {
        name: "Metabolomics",
        description: "Systematic measurement of the complete set of small-molecule metabolites in a cell, tissue, or organism.",
        keyFact: "Metabolome is the closest layer to phenotype. Techniques: NMR, GC-MS, LC-MS. Human Metabolome Database: >220,000 metabolites. Biomarker discovery for disease; metabolic flux analysis for engineering.",
        evolvedFrom: ["Proteomics"],
        tags: ["metabolomics", "metabolites", "NMR"],
        xref: ["chemistry"],
      },
      {
        name: "Network biology",
        description: "Representing biological systems as graphs of interacting molecules: protein interaction networks, metabolic networks, gene regulatory networks.",
        keyFact: "Protein interaction networks are scale-free (power-law degree distribution) with hub proteins. Network topology identifies essential genes (hubs are lethal when deleted). Interactome projects: ~400,000 human protein interactions mapped.",
        evolvedFrom: ["Systems biology"],
        tags: ["network", "interactome", "graph theory"],
        xref: ["computer-science"],
      },
      {
        name: "Machine learning in biology",
        description: "Deep learning models applied to protein structure prediction, genomics, drug discovery, and medical imaging.",
        keyFact: "AlphaFold2 (DeepMind, 2020): predicted protein structures for virtually all known proteins (~200 million, 2022 database); solved the 50-year protein-folding problem. Foundation models for genomics (Enformer, Evo) predict regulatory function from sequence.",
        evolvedFrom: ["Sequence alignment", "Protein folding"],
        tags: ["machine learning", "AlphaFold", "deep learning"],
        xref: ["computer-science"],
      },
      {
        name: "Computational modeling",
        description: "Mathematical and simulation models of biological processes — from biochemical kinetics to population dynamics to whole-cell models.",
        keyFact: "Hodgkin-Huxley model (1952): differential equations for action potential. Lotka-Volterra: predator-prey oscillations. Whole-cell model (Karr et al., 2012): first complete model of M. genitalium (525 genes, all processes).",
        evolvedFrom: ["Population dynamics", "Action potential"],
        tags: ["modeling", "simulation", "differential equations"],
        xref: ["computer-science"],
      },
      {
        name: "Systems biology",
        description: "Studies biological systems as integrated wholes, seeking emergent properties not visible at the level of individual components.",
        keyFact: "Integration of genomics, transcriptomics, proteomics, metabolomics across time and space. Aims to build predictive, mechanistic models. Synthetic biology is the 'engineering arm' of systems biology.",
        evolvedFrom: ["Network biology"],
        tags: ["systems biology", "emergent properties", "integration"],
      },
    ],
  },

  // ── Family 18 — Origins of Life & Major Evolutionary Transitions ──────────
  {
    slug: "origins-of-life",
    number: 18,
    name: "Origins of Life & Major Evolutionary Transitions",
    blurb: "Abiogenesis, the RNA world, and the pivotal transitions that shaped the history of life.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Abiogenesis",
        description: "The hypothetical process by which life arose from non-living chemistry; no confirmed theory exists.",
        keyFact: "Two leading venues: hydrothermal vents (alkaline, submarine, proton gradient as primordial energy) and warm little ponds (Oparin-Haldane, UV-driven prebiotic chemistry). Timescale: life arose within ~200 Ma of Earth's formation (~4.4–4.1 Ga).",
        status: "open",
        evolvedFrom: [],
        tags: ["abiogenesis", "origin of life", "prebiotic chemistry"],
        xref: ["chemistry"],
      },
      {
        name: "RNA world hypothesis",
        description: "In an early evolutionary stage, RNA molecules served both as genetic information carriers and as catalysts, before the DNA/protein division of labor.",
        keyFact: "Ribozymes (catalytic RNA) demonstrate RNA can catalyze reactions; ribosome active site is RNA, not protein. Cech and Altman (Nobel 1989). Synthesis of RNA nucleotides under plausible prebiotic conditions demonstrated (Sutherland group).",
        status: "open",
        evolvedFrom: ["Abiogenesis", "Non-coding RNA"],
        tags: ["RNA world", "ribozyme", "prebiotic"],
        xref: ["chemistry"],
      },
      {
        name: "Last universal common ancestor (LUCA)",
        description: "The most recent population of organisms from which all extant life descends.",
        keyFact: "Genomic reconstruction: LUCA likely anaerobic, thermophilic, chemolithotrophic; possessed DNA, ribosomes, and a membrane. Estimated ~3.5–4.2 Ga. Recent phylogenomic analysis (2024) places LUCA before the divergence of Bacteria and Archaea with a complex gene repertoire.",
        evolvedFrom: ["Common descent"],
        tags: ["LUCA", "common ancestor", "deep evolution"],
      },
      {
        name: "Origin of eukaryotes",
        description: "Eukaryotes arose through an endosymbiotic merger of an archaeal host and a bacterial symbiont (the future mitochondrion).",
        keyFact: "Asgard archaea (Lokiarchaeota) are the closest archaeal relatives of eukaryotes (2015); may have had cytoskeletal proteins. Two-domain tree of life vs three-domain: active debate. Event ~1.8–2 Ga. Nucleus origin disputed.",
        status: "open",
        evolvedFrom: ["Endosymbiotic theory", "Three domains of life"],
        tags: ["eukaryote origin", "Asgard", "endosymbiosis"],
      },
      {
        name: "Origin of multicellularity",
        description: "The transition from single-celled to multicellular organization, enabling division of labor and larger body size.",
        keyFact: "Evolved independently at least 25 times (animals, plants, fungi, algae, slime molds, etc.). Requires cell adhesion, communication, and altruism (some cells die for others). Volvox: model for incipient multicellularity. Transition >700 Ma in animals.",
        evolvedFrom: ["Eukaryotic cell", "Kin selection"],
        tags: ["multicellularity", "transition", "division of labor"],
      },
      {
        name: "Cambrian explosion",
        description: "The geologically rapid (~538–520 Ma) diversification of animal body plans, leaving a rich fossil record.",
        keyFact: "Most animal phyla appear within ~13 million years. Burgess Shale (Canada) and Chengjiang (China) preserve soft-bodied fauna. Causes debated: oxygen increase, snowball Earth aftermath, predator-prey arms race, ecological triggering.",
        evolvedFrom: ["Natural selection", "Origin of multicellularity"],
        tags: ["Cambrian explosion", "body plans", "Burgess Shale"],
      },
      {
        name: "Origin of sex",
        description: "The evolutionary puzzle of why meiosis and sexual reproduction persist despite their costs (only half of offspring reproduce).",
        keyFact: "Hypotheses: Red Queen (parasite-driven allele shuffling), DNA repair (recombination fixes damage), Muller's Ratchet (sex purges deleterious mutations). No consensus. Most eukaryotes sexual; asexual lineages tend to go extinct.",
        status: "open",
        evolvedFrom: ["Meiosis", "Natural selection"],
        tags: ["sex evolution", "Red Queen", "meiosis"],
      },
      {
        name: "Major evolutionary transitions",
        description: "Maynard Smith and Szathmary (1995): eight key transitions in the history of life that changed the way information is stored and transmitted.",
        keyFact: "Transitions: replicating molecules → chromosomes; RNA → DNA+protein; prokaryote → eukaryote; asexual → sexual; unicellular → multicellular; solitary → colonial (eusocial); primate societies → human language. Each transition creates a new level of individuality.",
        evolvedFrom: ["Origin of multicellularity", "Eusociality"],
        tags: ["major transitions", "Maynard Smith", "information"],
      },
      {
        name: "Endosymbiotic events",
        description: "The nested series of symbioses by which plastids arose: primary, secondary, and tertiary endosymbiosis explains the complex algal diversity.",
        keyFact: "Primary: cyanobacterium engulfed → chloroplast (in green plants, red algae). Secondary: a eukaryotic alga engulfed → complex plastids in diatoms, dinoflagellates, euglenids, etc. Tertiary: secondary alga engulfed. Causes reticulate evolution in algal classification.",
        evolvedFrom: ["Endosymbiotic theory"],
        tags: ["secondary endosymbiosis", "plastid", "algae evolution"],
      },
    ],
  },

  // ── Family 19 — Contested Classifications & Open Problems ──────────────────
  {
    slug: "contested-open",
    number: 19,
    name: "Contested Classifications & Open Problems",
    blurb: "Where biology's hardest questions live — contested borders, unresolved debates, and genuinely open problems.",
    section: "E",
    color: "amber",
    entries: [
      {
        name: "Are viruses alive?",
        description: "Viruses replicate and evolve but lack metabolism, ribosomes, and the ability to reproduce independently — their status as 'living' is genuinely contested.",
        keyFact: "Classic criteria for life (metabolism, homeostasis, reproduction) exclude viruses. Giant viruses (Mimivirus) have translation-related genes, blurring the line. Many biologists consider the question semantic; viruses clearly evolve and interact with life.",
        status: "contested",
        evolvedFrom: ["Viruses"],
        tags: ["virus", "definition of life", "contested"],
      },
      {
        name: "Species concept debate",
        description: "More than 25 competing species concepts exist; no universal definition works across all organisms and purposes.",
        keyFact: "Biological species concept (BSC) fails for asexuals, fossils, and bacteria. Phylogenetic species concept proliferates species counts. Practical taxonomy uses morphology + genetics. Most biologists use a pluralistic approach.",
        status: "contested",
        evolvedFrom: ["Species concepts"],
        tags: ["species", "definition", "pluralism"],
      },
      {
        name: "Epigenetic inheritance across generations",
        description: "Whether environmentally induced epigenetic changes (DNA methylation, histone marks) can be inherited by offspring, reviving a form of Lamarckian inheritance.",
        keyFact: "Evidence in plants (clear), nematodes (demonstrated), rodents (some studies), humans (disputed). Germline epigenetic reprogramming largely erases epigenetic marks between generations in mammals; extent of transmission debated.",
        status: "contested",
        evolvedFrom: ["Epigenetics", "Extended evolutionary synthesis"],
        tags: ["epigenetic inheritance", "Lamarck", "transgenerational"],
      },
      {
        name: "Junk DNA debate",
        description: "What fraction of the human genome is functional? The ENCODE project's claim that >80% is biochemically active is disputed.",
        keyFact: "ENCODE (2012): >80% of genome has biochemical activity (binds protein, is transcribed). Critics (Graur, Doolittle): biochemical activity ≠ biological function; estimated true functional fraction is 8–25%. Ongoing controversy.",
        status: "contested",
        evolvedFrom: ["Non-coding DNA"],
        tags: ["junk DNA", "ENCODE", "functional genome"],
      },
      {
        name: "Consciousness and sentience in animals",
        description: "Whether non-human animals have subjective experience — moral and legal implications depend on the answer.",
        keyFact: "Cambridge Declaration on Consciousness (2012): many non-human animals possess neurological substrates for conscious experience. Cephalopods, corvids, and fish show surprisingly complex cognitive behaviors. No agreed criterion for sentience; central to animal welfare law.",
        status: "open",
        evolvedFrom: ["Neuroscience"],
        tags: ["consciousness", "sentience", "animal cognition"],
      },
      {
        name: "What is a gene?",
        description: "Alternative splicing, overlapping genes, regulatory RNA, and transposable elements have profoundly complicated the classical one-gene-one-protein definition.",
        keyFact: "~95% of human multi-exon genes are alternatively spliced. Many 'genes' encode regulatory RNAs; some are embedded within other genes on the same strand. ENCODE identified thousands of novel transcripts. Multiple competing definitions coexist in the literature.",
        status: "contested",
        evolvedFrom: ["Non-coding RNA", "Transcription"],
        tags: ["gene definition", "alternative splicing", "ncRNA"],
      },
      {
        name: "Neutral vs. adaptive molecular evolution",
        description: "What proportion of molecular variation within and between species is neutral (drift) vs. adaptive (positive selection) vs. purifying selection?",
        keyFact: "McDonald-Kreitman test estimates adaptive substitution fraction (alpha). Estimates in Drosophila: ~50% of amino acid substitutions are adaptive; in humans: <10%. Debate ongoing; strongly affected by effective population size.",
        status: "open",
        evolvedFrom: ["Neutral theory of molecular evolution"],
        tags: ["neutral theory", "adaptive evolution", "alpha"],
      },
      {
        name: "Multilevel selection",
        description: "Whether natural selection operates only on individuals (and genes within them) or also on groups, generating altruism by inter-group competition.",
        keyFact: "Hamilton, Dawkins: kin selection and inclusive fitness are sufficient; no need for group selection. D.S. Wilson, E.O. Wilson (2010): group selection is real and important, especially for eusociality. Debate partly terminological; both sides agree selection can act at multiple levels in different contexts.",
        status: "contested",
        evolvedFrom: ["Kin selection", "Eusociality"],
        tags: ["multilevel selection", "group selection", "inclusive fitness"],
      },
      {
        name: "Horizontal gene transfer in eukaryotes",
        description: "The extent and significance of HGT from bacteria or other domains into eukaryotic genomes is actively debated.",
        keyFact: "Mitochondrial and plastid gene transfers to nucleus: well-documented. HGT into animal genomes from non-organellar sources: some cases confirmed (bdelloid rotifers: ~10% of genome), but many early claims overturned by contamination controls. Debate ongoing.",
        status: "contested",
        evolvedFrom: ["Horizontal gene transfer", "Origin of eukaryotes"],
        tags: ["HGT eukaryotes", "contested", "rotifers"],
      },
      {
        name: "Kingdom boundaries in the eukaryotic tree",
        description: "How many kingdoms or supergroups should be recognized? The placement of several major lineages remains disputed.",
        keyFact: "Major proposed supergroups: Opisthokonta (animals + fungi), Archaeplastida (plants + red/green algae), SAR (stramenopiles + alveolates + Rhizaria), Excavata (flagellated protists). Phylogenomic studies disagree on eukaryote root; Metamonada placement contentious.",
        status: "contested",
        evolvedFrom: ["Kingdom debates"],
        tags: ["eukaryote supergroups", "SAR", "classification"],
      },
      {
        name: "Protein moonlighting",
        description: "The discovery that many proteins have multiple, unrelated functions — the classical one-gene-one-protein-one-function paradigm is broken.",
        keyFact: "Glycolytic enzymes serve as transcription factors in the nucleus; cytoskeletal proteins moonlight as RNA-binding proteins; heat shock proteins act as extracellular signaling molecules. >300 moonlighting proteins documented. Implications for drug targeting and systems models.",
        status: "open",
        evolvedFrom: ["Protein folding", "Post-translational modification"],
        tags: ["moonlighting", "protein function", "proteomics"],
      },
    ],
  },

  // ── Family 20 — Landmark Experiments & Discoveries ────────────────────────
  {
    slug: "landmark-experiments",
    number: 20,
    name: "Landmark Experiments & Discoveries",
    blurb: "The pivotal experiments and discoveries that transformed our understanding of life — nature revealed at its most surprising.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Mendel's pea experiments (1856–1863)",
        description: "Gregor Mendel's crosses of pea plants established the laws of inheritance — published 1866, ignored for 35 years.",
        keyFact: "7 traits, ~29,000 plants. Traits segregated independently (except when linked). Mendel's ratios (3:1, 9:3:3:1) required discrete, particulate hereditary factors — not blending. Rediscovered by de Vries, Correns, and Tschermak in 1900.",
        status: "resolved",
        evolvedFrom: ["Mendel's laws"],
        tags: ["Mendel", "history", "genetics"],
      },
      {
        name: "Griffith's transformation (1928)",
        description: "Fred Griffith showed that heat-killed virulent bacteria could 'transform' live avirulent bacteria — suggesting a transmissible hereditary material.",
        keyFact: "Live rough (avirulent) + heat-killed smooth (virulent) Streptococcus → live smooth bacteria in mice. Griffith called the agent the 'transforming principle.' Did not identify DNA, but established horizontal gene transfer in bacteria.",
        status: "resolved",
        evolvedFrom: ["Bacteria", "Horizontal gene transfer"],
        tags: ["Griffith", "transformation", "history"],
      },
      {
        name: "Avery-MacLeod-McCarty (1944)",
        description: "Oswald Avery, Colin MacLeod, and Maclyn McCarty demonstrated that DNA (not protein) is the hereditary material.",
        keyFact: "Used biochemical fractionation of Griffith's transforming principle: DNase destroyed activity; protease and RNase did not. Initially controversial — protein was favored. Avery not awarded the Nobel Prize before his death (1955).",
        status: "resolved",
        evolvedFrom: ["Griffith's transformation (1928)", "DNA structure"],
        tags: ["Avery", "DNA", "hereditary material"],
      },
      {
        name: "Hershey-Chase experiment (1952)",
        description: "Alfred Hershey and Martha Chase used radioactive labels to confirm that phage DNA (not protein) enters the host and directs replication.",
        keyFact: "35S-labelled protein stays outside; 32P-labelled DNA enters. Infected bacteria with 32P-containing phage produced new phage with 32P label. Widely credited with convincing the scientific community of DNA as the genetic material.",
        status: "resolved",
        evolvedFrom: ["Avery-MacLeod-McCarty (1944)", "Bacteriophages"],
        tags: ["Hershey-Chase", "phage", "DNA"],
      },
      {
        name: "Watson, Crick & Franklin — DNA double helix (1953)",
        description: "The determination of DNA's double-helical structure, the most consequential discovery in molecular biology.",
        keyFact: "X-ray diffraction images (Photo 51) by Rosalind Franklin and Raymond Wilkins provided critical data. Watson and Crick's model (April 1953, Nature): antiparallel strands, base complementarity immediately suggests replication mechanism. Nobel 1962 (Watson, Crick, Wilkins).",
        status: "resolved",
        evolvedFrom: ["DNA structure"],
        tags: ["DNA double helix", "Franklin", "Watson Crick"],
      },
      {
        name: "Meselson-Stahl experiment (1958)",
        description: "Demonstrated semi-conservative DNA replication using heavy and light nitrogen isotopes — called 'the most beautiful experiment in biology'.",
        keyFact: "Bacteria grown in 15N, then shifted to 14N; after one generation, all DNA was hybrid (one heavy/one light strand). After two generations, half hybrid and half light. Conclusively eliminated conservative and dispersive replication models.",
        status: "resolved",
        evolvedFrom: ["DNA replication", "Watson, Crick & Franklin — DNA double helix (1953)"],
        tags: ["Meselson-Stahl", "replication", "semi-conservative"],
      },
      {
        name: "Jacob & Monod — lac operon (1961)",
        description: "Francois Jacob and Jacques Monod discovered the operon: a regulatory unit where a repressor protein controls a cluster of functionally related genes.",
        keyFact: "lac operon: lacI repressor binds operator to block transcription; allolactose (inducer) causes repressor to dissociate. First molecular model of gene regulation. Nobel 1965. Concept of negative feedback in gene expression.",
        status: "resolved",
        evolvedFrom: ["Gene expression regulation", "Transcription"],
        tags: ["lac operon", "Jacob Monod", "gene regulation"],
      },
      {
        name: "McClintock — transposable elements (1940s–1950s)",
        description: "Barbara McClintock discovered 'jumping genes' — transposable elements that move within and between chromosomes — in maize.",
        keyFact: "Observed Ds and Ac elements controlling color patterns in maize kernels. Ignored for decades; vindicated when TEs found in all organisms. TEs constitute ~45% of human genome. Nobel 1983.",
        status: "resolved",
        evolvedFrom: ["Mutation", "Non-coding DNA"],
        tags: ["McClintock", "transposable elements", "jumping genes"],
      },
      {
        name: "Nüsslein-Volhard & Wieschaus — developmental genes (1980)",
        description: "Systematic mutagenesis of Drosophila revealed the genetic control of body plan development.",
        keyFact: "Screened >40,000 mutagenized lines; identified classes of genes organizing the body plan: gap, pair-rule, segment-polarity, homeotic. Opened the field of developmental genetics; genes conserved in humans. Nobel 1995 (with Lewis).",
        status: "resolved",
        evolvedFrom: ["Hox genes", "Embryogenesis"],
        tags: ["Nüsslein-Volhard", "Drosophila", "developmental genetics"],
      },
      {
        name: "Marshall & Warren — H. pylori and ulcers (1984)",
        description: "Barry Marshall and Robin Warren demonstrated that peptic ulcers are caused by the bacterium Helicobacter pylori, not by stress.",
        keyFact: "Marshall drank H. pylori culture to self-infect, developed gastritis, and was cured by antibiotics. Initially dismissed; now ulcers are treated with antibiotics. Nobel 2005. Paradigm shift: common diseases can have microbial causes.",
        status: "resolved",
        evolvedFrom: ["Bacteria", "Biofilms"],
        tags: ["H. pylori", "Marshall Warren", "ulcers"],
        xref: ["medicine"],
      },
      {
        name: "Yamanaka factors — iPSCs (2006)",
        description: "Shinya Yamanaka showed that four transcription factors (Oct4, Sox2, Klf4, c-Myc) can reprogram differentiated cells into induced pluripotent stem cells.",
        keyFact: "Adult mouse fibroblasts → iPSCs with properties essentially identical to embryonic stem cells. Nobel 2012 (shared with Gurdon). Eliminates embryo requirement for stem cell therapy; patient-specific disease modeling and cell therapy.",
        status: "resolved",
        evolvedFrom: ["Induced pluripotent stem cells (iPSCs)", "Transcription factors"],
        tags: ["Yamanaka", "iPSC", "reprogramming"],
        xref: ["medicine"],
      },
      {
        name: "AlphaFold2 — protein structure prediction (2020)",
        description: "DeepMind's AlphaFold2 deep learning model predicted protein structures from sequence with near-experimental accuracy, effectively solving the 50-year protein-folding problem.",
        keyFact: "CASP14 competition (2020): AlphaFold2 dominated all categories. AlphaFold Protein Structure Database (2022): ~200 million structures. Enabled rapid COVID-19 structural biology. Nobel 2024 (Hassabis, Jumper for AlphaFold; Baker for computational protein design).",
        status: "resolved",
        evolvedFrom: ["Protein folding", "Machine learning in biology"],
        tags: ["AlphaFold", "protein structure", "deep learning"],
        xref: ["computer-science"],
      },
    ],
  },
];
