export type Entry = {
  name: string;
  description: string;
  tags: string[];
  tenet: string;
  lineage: { parents: string[]; divergence: string; contested?: boolean };
  figures: string[];
  era: string[];
  coreTenets: string[];
  keyThinkers: string[];
  historicalInstances?: string[];
  principalCritiques: string[];
  broadFamily?: boolean;
  flagged?: boolean;
  /** Approximate start year for timeline positioning */
  startYear?: number;
};

export type Family = {
  slug: string;
  name: string;
  blurb: string;
  color: string;
  entries: Entry[];
  broadFamily?: boolean;
};

// ── FAMILY 1 — ANCIENT TO RENAISSANCE ──────────────────────────────────────────

const ANCIENT_TO_RENAISSANCE: Family = {
  slug: "ancient-to-renaissance",
  name: "Ancient to Renaissance",
  blurb: "From prehistoric cave painting through the classical world, Byzantium, and the rebirth of naturalism in Europe.",
  color: "stone",
  entries: [
    {
      name: "Prehistoric / Cave art",
      description: "Image-making in the Upper Palaeolithic, using pigment, engraving, and relief on cave walls and portable objects.",
      tags: ["visual"],
      tenet: "Represent the animal and symbolic world on durable surfaces using mineral pigments and incised lines.",
      lineage: { parents: [], divergence: "root — earliest surviving human image-making tradition" },
      figures: ["Lascaux caves (c. 17,000 BP)", "Altamira (c. 36,000 BP)", "Chauvet cave (c. 36,000 BP)"],
      era: ["prehistoric"],
      startYear: -35000,
      coreTenets: [
        "Depictions of animals, handprints, and abstract signs dominate the surviving corpus.",
        "Pigment sources include iron oxides (ochre), manganese dioxide, and charcoal.",
        "Function remains debated: proposed purposes include ritual, hunting magic, narrative, and social bonding.",
      ],
      keyThinkers: ["Henri Breuil — early classification of cave art", "Jean Clottes & David Lewis-Williams — shamanistic interpretation (contested)"],
      principalCritiques: [
        "Interpretive frameworks (hunting magic, shamanism) rest on ethnographic analogy whose applicability to Palaeolithic societies is uncertain.",
        "Survivorship bias: portable and outdoor art is largely lost, so cave art may not represent the full range of prehistoric image-making.",
      ],
    },
    {
      name: "Ancient Egyptian art",
      description: "Image and object production in pharaonic Egypt, governed by canonical proportions and oriented toward the afterlife.",
      tags: ["visual"],
      tenet: "Represent figures according to canonical proportions and hieratic scale to serve funerary and religious functions.",
      lineage: { parents: [], divergence: "root — Nile valley tradition; functionally tied to kingship, cult, and the afterlife" },
      figures: ["Tomb painters of Thebes", "sculptors of the Great Sphinx", "Amarna-period artists under Akhenaten"],
      era: ["ancient"],
      startYear: -3000,
      coreTenets: [
        "Composite perspective: heads and legs in profile, torsos frontal, to show each body part in its most recognizable aspect.",
        "Hieratic scale: size indicates social or divine importance, not spatial distance.",
        "Art serves ka (spirit) preservation, tomb provision, and temple ritual — not aesthetic display in the modern sense.",
      ],
      keyThinkers: ["Heinrich Schäfer — Principles of Egyptian Art", "Gay Robins — The Art of Ancient Egypt"],
      principalCritiques: [
        "The Western label 'art' imposes anachronistic categories on objects whose makers conceived them as functional ritual instruments.",
        "The Amarna period's departure from canonical style complicates narratives of unchanging Egyptian aesthetic.",
      ],
    },
    {
      name: "Greek / Hellenistic art",
      description: "Sculpture, painting, and architecture in the Greek world from the Archaic through the Hellenistic period.",
      tags: ["visual"],
      tenet: "Pursue idealized naturalism through proportion, contrapposto, and the study of the human body.",
      lineage: { parents: [], divergence: "root — Aegean and Mediterranean tradition; progressive naturalism from Archaic to Hellenistic" },
      figures: ["Phidias — Parthenon sculptures", "Polykleitos — Doryphoros (Canon)", "Praxiteles — Aphrodite of Knidos", "Lysippos"],
      era: ["ancient"],
      startYear: -700,
      coreTenets: [
        "The human figure is the central subject; ideal proportions express beauty and order.",
        "Contrapposto distributes weight asymmetrically, animating the standing figure.",
        "Progression from Archaic stylization through Classical idealism to Hellenistic emotional expressiveness.",
      ],
      keyThinkers: ["Polykleitos — Canon (lost treatise on ideal proportions)", "J.J. Winckelmann — History of the Art of Antiquity (reception)"],
      principalCritiques: [
        "Winckelmann's 'noble simplicity and quiet grandeur' idealization shaped later reception and obscured the actual polychromy of Greek sculpture.",
        "Surviving works are predominantly marble copies of lost bronzes, raising questions about fidelity to originals.",
      ],
    },
    {
      name: "Roman art",
      description: "Art and architecture of the Roman Republic and Empire, synthesizing Greek, Etruscan, and indigenous traditions.",
      tags: ["visual"],
      tenet: "Adapt Greek aesthetic models to Roman civic purposes — portraiture, triumphal narrative, and architectural spectacle.",
      lineage: { parents: ["Greek / Hellenistic art"], divergence: "absorbed Greek models; added veristic portraiture, historical relief, and monumental engineering" },
      figures: ["Trajan's Column sculptors", "Pompeian fresco painters", "builders of the Pantheon"],
      era: ["ancient"],
      startYear: -500,
      coreTenets: [
        "Veristic portraiture records individual features including age and imperfection, departing from Greek idealization.",
        "Continuous narrative on relief sculpture (e.g., Trajan's Column) documents military campaigns and state events.",
        "Architectural innovation — concrete, arches, vaults, domes — enables monumental interior spaces.",
      ],
      keyThinkers: ["Vitruvius — De Architectura", "Pliny the Elder — Natural History (books on art)"],
      principalCritiques: [
        "Earlier scholarship dismissed Roman art as derivative of Greek originals; revisionist accounts emphasize its distinct contributions.",
        "The 'decline' narrative for late Roman art imports value judgments that obscure intentional stylistic shifts.",
      ],
    },
    {
      name: "Byzantine art",
      description: "Art of the Eastern Roman Empire, centered on icon painting, mosaic, and architectural form in the service of Christian theology.",
      tags: ["visual"],
      tenet: "Make the divine visible through icons, mosaics, and gold-ground compositions governed by theological rather than naturalistic principles.",
      lineage: { parents: ["Roman art"], divergence: "absorbed late Roman forms; shifted from naturalism to hieratic, symbolic representation in service of Christian liturgy" },
      figures: ["Mosaicists of Hagia Sophia", "Ravenna mosaic workshops", "icon painters of Constantinople"],
      era: ["medieval"],
      startYear: 330,
      coreTenets: [
        "Icons are not mere images but participate in the holiness of their prototypes (theology of images).",
        "Gold ground signifies divine light and eternity; spatial depth is deliberately suppressed.",
        "Frontal, hieratic figures with large eyes communicate spiritual presence rather than physical likeness.",
      ],
      keyThinkers: ["John of Damascus — defense of icons", "Second Council of Nicaea (787) — doctrinal basis for image veneration"],
      principalCritiques: [
        "Iconoclasts (726-843) argued image veneration bordered on idolatry; the controversy nearly destroyed the tradition.",
        "Western Renaissance critics regarded Byzantine style as rigid and artistically stagnant, a view now widely reconsidered.",
      ],
    },
    {
      name: "Medieval / Gothic art",
      description: "Art and architecture of Western Europe from the early medieval period through the Gothic, encompassing manuscript illumination, stone sculpture, and stained glass.",
      tags: ["visual"],
      tenet: "Teach scripture and doctrine through visual programs in manuscripts, portals, and stained glass within a vertical, light-filled architectural framework.",
      lineage: { parents: ["Byzantine art"], divergence: "Western Latin tradition; absorbed Byzantine and barbarian motifs; developed pointed-arch Gothic structural system" },
      figures: ["Abbot Suger — Saint-Denis (proto-Gothic)", "Chartres Cathedral sculptors", "Limbourg Brothers — Très Riches Heures"],
      era: ["medieval"],
      startYear: 500,
      coreTenets: [
        "Art serves didactic and devotional purposes: the church building is a 'Bible in stone and glass.'",
        "Gothic architecture uses pointed arches, ribbed vaults, and flying buttresses to maximize window area and interior height.",
        "Manuscript illumination preserves and transmits classical, scriptural, and scientific knowledge.",
      ],
      keyThinkers: ["Abbot Suger — De Administratione (c. 1145)", "Émile Mâle — Religious Art in France"],
      principalCritiques: [
        "The term 'Gothic' was coined pejoratively by Renaissance writers who associated the style with barbarian Goths.",
        "Romanesque art and regional variations resist easy periodization under a single 'medieval' label.",
      ],
    },
    {
      name: "Early Renaissance",
      description: "The revival of classical naturalism and perspective in 15th-century Italy, especially Florence.",
      tags: ["visual"],
      tenet: "Recover and surpass classical models through the rational study of nature, anatomy, and linear perspective.",
      lineage: { parents: ["Medieval / Gothic art", "Greek / Hellenistic art"], divergence: "self-conscious revival of Greco-Roman models; applied mathematical perspective to pictorial space" },
      figures: ["Brunelleschi — perspective demonstration", "Masaccio — Holy Trinity (c. 1427)", "Donatello — David", "Botticelli — Birth of Venus"],
      era: ["c15"],
      startYear: 1400,
      coreTenets: [
        "Linear (one-point) perspective constructs a unified, measurable pictorial space on a flat surface.",
        "Anatomy study enables naturalistic representation of the human body in motion.",
        "Classical antiquity provides models of excellence to be emulated and exceeded.",
      ],
      keyThinkers: ["Leon Battista Alberti — Della Pittura (1435)", "Cennino Cennini — Il Libro dell'Arte"],
      principalCritiques: [
        "The 'rebirth' narrative implies medieval art lacked sophistication, which medievalists contest.",
        "The Florentine focus of standard accounts marginalizes simultaneous developments in Siena, Venice, and Northern Europe.",
      ],
    },
    {
      name: "High Renaissance",
      description: "The culmination of Renaissance naturalism in the works of Leonardo, Michelangelo, and Raphael, c. 1490-1527.",
      tags: ["visual"],
      tenet: "Achieve an ideal synthesis of classical beauty, anatomical mastery, and compositional harmony.",
      lineage: { parents: ["Early Renaissance"], divergence: "perfected perspective, sfumato, and monumental composition; centered in Rome and Florence" },
      figures: ["Leonardo da Vinci — Mona Lisa, Last Supper", "Michelangelo — Sistine Ceiling, David", "Raphael — School of Athens"],
      era: ["c15", "c16"],
      startYear: 1490,
      coreTenets: [
        "Sprezzatura — the appearance of effortless mastery — marks the highest artistic achievement.",
        "Sfumato, chiaroscuro, and aerial perspective create atmospheric depth and psychological subtlety.",
        "The artist is an intellectual creator, not merely a craftsman; disegno (design/drawing) embodies thought.",
      ],
      keyThinkers: ["Giorgio Vasari — Lives of the Artists (1550)", "Leonardo da Vinci — notebooks"],
      principalCritiques: [
        "Vasari's teleological narrative — art progressing toward perfection in Michelangelo — shaped centuries of art-historical hierarchy.",
        "The three canonical masters overshadow contemporaries (Giorgione, Titian, Andrea del Sarto) who pursued different aims.",
      ],
    },
    {
      name: "Northern Renaissance",
      description: "Renaissance art north of the Alps, especially in the Low Countries and Germany, distinguished by oil technique and minute naturalism.",
      tags: ["visual"],
      tenet: "Render the visible world in painstaking optical detail using oil glazes, without relying on Italian mathematical perspective.",
      lineage: { parents: ["Medieval / Gothic art"], divergence: "parallel to Italian Renaissance; oil painting technique and empirical observation rather than geometric perspective" },
      figures: ["Jan van Eyck — Ghent Altarpiece (1432)", "Albrecht Dürer — engravings, self-portraits", "Hieronymus Bosch — Garden of Earthly Delights"],
      era: ["c15", "c16"],
      startYear: 1420,
      coreTenets: [
        "Oil glazing permits luminous color, fine detail, and convincing textures unmatched by tempera or fresco.",
        "Domestic interiors and landscape settings carry symbolic content through 'disguised symbolism.'",
        "Printmaking (woodcut, engraving) disseminates images widely, democratizing visual culture.",
      ],
      keyThinkers: ["Erwin Panofsky — Early Netherlandish Painting", "Albrecht Dürer — theoretical writings on proportion"],
      principalCritiques: [
        "Panofsky's 'disguised symbolism' thesis is debated: some scholars argue not every depicted object carries hidden meaning.",
        "The 'Northern' label subordinates these traditions to an Italocentric narrative of Renaissance art.",
      ],
    },
    {
      name: "Mannerism",
      description: "Post-High-Renaissance style characterized by elongated proportions, spatial ambiguity, and self-conscious artifice, c. 1520-1600.",
      tags: ["visual"],
      tenet: "Pursue expressive distortion, spatial complexity, and stylish artifice beyond the balanced harmony of the High Renaissance.",
      lineage: { parents: ["High Renaissance"], divergence: "reacted against High Renaissance equilibrium; cultivated tension, elongation, and virtuoso complexity" },
      figures: ["Pontormo — Deposition (c. 1528)", "Parmigianino — Madonna with the Long Neck", "El Greco — View of Toledo"],
      era: ["c16"],
      startYear: 1520,
      coreTenets: [
        "Figura serpentinata — the spiraling, elongated figure — expresses grace and spiritual tension.",
        "Spatial ambiguity and compressed picture planes replace the rationalized space of the High Renaissance.",
        "The 'manner' (maniera) of the great masters is a starting point for further invention, not a standard to replicate.",
      ],
      keyThinkers: ["Giorgio Vasari — maniera concept", "John Shearman — Mannerism (1967)"],
      principalCritiques: [
        "The term 'Mannerism' was long pejorative, implying decadence after the High Renaissance; rehabilitation began in the 20th century.",
        "Whether Mannerism is a distinct period style or a transitional phase remains debated among art historians.",
      ],
    },
  ],
};

// ── FAMILY 2 — BAROQUE TO 19TH CENTURY ────────────────────────────────────────

const BAROQUE_TO_19TH: Family = {
  slug: "baroque-to-19th",
  name: "Baroque to 19th Century",
  blurb: "Dramatic naturalism, courtly refinement, and the turn toward realism and emotional intensity.",
  color: "amber",
  entries: [
    {
      name: "Baroque",
      description: "A style of dramatic dynamism, rich color, and emotional intensity dominant in 17th-century Europe.",
      tags: ["visual"],
      tenet: "Create dramatic, emotionally compelling compositions using strong contrasts of light and shadow, dynamic movement, and sensory richness.",
      lineage: { parents: ["Mannerism"], divergence: "replaced Mannerist artifice with dramatic naturalism, theatrical lighting, and Counter-Reformation emotional immediacy" },
      figures: ["Caravaggio — Calling of Saint Matthew", "Peter Paul Rubens — Descent from the Cross", "Rembrandt van Rijn — Night Watch", "Gian Lorenzo Bernini — Ecstasy of Saint Teresa"],
      era: ["c17"],
      startYear: 1600,
      coreTenets: [
        "Tenebrism and chiaroscuro create dramatic contrasts of light and dark that heighten emotional impact.",
        "Compositions employ diagonal movement, foreshortening, and theatrical staging.",
        "Counter-Reformation patronage encouraged art that moved the faithful through sensory and emotional engagement.",
      ],
      keyThinkers: ["Heinrich Wölfflin — Principles of Art History (Baroque vs. Renaissance contrast)"],
      principalCritiques: [
        "The term 'Baroque' was originally pejorative (from Portuguese barroco, an irregular pearl), implying excess.",
        "Regional variations (Italian, Flemish, Spanish, Dutch) are so distinct that a single 'Baroque' label is contested.",
      ],
    },
    {
      name: "Dutch Golden Age",
      description: "Art of the 17th-century Dutch Republic, characterized by genre scenes, landscapes, still life, and bourgeois patronage.",
      tags: ["visual"],
      tenet: "Paint everyday subjects — domestic interiors, landscapes, still lifes — with optical fidelity for a bourgeois market.",
      lineage: { parents: ["Baroque", "Northern Renaissance"], divergence: "Protestant, mercantile context; art for private buyers rather than church or court" },
      figures: ["Johannes Vermeer — Girl with a Pearl Earring", "Frans Hals — group portraits", "Jacob van Ruisdael — landscapes"],
      era: ["c17"],
      startYear: 1615,
      coreTenets: [
        "Specialization by genre (landscape, still life, portraiture, genre scene) serves an open art market.",
        "Meticulous observation of light, texture, and atmospheric effects conveys the visible world.",
        "Vanitas and memento mori themes embed moral reflection in seemingly secular subjects.",
      ],
      keyThinkers: ["Svetlana Alpers — The Art of Describing"],
      principalCritiques: [
        "Whether Dutch genre painting is purely descriptive or laden with moralizing emblematic content remains debated.",
        "The 'Golden Age' label celebrates Dutch prosperity while omitting the colonial and slave-trade economy that funded it.",
      ],
    },
    {
      name: "Rococo",
      description: "An ornamental, light-toned style of the early-to-mid 18th century, centered in France.",
      tags: ["visual"],
      tenet: "Cultivate lightness, pastel color, asymmetrical ornamentation, and scenes of aristocratic pleasure.",
      lineage: { parents: ["Baroque"], divergence: "lightened Baroque grandeur into intimate, decorative elegance for aristocratic interiors" },
      figures: ["Antoine Watteau — Pilgrimage to Cythera", "Jean-Honoré Fragonard — The Swing", "François Boucher"],
      era: ["c18"],
      startYear: 1720,
      coreTenets: [
        "Asymmetry, curvilinear forms, and shell-like (rocaille) motifs define ornamental vocabulary.",
        "Fêtes galantes depict idealized aristocratic leisure in parkland settings.",
        "Pastel tonalities and playful eroticism replace Baroque solemnity.",
      ],
      keyThinkers: ["the Goncourt brothers — rediscovery of Rococo in 19th century"],
      principalCritiques: [
        "Neoclassical critics (Diderot) condemned Rococo as frivolous and morally vacuous.",
        "The style is closely associated with ancien-régime aristocratic culture, complicating its reception after the French Revolution.",
      ],
    },
    {
      name: "Neoclassicism",
      description: "A return to the forms and moral seriousness of Greco-Roman antiquity, dominant c. 1760-1830.",
      tags: ["visual"],
      tenet: "Revive the clarity, order, and moral gravity of ancient Greek and Roman art as a corrective to Rococo frivolity.",
      lineage: { parents: ["Rococo", "Greek / Hellenistic art"], divergence: "reaction against Rococo; inspired by archaeological discoveries at Pompeii and Herculaneum" },
      figures: ["Jacques-Louis David — Oath of the Horatii (1784)", "Antonio Canova — Psyche Revived by Cupid's Kiss", "Jean-Auguste-Dominique Ingres"],
      era: ["c18", "c19"],
      startYear: 1760,
      coreTenets: [
        "Classical subjects — Greco-Roman history, mythology — provide exempla virtutis (models of virtue).",
        "Clear contour, restrained color, and shallow pictorial space emulate relief sculpture.",
        "Art should serve civic and moral purposes, elevating public virtue.",
      ],
      keyThinkers: ["J.J. Winckelmann — Thoughts on the Imitation of Greek Works (1755)", "Anton Raphael Mengs"],
      principalCritiques: [
        "Romantics argued Neoclassicism's rule-bound approach suppressed feeling, imagination, and individual expression.",
        "The movement's association with both revolutionary and imperial regimes (David served Napoleon) complicates its moral claims.",
      ],
    },
    {
      name: "Romanticism (visual art)",
      description: "An emphasis on emotion, imagination, the sublime, and individual genius, flourishing c. 1790-1850.",
      tags: ["visual"],
      tenet: "Prioritize emotion, imagination, and the experience of the sublime over classical rules and rational order.",
      lineage: { parents: ["Neoclassicism"], divergence: "reaction against Neoclassical rationalism; elevated feeling, nature, and the irrational" },
      figures: ["Eugène Delacroix — Liberty Leading the People", "J.M.W. Turner — The Fighting Temeraire", "Caspar David Friedrich — Wanderer above the Sea of Fog", "Francisco Goya"],
      era: ["c18", "c19"],
      startYear: 1790,
      coreTenets: [
        "The sublime — awe, terror, vastness — is a central aesthetic category alongside or above beauty.",
        "The artist is an individual genius whose inner vision transcends academic convention.",
        "Nature, emotion, and the medieval past are sources of authentic experience against industrial modernity.",
      ],
      keyThinkers: ["Edmund Burke — A Philosophical Enquiry into the Sublime and Beautiful", "Charles Baudelaire — art criticism"],
      principalCritiques: [
        "Realists (Courbet) argued Romanticism escaped into fantasy and sentiment rather than confronting social reality.",
        "The cult of individual genius has been criticized for obscuring collaborative studio practices and social conditions of production.",
      ],
    },
    {
      name: "Realism",
      description: "A mid-19th-century movement depicting contemporary life without idealization.",
      tags: ["visual"],
      tenet: "Depict contemporary life and ordinary people as they are, without idealization, mythologizing, or sentimentality.",
      lineage: { parents: ["Romanticism (visual art)"], divergence: "rejected Romantic escape and academic idealism; insisted on observable contemporary subject matter" },
      figures: ["Gustave Courbet — The Stone Breakers (1849)", "Jean-François Millet — The Gleaners", "Honoré Daumier"],
      era: ["c19"],
      startYear: 1848,
      coreTenets: [
        "Painting should show 'things as they are,' including labor, poverty, and unglamorous daily life.",
        "Grand historical and mythological subjects are rejected in favor of the present moment.",
        "The artist's social position and political commitments are inseparable from aesthetic choices.",
      ],
      keyThinkers: ["Gustave Courbet — 'Realist Manifesto' (exhibition preface, 1855)", "Champfleury — essays on Realism"],
      principalCritiques: [
        "Academic critics accused Realism of vulgarity, ugliness, and socialist agitation.",
        "Later critics note that Realist 'objectivity' is itself a constructed stance, not a neutral view.",
      ],
    },
    {
      name: "Pre-Raphaelite Brotherhood",
      description: "A group of English painters (founded 1848) who sought to recover the sincerity and detail of art before Raphael.",
      tags: ["visual"],
      tenet: "Return to the vivid color, minute detail, and spiritual sincerity of art before the High Renaissance.",
      lineage: { parents: ["Romanticism (visual art)", "Medieval / Gothic art"], divergence: "rejected academic convention and Raphael's influence; drew on medieval and early Renaissance models" },
      figures: ["Dante Gabriel Rossetti", "John Everett Millais — Ophelia", "William Holman Hunt — The Light of the World"],
      era: ["c19"],
      startYear: 1848,
      coreTenets: [
        "Intense, jewel-like color and meticulous natural detail achieve truthfulness to nature.",
        "Literary and religious subjects, often drawn from Dante, Shakespeare, and Arthurian legend, carry moral seriousness.",
        "The academic system following Raphael introduced conventionality and artificial 'grand manner' at the expense of sincerity.",
      ],
      keyThinkers: ["John Ruskin — Modern Painters (champion of the PRB)", "William Morris — Arts and Crafts continuation"],
      principalCritiques: [
        "Critics at the time (Charles Dickens) attacked the PRB as archaic and willfully naive.",
        "The movement's medievalism is selective and idealized, projecting Victorian values onto the Middle Ages.",
      ],
    },
    {
      name: "Barbizon school",
      description: "A group of French landscape painters active c. 1830-1870 near the village of Barbizon, emphasizing plein-air observation.",
      tags: ["visual"],
      tenet: "Paint landscape directly from nature, outdoors, with attention to light, atmosphere, and rural life.",
      lineage: { parents: ["Romanticism (visual art)"], divergence: "shifted from Romantic drama to quiet, observed landscape; pioneered plein-air painting" },
      figures: ["Théodore Rousseau", "Charles-François Daubigny", "Jean-François Millet", "Camille Corot"],
      era: ["c19"],
      startYear: 1830,
      coreTenets: [
        "Direct observation of nature, painted outdoors (en plein air), captures transient light and atmosphere.",
        "Landscape is a worthy subject independent of historical or mythological narrative.",
        "Rural life and the French countryside carry authenticity absent from urban and academic art.",
      ],
      keyThinkers: ["the Barbizon painters' collective practice"],
      principalCritiques: [
        "Academic critics dismissed Barbizon landscapes as sketches, lacking the finish of Salon painting.",
        "The school's nostalgic view of rural France idealized a peasantry already being transformed by industrialization.",
      ],
    },
    {
      name: "Academic art / Salon",
      description: "The officially sanctioned art of European academies and annual Salon exhibitions, dominant through the 19th century.",
      tags: ["visual"],
      tenet: "Maintain the hierarchy of genres, the primacy of historical painting, and academic standards of drawing and finish.",
      lineage: { parents: ["Neoclassicism", "High Renaissance"], divergence: "institutional codification of Renaissance and Neoclassical ideals into official pedagogy and exhibition system" },
      figures: ["William-Adolphe Bouguereau", "Jean-Léon Gérôme", "Alexandre Cabanel"],
      era: ["c19"],
      startYear: 1800,
      coreTenets: [
        "The hierarchy of genres ranks history painting above portraiture, genre, landscape, and still life.",
        "Drawing (disegno) is the foundation of art; academic training proceeds from casts to life models.",
        "The annual Salon is the legitimate venue for artistic recognition and career advancement.",
      ],
      keyThinkers: ["French Academy of Fine Arts — institutional rules", "Charles Blanc — Grammaire des arts du dessin"],
      historicalInstances: ["Salon des Refusés (1863) — Napoleon III's exhibition of works rejected by the official Salon"],
      principalCritiques: [
        "Impressionists and avant-garde artists attacked the Salon as conservative, jury-controlled, and hostile to innovation.",
        "Revisionist scholars note that Academic art was technically accomplished and responsive to public taste, not simply reactionary.",
      ],
    },
  ],
};

// ── FAMILY 3 — IMPRESSIONISM TO EARLY MODERNISM ───────────────────────────────

const IMPRESSIONISM_TO_EARLY_MOD: Family = {
  slug: "impressionism-to-early-mod",
  name: "Impressionism to Early Modernism",
  blurb: "From optical revolution in light and color through the formal experiments that launched modern art.",
  color: "blue",
  entries: [
    {
      name: "Impressionism",
      description: "A movement originating in 1870s France that captured transient effects of light and color through broken brushwork and plein-air painting.",
      tags: ["visual"],
      tenet: "Capture the fleeting impression of a moment — its light, atmosphere, and color — through direct observation and broken brushwork.",
      lineage: { parents: ["Barbizon school", "Realism"], divergence: "radicalized plein-air practice; dissolved form into light and color; rejected Salon finish" },
      figures: ["Claude Monet — Impression, Sunrise (1872; exhibited 1874)", "Pierre-Auguste Renoir", "Camille Pissarro", "Edgar Degas", "Berthe Morisot"],
      era: ["c19"],
      startYear: 1874,
      coreTenets: [
        "Light and atmosphere are the true subjects; objects are vehicles for optical sensation.",
        "Broken, visible brushstrokes and pure spectral color applied side by side mix optically in the viewer's eye.",
        "Modern life — cafés, boulevards, leisure — is worthy subject matter equal to academic history painting.",
      ],
      keyThinkers: ["Monet, Renoir, Pissarro — collective exhibition practice (first exhibition April 1874)"],
      historicalInstances: ["Eight Impressionist exhibitions (1874-1886)", "Salon des Refusés (1863) — precursor"],
      principalCritiques: [
        "Academic critics attacked Impressionism as unfinished and lacking drawing, composition, and seriousness.",
        "Post-Impressionists (Cézanne, Seurat) argued Impressionism dissolved structure in pursuit of fleeting sensation.",
      ],
    },
    {
      name: "Post-Impressionism",
      description: "A diverse set of styles that extended and reacted against Impressionism, c. 1886-1905.",
      tags: ["visual"],
      tenet: "Restore structure, symbolic color, and personal expression to painting beyond Impressionism's optical empiricism.",
      lineage: { parents: ["Impressionism"], divergence: "retained Impressionist color but sought to restore form, structure, and subjective expression" },
      figures: ["Paul Cézanne — Mont Sainte-Victoire series", "Vincent van Gogh — Starry Night", "Paul Gauguin — Vision After the Sermon", "Georges Seurat — A Sunday on La Grande Jatte"],
      era: ["c19"],
      startYear: 1886,
      flagged: true,
      coreTenets: [
        "Cézanne: construct solid, enduring compositions by treating nature 'in terms of the cylinder, sphere, and cone.'",
        "Van Gogh: use color expressively to convey inner emotional states, not just optical truth.",
        "Gauguin: pursue symbolic and 'primitive' sources of meaning beyond Western naturalism.",
      ],
      keyThinkers: ["Roger Fry — coined 'Post-Impressionism' (1910 exhibition, Grafton Galleries)"],
      principalCritiques: [
        "The boundary between Impressionism and Post-Impressionism is conventional rather than sharp; Fry's 1910 label grouped very different artists retroactively.",
        "The 'primitivism' attributed to Gauguin raises questions about cultural appropriation and colonial context.",
      ],
    },
    {
      name: "Pointillism / Neo-Impressionism",
      description: "A technique of applying small dots of pure color that blend optically, developed by Seurat and Signac.",
      tags: ["visual"],
      tenet: "Apply color as discrete dots calibrated by optical science so that they fuse in the viewer's eye into luminous tone.",
      lineage: { parents: ["Impressionism"], divergence: "systematized Impressionist color theory using Chevreul's optics; replaced intuitive brushwork with measured dot application" },
      figures: ["Georges Seurat — A Sunday on La Grande Jatte (1886)", "Paul Signac — D'Eugène Delacroix au Néo-Impressionisme"],
      era: ["c19"],
      startYear: 1884,
      coreTenets: [
        "Complementary colors placed in small adjacent dots produce more luminous mixtures than palette mixing.",
        "Michel Eugène Chevreul's law of simultaneous contrast provides the scientific basis for color placement.",
        "Systematic method replaces Impressionist spontaneity with deliberate, repeatable technique.",
      ],
      keyThinkers: ["Georges Seurat — color and line theory", "Paul Signac — D'Eugène Delacroix au Néo-Impressionisme (1899)"],
      principalCritiques: [
        "Critics argued the laborious dot technique sacrificed spontaneity and vitality for pseudo-scientific rigor.",
        "The optical-mixture claim is disputed; at normal viewing distances, dots may remain visible rather than fully fusing.",
      ],
    },
    {
      name: "Symbolism",
      description: "A late-19th-century movement in art and literature privileging suggestion, myth, and inner states over naturalistic depiction.",
      tags: ["visual"],
      tenet: "Evoke ideas, emotions, and spiritual states through symbol, myth, and suggestion rather than direct representation.",
      lineage: { parents: ["Romanticism (visual art)", "Post-Impressionism"], divergence: "turned inward from both Realist observation and Impressionist optics toward dream, myth, and the unconscious" },
      figures: ["Gustave Moreau — The Apparition", "Odilon Redon", "Pierre Puvis de Chavannes", "Fernand Khnopff"],
      era: ["c19"],
      startYear: 1886,
      coreTenets: [
        "Art should suggest rather than describe; the symbol mediates between visible and invisible reality.",
        "Myth, dream, and the occult are primary sources of artistic content.",
        "Mallarmé's dictum: 'To name an object is to destroy three-quarters of the enjoyment of the poem.'",
      ],
      keyThinkers: ["Jean Moréas — Symbolist Manifesto (1886)", "Albert Aurier — art criticism supporting Symbolism"],
      principalCritiques: [
        "Realists and naturalists dismissed Symbolism as escapist mystification.",
        "The movement's boundaries are porous; its overlap with Decadence, Art Nouveau, and Post-Impressionism resists clear definition.",
      ],
    },
    {
      name: "Art Nouveau",
      description: "A decorative style of the 1890s-1910s integrating organic, curvilinear forms across architecture, furniture, and graphic design.",
      tags: ["visual", "architecture"],
      tenet: "Unify the decorative and fine arts through organic, curvilinear forms inspired by natural growth and structure.",
      lineage: { parents: ["Symbolism", "Pre-Raphaelite Brotherhood"], divergence: "applied Symbolist and craft-revival principles to architecture and applied arts; Gesamtkunstwerk ideal" },
      figures: ["Alphonse Mucha — posters", "Hector Guimard — Paris Métro entrances", "Antoni Gaudí — Sagrada Família", "Louis Comfort Tiffany"],
      era: ["c19", "c20"],
      startYear: 1890,
      coreTenets: [
        "The whiplash curve, vegetal ornament, and asymmetrical composition define the visual vocabulary.",
        "No distinction between fine and applied arts: furniture, buildings, and posters share the same aesthetic.",
        "Total environment design (Gesamtkunstwerk) integrates all elements into a unified artistic experience.",
      ],
      keyThinkers: ["Siegfried Bing — opened L'Art Nouveau gallery (1895)", "Victor Horta — architectural innovation"],
      principalCritiques: [
        "Modernists (Adolf Loos, 'Ornament and Crime,' 1908) attacked Art Nouveau's ornament as wasteful and regressive.",
        "The style's labor-intensive handcraft made it accessible mainly to wealthy patrons, contradicting democratic aspirations.",
      ],
    },
    {
      name: "Fauvism",
      description: "A short-lived French movement (c. 1905-1908) using bold, non-naturalistic color and simplified drawing.",
      tags: ["visual"],
      tenet: "Liberate color from descriptive function; use intense, arbitrary hues for expressive and structural purposes.",
      lineage: { parents: ["Post-Impressionism", "Impressionism"], divergence: "radicalized Post-Impressionist color; abandoned local color for expressive chromatic freedom" },
      figures: ["Henri Matisse — Woman with a Hat (1905)", "André Derain — London Bridge", "Maurice de Vlaminck"],
      era: ["c20"],
      startYear: 1905,
      coreTenets: [
        "Color is an autonomous expressive force, independent of the color objects 'really' appear.",
        "Simplified, flattened forms emphasize the painted surface over illusionistic depth.",
        "Spontaneity and directness of execution override Academic finish.",
      ],
      keyThinkers: ["Henri Matisse — 'Notes of a Painter' (1908)"],
      historicalInstances: ["Salon d'Automne (1905) — critic Louis Vauxcelles coined 'les fauves' (the wild beasts)"],
      principalCritiques: [
        "The name 'Fauves' was derisive, implying crude savagery; the artists did not choose it.",
        "Fauvism was brief and loosely organized; members quickly diverged toward Cubism and other directions.",
      ],
    },
    {
      name: "German Expressionism",
      description: "Early-20th-century German movements (Die Brücke, Der Blaue Reiter) prioritizing emotional intensity and inner vision.",
      tags: ["visual"],
      tenet: "Express inner emotional and spiritual states through distorted forms, raw colors, and gestural marks.",
      lineage: { parents: ["Post-Impressionism", "Fauvism", "Symbolism"], divergence: "combined Fauvist color freedom with Northern European angst and woodcut traditions" },
      figures: ["Ernst Ludwig Kirchner — Street, Dresden", "Emil Nolde", "Wassily Kandinsky — Der Blaue Reiter", "Franz Marc — The Tower of Blue Horses"],
      era: ["c20"],
      startYear: 1905,
      coreTenets: [
        "Die Brücke (Dresden, 1905): raw, angular forms and jarring colors convey urban alienation.",
        "Der Blaue Reiter (Munich, 1911): spiritual aspiration, synesthesia, and the move toward abstraction.",
        "The woodcut's coarse, direct quality is integral, not incidental, to the Expressionist aesthetic.",
      ],
      keyThinkers: ["Wassily Kandinsky — On the Spiritual in Art (1911)", "Franz Marc — artistic writings"],
      principalCritiques: [
        "The Nazi regime classified Expressionism as 'Degenerate Art' (Entartete Kunst, 1937 exhibition), persecuting its practitioners.",
        "Critics question whether a single 'Expressionist' label can encompass Die Brücke, Der Blaue Reiter, and Austrian Expressionism.",
      ],
    },
    {
      name: "Cubism",
      description: "A revolution in pictorial representation (c. 1907-1920s) that fragmented objects into geometric facets shown from multiple viewpoints.",
      tags: ["visual"],
      tenet: "Represent objects from multiple simultaneous viewpoints, fracturing three-dimensional form onto a two-dimensional surface.",
      lineage: { parents: ["Post-Impressionism"], divergence: "extended Cézanne's geometric analysis and absorbed African sculpture's formal innovations", contested: true },
      figures: ["Pablo Picasso — Les Demoiselles d'Avignon (1907)", "Georges Braque — Houses at l'Estaque", "Juan Gris", "Fernand Léger"],
      era: ["c20"],
      startYear: 1907,
      coreTenets: [
        "Analytic Cubism (c. 1909-12): objects are fragmented into overlapping facets of muted tone.",
        "Synthetic Cubism (c. 1912-): papier collé and collage reintroduce color, texture, and found materials.",
        "Single-point perspective is abandoned; the picture surface is acknowledged as flat rather than a window.",
      ],
      keyThinkers: ["Daniel-Henry Kahnweiler — The Rise of Cubism", "Albert Gleizes & Jean Metzinger — Du Cubisme (1912)"],
      principalCritiques: [
        "The role of African and Iberian sculpture in Cubism's genesis raises questions about appropriation and acknowledgment.",
        "Whether Picasso or Braque 'invented' Cubism is conventionally shared, but priority debates persist.",
      ],
    },
    {
      name: "Futurism",
      description: "An Italian avant-garde movement (manifesto 20 February 1909) celebrating speed, technology, and violent rupture with the past.",
      tags: ["visual"],
      tenet: "Embrace speed, technology, dynamism, and the destruction of museums and tradition to build a new civilization.",
      lineage: { parents: ["Cubism", "Post-Impressionism"], divergence: "adopted Cubist fragmentation to depict motion and speed; added militant anti-traditionalism" },
      figures: ["Filippo Tommaso Marinetti — Futurist Manifesto (20 Feb 1909)", "Umberto Boccioni — Unique Forms of Continuity in Space", "Giacomo Balla — Dynamism of a Dog on a Leash"],
      era: ["c20"],
      startYear: 1909,
      coreTenets: [
        "Speed, machines, and industrial power are the new sources of beauty.",
        "'We will destroy the museums, libraries, academies of every kind' (Marinetti, 1909).",
        "Simultaneity — showing successive phases of motion in a single image — captures modern dynamism.",
      ],
      keyThinkers: ["F.T. Marinetti — Futurist Manifesto (Le Figaro, 20 Feb 1909)", "Umberto Boccioni — Technical Manifesto of Futurist Painting (1910)"],
      principalCritiques: [
        "Futurism's glorification of war and violence, and Marinetti's later alignment with Fascism, compromises its legacy.",
        "Russian Futurism (Mayakovsky, Khlebnikov) shared the name but diverged significantly in political orientation.",
      ],
    },
  ],
};

// ── FAMILY 4 — AVANT-GARDE & ABSTRACTION ──────────────────────────────────────

const AVANT_GARDE_ABSTRACTION: Family = {
  slug: "avant-garde-abstraction",
  name: "Avant-Garde & Abstraction",
  blurb: "The leap beyond representation — pure form, radical negation, and the unconscious.",
  color: "indigo",
  entries: [
    {
      name: "Kandinsky's abstraction",
      description: "The pioneering move toward non-representational painting, treating color and form as self-sufficient expressive elements.",
      tags: ["visual"],
      tenet: "Color and form express inner spiritual states directly, without needing to depict recognizable objects.",
      lineage: { parents: ["German Expressionism"], divergence: "extended Expressionist inner-vision principle to its logical conclusion: pure non-representation" },
      figures: ["Wassily Kandinsky — Composition VII (1913)", "Kandinsky — First Abstract Watercolor (c. 1910-1913, date disputed)"],
      era: ["c20"],
      startYear: 1910,
      coreTenets: [
        "Color has direct psychological and spiritual effects analogous to musical tones.",
        "The 'inner necessity' of the artist determines form, not external appearances.",
        "Abstraction is not decoration but a higher form of spiritual communication.",
      ],
      keyThinkers: ["Wassily Kandinsky — On the Spiritual in Art (1911)", "Kandinsky — Point and Line to Plane (1926)"],
      principalCritiques: [
        "The dating of Kandinsky's 'first abstract' work is contested; some scholars argue it was backdated.",
        "Hilma af Klint's abstract paintings (from 1906) predate Kandinsky's, complicating the origin narrative.",
      ],
    },
    {
      name: "Suprematism",
      description: "A Russian abstract movement founded by Malevich, reducing painting to pure geometric form.",
      tags: ["visual"],
      tenet: "Achieve the supremacy of pure feeling in art through elementary geometric forms — square, circle, cross — on a white ground.",
      lineage: { parents: ["Cubism", "Futurism"], divergence: "pushed Cubist abstraction to its endpoint: pure geometry freed from all representation" },
      figures: ["Kazimir Malevich — Black Square (1915)", "Malevich — White on White (1918)"],
      era: ["c20"],
      startYear: 1915,
      coreTenets: [
        "The black square on a white ground is the zero degree of painting — pure relation of form and non-form.",
        "Art must free itself from the 'dead weight of the real world' to access pure feeling.",
        "Geometric forms — square, circle, cross — are the fundamental vocabulary of non-objective art.",
      ],
      keyThinkers: ["Kazimir Malevich — The Non-Objective World (1927)"],
      principalCritiques: [
        "Soviet authorities eventually suppressed Suprematism as bourgeois formalism incompatible with Socialist Realism.",
        "Critics argue Suprematism's reduction to geometry evacuates art of communicable content.",
      ],
    },
    {
      name: "Constructivism",
      description: "A Russian movement applying abstract art to industrial design, architecture, and social transformation.",
      tags: ["visual", "architecture"],
      tenet: "Art should construct rather than depict — build useful objects and environments using industrial materials and abstract form.",
      lineage: { parents: ["Suprematism", "Cubism"], divergence: "shifted from Suprematist pure aesthetics to utilitarian production and social engineering" },
      figures: ["Vladimir Tatlin — Monument to the Third International (1919-20)", "Alexander Rodchenko — photomontage", "El Lissitzky — Prouns"],
      era: ["c20"],
      startYear: 1919,
      coreTenets: [
        "The artist is a constructor (konstruktor), not a creator of autonomous aesthetic objects.",
        "Industrial materials — steel, glass, plywood — replace traditional fine-art media.",
        "Art merges with production: graphic design, architecture, theatre, and textiles are equal fields.",
      ],
      keyThinkers: ["Vladimir Tatlin — productivism", "Aleksei Gan — Constructivism (1922 manifesto)"],
      principalCritiques: [
        "Tatlin's Monument was never built; Constructivism's utopian ambitions often exceeded available resources and political will.",
        "By the late 1920s the Soviet state favored Socialist Realism and marginalized Constructivist experimentation.",
      ],
    },
    {
      name: "De Stijl / Neoplasticism",
      description: "A Dutch movement (1917-1931) reducing art to horizontal and vertical lines and primary colors.",
      tags: ["visual", "architecture"],
      tenet: "Achieve universal harmony by reducing art to straight lines, right angles, and primary colors plus black, white, and grey.",
      lineage: { parents: ["Cubism"], divergence: "distilled Cubist geometry into a purist vocabulary of orthogonals and primaries" },
      figures: ["Piet Mondrian — Composition with Red, Blue, and Yellow", "Theo van Doesburg — De Stijl journal", "Gerrit Rietveld — Schröder House"],
      era: ["c20"],
      startYear: 1917,
      coreTenets: [
        "Horizontal and vertical lines in dynamic equilibrium express universal, objective relationships.",
        "Only primary colors (red, blue, yellow) plus non-colors (black, white, grey) achieve pure plastic expression.",
        "Art, architecture, and design should share the same abstract vocabulary, creating a total environment.",
      ],
      keyThinkers: ["Piet Mondrian — 'Neoplasticism in Painting' (1917-18)", "Theo van Doesburg — De Stijl manifesto"],
      principalCritiques: [
        "Van Doesburg's introduction of the diagonal line (Elementarism, 1924) split the group; Mondrian left in protest.",
        "Critics argue Neoplasticism's extreme reduction limits its applicability and emotional range.",
      ],
    },
    {
      name: "Dada",
      description: "An anti-art movement born during World War I that used absurdity, chance, and provocation to attack bourgeois culture.",
      tags: ["visual"],
      tenet: "Negate conventional art, logic, and bourgeois values through absurdity, chance, and provocative anti-art gestures.",
      lineage: { parents: [], divergence: "root — arose from disgust at World War I; rejection of all prevailing artistic and rational systems" },
      figures: ["Marcel Duchamp — Fountain (1917), readymades", "Hugo Ball — sound poetry at Cabaret Voltaire (5 Feb 1916)", "Hannah Höch — photomontage", "Tristan Tzara"],
      era: ["c20"],
      startYear: 1916,
      coreTenets: [
        "The readymade (Duchamp) challenges the assumption that art requires craft or aesthetic intention.",
        "Chance operations, nonsense, and provocation disrupt rational and aesthetic conventions.",
        "'Dada is anti-Dada' — the movement negates even its own positions.",
      ],
      keyThinkers: ["Tristan Tzara — Dada Manifesto (1918)", "Hugo Ball — diary, Flight Out of Time"],
      historicalInstances: ["Cabaret Voltaire, Zurich (opened 5 Feb 1916)", "Berlin Dada (political photomontage)", "New York Dada (Duchamp, Man Ray)"],
      principalCritiques: [
        "If Dada negates everything including itself, it is unclear what positive contribution it makes.",
        "Dada's anti-art gestures have been absorbed into the art market and institutional canon, arguably neutralizing them.",
      ],
    },
    {
      name: "Surrealism",
      description: "A movement founded by André Breton in 1924, exploring dreams, the unconscious, and automatic processes.",
      tags: ["visual"],
      tenet: "Access the unconscious mind through automatism, dreams, and chance to liberate imagination from rational control.",
      lineage: { parents: ["Dada"], divergence: "channeled Dada's negation into a positive program drawing on Freudian psychoanalysis and automatic techniques" },
      figures: ["André Breton — Surrealist Manifesto (1924)", "Salvador Dalí — The Persistence of Memory", "René Magritte — The Treachery of Images", "Max Ernst — frottage, collage"],
      era: ["c20"],
      startYear: 1924,
      coreTenets: [
        "Psychic automatism — writing or drawing without conscious control — reveals the unconscious.",
        "Dreams are a primary source of imagery; the 'marvellous' disrupts rational categories.",
        "Surrealism is not merely an art movement but a revolutionary project for transforming life.",
      ],
      keyThinkers: ["André Breton — Manifesto of Surrealism (1924)", "Sigmund Freud — The Interpretation of Dreams (theoretical source)"],
      principalCritiques: [
        "Breton's authoritarian leadership and serial expulsions of members contradicted the movement's libertarian claims.",
        "Feminist critics note Surrealism's frequent treatment of women as muse-objects of male desire.",
      ],
    },
    {
      name: "Metaphysical painting",
      description: "An Italian style (pittura metafisica) using illogical perspectives and uncanny juxtapositions to evoke mystery.",
      tags: ["visual"],
      tenet: "Depict enigmatic, silent spaces with classical architecture and irrational juxtapositions to evoke metaphysical disquiet.",
      lineage: { parents: ["Symbolism"], divergence: "combined classical settings with dreamlike incongruity; directly influenced Surrealism" },
      figures: ["Giorgio de Chirico — The Enigma of the Hour, The Song of Love", "Carlo Carrà"],
      era: ["c20"],
      startYear: 1911,
      coreTenets: [
        "Deserted piazzas, long shadows, and dislocated perspectives create an atmosphere of enigma and waiting.",
        "Classical architecture and mannequin figures stand in for human presence, estranged from meaning.",
        "The 'metaphysical' quality lies in showing 'what does not let itself be seen' beneath ordinary surfaces.",
      ],
      keyThinkers: ["Giorgio de Chirico — essays on metaphysical art"],
      principalCritiques: [
        "De Chirico's later repudiation of his early work and turn to academic classicism puzzled admirers and critics alike.",
        "The movement was brief and limited in membership; its influence was felt mainly through its absorption into Surrealism.",
      ],
    },
    {
      name: "Precisionism",
      description: "An American style of the 1920s-30s depicting industrial and architectural subjects with sharp-edged, simplified geometry.",
      tags: ["visual"],
      tenet: "Render American industrial and architectural subjects with crisp geometry, clean edges, and smooth surfaces.",
      lineage: { parents: ["Cubism", "Futurism"], divergence: "American adaptation; applied Cubist geometry to specifically American industrial subjects without Futurist rhetoric" },
      figures: ["Charles Sheeler — American Landscape", "Charles Demuth — The Figure 5 in Gold", "Georgia O'Keeffe — cityscapes"],
      era: ["c20"],
      startYear: 1920,
      coreTenets: [
        "Factories, grain elevators, bridges, and skyscrapers are subjects of modern American beauty.",
        "Hard edges, flat planes, and suppressed brushwork emphasize structural clarity.",
        "Neither celebratory nor critical — observation of the built environment without explicit social commentary.",
      ],
      keyThinkers: ["Charles Sheeler — photographic and painted studies of Ford's River Rouge plant"],
      principalCritiques: [
        "Social Realists criticized Precisionism's depopulated factories as an aestheticization that ignored labor conditions.",
        "The movement's ambiguous stance toward industrialism — neither protest nor propaganda — resists ideological classification.",
      ],
    },
    {
      name: "Harlem Renaissance (visual art)",
      description: "African-American artistic and intellectual flourishing in 1920s-30s Harlem, integrating African heritage with modernist form.",
      tags: ["visual"],
      tenet: "Forge a distinctly African-American visual art that integrates African heritage, modern form, and the lived experience of Black America.",
      lineage: { parents: ["Post-Impressionism", "Cubism"], divergence: "combined modernist formal innovations with African diasporic identity and social themes" },
      figures: ["Aaron Douglas — Aspects of Negro Life murals", "Augusta Savage — sculpture", "Palmer Hayden", "Archibald Motley Jr."],
      era: ["c20"],
      startYear: 1920,
      coreTenets: [
        "African aesthetic traditions — pattern, silhouette, rhythm — are valid sources for modern art.",
        "The 'New Negro' asserts cultural self-definition against stereotypes and minstrelsy.",
        "Art addresses migration, urbanization, jazz culture, and racial injustice as defining African-American experiences.",
      ],
      keyThinkers: ["Alain Locke — The New Negro (1925)", "W.E.B. Du Bois — arts advocacy"],
      principalCritiques: [
        "Debates within the movement: Locke urged 'racial art' rooted in African heritage; others (Schuyler) resisted racial prescriptions for art.",
        "The 'Renaissance' label implies a bounded period, but Black artistic production continued and evolved well beyond the 1930s.",
      ],
    },
  ],
};

// ── FAMILY 5 — POSTWAR & CONTEMPORARY ──────────────────────────────────────────

const POSTWAR_CONTEMPORARY: Family = {
  slug: "postwar-contemporary",
  name: "Postwar & Contemporary",
  blurb: "From Abstract Expressionism through Pop, Minimalism, and the pluralism of the contemporary art world.",
  color: "purple",
  entries: [
    {
      name: "Abstract Expressionism",
      description: "A mid-20th-century American movement emphasizing large-scale gestural or color-field abstraction.",
      tags: ["visual"],
      tenet: "Create large-scale abstract paintings that express existential intensity through gesture, scale, and the physical act of painting.",
      lineage: { parents: ["Surrealism", "Kandinsky's abstraction"], divergence: "absorbed Surrealist automatism and European abstraction; scaled up and relocated art's center to New York" },
      figures: ["Jackson Pollock — drip paintings (Number 1A, 1948)", "Mark Rothko — color-field canvases", "Willem de Kooning — Woman series", "Franz Kline"],
      era: ["c20"],
      startYear: 1943,
      coreTenets: [
        "The canvas is an arena for action (Harold Rosenberg) or a field for contemplation (Rothko).",
        "Monumental scale creates an immersive environment that envelops the viewer.",
        "The act of painting itself — gesture, drip, pour — is the content, not a depiction of something else.",
      ],
      keyThinkers: ["Clement Greenberg — 'Avant-Garde and Kitsch' (1939), advocacy of Color Field", "Harold Rosenberg — 'The American Action Painters' (1952)"],
      principalCritiques: [
        "Revisionist historians note the CIA covertly promoted Abstract Expressionism during the Cold War as evidence of American cultural freedom.",
        "Feminist art historians (Griselda Pollock) argue the movement's heroic-male-genius narrative systematically excluded women and artists of color.",
      ],
    },
    {
      name: "Color Field painting",
      description: "A branch of Abstract Expressionism using large areas of flat color to create immersive optical experiences.",
      tags: ["visual"],
      tenet: "Fill the canvas with expansive, saturated fields of color that create a contemplative, enveloping visual experience.",
      lineage: { parents: ["Abstract Expressionism"], divergence: "Greenberg's preferred strain; foregrounded color and flatness over gestural action" },
      figures: ["Mark Rothko — multiform paintings", "Barnett Newman — Vir Heroicus Sublimis", "Clyfford Still", "Helen Frankenthaler — soak-stain technique", "Morris Louis"],
      era: ["c20"],
      startYear: 1950,
      coreTenets: [
        "Color, not gesture, is the primary expressive vehicle.",
        "Staining thinned paint into raw canvas (Frankenthaler) fuses pigment with surface, eliminating figure-ground distinction.",
        "Large, uninterrupted chromatic fields induce contemplative or sublime states in the viewer.",
      ],
      keyThinkers: ["Clement Greenberg — 'American-Type Painting' (1955)"],
      principalCritiques: [
        "Pop and Minimalist artists rejected Color Field's elevated spiritual claims as pretentious and elitist.",
        "Greenberg's critical authority over the movement raised concerns about a single critic functioning as gatekeeper.",
      ],
    },
    {
      name: "Pop art",
      description: "A movement of the 1950s-60s incorporating imagery from advertising, comics, and mass culture.",
      tags: ["visual"],
      tenet: "Appropriate imagery from advertising, consumer products, and mass media, collapsing the boundary between high art and popular culture.",
      lineage: { parents: ["Abstract Expressionism", "Dada"], divergence: "reaction against AbEx interiority; reintroduced representation using commercial imagery and techniques" },
      figures: ["Andy Warhol — Campbell's Soup Cans, Marilyn Diptych", "Roy Lichtenstein — comic-derived paintings", "Richard Hamilton — collage", "Claes Oldenburg"],
      era: ["c20"],
      startYear: 1956,
      coreTenets: [
        "Mass-produced images — advertisements, product packaging, celebrities — are legitimate artistic subject matter.",
        "Mechanical reproduction techniques (silkscreen, Ben-Day dots) challenge the cult of the handmade.",
        "The distinction between 'high' and 'low' culture is an artificial hierarchy.",
      ],
      keyThinkers: ["Lawrence Alloway — coined 'Pop Art'", "Richard Hamilton — 'Just what is it that makes today's homes so different, so appealing?' (1956)"],
      principalCritiques: [
        "Critics debate whether Pop art critiques consumer culture or merely celebrates and reproduces it.",
        "Greenberg dismissed Pop as a capitulation to kitsch; others see it as a democratic expansion of art's vocabulary.",
      ],
    },
    {
      name: "Minimalism (visual art)",
      description: "A movement of the 1960s reducing sculpture and painting to elemental geometric forms and industrial materials.",
      tags: ["visual"],
      tenet: "Reduce art to its essential physical properties — shape, surface, material — eliminating representation, metaphor, and compositional hierarchy.",
      lineage: { parents: ["Abstract Expressionism", "De Stijl / Neoplasticism"], divergence: "stripped away AbEx's emotive gesture and Constructivist social mission; art as literal object" },
      figures: ["Donald Judd — 'specific objects'", "Dan Flavin — fluorescent-light installations", "Carl Andre — floor sculptures", "Frank Stella — Black Paintings", "Agnes Martin"],
      era: ["c20"],
      startYear: 1960,
      coreTenets: [
        "'What you see is what you see' (Stella) — no hidden content or symbolism.",
        "Industrial fabrication and standardized materials (plywood, steel, fluorescent tubes) replace the artist's hand.",
        "Serial repetition and modular composition eliminate hierarchical arrangement.",
      ],
      keyThinkers: ["Donald Judd — 'Specific Objects' (1965)", "Robert Morris — 'Notes on Sculpture' (1966)"],
      principalCritiques: [
        "Michael Fried attacked Minimalism as 'theatrical' — dependent on the viewer's spatial experience rather than self-contained ('Art and Objecthood,' 1967).",
        "Critics argue Minimalism's claim to eliminate content is itself a content claim.",
      ],
    },
    {
      name: "Conceptual art",
      description: "Art in which the idea or concept takes precedence over traditional aesthetic and material concerns.",
      tags: ["visual"],
      tenet: "The idea behind the work is more important than the finished object; art can consist of language, instructions, or documentation.",
      lineage: { parents: ["Dada", "Minimalism (visual art)"], divergence: "extended Duchamp's readymade logic and Minimalism's dematerialization toward language and concept" },
      figures: ["Sol LeWitt — wall drawings and instructions", "Joseph Kosuth — One and Three Chairs", "Yoko Ono — instruction pieces", "Lawrence Weiner"],
      era: ["c20"],
      startYear: 1966,
      coreTenets: [
        "'The idea becomes a machine that makes the art' (LeWitt, 1967).",
        "Art need not be a physical object; documentation, propositions, and instructions can constitute the work.",
        "The dematerialization of the art object challenges commodification and market logic.",
      ],
      keyThinkers: ["Sol LeWitt — 'Paragraphs on Conceptual Art' (1967)", "Joseph Kosuth — 'Art After Philosophy' (1969)", "Lucy Lippard — Six Years (documenting dematerialization)"],
      principalCritiques: [
        "Despite anti-commodity intentions, conceptual works are collected and sold, often at high prices, through certificates and documentation.",
        "Accusations of elitism: if art is 'just ideas,' it risks becoming accessible only to those trained in art theory.",
      ],
    },
    {
      name: "Art Informel / Tachisme",
      description: "European abstract painting of the 1940s-50s emphasizing spontaneous gesture and material texture.",
      tags: ["visual"],
      tenet: "Create through spontaneous, gestural mark-making and direct material manipulation without preconceived form.",
      lineage: { parents: ["Surrealism"], divergence: "European parallel to Abstract Expressionism; emphasized informality and matière (material quality)" },
      figures: ["Jean Dubuffet — Art Brut", "Jean Fautrier — Otages series", "Pierre Soulages — outrenoir", "Antoni Tàpies — mixed media"],
      era: ["c20"],
      startYear: 1945,
      coreTenets: [
        "Art informel ('unformed art') rejects geometric abstraction in favor of amorphous, organic form.",
        "Matière — the physical texture and substance of paint — becomes primary content.",
        "Spontaneity and improvisation reflect existentialist emphasis on authenticity and being-in-the-world.",
      ],
      keyThinkers: ["Michel Tapié — Art Autre (1952)", "Jean Dubuffet — anti-cultural position"],
      principalCritiques: [
        "Art Informel is sometimes seen as the European counterpart to Abstract Expressionism, raising questions about parallel development versus transatlantic influence.",
        "The movement's rejection of all formal discipline was criticized as potentially arbitrary.",
      ],
    },
    {
      name: "Op art",
      description: "Art of the 1960s using geometric patterns to create optical effects — motion, vibration, and visual instability.",
      tags: ["visual"],
      tenet: "Construct precise geometric patterns that activate optical phenomena — apparent motion, moiré, afterimage — in the viewer's perception.",
      lineage: { parents: ["Constructivism", "De Stijl / Neoplasticism"], divergence: "applied Constructivist geometry to perceptual psychology; art as retinal experiment" },
      figures: ["Bridget Riley — Fall, Movement in Squares", "Victor Vasarely — Zebra", "Carlos Cruz-Diez"],
      era: ["c20"],
      startYear: 1964,
      coreTenets: [
        "Precise geometric patterns trigger involuntary optical effects: vibration, afterimages, apparent depth and motion.",
        "The artwork is completed by the viewer's perceptual apparatus, not by the artist's hand alone.",
        "Black-and-white contrast and high-chroma color interactions are primary tools.",
      ],
      keyThinkers: ["Victor Vasarely — Yellow Manifesto (1955)"],
      historicalInstances: ["'The Responsive Eye' exhibition, MoMA (1965)"],
      principalCritiques: [
        "Critics dismissed Op art as gimmicky and decorative, lacking intellectual or emotional depth.",
        "Its rapid commercial application in fashion and design blurred the line between fine art and surface decoration.",
      ],
    },
    {
      name: "Performance & body art",
      description: "Art forms using the artist's body and live action as the primary medium.",
      tags: ["visual"],
      tenet: "Use the artist's body and live presence as the primary medium, making art inseparable from lived experience and time.",
      lineage: { parents: ["Dada", "Conceptual art"], divergence: "extended Dadaist action and conceptual dematerialization to the body itself as artistic medium" },
      figures: ["Marina Abramović — The Artist Is Present", "Yves Klein — Anthropométries", "Carolee Schneemann — Interior Scroll", "Chris Burden — Shoot"],
      era: ["c20"],
      startYear: 1960,
      coreTenets: [
        "The body is simultaneously subject, object, and medium of the work.",
        "Liveness and temporal unrepeatability challenge art's commodity status.",
        "Endurance, pain, vulnerability, and audience interaction test the limits of art and life.",
      ],
      keyThinkers: ["RoseLee Goldberg — Performance Art: From Futurism to the Present"],
      principalCritiques: [
        "Documentation (photographs, video) becomes the collectible artifact, arguably re-commodifying what was meant to resist the market.",
        "Ethical questions arise when performances involve pain, risk, or nonconsenting audience members.",
      ],
    },
    {
      name: "Land art / Earthworks",
      description: "Art made with and in the natural landscape, often at monumental scale in remote locations.",
      tags: ["visual"],
      tenet: "Use the earth itself — soil, rock, water, weather — as both material and site, making art that exists outside galleries.",
      lineage: { parents: ["Minimalism (visual art)", "Conceptual art"], divergence: "extended Minimalist materials and scale into the landscape; escaped the gallery system" },
      figures: ["Robert Smithson — Spiral Jetty (1970, Great Salt Lake)", "Michael Heizer — Double Negative", "Walter De Maria — The Lightning Field", "Andy Goldsworthy"],
      era: ["c20"],
      startYear: 1968,
      coreTenets: [
        "The work is inseparable from its site; it cannot be moved to a museum without destruction.",
        "Geological time, entropy, and natural processes are integral to the work's meaning and evolution.",
        "Monumental scale and remote locations challenge art-world conventions of accessibility and commerce.",
      ],
      keyThinkers: ["Robert Smithson — 'A Sedimentation of the Mind: Earth Projects' (1968)"],
      principalCritiques: [
        "Environmental critics note that Earthworks sometimes cause significant landscape disruption.",
        "Despite anti-commercial intentions, Land art is documented, collected, and sold through photographs and drawings.",
      ],
    },
    {
      name: "Photorealism",
      description: "A painting movement of the late 1960s-70s replicating photographs with trompe-l'oeil precision.",
      tags: ["visual"],
      tenet: "Reproduce photographic images on canvas with meticulous, hand-painted precision that rivals or exceeds the source photograph.",
      lineage: { parents: ["Pop art", "Realism"], divergence: "combined Pop's engagement with mass imagery with extreme technical replication of photographs" },
      figures: ["Chuck Close — large-scale portraits", "Richard Estes — urban reflections", "Ralph Goings — diners and trucks"],
      era: ["c20"],
      startYear: 1968,
      coreTenets: [
        "The photograph, not the scene, is the subject: depth of field, lens distortion, and reflections are faithfully reproduced.",
        "The tension between painted surface and photographic illusion is central to the viewer's experience.",
        "Subject matter is deliberately banal — diners, cars, storefronts — shifting attention to the act of seeing.",
      ],
      keyThinkers: ["Louis K. Meisel — Photorealism (coined the term, 1969)"],
      principalCritiques: [
        "Critics questioned whether reproducing photographs constitutes creative originality or technical virtuosity without conceptual depth.",
        "Conceptual artists dismissed Photorealism as retrograde in an era of dematerialized art.",
      ],
    },
    {
      name: "Neo-Expressionism",
      description: "A return to figurative, gestural painting in the late 1970s and 1980s, reacting against Minimalism and Conceptualism.",
      tags: ["visual"],
      tenet: "Return to large-scale figurative and gestural painting with raw emotional intensity, reacting against the austerity of Minimalism and Conceptualism.",
      lineage: { parents: ["Abstract Expressionism", "German Expressionism"], divergence: "revived expressionist figuration after a decade of Minimalist and Conceptualist dominance" },
      figures: ["Jean-Michel Basquiat — graffiti-derived paintings", "Anselm Kiefer — German history paintings", "Georg Baselitz — inverted figures", "Julian Schnabel"],
      era: ["c20"],
      startYear: 1978,
      coreTenets: [
        "Figuration, narrative, and emotional intensity are reclaimed against Minimalist and Conceptualist restraint.",
        "Raw, aggressive paint handling and large scale convey existential urgency.",
        "History, mythology, and personal biography return as legitimate artistic content.",
      ],
      keyThinkers: ["Achille Bonito Oliva — Transavantgarde (Italian variant)", "Benjamin Buchloh — critical responses"],
      principalCritiques: [
        "Critics (Buchloh, Foster) accused Neo-Expressionism of being a market-driven regression to outmoded heroic-painter myths.",
        "The movement's rapid commercial success raised questions about whether transgression is possible within a booming art market.",
      ],
    },
    {
      name: "Postmodern / contemporary art",
      description: "A pluralistic field since the 1980s characterized by appropriation, identity politics, institutional critique, and media pluralism.",
      tags: ["visual"],
      tenet: "No single style or medium defines art; appropriation, critique of institutions, identity, and media hybridity coexist.",
      lineage: { parents: ["Conceptual art", "Pop art"], divergence: "post-medium condition: pluralism of styles, media, and critical positions replaces linear avant-garde progression" },
      figures: ["Cindy Sherman — Untitled Film Stills", "Jeff Koons — Balloon Dog", "Ai Weiwei — Sunflower Seeds", "Kara Walker — silhouettes"],
      era: ["c20", "c21"],
      startYear: 1980,
      broadFamily: true,
      coreTenets: [
        "Appropriation — reusing existing images and objects — questions originality and authorship.",
        "Institutional critique examines how museums, galleries, and markets construct meaning and value.",
        "Identity (race, gender, sexuality, postcolonialism) is a primary site of artistic inquiry.",
      ],
      keyThinkers: ["Rosalind Krauss — 'Sculpture in the Expanded Field' (1979)", "Arthur Danto — 'The End of Art' thesis", "Hal Foster — The Anti-Aesthetic (1983)"],
      principalCritiques: [
        "If anything can be art and no criteria distinguish quality, the field risks incoherence.",
        "The global art market's influence on production and reception raises concerns about co-optation of critical practice.",
      ],
    },
    {
      name: "Street art",
      description: "Art made in public spaces — murals, stencils, wheat-paste, and graffiti-derived forms — outside institutional sanction.",
      tags: ["visual"],
      tenet: "Create art in public space, accessible to everyone, outside the gallery and museum system.",
      lineage: { parents: ["Pop art", "Dada"], divergence: "relocated art-making to the street; combined graffiti traditions with Pop imagery and political statement" },
      figures: ["Banksy — stencil works", "Jean-Michel Basquiat — SAMO graffiti (early career)", "Shepard Fairey — Obey", "Keith Haring — subway drawings"],
      era: ["c20", "c21"],
      startYear: 1970,
      coreTenets: [
        "Public walls and infrastructure are legitimate sites for art, accessible without entry fees or gatekeepers.",
        "Anonymity or pseudonymity challenges the art world's emphasis on named authorship and biography.",
        "Political commentary, social critique, and humor are central motivations.",
      ],
      keyThinkers: ["the street art tradition operates largely outside academic theory"],
      principalCritiques: [
        "Property owners and municipalities classify unauthorized street art as vandalism subject to legal penalties.",
        "Commercial success (Banksy auctions, brand collaborations) arguably compromises street art's outsider status.",
      ],
    },
  ],
};

export const FAMILIES: Family[] = [
  ANCIENT_TO_RENAISSANCE,
  BAROQUE_TO_19TH,
  IMPRESSIONISM_TO_EARLY_MOD,
  AVANT_GARDE_ABSTRACTION,
  POSTWAR_CONTEMPORARY,
];
