import type { Family } from "./types";

export const FAMILIES_1_6: Family[] = [
  // ── Family 1 ──────────────────────────────────────────────────────────────
  {
    slug: "pharmacokinetics-adme",
    number: 1,
    name: "Pharmacokinetics: Absorption, Distribution, Metabolism, Excretion",
    blurb: "What the body does to the drug — the quantitative core: how much reaches the circulation, where it goes, how it is transformed, and how it is cleared.",
    section: "A",
    color: "violet",
    dataSource: "ChEBI / PubChem physicochemical properties; primary PK literature.",
    entries: [
      {
        name: "Pharmacokinetics (scope)",
        description: "What the body does to a drug over time.",
        kind: "concept",
        className: "PK concept",
        formula: "The study of absorption, distribution, metabolism, and excretion (ADME); concentration as a function of time, $C(t)$.",
        example: "The plasma concentration-time curve.",
        tags: ["PK", "foundations"],
      },
      {
        name: "Absorption & bioavailability",
        description: "How much drug reaches the circulation, and how fast.",
        kind: "concept",
        className: "PK parameter",
        formula: "Bioavailability $F = \\dfrac{AUC_{\\text{oral}}/\\text{Dose}_{\\text{oral}}}{AUC_{\\text{IV}}/\\text{Dose}_{\\text{IV}}}$; $F=1$ for IV by definition.",
        example: "First-pass metabolism lowers oral $F$.",
        tags: ["PK", "absorption"],
      },
      {
        name: "First-pass (presystemic) metabolism",
        description: "Loss before reaching systemic circulation.",
        kind: "concept",
        className: "PK concept",
        formula: "Fraction escaping hepatic extraction $F_H = 1 - E_H$, where $E_H$ is the hepatic extraction ratio.",
        example: "Why oral nitroglycerin is ineffective but sublingual works.",
        tags: ["PK"],
      },
      {
        name: "Volume of distribution (Vd)",
        description: "The apparent volume a drug occupies.",
        kind: "concept",
        className: "PK parameter",
        formula: "$V_d = \\dfrac{\\text{Amount in body}}{C_{\\text{plasma}}}$; large $V_d$ means extensive tissue binding.",
        example: "Highly lipophilic drugs have $V_d \\gg$ total body water.",
        tags: ["PK", "distribution"],
      },
      {
        name: "Plasma protein binding",
        description: "Bound vs free drug.",
        kind: "concept",
        className: "PK concept",
        formula: "Only the unbound fraction $f_u$ is pharmacologically active and cleared; $f_u = C_{\\text{free}}/C_{\\text{total}}$.",
        example: "Warfarin is about 99% albumin-bound.",
        tags: ["PK", "distribution"],
      },
      {
        name: "Clearance (CL)",
        description: "The volume of plasma cleared of drug per unit time.",
        kind: "concept",
        className: "PK parameter",
        formula: "$CL = \\dfrac{\\text{Dose}}{AUC}$; total $CL = CL_{\\text{hepatic}} + CL_{\\text{renal}} + \\ldots$",
        example: "Sets the maintenance dose rate.",
        tags: ["PK", "elimination"],
      },
      {
        name: "Elimination half-life (t1/2)",
        description: "Time for concentration to fall by half.",
        kind: "concept",
        className: "PK parameter",
        formula: "$t_{1/2} = \\dfrac{0.693\\,V_d}{CL} = \\dfrac{\\ln 2}{k_e}$.",
        example: "About 4-5 half-lives to reach steady state or to eliminate a drug.",
        tags: ["PK", "elimination"],
      },
      {
        name: "First-order vs zero-order kinetics",
        description: "Concentration-dependent vs saturated elimination.",
        kind: "concept",
        className: "PK concept",
        formula: "First-order $\\dfrac{dC}{dt} = -k_e C$ (constant fraction); zero-order $\\dfrac{dC}{dt} = -k_0$ (constant amount).",
        example: "Ethanol and phenytoin show zero-order (saturable) kinetics.",
        tags: ["PK"],
        xref: ["mathematics"],
      },
      {
        name: "Compartmental models",
        description: "Idealizing the body as kinetic compartments.",
        kind: "concept",
        className: "PK model",
        formula: "One-compartment $C(t) = C_0 e^{-k_e t}$; two-compartment adds a distribution phase.",
        example: "Fits the biexponential decline of many IV drugs.",
        tags: ["PK", "models"],
        xref: ["mathematics"],
      },
      {
        name: "Area under the curve (AUC)",
        description: "Total drug exposure.",
        kind: "concept",
        className: "PK parameter",
        formula: "$AUC = \\int_0^\\infty C(t)\\,dt$; proportional to dose in linear PK.",
        example: "The basis of bioequivalence testing.",
        tags: ["PK"],
      },
      {
        name: "Steady state & accumulation",
        description: "Repeated dosing plateau.",
        kind: "concept",
        className: "PK concept",
        formula: "Reached in ~4-5 half-lives; $C_{ss,\\text{avg}} = \\dfrac{F \\cdot \\text{Dose}}{CL \\cdot \\tau}$ for dosing interval $\\tau$.",
        example: "Why loading doses shorten time to effect.",
        tags: ["PK"],
      },
      {
        name: "Loading & maintenance dose",
        description: "Filling the volume vs matching clearance.",
        kind: "concept",
        className: "PK concept",
        formula: "Loading dose $= V_d \\cdot C_{\\text{target}}/F$; maintenance rate $= CL \\cdot C_{ss}/F$.",
        example: "Digoxin and amiodarone are loaded to reach effect faster.",
        tags: ["PK"],
      },
      {
        name: "Metabolism — Phase I & Phase II",
        description: "Functionalization then conjugation.",
        kind: "concept",
        className: "PK concept",
        formula: "Phase I (oxidation/reduction/hydrolysis, largely CYP450) adds or exposes a functional group; Phase II (glucuronidation, sulfation, acetylation, GSH conjugation) attaches a polar moiety for excretion.",
        example: "CYP oxidation then UGT glucuronidation.",
        tags: ["PK", "metabolism"],
        xref: ["chemistry"],
      },
      {
        name: "Cytochrome P450 (CYP450) system",
        description: "The main drug-metabolizing enzymes.",
        kind: "concept",
        className: "PK concept",
        formula: "A heme-thiolate mono-oxygenase superfamily; CYP3A4, 2D6, 2C9, 2C19, and 1A2 handle most drugs.",
        example: "CYP3A4 metabolizes a large share of marketed drugs.",
        tags: ["PK", "metabolism"],
        xref: ["biology"],
      },
      {
        name: "Enzyme induction & inhibition",
        description: "The engine of PK drug interactions.",
        kind: "concept",
        className: "PK concept",
        formula: "Inducers (rifampin, carbamazepine) raise CYP expression and lower substrate levels; inhibitors (ketoconazole, ritonavir, grapefruit juice) raise them.",
        example: "The rifampin - oral-contraceptive interaction.",
        tags: ["PK", "interactions"],
      },
      {
        name: "Renal excretion & clearance",
        description: "The kidney's role in elimination.",
        kind: "concept",
        className: "PK concept",
        formula: "Renal $CL = (\\text{filtration} + \\text{secretion} - \\text{reabsorption})$; scales with GFR.",
        example: "Dose-adjust renally cleared drugs in kidney disease.",
        tags: ["PK", "elimination"],
      },
      {
        name: "Biliary excretion & enterohepatic recirculation",
        description: "Elimination via bile, and its recycling.",
        kind: "concept",
        className: "PK concept",
        formula: "Drug excreted in bile can be reabsorbed from the gut, prolonging exposure.",
        example: "Extends the half-life of some drugs and endogenous hormones.",
        tags: ["PK"],
      },
      {
        name: "Therapeutic drug monitoring (TDM)",
        description: "Dosing to a measured level.",
        kind: "concept",
        className: "PK application",
        formula: "Measure plasma concentration and titrate for narrow-therapeutic-index drugs.",
        example: "Vancomycin, lithium, aminoglycosides, tacrolimus.",
        tags: ["PK", "clinical"],
        xref: ["statistics"],
      },
      {
        name: "Population PK & compartmental modeling",
        description: "PK across a population with covariates.",
        kind: "concept",
        className: "PK modeling",
        formula: "Nonlinear mixed-effects models estimate typical parameters plus between-subject variability; covariates (weight, renal function) explain variation.",
        example: "Model-informed precision dosing.",
        tags: ["PK", "modeling"],
        xref: ["statistics"],
      },
    ],
  },

  // ── Family 2 ──────────────────────────────────────────────────────────────
  {
    slug: "pharmacodynamics",
    number: 2,
    name: "Pharmacodynamics: Receptors, Dose-Response & Drug Action",
    blurb: "What the drug does to the body — the receptor-level quantitative core: dose-response, affinity, potency, efficacy, and the receptor superfamilies.",
    section: "A",
    color: "indigo",
    dataSource: "Primary receptor pharmacology literature; IUPHAR/BPS Guide to Pharmacology.",
    entries: [
      {
        name: "Pharmacodynamics (scope)",
        description: "What the drug does to the body.",
        kind: "concept",
        className: "PD concept",
        formula: "The relationship between drug concentration and biological effect, $E = f(C)$.",
        example: "The concentration-effect curve.",
        tags: ["PD", "foundations"],
      },
      {
        name: "Dose-response relationship",
        description: "Effect rising with dose.",
        kind: "concept",
        className: "PD concept",
        formula: "Graded (continuous effect) vs quantal (all-or-none, population fraction responding); typically sigmoidal on a log-dose axis.",
        example: "The classic log-dose-response curve.",
        tags: ["PD"],
        xref: ["statistics"],
      },
      {
        name: "The Hill / Emax equation",
        description: "Quantifying graded response.",
        kind: "concept",
        className: "PD equation",
        formula: "$E = \\dfrac{E_{max}\\,C^{n}}{EC_{50}^{\\,n} + C^{n}}$, with Hill coefficient $n$ setting steepness.",
        example: "Fits receptor occupancy and enzyme kinetics alike.",
        tags: ["PD"],
        xref: ["mathematics"],
      },
      {
        name: "Potency vs efficacy",
        description: "Concentration needed vs maximal effect.",
        kind: "concept",
        className: "PD concept",
        formula: "Potency is inversely related to $EC_{50}$; efficacy is the ceiling $E_{max}$.",
        example: "A more potent drug works at lower dose; a more efficacious one reaches a higher effect.",
        tags: ["PD"],
      },
      {
        name: "Affinity & the dissociation constant (Kd)",
        description: "How tightly drug binds receptor.",
        kind: "concept",
        className: "PD parameter",
        formula: "$K_d = \\dfrac{k_{\\text{off}}}{k_{\\text{on}}}$; occupancy $= \\dfrac{[L]}{K_d + [L]}$ (Langmuir isotherm).",
        example: "Lower $K_d$ means higher affinity.",
        tags: ["PD", "receptors"],
      },
      {
        name: "Agonists (full & partial)",
        description: "Drugs that activate a receptor.",
        kind: "concept",
        className: "receptor concept",
        formula: "A full agonist produces the maximal response; a partial agonist has submaximal efficacy even at full occupancy.",
        example: "Morphine (full) vs buprenorphine (partial) at the mu-opioid receptor.",
        tags: ["PD"],
      },
      {
        name: "Antagonists (competitive & non-competitive)",
        description: "Drugs that block a receptor.",
        kind: "concept",
        className: "receptor concept",
        formula: "Competitive antagonism is surmountable (shifts the curve right, $E_{max}$ preserved); non-competitive/irreversible lowers $E_{max}$.",
        example: "Naloxone competitively reverses opioids.",
        tags: ["PD"],
      },
      {
        name: "Inverse agonists",
        description: "Drugs that reduce constitutive activity.",
        kind: "concept",
        className: "receptor concept",
        formula: "Stabilize the inactive receptor state, lowering baseline signaling below the unliganded level.",
        example: "Some antihistamines and beta-blockers act as inverse agonists.",
        tags: ["PD"],
      },
      {
        name: "Allosteric modulators",
        description: "Binding away from the active site.",
        kind: "concept",
        className: "receptor concept",
        formula: "Positive (PAM) or negative (NAM) modulators change the response to the orthosteric ligand rather than acting alone.",
        example: "Benzodiazepines are positive allosteric modulators at GABA-A.",
        tags: ["PD"],
      },
      {
        name: "Spare receptors & receptor reserve",
        description: "Maximal effect below full occupancy.",
        kind: "concept",
        className: "receptor concept",
        formula: "$EC_{50} < K_d$ when a system has spare receptors, so a maximal response needs only partial occupancy.",
        example: "Some agonist systems retain a reserve.",
        tags: ["PD", "receptors"],
      },
      {
        name: "Signal transduction & receptor superfamilies",
        description: "How binding becomes effect.",
        kind: "concept",
        className: "receptor concept",
        formula: "GPCRs (via G-proteins/second messengers), ligand-gated ion channels, enzyme-linked receptors (RTKs), and nuclear receptors are the four major classes.",
        example: "Beta-adrenergic (GPCR) vs nicotinic (ion channel).",
        tags: ["PD", "receptors"],
        xref: ["biology"],
      },
      {
        name: "Second messengers",
        description: "Intracellular amplifiers.",
        kind: "concept",
        className: "signaling concept",
        formula: "cAMP, cGMP, IP3/DAG, and Ca2+ relay and amplify the receptor signal.",
        example: "cAMP downstream of beta-adrenergic activation.",
        tags: ["PD"],
        xref: ["biology"],
      },
      {
        name: "Tolerance, tachyphylaxis & desensitization",
        description: "Diminishing response with exposure.",
        kind: "concept",
        className: "PD concept",
        formula: "Receptor downregulation/desensitization reduces effect over time; tachyphylaxis is rapid tolerance.",
        example: "Nitrate tolerance; decongestant rebound.",
        tags: ["PD"],
      },
      {
        name: "Therapeutic index & window",
        description: "The safety margin.",
        kind: "concept",
        className: "PD safety parameter",
        formula: "$TI = \\dfrac{TD_{50}}{ED_{50}}$ (or $LD_{50}/ED_{50}$); a narrow window (warfarin, digoxin, lithium) demands monitoring.",
        example: "Penicillin has a wide index; digoxin a narrow one.",
        tags: ["PD", "safety"],
      },
      {
        name: "Drug interactions (PD): additivity, synergy, antagonism",
        description: "Combined-drug effects.",
        kind: "concept",
        className: "PD concept",
        formula: "Additive (effects sum), synergistic (greater than sum), or antagonistic; isobolograms quantify it.",
        example: "Beta-lactam plus aminoglycoside synergy.",
        tags: ["PD", "interactions"],
      },
      {
        name: "Selectivity & the therapeutic-target concept",
        description: "Hitting the intended target.",
        kind: "concept",
        className: "PD concept",
        formula: "A drug's ratio of desired-target to off-target activity sets its side-effect profile; loss of selectivity at higher doses drives toxicity.",
        example: "'Cardioselective' beta-blockers lose beta-1 selectivity at high dose.",
        tags: ["PD"],
        xref: ["chemistry"],
      },
    ],
  },

  // ── Family 3 ──────────────────────────────────────────────────────────────
  {
    slug: "neuropsychiatric-agents",
    number: 3,
    name: "Neuropsychiatric Agents (CNS)",
    blurb: "Antipsychotics, antidepressants, anxiolytics, hypnotics, mood stabilizers, antiepileptics, anti-Parkinson, anti-dementia and ADHD agents. Controlled classes described at reference level and by scheduling only.",
    section: "B",
    color: "blue",
    dataSource: "RxNorm / Drugs@FDA; WHO EML (essential CNS medicines); openFDA/FAERS.",
    entries: [
      {
        name: "Typical (first-generation) antipsychotics",
        description: "Dopamine-blocking neuroleptics.",
        kind: "drug",
        className: "antipsychotic",
        mechanism: "Antagonize D2 dopamine receptors, especially mesolimbic.",
        indications: "Schizophrenia, acute psychosis, mania.",
        atc: ["N05A"],
        example: "Haloperidol, chlorpromazine.",
        cautions: "Extrapyramidal symptoms, tardive dyskinesia.",
        tags: ["CNS", "psychiatry"],
      },
      {
        name: "Atypical (second-generation) antipsychotics",
        description: "Broader-receptor antipsychotics.",
        kind: "drug",
        className: "antipsychotic",
        mechanism: "Combined D2 and 5-HT2A antagonism (some partial D2 agonism), lowering extrapyramidal risk relative to typicals.",
        indications: "Schizophrenia, bipolar disorder, adjunct in depression.",
        atc: ["N05A"],
        example: "Risperidone, olanzapine, quetiapine, aripiprazole; clozapine reserved for refractory disease and requires hematologic monitoring.",
        cautions: "Metabolic syndrome, weight gain; clozapine agranulocytosis; QT prolongation.",
        tags: ["CNS", "psychiatry"],
      },
      {
        name: "SSRIs",
        description: "Serotonin-selective antidepressants.",
        kind: "drug",
        className: "antidepressant",
        mechanism: "Inhibit the presynaptic serotonin transporter (SERT), raising synaptic 5-HT.",
        indications: "Depression, anxiety disorders, OCD, PTSD.",
        atc: ["N06AB"],
        example: "Fluoxetine, sertraline, escitalopram.",
        cautions: "GI upset, sexual dysfunction, hyponatremia, serotonin syndrome with other serotonergics.",
        tags: ["CNS", "psychiatry"],
      },
      {
        name: "SNRIs",
        description: "Dual reuptake inhibitors.",
        kind: "drug",
        className: "antidepressant",
        mechanism: "Inhibit serotonin and norepinephrine transporters.",
        indications: "Depression, anxiety, neuropathic pain, fibromyalgia.",
        atc: ["N06AX"],
        example: "Venlafaxine, duloxetine.",
        cautions: "Blood-pressure elevation; discontinuation syndrome.",
        tags: ["CNS", "psychiatry"],
      },
      {
        name: "Tricyclic antidepressants (TCAs)",
        description: "Older reuptake inhibitors.",
        kind: "drug",
        className: "antidepressant",
        mechanism: "Block 5-HT and NE reuptake, with anticholinergic and antihistaminic activity.",
        indications: "Depression, neuropathic pain, migraine prophylaxis.",
        atc: ["N06AA"],
        example: "Amitriptyline, nortriptyline.",
        cautions: "Cardiotoxic in overdose; anticholinergic side effects.",
        tags: ["CNS"],
      },
      {
        name: "Monoamine oxidase inhibitors (MAOIs)",
        description: "Enzyme-blocking antidepressants.",
        kind: "drug",
        className: "antidepressant",
        mechanism: "Inhibit monoamine oxidase, raising monoamine stores.",
        indications: "Refractory or atypical depression.",
        atc: ["N06AF", "N06AG"],
        example: "Phenelzine, tranylcypromine, selegiline.",
        cautions: "Tyramine ('cheese') reaction; serotonin syndrome risk with serotonergic co-medication.",
        tags: ["CNS"],
      },
      {
        name: "Atypical antidepressants (bupropion, mirtazapine)",
        description: "Distinct-mechanism antidepressants.",
        kind: "drug",
        className: "antidepressant",
        mechanism: "Bupropion inhibits dopamine and NE reuptake; mirtazapine antagonizes alpha-2 and 5-HT2/3.",
        indications: "Depression (bupropion also smoking cessation).",
        atc: ["N06AX"],
        example: "Bupropion, mirtazapine, trazodone.",
        cautions: "Bupropion lowers seizure threshold; mirtazapine causes weight gain and sedation.",
        tags: ["CNS"],
      },
      {
        name: "Rapid-acting antidepressants (ketamine/esketamine)",
        description: "Glutamatergic antidepressants.",
        kind: "drug",
        className: "antidepressant",
        mechanism: "NMDA-receptor antagonism with rapid downstream synaptic effects.",
        indications: "Treatment-resistant depression (esketamine nasal, under a restricted access program).",
        atc: ["N06AX"],
        example: "Esketamine.",
        cautions: "Dissociation, transient blood-pressure elevation; ketamine is a controlled substance and is described at reference level.",
        schedule: "Ketamine: US Schedule III.",
        tags: ["CNS", "psychiatry", "controlled"],
      },
      {
        name: "Benzodiazepines",
        description: "GABAergic anxiolytics and sedatives.",
        kind: "drug",
        className: "anxiolytic / hypnotic",
        mechanism: "Positive allosteric modulation of GABA-A, increasing chloride-channel opening frequency.",
        indications: "Anxiety, seizures, insomnia, alcohol withdrawal, procedural sedation.",
        atc: ["N05BA", "N05CD"],
        example: "Diazepam, lorazepam, alprazolam, midazolam.",
        cautions: "Dependence, withdrawal, respiratory depression when combined with opioids; falls and cognitive effects in older adults.",
        schedule: "US Schedule IV.",
        tags: ["CNS", "controlled"],
      },
      {
        name: "Z-drugs (non-benzodiazepine hypnotics)",
        description: "Selective GABA-A hypnotics.",
        kind: "drug",
        className: "hypnotic",
        mechanism: "Act at the benzodiazepine site with hypnotic selectivity.",
        indications: "Short-term insomnia.",
        atc: ["N05CF"],
        example: "Zolpidem, zopiclone, eszopiclone.",
        cautions: "Complex sleep behaviors (boxed warning for some agents); dependence with prolonged use.",
        schedule: "US Schedule IV.",
        tags: ["CNS", "controlled"],
      },
      {
        name: "Barbiturates",
        description: "Older CNS depressants.",
        kind: "drug",
        className: "sedative / anticonvulsant",
        mechanism: "Prolong GABA-A chloride-channel opening (and open the channel directly at high concentration).",
        indications: "Now mainly anesthesia induction, refractory status epilepticus, and selected seizure disorders.",
        atc: ["N05CA", "N03AA"],
        example: "Phenobarbital, thiopental.",
        cautions: "Narrow therapeutic index; respiratory depression; strong enzyme induction.",
        schedule: "Controlled, varying schedules by agent.",
        tags: ["CNS", "controlled"],
      },
      {
        name: "Mood stabilizers — lithium",
        description: "The archetypal bipolar agent.",
        kind: "drug",
        className: "mood stabilizer",
        mechanism: "Incompletely understood; inhibits inositol monophosphatase and GSK-3-beta, modulating second messengers.",
        indications: "Bipolar disorder (maintenance, mania), suicide-risk reduction.",
        atc: ["N05AN"],
        example: "Lithium carbonate.",
        cautions: "Narrow therapeutic index requires TDM; renal and thyroid toxicity with chronic use; teratogenic risk.",
        tags: ["CNS", "psychiatry"],
      },
      {
        name: "Mood-stabilizing anticonvulsants",
        description: "Antiepileptics used in mood disorders.",
        kind: "drug",
        className: "mood stabilizer / anticonvulsant",
        mechanism: "Sodium-channel and synaptic modulation (see antiepileptics).",
        indications: "Bipolar disorder, especially mixed and rapid-cycling presentations.",
        atc: ["N03A"],
        example: "Valproate, lamotrigine, carbamazepine.",
        cautions: "Valproate teratogenicity; lamotrigine Stevens-Johnson risk; carbamazepine induction.",
        tags: ["CNS", "psychiatry"],
      },
      {
        name: "Antiepileptics / anticonvulsants",
        description: "Seizure-suppressing agents.",
        kind: "drug",
        className: "anticonvulsant",
        mechanism: "Diverse — sodium-channel blockade (phenytoin, carbamazepine, lamotrigine), GABA enhancement (valproate, benzodiazepines), calcium-channel or SV2A modulation (ethosuximide, levetiracetam), or glutamate reduction.",
        indications: "Epilepsy syndromes, status epilepticus, neuropathic pain, migraine prophylaxis.",
        atc: ["N03A"],
        example: "Levetiracetam, valproate, lamotrigine, phenytoin.",
        cautions: "Class-dependent — teratogenicity, hepatic injury, hematologic effects; enzyme induction with older agents.",
        tags: ["CNS"],
      },
      {
        name: "Anti-Parkinson dopaminergics",
        description: "Restoring dopaminergic tone.",
        kind: "drug",
        className: "dopaminergic",
        mechanism: "Levodopa (with a decarboxylase inhibitor) replaces dopamine; dopamine agonists, MAO-B inhibitors, and COMT inhibitors extend its action.",
        indications: "Parkinson's disease.",
        atc: ["N04B"],
        example: "Levodopa/carbidopa, pramipexole, selegiline, entacapone.",
        cautions: "Levodopa motor fluctuations and dyskinesias; dopamine-agonist impulse-control disorders.",
        tags: ["CNS", "neurology"],
      },
      {
        name: "Anti-dementia agents — cholinesterase inhibitors",
        description: "Raising acetylcholine in dementia.",
        kind: "drug",
        className: "cholinesterase inhibitor",
        mechanism: "Inhibit acetylcholinesterase, increasing synaptic ACh.",
        indications: "Alzheimer's disease (symptomatic).",
        atc: ["N06DA"],
        example: "Donepezil, rivastigmine, galantamine.",
        cautions: "Cholinergic side effects (GI, bradycardia); modest symptomatic benefit.",
        tags: ["CNS", "neurology"],
      },
      {
        name: "Anti-dementia agents — NMDA antagonist",
        description: "Glutamate modulation in dementia.",
        kind: "drug",
        className: "NMDA antagonist",
        mechanism: "Memantine is an uncompetitive NMDA-receptor antagonist.",
        indications: "Moderate-severe Alzheimer's disease.",
        atc: ["N06DX"],
        example: "Memantine.",
        tags: ["CNS"],
      },
      {
        name: "Anti-amyloid monoclonal antibodies",
        description: "Disease-modifying Alzheimer's biologics.",
        kind: "drug",
        className: "monoclonal antibody",
        mechanism: "Monoclonal antibodies that bind and clear aggregated amyloid-beta.",
        indications: "Early Alzheimer's disease with confirmed amyloid pathology.",
        atc: ["N06DX"],
        example: "Lecanemab (traditional approval 2023), donanemab (2024).",
        cautions: "Boxed warning for amyloid-related imaging abnormalities (ARIA); APOE4 testing advised; benefit-vs-harm remains contested.",
        status: "in-flux",
        tags: ["CNS", "neurology", "biologic"],
        xref: ["medicine"],
      },
      {
        name: "CNS stimulants (ADHD)",
        description: "Catecholaminergic stimulants.",
        kind: "drug",
        className: "psychostimulant",
        mechanism: "Increase synaptic dopamine and norepinephrine — methylphenidate blocks reuptake; amphetamines also promote release.",
        indications: "ADHD, narcolepsy.",
        atc: ["N06BA"],
        example: "Methylphenidate, amphetamine salts.",
        cautions: "Blood-pressure and heart-rate elevation; dependence and diversion risk. Described at reference level only.",
        schedule: "US Schedule II.",
        tags: ["CNS", "controlled"],
      },
      {
        name: "Non-stimulant ADHD agents",
        description: "Noradrenergic alternatives.",
        kind: "drug",
        className: "noradrenergic agent",
        mechanism: "Atomoxetine inhibits the norepinephrine transporter; guanfacine and clonidine are alpha-2 agonists.",
        indications: "ADHD.",
        atc: ["N06BA", "C02AC"],
        example: "Atomoxetine, guanfacine.",
        tags: ["CNS"],
      },
      {
        name: "Wakefulness-promoting agents",
        description: "Non-amphetamine stimulants.",
        kind: "drug",
        className: "wake-promoting agent",
        mechanism: "Modafinil and armodafinil promote wakefulness through (incompletely defined) dopaminergic and other pathways.",
        indications: "Narcolepsy, shift-work disorder, OSA-related sleepiness.",
        atc: ["N06BA"],
        example: "Modafinil.",
        cautions: "Serious skin reactions reported; psychiatric effects.",
        schedule: "US Schedule IV.",
        tags: ["CNS", "controlled"],
      },
    ],
  },

  // ── Family 4 ──────────────────────────────────────────────────────────────
  {
    slug: "analgesics-anesthetics",
    number: 4,
    name: "Analgesics, Anesthetics & Controlled CNS Agents",
    blurb: "Pain, anesthesia, and CNS controlled-substance classes. Every controlled class here is described by mechanism, therapeutic use, adverse profile, and scheduling only.",
    section: "B",
    color: "sky",
    dataSource: "RxNorm / Drugs@FDA; WHO EML (essential analgesics); openFDA/FAERS.",
    entries: [
      {
        name: "Opioid analgesics",
        description: "Mu-receptor pain relievers.",
        kind: "drug",
        className: "opioid analgesic",
        mechanism: "Agonism at mu (and kappa/delta) opioid receptors, inhibiting ascending pain transmission and modulating perception.",
        indications: "Moderate-severe acute pain, cancer pain, palliative care.",
        atc: ["N02A"],
        example: "Morphine, oxycodone, hydromorphone, fentanyl.",
        cautions: "Respiratory depression is the lethal toxicity; dependence and tolerance; overdose reversed by naloxone. Described at reference level only — no dosing, formulation-defeat, or misuse content.",
        schedule: "Most agents US Schedule II.",
        tags: ["analgesia", "controlled"],
      },
      {
        name: "Partial-agonist & atypical opioids",
        description: "Lower-ceiling and mixed opioids.",
        kind: "drug",
        className: "opioid analgesic",
        mechanism: "Buprenorphine is a high-affinity partial mu-agonist; tramadol and tapentadol add monoamine-reuptake inhibition.",
        indications: "Pain; buprenorphine also for opioid use disorder.",
        atc: ["N02AE", "N02AX"],
        example: "Buprenorphine, tramadol.",
        cautions: "Serotonin syndrome risk with tramadol; seizures at high dose.",
        schedule: "Controlled — varying schedules.",
        tags: ["analgesia", "controlled"],
      },
      {
        name: "Opioid antagonists & reversal agents",
        description: "Blocking opioid receptors.",
        kind: "drug",
        className: "opioid antagonist",
        mechanism: "Competitive mu-opioid antagonism.",
        indications: "Opioid overdose reversal (naloxone), opioid and alcohol use disorder (naltrexone).",
        atc: ["V03AB", "N07BB"],
        example: "Naloxone, naltrexone.",
        tags: ["analgesia", "antidote"],
      },
      {
        name: "Opioid use disorder — medication-assisted treatment",
        description: "Pharmacotherapy for OUD.",
        kind: "drug",
        className: "OUD pharmacotherapy",
        mechanism: "Methadone (full agonist, long-acting) or buprenorphine (partial agonist) stabilize receptor signaling; naltrexone blocks it.",
        indications: "Opioid use disorder.",
        atc: ["N07BC"],
        example: "Methadone, buprenorphine/naloxone.",
        cautions: "Dispensed under regulated programs; QT prolongation with methadone.",
        schedule: "Regulated programs.",
        tags: ["analgesia", "controlled"],
        xref: ["public-health"],
      },
      {
        name: "NSAIDs (non-selective)",
        description: "Anti-inflammatory analgesics.",
        kind: "drug",
        className: "NSAID",
        mechanism: "Inhibit cyclooxygenase (COX-1/COX-2), reducing prostaglandin synthesis.",
        indications: "Pain, inflammation, fever.",
        atc: ["M01A"],
        example: "Ibuprofen, naproxen, diclofenac.",
        cautions: "GI bleeding, renal impairment, cardiovascular risk.",
        tags: ["analgesia", "anti-inflammatory"],
      },
      {
        name: "COX-2 selective inhibitors (coxibs)",
        description: "GI-sparing NSAIDs.",
        kind: "drug",
        className: "NSAID",
        mechanism: "Selectively inhibit COX-2, sparing gastroprotective COX-1.",
        indications: "Pain and inflammation with lower GI-bleed risk.",
        atc: ["M01AH"],
        example: "Celecoxib.",
        cautions: "Cardiovascular risk (rofecoxib withdrawn).",
        tags: ["analgesia"],
      },
      {
        name: "Acetaminophen / paracetamol",
        description: "Analgesic-antipyretic.",
        kind: "drug",
        className: "analgesic",
        mechanism: "Central COX inhibition and other pathways (not fully defined); little peripheral anti-inflammatory effect.",
        indications: "Pain, fever.",
        atc: ["N02BE"],
        example: "Paracetamol.",
        cautions: "Hepatotoxic in overdose (antidote: N-acetylcysteine).",
        tags: ["analgesia"],
      },
      {
        name: "Non-opioid acute-pain agents (Na-v1.8 blockers)",
        description: "First-in-class peripheral pain blockers.",
        kind: "drug",
        className: "sodium-channel blocker",
        mechanism: "Selective inhibition of the Na-v1.8 sodium channel on peripheral pain-sensing neurons.",
        indications: "Moderate-severe acute pain, non-opioid.",
        atc: ["N02BG"],
        example: "Suzetrigine (approved 2025).",
        cautions: "First-in-class; long-term real-world data still accumulating.",
        status: "needs-verification",
        tags: ["analgesia"],
      },
      {
        name: "Adjuvant analgesics for neuropathic pain",
        description: "Non-analgesic drugs used for pain.",
        kind: "drug",
        className: "neuropathic-pain adjuvant",
        mechanism: "Gabapentinoids inhibit the alpha-2-delta calcium-channel subunit; TCAs and SNRIs, plus some anticonvulsants, also apply.",
        indications: "Neuropathic pain, fibromyalgia.",
        atc: ["N02BF"],
        example: "Gabapentin, pregabalin, duloxetine.",
        cautions: "Sedation, gabapentinoid abuse potential.",
        tags: ["analgesia"],
      },
      {
        name: "Antimigraine — triptans",
        description: "Acute migraine agonists.",
        kind: "drug",
        className: "triptan",
        mechanism: "5-HT1B/1D agonism causing cranial vasoconstriction and inhibition of trigeminal peptide release.",
        indications: "Acute migraine.",
        atc: ["N02CC"],
        example: "Sumatriptan, rizatriptan.",
        cautions: "Coronary vasoconstriction — contraindicated in ischemic heart disease.",
        tags: ["analgesia", "neurology"],
      },
      {
        name: "Antimigraine — CGRP-targeted agents",
        description: "Migraine biologics and gepants.",
        kind: "drug",
        className: "CGRP antagonist",
        mechanism: "Block calcitonin-gene-related-peptide signaling — monoclonal antibodies or small-molecule receptor antagonists (gepants).",
        indications: "Migraine prevention and acute treatment.",
        atc: ["N02CD", "N02CX"],
        example: "Erenumab, rimegepant, ubrogepant.",
        tags: ["analgesia", "neurology", "biologic"],
      },
      {
        name: "General anesthetics — inhaled",
        description: "Volatile anesthesia.",
        kind: "drug",
        className: "inhaled anesthetic",
        mechanism: "Enhance inhibitory (GABA-A) and reduce excitatory transmission; potency indexed by MAC (minimum alveolar concentration).",
        indications: "Maintenance of general anesthesia.",
        atc: ["N01AB"],
        example: "Sevoflurane, isoflurane, desflurane.",
        cautions: "Malignant hyperthermia (with succinylcholine); post-op nausea.",
        tags: ["anesthesia"],
      },
      {
        name: "General anesthetics — intravenous",
        description: "IV induction agents.",
        kind: "drug",
        className: "IV anesthetic",
        mechanism: "Propofol and etomidate potentiate GABA-A; ketamine antagonizes NMDA.",
        indications: "Induction and maintenance of anesthesia, procedural sedation.",
        atc: ["N01AX"],
        example: "Propofol, etomidate, ketamine.",
        cautions: "Propofol infusion syndrome; etomidate adrenal suppression; ketamine is controlled.",
        tags: ["anesthesia"],
      },
      {
        name: "Local anesthetics",
        description: "Reversible nerve conduction block.",
        kind: "drug",
        className: "local anesthetic",
        mechanism: "Block voltage-gated sodium channels, preventing action-potential propagation.",
        indications: "Local and regional anesthesia; arrhythmia (lidocaine).",
        atc: ["N01B"],
        example: "Lidocaine, bupivacaine, ropivacaine.",
        cautions: "Systemic toxicity (LAST) — CNS then cardiac; bupivacaine cardiotoxicity.",
        tags: ["anesthesia"],
      },
      {
        name: "Neuromuscular blocking agents",
        description: "Surgical paralysis.",
        kind: "drug",
        className: "neuromuscular blocker",
        mechanism: "Depolarizing (succinylcholine) or non-depolarizing (competitive nicotinic antagonists) block the neuromuscular junction.",
        indications: "Intubation, surgical muscle relaxation.",
        atc: ["M03A"],
        example: "Succinylcholine, rocuronium, vecuronium.",
        cautions: "Succinylcholine hyperkalemia and malignant-hyperthermia trigger.",
        tags: ["anesthesia"],
      },
      {
        name: "Cannabinoids (therapeutic)",
        description: "Cannabinoid-receptor agents.",
        kind: "drug",
        className: "cannabinoid",
        mechanism: "Act on CB1/CB2 receptors of the endocannabinoid system; cannabidiol (CBD) acts through multiple non-CB1 targets.",
        indications: "Specific seizure syndromes (purified CBD), chemotherapy nausea, spasticity, appetite stimulation.",
        atc: ["N02BG", "A04AD"],
        example: "Cannabidiol (Epidiolex), nabilone, dronabinol.",
        cautions: "CBD hepatic-enzyme elevation and drug interactions; described as governance only for scheduling.",
        schedule: "US marijuana scheduling is in flux. As of April 2026, FDA-approved marijuana drug products and state-licensed medical marijuana were moved to Schedule III; other (recreational) marijuana remains Schedule I; a broader rescheduling review is ongoing.",
        status: "in-flux",
        tags: ["CNS", "controlled"],
        xref: ["public-health"],
      },
      {
        name: "Psychedelic-assisted therapeutics (investigational)",
        description: "Serotonergic agents under study.",
        kind: "drug",
        className: "psychedelic (investigational)",
        mechanism: "5-HT2A receptor agonism (classic psychedelics); MDMA acts as a monoamine releaser.",
        indications: "Under clinical investigation for treatment-resistant depression and PTSD; regulatory status evolving.",
        atc: [],
        example: "Psilocybin, MDMA.",
        cautions: "Both are controlled substances. Efficacy and approval are unsettled and disputed — presented as governance and reference level only.",
        schedule: "Both US Schedule I (with limited investigational access).",
        status: "contested",
        tags: ["CNS", "controlled"],
        xref: ["medicine"],
      },
    ],
  },

  // ── Family 5 ──────────────────────────────────────────────────────────────
  {
    slug: "cardiovascular-drugs",
    number: 5,
    name: "Cardiovascular Drugs",
    blurb: "ATC group C — hypertension, heart failure, arrhythmia, ischemic heart disease, and dyslipidemia agents. The high-volume chronic-disease pharmacopeia.",
    section: "C",
    color: "cyan",
    dataSource: "RxNorm / Drugs@FDA; WHO EML; openFDA/FAERS.",
    entries: [
      {
        name: "Thiazide & thiazide-like diuretics",
        description: "First-line antihypertensive diuretics.",
        kind: "drug",
        className: "diuretic",
        mechanism: "Inhibit the Na+/Cl- cotransporter in the distal convoluted tubule.",
        indications: "Hypertension, edema.",
        atc: ["C03A"],
        example: "Hydrochlorothiazide, chlorthalidone, indapamide.",
        cautions: "Hyponatremia, hypokalemia, hyperuricemia, hyperglycemia.",
        tags: ["cardiovascular"],
      },
      {
        name: "Loop diuretics",
        description: "Potent volume-removal agents.",
        kind: "drug",
        className: "diuretic",
        mechanism: "Inhibit the Na+/K+/2Cl- cotransporter in the thick ascending loop of Henle.",
        indications: "Heart failure, edema, resistant hypertension.",
        atc: ["C03C"],
        example: "Furosemide, bumetanide, torsemide.",
        cautions: "Ototoxicity, hypokalemia, dehydration.",
        tags: ["cardiovascular"],
      },
      {
        name: "Potassium-sparing diuretics & aldosterone antagonists",
        description: "Distal-tubule and mineralocorticoid-receptor agents.",
        kind: "drug",
        className: "diuretic",
        mechanism: "Block the epithelial sodium channel (amiloride) or the mineralocorticoid receptor (spironolactone, eplerenone).",
        indications: "Heart failure, resistant hypertension, hyperaldosteronism.",
        atc: ["C03D"],
        example: "Spironolactone, eplerenone.",
        cautions: "Hyperkalemia; spironolactone gynecomastia.",
        tags: ["cardiovascular"],
      },
      {
        name: "ACE inhibitors",
        description: "RAAS-blocking antihypertensives.",
        kind: "drug",
        className: "RAAS inhibitor",
        mechanism: "Inhibit angiotensin-converting enzyme, reducing angiotensin II and aldosterone.",
        indications: "Hypertension, heart failure, diabetic nephropathy, post-MI.",
        atc: ["C09A"],
        example: "Lisinopril, enalapril, ramipril.",
        cautions: "Cough, angioedema, hyperkalemia, teratogenicity.",
        tags: ["cardiovascular"],
      },
      {
        name: "Angiotensin receptor blockers (ARBs)",
        description: "AT1-receptor antagonists.",
        kind: "drug",
        className: "RAAS inhibitor",
        mechanism: "Block the angiotensin II type-1 receptor.",
        indications: "Hypertension, heart failure, nephropathy — ACE-inhibitor alternative.",
        atc: ["C09C"],
        example: "Losartan, valsartan, candesartan.",
        cautions: "Hyperkalemia, teratogenicity; less cough than ACE inhibitors.",
        tags: ["cardiovascular"],
      },
      {
        name: "Angiotensin receptor-neprilysin inhibitor (ARNI)",
        description: "Combined RAAS/natriuretic-peptide agent.",
        kind: "drug",
        className: "ARNI",
        mechanism: "Sacubitril inhibits neprilysin (raising natriuretic peptides) combined with the ARB valsartan.",
        indications: "Heart failure with reduced ejection fraction.",
        atc: ["C09DX"],
        example: "Sacubitril/valsartan.",
        cautions: "Do not co-administer with ACE inhibitors — angioedema risk.",
        tags: ["cardiovascular"],
      },
      {
        name: "Beta-blockers",
        description: "Sympathetic-drive blockers.",
        kind: "drug",
        className: "beta-blocker",
        mechanism: "Antagonize beta-adrenergic receptors, lowering heart rate, contractility, and renin.",
        indications: "Hypertension, angina, arrhythmia, heart failure, post-MI.",
        atc: ["C07"],
        example: "Metoprolol, atenolol, carvedilol, bisoprolol.",
        cautions: "Bradycardia, bronchospasm (non-selective), fatigue; abrupt withdrawal risk.",
        tags: ["cardiovascular"],
      },
      {
        name: "Dihydropyridine calcium channel blockers",
        description: "Vascular calcium blockers.",
        kind: "drug",
        className: "calcium channel blocker",
        mechanism: "Block L-type calcium channels preferentially in vascular smooth muscle, causing vasodilation.",
        indications: "Hypertension, angina.",
        atc: ["C08CA"],
        example: "Amlodipine, nifedipine.",
        cautions: "Peripheral edema, reflex tachycardia.",
        tags: ["cardiovascular"],
      },
      {
        name: "Non-dihydropyridine calcium channel blockers",
        description: "Cardiac calcium blockers.",
        kind: "drug",
        className: "calcium channel blocker",
        mechanism: "Block L-type channels with greater cardiac (rate/conduction) effect.",
        indications: "Rate control in atrial fibrillation, angina, hypertension.",
        atc: ["C08D"],
        example: "Verapamil, diltiazem.",
        cautions: "Bradycardia, AV block; avoid with beta-blockers.",
        tags: ["cardiovascular"],
      },
      {
        name: "Nitrates",
        description: "Coronary and venous vasodilators.",
        kind: "drug",
        className: "vasodilator",
        mechanism: "Release nitric oxide, raising cGMP and relaxing vascular smooth muscle (mainly venodilation).",
        indications: "Angina, acute coronary syndrome, heart failure.",
        atc: ["C01DA"],
        example: "Nitroglycerin, isosorbide mononitrate.",
        cautions: "Tolerance requires nitrate-free intervals; contraindicated with PDE5 inhibitors.",
        tags: ["cardiovascular"],
      },
      {
        name: "Antiarrhythmics (Vaughan-Williams classes I-IV)",
        description: "Rhythm-controlling agents.",
        kind: "drug",
        className: "antiarrhythmic",
        mechanism: "Class I block sodium channels; class II are beta-blockers; class III block potassium channels (prolong repolarization); class IV are calcium channel blockers.",
        indications: "Atrial and ventricular arrhythmias.",
        atc: ["C01B"],
        example: "Amiodarone (III), flecainide (Ic), sotalol, lidocaine (Ib).",
        cautions: "Amiodarone pulmonary, thyroid, and hepatic toxicity; proarrhythmia with several agents.",
        tags: ["cardiovascular"],
      },
      {
        name: "Cardiac glycosides",
        description: "Positive inotropes / rate agents.",
        kind: "drug",
        className: "cardiac glycoside",
        mechanism: "Inhibit the Na+/K+-ATPase, raising intracellular calcium; also increase vagal tone.",
        indications: "Heart failure, atrial fibrillation rate control.",
        atc: ["C01AA"],
        example: "Digoxin.",
        cautions: "Narrow therapeutic index requires TDM; antidote digoxin immune Fab.",
        tags: ["cardiovascular"],
      },
      {
        name: "Statins (HMG-CoA reductase inhibitors)",
        description: "Cholesterol-lowering agents.",
        kind: "drug",
        className: "statin",
        mechanism: "Inhibit HMG-CoA reductase, the rate-limiting step of cholesterol synthesis, upregulating LDL receptors.",
        indications: "Hyperlipidemia, cardiovascular risk reduction.",
        atc: ["C10AA"],
        example: "Atorvastatin, rosuvastatin, simvastatin.",
        cautions: "Myopathy, rare rhabdomyolysis; hepatic enzyme elevations.",
        tags: ["cardiovascular", "lipids"],
      },
      {
        name: "Ezetimibe & bile-acid sequestrants",
        description: "Non-statin lipid agents.",
        kind: "drug",
        className: "lipid-lowering agent",
        mechanism: "Ezetimibe blocks intestinal cholesterol absorption (NPC1L1); sequestrants bind bile acids.",
        indications: "Hyperlipidemia (adjunct or alternative to statins).",
        atc: ["C10AX", "C10AC"],
        example: "Ezetimibe, cholestyramine.",
        tags: ["cardiovascular", "lipids"],
      },
      {
        name: "PCSK9 inhibitors",
        description: "Injectable LDL-lowering biologics.",
        kind: "drug",
        className: "PCSK9 inhibitor",
        mechanism: "Monoclonal antibodies (or siRNA) inhibiting PCSK9, prolonging LDL-receptor recycling.",
        indications: "Refractory hypercholesterolemia, high cardiovascular risk.",
        atc: ["C10AX"],
        example: "Evolocumab, alirocumab, inclisiran (siRNA).",
        tags: ["cardiovascular", "lipids", "biologic"],
      },
      {
        name: "Fibrates & omega-3 agents",
        description: "Triglyceride-lowering agents.",
        kind: "drug",
        className: "lipid-lowering agent",
        mechanism: "Fibrates activate PPAR-alpha; icosapent ethyl lowers triglycerides through multiple pathways.",
        indications: "Hypertriglyceridemia.",
        atc: ["C10AB", "C10AX"],
        example: "Fenofibrate, icosapent ethyl.",
        tags: ["cardiovascular", "lipids"],
      },
      {
        name: "Central & peripheral sympatholytics / vasodilators",
        description: "Adjunct antihypertensives.",
        kind: "drug",
        className: "antihypertensive",
        mechanism: "Central alpha-2 agonists (clonidine) reduce sympathetic outflow; alpha-1 blockers (doxazosin) and direct vasodilators (hydralazine) relax vessels.",
        indications: "Resistant hypertension, specific settings.",
        atc: ["C02"],
        example: "Clonidine, hydralazine, doxazosin.",
        cautions: "Clonidine rebound hypertension; hydralazine lupus-like syndrome.",
        tags: ["cardiovascular"],
      },
    ],
  },

  // ── Family 6 ──────────────────────────────────────────────────────────────
  {
    slug: "respiratory-drugs",
    number: 6,
    name: "Respiratory Drugs",
    blurb: "ATC group R — asthma, COPD, allergy, cough, and pulmonary hypertension agents.",
    section: "C",
    color: "teal",
    dataSource: "RxNorm / Drugs@FDA; WHO EML; openFDA/FAERS.",
    entries: [
      {
        name: "Short-acting beta-2 agonists (SABA)",
        description: "Rescue bronchodilators.",
        kind: "drug",
        className: "bronchodilator",
        mechanism: "Beta-2 adrenergic agonism relaxes airway smooth muscle.",
        indications: "Acute bronchospasm in asthma and COPD.",
        atc: ["R03AC"],
        example: "Albuterol (salbutamol).",
        cautions: "Tremor, tachycardia; overuse signals uncontrolled asthma.",
        tags: ["respiratory"],
      },
      {
        name: "Long-acting beta-2 agonists (LABA)",
        description: "Maintenance bronchodilators.",
        kind: "drug",
        className: "bronchodilator",
        mechanism: "Prolonged beta-2 agonism.",
        indications: "Maintenance asthma (with an ICS) and COPD.",
        atc: ["R03AC"],
        example: "Salmeterol, formoterol.",
        cautions: "Not as monotherapy in asthma — historical mortality signal.",
        tags: ["respiratory"],
      },
      {
        name: "Inhaled corticosteroids (ICS)",
        description: "Anti-inflammatory controllers.",
        kind: "drug",
        className: "corticosteroid",
        mechanism: "Glucocorticoid-receptor agonism reduces airway inflammation and hyperresponsiveness.",
        indications: "Persistent asthma, COPD (selected).",
        atc: ["R03BA"],
        example: "Fluticasone, budesonide.",
        cautions: "Oral candidiasis, dysphonia; growth effects in children.",
        tags: ["respiratory"],
      },
      {
        name: "Muscarinic antagonists (SAMA / LAMA)",
        description: "Anticholinergic bronchodilators.",
        kind: "drug",
        className: "bronchodilator",
        mechanism: "Block airway muscarinic (M3) receptors, reducing bronchoconstriction and secretions.",
        indications: "COPD, asthma (add-on).",
        atc: ["R03BB"],
        example: "Ipratropium (short), tiotropium (long).",
        cautions: "Dry mouth, urinary retention.",
        tags: ["respiratory"],
      },
      {
        name: "Leukotriene modifiers",
        description: "Anti-inflammatory oral agents.",
        kind: "drug",
        className: "leukotriene modifier",
        mechanism: "Antagonize the cysteinyl-leukotriene receptor (montelukast) or inhibit 5-lipoxygenase (zileuton).",
        indications: "Asthma, allergic rhinitis.",
        atc: ["R03DC"],
        example: "Montelukast.",
        cautions: "Neuropsychiatric boxed warning (montelukast).",
        tags: ["respiratory"],
      },
      {
        name: "Methylxanthines",
        description: "Older bronchodilators.",
        kind: "drug",
        className: "bronchodilator",
        mechanism: "Nonselective phosphodiesterase inhibition and adenosine antagonism.",
        indications: "Asthma and COPD (limited role, narrow therapeutic index).",
        atc: ["R03DA"],
        example: "Theophylline.",
        cautions: "Narrow index; arrhythmia and seizure risk at high levels; TDM.",
        tags: ["respiratory"],
      },
      {
        name: "Biologics for severe asthma",
        description: "Targeted anti-inflammatory antibodies.",
        kind: "drug",
        className: "biologic",
        mechanism: "Monoclonal antibodies against IgE (omalizumab), IL-5 / IL-5R (mepolizumab, benralizumab), IL-4 / IL-13 (dupilumab), or TSLP.",
        indications: "Severe eosinophilic or allergic asthma; also atopic dermatitis (dupilumab).",
        atc: ["R03DX"],
        example: "Omalizumab, dupilumab.",
        tags: ["respiratory", "biologic"],
      },
      {
        name: "Antitussives, expectorants & mucolytics",
        description: "Cough and mucus agents.",
        kind: "drug",
        className: "cough / mucus agent",
        mechanism: "Central cough suppression (dextromethorphan, codeine); mucus thinning (guaifenesin, N-acetylcysteine).",
        indications: "Symptomatic cough and congestion.",
        atc: ["R05"],
        example: "Dextromethorphan, guaifenesin, acetylcysteine.",
        cautions: "Codeine controlled; dextromethorphan misuse potential.",
        tags: ["respiratory"],
      },
      {
        name: "Antihistamines (H1 antagonists)",
        description: "Allergy agents.",
        kind: "drug",
        className: "antihistamine",
        mechanism: "Inverse agonism/antagonism at the H1 histamine receptor; second-generation agents are non-sedating.",
        indications: "Allergic rhinitis, urticaria.",
        atc: ["R06A"],
        example: "Cetirizine, loratadine, diphenhydramine (first-gen).",
        cautions: "Anticholinergic effects with first-generation agents.",
        tags: ["respiratory", "allergy"],
      },
      {
        name: "Pulmonary hypertension agents",
        description: "Selective pulmonary vasodilators.",
        kind: "drug",
        className: "pulmonary vasodilator",
        mechanism: "Endothelin-receptor antagonists, PDE5 inhibitors, and prostacyclin analogues lower pulmonary vascular resistance.",
        indications: "Pulmonary arterial hypertension.",
        atc: ["C02KX", "G04BE"],
        example: "Bosentan, sildenafil, epoprostenol.",
        cautions: "Bosentan hepatotoxicity and teratogenicity (REMS).",
        tags: ["respiratory", "cardiovascular"],
      },
    ],
  },
];
