import type { Family } from "./types";

export const FAMILIES_7_11: Family[] = [
  // ── Family 7 ──────────────────────────────────────────────────────────────
  {
    slug: "gastrointestinal-drugs",
    number: 7,
    name: "Gastrointestinal Drugs",
    blurb: "ATC group A — acid suppression, antiemetics, laxatives, IBD agents, and functional-bowel drugs.",
    section: "C",
    color: "emerald",
    dataSource: "RxNorm / Drugs@FDA; WHO EML; openFDA/FAERS.",
    entries: [
      {
        name: "Proton pump inhibitors (PPIs)",
        description: "Potent acid suppressants.",
        kind: "drug",
        className: "acid suppressant",
        mechanism: "Irreversibly inhibit the gastric H+/K+-ATPase (proton pump).",
        indications: "GERD, peptic ulcer disease, H. pylori regimens, stress-ulcer prophylaxis.",
        atc: ["A02BC"],
        example: "Omeprazole, pantoprazole, esomeprazole.",
        cautions: "Long-term risks debated — fractures, C. difficile, hypomagnesemia; overuse concerns.",
        tags: ["GI"],
      },
      {
        name: "H2-receptor antagonists",
        description: "Acid-reducing agents.",
        kind: "drug",
        className: "acid suppressant",
        mechanism: "Block histamine H2 receptors on gastric parietal cells.",
        indications: "GERD, dyspepsia, ulcer disease.",
        atc: ["A02BA"],
        example: "Famotidine.",
        tags: ["GI"],
      },
      {
        name: "Antacids & mucosal protectants",
        description: "Neutralizers and barrier agents.",
        kind: "drug",
        className: "GI protectant",
        mechanism: "Neutralize gastric acid (aluminum, magnesium, calcium salts) or coat and protect mucosa (sucralfate, bismuth).",
        indications: "Dyspepsia, ulcer adjunct.",
        atc: ["A02A"],
        example: "Calcium carbonate, sucralfate.",
        tags: ["GI"],
      },
      {
        name: "Antiemetics — 5-HT3 antagonists",
        description: "Nausea blockers.",
        kind: "drug",
        className: "antiemetic",
        mechanism: "Antagonize 5-HT3 receptors centrally and in the gut.",
        indications: "Chemotherapy- and post-op nausea and vomiting.",
        atc: ["A04AA"],
        example: "Ondansetron.",
        cautions: "QT prolongation.",
        tags: ["GI"],
      },
      {
        name: "Antiemetics — other classes",
        description: "Dopamine, NK1, and antihistaminic agents.",
        kind: "drug",
        className: "antiemetic",
        mechanism: "D2 antagonism (metoclopramide, prochlorperazine), NK1 antagonism (aprepitant), or antihistaminic/antimuscarinic (promethazine, scopolamine).",
        indications: "Nausea and vomiting of varied cause.",
        atc: ["A04A", "A03F"],
        example: "Metoclopramide, aprepitant.",
        cautions: "Metoclopramide tardive dyskinesia (boxed warning).",
        tags: ["GI"],
      },
      {
        name: "Laxatives",
        description: "Constipation agents.",
        kind: "drug",
        className: "laxative",
        mechanism: "Osmotic (polyethylene glycol, lactulose), stimulant (senna, bisacodyl), or bulk-forming (psyllium).",
        indications: "Constipation, bowel preparation.",
        atc: ["A06A"],
        example: "PEG 3350, senna.",
        tags: ["GI"],
      },
      {
        name: "Antidiarrheals",
        description: "Gut-slowing agents.",
        kind: "drug",
        className: "antidiarrheal",
        mechanism: "Opioid-receptor agonism in the gut slows motility (loperamide); adsorbents bind toxins.",
        indications: "Symptomatic diarrhea.",
        atc: ["A07D"],
        example: "Loperamide.",
        cautions: "Loperamide misuse at high doses is associated with cardiac arrhythmia — reference-level mention only.",
        tags: ["GI"],
      },
      {
        name: "Inflammatory bowel disease agents",
        description: "Anti-inflammatory GI therapy.",
        kind: "drug",
        className: "IBD therapy",
        mechanism: "Aminosalicylates (5-ASA) act topically on gut mucosa; corticosteroids, immunomodulators, and biologics (anti-TNF, anti-integrin, anti-IL) target inflammation.",
        indications: "Ulcerative colitis, Crohn's disease.",
        atc: ["A07E"],
        example: "Mesalazine, infliximab, vedolizumab, ustekinumab.",
        cautions: "Biologic infection risk; JAK-inhibitor boxed warnings.",
        tags: ["GI", "immunology"],
      },
      {
        name: "Antispasmodics & IBS agents",
        description: "Functional-bowel drugs.",
        kind: "drug",
        className: "functional-bowel agent",
        mechanism: "Antimuscarinics reduce spasm; newer agents target gut secretion or motility (linaclotide, eluxadoline).",
        indications: "Irritable bowel syndrome, spasm.",
        atc: ["A03"],
        example: "Dicyclomine, linaclotide.",
        tags: ["GI"],
      },
    ],
  },

  // ── Family 8 ──────────────────────────────────────────────────────────────
  {
    slug: "endocrine-metabolic",
    number: 8,
    name: "Endocrine & Metabolic Agents",
    blurb: "ATC groups A (metabolism), H (hormones), G (sex hormones). Diabetes, thyroid, adrenal, sex-steroid, and bone-metabolism therapies — including the incretin era.",
    section: "D",
    color: "green",
    dataSource: "RxNorm / Drugs@FDA; WHO EML (essential insulins and endocrine agents); openFDA/FAERS.",
    entries: [
      {
        name: "Insulins",
        description: "Glucose-lowering hormone replacement.",
        kind: "drug",
        className: "hormone",
        mechanism: "Agonize the insulin receptor, driving cellular glucose uptake and anabolism. Formulations vary by onset and duration — rapid, short, intermediate, long, ultra-long.",
        indications: "Type 1 and advanced type 2 diabetes.",
        atc: ["A10A"],
        example: "Insulin glargine, insulin aspart, insulin degludec.",
        cautions: "Hypoglycemia is the principal adverse effect.",
        tags: ["endocrine", "diabetes"],
      },
      {
        name: "Biguanides (metformin)",
        description: "First-line oral antidiabetic.",
        kind: "drug",
        className: "antidiabetic",
        mechanism: "Reduce hepatic gluconeogenesis and improve insulin sensitivity (AMPK-linked pathways).",
        indications: "Type 2 diabetes.",
        atc: ["A10BA"],
        example: "Metformin.",
        cautions: "GI upset; rare lactic acidosis in renal failure.",
        tags: ["endocrine", "diabetes"],
      },
      {
        name: "Sulfonylureas & meglitinides",
        description: "Insulin secretagogues.",
        kind: "drug",
        className: "insulin secretagogue",
        mechanism: "Close the pancreatic beta-cell K-ATP channel, triggering insulin release.",
        indications: "Type 2 diabetes.",
        atc: ["A10BB", "A10BX"],
        example: "Glipizide, glimepiride, repaglinide.",
        cautions: "Hypoglycemia and weight gain.",
        tags: ["endocrine", "diabetes"],
      },
      {
        name: "DPP-4 inhibitors (gliptins)",
        description: "Incretin-enhancing oral agents.",
        kind: "drug",
        className: "incretin-based agent",
        mechanism: "Inhibit dipeptidyl peptidase-4, prolonging endogenous GLP-1 and GIP.",
        indications: "Type 2 diabetes.",
        atc: ["A10BH"],
        example: "Sitagliptin, linagliptin.",
        tags: ["endocrine", "diabetes"],
      },
      {
        name: "SGLT2 inhibitors (gliflozins)",
        description: "Glucose-excreting agents.",
        kind: "drug",
        className: "SGLT2 inhibitor",
        mechanism: "Block renal sodium-glucose cotransporter 2, promoting urinary glucose loss.",
        indications: "Type 2 diabetes, heart failure, chronic kidney disease.",
        atc: ["A10BK"],
        example: "Empagliflozin, dapagliflozin.",
        cautions: "Euglycemic DKA, genital mycotic infections, volume depletion.",
        tags: ["endocrine", "diabetes", "cardiovascular"],
      },
      {
        name: "GLP-1 receptor agonists",
        description: "Incretin-mimetic injectables and orals.",
        kind: "drug",
        className: "GLP-1 agonist",
        mechanism: "Agonize the GLP-1 receptor, enhancing glucose-dependent insulin secretion, slowing gastric emptying, and reducing appetite.",
        indications: "Type 2 diabetes, obesity and weight management.",
        atc: ["A10BJ"],
        example: "Semaglutide, liraglutide, dulaglutide.",
        cautions: "GI intolerance; medullary-thyroid-cancer boxed warning (rodent data); pancreatitis signal.",
        tags: ["endocrine", "diabetes", "obesity"],
      },
      {
        name: "Dual/triple incretin agonists",
        description: "Multi-receptor metabolic agents.",
        kind: "drug",
        className: "GLP-1 / GIP agonist",
        mechanism: "Co-agonize GIP and GLP-1 receptors (tirzepatide); triple GIP / GLP-1 / glucagon agents are emerging.",
        indications: "Type 2 diabetes, obesity.",
        atc: ["A10BX"],
        example: "Tirzepatide.",
        tags: ["endocrine", "diabetes", "obesity"],
      },
      {
        name: "Thyroid hormone & antithyroid agents",
        description: "Thyroid regulators.",
        kind: "drug",
        className: "thyroid agent",
        mechanism: "Levothyroxine replaces T4; thionamides (methimazole, propylthiouracil) inhibit thyroid hormone synthesis.",
        indications: "Hypothyroidism; hyperthyroidism.",
        atc: ["H03A", "H03B"],
        example: "Levothyroxine, methimazole.",
        cautions: "Levothyroxine narrow TSH targeting; PTU hepatotoxicity.",
        tags: ["endocrine"],
      },
      {
        name: "Glucocorticoids (systemic)",
        description: "Broad anti-inflammatory hormones.",
        kind: "drug",
        className: "corticosteroid",
        mechanism: "Glucocorticoid-receptor agonism regulating gene transcription, broadly anti-inflammatory and immunosuppressive.",
        indications: "Inflammation, autoimmune disease, adrenal insufficiency, many other conditions.",
        atc: ["H02AB"],
        example: "Prednisone, dexamethasone, hydrocortisone.",
        cautions: "Extensive with chronic use — osteoporosis, hyperglycemia, infection, HPA suppression.",
        tags: ["endocrine", "anti-inflammatory"],
      },
      {
        name: "Mineralocorticoids",
        description: "Salt-retaining hormones.",
        kind: "drug",
        className: "mineralocorticoid",
        mechanism: "Mineralocorticoid-receptor agonism promotes renal sodium retention.",
        indications: "Adrenal insufficiency, orthostatic hypotension.",
        atc: ["H02AA"],
        example: "Fludrocortisone.",
        tags: ["endocrine"],
      },
      {
        name: "Estrogens & progestogens / hormonal contraceptives",
        description: "Sex-hormone therapy and contraception.",
        kind: "drug",
        className: "sex hormone",
        mechanism: "Estrogen- and progesterone-receptor agonism; combined contraceptives suppress ovulation through feedback.",
        indications: "Contraception, menopausal hormone therapy, gynecologic conditions.",
        atc: ["G03"],
        example: "Ethinylestradiol/levonorgestrel, estradiol.",
        cautions: "Thromboembolism risk; breast-cancer risk with combined estrogen-progestin HRT; timing hypothesis debated.",
        tags: ["endocrine", "reproductive"],
      },
      {
        name: "Androgens & anabolic steroids (therapeutic)",
        description: "Androgen-receptor agents.",
        kind: "drug",
        className: "androgen",
        mechanism: "Androgen-receptor agonism.",
        indications: "Male hypogonadism, selected wasting conditions.",
        atc: ["G03B", "A14A"],
        example: "Testosterone.",
        cautions: "Erythrocytosis, cardiovascular signal, HPG suppression; described at reference and therapeutic level only.",
        schedule: "US Schedule III.",
        tags: ["endocrine", "controlled"],
      },
      {
        name: "SERMs & aromatase inhibitors",
        description: "Tissue-selective and estrogen-lowering agents.",
        kind: "drug",
        className: "SERM / aromatase inhibitor",
        mechanism: "SERMs act as estrogen agonists or antagonists by tissue (tamoxifen, raloxifene); aromatase inhibitors block estrogen synthesis (anastrozole).",
        indications: "Breast cancer, osteoporosis, ovulation induction.",
        atc: ["L02B", "G03XC"],
        example: "Tamoxifen, anastrozole.",
        cautions: "Tamoxifen endometrial-cancer and VTE risk; AI musculoskeletal effects.",
        tags: ["endocrine", "oncology"],
      },
      {
        name: "Bisphosphonates & bone agents",
        description: "Osteoporosis therapy.",
        kind: "drug",
        className: "bone agent",
        mechanism: "Bisphosphonates inhibit osteoclast-mediated bone resorption; denosumab inhibits RANKL; teriparatide and romosozumab are anabolic.",
        indications: "Osteoporosis, hypercalcemia, bone metastases.",
        atc: ["M05B"],
        example: "Alendronate, zoledronic acid, denosumab.",
        cautions: "Osteonecrosis of the jaw; atypical femur fractures.",
        tags: ["endocrine", "bone"],
      },
      {
        name: "Pituitary & hypothalamic agents",
        description: "Central endocrine regulators.",
        kind: "drug",
        className: "hypothalamic-pituitary agent",
        mechanism: "Analogues or antagonists of pituitary and hypothalamic hormones (GnRH, somatostatin, growth hormone, ADH).",
        indications: "Acromegaly, endometriosis, prostate cancer, diabetes insipidus, growth disorders.",
        atc: ["H01"],
        example: "Octreotide, leuprolide, desmopressin, somatropin.",
        tags: ["endocrine"],
      },
    ],
  },

  // ── Family 9 ──────────────────────────────────────────────────────────────
  {
    slug: "antibacterials",
    number: 9,
    name: "Antibacterials (Antibiotics)",
    blurb: "ATC group J01. Organized by mechanism and class; the WHO AWaRe framework (Access / Watch / Reserve) is a stewardship overlay. Antimicrobial resistance is a cross-cutting caution.",
    section: "D",
    color: "amber",
    dataSource: "RxNorm / Drugs@FDA; WHO EML; WHO AWaRe antibiotic classification; openFDA/FAERS.",
    entries: [
      {
        name: "Penicillins",
        description: "Beta-lactam cell-wall agents.",
        kind: "drug",
        className: "beta-lactam antibiotic",
        mechanism: "Inhibit penicillin-binding proteins, blocking peptidoglycan cross-linking; bactericidal.",
        indications: "Streptococcal, syphilis, and many gram-positive and selected gram-negative infections.",
        atc: ["J01C"],
        example: "Penicillin G, amoxicillin, piperacillin.",
        cautions: "Anaphylaxis; cross-reactivity with other beta-lactams.",
        tags: ["anti-infective", "beta-lactam"],
      },
      {
        name: "Beta-lactam / beta-lactamase-inhibitor combinations",
        description: "Resistance-restoring pairs.",
        kind: "drug",
        className: "beta-lactam antibiotic",
        mechanism: "Pair a beta-lactam with an inhibitor (clavulanate, tazobactam, avibactam) that protects it from beta-lactamases.",
        indications: "Infections by beta-lactamase-producing organisms.",
        atc: ["J01CR"],
        example: "Amoxicillin/clavulanate, piperacillin/tazobactam.",
        tags: ["anti-infective", "beta-lactam"],
      },
      {
        name: "Cephalosporins",
        description: "Beta-lactams by generation.",
        kind: "drug",
        className: "beta-lactam antibiotic",
        mechanism: "PBP inhibition; successive generations broaden gram-negative coverage.",
        indications: "Wide range by generation — skin and soft tissue, meningitis, resistant gram-negatives.",
        atc: ["J01D"],
        example: "Cefazolin (1st), ceftriaxone (3rd), cefepime (4th), ceftaroline (anti-MRSA).",
        tags: ["anti-infective", "beta-lactam"],
      },
      {
        name: "Carbapenems",
        description: "Broad-spectrum beta-lactams.",
        kind: "drug",
        className: "beta-lactam antibiotic",
        mechanism: "PBP inhibition, stable against many beta-lactamases; bactericidal and very broad.",
        indications: "Severe or multidrug-resistant gram-negative infections (reserve).",
        atc: ["J01DH"],
        example: "Meropenem, imipenem/cilastatin.",
        cautions: "Emerging carbapenem resistance is a major stewardship concern.",
        tags: ["anti-infective", "beta-lactam", "reserve"],
        xref: ["public-health"],
      },
      {
        name: "Monobactams",
        description: "Gram-negative beta-lactams.",
        kind: "drug",
        className: "beta-lactam antibiotic",
        mechanism: "PBP3 inhibition, active against aerobic gram-negatives only.",
        indications: "Gram-negative infection, including in penicillin allergy.",
        atc: ["J01DF"],
        example: "Aztreonam.",
        tags: ["anti-infective", "beta-lactam"],
      },
      {
        name: "Glycopeptides",
        description: "Gram-positive cell-wall agents.",
        kind: "drug",
        className: "glycopeptide antibiotic",
        mechanism: "Bind the D-Ala-D-Ala terminus of peptidoglycan precursors, blocking cross-linking.",
        indications: "MRSA and serious gram-positive infections.",
        atc: ["J01XA"],
        example: "Vancomycin, teicoplanin.",
        cautions: "Vancomycin requires TDM; nephrotoxicity; VRE emergence.",
        tags: ["anti-infective"],
      },
      {
        name: "Aminoglycosides",
        description: "Protein-synthesis inhibitors (30S).",
        kind: "drug",
        className: "aminoglycoside antibiotic",
        mechanism: "Bind the 30S ribosomal subunit, causing misreading; bactericidal and concentration-dependent.",
        indications: "Serious gram-negative infections, synergy with cell-wall agents.",
        atc: ["J01G"],
        example: "Gentamicin, amikacin, tobramycin.",
        cautions: "Nephro- and ototoxicity; requires TDM.",
        tags: ["anti-infective"],
      },
      {
        name: "Tetracyclines & glycylcyclines",
        description: "Broad 30S inhibitors.",
        kind: "drug",
        className: "tetracycline antibiotic",
        mechanism: "Bind the 30S subunit, blocking aminoacyl-tRNA binding; bacteriostatic.",
        indications: "Atypical pathogens, acne, rickettsia, tick-borne disease; tigecycline for resistant organisms.",
        atc: ["J01A"],
        example: "Doxycycline, minocycline, tigecycline.",
        cautions: "Photosensitivity; tooth discoloration in children.",
        tags: ["anti-infective"],
      },
      {
        name: "Macrolides",
        description: "50S protein-synthesis inhibitors.",
        kind: "drug",
        className: "macrolide antibiotic",
        mechanism: "Bind the 50S ribosomal subunit, blocking translocation.",
        indications: "Respiratory, atypical, and some sexually transmitted infections.",
        atc: ["J01FA"],
        example: "Azithromycin, clarithromycin, erythromycin.",
        cautions: "QT prolongation; CYP3A4 interactions.",
        tags: ["anti-infective"],
      },
      {
        name: "Lincosamides",
        description: "50S inhibitors for anaerobes and gram-positives.",
        kind: "drug",
        className: "lincosamide antibiotic",
        mechanism: "Bind the 50S subunit, inhibiting translocation.",
        indications: "Anaerobic and gram-positive infections, toxin suppression.",
        atc: ["J01FF"],
        example: "Clindamycin.",
        cautions: "C. difficile colitis.",
        tags: ["anti-infective"],
      },
      {
        name: "Fluoroquinolones",
        description: "DNA-topoisomerase inhibitors.",
        kind: "drug",
        className: "quinolone antibiotic",
        mechanism: "Inhibit DNA gyrase and topoisomerase IV, blocking replication; bactericidal.",
        indications: "Urinary, respiratory, GI, and selected resistant infections.",
        atc: ["J01M"],
        example: "Ciprofloxacin, levofloxacin, moxifloxacin.",
        cautions: "Tendon rupture, QT prolongation, peripheral neuropathy — multiple boxed warnings.",
        tags: ["anti-infective"],
      },
      {
        name: "Sulfonamides & trimethoprim",
        description: "Folate-synthesis inhibitors.",
        kind: "drug",
        className: "folate-pathway inhibitor",
        mechanism: "Sequentially block dihydropteroate synthase (sulfonamides) and dihydrofolate reductase (trimethoprim), starving folate synthesis.",
        indications: "Urinary tract infections, PCP prophylaxis and treatment, MRSA (skin).",
        atc: ["J01E"],
        example: "Trimethoprim/sulfamethoxazole.",
        cautions: "Hypersensitivity, Stevens-Johnson syndrome; hyperkalemia.",
        tags: ["anti-infective"],
      },
      {
        name: "Nitroimidazoles",
        description: "Anaerobe and protozoal agents.",
        kind: "drug",
        className: "nitroimidazole",
        mechanism: "Reduced intracellularly to reactive species that damage microbial DNA.",
        indications: "Anaerobic infections, C. difficile, protozoa (Giardia, Trichomonas), H. pylori regimens.",
        atc: ["J01XD", "P01AB"],
        example: "Metronidazole.",
        cautions: "Disulfiram-like reaction with alcohol; neuropathy with prolonged use.",
        tags: ["anti-infective"],
      },
      {
        name: "Oxazolidinones",
        description: "Gram-positive 50S inhibitors.",
        kind: "drug",
        className: "oxazolidinone antibiotic",
        mechanism: "Bind the 50S subunit at initiation, blocking protein synthesis.",
        indications: "Resistant gram-positives (MRSA, VRE).",
        atc: ["J01XX"],
        example: "Linezolid.",
        cautions: "Serotonergic interactions; cytopenias with prolonged use.",
        tags: ["anti-infective", "reserve"],
      },
      {
        name: "Lipopeptides",
        description: "Membrane-disrupting gram-positive agents.",
        kind: "drug",
        className: "lipopeptide antibiotic",
        mechanism: "Daptomycin inserts into the bacterial membrane, causing depolarization.",
        indications: "MRSA bacteremia, skin infections (not pneumonia — inactivated by surfactant).",
        atc: ["J01XX"],
        example: "Daptomycin.",
        cautions: "CPK elevation and myopathy.",
        tags: ["anti-infective"],
      },
      {
        name: "Novel bacterial-topoisomerase inhibitors",
        description: "First-in-class antibacterials.",
        kind: "drug",
        className: "topoisomerase inhibitor",
        mechanism: "Triazaacenaphthylenes inhibit two bacterial type-II topoisomerase enzymes by a novel mechanism, retaining activity against many fluoroquinolone-resistant strains.",
        indications: "Uncomplicated urinary tract infection and urogenital gonorrhea.",
        atc: ["J01"],
        example: "Gepotidacin (approved 2025).",
        cautions: "First-in-class; long-term real-world data still accumulating.",
        status: "needs-verification",
        tags: ["anti-infective"],
      },
      {
        name: "Antimycobacterials (anti-TB & leprosy)",
        description: "Mycobacterial agents.",
        kind: "drug",
        className: "antimycobacterial",
        mechanism: "Varied — isoniazid inhibits mycolic-acid synthesis; rifampin inhibits RNA polymerase; ethambutol blocks arabinogalactan synthesis; pyrazinamide disrupts membrane energetics; bedaquiline inhibits ATP synthase.",
        indications: "Tuberculosis (multidrug regimens), leprosy.",
        atc: ["J04A"],
        example: "Isoniazid, rifampin, ethambutol, pyrazinamide, bedaquiline.",
        cautions: "Isoniazid hepatotoxicity; ethambutol optic neuritis; rifampin enzyme induction.",
        tags: ["anti-infective"],
        xref: ["public-health"],
      },
    ],
  },

  // ── Family 10 ─────────────────────────────────────────────────────────────
  {
    slug: "antivirals-antifungals-antiparasitics",
    number: 10,
    name: "Antivirals, Antifungals & Antiparasitics",
    blurb: "ATC groups J02, J05, P01, P02. Antiviral cures and long-term suppression, antifungal expansion, and neglected-tropical-disease agents.",
    section: "D",
    color: "amber",
    dataSource: "RxNorm / Drugs@FDA; WHO EML; openFDA/FAERS.",
    entries: [
      {
        name: "Anti-herpesvirus nucleoside analogues",
        description: "Herpes and VZV agents.",
        kind: "drug",
        className: "antiviral",
        mechanism: "Nucleoside analogues phosphorylated by viral thymidine kinase, then inhibiting viral DNA polymerase.",
        indications: "HSV, varicella-zoster, CMV.",
        atc: ["J05AB"],
        example: "Acyclovir, valacyclovir, ganciclovir.",
        cautions: "Nephrotoxicity with poor hydration; ganciclovir cytopenias.",
        tags: ["anti-infective", "antiviral"],
      },
      {
        name: "Antiretrovirals (HIV) — NRTIs & NNRTIs",
        description: "Reverse-transcriptase inhibitors.",
        kind: "drug",
        className: "antiretroviral",
        mechanism: "NRTIs are chain-terminating nucleoside analogues; NNRTIs bind reverse transcriptase allosterically.",
        indications: "HIV infection (combination ART).",
        atc: ["J05AF", "J05AG"],
        example: "Tenofovir, emtricitabine, efavirenz.",
        cautions: "Tenofovir renal and bone effects; efavirenz neuropsychiatric effects.",
        tags: ["antiviral"],
        xref: ["public-health"],
      },
      {
        name: "Antiretrovirals (HIV) — protease & integrase inhibitors",
        description: "Later-step HIV blockers.",
        kind: "drug",
        className: "antiretroviral",
        mechanism: "Protease inhibitors block viral maturation; integrase strand-transfer inhibitors (INSTIs) block proviral integration.",
        indications: "HIV (combination ART; INSTIs are backbone therapy).",
        atc: ["J05AR", "J05AX", "J05AJ"],
        example: "Dolutegravir, bictegravir, darunavir.",
        cautions: "INSTI weight gain signal; PI GI intolerance and metabolic effects.",
        tags: ["antiviral"],
      },
      {
        name: "HIV pre-exposure prophylaxis (PrEP)",
        description: "Prevention pharmacotherapy.",
        kind: "drug",
        className: "antiretroviral prevention",
        mechanism: "Antiretrovirals taken before exposure to prevent HIV acquisition — oral tenofovir-based, or long-acting injectables.",
        indications: "HIV prevention in at-risk individuals.",
        atc: ["J05AR", "J05AJ"],
        example: "Tenofovir/emtricitabine, cabotegravir (long-acting), lenacapavir.",
        tags: ["antiviral"],
        xref: ["public-health"],
      },
      {
        name: "Anti-hepatitis agents",
        description: "HBV and HCV therapy.",
        kind: "drug",
        className: "antiviral",
        mechanism: "HBV nucleos(t)ide analogues suppress viral polymerase; HCV direct-acting antivirals target NS3/4A protease, NS5A, and NS5B polymerase (curative regimens).",
        indications: "Chronic hepatitis B (suppression); hepatitis C (cure).",
        atc: ["J05AP", "J05AF"],
        example: "Entecavir, tenofovir (HBV); sofosbuvir/velpatasvir (HCV).",
        tags: ["antiviral"],
      },
      {
        name: "Anti-influenza & broad antivirals",
        description: "Respiratory-virus and pandemic agents.",
        kind: "drug",
        className: "antiviral",
        mechanism: "Neuraminidase inhibitors (oseltamivir) block viral release; endonuclease inhibitors (baloxavir); polymerase and protease inhibitors used for other RNA viruses.",
        indications: "Influenza; selected emerging viral infections.",
        atc: ["J05A"],
        example: "Oseltamivir, baloxavir.",
        tags: ["antiviral"],
        xref: ["public-health"],
      },
      {
        name: "Azole antifungals",
        description: "Ergosterol-synthesis inhibitors.",
        kind: "drug",
        className: "antifungal",
        mechanism: "Inhibit fungal CYP51 (lanosterol 14-alpha-demethylase), depleting ergosterol.",
        indications: "Candidiasis, aspergillosis, dermatophytes, endemic mycoses.",
        atc: ["J02AC"],
        example: "Fluconazole, voriconazole, itraconazole, isavuconazole.",
        cautions: "CYP interactions; voriconazole visual and hepatic effects.",
        tags: ["antifungal"],
      },
      {
        name: "Polyene & echinocandin antifungals",
        description: "Membrane and cell-wall antifungals.",
        kind: "drug",
        className: "antifungal",
        mechanism: "Polyenes (amphotericin B) bind ergosterol and form membrane pores; echinocandins inhibit beta-1,3-glucan synthase (cell wall).",
        indications: "Invasive and systemic fungal infections.",
        atc: ["J02A"],
        example: "Amphotericin B, caspofungin, micafungin.",
        cautions: "Amphotericin infusion reactions and nephrotoxicity.",
        tags: ["antifungal"],
      },
      {
        name: "Antimalarials",
        description: "Plasmodium agents.",
        kind: "drug",
        className: "antimalarial",
        mechanism: "Varied — artemisinins generate reactive radicals; 4-aminoquinolines (chloroquine) interfere with heme detoxification; others target folate or mitochondrial transport.",
        indications: "Malaria treatment and prophylaxis.",
        atc: ["P01B"],
        example: "Artemisinin-based combination therapy, chloroquine, atovaquone/proguanil.",
        cautions: "Emerging artemisinin resistance; chloroquine retinal toxicity with long use.",
        tags: ["antiparasitic"],
        xref: ["public-health"],
      },
      {
        name: "Anthelmintics & antiprotozoals",
        description: "Worm and protozoal agents.",
        kind: "drug",
        className: "antiparasitic",
        mechanism: "Benzimidazoles inhibit helminth microtubules; ivermectin activates invertebrate glutamate-gated chloride channels; praziquantel disrupts fluke and tapeworm membranes.",
        indications: "Helminth and protozoal infections.",
        atc: ["P02", "P01"],
        example: "Albendazole, ivermectin, praziquantel.",
        tags: ["antiparasitic"],
        xref: ["public-health"],
      },
      {
        name: "Antiseptics & disinfectants",
        description: "Topical and surface antimicrobials.",
        kind: "drug",
        className: "antiseptic",
        mechanism: "Nonspecific microbicidal action — oxidation, protein denaturation, membrane disruption.",
        indications: "Skin antisepsis, surface disinfection.",
        atc: ["D08A"],
        example: "Chlorhexidine, povidone-iodine, alcohol.",
        tags: ["anti-infective", "topical"],
      },
    ],
  },

  // ── Family 11 ─────────────────────────────────────────────────────────────
  {
    slug: "antineoplastics-immunomodulators",
    number: 11,
    name: "Antineoplastics & Immunomodulators (Oncology & Immunology)",
    blurb: "ATC group L. The most rapidly evolving family; targeted and immuno-oncology agents dominate recent approvals. Adverse-effect classes are quarantined to the cautions field.",
    section: "D",
    color: "rose",
    dataSource: "RxNorm / Drugs@FDA; WHO EML (essential oncology); openFDA/FAERS.",
    entries: [
      {
        name: "Alkylating agents",
        description: "DNA-crosslinking cytotoxics.",
        kind: "drug",
        className: "cytotoxic",
        mechanism: "Covalently alkylate DNA, causing crosslinks and strand breaks that block replication.",
        indications: "Many hematologic and solid tumors, transplant conditioning.",
        atc: ["L01A"],
        example: "Cyclophosphamide, cisplatin (platinum), temozolomide.",
        cautions: "Myelosuppression, secondary malignancy, cisplatin nephro- and ototoxicity.",
        tags: ["oncology", "cytotoxic"],
      },
      {
        name: "Antimetabolites",
        description: "Nucleotide-pathway inhibitors.",
        kind: "drug",
        className: "cytotoxic",
        mechanism: "Mimic metabolites to block DNA and RNA synthesis (antifolates, pyrimidine and purine analogues).",
        indications: "Leukemias, GI and breast cancers; also autoimmune disease (methotrexate).",
        atc: ["L01B"],
        example: "Methotrexate, 5-fluorouracil, gemcitabine.",
        cautions: "Myelosuppression, mucositis; DPYD deficiency worsens 5-FU toxicity.",
        tags: ["oncology", "cytotoxic"],
      },
      {
        name: "Mitotic inhibitors (taxanes & vinca alkaloids)",
        description: "Microtubule-targeting cytotoxics.",
        kind: "drug",
        className: "cytotoxic",
        mechanism: "Taxanes stabilize microtubules; vinca alkaloids prevent their assembly — both arrest mitosis.",
        indications: "Breast, lung, ovarian, and hematologic cancers.",
        atc: ["L01C"],
        example: "Paclitaxel, docetaxel, vincristine.",
        cautions: "Peripheral neuropathy; vinca neurotoxicity; taxane hypersensitivity.",
        tags: ["oncology", "cytotoxic"],
      },
      {
        name: "Topoisomerase inhibitors (cytotoxic)",
        description: "DNA-unwinding-enzyme poisons.",
        kind: "drug",
        className: "cytotoxic",
        mechanism: "Inhibit topoisomerase I or II, causing lethal DNA breaks.",
        indications: "Colorectal, lung, ovarian, and hematologic cancers.",
        atc: ["L01C", "L01D"],
        example: "Irinotecan, etoposide, doxorubicin (anthracycline).",
        cautions: "Anthracycline cardiotoxicity; irinotecan diarrhea.",
        tags: ["oncology", "cytotoxic"],
      },
      {
        name: "Tyrosine kinase inhibitors (TKIs)",
        description: "Targeted small-molecule inhibitors.",
        kind: "drug",
        className: "targeted therapy",
        mechanism: "Inhibit specific tyrosine kinases driving tumor growth — BCR-ABL, EGFR, ALK, BTK, VEGFR, and others.",
        indications: "CML, EGFR/ALK-mutant lung cancer, renal cancer, CLL, and more.",
        atc: ["L01E"],
        example: "Imatinib, osimertinib, ibrutinib.",
        cautions: "Diverse — cardiotoxicity, hepatotoxicity, hypertension by agent.",
        tags: ["oncology", "targeted"],
      },
      {
        name: "Monoclonal antibodies (anti-tumor)",
        description: "Antigen-targeted biologics.",
        kind: "drug",
        className: "monoclonal antibody",
        mechanism: "Bind tumor-associated antigens (CD20, HER2, VEGF, EGFR), triggering immune clearance or blocking growth signals.",
        indications: "Lymphoma, HER2+ breast cancer, colorectal cancer, and others.",
        atc: ["L01F"],
        example: "Rituximab, trastuzumab, bevacizumab.",
        cautions: "Infusion reactions; trastuzumab cardiotoxicity; bevacizumab hypertension and bleeding.",
        tags: ["oncology", "biologic"],
      },
      {
        name: "Immune checkpoint inhibitors",
        description: "T-cell-unleashing immunotherapy.",
        kind: "drug",
        className: "checkpoint inhibitor",
        mechanism: "Block inhibitory checkpoints (PD-1, PD-L1, CTLA-4), restoring antitumor T-cell activity.",
        indications: "Melanoma, lung, renal, bladder, and many other cancers.",
        atc: ["L01F"],
        example: "Pembrolizumab, nivolumab, ipilimumab.",
        cautions: "Immune-related adverse events across essentially every organ system.",
        tags: ["oncology", "immuno-oncology"],
      },
      {
        name: "Antibody-drug conjugates (ADCs)",
        description: "Targeted cytotoxic delivery.",
        kind: "drug",
        className: "targeted therapy",
        mechanism: "A tumor-antigen antibody linked to a cytotoxic payload delivers chemotherapy selectively to tumor cells.",
        indications: "HER2+ breast and gastric cancer, urothelial and hematologic cancers.",
        atc: ["L01F"],
        example: "Trastuzumab deruxtecan, brentuximab vedotin.",
        cautions: "Payload-specific toxicities — interstitial lung disease, cytopenias.",
        tags: ["oncology", "targeted"],
      },
      {
        name: "CAR-T & cellular immunotherapies",
        description: "Engineered-cell therapy.",
        kind: "drug",
        className: "cell therapy",
        mechanism: "A patient's T cells are engineered with a chimeric antigen receptor to recognize and kill tumor cells.",
        indications: "Refractory B-cell malignancies, multiple myeloma.",
        atc: ["L01X"],
        example: "Tisagenlecleucel, axicabtagene ciloleucel.",
        cautions: "Cytokine release syndrome and neurotoxicity — REMS-managed.",
        tags: ["oncology", "cell-therapy"],
      },
      {
        name: "PARP inhibitors & targeted DNA-repair agents",
        description: "Synthetic-lethality agents.",
        kind: "drug",
        className: "targeted therapy",
        mechanism: "Inhibit PARP, causing lethal DNA damage in homologous-recombination-deficient (e.g. BRCA-mutant) tumors.",
        indications: "Ovarian, breast, prostate, and pancreatic cancers with DNA-repair defects.",
        atc: ["L01XK"],
        example: "Olaparib, niraparib.",
        cautions: "MDS/AML signal with long-term use.",
        tags: ["oncology", "targeted"],
      },
      {
        name: "Menin inhibitors",
        description: "First-in-class leukemia agents.",
        kind: "drug",
        className: "targeted therapy",
        mechanism: "Disrupt the menin - KMT2A (MLL) protein interaction driving leukemic transcription.",
        indications: "Relapsed or refractory KMT2A-rearranged or NPM1-mutated acute leukemia.",
        atc: ["L01X"],
        example: "Revumenib.",
        cautions: "Differentiation syndrome; first-in-class, real-world data accumulating.",
        status: "needs-verification",
        tags: ["oncology", "targeted"],
      },
      {
        name: "Hormonal antineoplastics",
        description: "Endocrine cancer therapy.",
        kind: "drug",
        className: "endocrine oncology",
        mechanism: "Deprive hormone-dependent tumors of driving hormones — antiandrogens, GnRH agonists and antagonists, aromatase inhibitors, antiestrogens.",
        indications: "Prostate and breast cancer.",
        atc: ["L02"],
        example: "Enzalutamide, leuprolide, letrozole, tamoxifen.",
        tags: ["oncology", "endocrine"],
      },
      {
        name: "Immunosuppressants (transplant & autoimmune)",
        description: "Immune-dampening agents.",
        kind: "drug",
        className: "immunosuppressant",
        mechanism: "Calcineurin inhibitors (block T-cell IL-2), mTOR inhibitors, antimetabolites, and depleting antibodies suppress immune responses.",
        indications: "Transplant rejection prophylaxis, autoimmune disease.",
        atc: ["L04A"],
        example: "Tacrolimus, cyclosporine, mycophenolate, sirolimus.",
        cautions: "Nephrotoxicity, infection, malignancy risk; tacrolimus and cyclosporine require TDM.",
        tags: ["immunology", "transplant"],
      },
      {
        name: "Biologic DMARDs (anti-cytokine)",
        description: "Targeted immunomodulators.",
        kind: "drug",
        className: "biologic DMARD",
        mechanism: "Monoclonal antibodies or fusion proteins neutralizing cytokines and receptors (TNF-alpha, IL-6, IL-17, IL-23, IL-1) or depleting immune cells.",
        indications: "Rheumatoid arthritis, psoriasis, IBD, and other immune-mediated diseases.",
        atc: ["L04AB", "L04AC"],
        example: "Adalimumab, etanercept, tocilizumab, secukinumab, ustekinumab.",
        cautions: "Serious infections including TB reactivation; screening required.",
        tags: ["immunology", "biologic"],
      },
      {
        name: "Conventional & targeted synthetic DMARDs",
        description: "Small-molecule disease modifiers.",
        kind: "drug",
        className: "DMARD",
        mechanism: "Methotrexate and others broadly modulate immunity; JAK inhibitors block Janus-kinase intracellular signaling.",
        indications: "Rheumatoid arthritis and other autoimmune diseases.",
        atc: ["L04AA", "L04AF"],
        example: "Methotrexate, hydroxychloroquine, tofacitinib.",
        cautions: "JAK-inhibitor boxed warnings — cardiovascular events, malignancy, thrombosis.",
        tags: ["immunology"],
      },
      {
        name: "Interferons & immunostimulants",
        description: "Immune-activating agents.",
        kind: "drug",
        className: "immunostimulant",
        mechanism: "Interferons and other cytokines stimulate antiviral and antitumor immunity; some vaccines, adjuvants, and colony-stimulating factors also fit here.",
        indications: "Multiple sclerosis, some cancers and viral infections.",
        atc: ["L03"],
        example: "Interferon beta, peginterferon.",
        cautions: "Flu-like syndrome, depression, cytopenias.",
        tags: ["immunology"],
      },
    ],
  },
];
