import type { Family } from "./types";

export const FAMILIES_15_22: Family[] = [
  // ── Family 15 ─────────────────────────────────────────────────────────────
  {
    slug: "international-law",
    number: 15,
    name: "International Law",
    blurb: "Rules between states — treaties, custom, jurisdiction, and the law of armed conflict.",
    section: "D",
    color: "amber",
    entries: [
      {
        name: "Sources of international law",
        description: "Treaties, custom, general principles, judicial decisions, and scholarly writings.",
        keyPrinciple: "ICJ Statute Article 38. Hierarchy debated; treaties and custom are co-equal primary sources. Jus cogens norms (peremptory) override all other rules.",
        tags: ["international", "sources"],
      },
      {
        name: "Pacta sunt servanda",
        description: "Treaties must be performed in good faith.",
        keyPrinciple: "Vienna Convention on the Law of Treaties (1969) Article 26. Foundational principle of treaty law. Exceptions: rebus sic stantibus (fundamental change of circumstances), material breach, impossibility.",
        tags: ["international", "treaties"],
      },
      {
        name: "Customary international law",
        description: "Unwritten rules derived from consistent state practice plus opinio juris.",
        keyPrinciple: "Two-element test (North Sea Continental Shelf, ICJ 1969): general and consistent practice + sense of legal obligation. Persistent objector may escape new rules; cannot escape jus cogens.",
        tags: ["international", "custom"],
      },
      {
        name: "Sovereign immunity",
        description: "States are immune from suit in foreign courts except in specific circumstances.",
        keyPrinciple: "Restrictive theory: immunity for sovereign (jure imperii) acts only, not commercial (jure gestionis) acts. Foreign Sovereign Immunities Act (1976, U.S.). Recent debate over jus cogens exception (Jurisdictional Immunities, ICJ 2012, rejected).",
        tags: ["international", "immunity"],
      },
      {
        name: "Jus cogens (peremptory norms)",
        description: "Fundamental rules of international law from which no derogation is permitted.",
        keyPrinciple: "Examples: prohibition of genocide, slavery, torture, aggressive war, apartheid. VCLT Article 53. Treaties conflicting with jus cogens are void.",
        tags: ["international", "jus-cogens"],
      },
      {
        name: "Geneva Conventions (IHL)",
        description: "Four 1949 conventions plus protocols governing the conduct of armed conflict.",
        keyPrinciple: "Protect wounded soldiers, shipwrecked sailors, prisoners of war, and civilians. Common Article 3 applies to non-international armed conflict. Grave breaches are prosecutable as war crimes.",
        tags: ["international", "IHL", "geneva"],
      },
      {
        name: "International criminal law",
        description: "Individual liability for genocide, war crimes, crimes against humanity, and aggression.",
        keyPrinciple: "Nuremberg principles (1945) established individual criminal responsibility. Rome Statute (1998) created ICC for ratifying states. US, China, Russia, India have not ratified. Universal jurisdiction available for certain core crimes.",
        tags: ["international", "criminal", "ICC"],
      },
      {
        name: "UN Charter and use of force",
        description: "Prohibits use of force in international relations with two exceptions: self-defense and UNSC authorization.",
        keyPrinciple: "UN Charter Articles 2(4), 51, Chapter VII. Self-defense requires an armed attack and meets necessity, proportionality, and immediacy. R2P (Responsibility to Protect) emerging norm, contested status.",
        tags: ["international", "use-of-force", "UN"],
      },
      {
        name: "Diplomatic and consular law",
        description: "Inviolability of diplomatic premises, persons, and communications.",
        keyPrinciple: "Vienna Convention on Diplomatic Relations (1961). Diplomats immune from criminal and most civil jurisdiction; declared persona non grata may be expelled. US Embassy hostage case (Iran-US Hostages, ICJ 1980) affirms inviolability even in revolution.",
        tags: ["international", "diplomatic"],
      },
      {
        name: "Law of the sea (UNCLOS)",
        description: "Comprehensive treaty regulating maritime zones, navigation, and resources.",
        keyPrinciple: "United Nations Convention on the Law of the Sea (1982). Territorial sea (12 nm), contiguous zone (24 nm), exclusive economic zone (200 nm), continental shelf. US has not ratified but follows most provisions as customary law.",
        tags: ["international", "UNCLOS", "maritime"],
      },
      {
        name: "WTO and trade law",
        description: "Multilateral framework governing international trade.",
        keyPrinciple: "GATT 1994, GATS, TRIPS. Most-favored-nation and national treatment principles. Dispute settlement appellate body paralyzed since 2019 due to U.S. blocking appointments.",
        tags: ["international", "trade", "WTO"],
        status: "contested",
      },
      {
        name: "State responsibility (ARSIWA)",
        description: "Rules on when conduct is attributable to a state and the consequences of internationally wrongful acts.",
        keyPrinciple: "ILC Articles on Responsibility of States for Internationally Wrongful Acts (2001). Attribution: organs, persons exercising governmental authority, persons acting on instructions or under direction/control. Consequences: cessation, reparation, countermeasures.",
        tags: ["international", "responsibility"],
      },
    ],
  },

  // ── Family 16 ─────────────────────────────────────────────────────────────
  {
    slug: "human-rights-law",
    number: 16,
    name: "Human Rights Law",
    blurb: "International and constitutional protections of individual rights against state action.",
    section: "D",
    color: "amber",
    entries: [
      {
        name: "Universal Declaration of Human Rights",
        description: "1948 UN General Assembly declaration of fundamental human rights.",
        keyPrinciple: "Non-binding but foundational. Inspired binding covenants (ICCPR, ICESCR) and regional systems. Often invoked as evidence of customary norms.",
        tags: ["human-rights", "UDHR"],
      },
      {
        name: "ICCPR (civil and political rights)",
        description: "1966 binding treaty on civil and political rights.",
        keyPrinciple: "International Covenant on Civil and Political Rights. Human Rights Committee monitors. Protects life, liberty, fair trial, expression, religion, equality. Some rights non-derogable even in emergency.",
        tags: ["human-rights", "ICCPR"],
      },
      {
        name: "ICESCR (economic, social, cultural)",
        description: "1966 binding treaty on economic, social, and cultural rights.",
        keyPrinciple: "Progressive realization (Art. 2): states obligated to take steps to the maximum of available resources. Includes work, social security, family protection, health, education, cultural participation. US has signed but not ratified.",
        tags: ["human-rights", "ICESCR"],
      },
      {
        name: "ECHR / European Convention",
        description: "Council of Europe regional human rights instrument with binding court.",
        keyPrinciple: "European Convention on Human Rights (1950). European Court of Human Rights (Strasbourg) hears individual petitions after exhaustion of domestic remedies. Margin of appreciation doctrine. UK Human Rights Act 1998 domesticated.",
        tags: ["human-rights", "ECHR"],
      },
      {
        name: "Prohibition of torture",
        description: "Absolute prohibition with no exception, even in war or emergency.",
        keyPrinciple: "Convention Against Torture (1984). Jus cogens. Non-refoulement to torture is also absolute. Definition: severe pain or suffering, intentionally inflicted, by or with state acquiescence, for a prohibited purpose.",
        tags: ["human-rights", "torture", "jus-cogens"],
      },
      {
        name: "Non-refoulement",
        description: "States cannot return refugees to a country where they face persecution.",
        keyPrinciple: "1951 Refugee Convention Art. 33; CAT Art. 3. Applies regardless of immigration status. Exceptions for serious crimes are narrowly construed.",
        tags: ["human-rights", "refugee", "non-refoulement"],
      },
      {
        name: "Genocide Convention",
        description: "Defines and criminalizes acts intended to destroy a national, ethnic, racial, or religious group.",
        keyPrinciple: "1948 Convention. Five acts: killing, serious bodily/mental harm, deliberately inflicting conditions of destruction, preventing births, transferring children. Specific intent (dolus specialis) required.",
        tags: ["human-rights", "genocide"],
      },
      {
        name: "Habeas corpus",
        description: "Writ requiring custodian to justify the legality of detention.",
        keyPrinciple: "Origin: Magna Carta (1215) and Habeas Corpus Act (1679). Suspendable only in narrow circumstances (rebellion, invasion). Boumediene v. Bush (2008) extended to Guantanamo detainees.",
        citation: "Boumediene v. Bush, 553 U.S. 723 (2008)",
        tags: ["human-rights", "habeas", "liberty"],
      },
      {
        name: "Freedom from arbitrary detention",
        description: "Detention must be lawful, non-arbitrary, and subject to judicial control.",
        keyPrinciple: "ICCPR Art. 9. Working Group on Arbitrary Detention (UN). Prolonged pretrial detention, secret detention, and incommunicado detention are particularly scrutinized.",
        tags: ["human-rights", "detention"],
      },
      {
        name: "Right to a fair trial",
        description: "Independent tribunal, equality of arms, presumption of innocence, public hearing.",
        keyPrinciple: "ICCPR Art. 14, ECHR Art. 6. Includes adequate time and facilities for defense, right to counsel, examination of witnesses, free interpreter, no compelled self-incrimination, right to appeal.",
        tags: ["human-rights", "fair-trial"],
      },
    ],
  },

  // ── Family 17 ─────────────────────────────────────────────────────────────
  {
    slug: "environmental-law",
    number: 17,
    name: "Environmental Law",
    blurb: "Domestic and international regulation of pollution, conservation, and climate change.",
    section: "D",
    color: "amber",
    entries: [
      {
        name: "Polluter pays principle",
        description: "Those responsible for pollution bear the costs of remediation and prevention.",
        keyPrinciple: "OECD recommendation (1972), Rio Declaration Principle 16 (1992). Implemented via taxes, permits, liability regimes (Superfund/CERCLA in U.S.). Internalizes externalities.",
        tags: ["environment", "polluter-pays"],
        xref: ["governance"],
      },
      {
        name: "Precautionary principle",
        description: "Lack of full scientific certainty should not postpone cost-effective measures to prevent environmental harm.",
        keyPrinciple: "Rio Declaration Principle 15. Operative in EU law (TFEU Art. 191). Critics argue it justifies excessive risk aversion; defenders argue it counteracts uncertainty bias.",
        tags: ["environment", "precaution"],
        status: "contested",
      },
      {
        name: "NEPA (environmental impact)",
        description: "Federal agencies must consider environmental effects of major actions.",
        keyPrinciple: "42 U.S.C. § 4321 et seq. (1969). Requires Environmental Assessment (EA) or full Environmental Impact Statement (EIS). Procedural only — does not mandate substantive outcomes (Strycker's Bay v. Karlen, 1980).",
        tags: ["environment", "NEPA"],
      },
      {
        name: "Clean Air Act",
        description: "Federal framework for setting and enforcing air quality standards.",
        keyPrinciple: "42 U.S.C. §§ 7401-7671. NAAQS for six criteria pollutants. State Implementation Plans. New Source Review. Massachusetts v. EPA (2007): CO2 is a 'pollutant' under the Act.",
        citation: "Massachusetts v. EPA, 549 U.S. 497 (2007)",
        tags: ["environment", "air", "CAA"],
        status: "landmark",
      },
      {
        name: "Clean Water Act",
        description: "Regulates discharges of pollutants into waters of the United States.",
        keyPrinciple: "33 U.S.C. §§ 1251-1389 (1972). NPDES permits. Sackett v. EPA (2023) narrowed scope of 'waters of the United States' to traditional and adjacent navigable waters with continuous surface connection.",
        citation: "Sackett v. EPA, 598 U.S. 651 (2023)",
        tags: ["environment", "water", "CWA"],
      },
      {
        name: "CERCLA (Superfund)",
        description: "Strict, joint and several liability for cleanup of contaminated sites.",
        keyPrinciple: "42 U.S.C. §§ 9601-9675 (1980). Four categories of PRPs (potentially responsible parties): current owners, past owners at time of disposal, generators, transporters. Retroactive liability — controversial.",
        tags: ["environment", "CERCLA", "liability"],
      },
      {
        name: "Endangered Species Act",
        description: "Protects threatened and endangered species and their critical habitat.",
        keyPrinciple: "16 U.S.C. §§ 1531-1544 (1973). Section 7 consultation. Section 9 take prohibition (Babbitt v. Sweet Home, 1995: habitat modification can be a 'take'). TVA v. Hill (1978): the snail darter trumped the dam.",
        citation: "TVA v. Hill, 437 U.S. 153 (1978)",
        tags: ["environment", "ESA", "species"],
      },
      {
        name: "Paris Agreement",
        description: "2015 multilateral treaty on climate change with nationally determined contributions.",
        keyPrinciple: "Goal: hold warming well below 2°C, aim for 1.5°C. Bottom-up NDCs ratcheted up over time. Not binding on emission targets themselves. U.S. withdrew (2017), rejoined (2021).",
        tags: ["environment", "climate", "paris"],
      },
      {
        name: "Carbon pricing",
        description: "Tax or cap-and-trade pricing of greenhouse gas emissions.",
        keyPrinciple: "Pigouvian approach. EU ETS is the largest market. Carbon tax (Sweden, Canada). Border adjustment mechanisms (EU CBAM, 2026) to prevent leakage. Strong economic-theory support, weak political durability.",
        tags: ["environment", "climate", "carbon-tax"],
        xref: ["governance"],
      },
      {
        name: "Public trust doctrine",
        description: "Government holds certain resources (navigable waters, tidelands) in trust for public.",
        keyPrinciple: "Common-law roots; constitutional dimension in some states (e.g., California). Used in climate litigation (Juliana v. United States) — courts have generally resisted expanding to atmosphere.",
        tags: ["environment", "public-trust"],
      },
    ],
  },

  // ── Family 18 ─────────────────────────────────────────────────────────────
  {
    slug: "labor-and-employment",
    number: 18,
    name: "Labor & Employment Law",
    blurb: "Wages, workplace conditions, discrimination, collective bargaining, and the employment relationship.",
    section: "D",
    color: "amber",
    entries: [
      {
        name: "Employment at will",
        description: "Either employer or employee may terminate the relationship at any time for any non-illegal reason.",
        keyPrinciple: "Default rule in 49 U.S. states (Montana is the exception, with good-cause requirement after probationary period). Exceptions: public policy, implied contract, covenant of good faith. Trend toward erosion through statutes.",
        tags: ["employment", "at-will"],
      },
      {
        name: "Title VII",
        description: "Bars employment discrimination based on race, color, religion, sex, or national origin.",
        keyPrinciple: "Civil Rights Act of 1964. Disparate treatment (McDonnell Douglas burden-shifting) and disparate impact (Griggs v. Duke Power, 1971). Bostock v. Clayton County (2020) extended to sexual orientation and gender identity.",
        citation: "Bostock v. Clayton County, 590 U.S. 644 (2020)",
        tags: ["employment", "discrimination", "title-VII"],
        status: "landmark",
      },
      {
        name: "NLRA / National Labor Relations Act",
        description: "Federal statute governing private-sector collective bargaining.",
        keyPrinciple: "Wagner Act (1935). Section 7 right to organize. Section 8 unfair labor practices. NLRB administers. Excludes agricultural workers, domestic workers, supervisors, public employees, and railway/airline (covered by RLA).",
        tags: ["employment", "NLRA", "union"],
      },
      {
        name: "Right-to-work laws",
        description: "Prohibit union security agreements requiring union dues as condition of employment.",
        keyPrinciple: "Authorized by NLRA § 14(b). Currently in 27 U.S. states. Janus v. AFSCME (2018): public-sector agency fees violate First Amendment, effectively making the entire public sector right-to-work.",
        citation: "Janus v. AFSCME, 585 U.S. 878 (2018)",
        tags: ["employment", "union", "right-to-work"],
        status: "contested",
      },
      {
        name: "FLSA (wages and hours)",
        description: "Federal minimum wage, overtime, and child-labor standards.",
        keyPrinciple: "Fair Labor Standards Act (1938). Federal minimum wage stuck at $7.25/hr since 2009 (many states higher). Time-and-a-half over 40 hours/week. Exempt categories: executive, administrative, professional, outside sales, computer.",
        tags: ["employment", "FLSA", "wages"],
      },
      {
        name: "Worker classification (employee vs. independent contractor)",
        description: "Major dividing line for tax, wage-hour, and discrimination law coverage.",
        keyPrinciple: "Multiple tests: common-law control test, economic-reality test (FLSA), ABC test (CA AB5). Contested in gig economy. Misclassification carries substantial back-pay, tax, and penalty exposure.",
        tags: ["employment", "classification"],
        status: "contested",
      },
      {
        name: "ADA (disability)",
        description: "Prohibits discrimination against qualified individuals with disabilities and requires reasonable accommodation.",
        keyPrinciple: "Americans with Disabilities Act (1990). 'Disability' broadly construed after ADAAA (2008). Reasonable accommodation unless undue hardship. Essential functions of the job test.",
        tags: ["employment", "ADA", "disability"],
      },
      {
        name: "Family and Medical Leave Act",
        description: "Up to 12 weeks unpaid leave for serious health conditions, birth, adoption, military caregiver.",
        keyPrinciple: "29 U.S.C. § 2601 et seq. (1993). Applies to employers with 50+ employees within 75 miles. Restoration to same or equivalent position. Anti-retaliation provisions.",
        tags: ["employment", "FMLA", "leave"],
      },
      {
        name: "Sexual harassment",
        description: "Quid pro quo and hostile work environment harassment violate Title VII.",
        keyPrinciple: "Meritor Savings Bank v. Vinson (1986). Faragher/Ellerth affirmative defense for supervisor harassment without tangible action — employer must show preventive measures + employee unreasonable failure to use them.",
        tags: ["employment", "harassment"],
      },
      {
        name: "Non-compete and trade secret",
        description: "Restrictive covenants limiting post-employment competition.",
        keyPrinciple: "Reasonableness in time, geography, and scope. California voids most non-competes (Bus. & Prof. Code § 16600). FTC banned most non-competes (2024) — court-blocked, on appeal as of 2026.",
        tags: ["employment", "non-compete"],
        status: "contested",
      },
    ],
  },

  // ── Family 19 ─────────────────────────────────────────────────────────────
  {
    slug: "immigration-law",
    number: 19,
    name: "Immigration Law",
    blurb: "Admission, status, removal, and the constitutional treatment of non-citizens.",
    section: "D",
    color: "amber",
    entries: [
      {
        name: "Plenary power doctrine",
        description: "Congress and the executive have broad authority over immigration with limited judicial review.",
        keyPrinciple: "Chinese Exclusion Case (1889), Fong Yue Ting (1893). Modern: rational-basis review even for race-based distinctions (Trump v. Hawaii, 2018, travel ban). Increasingly contested by scholars.",
        citation: "Trump v. Hawaii, 585 U.S. 667 (2018)",
        tags: ["immigration", "plenary-power"],
        status: "contested",
      },
      {
        name: "Asylum and refugee status",
        description: "Protection for those persecuted on account of race, religion, nationality, political opinion, or particular social group.",
        keyPrinciple: "INA § 208; 1951 Refugee Convention via 1967 Protocol. Affirmative (USCIS) and defensive (immigration court). One-year filing deadline. Particular-social-group jurisprudence highly unstable.",
        tags: ["immigration", "asylum", "refugee"],
      },
      {
        name: "Removal proceedings",
        description: "Administrative process to expel non-citizens, conducted in immigration court (EOIR).",
        keyPrinciple: "Immigration judges are DOJ employees, not Article III. No right to appointed counsel except certain minors and mentally incompetent. Standards: clear and convincing for deportability; preponderance for inadmissibility.",
        tags: ["immigration", "removal"],
      },
      {
        name: "Cancellation of removal",
        description: "Discretionary relief allowing certain deportable non-citizens to remain.",
        keyPrinciple: "INA § 240A. Lawful permanent residents: 7 years residence + 5 years LPR + no aggravated felony. Non-LPRs: 10 years presence + good moral character + exceptional and extremely unusual hardship to qualifying relative.",
        tags: ["immigration", "cancellation"],
      },
      {
        name: "Aggravated felony",
        description: "Statutory category triggering automatic removal and broad consequences.",
        keyPrinciple: "INA § 101(a)(43). Defined by 21 categories — includes many drug offenses, theft over $10k, sexual abuse of a minor, alien smuggling. Bars most forms of discretionary relief.",
        tags: ["immigration", "aggravated-felony"],
      },
      {
        name: "Immediate relative vs. preference",
        description: "Family-based immigration is divided into uncapped immediate relatives and capped preference categories.",
        keyPrinciple: "Immediate relatives: spouses, unmarried children under 21, and parents of U.S. citizens. Preference categories (F1-F4) face annual caps and lengthy backlogs by country of birth.",
        tags: ["immigration", "family"],
      },
      {
        name: "Employment-based immigration (EB)",
        description: "Five preference categories for employment-based immigrants.",
        keyPrinciple: "EB-1 (extraordinary ability, multinational executives), EB-2 (advanced degrees, NIW), EB-3 (skilled and professional), EB-4 (special workers), EB-5 (investors). Per-country caps create decades-long backlogs for Indian and Chinese nationals.",
        tags: ["immigration", "employment"],
      },
      {
        name: "DACA",
        description: "Deferred Action for Childhood Arrivals — administrative program for non-citizens brought to U.S. as children.",
        keyPrinciple: "Created by 2012 memo. Department of Homeland Security v. Regents (2020) blocked Trump-era rescission as arbitrary and capricious. Subsequent litigation has held the program unlawful but allows current recipients to renew.",
        tags: ["immigration", "DACA"],
        status: "contested",
      },
      {
        name: "Naturalization",
        description: "Process by which lawful permanent residents become U.S. citizens.",
        keyPrinciple: "INA § 316. Requirements: 5 years LPR (3 if spouse of citizen), continuous residence and physical presence, good moral character, English and civics, oath of allegiance. Denials reviewable in district court (§ 1421(c)).",
        tags: ["immigration", "naturalization"],
      },
      {
        name: "Sanctuary jurisdictions",
        description: "Local and state governments declining to assist federal immigration enforcement.",
        keyPrinciple: "10th Amendment anti-commandeering: federal government cannot compel state/local officials to enforce federal law (Printz v. United States, 1997). Litigation over conditions on federal funding (City of Los Angeles v. Barr).",
        tags: ["immigration", "federalism", "sanctuary"],
        xref: ["governance"],
      },
    ],
  },

  // ── Family 20 ─────────────────────────────────────────────────────────────
  {
    slug: "comparative-law",
    number: 20,
    name: "Comparative Law (Civil vs. Common)",
    blurb: "Structural differences between major legal traditions — civil, common, religious, and customary.",
    section: "D",
    color: "amber",
    entries: [
      {
        name: "Common law tradition",
        description: "Judge-made law evolves through binding precedent.",
        keyPrinciple: "Originated in medieval England. Stare decisis is binding. Adversarial procedure. Lay juries play a significant role. Practiced in UK, U.S., Canada, Australia, India, Ireland, Nigeria, Kenya.",
        tags: ["comparative", "common-law"],
      },
      {
        name: "Civil law tradition",
        description: "Code-based system with comprehensive legislation.",
        keyPrinciple: "Roman law roots; codification under Napoleon (1804) and BGB (1900). Inquisitorial procedure. Judges apply, not make, law. Practiced in continental Europe, Latin America, Quebec, Louisiana (partially), Japan, Korea.",
        tags: ["comparative", "civil-law"],
      },
      {
        name: "Stare decisis",
        description: "Common law principle that courts follow earlier decisions of the same or higher court.",
        keyPrinciple: "Vertical (lower courts bound by higher) and horizontal (same court bound by own precedents) varieties. Weaker in civil law systems — French courts traditionally do not cite prior decisions as authority.",
        tags: ["comparative", "precedent"],
      },
      {
        name: "Adversarial vs. inquisitorial procedure",
        description: "Common-law parties drive the case; civil-law judges actively investigate.",
        keyPrinciple: "Adversarial: party-controlled discovery and witness examination. Inquisitorial: judge-conducted examination, dossier-based, often no live witness testimony at trial. Both converging in practice.",
        tags: ["comparative", "procedure"],
      },
      {
        name: "Codification",
        description: "Comprehensive written statutory schemes covering broad areas of law.",
        keyPrinciple: "Code Napoléon (1804), German BGB (1900) are foundational. UCC and the Restatements are common-law cousins. Aim: accessibility, certainty, and systematic coherence.",
        tags: ["comparative", "codification"],
      },
      {
        name: "Religious legal systems",
        description: "Law derived from sacred texts and religious doctrine.",
        keyPrinciple: "Sharia in Islamic systems (varies widely from secular implementations to strict). Halakha (Jewish law). Canon law (Catholic). Often coexist with secular legal systems in personal-status matters.",
        tags: ["comparative", "religious-law"],
      },
      {
        name: "Customary law",
        description: "Unwritten norms derived from tradition and community practice.",
        keyPrinciple: "Prevalent in indigenous communities and many African systems. Often recognized alongside formal law. Tension with constitutional rights, especially regarding women's status and property.",
        tags: ["comparative", "customary"],
      },
      {
        name: "Mixed legal systems",
        description: "Jurisdictions combining elements from multiple traditions.",
        keyPrinciple: "Examples: Louisiana (civil + common), Quebec (civil + common), South Africa (Roman-Dutch + common + customary), Scotland (civil + common), Israel (English common + religious + Ottoman).",
        tags: ["comparative", "mixed"],
      },
      {
        name: "Civil law judge vs. common law judge",
        description: "Distinct professional and institutional roles.",
        keyPrinciple: "Civil law: career judges trained from law school as civil servants. Common law: judges appointed/elected from practicing lawyers later in career, with more individualized authority and political visibility.",
        tags: ["comparative", "judges"],
      },
      {
        name: "Reception and legal transplants",
        description: "Adoption of foreign legal doctrine into a domestic system.",
        keyPrinciple: "Watson (1974): law is more easily transplanted than reformers assume. Legrand counters: legal meaning is culturally embedded. Major transplants: Japanese Meiji Code (German + French), Turkish Civil Code (Swiss), Latin American codes (French).",
        tags: ["comparative", "transplant"],
        xref: ["ideologies"],
      },
    ],
  },

  // ── Family 21 ─────────────────────────────────────────────────────────────
  {
    slug: "jurisprudence",
    number: 21,
    name: "Jurisprudence & Legal Philosophy",
    blurb: "Foundational debates about what law is, how it ought to be interpreted, and the relationship between law and morality.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Natural law",
        description: "Law derives its authority from an objective moral order.",
        keyPrinciple: "Tradition: Aquinas, Locke, Finnis. Unjust law is no law (lex iniusta non est lex). Provides foundation for human-rights arguments and 'higher law' challenges to positive law. Contested by positivists.",
        tags: ["jurisprudence", "natural-law"],
        xref: ["ideologies"],
      },
      {
        name: "Legal positivism",
        description: "Law is what authoritative sources say it is; its validity is independent of moral merit.",
        keyPrinciple: "Bentham, Austin, Hart (rule of recognition), Raz (sources thesis). Separation thesis: law and morality are conceptually distinct. Compatible with strong moral criticism of law.",
        tags: ["jurisprudence", "positivism"],
        xref: ["ideologies"],
      },
      {
        name: "Legal realism",
        description: "Law is what judges actually do; doctrine is rationalization.",
        keyPrinciple: "Holmes, Pound, Llewellyn, Frank. 'The prophecies of what the courts will do in fact... are what I mean by the law' (Holmes). Foundation of empirical and behavioral analysis of law.",
        tags: ["jurisprudence", "realism"],
        xref: ["ideologies"],
      },
      {
        name: "Originalism",
        description: "Constitutional text should be interpreted according to its original public meaning at ratification.",
        keyPrinciple: "Distinguished from original-intent (drafter intent) and from non-originalism (living constitutionalism). Scalia, Bork, Whittington. Dominant in current U.S. Supreme Court.",
        tags: ["jurisprudence", "originalism", "interpretation"],
        status: "contested",
      },
      {
        name: "Living constitutionalism",
        description: "Constitutional meaning evolves with changing social conditions and values.",
        keyPrinciple: "Brennan, Marshall, Strauss. Emphasizes broad principles and common-law development through precedent. Critics call it judicial activism; defenders point to traditional Anglo-American interpretive practice.",
        tags: ["jurisprudence", "living-constitution", "interpretation"],
        status: "contested",
      },
      {
        name: "Textualism vs. purposivism",
        description: "Two competing methods of statutory interpretation.",
        keyPrinciple: "Textualism (Scalia, Easterbrook): plain meaning of statutory text controls; legislative history disfavored. Purposivism (Breyer, traditional Anglo-American): interpret to serve statute's underlying purpose.",
        tags: ["jurisprudence", "textualism", "interpretation"],
      },
      {
        name: "Law and economics",
        description: "Application of economic analysis to legal rules and institutions.",
        keyPrinciple: "Coase Theorem; efficient breach; cheapest cost avoider. Posner, Calabresi. Coase's 'The Problem of Social Cost' (1960). Strongly influential in tort, contract, antitrust, and corporate law.",
        tags: ["jurisprudence", "law-and-economics"],
      },
      {
        name: "Critical legal studies",
        description: "Movement challenging law's claim to neutrality and coherence.",
        keyPrinciple: "Unger, Kennedy, Tushnet. Emphasizes law's indeterminacy and its role in legitimating power. Spawned critical race theory, feminist jurisprudence, queer theory in law.",
        tags: ["jurisprudence", "CLS"],
        xref: ["ideologies"],
      },
      {
        name: "Rawlsian justice",
        description: "Principles of justice chosen behind a 'veil of ignorance.'",
        keyPrinciple: "John Rawls, A Theory of Justice (1971). Two principles: (1) equal basic liberties; (2) social/economic inequalities arranged to benefit the worst-off (difference principle) and attached to positions of fair equal opportunity.",
        tags: ["jurisprudence", "justice", "rawls"],
        xref: ["ideologies"],
      },
      {
        name: "Hart vs. Dworkin",
        description: "Central jurisprudential debate of the late 20th century — rules vs. principles.",
        keyPrinciple: "Hart: law is rules identified by a rule of recognition. Dworkin: law also includes principles and policies, and there is one right answer to most legal questions (Law's Empire, 1986).",
        tags: ["jurisprudence", "hart-dworkin"],
      },
      {
        name: "Rule of law",
        description: "Government acts through general, prospective, public laws applied equally by independent tribunals.",
        keyPrinciple: "Dicey: supremacy of regular law over arbitrary power, equality before law, constitution as ordinary-law product. Fuller's eight desiderata of legality. Contrast with rule by law (instrumental use of legal forms by arbitrary power).",
        tags: ["jurisprudence", "rule-of-law"],
        xref: ["governance"],
      },
      {
        name: "Procedural vs. substantive justice",
        description: "Fair procedures vs. fair outcomes.",
        keyPrinciple: "Procedural justice (Tyler): people accept outcomes from procedures they perceive as fair. Substantive justice asks whether the outcome itself is just. Both matter; they can diverge dramatically.",
        tags: ["jurisprudence", "justice"],
      },
    ],
  },

  // ── Family 22 ─────────────────────────────────────────────────────────────
  {
    slug: "landmark-cases-and-open-questions",
    number: 22,
    name: "Landmark Cases & Open Questions",
    blurb: "The decisions that shaped legal doctrine, and the questions still unresolved.",
    section: "E",
    color: "amber",
    entries: [
      {
        name: "Marbury v. Madison (1803)",
        description: "Established judicial review of federal legislation.",
        keyPrinciple: "Chief Justice Marshall held that the Judiciary Act of 1789 violated Article III; courts must declare unconstitutional acts void. The keystone of American constitutionalism.",
        citation: "5 U.S. (1 Cranch) 137 (1803)",
        tags: ["landmark", "constitutional", "judicial-review"],
        status: "landmark",
      },
      {
        name: "Brown v. Board of Education (1954)",
        description: "Overruled Plessy v. Ferguson; held separate-but-equal violates Equal Protection.",
        keyPrinciple: "Unanimous Warren Court opinion. 'In the field of public education the doctrine of separate but equal has no place.' Triggered massive resistance, decades of desegregation litigation.",
        citation: "347 U.S. 483 (1954)",
        tags: ["landmark", "equal-protection", "race"],
        status: "landmark",
      },
      {
        name: "Roe v. Wade (1973) and Dobbs (2022)",
        description: "Roe recognized a constitutional right to abortion; Dobbs overruled it 49 years later.",
        keyPrinciple: "Roe v. Wade and Planned Parenthood v. Casey (1992) held abortion was a fundamental constitutional right. Dobbs v. Jackson Women's Health (2022) held the Constitution does not confer such a right, returning regulation to the states.",
        citation: "Dobbs v. Jackson Women's Health, 597 U.S. 215 (2022)",
        tags: ["landmark", "overruled", "reproductive-rights"],
        status: "contested",
      },
      {
        name: "Lochner v. New York (1905)",
        description: "Struck down maximum-hours law as violating substantive due process freedom of contract.",
        keyPrinciple: "Symbol of the 'Lochner era' of judicial intervention into economic regulation. Repudiated by West Coast Hotel v. Parrish (1937) and Williamson v. Lee Optical (1955). Cited as cautionary tale on both left and right.",
        citation: "198 U.S. 45 (1905)",
        tags: ["landmark", "substantive-due-process", "overruled"],
        status: "overruled",
      },
      {
        name: "Dred Scott v. Sandford (1857)",
        description: "Held that African Americans, free or enslaved, were not U.S. citizens and Congress could not ban slavery in territories.",
        keyPrinciple: "Widely regarded as the worst Supreme Court decision in U.S. history. Helped precipitate the Civil War. Overturned by the 13th and 14th Amendments.",
        citation: "60 U.S. (19 How.) 393 (1857)",
        tags: ["landmark", "overruled", "race"],
        status: "overruled",
      },
      {
        name: "Korematsu v. United States (1944)",
        description: "Upheld internment of Japanese Americans during WWII.",
        keyPrinciple: "Repudiated as 'gravely wrong' by Trump v. Hawaii (2018) majority. Established strict scrutiny for racial classifications even as it failed to apply it meaningfully. Coram nobis grants (1980s) vacated underlying convictions.",
        citation: "323 U.S. 214 (1944)",
        tags: ["landmark", "repudiated", "race"],
        status: "overruled",
      },
      {
        name: "Citizens United v. FEC (2010)",
        description: "Held that corporate and union independent political expenditures are protected speech.",
        keyPrinciple: "Overruled Austin v. Michigan Chamber of Commerce (1990). Catalyzed Super PACs and 'dark money.' Sharp dissent by Stevens. Among the most politically contested decisions of the 21st century.",
        citation: "558 U.S. 310 (2010)",
        tags: ["landmark", "first-amendment", "campaign-finance"],
        status: "contested",
      },
      {
        name: "Nuremberg Trials (1945-46)",
        description: "International military tribunal that prosecuted Nazi leaders for war crimes, crimes against humanity, and crimes against peace.",
        keyPrinciple: "Established individual criminal responsibility under international law. 'Following orders' is no defense. Created the conceptual basis for the ICC and modern international criminal law.",
        tags: ["landmark", "international", "criminal"],
        xref: ["historical-events"],
        status: "landmark",
      },
      {
        name: "Open question: AI personhood and liability",
        description: "Whether AI systems can hold rights, bear duties, or be objects of liability.",
        keyPrinciple: "Currently, AI is a tool — liability runs to humans (developer, deployer, user). Open questions: copyright in AI-generated works (Thaler v. Perlmutter), patent inventorship (DABUS), tort allocation when an autonomous system causes harm.",
        tags: ["open-question", "AI", "personhood"],
        status: "open",
      },
      {
        name: "Open question: Digital privacy and the Fourth Amendment",
        description: "Whether and how Fourth Amendment doctrine adapts to digital evidence and surveillance.",
        keyPrinciple: "Riley v. California (2014, cellphone searches) and Carpenter v. United States (2018, historical cell-site location) gestured toward stronger protection. Open: encryption, content-vs-metadata, foreign-intelligence surveillance, AI-aided pattern detection.",
        tags: ["open-question", "fourth-amendment", "privacy"],
        status: "open",
      },
      {
        name: "Open question: Standing for climate plaintiffs",
        description: "Whether and how plaintiffs can establish standing for climate-change harms.",
        keyPrinciple: "Juliana v. United States (9th Cir. 2020) found no judicial remedy. Held v. Montana (2023) succeeded under state constitution. Generalized, attenuated, future harms create chronic standing problems for federal climate suits.",
        tags: ["open-question", "standing", "climate"],
        status: "open",
      },
      {
        name: "Open question: Status of regulatory agencies",
        description: "Whether the modern administrative state survives the major-questions doctrine and Loper Bright.",
        keyPrinciple: "2020s decisions (West Virginia v. EPA, Loper Bright, Jarkesy, SEC v. Jarkesy) have significantly constrained agency power. Open: scope of nondelegation revival, future of Humphrey's Executor, whether large delegations to ALJs survive.",
        tags: ["open-question", "administrative", "separation-of-powers"],
        xref: ["governance"],
        status: "open",
      },
    ],
  },
];
