import type { Family } from "./types";

export const FAMILIES_8_14: Family[] = [
  // ── Family 8 ──────────────────────────────────────────────────────────────
  {
    slug: "tort-law",
    number: 8,
    name: "Tort Law",
    blurb: "Civil wrongs that cause loss or harm — negligence, intentional torts, and strict liability.",
    section: "C",
    color: "green",
    entries: [
      {
        name: "Negligence",
        description: "Breach of a duty of care that proximately causes damage.",
        keyPrinciple: "Four elements: duty, breach, causation (factual + proximate), damages. Reasonable-person standard adjusted for expertise (professionals) and age (children). The dominant tort cause of action.",
        tags: ["tort", "negligence"],
      },
      {
        name: "Duty of care",
        description: "Legal obligation to exercise reasonable care toward foreseeable plaintiffs.",
        keyPrinciple: "Palsgraf v. Long Island R.R. (1928): duty extends only to plaintiffs in the foreseeable zone of danger (Cardozo). Andrews dissent: duty to all the world. Modern multi-factor tests (Rowland v. Christian, 1968).",
        citation: "Palsgraf v. Long Island R.R., 248 N.Y. 339 (1928)",
        tags: ["tort", "negligence", "duty"],
        status: "landmark",
      },
      {
        name: "Proximate cause",
        description: "Legal limitation on liability for foreseeable consequences only.",
        keyPrinciple: "Cuts off liability where the connection between act and harm is too attenuated. Foreseeability is the dominant test (Wagon Mound No. 1, 1961). Intervening superseding causes break the chain.",
        tags: ["tort", "causation"],
      },
      {
        name: "Res ipsa loquitur",
        description: "Negligence inferred from the nature of an accident absent direct proof.",
        keyPrinciple: "'The thing speaks for itself.' Byrne v. Boadle (1863). Requirements: (1) accident does not normally occur without negligence, (2) instrumentality in defendant's exclusive control, (3) plaintiff did not contribute.",
        tags: ["tort", "negligence", "inference"],
      },
      {
        name: "Comparative vs. contributory negligence",
        description: "Plaintiff's own negligence reduces (or in older systems, bars) recovery.",
        keyPrinciple: "Contributory: any plaintiff fault bars recovery (NC, AL, MD, VA, DC). Pure comparative: damages reduced by plaintiff's %. Modified comparative: bar at 50% or 51% plaintiff fault.",
        tags: ["tort", "comparative-fault"],
      },
      {
        name: "Strict liability",
        description: "Liability without fault for abnormally dangerous activities and certain products.",
        keyPrinciple: "Rylands v. Fletcher (1868): non-natural use, escape. Restatement (Second) Torts § 519-520: abnormally dangerous activities (blasting, hazardous materials). Limited to harms making activity abnormally dangerous.",
        citation: "Rylands v. Fletcher, L.R. 3 H.L. 330 (1868)",
        tags: ["tort", "strict-liability"],
      },
      {
        name: "Products liability",
        description: "Strict liability for manufacturers, distributors, and sellers of defective products.",
        keyPrinciple: "Greenman v. Yuba Power Products (1963) and Restatement (Second) § 402A. Three defect types: manufacturing, design (risk-utility or consumer-expectations), warning. Privity not required.",
        tags: ["tort", "products-liability"],
      },
      {
        name: "Intentional torts — battery and assault",
        description: "Battery: harmful or offensive contact. Assault: imminent apprehension of such contact.",
        keyPrinciple: "Intent: substantial certainty or purpose. Transferred intent across persons and across torts (battery → assault, etc.). Consent, self-defense, defense of others are key defenses.",
        tags: ["tort", "intentional", "battery"],
      },
      {
        name: "False imprisonment",
        description: "Intentional confinement of another within boundaries fixed by the actor.",
        keyPrinciple: "Plaintiff must be conscious of confinement or harmed by it. Shopkeeper's privilege: reasonable detention to investigate suspected shoplifting.",
        tags: ["tort", "intentional"],
      },
      {
        name: "Defamation",
        description: "False statement of fact published to a third party that damages reputation.",
        keyPrinciple: "Libel (written/permanent) vs. slander (spoken). New York Times v. Sullivan (1964): public officials must prove actual malice (knowledge of falsity or reckless disregard). Extended to public figures (Curtis Publishing, 1967).",
        citation: "New York Times Co. v. Sullivan, 376 U.S. 254 (1964)",
        tags: ["tort", "defamation", "first-amendment"],
        status: "landmark",
      },
      {
        name: "Privacy torts",
        description: "Four invasion-of-privacy theories: intrusion, public disclosure, false light, appropriation.",
        keyPrinciple: "Prosser's taxonomy. Restatement (Second) §§ 652A-652E. False light overlaps with defamation; appropriation overlaps with right of publicity.",
        tags: ["tort", "privacy"],
      },
      {
        name: "Intentional infliction of emotional distress",
        description: "Extreme and outrageous conduct intentionally or recklessly causing severe emotional distress.",
        keyPrinciple: "High threshold: 'beyond all possible bounds of decency, regarded as atrocious, and utterly intolerable in a civilized community.' Snyder v. Phelps (2011): First Amendment protection for picketing of military funerals.",
        tags: ["tort", "IIED", "intentional"],
      },
      {
        name: "Joint and several liability",
        description: "Each tortfeasor liable for the full judgment; plaintiff can collect entire amount from any one.",
        keyPrinciple: "Traditional rule for indivisible injuries from concurrent tortfeasors. Tort reform in many states limited to a defendant's percentage of fault for non-economic damages.",
        tags: ["tort", "damages", "liability"],
      },
    ],
  },

  // ── Family 9 ──────────────────────────────────────────────────────────────
  {
    slug: "contract-law",
    number: 9,
    name: "Contract Law",
    blurb: "Formation, performance, breach, and remedies for legally enforceable promises.",
    section: "C",
    color: "emerald",
    entries: [
      {
        name: "Offer, acceptance, consideration",
        description: "The three classical elements of contract formation.",
        keyPrinciple: "Offer: manifestation of willingness with definite terms. Acceptance: assent on the same terms (mirror image, UCC eased). Consideration: bargained-for legal detriment. Restatement (Second) §§ 17, 24, 50, 71.",
        tags: ["contract", "formation"],
      },
      {
        name: "Promissory estoppel",
        description: "Promise reasonably relied upon may be enforced absent consideration.",
        keyPrinciple: "Restatement (Second) § 90. Elements: promise, reasonable expectation of reliance, actual reliance, injustice avoidable only by enforcement. Remedy often limited to reliance damages.",
        tags: ["contract", "estoppel"],
      },
      {
        name: "Statute of frauds",
        description: "Certain contracts must be in writing to be enforceable.",
        keyPrinciple: "Origin: English Statute of Frauds (1677). Modern: contracts for marriage, more than one year, land, executor liability, sales of goods ≥ $500 (UCC § 2-201), and suretyship.",
        tags: ["contract", "statute-of-frauds"],
      },
      {
        name: "Parol evidence rule",
        description: "Prior or contemporaneous oral statements may not vary the terms of a fully integrated written contract.",
        keyPrinciple: "Excludes evidence inconsistent with a final integrated agreement. Exceptions: ambiguity, fraud, mistake, condition precedent, course of dealing/usage of trade. UCC § 2-202 more permissive.",
        tags: ["contract", "parol-evidence"],
      },
      {
        name: "Mistake",
        description: "Erroneous belief at the time of contracting may justify avoidance.",
        keyPrinciple: "Mutual mistake: both parties wrong about a basic assumption with material effect (Sherwood v. Walker — pregnant cow). Unilateral mistake harder to undo absent palpable mistake or other party's knowledge.",
        tags: ["contract", "mistake", "defense"],
      },
      {
        name: "Duress and undue influence",
        description: "Improper pressure may make a contract voidable.",
        keyPrinciple: "Duress: wrongful threat that leaves no reasonable alternative. Undue influence: unfair persuasion exploiting a relationship of trust/dependence. Both render contract voidable, not void.",
        tags: ["contract", "duress", "defense"],
      },
      {
        name: "Unconscionability",
        description: "Court may refuse to enforce a contract or term that is unconscionable at formation.",
        keyPrinciple: "Procedural unconscionability (unfair process: surprise, oppression) + substantive unconscionability (one-sided terms). UCC § 2-302. Williams v. Walker-Thomas Furniture (1965) is the foundational case.",
        tags: ["contract", "unconscionability", "defense"],
      },
      {
        name: "Material breach and substantial performance",
        description: "Only a material breach excuses the non-breaching party's performance.",
        keyPrinciple: "Restatement (Second) § 241 factors: deprivation of expected benefit, adequacy of compensation, forfeiture, likelihood of cure, good faith. Jacob & Youngs v. Kent (1921): builder substantially performed despite wrong-brand pipe.",
        citation: "Jacob & Youngs v. Kent, 230 N.Y. 239 (1921)",
        tags: ["contract", "breach"],
      },
      {
        name: "Expectation damages",
        description: "Standard remedy: put the non-breaching party in the position it would have occupied had the contract been performed.",
        keyPrinciple: "Expectation = loss in value + other loss − cost avoided − loss avoided. Reliance and restitution are alternative measures when expectation is uncertain.",
        tags: ["contract", "damages"],
      },
      {
        name: "Liquidated damages vs. penalty",
        description: "Stipulated damages enforceable if a reasonable forecast of actual loss; unenforceable if a penalty.",
        keyPrinciple: "Restatement (Second) § 356. Test: damages at formation (or at breach in UCC § 2-718) are difficult to determine; stipulated amount is reasonable. Penalty clauses unenforceable.",
        tags: ["contract", "damages"],
      },
      {
        name: "Hadley v. Baxendale (foreseeable damages)",
        description: "Consequential damages limited to those reasonably foreseeable at contracting.",
        keyPrinciple: "Hadley v. Baxendale (1854): two limbs — damages arising naturally from breach, plus damages reasonably contemplated by both parties as probable result of breach.",
        citation: "Hadley v. Baxendale, 9 Exch. 341 (1854)",
        tags: ["contract", "damages", "foreseeability"],
        status: "landmark",
      },
      {
        name: "Specific performance",
        description: "Equitable remedy forcing the breaching party to perform.",
        keyPrinciple: "Available when damages inadequate — typically for unique goods, real property, or rare collectibles. Disfavored for personal services. UCC § 2-716 codifies for unique goods.",
        tags: ["contract", "remedies", "equity"],
      },
    ],
  },

  // ── Family 10 ─────────────────────────────────────────────────────────────
  {
    slug: "property-law",
    number: 10,
    name: "Property Law",
    blurb: "Rights in things — possession, ownership, transfer, and the bundle of interests in real and personal property.",
    section: "C",
    color: "teal",
    entries: [
      {
        name: "Bundle of rights",
        description: "Property is a bundle of legal relations — possess, use, exclude, transfer, destroy.",
        keyPrinciple: "Wesley Hohfeld's analysis (1913) and Honoré's incidents (1961). Each stick can be separated (a lease severs possession; an easement carves out a right of way).",
        tags: ["property", "theory"],
      },
      {
        name: "Estates in land",
        description: "Hierarchy of possessory interests: fee simple, fee tail, life estate, leasehold.",
        keyPrinciple: "Fee simple absolute is the largest; defeasible fees end on a condition. Life estate ends at life-tenant's death; remainder or reversion follows.",
        tags: ["property", "estates"],
      },
      {
        name: "Concurrent ownership",
        description: "Joint tenancy, tenancy in common, tenancy by the entirety.",
        keyPrinciple: "Joint tenancy: equal shares + right of survivorship + four unities (time, title, interest, possession). Tenancy in common: alienable, descendible shares, no survivorship. Entirety: only between spouses; creditor-protected in many states.",
        tags: ["property", "concurrent-ownership"],
      },
      {
        name: "Adverse possession",
        description: "Long, open use of another's land can ripen into title.",
        keyPrinciple: "Elements: actual, open and notorious, continuous, exclusive, hostile, for the statutory period (typically 10-20 years). Some jurisdictions require color of title or good faith.",
        tags: ["property", "adverse-possession"],
      },
      {
        name: "Recording acts",
        description: "Statutes governing priority among competing claims to real property.",
        keyPrinciple: "Race (first to record wins), notice (later bona fide purchaser without notice prevails), race-notice (later BFP without notice who records first prevails). Constructive notice from public records.",
        tags: ["property", "recording", "title"],
      },
      {
        name: "Easements",
        description: "Right to use another's land for a specific purpose.",
        keyPrinciple: "Affirmative vs. negative; appurtenant (runs with dominant land) vs. in gross (personal). Created by express grant, prescription, implication, necessity. Terminated by merger, release, abandonment.",
        tags: ["property", "easements"],
      },
      {
        name: "Eminent domain and takings",
        description: "Government may take private property for public use upon just compensation.",
        keyPrinciple: "5th Amendment Takings Clause (U.S.). Kelo v. City of New London (2005): 'public use' extended to economic development — politically contested, prompting many state reforms.",
        citation: "Kelo v. City of New London, 545 U.S. 469 (2005)",
        tags: ["property", "takings", "constitutional"],
        status: "contested",
      },
      {
        name: "Regulatory taking",
        description: "Government regulation may so diminish property value as to require compensation.",
        keyPrinciple: "Penn Central (1978) three-factor test: economic impact, interference with investment-backed expectations, character of government action. Lucas v. South Carolina Coastal Council (1992): total economic wipeout is a per se taking.",
        tags: ["property", "takings", "regulatory"],
      },
      {
        name: "Nuisance",
        description: "Substantial and unreasonable interference with use and enjoyment of land.",
        keyPrinciple: "Private (affecting specific landowners) vs. public (affecting community). Balancing of utilities. Boomer v. Atlantic Cement (1970): injunction denied but damages awarded — economic balancing.",
        tags: ["property", "nuisance", "tort"],
      },
      {
        name: "Landlord-tenant",
        description: "Distinct body of law combining contract and property — leasehold estates with statutory overlays.",
        keyPrinciple: "Implied warranty of habitability (Javins v. First National Realty, 1970). Constructive eviction. Modern statutory regimes for security deposits, notice, rent control. Lease both conveys an estate and creates contractual duties.",
        tags: ["property", "landlord-tenant"],
      },
      {
        name: "Rule against perpetuities",
        description: "No interest is valid unless it must vest, if at all, within 21 years after some life in being.",
        keyPrinciple: "Originated in Duke of Norfolk's Case (1682). Aimed at restraints on alienation via dead-hand control. Modern reforms: USRAP (90 years), abolition for trusts in many states.",
        tags: ["property", "perpetuities"],
      },
    ],
  },

  // ── Family 11 ─────────────────────────────────────────────────────────────
  {
    slug: "family-law",
    number: 11,
    name: "Family Law",
    blurb: "Marriage, divorce, child custody, support, adoption, and the legal regulation of intimate relationships.",
    section: "C",
    color: "green",
    entries: [
      {
        name: "Marriage and same-sex marriage",
        description: "Civil status conferring rights, duties, and tax/inheritance consequences on couples.",
        keyPrinciple: "Obergefell v. Hodges (2015): same-sex couples have a fundamental right to marry under 14th Amendment. Loving v. Virginia (1967): interracial marriage bans unconstitutional. State-administered, federally recognized.",
        citation: "Obergefell v. Hodges, 576 U.S. 644 (2015)",
        tags: ["family", "marriage", "constitutional"],
        status: "landmark",
      },
      {
        name: "No-fault divorce",
        description: "Marriage dissolved without proving wrongdoing by either spouse.",
        keyPrinciple: "California Family Law Act (1969) inaugurated; now universal in the U.S. Common grounds: irreconcilable differences, irretrievable breakdown. Fault may still affect property division or alimony.",
        tags: ["family", "divorce"],
      },
      {
        name: "Equitable distribution vs. community property",
        description: "Two systems for dividing marital assets on divorce.",
        keyPrinciple: "Equitable distribution (most states): division based on fairness factors, not necessarily equal. Community property (CA, TX, AZ, LA, NM, NV, ID, WA, WI): equal division of community assets acquired during marriage.",
        tags: ["family", "property-division"],
      },
      {
        name: "Best interests of the child",
        description: "Standard governing custody, visitation, adoption, and termination decisions.",
        keyPrinciple: "Factors: child's preference, parental fitness, stability, sibling ties, mental and physical health, ability to provide. Wide judicial discretion; trend toward shared physical custody.",
        tags: ["family", "custody"],
      },
      {
        name: "Child support guidelines",
        description: "Statutory formulas for calculating support based on parents' income and custodial arrangement.",
        keyPrinciple: "Two main models: percentage of obligor's income, income-shares (most states). Federal Family Support Act (1988) required guidelines. Deviation permitted only with written findings.",
        tags: ["family", "support"],
      },
      {
        name: "Alimony / spousal support",
        description: "Periodic or lump payments to a former spouse after divorce.",
        keyPrinciple: "Modernized: rehabilitative (short-term, to transition), reimbursement (e.g., for spouse who supported the other through school), permanent (long marriages). 2017 federal tax change ended deductibility/inclusion for new agreements.",
        tags: ["family", "alimony"],
      },
      {
        name: "Prenuptial agreements",
        description: "Contracts addressing property and support consequences of marriage and divorce.",
        keyPrinciple: "Generally enforceable with: full disclosure, voluntariness, no unconscionability at execution or enforcement. UPAA / UPMAA model rules. Some states impose stricter standards on spousal support waivers.",
        tags: ["family", "contract", "prenup"],
      },
      {
        name: "Adoption",
        description: "Legal severance of parental rights to one set of parents and creation of new parental relationship.",
        keyPrinciple: "Voluntary or involuntary (after termination of parental rights). Federal ICWA (1978) special rules for Native American children. Hague Convention on Intercountry Adoption (1993).",
        tags: ["family", "adoption"],
      },
      {
        name: "Termination of parental rights",
        description: "Severance of legal parent-child relationship by court order.",
        keyPrinciple: "Grounds: abandonment, abuse, neglect, parental unfitness, failure to provide. Santosky v. Kramer (1982): clear-and-convincing evidence standard constitutionally required.",
        citation: "Santosky v. Kramer, 455 U.S. 745 (1982)",
        tags: ["family", "TPR"],
      },
      {
        name: "Reproductive rights",
        description: "The constitutional status of abortion, contraception, and assisted reproduction.",
        keyPrinciple: "Roe v. Wade (1973) and Planned Parenthood v. Casey (1992) recognized a federal right; Dobbs v. Jackson Women's Health (2022) overruled both, returning regulation to the states. Griswold v. Connecticut (1965, contraception) survives.",
        citation: "Dobbs v. Jackson Women's Health Org., 597 U.S. 215 (2022)",
        tags: ["family", "reproductive-rights", "constitutional"],
        status: "contested",
      },
    ],
  },

  // ── Family 12 ─────────────────────────────────────────────────────────────
  {
    slug: "civil-procedure",
    number: 12,
    name: "Civil Procedure",
    blurb: "Rules governing how civil litigation proceeds — jurisdiction, pleading, discovery, judgment, appeal.",
    section: "C",
    color: "emerald",
    entries: [
      {
        name: "Personal jurisdiction",
        description: "Court's power over a defendant — requires minimum contacts and fair play.",
        keyPrinciple: "International Shoe v. Washington (1945): minimum contacts such that exercise does not offend traditional notions of fair play and substantial justice. General (continuous, systematic) vs. specific (claim-related).",
        citation: "International Shoe Co. v. Washington, 326 U.S. 310 (1945)",
        tags: ["civil-procedure", "jurisdiction"],
        status: "landmark",
      },
      {
        name: "Subject-matter jurisdiction (federal)",
        description: "Federal courts may hear only federal-question or diversity cases.",
        keyPrinciple: "Article III + 28 U.S.C. §§ 1331, 1332. Federal question: well-pleaded complaint rule. Diversity: complete diversity + amount in controversy > $75,000. Non-waivable; can be raised at any time.",
        tags: ["civil-procedure", "jurisdiction", "federal"],
      },
      {
        name: "Venue",
        description: "The proper geographic location for the lawsuit.",
        keyPrinciple: "28 U.S.C. § 1391: where defendant resides, where substantial part of events occurred, where defendant subject to jurisdiction. Transfer for convenience (§ 1404) or to cure improper venue (§ 1406). Forum non conveniens at common law.",
        tags: ["civil-procedure", "venue"],
      },
      {
        name: "Service of process",
        description: "Formal delivery of legal documents notifying defendant of suit.",
        keyPrinciple: "FRCP 4. Constitutional due process requires notice reasonably calculated to reach the defendant (Mullane v. Central Hanover Bank, 1950). Waiver of service available to spare defendants.",
        tags: ["civil-procedure", "service"],
      },
      {
        name: "Pleading standard (Twiqbal)",
        description: "Complaints must state a claim plausible on its face.",
        keyPrinciple: "Bell Atlantic v. Twombly (2007) + Ashcroft v. Iqbal (2009) replaced 'no set of facts' (Conley v. Gibson, 1957) with plausibility. Factual content must allow court to draw reasonable inference of liability.",
        citation: "Ashcroft v. Iqbal, 556 U.S. 662 (2009)",
        tags: ["civil-procedure", "pleading"],
      },
      {
        name: "Erie doctrine",
        description: "Federal courts sitting in diversity apply state substantive law.",
        keyPrinciple: "Erie R.R. v. Tompkins (1938) overturned Swift v. Tyson. Federal courts apply state law for substance, federal law for procedure. Hanna v. Plumer (1965) sharpens the Rules Enabling Act analysis.",
        citation: "Erie R.R. v. Tompkins, 304 U.S. 64 (1938)",
        tags: ["civil-procedure", "erie", "federal"],
        status: "landmark",
      },
      {
        name: "Discovery",
        description: "Pre-trial information exchange under FRCP — interrogatories, depositions, document requests.",
        keyPrinciple: "FRCP 26-37. Scope: nonprivileged, relevant, proportional. 2015 proportionality amendment. ESI (electronically stored information) presents continuing challenges and sanctions risk.",
        tags: ["civil-procedure", "discovery"],
      },
      {
        name: "Summary judgment",
        description: "Pre-trial disposition where no genuine dispute of material fact exists.",
        keyPrinciple: "FRCP 56. Celotex Corp. v. Catrett (1986): movant may show absence of evidence. Non-movant must produce evidence creating a genuine issue. Trilogy of 1986 cases (Celotex, Anderson, Matsushita) reshaped the standard.",
        tags: ["civil-procedure", "summary-judgment"],
      },
      {
        name: "Class actions",
        description: "Representative lawsuit on behalf of a class of similarly situated persons.",
        keyPrinciple: "FRCP 23: numerosity, commonality, typicality, adequacy. (b)(3) damages classes require predominance + superiority. Wal-Mart Stores v. Dukes (2011) tightened commonality.",
        tags: ["civil-procedure", "class-action"],
      },
      {
        name: "Res judicata and collateral estoppel",
        description: "Preclusion doctrines — same claim cannot be relitigated; same issue cannot be relitigated.",
        keyPrinciple: "Claim preclusion (res judicata): final judgment on merits bars re-litigation between same parties on same claim. Issue preclusion (collateral estoppel): bars re-litigation of an issue actually litigated and necessary to the judgment.",
        tags: ["civil-procedure", "preclusion"],
      },
      {
        name: "Standards of appellate review",
        description: "Different deference standards for fact, law, and discretion.",
        keyPrinciple: "De novo for legal questions; clearly erroneous for findings of fact (FRCP 52(a)); abuse of discretion for trial-court discretionary calls; substantial evidence for jury verdicts.",
        tags: ["civil-procedure", "appellate"],
      },
    ],
  },

  // ── Family 13 ─────────────────────────────────────────────────────────────
  {
    slug: "corporate-and-business-law",
    number: 13,
    name: "Corporate & Business Law",
    blurb: "Formation and governance of business entities, fiduciary duties, securities regulation, and antitrust.",
    section: "C",
    color: "teal",
    entries: [
      {
        name: "Limited liability",
        description: "Shareholders are not personally liable for corporate debts beyond their investment.",
        keyPrinciple: "Foundational corporate attribute. 'Piercing the corporate veil' may impose personal liability where corporate form is abused (inadequate capitalization, intermingling, fraud).",
        tags: ["corporate", "limited-liability"],
      },
      {
        name: "Business judgment rule",
        description: "Courts presume directors act on informed, good-faith basis in best interests of corporation.",
        keyPrinciple: "Shields directors from second-guessing of business decisions. Rebutted by gross negligence, conflicts of interest, or bad faith. Aronson v. Lewis (Del. 1984) is the canonical statement.",
        tags: ["corporate", "fiduciary"],
      },
      {
        name: "Duty of care",
        description: "Directors and officers must act with the care of an ordinarily prudent person.",
        keyPrinciple: "Smith v. Van Gorkom (Del. 1985): directors breached duty of care by inadequately informing themselves before approving merger. Most Delaware corporations have § 102(b)(7) charter provisions exculpating directors for duty-of-care breaches.",
        tags: ["corporate", "fiduciary", "care"],
      },
      {
        name: "Duty of loyalty",
        description: "Fiduciaries must put corporate interests ahead of personal interests.",
        keyPrinciple: "Self-dealing transactions presumptively voidable unless fair to corporation or approved by disinterested directors/shareholders after full disclosure. Corporate opportunity doctrine. Not exculpable under § 102(b)(7).",
        tags: ["corporate", "fiduciary", "loyalty"],
      },
      {
        name: "Insider trading",
        description: "Trading on material non-public information in breach of duty.",
        keyPrinciple: "Securities Exchange Act § 10(b) and Rule 10b-5. Classical theory (insider's fiduciary duty). Misappropriation theory (O'Hagan, 1997). Tipper/tippee liability requires personal benefit (Salman, 2016).",
        tags: ["corporate", "securities", "insider-trading"],
      },
      {
        name: "Securities registration",
        description: "Public offerings must be registered with the SEC unless exempt.",
        keyPrinciple: "Securities Act of 1933, § 5. Major exemptions: Regulation D (private placements), Rule 144A (resales to QIBs), crowdfunding (Reg CF). Disclosure regime relies on prospectus and ongoing reporting.",
        tags: ["corporate", "securities", "registration"],
      },
      {
        name: "Antitrust — restraint of trade",
        description: "Sherman Act § 1 bars contracts and combinations in restraint of trade.",
        keyPrinciple: "Per se illegal: horizontal price fixing, bid rigging, market allocation. Rule of reason for vertical restraints (Leegin, 2007) and most other arrangements. Quick-look intermediate review.",
        tags: ["corporate", "antitrust", "sherman-1"],
      },
      {
        name: "Antitrust — monopolization",
        description: "Sherman Act § 2 bars monopolization and attempts to monopolize.",
        keyPrinciple: "Two elements: (1) monopoly power in a relevant market, (2) willful acquisition or maintenance through anticompetitive conduct. United States v. Microsoft (2001); recent suits against Google, Meta, Amazon.",
        tags: ["corporate", "antitrust", "monopolization"],
      },
      {
        name: "M&A — fiduciary review",
        description: "Heightened scrutiny applied to certain mergers and change-of-control transactions.",
        keyPrinciple: "Delaware doctrines: Unocal (defensive measures must be proportionate to threat), Revlon (when sale becomes inevitable, board must maximize value), Blasius (interference with voting franchise needs compelling justification).",
        tags: ["corporate", "M&A", "fiduciary"],
      },
      {
        name: "Shareholder derivative suit",
        description: "Suit by shareholders on behalf of the corporation against officers, directors, or third parties.",
        keyPrinciple: "Demand on the board required, unless excused by demand futility (Aronson, Rales tests in Delaware). Settlement requires court approval. Recovery goes to corporation, not plaintiff.",
        tags: ["corporate", "derivative", "shareholder"],
      },
      {
        name: "LLC and partnership form",
        description: "Alternative entities offering limited liability with pass-through taxation and contract flexibility.",
        keyPrinciple: "LLCs governed primarily by operating agreement; fiduciary duties may be modified or eliminated by contract (Delaware LLC Act § 18-1101(c)). Partnership: default joint and several liability for partners; LLPs and LLLPs reform this.",
        tags: ["corporate", "LLC", "partnership"],
      },
    ],
  },

  // ── Family 14 ─────────────────────────────────────────────────────────────
  {
    slug: "intellectual-property",
    number: 14,
    name: "Intellectual Property",
    blurb: "Legal rights in intangible creations — patents, copyrights, trademarks, and trade secrets.",
    section: "C",
    color: "green",
    entries: [
      {
        name: "Patent — utility",
        description: "Exclusive rights for inventions that are novel, non-obvious, and useful.",
        keyPrinciple: "35 U.S.C. §§ 101-103. 20-year term from filing. Quid pro quo: disclosure (§ 112) in exchange for exclusivity. Alice v. CLS Bank (2014): abstract ideas implemented on a computer are unpatentable.",
        tags: ["IP", "patent"],
      },
      {
        name: "Patent — design and plant",
        description: "Design patents protect ornamental designs (15 years); plant patents protect asexually reproduced plants (20 years).",
        keyPrinciple: "Design patents: ordinary observer test for infringement (Egyptian Goddess, 2008). Plant Variety Protection Act offers separate protection for sexually reproduced varieties.",
        tags: ["IP", "patent", "design"],
      },
      {
        name: "Copyright — originality",
        description: "Original works of authorship fixed in a tangible medium.",
        keyPrinciple: "17 U.S.C. §§ 101-102. Feist v. Rural Telephone (1991): originality requires modicum of creativity; alphabetical white-pages not protectable. Idea/expression dichotomy.",
        citation: "Feist Publ'ns, Inc. v. Rural Tel. Serv. Co., 499 U.S. 340 (1991)",
        tags: ["IP", "copyright"],
        status: "landmark",
      },
      {
        name: "Copyright — fair use",
        description: "Defense permitting limited use of copyrighted material without permission.",
        keyPrinciple: "17 U.S.C. § 107 four factors: purpose and character (including transformativeness), nature of work, amount used, market effect. Campbell v. Acuff-Rose (1994). Andy Warhol v. Goldsmith (2023) tightened transformative test.",
        tags: ["IP", "copyright", "fair-use"],
      },
      {
        name: "DMCA safe harbor",
        description: "Online service providers immune from copyright liability if they comply with notice-and-takedown.",
        keyPrinciple: "17 U.S.C. § 512 (1998). OSP must designate agent, expeditiously remove on notice, terminate repeat infringers, lack actual or red-flag knowledge. Cox Communications (4th Cir. 2018) tightened repeat-infringer requirement.",
        tags: ["IP", "copyright", "DMCA"],
      },
      {
        name: "Trademark — distinctiveness",
        description: "Marks must be distinctive — fanciful, arbitrary, suggestive, or descriptive with secondary meaning.",
        keyPrinciple: "Abercrombie spectrum (1976). Generic marks never protectable. Likelihood-of-confusion test (Polaroid, Sleekcraft factors) governs infringement.",
        tags: ["IP", "trademark"],
      },
      {
        name: "Trademark — dilution",
        description: "Famous marks protected against blurring or tarnishment even without confusion.",
        keyPrinciple: "Federal Trademark Dilution Revision Act (2006). Requires fame, similarity, and either blurring (impairment of distinctiveness) or tarnishment (harm to reputation). Fair use, news reporting, and noncommercial use exempt.",
        tags: ["IP", "trademark", "dilution"],
      },
      {
        name: "Trade secrets",
        description: "Confidential business information that derives value from secrecy.",
        keyPrinciple: "Defend Trade Secrets Act (2016) + state UTSA. Requirements: (1) reasonable measures to maintain secrecy, (2) economic value from secrecy. Coca-Cola formula is the canonical example.",
        tags: ["IP", "trade-secrets"],
      },
      {
        name: "Right of publicity",
        description: "Right to control commercial use of one's name, likeness, voice, and identity.",
        keyPrinciple: "State-law right, varies widely. Zacchini v. Scripps-Howard (1977): SCOTUS recognized constitutional limits. Issues with deepfakes, AI-generated likenesses, and post-mortem rights.",
        tags: ["IP", "publicity", "privacy"],
      },
      {
        name: "Patent eligibility — Alice/Mayo",
        description: "Two-step test for patent-eligible subject matter under § 101.",
        keyPrinciple: "(1) Is the claim directed to a judicial exception (abstract idea, law of nature, natural phenomenon)? (2) If so, does it contain an inventive concept that transforms it? Has invalidated many software and diagnostic-method patents.",
        citation: "Alice Corp. v. CLS Bank Int'l, 573 U.S. 208 (2014)",
        tags: ["IP", "patent", "eligibility"],
        status: "contested",
      },
      {
        name: "First-sale doctrine",
        description: "Owner of a particular copy may sell or dispose of it without copyright holder's consent.",
        keyPrinciple: "17 U.S.C. § 109. Kirtsaeng v. John Wiley & Sons (2013): applies to copies lawfully made anywhere in the world, undercutting attempts at international price discrimination via copyright.",
        tags: ["IP", "copyright", "first-sale"],
      },
      {
        name: "AI training and copyright",
        description: "Whether training generative models on copyrighted works infringes.",
        keyPrinciple: "Contested. Pending litigation: NYT v. OpenAI, Authors Guild v. OpenAI, Getty v. Stability AI. Defendants argue transformative fair use; plaintiffs argue scale and market substitution defeat it. No appellate resolution yet.",
        tags: ["IP", "copyright", "AI"],
        status: "open",
      },
    ],
  },
];
