
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

// With a prisma.config.ts present, Prisma skips its own env-file loading, so
// we load explicitly. This repo keeps DB URLs in .env.local (Next.js
// convention), not .env. dotenv never overrides variables that are already
// set, so real environment variables (e.g. Vercel's) always win.
loadEnv();
loadEnv({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Migrations must use the direct (non-pooled) connection. Fall back to
    // DATABASE_URL so commands that never connect (e.g. `prisma generate`
    // during a Vercel build, where DIRECT_URL may not be set) can still load
    // this config. Do NOT use the throwing env() helper here — a missing var
    // would crash `prisma generate` at config-load time (see 1b5f030's
    // failed Vercel build: "Cannot destructure property 'url'").
    url: process.env.DIRECT_URL ?? process.env.DATABASE_URL ?? "",
  },
});
