import type { Family } from "./data";

// ── SECTION 5: FORMS OF RULE & DEMOCRACY ─────────────────────────────────────

export const DEMOCRATIC_THEORY_FAMILY: Family = {
  slug: "democratic-theory",
  name: "Democratic Theory & Forms",
  blurb: "Models of how 'the people' rule. Catalogued descriptively.",
  color: "teal",
  isms: [
    {
      name: "Democracy",
      description: "Rule by the people; political authority derives from and is accountable to the citizenry.",
      tags: ["ancient","c18"],
      tenet: "Political authority derives from and remains accountable to the citizenry.",
      lineage: { parents: [], divergence: "root — ancient Athenian and Roman republican forms; revived in Enlightenment political theory" },
      figures: ["the Athenian tradition","James Madison","Jean-Jacques Rousseau"],
      era: ["ancient","c18"],
      coreTenets: [
        "Legitimate political authority derives from the consent of the governed.",
        "Citizens have the right to participate in collective decisions that govern their lives.",
        "Accountability mechanisms allow citizens to remove rulers who fail or abuse their mandate.",
      ],
      keyThinkers: ["Pericles' Funeral Oration (reported by Thucydides)","Jean-Jacques Rousseau — The Social Contract","Robert Dahl — Democracy and Its Critics"],
      historicalInstances: ["Athenian democracy (5th–4th c. BCE)","American and French revolutions","Modern liberal democracies"],
      principalCritiques: [
        "Plato argued democracy leads to demagoguery; the many will choose pleasures over wisdom.",
        "Elite theorists (Michels, Mosca) contend democracy inevitably produces oligarchical leadership regardless of formal procedures.",
      ],
    },
    {
      name: "Liberal democracy",
      description: "Majority rule plus rights; combine elected government with constitutional limits and minority protections.",
      tags: ["c18","c19"],
      tenet: "Combine elected majority government with constitutional limits, rule of law, and protected minority rights.",
      lineage: { parents: ["Democracy","Classical liberalism"], divergence: "adds liberal constraints — rights, rule of law, separation of powers — to democratic majority rule" },
      figures: ["James Madison","Alexis de Tocqueville","Robert Dahl"],
      era: ["c18","c19"],
      coreTenets: [
        "Electoral competition between parties provides democratic accountability.",
        "Constitutional rights protect individuals and minorities from majoritarian overreach.",
        "Independent courts, press, and civil society check executive and legislative power.",
      ],
      keyThinkers: ["The Federalist Papers (Madison, Hamilton, Jay)","Alexis de Tocqueville — Democracy in America"],
      historicalInstances: ["American constitutional republic","Western European parliamentary democracies","Post-WWII democratic reconstruction"],
      principalCritiques: [
        "Radicals argue liberal democracy systematically advantages those with economic power over ordinary citizens.",
        "Deliberative democrats contend competitive electoral politics is a poor substitute for genuine public deliberation.",
      ],
    },
    {
      name: "Representative democracy",
      description: "Rule through elected agents; citizens govern indirectly by electing representatives.",
      tags: ["c18"],
      tenet: "Citizens govern indirectly by electing representatives who act on their behalf between elections.",
      lineage: { parents: ["Democracy"], divergence: "indirect form; necessary for large polities where direct participation is impractical" },
      figures: ["James Madison","John Stuart Mill","Edmund Burke"],
      era: ["c18"],
      coreTenets: [
        "Representatives are elected to exercise judgement on behalf of their constituents, not merely to follow instructions.",
        "Regular elections provide accountability without requiring continuous direct participation.",
        "Deliberation among elected representatives produces better outcomes than unmediated popular votes.",
      ],
      keyThinkers: ["Edmund Burke — Speech to the Electors of Bristol","John Stuart Mill — Considerations on Representative Government"],
      principalCritiques: [
        "Direct democrats argue that representation substitutes elite judgement for popular will.",
        "Participatory democrats contend elections are too infrequent and limited to constitute genuine self-governance.",
      ],
    },
    {
      name: "Direct democracy",
      description: "Citizens decide themselves; the people vote directly on laws without representatives.",
      tags: ["ancient","c18"],
      tenet: "The people vote directly on laws and policies rather than delegating authority to representatives.",
      lineage: { parents: ["Democracy"], divergence: "unmediated form; eliminates the representative layer between citizens and decisions" },
      figures: ["Athenian assembly tradition","Jean-Jacques Rousseau (proto)"],
      era: ["ancient","c18"],
      coreTenets: [
        "Genuine self-governance requires that citizens make decisions themselves, not through intermediaries.",
        "Referenda and initiatives allow citizens to bypass representatives on major questions.",
        "A well-informed citizenry can make sound collective decisions through direct deliberation.",
      ],
      keyThinkers: ["Jean-Jacques Rousseau — The Social Contract","Benjamin Barber — Strong Democracy"],
      historicalInstances: ["Athenian ekklesia","Swiss direct democracy (referenda, initiatives)","New England town meetings"],
      principalCritiques: [
        "Madison argued that direct democracy is prone to mob passions that representation filters.",
        "Critics note that direct democracy can be used by majorities to remove rights from minorities.",
      ],
    },
    {
      name: "Deliberative democracy",
      description: "Legitimacy through reasoned debate; decisions are legitimate when they emerge from inclusive deliberation.",
      tags: ["c20"],
      tenet: "Political decisions are legitimate when they emerge from inclusive, rational public deliberation rather than mere majority aggregation.",
      lineage: { parents: ["Democracy"], divergence: "procedural emphasis; legitimacy requires quality of deliberation, not just majority count" },
      figures: ["Jürgen Habermas","John Rawls","Joshua Cohen"],
      era: ["c20"],
      coreTenets: [
        "Democratic legitimacy requires that affected parties have the opportunity to participate in reasoned public debate.",
        "Participants should be willing to revise their preferences in response to better arguments.",
        "Deliberation improves the quality of decisions by forcing consideration of diverse perspectives.",
      ],
      keyThinkers: ["Jürgen Habermas — Between Facts and Norms","John Rawls — Political Liberalism"],
      principalCritiques: [
        "Critics argue that deliberative standards systematically disadvantage those less skilled in formal argumentation.",
        "Agonistic theorists (Mouffe) contend that genuine political conflicts cannot be resolved by rational deliberation.",
      ],
    },
    {
      name: "Participatory democracy",
      description: "Maximise citizen involvement; citizens should engage directly and continuously, not just vote periodically.",
      tags: ["c20"],
      tenet: "Citizens should engage directly and continuously in governance, not merely vote in periodic elections.",
      lineage: { parents: ["Democracy"], divergence: "participatory emphasis; expands the scope and frequency of citizen engagement beyond elections" },
      figures: ["Carole Pateman","the New Left","Arnold Kaufman"],
      era: ["c20"],
      coreTenets: [
        "Political participation is intrinsically valuable: it educates citizens and develops their capacities.",
        "Democracy should extend beyond government into workplaces, schools, and communities.",
        "Low voter turnout and civic disengagement reflect the poverty of existing democratic forms.",
      ],
      keyThinkers: ["Carole Pateman — Participation and Democratic Theory","Benjamin Barber — Strong Democracy"],
      principalCritiques: [
        "Realists argue that most citizens lack the time, information, or interest to participate more actively.",
        "Liberals note that mandatory participation requirements raise coercion concerns.",
      ],
    },
    {
      name: "Illiberal democracy",
      description: "Elections without liberal limits; elected leaders erode checks, rights, and independent institutions.",
      tags: ["c20","c21"],
      tenet: "Elected leaders claim popular mandates to dismantle institutional checks, minority rights, and independent oversight (descriptive category).",
      lineage: { parents: ["Democracy"], divergence: "minus liberal constraints; describes the degradation of liberal democratic systems through electoral means" },
      figures: ["Fareed Zakaria (coined term)"],
      era: ["c20","c21"],
      coreTenets: [
        "Electoral legitimacy is used to justify dismantling the liberal constraints on majority power.",
        "Judicial independence, press freedom, and civil society are targets for executive domination.",
        "Illiberal democracies claim to represent the 'true' will of the people against liberal elites.",
      ],
      keyThinkers: ["Fareed Zakaria — 'The Rise of Illiberal Democracy' (1997)","Steven Levitsky & Daniel Ziblatt — How Democracies Die"],
      historicalInstances: ["Hungary under Fidesz","Turkey under Erdoğan","Poland under Law and Justice"],
      principalCritiques: [
        "Liberal democrats argue illiberal democracy is a contradiction: without rights protection, elections cannot be genuinely free.",
        "Defenders of these regimes argue liberal constraints were elitist impediments to genuine popular sovereignty.",
      ],
    },
    {
      name: "Consociationalism",
      description: "Power-sharing across groups; divided societies governed by elite coalitions and group vetoes.",
      tags: ["c20"],
      tenet: "Divided societies require elite coalitions, group autonomy, proportionality, and mutual vetoes to remain governable.",
      lineage: { parents: ["Democracy"], divergence: "divided-society model; modifies majority-rule democracy with group-based guarantees" },
      figures: ["Arend Lijphart"],
      era: ["c20"],
      coreTenets: [
        "In deeply divided societies, majority rule produces permanent minority exclusion and potential conflict.",
        "Power-sharing, proportionality, mutual veto, and segment autonomy stabilise divided polities.",
        "Elite accommodation at the top is more achievable than mass integration across group boundaries.",
      ],
      keyThinkers: ["Arend Lijphart — The Politics of Accommodation","Arend Lijphart — Democracy in Plural Societies"],
      historicalInstances: ["Netherlands (pillarisation)","Belgium","Lebanon (partially)","Northern Ireland (Good Friday Agreement)","Bosnia-Herzegovina"],
      principalCritiques: [
        "Critics argue consociationalism entrenches group identities rather than building cross-cutting civic integration.",
        "Democrats note that elite bargains in consociational systems can be unresponsive to popular preferences.",
      ],
    },
    {
      name: "Republicanism",
      description: "Liberty as non-domination; freedom means not being subject to arbitrary power.",
      tags: ["ancient","early-modern"],
      tenet: "Freedom means not being subject to arbitrary power (non-domination), sustained by civic virtue and mixed government.",
      lineage: { parents: [], divergence: "root — classical; Roman republican tradition; distinct from both liberal and democratic conceptions of liberty" },
      figures: ["Cicero","Niccolò Machiavelli","Philip Pettit"],
      era: ["ancient","early-modern"],
      coreTenets: [
        "Liberty is freedom from domination — not merely from actual interference but from the capacity for arbitrary interference.",
        "Mixed government balances monarchy, aristocracy, and democracy to prevent any faction from dominating.",
        "Civic virtue — the willingness to participate in self-governance — is essential to maintaining republican freedom.",
      ],
      keyThinkers: ["Cicero — De Re Publica","Niccolò Machiavelli — Discourses on Livy","Philip Pettit — Republicanism"],
      historicalInstances: ["Roman Republic","Florentine republic","American founding (republican elements)"],
      principalCritiques: [
        "Liberals argue non-domination theory expands state power by treating all potential interference as a liberty threat.",
        "Democrats note that classical republicanism historically excluded most people from the civic community.",
      ],
    },
    {
      name: "Sortition / demarchy",
      description: "Govern by lottery; select officeholders randomly from the citizenry.",
      tags: ["ancient","c20"],
      tenet: "Select officeholders randomly from the citizenry to ensure representativeness and curb corruption.",
      lineage: { parents: ["Direct democracy"], divergence: "selection method; replaces voting with random selection as a more representative mechanism" },
      figures: ["the Athenian model","John Burnheim"],
      era: ["ancient","c20"],
      coreTenets: [
        "Elections select for an elite class of professional politicians who don't represent ordinary citizens.",
        "Random selection (as used in Athens and jury systems) produces bodies that statistically resemble the population.",
        "Lottery removes incentives for campaign fundraising, gerrymandering, and electoral manipulation.",
      ],
      keyThinkers: ["John Burnheim — Is Democracy Possible?","David Van Reybrouck — Against Elections"],
      historicalInstances: ["Athenian boule (Council of 500)","Jury selection (continuing)","Citizens' assemblies (Ireland, France, UK)"],
      principalCritiques: [
        "Critics argue randomly selected citizens lack the expertise and commitment for effective governance.",
        "Democrats note that sortition eliminates electoral accountability, the primary mechanism by which citizens can remove bad rulers.",
      ],
    },
    {
      name: "Economic / workplace democracy",
      description: "Democratize the firm; workers should govern their enterprises and the broader economy.",
      tags: ["c20"],
      tenet: "Workers should govern their enterprises democratically, extending democratic principles to economic life.",
      lineage: { parents: ["Democracy","Democratic socialism"], divergence: "applies democratic governance to the workplace and economy, not just political institutions" },
      figures: ["G.D.H. Cole","Robert Dahl","cooperative movement"],
      era: ["c20"],
      coreTenets: [
        "Political democracy is incomplete without economic democracy; workers are governed in their workplaces without their consent.",
        "Worker-owned and self-managed enterprises distribute economic power more equitably.",
        "Workplace democracy develops civic capacities and reduces alienation.",
      ],
      keyThinkers: ["Robert Dahl — A Preface to Economic Democracy","G.D.H. Cole — Guild Socialism Restated"],
      historicalInstances: ["Mondragon Corporation (Spain)","German Mitbestimmung (co-determination)","Yugoslav worker self-management"],
      principalCritiques: [
        "Economists argue that worker self-management creates inefficiencies due to underinvestment and employment preferences.",
        "Liberals note that workers are not consumers of their firms and may have interests in conflict with customers and society.",
      ],
    },
  ],
};

export const AUTHORITARIAN_FAMILY: Family = {
  slug: "authoritarian",
  name: "Authoritarian, Monarchist & Statist Forms",
  blurb: "Concentrated, unaccountable, or hereditary rule. Catalogued descriptively.",
  color: "teal",
  isms: [
    {
      name: "Authoritarianism",
      description: "Order above participation; concentrate power and limit political pluralism.",
      tags: ["c20"],
      tenet: "Concentrate political power and limit pluralism and dissent in the name of order, stability, or national purpose.",
      lineage: { parents: [], divergence: "root — descriptive category for non-democratic regimes that fall short of totalitarianism" },
      figures: ["Juan Linz (scholar)"],
      era: ["c20"],
      coreTenets: [
        "Political order and stability are preconditions for economic development and social peace.",
        "Political pluralism and organised opposition create instability that threatens national interests.",
        "Limited mobilisation distinguishes authoritarianism from totalitarianism: it does not require active ideological participation.",
      ],
      keyThinkers: ["Juan Linz — Totalitarian and Authoritarian Regimes","Samuel Huntington — Political Order in Changing Societies"],
      historicalInstances: ["Franco's Spain","Pinochet's Chile","Most 20th-century military juntas"],
      principalCritiques: [
        "Human rights organisations document systematic torture, disappearances, and suppression of expression under authoritarian regimes.",
        "Political scientists note authoritarianism often produces the instability it claims to prevent.",
      ],
    },
    {
      name: "Totalitarianism",
      description: "The state claims everything; a single party penetrates and controls all public and private life.",
      tags: ["c20"],
      tenet: "A single party and ideology penetrate and control all of public and private life, mobilising citizens into active participation.",
      lineage: { parents: ["Authoritarianism"], divergence: "total-control variant; adds mass mobilisation, ideological pervasion of private life, and the destruction of civil society" },
      figures: ["Hannah Arendt (scholar)","Carl Friedrich (scholar)"],
      era: ["c20"],
      coreTenets: [
        "The party-state penetrates and reorganises all institutions — family, workplace, church, culture.",
        "Active ideological mobilisation of the population is required, not merely passive compliance.",
        "Terror and secret police are tools for maintaining total control by eliminating potential sources of opposition.",
      ],
      keyThinkers: ["Hannah Arendt — The Origins of Totalitarianism","Carl Friedrich & Zbigniew Brzezinski — Totalitarian Dictatorship and Autocracy"],
      historicalInstances: ["Nazi Germany","Stalinist USSR","Maoist China (Cultural Revolution)","North Korea"],
      principalCritiques: [
        "Arendt's analysis documents how totalitarianism destroys the human capacity for thought and action through terror and ideology.",
        "Scholars debate whether 'totalitarianism' is a useful category or one that obscures differences between Nazi and Soviet systems.",
      ],
    },
    {
      name: "Absolutism",
      description: "Unlimited royal sovereignty; the monarch's power is total and not subject to other institutions.",
      tags: ["early-modern"],
      tenet: "The monarch holds absolute sovereignty, not limited by estates, parliament, or any human institution.",
      lineage: { parents: ["Monarchism"], divergence: "unlimited form; eliminates traditional feudal limits on royal authority" },
      figures: ["Jacques-Bénigne Bossuet","Thomas Hobbes (philosophical justification)"],
      era: ["early-modern"],
      coreTenets: [
        "Absolute sovereignty must rest in a single undivided authority to be effective.",
        "Divine right: the king's authority derives from God and cannot be legitimately resisted.",
        "Social peace requires that the sovereign's commands be obeyed without qualification.",
      ],
      keyThinkers: ["Jacques-Bénigne Bossuet — Politics Drawn from the Very Words of Holy Scripture","Jean Bodin — Six Books of the Commonwealth"],
      historicalInstances: ["Louis XIV's France","Hohenzollern Prussia (partially)","Stuart absolutism (attempted, UK)"],
      principalCritiques: [
        "Whigs and constitutionalists argued absolutism makes arbitrary tyranny the constitutional order.",
        "Social contract theorists (Locke) contended that sovereignty derives from the people and cannot be absolute.",
      ],
    },
    {
      name: "Monarchism",
      description: "Rule by a hereditary sovereign; legitimate authority resides in a king or queen.",
      tags: ["ancient"],
      tenet: "Legitimate political authority resides in a hereditary monarch whose succession is regulated by dynastic law.",
      lineage: { parents: [], divergence: "root — ancient; the most widespread historical form of government" },
      figures: ["the royalist traditions"],
      era: ["ancient"],
      coreTenets: [
        "Hereditary succession provides stable, predictable transfer of power without electoral conflict.",
        "The monarch embodies national continuity and provides a focus of loyalty above partisan division.",
        "Dynastic legitimacy, grounded in law and custom, is a firmer foundation than popular election.",
      ],
      keyThinkers: ["Robert Filmer — Patriarcha","Charles Maurras — political monarchism"],
      principalCritiques: [
        "Republicans argue hereditary succession is arbitrary and produces rulers regardless of ability.",
        "Democrats contend monarchism removes political authority from popular accountability.",
      ],
    },
    {
      name: "Constitutional monarchy",
      description: "A crowned, limited head of state; a monarch reigns within constitutional limits.",
      tags: ["c18","c19"],
      tenet: "A monarch reigns within constitutional limits while elected bodies govern; combines tradition with parliamentary accountability.",
      lineage: { parents: ["Monarchism","Whiggism"], divergence: "constitutional limits added to hereditary monarchy; the monarch reigns but does not rule" },
      figures: ["the Westminster tradition"],
      era: ["c18","c19"],
      coreTenets: [
        "The monarch provides national continuity and symbolic unity while Parliament and ministers govern.",
        "Constitutional conventions limit royal prerogative and ensure elected accountability.",
        "The monarchy is a stabilising institution that removes the head of state from partisan competition.",
      ],
      keyThinkers: ["Walter Bagehot — The English Constitution"],
      historicalInstances: ["United Kingdom","Scandinavian monarchies","Netherlands, Belgium, Spain"],
      principalCritiques: [
        "Republicans argue that hereditary heads of state are incompatible with genuine democratic equality.",
        "Critics note that constitutional monarchy concentrates symbolic power and social capital in a hereditary family.",
      ],
    },
    {
      name: "Enlightened absolutism",
      description: "Reform from the throne; an absolute ruler governs rationally for the people's welfare.",
      tags: ["c18"],
      tenet: "An absolute ruler governs according to rational Enlightenment principles for the welfare of the people, without their participation.",
      lineage: { parents: ["Absolutism","Classical liberalism"], divergence: "adds Enlightenment rationalism to absolutist governance; reforms from above without popular input" },
      figures: ["Frederick the Great","Joseph II"],
      era: ["c18"],
      coreTenets: [
        "The monarch's duty is to govern for the welfare of subjects using the best available rational principles.",
        "Reform from above is more effective and less disruptive than reform through popular pressure.",
        "Enlightened rulers should codify laws, promote religious toleration, and develop their states' economies.",
      ],
      keyThinkers: ["Frederick II — Essay on the Forms of Government","Voltaire's correspondence with Frederick"],
      historicalInstances: ["Frederick the Great's Prussia","Joseph II's Austria","Catherine the Great's Russia (partially)"],
      principalCritiques: [
        "Liberals argue enlightened absolutism produces paternalistic governance without accountability.",
        "Democrats note that 'governing for the people but not by the people' is not genuine self-governance.",
      ],
    },
    {
      name: "Bonapartism / Caesarism",
      description: "Strongman above the parties; a charismatic leader claims to embody the whole nation via plebiscite.",
      tags: ["c19"],
      tenet: "A charismatic leader claims to embody the whole nation and govern above partisan division, typically ratified by plebiscite.",
      lineage: { parents: [], divergence: "root — recurring form; distinct from traditional monarchy and fascism; plebiscitary legitimation" },
      figures: ["Napoleon Bonaparte","Louis-Napoleon"],
      era: ["c19"],
      coreTenets: [
        "A strong leader who transcends party divisions can govern in the national interest that faction-ridden parliaments cannot.",
        "Plebiscitary democracy — direct appeals to the people over parliamentary heads — legitimises personal rule.",
        "Caesarism can be either left or right in content; the form is concentration of personal power with popular sanction.",
      ],
      keyThinkers: ["Marx — The Eighteenth Brumaire of Louis Bonaparte (critical analysis)","Max Weber — plebiscitary leadership"],
      historicalInstances: ["Napoleon I and Napoleon III (France)","Gaullism (successor form)","Various 20th-century strongmen"],
      principalCritiques: [
        "Republicans argue plebiscitary legitimation allows leaders to claim mandates for unlimited power.",
        "Democrats note that Caesarism routinely degrades into despotism once the leader's legitimacy is established.",
      ],
    },
    {
      name: "Statism",
      description: "The state as prime mover; the state should direct the economy and society.",
      tags: ["c19","c20"],
      tenet: "The state should actively direct the economy and key social institutions to achieve collective goals.",
      lineage: { parents: [], divergence: "root — descriptive; covers a range of positions from social democracy to authoritarian planning" },
      figures: ["varies"],
      era: ["c19","c20"],
      coreTenets: [
        "Markets and civil society cannot coordinate for collective goals without strong state direction.",
        "The state is the highest expression of collective will and social solidarity.",
        "Strategic industries and social reproduction should be subject to state control or ownership.",
      ],
      keyThinkers: ["Jean-Baptiste Colbert (mercantilist antecedent)","Friedrich List — The National System of Political Economy"],
      principalCritiques: [
        "Liberals argue statism produces inefficiency, bureaucratic capture, and suppression of individual initiative.",
        "Anarchists contend the state is an instrument of domination, not collective self-expression.",
      ],
    },
    {
      name: "Kemalism",
      description: "Secular modernising nationalism; the 'six arrows' of Turkish republican reform.",
      tags: ["c20"],
      tenet: "Modernise and secularise the state through republicanism, nationalism, populism, statism, secularism, and reformism (the six arrows).",
      lineage: { parents: ["Nationalism","Statism"], divergence: "Turkish nationalist-secularist variant; top-down modernisation project combining state-led development with radical secularism" },
      figures: ["Mustafa Kemal Atatürk"],
      era: ["c20"],
      coreTenets: [
        "Religion must be separated from state authority to enable rational governance and national modernisation.",
        "The nation requires active state construction: language, history, and identity are reshaped from above.",
        "Western civilisation provides the model of scientific and political progress that Turkey must adopt.",
      ],
      keyThinkers: ["Atatürk — speeches and reforms","Şükrü Hanioğlu — scholarly analysis"],
      historicalInstances: ["Turkish Republic under Atatürk (1923–38)","Continuing Kemalist political tradition in Turkey"],
      principalCritiques: [
        "Islamists argue Kemalism imposed alien secular values that suppressed Muslim identity and religious practice.",
        "Democrats note that Kemalist secularism was enforced through authoritarian means including restrictions on religious expression.",
      ],
    },
    {
      name: "Technocracy",
      description: "Rule by experts; decisions should be made by qualified specialists rather than politicians.",
      tags: ["c19","c20"],
      tenet: "Governing decisions should be made by qualified specialists using technical knowledge rather than by politicians or popular vote.",
      lineage: { parents: ["Statism"], divergence: "expert-rule variant; removes decision-making from democratic politics into specialist hands" },
      figures: ["Henri de Saint-Simon (proto)","the Technocracy movement (1930s)"],
      era: ["c19","c20"],
      coreTenets: [
        "Complex social problems require specialised knowledge that politicians and voters do not possess.",
        "Scientific and technical expertise provides more reliable guidance than democratic deliberation.",
        "Political irrationality and corruption are avoided when decisions are made on technical rather than partisan grounds.",
      ],
      keyThinkers: ["Thorstein Veblen — The Engineers and the Price System","James Burnham — The Managerial Revolution"],
      historicalInstances: ["Technocracy movement (USA, 1930s)","EU technocratic governance (partially)","IMF/World Bank conditionality"],
      principalCritiques: [
        "Democrats argue technocracy removes decisions from accountability and imposes expert values on citizens.",
        "Political theorists note that 'technical' decisions always embed contested value choices that require democratic legitimation.",
      ],
    },
    {
      name: "Meritocracy",
      description: "Power to the able; positions should be allocated by talent and achievement.",
      tags: ["c20"],
      tenet: "Positions of authority and reward should be allocated by demonstrated talent and achievement, not birth or connections.",
      lineage: { parents: [], divergence: "root — principle that challenges both hereditary aristocracy and democratic equality" },
      figures: ["Michael Young (who coined it critically)"],
      era: ["c20"],
      coreTenets: [
        "Allocating positions by merit (talent plus effort) is more efficient and fairer than allocation by birth.",
        "Equal opportunity is the precondition for meritocracy; disparate outcomes reflect genuine differences in merit.",
        "A meritocratic elite has earned its position and governs more capably than hereditary or elected alternatives.",
      ],
      keyThinkers: ["Michael Young — The Rise of the Meritocracy (critical)","Daniel Markovits — The Meritocracy Trap (critical)"],
      principalCritiques: [
        "Young coined the term in a dystopian novel; he argued meritocracy produces a new class system with moral justification.",
        "Rawlsians argue that talent itself is morally arbitrary; those with natural advantages did not earn them.",
      ],
    },
    {
      name: "Stratocracy",
      description: "Government by the armed forces; the military holds and exercises political authority.",
      tags: ["c20"],
      tenet: "The military holds and directly exercises political authority, typically following a coup.",
      lineage: { parents: ["Authoritarianism"], divergence: "military form; the armed forces as the governing institution rather than a party or monarch" },
      figures: ["various military junta leaders"],
      era: ["c20"],
      coreTenets: [
        "The military is the only institution capable of restoring order when civilian government fails.",
        "A temporary military government protects national interests until conditions for civil government are restored.",
        "Military discipline and hierarchy provide a model for efficient national governance.",
      ],
      keyThinkers: ["various theorists of civil-military relations"],
      historicalInstances: ["Greek junta (1967–74)","Chilean junta (1973–90)","Numerous African and Latin American juntas"],
      principalCritiques: [
        "Human rights organisations document systematic torture, disappearances, and suppression of dissent under military regimes.",
        "Political scientists note military regimes are typically less stable than civilian authoritarian systems.",
      ],
    },
    {
      name: "Sultanism",
      description: "Personalist arbitrary rule; power rests on the ruler's personal discretion and patronage.",
      tags: ["c20"],
      tenet: "Power rests entirely on the ruler's personal discretion and patronage network, with minimal institutional or ideological constraints.",
      lineage: { parents: ["Authoritarianism"], divergence: "personalist extreme; defined by the ruler's personal control of all institutions without a guiding ideology" },
      figures: ["Max Weber (coined term)","Juan Linz (elaborated)"],
      era: ["c20"],
      coreTenets: [
        "All institutions — party, army, bureaucracy — are instruments of the ruler's personal will, not independent actors.",
        "Loyalty to the person, not the institution or ideology, is the key political resource.",
        "The ruler's family and cronies control the economy through direct patronage.",
      ],
      keyThinkers: ["Max Weber — Economy and Society","Juan Linz — Sultanistic Regimes"],
      historicalInstances: ["Trujillo's Dominican Republic","Somoza's Nicaragua","Mobutu's Zaire"],
      principalCritiques: [
        "Political scientists document that sultanistic regimes are highly unstable and collapse catastrophically when the ruler falls.",
        "Governance scholars note that the erosion of institutions under sultanism produces state failure.",
      ],
    },
    {
      name: "Oligarchy",
      description: "Rule by the few; a small group holds power, typically by wealth or birth.",
      tags: ["ancient"],
      tenet: "A small group holds political power to the exclusion of the majority (descriptive/analytical category).",
      lineage: { parents: [], divergence: "root — ancient; Aristotle's classification of the corrupt form of aristocracy" },
      figures: ["Aristotle (analysis)"],
      era: ["ancient"],
      coreTenets: [
        "Political power is concentrated in a small group that governs for its own rather than the common interest.",
        "Wealth is the typical basis of oligarchic power in market societies.",
        "Oligarchies typically combine formal democratic institutions with substantive elite control.",
      ],
      keyThinkers: ["Aristotle — Politics","Gaetano Mosca — The Ruling Class","Robert Michels — Political Parties"],
      principalCritiques: [
        "Democrats argue oligarchy undermines the equal political standing of citizens.",
        "Elite theorists note that all complex societies produce ruling minorities regardless of formal structure.",
      ],
    },
    {
      name: "Theocracy",
      description: "Rule in God's name; religious law and clergy hold ultimate political authority.",
      tags: ["ancient","c20"],
      tenet: "Religious law and clergy hold ultimate political authority; the state governs in the name of divine will.",
      lineage: { parents: [], divergence: "root — ancient; recurs in various religious traditions as an ideal form" },
      figures: ["various religious state leaders"],
      era: ["ancient","c20"],
      coreTenets: [
        "Political authority derives from divine mandate rather than popular consent or hereditary succession.",
        "Religious law provides the ultimate normative framework for governance.",
        "Religious authorities have the right and duty to guide or control political decision-making.",
      ],
      keyThinkers: ["Plato — Euthyphro (divine law)","Islamic jurists (fiqh tradition)"],
      historicalInstances: ["Papal States","Calvinist Geneva","Islamic Republic of Iran","Taliban Afghanistan"],
      principalCritiques: [
        "Liberal secularists argue theocracy imposes one religion's norms on citizens of other faiths.",
        "Religious reformers note that theocratic states often corrupt religious institutions through political entanglement.",
      ],
    },
  ],
};

// ── SECTION 6: RELIGIOUS & THEOLOGICAL POLITICS ─────────────────────────────

export const RELIGIOUS_FAMILY: Family = {
  slug: "religious-theological",
  name: "Religious & Theological Politics",
  blurb: "Ideologies grounding political order in faith. Catalogued descriptively across traditions.",
  color: "purple",
  isms: [
    {
      name: "Political Catholicism",
      description: "Public order on Catholic principles; organise society around Catholic social teaching.",
      tags: ["c19","c20"],
      tenet: "Organise public life around Catholic social teaching: the common good, subsidiarity, and solidarity.",
      lineage: { parents: [], divergence: "root — Catholic Church's engagement with modern politics after the French Revolution" },
      figures: ["Pope Leo XIII","Jacques Maritain"],
      era: ["c19","c20"],
      coreTenets: [
        "Society must be organised around the common good, not merely individual rights or class interests.",
        "Subsidiarity: decisions should be taken at the lowest level capable of making them; the state should not absorb functions proper to families and associations.",
        "Solidarity: persons are social beings whose duties to one another ground a positive social politics.",
      ],
      keyThinkers: ["Leo XIII — Rerum Novarum","Jacques Maritain — Man and the State","John Paul II — Centesimus Annus"],
      historicalInstances: ["Christian Democratic parties in Europe","Catholic trade union movements","Social Catholicism in interwar period"],
      principalCritiques: [
        "Secular liberals argue that Catholic social teaching is a confessional basis for politics that non-Catholics cannot accept.",
        "Socialists contend Catholic social teaching defends private property against genuinely egalitarian redistribution.",
      ],
    },
    {
      name: "Liberation theology",
      description: "A faith of the poor; Christianity demands active struggle against structural injustice.",
      tags: ["c20"],
      tenet: "Christianity demands active commitment to the liberation of the poor from structural injustice, drawing on Marxist social analysis.",
      lineage: { parents: ["Political Catholicism","Marxism"], divergence: "integrates Marxist analysis of structural oppression into Catholic theology; the 'preferential option for the poor'" },
      figures: ["Gustavo Gutiérrez","Leonardo Boff"],
      era: ["c20"],
      coreTenets: [
        "The 'preferential option for the poor' is a scriptural imperative: God's revelation is from the perspective of the oppressed.",
        "Sin is structural as well as personal; unjust economic and political systems are forms of institutionalised sin.",
        "Base communities of the poor reading the Bible together constitute a new form of church.",
      ],
      keyThinkers: ["Gustavo Gutiérrez — A Theology of Liberation","Leonardo Boff — Church: Charism and Power"],
      historicalInstances: ["Latin American base communities (1960s–80s)","Nicaraguan revolution (clerical participants)","Brazilian MST (landless movement)"],
      principalCritiques: [
        "The Vatican (under John Paul II and Ratzinger) criticised liberation theology for adopting Marxist class analysis incompatible with Church teaching.",
        "Conservative critics argue it reduces the Gospel to a political programme.",
      ],
    },
    {
      name: "Christian right / Dominionism",
      description: "Govern by Biblical norms; public life and law should reflect conservative Christian morality.",
      tags: ["c20","c21"],
      tenet: "Public life and law should be governed by Biblical principles and conservative Christian moral teaching.",
      lineage: { parents: ["Social conservatism","Protestant theology"], divergence: "Theonomist/Dominionist strand; seeks to bring all of public life under Biblical governance" },
      figures: ["various US evangelical and fundamentalist political leaders"],
      era: ["c20","c21"],
      coreTenets: [
        "Christian moral principles — on family, sexuality, life — should be embodied in public law.",
        "America was founded as a Christian nation and should return to its Christian heritage.",
        "Dominionism: Christians are called to take dominion over all spheres of society — government, education, media.",
      ],
      keyThinkers: ["Rousas John Rushdoony — The Institutes of Biblical Law (theonomy)","Jerry Falwell — Moral Majority"],
      historicalInstances: ["Moral Majority (USA)","Christian Coalition","Culture war politics (USA)"],
      principalCritiques: [
        "Liberal secularists argue Christian right politics violates the separation of church and state.",
        "Other Christians argue imposing Biblical law by political means misunderstands the nature of Christian witness.",
      ],
    },
    {
      name: "Islamism (Political Islam)",
      description: "Islam as a political system; the state and law should be organised according to Islamic principles.",
      tags: ["c20"],
      tenet: "The state, law, and public life should be organised according to Islamic principles; internally diverse in aims and methods.",
      lineage: { parents: [], divergence: "root — 20th-century movements seeking to apply Islam to political governance" },
      figures: ["Hassan al-Banna","Sayyid Maududi","Sayyid Qutb"],
      era: ["c20"],
      broadFamily: true,
      coreTenets: [
        "Islam is not merely a personal religion but a comprehensive way of life governing politics, law, and society.",
        "The secular nation-state is a Western import incompatible with Islamic governance; sharia should be the supreme law.",
        "Islamic movements range from parliamentary participation to violent revolutionary action; they share the goal of Islamic governance.",
      ],
      keyThinkers: ["Hassan al-Banna — Muslim Brotherhood founding ideas","Sayyid Maududi — Islamic Law and Constitution","Sayyid Qutb — Milestones"],
      historicalInstances: ["Muslim Brotherhood (Egypt, Jordan, etc.)","Islamic Republic of Iran","AKP (Turkey)","Hamas","Various Islamist movements globally"],
      principalCritiques: [
        "Liberal critics argue Islamism seeks to replace the rule of law with religious authority, suppressing minority rights.",
        "Muslim reformers contend that imposing sharia by political force misunderstands the voluntary nature of Islamic ethics.",
      ],
    },
    {
      name: "Salafism",
      description: "Return to the pious ancestors; restore Islam to the practice of its earliest generations.",
      tags: ["c19","c20"],
      tenet: "Restore Islamic practice to the methodology of the Prophet's companions (salaf), the pious ancestors.",
      lineage: { parents: ["Islamism (Political Islam)"], divergence: "purist strand; focuses on individual and communal religious practice aligned with early Muslim generations" },
      figures: ["various revivalist scholars","Ibn Abd al-Wahhab (antecedent)"],
      era: ["c19","c20"],
      coreTenets: [
        "Innovation (bid'a) in religious practice is prohibited; authentic Islam is that of the first three generations of Muslims.",
        "All religious knowledge must be derived from the Quran and authentic Hadith, not later theological traditions.",
        "Salafism ranges from quietist (apolitical) to jihadist variants; the term covers a wide spectrum.",
      ],
      keyThinkers: ["Ibn Taymiyya (medieval reference)","Muhammad ibn Abd al-Wahhab — Kitab al-Tawhid"],
      principalCritiques: [
        "Islamic scholars of other traditions argue Salafism's rejection of classical legal methodology impoverishes Islamic thought.",
        "Anthropologists note that 'authentic early Islam' is partly constructed and contested.",
      ],
    },
    {
      name: "Pan-Islamism",
      description: "Unity of the Muslim world; Muslims worldwide should unite politically.",
      tags: ["c19","c20"],
      tenet: "Muslims worldwide share a common political destiny and should unite, potentially under a renewed caliphate.",
      lineage: { parents: ["Islamism (Political Islam)","Pan-nationalism"], divergence: "adds transnational Islamic solidarity to Islamist politics; religious community as global political unit" },
      figures: ["Jamal al-Din al-Afghani"],
      era: ["c19","c20"],
      coreTenets: [
        "The Muslim umma (community) constitutes a supranational political unity that overrides national borders.",
        "Western colonialism and imperialism have divided and weakened the Muslim world; unity is the response.",
        "A revived caliphate or strong pan-Islamic institution would restore Muslim civilisational strength.",
      ],
      keyThinkers: ["Jamal al-Din al-Afghani — The Refutation of the Materialists"],
      historicalInstances: ["Khilafat movement (India, 1919–24)","OIC (Organisation of Islamic Cooperation)","Various calls for caliphate restoration"],
      principalCritiques: [
        "Nationalist Muslims argue that linguistic, ethnic, and cultural diversity within Islam makes pan-Islamic unity impractical.",
        "Secularists note that pan-Islamism's exclusion of non-Muslims from the political community discriminates against minorities.",
      ],
    },
    {
      name: "Islamic modernism",
      description: "Reconcile Islam and modernity; reinterpret Islamic sources to accommodate reason, science, and reform.",
      tags: ["c19","c20"],
      tenet: "Reinterpret Islamic sources through reason and contextual analysis to reconcile Islam with modern science and governance.",
      lineage: { parents: ["Islamism (Political Islam)"], divergence: "reformist strand; accepts modern knowledge and institutions, reinterprets rather than rejects" },
      figures: ["Muhammad Abduh","Jamal al-Din al-Afghani"],
      era: ["c19","c20"],
      coreTenets: [
        "Islamic thought stagnated; ijtihad (independent reasoning) must be reopened to address modern conditions.",
        "Islam is compatible with reason, science, and democratic governance when properly interpreted.",
        "Western colonialism is best resisted through internal Islamic reform and renewal, not rejection of modernity.",
      ],
      keyThinkers: ["Muhammad Abduh — The Theology of Unity","Fazlur Rahman — Islam and Modernity"],
      principalCritiques: [
        "Salafis and traditionalists argue Islamic modernism compromises revelation by subordinating it to Western rational standards.",
        "Secular Muslims contend that grounding reform in Islamic arguments remains insufficient for fully pluralist societies.",
      ],
    },
    {
      name: "Islamic democracy",
      description: "Faith plus popular sovereignty; reconcile Islamic governance with democratic institutions.",
      tags: ["c20","c21"],
      tenet: "Reconcile Islamic governance with democratic institutions, elections, and consultation (shura).",
      lineage: { parents: ["Islamism (Political Islam)","Democracy"], divergence: "democratic turn; accepts electoral politics as compatible with Islamic governance" },
      figures: ["various Muslim democratic politicians and theorists"],
      era: ["c20","c21"],
      coreTenets: [
        "Shura (consultation) is an Islamic principle compatible with democratic governance.",
        "Islamic democracy accepts elections and pluralism while maintaining Islamic reference points for law and ethics.",
        "Muslim-majority societies can develop their own democratic forms rooted in their religious and cultural traditions.",
      ],
      keyThinkers: ["Rachid Ghannouchi — Public Freedoms in the Islamic State","various AKP theorists"],
      historicalInstances: ["Ennahda (Tunisia)","AKP (Turkey)","PAS (Malaysia, partially)"],
      principalCritiques: [
        "Liberal democrats argue that making Islamic law supreme creates an unequal legal status for non-Muslim minorities.",
        "Islamist fundamentalists contend democratic procedures cannot override divine law.",
      ],
    },
    {
      name: "Religious Zionism",
      description: "Jewish statehood as sacred; the return to and settlement of the land carries religious significance.",
      tags: ["c20"],
      tenet: "The return of the Jewish people to the Land of Israel and its settlement are stages in a sacred process of divine redemption.",
      lineage: { parents: ["Zionism","Orthodox Judaism"], divergence: "religious dimension added to nationalist Zionism; the state as a sacred rather than merely political project" },
      figures: ["Rabbi Abraham Isaac Kook"],
      era: ["c20"],
      coreTenets: [
        "The establishment of the Jewish state is the 'beginning of the flowering of our redemption.'",
        "Settlement of the biblical Land of Israel — including the West Bank — is a religious duty.",
        "The secular Zionist pioneers, unknowingly, are instruments of divine redemption.",
      ],
      keyThinkers: ["Rabbi A.I. Kook — Orot","Rabbi Tzvi Yehuda Kook — extension of his father's thought"],
      historicalInstances: ["Gush Emunim (Bloc of the Faithful)","Religious Zionist settlement movement","National Religious Party (Mafdal) and successors"],
      principalCritiques: [
        "Secular Israelis argue religious Zionism's settlement agenda has undermined prospects for a two-state solution.",
        "Palestinian and Arab critics argue settlement on occupied land violates international law.",
      ],
    },
    {
      name: "Hindu nationalism",
      description: "Politics rooted in Hindu identity; Indian polity should reflect Hindu civilisational values.",
      tags: ["c20"],
      tenet: "The Indian polity should reflect Hindu civilisational values and identity as the basis of national governance.",
      lineage: { parents: ["Religious nationalism"], divergence: "Hindu civilisational variant; applies religious nationalist logic to Hindu identity in India" },
      figures: ["Vinayak Damodar Savarkar"],
      era: ["c20"],
      coreTenets: [
        "Hindu civilisation is the foundation of Indian identity; the state should protect and promote this heritage.",
        "India's secular constitution obscures a Hindu national character that political Hinduism must restore.",
        "Religious minorities are welcome as citizens but must accommodate themselves to Hindu cultural norms.",
      ],
      keyThinkers: ["V.D. Savarkar — Hindutva","Deendayal Upadhyaya — Integral Humanism"],
      historicalInstances: ["RSS","BJP governments","VHP","Hindu nationalist movements"],
      principalCritiques: [
        "Constitutional secularists argue Hindu nationalism violates the guarantee of equal citizenship for all religious communities.",
        "Minority rights advocates document communal violence and discrimination linked to Hindu nationalist politics.",
      ],
    },
    {
      name: "Buddhist socialism",
      description: "The Dharma and equality; Buddhist ethics support cooperative, anti-materialist social organisation.",
      tags: ["c20"],
      tenet: "Buddhist principles of interdependence, compassion, and non-attachment support cooperative, equitable social organisation.",
      lineage: { parents: ["Democratic socialism","Buddhism"], divergence: "Buddhist ethical grounding of socialist politics; detachment from material accumulation as a social as well as personal virtue" },
      figures: ["U Nu","B.R. Ambedkar-adjacent","Sulak Sivaraksa"],
      era: ["c20"],
      coreTenets: [
        "Greed (lobha) is a root cause of suffering at both the individual and social level; a just society reduces structural greed.",
        "The Buddhist principles of interdependence and compassion support cooperative rather than competitive economic arrangements.",
        "Right livelihood — work that does not harm others — is both a personal and social-political standard.",
      ],
      keyThinkers: ["Sulak Sivaraksa — Seeds of Peace","Bhikkhu Buddhadasa — Dhammic Socialism"],
      historicalInstances: ["U Nu's Burma","Ambedkar's Buddhist social movement","Engaged Buddhist movements"],
      principalCritiques: [
        "Political secularists argue that Buddhist socialism imports contested religious metaphysics into political economy.",
        "Socialists note that Buddhist emphasis on individual transformation can depoliticise structural inequalities.",
      ],
    },
    {
      name: "Confucian political thought",
      description: "Order through virtue and hierarchy; good government rests on moral cultivation and benevolent hierarchy.",
      tags: ["ancient","c20"],
      tenet: "Good governance rests on the moral cultivation of rulers and the observance of hierarchical roles defined by ritual propriety.",
      lineage: { parents: [], divergence: "root — ancient Chinese political philosophy; revived in modern 'New Confucian' political theory" },
      figures: ["Confucius","Mencius","New Confucians (contemporary)"],
      era: ["ancient","c20"],
      coreTenets: [
        "Rulers must cultivate their own virtue (ren — humaneness) before they can govern others rightly.",
        "The five relationships — ruler-minister, father-son, husband-wife, elder-younger, friend-friend — constitute the social order.",
        "Political legitimacy rests on the ruler's virtuous conduct rather than on popular election.",
      ],
      keyThinkers: ["Confucius — Analects","Mencius — Mencius","Kang Youwei — modern Confucian constitutionalism"],
      historicalInstances: ["Imperial Chinese governance","East Asian developmental states (partial)","Singapore (Confucian reference)"],
      principalCritiques: [
        "Liberals argue Confucian hierarchy is incompatible with equal political standing.",
        "Feminists note that the Confucian gender hierarchy systematically subordinates women.",
      ],
    },
    {
      name: "Caliphate / Khilafat",
      description: "Unified Islamic leadership; the Muslim community led by a successor to the Prophet.",
      tags: ["ancient","c20"],
      tenet: "The Muslim community should be led by a caliph — successor to the Prophet — governing by Islamic law.",
      lineage: { parents: [], divergence: "root — classical Islamic institution; revived as a political aspiration in modern Islamist movements" },
      figures: ["classical Islamic jurists","Khilafat movement leaders"],
      era: ["ancient","c20"],
      coreTenets: [
        "The caliphate was the legitimate political institution of early Islam; its restoration is a religious obligation.",
        "A universal Islamic political community (umma) requires a head with religious and political authority.",
        "The division of the Muslim world into nation-states is an artificial colonial imposition.",
      ],
      keyThinkers: ["Al-Mawardi — The Ordinances of Government","Abu Ala Maududi — caliphate theory"],
      historicalInstances: ["Rashidun, Umayyad, and Abbasid caliphates","Ottoman caliphate claim","Khilafat movement (India)","ISIS caliphate claim (2014–19)"],
      principalCritiques: [
        "Muslim political theorists debate whether the classical caliphate is a religious requirement or a historical contingency.",
        "International lawyers note that establishing a transnational theocratic state conflicts with the sovereignty of existing states.",
      ],
    },
    {
      name: "Caesaropapism",
      description: "One ruler over church and state; secular and religious supreme authority united in a single sovereign.",
      tags: ["ancient","early-modern"],
      tenet: "Secular and religious supreme authority are united in a single sovereign who governs both temporal and spiritual affairs.",
      lineage: { parents: [], divergence: "root — Byzantine model; distinct from theocracy (clergy rule) and from secular state" },
      figures: ["Byzantine emperors","Russian Tsars"],
      era: ["ancient","early-modern"],
      coreTenets: [
        "The emperor or tsar exercises authority over the church as well as the state, appointing bishops and convening councils.",
        "Religious and political unity reinforce each other; a divided authority would weaken both.",
        "The Christian emperor's rule is an image of divine rule on earth.",
      ],
      keyThinkers: ["Eusebius of Caesarea — Life of Constantine (justification)","Justinian — legal-religious legislation"],
      historicalInstances: ["Byzantine Empire","Russian Orthodox Church under the Tsars","Henry VIII's Church of England (partial)"],
      principalCritiques: [
        "The papacy argued that caesaropapism subordinated spiritual authority to temporal power, corrupting the church.",
        "Church historians note that imperial control of the church produced theological politics rather than pastoral care.",
      ],
    },
  ],
};

export const FAMILIES_S5_S6: Family[] = [
  DEMOCRATIC_THEORY_FAMILY,
  AUTHORITARIAN_FAMILY,
  RELIGIOUS_FAMILY,
];
