import type { Family } from "./types";

export const FAMILIES_8_14: Family[] = [
  // ── Family 8 ──────────────────────────────────────────────────────────────
  {
    slug: "memory",
    number: 8,
    name: "Memory",
    blurb: "Systems, stages, and the malleability of the record we believe in.",
    section: "C",
    color: "green",
    entries: [
      {
        name: "Atkinson-Shiffrin multi-store model",
        description: "Sensory register → short-term store → long-term store.",
        keyFact: "1968 modal model. Information is transferred between stores by rehearsal and attention; the long-term store is essentially unlimited.",
        researcher: "Atkinson & Shiffrin",
        tags: ["memory", "model"],
        status: "landmark",
      },
      {
        name: "Sensory memory",
        description: "Brief, modality-specific buffers.",
        keyFact: "Iconic memory (Sperling 1960): ~250 ms decay. Echoic memory: ~3–4 s. Capacity is large; persistence is fleeting.",
        researcher: "George Sperling",
        tags: ["memory", "sensory"],
      },
      {
        name: "Short-term memory & Miller's 7±2",
        description: "Limited-capacity, limited-duration store.",
        keyFact: "Miller (1956): \"the magical number seven plus or minus two\" chunks. Later estimates (Cowan) put capacity closer to 4 chunks.",
        researcher: "George Miller, Nelson Cowan",
        tags: ["memory", "STM", "Miller"],
        status: "landmark",
      },
      {
        name: "Working memory (Baddeley)",
        description: "Multi-component active maintenance system.",
        keyFact: "Central executive coordinates phonological loop (verbal), visuospatial sketchpad (visual), and episodic buffer (integration). Replaced \"STM\" in modern cognitive psychology.",
        researcher: "Alan Baddeley",
        tags: ["working-memory", "Baddeley"],
        status: "landmark",
      },
      {
        name: "Declarative vs procedural memory",
        description: "Knowing that vs knowing how.",
        keyFact: "Declarative (explicit): episodic + semantic; medial temporal lobe. Procedural (implicit): skills, habits; basal ganglia and cerebellum. HM kept procedural; lost declarative.",
        researcher: "Larry Squire",
        tags: ["memory", "MTL"],
        xref: ["biology"],
      },
      {
        name: "Episodic vs semantic memory",
        description: "Personal events vs general knowledge.",
        keyFact: "Tulving's distinction (1972). Episodic is autonoetic (re-experiential); semantic is noetic (knowing without remembering).",
        researcher: "Endel Tulving",
        tags: ["memory", "Tulving"],
      },
      {
        name: "Levels of processing",
        description: "Deeper, semantic processing yields better memory than shallow, perceptual processing.",
        keyFact: "Craik & Lockhart (1972). \"Is the word in capital letters?\" → poor recall. \"Does the word fit the sentence?\" → excellent recall.",
        researcher: "Craik & Lockhart",
        tags: ["memory", "encoding"],
      },
      {
        name: "Encoding specificity",
        description: "Retrieval is best when cues match the encoding context.",
        keyFact: "Godden & Baddeley (1975): divers who learned words underwater recalled best underwater. State-dependent and mood-congruent recall are related phenomena.",
        researcher: "Tulving & Thomson, Godden & Baddeley",
        tags: ["memory", "retrieval"],
      },
      {
        name: "Forgetting curve",
        description: "Memory decays as a power-law function of time.",
        keyFact: "Ebbinghaus (1885) memorized nonsense syllables and plotted savings vs delay. ~50% forgotten within an hour, but the curve flattens; well-encoded material persists for years.",
        formula: "R = e^{-t/S}",
        researcher: "Hermann Ebbinghaus",
        tags: ["memory", "forgetting", "Ebbinghaus"],
        status: "landmark",
      },
      {
        name: "Interference theory",
        description: "Forgetting is caused by competing memories, not passive decay.",
        keyFact: "Proactive interference: old memories block new ones. Retroactive interference: new memories block old ones. The dominant theory of long-term forgetting.",
        tags: ["forgetting", "interference"],
      },
      {
        name: "Reconsolidation",
        description: "Reactivated memories become labile and must be re-stabilized.",
        keyFact: "Nader, Schafe & LeDoux (2000): a memory is not a fixed record but a process that can be modified each time it is retrieved. Basis for emerging PTSD treatments.",
        researcher: "Karim Nader",
        tags: ["memory", "reconsolidation"],
        xref: ["medicine"],
        status: "landmark",
      },
      {
        name: "Eyewitness misinformation",
        description: "Post-event information rewrites memory of the original event.",
        keyFact: "Loftus & Palmer (1974): \"smashed\" vs \"hit\" changed speed estimates and the false report of broken glass. Foundational for the unreliability of eyewitness testimony.",
        researcher: "Elizabeth Loftus",
        tags: ["memory", "Loftus", "false-memory"],
        status: "landmark",
      },
      {
        name: "Flashbulb memories",
        description: "Vivid, confidently held memories of surprising or emotional events.",
        keyFact: "Brown & Kulik (1977) proposed a special mechanism. Later work (Talarico & Rubin) shows they decay like ordinary memories — only confidence stays high. The vividness is the illusion.",
        researcher: "Roger Brown, James Kulik",
        tags: ["memory", "flashbulb"],
        status: "contested",
      },
      {
        name: "Testing effect (retrieval practice)",
        description: "Retrieving information strengthens it more than re-reading.",
        keyFact: "Roediger & Karpicke (2006). Active retrieval — even with errors — boosts long-term retention more than equivalent study time. One of the most replicated effects in education.",
        researcher: "Roediger & Karpicke",
        tags: ["memory", "education", "testing-effect"],
        status: "landmark",
      },
    ],
  },

  // ── Family 9 ──────────────────────────────────────────────────────────────
  {
    slug: "attention",
    number: 9,
    name: "Attention",
    blurb: "The selection that makes a perceptual world possible — and what slips through it.",
    section: "C",
    color: "amber",
    entries: [
      {
        name: "Cocktail party effect",
        description: "Selective attention to one voice in a noisy room.",
        keyFact: "Cherry (1953) showed listeners could track one ear's content while remaining oblivious to the other — except for high-priority stimuli like one's own name.",
        researcher: "Colin Cherry",
        tags: ["attention", "selective"],
        status: "landmark",
      },
      {
        name: "Broadbent's filter theory",
        description: "Attention is an early all-or-nothing filter on sensory input.",
        keyFact: "Information from the unattended channel is blocked before semantic analysis. Pure version refuted by name-recognition findings.",
        researcher: "Donald Broadbent",
        tags: ["attention", "early-selection"],
        status: "contested",
      },
      {
        name: "Treisman's attenuation theory",
        description: "Unattended input is not blocked but attenuated.",
        keyFact: "Allows highly salient or low-threshold words to break through. Reconciled the cocktail party effect with selective attention.",
        researcher: "Anne Treisman",
        tags: ["attention", "attenuation"],
        status: "landmark",
      },
      {
        name: "Late selection theory",
        description: "All input is processed semantically before selection.",
        keyFact: "Deutsch & Deutsch (1963). Modern view: selection occurs at multiple stages depending on task demands.",
        tags: ["attention", "late-selection"],
      },
      {
        name: "Divided attention",
        description: "Performing multiple tasks at once.",
        keyFact: "Dual-task performance falls off sharply when tasks share modality or process. \"Multitasking\" is mostly fast switching, not parallel processing.",
        tags: ["attention", "dual-task"],
      },
      {
        name: "Stroop effect",
        description: "Naming the color of a word is slowed when the word is an incongruent color name.",
        keyFact: "Stroop (1935): RED printed in blue takes longer to name than XXX printed in blue. Demonstrates automatic reading; widely used as an executive-function measure.",
        researcher: "John Ridley Stroop",
        tags: ["attention", "Stroop", "interference"],
        status: "landmark",
      },
      {
        name: "Inattentional blindness",
        description: "Failure to notice an unexpected stimulus while attending elsewhere.",
        keyFact: "Simons & Chabris (1999): ~50% of viewers counting basketball passes failed to notice a person in a gorilla suit walking through.",
        researcher: "Simons & Chabris",
        tags: ["attention", "blindness", "gorilla"],
        status: "landmark",
      },
      {
        name: "Change blindness",
        description: "Failure to detect substantial changes across views.",
        keyFact: "Rensink et al. (1997). A brief flicker or saccade is enough to mask a large change. Refutes the intuition that we hold a detailed mental picture of the scene.",
        tags: ["attention", "blindness", "change"],
        status: "landmark",
      },
      {
        name: "Posner cueing paradigm",
        description: "Spatial cues facilitate detection at the cued location.",
        keyFact: "Posner (1980) distinguished exogenous (peripheral, automatic) and endogenous (central, voluntary) orienting and their distinct time courses.",
        researcher: "Michael Posner",
        tags: ["attention", "cueing"],
        status: "landmark",
      },
      {
        name: "Attentional blink",
        description: "Failure to detect a second target within ~200–500 ms of a first.",
        keyFact: "Identified by Raymond, Shapiro & Arnell (1992) in rapid serial visual presentation. Suggests a temporal bottleneck in conscious selection.",
        tags: ["attention", "blink"],
      },
      {
        name: "Vigilance and sustained attention",
        description: "Maintaining attention to infrequent signals over long periods.",
        keyFact: "Performance decrements within 30 min — the vigilance decrement, well documented in radar operators and TSA screeners. ADHD prominently affects sustained attention.",
        tags: ["attention", "vigilance"],
        xref: ["medicine"],
      },
      {
        name: "Feature integration theory",
        description: "Visual features are bound into objects only with focused attention.",
        keyFact: "Treisman (1980). Pop-out (single-feature) search is parallel; conjunction search (e.g. red verticals among red horizontals and green verticals) is serial.",
        researcher: "Anne Treisman",
        tags: ["attention", "FIT", "binding"],
        status: "landmark",
      },
    ],
  },

  // ── Family 10 ─────────────────────────────────────────────────────────────
  {
    slug: "cognition-language",
    number: 10,
    name: "Cognition: Language & Thinking",
    blurb: "Categories, concepts, reasoning, and the structures of language.",
    section: "C",
    color: "rose",
    entries: [
      {
        name: "Language acquisition device (LAD)",
        description: "Hypothesized innate mechanism for acquiring grammar.",
        keyFact: "Chomsky (1959, 1965): the poverty of the stimulus argues for an innate Universal Grammar. The strong nativist version is heavily contested by usage-based approaches.",
        researcher: "Noam Chomsky",
        tags: ["language", "Chomsky", "UG"],
        status: "contested",
      },
      {
        name: "Critical period for language",
        description: "A window in which language acquisition occurs effortlessly.",
        keyFact: "Lenneberg (1967). Late L1 acquisition (\"Genie\", deaf isolates) produces lasting deficits, especially in syntax. The endpoint is gradual, not sharp.",
        researcher: "Eric Lenneberg",
        tags: ["language", "critical-period"],
      },
      {
        name: "Phonemes, morphemes, syntax",
        description: "Hierarchical units of language.",
        keyFact: "Phoneme: minimal sound unit (~40 in English). Morpheme: minimal meaning unit (cat-s = 2 morphemes). Syntax: rules combining words into sentences.",
        tags: ["language", "linguistics"],
      },
      {
        name: "Sapir-Whorf hypothesis",
        description: "Language shapes thought (linguistic relativity).",
        keyFact: "Strong form (\"language determines thought\") has been refuted. Weak form (language influences thought) has empirical support — color discrimination, spatial frames, grammatical gender.",
        researcher: "Sapir, Whorf",
        tags: ["language", "Whorf"],
        xref: ["philosophy"],
        status: "contested",
      },
      {
        name: "Mental imagery",
        description: "Quasi-perceptual representation in the absence of external stimulus.",
        keyFact: "Kosslyn (1980): imagery uses depictive representations, supported by overlap with visual cortex. Pylyshyn's propositional account remains a dissent.",
        researcher: "Stephen Kosslyn",
        tags: ["imagery", "visual"],
        status: "contested",
      },
      {
        name: "Mental rotation",
        description: "Imagined rotation of objects takes time proportional to the angle.",
        keyFact: "Shepard & Metzler (1971): response time scales linearly with rotation angle, suggesting analog (not propositional) representation.",
        formula: "RT \\propto \\theta",
        researcher: "Shepard & Metzler",
        tags: ["imagery", "rotation"],
        status: "landmark",
      },
      {
        name: "Categorization & prototype theory",
        description: "Categories organized around best examples, not strict definitions.",
        keyFact: "Rosch (1973): \"robin\" is a better bird than \"penguin\". Typicality effects and family resemblance defeat classical (necessary and sufficient features) views.",
        researcher: "Eleanor Rosch",
        tags: ["concepts", "prototype", "Rosch"],
        status: "landmark",
      },
      {
        name: "Concept formation",
        description: "Learning which features define category membership.",
        keyFact: "Exemplar models (Medin, Nosofsky) and theory-based views (Murphy & Medin) supplement prototype theory. Concepts are richer than feature lists.",
        tags: ["concepts", "exemplar"],
      },
      {
        name: "Problem-solving and means-end analysis",
        description: "Breaking goal-distance into sub-goals.",
        keyFact: "Newell & Simon's General Problem Solver (1959) used means-end analysis on the Tower of Hanoi and Missionaries-and-Cannibals.",
        researcher: "Newell & Simon",
        tags: ["problem-solving", "GPS"],
        xref: ["mathematics"],
        status: "landmark",
      },
      {
        name: "Functional fixedness",
        description: "Difficulty using an object in a non-standard way.",
        keyFact: "Duncker's candle problem (1945): subjects fail to use a tack box as a candle platform because they see it as a container.",
        researcher: "Karl Duncker",
        tags: ["problem-solving", "fixedness"],
      },
      {
        name: "Algorithm vs heuristic",
        description: "Guaranteed solution procedures vs cognitive shortcuts.",
        keyFact: "Algorithms always solve when applicable but are often intractable. Heuristics (rules of thumb) are fast but fallible.",
        tags: ["reasoning", "heuristic"],
        xref: ["mathematics"],
      },
      {
        name: "Insight problems",
        description: "Solutions arrive suddenly after impasse, often with an \"Aha!\".",
        keyFact: "Distinguished from incremental problems by feeling-of-knowing patterns and a right-temporal EEG gamma burst (Kounios & Beeman 2004).",
        tags: ["insight", "aha"],
      },
      {
        name: "Theories of intelligence",
        description: "What \"$g$\" is and whether there is one.",
        keyFact: "Spearman's $g$ (general factor) is robustly found in factor analyses; Cattell split it into fluid (Gf) and crystallized (Gc). Gardner's multiple intelligences lacks psychometric support but is influential in education.",
        researcher: "Spearman, Cattell, Gardner",
        tags: ["intelligence", "g-factor"],
        xref: ["statistics"],
      },
    ],
  },

  // ── Family 11 ─────────────────────────────────────────────────────────────
  {
    slug: "judgment-decision",
    number: 11,
    name: "Judgment & Decision-Making",
    blurb: "How humans actually decide — and how systematically they depart from expected utility.",
    section: "C",
    color: "violet",
    entries: [
      {
        name: "Expected utility theory",
        description: "Rational choice maximizes expected utility.",
        keyFact: "$EU(A) = \\sum_i p_i u(x_i)$. Normative benchmark from von Neumann & Morgenstern; descriptively violated by virtually every human.",
        formula: "EU(A) = \\sum_i p_i\\, u(x_i)",
        researcher: "von Neumann & Morgenstern",
        tags: ["decision", "EU"],
        xref: ["mathematics"],
      },
      {
        name: "Bounded rationality",
        description: "Rationality limited by information, time, and cognitive capacity.",
        keyFact: "Simon's satisficing (1956) — choosing the first acceptable option, not the best. Foundational for behavioral economics.",
        researcher: "Herbert Simon",
        tags: ["decision", "Simon"],
        status: "landmark",
      },
      {
        name: "Prospect theory",
        description: "People evaluate outcomes as gains/losses from a reference point, with loss aversion and probability weighting.",
        keyFact: "Kahneman & Tversky (1979). Value function is concave for gains, convex for losses, steeper for losses (loss aversion ~2:1). Probability weights overweight small probabilities.",
        formula: "V(x) = \\begin{cases} x^\\alpha & x \\geq 0 \\\\ -\\lambda(-x)^\\beta & x < 0 \\end{cases}",
        researcher: "Kahneman & Tversky",
        tags: ["decision", "Kahneman", "prospect"],
        xref: ["mathematics"],
        status: "landmark",
      },
      {
        name: "Loss aversion",
        description: "Losses loom larger than equivalent gains.",
        keyFact: "Tversky & Kahneman (1991). The pain of losing $100 is ~2× the pleasure of gaining $100. Underlies the endowment effect and status-quo bias.",
        tags: ["decision", "loss-aversion"],
      },
      {
        name: "Anchoring",
        description: "Initial values bias subsequent estimates.",
        keyFact: "Tversky & Kahneman (1974): asked whether the % of UN African countries is above or below a random number, judges anchored on the random number. Robust even when anchor is obviously irrelevant.",
        tags: ["heuristic", "anchoring"],
      },
      {
        name: "Availability heuristic",
        description: "Judging frequency by ease of recall.",
        keyFact: "Tversky & Kahneman (1973). Why people overestimate plane-crash and shark-attack risk and underestimate stroke and stomach-cancer risk.",
        tags: ["heuristic", "availability"],
      },
      {
        name: "Representativeness heuristic",
        description: "Judging probability by resemblance.",
        keyFact: "Tversky & Kahneman (1972): the Linda problem — \"feminist bank teller\" judged more likely than \"bank teller\" (conjunction fallacy). Defeats Bayesian updating.",
        tags: ["heuristic", "representativeness"],
        status: "landmark",
      },
      {
        name: "Framing effects",
        description: "Equivalent options elicit different choices depending on description.",
        keyFact: "Asian disease problem (Tversky & Kahneman 1981): \"save 200 of 600\" → risk-averse; \"400 die\" → risk-seeking. Same outcomes, different choices.",
        tags: ["decision", "framing"],
      },
      {
        name: "Confirmation bias",
        description: "Preferential search for and weighting of belief-confirming evidence.",
        keyFact: "Wason's 2-4-6 task (1960): subjects rarely test their hypothesis with disconfirming cases. Pervasive in motivated reasoning.",
        researcher: "Peter Wason",
        tags: ["bias", "confirmation"],
        status: "landmark",
      },
      {
        name: "Sunk cost fallacy",
        description: "Continuing because of past investment, irrational under EU theory.",
        keyFact: "\"Throwing good money after bad\". Robust in humans and partly in some animals (an interesting cross-species effect).",
        tags: ["bias", "sunk-cost"],
      },
      {
        name: "Dual-process theory (System 1 / 2)",
        description: "Fast, automatic, intuitive vs slow, controlled, deliberate processing.",
        keyFact: "Stanovich, Evans, Kahneman's Thinking, Fast and Slow (2011). Useful organizing metaphor; specific dual-process models vary widely.",
        researcher: "Stanovich, Evans, Kahneman",
        tags: ["decision", "dual-process"],
        xref: ["philosophy"],
      },
      {
        name: "Bayesian updating",
        description: "Rational belief revision via Bayes' rule.",
        keyFact: "$P(H \\mid E) = P(E \\mid H)P(H)/P(E)$. Humans systematically under-update (conservatism) or over-update (base-rate neglect) depending on framing.",
        formula: "P(H \\mid E) = \\frac{P(E \\mid H)\\, P(H)}{P(E)}",
        tags: ["decision", "Bayes"],
        xref: ["mathematics", "statistics"],
      },
      {
        name: "Ego depletion (refuted)",
        description: "Self-control draws on a limited resource that fatigues with use.",
        keyFact: "Baumeister et al. (1998). Multi-lab Registered Replication Report (Hagger et al. 2016) found $d \\approx 0.04$ — essentially zero. The original effect does not replicate.",
        researcher: "Roy Baumeister",
        tags: ["self-control", "refuted"],
        status: "refuted",
      },
    ],
  },

  // ── Family 12 ─────────────────────────────────────────────────────────────
  {
    slug: "developmental",
    number: 12,
    name: "Developmental Psychology",
    blurb: "Lifespan trajectories — cognition, attachment, morality, identity, aging.",
    section: "D",
    color: "indigo",
    entries: [
      {
        name: "Piaget's stages",
        description: "Sensorimotor → preoperational → concrete operational → formal operational.",
        keyFact: "Piaget (1936). Stage ages are now considered too late: object permanence emerges earlier (Baillargeon), theory of mind emerges around 4. Stages themselves are descriptively useful but not strictly invariant.",
        researcher: "Jean Piaget",
        tags: ["development", "Piaget", "stages"],
        status: "landmark",
      },
      {
        name: "Conservation",
        description: "Recognizing that quantity is preserved despite perceptual changes.",
        keyFact: "Pouring liquid from a short wide glass into a tall thin one: preoperational children say there is now \"more\". Acquired around age 7 in Western samples; varies by culture.",
        tags: ["development", "conservation"],
      },
      {
        name: "Object permanence",
        description: "Objects continue to exist when out of sight.",
        keyFact: "Piaget put it at ~8 months. Baillargeon's violation-of-expectation paradigm (1985) finds evidence as early as 3–4 months.",
        researcher: "Renée Baillargeon",
        tags: ["development", "permanence"],
      },
      {
        name: "Theory of mind",
        description: "Understanding that others have mental states different from one's own.",
        keyFact: "Sally-Anne false-belief task: ~50% pass at age 4, ~85% by age 5. Explicit ToM is delayed in autism; implicit ToM (looking-time) may emerge much earlier.",
        researcher: "Wimmer & Perner",
        tags: ["development", "ToM", "false-belief"],
        status: "landmark",
      },
      {
        name: "Vygotsky's zone of proximal development",
        description: "The gap between what a learner can do alone and with guidance.",
        keyFact: "Vygotsky (1934). Scaffolding (Bruner) is the mechanism. The social/cultural counterweight to Piaget.",
        researcher: "Lev Vygotsky",
        tags: ["development", "Vygotsky", "ZPD"],
      },
      {
        name: "Attachment theory",
        description: "Early infant–caregiver bond shapes later relational expectations.",
        keyFact: "Bowlby (1969). Internal working models of self and other persist into adulthood; predicts a modest portion of relationship outcomes.",
        researcher: "John Bowlby",
        tags: ["attachment", "Bowlby"],
        status: "landmark",
      },
      {
        name: "Strange situation",
        description: "Lab procedure classifying infant attachment style.",
        keyFact: "Ainsworth (1978). Secure (~60%), anxious-ambivalent (~10%), anxious-avoidant (~20%), disorganized (~5–15%). Cross-cultural distributions vary.",
        researcher: "Mary Ainsworth",
        tags: ["attachment", "Ainsworth"],
        status: "landmark",
      },
      {
        name: "Harlow's monkeys",
        description: "Infant rhesus monkeys preferred a cloth surrogate over a wire one with food.",
        keyFact: "Harlow (1958) refuted the dominant \"cupboard theory\" of attachment (that babies bond because of feeding). Contact comfort matters more than calories.",
        researcher: "Harry Harlow",
        tags: ["attachment", "Harlow", "contact-comfort"],
        status: "landmark",
      },
      {
        name: "Erikson's psychosocial stages",
        description: "Eight lifespan crises, from trust-vs-mistrust to integrity-vs-despair.",
        keyFact: "Erikson (1950). More speculative than Piaget; influential as a framework for adolescent identity formation (identity vs role confusion).",
        researcher: "Erik Erikson",
        tags: ["development", "Erikson"],
      },
      {
        name: "Kohlberg's moral development",
        description: "Pre-conventional → conventional → post-conventional moral reasoning.",
        keyFact: "Heinz dilemma. Critiqued for cultural and gender bias (Gilligan's care ethics); the stage scoring system itself is rarely used today.",
        researcher: "Lawrence Kohlberg",
        tags: ["development", "Kohlberg", "moral"],
        xref: ["philosophy"],
        status: "contested",
      },
      {
        name: "Marshmallow test",
        description: "Delay of gratification predicts later life outcomes.",
        keyFact: "Mischel (1972). Original effects were large; pre-registered replication (Watts, Duncan & Quan 2018) found effects shrink to near zero after controlling for family background and cognitive ability.",
        researcher: "Walter Mischel",
        tags: ["development", "marshmallow"],
        status: "contested",
      },
      {
        name: "Sensitive periods",
        description: "Windows of heightened plasticity for specific functions.",
        keyFact: "Imprinting (Lorenz), binocular vision (Hubel & Wiesel kitten work), L1 language. Strict critical-period claims have been softened toward graded sensitivity.",
        researcher: "Konrad Lorenz",
        tags: ["development", "sensitive-period"],
        xref: ["biology"],
      },
      {
        name: "Identity formation in adolescence",
        description: "Exploration of and commitment to identity domains.",
        keyFact: "Marcia (1966): identity achievement, moratorium, foreclosure, diffusion. Identity work continues into emerging adulthood (Arnett).",
        researcher: "James Marcia, Jeffrey Arnett",
        tags: ["development", "identity"],
      },
      {
        name: "Cognitive aging",
        description: "Fluid abilities decline from ~20s; crystallized abilities remain stable or rise.",
        keyFact: "Salthouse: processing speed declines linearly through adulthood. Working memory and inhibition decline; vocabulary and accumulated knowledge are preserved or grow.",
        tags: ["aging", "cognition"],
        xref: ["medicine"],
      },
    ],
  },

  // ── Family 13 ─────────────────────────────────────────────────────────────
  {
    slug: "personality",
    number: 13,
    name: "Personality & Individual Differences",
    blurb: "Traits, structure, and the heritability of who we are.",
    section: "D",
    color: "blue",
    entries: [
      {
        name: "Big Five (OCEAN)",
        description: "Openness, Conscientiousness, Extraversion, Agreeableness, Neuroticism.",
        keyFact: "Emerged from factor analysis of trait adjectives (Tupes & Christal 1961; Costa & McCrae's NEO-PI-R). Replicated across languages and cultures; the dominant trait taxonomy.",
        researcher: "Costa & McCrae",
        tags: ["personality", "Big-Five", "OCEAN"],
        xref: ["statistics"],
        status: "landmark",
      },
      {
        name: "HEXACO",
        description: "Six-factor extension: Big Five + Honesty-Humility.",
        keyFact: "Ashton & Lee (2007). Honesty-Humility captures sincerity, fairness, greed avoidance, modesty — variance not absorbed by Big Five A.",
        researcher: "Ashton & Lee",
        tags: ["personality", "HEXACO"],
      },
      {
        name: "Cattell's 16PF",
        description: "Sixteen primary personality factors derived from lexical analysis.",
        keyFact: "Cattell (1957). Higher-order factors largely correspond to the Big Five — but the 16-factor structure has not replicated as cleanly.",
        researcher: "Raymond Cattell",
        tags: ["personality", "Cattell"],
        status: "contested",
      },
      {
        name: "Eysenck's PEN model",
        description: "Three super-factors: Psychoticism, Extraversion, Neuroticism.",
        keyFact: "Eysenck linked E and N to biological substrates (arousal and limbic reactivity). P was the most controversial and has the weakest replication.",
        researcher: "Hans Eysenck",
        tags: ["personality", "Eysenck"],
        xref: ["biology"],
      },
      {
        name: "MBTI (Myers-Briggs)",
        description: "Sixteen types based on four dichotomies.",
        keyFact: "Test-retest reliability is poor (~50% type-stability over weeks). Most personality variation is continuous, not categorical. Widely used commercially despite no psychometric standing.",
        tags: ["personality", "MBTI"],
        status: "refuted",
      },
      {
        name: "Dark triad / dark tetrad",
        description: "Machiavellianism, narcissism, psychopathy (+ sadism).",
        keyFact: "Paulhus & Williams (2002). Negatively correlated with Agreeableness and Honesty-Humility. Useful in organizational and forensic prediction.",
        researcher: "Paulhus & Williams",
        tags: ["personality", "dark-triad"],
      },
      {
        name: "Cardinal, central, secondary traits",
        description: "Allport's nominal taxonomy of trait centrality.",
        keyFact: "Cardinal (life-organizing); central (5–10 defining traits); secondary (situational preferences). Pre-Big-Five but conceptually rich.",
        researcher: "Gordon Allport",
        tags: ["personality", "Allport"],
      },
      {
        name: "Behavioral genetics",
        description: "Twin and adoption studies decompose variance into genetic, shared, and non-shared environmental components.",
        keyFact: "Heritability of personality traits ~40–50%. Shared environment contributes near zero to adult personality (Plomin et al.) — surprising and replicated.",
        researcher: "Robert Plomin",
        tags: ["genetics", "twin-studies"],
        xref: ["biology", "statistics"],
        status: "landmark",
      },
      {
        name: "Person vs situation debate",
        description: "Do traits or situations better predict behavior?",
        keyFact: "Mischel (1968) showed trait-behavior correlations rarely exceed ~0.3. Resolved (mostly) by interactionism: traits predict aggregate behavior; situations dominate single acts.",
        researcher: "Walter Mischel",
        tags: ["personality", "consistency"],
        status: "landmark",
      },
      {
        name: "General intelligence (g)",
        description: "A common factor underlying performance on diverse cognitive tasks.",
        keyFact: "Spearman (1904). $g$ has predictive validity for education, job performance, health, and mortality. Heritability rises with age (~0.7 in adulthood).",
        researcher: "Charles Spearman",
        tags: ["intelligence", "g-factor"],
        xref: ["statistics"],
        status: "landmark",
      },
      {
        name: "Fluid vs crystallized intelligence",
        description: "Reasoning capacity vs accumulated knowledge.",
        keyFact: "Cattell, Horn. Gf peaks in 20s and declines; Gc rises into 60s and is largely preserved in normal aging.",
        researcher: "Cattell, Horn",
        tags: ["intelligence", "Gf", "Gc"],
      },
      {
        name: "Flynn effect",
        description: "Secular IQ score gains of ~3 points per decade through the 20th century.",
        keyFact: "Flynn (1984). Largest gains on Raven's Progressive Matrices. Has stalled or reversed in several Western countries since the 1990s.",
        researcher: "James Flynn",
        tags: ["intelligence", "Flynn"],
        status: "contested",
      },
      {
        name: "Multiple intelligences (Gardner)",
        description: "Linguistic, logical-mathematical, spatial, musical, bodily-kinesthetic, interpersonal, intrapersonal, naturalistic.",
        keyFact: "Gardner (1983). Influential in education but lacks psychometric support — the proposed \"intelligences\" do not load on independent factors.",
        researcher: "Howard Gardner",
        tags: ["intelligence", "Gardner"],
        status: "contested",
      },
      {
        name: "Stereotype threat",
        description: "Anxiety about confirming a stereotype impairs performance.",
        keyFact: "Steele & Aronson (1995). Many-lab replication (Flore et al. 2018) and meta-analyses found small or null effects under registered protocols. Effect-size estimates have shrunk substantially.",
        researcher: "Claude Steele",
        tags: ["social", "stereotype-threat"],
        status: "contested",
      },
    ],
  },

  // ── Family 14 ─────────────────────────────────────────────────────────────
  {
    slug: "motivation-emotion",
    number: 14,
    name: "Motivation & Emotion",
    blurb: "What moves us — drives, incentives, appraisals, and the affective response system.",
    section: "D",
    color: "rose",
    entries: [
      {
        name: "Maslow's hierarchy of needs",
        description: "Physiological → safety → belongingness → esteem → self-actualization.",
        keyFact: "Maslow (1943). Pyramid was added by later authors. The strict prepotency claim — that lower needs must be met first — has weak empirical support.",
        researcher: "Abraham Maslow",
        tags: ["motivation", "Maslow"],
        status: "contested",
      },
      {
        name: "Self-determination theory (SDT)",
        description: "Three innate psychological needs: autonomy, competence, relatedness.",
        keyFact: "Deci & Ryan (1985, 2000). Predicts intrinsic motivation, well-being, and engagement across cultures. Among the best-supported general theories.",
        researcher: "Deci & Ryan",
        tags: ["motivation", "SDT"],
        status: "landmark",
      },
      {
        name: "Intrinsic vs extrinsic motivation",
        description: "Doing for its own sake vs for external reward.",
        keyFact: "Overjustification effect (Deci 1971, Lepper et al. 1973): rewarding intrinsically motivated behavior can reduce it. Tangible expected rewards have the strongest undermining effect.",
        tags: ["motivation", "intrinsic"],
        status: "landmark",
      },
      {
        name: "Drive-reduction theory",
        description: "Motivation arises from need-driven physiological imbalance.",
        keyFact: "Hull (1943). Failed to explain curiosity, sensation-seeking, or play — behaviors that increase, not reduce, arousal.",
        researcher: "Clark Hull",
        tags: ["motivation", "drive"],
        status: "refuted",
      },
      {
        name: "Yerkes-Dodson law",
        description: "Performance peaks at intermediate arousal; the optimum is lower for hard tasks.",
        keyFact: "Yerkes & Dodson (1908). Often drawn as an inverted U; the original mouse data were limited and the empirical generality is weaker than commonly presented.",
        formula: "\\text{Performance} \\sim \\text{arousal} \\cdot \\text{difficulty}",
        researcher: "Yerkes & Dodson",
        tags: ["arousal", "Yerkes-Dodson"],
      },
      {
        name: "Achievement motivation",
        description: "The drive to attain and excel at standards of excellence.",
        keyFact: "McClelland's nAch, measured by TAT. Atkinson's expectancy × value formulation: motivation = need × probability of success × incentive value.",
        researcher: "David McClelland, John Atkinson",
        tags: ["motivation", "achievement"],
      },
      {
        name: "James-Lange theory",
        description: "Emotion is the perception of bodily change caused by stimulus.",
        keyFact: "James (1884), Lange (1885): we feel sad because we cry. Reframed by modern somatic-marker and interoceptive theories of emotion.",
        researcher: "William James, Carl Lange",
        tags: ["emotion", "James-Lange"],
      },
      {
        name: "Cannon-Bard theory",
        description: "Emotion and bodily change occur simultaneously.",
        keyFact: "Cannon (1927) critique of James-Lange. Animals with severed sympathetic input still showed emotion; bodily responses too slow and indistinct.",
        researcher: "Walter Cannon",
        tags: ["emotion", "Cannon-Bard"],
      },
      {
        name: "Schachter-Singer two-factor",
        description: "Emotion = unexplained arousal + cognitive label.",
        keyFact: "Schachter & Singer (1962): epinephrine-injected subjects in a euphoric or angry confederate's company labeled their arousal accordingly. Replication has been mixed.",
        researcher: "Schachter & Singer",
        tags: ["emotion", "two-factor"],
        status: "contested",
      },
      {
        name: "Basic emotions (Ekman)",
        description: "Six (or seven) universal emotions with distinctive facial expressions.",
        keyFact: "Ekman & Friesen (1971): happiness, sadness, fear, anger, surprise, disgust (+ contempt) recognized cross-culturally. Universality has been narrowed; Western influence in source cultures (Crivelli et al. 2016) is a significant confound.",
        researcher: "Paul Ekman",
        tags: ["emotion", "basic", "Ekman"],
        status: "contested",
      },
      {
        name: "Constructivist theory of emotion",
        description: "Emotions are constructed from core affect + concept knowledge.",
        keyFact: "Barrett (2017). Predicts variable, culture-specific neural and behavioral signatures of emotion — and is supported by null findings for fingerprint patterns of basic emotions.",
        researcher: "Lisa Feldman Barrett",
        tags: ["emotion", "constructivist", "Barrett"],
      },
      {
        name: "Appraisal theory",
        description: "Emotions arise from interpretations of events relative to goals.",
        keyFact: "Lazarus, Scherer. Different appraisals (novelty, valence, agency, coping) produce different emotions from the same event.",
        researcher: "Richard Lazarus, Klaus Scherer",
        tags: ["emotion", "appraisal"],
      },
      {
        name: "Facial feedback hypothesis",
        description: "Facial expressions feed back into the felt emotion.",
        keyFact: "Strack pen-in-mouth study (1988) replicated $d \\approx 0.02$ in Wagenmakers et al.'s Many Labs RRR (2016). The strong version does not hold; weaker modulatory effects may.",
        tags: ["emotion", "facial-feedback"],
        status: "contested",
      },
      {
        name: "Emotion regulation (Gross)",
        description: "Antecedent-focused vs response-focused strategies.",
        keyFact: "Reappraisal generally outperforms suppression on well-being and physiology. The process model is widely used in CBT and DBT.",
        researcher: "James Gross",
        tags: ["emotion", "regulation"],
        xref: ["medicine"],
      },
    ],
  },
];
