import type { Family } from "./types";

export const FAMILIES_17_24: Family[] = [
  // ── Family 17 ─────────────────────────────────────────────────────────────
  {
    slug: "atmospheric-geoscience",
    number: 17,
    name: "Atmospheric Geoscience & Climate Geology",
    blurb: "Earth's atmosphere through time; paleoclimate proxies and Quaternary climate.",
    section: "C",
    color: "sky",
    entries: [
      {
        name: "Earth's atmosphere — composition and structure",
        description: "78% $\\mathrm{N_2}$, 21% $\\mathrm{O_2}$, ~1% Ar, ~420 ppm $\\mathrm{CO_2}$, variable $\\mathrm{H_2O}$.",
        keyFact: "Vertical structure: troposphere (0–12 km, weather), stratosphere (12–50 km, ozone), mesosphere (50–85 km), thermosphere (>85 km). Boundary-layer mixing; stratospheric thermal inversion; mesopause is coldest natural Earth-surface temperature (~$-90$°C).",
        xref: ["chemistry"],
        tags: ["atmosphere", "structure"],
      },
      {
        name: "Great Oxidation Event",
        description: "Atmospheric $\\mathrm{O_2}$ rose from <0.001% to ~1–10% PAL between ~2.5–2.0 Ga.",
        keyFact: "Recorded by mass-independent fractionation of S isotopes ($\\Delta^{33}\\mathrm{S}$) — present pre-GOE, absent after. Driven by cyanobacterial oxygenic photosynthesis outpacing reductant supply. Cause of banded iron formation deposition.",
        status: "landmark",
        tags: ["goe", "oxygenation", "cyanobacteria"],
      },
      {
        name: "Banded iron formations (BIFs)",
        description: "Iron-rich Precambrian sedimentary rocks; thin layers of magnetite/hematite + chert.",
        keyFact: "Mostly 2.5–1.8 Ga; minor Phanerozoic. Source of >90% of mineable iron worldwide. Form when reduced $\\mathrm{Fe^{2+}}$-rich seawater meets photosynthetic $\\mathrm{O_2}$, precipitating $\\mathrm{Fe_2O_3}$/$\\mathrm{Fe_3O_4}$.",
        tags: ["bif", "iron", "precambrian"],
      },
      {
        name: "Greenhouse and icehouse climates",
        description: "Long-term alternations between warm ice-free and cold polar-ice states.",
        keyFact: "Phanerozoic: hot Cambrian-Ordovician (greenhouse), late Paleozoic ice age (icehouse), Mesozoic greenhouse, Cenozoic icehouse with progressive cooling since ~50 Ma. Driven by paleogeography, $\\mathrm{CO_2}$, weathering.",
        tags: ["greenhouse", "icehouse"],
      },
      {
        name: "Milankovitch cycles",
        description: "Orbital pacing of glacial cycles: eccentricity (~100 kyr), obliquity (~41 kyr), precession (~21 kyr).",
        keyFact: "Demonstrated by Hays, Imbrie & Shackleton (1976) from deep-sea $\\delta^{18}\\mathrm{O}$ records. Drove Pleistocene glaciations. Mid-Pleistocene transition (~1 Ma): glacial periodicity shifted from 41-kyr to 100-kyr dominance.",
        status: "landmark",
        xref: ["physics"],
        tags: ["milankovitch", "orbital", "pleistocene"],
      },
      {
        name: "Last Glacial Maximum",
        description: "Most recent peak of Pleistocene ice volume, ~26.5–19 ka.",
        keyFact: "Sea level ~130 m below present; Laurentide and Fennoscandian ice sheets covered N. America and N. Europe; Beringia exposed enabling human dispersal to Americas. $\\mathrm{CO_2}$ ~180 ppm. Atmospheric $\\mathrm{CO_2}$ lag and lead vs temperature is mechanistically rich.",
        tags: ["lgm", "ice-age"],
      },
      {
        name: "Younger Dryas",
        description: "Abrupt ~1,200-yr cold reversal ~12,900–11,700 yr ago.",
        keyFact: "Greenland $\\delta^{18}\\mathrm{O}$ dropped within decades. Likely triggered by meltwater pulse disrupting AMOC; alternative impact hypothesis (Younger Dryas Impact) remains controversial. Termination in ~10 yr.",
        status: "open",
        tags: ["younger-dryas", "abrupt-climate"],
      },
      {
        name: "Holocene climate optimum and Holocene stability",
        description: "Climatically stable interglacial of the past ~11.7 kyr.",
        keyFact: "Holocene Climatic Optimum (~8,000–5,000 BP): mid-latitudes ~1–2 °C warmer than late-Holocene mean. Enabled agriculture, urbanization. Mid-Holocene insolation differs from present; climate models tested against proxy data.",
        tags: ["holocene", "interglacial"],
      },
      {
        name: "Anthropocene",
        description: "Proposed epoch marking dominant human geologic impact.",
        keyFact: "Stratigraphy Subcommission (2024) declined to formalize. Proposed GSSP at Crawford Lake (Ontario) with 1952 plutonium fallout horizon. Many geologists support concept but disagree on whether it merits formal chronostratigraphic status.",
        status: "open",
        tags: ["anthropocene", "icsac"],
      },
      {
        name: "Paleotemperature proxies",
        description: "Quantitative paleothermometry from biogenic and geochemical archives.",
        keyFact: "$\\delta^{18}\\mathrm{O}$ in forams, $\\mathrm{Mg/Ca}$ in foram calcite, alkenones ($U^{K'}_{37}$) in coccolithophores, TEX86 in archaea, fluid inclusions, $\\Delta_{47}$ clumped-isotope thermometry. Multi-proxy approaches resist single-proxy biases.",
        xref: ["chemistry"],
        tags: ["paleothermometer", "alkenone", "clumped"],
      },
      {
        name: "Carbon dioxide record",
        description: "Atmospheric $\\mathrm{CO_2}$ measured directly (Mauna Loa, 1958–) and from ice cores.",
        keyFact: "Keeling curve (1958–present): annual cycle on 1.7-ppm/yr secular rise. Crossed 420 ppm in 2024. Ice cores extend to 800 ka with Pleistocene oscillations of 180–280 ppm. Highest level in millions of years.",
        status: "landmark",
        tags: ["keeling", "co2"],
      },
      {
        name: "Climate sensitivity",
        description: "Equilibrium $\\Delta T$ for doubled $\\mathrm{CO_2}$.",
        keyFact: "IPCC AR6 likely range 2.5–4.0 °C; best estimate 3 °C. Constrained by paleoclimate (LGM, PETM, Pliocene), modern instrumental, and climate model emergent constraints. Long-debated; recent tightening reduced upper-tail risk.",
        xref: ["statistics", "physics"],
        tags: ["climate-sensitivity", "ar6"],
      },
    ],
  },

  // ── Family 18 ─────────────────────────────────────────────────────────────
  {
    slug: "stratigraphy",
    number: 18,
    name: "Stratigraphy",
    blurb: "The order and arrangement of rock layers — relative time and correlation.",
    section: "D",
    color: "amber",
    entries: [
      {
        name: "Law of superposition",
        description: "In undisturbed sequences, younger strata overlie older ones.",
        keyFact: "Articulated by Nicolas Steno (1669). The cornerstone of relative dating. Way-up structures (cross-bedding, mud cracks, graded bedding) are needed in deformed sequences to tell whether overturning has occurred.",
        status: "landmark",
        tags: ["superposition", "steno"],
      },
      {
        name: "Original horizontality",
        description: "Strata are originally deposited approximately horizontal.",
        keyFact: "Steno's second principle. Tilted strata therefore record post-depositional deformation. Sedimentary geometry preserves the original depositional surface as a datum.",
        tags: ["horizontality", "steno"],
      },
      {
        name: "Lateral continuity",
        description: "Layers extend laterally until they thin to zero or are interrupted.",
        keyFact: "Steno's third principle. Justifies correlation of stratigraphic units across gaps (gorges, eroded outcrops). Used in well-log correlation by basinal sedimentologists.",
        tags: ["lateral-continuity", "correlation"],
      },
      {
        name: "Cross-cutting relationships",
        description: "Geologic features that cut other features are younger.",
        keyFact: "Articulated by James Hutton (1788, Theory of the Earth). Dikes cutting strata, faults cutting plutons, and unconformities cutting tilted layers all yield relative age sequences.",
        tags: ["cross-cutting", "hutton"],
      },
      {
        name: "Uniformitarianism",
        description: "Present geologic processes also operated in the past.",
        keyFact: "Hutton (1788), Lyell (1830). Often paraphrased as 'the present is the key to the past.' Now refined: process rates may vary (catastrophism partially rehabilitated by impacts, supereruptions, Snowball Earth).",
        status: "landmark",
        tags: ["uniformitarianism", "hutton", "lyell"],
      },
      {
        name: "Unconformities",
        description: "Surfaces of erosion or non-deposition representing missing time.",
        keyFact: "Types: angular unconformity (tilted lower beds), nonconformity (sediment on igneous/metamorphic basement), disconformity (parallel beds), paraconformity (cryptic break). Hutton's angular unconformity at Siccar Point demonstrated 'no vestige of a beginning.'",
        tags: ["unconformity", "siccar-point"],
      },
      {
        name: "Biostratigraphy",
        description: "Correlation by characteristic fossil assemblages.",
        keyFact: "William Smith's principle of faunal succession (1815): fossils succeed in a definite, recognizable order. Best with rapidly evolving, widely distributed taxa (graptolites, ammonites, conodonts, forams). Defines zones.",
        status: "landmark",
        tags: ["biostratigraphy", "smith", "faunal-succession"],
      },
      {
        name: "Lithostratigraphy",
        description: "Rock-based subdivision — formations, members, beds, groups.",
        keyFact: "Lithologic units defined by physical characteristics, mapped at field scale. Formation = mappable rock unit (~10s–100s m thick). North American Stratigraphic Code formalizes the rules.",
        tags: ["lithostratigraphy", "formation"],
      },
      {
        name: "Chronostratigraphy",
        description: "Time-based subdivision: eon → era → period → epoch → age.",
        keyFact: "Defined by GSSPs (Global Stratotype Section and Points) — 'golden spikes' placed at specific outcrops by the International Commission on Stratigraphy. Each GSSP defines the base of a chronostratigraphic unit.",
        tags: ["chronostratigraphy", "gssp", "icsac"],
      },
      {
        name: "Chemostratigraphy",
        description: "Correlation using time-varying geochemical signals.",
        keyFact: "Marine $^{87}\\mathrm{Sr}/^{86}\\mathrm{Sr}$, $\\delta^{13}\\mathrm{C}$, $\\delta^{18}\\mathrm{O}$, $\\mathrm{Os}$ isotopes. Global signals propagate via ocean mixing within ~1,000 yr — better resolution than biostratigraphy for some intervals.",
        tags: ["chemostratigraphy", "isotope"],
      },
      {
        name: "Magnetostratigraphy",
        description: "Correlation using the sequence of magnetic reversals.",
        keyFact: "Geomagnetic Polarity Time Scale (GPTS) provides ~140 reversals across the Cenozoic. Reversal events are essentially globally synchronous (within ~1 kyr), giving high-resolution correlation across continents.",
        tags: ["magnetostratigraphy", "gpts"],
      },
      {
        name: "Sequence boundaries and GSSPs",
        description: "Formal global definitions of chronostratigraphic boundaries.",
        keyFact: "K-Pg GSSP at El Kef (Tunisia) — defined by Ir anomaly + foram extinction. Permian-Triassic GSSP at Meishan (China) — first appearance of Hindeodus parvus conodont. P-Tr extinction is the worst on record (~96% marine species).",
        tags: ["gssp", "k-pg", "p-tr"],
      },
    ],
  },

  // ── Family 19 ─────────────────────────────────────────────────────────────
  {
    slug: "geochronology",
    number: 19,
    name: "Geologic Time Scale & Geochronology",
    blurb: "Numerical ages: how we measure deep time.",
    section: "D",
    color: "violet",
    entries: [
      {
        name: "Age of Earth",
        description: "~4.567 billion years.",
        keyFact: "Established by $\\mathrm{Pb-Pb}$ dating of CAIs (calcium-aluminum-rich inclusions) in carbonaceous chondrites (e.g. Allende). Earth itself ~4.54 Ga (oldest dated terrestrial: Jack Hills zircons, 4.404 Ga). Clair Patterson 1956 gave the modern value.",
        status: "landmark",
        tags: ["age-of-earth", "patterson", "cai"],
      },
      {
        name: "Half-life",
        description: "Time for half of a radioactive parent to decay.",
        keyFact: "$T_{1/2} = \\ln 2 / \\lambda$. Common geochronologic systems: $^{14}\\mathrm{C}$ (5,730 yr), $^{40}\\mathrm{K}$ (1.25 Gyr), $^{87}\\mathrm{Rb}$ (49 Gyr), $^{238}\\mathrm{U}$ (4.47 Gyr), $^{235}\\mathrm{U}$ (704 Myr). Each suits a different age range.",
        formula: "T_{1/2} = \\ln 2 / \\lambda",
        xref: ["physics"],
        tags: ["half-life", "decay-constant"],
      },
      {
        name: "U-Pb zircon geochronology",
        description: "Twin decay series of $^{235}\\mathrm{U}$ and $^{238}\\mathrm{U}$ to $\\mathrm{Pb}$.",
        keyFact: "Most precise tool for dating rocks ≥1 Ma. Zircon ($\\mathrm{ZrSiO_4}$) excludes Pb at crystallization and resists isotopic disturbance. Concordia diagrams reveal disturbance. SHRIMP, LA-ICP-MS, and ID-TIMS span scales from grain interiors (Ma) to single crystals (ka).",
        status: "landmark",
        tags: ["u-pb", "zircon", "concordia"],
      },
      {
        name: "Ar-Ar geochronology",
        description: "$^{40}\\mathrm{Ar}/^{39}\\mathrm{Ar}$ dating of K-bearing minerals.",
        keyFact: "Refinement of K-Ar that uses neutron irradiation to convert $^{39}\\mathrm{K}$ to $^{39}\\mathrm{Ar}$. Step-heating spectra reveal disturbance and partial argon loss. Dates micas, feldspars, hornblende, volcanic glass; main tool for Cenozoic and Mesozoic volcanic ages.",
        tags: ["ar-ar", "step-heating"],
      },
      {
        name: "Radiocarbon ($^{14}$C) dating",
        description: "Decay of cosmogenic $^{14}\\mathrm{C}$ in organic matter.",
        keyFact: "Half-life 5,730 yr; useful range ~50,000 yr. Atmospheric $^{14}\\mathrm{C}$ variability requires calibration (IntCal). Bomb spike (post-1950) is also used. Revolutionized late Pleistocene archaeology and Holocene geology.",
        xref: ["physics"],
        tags: ["c14", "intcal"],
      },
      {
        name: "Cosmogenic exposure dating",
        description: "$^{10}\\mathrm{Be}$, $^{26}\\mathrm{Al}$, $^{36}\\mathrm{Cl}$, $^3\\mathrm{He}$ produced in surface rocks by cosmic rays.",
        keyFact: "Production rates depend on altitude and latitude. Used to date moraines, fluvial terraces, fault scarps, glacial erratics over $10^3$–$10^6$ yr. Burial dating uses parallel decay of two cosmogenic nuclides at depth.",
        tags: ["cosmogenic", "10be", "exposure"],
      },
      {
        name: "Fission track dating",
        description: "Dating damage tracks from $^{238}\\mathrm{U}$ spontaneous fission.",
        keyFact: "Apatite (~110 °C closure) and zircon (~240 °C) are workhorses for low-temperature thermochronology. Track-length distributions reveal cooling history through the partial annealing zone — used in mountain-belt exhumation studies.",
        tags: ["fission-track", "thermochronology"],
      },
      {
        name: "U-Th/He thermochronology",
        description: "Helium produced by $\\alpha$-decay; degasses below closure temperature.",
        keyFact: "Apatite $\\mathrm{(U-Th)/He}$ closure ~70 °C; zircon ~180 °C. Low-T thermochronometer for upper-crustal exhumation, fault-block uplift, and landscape evolution.",
        tags: ["u-th-he", "thermochronology"],
      },
      {
        name: "Geologic time scale (ICS chart)",
        description: "Hierarchical international chronostratigraphic chart.",
        keyFact: "International Commission on Stratigraphy maintains the chart; updated periodically with new GSSPs and refined ages. Hierarchy: Eon → Era → Period → Epoch → Age (Stage). The Phanerozoic was historically defined first; the Precambrian only later subdivided.",
        status: "landmark",
        tags: ["time-scale", "ics"],
      },
      {
        name: "Astrochronology",
        description: "Using Milankovitch cycles preserved in strata as time-counters.",
        keyFact: "Cyclostratigraphy ties orbital periods (~21, 41, 100, 405 kyr) to bedding rhythms; eccentricity 405-kyr cycle is the metronome of the Cenozoic. Refines numerical ages and ties geologic time scale to astronomical solutions.",
        xref: ["physics"],
        tags: ["astrochronology", "milankovitch"],
      },
      {
        name: "Concordia and discordia",
        description: "Graphical representation of $\\mathrm{U}$-$\\mathrm{Pb}$ ages from twin decay systems.",
        keyFact: "Concordia: locus of $^{206}\\mathrm{Pb}/^{238}\\mathrm{U}$ vs $^{207}\\mathrm{Pb}/^{235}\\mathrm{U}$ for closed-system ages. Discordia: chord through analyses disturbed by Pb loss — upper intercept gives true crystallization age, lower intercept the disturbance age.",
        tags: ["concordia", "discordia", "u-pb"],
      },
      {
        name: "Closure temperature",
        description: "Temperature at which a thermochronometer 'starts the clock.'",
        keyFact: "Dodson (1973) formalism. U-Pb zircon ~900 °C, $^{40}\\mathrm{Ar}/^{39}\\mathrm{Ar}$ hornblende ~530 °C, biotite ~310 °C, K-feldspar ~150–350 °C, fission track apatite ~110 °C, $\\mathrm{(U-Th)/He}$ apatite ~70 °C. Multi-system gives full thermal history.",
        xref: ["physics"],
        tags: ["closure", "thermochronology", "dodson"],
      },
    ],
  },

  // ── Family 20 ─────────────────────────────────────────────────────────────
  {
    slug: "paleontology",
    number: 20,
    name: "Paleontology",
    blurb: "Life through geologic time — fossils, evolution, and mass extinctions.",
    section: "D",
    color: "green",
    entries: [
      {
        name: "Fossil — definition and modes of preservation",
        description: "Remains, traces, or chemical signatures of past life preserved in rock.",
        keyFact: "Preservation modes: original (amber, freeze-dried mammoths), unaltered hard parts (shells, teeth, bone), permineralization (petrified wood), recrystallization, replacement (pyritization, silicification), molds and casts, trace fossils, chemical biomarkers.",
        tags: ["fossil", "preservation"],
      },
      {
        name: "Lagerstätten",
        description: "Exceptionally preserved fossil deposits.",
        keyFact: "Examples: Burgess Shale (Cambrian soft-bodied fauna), Solnhofen (Jurassic Archaeopteryx), Mazon Creek (Carboniferous), Maotianshan (Cambrian), Messel Pit (Eocene), Yixian (Cretaceous feathered dinosaurs). Disproportionate paleontologic impact.",
        tags: ["lagerstaette", "burgess-shale"],
      },
      {
        name: "Stromatolites",
        description: "Layered microbial structures — the oldest fossils.",
        keyFact: "Date to at least 3.48 Ga (Strelley Pool, Western Australia). Modern stromatolites at Shark Bay, Australia, are rare relics. Confirm the existence of life on early Earth and provide context for atmospheric oxygenation.",
        status: "landmark",
        tags: ["stromatolite", "archaean", "early-life"],
      },
      {
        name: "Cambrian explosion",
        description: "Abrupt appearance of most modern animal phyla ~538–520 Ma.",
        keyFact: "Earliest small-shelly fossils ~539 Ma; Burgess Shale (508 Ma) and Maotianshan (518 Ma) preserve full phyla. Possible drivers: $\\mathrm{O_2}$ rise, ecological feedback (predation), genetic innovation. Caused much debate over rate vs preservation.",
        status: "landmark",
        tags: ["cambrian-explosion", "phyla"],
      },
      {
        name: "Plant fossil record",
        description: "Land plants from ~470 Ma to present.",
        keyFact: "Cooksonia (Silurian) earliest vascular plant; Devonian forests (Archaeopteris); Carboniferous coal swamps (Lycopsida, Sphenopsida); seed plants (gymnosperms) Devonian-Mesozoic dominance; angiosperms (flowering plants) explode in mid-Cretaceous.",
        tags: ["plant-fossil", "angiosperm"],
      },
      {
        name: "Vertebrate origins",
        description: "Vertebrates from late Cambrian agnathans to modern.",
        keyFact: "Earliest fish: Haikouichthys (Cambrian). Tetrapods emerge from sarcopterygians in Devonian (Tiktaalik, Ichthyostega). Amniotes (reptile-line) Carboniferous. Mammals from synapsid lineage; first true mammals Late Triassic.",
        tags: ["vertebrate", "tetrapod", "tiktaalik"],
      },
      {
        name: "Dinosaurs",
        description: "Reptilian clade dominant Late Triassic to End Cretaceous.",
        keyFact: "Originated ~233 Ma (Carnian); diversified through Jurassic–Cretaceous. Two main groups: Saurischia (sauropods, theropods including birds) and Ornithischia (Triceratops, hadrosaurs, ankylosaurs). Birds are surviving theropods.",
        tags: ["dinosaur", "saurischia", "ornithischia"],
      },
      {
        name: "K-Pg mass extinction",
        description: "End-Cretaceous extinction, 66 Ma — non-avian dinosaurs eliminated.",
        keyFact: "Triggered by Chicxulub impact (Mexico, ~150 km crater), evidenced by global iridium anomaly (Alvarez et al. 1980), shocked quartz, microspherules, K-Pg boundary clay. Deccan Traps volcanism (India) contributed. ~76% of species lost.",
        status: "landmark",
        tags: ["k-pg", "chicxulub", "alvarez"],
      },
      {
        name: "End-Permian (P-Tr) mass extinction",
        description: "Worst extinction in Earth history, ~252 Ma — ~96% of marine species.",
        keyFact: "Driven by Siberian Traps flood basalts (~$10^6$ km³): $\\mathrm{CO_2}$ + $\\mathrm{SO_2}$ + Hg release, ocean anoxia, acidification, warming. 'Great Dying'; recovery took 5–10 Myr. End of Paleozoic biota.",
        tags: ["p-tr", "siberian-traps", "great-dying"],
      },
      {
        name: "Mammal radiation",
        description: "Adaptive radiation of mammals after K-Pg extinction.",
        keyFact: "Diversification began within ~200 kyr of K-Pg. Eocene PETM (~56 Ma) saw rise of modern mammalian orders (artiodactyls, perissodactyls, primates). Cetacean evolution from terrestrial Mesonychids/Indohyus through Pakicetus (~50 Ma) is well documented.",
        tags: ["mammal", "petm", "radiation"],
      },
      {
        name: "Hominin evolution",
        description: "Divergence of human lineage from other apes ~7 Ma.",
        keyFact: "Sahelanthropus (~7 Ma), Australopithecus (~4 Ma, Lucy), Homo erectus (~2 Ma, out of Africa), Neanderthals + Denisovans + Homo sapiens (~300 ka). Modern humans dispersed from Africa ~70–60 ka; admixed with Neanderthals/Denisovans.",
        tags: ["hominin", "lucy", "homo-sapiens"],
      },
      {
        name: "Sixth mass extinction (current)",
        description: "Anthropogenic biodiversity loss potentially comparable to past Big Five.",
        keyFact: "Background extinction rate: ~0.1–1 per million species-years. Current rate: ~100–1000× background (IPBES 2019). Habitat loss, climate change, invasive species, overharvest as drivers. Whether it qualifies as a mass extinction on geologic time depends on continuation.",
        status: "open",
        xref: ["statistics"],
        tags: ["sixth-extinction", "biodiversity"],
      },
    ],
  },

  // ── Family 21 ─────────────────────────────────────────────────────────────
  {
    slug: "economic-geology",
    number: 21,
    name: "Economic Geology & Mineral Resources",
    blurb: "Where ore deposits form and how we find them.",
    section: "E",
    color: "amber",
    entries: [
      {
        name: "Ore deposit — definition",
        description: "A natural concentration of a useful element above its crustal abundance to economic levels.",
        keyFact: "Concentration factor required: Al (~3), Fe (~6), Cu (~80), Au (~2,000), Pt (~2,000). Economic cutoff depends on commodity price, deposit size, depth, metallurgy. Reserves vs resources distinction is standardized (CRIRSCO).",
        tags: ["ore-deposit", "concentration-factor"],
      },
      {
        name: "Magmatic sulfide deposits",
        description: "Ni, Cu, PGE deposits from immiscible sulfide melt segregating from mafic-ultramafic magma.",
        keyFact: "Type localities: Sudbury (Ontario, also impact-generated), Norilsk-Talnakh (Russia, world's largest Ni-Cu-Pd source), Bushveld Complex (S. Africa, Pt). Sulfur saturation triggers sulfide droplet exsolution; chalcophile elements partition strongly.",
        tags: ["magmatic-sulfide", "norilsk", "ni-cu-pge"],
      },
      {
        name: "Porphyry copper deposits",
        description: "Large low-grade Cu (Mo, Au) deposits associated with felsic-intermediate intrusions in arc settings.",
        keyFact: "Type locality: Bingham Canyon (Utah). Source of ~75% of world Cu. Hydrothermal fluid exsolution from late-stage I-type magmas; characteristic alteration zones (potassic, phyllic, argillic, propylitic) outward from the stock.",
        status: "landmark",
        tags: ["porphyry", "bingham", "cu-mo"],
      },
      {
        name: "Volcanogenic massive sulfide (VMS) deposits",
        description: "Sea-floor sulfide deposits formed at submarine hydrothermal vents.",
        keyFact: "Modern analog: black smokers. Ancient VMS examples: Kidd Creek (Ontario, 2.7 Ga), Rio Tinto (Spain, IPB). Cu-Zn-Pb-Au-Ag in submarine volcanic settings — Kuroko (Japan), Cyprus, Besshi types.",
        tags: ["vms", "kuroko", "black-smoker"],
      },
      {
        name: "Sedimentary exhalative (SEDEX) deposits",
        description: "Stratiform Pb-Zn-Ag deposits from brines vented into anoxic basins.",
        keyFact: "Type localities: Red Dog (Alaska, world's largest Zn mine), Mount Isa (Australia), Sullivan (Canada). Brines exhale onto sediment-starved basin floor; pyrite, sphalerite, galena interlaminated with shale.",
        tags: ["sedex", "red-dog", "pb-zn"],
      },
      {
        name: "Mississippi Valley-type (MVT) deposits",
        description: "Carbonate-hosted Pb-Zn deposits formed by warm basin brines.",
        keyFact: "Form by basin-derived brines migrating to platform carbonates. Examples: Mississippi Valley, Pine Point (Canada), Lennard Shelf (Australia), Tri-State (US). Brine temperatures ~75–200 °C; epigenetic with respect to host.",
        tags: ["mvt", "carbonate-hosted", "pb-zn"],
      },
      {
        name: "Orogenic gold deposits",
        description: "Gold deposits in metamorphic terranes from devolatilization fluids.",
        keyFact: "Mother Lode (California), Bendigo (Australia), Witwatersrand (S. Africa — paleoplacer + modified). Quartz-vein hosted, with sulfides and Au. ~$10^{14}$ g Au extracted total from Witwatersrand alone — the largest gold concentration on Earth.",
        tags: ["orogenic-gold", "witwatersrand"],
      },
      {
        name: "Placer deposits",
        description: "Mechanical concentration of dense minerals in stream or beach sediment.",
        keyFact: "Gold, platinum, tin (cassiterite), titanium (rutile, ilmenite), zircon, diamonds, monazite. Modern placer mining (California 1849, Klondike, Witwatersrand paleoplacer). Beach placers source most heavy-mineral sand mining.",
        tags: ["placer", "gold-rush", "cassiterite"],
      },
      {
        name: "Banded iron formations as iron ores",
        description: "Precambrian BIFs are the source of >90% of mineable iron.",
        keyFact: "Hamersley Basin (Western Australia, ~2.5 Ga), Carajás (Brazil), Krivoy Rog (Ukraine), Mesabi Range (Minnesota). High-grade hematite ore from supergene enrichment of magnetite-rich BIF protolith.",
        tags: ["bif", "iron-ore", "hamersley"],
      },
      {
        name: "Critical and rare-earth element deposits",
        description: "Sources of elements essential for batteries, magnets, and high-tech industries.",
        keyFact: "Bayan Obo (China, REE), Mountain Pass (California, REE), Greenland (Kvanefjeld, REE-U), Mt Weld (Australia, REE), DRC cobalt copper belt, Chilean lithium brines, Australian hard-rock lithium (Pilbara). Geopolitically concentrated.",
        tags: ["ree", "lithium", "cobalt", "critical-mineral"],
      },
      {
        name: "Diamond geology",
        description: "Diamonds form in cratonic upper mantle and are transported by kimberlite or lamproite eruptions.",
        keyFact: "Formed at >150 km depth and >$10^9$ Pa, mostly 1–3 Ga old. Hosted in kimberlites that erupt explosively. Major sources: Russia (Yakutia), Botswana (Orapa, Jwaneng), Canada (Diavik, Ekati), Australia (Argyle, closed 2020).",
        tags: ["diamond", "kimberlite", "craton"],
      },
      {
        name: "Mineral exploration techniques",
        description: "Methods for finding new ore deposits.",
        keyFact: "Geological mapping, geochemical surveys (soil, stream sediment, biogeochemistry), geophysical surveys (gravity, magnetic, EM, IP), drilling. Increasing role of remote sensing (ASTER, Sentinel-2 for alteration mineralogy) and machine learning.",
        xref: ["statistics"],
        tags: ["exploration", "geochemical-survey", "geophysical"],
      },
    ],
  },

  // ── Family 22 ─────────────────────────────────────────────────────────────
  {
    slug: "petroleum-geology",
    number: 22,
    name: "Petroleum & Energy Geology",
    blurb: "Hydrocarbons — generation, migration, trapping, and unconventional resources.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Petroleum system",
        description: "Source, reservoir, seal, trap, migration pathway, and timing.",
        keyFact: "All six elements must coincide in space and time for a commercial accumulation. Magoon & Dow (1994) formalized the framework now used by every exploration company.",
        tags: ["petroleum-system"],
      },
      {
        name: "Source rocks and kerogen types",
        description: "Organic-rich (>1% TOC) shales that generate hydrocarbons on heating.",
        keyFact: "Type I: lacustrine algal — oil-prone. Type II: marine — oil and gas. Type III: terrestrial woody — gas. Type IV: oxidized — inert. Bakken, Marcellus, Eagle Ford, Vaca Muerta are world-class shales.",
        xref: ["chemistry"],
        tags: ["source-rock", "kerogen", "toc"],
      },
      {
        name: "Oil and gas windows",
        description: "Temperature-controlled hydrocarbon generation zones.",
        keyFact: "Oil window ~60–150 °C; gas window ~150–230 °C; overmature ~>230 °C. Vitrinite reflectance ($R_o$) maps maturity: 0.6–1.3 % $R_o$ = oil; 1.3–2.0 = wet gas; >2.0 = dry gas.",
        tags: ["oil-window", "vitrinite-reflectance"],
      },
      {
        name: "Migration",
        description: "Movement of hydrocarbons from source to reservoir.",
        keyFact: "Primary migration: expulsion from source by overpressure and microfracturing. Secondary migration: buoyancy-driven movement through carrier beds and faults. Tertiary: redistribution after entrapment. Total distances 10s–1000s of km.",
        tags: ["migration", "primary", "secondary"],
      },
      {
        name: "Reservoir rocks",
        description: "Porous, permeable rocks holding hydrocarbons.",
        keyFact: "Sandstones (clastic) and carbonates (reefs, grainstones) are dominant; fractured basement and shale (unconventional). Porosity typically 5–35%; permeability 0.1–1000+ mD. Diagenetic alteration of these reservoirs (cementation, dissolution) is a major control.",
        tags: ["reservoir", "porosity", "permeability"],
      },
      {
        name: "Trap types",
        description: "Geometries that capture and retain hydrocarbons.",
        keyFact: "Structural: anticlines, fault-bounded, salt domes (Gulf Coast). Stratigraphic: pinchouts, unconformity traps, reef buildups, deltaic sand bodies. Combination traps common. Hydrocarbon column depends on seal capillary entry pressure.",
        tags: ["trap", "anticline", "salt-dome"],
      },
      {
        name: "Unconventional resources — shale, tight oil/gas, coal-bed methane, oil sands",
        description: "Resources not produced through conventional trap-and-reservoir geology.",
        keyFact: "Shale gas/oil produced via horizontal drilling + hydraulic fracturing — revolutionized US production after ~2008. Athabasca oil sands (Alberta) host ~1.7 trillion bbl bitumen. Coal-bed methane (CBM) and gas hydrates round out the unconventional spectrum.",
        tags: ["unconventional", "shale", "oil-sands"],
      },
      {
        name: "Methane hydrates (clathrates)",
        description: "Ice-like crystalline compound of methane trapped in water structure.",
        keyFact: "Stable at high P and low T in marine sediments and permafrost. Estimated $10^{15}$–$10^{16}$ m³ of methane stored globally — likely larger than all conventional gas reserves. Both a potential resource and a climate hazard.",
        tags: ["hydrate", "clathrate", "methane"],
      },
      {
        name: "Coal as energy resource",
        description: "Anthracite, bituminous, lignite — formed in Carboniferous and Permian peat swamps.",
        keyFact: "Major basins: Appalachian, Illinois, Powder River, Bowen-Sydney, Donbas, Ruhr, Karaganda. Coal use peaked in 2014–2024 range globally; declining share of electricity mix. Stranded-asset risk as climate policy tightens.",
        tags: ["coal", "anthracite", "appalachian"],
      },
      {
        name: "Geothermal energy",
        description: "Heat from Earth's interior tapped for electricity and direct use.",
        keyFact: "Conventional: hot-water reservoirs (Iceland, Geysers California, Larderello Italy, Wairakei NZ). Enhanced Geothermal Systems (EGS) attempt to engineer reservoirs in dry hot rock — Cooper Basin (Australia), Soultz (France), Utah FORGE.",
        xref: ["physics"],
        tags: ["geothermal", "egs"],
      },
      {
        name: "Carbon capture and storage (CCS)",
        description: "Capturing $\\mathrm{CO_2}$ and injecting into geologic reservoirs for long-term storage.",
        keyFact: "Sleipner (North Sea, since 1996) and Quest (Alberta) demonstrate decade-scale safe storage. Mineralization in basalt (CarbFix, Iceland) traps $\\mathrm{CO_2}$ as carbonate within years. Required to meet 1.5 °C and 2 °C targets in essentially every IPCC scenario.",
        tags: ["ccs", "sleipner", "carbfix"],
      },
      {
        name: "Uranium ore deposits",
        description: "Sandstone-hosted roll-front, unconformity-related, and IOCG U deposits.",
        keyFact: "Major types: unconformity-related (Athabasca, Saskatchewan — highest grades globally, 20%+ U); sandstone (Wyoming Powder River, Niger, Kazakhstan); IOCG (Olympic Dam, Australia). Kazakhstan accounts for ~40% of world primary production.",
        tags: ["uranium", "athabasca", "olympic-dam"],
      },
    ],
  },

  // ── Family 23 ─────────────────────────────────────────────────────────────
  {
    slug: "planetary-geology",
    number: 23,
    name: "Planetary & Astrobiology Geology",
    blurb: "The geology of other worlds — Moon, Mars, Venus, icy moons.",
    section: "E",
    color: "indigo",
    entries: [
      {
        name: "Solar system formation",
        description: "Collapse of a molecular cloud ~4.567 Ga produced Sun + protoplanetary disk + planets.",
        keyFact: "Refractory CAIs (~4.567 Ga) date disk-condensation start. Inner-rocky / outer-gas dichotomy reflects snow-line condensation. Nice/Grand Tack models address giant-planet migration and inner-solar-system bombardment.",
        status: "landmark",
        xref: ["physics"],
        tags: ["solar-system", "cai", "nebula"],
      },
      {
        name: "Moon — origin and geology",
        description: "Formed by giant impact of Mars-sized Theia with proto-Earth ~4.51 Ga.",
        keyFact: "Apollo samples + lunar meteorites established maria (basaltic plains) vs highlands (anorthositic crust). KREEP signature confirms magma ocean differentiation. Late Heavy Bombardment (~3.9 Ga) carved most large basins.",
        status: "landmark",
        tags: ["moon", "theia", "maria", "kreep"],
      },
      {
        name: "Mars — geology",
        description: "Cold, dry, volcanically dead today, but active aqueous past.",
        keyFact: "Three eras: Noachian (4.1–3.7 Ga, wet, basin-forming), Hesperian (3.7–3.0 Ga, volcanic, transitional), Amazonian (3.0 Ga–present, cold/dry). Olympus Mons (22 km), Valles Marineris (4000 km long, 7 km deep), polar ice caps, ancient deltas and lake beds.",
        tags: ["mars", "olympus-mons", "valles-marineris"],
      },
      {
        name: "Venus — geology",
        description: "Earth-like size and composition, but resurfaced ~500–700 Ma; lethal greenhouse atmosphere.",
        keyFact: "Surface ~462 °C, ~92 bar $\\mathrm{CO_2}$ atmosphere. Dominated by volcanic plains, coronae (mantle plumes), tesserae (deformed terranes). Mostly ~500 Ma global resurfacing — no plate tectonics. Recent DAVINCI/VERITAS and EnVision missions will revisit.",
        tags: ["venus", "coronae", "tesserae"],
      },
      {
        name: "Mercury — geology",
        description: "Heavily cratered, geologically old, lobate scarps record planetary contraction.",
        keyFact: "Highest density of any planet (~5.4 g/cm³) — disproportionately large iron core. Caloris Basin (~1,550 km) is one of largest impact features in solar system. Lobate scarps indicate planetary radius shrank ~7 km over Mercury's history.",
        tags: ["mercury", "caloris", "lobate-scarp"],
      },
      {
        name: "Icy moons — Europa, Enceladus, Titan",
        description: "Outer-planet moons with subsurface oceans (Europa, Enceladus) or thick organic atmospheres (Titan).",
        keyFact: "Europa (Jupiter): ~100 km deep liquid water ocean under ice shell. Enceladus (Saturn): plumes from south-polar fractures, salty ocean. Titan: thick $\\mathrm{N_2}$ atmosphere, methane rivers and seas. Prime astrobiology targets.",
        tags: ["icy-moon", "europa", "enceladus", "titan"],
      },
      {
        name: "Asteroids and meteorites",
        description: "Building blocks left over from solar system formation.",
        keyFact: "Classes: chondrites (primitive — CI, CM, CV, ordinary), achondrites (differentiated parent body), irons (cores). CI chondrites match solar photosphere composition for non-volatile elements. Provide ages, parent-body history, isotopic anomalies.",
        tags: ["meteorite", "chondrite", "achondrite"],
      },
      {
        name: "Impact cratering",
        description: "Universal geologic process; scaled by gravity and projectile energy.",
        keyFact: "Crater forms in three stages: contact-compression, excavation, modification. Final/transient diameter ratio increases for complex craters (>~3 km on Earth). Simple-to-complex transition depends on gravity (Earth ~3 km, Moon ~15 km).",
        xref: ["physics"],
        tags: ["impact", "crater", "complex-crater"],
      },
      {
        name: "Chicxulub impact",
        description: "~150 km crater in Yucatán, ~66 Ma — K-Pg mass extinction trigger.",
        keyFact: "Discovered as gravity-magnetic anomaly (Hildebrand et al. 1991). Iridium anomaly (Alvarez et al. 1980), shocked quartz, microspherules globally. Earth's only confirmed extinction-scale impact in the Phanerozoic.",
        status: "landmark",
        tags: ["chicxulub", "alvarez", "k-pg"],
      },
      {
        name: "Habitable zone and biosignatures",
        description: "Range of orbital distances where surface liquid water is possible.",
        keyFact: "Solar HZ ~0.95–1.67 AU under Sun's current luminosity. Beyond surface life: subsurface oceans on icy moons broaden 'habitable' criteria. Biosignatures: $\\mathrm{O_2}$+$\\mathrm{CH_4}$ disequilibrium, isotope fractionation, morphological microfossils.",
        xref: ["chemistry"],
        tags: ["habitable-zone", "biosignature"],
      },
      {
        name: "Life on Mars",
        description: "Did Mars ever harbor life?",
        keyFact: "Persistent ALH84001 meteorite (1996) carbonate-globule claims of nanobacteria remain unverified. Curiosity (Gale Crater) and Perseverance (Jezero) detect organics, fluvio-lacustrine deposits, biosignature targets. Mars sample-return is the path to resolution.",
        status: "open",
        tags: ["mars-life", "alh84001", "perseverance"],
      },
      {
        name: "Lunar resources and ISRU",
        description: "Water ice at lunar poles enables in-situ resource utilization.",
        keyFact: "Permanently shadowed crater interiors at poles host water ice (LCROSS 2009, Chandrayaan-3 2023). Helium-3 in regolith proposed as fusion fuel. Plans for resource utilization underpin Artemis-era return to the Moon.",
        tags: ["isru", "lunar-ice", "helium-3"],
      },
    ],
  },

  // ── Family 24 ─────────────────────────────────────────────────────────────
  {
    slug: "environmental-frontier",
    number: 24,
    name: "Environmental Geology & Open Questions",
    blurb: "Geology in human use — hazards, resources, contamination — and unsolved questions.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Natural hazards",
        description: "Earthquakes, volcanoes, tsunamis, landslides, floods, sinkholes, subsidence.",
        keyFact: "Earthquake hazard mapped via probabilistic seismic hazard analysis (PSHA). 2004 Sumatra tsunami: ~230,000 deaths; 2010 Haiti quake: ~150,000; 2011 Tōhoku: ~18,000 + Fukushima. Mortality concentrated in low-income coastal megacities.",
        xref: ["statistics"],
        tags: ["hazard", "psha", "tsunami"],
      },
      {
        name: "Land subsidence",
        description: "Ground sinking from natural compaction or anthropogenic causes.",
        keyFact: "Groundwater withdrawal: Mexico City (~5 cm/yr), Jakarta (~25 cm/yr at maximum), Central Valley California (~25 cm in 2014–2016 drought). Oil & gas extraction; mine subsidence; oxidation of peat; permafrost thaw. InSAR is workhorse monitoring tool.",
        tags: ["subsidence", "jakarta", "mexico-city"],
      },
      {
        name: "Acid mine drainage",
        description: "$\\mathrm{H_2SO_4}$-rich runoff from sulfide-mineral oxidation in mine waste.",
        keyFact: "$\\mathrm{FeS_2} + \\mathrm{O_2}$ + bacteria → $\\mathrm{SO_4^{2-}}$ + $\\mathrm{Fe^{3+}}$ + $\\mathrm{H^+}$. Iron Mountain (California), Rio Tinto (Spain), Berkeley Pit (Montana). Acidophile bacteria (Acidithiobacillus) drive the reaction. Treatment via lime neutralization, constructed wetlands.",
        xref: ["chemistry"],
        tags: ["amd", "pyrite-oxidation"],
      },
      {
        name: "Soil and groundwater contamination",
        description: "Industrial, agricultural, and urban pollutants reaching the subsurface.",
        keyFact: "Major plumes: BTEX (gasoline), TCE/PCE (industrial solvents), PFAS (fluorinated chemicals, 'forever chemicals'), nitrate (agriculture), arsenic (natural + irrigation, Bangladesh crisis), lead (Pb-paint, plumbing — Flint).",
        tags: ["contamination", "pfas", "tce"],
      },
      {
        name: "Geologic carbon storage",
        description: "Long-term sequestration of $\\mathrm{CO_2}$ in geologic reservoirs.",
        keyFact: "Saline aquifers (Sleipner, Snøhvit), depleted oil/gas fields, basalts (CarbFix). Trapping mechanisms: structural, residual, dissolution, mineral (basalt → carbonate within years vs Myr). Likely required at gigaton-per-year scale to meet climate targets.",
        tags: ["ccs", "sequestration"],
      },
      {
        name: "Nuclear waste storage",
        description: "Disposal of spent nuclear fuel and high-level waste in deep geologic repositories.",
        keyFact: "Onkalo (Finland) is the world's first operating deep geologic repository, opening 2024–2025 for licensing. Yucca Mountain (Nevada) defunded politically. Key criteria: low groundwater flow, stable host rock, $10^5$-yr isolation timescale.",
        tags: ["nuclear-waste", "onkalo", "yucca"],
      },
      {
        name: "What drives core convection — and how stable is the geodynamo?",
        description: "Outer-core flow generates Earth's magnetic field; rates and inner-core dynamics are debated.",
        keyFact: "Inner-core nucleation age (0.5–1.5 Ga vs older) constrains energy budget. Excursions and reversal frequency variable. Current secular weakening of the dipole field and South Atlantic Anomaly raise (unfounded) reversal-soon claims.",
        status: "open",
        xref: ["physics"],
        tags: ["geodynamo", "inner-core", "reversal"],
      },
      {
        name: "Origin of life",
        description: "How did chemistry become biology on early Earth?",
        keyFact: "Hydrothermal vent (Lost City — alkaline serpentinite), surface hot-spring (Damer & Deamer), RNA world (Joyce, Gilbert) hypotheses still competing. Last Universal Common Ancestor lived ~3.5–4.0 Ga. No fossil record below ~3.5 Ga.",
        status: "open",
        xref: ["chemistry"],
        tags: ["origin-of-life", "luca", "rna-world"],
      },
      {
        name: "Was there life on early Mars?",
        description: "Evidence for fluvio-lacustrine environments ~4–3.7 Ga; whether life arose remains unknown.",
        keyFact: "Curiosity and Perseverance rovers have found organics, redox gradients, lake-bed mudstones, deltas. Mars Sample Return (NASA-ESA) plans to return cores from Jezero Crater for laboratory study by ~2033 (timeline contested).",
        status: "open",
        tags: ["mars-life", "perseverance"],
      },
      {
        name: "Slow earthquakes and tremor",
        description: "Plate boundary slip at sub-seismic rates discovered in 2000s.",
        keyFact: "Episodic tremor and slip (ETS) at Cascadia, Nankai, Mexico. Slow-slip events release as much moment as $M$7 earthquakes over weeks. Mechanism (fluid pressure cycling? frictional heterogeneity?) and significance for triggering megathrust ruptures remain open.",
        status: "open",
        tags: ["slow-slip", "ets", "cascadia"],
      },
      {
        name: "Atlantic Meridional Overturning Circulation (AMOC) tipping",
        description: "Could the deep-ocean conveyor collapse this century?",
        keyFact: "Paleoclimate analogs (Younger Dryas, Heinrich events) record past abrupt AMOC weakening. CMIP6 models show 20–30% weakening by 2100 under high emissions; tipping risk debated. Direct observations (RAPID array, OSNAP) cover ~20 yr.",
        status: "open",
        xref: ["statistics"],
        tags: ["amoc", "tipping-point"],
      },
      {
        name: "Are humans an Anthropocene-defining stratigraphic signal?",
        description: "The Anthropocene Working Group proposed formal designation; ICS subcommission declined in 2024.",
        keyFact: "Markers proposed: 1952 plutonium fallout, microplastics, anthropogenic carbon isotope shift, novel mineral species, species translocations. Disagreement: 'is the signal large and global enough to define a chronostratigraphic unit?'",
        status: "open",
        tags: ["anthropocene", "stratigraphy"],
      },
    ],
  },
];
