import type { Family } from "./types";

export const FAMILIES_9_16: Family[] = [
  // ── Family 9 ──────────────────────────────────────────────────────────────
  {
    slug: "volcanology",
    number: 9,
    name: "Volcanology",
    blurb: "Volcanic eruptions, products, edifices, and hazards.",
    section: "B",
    color: "rose",
    entries: [
      {
        name: "Magma viscosity and silica content",
        description: "Silica polymerization sets eruptive style.",
        keyFact: "Basaltic magma (~50% $\\mathrm{SiO_2}$, $10^2$ Pa·s): fluid, effusive — Hawaii. Andesitic (~60%, $10^5$ Pa·s): explosive. Rhyolitic (~75%, $10^8$ Pa·s): viscous, very explosive. Viscosity controls volatile release: it's about gas escape, not gas volume.",
        xref: ["physics"],
        tags: ["viscosity", "silica", "rheology"],
      },
      {
        name: "Shield volcanoes",
        description: "Broad, gently sloping edifices built by basaltic flows.",
        keyFact: "Mauna Loa is the largest active volcano on Earth (~74,000 km³). Effusive, low-explosivity eruptions; threat is lava-flow inundation, not pyroclastic destruction. Olympus Mons on Mars is a shield volcano 22 km tall.",
        tags: ["shield", "basalt", "mauna-loa"],
      },
      {
        name: "Stratovolcanoes (composite volcanoes)",
        description: "Steep-sided cones built by alternating lava and pyroclastic layers.",
        keyFact: "Andesite-dacite composition; explosive. Iconic examples: Fuji, Vesuvius, St. Helens, Pinatubo, Mayon. Vesuvius destroyed Pompeii in 79 CE; Mount St. Helens lost 400 m of summit on May 18, 1980.",
        tags: ["stratovolcano", "andesite", "arc"],
      },
      {
        name: "Calderas and supervolcanoes",
        description: "Collapse depressions formed when a magma chamber empties catastrophically.",
        keyFact: "Yellowstone, Long Valley, Toba (74 ka, possibly bottlenecked human population), Taupo, Aira (Sakurajima). Volcanic Explosivity Index (VEI) 8 — supervolcano eruptions eject ≥1,000 km³ of tephra; last was Taupo's Oruanui (~25.4 ka).",
        tags: ["caldera", "supervolcano", "vei"],
      },
      {
        name: "Volcanic Explosivity Index (VEI)",
        description: "Logarithmic 0–8 scale for eruption size based on ejecta volume.",
        keyFact: "Each step ≈ 10× more tephra. VEI 5: Vesuvius 79, Mt. St. Helens 1980. VEI 6: Krakatau 1883, Pinatubo 1991. VEI 7: Tambora 1815 (Year Without a Summer). VEI 8: Toba 74 ka, Yellowstone Lava Creek 0.63 Ma.",
        tags: ["vei", "explosivity"],
      },
      {
        name: "Pyroclastic flow",
        description: "Fast-moving ground-hugging cloud of hot ash, gas, and rock.",
        keyFact: "Temperatures 300–800 °C; speeds 50–700 km/h. Cannot be outrun. Pyroclastic surges destroyed Pompeii, St. Pierre (Martinique 1902, ~28,000 killed), and Plymouth (Montserrat 1997). Most lethal volcanic phenomenon.",
        tags: ["pyroclastic-flow", "nuee-ardente"],
      },
      {
        name: "Lahar",
        description: "Volcanic mudflow — water-saturated debris flow from a volcanic source.",
        keyFact: "Triggered by eruption-melted snow/ice, breached crater lakes, or heavy rain on fresh tephra. Nevado del Ruiz lahar killed ~25,000 in Armero, Colombia (1985). Set in concrete-like rock when emplaced.",
        tags: ["lahar", "debris-flow", "nevado-del-ruiz"],
      },
      {
        name: "Hawaiian, Strombolian, Vulcanian, Plinian styles",
        description: "Eruption-style classification by intensity and ejecta type.",
        keyFact: "Hawaiian (lava fountains, fluid basalt), Strombolian (mild explosions, scoria), Vulcanian (short violent blasts, blocky tephra), Plinian (sustained towering eruption column, Vesuvius 79), Ultra-Plinian (Krakatau).",
        tags: ["eruption-style", "plinian"],
      },
      {
        name: "Volcanic gases",
        description: "$\\mathrm{H_2O}$, $\\mathrm{CO_2}$, $\\mathrm{SO_2}$, $\\mathrm{H_2S}$, HCl, HF released during eruptions.",
        keyFact: "Water dominant by mole fraction (~60–90%); $\\mathrm{CO_2}$ next. Mass-balance for atmospheric chemistry over geologic time. $\\mathrm{SO_2}$ aerosols cool climate transiently (Pinatubo 1991: ~0.5 °C global cooling for 2 years).",
        xref: ["chemistry"],
        tags: ["volcanic-gas", "so2", "climate"],
      },
      {
        name: "Volcano monitoring",
        description: "Detecting unrest via seismicity, ground deformation, and gas flux.",
        keyFact: "Multi-instrument suite: seismometers (long-period and tornillo events), GPS/InSAR (cm-scale inflation), tiltmeters, $\\mathrm{SO_2}$ remote sensing (UV camera, DOAS), thermal cameras, infrasound. Pinatubo 1991 evacuation saved ~5,000–20,000 lives.",
        tags: ["monitoring", "insar", "doas"],
      },
      {
        name: "Mid-ocean ridge volcanism",
        description: "Submarine basalt eruptions along the global ridge system.",
        keyFact: "~75% of all magma erupted on Earth comes from mid-ocean ridges, ~3 km³/yr. Pillow lavas, sheeted dikes, and gabbros below form the canonical ophiolite stratigraphy. Black smoker vents (350 °C) host chemosynthetic ecosystems.",
        tags: ["mor", "pillow-lava", "black-smoker"],
      },
      {
        name: "Volcanic hazards and risk",
        description: "Lava, tephra, ash, lahar, gas, tsunami, sector collapse.",
        keyFact: "Sector collapse (St. Helens, Krakatau 535 CE) generates debris avalanche and possibly tsunami. ~800 million people live within 100 km of a Holocene volcano. Ash clouds disable jet engines (Eyjafjallajökull 2010 grounded European air traffic).",
        tags: ["hazard", "risk", "sector-collapse"],
      },
    ],
  },

  // ── Family 10 ─────────────────────────────────────────────────────────────
  {
    slug: "seismology",
    number: 10,
    name: "Seismology",
    blurb: "Earthquake sources, wave propagation, and Earth's interior from seismic data.",
    section: "B",
    color: "amber",
    entries: [
      {
        name: "Earthquake — elastic rebound theory",
        description: "Earthquakes result from sudden release of accumulated elastic strain on a fault.",
        keyFact: "H. F. Reid (1910), after the 1906 San Francisco quake. Rock deforms elastically until stress exceeds frictional strength; slip occurs, releasing energy as seismic waves; the cycle resets. Foundation of modern earthquake physics.",
        status: "landmark",
        tags: ["elastic-rebound", "reid"],
      },
      {
        name: "Hypocenter and epicenter",
        description: "Point of fault rupture initiation (hypo) and its projection on the surface (epi).",
        keyFact: "Located by inverting first-arrival times at ≥4 stations. Hypocenter depth classes: shallow (<70 km), intermediate (70–300 km), deep (300–700 km — mostly subducted slabs along Wadati-Benioff zones).",
        tags: ["hypocenter", "epicenter", "benioff"],
      },
      {
        name: "P-waves (primary)",
        description: "Compressional body waves — fastest seismic wave.",
        keyFact: "Push-pull motion in propagation direction. Travel through solids and liquids. Speed: ~6 km/s in upper crust, ~13.7 km/s at base of mantle. Velocity depends on bulk modulus, shear modulus, density.",
        formula: "v_P = \\sqrt{(K + \\tfrac{4}{3}\\mu)/\\rho}",
        xref: ["physics"],
        tags: ["p-wave", "compressional"],
      },
      {
        name: "S-waves (secondary)",
        description: "Shear body waves — second-arrival, slower than P.",
        keyFact: "Transverse motion perpendicular to propagation. Cannot travel through liquids — S-wave shadow zone (104°–180° from epicenter) was the key evidence for a liquid outer core (Oldham 1906, Lehmann 1936).",
        formula: "v_S = \\sqrt{\\mu/\\rho}",
        xref: ["physics"],
        status: "landmark",
        tags: ["s-wave", "shear", "shadow-zone"],
      },
      {
        name: "Surface waves — Love and Rayleigh",
        description: "Waves trapped at Earth's surface; cause most earthquake damage.",
        keyFact: "Love waves: horizontal shear motion. Rayleigh waves: retrograde elliptical motion (like ocean waves). Slower than body waves (~3.5 km/s) but largest amplitude — dominate seismograms at teleseismic distances.",
        tags: ["love", "rayleigh", "surface-wave"],
      },
      {
        name: "Moment magnitude (Mw)",
        description: "Modern measure of earthquake size based on seismic moment.",
        keyFact: "$M_w = \\tfrac{2}{3}\\log_{10}(M_0) - 6.07$, where $M_0 = \\mu A D$ (shear modulus × fault area × slip). Replaced the saturating Richter $M_L$ scale for $M\\!\\gtrsim\\!7$. Tohoku 2011 was $M_w$ 9.1.",
        formula: "M_w = \\tfrac{2}{3}\\log_{10}(M_0) - 6.07",
        tags: ["moment-magnitude", "mw"],
      },
      {
        name: "Gutenberg-Richter law",
        description: "Frequency-magnitude relation: smaller earthquakes are exponentially more common.",
        keyFact: "$\\log_{10} N = a - bM$, with $b$ typically $\\sim 1$. Implies ~10× more $M$5 than $M$6 earthquakes; ~10⁴ times more $M$3 than $M$7. The b-value can shift before/during volcanic or aftershock sequences.",
        formula: "\\log_{10} N = a - bM",
        xref: ["statistics"],
        status: "landmark",
        tags: ["gutenberg-richter", "b-value"],
      },
      {
        name: "Modified Mercalli intensity",
        description: "Felt-effect scale I–XII; not the same as magnitude.",
        keyFact: "I = unfelt; XII = total destruction. Magnitude is a property of the source; intensity is a property of the location — depends on site amplification, depth, and ground type. 'Did You Feel It?' crowdsourced maps replaced field surveys.",
        tags: ["mercalli", "intensity"],
      },
      {
        name: "PREM (Preliminary Reference Earth Model)",
        description: "Dziewonski & Anderson (1981) — radial seismic velocity profile.",
        keyFact: "Reference 1D velocity/density model. Defines the layers: crust (0–35 km), upper mantle, transition zone (410–660 km discontinuities), lower mantle, D″ layer, liquid outer core, solid inner core. Standard against which lateral heterogeneities are referenced.",
        status: "landmark",
        tags: ["prem", "earth-structure"],
      },
      {
        name: "Mohorovičić discontinuity (Moho)",
        description: "Boundary between crust and mantle, identified by sharp velocity increase.",
        keyFact: "Discovered by Andrija Mohorovičić in 1909 from 1909 Pokupsko quake records. P-wave velocity jumps from ~6 to ~8 km/s. Depth: 5–10 km under oceans, 30–80 km under continents.",
        tags: ["moho", "crust-mantle"],
      },
      {
        name: "Liquid outer core",
        description: "Liquid iron-nickel layer 2890–5150 km depth, source of geodynamo.",
        keyFact: "Inferred from S-wave shadow zone (Oldham 1906) and PKP refraction. Convective flow generates Earth's magnetic field; freezing onto the inner core liberates latent heat and light elements driving compositional convection.",
        xref: ["physics"],
        tags: ["outer-core", "geodynamo"],
      },
      {
        name: "Seismic tomography",
        description: "Imaging 3D velocity structure of Earth's interior from many earthquake arrivals.",
        keyFact: "P- and S-wave tomography reveals subducted slabs sinking to the lower mantle, mantle plumes (Hawaii, Iceland), and LLSVPs (large low-shear-velocity provinces) beneath Africa and the Pacific. The 3D mantle, not the 1D Earth.",
        xref: ["statistics"],
        tags: ["tomography", "llsvp", "imaging"],
      },
    ],
  },

  // ── Family 11 ─────────────────────────────────────────────────────────────
  {
    slug: "geophysics",
    number: 11,
    name: "Geophysics",
    blurb: "Physical methods applied to Earth — gravity, magnetism, heat flow, electromagnetism.",
    section: "B",
    color: "indigo",
    entries: [
      {
        name: "Earth's gravitational field",
        description: "Surface gravity $g$ varies with latitude, elevation, and subsurface density.",
        keyFact: "Normal gravity $\\approx 9.81\\,\\mathrm{m/s^2}$, ~0.5% larger at poles than equator due to rotation + oblateness. Geoid: equipotential surface approximating mean sea level; geoid–ellipsoid separations reach ±100 m globally.",
        formula: "g = GM_\\oplus / r^2",
        xref: ["physics"],
        tags: ["gravity", "geoid"],
      },
      {
        name: "Isostasy",
        description: "Lithosphere floats on asthenosphere; loads adjust by vertical motion.",
        keyFact: "Airy model: thicker crust → deeper root (icebergs in mantle). Pratt model: lateral density variation. Pleistocene glacial unloading drives present-day uplift in Fennoscandia (~10 mm/yr) and Hudson Bay.",
        status: "landmark",
        tags: ["isostasy", "airy", "pratt"],
      },
      {
        name: "Free-air and Bouguer anomalies",
        description: "Gravity anomalies corrected for elevation alone (free-air) or also rock mass (Bouguer).",
        keyFact: "Free-air: $\\Delta g_{FA} = g_{obs} - g_{norm} + 0.3086 h$. Bouguer additionally subtracts $2\\pi G \\rho h \\approx 0.0419 \\rho h$ mGal/m. Negative Bouguer anomalies over mountains confirm low-density crustal roots.",
        formula: "\\Delta g_B = \\Delta g_{FA} - 0.0419\\rho h",
        xref: ["physics"],
        tags: ["gravity-anomaly", "bouguer", "free-air"],
      },
      {
        name: "Geomagnetic field",
        description: "Roughly dipolar field generated by the geodynamo in the liquid outer core.",
        keyFact: "Surface intensity 25–65 μT, declination drifts ~0.2°/yr. Approximated as a tilted dipole 11° off the spin axis. Non-dipole field (~10% intensity) drifts westward at ~0.2°/yr.",
        xref: ["physics"],
        tags: ["geomagnetic", "dipole", "dynamo"],
      },
      {
        name: "Magnetic reversals",
        description: "The dipole field reverses polarity at intervals of $10^4$–$10^7$ yr.",
        keyFact: "Geomagnetic Polarity Time Scale (GPTS) is a global stratigraphic correlation tool. Last reversal: Brunhes-Matuyama (~780 ka). Cretaceous Normal Superchron: ~40 Myr without a reversal.",
        tags: ["reversal", "gpts", "brunhes-matuyama"],
      },
      {
        name: "Heat flow",
        description: "Conductive flux out of Earth's surface, ~47 TW globally.",
        keyFact: "Average continental heat flow ~65 mW/m²; oceanic ~100 mW/m² (younger crust → higher flow). Sources: radiogenic decay of $\\mathrm{U, Th, K}$ (~50%), residual primordial heat (~50%). Drives mantle convection.",
        formula: "q = -k\\, dT/dz",
        xref: ["physics"],
        tags: ["heat-flow", "geotherm"],
      },
      {
        name: "Geothermal gradient",
        description: "Rate of temperature increase with depth.",
        keyFact: "Continental average ~25 °C/km. Hotter (50+ °C/km) in active rifts, lower (~10 °C/km) under stable cratons. Sets the depth to oil/gas window (~60–150 °C), gas-condensate window, and brittle-ductile transition.",
        tags: ["geothermal-gradient", "thermal"],
      },
      {
        name: "Electrical resistivity surveying",
        description: "Subsurface imaging from injected DC currents and measured potentials.",
        keyFact: "Schlumberger, Wenner, and dipole-dipole arrays map resistivity vs depth. Used in groundwater exploration (saline vs fresh aquifers contrast strongly) and ore-body delineation.",
        xref: ["physics"],
        tags: ["resistivity", "geoelectric"],
      },
      {
        name: "Magnetotellurics (MT)",
        description: "Imaging deep electrical resistivity from natural EM-field variations.",
        keyFact: "Uses Earth-ionosphere AC current at $10^{-4}$–$10^4$ Hz. Penetrates to upper mantle depths. Detects partial melt, hydration, and slab fluids; standard tool in geothermal and continental-scale lithospheric studies.",
        xref: ["physics"],
        tags: ["mt", "magnetotellurics"],
      },
      {
        name: "Seismic reflection profiling",
        description: "Imaging subsurface layering from reflected seismic waves.",
        keyFact: "Workhorse of petroleum exploration. Active source (vibroseis on land, airgun at sea); arrays of geophones/hydrophones record reflections. 3D and 4D (time-lapse) seismic image reservoirs to <10 m vertical resolution.",
        tags: ["reflection-seismic", "exploration"],
      },
      {
        name: "InSAR (interferometric synthetic aperture radar)",
        description: "Satellite radar interferometry detects mm-scale ground deformation.",
        keyFact: "Sentinel-1, ALOS-2, NISAR-class missions. Resolves volcanic inflation, earthquake co- and post-seismic motion, subsidence from groundwater withdrawal, glacier flow. Revolutionized natural-hazard monitoring.",
        tags: ["insar", "sentinel-1", "deformation"],
      },
      {
        name: "GPS/GNSS geodesy",
        description: "Continuous global positioning networks measuring plate motion and deformation.",
        keyFact: "Plate Boundary Observatory (US), GEONET (Japan), EUREF, and others provide mm-level horizontal precision. Detects interseismic strain accumulation, slow-slip events, and post-glacial rebound directly.",
        tags: ["gps", "gnss", "geodesy"],
      },
    ],
  },

  // ── Family 12 ─────────────────────────────────────────────────────────────
  {
    slug: "geomorphology",
    number: 12,
    name: "Geomorphology",
    blurb: "The form of the land surface and the processes that sculpt it.",
    section: "C",
    color: "green",
    entries: [
      {
        name: "Davis cycle of erosion",
        description: "William Morris Davis (1899): landscapes evolve through youth → maturity → old age.",
        keyFact: "Now mostly historical, replaced by quantitative process geomorphology. Influential in articulating that landscape evolves over geologic time but criticized for assuming long tectonic quiescence.",
        tags: ["davis", "cycle"],
      },
      {
        name: "Drainage basins and stream networks",
        description: "Catchments funneling water to a single outlet.",
        keyFact: "Horton's laws relate stream order, number, and length geometrically. Hack's law: $L \\sim A^{0.6}$. Drainage divides shift over time, capturing or yielding tributaries (Pliny's stream capture, river piracy).",
        formula: "L \\sim A^{0.6}",
        tags: ["drainage", "horton", "hack"],
      },
      {
        name: "Fluvial geomorphology",
        description: "River channels, floodplains, and sediment transport.",
        keyFact: "Channel patterns: straight, meandering, braided (high bedload, variable discharge), anastomosing. Bankfull discharge (~1.5 yr recurrence) is the dominant geomorphic event. Meanders migrate by cutbank erosion and point-bar deposition.",
        tags: ["fluvial", "meander", "braided"],
      },
      {
        name: "Glacial landforms",
        description: "Erosional and depositional features from continental and alpine glaciers.",
        keyFact: "Erosional: U-shaped valleys, cirques, arêtes, horns, fjords, roche moutonnée, striations. Depositional: moraines (terminal, lateral, medial, ground), drumlins, eskers, kames, kettles, outwash plains. Sets large fractions of mid-latitude landscapes.",
        tags: ["glacial", "moraine", "u-shaped-valley"],
      },
      {
        name: "Karst topography",
        description: "Landscape formed by dissolution of carbonate (or evaporite) bedrock.",
        keyFact: "Sinkholes (dolines), caves, disappearing streams, polje, towers (Guilin), springs. Slovenian Karst is the type locality. Threatens infrastructure with collapse; hosts major aquifers.",
        tags: ["karst", "sinkhole", "dissolution"],
      },
      {
        name: "Aeolian (desert) landforms",
        description: "Wind-shaped deposits and erosional features.",
        keyFact: "Dune types by wind regime: barchan (unimodal), transverse, longitudinal/seif (bimodal), star (multidirectional), parabolic (vegetated). Loess: airborne silt deposits from glacial-margin outwash (Chinese Loess Plateau).",
        tags: ["aeolian", "dune", "loess"],
      },
      {
        name: "Coastal geomorphology",
        description: "Shorelines shaped by waves, tides, currents, and sediment supply.",
        keyFact: "Erosional: cliffs, wave-cut platforms, sea stacks, arches. Depositional: beaches, spits, tombolos, bay barriers, barrier islands. Longshore drift sets sediment budgets; sea-level rise is the dominant present-day perturbation.",
        tags: ["coastal", "beach", "longshore"],
      },
      {
        name: "Hillslope processes",
        description: "Soil creep, landslides, debris flows, rockfall.",
        keyFact: "Diffusion-like soil creep ($\\partial z/\\partial t = K \\nabla^2 z$); episodic mass wasting at angles of repose; debris flows behave as non-Newtonian fluids. Slope failure modeled by infinite-slope or Bishop's method using Mohr-Coulomb.",
        xref: ["physics"],
        tags: ["hillslope", "landslide", "creep"],
      },
      {
        name: "Periglacial landforms",
        description: "Features of cold non-glacial environments with permafrost.",
        keyFact: "Patterned ground (stone circles, polygons), pingos, palsas, rock glaciers, solifluction lobes, thermokarst. Active layer freeze-thaw cycle ~1 m thick over permafrost. Vulnerable to climate warming.",
        tags: ["periglacial", "permafrost", "pingo"],
      },
      {
        name: "Soils and weathering profiles",
        description: "Vertical zones (O, A, B, C, R horizons) of biological-chemical-physical alteration.",
        keyFact: "USDA soil taxonomy: 12 orders (oxisol, ultisol, mollisol, alfisol, spodosol, vertisol, aridisol, andisol, gelisol, histosol, inceptisol, entisol). Sets agricultural capability and engineering behavior.",
        tags: ["soil", "pedogenesis", "horizon"],
      },
      {
        name: "Stream power law",
        description: "Rate of bedrock incision relates to discharge and slope.",
        keyFact: "$E = K A^m S^n$ — erosion rate as power of upstream area $A$ (proxy for discharge) and channel slope $S$. Underpins landscape evolution models (CHILD, LANDLAB) for tectonic-climate-erosion coupling.",
        formula: "E = K A^m S^n",
        xref: ["statistics", "physics"],
        tags: ["stream-power", "incision"],
      },
      {
        name: "Mass balance and denudation rates",
        description: "Net surface lowering of landscapes over time.",
        keyFact: "Modern global average ~50 mm/kyr. Measured by cosmogenic $^{10}\\mathrm{Be}$ in catchment sediments, thermochronology (apatite fission track, $\\mathrm{U-Th}/\\mathrm{He}$), and sediment flux. Records orogen-erosion-climate coupling.",
        tags: ["denudation", "cosmogenic", "exhumation"],
      },
    ],
  },

  // ── Family 13 ─────────────────────────────────────────────────────────────
  {
    slug: "sedimentology",
    number: 13,
    name: "Sedimentology",
    blurb: "Modern depositional environments and the processes producing sedimentary deposits.",
    section: "C",
    color: "amber",
    entries: [
      {
        name: "Depositional environments",
        description: "Settings where sediment accumulates: terrestrial, transitional, marine.",
        keyFact: "Terrestrial: alluvial fan, fluvial, lacustrine, eolian, glacial. Transitional: delta, estuary, lagoon, tidal flat, beach, barrier island. Marine: shoreface, shelf, slope, deep sea, reef, abyssal. Each leaves characteristic facies.",
        tags: ["environments", "facies"],
      },
      {
        name: "Grain size — Wentworth scale",
        description: "Logarithmic size classification of clastic particles.",
        keyFact: "Boulder (>256 mm) → cobble (64–256) → pebble (4–64) → granule (2–4) → sand (0.0625–2) → silt (0.004–0.0625) → clay (<0.004). $\\phi = -\\log_2 D$ where $D$ is mm. Sets transport mechanics and reservoir quality.",
        formula: "\\phi = -\\log_2 D_{mm}",
        xref: ["statistics"],
        tags: ["grain-size", "wentworth", "phi"],
      },
      {
        name: "Sorting and rounding",
        description: "Textural maturity indicators: uniformity of size and roundness of grains.",
        keyFact: "Well-sorted, well-rounded → mature, long-transported (eolian, beach). Poorly sorted, angular → immature, short-transported (debris flow, glacial). Beach sands often dual-sorted (waves) but variable in roundness.",
        tags: ["sorting", "rounding", "maturity"],
      },
      {
        name: "Bedforms and flow regimes",
        description: "Sediment shapes change with flow velocity: ripples → dunes → upper plane bed → antidunes.",
        keyFact: "Lower-flow regime: ripples (<~0.5 m/s), dunes (~0.5–1.5 m/s). Upper-flow regime: plane bed, antidunes. Cross-bedding architecture records the bedform type and flow direction.",
        tags: ["bedforms", "ripple", "dune"],
      },
      {
        name: "Turbidites and Bouma sequence",
        description: "Deep-water deposits from sediment gravity flows.",
        keyFact: "Bouma (1962) Ta–Te sequence: massive/graded, parallel-laminated, ripple cross-laminated, parallel-laminated, pelagic mud. Classic submarine fan facies; Tertiary turbidites are major hydrocarbon reservoirs (North Sea, Gulf of Mexico).",
        status: "landmark",
        tags: ["turbidite", "bouma"],
      },
      {
        name: "Sequence stratigraphy",
        description: "Subdivision of strata into sequences bounded by unconformities driven by relative sea-level change.",
        keyFact: "Exxon model: lowstand, transgressive, and highstand systems tracts bounded by sequence boundaries (subaerial unconformity) and flooding surfaces. Predicts reservoir, seal, and source-rock distributions globally.",
        tags: ["sequence-stratigraphy", "exxon", "systems-tract"],
      },
      {
        name: "Carbonate facies and Wilson model",
        description: "Carbonate platforms partitioned into 9 facies belts from basin to back-reef.",
        keyFact: "James Lee Wilson (1975): basin, deep shelf, slope, reef, shelf margin, shelf, lagoon, evaporite. Architecture controlled by light, oxygen, and salinity — not just water depth. Bahamas is the modern type case.",
        tags: ["carbonate", "wilson-model", "platform"],
      },
      {
        name: "Reef-building organisms through time",
        description: "Reef-building biotas have shifted between major taxonomic groups.",
        keyFact: "Stromatolite-dominant (Precambrian); archaeocyathid (early Cambrian); tabulate-rugose corals (Paleozoic); scleractinian corals (Mesozoic-Recent); rudist bivalves (mid-Cretaceous, replaced corals briefly). Reef gaps follow mass extinctions.",
        tags: ["reef", "stromatolite", "rudist"],
      },
      {
        name: "Deltas — Galloway classification",
        description: "Three end-members by dominant process: river, wave, tide.",
        keyFact: "Galloway (1975) ternary diagram. River-dominated (Mississippi, bird-foot), wave-dominated (Nile, Senegal), tide-dominated (Ganges-Brahmaputra, Fly). Architecture controls sand-body geometry and reservoir compartmentalization.",
        tags: ["delta", "galloway"],
      },
      {
        name: "Trace fossils (ichnofacies)",
        description: "Sedimentary structures from organism activity — burrows, tracks, feeding traces.",
        keyFact: "Seilacher ichnofacies (Skolithos, Cruziana, Zoophycos, Nereites) recur through time in equivalent water depths/energies. Trace-fossil 'tiering' integrates the disturbance over depth in sediment.",
        tags: ["ichnofacies", "burrows", "seilacher"],
      },
      {
        name: "Mass extinctions in the rock record",
        description: "Sharp turnovers preserved as biostratigraphic breaks.",
        keyFact: "The 'Big Five': End-Ordovician, Late Devonian, End-Permian (worst), End-Triassic, End-Cretaceous. K-Pg iridium anomaly (Alvarez 1980) was a sedimentologic discovery — a 1-cm clay layer worldwide.",
        status: "landmark",
        tags: ["mass-extinction", "iridium", "k-pg"],
      },
      {
        name: "Provenance analysis",
        description: "Identifying the source region of clastic sediments.",
        keyFact: "Detrital zircon $\\mathrm{U-Pb}$ ages, heavy-mineral assemblages, sandstone composition (QFL diagrams), $\\mathrm{Sm-Nd}$ model ages. Built the modern picture of paleocontinental reconstructions back through the Precambrian.",
        tags: ["provenance", "detrital-zircon", "qfl"],
      },
    ],
  },

  // ── Family 14 ─────────────────────────────────────────────────────────────
  {
    slug: "hydrogeology",
    number: 14,
    name: "Hydrogeology",
    blurb: "Subsurface water — aquifers, flow, and groundwater quality.",
    section: "C",
    color: "blue",
    entries: [
      {
        name: "Hydrologic cycle",
        description: "Continuous movement of water among atmosphere, ocean, land, and ice.",
        keyFact: "Reservoirs: ocean (~96.5%), ice (~1.7%), groundwater (~1.7%), surface water (~0.013%). Residence times: oceans ~3,000 yr, groundwater years to millions, atmosphere ~9 days. Global precipitation ~500,000 km³/yr.",
        tags: ["hydrologic-cycle", "residence-time"],
      },
      {
        name: "Aquifer (definition)",
        description: "A geologic unit that can transmit useful quantities of water.",
        keyFact: "Confined vs unconfined; consolidated (limestone, sandstone, basalt) vs unconsolidated (alluvium). Aquitard: low-permeability layer that confines. Aquiclude (rare): essentially impermeable.",
        tags: ["aquifer", "confined", "unconfined"],
      },
      {
        name: "Porosity and permeability",
        description: "Fraction of void space; ability to transmit fluid.",
        keyFact: "Porosity $n$ = void volume / total volume. Permeability $k$ (m²) is a property of the rock; hydraulic conductivity $K = k\\rho g/\\mu$ depends on the fluid too. Gravels can exceed $10^{-2}$ m/s; clays as low as $10^{-11}$ m/s.",
        formula: "K = \\rho g k / \\mu",
        xref: ["physics"],
        tags: ["porosity", "permeability", "conductivity"],
      },
      {
        name: "Darcy's law",
        description: "Henry Darcy (1856) — discharge through a porous medium scales linearly with hydraulic gradient.",
        keyFact: "$Q = -KA\\,(dh/dl)$ — discharge $Q$ equals hydraulic conductivity $K$ × cross-sectional area $A$ × hydraulic gradient. Foundation of quantitative hydrogeology. Breaks down at very high Reynolds number (Forchheimer regime).",
        formula: "Q = -KA\\, \\tfrac{dh}{dl}",
        xref: ["physics"],
        status: "landmark",
        tags: ["darcy", "groundwater-flow"],
      },
      {
        name: "Hydraulic head and potentiometric surface",
        description: "Combined pressure + elevation head; the energy driving groundwater flow.",
        keyFact: "$h = z + p/(\\rho g)$. Water flows from higher to lower head, not from higher to lower elevation. Potentiometric surfaces map the head in confined aquifers; the water table is the unconfined equivalent.",
        formula: "h = z + p/(\\rho g)",
        xref: ["physics"],
        tags: ["head", "potentiometric"],
      },
      {
        name: "Theis equation",
        description: "Transient drawdown response to constant pumping from a confined aquifer.",
        keyFact: "C. V. Theis (1935) — analytical solution for drawdown $s = (Q/4\\pi T) W(u)$, $u = r^2 S / 4 T t$. Standard test for transmissivity $T$ and storativity $S$. Cooper-Jacob is its semi-log approximation.",
        formula: "s = (Q/4\\pi T)\\, W(u)",
        xref: ["physics", "statistics"],
        status: "landmark",
        tags: ["theis", "pump-test"],
      },
      {
        name: "Confined vs unconfined aquifers",
        description: "Aquifers bounded above by aquitard (confined) or by the water table (unconfined).",
        keyFact: "Confined aquifers respond elastically to pumping (storativity $S \\sim 10^{-4}$); unconfined dewater (specific yield $S_y \\sim 0.1$–0.3). Artesian wells flow without pumping when potentiometric surface is above ground.",
        tags: ["confined", "unconfined", "artesian"],
      },
      {
        name: "Saltwater intrusion (Ghyben-Herzberg)",
        description: "Saline-freshwater interface in coastal aquifers.",
        keyFact: "Ghyben-Herzberg: depth to saltwater interface = ~40 × elevation of water table above sea level (density ratio 1025/25 ≈ 41). Over-pumping coastal wells lifts the interface and salinizes wells (Florida, Bangladesh, California).",
        formula: "z_s = (\\rho_f/(\\rho_s - \\rho_f))\\, h_f",
        tags: ["saltwater-intrusion", "ghyben-herzberg"],
      },
      {
        name: "Contaminant transport",
        description: "Movement of dissolved or particulate contaminants in groundwater.",
        keyFact: "Advection-dispersion equation $\\partial c/\\partial t = -v\\,\\partial c/\\partial x + D\\,\\partial^2 c/\\partial x^2$. Sorption, biodegradation, radioactive decay modify transport. Plumes from gasoline (BTEX), TCE, PFAS, nitrate are common.",
        formula: "\\tfrac{\\partial c}{\\partial t} = -v\\tfrac{\\partial c}{\\partial x} + D\\tfrac{\\partial^2 c}{\\partial x^2}",
        xref: ["statistics", "physics"],
        tags: ["transport", "advection-dispersion", "pfas"],
      },
      {
        name: "Aquifer depletion",
        description: "Persistent over-pumping draws down regional water tables irreversibly.",
        keyFact: "Ogallala Aquifer (US High Plains) — half-life ~50 yr at present rates. North China Plain, North India (NW), Central Valley California, Murzuk (Libya). Subsidence, well failure, salinization follow. GRACE satellites measure depletion globally.",
        tags: ["depletion", "ogallala", "grace"],
      },
      {
        name: "Geothermal water and hot springs",
        description: "Surface manifestation of heated groundwater systems.",
        keyFact: "Boiling springs (geysers — Yellowstone Old Faithful, Geysir Iceland), fumaroles, mud pots. Convective cells driven by heat at depth. Enhanced geothermal systems (EGS) attempt to extract heat from dry hot rock for power.",
        tags: ["geothermal", "geyser", "egs"],
      },
    ],
  },

  // ── Family 15 ─────────────────────────────────────────────────────────────
  {
    slug: "glaciology",
    number: 15,
    name: "Glaciology",
    blurb: "Ice sheets, glaciers, sea ice, and the cryosphere.",
    section: "C",
    color: "sky",
    entries: [
      {
        name: "Glacier (definition)",
        description: "A persistent body of dense ice that flows downhill under its own weight.",
        keyFact: "Forms where snow accumulation exceeds melting over many years; ~10% snow becomes ~90% ice after ~$10^2$ yr densification. Polythermal (cold-based vs warm-based) classification distinguishes basal conditions.",
        tags: ["glacier", "ice"],
      },
      {
        name: "Continental ice sheets",
        description: "Greenland and Antarctica — Earth's two remaining ice sheets.",
        keyFact: "Antarctic ice sheet ~26.5 million km³ (sea-level equivalent ~58 m); Greenland ~2.9 million km³ (~7.4 m). Both losing mass since ~2000 (GRACE, IceSat-2). West Antarctic Ice Sheet considered marine-instability vulnerable.",
        tags: ["ice-sheet", "greenland", "antarctica"],
      },
      {
        name: "Glacier mass balance",
        description: "Annual accumulation minus ablation; sets whether a glacier grows or retreats.",
        keyFact: "ELA (equilibrium line altitude) separates net accumulation from net loss zone. Worldwide negative mass balances since ~1990 (WGMS data); glaciers have lost ~30 m water equivalent on average. Sea-level contribution ~1 mm/yr currently from non-ice-sheet glaciers.",
        tags: ["mass-balance", "ela"],
      },
      {
        name: "Glacier flow — Glen's law",
        description: "Ice deforms as a power-law fluid: strain rate $\\propto \\tau^n$, $n \\approx 3$.",
        keyFact: "Glen (1955): $\\dot\\varepsilon = A \\tau^n$ with $n \\approx 3$. Underpins all glacier flow models. Temperature-dependent $A$ doubles roughly every 10 °C between $-30$°C and $0$°C.",
        formula: "\\dot\\varepsilon = A \\tau^n",
        xref: ["physics"],
        status: "landmark",
        tags: ["glen", "rheology"],
      },
      {
        name: "Basal sliding and surging",
        description: "Many glaciers move by basal slip on water-lubricated beds; some surge episodically.",
        keyFact: "Cold-based: frozen to bed, no slip. Warm-based: slip on subglacial water film and till. Surge-type glaciers cycle between quiescent decades and 10–100× speed-up over months (Karakoram, Yukon, Svalbard).",
        tags: ["basal-sliding", "surge"],
      },
      {
        name: "Crevasses and seracs",
        description: "Brittle fractures and ice columns in the upper ~30 m of glaciers.",
        keyFact: "Crevasses open perpendicular to maximum tensile stress; transverse (extensional flow), longitudinal (lateral spreading), marginal (shear with valley walls). Below ~30 m, ice flow heals fractures by creep.",
        tags: ["crevasse", "serac"],
      },
      {
        name: "Glacial erosion and deposition",
        description: "Glaciers carve and deposit at distinctive scales.",
        keyFact: "Plucking and abrasion produce striations, roche moutonnée, whaleback. Subglacial meltwater carves tunnel valleys. Deposition zones leave moraines, drumlins, eskers, outwash plains — defining glaciated landscapes.",
        tags: ["erosion", "plucking", "abrasion"],
      },
      {
        name: "Ice cores and paleoclimate",
        description: "Layered glacier ice preserves atmospheric history.",
        keyFact: "EPICA Dome C: 800,000 yr of $\\mathrm{CO_2}$, $\\mathrm{CH_4}$, $\\delta D$ temperature. Glacial maxima at ~280→180 ppm $\\mathrm{CO_2}$; interglacials at ~280 ppm. Modern $\\mathrm{CO_2}$ (~420 ppm in 2024) is the highest in at least 800 kyr — likely several Myr.",
        status: "landmark",
        tags: ["ice-core", "epica", "co2"],
      },
      {
        name: "Sea ice",
        description: "Frozen surface of polar oceans — Arctic perennial vs seasonal Antarctic.",
        keyFact: "Arctic sea-ice September minimum has declined ~13%/decade since 1979 (NSIDC). Antarctic sea ice was rising slightly until ~2016, then dropped sharply. Brine rejection during freezing drives Antarctic Bottom Water formation.",
        tags: ["sea-ice", "nsidc", "aabw"],
      },
      {
        name: "Snowball Earth",
        description: "Hypothesized global glaciations in the Neoproterozoic.",
        keyFact: "Cryogenian glaciations (Sturtian ~717–660 Ma, Marinoan ~650–635 Ma) reached the equator. Iron formations and cap carbonates support the freeze-thaw scenario. Possibly co-evolved with rise of multicellular life. Still debated in detail.",
        status: "open",
        tags: ["snowball-earth", "cryogenian", "cap-carbonate"],
      },
      {
        name: "Permafrost and methane release",
        description: "Permanently frozen ground containing organic carbon and methane clathrates.",
        keyFact: "Northern hemisphere permafrost stores ~1500 PgC. Warming releases $\\mathrm{CO_2}$ and $\\mathrm{CH_4}$, potentially amplifying global warming. Thermokarst, thaw slumps, gas blowout craters (Yamal Peninsula) document active loss.",
        tags: ["permafrost", "methane-clathrate"],
      },
      {
        name: "Marine ice sheet instability",
        description: "Grounded ice sheets resting on landward-deepening beds can collapse irreversibly.",
        keyFact: "Hypothesized for Thwaites and Pine Island Glaciers (W. Antarctica). Once grounding line retreats past a bedrock high, accelerating retreat is hard to halt. Sea-level rise estimates of 1+ m by 2100 hinge on this process.",
        status: "open",
        tags: ["misi", "thwaites", "sea-level"],
      },
    ],
  },

  // ── Family 16 ─────────────────────────────────────────────────────────────
  {
    slug: "oceanography",
    number: 16,
    name: "Marine Geology & Oceanography",
    blurb: "Ocean basins, seafloor, currents, and marine sediments.",
    section: "C",
    color: "cyan",
    entries: [
      {
        name: "Ocean basin morphology",
        description: "Continental shelf, slope, rise, abyssal plain, mid-ocean ridge, trench.",
        keyFact: "Shelves average ~78 km wide, slopes drop ~3,500 m at ~4° to abyssal plains (~4–5 km depth). Trenches are the deepest (Mariana ~11 km). Mid-ocean ridges stand ~2.5 km above abyssal plains.",
        tags: ["basin", "shelf", "trench"],
      },
      {
        name: "Bathymetric mapping",
        description: "Mapping ocean depth — multibeam sonar and satellite altimetry.",
        keyFact: "Only ~25% of seafloor mapped at <100-m resolution as of 2024 (Seabed 2030). Satellite altimetry (Sandwell & Smith) gives ~5-km resolution everywhere via gravity-from-sea-surface; multibeam ships fill in the high-resolution gaps.",
        tags: ["bathymetry", "multibeam", "altimetry"],
      },
      {
        name: "Mid-ocean ridge system",
        description: "65,000 km global underwater mountain range — the longest geologic feature on Earth.",
        keyFact: "Continuous from Arctic through Atlantic to Indian and into the East Pacific. Spreading rates 1.3 cm/yr (Gakkel, Arctic) to ~16 cm/yr (East Pacific Rise). Source of ~75% of Earth's volcanism.",
        tags: ["mor", "ridge", "spreading"],
      },
      {
        name: "Hydrothermal vents and black smokers",
        description: "Hot mineral-rich fluids venting from cracked oceanic crust.",
        keyFact: "First observed at Galápagos Rift (1977) and East Pacific Rise (1979). Black smokers vent ~350 °C $\\mathrm{Fe-Cu-Zn}$ sulfide-laden fluids. Host chemosynthetic ecosystems (tube worms, mussels) and may have been the cradle of life.",
        status: "landmark",
        tags: ["hydrothermal", "black-smoker", "origin-of-life"],
      },
      {
        name: "Submarine canyons and fans",
        description: "V-shaped erosional features cut across continental slopes; depositional fans seaward.",
        keyFact: "Carved by turbidity currents. Major systems: Hudson, Monterey, Congo, Bengal, Indus. Bengal Fan is the world's largest (~3,000 km long, 7 km thick) — sediment from Himalayan erosion since ~17 Ma.",
        tags: ["canyon", "fan", "bengal"],
      },
      {
        name: "Pelagic and hemipelagic sediments",
        description: "Slow-rain biogenic and clay deposits in deep ocean.",
        keyFact: "Calcareous ooze (foram/coccolithophore) above CCD (~4.5 km); siliceous ooze (diatom/radiolarian) where productivity high; red clay where neither dominates. Sedimentation rates 1–10 mm/kyr.",
        tags: ["pelagic", "ooze", "ccd"],
      },
      {
        name: "Carbonate compensation depth (CCD)",
        description: "Depth below which $\\mathrm{CaCO_3}$ dissolves faster than it accumulates.",
        keyFact: "Modern CCD ~4.5 km. Above the CCD, calcareous oozes accumulate; below, only red clay and siliceous ooze persist. CCD shoaling is a marker for ocean acidification events (PETM, K-Pg).",
        tags: ["ccd", "calcite", "acidification"],
      },
      {
        name: "Thermohaline circulation",
        description: "Global conveyor belt — density-driven deep ocean circulation.",
        keyFact: "Cold dense water sinks in N. Atlantic (NADW) and around Antarctica (AABW), upwells in Pacific/Indian, returns at surface. Cycle time ~1,000 yr. AMOC (Atlantic Meridional Overturning) slowing is a major climate-tipping concern.",
        xref: ["physics"],
        tags: ["thermohaline", "amoc", "conveyor"],
      },
      {
        name: "Sea-level change",
        description: "Eustatic, glacio-isostatic, tectonic, and steric components.",
        keyFact: "Eustatic: global mean from ice-volume and ocean-volume change. GIA: glacial isostatic adjustment, ~1 mm/yr at far field from former ice sheets. Modern rise ~3.7 mm/yr (satellite altimetry, 1993–present), accelerating.",
        tags: ["sea-level", "eustatic", "gia"],
      },
      {
        name: "Tsunamis",
        description: "Long-wavelength ocean waves from sudden seafloor displacement.",
        keyFact: "Generated by subduction megathrust earthquakes (2004 Sumatra $M_w$ 9.1; 2011 Tōhoku $M_w$ 9.1), large submarine landslides (Storegga ~8200 BP), or volcanic flank collapse (Krakatau 1883). Wavelength 100s of km in deep ocean.",
        tags: ["tsunami", "megathrust", "sumatra"],
      },
      {
        name: "Continental shelves and exclusive economic zones",
        description: "Submerged margins of continents — geology, biology, jurisdiction.",
        keyFact: "Average shelf width ~78 km, depth <200 m. UN Convention on Law of the Sea (UNCLOS) extends EEZ to 200 nautical miles; extended continental shelf claims to 350 nm with geologic justification (sediment thickness $\\geq 1$%).",
        tags: ["shelf", "eez", "unclos"],
      },
      {
        name: "Marine geohazards",
        description: "Submarine landslides, methane hydrate destabilization, slope instability.",
        keyFact: "Storegga Slide (~8,200 BP, North Sea) — 3,500 km³ slumped, generated tsunami flooding the Shetlands. Methane hydrate destabilization is a destabilizing climate feedback; gas blowouts have left pockmarks on shelf seafloor globally.",
        tags: ["geohazard", "storegga", "hydrate"],
      },
    ],
  },
];
