import type { Family } from "./types";

export const FAMILIES_12_18: Family[] = [
  // ── Family 12 ─────────────────────────────────────────────────────────────
  {
    slug: "endocrine-physiology",
    number: 12,
    name: "Endocrine Physiology",
    blurb: "Hypothalamic-pituitary axes, thyroid, adrenal, pancreatic islets, and the integration of hormonal control.",
    section: "C",
    color: "amber",
    systems: ["endocrine"],
    entries: [
      {
        name: "Hypothalamic-pituitary axis",
        description: "Hypothalamic releasing hormones travel through portal capillaries to control anterior pituitary trophic hormones.",
        keyFact: "Releasing hormones: TRH, CRH, GnRH, GHRH; inhibitory: somatostatin, dopamine (PIF for prolactin). Negative feedback at three levels: target-gland hormone on pituitary and hypothalamus, and pituitary hormones on hypothalamus. Posterior pituitary stores ADH and oxytocin synthesized by SON/PVN. Pulsatile GnRH (every 60–90 min) is required for LH/FSH secretion — continuous GnRH desensitizes (leuprolide).",
        tags: ["HPA", "portal system", "feedback"],
        status: "landmark",
      },
      {
        name: "Thyroid hormone synthesis and action",
        description: "Iodide trapped, oxidized, coupled to thyroglobulin tyrosines, secreted as T4; converted to active T3 peripherally.",
        keyFact: "NIS (Na⁺/I⁻ symporter) concentrates iodide ∼30×. TPO catalyzes oxidation, organification, coupling. T4:T3 ratio ∼14:1 secreted; 80% of T3 comes from peripheral deiodination (D1 liver/kidney, D2 brain/pituitary/BAT, D3 inactivating). T3 binds nuclear TR → coactivator recruitment → ↑BMR, thermogenesis, growth, cardiac inotropy. Wolff-Chaikoff effect: pharmacologic iodide transiently inhibits hormone synthesis.",
        researcher: "Harington (T4 structure, 1926); Gross & Pitt-Rivers (T3, 1952)",
        tags: ["T4", "T3", "deiodinase"],
        xref: ["medicine"],
      },
      {
        name: "Adrenal cortex: cortisol and aldosterone",
        description: "Zona fasciculata makes glucocorticoids; zona glomerulosa makes mineralocorticoids; zona reticularis makes androgens.",
        keyFact: "Cortisol: diurnal (peak ∼6–8 AM); permissive for glucagon and catecholamines; gluconeogenic; immunosuppressive at pharmacologic doses; CRH-ACTH-cortisol with negative feedback. Aldosterone: stimulated by AngII and ↑K⁺ (not by ACTH chronically); MR also binds cortisol but 11β-HSD2 in kidney protects MR. Congenital adrenal hyperplasia: 21-hydroxylase deficiency (∼95%) → low cortisol, shunted androgens → virilization.",
        tags: ["cortisol", "aldosterone", "CAH"],
        xref: ["medicine"],
      },
      {
        name: "Insulin secretion and action",
        description: "Glucose-driven β-cell depolarization releases insulin; insulin enables tissue glucose uptake and anabolic storage.",
        keyFact: "Glucose → GLUT2 → glucokinase (glucose sensor, K_m ∼10 mM) → ↑ATP/ADP → closes KATP (SUR1/Kir6.2) → depolarization → Cav1.2 → Ca²⁺-triggered insulin exocytosis. Insulin → IR tyrosine kinase → IRS-1 → PI3K-Akt → GLUT4 translocation in muscle and adipose; ↑glycogen synthesis; ↓lipolysis; ↓gluconeogenesis. Sulfonylureas close KATP (independent of glucose) → hypoglycemia risk.",
        researcher: "Banting & Macleod (Nobel 1923)",
        tags: ["insulin", "KATP", "GLUT4"],
        status: "landmark",
        xref: ["medicine"],
      },
      {
        name: "Glucagon and counter-regulation",
        description: "α-cells release glucagon during hypoglycemia, mobilizing hepatic glucose output.",
        keyFact: "Glucagon → Gs/cAMP/PKA → ↑glycogenolysis, ↑gluconeogenesis, ↑ketogenesis. Other counter-regulatory hormones: epinephrine, cortisol, GH. T1DM patients lose glucagon counter-regulation over years → hypoglycemia unawareness. GLP-1 from L cells potentiates glucose-stimulated insulin secretion (incretin effect — explains why oral glucose triggers more insulin than IV).",
        tags: ["glucagon", "incretin", "GLP-1"],
        xref: ["medicine"],
      },
      {
        name: "Calcium homeostasis: PTH, vitamin D, calcitonin",
        description: "PTH and 1,25(OH)₂D coordinate intestinal absorption, renal handling, and bone turnover to maintain serum [Ca²⁺].",
        keyFact: "PTH (chief cells; CaSR senses ↓[Ca²⁺]): ↑bone resorption (RANKL), ↑renal Ca²⁺ reabsorption (DCT), ↓phosphate reabsorption (PT), ↑1α-hydroxylase → calcitriol. Calcitriol: ↑intestinal Ca²⁺ and PO₄³⁻ absorption (TRPV6, calbindin). FGF23 from osteocytes: phosphaturic and suppresses calcitriol. Calcitonin (parafollicular C cells): inhibits osteoclasts; minor physiologic role in humans.",
        tags: ["PTH", "calcitriol", "FGF23"],
        xref: ["medicine"],
      },
      {
        name: "Growth hormone and IGF-1",
        description: "Pulsatile GH stimulates hepatic IGF-1 production, driving longitudinal growth and metabolic effects.",
        keyFact: "GHRH ↑, somatostatin ↓; ghrelin from stomach is a GH secretagogue. GH effects: direct (lipolysis, insulin antagonism — diabetogenic) and indirect via IGF-1 (anabolic). Epiphyseal closure ends linear growth; excess GH after closure → acromegaly. GH negative feedback via IGF-1 and somatostatin.",
        tags: ["GH", "IGF-1", "acromegaly"],
        xref: ["medicine"],
      },
      {
        name: "Reproductive hormones (HPG axis)",
        description: "Pulsatile GnRH drives LH/FSH; LH stimulates Leydig/theca androgens, FSH stimulates Sertoli/granulosa.",
        keyFact: "Female cycle: follicular phase (FSH-driven follicle growth, rising estradiol) → mid-cycle estradiol positive feedback → LH surge → ovulation → luteal phase (progesterone-dominant). Menopause: ovarian failure → ↑FSH, ↑LH, ↓estradiol. Male: continuous LH-pulsatile testosterone; inhibin B from Sertoli feeds back on FSH. Aromatase converts androgens to estrogens locally.",
        tags: ["GnRH", "LH", "estrogen"],
        xref: ["medicine"],
        status: "landmark",
      },
    ],
  },

  // ── Family 13 ─────────────────────────────────────────────────────────────
  {
    slug: "reproductive-physiology",
    number: 13,
    name: "Reproductive Physiology",
    blurb: "Gametogenesis, pregnancy, parturition, and lactation.",
    section: "C",
    color: "rose",
    systems: ["reproductive"],
    entries: [
      {
        name: "Spermatogenesis",
        description: "Continuous production of ∼200 million sperm/day from spermatogonia in seminiferous tubules.",
        keyFact: "Spermatogonia (2n) → primary spermatocyte (2n, 4C) → meiosis I → secondary spermatocyte → meiosis II → spermatids → spermiogenesis → spermatozoa. Sertoli cells form blood-testis barrier and nurse developing germ cells; FSH-responsive. Testosterone (from Leydig cells) required at high local concentration. Cycle ∼74 days. Cool (∼34 °C) scrotal temperature required.",
        tags: ["meiosis", "Sertoli", "Leydig"],
        xref: ["biology"],
      },
      {
        name: "Oogenesis and the ovarian cycle",
        description: "Fixed pool of primary oocytes arrested in prophase I; one matures per cycle.",
        keyFact: "All primary oocytes formed by mid-gestation (∼7M); ∼1M at birth; ∼400K at menarche; ∼400 ovulated over reproductive life. Meiosis I completed at ovulation (LH surge); meiosis II only at fertilization. Dominant follicle selected ∼day 7 (highest FSH responsiveness, lowest atresia). Corpus luteum: progesterone-dominant; regresses without hCG rescue.",
        tags: ["oocyte", "follicle", "corpus luteum"],
      },
      {
        name: "Fertilization and implantation",
        description: "Acrosomal reaction, sperm-egg fusion, cortical reaction prevent polyspermy; blastocyst implants ∼day 6–7.",
        keyFact: "Capacitation in female tract enables acrosome reaction. ZP3 triggers acrosome reaction; ZP2 cleavage post-fertilization blocks polyspermy. Trophoblast invades endometrium; syncytiotrophoblast secretes hCG (rescues corpus luteum). Implantation requires receptive endometrium (window ∼days 20–24 of cycle) — high progesterone, low LIF and integrin defects → implantation failure.",
        tags: ["fertilization", "blastocyst", "hCG"],
      },
      {
        name: "Maternal adaptations to pregnancy",
        description: "Cardiac output ↑40%, plasma volume ↑45%, GFR ↑50%, BP often ↓ in mid-pregnancy.",
        keyFact: "Plasma volume rises more than RBC mass → physiologic anemia of pregnancy. Progesterone-driven smooth-muscle relaxation: ↓SVR, ↓GI motility, ↓ureteral tone. Respiratory: progesterone-driven chronic respiratory alkalosis (↑VT, mild ↓PaCO₂). Insulin resistance progresses across gestation (hPL, cortisol, placental GH) → gestational diabetes if β-cell reserve inadequate.",
        tags: ["pregnancy", "plasma volume"],
        xref: ["medicine"],
      },
      {
        name: "Placental physiology",
        description: "The placenta serves as fetal lung, gut, kidney, and endocrine organ.",
        keyFact: "Maternal-fetal gas exchange driven by partial-pressure gradients; fetal Hb left-shifts curve. Glucose crosses by GLUT1 facilitated diffusion. Endocrine: hCG (early), progesterone and estriol (term), hPL, placental GH. IgG actively transported via FcRn — sole source of fetal humoral immunity. Drug crossing: lipid-soluble, low MW, unionized cross most.",
        tags: ["placenta", "FcRn", "hCG"],
      },
      {
        name: "Parturition",
        description: "Labor initiated by integrated fetal-maternal signals: CRH, oxytocin, prostaglandins, mechanical stretch.",
        keyFact: "Late gestation: placental CRH rises → fetal HPA activation → cortisol → lung maturation, surfactant. Estrogen:progesterone ratio reverses near term. Ferguson reflex: cervical stretch → oxytocin release → ↑uterine contractions (positive feedback). PGF2α-driven contractions and cervical ripening. Prematurity remains a leading cause of neonatal mortality globally.",
        tags: ["labor", "oxytocin", "CRH"],
        xref: ["medicine"],
        status: "contested",
      },
      {
        name: "Lactation",
        description: "Mammogenesis (estrogen/progesterone) → lactogenesis (delivery + prolactin) → milk ejection (oxytocin let-down).",
        keyFact: "Prolactin (anterior pituitary, dopamine-inhibited) drives milk synthesis. Falling progesterone post-placental delivery permits lactogenesis II (∼day 3). Suckling → afferent stimulus → oxytocin (myoepithelial contraction) and prolactin pulses. Exclusive breastfeeding suppresses ovulation via PRL-mediated GnRH suppression — \"lactational amenorrhea.\"",
        tags: ["lactation", "prolactin", "oxytocin"],
      },
    ],
  },

  // ── Family 14 ─────────────────────────────────────────────────────────────
  {
    slug: "muscle-physiology",
    number: 14,
    name: "Muscle Physiology",
    blurb: "Skeletal, smooth, and cardiac muscle — structure, contraction, and force generation.",
    section: "D",
    color: "indigo",
    systems: ["musculoskeletal"],
    entries: [
      {
        name: "Sarcomere and sliding-filament theory",
        description: "Force generation arises from cross-bridge cycling between actin and myosin filaments within sarcomeres.",
        keyFact: "Z-disc to Z-disc; thick filaments (myosin) anchored at M-line, thin filaments (actin) anchored at Z-disc. Contraction shortens I band and H zone; A band length unchanged. Optimal sarcomere length ∼2.2 µm (maximal overlap). Cross-bridge cycle: ATP binding → myosin detachment → hydrolysis-driven recocking → weak then strong actin binding → Pi release → power stroke → ADP release.",
        researcher: "H.E. Huxley & A.F. Huxley (1954)",
        tags: ["sarcomere", "cross-bridge", "sliding filament"],
        status: "landmark",
      },
      {
        name: "Skeletal E-C coupling",
        description: "DHPR-RyR1 mechanical coupling links T-tubule depolarization to SR Ca²⁺ release.",
        keyFact: "Unlike cardiac CICR, skeletal muscle uses voltage-sensor DHPR (Cav1.1) to physically open RyR1 — no Ca²⁺ entry required. Ca²⁺ binds troponin C → tropomyosin moves → exposes actin binding sites. Relaxation: SERCA1 returns Ca²⁺ to SR; parvalbumin buffers cytosolic Ca²⁺ in fast fibers. Malignant hyperthermia: RYR1 mutation → uncontrolled Ca²⁺ release with volatile anesthetics/succinylcholine.",
        tags: ["DHPR", "RyR1", "MH"],
        xref: ["medicine"],
      },
      {
        name: "Motor units and recruitment",
        description: "One α-motor neuron + all fibers it innervates; the smallest unit of motor control.",
        keyFact: "Size principle (Henneman): small (slow, fatigue-resistant, low-threshold) motor units recruited first; large (fast, fatigable) recruited for high-force outputs. Force gradation: recruitment + rate coding (∼5 to 50 Hz). Innervation ratio: extraocular muscle ∼5:1 (fine control); quadriceps ∼1000:1 (force). Reinnervation after motor-neuron disease produces large units → fasciculations.",
        researcher: "Elwood Henneman",
        tags: ["motor unit", "size principle"],
        xref: ["neuroscience"],
        status: "landmark",
      },
      {
        name: "Fiber types",
        description: "Type I (slow oxidative), IIa (fast oxidative-glycolytic), IIx (fast glycolytic).",
        keyFact: "Type I: myoglobin-rich, mitochondria-rich, slow myosin heavy chain, fatigue-resistant — postural muscles. Type IIa: aerobic + glycolytic; sustained sprinting. Type IIx (humans lack pure IIb): glycolytic, fastest contraction, high force, fatigues quickly. Training shifts IIx → IIa. Aging: preferential type-II atrophy contributes to sarcopenia. PGC-1α mediates exercise-induced mitochondrial biogenesis.",
        tags: ["fiber types", "PGC-1α", "sarcopenia"],
      },
      {
        name: "Smooth muscle physiology",
        description: "Multi-unit and single-unit (visceral) smooth muscle differ in coupling and rhythmogenesis.",
        keyFact: "No sarcomeres — actin/myosin in irregular array anchored at dense bodies. Ca²⁺-CaM-MLCK pathway (not troponin-mediated). \"Latch\" cross-bridges sustain tone with low ATP. Visceral SM: gap-junction coupled, ICCs (Cajal cells) as pacemakers in gut. Pharmacomechanical coupling: agonist-induced contraction without depolarization (Gq/IP3 → Ca²⁺ release).",
        tags: ["smooth muscle", "latch", "MLCK"],
      },
      {
        name: "Length-tension and force-velocity relationships",
        description: "Active force depends on overlap; shortening velocity is inversely related to load.",
        keyFact: "Length-tension: active force peaks at L₀ (∼2.2 µm sarcomere); falls off below (filament overlap reduced) and above (less overlap). Force-velocity: $V = V_{max}(F_0 - F)/(F + a)$ (Hill, 1938); $V_{max}$ unloaded. Power = F·V peaks at ∼30% F₀. Eccentric (lengthening) contractions produce highest force (∼1.8× isometric) but cause most damage.",
        formula: "V = V_{max}(F_0 - F)/(F + a)",
        researcher: "A.V. Hill",
        tags: ["force-velocity", "Hill"],
      },
    ],
  },

  // ── Family 15 ─────────────────────────────────────────────────────────────
  {
    slug: "immune-physiology",
    number: 15,
    name: "Immune Physiology",
    blurb: "Innate and adaptive immunity, inflammation, and tolerance.",
    section: "D",
    color: "emerald",
    systems: ["immune"],
    entries: [
      {
        name: "Innate immunity and PRRs",
        description: "Germline-encoded pattern recognition receptors detect conserved microbial molecular patterns.",
        keyFact: "Toll-like receptors (TLR4 → LPS; TLR3 → dsRNA; TLR9 → CpG DNA), NOD-like receptors (NLRP3 inflammasome → caspase-1 → IL-1β/IL-18), RIG-I-like (cytosolic RNA), cGAS-STING (cytosolic DNA). Complement: classical (Ab), lectin (MBL), alternative (spontaneous C3 tickover) — converge on C3 → opsonization, MAC (C5b-9), anaphylatoxins (C3a, C5a).",
        researcher: "Janeway (PRRs); Beutler/Hoffmann (Nobel 2011)",
        tags: ["PRR", "TLR", "complement"],
        status: "landmark",
      },
      {
        name: "Adaptive immunity: T cells",
        description: "Thymic education yields TCRs that recognize peptide-MHC complexes; CD8 kills, CD4 helps.",
        keyFact: "MHC I (all nucleated cells): presents endogenous peptides (∼8–10 aa) → CD8 T cells. MHC II (APCs): presents exogenous peptides (∼12–25 aa) → CD4 T cells. Positive selection: TCR must bind self-MHC. Negative selection: high-affinity self-reactive cells deleted. CD4 subsets: Th1 (IFN-γ, intracellular), Th2 (IL-4/5/13, helminths/allergy), Th17 (IL-17, extracellular bacteria/fungi), Treg (FoxP3, suppression).",
        tags: ["MHC", "TCR", "Th"],
        status: "landmark",
      },
      {
        name: "Adaptive immunity: B cells and antibodies",
        description: "BCR diversity by V(D)J recombination; class switching and somatic hypermutation in germinal centers.",
        keyFact: "Five isotypes: IgM (pentamer, first response), IgG (4 subclasses, dominant secondary), IgA (mucosal dimer + secretory component), IgE (mast cells, allergy/helminths), IgD (BCR). Class switching (AID-mediated) and SHM occur in GCs under T-cell help (CD40L, IL-21). Affinity maturation selects high-affinity clones. Plasma cells: long-lived in bone marrow secrete Ab; memory B cells respond rapidly to re-encounter.",
        researcher: "Tonegawa (Nobel 1987)",
        tags: ["BCR", "VDJ", "germinal center"],
      },
      {
        name: "Inflammation and resolution",
        description: "Cardinal signs (rubor, calor, tumor, dolor, functio laesa) reflect vasodilation, ↑permeability, and recruitment.",
        keyFact: "Initiators: PAMPs/DAMPs → TLR/NLR → NF-κB → IL-1, TNF, IL-6. Vasoactive mediators: histamine, bradykinin, prostaglandins, NO. Leukocyte recruitment cascade: rolling (selectins) → activation (chemokines) → firm adhesion (integrin/ICAM) → diapedesis. Resolution: pro-resolving lipid mediators (lipoxins, resolvins, protectins); efferocytosis of apoptotic neutrophils by macrophages → switch to M2.",
        researcher: "Charles Serhan (resolvins)",
        tags: ["inflammation", "NF-kB", "resolvins"],
      },
      {
        name: "Tolerance and autoimmunity",
        description: "Central and peripheral mechanisms maintain self-tolerance; failure produces autoimmunity.",
        keyFact: "Central: thymic deletion (AIRE drives ectopic tissue antigen expression — APECED if mutated), bone marrow B-cell deletion/editing. Peripheral: anergy (signal 1 without signal 2), Tregs (FoxP3, CTLA-4, IL-10/TGF-β), peripheral deletion, ignorance. Checkpoint molecules CTLA-4 and PD-1 enforce peripheral tolerance — and are oncology targets when blockade unleashes anti-tumor T cells (Allison/Honjo, Nobel 2018).",
        tags: ["tolerance", "Treg", "checkpoint"],
        xref: ["medicine"],
        status: "landmark",
      },
      {
        name: "Mucosal and skin barrier immunity",
        description: "Most pathogen encounters occur at epithelial surfaces; barrier tissues mount tailored, regulated responses.",
        keyFact: "Gut: tolerance to food/microbiota with reactivity to pathogens — Peyer's patches, M cells, secretory IgA, ILC3 + Th17 maintain epithelium. Lung: alveolar macrophages constitutively suppressed; CCR6+ Th17 protect mucosa. Skin: keratinocyte AMPs (cathelicidin, defensins), Langerhans cells, γδ T cells. Dysregulation underlies IBD, asthma, atopic dermatitis.",
        tags: ["mucosal", "IgA", "barrier"],
        xref: ["medicine"],
      },
    ],
  },

  // ── Family 16 ─────────────────────────────────────────────────────────────
  {
    slug: "blood-hematology",
    number: 16,
    name: "Blood & Hemostasis",
    blurb: "Erythropoiesis, leukocyte production, coagulation, and the regulation of bleeding.",
    section: "D",
    color: "rose",
    systems: ["cardiovascular", "immune"],
    entries: [
      {
        name: "Erythropoiesis",
        description: "Bone-marrow production of ∼2 × 10¹¹ RBCs per day driven by erythropoietin.",
        keyFact: "EPO from renal peritubular fibroblasts under HIF-2α control responds to tissue PO₂. Acts on BFU-E/CFU-E via JAK2-STAT5. Iron, folate, B12 required. RBC lifespan ∼120 days; senescent cells cleared by splenic macrophages. HIF stabilization (PHD inhibitors) is a newer anemia therapy. Polycythemia vera: JAK2 V617F → EPO-independent erythropoiesis.",
        researcher: "Semenza & Ratcliffe (HIF, Nobel 2019)",
        tags: ["EPO", "HIF", "JAK2"],
        status: "landmark",
        xref: ["medicine"],
      },
      {
        name: "Hemostasis: primary and secondary",
        description: "Platelet plug (primary) plus fibrin mesh (secondary) seal vascular injury.",
        keyFact: "Primary: vWF bridges platelet GPIb to exposed collagen; platelet activation (Gq/TXA2/ADP) → integrin αIIbβ3 conformational change → fibrinogen bridging → aggregation. Secondary: tissue factor → VIIa → IXa/Xa → IIa (thrombin) → fibrin. Thrombin also positive-feedback activates V, VIII, XI and platelets. XIIIa cross-links fibrin. Modern \"cell-based model\" emphasizes platelet-surface localization.",
        tags: ["platelet", "thrombin", "vWF"],
      },
      {
        name: "Anticoagulant pathways and fibrinolysis",
        description: "Endogenous brakes (AT-III, protein C/S, TFPI) plus the plasmin system limit and resolve clots.",
        keyFact: "Antithrombin III: inhibits IIa and Xa (heparin potentiates ∼1000×). Protein C, activated by thrombomodulin-thrombin, cleaves Va and VIIIa (cofactor: protein S). TFPI binds Xa-VIIa-TF. Fibrinolysis: tPA → plasmin → fibrin degradation (D-dimer). Factor V Leiden: APC-resistant Va → hypercoagulability. tPA used in acute ischemic stroke and STEMI within tight windows.",
        tags: ["protein C", "fibrinolysis", "tPA"],
        xref: ["medicine"],
      },
      {
        name: "Leukocytes and hematopoiesis",
        description: "All blood cells derive from HSCs through lineage-specific cytokine signaling.",
        keyFact: "HSC → common myeloid vs. common lymphoid progenitors. G-CSF (neutrophils), M-CSF (monocytes), GM-CSF (broad), EPO (RBC), TPO (platelets), IL-7 (lymphoid). Neutrophil half-life ∼6 h in blood; resident macrophages can live years. CXCR4-CXCL12 retains HSCs in marrow; G-CSF disrupts this (basis of stem-cell mobilization for transplant).",
        tags: ["HSC", "G-CSF", "CXCR4"],
      },
    ],
  },

  // ── Family 17 ─────────────────────────────────────────────────────────────
  {
    slug: "integrative-homeostasis",
    number: 17,
    name: "Integrative Physiology & Homeostasis",
    blurb: "Cross-system regulation — thermoregulation, exercise, fluid balance, and circadian control.",
    section: "E",
    color: "cyan",
    systems: ["cellular"],
    entries: [
      {
        name: "Homeostasis (the unifying principle)",
        description: "Closed-loop negative feedback maintains regulated variables within narrow set-point ranges.",
        keyFact: "Sensor → integrator → effector → controlled variable → feedback. Gain = ∆correction / ∆disturbance; high-gain systems (core temperature, pH) tightly regulated. Allostasis: stability through change — set points adjust with anticipated load (e.g., circadian, exercise). Bernard's milieu intérieur (1865); Cannon's coining of \"homeostasis\" (1929).",
        researcher: "Claude Bernard / Walter Cannon",
        tags: ["homeostasis", "feedback", "allostasis"],
        status: "landmark",
      },
      {
        name: "Thermoregulation",
        description: "Hypothalamic preoptic area integrates skin and core temperature signals to drive autonomic and behavioral effectors.",
        keyFact: "Heat dissipation: cutaneous vasodilation, sweating (sympathetic cholinergic — anatomical exception). Heat production: shivering thermogenesis (skeletal muscle), non-shivering (BAT via UCP1 — significant in neonates and rediscovered in adults). Fever: pyrogens → PGE2 → ↑set point. Heat stroke vs. exertional heat illness; malignant hyperthermia is a separate mechanism (RYR1).",
        tags: ["thermoreg", "UCP1", "fever"],
        xref: ["medicine"],
      },
      {
        name: "Exercise physiology",
        description: "Coordinated cardiovascular, respiratory, and metabolic adaptations to sustain ATP supply during work.",
        keyFact: "VO₂max = CO × (a-v O₂ difference); elite endurance ∼80 mL/kg/min vs. ∼40 sedentary. Lactate threshold (∼60% VO₂max untrained, ∼80% trained) marks onset of disproportionate blood lactate. Training adaptations: ↑LV mass and stroke volume (endurance), ↑mitochondrial density, ↑capillary:fiber ratio, ↑GLUT4. Resistance training: hypertrophy via mTORC1 activation; central adaptations early then peripheral.",
        formula: "\\dot{V}O_{2max} = CO \\times (CaO_2 - C\\bar{v}O_2)",
        tags: ["VO2max", "lactate", "training"],
        xref: ["medicine"],
      },
      {
        name: "Body fluid compartments",
        description: "Total body water (∼60% lean body mass) partitions into ICF (∼⅔) and ECF (∼⅓, with plasma vs. interstitial ∼1:3).",
        keyFact: "Indicator dilution: TBW (D₂O), ECF (inulin, mannitol), plasma (Evans blue/albumin). Osmolarity equal across cell membranes (water freely permeable) but tonicity and ionic composition differ markedly — Na⁺-dominant ECF, K⁺-dominant ICF, set by Na⁺/K⁺-ATPase. Hypertonic saline shrinks cells (used in cerebral edema); free water shifts hyponatremia → cell swelling, seizures.",
        tags: ["TBW", "ECF", "tonicity"],
      },
      {
        name: "Circadian physiology",
        description: "A ∼24-h transcription-translation feedback loop in the SCN (and peripheral tissues) coordinates rhythms.",
        keyFact: "Core loop: CLOCK/BMAL1 activate Per/Cry → PER/CRY proteins inhibit CLOCK/BMAL1 → degraded → restart. Light entrains SCN via ipRGCs (melanopsin) → RHT → SCN. Peripheral clocks in liver, adipose, muscle entrained by feeding/temperature. Misalignment (shift work, jet lag, late-night eating) is associated with metabolic disease and cancer risk.",
        researcher: "Hall, Rosbash, Young (Nobel 2017)",
        tags: ["SCN", "CLOCK", "circadian"],
        xref: ["neuroscience"],
        status: "landmark",
      },
      {
        name: "Autonomic nervous system overview",
        description: "Sympathetic (thoracolumbar) and parasympathetic (craniosacral) divisions tonically and reciprocally control viscera.",
        keyFact: "All preganglionic: ACh on nicotinic. Sympathetic postganglionic: mostly NE on α/β (exception: sweat glands ACh on muscarinic). Parasympathetic postganglionic: ACh on muscarinic. Adrenal medulla = modified sympathetic ganglion → epi (∼80%) + NE. Tonic sympathetic and parasympathetic outflow set baseline HR, BP, GI motility. Heart-rate variability is a window into autonomic balance.",
        tags: ["ANS", "sympathetic", "parasympathetic"],
        xref: ["neuroscience"],
      },
    ],
  },

  // ── Family 18 ─────────────────────────────────────────────────────────────
  {
    slug: "frontiers-pathophysiology",
    number: 18,
    name: "Frontiers, Aging & Pathophysiology",
    blurb: "Open questions and the systems-level breakdowns of disease — aging, regeneration, organoids, and beyond.",
    section: "E",
    color: "violet",
    systems: ["cellular"],
    entries: [
      {
        name: "Cellular senescence and aging",
        description: "Cells permanently exit cell cycle while remaining metabolically active and pro-inflammatory (SASP).",
        keyFact: "Triggers: telomere shortening (Hayflick limit), DNA damage, oxidative stress, oncogene activation. p16^INK4a and p21 stabilize arrest. SASP (IL-6, IL-8, MMPs) drives tissue dysfunction. Senolytics (dasatinib + quercetin, navitoclax) clear senescent cells in preclinical models and early human trials. Whether net effect on healthspan/lifespan in humans matches mouse data is still open.",
        researcher: "Hayflick (1961); van Deursen (senolytics)",
        tags: ["senescence", "SASP", "senolytics"],
        status: "open",
      },
      {
        name: "Stem cells and regeneration",
        description: "Adult stem cells in niches replenish high-turnover tissues; most organs regenerate poorly.",
        keyFact: "Intestinal crypt Lgr5⁺ cells, hematopoietic HSCs, skin basal cells, satellite cells (muscle) — well-defined niches. CNS regeneration limited (subgranular and subventricular zones produce neurons throughout life — human adult hippocampal neurogenesis remains CONTESTED). Yamanaka factors (OCT4, SOX2, KLF4, c-MYC) reprogram somatic cells to iPSCs.",
        researcher: "Yamanaka (Nobel 2012)",
        tags: ["stem cells", "iPSC", "regeneration"],
        status: "contested",
        xref: ["neuroscience"],
      },
      {
        name: "Organoids and physiological models",
        description: "Self-organizing 3D mini-organs from stem cells recapitulate tissue architecture and function.",
        keyFact: "Intestinal, brain, kidney, liver, retinal organoids reproducibly grown. Used to model CFTR (CF rectal organoids predict drug response), study Zika microcephaly, screen drugs. Limitations: vascularization, immune component, mature differentiation. Organ-on-chip and assembloid (multi-organoid fusion) approaches address some gaps. Not a substitute for in vivo systems yet.",
        tags: ["organoid", "iPSC", "organ-on-chip"],
        xref: ["medicine"],
      },
      {
        name: "Pathophysiology of shock",
        description: "Shock = inadequate tissue perfusion despite cardiovascular compensation; classified by hemodynamic profile.",
        keyFact: "Hypovolemic: ↓preload (hemorrhage, dehydration) — ↓CO, ↑SVR. Cardiogenic: pump failure — ↓CO, ↑SVR, ↑PCWP. Distributive (sepsis, anaphylaxis): vasodilation — ↓SVR, ↑CO initially. Obstructive (PE, tamponade, tension PTX): mechanical block. Common endpoint: cellular hypoxia → anaerobic metabolism → lactic acidosis → multi-organ failure. Early goal-directed therapy debate (Rivers 2001 vs. ProCESS/ARISE/ProMISe) reshaped sepsis care.",
        tags: ["shock", "sepsis", "MODS"],
        xref: ["medicine"],
        status: "contested",
      },
      {
        name: "Brain-body axes (gut-brain, immune-brain)",
        description: "Bidirectional vagal, neuroendocrine, and immune signaling between viscera and CNS.",
        keyFact: "Vagal afferents carry visceral information to NTS; cholinergic anti-inflammatory pathway (Tracey) suppresses cytokine release via α7-nAChR on splenic macrophages. Sickness behavior driven by IL-1β, TNF acting on circumventricular organs and vagal afferents. Microbiome-derived SCFAs, tryptophan metabolites, vagal signaling all proposed as gut-brain mediators — causal contributions to depression/anxiety remain CONTESTED.",
        researcher: "Kevin Tracey",
        tags: ["vagal", "neuroimmune", "gut-brain"],
        status: "contested",
        xref: ["neuroscience"],
      },
      {
        name: "Personalized physiology and -omics",
        description: "Wearables, continuous biomarker monitoring, and multi-omics promise individualized baselines and early disease detection.",
        keyFact: "Continuous glucose monitors reveal substantial inter-individual postprandial variability (PREDICT, Personalized Nutrition studies). Wearable HRV and overnight HR drop track cardiometabolic risk and overtraining. Proteomic aging clocks (∼200 plasma proteins) predict mortality independent of chronological age. Clinical translation lags: most associations modest, replication mixed, and behavioral change from measurement remains the bottleneck.",
        tags: ["wearables", "omics", "personalized"],
        xref: ["medicine"],
        status: "open",
      },
      {
        name: "The hard problems of physiology",
        description: "Open frontier questions where mechanism is unsettled.",
        keyFact: "How is body weight set point defended? Why does adult human cardiac and CNS regeneration fail? What sets species-specific lifespan within ∼50× range? How do many drugs act with no clear molecular target (e.g., general anesthetics, lithium)? Can we measure tissue ages non-invasively? These are physiology's analogues of consciousness in neuroscience.",
        tags: ["open problems", "frontiers"],
        status: "open",
      },
    ],
  },
];
