import type { Family } from "./types";

export const FAMILIES_1_6: Family[] = [
  // ── Family 1 ──────────────────────────────────────────────────────────────
  {
    slug: "membrane-biophysics",
    number: 1,
    name: "Membrane Biophysics",
    blurb: "The physical properties of cell membranes — lipid bilayers, membrane potential, and the driving forces for ion movement.",
    section: "A",
    color: "violet",
    systems: ["cellular"],
    entries: [
      {
        name: "Fluid mosaic model",
        description: "Proteins embedded in or attached to a sea of phospholipids; both laterally mobile.",
        keyFact: "Singer & Nicolson (1972) proposed that the membrane is a two-dimensional fluid: integral proteins float in a phospholipid bilayer with rapid lateral diffusion (~1 µm²/s) but very slow transverse flip-flop. Replaced the unit-membrane model.",
        researcher: "S.J. Singer & G.L. Nicolson",
        tags: ["membrane", "lipid", "protein"],
        xref: ["biology"],
        status: "landmark",
      },
      {
        name: "Phospholipid bilayer",
        description: "Amphipathic phospholipids self-assemble into a 7–8 nm thick bilayer; the universal basis of biological membranes.",
        keyFact: "Hydrophobic tails sequester inward; hydrophilic heads face aqueous phases. Cholesterol intercalates between tails, modulating fluidity and forming liquid-ordered phases. Outer leaflet is enriched in phosphatidylcholine and sphingomyelin; inner in phosphatidylserine and phosphatidylethanolamine.",
        tags: ["lipid", "structure"],
        xref: ["chemistry"],
      },
      {
        name: "Nernst equation",
        description: "Calculates the equilibrium (reversal) potential for a single ion species.",
        keyFact: "At 37 °C: $E_X = \\frac{61}{z}\\log\\frac{[X]_o}{[X]_i}$ mV. For K⁺ (z = +1, [K]_i ≈ 140 mM, [K]_o ≈ 5 mM): $E_K ≈ -90$ mV. For Na⁺: $E_{Na} ≈ +60$ mV. For Cl⁻: $E_{Cl} ≈ -70$ mV. At equilibrium, the Nernst potential exactly opposes the concentration gradient; no net flux occurs.",
        formula: "E_X = \\frac{RT}{zF}\\ln\\frac{[X]_o}{[X]_i}",
        researcher: "Walther Nernst",
        tags: ["equation", "electrochemistry"],
        status: "landmark",
      },
      {
        name: "Goldman-Hodgkin-Katz (GHK) equation",
        description: "Predicts resting membrane potential when multiple permeable ions coexist.",
        keyFact: "Accounts for relative permeabilities (P_Na, P_K, P_Cl) and ion concentrations. At rest, P_K >> P_Na: V_m ≈ −70 mV in neurons, −90 mV in skeletal muscle. GHK supersedes simple Nernst for multi-ion systems; during an action potential P_Na transiently dominates, shifting V_m toward E_Na.",
        formula: "V_m = \\frac{RT}{F}\\ln\\frac{P_K[K]_o + P_{Na}[Na]_o + P_{Cl}[Cl]_i}{P_K[K]_i + P_{Na}[Na]_i + P_{Cl}[Cl]_o}",
        researcher: "David Goldman / Alan Hodgkin / Bernard Katz",
        tags: ["equation", "resting potential"],
      },
      {
        name: "Electrochemical gradient",
        description: "The combined driving force on an ion — chemical concentration gradient plus electrical potential difference.",
        keyFact: "The electrochemical potential for ion X is $\\mu_X = RT\\ln[X] + zFV_m$. Net ion flux is zero only when $V_m = E_X$ (the Nernst potential). Inward electrochemical gradient for Na⁺ at rest (~−140 mV total driving force) powers secondary active transport and action potential depolarization.",
        tags: ["thermodynamics", "driving force"],
        xref: ["physics"],
      },
      {
        name: "Membrane capacitance",
        description: "The cell membrane stores charge like a parallel-plate capacitor; determines how quickly voltage changes.",
        keyFact: "Specific membrane capacitance $C_m \\approx 1$ µF/cm². Small cells can be voltage-clamped rapidly; large cells and myelinated axons (thicker insulation = lower C_m per unit length) respond faster. $\\tau_m = R_m C_m$ sets the time constant for passive voltage changes.",
        formula: "\\tau_m = R_m C_m",
        tags: ["biophysics", "capacitance"],
        xref: ["physics"],
      },
      {
        name: "Space constant (λ)",
        description: "The distance over which a subthreshold voltage signal decays to 1/e of its original amplitude.",
        keyFact: "$\\lambda = \\sqrt{r_m / r_i}$ where $r_m$ is membrane resistance and $r_i$ is axial resistance per unit length. Large-diameter, myelinated axons have large λ (electrotonic signals spread further). Dendrite geometry shapes synaptic integration: distal inputs attenuate severely.",
        formula: "\\lambda = \\sqrt{r_m / r_i}",
        tags: ["electrotonic", "cable theory"],
      },
      {
        name: "Osmosis and osmotic pressure",
        description: "Net movement of water across a semipermeable membrane toward higher solute concentration.",
        keyFact: "Osmotic pressure $\\pi = iMRT$ (van't Hoff equation). Normal plasma osmolarity ≈ 290 mOsm/kg. Tonicity (effective osmolarity) determines cell volume: hypertonicity → cell shrinkage, hypotonicity → swelling. Urea is an 'ineffective' osmole because it equilibrates across cell membranes.",
        formula: "\\pi = iMRT",
        tags: ["osmosis", "fluid balance"],
        xref: ["chemistry"],
      },
      {
        name: "Membrane asymmetry & flippases",
        description: "Different phospholipid species reside on opposite leaflets; asymmetry is maintained by ATP-dependent flippases.",
        keyFact: "Flippases (P4-ATPases) move PS and PE inward; scramblases disrupt asymmetry during apoptosis, exposing PS externally (an 'eat-me' signal). Sphingomyelin and PC predominate in the outer leaflet. Asymmetry is essential for platelet activation and cell signaling.",
        tags: ["lipid", "apoptosis"],
        xref: ["biology"],
      },
      {
        name: "Lipid rafts",
        description: "Cholesterol- and sphingolipid-enriched microdomains that cluster specific proteins and receptors.",
        keyFact: "Operationally defined as detergent-resistant membranes; existence in living cells remains debated. Proposed to concentrate GPCRs, GPI-anchored proteins, and signaling molecules (Src kinases). Disruption by methyl-β-cyclodextrin (cholesterol extraction) impairs signaling cascades.",
        tags: ["lipid", "signaling"],
        status: "contested",
      },
      {
        name: "Donnan equilibrium",
        description: "Ion distribution across a membrane with fixed, impermeable charges.",
        keyFact: "Fixed negative charges (proteins, proteoglycans) inside cells cause intracellular concentrations of diffusible cations to exceed extracellular, and anion concentrations to be lower. The Donnan potential contributes a few mV to resting membrane potential and causes cells to accumulate water unless counteracted by the Na+/K+-ATPase.",
        tags: ["electrochemistry", "cell volume"],
      },
      {
        name: "Gibbs-Donnan effect on cell volume",
        description: "Tendency of cells to swell due to fixed intracellular anions; counteracted by active ion pumping.",
        keyFact: "Fixed impermeant anions attract cations and water, threatening osmotic lysis. The Na+/K+-ATPase continuously pumps out Na⁺ (effectively reducing intracellular osmolarity), counterbalancing the Donnan swelling tendency. Poisoning the pump causes cells to swell rapidly.",
        tags: ["volume regulation", "pump"],
      },
    ],
  },

  // ── Family 2 ──────────────────────────────────────────────────────────────
  {
    slug: "ion-channels-transporters",
    number: 2,
    name: "Ion Channels & Transporters",
    blurb: "Proteins that allow ions and molecules to cross the lipid bilayer — from voltage-gated channels to ATP-powered pumps.",
    section: "A",
    color: "indigo",
    systems: ["cellular", "nervous", "cardiovascular"],
    entries: [
      {
        name: "Voltage-gated Na⁺ channel",
        description: "Opens upon depolarization; responsible for the upstroke of action potentials in neurons and muscle.",
        keyFact: "Hodgkin & Huxley's m³h model (1952): activation gate (m) opens in ~0.1 ms; inactivation gate (h) closes in ~1 ms. Nine isoforms (Nav1.1–Nav1.9): Nav1.4 in skeletal muscle, Nav1.5 in heart, Nav1.7 in nociceptors. Tetrodotoxin (TTX) blocks fish-origin channels; local anesthetics bind the pore from inside.",
        researcher: "Alan Hodgkin & Andrew Huxley",
        tags: ["channel", "action potential", "Nav"],
        xref: ["neuroscience"],
        status: "landmark",
      },
      {
        name: "Voltage-gated K⁺ channel",
        description: "Delayed rectifier; opens after Na⁺ channels to repolarize the membrane.",
        keyFact: "Selectivity filter (TVGYG sequence) discriminates K⁺ over Na⁺ by ~1000:1 via coordination in a dehydrated pore (MacKinnon Nobel 2003). Kv11.1 (hERG) channels are critical for cardiac repolarization; block by drugs causes long-QT syndrome. Kir channels (inward rectifiers) stabilize resting potential.",
        researcher: "Roderick MacKinnon",
        tags: ["channel", "repolarization", "Kv"],
        xref: ["neuroscience"],
        status: "landmark",
      },
      {
        name: "Voltage-gated Ca²⁺ channel",
        description: "Couples membrane depolarization to intracellular calcium signaling.",
        keyFact: "L-type (Cav1.2/1.3): slow-inactivating; cardiac and smooth muscle E-C coupling, β-cell insulin secretion. T-type (Cav3.x): low-threshold; pacemaker activity in SA/AV nodes. N-type (Cav2.2) and P/Q-type (Cav2.1): neuronal presynaptic terminals; neurotransmitter release. Dihydropyridines (nifedipine) block L-type.",
        tags: ["channel", "calcium", "Cav"],
        xref: ["neuroscience"],
      },
      {
        name: "Ligand-gated ion channels (ionotropic receptors)",
        description: "Receptor and ion channel in a single protein complex; fast (millisecond) synaptic signaling.",
        keyFact: "Pentameric Cys-loop superfamily: nicotinic ACh receptor (nAChR), GABA_A, glycine, 5-HT₃. Tetrameric glutamate receptors: AMPA, NMDA, kainate. Binding of neurotransmitter causes rapid conformational change → pore opening. Patch clamp reveals unitary conductances of 10–150 pS.",
        tags: ["channel", "receptor", "synapse"],
        xref: ["neuroscience"],
      },
      {
        name: "Na⁺/K⁺-ATPase (sodium-potassium pump)",
        description: "Primary active transporter that maintains the steep Na⁺ and K⁺ gradients essential for excitability.",
        keyFact: "Stoichiometry: 3 Na⁺ out / 2 K⁺ in per ATP hydrolyzed; electrogenic (net −1 charge outward). Maintains [Na⁺]_i ≈ 10 mM, [K⁺]_o ≈ 5 mM. Accounts for 20–40% of resting ATP consumption. Cardiac glycosides (ouabain, digoxin) inhibit by trapping the E2-P state; secondarily increase intracellular Ca²⁺ via NCX.",
        tags: ["pump", "ATPase", "active transport"],
        xref: ["chemistry"],
        status: "landmark",
      },
      {
        name: "Na⁺/Ca²⁺ exchanger (NCX)",
        description: "Electrogenic antiporter coupling Na⁺ influx to Ca²⁺ efflux; pivotal for cardiac Ca²⁺ homeostasis.",
        keyFact: "3 Na⁺ in : 1 Ca²⁺ out (under normal conditions); driven by Na⁺ gradient. At normal V_m and [Na⁺]_i, NCX operates in forward mode (Ca²⁺ extrusion). During early depolarization or elevated [Na⁺]_i (e.g., Na⁺ channel burst, digoxin), NCX reverses, loading Ca²⁺. Key mechanism of digitalis inotropy.",
        tags: ["exchanger", "calcium", "cardiac"],
        xref: ["medicine"],
      },
      {
        name: "SERCA pump",
        description: "Sarco-endoplasmic reticulum Ca²⁺-ATPase; resequesters Ca²⁺ into the SR/ER after each contraction.",
        keyFact: "SERCA2a is the cardiac isoform; regulated by phospholamban (PLB). Unphosphorylated PLB inhibits SERCA; β-adrenergic stimulation → PKA phosphorylation of PLB → disinhibition → faster Ca²⁺ reuptake → accelerated relaxation (lusitropy). SERCA2a gene therapy is under investigation for heart failure.",
        tags: ["pump", "calcium", "SR"],
        xref: ["medicine"],
      },
      {
        name: "Aquaporins",
        description: "Protein water channels that vastly accelerate osmotic water flux across cell membranes.",
        keyFact: "Peter Agre (Nobel 2003) discovered AQP1. AQP2 in collecting duct principal cells is regulated by ADH (vasopressin): PKA phosphorylates AQP2 → vesicle insertion into apical membrane → water permeability ↑ 10–100-fold. Mutations in AQP2 or V2 receptor → nephrogenic diabetes insipidus.",
        researcher: "Peter Agre",
        tags: ["channel", "water", "kidney"],
        xref: ["medicine"],
        status: "landmark",
      },
      {
        name: "KATP channel",
        description: "ATP-sensitive K⁺ channel linking metabolic state to membrane excitability.",
        keyFact: "Opens when intracellular [ATP] falls (e.g., hypoxia, fasting); inhibited by ATP (Kir6 subunit) and modulated by sulfonylurea receptor (SUR). In pancreatic β-cells: glucose↑ → ATP↑ → channel closes → depolarization → Ca²⁺ entry → insulin secretion. Sulfonylureas (glibenclamide) close KATP → insulin release in T2D treatment.",
        tags: ["channel", "metabolism", "pancreas"],
        xref: ["medicine"],
      },
      {
        name: "Cotransporters (SGLT, NKCC, NCC)",
        description: "Secondary active transporters that use the Na⁺ gradient to drive uphill co-transport of other solutes.",
        keyFact: "SGLT1/2: Na⁺-glucose cotransport in intestine and renal PCT (electrogenic, 2:1). SGLT2 inhibitors (gliflozins) block renal glucose reabsorption → glycosuria. NKCC2 in loop of Henle thick ascending limb: 1Na⁺:1K⁺:2Cl⁻ — target of loop diuretics (furosemide). NCC in distal tubule: target of thiazide diuretics.",
        tags: ["cotransporter", "kidney", "diabetes"],
        xref: ["medicine"],
      },
      {
        name: "Gap junctions",
        description: "Intercellular channels formed by paired connexon hemichannels; allow direct electrical and metabolic coupling.",
        keyFact: "Each connexon is a hexamer of connexins; two hemichannels dock at the intercalated disc. Unitary conductance 20–300 pS; passes molecules <1 kDa (ions, cAMP, IP3). Connexin 43 (Cx43) is the predominant cardiac isoform; its genetic loss causes arrhythmia. Pharmacological uncoupling (carbenoxolone) dissects cell-to-cell signaling.",
        tags: ["junction", "coupling", "cardiac"],
        xref: ["neuroscience"],
      },
      {
        name: "Mechanosensitive channels (Piezo1/2)",
        description: "Ion channels gated by membrane tension or mechanical force; convert physical stimuli into ionic currents.",
        keyFact: "Patapoutian (Nobel 2021) identified Piezo1 and Piezo2. Piezo2 is the principal mechanotransducer for touch and proprioception in dorsal root ganglia. Piezo1 in red blood cells mediates volume regulation and dehydration in hereditary xerocytosis. Both are large (~2500 aa), trimeric, with 38 transmembrane blades.",
        researcher: "Ardem Patapoutian",
        tags: ["mechanosensation", "touch", "proprioception"],
        xref: ["neuroscience"],
        status: "landmark",
      },
      {
        name: "Chloride channels (CFTR)",
        description: "CFTR is a cAMP-regulated Cl⁻ channel in epithelial cells; its loss of function causes cystic fibrosis.",
        keyFact: "CFTR is both an ion channel (Cl⁻) and a regulator of other channels. The most common mutation, ΔF508, causes misfolding → ER retention. CFTR modulators: ivacaftor (potentiator), lumacaftor/tezacaftor/elexacaftor (correctors) dramatically improve lung function in CF. Structurally, CFTR is an ABC transporter fold repurposed as a channel.",
        tags: ["channel", "chloride", "cystic fibrosis"],
        xref: ["medicine"],
      },
    ],
  },

  // ── Family 3 ──────────────────────────────────────────────────────────────
  {
    slug: "signal-transduction",
    number: 3,
    name: "Signal Transduction",
    blurb: "How cells convert extracellular signals — hormones, neurotransmitters, growth factors — into intracellular responses.",
    section: "A",
    color: "blue",
    systems: ["cellular", "endocrine", "nervous"],
    entries: [
      {
        name: "G protein-coupled receptors (GPCRs)",
        description: "Seven-transmembrane receptors; the largest receptor superfamily; signal through heterotrimeric G proteins.",
        keyFact: "~800 human GPCRs; ~35% of current drug targets. Activated receptor catalyzes GTP↔GDP exchange on Gα, dissociating Gβγ. Gs → adenylyl cyclase → cAMP↑; Gi → AC inhibition; Gq → PLCβ → IP3+DAG. β-arrestin recruitment → internalization and GPCR kinase (GRK) phosphorylation → desensitization. Biased agonism targets either G-protein or β-arrestin arm selectively.",
        tags: ["GPCR", "receptor", "signaling"],
        xref: ["chemistry"],
        status: "landmark",
      },
      {
        name: "cAMP-PKA signaling pathway",
        description: "Gs-linked second messenger cascade; mediates adrenaline and glucagon responses.",
        keyFact: "Gs → adenylyl cyclase → cAMP → PKA (regulatory subunit dissociation) → substrate phosphorylation. Targets: glycogen phosphorylase kinase (glycogenolysis), CREB (transcription), L-type Ca²⁺ channel (cardiac inotropy), troponin I (lusitropy). Phosphodiesterases (PDE3/4) degrade cAMP; milrinone (PDE3 inhibitor) used in heart failure.",
        tags: ["cAMP", "PKA", "second messenger"],
        xref: ["chemistry"],
      },
      {
        name: "IP3/DAG signaling pathway",
        description: "Gq-linked pathway generating two second messengers: IP3 triggers Ca²⁺ release; DAG activates PKC.",
        keyFact: "Gq → PLCβ cleaves PIP2 → IP3 + DAG. IP3 binds IP3R on ER/SR → Ca²⁺ release. DAG recruits PKC to the membrane → phosphorylation of diverse substrates. Ca²⁺ + DAG synergize on conventional PKC. Physiological examples: α1-adrenergic (vasoconstriction), muscarinic M1/M3 (smooth muscle), thrombin (platelet activation).",
        tags: ["IP3", "DAG", "calcium", "PKC"],
        xref: ["chemistry"],
      },
      {
        name: "Receptor tyrosine kinases (RTKs)",
        description: "Growth factor receptors that dimerize and autophosphorylate upon ligand binding; activate Ras-MAPK and PI3K-Akt.",
        keyFact: "Examples: EGFR, insulin receptor, PDGFR, VEGFR. Ligand → dimerization → transautophosphorylation of cytoplasmic tail → recruitment of SH2/PTB domain adaptors (Grb2, Shc) → Sos → Ras-GTP → MAPK cascade. Germline RTK mutations cause hereditary cancers; somatic mutations in EGFR drive lung adenocarcinoma (erlotinib target).",
        tags: ["RTK", "growth factor", "MAPK"],
        xref: ["medicine"],
      },
      {
        name: "MAPK/ERK cascade",
        description: "Three-tier kinase cascade (Raf → MEK → ERK); controls proliferation, differentiation, and survival.",
        keyFact: "Ras-GTP → Raf → MEK1/2 → ERK1/2 → nuclear translocation → transcription factors (Elk1, c-Fos). ERK also phosphorylates cytoplasmic substrates (RSK, MNK). Feedback: ERK phosphorylates Sos → attenuating Ras activation. BRAF V600E mutation drives ~50% of melanomas; vemurafenib targets it.",
        tags: ["MAPK", "ERK", "proliferation"],
        xref: ["medicine"],
      },
      {
        name: "PI3K-Akt-mTOR pathway",
        description: "Growth factor/nutrient-sensing pathway promoting cell survival, growth, and metabolism.",
        keyFact: "RTK → PI3K → PIP3 → PDK1 → Akt phosphorylation. Akt phosphorylates: FOXO (survival), GSK3β (glycogen synthesis), TSC2 → mTORC1 activation → S6K/4EBP1 → protein synthesis. PTEN is the tumor-suppressor phosphatase that degrades PIP3; PTEN loss is the most common cancer event. Rapamycin (sirolimus) inhibits mTORC1.",
        tags: ["PI3K", "Akt", "mTOR", "growth"],
        xref: ["medicine"],
      },
      {
        name: "JAK-STAT pathway",
        description: "Cytokine and interferon signaling through Janus kinases and signal transducers and activators of transcription.",
        keyFact: "Cytokine → receptor oligomerization → JAK transphosphorylation → STAT phosphorylation → STAT dimerization → nuclear translocation → target gene expression (SOCS, IRF). JAK1/2 inhibitors (ruxolitinib, baricitinib) used in myelofibrosis, rheumatoid arthritis, and COVID-19. IFN-γ → JAK1/JAK2 → STAT1 → antiviral and antitumor immunity.",
        tags: ["JAK", "STAT", "cytokine", "interferon"],
        xref: ["medicine"],
      },
      {
        name: "Nuclear hormone receptors",
        description: "Intracellular receptors for steroid and thyroid hormones; directly regulate gene transcription.",
        keyFact: "Lipid-soluble ligands cross the membrane → bind receptor in cytosol or nucleus → conformational change → dimerization → binding to hormone response elements (HREs) → co-activator recruitment → transcription. Type I (steroid): cytoplasmic/heat-shock-associated (GR, AR, ER, PR, MR). Type II (thyroid/retinoid): nuclear, bind as heterodimers with RXR. Response latency: minutes to hours.",
        tags: ["nuclear receptor", "steroid", "transcription"],
        xref: ["chemistry"],
      },
      {
        name: "Calcium as second messenger",
        description: "Free intracellular [Ca²⁺] is kept ~100 nM at rest; transient rises to 1–10 µM trigger diverse responses.",
        keyFact: "Sources: IP3R and RyR on SR/ER; VGCC from extracellular. Calmodulin (CaM) is the major Ca²⁺ sensor: Ca²⁺ binding → CaM conformational change → CaM-kinase II (synaptic plasticity), calcineurin (NFAT dephosphorylation → T-cell activation), MLCK (smooth muscle contraction). Oscillatory Ca²⁺ signals encode frequency information.",
        tags: ["calcium", "calmodulin", "signaling"],
        xref: ["neuroscience"],
      },
      {
        name: "NO/cGMP signaling",
        description: "Nitric oxide diffuses to adjacent cells and activates soluble guanylyl cyclase; mediates vasodilation and neuronal signaling.",
        keyFact: "Endothelial NOS (eNOS): shear stress or ACh → Ca²⁺/CaM → L-arginine oxidation → NO + citrulline. NO → soluble guanylyl cyclase → cGMP → PKG → myosin light-chain phosphatase activation → smooth muscle relaxation. PDE5 inhibitors (sildenafil, tadalafil) amplify cGMP in corpus cavernosum and pulmonary vasculature.",
        researcher: "Robert Furchgott / Louis Ignarro / Ferid Murad",
        tags: ["NO", "cGMP", "vasodilation"],
        xref: ["medicine"],
        status: "landmark",
      },
      {
        name: "Receptor desensitization and internalization",
        description: "Sustained receptor activation triggers phosphorylation and internalization, attenuating signaling — the basis of tachyphylaxis.",
        keyFact: "GRKs phosphorylate the active receptor → β-arrestin recruitment → clathrin-coated pit internalization (β2AR endocytosis in seconds to minutes). Internalized receptors are either recycled (resensitization) or degraded (downregulation). Opioid tolerance and rebound involve receptor desensitization and upregulation of adenylyl cyclase.",
        tags: ["receptor", "desensitization", "tolerance"],
      },
      {
        name: "Wnt/β-catenin signaling",
        description: "Developmental pathway controlling cell fate, proliferation, and tissue homeostasis.",
        keyFact: "Without Wnt: destruction complex (APC, Axin, GSK3β, CK1) phosphorylates β-catenin → ubiquitin-proteasome degradation. Wnt binding → LRP5/6 + Frizzled → Dishevelled → destruction complex inhibition → β-catenin accumulates → nuclear entry → TCF/LEF → target gene activation (cyclin D1, c-Myc). APC mutations in ~80% of colorectal cancers.",
        tags: ["Wnt", "beta-catenin", "development"],
        xref: ["biology", "medicine"],
      },
    ],
  },

  // ── Family 4 ──────────────────────────────────────────────────────────────
  {
    slug: "cellular-energetics",
    number: 4,
    name: "Cellular Energetics & Metabolism",
    blurb: "How cells generate, store, and spend energy — from glycolysis to oxidative phosphorylation and metabolic sensing.",
    section: "A",
    color: "sky",
    systems: ["cellular"],
    entries: [
      {
        name: "ATP and the cell's energy currency",
        description: "Adenosine triphosphate is the universal intracellular energy carrier; its hydrolysis drives endergonic reactions.",
        keyFact: "Standard free energy of hydrolysis ΔG°' ≈ −30.5 kJ/mol; physiological ΔG ≈ −50 kJ/mol (given low ADP, Pi). Intracellular [ATP] ≈ 5 mM; [ADP] ≈ 0.1 mM; [AMP] ≈ 0.01 mM. Turnover: a resting human hydrolyzes ~40 kg of ATP/day. Creatine phosphate (PCr) acts as an immediate buffer (PCr + ADP → ATP + Cr), essential in muscle.",
        tags: ["ATP", "energy", "thermodynamics"],
        xref: ["chemistry"],
      },
      {
        name: "Glycolysis",
        description: "10-enzyme cytoplasmic pathway converting glucose to two pyruvate molecules; produces 2 ATP and 2 NADH net.",
        keyFact: "Rate-limiting enzyme: phosphofructokinase-1 (PFK-1), allosterically inhibited by ATP and citrate, activated by AMP and fructose-2,6-bisphosphate (F2,6BP; regulated by PFK-2 — itself regulated by insulin vs glucagon). Net yield per glucose: 2 pyruvate + 2 ATP + 2 NADH. Under anaerobic conditions, pyruvate → lactate (regenerates NAD⁺).",
        researcher: "Gustav Embden / Otto Meyerhof",
        tags: ["glycolysis", "glucose", "ATP"],
        xref: ["chemistry"],
        status: "landmark",
      },
      {
        name: "Citric acid cycle (TCA cycle / Krebs cycle)",
        description: "Eight-enzyme mitochondrial cycle oxidizing acetyl-CoA; generates NADH and FADH₂ for the ETC.",
        keyFact: "Per acetyl-CoA turn: 3 NADH + 1 FADH₂ + 1 GTP. Rate-limiting enzymes: isocitrate dehydrogenase (activated by ADP/Ca²⁺, inhibited by ATP/NADH) and α-ketoglutarate dehydrogenase. TCA intermediates are cataplerosed for biosynthesis (amino acids, heme, lipid). The cycle also runs in reverse (rTCA) in some archaea.",
        researcher: "Hans Krebs",
        tags: ["TCA", "Krebs", "mitochondria"],
        xref: ["chemistry"],
        status: "landmark",
      },
      {
        name: "Oxidative phosphorylation and chemiosmosis",
        description: "The electron transport chain generates a proton gradient that drives ATP synthesis via ATP synthase.",
        keyFact: "Peter Mitchell's chemiosmotic hypothesis (Nobel 1978): NADH/FADH₂ → Complexes I→IV → proton pumping → ΔΨ_m (~−180 mV) + ΔpH → proton flow through F₀F₁-ATP synthase → ATP synthesis. Yield: ~2.5 ATP/NADH, ~1.5 ATP/FADH₂; ~30–32 ATP per glucose overall. Uncouplers (DNP, UCP1 in BAT) dissipate the proton gradient as heat.",
        researcher: "Peter Mitchell",
        tags: ["OXPHOS", "ETC", "ATP synthase"],
        xref: ["chemistry"],
        status: "landmark",
      },
      {
        name: "Fatty acid oxidation (β-oxidation)",
        description: "Mitochondrial degradation of fatty acids to acetyl-CoA, generating large amounts of NADH and FADH₂.",
        keyFact: "Palmitoyl-CoA (16C) undergoes 7 cycles of β-oxidation → 8 acetyl-CoA + 7 NADH + 7 FADH₂. Net ATP yield ~129 per palmitate vs ~36 per glucose (energy density advantage). Rate-limited by carnitine shuttle (CPT1): inhibited by malonyl-CoA (signal of fed state). Defects in LCAD/VLCAD → hypoketotic hypoglycemia during fasting.",
        tags: ["beta-oxidation", "fatty acid", "lipid"],
        xref: ["chemistry"],
      },
      {
        name: "Gluconeogenesis",
        description: "Hepatic (and renal) synthesis of glucose from non-carbohydrate precursors during fasting; reverses several glycolytic steps.",
        keyFact: "Precursors: lactate (Cori cycle), alanine (alanine cycle from muscle), glycerol (from lipolysis), oxaloacetate. Unique enzymes bypassing glycolytic irreversible steps: pyruvate carboxylase, PEPCK, fructose-1,6-bisphosphatase, glucose-6-phosphatase. Stimulated by glucagon and cortisol; inhibited by insulin. Metformin inhibits complex I → reduces gluconeogenesis.",
        tags: ["gluconeogenesis", "liver", "fasting"],
        xref: ["medicine"],
      },
      {
        name: "Ketogenesis and ketone body utilization",
        description: "Hepatic production of ketone bodies (β-hydroxybutyrate, acetoacetate) from excess acetyl-CoA during fasting or diabetic ketoacidosis.",
        keyFact: "Stimulated when: fasting → low insulin → maximal lipolysis → hepatic β-oxidation exceeds TCA capacity → acetyl-CoA → HMG-CoA → acetoacetate / β-hydroxybutyrate. Brain can use ketones when glucose is scarce (>3 days fasting). DKA: insulin absence → uncontrolled ketogenesis → pH < 7.3. β-hydroxybutyrate is a HCAR2 agonist (anti-inflammatory).",
        tags: ["ketones", "fasting", "DKA"],
        xref: ["medicine"],
      },
      {
        name: "AMPK — the cellular energy sensor",
        description: "AMP-activated protein kinase senses the AMP/ATP ratio and switches cells from anabolic to catabolic programs.",
        keyFact: "AMP (or ADP) binding to γ-subunit → allosteric activation + prevention of dephosphorylation at Thr172. Upstream kinase: LKB1 (STK11; tumor suppressor). AMPK phosphorylates: ACC (malonyl-CoA↓ → FAO↑), HMGCR (sterol synthesis↓), TSC2 (mTORC1↓ → protein synthesis↓). Metformin activates AMPK (partly via complex I inhibition). Exercise is a potent AMPK activator.",
        tags: ["AMPK", "energy sensing", "mTOR"],
        xref: ["medicine"],
      },
      {
        name: "mTOR signaling",
        description: "A nutrient/growth-factor kinase complex that promotes anabolic processes and suppresses autophagy.",
        keyFact: "mTORC1 (rapamycin-sensitive): activated by amino acids (Rag GTPases), insulin/IGF-1 (PI3K-Akt), and energy (AMPK OFF). Promotes ribosome biogenesis (S6K1), mRNA translation (4EBP1 phosphorylation), lipid synthesis (SREBP1). Suppresses autophagy (ULK1 inhibition). mTORC2 (rapamycin-insensitive): Akt Ser473 phosphorylation. Constitutive mTOR activation in TSC, PTEN-loss tumors.",
        tags: ["mTOR", "anabolism", "autophagy"],
        xref: ["medicine"],
      },
      {
        name: "Reactive oxygen species (ROS) and redox signaling",
        description: "Partially reduced oxygen species generated by mitochondria and NADPH oxidase; toxic at high levels, signaling molecules at low levels.",
        keyFact: "Superoxide (O₂·⁻) → dismutation (SOD) → H₂O₂ → (Fenton reaction) → OH·. Antioxidant defenses: catalase, glutathione peroxidase (GPx), thioredoxin. Physiological ROS signaling: H₂O₂ oxidizes cysteine residues on PTPs, Cys-based redox switches. Mitochondrial ROS (complex I/III leakage) contribute to aging and ischemia-reperfusion injury.",
        tags: ["ROS", "oxidative stress", "antioxidant"],
        xref: ["biology"],
      },
      {
        name: "Warburg effect",
        description: "Cancer cells preferentially use aerobic glycolysis (glucose → lactate) even in the presence of oxygen.",
        keyFact: "Otto Warburg observed high glucose uptake and lactate production in tumors (1924). Explanation is not fully settled: may provide biosynthetic precursors (ribose, serine, glycine, acetyl-CoA), maintain redox balance, or result from oncogene-driven PKM2 expression. [¹⁸F]-FDG-PET exploits the Warburg effect for tumor imaging.",
        researcher: "Otto Warburg",
        tags: ["cancer metabolism", "glycolysis", "Warburg"],
        xref: ["medicine"],
        status: "contested",
      },
      {
        name: "Substrate cycles and metabolic flexibility",
        description: "Opposing pathways operating simultaneously (futile cycles) can generate heat and increase regulatory sensitivity.",
        keyFact: "The glucose-fructose-1,6-bisphosphate cycle (PFK + FBPase simultaneously active) allows fine-grained flux control at low ATP cost. Metabolic flexibility: the capacity to shift substrate oxidation from fat to glucose with feeding and exercise. Loss of metabolic flexibility (dominant fat oxidation even after carbohydrate meal) is a feature of insulin resistance.",
        tags: ["futile cycle", "metabolic flexibility", "insulin resistance"],
        xref: ["medicine"],
      },
    ],
  },

  // ── Family 5 ──────────────────────────────────────────────────────────────
  {
    slug: "neurophysiology-fundamentals",
    number: 5,
    name: "Neurophysiology Fundamentals",
    blurb: "The electrical language of the nervous system — action potentials, passive properties, and the autonomic division.",
    section: "B",
    color: "cyan",
    systems: ["nervous"],
    entries: [
      {
        name: "Action potential",
        description: "The all-or-none electrical signal propagated along axons; the fundamental unit of neural communication.",
        keyFact: "Threshold (~−55 mV in neurons) triggers a stereotyped sequence: Na⁺ channels open rapidly (depolarization to +40 mV), then inactivate; delayed K⁺ channels open (repolarization below rest) → afterhyperpolarization. Absolute refractory period: Na⁺ channels inactivated (~1 ms); relative refractory: higher threshold until K⁺ channels close. Frequency encodes stimulus intensity.",
        tags: ["action potential", "depolarization"],
        xref: ["neuroscience"],
        status: "landmark",
      },
      {
        name: "Hodgkin-Huxley model",
        description: "Quantitative mathematical model of the action potential in terms of voltage-gated conductances.",
        keyFact: "Using voltage clamp on the squid giant axon, Hodgkin & Huxley (1952) described Na⁺ conductance as g_Na = ĝ_Na·m³·h and K⁺ conductance as g_K = ĝ_K·n⁴. Their equations predicted action potential shape, propagation velocity, and refractory period with ~1% accuracy — a landmark in quantitative biology. Nobel Prize 1963.",
        researcher: "Alan Hodgkin & Andrew Huxley",
        tags: ["HH model", "voltage clamp", "quantitative"],
        xref: ["neuroscience"],
        status: "landmark",
      },
      {
        name: "Saltatory conduction",
        description: "In myelinated axons, action potentials 'jump' from node of Ranvier to node, dramatically increasing conduction velocity.",
        keyFact: "Myelin (from Schwann cells in PNS, oligodendrocytes in CNS) increases membrane resistance and decreases capacitance between nodes. Conduction velocity scales with axon diameter and myelination: Aα fibers (~20 µm, myelinated) ≈ 80–120 m/s; C fibers (0.2–1.5 µm, unmyelinated) ≈ 0.5–2 m/s. Multiple sclerosis: demyelination → conduction block or slowing.",
        tags: ["myelin", "conduction velocity", "nodes of Ranvier"],
        xref: ["neuroscience", "medicine"],
      },
      {
        name: "Patch clamp technique",
        description: "Single-channel and whole-cell recording method enabling direct measurement of membrane currents.",
        keyFact: "Neher & Sakmann (Nobel 1991) achieved gigohm seals with fire-polished pipettes, reducing noise to allow picoampere current resolution. Four configurations: cell-attached, whole-cell, inside-out, outside-out. Enabled the unitary conductance and gating kinetics of individual channels to be measured, revolutionizing membrane physiology.",
        researcher: "Erwin Neher & Bert Sakmann",
        tags: ["patch clamp", "electrophysiology", "technique"],
        xref: ["neuroscience"],
        status: "landmark",
      },
      {
        name: "Resting membrane potential",
        description: "The stable negative interior voltage of a cell at rest; set by selective permeabilities and active pumping.",
        keyFact: "Neurons: ~−70 mV; cardiac ventricular myocytes: ~−90 mV; red blood cells: ~−10 mV. Primarily governed by high K⁺ permeability (leak channels) pulling V_m toward E_K ≈ −90 mV, with a small Na⁺ permeability and the electrogenic Na⁺/K⁺-ATPase contribution (~−3 mV). Depolarizing agents (high extracellular K⁺) reduce excitability; hyperpolarizing agents increase threshold.",
        tags: ["resting potential", "K+ leak", "excitability"],
        xref: ["neuroscience"],
      },
      {
        name: "Autonomic nervous system",
        description: "The visceral motor system — sympathetic and parasympathetic divisions dually innervate most target organs.",
        keyFact: "Sympathetic (thoracolumbar, T1–L2): short pre-ganglionic, long post-ganglionic; NE on adrenergic receptors (α1: vasoconstriction; β1: cardiac; β2: bronchodilation). Parasympathetic (craniosacral, CN III/VII/IX/X + S2-4): long pre-ganglionic, short post-ganglionic; ACh on muscarinic receptors (M2: cardiac slowing; M3: glandular, smooth muscle). Adrenal medulla: chromaffin cells secrete Epi/NE directly into blood.",
        tags: ["ANS", "sympathetic", "parasympathetic"],
        xref: ["neuroscience"],
      },
      {
        name: "Accommodation and adaptation",
        description: "Reduced firing in response to sustained depolarization; neurons become less responsive to constant stimuli.",
        keyFact: "Accommodation: slow depolarization allows Na⁺ channels to inactivate before threshold is reached → fewer APs despite maintained depolarization. Spike frequency adaptation: repetitive firing → cumulative K⁺ channel activation and Na⁺ channel inactivation → firing rate decreases. Rapidly adapting (RA) vs slowly adapting (SA) mechanoreceptors encode different sensory features.",
        tags: ["accommodation", "adaptation", "firing rate"],
        xref: ["neuroscience"],
      },
      {
        name: "Nociception and pain physiology",
        description: "The transduction, conduction, and modulation of pain signals from periphery to cortex.",
        keyFact: "Nociceptors: free nerve endings; Aδ (myelinated, sharp/fast pain, ~15 m/s) and C fibres (unmyelinated, slow/burning, <2 m/s). Transducers: TRPV1 (capsaicin/heat), TRPA1 (cold/noxious), ASICs (acid), Piezo2 (mechano). Gate control theory (Melzack & Wall, 1965): large-diameter Aβ fibre activity can inhibit dorsal horn transmission (basis of TENS). Central sensitization → allodynia, hyperalgesia.",
        researcher: "Ronald Melzack & Patrick Wall",
        tags: ["pain", "nociception", "gate control"],
        xref: ["neuroscience", "medicine"],
      },
      {
        name: "Sensory receptor physiology",
        description: "Specialized receptors transduce specific energy forms into receptor potentials; encoding involves type, location, intensity, and duration.",
        keyFact: "Generator potential amplitude is graded (unlike AP); if threshold is reached, AP frequency encodes intensity (frequency coding). Labeled-line coding: each receptor type connects to specific brain areas. Mechanoreceptors (Meissner, Pacinian, Ruffini, Merkel) in skin encode vibration, pressure, texture, and sustained contact; differ in adaptation rate and receptive field size.",
        tags: ["sensory", "transduction", "receptor potential"],
        xref: ["neuroscience"],
      },
      {
        name: "Motor neuron and motor unit",
        description: "A single alpha motor neuron and all the muscle fibers it innervates; the fundamental unit of motor output.",
        keyFact: "Size principle (Henneman, 1965): motor units are recruited in order of increasing size (fatigue resistance → speed). Small type-S units (slow, fatigue-resistant) recruited first; type-FF (fast, fatigable) last. Motor unit size ranges from ~10 fibres (extra-ocular) to ~1000+ (gastrocnemius). Upper vs lower motor neuron lesions: UMN spasticity/Babinski; LMN flaccid/atrophy.",
        researcher: "Elwood Henneman",
        tags: ["motor unit", "size principle", "motor neuron"],
        xref: ["neuroscience"],
        status: "landmark",
      },
      {
        name: "Spinal reflex circuits",
        description: "Fixed, rapid sensorimotor loops within the spinal cord — the simplest level of motor control.",
        keyFact: "Monosynaptic stretch reflex (DTR): muscle stretch → Ia afferent → α-motor neuron → contraction of the same muscle; reciprocal inhibition via Ia interneurons of antagonist. Golgi tendon organ (Ib afferent) → interneuron → autogenic inhibition (prevents excessive force). Flexor withdrawal reflex crosses midline. These circuits are modulated by descending supraspinal pathways.",
        tags: ["reflex", "spinal cord", "stretch reflex"],
        xref: ["neuroscience"],
      },
      {
        name: "Proprioception and kinesthesia",
        description: "Sensing of body position and movement from muscle spindles, Golgi tendon organs, and joint receptors.",
        keyFact: "Muscle spindles (intrafusal fibres): Ia (annulospiral) sensitive to length and velocity; II afferents to length only. Gamma motor neurons set spindle sensitivity (fusimotor drive) — maintained during voluntary contraction. Piezo2 is the mechanosensor in Ia/II sensory neurons. DCML pathway to cortex (somatotopic map, S1 area 2). Proprioception loss (tabes dorsalis, large-fibre neuropathy) causes sensory ataxia.",
        tags: ["proprioception", "muscle spindle", "spindle"],
        xref: ["neuroscience"],
      },
    ],
  },

  // ── Family 6 ──────────────────────────────────────────────────────────────
  {
    slug: "synaptic-physiology",
    number: 6,
    name: "Synaptic Physiology",
    blurb: "Chemical and electrical communication between neurons — transmitter release, receptor activation, and synaptic plasticity.",
    section: "B",
    color: "teal",
    systems: ["nervous"],
    entries: [
      {
        name: "Chemical synaptic transmission",
        description: "The dominant mode of interneuronal communication: action potential triggers neurotransmitter release, which diffuses across the cleft to activate postsynaptic receptors.",
        keyFact: "AP → Ca²⁺ entry via Cav2.1/2.2 → SNARE-mediated vesicle fusion (VAMP/synaptobrevin + syntaxin + SNAP-25) → NT diffuses ~20 nm → ionotropic or metabotropic postsynaptic receptor. Total synaptic delay ≈ 0.5–1 ms. Clostridial toxins (botulinum: VAMP/SNAP-25; tetanus: VAMP) prevent fusion → paralysis.",
        tags: ["synapse", "SNARE", "neurotransmitter"],
        xref: ["neuroscience"],
        status: "landmark",
      },
      {
        name: "Quantal release and miniature potentials",
        description: "Neurotransmitter is released in discrete packets (quanta); spontaneous release produces miniature EPPs.",
        keyFact: "Katz & del Castillo (1954): end-plate potential amplitude fluctuates in integer multiples of the miniature EPP. Each quantum = one synaptic vesicle (~5000 ACh molecules). Quantal content m = n × p (n vesicles, p probability of release). Reduced n (Lambert-Eaton syndrome: Cav2.1 Ab) or p (Mg²⁺, low Ca²⁺) → reduced EPP.",
        researcher: "Bernard Katz & José del Castillo",
        tags: ["quantal", "mEPP", "vesicle"],
        xref: ["neuroscience"],
        status: "landmark",
      },
      {
        name: "EPSP summation and integration",
        description: "Individual EPSPs are subthreshold; spatial and temporal summation brings the neuron to firing threshold.",
        keyFact: "Spatial summation: simultaneous inputs from multiple synapses. Temporal summation: rapid succession of inputs within the membrane time constant. Dendritic computation: distal synapses are attenuated (low λ); active dendrites (NMDA spikes, Ca²⁺ spikes) can amplify. Inhibitory synapses control the I/E balance — shunting inhibition near the soma is most effective.",
        tags: ["summation", "integration", "EPSP"],
        xref: ["neuroscience"],
      },
      {
        name: "Glutamate receptors",
        description: "The major excitatory neurotransmitter in the CNS; activates ionotropic (AMPA, NMDA, kainate) and metabotropic (mGluR) receptors.",
        keyFact: "AMPA: fast (1–5 ms) Na⁺/K⁺; mediates basal excitatory transmission. NMDA: slow (50–150 ms); Ca²⁺-permeable; voltage-dependent Mg²⁺ block removed at depolarization; requires both presynaptic (glutamate) and postsynaptic (depolarization) activity simultaneously → coincidence detector. NMDAR antagonists (ketamine, memantine) are neuroprotective/anesthetic/antidepressant.",
        tags: ["glutamate", "AMPA", "NMDA"],
        xref: ["neuroscience"],
      },
      {
        name: "Long-term potentiation (LTP)",
        description: "Sustained strengthening of a synapse following high-frequency stimulation; the leading cellular model of learning.",
        keyFact: "Bliss & Lømo (1973): tetanic stimulation in hippocampus → persistent increase in EPP. Mechanism: NMDA Ca²⁺ entry → CaM-KII autophosphorylation → AMPAR phosphorylation and trafficking to synapse → larger EPSP (AMPA-silent synapses 'unsilenced'). LTP requires protein synthesis for late phase (L-LTP) and CREB-driven gene expression. Blocked by AP5 (NMDA antagonist).",
        researcher: "Timothy Bliss & Terje Lømo",
        tags: ["LTP", "memory", "plasticity"],
        xref: ["neuroscience"],
        status: "landmark",
      },
      {
        name: "Long-term depression (LTD)",
        description: "Persistent weakening of synaptic strength; complementary to LTP in allowing bidirectional modification of synapses.",
        keyFact: "Induced by low-frequency stimulation (1 Hz, 900 pulses) or cerebellar climbing fiber + parallel fiber co-activation. Mechanism (hippocampal): modest NMDAR Ca²⁺ entry → protein phosphatases (PP1/PP2B) → AMPAR dephosphorylation → internalization (GluA2 subunit endocytosis). Cerebellar LTD (mGluR + parallel fiber): PKC-mediated GluA2 phosphorylation → removal; underlies motor adaptation.",
        tags: ["LTD", "plasticity", "cerebellum"],
        xref: ["neuroscience"],
      },
      {
        name: "GABA and inhibitory transmission",
        description: "γ-Aminobutyric acid is the major inhibitory neurotransmitter in the brain; acts on ionotropic GABA_A and metabotropic GABA_B receptors.",
        keyFact: "GABA_A: Cl⁻-selective (Cys-loop); at [Cl⁻]_i below ECl (~−70 mV in mature neurons) → hyperpolarizing IPSP; at higher [Cl⁻]_i (immature neurons, perinatal) → depolarizing. GABA_B: GPCR; presynaptic (reduces NT release via Cav inhibition) and postsynaptic (Kir activation → hyperpolarization). Benzodiazepines: positive allosteric modulators of GABA_A; increase Cl⁻ channel frequency.",
        tags: ["GABA", "inhibition", "IPSP"],
        xref: ["neuroscience"],
      },
      {
        name: "Acetylcholine (ACh) and the neuromuscular junction",
        description: "The archetypal cholinergic synapse; ACh from the motor terminal activates nicotinic receptors on the end plate.",
        keyFact: "ACh stored in vesicles (~10,000/vesicle); released by Cav2.1 (P/Q-type) Ca²⁺. Nicotinic nAChR (α2βγδ/α2βεδ): cation channel; end-plate potential (EPP) is usually suprathreshold (~25 mV above rest). Acetylcholinesterase (AChE) in the basal lamina cleaves ACh within 1 ms. Myasthenia gravis: anti-nAChR (or anti-MuSK) Ab → reduced EPP amplitude → neuromuscular fatigue.",
        tags: ["NMJ", "ACh", "nicotinic"],
        xref: ["neuroscience", "medicine"],
        status: "landmark",
      },
      {
        name: "Presynaptic modulation",
        description: "Autoreceptors and heteroreceptors on presynaptic terminals regulate transmitter release through G-protein-coupled feedback.",
        keyFact: "Autoreceptors (e.g., α2-adrenergic, D2, mGluR2/3, GABA_B) sense released NT and limit further release. Heteroreceptors: different NT from nearby terminals modulates release (e.g., adenosine A1 on glutamate terminals → suppression). Gi/Go coupling → Cav2 inhibition (G-βγ), K-channel opening, and AC inhibition → reduced AP-evoked Ca²⁺ and vesicle fusion.",
        tags: ["autoreceptor", "presynaptic", "modulation"],
        xref: ["neuroscience"],
      },
      {
        name: "Short-term synaptic plasticity",
        description: "Use-dependent changes in synaptic strength over milliseconds to minutes — facilitation, depression, and augmentation.",
        keyFact: "Facilitation (paired-pulse): residual presynaptic Ca²⁺ after first AP → enhanced release from second AP (~200% at 20 ms interval). Synaptic depression: vesicle pool depletion at high firing rates. Augmentation/post-tetanic potentiation (PTP): prolonged residual Ca²⁺ or PKC activation. These short-term mechanisms allow synapses to act as high-pass or low-pass filters.",
        tags: ["STF", "STD", "plasticity"],
        xref: ["neuroscience"],
      },
      {
        name: "Neuromodulation",
        description: "Volume transmission by biogenic amines (dopamine, norepinephrine, serotonin, histamine) that modulate network excitability rather than fast point-to-point signaling.",
        keyFact: "Neuromodulators act primarily on GPCRs; effects are slow (seconds) and diffuse. DA: reward prediction error (mesolimbic), motor control (nigrostriatal), working memory (mesocortical). 5-HT: mood, appetite, sleep (raphe → widespread). NE: arousal, attention (locus coeruleus → cortex). Histamine: wakefulness (tuberomammillary nucleus). Most psychotropic drugs target neuromodulatory systems.",
        tags: ["dopamine", "serotonin", "norepinephrine", "neuromodulation"],
        xref: ["neuroscience"],
      },
      {
        name: "Endocannabinoid retrograde signaling",
        description: "Postsynaptic depolarization triggers synthesis and release of endocannabinoids that retrogradely inhibit presynaptic release.",
        keyFact: "2-AG (2-arachidonoylglycerol) is the main endocannabinoid; synthesized postsynaptically via DAG lipase in response to Ca²⁺ and mGluR1/5 activation. Acts on presynaptic CB1 receptors (Gi/Go) → reduced Cav2 Ca²⁺ entry → inhibition of GABA or glutamate release (DSI, depolarization-induced suppression of inhibition/excitation). Phytocannabinoid THC mimics endocannabinoids.",
        tags: ["endocannabinoid", "retrograde", "eCB"],
        xref: ["neuroscience"],
      },
    ],
  },
];
