import type { Family } from "./types";

export const FAMILIES_15_21: Family[] = [
  // ── Family 15 ─────────────────────────────────────────────────────────────
  {
    slug: "active-galactic-nuclei",
    number: 15,
    name: "Active Galactic Nuclei",
    blurb: "Quasars, blazars, Seyferts, radio galaxies — accretion onto supermassive black holes.",
    section: "D",
    color: "rose",
    entries: [
      {
        name: "Supermassive black holes",
        description: "Black holes of $10^6$–$10^{10}\\,M_\\odot$ at the centers of most massive galaxies.",
        keyFact: "Sgr A* ($4\\times10^6\\,M_\\odot$, Milky Way), M87* ($\\sim 6.5\\times 10^9\\,M_\\odot$), TON 618 ($\\sim 4\\times 10^{10}\\,M_\\odot$ — among the largest known). EHT has now imaged both nearest SMBHs (M87 2019, Sgr A* 2022).",
        tags: ["AGN", "SMBH"],
      },
      {
        name: "Accretion disk",
        description: "Geometrically thin, optically thick gas spiraling onto a black hole.",
        keyFact: "Shakura-Sunyaev $\\alpha$-disk (1973). Innermost stable circular orbit at $6GM/c^2$ (Schwarzschild) or down to $GM/c^2$ (maximally rotating Kerr). Sets the radiative efficiency: $\\eta \\sim 0.06$–$0.42$.",
        formula: "\\dot M_{acc}\\,\\eta c^2 = L_{AGN}",
        tags: ["AGN", "accretion"],
        xref: ["physics"],
      },
      {
        name: "Quasars",
        description: "Most luminous persistent objects in the universe — AGN whose host galaxies were initially invisible behind the central source.",
        keyFact: "3C 273 was the first identified (Schmidt 1963; $z = 0.158$, $M_V \\sim -27$). Quasar density peaked at $z \\sim 2$–$3$.",
        tags: ["AGN", "quasars"],
      },
      {
        name: "Unified AGN model",
        description: "Different AGN classes are the same engine viewed from different angles.",
        keyFact: "Obscuring torus blocks the broad-line region for edge-on views (Type 2). Polar viewing reveals broad lines (Type 1). Jets seen end-on become blazars. Substantial supporting evidence but not all-encompassing.",
        tags: ["AGN", "unified-model"],
      },
      {
        name: "Relativistic jets",
        description: "Collimated outflows from AGN at near-light speeds.",
        keyFact: "Lorentz factors $\\Gamma \\sim 5$–$50$. Jets can extend $>$Mpc — exceeding the host galaxy's stellar extent. Launch mechanism (Blandford-Znajek vs Blandford-Payne) debated.",
        tags: ["AGN", "jets"],
      },
      {
        name: "Blazars",
        description: "AGN with jets pointed almost directly at us.",
        keyFact: "Relativistic Doppler boosting amplifies flux by $\\delta^4$. Two subclasses: BL Lacs (featureless spectra) and flat-spectrum radio quasars. Rapid variability ($\\sim$ hours), polarization, and TeV emission diagnostic.",
        tags: ["AGN", "blazars"],
      },
      {
        name: "Seyfert galaxies",
        description: "Lower-luminosity AGN in spiral hosts.",
        keyFact: "Seyfert 1: broad permitted + narrow forbidden lines (polar view). Seyfert 2: only narrow lines (torus-obscured). Carl Seyfert (1943) catalogued the prototype set.",
        tags: ["AGN", "Seyferts"],
      },
      {
        name: "AGN feedback",
        description: "Energy and momentum injection from AGN regulates host-galaxy growth.",
        keyFact: "Mechanical feedback (radio jets carving cavities in cluster ICM) and radiative feedback (driving winds). Resolves cooling-flow problem in clusters and the high-mass cutoff of the galaxy luminosity function.",
        tags: ["AGN", "feedback"],
      },
      {
        name: "Tidal disruption events",
        description: "A star wandering too close to a SMBH is ripped apart, partially accreted, and lights up a flare.",
        keyFact: "Roche limit for stellar disruption: $r_T \\sim R_\\star (M_{BH}/M_\\star)^{1/3}$. Peak emission in soft X-ray/UV; characteristic $t^{-5/3}$ fallback rate. ZTF, ASAS-SN routinely discover them.",
        formula: "r_T \\sim R_\\star\\left(\\frac{M_{BH}}{M_\\star}\\right)^{1/3}",
        tags: ["AGN", "TDE", "transients"],
      },
      {
        name: "Event Horizon Telescope images",
        description: "First direct images of black-hole shadows.",
        keyFact: "M87* (2019): bright ring with central dark region $\\sim 40\\,\\mu$as across, matching GR prediction for a $6.5\\times 10^9\\,M_\\odot$ Kerr BH. Sgr A* (2022): comparable agreement at $\\sim 52\\,\\mu$as.",
        tags: ["AGN", "EHT", "imaging"],
      },
      {
        name: "Intermediate-mass black holes",
        description: "BHs in the $10^2$–$10^5\\,M_\\odot$ range — long suspected, hard to confirm.",
        keyFact: "Possible candidates include ultraluminous X-ray sources, central BHs of dwarf galaxies (NGC 4395, mass $\\sim 4\\times 10^5\\,M_\\odot$), and GW190521 ($\\sim 142\\,M_\\odot$ remnant from LIGO).",
        status: "open",
        tags: ["AGN", "IMBH"],
      },
      {
        name: "SMBH seed problem",
        description: "How did $\\sim 10^9\\,M_\\odot$ SMBHs assemble by $z > 7$ (within $\\sim 800$ Myr of Big Bang)?",
        keyFact: "Direct collapse of $\\sim 10^5\\,M_\\odot$ gas clouds vs Population III stellar remnants vs runaway mergers in dense clusters. JWST detections of massive black holes at $z > 10$ favor heavy-seed channels.",
        status: "open",
        tags: ["AGN", "seeds", "high-z"],
      },
    ],
  },

  // ── Family 16 ─────────────────────────────────────────────────────────────
  {
    slug: "large-scale-structure",
    number: 16,
    name: "Large-scale Structure",
    blurb: "Clusters, filaments, voids, and the cosmic web.",
    section: "D",
    color: "indigo",
    entries: [
      {
        name: "Galaxy clusters",
        description: "Largest gravitationally bound objects in the universe.",
        keyFact: "Masses $10^{14}$–$10^{15}\\,M_\\odot$. Composition: $\\sim 80\\%$ dark matter, $\\sim 15\\%$ hot intracluster medium ($T \\sim 10^7$–$10^8$ K, X-ray bright), $\\sim 5\\%$ galaxies.",
        tags: ["LSS", "clusters"],
      },
      {
        name: "Virial theorem and cluster mass",
        description: "For a self-gravitating system in equilibrium, $2T + U = 0$.",
        keyFact: "$M \\sim R\\sigma^2/G$ from velocity dispersion and size. Zwicky (1933) applied this to Coma cluster and discovered missing mass — the original dark-matter signal.",
        formula: "M_{vir} \\sim \\frac{R\\sigma^2}{G}",
        tags: ["LSS", "virial", "dark-matter"],
        xref: ["physics"],
      },
      {
        name: "Sunyaev-Zel'dovich effect",
        description: "Inverse-Compton scattering of CMB photons off hot ICM electrons.",
        keyFact: "Distinctive spectral distortion: deficit below $217$ GHz, excess above. Independent of redshift — picks out clusters out to high $z$ (Planck, SPT, ACT catalogs).",
        tags: ["LSS", "SZ", "clusters"],
      },
      {
        name: "Cosmic web",
        description: "Galaxies arranged in filaments, walls, sheets surrounding voids.",
        keyFact: "Mapped by SDSS, 2dFGRS, DESI. Voids $\\sim 30$–$100$ Mpc across cover $\\sim 80\\%$ of the volume but contain $\\sim 20\\%$ of the mass. Match $N$-body simulations of $\\Lambda$CDM.",
        tags: ["LSS", "web", "voids"],
      },
      {
        name: "Baryon Acoustic Oscillations",
        description: "Sound waves in the pre-recombination plasma left a $\\sim 150$ Mpc imprint on galaxy clustering.",
        keyFact: "Standard ruler — used to measure expansion history. Detected in SDSS (2005) and now precisely characterized by DESI (2024). 2024 DESI results show mild tension with $\\Lambda$CDM.",
        tags: ["LSS", "BAO", "cosmology"],
      },
      {
        name: "Redshift surveys",
        description: "Mapping 3D positions of galaxies using redshift as the radial coordinate.",
        keyFact: "CfA (1985, first wedge), 2dF (2003, $\\sim 220{,}000$ galaxies), SDSS ($\\sim 2$ million spectra), DESI (target: $40$ million by 2026). DESI Year 3 (2024) detected mild evidence for evolving dark energy.",
        tags: ["LSS", "surveys"],
      },
      {
        name: "Cosmic flows and bulk motion",
        description: "Peculiar velocity field traces gravitational pull of large-scale structure.",
        keyFact: "Local Group falls toward the Great Attractor at $\\sim 600$ km/s. Laniakea Supercluster (Tully 2014) identified as our home flow basin, $\\sim 160$ Mpc across.",
        tags: ["LSS", "flows", "Laniakea"],
      },
      {
        name: "Weak gravitational lensing",
        description: "Light from distant galaxies is slightly sheared by foreground mass.",
        keyFact: "Coherent ellipticity ($\\sim 1\\%$ effect) maps dark-matter distribution. Major surveys: DES, KiDS, HSC, Euclid (2023+), LSST (2025+). Tension with CMB on $S_8$ at $\\sim 2$–$3\\sigma$.",
        tags: ["LSS", "lensing", "dark-matter"],
        xref: ["physics"],
      },
      {
        name: "Bullet Cluster",
        description: "Merging cluster pair 1E 0657-558 — direct evidence for dark matter.",
        keyFact: "Lensing mass peaks are offset from X-ray gas peaks, exactly as expected if collisionless dark matter (passes through) is distinct from baryonic gas (shocked, lagging). Disfavors modified-gravity-without-dark-matter explanations.",
        tags: ["LSS", "Bullet", "dark-matter"],
      },
      {
        name: "Halo mass function",
        description: "Number density of dark-matter halos as a function of mass.",
        keyFact: "Press-Schechter (1974), refined to Sheth-Tormen, used to predict cluster counts. Sensitive to $\\sigma_8$, $\\Omega_m$, $\\Omega_\\Lambda$.",
        tags: ["LSS", "halos"],
        xref: ["statistics"],
      },
      {
        name: "Two-point correlation function",
        description: "Excess probability of finding a pair of galaxies at separation $r$.",
        keyFact: "$\\xi(r) \\sim (r/r_0)^{-\\gamma}$ with $r_0 \\sim 5\\,h^{-1}$ Mpc and $\\gamma \\approx 1.8$ for $L^\\star$ galaxies. Power spectrum $P(k)$ is its Fourier transform.",
        formula: "\\xi(r) = \\left(\\frac{r}{r_0}\\right)^{-\\gamma}",
        tags: ["LSS", "statistics"],
        xref: ["statistics"],
      },
      {
        name: "Sloan Great Wall",
        description: "Largest known galaxy supercluster, $\\sim 420$ Mpc across.",
        keyFact: "Discovered in SDSS data (Gott 2003). Tests the cosmological principle: such structures are barely allowed by $\\Lambda$CDM at the largest scales. Hercules-Corona Borealis Great Wall (controversial) would be even bigger.",
        tags: ["LSS", "superclusters"],
      },
    ],
  },

  // ── Family 17 ─────────────────────────────────────────────────────────────
  {
    slug: "cosmology",
    number: 17,
    name: "Cosmology",
    blurb: "The history, geometry, and contents of the universe.",
    section: "D",
    color: "violet",
    entries: [
      {
        name: "Cosmological principle",
        description: "The universe is homogeneous and isotropic on large scales.",
        keyFact: "Observationally verified by isotropy of CMB and galaxy distribution at $\\sim 100$ Mpc and larger. Underlies FLRW metric.",
        tags: ["cosmology", "principles"],
      },
      {
        name: "FLRW metric",
        description: "Spacetime line element for a homogeneous, isotropic universe.",
        keyFact: "$ds^2 = -c^2 dt^2 + a^2(t)[d\\chi^2 + S_k^2(\\chi)d\\Omega^2]$. Solutions of Einstein's equations with perfect-fluid matter give Friedmann equations.",
        formula: "ds^2 = -c^2dt^2 + a^2(t)\\left[\\frac{dr^2}{1-kr^2} + r^2d\\Omega^2\\right]",
        tags: ["cosmology", "metric"],
        xref: ["physics", "mathematics"],
      },
      {
        name: "Friedmann equations",
        description: "Differential equations governing the scale factor $a(t)$.",
        keyFact: "$\\left(\\frac{\\dot a}{a}\\right)^2 = \\frac{8\\pi G}{3}\\rho - \\frac{kc^2}{a^2} + \\frac{\\Lambda c^2}{3}$. With matter, radiation, and a cosmological constant, predicts expansion history.",
        formula: "H^2 = \\frac{8\\pi G}{3}\\rho - \\frac{kc^2}{a^2} + \\frac{\\Lambda c^2}{3}",
        tags: ["cosmology", "Friedmann"],
        xref: ["physics"],
      },
      {
        name: "Hubble's law",
        description: "Recession velocity is proportional to distance.",
        keyFact: "$v = H_0 d$. Hubble (1929) using Slipher's redshifts and Cepheid distances. Current Planck CMB-derived value: $67.4 \\pm 0.5$ km/s/Mpc; SH0ES local: $73.0 \\pm 1.0$ km/s/Mpc. The tension is unresolved.",
        formula: "v = H_0\\,d",
        tags: ["cosmology", "Hubble"],
        xref: ["physics"],
      },
      {
        name: "Hubble tension",
        description: "Mismatch between early-universe ($H_0 \\sim 67$) and late-universe ($H_0 \\sim 73$) determinations.",
        keyFact: "Significance now $\\sim 5\\sigma$. Possible resolutions: early dark energy, recalibrated distance ladder, new physics at recombination — none yet conclusive.",
        status: "open",
        tags: ["cosmology", "tension"],
      },
      {
        name: "Cosmic microwave background",
        description: "Thermal radiation from the universe at $\\sim 380{,}000$ yr, when electrons and protons recombined.",
        keyFact: "$T = 2.7255$ K blackbody (COBE FIRAS, the most perfect blackbody ever measured). Anisotropies at $\\sim 10^{-5}$ level encode initial conditions.",
        formula: "T_{CMB} = 2.7255\\,\\mathrm{K}",
        tags: ["cosmology", "CMB"],
        xref: ["physics"],
      },
      {
        name: "CMB power spectrum",
        description: "Angular spectrum of CMB temperature anisotropies.",
        keyFact: "Acoustic peaks at $\\ell \\sim 200, 540, 810$. First peak position fixes spatial flatness; relative heights fix $\\Omega_b$, $\\Omega_m$, $n_s$. Planck (2013–2018) is the definitive measurement.",
        tags: ["cosmology", "CMB"],
      },
      {
        name: "Cosmic inflation",
        description: "Brief epoch of exponential expansion in the early universe.",
        keyFact: "Solves horizon, flatness, monopole problems. Predicts nearly scale-invariant Gaussian primordial perturbations — confirmed by CMB. Direct detection (primordial gravitational waves / B-modes) still pending.",
        status: "open",
        tags: ["cosmology", "inflation"],
        xref: ["physics"],
      },
      {
        name: "Big Bang nucleosynthesis",
        description: "Production of D, $^3$He, $^4$He, $^7$Li in the first $\\sim 20$ minutes.",
        keyFact: "Predicts $^4$He mass fraction $Y_p \\approx 0.247$, D/H $\\sim 2.5\\times 10^{-5}$ — both matched to $\\%$ level. The $^7$Li problem (predicted higher than observed) persists.",
        tags: ["cosmology", "BBN"],
        xref: ["chemistry", "physics"],
      },
      {
        name: "Recombination and last scattering",
        description: "When the universe cooled enough for electrons and protons to combine into neutral H.",
        keyFact: "Occurred at $z \\approx 1090$ ($\\sim 380{,}000$ yr after Big Bang). Photon mean free path went from $\\ll H^{-1}$ to $\\gg H^{-1}$ — that decoupling moment is the CMB.",
        tags: ["cosmology", "recombination"],
      },
      {
        name: "Reionization",
        description: "Period when UV from first stars and galaxies re-ionized the IGM.",
        keyFact: "Began at $z \\sim 15$–$20$, completed by $z \\sim 5.5$. Constrained by CMB optical depth ($\\tau \\sim 0.054$) and Ly$\\alpha$ forest dark gaps.",
        tags: ["cosmology", "reionization"],
      },
      {
        name: "$\\Lambda$CDM model",
        description: "Concordance cosmological model: cold dark matter + cosmological constant.",
        keyFact: "6 parameters fit CMB, BAO, SN Ia, lensing, $H_0$ (modulo tensions). Best-fit: $\\Omega_m \\sim 0.31$, $\\Omega_\\Lambda \\sim 0.69$, $\\Omega_b \\sim 0.049$, $n_s \\sim 0.965$, $\\sigma_8 \\sim 0.81$, $h \\sim 0.674$.",
        tags: ["cosmology", "LCDM"],
      },
      {
        name: "Accelerating expansion",
        description: "Type Ia supernovae at $z > 0.5$ are dimmer than expected — universe is accelerating.",
        keyFact: "Riess and Perlmutter teams independently (1998). Nobel 2011. Implies $\\sim 70\\%$ of energy density is dark energy (or modified gravity).",
        tags: ["cosmology", "dark-energy"],
      },
      {
        name: "Age and size of the universe",
        description: "Best estimates from combined cosmological data.",
        keyFact: "Age $13.787 \\pm 0.020$ Gyr (Planck). Observable universe diameter $\\sim 93$ Gly (much larger than $ct$ because of expansion). Particle horizon $\\sim 46.5$ Gly comoving.",
        tags: ["cosmology", "fundamentals"],
      },
    ],
  },

  // ── Family 18 ─────────────────────────────────────────────────────────────
  {
    slug: "multi-messenger",
    number: 18,
    name: "Multi-messenger Astronomy",
    blurb: "Gravitational waves, neutrinos, cosmic rays, and the era of joint detections.",
    section: "D",
    color: "cyan",
    entries: [
      {
        name: "Gravitational waves",
        description: "Ripples in spacetime predicted by general relativity (1916).",
        keyFact: "Strain $h = \\Delta L/L$ at $\\sim 10^{-21}$ for LIGO sources. Quadrupole formula: $h \\sim GM v^2/(c^4 d)$. Indirect evidence from Hulse-Taylor pulsar (1974); direct detection GW150914 (2015).",
        formula: "h \\sim \\frac{G\\ddot Q}{c^4 d}",
        tags: ["GW", "multi-messenger"],
        xref: ["physics"],
      },
      {
        name: "LIGO and Virgo",
        description: "Ground-based laser interferometers detecting GWs in the $10$–$10^3$ Hz band.",
        keyFact: "$4$-km arms with $\\sim 10^{-19}$ m sensitivity. Detected dozens of binary-BH mergers, two BNS, and BH-NS systems by O4. Nobel Prize 2017 (Weiss, Barish, Thorne).",
        tags: ["GW", "interferometry"],
      },
      {
        name: "GW150914 — first detection",
        description: "Binary black hole merger detected September 14, 2015.",
        keyFact: "Final mass $\\sim 62\\,M_\\odot$ from progenitor $36 + 29\\,M_\\odot$. Distance $\\sim 410$ Mpc. Confirmed BHs of $30\\,M_\\odot$ exist and merge — both new at the time.",
        tags: ["GW", "BBH"],
      },
      {
        name: "GW170817 — multi-messenger",
        description: "Binary neutron star merger with electromagnetic counterpart.",
        keyFact: "GW + short GRB (1.7s delay) + kilonova in NGC 4993. Confirmed BNS mergers as r-process sites and short-GRB progenitors. Constrained $c_{GW} - c$ to $<10^{-15}$.",
        tags: ["GW", "BNS", "multi-messenger"],
      },
      {
        name: "Pulsar timing arrays",
        description: "Networks of millisecond pulsars detect nanohertz gravitational waves.",
        keyFact: "NANOGrav, EPTA, PPTA reported evidence (June 2023) for a stochastic GW background, consistent with supermassive BH-BH binaries throughout the universe.",
        tags: ["GW", "PTA", "nHz"],
      },
      {
        name: "LISA — future space interferometer",
        description: "ESA-NASA space-based detector targeting $10^{-4}$–$10^{-1}$ Hz.",
        keyFact: "Three spacecraft in heliocentric orbit, $2.5\\times 10^6$ km baseline. Launch $\\sim 2035$. Will detect SMBH mergers, EMRIs, Galactic compact binaries, possibly stochastic backgrounds.",
        tags: ["GW", "LISA", "space"],
      },
      {
        name: "Astrophysical neutrinos",
        description: "TeV–PeV neutrinos from cosmic accelerators.",
        keyFact: "IceCube (1 km$^3$ in Antarctic ice) detected diffuse extragalactic neutrino flux (2013). TXS 0506+056 blazar (2018) — first identified source. Probe inaccessible regions optically obscured.",
        tags: ["neutrinos", "multi-messenger"],
      },
      {
        name: "Supernova neutrinos",
        description: "Burst from core-collapse SN delivers most of the energy in neutrinos.",
        keyFact: "$99\\%$ of SN energy ($\\sim 3\\times 10^{53}$ erg) goes into neutrinos. SN 1987A: $\\sim 25$ neutrinos detected at Kamiokande/IMB/Baksan — first extrasolar neutrinos.",
        tags: ["neutrinos", "SN"],
      },
      {
        name: "Ultra-high-energy cosmic rays",
        description: "Particles with $E > 10^{18}$ eV — origin still uncertain.",
        keyFact: "GZK cutoff at $\\sim 5\\times 10^{19}$ eV from CMB photopion interactions. Pierre Auger Observatory has detected anisotropies correlated with starburst and active galaxies above $\\sim 8\\times 10^{18}$ eV.",
        tags: ["cosmic-rays", "UHECR"],
        status: "open",
      },
      {
        name: "Gamma-ray bursts (long and short)",
        description: "Brightest electromagnetic events in the universe.",
        keyFact: "Long ($>2$ s): collapsars from massive-star core collapse. Short ($<2$ s): compact-object mergers. Energies isotropic-equivalent $\\sim 10^{50}$–$10^{54}$ erg, beamed.",
        tags: ["GRB", "transients"],
      },
      {
        name: "Fast radio bursts",
        description: "Millisecond-scale, MHz–GHz radio flashes from cosmological distances.",
        keyFact: "First detected 2007 (Lorimer); rate now $\\sim 10^3$/day on the sky. Some repeat (FRB 121102). FRB 200428 from SGR 1935+2154 (Galactic magnetar, 2020) established at least one source class.",
        tags: ["FRB", "transients"],
      },
      {
        name: "Optical transient surveys",
        description: "Wide-field, high-cadence imaging surveys discover new transients in real time.",
        keyFact: "ZTF (2018+), ASAS-SN (2014+), Rubin/LSST (2025+, $\\sim 10$ million alerts/night). Backbone of multi-messenger electromagnetic follow-up.",
        tags: ["transients", "surveys"],
      },
    ],
  },

  // ── Family 19 ─────────────────────────────────────────────────────────────
  {
    slug: "astrobiology",
    number: 19,
    name: "Astrobiology",
    blurb: "Origins of life, biosignatures, technosignatures, and the search for life beyond Earth.",
    section: "E",
    color: "green",
    entries: [
      {
        name: "Definitions of life",
        description: "No universally agreed-upon definition.",
        keyFact: "NASA working definition: \"a self-sustaining chemical system capable of Darwinian evolution.\" Edge cases — viruses, prions, putative shadow biospheres — make this hard. Astrobiology must work without a closed definition.",
        tags: ["astrobiology", "definitions"],
        status: "open",
      },
      {
        name: "Habitability factors",
        description: "Beyond the HZ: tidal heating, magnetic shielding, plate tectonics, water inventory, atmospheric escape.",
        keyFact: "A planet \"in the habitable zone\" can be uninhabitable (Venus, Mars); a moon outside it can host a subsurface ocean (Europa, Enceladus). Habitability is multidimensional.",
        tags: ["astrobiology", "habitability"],
      },
      {
        name: "Miller-Urey and prebiotic chemistry",
        description: "Spark discharge in $\\mathrm{CH_4}+\\mathrm{NH_3}+\\mathrm{H_2O}+\\mathrm{H_2}$ produces amino acids.",
        keyFact: "Miller-Urey (1953). Modern view: early Earth atmosphere may have been less reducing, but other sources (hydrothermal vents, ice eutectics, impacts on iron-rich surfaces) provide alternative pathways.",
        tags: ["astrobiology", "prebiotic"],
        xref: ["chemistry"],
      },
      {
        name: "Origin of life — leading hypotheses",
        description: "Hydrothermal vent, surface warm-pond, panspermia (transported), late-veneer (delivered ingredients).",
        keyFact: "Earth's oldest microfossils $\\sim 3.5$ Gya (Apex chert, contested) and $3.7$ Gya stromatolites (Isua). Time window: between $\\sim 4.1$ Gya end-of-bombardment and earliest fossils — $\\sim 200$ Myr.",
        status: "open",
        tags: ["astrobiology", "origins"],
      },
      {
        name: "Extremophiles",
        description: "Earth life thrives in environments once thought uninhabitable.",
        keyFact: "Thermophiles ($>80°$C), psychrophiles ($<0°$C), halophiles, acidophiles, radioresistance ($Deinococcus$). Greatly expanded our notion of habitable parameter space.",
        tags: ["astrobiology", "extremophiles"],
      },
      {
        name: "Biosignatures",
        description: "Spectral signatures of life on exoplanets.",
        keyFact: "$\\mathrm{O_2}$ + reducing gases (CH$_4$, N$_2$O) is a strong disequilibrium signature. Vegetation red edge (700 nm) is a surface signature. JWST and future direct-imaging missions are key technologies.",
        tags: ["astrobiology", "biosignatures"],
        xref: ["chemistry"],
      },
      {
        name: "False-positive biosignatures",
        description: "Abiotic processes can mimic the signatures of life.",
        keyFact: "$\\mathrm{O_2}$ can build up from H$_2$O photolysis followed by H escape (Venus-like). Methane has many abiotic sources. Biosignature claims require ruling out abiotic explanations — much of recent debate (e.g. Mars methane, K2-18b DMS) is about this.",
        tags: ["astrobiology", "biosignatures", "caveats"],
      },
      {
        name: "Technosignatures",
        description: "Signatures of intelligent technology rather than biology.",
        keyFact: "Radio narrow-band signals (SETI), megastructures (Dyson spheres in IR), industrial pollutants (CFCs), laser pulses, persistent anomalies. Breakthrough Listen ($2015$+) is the largest current program.",
        tags: ["astrobiology", "SETI"],
      },
      {
        name: "Mars past habitability",
        description: "Mars had liquid water, volcanism, magnetic field $>3.5$ Gya.",
        keyFact: "Curiosity (Gale crater, 2012+) and Perseverance (Jezero crater, 2021+) found organics, sustained-water clay minerals, and evidence of habitable lake-bed environments. Sample-return planned via MSR (target 2030s).",
        tags: ["astrobiology", "Mars"],
      },
      {
        name: "Enceladus plumes",
        description: "Geyser plumes from south-polar fissures vent material from the subsurface ocean.",
        keyFact: "Cassini flew through them ($\\sim 2008$–$15$), detected H$_2$O, CO$_2$, NH$_3$, CH$_4$, H$_2$, salts, complex organics, and (2023) phosphates. Active hydrothermal chemistry — a habitable environment.",
        tags: ["astrobiology", "Enceladus", "moons"],
        xref: ["chemistry"],
      },
      {
        name: "Europa subsurface ocean",
        description: "Inferred from induced magnetic field response to Jupiter's field (Galileo).",
        keyFact: "Salty global ocean $\\sim 100$ km deep beneath $\\sim 15$–$25$ km ice. Europa Clipper (2024) will characterize it in detail.",
        tags: ["astrobiology", "Europa", "moons"],
      },
      {
        name: "Titan as a non-water-based test case",
        description: "Cryogenic methane/ethane lakes — chemistry without water.",
        keyFact: "Could host non-aqueous biochemistries? Theoretical work on \"azotosomes\" (membranes from N-containing molecules at $94$ K). Dragonfly mission (2028 launch) will fly an octocopter on Titan.",
        tags: ["astrobiology", "Titan", "moons"],
      },
    ],
  },

  // ── Family 20 ─────────────────────────────────────────────────────────────
  {
    slug: "astrochemistry-radiative-transfer",
    number: 20,
    name: "Astrochemistry & Radiative Transfer",
    blurb: "Molecules in space and the physics of how their light reaches us.",
    section: "E",
    color: "blue",
    entries: [
      {
        name: "Molecules in space",
        description: "Over $\\sim 300$ molecules detected in the ISM and circumstellar shells.",
        keyFact: "Detections range from H$_2$ (most abundant) to fullerenes (C$_{60}$, 2010) and amino acid glycine in comets. Surveys via mm/sub-mm rotational transitions; ALMA, IRAM, CSO are the workhorses.",
        tags: ["astrochemistry", "molecules"],
        xref: ["chemistry"],
      },
      {
        name: "Polycyclic aromatic hydrocarbons (PAHs)",
        description: "Aromatic ring molecules detected via IR emission features.",
        keyFact: "Strong bands at $3.3, 6.2, 7.7, 8.6, 11.3\\,\\mu$m. Carry $\\sim 10\\%$ of UV-absorbed energy in normal galaxies. Specific species (e.g. cyanonaphthalene) identified by JWST in TMC-1.",
        tags: ["astrochemistry", "PAHs"],
        xref: ["chemistry"],
      },
      {
        name: "Dust grains",
        description: "Submicron solid particles of silicates, carbonaceous, and ice mantles.",
        keyFact: "$\\sim 1\\%$ of ISM by mass; dominate FIR emission. Sites of H$_2$ formation (via H atom recombination on grain surfaces). Composition and size from infrared spectra and polarization.",
        tags: ["astrochemistry", "dust"],
        xref: ["chemistry"],
      },
      {
        name: "Masers",
        description: "Astrophysical microwave amplification by stimulated emission.",
        keyFact: "Water masers at $22$ GHz from star-forming regions and accretion disks (NGC 4258 disk maser gave SMBH mass to $\\sim 1\\%$). OH, methanol, SiO masers also common. Pumping is collisional or radiative.",
        tags: ["astrochemistry", "masers"],
        xref: ["physics"],
      },
      {
        name: "Radiative transfer equation",
        description: "Differential equation describing intensity propagation through a medium.",
        keyFact: "$dI_\\nu/ds = -\\kappa_\\nu I_\\nu + j_\\nu$. Solutions in limits: pure absorption (Beer's law), local thermodynamic equilibrium ($I_\\nu \\to B_\\nu(T)$), scattering-dominated (random-walk diffusion).",
        formula: "\\frac{dI_\\nu}{ds} = -\\kappa_\\nu I_\\nu + j_\\nu",
        tags: ["radiative-transfer", "fundamentals"],
        xref: ["physics", "mathematics"],
      },
      {
        name: "Optical depth",
        description: "Integrated absorption along a line of sight.",
        keyFact: "$\\tau_\\nu = \\int\\kappa_\\nu ds$. $\\tau \\ll 1$ optically thin (linear in column); $\\tau \\gg 1$ optically thick (saturates at blackbody). Often $\\tau = 1$ defines a \"photosphere.\"",
        formula: "\\tau_\\nu = \\int\\kappa_\\nu\\,ds",
        tags: ["radiative-transfer"],
      },
      {
        name: "Source function",
        description: "$S_\\nu = j_\\nu/\\kappa_\\nu$ — emission per absorption.",
        keyFact: "Under LTE, $S_\\nu = B_\\nu(T)$ (Kirchhoff). The Eddington-Barbier relation $I_\\nu(0) \\approx S_\\nu(\\tau = 2/3)$ is why we \"see\" to optical depth 2/3 in solar limb darkening.",
        tags: ["radiative-transfer"],
      },
      {
        name: "Synchrotron emission",
        description: "Radiation from relativistic electrons spiraling in magnetic fields.",
        keyFact: "Power-law spectrum $S_\\nu \\propto \\nu^{-\\alpha}$ with $\\alpha = (p-1)/2$ for electron power-law index $p$. Dominant in radio galaxies, SNRs, jets, pulsar wind nebulae.",
        formula: "S_\\nu \\propto \\nu^{-\\alpha}",
        tags: ["radiative-transfer", "synchrotron"],
        xref: ["physics"],
      },
      {
        name: "Bremsstrahlung (free-free)",
        description: "Radiation from charged particles deflected by other charges.",
        keyFact: "Dominant emission mechanism in HII regions and hot ICM ($\\sim 10^7$–$10^8$ K). Thermal bremsstrahlung gives flat spectrum cutting off at $h\\nu \\sim kT$.",
        tags: ["radiative-transfer", "thermal"],
        xref: ["physics"],
      },
      {
        name: "Inverse Compton scattering",
        description: "Relativistic electrons up-scatter low-energy photons.",
        keyFact: "Cooling time $t_{IC} = m_e c^2/(\\sigma_T c\\,\\gamma\\,U_{rad})$. Operates in AGN jets, SNRs, the cosmic-ray ISM, and is responsible for the high-energy peak in blazar spectra.",
        tags: ["radiative-transfer", "Compton"],
        xref: ["physics"],
      },
      {
        name: "Saha equation",
        description: "Ionization equilibrium in a partially ionized gas.",
        keyFact: "$\\frac{n_{i+1}n_e}{n_i} = \\frac{2 Z_{i+1}}{Z_i}\\left(\\frac{2\\pi m_e k_BT}{h^2}\\right)^{3/2}e^{-\\chi/kT}$. Explains why H is mostly neutral in stellar photospheres despite $kT \\sim \\chi$.",
        formula: "\\frac{n_{i+1}n_e}{n_i} = \\frac{2Z_{i+1}}{Z_i}\\!\\left(\\frac{2\\pi m_ek_BT}{h^2}\\right)^{3/2}\\!e^{-\\chi/k_BT}",
        tags: ["astrochemistry", "Saha"],
        xref: ["physics", "chemistry"],
      },
      {
        name: "Boltzmann excitation",
        description: "Relative populations of atomic energy levels in thermal equilibrium.",
        keyFact: "$n_2/n_1 = (g_2/g_1)e^{-\\Delta E/k_BT}$. Combined with Saha, gives ionization+excitation structure — the basis of spectral classification.",
        formula: "\\frac{n_2}{n_1} = \\frac{g_2}{g_1}e^{-\\Delta E/k_BT}",
        tags: ["astrochemistry", "Boltzmann"],
        xref: ["physics"],
      },
    ],
  },

  // ── Family 21 ─────────────────────────────────────────────────────────────
  {
    slug: "open-questions",
    number: 21,
    name: "Open Questions",
    blurb: "The genuinely unresolved problems at the frontier of astronomy.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Nature of dark matter",
        description: "What is the $\\sim 27\\%$ of the energy budget that interacts gravitationally but not electromagnetically?",
        keyFact: "Direct-detection experiments (LZ, XENONnT, PandaX) have not detected WIMPs to cross-sections $\\sim 10^{-47}\\,\\mathrm{cm}^2$. Axions, sterile neutrinos, primordial black holes are viable alternatives. The existence is firm; the identity is unknown.",
        status: "open",
        tags: ["frontier", "dark-matter"],
        xref: ["physics"],
      },
      {
        name: "Nature of dark energy",
        description: "What is driving the accelerating expansion?",
        keyFact: "Cosmological constant requires vacuum energy density $\\sim 10^{120}$ smaller than QFT prediction. Quintessence (dynamic scalar fields), modified gravity, anthropic-multiverse arguments are all live. DESI 2024 mildly favors evolving dark energy.",
        status: "open",
        tags: ["frontier", "dark-energy"],
        xref: ["physics"],
      },
      {
        name: "Hubble tension",
        description: "$\\sim 5\\sigma$ discrepancy between early- and late-universe $H_0$ measurements.",
        keyFact: "CMB-inferred: $H_0 \\approx 67.4$. Local SH0ES/Cepheid: $\\approx 73.0$. Systematic resolution, early-dark-energy boost, or new recombination physics — none yet definitive.",
        status: "open",
        tags: ["frontier", "cosmology", "tension"],
      },
      {
        name: "Coronal heating",
        description: "Why is the solar corona $\\sim 200\\times$ hotter than the photosphere?",
        keyFact: "Nanoflares (Parker) and Alfvén wave dissipation are the two leading mechanisms; Parker Solar Probe (2018+) has constrained both. Likely a mixture; relative weight unknown.",
        status: "open",
        tags: ["frontier", "Sun"],
      },
      {
        name: "Lithium-7 problem",
        description: "BBN-predicted $^7$Li is $\\sim 3\\times$ observed in metal-poor stars.",
        keyFact: "Suggests either (a) atmospheric depletion in old stars, (b) under-appreciated nuclear-physics uncertainties, or (c) new physics during BBN. Persists as the only significant BBN-vs-observation mismatch.",
        status: "open",
        tags: ["frontier", "BBN"],
      },
      {
        name: "First-star nucleosynthesis",
        description: "What were Pop III stars like and what did they leave behind?",
        keyFact: "Never directly observed (yet). Inferred masses range $\\sim 10$–$1000\\,M_\\odot$. JWST may detect them via lensing; their nucleosynthetic fingerprints are sought in carbon-enhanced metal-poor stars in the Galactic halo.",
        status: "open",
        tags: ["frontier", "Pop-III"],
      },
      {
        name: "SMBH seed mechanism",
        description: "How did $\\sim 10^9\\,M_\\odot$ black holes form by $z > 7$?",
        keyFact: "Direct collapse of $\\sim 10^4$–$10^5\\,M_\\odot$ gas, runaway mergers in dense clusters, or Population III remnants. JWST detections of overmassive BHs in early galaxies favor heavy-seed channels.",
        status: "open",
        tags: ["frontier", "SMBH"],
      },
      {
        name: "Origin of UHE cosmic rays",
        description: "What accelerates particles to $>10^{19}$ eV?",
        keyFact: "Possible sources: AGN jets, GRBs, starburst galaxies, magnetars. Pierre Auger sees correlations with starburst-galaxy positions above $8\\times 10^{18}$ eV at $\\sim 4\\sigma$. Identification of the dominant source class remains open.",
        status: "open",
        tags: ["frontier", "UHECR"],
      },
      {
        name: "Origin of fast radio bursts",
        description: "What produces millisecond extragalactic radio flashes?",
        keyFact: "FRB 200428 from Galactic magnetar SGR 1935+2154 confirms magnetars as one source. Diversity (repeaters vs non-repeaters) suggests multiple progenitor channels.",
        status: "open",
        tags: ["frontier", "FRB"],
      },
      {
        name: "Black-hole information paradox",
        description: "Does information that falls into a black hole survive evaporation?",
        keyFact: "Hawking radiation appears thermal — implying loss. Recent work on Page curve and replica wormholes suggests unitarity is preserved, but the mechanism (and observational implications, if any) is not established.",
        status: "open",
        tags: ["frontier", "black-holes"],
        xref: ["physics"],
      },
      {
        name: "Detection of primordial gravitational waves",
        description: "Inflation predicts a stochastic GW background imprinted as CMB B-mode polarization.",
        keyFact: "BICEP/Keck constrain $r < 0.036$ (95% CL). LiteBIRD, CMB-S4 aim for $r \\sim 0.001$. A detection would directly probe the energy scale of inflation.",
        status: "open",
        tags: ["frontier", "inflation", "GW"],
      },
      {
        name: "Existence of life beyond Earth",
        description: "The cardinal question of astrobiology.",
        keyFact: "No confirmed detection — biosignature claims (Mars methane, K2-18b DMS, Venusian PH$_3$) are all contested. Sample return (Mars), Europa Clipper, Enceladus orbiter, Dragonfly, and exoplanet atmospheric characterization are the principal probes.",
        status: "open",
        tags: ["frontier", "astrobiology"],
      },
      {
        name: "Drake equation factors",
        description: "Several Drake-equation factors remain unconstrained by orders of magnitude.",
        keyFact: "Rate of star formation, fraction with planets, planets per system in HZ — all now known within factor of a few. $f_l$, $f_i$, $f_c$, $L$ remain unmeasured. Decisive constraints likely require either a detection or definitive non-detection on a deep survey.",
        status: "open",
        tags: ["frontier", "SETI"],
      },
      {
        name: "Are we typical observers? (Copernican principle)",
        description: "Anthropic-multiverse cosmology questions the universality of the cosmological principle.",
        keyFact: "If we live in a multiverse with varying fundamental constants, anthropic selection picks out habitable subregions. Whether this counts as physics, philosophy, or both remains contested.",
        status: "open",
        tags: ["frontier", "cosmology", "philosophy"],
      },
    ],
  },
];
