import type { Family } from "./types";

// ── SECTION D — MATHEMATICAL LOGIC + SECTION E — PHILOSOPHICAL/HISTORY ──────

export const FAMILIES_13_18: Family[] = [
  // ── Family 13 — Set Theory ──────────────────────────────────────────────
  {
    slug: "set-theory",
    number: 13,
    name: "Set Theory",
    blurb: "Sets as the standard foundation — ZFC, the cumulative hierarchy, large cardinals, and forcing.",
    section: "D",
    color: "sky",
    entries: [
      {
        name: "ZFC axioms",
        description: "Zermelo–Fraenkel set theory with choice.",
        formalDef: "axioms: extensionality, pairing, union, power set, infinity, foundation, separation (schema), replacement (schema), and choice; underlying logic is FOL with $\\in$ and $=$.",
        keyResults: "Standard foundation of mathematics; consistency unprovable in ZFC (Gödel's second incompleteness theorem).",
        extends: ["First-order logic"],
        tags: ["foundational", "landmark"],
        xref: ["mathematics"],
        historical: true,
      },
      {
        name: "Russell's paradox",
        description: "The set $R = \\{x : x \\notin x\\}$ is inconsistent.",
        formalDef: "if $R\\in R$ then $R\\notin R$; if $R\\notin R$ then $R\\in R$ — contradiction from naive comprehension $\\exists y\\,\\forall x\\,(x\\in y \\leftrightarrow \\varphi(x))$.",
        keyResults: "Killed Frege's logicism (1902); motivated Zermelo's restriction to separation $\\{x\\in A : \\varphi(x)\\}$.",
        extends: ["ZFC axioms"],
        tags: ["paradox", "landmark"],
        historical: true,
        xref: ["mathematics", "philosophy"],
      },
      {
        name: "Axiom of choice",
        description: "Every family of non-empty sets has a choice function.",
        formalDef: "$\\forall \\mathcal{F}\\,(\\emptyset \\notin \\mathcal{F} \\to \\exists f: \\mathcal{F}\\to \\bigcup \\mathcal{F}\\;\\forall A\\in \\mathcal{F}\\,f(A)\\in A)$.",
        keyResults: "Independent of ZF (Cohen 1963); equivalent to Zorn's lemma and the well-ordering theorem; required for vector-space bases, Tychonoff, etc.",
        extends: ["ZFC axioms"],
        tags: ["independence"],
        xref: ["mathematics"],
      },
      {
        name: "Zorn's lemma",
        description: "Every chain-complete partial order has a maximal element.",
        formalDef: "if $(P,\\le)$ is non-empty and every chain has an upper bound, then $P$ has a maximal element.",
        keyResults: "Equivalent to AC in ZF; standard tool for non-constructive existence (Hahn–Banach, maximal ideals, ultrafilters).",
        extends: ["Axiom of choice"],
        tags: ["equivalent-to-AC"],
        xref: ["mathematics"],
      },
      {
        name: "Well-ordering theorem",
        description: "Every set admits a well-order.",
        formalDef: "$\\forall A\\,\\exists R\\,(R$ well-orders $A)$ — every nonempty subset has a least element.",
        keyResults: "Equivalent to AC; Zermelo's first proof (1904) provoked the AC controversy.",
        extends: ["Axiom of choice"],
        tags: ["equivalent-to-AC"],
        historical: true,
      },
      {
        name: "Cardinal arithmetic",
        description: "Arithmetic on infinite sizes.",
        formalDef: "$|A|+|B|=|A\\sqcup B|$, $|A|\\cdot |B|=|A\\times B|$, $|A|^{|B|}=|A^B|$; under AC, infinite cardinal addition and multiplication collapse: $\\kappa + \\lambda = \\kappa \\cdot \\lambda = \\max(\\kappa,\\lambda)$.",
        keyResults: "Cantor's theorem $|A|<|2^A|$; König's theorem $\\kappa^{\\mathrm{cf}(\\kappa)}>\\kappa$; cardinal exponentiation is not absolute (depends on forcing).",
        extends: ["ZFC axioms"],
        tags: ["arithmetic"],
        xref: ["mathematics"],
      },
      {
        name: "Ordinal arithmetic",
        description: "Arithmetic on well-ordered 'positions'.",
        formalDef: "ordinals defined by Von Neumann: $\\alpha = \\{\\beta : \\beta < \\alpha\\}$; $\\alpha + \\beta$ is the order type of $\\alpha$ followed by $\\beta$; non-commutative.",
        keyResults: "$\\omega + 1 \\ne 1 + \\omega$; ordinals up to $\\varepsilon_0$ encode primitive-recursive arithmetic.",
        extends: ["ZFC axioms"],
        tags: ["arithmetic"],
        xref: ["mathematics"],
      },
      {
        name: "Transfinite induction",
        description: "Induction along an ordinal.",
        formalDef: "$\\forall \\alpha\\,(\\forall \\beta < \\alpha\\,P(\\beta) \\to P(\\alpha)) \\to \\forall \\alpha\\,P(\\alpha)$.",
        keyResults: "Generalises ordinary induction to all ordinals; basis of constructions on the cumulative hierarchy $V_\\alpha$.",
        extends: ["Ordinal arithmetic"],
        tags: ["proof-principle"],
        xref: ["mathematics"],
      },
      {
        name: "Cantor's theorem",
        description: "The power set is strictly larger.",
        formalDef: "for any set $A$, $|A| < |\\mathcal{P}(A)|$; proof by diagonalisation: assume $f:A \\to \\mathcal{P}(A)$ surjective and consider $D = \\{x\\in A : x \\notin f(x)\\}$.",
        keyResults: "Yields the hierarchy of infinities $\\aleph_0 < \\aleph_1 < \\dots$; underlies Russell's paradox and Gödel/Tarski self-reference.",
        extends: ["ZFC axioms"],
        tags: ["theorem", "landmark"],
        historical: true,
        xref: ["mathematics"],
      },
      {
        name: "Continuum hypothesis",
        description: "Is there a size strictly between $\\aleph_0$ and $2^{\\aleph_0}$?",
        formalDef: "$\\mathrm{CH}: 2^{\\aleph_0} = \\aleph_1$.",
        keyResults: "Independent of ZFC: Gödel (1940) showed consistency, Cohen (1963) forced its negation; one of Hilbert's first problems.",
        extends: ["Cardinal arithmetic"],
        tags: ["independence", "landmark"],
        status: "solved",
        xref: ["mathematics"],
        historical: true,
      },
      {
        name: "Inaccessible cardinals",
        description: "Smallest 'large' cardinals — uncountable, regular, strong limit.",
        formalDef: "$\\kappa$ is strongly inaccessible iff $\\kappa > \\aleph_0$, $\\kappa$ regular (no shorter cofinal sequence) and $\\lambda < \\kappa \\Rightarrow 2^\\lambda < \\kappa$.",
        keyResults: "$V_\\kappa$ models ZFC; existence not provable in ZFC by Gödel's second theorem.",
        extends: ["Cardinal arithmetic"],
        tags: ["large-cardinal"],
        xref: ["mathematics"],
      },
      {
        name: "Measurable cardinals",
        description: "Cardinals admitting a non-trivial $\\sigma$-additive two-valued measure.",
        formalDef: "$\\kappa$ is measurable iff there is a non-principal $\\kappa$-complete ultrafilter on $\\kappa$; equivalently, an elementary embedding $j:V\\to M$ with critical point $\\kappa$.",
        keyResults: "Imply existence of inner models with measurable cardinals; refute $V=L$.",
        extends: ["Inaccessible cardinals", "Elementary embedding"],
        tags: ["large-cardinal"],
        xref: ["mathematics"],
      },
      {
        name: "Inner models (L)",
        description: "Gödel's constructible universe.",
        formalDef: "$L_0 = \\emptyset$; $L_{\\alpha+1} = \\mathrm{Def}(L_\\alpha)$ (first-order definable subsets); $L_\\lambda = \\bigcup_{\\alpha<\\lambda} L_\\alpha$ for limit $\\lambda$; $L = \\bigcup_\\alpha L_\\alpha$.",
        keyResults: "$L$ is a model of ZFC + GCH + V=L; gives the consistency of CH and AC; refuted by sufficiently large cardinals.",
        extends: ["ZFC axioms"],
        tags: ["model", "landmark"],
        historical: true,
        xref: ["mathematics"],
      },
      {
        name: "Forcing",
        description: "Cohen's method for building models of ZFC.",
        formalDef: "start in a ground model $M$ with a forcing poset $\\mathbb{P}\\in M$; a $\\mathbb{P}$-generic filter $G$ over $M$ gives an extension $M[G]\\models \\mathrm{ZFC}$; truth in $M[G]$ governed by the forcing relation $\\Vdash$.",
        keyResults: "Independence of CH, AC, and many other statements; basis of nearly all set-theoretic independence results.",
        extends: ["ZFC axioms"],
        tags: ["technique", "landmark"],
        historical: true,
        xref: ["mathematics"],
      },
      {
        name: "Large cardinals",
        description: "Hierarchy of strong infinity axioms.",
        formalDef: "tower including inaccessible, Mahlo, weakly compact, Woodin, supercompact, huge, $I0$–$I3$, etc.; each strictly stronger in consistency.",
        keyResults: "Strict consistency hierarchy; Woodin cardinals imply projective determinacy; Reinhardt cardinals refuted by Kunen's inconsistency theorem.",
        extends: ["Measurable cardinals"],
        tags: ["hierarchy"],
        xref: ["mathematics"],
      },
      {
        name: "Axiom of determinacy",
        description: "Every two-player game of perfect information has a winning strategy.",
        formalDef: "for every $A\\subseteq \\omega^\\omega$, either player I or player II has a strategy in the Gale–Stewart game $G_A$.",
        keyResults: "Contradicts AC; AD$_{\\mathbb{R}}$ implies all sets of reals are Lebesgue-measurable; from Woodin cardinals, $L(\\mathbb{R})\\models \\mathrm{AD}$.",
        extends: ["Axiom of choice", "Large cardinals"],
        tags: ["determinacy"],
        xref: ["mathematics"],
      },
      {
        name: "Solovay model",
        description: "A model of ZF + DC in which every set of reals is Lebesgue-measurable.",
        formalDef: "starting from an inaccessible cardinal, Lévy-collapse to make it $\\aleph_1$; the symmetric inner model $L(\\mathbb{R})$ in the extension satisfies the required properties.",
        keyResults: "Solovay (1970); shows non-measurable sets require AC; the use of an inaccessible was shown necessary by Shelah.",
        extends: ["Forcing"],
        tags: ["model", "landmark"],
        historical: true,
        xref: ["mathematics"],
      },
      {
        name: "Generic absoluteness",
        description: "Truth of certain statements is invariant under forcing.",
        formalDef: "$\\Sigma^1_2$ statements are absolute between $M$ and $M[G]$ for any generic $G$, under sufficient large-cardinal hypotheses; Woodin cardinals give $\\Sigma^1_3$ absoluteness for $L(\\mathbb{R})$.",
        keyResults: "Connects large cardinals to descriptive set theory; key tool in Woodin's analysis of the continuum.",
        extends: ["Forcing", "Large cardinals"],
        tags: ["absoluteness"],
        xref: ["mathematics"],
      },
    ],
  },

  // ── Family 14 — Computability Theory ────────────────────────────────────
  {
    slug: "computability",
    number: 14,
    name: "Computability Theory",
    blurb: "What is computable in principle — Turing machines, reductions, the arithmetical hierarchy, and the algorithmic structure of definability.",
    section: "D",
    color: "cyan",
    entries: [
      {
        name: "Turing machines",
        description: "Idealised compute model with infinite tape.",
        formalDef: "$M = (Q,\\Sigma,\\Gamma,\\delta,q_0,F)$ with $\\delta : Q\\times \\Gamma \\to Q\\times \\Gamma \\times \\{L,R\\}$; computes a partial function $\\Sigma^* \\rightharpoonup \\Sigma^*$.",
        keyResults: "Turing (1936); defines computability and underlies the Church–Turing thesis.",
        extends: ["First-order logic"],
        tags: ["model", "landmark"],
        historical: true,
        xref: ["computer-science"],
      },
      {
        name: "λ-calculus",
        description: "Church's formal calculus of anonymous functions.",
        formalDef: "terms $t ::= x \\mid \\lambda x.t \\mid t\\,t$; $\\beta$-reduction $(\\lambda x.t)\\,u \\to t[u/x]$.",
        keyResults: "Church–Rosser confluence theorem; computes exactly the partial recursive functions; foundation of functional programming.",
        extends: ["First-order logic"],
        tags: ["computation", "landmark"],
        historical: true,
        xref: ["computer-science"],
      },
      {
        name: "Recursive functions",
        description: "Functions built from zero, successor, projections by composition, primitive recursion and minimisation.",
        formalDef: "the smallest class of partial functions $\\mathbb{N}^k \\rightharpoonup \\mathbb{N}$ closed under composition, primitive recursion, and unbounded minimisation $\\mu y.\\,[f(\\vec x,y)=0]$.",
        keyResults: "Coincides with Turing computability and lambda definability; Kleene normal form theorem.",
        extends: ["Turing machines"],
        tags: ["model"],
      },
      {
        name: "Church–Turing thesis",
        description: "The intuitive notion of effective computation equals Turing computability.",
        formalDef: "informal: every function effectively computable by a finite mechanical procedure is computable by a Turing machine; not a mathematical theorem.",
        keyResults: "Supported by the equivalence of Turing machines, $\\lambda$-calculus, recursive functions, register machines, Markov algorithms, and cellular automata.",
        extends: ["Turing machines", "λ-calculus", "Recursive functions"],
        tags: ["thesis", "philosophical"],
        xref: ["computer-science", "philosophy"],
        historical: true,
      },
      {
        name: "Halting problem",
        description: "Undecidability of whether a Turing machine halts.",
        formalDef: "$H = \\{(M,w) : M$ halts on input $w\\}$; $H$ is recursively enumerable but not recursive.",
        keyResults: "Turing's diagonal argument (1936); benchmark undecidable problem; basis of many further undecidability results.",
        extends: ["Turing machines"],
        tags: ["undecidability", "landmark"],
        historical: true,
        xref: ["computer-science"],
      },
      {
        name: "Recursion theorem",
        description: "Programs can reference their own code.",
        formalDef: "for every computable $f$, there is $e$ with $\\{e\\} \\simeq \\{f(e)\\}$ (Kleene's fixed-point theorem).",
        keyResults: "Underlies self-replication, quines, and self-modifying programs; essential in defining structures like the universal Turing machine.",
        extends: ["Turing machines"],
        tags: ["fixed-point"],
      },
      {
        name: "Rice's theorem",
        description: "All non-trivial semantic properties of programs are undecidable.",
        formalDef: "for any non-trivial set $S$ of partial computable functions (neither empty nor all), $\\{e : \\{e\\}\\in S\\}$ is undecidable.",
        keyResults: "Generalises the halting problem; reduces every semantic verification task to undecidable problems modulo abstraction.",
        extends: ["Halting problem"],
        tags: ["undecidability"],
        xref: ["computer-science"],
      },
      {
        name: "Recursively enumerable sets",
        description: "Sets enumerable by a Turing machine.",
        formalDef: "$A\\subseteq \\mathbb{N}$ is r.e.\\ iff $A = \\mathrm{dom}(\\{e\\})$ for some $e$; equivalently, $A$ is $\\Sigma^0_1$.",
        keyResults: "$A$ is recursive iff $A$ and $\\bar A$ are r.e.; $\\Sigma^0_1 \\setminus \\Pi^0_1 \\ne \\emptyset$ (witness: halting set).",
        extends: ["Halting problem"],
        tags: ["recursion-theory"],
      },
      {
        name: "Many-one reducibility",
        description: "Reduction by computable transformation of inputs.",
        formalDef: "$A \\le_m B$ iff there is computable $f$ with $x\\in A \\Leftrightarrow f(x)\\in B$.",
        keyResults: "Standard reducibility in degree theory; halting set is $\\le_m$-complete among r.e.\\ sets.",
        extends: ["Recursively enumerable sets"],
        tags: ["reducibility"],
      },
      {
        name: "Turing reducibility",
        description: "Reduction via oracle calls.",
        formalDef: "$A \\le_T B$ iff $A$ is computable by a Turing machine with oracle for $B$; Turing degree $\\mathrm{deg}(A)$ is the $\\le_T$-equivalence class.",
        keyResults: "The Turing degrees form an upper semi-lattice with rich structure; $\\mathbf{0}'$ is the degree of the halting set.",
        extends: ["Many-one reducibility"],
        tags: ["degrees"],
      },
      {
        name: "Arithmetical hierarchy",
        description: "Classification of sets by quantifier complexity over $\\mathbb{N}$.",
        formalDef: "$\\Sigma^0_0 = \\Pi^0_0$ = decidable; $\\Sigma^0_{n+1}$ = $\\exists$-projections of $\\Pi^0_n$; $\\Pi^0_n$ duals; $\\Delta^0_n = \\Sigma^0_n \\cap \\Pi^0_n$.",
        keyResults: "Hierarchy theorem: $\\Sigma^0_n \\subsetneq \\Sigma^0_{n+1}$; complete sets at each level.",
        extends: ["Turing reducibility"],
        tags: ["hierarchy"],
        xref: ["mathematics"],
      },
      {
        name: "Analytical hierarchy",
        description: "Second-order analogue of the arithmetical hierarchy.",
        formalDef: "quantifies over functions (or reals); $\\Sigma^1_n,\\Pi^1_n$ defined by alternations of second-order quantifiers; $\\Delta^1_1$ = hyperarithmetic.",
        keyResults: "Foundation of descriptive set theory; projective determinacy gives regularity properties throughout the projective hierarchy.",
        extends: ["Arithmetical hierarchy"],
        tags: ["hierarchy"],
        xref: ["mathematics"],
      },
      {
        name: "Post's problem",
        description: "Is there an r.e.\\ degree strictly between $\\mathbf{0}$ and $\\mathbf{0}'$?",
        formalDef: "asks whether there exist r.e.\\ sets $A$ with $\\emptyset <_T A <_T H$.",
        keyResults: "Solved positively by Friedberg and Muchnik (1956) via the finite-injury priority method.",
        extends: ["Turing reducibility"],
        tags: ["historical"],
        status: "solved",
        historical: true,
      },
      {
        name: "Friedberg–Muchnik theorem",
        description: "Existence of intermediate r.e.\\ Turing degrees.",
        formalDef: "there exist r.e.\\ sets $A,B$ that are Turing-incomparable: $A \\not\\le_T B$ and $B \\not\\le_T A$.",
        keyResults: "Introduced the priority method; foundation of computability theory's classification of r.e.\\ degrees.",
        extends: ["Post's problem"],
        tags: ["theorem", "landmark"],
        historical: true,
      },
      {
        name: "Kolmogorov complexity",
        description: "Algorithmic information content of a finite string.",
        formalDef: "$K(x) = \\min\\{|p| : U(p)=x\\}$ for a fixed universal machine $U$; defined up to additive constant.",
        keyResults: "Independent definition by Solomonoff, Kolmogorov, Chaitin; characterises randomness via $K(x) \\ge |x|-c$; not computable.",
        extends: ["Turing machines"],
        tags: ["randomness", "landmark"],
        historical: true,
        xref: ["computer-science", "mathematics"],
      },
      {
        name: "Oracle machines",
        description: "Turing machines with a black-box query state.",
        formalDef: "$M^A$ may query 'is $x \\in A$?' at any step; relativisation: complexity classes such as $\\mathrm{P}^A$, $\\mathrm{NP}^A$.",
        keyResults: "Baker–Gill–Solovay: there exist oracles $A,B$ with $\\mathrm{P}^A=\\mathrm{NP}^A$ and $\\mathrm{P}^B\\ne \\mathrm{NP}^B$; relativisation barrier for $\\mathrm{P}$ vs $\\mathrm{NP}$.",
        extends: ["Turing machines"],
        tags: ["complexity"],
        xref: ["computer-science"],
      },
    ],
  },

  // ── Family 15 — Type Theory ──────────────────────────────────────────────
  {
    slug: "type-theory",
    number: 15,
    name: "Type Theory",
    blurb: "Types as propositions, programs as proofs — from simply typed lambda calculus to homotopy type theory.",
    section: "D",
    color: "teal",
    entries: [
      {
        name: "Simply typed λ-calculus (STLC)",
        description: "Lambda calculus with simple function types.",
        formalDef: "types $\\tau ::= o \\mid \\tau \\to \\tau$; terms typed by $\\Gamma \\vdash t : \\tau$; standard introduction/elimination rules for $\\to$.",
        keyResults: "Strongly normalising; corresponds (Curry–Howard) to the implicational fragment of minimal intuitionistic logic.",
        extends: ["Curry–Howard correspondence"],
        tags: ["typed-lambda"],
        xref: ["computer-science"],
      },
      {
        name: "System F",
        description: "Second-order polymorphic lambda calculus.",
        formalDef: "types $\\tau ::= \\alpha \\mid \\tau\\to\\tau \\mid \\forall \\alpha.\\tau$; term abstraction $\\Lambda \\alpha.t$ over types.",
        keyResults: "Girard (1972) and Reynolds (1974); strongly normalising; expressively captures all functions provably total in second-order arithmetic.",
        extends: ["Simply typed λ-calculus (STLC)"],
        tags: ["polymorphism", "landmark"],
        historical: true,
        xref: ["computer-science"],
      },
      {
        name: "Dependent types",
        description: "Types that may depend on terms.",
        formalDef: "$\\Pi$-type: $\\Pi x:A.B(x)$ generalises $A\\to B$; $\\Sigma$-type: $\\Sigma x:A.B(x)$ generalises $A\\times B$.",
        keyResults: "Express predicates ($A \\to \\mathrm{Type}$), invariants and proofs internally; basis of Coq, Agda, Lean, Idris.",
        extends: ["System F"],
        tags: ["foundation"],
        xref: ["computer-science"],
      },
      {
        name: "Martin-Löf type theory",
        description: "Constructive type theory with intuitionistic foundations.",
        formalDef: "$\\Pi,\\Sigma,+,\\mathbb{N},\\mathrm{Id},U$ as basic types with introduction, elimination, and computation rules.",
        keyResults: "Foundational system for constructive mathematics; basis of Agda; predicative version uses a hierarchy of universes $U_0 : U_1 : U_2 :\\dots$.",
        extends: ["Dependent types"],
        tags: ["constructive", "landmark"],
        historical: true,
        xref: ["computer-science", "mathematics"],
      },
      {
        name: "Calculus of Constructions",
        description: "Coquand–Huet's impredicative dependent type theory.",
        formalDef: "Pure Type System with sorts $\\{\\mathrm{Prop},\\mathrm{Type}\\}$ and rules permitting impredicative quantification over $\\mathrm{Prop}$.",
        keyResults: "Basis of Coq's kernel; strongly normalising; extended to the Calculus of Inductive Constructions for usable mathematics.",
        extends: ["Dependent types"],
        tags: ["impredicative"],
        xref: ["computer-science"],
        historical: true,
      },
      {
        name: "Homotopy type theory (HoTT)",
        description: "Type theory with types as $\\infty$-groupoids.",
        formalDef: "extends Martin-Löf type theory by interpreting identity types as path spaces in an $(\\infty,1)$-topos; equality is structure, not property.",
        keyResults: "Voevodsky's univalent foundations programme (2009–); a new foundation for mathematics with computer-checked proofs.",
        extends: ["Martin-Löf type theory"],
        tags: ["foundations", "landmark"],
        historical: true,
        xref: ["mathematics"],
      },
      {
        name: "Univalence axiom",
        description: "Equivalent types are equal.",
        formalDef: "$\\mathrm{ua} : (A \\simeq B) \\simeq (A =_U B)$; identification of types is the same as type-equivalence.",
        keyResults: "Voevodsky (2010); justified semantically by simplicial-set model and cubical model; computationally realised in cubical type theory.",
        extends: ["Homotopy type theory (HoTT)"],
        tags: ["axiom", "landmark"],
        historical: true,
        xref: ["mathematics"],
      },
      {
        name: "Identity types",
        description: "Propositional equality as a type former.",
        formalDef: "$\\mathrm{Id}_A(a,b)$ formed for $a,b:A$; introduction by reflexivity $\\mathrm{refl}_a : \\mathrm{Id}_A(a,a)$; elimination by path induction.",
        keyResults: "In HoTT, paths in identity types correspond to homotopies; underlies the proof-irrelevant vs proof-relevant distinction.",
        extends: ["Martin-Löf type theory"],
        tags: ["equality"],
      },
      {
        name: "Inductive types",
        description: "Types defined by initial-algebra introduction rules.",
        formalDef: "$\\mathbb{N} : \\mathrm{Type}$ generated by $0:\\mathbb{N}$ and $\\mathrm{succ}:\\mathbb{N}\\to \\mathbb{N}$; eliminator $\\mathrm{rec}$ encodes induction.",
        keyResults: "Standard mechanism for data types in modern proof assistants; W-types subsume all strictly positive inductive definitions.",
        extends: ["Martin-Löf type theory"],
        tags: ["data-types"],
        xref: ["computer-science"],
      },
      {
        name: "Coinductive types",
        description: "Types defined by terminal-coalgebra elimination rules.",
        formalDef: "streams $\\mathrm{Stream}\\,A$ with destructors $\\mathrm{head}:\\mathrm{Stream}\\,A \\to A$ and $\\mathrm{tail}:\\mathrm{Stream}\\,A\\to \\mathrm{Stream}\\,A$.",
        keyResults: "Capture infinite/lazy data; bisimulation as canonical equality; basis of reactive and stream programming.",
        extends: ["Inductive types"],
        tags: ["data-types"],
      },
      {
        name: "Curry–Howard isomorphism",
        description: "Types are propositions; programs are proofs.",
        formalDef: "intuitionistic propositional logic $\\leftrightarrow$ STLC; FOL $\\leftrightarrow$ dependent type theory; classical logic $\\leftrightarrow$ control operators.",
        keyResults: "Foundation of modern proof assistants; explains why constructive proofs extract programs.",
        extends: ["Simply typed λ-calculus (STLC)"],
        tags: ["correspondence", "landmark"],
        historical: true,
        xref: ["computer-science"],
      },
      {
        name: "Linear types",
        description: "Type discipline tracking resource usage.",
        formalDef: "type system based on linear logic with $\\multimap,\\otimes,!$; variables of linear type are used exactly once.",
        keyResults: "Used in Rust's ownership system, Haskell's Linear Types extension, and quantum programming languages.",
        extends: ["Linear logic", "Curry–Howard correspondence"],
        tags: ["resource"],
        xref: ["computer-science"],
      },
      {
        name: "Subtyping",
        description: "Subset relation on types as polymorphism.",
        formalDef: "judgement $A <: B$ with rule $\\dfrac{\\Gamma \\vdash t:A\\quad A<: B}{\\Gamma \\vdash t : B}$.",
        keyResults: "Adds expressiveness at the cost of decidable type-checking in some calculi; foundational for object-oriented type systems.",
        extends: ["Simply typed λ-calculus (STLC)"],
        tags: ["polymorphism"],
        xref: ["computer-science"],
      },
      {
        name: "Hindley–Milner type inference",
        description: "Principal-type inference for let-polymorphic ML.",
        formalDef: "type system with prenex polymorphism and Algorithm W: unify constraints generated from terms to compute the most general type.",
        keyResults: "Decidable type inference in time exponential in worst case but linear in practice; backbone of ML, Haskell, OCaml.",
        extends: ["System F"],
        tags: ["inference", "landmark"],
        historical: true,
        xref: ["computer-science"],
      },
      {
        name: "Refinement types",
        description: "Types qualified by logical predicates.",
        formalDef: "type $\\{x : A \\mid \\varphi(x)\\}$ of $A$-elements satisfying $\\varphi$; type-checking reduces to SMT solving.",
        keyResults: "Liquid Haskell and Liquid Types in F#; bring lightweight verification into ordinary functional programming.",
        extends: ["Dependent types"],
        tags: ["verification"],
        xref: ["computer-science"],
      },
      {
        name: "Type-level computation",
        description: "Computing with types as values.",
        formalDef: "languages such as Haskell (with TypeFamilies/DataKinds) and Idris allow ordinary functions to operate on types; in dependent types this is just ordinary computation.",
        keyResults: "Enables type-safe APIs (vectors with length-indexed types, dimension-checked tensors); a key practical use of dependent types.",
        extends: ["Dependent types"],
        tags: ["meta"],
        xref: ["computer-science"],
      },
    ],
  },

  // ── Family 16 — Category Theory & Logic ─────────────────────────────────
  {
    slug: "category-theory-logic",
    number: 16,
    name: "Category Theory & Logic",
    blurb: "Logic interpreted in categories — topoi, internal languages, adjunctions and the categorical semantics of type theory.",
    section: "D",
    color: "emerald",
    entries: [
      {
        name: "Topos theory",
        description: "Categories that behave like the category of sets.",
        formalDef: "an (elementary) topos is a cartesian closed category with a subobject classifier $\\Omega$; every Grothendieck topos arises as the category of sheaves on a site.",
        keyResults: "Lawvere–Tierney; internal logic is intuitionistic higher-order; sheaf semantics generalises Kripke and Beth semantics.",
        extends: ["Heyting algebra"],
        tags: ["categorical", "landmark"],
        historical: true,
        xref: ["mathematics"],
      },
      {
        name: "Subobject classifier",
        description: "Generic representation of subobjects.",
        formalDef: "object $\\Omega$ with a 'true' arrow $\\top : 1 \\to \\Omega$ such that every monomorphism $S\\hookrightarrow X$ arises uniquely as a pullback of $\\top$ along a characteristic map $\\chi_S : X \\to \\Omega$.",
        keyResults: "In $\\mathbf{Set}$, $\\Omega = \\{0,1\\}$; in a sheaf topos, $\\Omega$ is a Heyting algebra of open subobjects.",
        extends: ["Topos theory"],
        tags: ["categorical"],
        xref: ["mathematics"],
      },
      {
        name: "Internal language",
        description: "Type-theoretic language interpreted in a category.",
        formalDef: "objects $\\to$ types; morphisms $\\to$ terms; pullbacks $\\to$ substitution; cartesian closed categories interpret simply typed lambda calculus; locally cartesian closed categories interpret dependent type theory.",
        keyResults: "Curry–Howard–Lambek correspondence: proofs / programs / morphisms; the internal language of a topos is intuitionistic higher-order logic.",
        extends: ["Topos theory"],
        tags: ["semantics"],
        xref: ["computer-science"],
      },
      {
        name: "Cartesian closed category",
        description: "Category with products and exponentials.",
        formalDef: "finite products and, for each pair $A,B$, an exponential $B^A$ with natural bijection $\\mathrm{Hom}(C\\times A, B) \\cong \\mathrm{Hom}(C, B^A)$.",
        keyResults: "Semantic counterpart of STLC; the category $\\mathbf{Set}$ is cartesian closed (exponentials are function spaces).",
        extends: ["Topos theory"],
        tags: ["categorical"],
        xref: ["computer-science", "mathematics"],
      },
      {
        name: "Lawvere theories",
        description: "Algebraic theories as categorical objects.",
        formalDef: "a Lawvere theory $\\mathcal{T}$ is a small category with finite products generated by a single object; a model is a product-preserving functor $\\mathcal{T}\\to \\mathbf{Set}$.",
        keyResults: "Lawvere (1963); unifies universal algebra; basis of operadic and PROP-style presentations of structures.",
        extends: ["Topos theory"],
        tags: ["algebraic"],
        xref: ["mathematics"],
        historical: true,
      },
      {
        name: "Adjoint functors",
        description: "Best-approximation pair between categories.",
        formalDef: "$F\\dashv G$ iff there is a natural isomorphism $\\mathrm{Hom}_\\mathcal{D}(FA,B)\\cong \\mathrm{Hom}_\\mathcal{C}(A,GB)$.",
        keyResults: "Quantifiers as adjoints to substitution (Lawvere); $\\exists \\dashv (-)^* \\dashv \\forall$ in hyperdoctrines; right adjoints preserve limits.",
        extends: ["Cartesian closed category"],
        tags: ["categorical", "landmark"],
        historical: true,
        xref: ["mathematics"],
      },
      {
        name: "Categorical semantics",
        description: "Logics and type theories interpreted in classes of categories.",
        formalDef: "interpret formulas as objects/subobjects, proofs as morphisms; soundness and completeness theorems relate syntactic categories to semantic ones.",
        keyResults: "Underlies the modern view of logic as fibration-theoretic structure; foundation of categorical proof theory.",
        extends: ["Internal language"],
        tags: ["semantics"],
        xref: ["mathematics", "computer-science"],
      },
      {
        name: "Sheaf semantics",
        description: "Truth-values varying continuously over a site.",
        formalDef: "topos of sheaves $\\mathrm{Sh}(\\mathcal{C},J)$ on a site $(\\mathcal{C},J)$; truth-value object $\\Omega$ is the sheaf of sieves.",
        keyResults: "Generalises Kripke and Beth semantics; gives forcing semantics for set theory and topological semantics for intuitionistic logic.",
        extends: ["Topos theory"],
        tags: ["semantics"],
        xref: ["mathematics"],
      },
      {
        name: "Geometric logic",
        description: "Fragment of FOL preserved by geometric morphisms.",
        formalDef: "formulas built from atomic predicates by $\\top, \\bot, \\wedge, \\bigvee_i, \\exists$ (no $\\neg,\\to,\\forall$).",
        keyResults: "Truth in geometric theories is preserved by inverse images of geometric morphisms of topoi; classifying topos for a geometric theory exists.",
        extends: ["Topos theory"],
        tags: ["fragment"],
        xref: ["mathematics"],
      },
      {
        name: "Categorical type theory",
        description: "Type-theoretic syntax as initial categorical structures.",
        formalDef: "syntactic category $\\mathcal{C}(T)$ of a type theory $T$ is initial among categories of the appropriate kind; soundness and completeness via the internal-language correspondence.",
        keyResults: "Underlies the Awodey–Warren and Hofmann–Streicher interpretations of HoTT; bridge between syntax and semantics.",
        extends: ["Categorical semantics"],
        tags: ["foundations"],
        xref: ["computer-science", "mathematics"],
      },
      {
        name: "Monads",
        description: "Functor + unit + multiplication encoding effects.",
        formalDef: "$T:\\mathcal{C}\\to \\mathcal{C}$ endofunctor with natural transformations $\\eta:1\\Rightarrow T$ and $\\mu : T^2 \\Rightarrow T$ satisfying the monad laws.",
        keyResults: "Moggi (1989): monads capture computational effects (state, exceptions, I/O) uniformly; backbone of effectful programming in Haskell.",
        extends: ["Adjoint functors"],
        tags: ["categorical", "computation"],
        xref: ["computer-science"],
        historical: true,
      },
      {
        name: "Yoneda lemma in logic",
        description: "Functor representability via the embedding into $\\mathbf{Set}^{\\mathcal{C}^{op}}$.",
        formalDef: "$\\mathrm{Nat}(\\mathrm{Hom}(-,A), F) \\cong F(A)$ for any presheaf $F$.",
        keyResults: "Encodes the principle that objects are determined by their generalised elements; ubiquitous in categorical logic and topos theory.",
        extends: ["Adjoint functors"],
        tags: ["categorical"],
        xref: ["mathematics"],
      },
    ],
  },

  // ── Family 17 — Philosophical Logic ─────────────────────────────────────
  {
    slug: "philosophical-logic",
    number: 17,
    name: "Philosophical Logic",
    blurb: "Where formal logic meets natural language, reference, vagueness, and the philosophy of logic itself.",
    section: "E",
    color: "green",
    entries: [
      {
        name: "Tarski's theory of truth",
        description: "Truth defined via the satisfaction relation for an object language.",
        formalDef: "convention T: an adequate truth-definition for $\\mathcal{L}$ implies all instances of '${\\ulcorner \\varphi \\urcorner}$ is true iff $p$' where $p$ is the metalanguage translation of $\\varphi$.",
        keyResults: "Tarski's undefinability theorem: no consistent extension of arithmetic can define its own truth predicate; founded modern semantics.",
        extends: ["Tarski's satisfaction"],
        tags: ["semantics", "landmark"],
        xref: ["philosophy"],
        historical: true,
      },
      {
        name: "Sense and reference",
        description: "Frege's twofold semantic theory.",
        formalDef: "every meaningful expression has a sense (Sinn — mode of presentation) and a reference (Bedeutung — object designated); sentences refer to truth-values and express thoughts.",
        keyResults: "Resolves the 'morning star = evening star' puzzle without identifying meaning with reference; foundational for philosophy of language.",
        extends: ["Russell's theory of descriptions"],
        tags: ["semantics", "landmark"],
        xref: ["philosophy"],
        historical: true,
      },
      {
        name: "Russell's theory of descriptions",
        description: "Definite descriptions analysed by quantifiers.",
        formalDef: "'the $F$ is $G$' parses as $\\exists x\\,(F(x)\\wedge \\forall y\\,(F(y)\\to y=x)\\wedge G(x))$.",
        keyResults: "Eliminates apparent reference to non-existents (e.g.\\ 'the present King of France'); paradigm of analysis-as-paraphrase.",
        extends: ["First-order logic"],
        tags: ["analytic", "landmark"],
        xref: ["philosophy"],
        historical: true,
      },
      {
        name: "Indicative vs subjunctive conditionals",
        description: "Two distinct conditionals in natural language.",
        formalDef: "'If Oswald didn't shoot Kennedy, someone else did' (indicative, true) vs 'If Oswald hadn't shot Kennedy, someone else would have' (subjunctive, contested).",
        keyResults: "Indicative conditionals close to material; subjunctive (counterfactual) conditionals analyzed by Lewis/Stalnaker via similarity.",
        extends: ["Material conditional", "Counterfactual logic (Lewis–Stalnaker)"],
        tags: ["conditional", "natural-language"],
        xref: ["philosophy"],
      },
      {
        name: "Counterfactuals (Lewis)",
        description: "Conditionals about non-actual scenarios.",
        formalDef: "$\\varphi \\Box{\\to}\\psi$ holds at $w$ iff every closest $\\varphi$-world to $w$ is a $\\psi$-world; closeness ordering $\\le_w$ between worlds.",
        keyResults: "Lewis (1973); centrepiece of analyses of causation, dispositions, and laws of nature.",
        extends: ["Counterfactual logic (Lewis–Stalnaker)"],
        tags: ["modal", "landmark"],
        xref: ["philosophy"],
        historical: true,
      },
      {
        name: "Vagueness and sorites",
        description: "Predicates like 'heap' or 'bald' lacking sharp boundaries.",
        formalDef: "sorites argument: 1 grain is not a heap; if $n$ grains is not a heap, $n+1$ is not; therefore no number of grains is a heap. Contradicts the existence of heaps.",
        keyResults: "Drives epistemicism, supervaluationism, degree theories, and contextualism; no consensus solution.",
        extends: ["Propositional logic"],
        tags: ["paradox", "contested"],
        status: "contested",
        xref: ["philosophy"],
      },
      {
        name: "Supervaluationism",
        description: "Vagueness as semantic underdetermination.",
        formalDef: "an utterance is true iff true on every admissible precisification; supertrue iff true on all, superfalse iff false on all.",
        keyResults: "Preserves classical logic in the supervaluations but truth fails to be compositional; central response to the sorites.",
        extends: ["Vagueness and sorites"],
        tags: ["semantics"],
        xref: ["philosophy"],
      },
      {
        name: "Epistemicism",
        description: "Vagueness as ignorance of a sharp cutoff.",
        formalDef: "every vague predicate has a sharp extension; vagueness is the speaker's ignorance of where the boundary falls.",
        keyResults: "Williamson's defence; preserves classical logic and bivalence; counterintuitive psychological commitments.",
        extends: ["Vagueness and sorites"],
        tags: ["epistemic", "contested"],
        status: "contested",
        xref: ["philosophy"],
      },
      {
        name: "Rigid designators",
        description: "Terms that refer to the same object in every possible world.",
        formalDef: "$t$ is rigid iff for every world $w$, $w \\models t = t'$ where $t'$ is the denotation of $t$ in the actual world.",
        keyResults: "Kripke's Naming and Necessity (1980): proper names are rigid; necessary identities like 'Hesperus = Phosphorus' a posteriori.",
        extends: ["System S5"],
        tags: ["reference", "landmark"],
        xref: ["philosophy"],
        historical: true,
      },
      {
        name: "Logical pluralism",
        description: "Multiple equally legitimate logical consequence relations.",
        formalDef: "Beall–Restall: $\\Gamma \\vDash_X \\varphi$ iff for every case $x\\in X$, if all of $\\Gamma$ are true in $x$ then $\\varphi$ is true in $x$; $X$ ranges over admissible case-types (possible worlds, situations, constructions).",
        keyResults: "Permits classical, intuitionistic, and relevance logic to coexist as correct accounts of consequence in different domains; contested.",
        extends: ["Propositional logic"],
        tags: ["philosophical", "contested"],
        status: "contested",
        xref: ["philosophy"],
      },
      {
        name: "Tonk (Prior)",
        description: "A pseudo-connective with inconsistent introduction/elimination rules.",
        formalDef: "$\\dfrac{\\varphi}{\\varphi\\,\\mathrm{tonk}\\,\\psi}\\;\\text{and}\\;\\dfrac{\\varphi\\,\\mathrm{tonk}\\,\\psi}{\\psi}$ yields $\\varphi \\vdash \\psi$ for all $\\varphi,\\psi$.",
        keyResults: "Prior (1960); shows that inference rules alone do not give meaning; Belnap (1962) replies with conservativity and uniqueness criteria.",
        extends: ["Natural deduction"],
        tags: ["paradox", "landmark"],
        historical: true,
        xref: ["philosophy"],
      },
      {
        name: "Material vs strict implication",
        description: "Truth-functional conditional vs necessity-based conditional.",
        formalDef: "material $\\varphi\\to\\psi \\equiv \\neg \\varphi \\vee \\psi$; strict $\\varphi \\fishhook \\psi \\equiv \\Box(\\varphi\\to\\psi)$.",
        keyResults: "Strict implication avoids some material-implication paradoxes but introduces its own (necessary consequents follow from anything); motivated C.\\,I.\\ Lewis's modal logics.",
        extends: ["Material conditional", "System S5"],
        tags: ["conditional"],
        xref: ["philosophy"],
        historical: true,
      },
      {
        name: "Liar paradox",
        description: "Self-referential sentence claiming its own falsity.",
        formalDef: "$L \\leftrightarrow \\neg \\mathrm{T}(\\ulcorner L \\urcorner)$ in a language with a truth predicate $\\mathrm{T}$.",
        keyResults: "Drives Tarskian hierarchies, Kripke's fixed-point theory, paraconsistent treatments, and revision theories of truth; no consensus solution.",
        extends: ["Tarski's theory of truth"],
        tags: ["paradox", "contested"],
        status: "contested",
        xref: ["philosophy"],
        historical: true,
      },
      {
        name: "Quine on logical truth",
        description: "Logical truth as truth under all reinterpretations of non-logical vocabulary.",
        formalDef: "$\\varphi$ is logically true iff every uniform substitution of its non-logical lexicon yields a true sentence.",
        keyResults: "Quine's substitutional account of logical truth; basis of his rejection of the analytic/synthetic distinction.",
        extends: ["First-order logic"],
        tags: ["philosophical"],
        xref: ["philosophy"],
        historical: true,
      },
      {
        name: "Logical constants",
        description: "What makes a vocabulary item logical.",
        formalDef: "candidate criteria: invariance under permutations of the domain (Tarski–Sher), topic-neutrality, role in valid inference, indispensability for expressing structure.",
        keyResults: "No consensus criterion; central question in the philosophy of logic.",
        extends: ["Quine on logical truth"],
        tags: ["philosophical", "contested"],
        status: "contested",
        xref: ["philosophy"],
      },
      {
        name: "Paradox of the Knower",
        description: "Self-referential paradox for knowledge.",
        formalDef: "if $K\\varphi \\to \\varphi$ and $K(K\\varphi \\to \\varphi)$ are theorems plus a self-referential 'this sentence is not known', contradiction follows.",
        keyResults: "Kaplan–Montague (1960); analogue of the Liar within epistemic logic; constrains the formal theory of knowledge.",
        extends: ["Liar paradox", "Knowledge operator"],
        tags: ["paradox"],
        xref: ["philosophy"],
        historical: true,
      },
    ],
  },

  // ── Family 18 — History, Paradoxes & Landmark Results ────────────────────
  {
    slug: "history-landmarks",
    number: 18,
    name: "History, Paradoxes & Landmark Results",
    blurb: "The historical arc of logic and its great theorems — from Aristotle to Gödel and beyond.",
    section: "E",
    color: "amber",
    entries: [
      {
        name: "Aristotle's syllogistic",
        description: "First systematic theory of deductive inference.",
        formalDef: "valid moods of categorical syllogisms over A, E, I, O propositions; e.g.\\ Barbara: $\\forall x(M(x)\\to P(x)),\\ \\forall x(S(x)\\to M(x)) \\vdash \\forall x(S(x)\\to P(x))$.",
        keyResults: "Prior Analytics (c.\\ 350 BCE); dominant logic in the West for two millennia; superseded by Frege.",
        extends: [],
        tags: ["ancient", "landmark"],
        historical: true,
        xref: ["philosophy"],
      },
      {
        name: "Stoic propositional logic",
        description: "Hellenistic logic of conditionals and propositions.",
        formalDef: "five indemonstrable argument schemata, including modus ponens, modus tollens, and disjunctive syllogism over propositional axiōmata.",
        keyResults: "Chrysippus (c.\\ 280–207 BCE); rediscovered as propositional logic in the 19th century after centuries of obscurity.",
        extends: ["Aristotle's syllogistic"],
        tags: ["ancient", "propositional"],
        historical: true,
        xref: ["philosophy"],
      },
      {
        name: "Medieval insolubilia",
        description: "Scholastic treatments of self-referential paradoxes.",
        formalDef: "study of the Liar and related paradoxes by Bradwardine, Buridan, and others; involves restricting self-reference or distinguishing supposition types.",
        keyResults: "Bradwardine (c.\\ 1320): a sentence asserting its own falsity also implicitly asserts its own truth; modern revival in Read and Spade.",
        extends: ["Aristotle's syllogistic"],
        tags: ["medieval", "paradox"],
        historical: true,
        xref: ["philosophy"],
      },
      {
        name: "Leibniz's characteristica universalis",
        description: "Project for a universal logical calculus.",
        formalDef: "envisaged a symbolic language ('characteristica') whose calculus ratiocinator would mechanically settle all disputes; never realised.",
        keyResults: "Anticipated Boolean algebra, formal logic, and the Frege–Russell programme; inspirational rather than technical.",
        extends: ["Aristotle's syllogistic"],
        tags: ["historical", "project"],
        historical: true,
        xref: ["philosophy"],
      },
      {
        name: "Boole's algebra of logic",
        description: "First algebraic treatment of propositional reasoning.",
        formalDef: "logic as algebra over $\\{0,1\\}$ with operations corresponding to AND, OR, NOT; class-calculus equivalent.",
        keyResults: "Boole's The Laws of Thought (1854); foundation of Boolean algebra and modern digital circuit design.",
        extends: ["Aristotle's syllogistic"],
        tags: ["landmark", "algebraic"],
        historical: true,
        xref: ["mathematics", "computer-science"],
      },
      {
        name: "Frege's Begriffsschrift",
        description: "First modern formal system of logic.",
        formalDef: "introduces predicate logic with quantifiers, identity, functions of arguments, a 2D notation, and proof rules sufficient for arithmetic.",
        keyResults: "Frege (1879); the birth of modern logic; led to Russell's paradox and the foundational crisis.",
        extends: ["Boole's algebra of logic"],
        tags: ["landmark"],
        historical: true,
        xref: ["mathematics", "philosophy"],
      },
      {
        name: "Principia Mathematica",
        description: "Russell and Whitehead's three-volume reconstruction of mathematics.",
        formalDef: "ramified type theory + axioms of infinity, choice, and reducibility; proves $1+1=2$ at *54.43 of Volume I.",
        keyResults: "Russell–Whitehead (1910–13); influential despite eventually being overtaken by ZFC and Hilbert-style formalism.",
        extends: ["Frege's Begriffsschrift", "Russell's paradox"],
        tags: ["landmark"],
        historical: true,
        xref: ["mathematics"],
      },
      {
        name: "Hilbert's programme",
        description: "Plan to ground mathematics by finitary consistency proofs.",
        formalDef: "encode all mathematics in a formal system $T$, then prove $T$'s consistency by finitary methods within a weak metatheory.",
        keyResults: "Hilbert (1920s); Gödel's second incompleteness theorem showed the original programme is impossible; partial revivals via ordinal analysis and reverse mathematics.",
        extends: ["Frege's Begriffsschrift"],
        tags: ["foundational", "landmark"],
        historical: true,
        xref: ["mathematics", "philosophy"],
      },
      {
        name: "Gödel's first incompleteness theorem",
        description: "Any consistent recursively axiomatised theory containing arithmetic has true unprovable sentences.",
        formalDef: "for every consistent recursively axiomatised $T\\supseteq Q$ (Robinson arithmetic), there is a sentence $G_T$ with $T\\nvdash G_T$ and $T\\nvdash \\neg G_T$; $G_T$ encodes 'I am not provable in $T$'.",
        keyResults: "Gödel (1931); destroys naive Hilbert programme; foundational result of mathematical logic.",
        extends: ["First-order logic"],
        tags: ["theorem", "landmark"],
        historical: true,
        xref: ["mathematics", "philosophy"],
      },
      {
        name: "Gödel's second incompleteness theorem",
        description: "No consistent theory containing arithmetic proves its own consistency.",
        formalDef: "for $T$ as above, $T \\nvdash \\mathrm{Con}(T)$, where $\\mathrm{Con}(T)\\equiv \\neg \\exists p\\,\\mathrm{Prf}_T(p,\\ulcorner 0=1\\urcorner)$.",
        keyResults: "Gödel (1931); rules out finitary consistency proofs of strong systems; central to the limitations of formal foundations.",
        extends: ["Gödel's first incompleteness theorem"],
        tags: ["theorem", "landmark"],
        historical: true,
        xref: ["mathematics", "philosophy"],
      },
      {
        name: "Tarski's undefinability theorem",
        description: "Arithmetic truth is not definable in arithmetic.",
        formalDef: "there is no formula $\\mathrm{T}(x)$ in the language of $\\mathrm{PA}$ such that for every sentence $\\varphi$, $\\mathrm{PA}\\vdash \\mathrm{T}(\\ulcorner \\varphi \\urcorner)\\leftrightarrow \\varphi$.",
        keyResults: "Tarski (1933); semantic counterpart of Gödel's theorem; motivates the hierarchy of metalanguages.",
        extends: ["Gödel's first incompleteness theorem", "Tarski's theory of truth"],
        tags: ["theorem", "landmark"],
        historical: true,
        xref: ["mathematics", "philosophy"],
      },
      {
        name: "Church's theorem",
        description: "First-order logic is undecidable.",
        formalDef: "there is no algorithm that decides, for an arbitrary FOL sentence $\\varphi$, whether $\\vdash \\varphi$.",
        keyResults: "Church (1936); proved independently of Turing via the lambda calculus; settles Hilbert's Entscheidungsproblem.",
        extends: ["First-order logic", "Halting problem"],
        tags: ["theorem", "landmark"],
        historical: true,
        xref: ["computer-science", "mathematics"],
      },
      {
        name: "Curry's paradox",
        description: "Self-referential paradox derivable from naive comprehension and contraction.",
        formalDef: "let $C \\leftrightarrow (C \\to \\varphi)$; then $C \\to \\varphi$ is provable using contraction, hence $C$, hence $\\varphi$ for arbitrary $\\varphi$.",
        keyResults: "Curry (1942); shows contraction is the structural culprit in naive set theory; motivates substructural responses.",
        extends: ["Russell's paradox"],
        tags: ["paradox", "landmark"],
        historical: true,
        xref: ["philosophy"],
      },
      {
        name: "Berry's paradox",
        description: "Self-referential paradox about definability in finitely many words.",
        formalDef: "consider 'the smallest natural number not nameable in fewer than fourteen English words' — which is itself named by a thirteen-word phrase.",
        keyResults: "Cited by Russell (1908) and reformulated arithmetically by Chaitin in algorithmic information theory.",
        extends: ["Russell's paradox"],
        tags: ["paradox"],
        historical: true,
        xref: ["philosophy"],
      },
      {
        name: "Cohen's forcing & CH",
        description: "Independence of the continuum hypothesis from ZFC.",
        formalDef: "construct a generic extension $M[G]$ of a countable transitive model $M$ of ZFC + V=L via the partial order $\\mathrm{Fn}(\\aleph_2\\times \\omega,2)$; in $M[G]$, $2^{\\aleph_0}\\ge \\aleph_2$, so $\\neg \\mathrm{CH}$.",
        keyResults: "Cohen (1963); awarded the Fields Medal; founded modern set theory and the forcing method.",
        extends: ["Forcing", "Continuum hypothesis"],
        tags: ["landmark"],
        historical: true,
        xref: ["mathematics"],
      },
      {
        name: "Lindström's theorem",
        description: "First-order logic is maximal under compactness and Löwenheim–Skolem.",
        formalDef: "any abstract logic extending FOL that is countably compact and has the downward Löwenheim–Skolem property is equivalent in expressive power to FOL.",
        keyResults: "Lindström (1969); explains the centrality of FOL in mathematics; pillar of abstract model theory.",
        extends: ["Compactness theorem", "Löwenheim–Skolem theorem"],
        tags: ["theorem", "landmark"],
        historical: true,
      },
      {
        name: "Robinson arithmetic Q",
        description: "Weakest finitely axiomatised essentially undecidable arithmetic.",
        formalDef: "axioms: $\\neg(0 = Sx)$; $Sx=Sy \\to x=y$; $x\\ne 0 \\to \\exists y\\,(x=Sy)$; $x+0=x$, $x+Sy=S(x+y)$; $x\\cdot 0=0$, $x\\cdot Sy = x\\cdot y + x$.",
        keyResults: "Tarski–Mostowski–Robinson (1953); any consistent extension of Q is undecidable; the natural floor for Gödel-style arguments.",
        extends: ["First-order logic"],
        tags: ["arithmetic"],
        historical: true,
        xref: ["mathematics"],
      },
      {
        name: "Solovay's completeness theorem (GL)",
        description: "$\\mathrm{GL}$ is the modal logic of provability in PA.",
        formalDef: "$\\mathrm{GL}\\vdash \\varphi$ iff for every arithmetical interpretation $\\ast$, $\\mathrm{PA}\\vdash \\varphi^\\ast$.",
        keyResults: "Solovay (1976); elegant modal characterisation of arithmetic provability; founded modern provability logic.",
        extends: ["Provability logic (GL)"],
        tags: ["theorem", "landmark"],
        historical: true,
        xref: ["mathematics"],
      },
    ],
  },
];
