import type { Family } from "./types";

export const FAMILIES_1_8: Family[] = [
  // ── Family 1 — Phonetics ──────────────────────────────────────────────────
  {
    slug: "phonetics",
    number: 1,
    name: "Phonetics",
    blurb: "The physical sounds of speech — articulation, acoustics, perception.",
    section: "A",
    color: "blue",
    entries: [
      {
        name: "Articulatory phonetics",
        description: "How speech sounds are produced by the vocal tract.",
        keyFact: "Sounds are classified by airstream mechanism, voicing, place of articulation, and manner of articulation.",
        tags: ["phonetics", "articulation"],
      },
      {
        name: "Acoustic phonetics",
        description: "The physical sound waves of speech and how they are measured.",
        keyFact: "Vowels are characterized by their first two formants $F_1$ (height) and $F_2$ (backness); higher $F_1$ = lower vowel.",
        notation: "F_1, F_2, F_3",
        example: "[i] has low $F_1$ (~280 Hz) and high $F_2$ (~2250 Hz); [ɑ] has high $F_1$ (~700 Hz) and low $F_2$ (~1100 Hz).",
        tags: ["phonetics", "acoustic", "formants"],
        xref: ["statistics"],
      },
      {
        name: "Auditory phonetics",
        description: "How the ear processes and the brain perceives speech sounds.",
        keyFact: "Categorical perception: listeners hear the continuous acoustic space as discrete phonemic categories, even when the cues vary continuously.",
        example: "VOT (voice onset time) for English /ba/ vs /pa/: listeners flip from 'b' to 'p' at ~30ms, not gradually.",
        tags: ["phonetics", "perception", "VOT"],
      },
      {
        name: "Voice onset time (VOT)",
        description: "The time between the release of a stop consonant and the onset of voicing.",
        keyFact: "Languages differ in where they place phonemic boundaries on the VOT continuum: English /b/ ~0–30ms, /p/ ~50ms+; Spanish /b/ is prevoiced (negative VOT).",
        notation: "VOT \\in (-100, +100)\\,\\text{ms}",
        tags: ["phonetics", "VOT", "stops"],
      },
      {
        name: "Cardinal vowels (Daniel Jones, 1917)",
        description: "Reference points for vowel quality independent of any language.",
        keyFact: "Eight primary cardinal vowels define the extremes of vowel space: [i e ɛ a ɑ ɔ o u]. Any vowel can be located relative to them.",
        tags: ["phonetics", "vowels", "cardinal"],
      },
      {
        name: "Coarticulation",
        description: "Adjacent speech sounds influence each other's articulation.",
        keyFact: "The /k/ in 'key' [kʲi] is more fronted than the /k/ in 'caw' [kɑ] because the tongue anticipates the following vowel.",
        tags: ["phonetics", "coarticulation"],
      },
      {
        name: "Suprasegmentals",
        description: "Prosodic features that span more than one segment: pitch, length, loudness, stress.",
        keyFact: "Stress, tone, intonation, and length are suprasegmental because they're properties of syllables or whole utterances, not individual phonemes.",
        tags: ["phonetics", "prosody"],
      },
      {
        name: "Tone",
        description: "Pitch contrasts that carry lexical meaning.",
        keyFact: "Mandarin has 4 tones (plus neutral); 'ma' means mother/hemp/horse/scold depending on tone. ~60–70% of the world's languages are tonal.",
        example: "Mandarin: mā (high) 妈 'mother', má (rising) 麻 'hemp', mǎ (dipping) 马 'horse', mà (falling) 骂 'scold'.",
        tags: ["phonetics", "tone", "prosody"],
      },
      {
        name: "Intonation",
        description: "Pitch contour over a phrase, signaling meaning or attitude.",
        keyFact: "English uses rising intonation for yes-no questions ('Coming?') and falling for declaratives ('Coming.') — but languages differ.",
        tags: ["phonetics", "prosody"],
      },
      {
        name: "Voice quality",
        description: "Long-term laryngeal settings: modal, breathy, creaky, falsetto, harsh.",
        keyFact: "Breathy and creaky voice are phonemic in many languages (Gujarati, Jalapa Mazatec). In English they are paralinguistic.",
        tags: ["phonetics", "phonation"],
      },
      {
        name: "Spectrogram",
        description: "Visualization of frequency vs time intensity, the workhorse tool of acoustic analysis.",
        keyFact: "Vowel formants show as dark horizontal bands; fricatives show as broadband noise; stops show as silent gaps + bursts.",
        tags: ["phonetics", "acoustic", "tools"],
      },
      {
        name: "Source-filter theory",
        description: "Speech = a sound source (vocal folds or noise) shaped by a filter (vocal tract resonances).",
        keyFact: "The vocal folds produce a buzz of harmonics; vocal-tract shape amplifies certain frequencies — those peaks are the formants.",
        tags: ["phonetics", "acoustic", "theory"],
      },
    ],
  },

  // ── Family 2 — Phonology ─────────────────────────────────────────────────
  {
    slug: "phonology",
    number: 2,
    name: "Phonology",
    blurb: "The abstract sound system — phonemes, features, rules.",
    section: "A",
    color: "sky",
    entries: [
      {
        name: "Phoneme",
        description: "The smallest contrastive unit of sound in a language.",
        keyFact: "Two sounds are separate phonemes iff swapping one for the other can change meaning. English /p/ vs /b/ are phonemes (pat vs bat); aspirated [pʰ] vs unaspirated [p] are allophones of /p/.",
        tags: ["phonology", "phoneme"],
      },
      {
        name: "Allophone",
        description: "A predictable phonetic variant of a phoneme.",
        keyFact: "English /t/ has allophones [tʰ] (top), [t] (stop), [ɾ] (butter, NAm.), [ʔ] (button) — same phoneme, predictable contexts.",
        tags: ["phonology", "allophone"],
      },
      {
        name: "Minimal pair",
        description: "Two words differing in a single sound, proving phonemic contrast.",
        keyFact: "[pɪn] 'pin' vs [bɪn] 'bin' establish /p/ ≠ /b/ in English; [θɪn] 'thin' vs [sɪn] 'sin' establish /θ/ ≠ /s/.",
        example: "Spanish /r/ vs /ɾ/: 'perro' [pero] 'dog' vs 'pero' [peɾo] 'but'.",
        tags: ["phonology", "phoneme", "minimal-pair"],
      },
      {
        name: "Distinctive features",
        description: "Binary phonetic primitives (±voice, ±nasal, ±continuant) used to define natural classes.",
        keyFact: "Jakobson/Halle/Chomsky-style: every phoneme decomposes into a feature bundle. /p/ = [−voice, −continuant, +labial, −nasal]; /b/ differs only in [+voice].",
        notation: "[+\\text{voice}, -\\text{cont}, +\\text{lab}, -\\text{nas}]",
        tags: ["phonology", "features"],
      },
      {
        name: "Syllable structure (CV, CVC, CCVCC)",
        description: "How phonemes group into syllables; languages have varying allowed shapes.",
        keyFact: "CV is the only universally permitted shape. Japanese is strictly (C)V(n); English allows up to CCCVCCCC (e.g., 'strengths' /stɹɛŋkθs/).",
        notation: "\\sigma \\to (Onset)\\,Rhyme;\\ Rhyme \\to Nucleus\\,(Coda)",
        tags: ["phonology", "syllable"],
      },
      {
        name: "Sonority hierarchy",
        description: "Universal ranking of segment sonority that constrains syllable shape.",
        keyFact: "Sonority Sequencing Principle: sonority rises monotonically to the nucleus and falls after. Vowels > glides > liquids > nasals > fricatives > stops.",
        tags: ["phonology", "syllable", "sonority"],
      },
      {
        name: "Phonotactics",
        description: "Language-specific constraints on legal sound sequences.",
        keyFact: "English allows /spr-/ ('spring') but not /sbr-/; Polish allows /pʂ-/ ('przy'); Japanese forbids most consonant clusters entirely.",
        tags: ["phonology", "phonotactics"],
      },
      {
        name: "Assimilation",
        description: "A sound becomes more like an adjacent sound.",
        keyFact: "English plural 'cats' [kæts] (voiceless after voiceless) vs 'dogs' [dɔɡz] (voiced after voiced) — assimilation of voice.",
        tags: ["phonology", "process", "assimilation"],
      },
      {
        name: "Dissimilation",
        description: "A sound becomes less like a nearby sound.",
        keyFact: "Latin 'peregrinus' → Spanish 'peregrino' but English 'pilgrim' — /r/…/r/ dissimilated to /l/…/r/.",
        tags: ["phonology", "process", "dissimilation"],
      },
      {
        name: "Vowel harmony",
        description: "Vowels in a word agree on some feature (frontness, rounding, height).",
        keyFact: "Turkish: vowels in suffixes match the root vowel for backness and rounding. 'ev-ler' (houses, front) but 'kız-lar' (girls, back).",
        example: "Hungarian dative suffix: ház-nak 'to the house' (back), kéz-nek 'to the hand' (front).",
        tags: ["phonology", "vowel-harmony"],
      },
      {
        name: "Optimality Theory (OT)",
        description: "Phonology as the selection of an optimal output from candidates, by ranked violable constraints (Prince & Smolensky 1993).",
        keyFact: "Output = candidate that least violates the highest-ranked constraint. Languages differ only in constraint ranking, not the constraint inventory.",
        notation: "GEN \\to \\{\\text{candidates}\\} \\xrightarrow{EVAL: C_1 \\gg C_2 \\gg \\cdots} \\text{winner}",
        tags: ["phonology", "OT", "theory"],
        xref: ["computer-science"],
      },
      {
        name: "Underlying representation (UR)",
        description: "The abstract stored form of a morpheme before phonological rules apply.",
        keyFact: "English plural is /-z/ underlyingly; surface allomorphs [s], [z], [ɪz] are derived by assimilation and epenthesis rules.",
        notation: "/z/ \\to [s]/[-\\text{voi}]\\_\\#",
        tags: ["phonology", "UR"],
      },
      {
        name: "Generative phonology (SPE)",
        description: "Chomsky & Halle (1968): phonology as ordered rewrite rules over feature matrices.",
        keyFact: "Rules of form A → B / C __ D apply in a fixed order from underlying representation to surface form.",
        tags: ["phonology", "SPE", "history"],
      },
      {
        name: "Autosegmental phonology",
        description: "Goldsmith (1976): tones, length, nasality are on separate tiers from segments.",
        keyFact: "Tones float independently of segments and are linked by association lines. Explains tone shifting, contour tones, and floating tones.",
        tags: ["phonology", "tone", "autosegmental"],
      },
    ],
  },

  // ── Family 3 — Morphology ────────────────────────────────────────────────
  {
    slug: "morphology",
    number: 3,
    name: "Morphology",
    blurb: "Word structure — morphemes, inflection, derivation, productivity.",
    section: "A",
    color: "cyan",
    entries: [
      {
        name: "Morpheme",
        description: "The smallest meaning-bearing unit.",
        keyFact: "'Unbreakable' = un- (negative) + break (root) + -able (capability). Three morphemes; one word.",
        tags: ["morphology", "morpheme"],
      },
      {
        name: "Free vs bound morphemes",
        description: "Free morphemes can stand alone as words; bound morphemes cannot.",
        keyFact: "'Cat', 'run', 'happy' are free. '-s', 'un-', '-ness' are bound. Latin and Greek roots like 'bio-' and 'cardi-' are bound roots.",
        tags: ["morphology", "morpheme"],
      },
      {
        name: "Inflection",
        description: "Modification of a word to express grammatical category (tense, number, case).",
        keyFact: "Inflection doesn't change part of speech or core meaning: 'walks', 'walked', 'walking' are all the same verb. Latin had 6 cases; Finnish has 15.",
        tags: ["morphology", "inflection"],
      },
      {
        name: "Derivation",
        description: "Word-formation processes that create new lexical items.",
        keyFact: "Derivation often changes part of speech and meaning: 'happy' (Adj) → 'happiness' (N) → 'unhappiness' (N).",
        tags: ["morphology", "derivation"],
      },
      {
        name: "Allomorph",
        description: "Phonologically conditioned variants of the same morpheme.",
        keyFact: "English plural /-z/ has allomorphs [s] (cats), [z] (dogs), [ɪz] (buses); negative 'in-' becomes 'im-' before bilabials (impossible).",
        tags: ["morphology", "allomorph"],
      },
      {
        name: "Compounding",
        description: "Forming a new word from two free morphemes.",
        keyFact: "English compounds are typically right-headed: 'doghouse' is a kind of house. German excels: 'Donaudampfschifffahrtsgesellschaftskapitän'.",
        tags: ["morphology", "compounding"],
      },
      {
        name: "Affixation: prefix, suffix, infix, circumfix",
        description: "Bound morphemes attaching before, after, inside, or surrounding a root.",
        keyFact: "Prefix: 're-do'. Suffix: 'walk-ed'. Infix: Tagalog 'sumulat' (su- + -m- + -ulat). Circumfix: German 'ge-mach-t' 'made'.",
        tags: ["morphology", "affix"],
      },
      {
        name: "Reduplication",
        description: "Repeating part or all of a word for grammatical effect.",
        keyFact: "Indonesian 'buku' = book, 'buku-buku' = books. Tagalog imperfective: 'bili' (buy) → 'bi-bili' (will buy).",
        tags: ["morphology", "reduplication"],
      },
      {
        name: "Suppletion",
        description: "An inflected form bears no phonological resemblance to the base.",
        keyFact: "English 'go/went', 'be/was/am'; French 'aller/vais/irai'. Suppletion clusters in high-frequency verbs (Zipf's law of suppletion).",
        tags: ["morphology", "suppletion"],
      },
      {
        name: "Agglutinative vs fusional vs isolating",
        description: "A classical morphological typology.",
        keyFact: "Isolating (Mandarin): one morpheme per word. Agglutinative (Turkish, Finnish): morphemes are clearly separable and each carries one meaning. Fusional (Latin, Russian): a single suffix encodes multiple categories.",
        example: "Turkish 'ev-ler-im-de' (house-PL-1SG-LOC, 'in my houses'); Latin 'amō' (love-1SG.PRES.IND.ACT).",
        tags: ["morphology", "typology"],
      },
      {
        name: "Polysynthesis",
        description: "Many morphemes per word; entire English sentences correspond to a single word.",
        keyFact: "Yupik 'tuntussuqatarniksaitengqiggtuq' = 'He had not yet said again that he was going to hunt reindeer.' Mohawk and Inuktitut also polysynthetic.",
        tags: ["morphology", "typology", "polysynthesis"],
      },
      {
        name: "Productivity",
        description: "How freely a morphological process forms new words.",
        keyFact: "English '-ness' is highly productive ('newness', 'sketchiness'); '-th' (warmth, length) is unproductive — *'redth' is unacceptable.",
        tags: ["morphology", "productivity"],
      },
      {
        name: "Templatic / nonconcatenative morphology",
        description: "Morphology by intercalation rather than concatenation.",
        keyFact: "Arabic root k-t-b 'write': 'kataba' (he wrote), 'kitāb' (book), 'kātib' (writer), 'maktūb' (written). Roots are consonantal templates; vowels inflect.",
        tags: ["morphology", "Semitic", "templatic"],
      },
      {
        name: "Zero derivation (conversion)",
        description: "Change of category without an overt affix.",
        keyFact: "English 'to email', 'a run', 'to chair (a meeting)' — same form, different category. Highly productive in modern English.",
        tags: ["morphology", "derivation", "conversion"],
      },
    ],
  },

  // ── Family 4 — Syntax ────────────────────────────────────────────────────
  {
    slug: "syntax",
    number: 4,
    name: "Syntax",
    blurb: "Sentence structure — phrases, dependencies, generative grammar.",
    section: "A",
    color: "teal",
    entries: [
      {
        name: "Constituent",
        description: "A group of words behaving as a unit for grammatical operations.",
        keyFact: "Tests for constituency: substitution (it/do so), movement (clefting, topicalization), coordination (X and Y), and standalone (answer to a wh-question).",
        tags: ["syntax", "constituent"],
      },
      {
        name: "Phrase structure rules",
        description: "Rewrite rules generating possible constituent structures.",
        keyFact: "S → NP VP; NP → (Det) N (PP); VP → V (NP) (PP). Context-free grammar formalization (Chomsky 1957).",
        notation: "S \\to NP\\ VP \\quad VP \\to V\\ NP",
        tags: ["syntax", "phrase-structure", "CFG"],
        xref: ["computer-science"],
      },
      {
        name: "X-bar theory",
        description: "All phrases have the same skeleton: specifier, head, complement.",
        keyFact: "XP → Spec X'; X' → X Comp. The same template covers NP, VP, AP, PP, IP, CP. Eliminates category-specific rules.",
        notation: "XP \\to \\text{Spec}\\ X';\\ X' \\to X\\ \\text{Comp}",
        tags: ["syntax", "X-bar", "GB"],
      },
      {
        name: "Government & Binding (GB)",
        description: "Chomsky 1981; modular syntax with sub-theories (case, theta, binding, bounding).",
        keyFact: "Replaced rule lists with universal principles + parameters. Sub-theories: X-bar, theta theory, case theory, binding theory, bounding theory, control theory.",
        tags: ["syntax", "GB", "history"],
      },
      {
        name: "Minimalist Program",
        description: "Chomsky 1995; syntax via Merge and Move; eliminate redundancy.",
        keyFact: "Two operations: External Merge (combine α and β) and Internal Merge (move). Economy principles: shortest move, fewest operations.",
        notation: "\\text{Merge}(\\alpha,\\beta) = \\{\\alpha,\\beta\\}",
        tags: ["syntax", "Minimalism"],
      },
      {
        name: "Dependency grammar",
        description: "Sentence structure as directed dependencies between words, not constituents.",
        keyFact: "Each word has one head; the verb is typically root. No phrase nodes. Universal Dependencies (UD) project annotates 200+ languages with the same scheme.",
        tags: ["syntax", "dependency", "UD"],
        xref: ["computer-science"],
      },
      {
        name: "Head Directionality Parameter",
        description: "Languages differ in whether heads precede or follow complements.",
        keyFact: "Head-initial (English, French): VO, prepositions. Head-final (Japanese, Korean, Turkish): OV, postpositions. ~95% of languages are consistent across phrase types.",
        tags: ["syntax", "typology", "parameter"],
      },
      {
        name: "Word order (SVO, SOV, VSO, ...)",
        description: "Basic ordering of subject, object, and verb in a clause.",
        keyFact: "SOV (~45%) and SVO (~42%) account for the vast majority. VSO ~9% (Arabic, Welsh). OSV/VOS/OVS each <1%. Greenberg (1963) cross-tabulated this with adposition and adjective order.",
        tags: ["syntax", "typology", "word-order"],
      },
      {
        name: "Movement / displacement",
        description: "A constituent appears far from where it is interpreted.",
        keyFact: "Wh-movement: 'What did you see __?' The wh-phrase originates as the object of 'see'. Tracked by traces or copies.",
        notation: "[CP\\ \\text{what}_i\\ [IP\\ \\text{you saw}\\ t_i]]",
        tags: ["syntax", "movement", "wh"],
      },
      {
        name: "Island constraints",
        description: "Domains out of which movement is forbidden (Ross 1967).",
        keyFact: "Cannot extract from: complex NPs, coordinate structures, sentential subjects, adjuncts, wh-islands. *'Who did you meet the man who saw __?'",
        tags: ["syntax", "islands", "constraints"],
      },
      {
        name: "Binding theory",
        description: "Conditions on the interpretation of pronouns, reflexives, and full NPs.",
        keyFact: "Principle A: anaphors bound in their domain. Principle B: pronouns free in their domain. Principle C: R-expressions free everywhere.",
        example: "John_i saw himself_i (A). John_i thinks Mary saw him_i (B). *He_i saw John_i (C violation).",
        tags: ["syntax", "binding", "GB"],
      },
      {
        name: "Case theory",
        description: "All overt NPs require structural case to be licensed.",
        keyFact: "Nominative assigned by finite T; accusative by transitive v/V; genitive by D. Case Filter: *NP with no case.",
        tags: ["syntax", "case", "GB"],
      },
      {
        name: "Theta theory",
        description: "Verbs assign thematic roles (agent, patient, goal, etc.) to arguments.",
        keyFact: "Theta Criterion: each argument bears one and only one theta-role; each theta-role is assigned to one and only one argument.",
        tags: ["syntax", "theta", "GB"],
      },
      {
        name: "Universal Grammar (UG)",
        description: "The hypothesized innate human capacity that constrains possible grammars.",
        keyFact: "Chomsky's poverty-of-the-stimulus argument: children acquire grammar despite incomplete and noisy input, so much must be innate. The exact content of UG is contested.",
        tags: ["syntax", "UG", "theory"],
        status: "contested",
      },
      {
        name: "Categorial grammar",
        description: "Each word has a functional type; combinations are by function application.",
        keyFact: "An intransitive verb is type S\\NP; a transitive verb is (S\\NP)/NP. Tightly tied to lambda calculus and Montague semantics.",
        notation: "(S\\backslash NP)/NP",
        tags: ["syntax", "categorial", "Lambek"],
        xref: ["mathematics", "computer-science"],
      },
      {
        name: "Head-driven phrase structure grammar (HPSG)",
        description: "Constraint-based, lexicalist grammar formalism (Pollard & Sag 1994).",
        keyFact: "All linguistic info on typed feature structures; syntactic and semantic information unified in one sign. No transformations.",
        tags: ["syntax", "HPSG", "constraint-based"],
        xref: ["computer-science"],
      },
    ],
  },

  // ── Family 5 — Semantics ─────────────────────────────────────────────────
  {
    slug: "semantics",
    number: 5,
    name: "Semantics",
    blurb: "Meaning — reference, truth conditions, composition, lexical fields.",
    section: "B",
    color: "emerald",
    entries: [
      {
        name: "Sense vs reference (Frege)",
        description: "Two aspects of meaning: what an expression denotes vs how it presents that denotation.",
        keyFact: "'The morning star' and 'the evening star' have the same reference (Venus) but different senses. Sense fixes reference but the two come apart.",
        tags: ["semantics", "Frege", "reference"],
        xref: ["philosophy"],
      },
      {
        name: "Truth-conditional semantics",
        description: "To know the meaning of a sentence is to know the conditions under which it would be true.",
        keyFact: "Tarski-Davidson program: a theory of meaning is a recursive definition of truth conditions over a formal grammar.",
        notation: "\\llbracket S \\rrbracket^{w} = 1 \\iff \\text{S is true at } w",
        tags: ["semantics", "truth-conditions"],
        xref: ["philosophy"],
      },
      {
        name: "Compositionality",
        description: "The meaning of a complex expression is determined by the meanings of its parts and how they are combined.",
        keyFact: "Frege's principle. Without it, language would require infinite memorization. Most semantic theories try to encode it formally.",
        notation: "\\llbracket \\alpha\\beta \\rrbracket = f(\\llbracket \\alpha \\rrbracket, \\llbracket \\beta \\rrbracket)",
        tags: ["semantics", "compositionality"],
      },
      {
        name: "Possible worlds semantics",
        description: "Sentence meaning = set of worlds in which it is true.",
        keyFact: "Necessity = true in all worlds; possibility = true in some. Propositional attitudes (belief, knowledge) modeled by relations to sets of worlds.",
        notation: "\\llbracket p \\rrbracket = \\{w : p \\text{ true at } w\\}",
        tags: ["semantics", "possible-worlds", "modal"],
        xref: ["philosophy"],
      },
      {
        name: "Montague semantics",
        description: "Richard Montague (1970): natural language and formal logic share the same syntax-to-semantics interface.",
        keyFact: "'English as a Formal Language' — quantifiers as generalized quantifiers (type ⟨⟨e,t⟩,t⟩); intensional types for opaque contexts. Sparked formal semantics.",
        tags: ["semantics", "Montague", "logic"],
        xref: ["mathematics", "philosophy"],
      },
      {
        name: "Generalized quantifiers",
        description: "Quantifiers as second-order relations.",
        keyFact: "'Every student' denotes the set of properties P such that every student has P. Type ⟨⟨e,t⟩,t⟩. Conservativity and monotonicity universals.",
        notation: "\\llbracket \\text{every student} \\rrbracket = \\lambda P. \\forall x[\\text{student}(x) \\to P(x)]",
        tags: ["semantics", "quantifier", "GQT"],
        xref: ["mathematics"],
      },
      {
        name: "Lambda calculus in semantics",
        description: "Lambda abstraction encodes how meanings compose.",
        keyFact: "Verb 'love' = λy.λx.love(x,y); 'John loves Mary' = (λy.λx.love(x,y))(Mary)(John) = love(John, Mary). Function application drives composition.",
        notation: "\\lambda y.\\lambda x.\\text{love}(x,y)",
        tags: ["semantics", "lambda"],
        xref: ["mathematics", "computer-science"],
      },
      {
        name: "Type theory",
        description: "Semantic objects classified by type: e (entities), t (truth values), s (worlds).",
        keyFact: "Standard inventory: e, t. Functions: ⟨e,t⟩ are properties. ⟨e,⟨e,t⟩⟩ are 2-place relations. Intensional types use s for worlds.",
        tags: ["semantics", "types"],
        xref: ["mathematics", "computer-science"],
      },
      {
        name: "Definite descriptions (Russell vs Strawson)",
        description: "Two analyses of 'the F'.",
        keyFact: "Russell: 'The king of France is bald' = ∃x[K(x) ∧ ∀y(K(y)→y=x) ∧ B(x)]; presuppositionless. Strawson: presupposes existence and uniqueness, fails to refer otherwise.",
        tags: ["semantics", "definites", "Russell"],
        xref: ["philosophy"],
      },
      {
        name: "Lexical semantics",
        description: "The meaning of individual words and their relations.",
        keyFact: "Studies polysemy, homonymy, synonymy, antonymy, hyponymy, meronymy. WordNet is a large-scale formalization.",
        tags: ["semantics", "lexical", "WordNet"],
      },
      {
        name: "Polysemy vs homonymy",
        description: "One word with related senses vs distinct words with the same form.",
        keyFact: "Polysemy: 'bank' (financial institution / building); related. Homonymy: 'bank' (financial) vs 'bank' (river bank); unrelated, etymologically distinct.",
        tags: ["semantics", "lexical", "polysemy"],
      },
      {
        name: "Frame semantics (Fillmore)",
        description: "Word meanings are anchored in conceptual frames (background scenarios).",
        keyFact: "'Buy' and 'sell' evoke the same Commercial Transaction frame with different perspectives. FrameNet implements this for English.",
        tags: ["semantics", "frame", "Fillmore"],
        xref: ["computer-science"],
      },
      {
        name: "Prototype theory",
        description: "Category membership is graded; some members more central than others.",
        keyFact: "Rosch (1973): 'robin' is a more prototypical bird than 'ostrich'. Categories have fuzzy boundaries, defined by family resemblance not necessary-and-sufficient conditions.",
        tags: ["semantics", "category", "Rosch"],
        xref: ["philosophy"],
      },
      {
        name: "Conceptual metaphor (Lakoff & Johnson)",
        description: "Abstract concepts structured by metaphorical mappings from concrete domains.",
        keyFact: "ARGUMENT IS WAR ('attacked', 'defended', 'shot down'); TIME IS MONEY ('spend', 'waste', 'invest'). Metaphor is conceptual, not just rhetorical.",
        tags: ["semantics", "metaphor", "cognitive"],
      },
      {
        name: "Aspect (telicity, perfective, imperfective)",
        description: "The internal temporal structure of an event.",
        keyFact: "Telic events have a natural endpoint ('build a house'); atelic do not ('run'). Vendler's four-way classification: states, activities, accomplishments, achievements.",
        tags: ["semantics", "aspect", "Vendler"],
      },
      {
        name: "Tense semantics",
        description: "How tense locates events in time.",
        keyFact: "Reichenbach's S, R, E: speech time, reference time, event time. Present perfect: E < R = S. Past: E = R < S. Pluperfect: E < R < S.",
        notation: "\\text{Past: } E = R < S",
        tags: ["semantics", "tense", "Reichenbach"],
      },
    ],
  },

  // ── Family 6 — Pragmatics ────────────────────────────────────────────────
  {
    slug: "pragmatics",
    number: 6,
    name: "Pragmatics",
    blurb: "Meaning in context — implicature, speech acts, deixis.",
    section: "B",
    color: "green",
    entries: [
      {
        name: "Speech acts (Austin, Searle)",
        description: "Utterances perform actions: stating, promising, ordering, marrying.",
        keyFact: "Austin's triad: locutionary act (saying), illocutionary act (what one does in saying — promise, order), perlocutionary act (effect on hearer).",
        tags: ["pragmatics", "speech-act", "Austin"],
        xref: ["philosophy"],
      },
      {
        name: "Performative utterances",
        description: "Sentences whose utterance is itself the performance of an act.",
        keyFact: "'I now pronounce you married'; 'I christen this ship the Queen Elizabeth.' Felicity conditions, not truth conditions, are at stake.",
        tags: ["pragmatics", "performative", "Austin"],
        xref: ["philosophy"],
      },
      {
        name: "Cooperative principle (Grice)",
        description: "Participants in conversation aim to be informative, truthful, relevant, and clear.",
        keyFact: "Four maxims: Quantity (be appropriately informative), Quality (be truthful), Relation (be relevant), Manner (be clear). Flouting generates implicature.",
        tags: ["pragmatics", "Grice", "maxims"],
        xref: ["philosophy"],
      },
      {
        name: "Conversational implicature",
        description: "What is implied by an utterance beyond what is literally said.",
        keyFact: "'Some students passed' implicates 'not all' via the Quantity maxim. Implicatures are cancelable: 'Some passed; in fact, all did.'",
        tags: ["pragmatics", "implicature", "Grice"],
      },
      {
        name: "Scalar implicature",
        description: "Use of a weak scalar item implicates the negation of stronger items.",
        keyFact: "'I ate some of the cake' → 'not all'. The scale ⟨all, most, some⟩ generates the inference. Calculated via Quantity maxim.",
        tags: ["pragmatics", "scalar", "implicature"],
      },
      {
        name: "Presupposition",
        description: "Information taken for granted by the speaker as background to the utterance.",
        keyFact: "'John stopped smoking' presupposes 'John used to smoke'. Survives negation: 'John didn't stop smoking' still presupposes this.",
        tags: ["pragmatics", "presupposition"],
      },
      {
        name: "Deixis",
        description: "Reference dependent on context (speaker, hearer, time, place).",
        keyFact: "Person deixis (I, you, we), spatial (here, this, that), temporal (now, yesterday), discourse (the latter, the former). Indexicals shift across contexts.",
        tags: ["pragmatics", "deixis", "indexical"],
        xref: ["philosophy"],
      },
      {
        name: "Politeness theory (Brown & Levinson)",
        description: "Linguistic strategies for managing face threats.",
        keyFact: "Positive face = desire to be liked; negative face = desire for autonomy. Strategies: bald-on-record, positive politeness, negative politeness, off-record, don't do it.",
        tags: ["pragmatics", "politeness", "face"],
      },
      {
        name: "Relevance theory (Sperber & Wilson)",
        description: "Communication driven by maximizing cognitive effects for minimal processing effort.",
        keyFact: "Cognitive principle: cognition geared to maximize relevance. Communicative principle: every utterance conveys a presumption of its own relevance.",
        tags: ["pragmatics", "relevance", "Sperber"],
      },
      {
        name: "Reference (anaphora, cataphora)",
        description: "How expressions pick out entities in discourse.",
        keyFact: "Anaphora: 'John_i said he_i would come' — 'he' refers backward. Cataphora: 'When she_i arrived, Mary_i was tired' — pronoun precedes referent.",
        tags: ["pragmatics", "anaphora", "reference"],
      },
      {
        name: "Common ground",
        description: "Mutually accepted background information at any point in a conversation.",
        keyFact: "Stalnaker's conception: assertion proposes to add a proposition to the common ground. Presupposition tests whether content is already in CG.",
        tags: ["pragmatics", "common-ground", "Stalnaker"],
        xref: ["philosophy"],
      },
      {
        name: "Indirect speech acts",
        description: "Performing one illocutionary act by performing another.",
        keyFact: "'Can you pass the salt?' literally a yes-no question, conventionally a request. Searle's conditions on conventional indirection.",
        tags: ["pragmatics", "indirect", "Searle"],
      },
    ],
  },

  // ── Family 7 — Historical linguistics ────────────────────────────────────
  {
    slug: "historical-linguistics",
    number: 7,
    name: "Historical Linguistics",
    blurb: "Language change over time — sound change, comparative method, reconstruction.",
    section: "C",
    color: "amber",
    entries: [
      {
        name: "Comparative method",
        description: "Systematic comparison of cognate forms across related languages to reconstruct the proto-language.",
        keyFact: "Established by 19th-c. Neogrammarians; underpins all of Indo-European studies. Requires regular sound correspondences across many vocabulary items.",
        tags: ["historical", "method", "comparative"],
      },
      {
        name: "Sound change (regularity)",
        description: "Phonological changes apply regularly to all words meeting their conditions.",
        keyFact: "Neogrammarian hypothesis (Osthoff & Brugmann 1878): 'sound laws operate without exceptions.' Lexical diffusion (Wang 1969) is the partial counter-claim.",
        tags: ["historical", "sound-change", "Neogrammarian"],
        status: "contested",
      },
      {
        name: "Grimm's Law (First Germanic Consonant Shift)",
        description: "Systematic stop shift defining Germanic from Proto-Indo-European.",
        keyFact: "PIE *p,t,k → Gmc f,θ,h; PIE *b,d,g → Gmc p,t,k; PIE *bh,dh,gh → Gmc b,d,g. Discovered by Rasmus Rask, formalized by Jacob Grimm 1822.",
        notation: "*p \\to f,\\ *t \\to \\theta,\\ *k \\to h",
        example: "Latin 'pater' vs English 'father'; Latin 'tres' vs English 'three'; Latin 'cor' vs English 'heart'.",
        tags: ["historical", "Grimm", "Germanic"],
      },
      {
        name: "Verner's Law",
        description: "Explains apparent Grimm's Law exceptions where the voiceless fricative is voiced.",
        keyFact: "Following an unaccented vowel, the voiceless fricatives from Grimm's Law become voiced: *p → f → v, etc. Resolved the Grimm 'exceptions'.",
        example: "Sanskrit 'pitár' (acute stress on second syllable) → Gmc 'fader' (with voiced d), not *faþer.",
        tags: ["historical", "Verner", "Germanic"],
      },
      {
        name: "Great Vowel Shift",
        description: "Systematic raising and diphthongization of English long vowels, ~1400–1700.",
        keyFact: "Long /iː/ → /aɪ/, /eː/ → /iː/, /aː/ → /eɪ/ (and back-vowel parallel). Why English spelling looks insane: it froze pre-shift.",
        notation: "/i\\colon/ \\to /a\\textsci/,\\quad /e\\colon/ \\to /i\\colon/,\\quad /a\\colon/ \\to /e\\textsci/",
        example: "Middle English 'bite' [biːtə] → Modern [baɪt]; 'meet' [meːt] → [miːt]; 'name' [naːmə] → [neɪm].",
        tags: ["historical", "GVS", "English"],
      },
      {
        name: "Proto-language reconstruction",
        description: "Inferring forms of an unattested ancestor language.",
        keyFact: "PIE reconstructed mainly from Sanskrit, Greek, Latin, Hittite. Notation: *bʰréh₂tēr 'brother'. Asterisk marks reconstructed forms.",
        tags: ["historical", "reconstruction", "PIE"],
      },
      {
        name: "Cognates vs borrowings",
        description: "Cognates inherit from a common ancestor; borrowings cross between languages by contact.",
        keyFact: "English 'father' and German 'Vater' are cognates (inherited from PIE). English 'beef' from French 'bœuf' is a borrowing, not a cognate of native 'cow'.",
        tags: ["historical", "cognate", "borrowing"],
      },
      {
        name: "Glottochronology",
        description: "Method for dating language divergence by measuring shared basic vocabulary retention.",
        keyFact: "Swadesh (1952) proposed a universal retention rate; widely rejected because rate varies. Still informally cited for time-depth estimates.",
        tags: ["historical", "glottochronology", "Swadesh"],
        status: "refuted",
      },
      {
        name: "Bayesian phylolinguistics",
        description: "Adapting molecular-phylogenetic tools to language trees.",
        keyFact: "Gray & Atkinson (2003) used cognate matrices and Bayesian inference to date Indo-European to ~8700 BCE, supporting Anatolian over Steppe hypothesis. Contested by archaeologists/geneticists.",
        tags: ["historical", "phylogenetic", "Bayesian"],
        status: "contested",
        xref: ["statistics", "computer-science"],
      },
      {
        name: "Grammaticalization",
        description: "Content words become grammatical morphemes over time.",
        keyFact: "Latin 'habere' (to have) → French future suffix '-rai' (j'aurai, je chanterai). One-way pathway: lexical → grammatical → reduced.",
        tags: ["historical", "grammaticalization"],
      },
      {
        name: "Wave model vs tree model",
        description: "Competing models of language relationships.",
        keyFact: "Tree (Schleicher 1863): clean splits into daughter languages. Wave (Schmidt 1872): innovations spread geographically, overlapping in unrelated patterns. Both apply.",
        tags: ["historical", "tree", "wave"],
      },
      {
        name: "Sapir-Whorf hypothesis",
        description: "Language structure influences (or determines) thought.",
        keyFact: "Strong version (determinism) is refuted; weak version (linguistic relativity) has partial empirical support (color terms, spatial frames of reference, grammatical gender effects).",
        tags: ["historical", "Whorf", "relativity"],
        status: "contested",
      },
    ],
  },

  // ── Family 8 — Sociolinguistics ──────────────────────────────────────────
  {
    slug: "sociolinguistics",
    number: 8,
    name: "Sociolinguistics",
    blurb: "Language in its social context — variation, register, change in progress.",
    section: "C",
    color: "rose",
    entries: [
      {
        name: "Variationist sociolinguistics (Labov)",
        description: "Quantitative study of linguistic variation tied to social factors.",
        keyFact: "Labov's NYC department-store study (1966) showed /r/ pronunciation correlates with social class. Methodologically grounded sociolinguistics as a field.",
        tags: ["sociolinguistics", "Labov", "variation"],
        xref: ["statistics"],
      },
      {
        name: "Sociolinguistic variable",
        description: "A linguistic feature with multiple variants whose distribution correlates with social factors.",
        keyFact: "Notation: (ng) variable in English, with variants [ɪŋ] 'walking' and [ɪn] 'walkin'. Predicted by class, formality, sex, age.",
        notation: "(\\text{ng}): [\\textsci\\ng] \\sim [\\textsci\\textn]",
        tags: ["sociolinguistics", "variable"],
      },
      {
        name: "Change from below / above",
        description: "Below: change below the level of social consciousness, led by working/middle class women. Above: conscious change, prestige-driven.",
        keyFact: "Most regular sound change is from below; lexical and pronunciation prestige features (rhoticity, dropping h-) are from above.",
        tags: ["sociolinguistics", "change"],
      },
      {
        name: "Diglossia (Ferguson)",
        description: "Two varieties of a language coexist, with strict functional division (H = High, L = Low).",
        keyFact: "Arabic (MSA H vs. local dialects L); Swiss German (Standard H vs. Schwyzerdütsch L); Tamil (literary H vs. colloquial L).",
        tags: ["sociolinguistics", "diglossia", "Ferguson"],
      },
      {
        name: "Code-switching",
        description: "Alternating between two or more languages within a single conversation.",
        keyFact: "Governed by syntactic constraints (Matrix Language Frame, Myers-Scotton 1993). Not random or 'deficient' — a sophisticated bilingual strategy.",
        tags: ["sociolinguistics", "bilingualism", "code-switching"],
      },
      {
        name: "Register",
        description: "Variety used in a particular social setting (formal, casual, technical).",
        keyFact: "Register varies across all linguistic levels: lexicon (vocabulary), syntax (passives), prosody (intonation). Often correlated with audience.",
        tags: ["sociolinguistics", "register"],
      },
      {
        name: "Pidgin and creole",
        description: "Pidgin: simplified contact language with no native speakers. Creole: a pidgin nativized.",
        keyFact: "Hawai'i Creole English nativized in one generation. Bickerton (1981): creoles share grammatical features universally (Language Bioprogram).",
        tags: ["sociolinguistics", "pidgin", "creole"],
        status: "contested",
      },
      {
        name: "African American English (AAE)",
        description: "Systematic, rule-governed variety of English with distinct phonology, syntax, lexicon.",
        keyFact: "Habitual 'be' ('She be working' = habitually, not currently); copula deletion ('He tall'); zero past tense. Not 'broken English' — a full grammar.",
        tags: ["sociolinguistics", "AAE", "dialect"],
      },
      {
        name: "Language and gender",
        description: "Empirical patterns in how men and women use language.",
        keyFact: "Women lead most sound changes from below; men tend to use more vernacular forms. 'Genderlect' (Lakoff 1975) and the Difference vs Dominance debate.",
        tags: ["sociolinguistics", "gender"],
      },
      {
        name: "Language attitudes",
        description: "Speakers' explicit and implicit evaluations of language varieties.",
        keyFact: "Matched-guise technique (Lambert 1960): listeners rate the same speaker more favorably in the prestige variety. Prestige is not intrinsic — it's projected.",
        tags: ["sociolinguistics", "attitudes", "matched-guise"],
      },
      {
        name: "Dialectology",
        description: "Geographic distribution of language variation.",
        keyFact: "Isoglosses mark boundaries between linguistic features. The 'Rhenish fan' bundles isoglosses showing High German consonant shift didn't cleanly reach the Rhine.",
        tags: ["sociolinguistics", "dialectology", "isogloss"],
      },
      {
        name: "Language shift and death",
        description: "Communities replace their native language with another, sometimes in 1–3 generations.",
        keyFact: "Ethnologue tracks ~3,000 languages as endangered out of ~7,100 living. Drivers: economic, political, educational pressure. Reversal cases: Welsh, Hebrew.",
        tags: ["sociolinguistics", "endangerment", "shift"],
      },
      {
        name: "Communities of practice",
        description: "Groups bound by shared activity, distinct from speech communities defined by region or class.",
        keyFact: "Eckert (1989) 'Jocks and Burnouts': linguistic style is constructed through participation, not just inherited identity.",
        tags: ["sociolinguistics", "CoP", "Eckert"],
      },
    ],
  },
];
