import type { Family } from "./types";

export const FAMILIES_9_16: Family[] = [
  // ── Family 9 — Psycholinguistics ─────────────────────────────────────────
  {
    slug: "psycholinguistics",
    number: 9,
    name: "Psycholinguistics",
    blurb: "Mental processes of language production, comprehension, and storage.",
    section: "C",
    color: "violet",
    entries: [
      {
        name: "Lexical access",
        description: "Retrieving a word's meaning, sound, and grammatical info from the mental lexicon.",
        keyFact: "Access is graded and parallel: candidates compete (cohort model). Frequency effects: high-frequency words recognized faster.",
        tags: ["psycholinguistics", "lexicon"],
      },
      {
        name: "Cohort model (Marslen-Wilson)",
        description: "Spoken-word recognition cohort narrows as more phonemes arrive.",
        keyFact: "Hearing 'cap-' activates 'capital, captain, capsule, ...'; with each phoneme the cohort shrinks until a unique candidate ('uniqueness point') wins.",
        tags: ["psycholinguistics", "word-recognition", "cohort"],
      },
      {
        name: "TRACE model (McClelland & Elman)",
        description: "Interactive activation model of speech perception.",
        keyFact: "Three layers (features, phonemes, words) with bidirectional excitation and within-layer inhibition. Predicts top-down lexical effects on phoneme perception.",
        tags: ["psycholinguistics", "TRACE", "connectionism"],
        xref: ["computer-science"],
      },
      {
        name: "Garden-path sentences",
        description: "Sentences that mislead the parser into a structure that must be revised.",
        keyFact: "'The horse raced past the barn fell' — readers initially parse 'raced' as main verb, must reanalyze as reduced relative. Evidence for serial parsing.",
        example: "'The old man the boats.' ('man' is the verb.)",
        tags: ["psycholinguistics", "parsing", "garden-path"],
      },
      {
        name: "Minimal attachment & Late closure",
        description: "Heuristic parsing strategies (Frazier 1978).",
        keyFact: "Minimal Attachment: prefer the simplest tree. Late Closure: attach incoming material to the currently-being-processed phrase.",
        tags: ["psycholinguistics", "parsing", "Frazier"],
      },
      {
        name: "Constraint-satisfaction parsing",
        description: "Alternative to serial parsing: probabilistic, parallel constraint integration.",
        keyFact: "MacDonald, Pearlmutter, Seidenberg (1994): multiple cues (lexical bias, frequency, context) weighted in parallel; no purely structural first pass.",
        tags: ["psycholinguistics", "parsing", "constraint"],
      },
      {
        name: "N400 (ERP component)",
        description: "Negative-going ERP peaking ~400ms after a stimulus, sensitive to semantic expectancy.",
        keyFact: "Kutas & Hillyard (1980): 'He spread the warm bread with socks' → large N400. Indexes ease of semantic integration.",
        tags: ["psycholinguistics", "ERP", "N400"],
      },
      {
        name: "P600 (ERP component)",
        description: "Positive-going ERP ~600ms, sensitive to syntactic anomaly and reanalysis.",
        keyFact: "'The cats won't EAT the food' (grammatical) vs 'The cats won't EATING the food' (syntactic) → P600. Used as a syntax index.",
        tags: ["psycholinguistics", "ERP", "P600"],
      },
      {
        name: "Tip of the tongue (TOT)",
        description: "Knowing a word but unable to retrieve its form.",
        keyFact: "Brown & McNeill (1966): subjects can often retrieve initial phoneme, syllable count, gender — evidence the lexicon stores form and meaning separately.",
        tags: ["psycholinguistics", "TOT", "retrieval"],
      },
      {
        name: "Speech errors as evidence",
        description: "Slips of the tongue reveal planning architecture.",
        keyFact: "Spoonerisms (the Lord is a shoving leopard) involve unit exchange. Errors respect syllable position; word-class preserved → modular planning.",
        tags: ["psycholinguistics", "speech-errors", "production"],
      },
      {
        name: "Levelt's model of speech production",
        description: "Conceptualization → formulation → articulation.",
        keyFact: "Levelt, Roelofs, Meyer (1999) WEAVER++: discrete-stage activation through concepts, lemmas (syntactic info), lexemes (phonological form). Influential.",
        tags: ["psycholinguistics", "Levelt", "production"],
      },
      {
        name: "Working memory in sentence processing",
        description: "Limited capacity affects parsing of complex structures.",
        keyFact: "Center-embedded structures (the rat the cat the dog chased killed ate) become unparseable after 2 levels — a working-memory bottleneck, not grammar.",
        tags: ["psycholinguistics", "memory", "embedding"],
      },
      {
        name: "Visual world paradigm",
        description: "Eye-tracking method that reveals incremental processing.",
        keyFact: "Tanenhaus et al. 1995: listeners fix on referents before the noun is fully spoken — language processing is incremental, not delayed to clause boundaries.",
        tags: ["psycholinguistics", "eye-tracking"],
      },
    ],
  },

  // ── Family 10 — Language acquisition ─────────────────────────────────────
  {
    slug: "language-acquisition",
    number: 10,
    name: "Language Acquisition",
    blurb: "How children acquire a first language; second-language learning.",
    section: "C",
    color: "indigo",
    entries: [
      {
        name: "Critical period hypothesis (Lenneberg 1967)",
        description: "Window of plasticity for language acquisition; closes around puberty.",
        keyFact: "Late L1 acquirers (deaf children acquiring sign late, Genie) never reach native-like competence. L2 learners have lower ceilings after ~puberty.",
        tags: ["acquisition", "critical-period", "Lenneberg"],
        status: "contested",
      },
      {
        name: "Stages of first-language acquisition",
        description: "Universal sequence: babbling → one-word → two-word → multi-word.",
        keyFact: "Babbling 6–10 mo; first words ~12 mo; two-word stage ~18–24 mo; rapid vocabulary growth ~24+ mo; near-adult grammar by ~4 yrs.",
        tags: ["acquisition", "stages", "L1"],
      },
      {
        name: "Poverty of the stimulus",
        description: "Children acquire grammar despite incomplete and noisy input.",
        keyFact: "Chomsky's argument for UG: structural facts (e.g., auxiliary inversion across embeddings) are acquired without negative evidence. Heavily contested by usage-based theorists.",
        tags: ["acquisition", "POS", "UG"],
        status: "contested",
      },
      {
        name: "Wug test (Berko 1958)",
        description: "Children apply morphological rules to nonce words.",
        keyFact: "Shown 'a wug' and 'two ___', 4-year-olds say 'wugs' with the correct [z] allomorph — proving they have rule-based, not memorized, morphology.",
        tags: ["acquisition", "Berko", "morphology"],
      },
      {
        name: "Overregularization",
        description: "Children apply regular rules to irregular forms.",
        keyFact: "'Goed', 'sheeps', 'foots'. Cited as evidence for rules (Pinker) vs analogy (Rumelhart & McClelland connectionist model). Decades-long debate.",
        tags: ["acquisition", "overregularization", "past-tense"],
      },
      {
        name: "Statistical learning",
        description: "Infants extract patterns from input via transitional probabilities.",
        keyFact: "Saffran, Aslin, Newport (1996): 8-month-olds segment word-like units from a continuous stream after 2 minutes' exposure, using transitional probabilities.",
        tags: ["acquisition", "statistical-learning"],
        xref: ["statistics", "computer-science"],
      },
      {
        name: "Categorical perception in infants",
        description: "Infants distinguish all phonetic contrasts, then prune to native ones.",
        keyFact: "Werker & Tees (1984): 6–8-mo English infants discriminate Hindi dental/retroflex /ʈ/ vs /t/; 10–12-mo infants no longer do. Perceptual narrowing.",
        tags: ["acquisition", "perception"],
      },
      {
        name: "Bilingual first-language acquisition",
        description: "Simultaneous acquisition of two languages from birth.",
        keyFact: "Bilingual children separate the two systems early. Mixed utterances drop sharply after ~3 yrs. No deficit; some metalinguistic and executive advantages.",
        tags: ["acquisition", "bilingual"],
      },
      {
        name: "Second-language acquisition (SLA)",
        description: "Adult learners' systematic interlanguages.",
        keyFact: "L2 learners pass through stages; errors are systematic, not random. Many features fossilize; near-native accent is rare after ~age 12.",
        tags: ["acquisition", "SLA", "interlanguage"],
      },
      {
        name: "Usage-based acquisition (Tomasello)",
        description: "Children learn grammar from frequent constructions, not innate rules.",
        keyFact: "Tomasello (2003): early grammar is item-based ('Where's X?', 'I wanna X'); abstraction is gradual and frequency-driven. Counter-position to UG.",
        tags: ["acquisition", "usage-based", "Tomasello"],
        status: "contested",
      },
      {
        name: "Language deprivation (Genie, Chelsea)",
        description: "Case studies of severely deprived children.",
        keyFact: "Genie (isolated until age 13) acquired lexicon but never mastered syntax. Cited as critical-period evidence; methodology and ethics complex.",
        tags: ["acquisition", "deprivation", "case-study"],
      },
      {
        name: "Sign language acquisition (Nicaraguan SL)",
        description: "When deaf children gather without an input language, they create one.",
        keyFact: "Senghas (1995) documented ISN/Nicaraguan Sign Language emerging in one generation among deaf students at a new school. Strong creation evidence.",
        tags: ["acquisition", "sign", "Nicaraguan"],
      },
    ],
  },

  // ── Family 11 — Neurolinguistics ─────────────────────────────────────────
  {
    slug: "neurolinguistics",
    number: 11,
    name: "Neurolinguistics",
    blurb: "Brain bases of language — aphasia, hemispheric specialization, imaging.",
    section: "C",
    color: "rose",
    entries: [
      {
        name: "Broca's area",
        description: "Left inferior frontal gyrus (BA 44/45), classically associated with speech production.",
        keyFact: "Damage produces non-fluent ('telegraphic') aphasia with relatively preserved comprehension. Modern view: also involved in syntactic processing.",
        tags: ["neuro", "Broca", "production"],
      },
      {
        name: "Wernicke's area",
        description: "Posterior superior temporal gyrus (BA 22), classically associated with comprehension.",
        keyFact: "Damage produces fluent aphasia with severely impaired comprehension — 'word salad' that is grammatical but semantically empty.",
        tags: ["neuro", "Wernicke", "comprehension"],
      },
      {
        name: "Wernicke-Geschwind model",
        description: "Classical 19th–20th-c. neuroanatomical model linking Broca, Wernicke, and arcuate fasciculus.",
        keyFact: "Comprehension at Wernicke → arcuate fasciculus → Broca for production. Modern imaging shows the model is too simple but the general dorsal/ventral distinction holds.",
        tags: ["neuro", "Wernicke-Geschwind", "history"],
      },
      {
        name: "Broca's aphasia",
        description: "Non-fluent, agrammatic speech with relatively preserved comprehension.",
        keyFact: "Patients produce short telegraphic utterances ('walk dog'), omit function words and inflection. Comprehension fails on syntactically complex sentences.",
        tags: ["neuro", "aphasia", "Broca"],
      },
      {
        name: "Wernicke's aphasia",
        description: "Fluent speech with impaired comprehension and content.",
        keyFact: "Speech rate normal but riddled with paraphasias (word substitutions, neologisms). Patient often unaware of deficit (anosognosia).",
        tags: ["neuro", "aphasia", "Wernicke"],
      },
      {
        name: "Conduction aphasia",
        description: "Impaired repetition with fluent speech and good comprehension.",
        keyFact: "Classically attributed to arcuate fasciculus damage. Patients can speak and understand but cannot repeat what they hear.",
        tags: ["neuro", "aphasia", "conduction"],
      },
      {
        name: "Global aphasia",
        description: "Severe impairment in all language modalities.",
        keyFact: "Typically results from large left middle-cerebral-artery strokes affecting both Broca's and Wernicke's areas.",
        tags: ["neuro", "aphasia", "global"],
      },
      {
        name: "Dorsal and ventral streams",
        description: "Two parallel pathways for language processing.",
        keyFact: "Hickok & Poeppel (2007): dorsal stream maps sound to articulation; ventral stream maps sound to meaning. Functional rather than purely anatomical division.",
        tags: ["neuro", "dual-stream", "Hickok"],
      },
      {
        name: "Hemispheric lateralization",
        description: "Language predominantly left-hemisphere in ~95% of right-handers.",
        keyFact: "Established via Wada test (sodium amytal injection) and later by fMRI. Left-handers are about 70% left-lateralized, 30% right or bilateral.",
        tags: ["neuro", "lateralization"],
      },
      {
        name: "Mismatch negativity (MMN)",
        description: "Pre-attentive ERP response to deviant stimuli.",
        keyFact: "Reveals automatic phonemic categorization in the brain. Infant MMN tracks acquisition of native phonemes.",
        tags: ["neuro", "MMN", "ERP"],
      },
      {
        name: "Specific Language Impairment (SLI / DLD)",
        description: "Developmental language disorder without other cognitive deficits.",
        keyFact: "Affects ~7% of children. Particular trouble with verb inflection. KE family with FOXP2 mutation links to a specific genetic locus.",
        tags: ["neuro", "SLI", "FOXP2"],
      },
      {
        name: "FOXP2",
        description: "The first identified gene strongly tied to a speech and language phenotype.",
        keyFact: "Mutations cause severe orofacial dyspraxia plus syntactic deficits. Highly conserved; not a 'language gene' per se but tied to motor planning.",
        tags: ["neuro", "genetics", "FOXP2"],
      },
    ],
  },

  // ── Family 12 — Computational & corpus linguistics ───────────────────────
  {
    slug: "computational-linguistics",
    number: 12,
    name: "Computational Linguistics",
    blurb: "Algorithms, corpora, and statistical/neural models of language.",
    section: "C",
    color: "blue",
    entries: [
      {
        name: "N-gram language model",
        description: "Probability of a word given preceding n-1 words.",
        keyFact: "Markov assumption: $P(w_t \\mid w_1^{t-1}) \\approx P(w_t \\mid w_{t-n+1}^{t-1})$. Foundation for early speech recognition and MT.",
        notation: "P(w_1^T) \\approx \\prod_{t=1}^T P(w_t \\mid w_{t-n+1}^{t-1})",
        tags: ["computational", "n-gram", "LM"],
        xref: ["statistics", "computer-science"],
      },
      {
        name: "Smoothing (Kneser-Ney, Good-Turing)",
        description: "Reassigning probability mass to unseen n-grams.",
        keyFact: "Kneser-Ney smoothing was the SOTA n-gram method for decades. Replaced by neural LMs only ~2014.",
        tags: ["computational", "smoothing", "LM"],
        xref: ["statistics"],
      },
      {
        name: "Word embeddings (word2vec, GloVe)",
        description: "Dense vector representations of words capturing distributional similarity.",
        keyFact: "Mikolov et al. 2013: 'king - man + woman ≈ queen'. Words appearing in similar contexts get similar vectors (distributional hypothesis, Harris 1954).",
        notation: "\\vec{v}_{\\text{king}} - \\vec{v}_{\\text{man}} + \\vec{v}_{\\text{woman}} \\approx \\vec{v}_{\\text{queen}}",
        tags: ["computational", "embeddings", "word2vec"],
        xref: ["computer-science"],
      },
      {
        name: "Transformer architecture (Vaswani et al. 2017)",
        description: "Attention-only neural architecture.",
        keyFact: "'Attention Is All You Need'. Self-attention $\\text{softmax}(QK^T/\\sqrt{d_k})V$ replaces recurrence. Backbone of every large language model since 2018.",
        notation: "\\text{Attention}(Q,K,V) = \\text{softmax}\\!\\left(\\frac{QK^T}{\\sqrt{d_k}}\\right)V",
        tags: ["computational", "transformer", "LLM"],
        xref: ["computer-science"],
      },
      {
        name: "Distributional hypothesis (Harris 1954, Firth 1957)",
        description: "Words occurring in similar contexts tend to have similar meanings.",
        keyFact: "Firth: 'You shall know a word by the company it keeps.' Empirical foundation for all modern vector semantics, including LLMs.",
        tags: ["computational", "distributional", "Firth"],
      },
      {
        name: "Part-of-speech tagging",
        description: "Assigning a syntactic category to each word.",
        keyFact: "HMM/CRF taggers achieved >97% on Penn Treebank by 2003. Neural taggers (BiLSTM-CRF, BERT) marginally better.",
        tags: ["computational", "tagging", "POS"],
        xref: ["computer-science", "statistics"],
      },
      {
        name: "Parsing (CKY, shift-reduce, neural)",
        description: "Building syntactic trees algorithmically.",
        keyFact: "CKY: bottom-up O(n³) dynamic-programming parser for CFGs. Shift-reduce: O(n) transition-based parsing. Neural transition parsers SOTA since 2014.",
        notation: "T(n) = O(n^3) \\text{ (CKY)}",
        tags: ["computational", "parsing", "CKY"],
        xref: ["computer-science"],
      },
      {
        name: "Machine translation (statistical, neural)",
        description: "Automatic translation between languages.",
        keyFact: "IBM Models 1–5 (1990s) — phrase-based SMT (2000s) — neural seq2seq (2014) — Transformer NMT (2017+). Each generation roughly +5 BLEU.",
        tags: ["computational", "MT", "translation"],
        xref: ["computer-science"],
      },
      {
        name: "BLEU score",
        description: "Standard automatic metric for MT quality.",
        keyFact: "Papineni et al. 2002: n-gram precision against reference translations, with brevity penalty. Correlates with human judgment in aggregate; brittle per sentence.",
        notation: "\\text{BLEU} = BP \\cdot \\exp\\!\\left(\\sum_n w_n \\log p_n\\right)",
        tags: ["computational", "BLEU", "metric"],
        xref: ["statistics"],
      },
      {
        name: "Treebanks (Penn Treebank, UD)",
        description: "Corpora annotated with syntactic structure.",
        keyFact: "PTB (Marcus et al. 1993): 1M words of WSJ with phrase-structure trees, still the parsing benchmark. UD: 200+ languages, uniform dependency scheme.",
        tags: ["computational", "treebank", "PTB"],
      },
      {
        name: "Corpus linguistics",
        description: "Empirical linguistics on large text collections.",
        keyFact: "BNC (100M words), COCA (1B+ words), Google Books N-grams (~500B tokens). Frequency, collocation, and KWIC concordances.",
        tags: ["computational", "corpus", "frequency"],
      },
      {
        name: "Large Language Models (LLMs)",
        description: "Multi-billion-parameter transformers trained on web-scale text.",
        keyFact: "Emergent abilities (chain-of-thought, instruction following, few-shot) appear roughly above 10^22 FLOPs of training compute. Mechanism debated.",
        tags: ["computational", "LLM"],
        xref: ["computer-science"],
        status: "open",
      },
      {
        name: "Named-entity recognition (NER)",
        description: "Identifying mentions of persons, organizations, locations, etc.",
        keyFact: "CoNLL-2003 benchmark. BiLSTM-CRF (2016) ~91 F1; RoBERTa (2019) ~94 F1. Mostly 'solved' for English news; struggles on low-resource languages.",
        tags: ["computational", "NER", "IE"],
        xref: ["computer-science"],
      },
      {
        name: "Speech recognition (ASR)",
        description: "Mapping audio to text.",
        keyFact: "HMM-GMM (1980s–2010) → DNN-HMM (2011) → end-to-end seq2seq (2015+) → Whisper (2022, multilingual). WER on LibriSpeech clean ~2%.",
        tags: ["computational", "ASR", "speech"],
        xref: ["computer-science"],
      },
    ],
  },

  // ── Family 13 — Applied linguistics ──────────────────────────────────────
  {
    slug: "applied-linguistics",
    number: 13,
    name: "Applied Linguistics",
    blurb: "Language teaching, assessment, policy, forensic and clinical applications.",
    section: "D",
    color: "amber",
    entries: [
      {
        name: "Communicative Language Teaching (CLT)",
        description: "L2 teaching that prioritizes meaningful communication over rote drills.",
        keyFact: "Dominant paradigm since ~1980, replacing audio-lingual method. Roots in Hymes' notion of communicative competence.",
        tags: ["applied", "teaching", "CLT"],
      },
      {
        name: "Communicative competence (Hymes)",
        description: "Knowledge of how to use language appropriately, not just grammatically.",
        keyFact: "Hymes (1972) extended Chomsky's competence to include social rules of use. Foundational for applied linguistics.",
        tags: ["applied", "Hymes", "competence"],
      },
      {
        name: "CEFR (Common European Framework of Reference)",
        description: "Six-level scale (A1–C2) for L2 proficiency.",
        keyFact: "Council of Europe 2001. Widely adopted in EU and beyond for testing, hiring, curriculum design. C2 = near-native; A1 = beginner.",
        tags: ["applied", "CEFR", "assessment"],
      },
      {
        name: "TOEFL / IELTS",
        description: "Standardized English L2 proficiency tests for university admission.",
        keyFact: "TOEFL iBT 0–120; IELTS 0–9. Used by ~11,000 institutions worldwide. Validated against academic performance.",
        tags: ["applied", "testing", "TOEFL"],
      },
      {
        name: "Krashen's Input Hypothesis",
        description: "Comprehensible input slightly above current level (i + 1) drives L2 acquisition.",
        keyFact: "Krashen (1985): acquisition vs learning distinction; affective filter. Influential but heavily critiqued for vagueness and weak operationalization.",
        tags: ["applied", "Krashen", "SLA"],
        status: "contested",
      },
      {
        name: "Forensic linguistics",
        description: "Linguistic analysis applied to legal evidence.",
        keyFact: "Authorship attribution (Unabomber ID'd via syntactic and lexical signatures); voice ID; trademark distinctiveness analysis; threat assessment.",
        tags: ["applied", "forensic"],
      },
      {
        name: "Clinical linguistics / SLP",
        description: "Diagnosis and treatment of communication disorders.",
        keyFact: "Speech-language pathology covers aphasia rehabilitation, child language disorders, fluency (stuttering), voice, dysphagia.",
        tags: ["applied", "clinical", "SLP"],
      },
      {
        name: "Lexicography",
        description: "Dictionary-making, descriptive and prescriptive.",
        keyFact: "OED reads 100M citation slips; corpus-based dictionaries (COBUILD 1987) defined senses by frequency. Definition theory: substitutability and circularity avoidance.",
        tags: ["applied", "lexicography"],
      },
      {
        name: "Language policy",
        description: "Governmental decisions about official languages, education medium, minority rights.",
        keyFact: "South Africa: 11 official languages (1996). India: 22 scheduled. Bilingual education models (immersion, transitional, two-way) studied for outcomes.",
        tags: ["applied", "policy"],
      },
      {
        name: "Translation studies",
        description: "Theory and practice of translation.",
        keyFact: "Nida's dynamic vs formal equivalence; Venuti's domesticating vs foreignizing translation. Computational MT increasingly displacing low-stakes translation since 2017.",
        tags: ["applied", "translation"],
      },
      {
        name: "Plain Language movement",
        description: "Reform aimed at clear, accessible legal and bureaucratic text.",
        keyFact: "US Plain Writing Act 2010 mandates plain language in federal communications. Research shows comprehension and compliance gains.",
        tags: ["applied", "plain-language"],
      },
      {
        name: "Reading research (whole language vs phonics)",
        description: "Decades-long pedagogical debate.",
        keyFact: "National Reading Panel 2000 found systematic phonics instruction superior for early decoding. 'Science of reading' consensus is phonics-first; whole-language remains in some districts.",
        tags: ["applied", "reading"],
        status: "resolved",
      },
    ],
  },

  // ── Family 14 — Discourse analysis ──────────────────────────────────────
  {
    slug: "discourse-analysis",
    number: 14,
    name: "Discourse Analysis",
    blurb: "Language above the sentence — coherence, turn-taking, framing, ideology.",
    section: "D",
    color: "teal",
    entries: [
      {
        name: "Conversation analysis (Sacks, Schegloff, Jefferson)",
        description: "Empirical study of turn-by-turn interaction structure.",
        keyFact: "Discovered turn-taking system, adjacency pairs (greeting/greeting, question/answer), preference organization, repair sequences.",
        tags: ["discourse", "CA"],
      },
      {
        name: "Turn-taking system",
        description: "How conversational floor passes between speakers.",
        keyFact: "Sacks/Schegloff/Jefferson (1974): TCUs end at Transition-Relevance Places. Rules: current selects next, self-selects, or current continues. Predicts ~200ms gap norm.",
        tags: ["discourse", "turn-taking"],
      },
      {
        name: "Adjacency pairs",
        description: "Two-turn structures with first-pair-part + second-pair-part.",
        keyFact: "Question/answer, offer/accept-reject, greeting/greeting. Preferred and dispreferred seconds have different prosodic and structural shapes.",
        tags: ["discourse", "adjacency"],
      },
      {
        name: "Repair",
        description: "Mechanisms for handling trouble in conversation.",
        keyFact: "Self-initiated self-repair preferred; other-initiated repair (huh? what?) treated as marked. Initiator and repairer can be same or different speakers.",
        tags: ["discourse", "repair"],
      },
      {
        name: "Cohesion and coherence (Halliday & Hasan)",
        description: "Cohesion: surface ties (pronouns, conjunctions). Coherence: underlying logical/topical unity.",
        keyFact: "A text can be cohesive without being coherent and vice versa. Five cohesive ties: reference, substitution, ellipsis, conjunction, lexical cohesion.",
        tags: ["discourse", "cohesion", "Halliday"],
      },
      {
        name: "Rhetorical Structure Theory (Mann & Thompson)",
        description: "A discourse parsed into hierarchical relations between nucleus and satellite.",
        keyFact: "About 25 relations (Cause, Elaboration, Contrast, Background, ...). Used in summarization and computational discourse parsing.",
        tags: ["discourse", "RST"],
        xref: ["computer-science"],
      },
      {
        name: "Centering theory",
        description: "Model of attentional state and discourse coherence (Grosz, Joshi, Weinstein 1995).",
        keyFact: "Each utterance has forward-looking centers; the preferred center is the highest-ranked entity continued in the next utterance. Predicts pronominal coherence.",
        tags: ["discourse", "centering", "anaphora"],
      },
      {
        name: "Critical Discourse Analysis (CDA)",
        description: "Discourse as a site of power, ideology, social inequality.",
        keyFact: "Fairclough, van Dijk, Wodak: analyzes how dominant ideologies are reproduced through lexical choice, presupposition, transitivity, modality in media and political text.",
        tags: ["discourse", "CDA", "ideology"],
      },
      {
        name: "Frame analysis (Goffman)",
        description: "How participants interpret what is going on in interaction.",
        keyFact: "Frames are interpretive schemata. Framing shifts (footing changes) signal new alignments and participant roles.",
        tags: ["discourse", "framing", "Goffman"],
      },
      {
        name: "Narrative analysis (Labov & Waletzky)",
        description: "Personal experience narratives have recurrent structure.",
        keyFact: "Abstract → Orientation → Complicating action → Evaluation → Resolution → Coda. The evaluation clauses carry the 'point' of the narrative.",
        tags: ["discourse", "narrative", "Labov"],
      },
      {
        name: "Politeness in discourse",
        description: "Discourse-level strategies for face-management.",
        keyFact: "Beyond utterance-level Brown-Levinson, discourse politeness includes topic management, hedging, indirectness clusters, ritual openings/closings.",
        tags: ["discourse", "politeness"],
      },
      {
        name: "Genre analysis (Swales)",
        description: "Patterns characteristic of recurring communicative events.",
        keyFact: "Research article introductions follow CARS model: Create A Research Space — Move 1 (establish territory), Move 2 (establish niche/gap), Move 3 (occupy niche).",
        tags: ["discourse", "genre", "Swales"],
      },
    ],
  },

  // ── Family 15 — Linguistic typology ──────────────────────────────────────
  {
    slug: "typology",
    number: 15,
    name: "Linguistic Typology",
    blurb: "Cross-linguistic patterns and universals.",
    section: "D",
    color: "emerald",
    entries: [
      {
        name: "Greenberg's universals (1963)",
        description: "Implicational generalizations across word order, morphology, agreement.",
        keyFact: "Universal 4: VSO ⊃ Prep; Universal 25: OV ⊃ AdjN (mostly). 45 implicational and unrestricted universals; the foundational typological dataset.",
        tags: ["typology", "Greenberg", "universals"],
      },
      {
        name: "Implicational universals",
        description: "If a language has X, it has Y (but not vice versa).",
        keyFact: "Dual ⊃ plural; trial ⊃ dual ⊃ plural. Defines tight typological clines that no language has been documented to violate.",
        tags: ["typology", "implicational"],
      },
      {
        name: "Word-order typology (basic and morpheme order)",
        description: "Languages cluster by where heads sit.",
        keyFact: "Dryer (1992) replaced Greenberg's basic-WO correlations with finer typology. Many features are 'noisy' but OV/VO and Adj-N order correlate weakly globally.",
        tags: ["typology", "word-order", "Dryer"],
      },
      {
        name: "Animacy hierarchy",
        description: "1st > 2nd > 3rd > human > animate > inanimate, governing many grammatical phenomena.",
        keyFact: "Silverstein (1976): split ergativity often cuts the hierarchy — high animacy nouns pattern nom/acc, low animacy pattern erg/abs. Differential object marking too.",
        tags: ["typology", "animacy"],
      },
      {
        name: "Definiteness hierarchy",
        description: "Personal pronouns > proper names > definite > indefinite specific > non-specific.",
        keyFact: "Aissen (2003) ties DOM, agreement, and other phenomena to combined animacy × definiteness hierarchies.",
        tags: ["typology", "definiteness"],
      },
      {
        name: "Alignment (nominative-accusative, ergative-absolutive, active-stative, tripartite)",
        description: "How languages mark subjects of intransitives, transitives, and objects.",
        keyFact: "Nom/Acc: SubjIntrans = SubjTrans ≠ Obj (English). Erg/Abs: SubjIntrans = Obj ≠ SubjTrans (Basque, Dyirbal). Split-ergative very common.",
        tags: ["typology", "alignment", "ergative"],
      },
      {
        name: "Polypersonal agreement",
        description: "Verb agrees with multiple arguments.",
        keyFact: "Basque, Georgian, Mohawk, Swahili agree with subject and object (and sometimes indirect object). Polysynthetic languages typically do.",
        tags: ["typology", "agreement"],
      },
      {
        name: "Evidentiality",
        description: "Grammatical marking of information source.",
        keyFact: "Tuyuca (Amazonian) has obligatory marking with ~5 evidential categories (visual, non-visual sensory, inferred, hearsay, assumed). English encodes this lexically.",
        tags: ["typology", "evidentiality"],
      },
      {
        name: "Classifiers vs noun classes (genders)",
        description: "Two systems for sorting nominal referents.",
        keyFact: "Numeral classifiers (Mandarin: 三只猫 'three CL cat') appear with counting/specification. Noun classes (Bantu, Romance gender) trigger agreement.",
        tags: ["typology", "classifiers", "gender"],
      },
      {
        name: "Switch-reference",
        description: "Verbal marking indicating whether the next clause shares its subject with the current one.",
        keyFact: "Common in Amazonian, Papuan, and N. American languages (e.g., Eastern Pomo). DS (different subject) and SS (same subject) suffixes.",
        tags: ["typology", "switch-reference"],
      },
      {
        name: "World Atlas of Language Structures (WALS)",
        description: "Online typological database covering 192 features across 2,679 languages.",
        keyFact: "Haspelmath et al. WALS lets you map any feature globally. Reveals geographic clusters (Sprachbund effects) that confound genetic explanations.",
        tags: ["typology", "WALS", "database"],
      },
      {
        name: "Sprachbund (linguistic area)",
        description: "Geographic convergence among unrelated languages.",
        keyFact: "Balkan Sprachbund: postposed definite article, future with 'want', reduced infinitive across Albanian, Bulgarian, Romanian, Greek. South Asia, Mesoamerica also classic cases.",
        tags: ["typology", "Sprachbund"],
      },
    ],
  },

  // ── Family 16 — Semiotics & language philosophy ─────────────────────────
  {
    slug: "semiotics-philosophy",
    number: 16,
    name: "Semiotics & Philosophy of Language",
    blurb: "Signs, meaning, reference, intentionality — bordering philosophy.",
    section: "D",
    color: "violet",
    entries: [
      {
        name: "Saussure's signifier / signified",
        description: "Sign = signifier (form) + signified (concept); the link is arbitrary.",
        keyFact: "Cours de linguistique générale (1916, posthumous). Founded structuralist linguistics; signs gain value by opposition within a system.",
        tags: ["semiotics", "Saussure"],
        xref: ["philosophy"],
      },
      {
        name: "Peirce's triadic sign",
        description: "Icon, index, symbol — three modes of sign relation.",
        keyFact: "Icon: resembles (portrait); Index: contiguous/caused (smoke→fire); Symbol: by convention (words). Often coexist in one sign.",
        tags: ["semiotics", "Peirce"],
        xref: ["philosophy"],
      },
      {
        name: "Arbitrariness of the sign",
        description: "No intrinsic resemblance between form and meaning.",
        keyFact: "Saussure's foundational principle. Onomatopoeia and sound symbolism are minor exceptions; bouba/kiki effect shows some non-arbitrariness exists.",
        tags: ["semiotics", "arbitrariness"],
      },
      {
        name: "Bouba/kiki effect (Köhler 1929)",
        description: "Cross-cultural mapping of nonsense sounds to shapes.",
        keyFact: "~95% of subjects match 'bouba' to a rounded shape and 'kiki' to a spiky shape, across cultures and ages. Sound symbolism is psychologically real.",
        tags: ["semiotics", "sound-symbolism"],
      },
      {
        name: "Speech acts (Searle's philosophy)",
        description: "Conditions on illocutionary acts: preparatory, sincerity, essential.",
        keyFact: "Promising requires speaker can perform, intends to, predicates future act, counts as obligation. Failures violate felicity conditions.",
        tags: ["semiotics", "Searle"],
        xref: ["philosophy"],
      },
      {
        name: "Reference and proper names (Kripke, Putnam)",
        description: "Causal-historical theory of names.",
        keyFact: "Kripke (Naming and Necessity, 1980): names are rigid designators fixed by a causal chain from an initial baptism; not by descriptions in speakers' heads.",
        tags: ["semiotics", "reference", "Kripke"],
        xref: ["philosophy"],
      },
      {
        name: "Indexicality and demonstratives (Kaplan)",
        description: "Context-dependent expressions: I, here, now, this.",
        keyFact: "Kaplan distinguishes character (linguistic meaning, function from contexts to contents) from content (proposition expressed in a context).",
        tags: ["semiotics", "indexical", "Kaplan"],
        xref: ["philosophy"],
      },
      {
        name: "Mentalese / Language of Thought (Fodor)",
        description: "Thought as computation over a language-like internal representation.",
        keyFact: "Fodor (1975): mentalese is innate, symbolic, compositional, prior to natural language. Connectionists and embodied-cognition theorists reject.",
        tags: ["semiotics", "Fodor", "LOT"],
        xref: ["philosophy"],
        status: "contested",
      },
      {
        name: "Linguistic relativity (weak Whorfian)",
        description: "Language influences (but does not determine) thought.",
        keyFact: "Documented effects on color memory (Berinmo), spatial frames of reference (Tzeltal absolute vs English egocentric), grammatical gender on object categorization.",
        tags: ["semiotics", "Whorf", "relativity"],
        status: "contested",
      },
      {
        name: "Wittgenstein on language games",
        description: "Meaning as use; family resemblance; no essence shared by all 'games'.",
        keyFact: "Philosophical Investigations (1953): rejects logical-atomist Tractatus picture. Meaning lives in public practices, not in mental items.",
        tags: ["semiotics", "Wittgenstein"],
        xref: ["philosophy"],
      },
      {
        name: "Derrida and différance",
        description: "Poststructuralist account of meaning as endlessly deferred.",
        keyFact: "Meaning is never present, always traced through differences. Targeted at Saussurean structuralism. Influential beyond linguistics, especially in literary theory.",
        tags: ["semiotics", "Derrida"],
        xref: ["philosophy"],
      },
    ],
  },
];
