import type { Family } from "./types";

export const FAMILIES_17_22: Family[] = [
  // ── Family 17 — Writing systems ──────────────────────────────────────────
  {
    slug: "writing-systems",
    number: 17,
    name: "Writing Systems",
    blurb: "Scripts, orthographies, and their relation to speech.",
    section: "D",
    color: "sky",
    entries: [
      {
        name: "Logographic systems",
        description: "Symbols represent morphemes or words.",
        keyFact: "Chinese characters (~3,000–6,000 in active use, ~50,000+ historical). Each character maps to a morpheme, sometimes with phonetic components.",
        tags: ["writing", "logographic"],
      },
      {
        name: "Syllabaries",
        description: "Symbols represent syllables.",
        keyFact: "Japanese hiragana/katakana (~46 each), Cherokee (85). Efficient when syllable inventory is small.",
        tags: ["writing", "syllabary"],
      },
      {
        name: "Abjads (consonantal alphabets)",
        description: "Letters mostly represent consonants; vowels optional.",
        keyFact: "Arabic, Hebrew. Reader supplies vowels from context; diacritics available for learners and religious texts.",
        tags: ["writing", "abjad"],
      },
      {
        name: "Alphabets",
        description: "Symbols represent both consonants and vowels.",
        keyFact: "Greek (~800 BCE) is the first true alphabet, adapted from Phoenician abjad. Latin, Cyrillic, Armenian, Georgian, Korean Hangul all alphabetic.",
        tags: ["writing", "alphabet"],
      },
      {
        name: "Abugidas (alphasyllabaries)",
        description: "Consonants carry an inherent vowel; other vowels marked with diacritics.",
        keyFact: "Brahmic scripts (Devanagari, Tamil, Khmer, Thai). Ge'ez (Ethiopic). Inherent vowel typically /a/.",
        tags: ["writing", "abugida"],
      },
      {
        name: "Featural scripts (Hangul)",
        description: "Shape of letters encodes phonetic features.",
        keyFact: "Korean Hangul (1443) groups letters by syllable block. Consonant shapes reflect articulator (ㄱ velar, ㄴ alveolar, ㅁ bilabial). Vowels combine horizontal/vertical strokes.",
        tags: ["writing", "featural", "Hangul"],
      },
      {
        name: "Origin of writing (cuneiform, hieroglyphs, Chinese)",
        description: "True writing emerged independently 3–4 times.",
        keyFact: "Sumerian cuneiform (~3200 BCE), Egyptian hieroglyphs (~3200 BCE), Chinese (~1250 BCE), Mesoamerican (~600 BCE). All began with logographic/pictographic stages.",
        tags: ["writing", "history"],
      },
      {
        name: "Phonological orthography depth",
        description: "Shallow: regular sound-spelling. Deep: irregular.",
        keyFact: "Finnish, Spanish, Italian shallow. English notoriously deep (mostly because the GVS scrambled the phoneme-grapheme mapping). Affects reading acquisition speed.",
        tags: ["writing", "orthography"],
      },
      {
        name: "Decipherment (Champollion, Ventris)",
        description: "Reading lost scripts.",
        keyFact: "Champollion 1822: Egyptian hieroglyphs via the Rosetta Stone. Ventris 1952: Linear B = Mycenaean Greek. Linear A and Proto-Elamite remain undeciphered.",
        tags: ["writing", "decipherment"],
        status: "contested",
      },
      {
        name: "Reading processes (dual-route)",
        description: "Whole-word lexical route + grapheme-phoneme assembly route.",
        keyFact: "Dual-route cascaded model (Coltheart). Surface dyslexia damages lexical; phonological dyslexia damages assembly route.",
        tags: ["writing", "reading", "dual-route"],
      },
      {
        name: "Punctuation and prosody",
        description: "Written marks emerged to signal prosodic and syntactic boundaries.",
        keyFact: "Classical scripts had little punctuation (scriptio continua). Modern punctuation systematized largely in the 16th–17th centuries.",
        tags: ["writing", "punctuation"],
      },
    ],
  },

  // ── Family 18 — Sign languages ──────────────────────────────────────────
  {
    slug: "sign-languages",
    number: 18,
    name: "Sign Languages",
    blurb: "Visual-gestural languages with full grammar.",
    section: "D",
    color: "indigo",
    entries: [
      {
        name: "Sign languages are not pantomime",
        description: "Sign languages have phonology, morphology, and syntax as rich as spoken languages.",
        keyFact: "Stokoe (1960) demonstrated ASL phonology: signs decompose into handshape, location, movement, orientation. Field-founding result.",
        tags: ["sign", "Stokoe", "ASL"],
      },
      {
        name: "Sign phonology",
        description: "Sub-lexical parameters: handshape, location, movement, orientation, non-manual features.",
        keyFact: "Minimal pairs differ in one parameter, e.g., ASL APPLE vs CANDY differ in handshape; SUMMER vs UGLY differ in location.",
        tags: ["sign", "phonology"],
      },
      {
        name: "Distinct sign languages",
        description: "Each Deaf community has its own; ASL ≠ BSL ≠ Auslan ≠ LSF.",
        keyFact: "ASL is closer to LSF (its 19th-c. ancestor) than to BSL despite shared spoken language. ~300 sign languages documented.",
        tags: ["sign", "ASL", "BSL"],
      },
      {
        name: "Classifiers in sign",
        description: "Productive handshape morphemes encoding shape, motion, and location.",
        keyFact: "Verbs of motion incorporate classifier handshapes that depict the shape of the moving entity. Polysynthetic-like properties.",
        tags: ["sign", "classifier"],
      },
      {
        name: "Iconicity in sign",
        description: "Many signs are motivated; iconicity is widespread but not random.",
        keyFact: "Iconicity affects acquisition speed for some signs but not grammar overall. Children acquire iconic and non-iconic signs at similar rates.",
        tags: ["sign", "iconicity"],
      },
      {
        name: "Non-manual markers",
        description: "Facial expression, head tilt, eye gaze function as obligatory grammatical signals.",
        keyFact: "ASL yes-no questions require raised eyebrows; wh-questions require furrowed brows; topicalization requires head tilt + raised brows. Equivalent to intonation.",
        tags: ["sign", "non-manual"],
      },
      {
        name: "Nicaraguan Sign Language (ISN)",
        description: "Language emerged in a new deaf school in the 1980s.",
        keyFact: "Senghas and others showed each new cohort grammaticized the system further. Evidence for human language-creation capacity.",
        tags: ["sign", "ISN", "creation"],
      },
      {
        name: "Home sign",
        description: "Gestural systems invented by deaf children without sign-language input.",
        keyFact: "Goldin-Meadow's research: home signers consistently invent regular word order, predicate-argument structure, recursion — pieces of grammar absent from input.",
        tags: ["sign", "home-sign"],
      },
      {
        name: "Cochlear implants and language outcomes",
        description: "Auditory prosthesis; outcomes vary by age and exposure to sign.",
        keyFact: "Implanted before age 2: most children develop near-typical spoken language. Bimodal (CI + sign) exposure offers protective baseline; ban on sign in deaf education is now widely rejected.",
        tags: ["sign", "CI", "deaf-education"],
      },
      {
        name: "Tactile sign / Pro-tactile",
        description: "Sign adapted for deafblind speakers.",
        keyFact: "Pro-tactile ASL (developed in 2000s): signs delivered via hand-over-hand contact; new conventions for backchanneling and turn-taking via touch.",
        tags: ["sign", "pro-tactile", "deafblind"],
      },
      {
        name: "International Sign",
        description: "Pidgin-like contact variety used at international Deaf gatherings.",
        keyFact: "Not a full language; flexible, draws on common iconic signs and improvised translations. Distinct from any national sign language.",
        tags: ["sign", "international"],
      },
    ],
  },

  // ── Family 19 — Anthropological linguistics & language documentation ────
  {
    slug: "anthropological",
    number: 19,
    name: "Anthropological Linguistics & Documentation",
    blurb: "Fieldwork, endangered languages, ethnolinguistics.",
    section: "D",
    color: "amber",
    entries: [
      {
        name: "Language documentation",
        description: "Systematic recording of underdescribed languages.",
        keyFact: "Modern documentation builds multimodal corpora: audio/video, transcription, glossing, translation, metadata. Archives: ELAR, AILLA, PARADISEC.",
        tags: ["fieldwork", "documentation"],
      },
      {
        name: "Boasian tradition",
        description: "Franz Boas's principle: describe each language in its own terms, not via Indo-European categories.",
        keyFact: "Handbook of American Indian Languages (1911) inaugurated rigorous fieldwork on indigenous languages. Sapir, Bloomfield his most influential students.",
        tags: ["fieldwork", "Boas"],
      },
      {
        name: "Interlinear glossed text (IGT)",
        description: "Standard format: original line / morpheme breakdown / morpheme gloss / free translation.",
        keyFact: "Leipzig Glossing Rules (2008) codified the conventions. Underpins all comparative work on underdescribed languages.",
        tags: ["fieldwork", "IGT", "glossing"],
      },
      {
        name: "Ethnographies of speaking (Hymes)",
        description: "Documenting communicative norms, not just structure.",
        keyFact: "SPEAKING acronym: Setting, Participants, Ends, Act sequence, Key, Instrumentalities, Norms, Genre. Adopted widely beyond anthropology.",
        tags: ["ethnography", "Hymes"],
      },
      {
        name: "Pirahã controversy",
        description: "Everett claims Pirahã lacks recursion, numerals, color terms — challenging UG.",
        keyFact: "Everett (2005); Nevins, Pesetsky, Rodrigues (2009) dispute. Stalemate; field consensus is recursion in Pirahã is debatable but the language's typological profile is real.",
        tags: ["fieldwork", "Pirahã", "recursion"],
        status: "contested",
      },
      {
        name: "Color term hierarchies (Berlin & Kay)",
        description: "Basic color terms in any language follow a strict implicational order.",
        keyFact: "Berlin & Kay (1969): if a language has N basic colors, the order is fixed (black/white → red → green/yellow → blue → brown → ...). Refined but largely confirmed.",
        tags: ["ethnography", "color", "Berlin-Kay"],
      },
      {
        name: "Kinship terms",
        description: "Six major systems: Hawaiian, Eskimo, Sudanese, Crow, Omaha, Iroquois.",
        keyFact: "Each system bundles relatives differently. English (Eskimo) lumps father's-brother and mother's-brother as 'uncle'; Sudanese languages distinguish them.",
        tags: ["ethnography", "kinship"],
      },
      {
        name: "Spatial frames of reference",
        description: "Languages differ on egocentric (left/right) vs allocentric (north/south, uphill/downhill).",
        keyFact: "Guugu Yimithirr (Australia), Tzeltal (Mexico) use cardinal-direction terms even for body parts. Speakers retain orientation acuity not found in English speakers.",
        tags: ["ethnography", "space", "Whorf"],
      },
      {
        name: "Endangerment metrics (EGIDS)",
        description: "Expanded Graded Intergenerational Disruption Scale (Ethnologue).",
        keyFact: "0 (international) → 10 (extinct). Threshold for endangerment: EGIDS ≥ 6b. ~40% of languages estimated EGIDS ≥ 6b.",
        tags: ["fieldwork", "endangerment", "EGIDS"],
      },
      {
        name: "Revitalization",
        description: "Efforts to reverse language shift.",
        keyFact: "Hebrew (only complete revival of a non-spoken liturgical language); Māori 'language nests' (kōhanga reo); Welsh (1993 Welsh Language Act). Outcomes vary widely.",
        tags: ["fieldwork", "revitalization"],
      },
      {
        name: "Master-Apprentice Program",
        description: "Intensive 1-on-1 immersion model for endangered languages.",
        keyFact: "Hinton (1994) at Berkeley; adopted across California. Replaces classroom instruction with daily oral apprenticeship.",
        tags: ["fieldwork", "revitalization", "MAP"],
      },
    ],
  },

  // ── Family 20 — Math, logic, formal grammars ────────────────────────────
  {
    slug: "formal-grammars",
    number: 20,
    name: "Formal Grammars & Mathematical Linguistics",
    blurb: "The Chomsky hierarchy, complexity, and formal models of language.",
    section: "E",
    color: "cyan",
    entries: [
      {
        name: "Chomsky hierarchy",
        description: "Four levels: regular ⊂ context-free ⊂ context-sensitive ⊂ recursively enumerable.",
        keyFact: "Chomsky (1956) showed natural languages exceed regular (English center-embedding) and exceed strictly context-free (Swiss German cross-serial dependencies).",
        notation: "\\text{REG} \\subsetneq \\text{CFG} \\subsetneq \\text{CSG} \\subsetneq \\text{RE}",
        tags: ["formal", "Chomsky-hierarchy"],
        xref: ["computer-science", "mathematics"],
      },
      {
        name: "Regular languages",
        description: "Languages recognized by finite-state automata.",
        keyFact: "Closed under union, concatenation, Kleene star, intersection, complement. Adequate for phonology and morphology — finite-state phonology (Kaplan & Kay 1994).",
        tags: ["formal", "FSA", "regular"],
        xref: ["computer-science"],
      },
      {
        name: "Context-free grammars",
        description: "Rewrite rules of form A → β with A a single nonterminal.",
        keyFact: "Parsed in O(n³) (CKY/Earley). English approximately CFG except for cross-serial dependencies, which require mildly context-sensitive power.",
        tags: ["formal", "CFG"],
        xref: ["computer-science"],
      },
      {
        name: "Mildly context-sensitive",
        description: "Class extending CFG to handle cross-serial dependencies but staying polynomial.",
        keyFact: "Includes Tree-Adjoining Grammar (TAG), CCG, Linear Indexed Grammar. All weakly equivalent (Joshi). Natural-language adequate by current evidence.",
        tags: ["formal", "MCS", "TAG", "CCG"],
        xref: ["computer-science"],
      },
      {
        name: "Tree-Adjoining Grammar (TAG)",
        description: "Joshi 1975: grammar formalism with adjunction over elementary trees.",
        keyFact: "Lexicalized TAG: each elementary tree anchored to a lexical item; syntax driven by lexical projection. Polynomial parsing (O(n^6)).",
        tags: ["formal", "TAG"],
        xref: ["computer-science"],
      },
      {
        name: "Combinatory Categorial Grammar (CCG)",
        description: "Steedman's extension of categorial grammar with combinators.",
        keyFact: "Function application + composition + type-raising. Handles coordination, gapping, extraction with a small grammar. Used in modern semantic parsing.",
        notation: "X/Y\\ Y \\Rightarrow X;\\ X/Y\\ Y/Z \\Rightarrow X/Z",
        tags: ["formal", "CCG", "Steedman"],
        xref: ["computer-science"],
      },
      {
        name: "Lexical Functional Grammar (LFG)",
        description: "Two-level grammar: c-structure (constituent) and f-structure (functional).",
        keyFact: "Kaplan & Bresnan (1982). C-structure CFG-style; f-structure encodes grammatical relations directly. Used in computational implementations like XLE.",
        tags: ["formal", "LFG"],
        xref: ["computer-science"],
      },
      {
        name: "Zipf's law",
        description: "Word frequency × rank ≈ constant.",
        keyFact: "Across nearly all natural-language corpora, $f(r) \\propto 1/r^s$ with $s \\approx 1$. Implications for ML: long tail dominates; rare words abundant.",
        notation: "f(r) \\propto \\frac{1}{r^s}",
        tags: ["formal", "Zipf"],
        xref: ["statistics", "mathematics"],
      },
      {
        name: "Heaps' law",
        description: "Vocabulary size grows sublinearly with corpus size.",
        keyFact: "$V(n) = K n^\\beta$ with $\\beta \\approx 0.4$–$0.6$. Even at billions of tokens new words keep appearing — proper names, neologisms.",
        notation: "V(n) = Kn^\\beta",
        tags: ["formal", "Heaps"],
        xref: ["statistics"],
      },
      {
        name: "Entropy and language",
        description: "Information-theoretic measures of redundancy and predictability.",
        keyFact: "Shannon (1951) estimated English entropy at ~1.3 bits/character. Modern LLM cross-entropy on diverse text ~1.1–1.2 bits/char, approaching this bound.",
        notation: "H = -\\sum_i p_i \\log_2 p_i",
        tags: ["formal", "entropy", "Shannon"],
        xref: ["statistics", "mathematics", "computer-science"],
      },
      {
        name: "Hidden Markov Models",
        description: "Probabilistic finite-state models with latent states.",
        keyFact: "Dominant model for speech recognition (1980s–2010) and POS tagging (1990s–2010s). Trained by Baum-Welch (EM); decoded by Viterbi.",
        tags: ["formal", "HMM"],
        xref: ["statistics", "computer-science"],
      },
      {
        name: "Universal Grammar formalism",
        description: "Attempts to formalize the innate language faculty.",
        keyFact: "Principles & Parameters (1980s), Minimalism (1995+). Critics argue UG is unfalsifiable as currently stated; defenders point to specific concrete proposals (e.g., subjacency).",
        tags: ["formal", "UG"],
        status: "contested",
      },
    ],
  },

  // ── Family 21 — Open problems in linguistics ────────────────────────────
  {
    slug: "open-problems",
    number: 21,
    name: "Open Problems",
    blurb: "Genuinely unresolved questions in linguistics as of 2026.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Origin of language",
        description: "When and how did language first emerge in Homo sapiens?",
        keyFact: "Estimates range 50 kya – 500 kya. Gesture-first vs vocal-first; gradual vs saltation. No direct evidence from before writing (~5 kya).",
        tags: ["origin", "evolution"],
        status: "open",
      },
      {
        name: "Are languages still evolving (biologically)?",
        description: "Does language evolution interact with biological evolution today?",
        keyFact: "FOXP2 selective sweep ~200 kya. Tone–ASPM/Microcephalin correlation (Dediu & Ladd 2007) suggested ongoing gene-language coevolution but is contested.",
        tags: ["evolution", "genetics"],
        status: "open",
      },
      {
        name: "Indo-European homeland",
        description: "Steppe (Yamnaya) vs Anatolian hypothesis.",
        keyFact: "Ancient DNA (Reich et al. 2015) strongly supports steppe migration ~3000 BCE. Bayesian phylogenetics (Gray & Atkinson) supports earlier Anatolian origin. Tension unresolved.",
        tags: ["historical", "PIE", "homeland"],
        status: "open",
      },
      {
        name: "Sapir-Whorf — strong relativity",
        description: "Does the language one speaks determine what one can think?",
        keyFact: "Strong determinism refuted; weak effects on color, space, time, gender confirmed. The 'effect size' question (how big, how cognitive) remains open.",
        tags: ["Whorf", "cognition"],
        status: "contested",
      },
      {
        name: "Critical period — sharp or gradient?",
        description: "Discontinuity vs continuous decline in language-acquisition ability.",
        keyFact: "Hartshorne, Tenenbaum, Pinker (2018) found a sharp drop in grammar learning after ~17.4 yrs, suggesting a real critical period. Hard to disentangle from input changes.",
        tags: ["acquisition", "critical-period"],
        status: "contested",
      },
      {
        name: "LLMs and linguistic competence",
        description: "Do large language models 'know' a language?",
        keyFact: "LLMs match human acceptability judgments on many phenomena (Linzen, Warstadt et al.) but fail on others (negation, syntactic islands cleanly). Whether they 'have grammar' is a live debate.",
        tags: ["LLM", "competence"],
        status: "open",
        xref: ["computer-science", "philosophy"],
      },
      {
        name: "Recursion as a human universal",
        description: "Is unbounded recursion universal in human grammar?",
        keyFact: "Hauser, Chomsky, Fitch (2002) proposed recursion as the only narrowly human language faculty. Pirahã claim (Everett) contests this. Field divided.",
        tags: ["recursion", "universal"],
        status: "contested",
      },
      {
        name: "Animal communication and language",
        description: "Why does no other species have human-like language?",
        keyFact: "Vervet alarm calls, prairie-dog calls, bee dances are not generative. Trained-ape sign and lexigram studies (Kanzi, Washoe) show comprehension but no productive syntax. Gap remains stark.",
        tags: ["evolution", "animal"],
        status: "open",
      },
      {
        name: "Reading and dyslexia",
        description: "Causal mechanisms of developmental dyslexia.",
        keyFact: "Phonological-deficit hypothesis dominant. Magnocellular and cerebellar accounts compete. Genetics (DCDC2, DYX1C1) explain a small fraction.",
        tags: ["reading", "dyslexia"],
        status: "open",
      },
      {
        name: "Lexical decision and access ceiling",
        description: "Is there a fundamental limit on word-access speed?",
        keyFact: "Visual lexical decision plateaus at ~400ms; auditory recognition uniqueness points typically ~200–300ms. Whether these reflect processing limits or measurement limits open.",
        tags: ["psycholinguistics", "access"],
        status: "open",
      },
      {
        name: "Are all languages equally complex?",
        description: "Trade-off hypothesis vs uniform complexity.",
        keyFact: "Compensatory complexity (more morphology ⇒ less syntactic; Pinker) once dominant. Recent work (Bentz, Berdicevskis) finds some languages measurably simpler overall, particularly L2-dominated ones.",
        tags: ["typology", "complexity"],
        status: "open",
      },
      {
        name: "Macro-family hypotheses (Nostratic, Altaic, Amerind)",
        description: "Proposed super-families uniting traditionally separate families.",
        keyFact: "Nostratic (Indo-European + Uralic + Altaic + Afro-Asiatic + ...) — methodologically questionable; not accepted by mainstream. Altaic widely rejected. Amerind (Greenberg) widely rejected.",
        tags: ["historical", "macro-family"],
        status: "contested",
      },
    ],
  },

  // ── Family 22 — Linguistic landmarks & misc concepts ────────────────────
  {
    slug: "landmarks",
    number: 22,
    name: "Linguistic Landmarks",
    blurb: "Foundational texts, key figures, and cross-cutting concepts.",
    section: "E",
    color: "amber",
    entries: [
      {
        name: "Pāṇini's Aṣṭādhyāyī (~500 BCE)",
        description: "Sanskrit grammar in ~4,000 ordered sūtras.",
        keyFact: "First fully formal grammar in history. Anticipates phonological feature notation, ordered rules, abstract underlying representations.",
        tags: ["landmark", "Panini"],
      },
      {
        name: "Saussure's Cours (1916)",
        description: "Posthumous lecture-note publication that founded structural linguistics.",
        keyFact: "Established langue/parole, signifier/signified, synchronic/diachronic distinctions. Indirectly seeded structuralism in anthropology and literary theory.",
        tags: ["landmark", "Saussure"],
      },
      {
        name: "Bloomfield's 'Language' (1933)",
        description: "Defined American structuralist linguistics.",
        keyFact: "Anti-mentalist behaviorism; rigorous discovery procedures. Dominated US linguistics until Chomsky's 1957 'Syntactic Structures'.",
        tags: ["landmark", "Bloomfield"],
      },
      {
        name: "Chomsky's 'Syntactic Structures' (1957)",
        description: "Introduced generative grammar.",
        keyFact: "78-page monograph showing English requires transformations beyond CFG. Triggered the 'cognitive revolution' in linguistics, psychology, philosophy.",
        tags: ["landmark", "Chomsky", "1957"],
      },
      {
        name: "Sapir 'Language' (1921)",
        description: "Influential popular and scholarly account.",
        keyFact: "Sapir's writing shaped early-20th-c. linguistic anthropology and seeded what became the Whorf hypothesis. Still in print, still readable.",
        tags: ["landmark", "Sapir"],
      },
      {
        name: "Labov NYC department-store study (1966)",
        description: "Quantitative urban dialect study.",
        keyFact: "Showed /r/ frequency at Saks > Macy's > S. Klein. Established replicable, quantitative methods in sociolinguistics.",
        tags: ["landmark", "Labov"],
      },
      {
        name: "Greenberg 'Universals of Language' (1963)",
        description: "Birth of cross-linguistic typology.",
        keyFact: "30-language sample, 45 universals. Established the implicational-universal program; precursor to WALS and modern typology.",
        tags: ["landmark", "Greenberg", "typology"],
      },
      {
        name: "Stokoe 'Sign Language Structure' (1960)",
        description: "Demonstrated ASL has phonology.",
        keyFact: "Founding paper of sign-language linguistics; established Deaf cultural and linguistic rights as a science-based claim.",
        tags: ["landmark", "Stokoe", "sign"],
      },
      {
        name: "Brown & Levinson 'Politeness' (1987)",
        description: "Cross-cultural theory of face and politeness strategies.",
        keyFact: "Universal face-management strategies tied to weight of imposition × social distance × power. Influential beyond linguistics in CS and HCI.",
        tags: ["landmark", "Brown-Levinson"],
      },
      {
        name: "Goldsmith autosegmental phonology (1976)",
        description: "Multitiered phonological representation.",
        keyFact: "Doctoral dissertation under Halle; reshaped phonological theory by separating tone, length, nasality from segments. Key for tone-language analysis.",
        tags: ["landmark", "Goldsmith"],
      },
      {
        name: "Mikolov word2vec (2013)",
        description: "Triggered the era of distributional vector semantics in NLP.",
        keyFact: "Skip-gram and CBOW with negative sampling produced high-quality word vectors at scale. Enabled massive transfer-learning gains.",
        tags: ["landmark", "word2vec"],
        xref: ["computer-science"],
      },
      {
        name: "Vaswani 'Attention Is All You Need' (2017)",
        description: "Introduced the Transformer.",
        keyFact: "Single most-cited paper of late-2010s ML. The base architecture for BERT, GPT, T5 and essentially every modern LLM.",
        tags: ["landmark", "transformer"],
        xref: ["computer-science"],
      },
      {
        name: "Ferdinand de Saussure",
        description: "Swiss linguist, 1857–1913. Founder of structural linguistics.",
        keyFact: "Cours assembled by students from lecture notes after his death. Earlier work on PIE laryngeals (Mémoire 1879) anticipated Hittite discoveries.",
        tags: ["figure", "Saussure"],
      },
      {
        name: "Edward Sapir",
        description: "American anthropological linguist, 1884–1939. Boas student.",
        keyFact: "Wrote major descriptions of Native American languages (Takelma, Yana, Navajo). Built bridges from linguistics to anthropology and psychology.",
        tags: ["figure", "Sapir"],
      },
      {
        name: "Noam Chomsky",
        description: "Founder of generative grammar; b. 1928.",
        keyFact: "Syntactic Structures (1957), Aspects (1965), Lectures on Government and Binding (1981), The Minimalist Program (1995). Reshaped linguistics, cognitive science, philosophy.",
        tags: ["figure", "Chomsky"],
      },
      {
        name: "William Labov",
        description: "Founder of variationist sociolinguistics; 1927–2024.",
        keyFact: "NYC study (1966), Philadelphia Atlas of North American English. Methodologically rigorous quantitative work on dialect and change.",
        tags: ["figure", "Labov"],
      },
      {
        name: "Roman Jakobson",
        description: "Russian-American linguist, 1896–1982.",
        keyFact: "Prague School; distinctive-feature phonology with Halle; functions of language (referential, emotive, conative, phatic, metalingual, poetic).",
        tags: ["figure", "Jakobson"],
      },
      {
        name: "Joseph Greenberg",
        description: "American typologist, 1915–2001.",
        keyFact: "Founded typology as a discipline. Controversial macro-family proposals (Indo-Pacific, Amerind) widely rejected; universals project enduring.",
        tags: ["figure", "Greenberg"],
      },
    ],
  },
];
