export type Cadence = 'static' | 'daily' | 'weekly' | 'monthly' | 'quarterly' | 'annual' | 'perpetual';

export interface PipelineEntry {
  tag: string;
  name: string;
  upstreamName: string;
  upstreamUrl: string;
  method: string;
  cadence: Cadence;
  caveats?: string;
  retired?: boolean;
}

export const PIPELINES: PipelineEntry[] = [
  // ── Science / Nature ─────────────────────────────────────────────────────
  {
    tag: 'crossref_retractions_v1',
    name: 'CrossRef Retractions',
    upstreamName: 'CrossRef',
    upstreamUrl: 'https://api.crossref.org/works',
    method: 'REST API',
    cadence: 'perpetual',
    caveats: 'Records depend on publishers self-reporting retractions to CrossRef; under-reporting is known.',
  },
  {
    tag: 'retraction_watch_v1',
    name: 'Retraction Watch',
    upstreamName: 'Retraction Watch',
    upstreamUrl: 'https://retractionwatch.com',
    method: 'Bulk dataset',
    cadence: 'static',
    caveats: 'Small curated set; not exhaustive.',
  },
  {
    tag: 'nasa_exoplanet_v1',
    name: 'NASA Exoplanet Archive',
    upstreamName: 'NASA Exoplanet Archive',
    upstreamUrl: 'https://exoplanetarchive.ipac.caltech.edu',
    method: 'REST API (TAP)',
    cadence: 'monthly',
  },
  {
    tag: 'usgs_eq_v1',
    name: 'USGS Earthquakes (M6.5+)',
    upstreamName: 'USGS Earthquake Hazards Program',
    upstreamUrl: 'https://earthquake.usgs.gov/fdsnws/event/1/',
    method: 'REST API (FDSN)',
    cadence: 'perpetual',
  },
  {
    tag: 'iau_constellations_v1',
    name: 'IAU Constellations',
    upstreamName: 'International Astronomical Union',
    upstreamUrl: 'https://www.iau.org/public/themes/constellations/',
    method: 'Static curated list',
    cadence: 'static',
  },
  {
    tag: 'iau_v1',
    name: 'IAU Designations',
    upstreamName: 'International Astronomical Union',
    upstreamUrl: 'https://www.iau.org',
    method: 'Static curated list',
    cadence: 'static',
  },
  {
    tag: 'solar_system_v1',
    name: 'Solar System Bodies',
    upstreamName: 'NASA / IAU',
    upstreamUrl: 'https://solarsystem.nasa.gov',
    method: 'Static curated list',
    cadence: 'static',
  },
  {
    tag: 'nuclear_tests_v1',
    name: 'Nuclear Weapons Tests',
    upstreamName: 'Wikipedia / CTBTO / DOE declassified records',
    upstreamUrl: 'https://en.wikipedia.org/wiki/List_of_nuclear_weapons_tests',
    method: 'Static curated list (Wikipedia-sourced)',
    cadence: 'static',
    caveats: 'Classified tests yield null on date/yield fields. Coverage: US, USSR, China, France, UK, DPRK, India, Pakistan (202 events).',
  },
  {
    tag: 'periodic_table_v1',
    name: 'Periodic Table Elements',
    upstreamName: 'IUPAC / Bowserinator JSON',
    upstreamUrl: 'https://github.com/Bowserinator/Periodic-Table-JSON',
    method: 'Static JSON (IUPAC-derived)',
    cadence: 'static',
  },
  {
    tag: 'volcanic_eruptions_v1',
    name: 'Significant Volcanic Eruptions',
    upstreamName: 'NOAA NGDC / Smithsonian GVP',
    upstreamUrl: 'https://www.ngdc.noaa.gov/hazel/hazard-service/api/v1/volcanoes',
    method: 'REST API (NOAA), fallback GVP',
    cadence: 'monthly',
  },
  {
    tag: 'space_missions_v1',
    name: 'Orbital Space Missions (GCAT)',
    upstreamName: 'Jonathan McDowell — GCAT',
    upstreamUrl: 'https://planet4589.org/space/gcat/',
    method: 'Bulk TSV download',
    cadence: 'monthly',
    caveats: 'Filter: OrbPay > 0 (payloads that reached orbit). Sputnik 1957 → present.',
  },
  {
    tag: 'who_essential_medicines_v1',
    name: 'WHO Essential Medicines List',
    upstreamName: 'World Health Organization',
    upstreamUrl: 'https://www.who.int/groups/expert-committee-on-selection-and-use-of-essential-medicines/essential-medicines-lists',
    method: 'Static (23rd edition, 2023)',
    cadence: 'static',
  },
  {
    tag: 'who_gho_v1',
    name: 'WHO Global Health Observatory',
    upstreamName: 'World Health Organization',
    upstreamUrl: 'https://ghoapi.azureedge.net/api',
    method: 'REST API',
    cadence: 'annual',
    caveats: 'Current scope: 5 indicators (life expectancy, child mortality, PM2.5, obesity, alcohol) — best year per country.',
  },
  {
    tag: 'genbank_v1',
    name: 'GenBank Accessions',
    upstreamName: 'NCBI GenBank',
    upstreamUrl: 'https://www.ncbi.nlm.nih.gov/genbank/',
    method: 'Entrez API',
    cadence: 'static',
    caveats: 'Small curated set; full GenBank corpus is background-tier.',
  },
  {
    tag: 'omim_v1',
    name: 'OMIM Phenotype Entries',
    upstreamName: 'OMIM (Online Mendelian Inheritance in Man)',
    upstreamUrl: 'https://omim.org',
    method: 'REST API (requires OMIM_API_KEY)',
    cadence: 'static',
    caveats: 'Partial ingest — hit rate limit 2026-05-21 at ~1,512 entries; resumption pending. Target ~15,000.',
  },
  {
    tag: 'pubchem_v1',
    name: 'PubChem Compounds',
    upstreamName: 'PubChem / NCBI',
    upstreamUrl: 'https://pubchem.ncbi.nlm.nih.gov',
    method: 'REST API (PUG)',
    cadence: 'static',
    caveats: 'Small curated set; full PubChem corpus is background-tier.',
  },
  {
    tag: 'nist_constants_v1',
    name: 'NIST Physical Constants (CODATA)',
    upstreamName: 'NIST / CODATA',
    upstreamUrl: 'https://physics.nist.gov/cuu/Constants/',
    method: 'Bulk file (CODATA 2022)',
    cadence: 'static',
  },

  // ── Medicine / Pharma ─────────────────────────────────────────────────────
  {
    tag: 'openfda_v1',
    name: 'FDA Drug Approvals',
    upstreamName: 'openFDA (FDA)',
    upstreamUrl: 'https://open.fda.gov/apis/drug/',
    method: 'REST API',
    cadence: 'monthly',
  },
  {
    tag: 'faers_normalized_drugs_v1',
    name: 'FDA Adverse Event Reports — Drug-Level Aggregates',
    upstreamName: 'FDA FAERS via openFDA',
    upstreamUrl: 'https://api.fda.gov/drug/event.json',
    method: 'REST API',
    cadence: 'quarterly',
    caveats: 'Drug-level aggregate counts only (reference-tier). Individual FAERS reports are background-tier. Cap: 1,000 drugs.',
  },
  {
    tag: 'openfda_labels_v1',
    name: 'FDA Drug Labels',
    upstreamName: 'openFDA',
    upstreamUrl: 'https://open.fda.gov/apis/drug/label/',
    method: 'REST API',
    cadence: 'static',
    caveats: 'Partial ingest (~52k of ~258k labels). Architectural gate applied — scope subject to review.',
  },
  {
    tag: 'clinicaltrials_v1',
    name: 'ClinicalTrials.gov Registrations',
    upstreamName: 'ClinicalTrials.gov (NLM)',
    upstreamUrl: 'https://clinicaltrials.gov/api/v2/',
    method: 'REST API',
    cadence: 'monthly',
  },
  {
    tag: 'nih_reporter_v1',
    name: 'NIH Research Grants (RePORTER)',
    upstreamName: 'NIH RePORTER',
    upstreamUrl: 'https://api.reporter.nih.gov',
    method: 'REST API',
    cadence: 'annual',
  },
  {
    tag: 'icd11_v1',
    name: 'WHO ICD-11 Disease Classifications',
    upstreamName: 'World Health Organization',
    upstreamUrl: 'https://icd.who.int/icdapi',
    method: 'REST API (ICD-11 MMS)',
    cadence: 'annual',
  },
  {
    tag: 'rxnorm_v1',
    name: 'RxNorm Drug Names',
    upstreamName: 'NLM RxNorm',
    upstreamUrl: 'https://rxnav.nlm.nih.gov/REST/',
    method: 'REST API',
    cadence: 'static',
    caveats: 'In progress — target ~14,632 canonical drug names.',
  },
  {
    tag: 'chebi_v1',
    name: 'ChEBI Chemical Entities',
    upstreamName: 'EBI ChEBI',
    upstreamUrl: 'https://www.ebi.ac.uk/chebi/',
    method: 'Bulk OBO download',
    cadence: 'static',
    caveats: 'In progress — target ~62,000 chemical entities.',
  },

  // ── US Law / Government ───────────────────────────────────────────────────
  {
    tag: 'congress_v1',
    name: 'US Enacted Legislation',
    upstreamName: 'Congress.gov',
    upstreamUrl: 'https://api.congress.gov',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'fr_rules_v1',
    name: 'Federal Register Significant Final Rules',
    upstreamName: 'Federal Register (NARA)',
    upstreamUrl: 'https://www.federalregister.gov/api/v1',
    method: 'REST API',
    cadence: 'perpetual',
    caveats: 'Filter: significant final rules under EO 12866 (EPA, FDA, OSHA, CMS, DEA, FTC, FCC). Coverage: 1994–present.',
  },
  {
    tag: 'sec_edgar_v1',
    name: 'SEC EDGAR Significant Filings',
    upstreamName: 'SEC EDGAR',
    upstreamUrl: 'https://www.sec.gov/cgi-bin/browse-edgar',
    method: 'REST API + archive crawl',
    cadence: 'static',
    caveats: 'Curated set of historically significant filings (Enron, WorldCom, Lehman Brothers, Boeing 737 MAX, General Electric). Not a full EDGAR index.',
  },
  {
    tag: 'courtlistener_scotus_v1',
    name: 'US Supreme Court Opinions',
    upstreamName: 'CourtListener (Free Law Project)',
    upstreamUrl: 'https://www.courtlistener.com/api/rest/v4/',
    method: 'REST API',
    cadence: 'perpetual',
    caveats: 'Post-2000 ingest, minimum 10 citations. In-progress backfill.',
  },
  {
    tag: 'doj_fara_v1',
    name: 'DOJ Foreign Agent Registrations (FARA)',
    upstreamName: 'Department of Justice FARA Unit',
    upstreamUrl: 'https://efile.fara.gov',
    method: 'Bulk CSV',
    cadence: 'quarterly',
    caveats: 'Active registrations only. One claim per registrant–foreign-principal pair.',
  },
  {
    tag: 'openfec_v1',
    name: 'FEC Candidate Fundraising Totals',
    upstreamName: 'OpenFEC (FEC)',
    upstreamUrl: 'https://api.open.fec.gov/v1/',
    method: 'REST API',
    cadence: 'annual',
    caveats: 'Coverage: 2020, 2022, 2024 election cycles.',
  },
  {
    tag: 'openfec_ie_v1',
    name: 'FEC Super PAC Independent Expenditures',
    upstreamName: 'OpenFEC (FEC)',
    upstreamUrl: 'https://api.open.fec.gov/v1/',
    method: 'REST API',
    cadence: 'annual',
    caveats: 'Coverage: 2020, 2022, 2024 election cycles.',
  },
  {
    tag: 'congress_votes_v1',
    name: 'US Congressional Roll Call Votes',
    upstreamName: 'Congress.gov',
    upstreamUrl: 'https://api.congress.gov',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'voteview_v1',
    name: 'Voteview Roll Call Votes (Full)',
    upstreamName: 'Voteview / Lewis et al.',
    upstreamUrl: 'https://voteview.com/data',
    method: 'Bulk CSV download',
    cadence: 'static',
    caveats: 'Full historical roll call record from 1789; includes DW-NOMINATE ideology scores.',
  },
  {
    tag: 'congress_stock_act_v1',
    name: 'STOCK Act Disclosures',
    upstreamName: 'US House / Senate disclosure portals',
    upstreamUrl: 'https://efts.house.gov/EFDAPI/',
    method: 'REST API',
    cadence: 'monthly',
    caveats: 'Small initial set; full disclosure corpus expansion pending.',
  },
  {
    tag: 'cces_v1',
    name: 'CCES Constituent Opinion Survey',
    upstreamName: 'Harvard Dataverse (CCES Cumulative File)',
    upstreamUrl: 'https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/II2DB6',
    method: 'Bulk download (Harvard Dataverse)',
    cadence: 'static',
    caveats: '702k respondents, 2006–2024. Aggregated to (state, year, topic) level. Used to compute representation gap vs. congressional vote record.',
  },

  // ── International Law ─────────────────────────────────────────────────────
  {
    tag: 'un_sc_resolutions_v1',
    name: 'UN Security Council Resolutions',
    upstreamName: 'United Nations',
    upstreamUrl: 'https://digitallibrary.un.org',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'un_ga_resolutions_v1',
    name: 'UN General Assembly Resolutions',
    upstreamName: 'United Nations',
    upstreamUrl: 'https://digitallibrary.un.org',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'echr_judgments_v1',
    name: 'ECHR Judgments',
    upstreamName: 'European Court of Human Rights',
    upstreamUrl: 'https://hudoc.echr.coe.int',
    method: 'REST API (HUDOC)',
    cadence: 'perpetual',
  },
  {
    tag: 'icj_judgments_v1',
    name: 'International Court of Justice Judgments',
    upstreamName: 'International Court of Justice',
    upstreamUrl: 'https://www.icj-cij.org/decisions',
    method: 'Bulk download',
    cadence: 'static',
    caveats: 'Coverage: 1946–2023 (800 decisions).',
  },
  {
    tag: 'wto_disputes_v1',
    name: 'WTO Dispute Settlement Cases',
    upstreamName: 'World Trade Organization',
    upstreamUrl: 'https://www.wto.org/english/tratop_e/dispu_e/dispu_status_e.htm',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'nato_official_texts_v1',
    name: 'NATO Official Texts',
    upstreamName: 'NATO',
    upstreamUrl: 'https://www.nato.int/cps/en/natohq/official_texts.htm',
    method: 'Archive crawl (Wayback CDX)',
    cadence: 'static',
  },

  // ── Nobel Prizes ──────────────────────────────────────────────────────────
  {
    tag: 'nobel_v1',
    name: 'Nobel Prize Laureates',
    upstreamName: 'Nobel Foundation',
    upstreamUrl: 'https://api.nobelprize.org/2.1/',
    method: 'REST API',
    cadence: 'annual',
  },

  // ── Economic Data ─────────────────────────────────────────────────────────
  {
    tag: 'worldbank_v1',
    name: 'World Bank Development Indicators',
    upstreamName: 'World Bank Open Data',
    upstreamUrl: 'https://api.worldbank.org/v2/',
    method: 'REST API',
    cadence: 'annual',
  },
  {
    tag: 'vdem_v1',
    name: 'V-Dem Democracy Indicators',
    upstreamName: 'Varieties of Democracy (V-Dem)',
    upstreamUrl: 'https://www.v-dem.net/data/',
    method: 'Bulk download',
    cadence: 'static',
    caveats: 'Small initial set (1 record); full V-Dem ingest pending.',
  },

  // ── Legislation: European ─────────────────────────────────────────────────
  {
    tag: 'riksdag_v1',
    name: 'Swedish Riksdag Legislation',
    upstreamName: 'Sveriges riksdag',
    upstreamUrl: 'https://riksdagen.se/sv/sok/?typ=doktyp&doktyp=bet',
    method: 'Open API',
    cadence: 'perpetual',
  },
  {
    tag: 'tweedekamer_v1',
    name: 'Dutch Tweede Kamer Legislation',
    upstreamName: 'Tweede Kamer der Staten-Generaal',
    upstreamUrl: 'https://gegevens.tweedekamer.nl',
    method: 'OData API',
    cadence: 'perpetual',
  },
  {
    tag: 'bundestag_v1',
    name: 'German Bundestag Enacted Laws',
    upstreamName: 'Deutscher Bundestag DIP',
    upstreamUrl: 'https://search.dip.bundestag.de/api/v1/',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'nationalrat_v1',
    name: 'Austrian Nationalrat Legislation',
    upstreamName: 'Parlament.gv.at',
    upstreamUrl: 'https://www.parlament.gv.at',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'oireachtas_v1',
    name: 'Irish Oireachtas Enacted Acts',
    upstreamName: 'Houses of the Oireachtas',
    upstreamUrl: 'https://api.oireachtas.ie',
    method: 'Open API',
    cadence: 'perpetual',
  },
  {
    tag: 'eu_parliament_v1',
    name: 'European Parliament Acts',
    upstreamName: 'European Parliament',
    upstreamUrl: 'https://www.europarl.europa.eu',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'eu_parliament_votes_v2',
    name: 'European Parliament Plenary Roll-Call Votes',
    upstreamName: 'HowTheyVote.eu',
    upstreamUrl: 'https://howtheyvote.eu',
    method: 'Bulk dataset download',
    cadence: 'static',
    caveats: 'Full per-political-group breakdown (EPP, S&D, Renew, Greens, ECR, etc.).',
  },
  {
    tag: 'scotland_legislation_v1',
    name: 'Scottish Parliament Acts',
    upstreamName: 'legislation.gov.uk',
    upstreamUrl: 'https://www.legislation.gov.uk',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'wales_senedd_v1',
    name: 'Welsh Senedd Acts',
    upstreamName: 'Senedd Cymru',
    upstreamUrl: 'https://senedd.wales',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'estonia_legislation_v1',
    name: 'Estonian Legislation',
    upstreamName: 'Riigi Teataja',
    upstreamUrl: 'https://www.riigiteataja.ee',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'malta_legislation_v1',
    name: 'Maltese Legislation',
    upstreamName: 'Malta Government',
    upstreamUrl: 'https://legislation.mt',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'romania_legislation_v1',
    name: 'Romanian Legislation',
    upstreamName: 'Romanian Government',
    upstreamUrl: 'https://legislatie.just.ro',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'hungary_legislation_v1',
    name: 'Hungarian Legislation',
    upstreamName: 'Hungarian National Assembly',
    upstreamUrl: 'https://mkogy.hu',
    method: 'REST API',
    cadence: 'perpetual',
    caveats: 'Partial ingest (170 records); full re-run pending.',
  },
  {
    tag: 'slovenia_legislation_v1',
    name: 'Slovenian Legislation',
    upstreamName: 'PISRS (Pravno-informacijski sistem)',
    upstreamUrl: 'https://www.pisrs.si',
    method: 'XML sitemaps',
    cadence: 'perpetual',
    caveats: 'Partial ingest (10 records); full re-run pending.',
  },
  {
    tag: 'czech_legislation_v1',
    name: 'Czech Legislation',
    upstreamName: 'Czech Parliament',
    upstreamUrl: 'https://psp.cz',
    method: 'REST API',
    cadence: 'perpetual',
    caveats: 'Partial ingest (5 records); full re-run pending.',
  },
  {
    tag: 'latvia_legislation_v1',
    name: 'Latvian Legislation',
    upstreamName: 'Likumi.lv',
    upstreamUrl: 'https://likumi.lv',
    method: 'Archive crawl (CDX)',
    cadence: 'perpetual',
    caveats: 'Partial ingest (5 records); full re-run pending.',
  },
  {
    tag: 'slovakia_legislation_v1',
    name: 'Slovak Legislation',
    upstreamName: 'Slovak Parliament',
    upstreamUrl: 'https://www.nrsr.sk',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'finland_legislation_v1',
    name: 'Finnish Legislation',
    upstreamName: 'Finnish Parliament',
    upstreamUrl: 'https://www.eduskunta.fi',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'portugal_legislation_v1',
    name: 'Portuguese Legislation',
    upstreamName: 'Assembleia da República',
    upstreamUrl: 'https://www.parlamento.pt',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'norway_legislation_v1',
    name: 'Norwegian Legislation',
    upstreamName: 'Stortinget',
    upstreamUrl: 'https://data.stortinget.no',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'iceland_legislation_v1',
    name: 'Icelandic Legislation',
    upstreamName: 'Althingi',
    upstreamUrl: 'https://www.althingi.is',
    method: 'REST API',
    cadence: 'perpetual',
  },

  // ── Legislation: Americas ─────────────────────────────────────────────────
  {
    tag: 'canada_bills_v1',
    name: 'Canadian Federal Bills (Royal Assent)',
    upstreamName: 'LEGISinfo (Parliament of Canada)',
    upstreamUrl: 'https://www.parl.ca/legisinfo',
    method: 'REST API',
    cadence: 'perpetual',
    caveats: 'Coverage: 35th–45th Parliament.',
  },
  {
    tag: 'nz_legislation_v1',
    name: 'New Zealand Acts in Force',
    upstreamName: 'New Zealand Parliamentary Counsel Office',
    upstreamUrl: 'https://www.legislation.govt.nz',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'nz_repealed_acts_v1',
    name: 'New Zealand Repealed Acts',
    upstreamName: 'New Zealand Parliamentary Counsel Office',
    upstreamUrl: 'https://www.legislation.govt.nz',
    method: 'REST API',
    cadence: 'static',
  },
  {
    tag: 'nz_bills_v1',
    name: 'New Zealand Bills',
    upstreamName: 'New Zealand Parliamentary Counsel Office',
    upstreamUrl: 'https://www.legislation.govt.nz',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'nz_local_acts_v1',
    name: 'New Zealand Local and Private Acts',
    upstreamName: 'New Zealand Parliamentary Counsel Office',
    upstreamUrl: 'https://www.legislation.govt.nz',
    method: 'REST API',
    cadence: 'static',
  },
  {
    tag: 'peru_legislation_v1',
    name: 'Peruvian Legislation',
    upstreamName: 'Congreso de la República del Perú',
    upstreamUrl: 'https://congreso.gob.pe',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'tt_legislation_v1',
    name: 'Trinidad & Tobago Legislation',
    upstreamName: 'Parliament of Trinidad and Tobago',
    upstreamUrl: 'https://ttparliament.org',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'jamaica_legislation_v1',
    name: 'Jamaican Legislation',
    upstreamName: 'Parliament of Jamaica',
    upstreamUrl: 'https://japarliament.gov.jm',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'uruguay_legislation_v1',
    name: 'Uruguayan Legislation',
    upstreamName: 'Parlamento del Uruguay',
    upstreamUrl: 'https://parlamento.gub.uy',
    method: 'REST API',
    cadence: 'perpetual',
  },

  // ── Legislation: Asia-Pacific ─────────────────────────────────────────────
  {
    tag: 'korea_legislation_v1',
    name: 'Korean Legislation (KLRI)',
    upstreamName: 'Korea Legislation Research Institute',
    upstreamUrl: 'https://www.law.go.kr',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'israel_knesset_v1',
    name: 'Israeli Knesset Primary Laws',
    upstreamName: 'Knesset of Israel',
    upstreamUrl: 'https://main.knesset.gov.il',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'malaysia_legislation_v1',
    name: 'Malaysian Legislation',
    upstreamName: "Malaysian Attorney General's Chambers",
    upstreamUrl: 'https://www.agc.gov.my',
    method: 'Bulk download',
    cadence: 'static',
  },
  {
    tag: 'singapore_legislation_v1',
    name: 'Singapore Legislation',
    upstreamName: "Singapore Attorney-General's Chambers",
    upstreamUrl: 'https://sso.agc.gov.sg',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'taiwan_legislation_v1',
    name: 'Taiwan Legislative Yuan',
    upstreamName: 'Legislative Yuan (Taiwan)',
    upstreamUrl: 'https://data.ly.gov.tw',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'srilanka_legislation_v1',
    name: 'Sri Lanka Legislation',
    upstreamName: 'Parliament of Sri Lanka',
    upstreamUrl: 'https://www.parliament.lk',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'bangladesh_legislation_v1',
    name: 'Bangladeshi Legislation',
    upstreamName: 'Bangladesh National Parliament',
    upstreamUrl: 'https://bdlaws.minlaw.gov.bd',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'paclii_legislation_v1',
    name: 'Pacific Island Legislation (PacLII)',
    upstreamName: 'PacLII (Pacific Islands Legal Information Institute)',
    upstreamUrl: 'https://www.paclii.org',
    method: 'Archive crawl (Wayback CDX)',
    cadence: 'static',
    caveats: 'Solomon Islands and Vanuatu CDX timed out (0 records). Coverage: other Pacific Island jurisdictions.',
  },
  {
    tag: 'brunei_legislation_v1',
    name: 'Brunei Legislation',
    upstreamName: "Attorney General's Chambers of Brunei Darussalam",
    upstreamUrl: 'https://www.agc.gov.bn',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'japan_legislation_v1',
    name: 'Japanese Legislation',
    upstreamName: 'National Diet Library / e-Gov',
    upstreamUrl: 'https://laws.e-gov.go.jp',
    method: 'REST API',
    cadence: 'perpetual',
  },

  // ── Legislation: Middle East / Africa ─────────────────────────────────────
  {
    tag: 'uae_legislation_v1',
    name: 'UAE Federal Laws',
    upstreamName: 'UAE Government',
    upstreamUrl: 'https://uaelegislation.gov.ae',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'georgia_legislation_v1',
    name: 'Georgian Legislation',
    upstreamName: 'Parliament of Georgia',
    upstreamUrl: 'https://matsne.gov.ge',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'south_africa_legislation_v1',
    name: 'South African Legislation',
    upstreamName: 'South African Parliament',
    upstreamUrl: 'https://www.parliament.gov.za',
    method: 'REST API',
    cadence: 'perpetual',
  },
  {
    tag: 'africanlii_v1',
    name: 'AfricaLII Legislation',
    upstreamName: 'AfricaLII (African Legal Information Institute)',
    upstreamUrl: 'https://africalii.org',
    method: 'REST API',
    cadence: 'perpetual',
  },

  // ── International / Cross-border ──────────────────────────────────────────
  {
    tag: 'wipo_lex_v1',
    name: 'WIPO Lex IP Laws',
    upstreamName: 'WIPO Lex',
    upstreamUrl: 'https://www.wipo.int/wipolex/',
    method: 'REST API',
    cadence: 'static',
    caveats: 'IP law texts from 190+ countries.',
  },

  // ── Historical Records ─────────────────────────────────────────────────────
  {
    tag: 'jacar_v1',
    name: 'JACAR Japanese Historical Records',
    upstreamName: 'Japan Center for Asian Historical Records',
    upstreamUrl: 'https://www.jacar.archives.go.jp',
    method: 'REST API',
    cadence: 'static',
    caveats: 'B and C series (1931–1945). In-progress full run.',
  },
  {
    tag: 'taiwan_archives_v1',
    name: 'Taiwan National Archives',
    upstreamName: 'Archives Administration, Executive Yuan (Taiwan)',
    upstreamUrl: 'https://archives.gov.tw',
    method: 'REST API',
    cadence: 'static',
  },
  {
    tag: 'romania_cnsas_v1',
    name: 'Romanian Securitate Files (CNSAS)',
    upstreamName: 'CNSAS (Romania National Council for Studying Securitate Archives)',
    upstreamUrl: 'https://www.cnsas.ro',
    method: 'Archive crawl (Wayback CDX)',
    cadence: 'static',
    caveats: 'Institutional records (CC member lists, org charts) only.',
  },
  {
    tag: 'czech_abs_v1',
    name: 'Czech StB Files (ABS)',
    upstreamName: 'Security Services Archive (ABS), Czech Republic',
    upstreamUrl: 'https://www.abscr.cz',
    method: 'Structured database',
    cadence: 'static',
  },
  {
    tag: 'frus_v1',
    name: 'Foreign Relations of the United States (FRUS)',
    upstreamName: 'U.S. Department of State / history.state.gov',
    upstreamUrl: 'https://history.state.gov/historicaldocuments',
    method: 'REST API',
    cadence: 'static',
    caveats: 'WWI, WWII, and Cold War US diplomatic records. Coverage: curated series.',
  },
  {
    tag: 'europeana_wwi_v1',
    name: 'Europeana WWI Collection',
    upstreamName: 'Europeana',
    upstreamUrl: 'https://www.europeana.eu',
    method: 'REST API',
    cadence: 'static',
    caveats: 'WWI items from European archives (heavily Romanian). Language badge for non-EN claims pending.',
  },
  {
    tag: 'ipn_v1',
    name: 'IPN Polish Institute of National Remembrance',
    upstreamName: 'Instytut Pamięci Narodowej (IPN)',
    upstreamUrl: 'https://ipn.gov.pl',
    method: 'REST API',
    cadence: 'static',
    caveats: '50k cap applied from 2.98M total records.',
  },
  {
    tag: 'stasi_v1',
    name: 'Stasi Archives (BStU)',
    upstreamName: 'Bundesarchiv / Stasi-Mediathek',
    upstreamUrl: 'https://www.stasi-mediathek.de',
    method: 'Structured database',
    cadence: 'static',
    caveats: 'Blocked: BStU site has no public API and blocks automated access. Only 2 records returned from trial run. Formal research application required.',
  },

  // ── RETIRED ──────────────────────────────────────────────────────────────
  {
    tag: 'uspto_v1',
    name: 'USPTO Patents (Pipeline 5)',
    upstreamName: 'United States Patent and Trademark Office',
    upstreamUrl: 'https://developer.uspto.gov',
    method: 'Hardcoded curated list (training-data recall — see retirement writeup)',
    cadence: 'static',
    retired: true,
    caveats: 'RETIRED 2026-05-12. All 182 records set to verificationStatus=DEPRECATED. Failure modes: (a) fabricated patent metadata from model recall — confirmed on US4431740; (b) structural field contamination in assignee column. Script relocated to scripts/retired/. See /corrections for full writeup.',
  },
  {
    tag: 'courtlistener_circuits_v1',
    name: 'Federal Circuit Courts (CourtListener)',
    upstreamName: 'CourtListener (Free Law Project)',
    upstreamUrl: 'https://www.courtlistener.com',
    method: 'REST API',
    cadence: 'perpetual',
    retired: true,
    caveats: 'Script written 2026-06-01 but never run; 0 records in database.',
  },
  {
    tag: 'uk_legislation_v1',
    name: 'UK Public General Acts',
    upstreamName: 'legislation.gov.uk',
    upstreamUrl: 'https://www.legislation.gov.uk',
    method: 'REST API',
    cadence: 'perpetual',
    retired: true,
    caveats: 'Ingestion in progress since 2026-05-19; 0 records confirmed in database.',
  },
  {
    tag: 'fred_v1',
    name: 'FRED Economic Indicators',
    upstreamName: 'Federal Reserve Bank of St. Louis',
    upstreamUrl: 'https://fred.stlouisfed.org',
    method: 'REST API (requires FRED_API_KEY)',
    cadence: 'monthly',
    retired: true,
    caveats: 'Script ready; FRED_API_KEY not configured. 0 records in database.',
  },
  {
    tag: 'costarica_legislation_v1',
    name: 'Costa Rica Legislation',
    upstreamName: 'Procuraduría General de la República de Costa Rica',
    upstreamUrl: 'https://pgrweb.go.cr',
    method: 'Archive crawl (Wayback CDX)',
    cadence: 'perpetual',
    retired: true,
    caveats: 'Full run started 2026-05-22; confirmed at ~0 records due to crawl issues.',
  },
];

export function getPipeline(tag: string): PipelineEntry | undefined {
  return PIPELINES.find(p => p.tag === tag);
}

export function getActivePipelines(): PipelineEntry[] {
  return PIPELINES.filter(p => !p.retired);
}
