-- NEUTRALIZED (Task 9): this migration was a duplicate of 20260609000000_claim_fts.
--
-- Both migrations added the same Claim.searchVector generated tsvector column and a
-- GIN index. The original version of this file used bare ADD COLUMN / CREATE INDEX
-- (no IF NOT EXISTS), so on any database where 20260609000000_claim_fts had already
-- run it failed with "column already exists". The canonical, idempotent work now
-- lives solely in 20260609000000_claim_fts/migration.sql.
--
-- This file is intentionally a no-op so the migration history stays linear and
-- `prisma migrate deploy` succeeds on both existing and fresh databases. Do not add
-- DDL here — extend 20260609000000_claim_fts instead.
SELECT 1;
