import type { Family } from "./types";

export const FAMILIES_15_21: Family[] = [
  // ── Family 15 ─────────────────────────────────────────────────────────────
  {
    slug: "polymers",
    number: 15,
    name: "Polymers & Macromolecules",
    blurb: "Long-chain molecules — natural, synthetic, biological — and how they're built.",
    section: "C",
    color: "cyan",
    entries: [
      {
        name: "Monomer & polymer",
        description: "Repeating subunits.",
        keyFact: "A monomer is the small unit; a polymer is the chain. Degree of polymerization (DP) counts repeat units.",
        example: "Polyethylene: $n$ \\ce{CH2=CH2} → \\ce{-(CH2-CH2)_n-}.",
        tags: ["polymers"],
      },
      {
        name: "Addition polymerization",
        description: "Chain growth across π bonds.",
        keyFact: "Initiator opens a double bond; chain propagates by repeated addition; ended by termination.",
        reaction: "n \\ce{H2C=CH2 ->[\\text{cat.}] -(CH2-CH2)_n-}",
        tags: ["polymers", "synthesis"],
      },
      {
        name: "Condensation polymerization",
        description: "Step growth losing a small molecule.",
        keyFact: "Two functional groups react, releasing \\ce{H2O} or \\ce{HCl}; the chain grows in steps.",
        example: "Nylon-6,6 from adipic acid + hexamethylenediamine, releasing \\ce{H2O}.",
        tags: ["polymers", "synthesis"],
      },
      {
        name: "Thermoplastics vs thermosets",
        description: "Melt vs cure.",
        keyFact: "Thermoplastics soften on heating and can be reshaped (PE, PP, PET); thermosets cross-link irreversibly on cure (epoxy, vulcanized rubber).",
        tags: ["polymers", "materials"],
      },
      {
        name: "Tacticity",
        description: "Stereochemistry along a polymer chain.",
        keyFact: "Isotactic (same side), syndiotactic (alternating), atactic (random); affects crystallinity and properties.",
        example: "Isotactic polypropylene is rigid and crystalline; atactic is rubbery.",
        tags: ["polymers", "stereochemistry"],
      },
      {
        name: "Glass-transition temperature",
        description: "Amorphous polymer softening.",
        keyFact: "$T_g$ — below it, the polymer is glassy; above, it's rubbery. Distinct from melting point of crystalline regions.",
        tags: ["polymers", "thermodynamics"],
      },
      {
        name: "Proteins as biopolymers",
        description: "Amino-acid polymers.",
        keyFact: "Peptide-bond (amide) links between α-amino acids; primary, secondary (helix, sheet), tertiary, quaternary structure.",
        tags: ["polymers", "biochemistry"],
      },
      {
        name: "Nucleic acids",
        description: "Phosphodiester polymers.",
        keyFact: "DNA and RNA are polymers of nucleotides (base + sugar + phosphate); double helix stabilized by base pairing and stacking.",
        tags: ["polymers", "biochemistry"],
      },
      {
        name: "Polysaccharides",
        description: "Sugar polymers.",
        keyFact: "Glycosidic bonds join monosaccharides; structural (cellulose, chitin) or storage (starch, glycogen).",
        tags: ["polymers", "biochemistry"],
      },
    ],
  },

  // ── Family 16 ─────────────────────────────────────────────────────────────
  {
    slug: "inorganic-coordination",
    number: 16,
    name: "Inorganic & Coordination Chemistry",
    blurb: "Transition-metal complexes, ligands, crystal-field splitting, and the colors of d-orbital chemistry.",
    section: "D",
    color: "teal",
    entries: [
      {
        name: "Coordination complex",
        description: "Central metal + ligands.",
        keyFact: "A Lewis-acid metal accepts lone pairs from Lewis-base ligands; written \\ce{[ML_n]^{q}} with overall charge $q$.",
        formula: "\\ce{[Cu(NH3)4]^{2+}}",
        tags: ["inorganic", "coordination"],
      },
      {
        name: "Ligand",
        description: "Electron-pair donor bonded to metal.",
        keyFact: "Monodentate (one donor atom), bidentate (e.g., ethylenediamine), polydentate (e.g., EDTA, six donors).",
        example: "\\ce{H2O}, \\ce{NH3}, \\ce{Cl^-}, en, EDTA.",
        tags: ["inorganic", "coordination"],
      },
      {
        name: "Coordination number & geometry",
        description: "How many donors and where.",
        keyFact: "Common geometries: 2 linear, 4 tetrahedral or square-planar, 6 octahedral; 5 and 7+ exist but rarer.",
        tags: ["inorganic", "coordination", "geometry"],
      },
      {
        name: "Chelate effect",
        description: "Polydentate ligands form more stable complexes.",
        keyFact: "Entropy-driven: releasing many monodentate ligands when one polydentate binds increases disorder.",
        example: "\\ce{[Cu(en)2]^{2+}} more stable than \\ce{[Cu(NH3)4]^{2+}}.",
        tags: ["inorganic", "coordination", "thermodynamics"],
      },
      {
        name: "Crystal-field theory",
        description: "d orbitals split in a ligand field.",
        keyFact: "Octahedral field splits d orbitals into $t_{2g}$ (lower) and $e_g$ (higher) by $\\Delta_o$; tetrahedral splits the opposite way and is smaller.",
        tags: ["inorganic", "coordination", "quantum"],
      },
      {
        name: "Spectrochemical series",
        description: "Ligand-field strength ordering.",
        keyFact: "$\\ce{I^-} < \\ce{Br^-} < \\ce{Cl^-} < \\ce{F^-} < \\ce{H2O} < \\ce{NH3} < \\ce{en} < \\ce{CN^-} < \\ce{CO}$; weak-field gives high spin, strong-field gives low spin.",
        tags: ["inorganic", "coordination"],
      },
      {
        name: "High-spin vs low-spin",
        description: "Pairing energy vs $\\Delta$.",
        keyFact: "If $\\Delta < P$ (pairing energy), electrons singly fill higher orbitals (high-spin); if $\\Delta > P$, they pair in lower orbitals (low-spin).",
        tags: ["inorganic", "coordination"],
      },
      {
        name: "Color of transition-metal complexes",
        description: "d–d transitions in the visible.",
        keyFact: "Light absorbed at $hc/\\lambda = \\Delta$; complementary color is transmitted; explains why \\ce{[Cu(H2O)6]^{2+}} is blue.",
        tags: ["inorganic", "coordination", "spectroscopy"],
      },
      {
        name: "Magnetism in complexes",
        description: "Unpaired electrons → paramagnetism.",
        keyFact: "Number of unpaired electrons depends on $d^n$ count and high/low spin; measured by magnetic susceptibility.",
        tags: ["inorganic", "coordination"],
      },
      {
        name: "Coordination isomerism",
        description: "Linkage, ionization, hydrate.",
        keyFact: "Linkage (\\ce{NO2^-} bound via N or O); ionization (\\ce{Cl^-} inside vs outside the coordination sphere); hydrate isomers — same formula, different structure.",
        tags: ["inorganic", "coordination", "isomerism"],
      },
      {
        name: "Organometallic chemistry",
        description: "Metal–carbon bonds.",
        keyFact: "Includes Grignards (R–MgX), ferrocene (\\ce{Fe(C5H5)2}), Wilkinson's catalyst, ZSM zeolites, and the platinum drugs.",
        tags: ["inorganic", "organometallic"],
      },
      {
        name: "Inorganic main-group chemistry",
        description: "Beyond transition metals.",
        keyFact: "Silicates (most of the crust), boranes (electron-deficient), interhalogens (\\ce{ICl}, \\ce{BrF5}), noble-gas compounds (\\ce{XeF4}).",
        tags: ["inorganic", "main-group"],
      },
    ],
  },

  // ── Family 17 ─────────────────────────────────────────────────────────────
  {
    slug: "materials-solid-state",
    number: 17,
    name: "Materials & Solid-State Chemistry",
    blurb: "Crystals, defects, semiconductors, glasses, ceramics, and the materials of the modern world.",
    section: "D",
    color: "emerald",
    entries: [
      {
        name: "Crystal lattice & unit cell",
        description: "Repeating pattern of a solid.",
        keyFact: "Seven crystal systems (cubic, tetragonal, orthorhombic, hexagonal, trigonal, monoclinic, triclinic) × 14 Bravais lattices.",
        tags: ["materials", "solid-state"],
      },
      {
        name: "Close packing",
        description: "Maximally dense sphere packing.",
        keyFact: "ABABAB (hcp) and ABCABC (fcc) both give 74% packing efficiency; common in metals.",
        tags: ["materials", "solid-state"],
        xref: ["mathematics"],
      },
      {
        name: "Ionic vs molecular vs covalent vs metallic solids",
        description: "Four lattice types.",
        keyFact: "Ionic (\\ce{NaCl}): hard, brittle, high mp; molecular (\\ce{I2}, ice): soft, low mp; covalent network (diamond, \\ce{SiO2}): very hard, very high mp; metallic: ductile, conducting.",
        tags: ["materials", "solid-state"],
      },
      {
        name: "Band theory",
        description: "Bonding orbitals smear into bands.",
        keyFact: "Valence band (filled) and conduction band (empty); band gap $E_g$ determines whether the solid is a metal ($E_g = 0$), semiconductor (small $E_g$), or insulator (large $E_g$).",
        tags: ["materials", "solid-state", "quantum"],
      },
      {
        name: "Semiconductors",
        description: "Conductivity tunable by doping.",
        keyFact: "Intrinsic (Si, Ge); n-type (donor dopants like P add carriers to conduction band); p-type (acceptor dopants like B create holes).",
        example: "Modern microelectronics rests on doped silicon.",
        tags: ["materials", "solid-state", "applied"],
      },
      {
        name: "Defects in solids",
        description: "Imperfections that drive properties.",
        keyFact: "Point defects (vacancies, interstitials, substitutional); line defects (dislocations) govern mechanical strength; planar defects (grain boundaries).",
        tags: ["materials", "solid-state"],
      },
      {
        name: "Alloys",
        description: "Metallic mixtures.",
        keyFact: "Substitutional (similar atomic radii, e.g., brass = Cu+Zn) or interstitial (small atoms in gaps, e.g., steel = Fe+C); engineered for strength, corrosion, machinability.",
        tags: ["materials", "metals"],
      },
      {
        name: "Glasses",
        description: "Amorphous, non-crystalline solids.",
        keyFact: "Supercooled liquids with no long-range order; soda-lime glass is \\ce{SiO2} + \\ce{Na2O} + \\ce{CaO}; characterized by $T_g$.",
        tags: ["materials"],
      },
      {
        name: "Ceramics",
        description: "Inorganic non-metallic solids.",
        keyFact: "Ionic/covalent network solids — oxides, nitrides, carbides; hard, refractory, brittle. Includes traditional ceramics and high-tech (\\ce{Al2O3}, \\ce{Si3N4}, ZrO₂).",
        tags: ["materials"],
      },
      {
        name: "Superconductors",
        description: "Zero electrical resistance below $T_c$.",
        keyFact: "Conventional (BCS, $T_c < 30$ K); cuprate high-$T_c$ (up to ~135 K at ambient pressure); hydride superconductors at very high pressures (e.g., \\ce{LaH10}, ~250 K but at ~170 GPa). Room-temperature ambient-pressure superconductivity has not been achieved.",
        tags: ["materials", "solid-state", "open"],
      },
      {
        name: "Nanomaterials",
        description: "Properties dominated by surface area.",
        keyFact: "When size approaches 1–100 nm, quantum confinement and surface effects dominate; includes graphene, carbon nanotubes, quantum dots, fullerenes.",
        tags: ["materials", "nanoscience"],
      },
    ],
  },

  // ── Family 18 ─────────────────────────────────────────────────────────────
  {
    slug: "nuclear-chemistry",
    number: 18,
    name: "Nuclear & Radiochemistry",
    blurb: "Decay, fission, fusion, and the chemistry of unstable nuclei.",
    section: "D",
    color: "amber",
    entries: [
      {
        name: "Radioactive decay",
        description: "Unstable nuclei emit particles.",
        keyFact: "Spontaneous, first-order in N; characterized by decay constant $\\lambda$ and half-life $t_{1/2} = \\ln 2 / \\lambda$.",
        formula: "N(t) = N_0 e^{-\\lambda t}",
        tags: ["nuclear"],
      },
      {
        name: "Alpha decay",
        description: "Emission of a \\ce{^4_2He} nucleus.",
        keyFact: "Loses 2 protons and 2 neutrons; common in heavy nuclei.",
        reaction: "\\ce{^{238}_{92}U -> ^{234}_{90}Th + ^4_2He}",
        tags: ["nuclear", "decay"],
      },
      {
        name: "Beta decay",
        description: "Neutron → proton + e⁻ + antineutrino.",
        keyFact: "$\\beta^-$ raises $Z$ by 1; $\\beta^+$ (positron emission) lowers $Z$ by 1; electron capture is the bound-electron analog of $\\beta^+$.",
        reaction: "\\ce{^{14}_6C -> ^{14}_7N + e- + \\bar\\nu_e}",
        tags: ["nuclear", "decay"],
      },
      {
        name: "Gamma emission",
        description: "Excited nucleus emits a photon.",
        keyFact: "Nuclear de-excitation; no change in Z or A; very high-energy electromagnetic radiation.",
        tags: ["nuclear", "decay"],
      },
      {
        name: "Nuclear fission",
        description: "Heavy nucleus splits.",
        keyFact: "Neutron-induced split of \\ce{^{235}U} into two lighter fragments + 2–3 neutrons + ~200 MeV; basis of reactors and weapons.",
        reaction: "\\ce{^{235}_{92}U + ^1_0n -> ^{141}_{56}Ba + ^{92}_{36}Kr + 3 ^1_0n}",
        tags: ["nuclear", "fission"],
      },
      {
        name: "Nuclear fusion",
        description: "Light nuclei combine.",
        keyFact: "Powers stars; \\ce{^2H + ^3H -> ^4He + ^1_0n} releases ~17.6 MeV. Controlled fusion (ITER, NIF) reached scientific breakeven (NIF, December 2022) but engineering breakeven and grid-relevant power remain open.",
        reaction: "\\ce{^2_1H + ^3_1H -> ^4_2He + ^1_0n}",
        tags: ["nuclear", "fusion", "open"],
      },
      {
        name: "Binding energy & mass defect",
        description: "Why nuclei stay together.",
        keyFact: "$E = (\\Delta m) c^2$; binding energy per nucleon peaks near \\ce{^{56}Fe}.",
        formula: "E = \\Delta m c^2",
        tags: ["nuclear"],
      },
      {
        name: "Decay series & secular equilibrium",
        description: "Chained decays.",
        keyFact: "Four natural series (4n, 4n+1, 4n+2, 4n+3 mod 4 by mass number); after enough time, intermediate activities equal the parent's.",
        tags: ["nuclear"],
      },
      {
        name: "Radiometric dating",
        description: "Decay clocks.",
        keyFact: "Carbon-14 (atmospheric origin, $t_{1/2} = 5730$ y) for organics up to ~50 ky; U–Pb for geological time; potassium-argon for old rocks.",
        tags: ["nuclear", "applied"],
      },
      {
        name: "Synthetic elements",
        description: "Made, not found.",
        keyFact: "Technetium (Z=43) was the first; transuranic elements made by neutron capture or heavy-ion bombardment; all elements through oganesson (Z=118) have been synthesized and named. Elements 119+ have not yet been synthesized.",
        tags: ["nuclear", "elements"],
      },
      {
        name: "Nuclear medicine",
        description: "Radioisotopes for diagnosis and therapy.",
        keyFact: "\\ce{^{99m}Tc} for imaging (γ, $t_{1/2}$=6 h); \\ce{^{131}I} for thyroid therapy ($\\beta$ and γ); PET uses \\ce{^{18}F}-FDG.",
        tags: ["nuclear", "applied", "medicine"],
      },
    ],
  },

  // ── Family 19 ─────────────────────────────────────────────────────────────
  {
    slug: "analytical-instruments",
    number: 19,
    name: "Analytical Chemistry & Instrumentation",
    blurb: "How chemists actually figure out what's in a sample.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Beer–Lambert law",
        description: "Absorbance vs concentration.",
        keyFact: "$A = \\varepsilon c \\ell$ — absorbance is linear in concentration and path length over a useful range.",
        formula: "A = \\varepsilon c \\ell",
        tags: ["analytical", "spectroscopy"],
      },
      {
        name: "UV–Vis spectroscopy",
        description: "Electronic transitions.",
        keyFact: "Measures absorption of UV (200–400 nm) and visible (400–700 nm) light; useful for π systems and metal-complex d–d bands.",
        tags: ["analytical", "spectroscopy"],
      },
      {
        name: "Infrared spectroscopy",
        description: "Vibrational transitions.",
        keyFact: "Bonds absorb at characteristic frequencies; \\ce{C=O} ~1715 cm⁻¹, \\ce{O-H} ~3300 cm⁻¹ broad, \\ce{C-H} ~3000 cm⁻¹.",
        tags: ["analytical", "spectroscopy"],
      },
      {
        name: "NMR spectroscopy",
        description: "Nuclear spins in a magnetic field.",
        keyFact: "Chemical shift, integration, and coupling tell you which carbons/hydrogens are present, how many, and how they're connected.",
        example: "\\ce{^1H} and \\ce{^{13}C} NMR are workhorses of organic structure elucidation.",
        tags: ["analytical", "spectroscopy"],
      },
      {
        name: "Mass spectrometry",
        description: "Ions sorted by mass-to-charge.",
        keyFact: "Ionize, accelerate, deflect, detect; gives molecular ion (M⁺) and a fragmentation pattern; high-resolution MS gives molecular formula.",
        tags: ["analytical"],
      },
      {
        name: "X-ray crystallography",
        description: "Diffraction reveals atomic positions.",
        keyFact: "Bragg's law $n\\lambda = 2d \\sin\\theta$; gives precise bond lengths and angles in crystalline solids; structures of DNA, proteins, minerals.",
        formula: "n\\lambda = 2 d \\sin\\theta",
        tags: ["analytical", "diffraction"],
        xref: ["mathematics"],
      },
      {
        name: "Chromatography",
        description: "Separation by differential affinity.",
        keyFact: "GC (gas), HPLC (liquid), TLC (thin-layer), affinity, ion-exchange; separates by partition between stationary and mobile phases.",
        tags: ["analytical", "separation"],
      },
      {
        name: "Gravimetric & volumetric analysis",
        description: "Classical quantitation.",
        keyFact: "Gravimetric: weigh a precipitate; volumetric: measure the volume of titrant at endpoint; both rely on stoichiometry, not instruments.",
        tags: ["analytical", "classical"],
      },
      {
        name: "Electrochemical analysis",
        description: "Potentiometry, voltammetry.",
        keyFact: "Ion-selective electrodes (pH glass electrode), cyclic voltammetry for redox couples, polarography for trace metals.",
        tags: ["analytical", "electrochemistry"],
      },
      {
        name: "Thermal analysis",
        description: "Properties vs temperature.",
        keyFact: "DSC measures heat flow (\\ce{T_g}, melting, reactions); TGA measures mass change (decomposition, drying).",
        tags: ["analytical", "thermal"],
      },
      {
        name: "Limits of detection & quantitation",
        description: "How low can you measure.",
        keyFact: "LoD ≈ 3 σ above blank; LoQ ≈ 10 σ; method validation reports both alongside linearity, accuracy, and precision.",
        tags: ["analytical", "method-validation"],
        xref: ["statistics"],
      },
      {
        name: "Hyphenated techniques",
        description: "Two instruments in series.",
        keyFact: "GC–MS, LC–MS, ICP–MS combine separation with identification; the workhorse of modern forensic, environmental, and clinical chemistry.",
        tags: ["analytical"],
      },
    ],
  },

  // ── Family 20 ─────────────────────────────────────────────────────────────
  {
    slug: "biochemistry",
    number: 20,
    name: "Biochemistry & Chemical Biology",
    blurb: "The chemistry of life: amino acids, sugars, lipids, nucleic acids, and the metabolism that runs on them.",
    section: "E",
    color: "green",
    entries: [
      {
        name: "Amino acids",
        description: "Building blocks of proteins.",
        keyFact: "20 proteinogenic α-amino acids — same NH₂–CHR–COOH backbone, side chain R varies. All but glycine are chiral; nature uses (L)-form.",
        formula: "\\ce{H2N-CHR-COOH}",
        tags: ["biochemistry"],
      },
      {
        name: "Peptide bond",
        description: "Amide between amino acids.",
        keyFact: "Condensation of NH₂ + COOH; planar with partial double-bond character; trans is strongly preferred except at proline.",
        reaction: "\\ce{H2N-CHR-COOH + H2N-CHR'-COOH -> H2N-CHR-CO-NH-CHR'-COOH + H2O}",
        tags: ["biochemistry", "proteins"],
      },
      {
        name: "Protein structure",
        description: "Four levels of folding.",
        keyFact: "Primary (sequence), secondary (α-helix, β-sheet), tertiary (3-D fold), quaternary (subunit assembly). Folding is largely encoded in sequence (Anfinsen).",
        tags: ["biochemistry", "proteins"],
      },
      {
        name: "Enzymes",
        description: "Protein catalysts.",
        keyFact: "Lower $E_a$ by orders of magnitude through transition-state stabilization; obey Michaelis–Menten kinetics; specificity from active-site geometry.",
        tags: ["biochemistry", "catalysis"],
      },
      {
        name: "Carbohydrates",
        description: "$C_n(H_2O)_n$.",
        keyFact: "Monosaccharides (glucose, fructose), disaccharides (sucrose, lactose), polysaccharides (starch, cellulose); glycosidic bonds.",
        formula: "\\ce{C6H12O6}",
        tags: ["biochemistry"],
      },
      {
        name: "Lipids",
        description: "Hydrophobic biomolecules.",
        keyFact: "Triglycerides (fats), phospholipids (membranes), steroids (cholesterol, hormones); not strictly defined by structure, only by hydrophobicity.",
        tags: ["biochemistry"],
      },
      {
        name: "Nucleotides & nucleic acids",
        description: "DNA and RNA.",
        keyFact: "Base + sugar + phosphate; A–T (or A–U) and G–C pairs; DNA double helix carries genetic information.",
        tags: ["biochemistry"],
      },
      {
        name: "ATP & energy currency",
        description: "Cellular energy carrier.",
        keyFact: "Adenosine triphosphate; hydrolysis to ADP + Pi releases $\\Delta G^\\circ' \\approx -30.5$ kJ/mol; drives nearly all coupled biosynthesis.",
        reaction: "\\ce{ATP + H2O -> ADP + Pi + H+}",
        tags: ["biochemistry", "thermodynamics"],
      },
      {
        name: "Glycolysis & the citric-acid cycle",
        description: "Central metabolism.",
        keyFact: "Glycolysis: glucose → 2 pyruvate, net 2 ATP + 2 NADH; TCA cycle oxidizes acetyl-CoA to \\ce{CO2}, generating NADH and FADH₂.",
        tags: ["biochemistry", "metabolism"],
      },
      {
        name: "Oxidative phosphorylation",
        description: "Electron transport + ATP synthesis.",
        keyFact: "NADH and FADH₂ drive an electron-transport chain pumping protons across the mitochondrial inner membrane; ATP synthase couples the gradient to ATP formation.",
        tags: ["biochemistry", "metabolism"],
      },
      {
        name: "Photosynthesis",
        description: "\\ce{CO2 + H2O -> sugar + O2}.",
        keyFact: "Light reactions split water and generate ATP + NADPH; the Calvin cycle fixes \\ce{CO2} into 3-carbon sugars.",
        reaction: "\\ce{6 CO2 + 6 H2O ->[h\\nu] C6H12O6 + 6 O2}",
        tags: ["biochemistry"],
      },
      {
        name: "Central dogma (chemistry view)",
        description: "DNA → RNA → protein.",
        keyFact: "Replication, transcription (DNA → RNA polymerase), translation (mRNA → ribosome → polypeptide); reverse transcription and RNA editing are known exceptions.",
        tags: ["biochemistry", "molecular-biology"],
      },
    ],
  },

  // ── Family 21 ─────────────────────────────────────────────────────────────
  {
    slug: "great-reactions-open-questions",
    number: 21,
    name: "Great Reactions, Industrial Processes & Open Questions",
    blurb: "Reactions that shaped industry, plus the questions still genuinely open.",
    section: "E",
    color: "violet",
    entries: [
      {
        name: "Haber–Bosch process",
        description: "Industrial ammonia synthesis.",
        keyFact: "\\ce{N2 + 3 H2 <=> 2 NH3} over Fe catalyst at ~450 °C, 200 atm; underlies the synthetic fertilizer that feeds roughly half the world's population.",
        reaction: "\\ce{N2 + 3 H2 <=>[\\text{Fe}, 450 ^\\circ C] 2 NH3}",
        tags: ["industrial", "history"],
      },
      {
        name: "Contact process (sulfuric acid)",
        description: "Largest-tonnage industrial chemical.",
        keyFact: "\\ce{2 SO2 + O2 <=> 2 SO3} on \\ce{V2O5}; \\ce{SO3} absorbed into oleum, diluted to give \\ce{H2SO4}. Indicator of industrial capacity.",
        reaction: "\\ce{2 SO2 + O2 ->[V2O5] 2 SO3}",
        tags: ["industrial"],
      },
      {
        name: "Chlor-alkali process",
        description: "Electrolysis of brine.",
        keyFact: "\\ce{2 NaCl + 2 H2O -> 2 NaOH + Cl2 + H2}; produces \\ce{Cl2}, \\ce{NaOH}, and \\ce{H2} simultaneously; foundational for plastics and bleach.",
        reaction: "\\ce{2 NaCl + 2 H2O ->[\\text{electrolysis}] 2 NaOH + Cl2 + H2}",
        tags: ["industrial"],
      },
      {
        name: "Steam reforming",
        description: "Methane → hydrogen.",
        keyFact: "\\ce{CH4 + H2O <=> CO + 3 H2}; followed by water-gas shift \\ce{CO + H2O <=> CO2 + H2}; supplies most industrial \\ce{H2}.",
        reaction: "\\ce{CH4 + H2O <=>[\\text{Ni}, 800 ^\\circ C] CO + 3 H2}",
        tags: ["industrial"],
      },
      {
        name: "Polymerization (Ziegler–Natta)",
        description: "Stereoregular polymers.",
        keyFact: "TiCl₄/AlR₃ catalysts polymerize alkenes with controlled tacticity; gave the world isotactic polypropylene.",
        tags: ["industrial", "polymers"],
      },
      {
        name: "Cracking & reforming",
        description: "Breaking heavy hydrocarbons.",
        keyFact: "Catalytic cracking shortens long alkanes for gasoline; catalytic reforming raises octane via cyclization and dehydrogenation to aromatics.",
        tags: ["industrial"],
      },
      {
        name: "Origin of life — abiogenesis chemistry",
        description: "How did chemistry become biology?",
        keyFact: "Miller–Urey-style discharge experiments make amino acids and nucleobases; RNA-world, metabolism-first, and hydrothermal-vent hypotheses all have evidence and gaps. No single mechanism is settled.",
        status: "open",
        tags: ["open-question", "origins"],
      },
      {
        name: "Protein folding — quantitative prediction",
        description: "From sequence to 3-D structure.",
        keyFact: "AlphaFold (2020–2024) dramatically improved structure prediction from sequence; the underlying physical folding-funnel problem and intrinsically disordered proteins remain active research.",
        status: "open",
        tags: ["open-question", "biochemistry"],
      },
      {
        name: "Room-temperature ambient-pressure superconductivity",
        description: "Open: not achieved as of 2026.",
        keyFact: "Hydrides under hundreds of GPa show high-$T_c$ behavior, but no material has been confirmed to superconduct at room temperature and ambient pressure. The 2023 LK-99 (Cu-doped lead-apatite) claim was specifically refuted by multiple independent replications.",
        status: "open",
        tags: ["open-question", "materials"],
      },
      {
        name: "LK-99 (Cu-doped lead-apatite)",
        description: "Claimed room-T superconductor; refuted.",
        keyFact: "A 2023 preprint claimed LK-99 was the first room-temperature ambient-pressure superconductor. Independent replications by groups at multiple institutions found no superconducting transition; the original resistivity drop is attributed to a structural transition in \\ce{Cu2S} impurities. The claim is considered refuted.",
        status: "refuted",
        tags: ["open-question", "refuted", "materials"],
      },
      {
        name: "Carbon capture & storage",
        description: "Removing \\ce{CO2} from the atmosphere.",
        keyFact: "Point-source amine scrubbing is mature but energy-intensive; direct air capture (~415 ppm) and durable storage are at much earlier scale. Whether DAC reaches climate-relevant scale by 2050 is unresolved.",
        status: "open",
        tags: ["open-question", "climate", "industrial"],
      },
      {
        name: "Catalytic asymmetric synthesis",
        description: "Building chirality on demand.",
        keyFact: "Recognized by the 2001 Nobel (Knowles, Noyori, Sharpless) and 2021 Nobel (List, MacMillan, organocatalysis). General, scalable, low-loading catalysts for any chiral target remain a frontier.",
        tags: ["organic", "industrial"],
      },
    ],
  },
];
