import type { Family } from "./types";

export const FAMILIES_1_7: Family[] = [
  // ── Family 1 ──────────────────────────────────────────────────────────────
  {
    slug: "atomic-structure",
    number: 1,
    name: "Atomic Structure & the Quantum Atom",
    blurb: "The constituents of the atom, quantized orbitals, and the rules that decide which electrons go where.",
    section: "A",
    color: "violet",
    entries: [
      {
        name: "Atom",
        description: "The basic unit of an element.",
        keyFact: "A dense positive nucleus (protons + neutrons) surrounded by electrons; the proton count fixes the element.",
        example: "A carbon atom has 6 protons.",
        tags: ["atomic", "foundations"],
      },
      {
        name: "Proton, neutron & electron",
        description: "The subatomic constituents.",
        keyFact: "Protons (+1) and neutrons (neutral) sit in the nucleus; electrons (−1) occupy orbitals. $m_p \\approx m_n \\approx 1836\\,m_e$.",
        example: "Mass number $A = Z + N$.",
        tags: ["atomic"],
      },
      {
        name: "Atomic number (Z)",
        description: "The element's identity.",
        keyFact: "$Z$ is the number of protons; it fixes which element an atom is and its place in the table.",
        example: "$Z=8$ is always oxygen.",
        tags: ["atomic", "periodicity"],
      },
      {
        name: "Isotopes",
        description: "Same element, different neutron count.",
        keyFact: "Equal $Z$ but different mass number $A$; chemically nearly identical.",
        formula: "\\ce{^{12}C}, \\ce{^{13}C}, \\ce{^{14}C}",
        tags: ["atomic", "isotopes"],
      },
      {
        name: "Atomic mass & the mass unit",
        description: "Average mass of an element's atoms.",
        keyFact: "Standard atomic weight is the abundance-weighted isotope average, in unified atomic mass units (u).",
        example: "Chlorine $\\approx 35.45$ u.",
        tags: ["atomic"],
      },
      {
        name: "The Bohr model",
        description: "Electrons in quantized orbits.",
        keyFact: "Electrons occupy fixed-energy shells; photons are emitted/absorbed on transitions, $E = h\\nu$.",
        example: "Explains the hydrogen line spectrum.",
        tags: ["atomic", "quantum"],
      },
      {
        name: "Quantum-mechanical model (orbitals)",
        description: "Electrons as probability clouds.",
        keyFact: "Solutions of the Schrödinger equation give orbitals — regions of high probability — replacing fixed orbits.",
        example: "s, p, d, f orbital shapes.",
        tags: ["atomic", "quantum"],
        xref: ["mathematics"],
      },
      {
        name: "Quantum numbers",
        description: "Labels for an electron's state.",
        keyFact: "$n$ (shell), $\\ell$ (subshell/shape), $m_\\ell$ (orientation), $m_s$ (spin $\\pm\\tfrac{1}{2}$).",
        example: "A 2p electron has $n=2$, $\\ell=1$.",
        tags: ["atomic", "quantum"],
      },
      {
        name: "Electron configuration",
        description: "How electrons fill orbitals.",
        keyFact: "Electrons occupy the lowest-energy orbitals first.",
        formula: "\\ce{Na}: [Ne]\\,3s^1",
        example: "Oxygen is \\ce{1s^2 2s^2 2p^4}.",
        tags: ["atomic"],
      },
      {
        name: "Aufbau, Hund & Pauli principles",
        description: "The filling rules.",
        keyFact: "Fill lowest energy first (Aufbau), singly before pairing (Hund), and no two electrons share all four quantum numbers (Pauli exclusion).",
        example: "Nitrogen's three 2p electrons are unpaired.",
        tags: ["atomic"],
      },
      {
        name: "Valence electrons",
        description: "The outermost, reactive electrons.",
        keyFact: "Electrons in the highest principal shell; they govern bonding and set the group.",
        example: "Every group-1 metal has one.",
        tags: ["atomic", "bonding"],
      },
      {
        name: "Ions (cations & anions)",
        description: "Charged atoms.",
        keyFact: "Losing electrons gives cations (+), gaining gives anions (−).",
        formula: "\\ce{Na+}, \\ce{Cl-}",
        tags: ["atomic", "ions"],
      },
      {
        name: "Ionization energy & electron affinity",
        description: "Energy to remove or add an electron.",
        keyFact: "Ionization energy removes the most loosely held electron; electron affinity is the energy change on gaining one; both rise across a period.",
        tags: ["atomic", "periodicity"],
      },
    ],
  },

  // ── Family 2 ──────────────────────────────────────────────────────────────
  {
    slug: "periodic-table",
    number: 2,
    name: "The Periodic Table & Periodic Trends",
    blurb: "Mendeleev's grid, the s/p/d/f blocks, and the trends that fall out when atoms are arranged by Z.",
    section: "A",
    color: "indigo",
    entries: [
      {
        name: "The periodic table",
        description: "The chart of the elements.",
        keyFact: "All 118 confirmed elements arranged by Z in 7 periods and 18 groups; period 7 is complete with oganesson (Z=118) the heaviest confirmed element.",
        tags: ["periodicity", "foundations"],
      },
      {
        name: "Periods & groups",
        description: "Rows and columns of the table.",
        keyFact: "A period is a row (same outermost shell n); a group is a column (similar valence configuration).",
        example: "Group 1: alkali metals; group 18: noble gases.",
        tags: ["periodicity"],
      },
      {
        name: "s-block",
        description: "Groups 1 and 2 plus helium.",
        keyFact: "Outermost electron fills an s orbital; comprises alkali and alkaline-earth metals.",
        example: "\\ce{Na}, \\ce{Ca}.",
        tags: ["periodicity", "blocks"],
      },
      {
        name: "p-block",
        description: "Groups 13–18.",
        keyFact: "Outermost electrons fill p orbitals; includes most nonmetals and metalloids.",
        example: "\\ce{C}, \\ce{N}, \\ce{O}, \\ce{Ne}.",
        tags: ["periodicity", "blocks"],
      },
      {
        name: "d-block (transition metals)",
        description: "Groups 3–12.",
        keyFact: "Filling (n−1)d orbitals; characterized by variable oxidation states and colored compounds.",
        example: "\\ce{Fe}, \\ce{Cu}, \\ce{Pt}.",
        tags: ["periodicity", "blocks", "transition-metals"],
      },
      {
        name: "f-block (lanthanides & actinides)",
        description: "The two strips below the main table.",
        keyFact: "Filling 4f (lanthanides Z=57–71) and 5f (actinides Z=89–103); rare-earth and heavy-element chemistry.",
        tags: ["periodicity", "blocks"],
      },
      {
        name: "Alkali metals",
        description: "Group 1.",
        keyFact: "Soft, very reactive metals with one valence electron; form +1 ions and reduce water vigorously.",
        reaction: "\\ce{2 Na + 2 H2O -> 2 NaOH + H2 ^}",
        tags: ["periodicity", "metals"],
      },
      {
        name: "Alkaline-earth metals",
        description: "Group 2.",
        keyFact: "Two valence electrons; form +2 ions; less reactive than group 1 but still reducing.",
        example: "\\ce{Ca}, \\ce{Mg}, \\ce{Ba}.",
        tags: ["periodicity", "metals"],
      },
      {
        name: "Halogens",
        description: "Group 17.",
        keyFact: "One electron short of a closed shell; strongly oxidizing nonmetals; form −1 ions or single covalent bonds.",
        formula: "\\ce{F2}, \\ce{Cl2}, \\ce{Br2}, \\ce{I2}",
        tags: ["periodicity", "halogens"],
      },
      {
        name: "Noble gases",
        description: "Group 18.",
        keyFact: "Closed-shell configurations; nearly inert; the heavier ones (Kr, Xe) form a handful of compounds with the most electronegative elements.",
        example: "\\ce{XeF4} is a real, stable compound.",
        tags: ["periodicity", "noble-gases"],
      },
      {
        name: "Atomic & ionic radius",
        description: "Size of the atom or ion.",
        keyFact: "Atomic radius decreases left-to-right across a period and increases down a group; cations are smaller than their parent atom, anions larger.",
        tags: ["periodicity", "trends"],
      },
      {
        name: "Electronegativity",
        description: "Pull on shared electrons.",
        keyFact: "Pauling scale; rises up and to the right; fluorine (3.98) is the most electronegative element.",
        example: "$\\chi(\\mathrm{F}) = 3.98$, $\\chi(\\mathrm{Cs}) \\approx 0.79$.",
        tags: ["periodicity", "trends", "bonding"],
      },
      {
        name: "Metallic vs nonmetallic character",
        description: "The diagonal stairstep.",
        keyFact: "Metals (lower-left) lose electrons easily and conduct; nonmetals (upper-right) gain electrons; metalloids straddle the staircase.",
        tags: ["periodicity", "trends"],
      },
      {
        name: "Effective nuclear charge & shielding",
        description: "What an electron actually feels.",
        keyFact: "Core electrons shield outer electrons from the nucleus; $Z_\\mathrm{eff} = Z - \\sigma$ rises across a period and drives most periodic trends.",
        tags: ["periodicity", "trends"],
      },
      {
        name: "Mendeleev's prediction",
        description: "The empty squares of 1869.",
        keyFact: "Mendeleev left gaps for unknown elements and predicted their properties; gallium (eka-aluminum) and germanium (eka-silicon) confirmed the predictions within a decade.",
        tags: ["periodicity", "history"],
      },
    ],
  },

  // ── Family 3 ──────────────────────────────────────────────────────────────
  {
    slug: "chemical-bonding",
    number: 3,
    name: "Chemical Bonding & Molecular Geometry",
    blurb: "Ionic, covalent, and metallic bonds; Lewis structures; VSEPR; hybridization; and resonance.",
    section: "A",
    color: "blue",
    entries: [
      {
        name: "Ionic bond",
        description: "Bond from electron transfer.",
        keyFact: "Electrostatic attraction between a cation and an anion; favored when the electronegativity difference is large ($\\Delta\\chi \\gtrsim 1.7$).",
        formula: "\\ce{NaCl}",
        reaction: "\\ce{2 Na + Cl2 -> 2 NaCl}",
        tags: ["bonding", "ionic"],
      },
      {
        name: "Covalent bond",
        description: "Bond from electron sharing.",
        keyFact: "Pair of electrons shared between two atoms; polar if the electronegativities differ.",
        formula: "\\ce{H-H}, \\ce{H-Cl}",
        tags: ["bonding", "covalent"],
      },
      {
        name: "Polar vs nonpolar covalent",
        description: "Sharing isn't always equal.",
        keyFact: "$0 < \\Delta\\chi < 0.5$ nonpolar; $0.5 \\le \\Delta\\chi < 1.7$ polar covalent; greater is essentially ionic.",
        example: "\\ce{H-Cl} is polar; \\ce{Cl-Cl} is nonpolar.",
        tags: ["bonding", "covalent"],
      },
      {
        name: "Metallic bond",
        description: "A sea of delocalized electrons.",
        keyFact: "Cations in a lattice share a free electron sea; explains conductivity, malleability, and metallic luster.",
        tags: ["bonding", "metals"],
      },
      {
        name: "Lewis structures",
        description: "Dots-and-lines bond bookkeeping.",
        keyFact: "Show all valence electrons; pair atoms to satisfy the octet (or duet for H) where possible.",
        example: "\\ce{H2O}: two O–H bonds and two lone pairs on O.",
        tags: ["bonding"],
      },
      {
        name: "Octet rule",
        description: "Eight valence electrons is stable.",
        keyFact: "Main-group atoms tend toward eight valence electrons; exceptions: H (2), Be (4), B (6), and expanded-octet species like \\ce{SF6}.",
        tags: ["bonding"],
      },
      {
        name: "Formal charge",
        description: "Bookkeeping for Lewis structures.",
        keyFact: "FC = (valence electrons) − (lone-pair electrons) − ½(bonding electrons); the best Lewis structure minimizes formal charges.",
        tags: ["bonding"],
      },
      {
        name: "Resonance",
        description: "When one Lewis structure isn't enough.",
        keyFact: "When several equivalent Lewis structures can be drawn, the true molecule is a weighted average (resonance hybrid); bond orders are fractional.",
        example: "Ozone \\ce{O3} has two resonance forms; both O–O bonds are equivalent.",
        tags: ["bonding"],
      },
      {
        name: "Bond order, length, and energy",
        description: "Strength of the bond.",
        keyFact: "Higher bond order ⇒ shorter, stronger bond; single < double < triple in strength but inversely in length.",
        example: "\\ce{C-C} 347 kJ/mol; \\ce{C=C} 614; \\ce{C#C} 839.",
        tags: ["bonding"],
      },
      {
        name: "VSEPR theory",
        description: "Electron pairs repel.",
        keyFact: "Valence Shell Electron Pair Repulsion: electron domains around the central atom arrange to minimize repulsion, predicting geometry.",
        example: "\\ce{CH4} tetrahedral; \\ce{NH3} trigonal pyramidal; \\ce{H2O} bent.",
        tags: ["bonding", "geometry"],
      },
      {
        name: "Molecular geometries",
        description: "The standard shapes.",
        keyFact: "Linear, trigonal planar, tetrahedral, trigonal bipyramidal, octahedral — plus bent, pyramidal, see-saw, T-shaped, square-planar variants from lone pairs.",
        tags: ["bonding", "geometry"],
      },
      {
        name: "Hybridization (sp, sp², sp³)",
        description: "Mixing atomic orbitals.",
        keyFact: "Atomic orbitals on the same atom combine into equivalent hybrid orbitals matching geometry: sp linear, sp² trigonal planar, sp³ tetrahedral.",
        example: "Methane carbon is sp³; ethene carbons are sp²; ethyne carbons are sp.",
        tags: ["bonding"],
      },
      {
        name: "Molecular orbital theory",
        description: "Orbitals across the whole molecule.",
        keyFact: "Atomic orbitals combine into bonding and antibonding MOs; bond order = ½(bonding − antibonding) electrons.",
        example: "\\ce{O2} has two unpaired electrons in $\\pi^*$ orbitals — paramagnetic, predicted by MO and not by Lewis.",
        tags: ["bonding", "quantum"],
        xref: ["mathematics"],
      },
      {
        name: "Dipole moment",
        description: "Net polarity of a molecule.",
        keyFact: "Vector sum of bond dipoles; \\ce{CO2} (linear) is nonpolar, \\ce{H2O} (bent) is polar.",
        formula: "\\vec\\mu = \\sum q_i \\vec r_i",
        tags: ["bonding", "polarity"],
      },
    ],
  },

  // ── Family 4 ──────────────────────────────────────────────────────────────
  {
    slug: "intermolecular-forces",
    number: 4,
    name: "Intermolecular Forces",
    blurb: "The weaker forces between molecules — what sets boiling points, solubility, and how DNA holds together.",
    section: "A",
    color: "sky",
    entries: [
      {
        name: "London dispersion forces",
        description: "Universal weak attraction.",
        keyFact: "Instantaneous dipoles induce dipoles in neighboring molecules; strength scales with polarizability and molecular size.",
        example: "Octane boils higher than methane purely from dispersion.",
        tags: ["imf"],
      },
      {
        name: "Dipole–dipole forces",
        description: "Permanent polar attractions.",
        keyFact: "Partial-positive end of one polar molecule attracts the partial-negative end of another; stronger than dispersion at the same size.",
        example: "Acetone \\ce{(CH3)2CO}.",
        tags: ["imf"],
      },
      {
        name: "Hydrogen bonding",
        description: "Special-case dipole–dipole.",
        keyFact: "H bonded to N/O/F donates a hydrogen bond to a lone pair on N/O/F; $\\approx 5{-}40$ kJ/mol — strong for an IMF, weak for a bond.",
        example: "Water's anomalously high boiling point; DNA base pairing.",
        tags: ["imf", "biochemistry"],
      },
      {
        name: "Ion–dipole forces",
        description: "Ion meets polar molecule.",
        keyFact: "An ion's full charge attracts polar molecules; the dominant force in aqueous ionic solutions.",
        example: "\\ce{Na+} surrounded by oriented \\ce{H2O} molecules.",
        tags: ["imf", "solutions"],
      },
      {
        name: "Van der Waals forces",
        description: "Umbrella for non-bonded attractions.",
        keyFact: "Collective term for dispersion, dipole–dipole, and dipole-induced-dipole forces — everything weaker than a real bond.",
        tags: ["imf"],
      },
      {
        name: "Surface tension & viscosity",
        description: "Macroscopic IMF effects.",
        keyFact: "Strong IMFs raise both surface tension (cohesion at the surface) and viscosity (resistance to flow).",
        example: "Water beads on a waxed surface; glycerol is highly viscous.",
        tags: ["imf", "liquids"],
      },
      {
        name: "Capillary action",
        description: "Liquid climbs a narrow tube.",
        keyFact: "Balance of adhesion (liquid–wall) and cohesion (liquid–liquid); water rises in glass, mercury depresses.",
        tags: ["imf", "liquids"],
      },
      {
        name: "Solvation & 'like dissolves like'",
        description: "Why polar and nonpolar separate.",
        keyFact: "Solvent–solute IMFs must rival solvent–solvent and solute–solute IMFs for dissolution; polar dissolves polar, nonpolar dissolves nonpolar.",
        example: "Salt dissolves in water but not in hexane.",
        tags: ["imf", "solutions"],
      },
    ],
  },

  // ── Family 5 ──────────────────────────────────────────────────────────────
  {
    slug: "stoichiometry-mole",
    number: 5,
    name: "Stoichiometry & the Mole",
    blurb: "Counting atoms by weighing them; balancing equations; limiting reagents and percent yield.",
    section: "B",
    color: "cyan",
    entries: [
      {
        name: "The mole",
        description: "Chemistry's counting unit.",
        keyFact: "One mole contains exactly $6.022 \\times 10^{23}$ entities (Avogadro's number, $N_A$); the SI now fixes $N_A$ as an exact integer.",
        tags: ["stoichiometry"],
      },
      {
        name: "Molar mass",
        description: "Grams per mole.",
        keyFact: "Mass of one mole of a substance in grams, numerically equal to its molecular weight in u.",
        example: "$M(\\ce{H2O}) = 18.015$ g/mol.",
        tags: ["stoichiometry"],
      },
      {
        name: "Avogadro's number",
        description: "The bridge from atoms to grams.",
        keyFact: "$N_A = 6.02214076 \\times 10^{23}\\,\\mathrm{mol^{-1}}$ — exact since the 2019 SI redefinition.",
        tags: ["stoichiometry", "constants"],
      },
      {
        name: "Balancing chemical equations",
        description: "Atoms are conserved.",
        keyFact: "Equal counts of each element on both sides; charges balance for ionic equations.",
        reaction: "\\ce{C3H8 + 5 O2 -> 3 CO2 + 4 H2O}",
        tags: ["stoichiometry"],
      },
      {
        name: "Mole ratios",
        description: "Stoichiometric coefficients.",
        keyFact: "Coefficients in a balanced equation give the ratio of moles consumed and produced.",
        example: "1 mol \\ce{C3H8} requires 5 mol \\ce{O2}.",
        tags: ["stoichiometry"],
      },
      {
        name: "Limiting reagent",
        description: "Who runs out first.",
        keyFact: "The reactant exhausted first sets the maximum yield; the others are in excess.",
        tags: ["stoichiometry"],
      },
      {
        name: "Theoretical, actual & percent yield",
        description: "What you should get vs. what you got.",
        keyFact: "Percent yield = (actual / theoretical) × 100%; losses come from side reactions, transfer, and incomplete reaction.",
        tags: ["stoichiometry"],
      },
      {
        name: "Empirical & molecular formulas",
        description: "Simplest ratio vs. actual composition.",
        keyFact: "Empirical formula is the smallest whole-number ratio of atoms; molecular formula is an integer multiple of it.",
        example: "Glucose: empirical \\ce{CH2O}, molecular \\ce{C6H12O6}.",
        tags: ["stoichiometry"],
      },
      {
        name: "Percent composition",
        description: "Mass fraction by element.",
        keyFact: "$\\%E = (n_E M_E / M_{\\text{total}}) \\times 100\\%$ — used to infer empirical formulas from combustion analysis.",
        tags: ["stoichiometry"],
      },
      {
        name: "Solution concentration (molarity)",
        description: "Moles per liter.",
        keyFact: "$M = n / V$, with $V$ in liters of solution; the workhorse concentration unit for aqueous chemistry.",
        formula: "M = n / V",
        tags: ["stoichiometry", "solutions"],
      },
    ],
  },

  // ── Family 6 ──────────────────────────────────────────────────────────────
  {
    slug: "states-of-matter-gases",
    number: 6,
    name: "States of Matter & Gas Laws",
    blurb: "Solid, liquid, gas, plasma; ideal-gas behavior and the corrections that bring it back to reality.",
    section: "B",
    color: "teal",
    entries: [
      {
        name: "States of matter",
        description: "The four common phases.",
        keyFact: "Solid (rigid lattice), liquid (incompressible, fluid), gas (compressible, fills container), plasma (ionized gas); also BEC and supercritical states.",
        tags: ["states"],
      },
      {
        name: "Phase transitions",
        description: "Moving between states.",
        keyFact: "Melting, freezing, vaporization, condensation, sublimation, deposition; each has a latent heat at constant T.",
        tags: ["states", "thermodynamics"],
      },
      {
        name: "Phase diagrams",
        description: "Mapping state vs. P and T.",
        keyFact: "Lines separate phases; triple point, all three coexist; critical point, gas/liquid distinction disappears.",
        example: "Water has a negative \\ce{solid-liquid} slope (ice less dense than water).",
        tags: ["states", "thermodynamics"],
      },
      {
        name: "Ideal-gas law",
        description: "The simplest gas equation.",
        keyFact: "$PV = nRT$; works well at low pressure and high temperature.",
        formula: "PV = nRT",
        tags: ["gases"],
      },
      {
        name: "Boyle's law",
        description: "Pressure–volume.",
        keyFact: "At constant T and n, $P \\propto 1/V$, so $P_1 V_1 = P_2 V_2$.",
        tags: ["gases"],
      },
      {
        name: "Charles's law",
        description: "Volume–temperature.",
        keyFact: "At constant P and n, $V \\propto T$, so $V_1/T_1 = V_2/T_2$ (T in kelvin).",
        tags: ["gases"],
      },
      {
        name: "Avogadro's law",
        description: "Volume–amount.",
        keyFact: "At constant P and T, $V \\propto n$ — equal volumes of any ideal gas contain equal numbers of molecules.",
        tags: ["gases"],
      },
      {
        name: "Dalton's law of partial pressures",
        description: "Mixtures of gases.",
        keyFact: "Total pressure equals the sum of partial pressures: $P_\\text{tot} = \\sum P_i$.",
        tags: ["gases"],
      },
      {
        name: "Graham's law of effusion",
        description: "Lighter gases escape faster.",
        keyFact: "Effusion rate $\\propto 1/\\sqrt{M}$; uranium enrichment of \\ce{UF6} exploits the \\ce{^{235}U}/\\ce{^{238}U} mass ratio.",
        tags: ["gases", "isotopes"],
      },
      {
        name: "Kinetic molecular theory",
        description: "Gas as bouncing point particles.",
        keyFact: "Gas pressure and temperature emerge from molecular motion; $\\tfrac{1}{2}m\\langle v^2\\rangle = \\tfrac{3}{2}k_B T$.",
        tags: ["gases", "kinetic-theory"],
        xref: ["statistics"],
      },
      {
        name: "Maxwell–Boltzmann distribution",
        description: "Distribution of molecular speeds.",
        keyFact: "Speeds follow $f(v) \\propto v^2 e^{-mv^2 / 2k_B T}$; the distribution widens and shifts right with temperature.",
        tags: ["gases", "kinetic-theory"],
        xref: ["statistics"],
      },
      {
        name: "Van der Waals equation",
        description: "Correcting the ideal-gas law.",
        keyFact: "$\\bigl(P + a(n/V)^2\\bigr)(V - nb) = nRT$; $a$ for IMFs, $b$ for finite molecular size.",
        formula: "(P + a(n/V)^2)(V - nb) = nRT",
        tags: ["gases", "real-gases"],
      },
      {
        name: "Critical point & supercritical fluids",
        description: "Beyond the liquid–gas distinction.",
        keyFact: "Above $T_c, P_c$ a single supercritical phase exists with gas-like diffusivity and liquid-like density; \\ce{CO2} supercritical is used for decaffeination.",
        tags: ["states", "gases"],
      },
    ],
  },

  // ── Family 7 ──────────────────────────────────────────────────────────────
  {
    slug: "thermodynamics",
    number: 7,
    name: "Thermodynamics & Thermochemistry",
    blurb: "Energy bookkeeping, heat vs. work, entropy, and what makes a reaction spontaneous.",
    section: "B",
    color: "emerald",
    entries: [
      {
        name: "First law of thermodynamics",
        description: "Energy is conserved.",
        keyFact: "$\\Delta U = q + w$ — internal energy changes equal heat added plus work done on the system.",
        formula: "\\Delta U = q + w",
        tags: ["thermodynamics"],
      },
      {
        name: "Enthalpy (H)",
        description: "Heat at constant pressure.",
        keyFact: "$H = U + PV$; at constant $P$, $\\Delta H = q_P$ — the heat released or absorbed by the reaction.",
        tags: ["thermodynamics"],
      },
      {
        name: "Exothermic vs endothermic",
        description: "Signs of $\\Delta H$.",
        keyFact: "Exothermic releases heat ($\\Delta H < 0$); endothermic absorbs heat ($\\Delta H > 0$).",
        example: "Combustion is exothermic; \\ce{NH4NO3} dissolving is endothermic.",
        tags: ["thermodynamics"],
      },
      {
        name: "Hess's law",
        description: "$\\Delta H$ is path-independent.",
        keyFact: "Enthalpy change equals the sum of step enthalpies; lets you compute $\\Delta H$ for any reaction from tabulated ones.",
        tags: ["thermodynamics"],
      },
      {
        name: "Standard enthalpy of formation",
        description: "Tabulated reference values.",
        keyFact: "$\\Delta H_f^\\circ$ is the enthalpy to form 1 mol of compound from elements in their standard states; defined as 0 for elements.",
        formula: "\\Delta H_\\text{rxn}^\\circ = \\sum \\nu_p \\Delta H_{f,p}^\\circ - \\sum \\nu_r \\Delta H_{f,r}^\\circ",
        tags: ["thermodynamics"],
      },
      {
        name: "Calorimetry",
        description: "Measuring heat.",
        keyFact: "$q = m c \\Delta T$ (constant pressure) or $q = C_\\text{cal} \\Delta T$ (bomb calorimeter, constant volume).",
        tags: ["thermodynamics", "experiment"],
      },
      {
        name: "Entropy (S)",
        description: "Disorder, or count of microstates.",
        keyFact: "$S = k_B \\ln W$; entropy increases with temperature, dispersion, and number of accessible states.",
        formula: "S = k_B \\ln W",
        tags: ["thermodynamics"],
        xref: ["statistics", "mathematics"],
      },
      {
        name: "Second law of thermodynamics",
        description: "Entropy of the universe rises.",
        keyFact: "$\\Delta S_\\text{universe} \\ge 0$; spontaneous processes increase universal entropy; equality only at equilibrium.",
        tags: ["thermodynamics"],
      },
      {
        name: "Third law of thermodynamics",
        description: "Entropy reference point.",
        keyFact: "A perfect crystalline solid has $S = 0$ at $T = 0$ K — gives an absolute reference for entropy.",
        tags: ["thermodynamics"],
      },
      {
        name: "Gibbs free energy (G)",
        description: "Spontaneity at constant T, P.",
        keyFact: "$G = H - TS$ and $\\Delta G = \\Delta H - T\\Delta S$; $\\Delta G < 0$ ⇒ spontaneous, $\\Delta G > 0$ ⇒ nonspontaneous, $\\Delta G = 0$ ⇒ equilibrium.",
        formula: "\\Delta G = \\Delta H - T\\,\\Delta S",
        tags: ["thermodynamics"],
      },
      {
        name: "Standard Gibbs energy & equilibrium",
        description: "Connecting $\\Delta G^\\circ$ to K.",
        keyFact: "$\\Delta G^\\circ = -RT \\ln K$; favorable thermodynamics give large equilibrium constants.",
        formula: "\\Delta G^\\circ = -RT \\ln K",
        tags: ["thermodynamics", "equilibrium"],
      },
      {
        name: "Coupled reactions",
        description: "Pushing uphill with downhill energy.",
        keyFact: "A reaction with $\\Delta G > 0$ can proceed when coupled to one with $\\Delta G \\ll 0$; ATP hydrolysis is the canonical biological coupling.",
        example: "ATP → ADP + Pi drives muscle contraction, ion transport, biosynthesis.",
        tags: ["thermodynamics", "biochemistry"],
      },
    ],
  },
];
