import type { PeriodicElement } from "./types";

// Standard atomic weights from IUPAC 2021 Commission on Isotopic Abundances and Atomic Weights.
// For synthetic / radioactive elements with no stable isotope, the value is the mass
// number of the most stable / commonly cited isotope (conventionally shown in brackets).
// Group numbers for the f-block (lanthanides Z=57–71, actinides Z=89–103) are conventionally
// shown in group 3; here they are tagged group=3 with block "f" and rendered in the f-block
// strip beneath the main grid by the periodic-table component.

export const ELEMENTS: PeriodicElement[] = [
  { symbol: "H",  name: "Hydrogen",      atomicNumber: 1,   group: 1,  period: 1, block: "s", category: "reactive-nonmetal",      standardAtomicWeight: 1.008,  disputedPlacement: "Conventionally placed in group 1 with the alkali metals; sometimes shown in group 17 alongside the halogens because it can gain one electron to form H⁻. The IUPAC table places it in group 1, but the dual placement is widely discussed and not adjudicated here." },
  { symbol: "He", name: "Helium",        atomicNumber: 2,   group: 18, period: 1, block: "s", category: "noble-gas",              standardAtomicWeight: 4.0026 },

  { symbol: "Li", name: "Lithium",       atomicNumber: 3,   group: 1,  period: 2, block: "s", category: "alkali-metal",           standardAtomicWeight: 6.94 },
  { symbol: "Be", name: "Beryllium",     atomicNumber: 4,   group: 2,  period: 2, block: "s", category: "alkaline-earth-metal",   standardAtomicWeight: 9.0122 },
  { symbol: "B",  name: "Boron",         atomicNumber: 5,   group: 13, period: 2, block: "p", category: "metalloid",              standardAtomicWeight: 10.81 },
  { symbol: "C",  name: "Carbon",        atomicNumber: 6,   group: 14, period: 2, block: "p", category: "reactive-nonmetal",      standardAtomicWeight: 12.011 },
  { symbol: "N",  name: "Nitrogen",      atomicNumber: 7,   group: 15, period: 2, block: "p", category: "reactive-nonmetal",      standardAtomicWeight: 14.007 },
  { symbol: "O",  name: "Oxygen",        atomicNumber: 8,   group: 16, period: 2, block: "p", category: "reactive-nonmetal",      standardAtomicWeight: 15.999 },
  { symbol: "F",  name: "Fluorine",      atomicNumber: 9,   group: 17, period: 2, block: "p", category: "reactive-nonmetal",      standardAtomicWeight: 18.998 },
  { symbol: "Ne", name: "Neon",          atomicNumber: 10,  group: 18, period: 2, block: "p", category: "noble-gas",              standardAtomicWeight: 20.180 },

  { symbol: "Na", name: "Sodium",        atomicNumber: 11,  group: 1,  period: 3, block: "s", category: "alkali-metal",           standardAtomicWeight: 22.990 },
  { symbol: "Mg", name: "Magnesium",     atomicNumber: 12,  group: 2,  period: 3, block: "s", category: "alkaline-earth-metal",   standardAtomicWeight: 24.305 },
  { symbol: "Al", name: "Aluminium",     atomicNumber: 13,  group: 13, period: 3, block: "p", category: "post-transition-metal",  standardAtomicWeight: 26.982 },
  { symbol: "Si", name: "Silicon",       atomicNumber: 14,  group: 14, period: 3, block: "p", category: "metalloid",              standardAtomicWeight: 28.085 },
  { symbol: "P",  name: "Phosphorus",    atomicNumber: 15,  group: 15, period: 3, block: "p", category: "reactive-nonmetal",      standardAtomicWeight: 30.974 },
  { symbol: "S",  name: "Sulfur",        atomicNumber: 16,  group: 16, period: 3, block: "p", category: "reactive-nonmetal",      standardAtomicWeight: 32.06 },
  { symbol: "Cl", name: "Chlorine",      atomicNumber: 17,  group: 17, period: 3, block: "p", category: "reactive-nonmetal",      standardAtomicWeight: 35.45 },
  { symbol: "Ar", name: "Argon",         atomicNumber: 18,  group: 18, period: 3, block: "p", category: "noble-gas",              standardAtomicWeight: 39.95 },

  { symbol: "K",  name: "Potassium",     atomicNumber: 19,  group: 1,  period: 4, block: "s", category: "alkali-metal",           standardAtomicWeight: 39.098 },
  { symbol: "Ca", name: "Calcium",       atomicNumber: 20,  group: 2,  period: 4, block: "s", category: "alkaline-earth-metal",   standardAtomicWeight: 40.078 },
  { symbol: "Sc", name: "Scandium",      atomicNumber: 21,  group: 3,  period: 4, block: "d", category: "transition-metal",       standardAtomicWeight: 44.956 },
  { symbol: "Ti", name: "Titanium",      atomicNumber: 22,  group: 4,  period: 4, block: "d", category: "transition-metal",       standardAtomicWeight: 47.867 },
  { symbol: "V",  name: "Vanadium",      atomicNumber: 23,  group: 5,  period: 4, block: "d", category: "transition-metal",       standardAtomicWeight: 50.942 },
  { symbol: "Cr", name: "Chromium",      atomicNumber: 24,  group: 6,  period: 4, block: "d", category: "transition-metal",       standardAtomicWeight: 51.996 },
  { symbol: "Mn", name: "Manganese",     atomicNumber: 25,  group: 7,  period: 4, block: "d", category: "transition-metal",       standardAtomicWeight: 54.938 },
  { symbol: "Fe", name: "Iron",          atomicNumber: 26,  group: 8,  period: 4, block: "d", category: "transition-metal",       standardAtomicWeight: 55.845 },
  { symbol: "Co", name: "Cobalt",        atomicNumber: 27,  group: 9,  period: 4, block: "d", category: "transition-metal",       standardAtomicWeight: 58.933 },
  { symbol: "Ni", name: "Nickel",        atomicNumber: 28,  group: 10, period: 4, block: "d", category: "transition-metal",       standardAtomicWeight: 58.693 },
  { symbol: "Cu", name: "Copper",        atomicNumber: 29,  group: 11, period: 4, block: "d", category: "transition-metal",       standardAtomicWeight: 63.546 },
  { symbol: "Zn", name: "Zinc",          atomicNumber: 30,  group: 12, period: 4, block: "d", category: "transition-metal",       standardAtomicWeight: 65.38 },
  { symbol: "Ga", name: "Gallium",       atomicNumber: 31,  group: 13, period: 4, block: "p", category: "post-transition-metal",  standardAtomicWeight: 69.723 },
  { symbol: "Ge", name: "Germanium",     atomicNumber: 32,  group: 14, period: 4, block: "p", category: "metalloid",              standardAtomicWeight: 72.630 },
  { symbol: "As", name: "Arsenic",       atomicNumber: 33,  group: 15, period: 4, block: "p", category: "metalloid",              standardAtomicWeight: 74.922 },
  { symbol: "Se", name: "Selenium",      atomicNumber: 34,  group: 16, period: 4, block: "p", category: "reactive-nonmetal",      standardAtomicWeight: 78.971 },
  { symbol: "Br", name: "Bromine",       atomicNumber: 35,  group: 17, period: 4, block: "p", category: "reactive-nonmetal",      standardAtomicWeight: 79.904 },
  { symbol: "Kr", name: "Krypton",       atomicNumber: 36,  group: 18, period: 4, block: "p", category: "noble-gas",              standardAtomicWeight: 83.798 },

  { symbol: "Rb", name: "Rubidium",      atomicNumber: 37,  group: 1,  period: 5, block: "s", category: "alkali-metal",           standardAtomicWeight: 85.468 },
  { symbol: "Sr", name: "Strontium",     atomicNumber: 38,  group: 2,  period: 5, block: "s", category: "alkaline-earth-metal",   standardAtomicWeight: 87.62 },
  { symbol: "Y",  name: "Yttrium",       atomicNumber: 39,  group: 3,  period: 5, block: "d", category: "transition-metal",       standardAtomicWeight: 88.906 },
  { symbol: "Zr", name: "Zirconium",     atomicNumber: 40,  group: 4,  period: 5, block: "d", category: "transition-metal",       standardAtomicWeight: 91.224 },
  { symbol: "Nb", name: "Niobium",       atomicNumber: 41,  group: 5,  period: 5, block: "d", category: "transition-metal",       standardAtomicWeight: 92.906 },
  { symbol: "Mo", name: "Molybdenum",    atomicNumber: 42,  group: 6,  period: 5, block: "d", category: "transition-metal",       standardAtomicWeight: 95.95 },
  { symbol: "Tc", name: "Technetium",    atomicNumber: 43,  group: 7,  period: 5, block: "d", category: "transition-metal",       standardAtomicWeight: 98 },
  { symbol: "Ru", name: "Ruthenium",     atomicNumber: 44,  group: 8,  period: 5, block: "d", category: "transition-metal",       standardAtomicWeight: 101.07 },
  { symbol: "Rh", name: "Rhodium",       atomicNumber: 45,  group: 9,  period: 5, block: "d", category: "transition-metal",       standardAtomicWeight: 102.91 },
  { symbol: "Pd", name: "Palladium",     atomicNumber: 46,  group: 10, period: 5, block: "d", category: "transition-metal",       standardAtomicWeight: 106.42 },
  { symbol: "Ag", name: "Silver",        atomicNumber: 47,  group: 11, period: 5, block: "d", category: "transition-metal",       standardAtomicWeight: 107.87 },
  { symbol: "Cd", name: "Cadmium",       atomicNumber: 48,  group: 12, period: 5, block: "d", category: "transition-metal",       standardAtomicWeight: 112.41 },
  { symbol: "In", name: "Indium",        atomicNumber: 49,  group: 13, period: 5, block: "p", category: "post-transition-metal",  standardAtomicWeight: 114.82 },
  { symbol: "Sn", name: "Tin",           atomicNumber: 50,  group: 14, period: 5, block: "p", category: "post-transition-metal",  standardAtomicWeight: 118.71 },
  { symbol: "Sb", name: "Antimony",      atomicNumber: 51,  group: 15, period: 5, block: "p", category: "metalloid",              standardAtomicWeight: 121.76 },
  { symbol: "Te", name: "Tellurium",     atomicNumber: 52,  group: 16, period: 5, block: "p", category: "metalloid",              standardAtomicWeight: 127.60 },
  { symbol: "I",  name: "Iodine",        atomicNumber: 53,  group: 17, period: 5, block: "p", category: "reactive-nonmetal",      standardAtomicWeight: 126.90 },
  { symbol: "Xe", name: "Xenon",         atomicNumber: 54,  group: 18, period: 5, block: "p", category: "noble-gas",              standardAtomicWeight: 131.29 },

  { symbol: "Cs", name: "Caesium",       atomicNumber: 55,  group: 1,  period: 6, block: "s", category: "alkali-metal",           standardAtomicWeight: 132.91 },
  { symbol: "Ba", name: "Barium",        atomicNumber: 56,  group: 2,  period: 6, block: "s", category: "alkaline-earth-metal",   standardAtomicWeight: 137.33 },

  { symbol: "La", name: "Lanthanum",     atomicNumber: 57,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 138.91, disputedPlacement: "IUPAC's preferred composition of group 3 (Sc, Y, Lu, Lr) places La in the f-block instead. Both placements appear in current textbooks; this table follows the historical convention of La in group 3 of the d-block and notes the dispute." },
  { symbol: "Ce", name: "Cerium",        atomicNumber: 58,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 140.12 },
  { symbol: "Pr", name: "Praseodymium",  atomicNumber: 59,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 140.91 },
  { symbol: "Nd", name: "Neodymium",     atomicNumber: 60,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 144.24 },
  { symbol: "Pm", name: "Promethium",    atomicNumber: 61,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 145 },
  { symbol: "Sm", name: "Samarium",      atomicNumber: 62,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 150.36 },
  { symbol: "Eu", name: "Europium",      atomicNumber: 63,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 151.96 },
  { symbol: "Gd", name: "Gadolinium",    atomicNumber: 64,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 157.25 },
  { symbol: "Tb", name: "Terbium",       atomicNumber: 65,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 158.93 },
  { symbol: "Dy", name: "Dysprosium",    atomicNumber: 66,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 162.50 },
  { symbol: "Ho", name: "Holmium",       atomicNumber: 67,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 164.93 },
  { symbol: "Er", name: "Erbium",        atomicNumber: 68,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 167.26 },
  { symbol: "Tm", name: "Thulium",       atomicNumber: 69,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 168.93 },
  { symbol: "Yb", name: "Ytterbium",     atomicNumber: 70,  group: 3,  period: 6, block: "f", category: "lanthanide",             standardAtomicWeight: 173.05 },
  { symbol: "Lu", name: "Lutetium",      atomicNumber: 71,  group: 3,  period: 6, block: "d", category: "lanthanide",             standardAtomicWeight: 174.97, disputedPlacement: "IUPAC's preferred group-3 composition places Lu in the main d-block (group 3, period 6). This table follows that placement; the alternative is La in group 3 with Lu in the lanthanide strip." },

  { symbol: "Hf", name: "Hafnium",       atomicNumber: 72,  group: 4,  period: 6, block: "d", category: "transition-metal",       standardAtomicWeight: 178.49 },
  { symbol: "Ta", name: "Tantalum",      atomicNumber: 73,  group: 5,  period: 6, block: "d", category: "transition-metal",       standardAtomicWeight: 180.95 },
  { symbol: "W",  name: "Tungsten",      atomicNumber: 74,  group: 6,  period: 6, block: "d", category: "transition-metal",       standardAtomicWeight: 183.84 },
  { symbol: "Re", name: "Rhenium",       atomicNumber: 75,  group: 7,  period: 6, block: "d", category: "transition-metal",       standardAtomicWeight: 186.21 },
  { symbol: "Os", name: "Osmium",        atomicNumber: 76,  group: 8,  period: 6, block: "d", category: "transition-metal",       standardAtomicWeight: 190.23 },
  { symbol: "Ir", name: "Iridium",       atomicNumber: 77,  group: 9,  period: 6, block: "d", category: "transition-metal",       standardAtomicWeight: 192.22 },
  { symbol: "Pt", name: "Platinum",      atomicNumber: 78,  group: 10, period: 6, block: "d", category: "transition-metal",       standardAtomicWeight: 195.08 },
  { symbol: "Au", name: "Gold",          atomicNumber: 79,  group: 11, period: 6, block: "d", category: "transition-metal",       standardAtomicWeight: 196.97 },
  { symbol: "Hg", name: "Mercury",       atomicNumber: 80,  group: 12, period: 6, block: "d", category: "transition-metal",       standardAtomicWeight: 200.59 },
  { symbol: "Tl", name: "Thallium",      atomicNumber: 81,  group: 13, period: 6, block: "p", category: "post-transition-metal",  standardAtomicWeight: 204.38 },
  { symbol: "Pb", name: "Lead",          atomicNumber: 82,  group: 14, period: 6, block: "p", category: "post-transition-metal",  standardAtomicWeight: 207.2 },
  { symbol: "Bi", name: "Bismuth",       atomicNumber: 83,  group: 15, period: 6, block: "p", category: "post-transition-metal",  standardAtomicWeight: 208.98 },
  { symbol: "Po", name: "Polonium",      atomicNumber: 84,  group: 16, period: 6, block: "p", category: "post-transition-metal",  standardAtomicWeight: 209 },
  { symbol: "At", name: "Astatine",      atomicNumber: 85,  group: 17, period: 6, block: "p", category: "metalloid",              standardAtomicWeight: 210 },
  { symbol: "Rn", name: "Radon",         atomicNumber: 86,  group: 18, period: 6, block: "p", category: "noble-gas",              standardAtomicWeight: 222 },

  { symbol: "Fr", name: "Francium",      atomicNumber: 87,  group: 1,  period: 7, block: "s", category: "alkali-metal",           standardAtomicWeight: 223 },
  { symbol: "Ra", name: "Radium",        atomicNumber: 88,  group: 2,  period: 7, block: "s", category: "alkaline-earth-metal",   standardAtomicWeight: 226 },

  { symbol: "Ac", name: "Actinium",      atomicNumber: 89,  group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 227, disputedPlacement: "Mirror of the La/Lu dispute: IUPAC's preferred placement puts Ac in the f-block strip and Lr at the bottom of group 3. This table follows the historical convention; the alternative is widely defensible." },
  { symbol: "Th", name: "Thorium",       atomicNumber: 90,  group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 232.04 },
  { symbol: "Pa", name: "Protactinium",  atomicNumber: 91,  group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 231.04 },
  { symbol: "U",  name: "Uranium",       atomicNumber: 92,  group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 238.03 },
  { symbol: "Np", name: "Neptunium",     atomicNumber: 93,  group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 237 },
  { symbol: "Pu", name: "Plutonium",     atomicNumber: 94,  group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 244 },
  { symbol: "Am", name: "Americium",     atomicNumber: 95,  group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 243 },
  { symbol: "Cm", name: "Curium",        atomicNumber: 96,  group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 247 },
  { symbol: "Bk", name: "Berkelium",     atomicNumber: 97,  group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 247 },
  { symbol: "Cf", name: "Californium",   atomicNumber: 98,  group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 251 },
  { symbol: "Es", name: "Einsteinium",   atomicNumber: 99,  group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 252 },
  { symbol: "Fm", name: "Fermium",       atomicNumber: 100, group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 257 },
  { symbol: "Md", name: "Mendelevium",   atomicNumber: 101, group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 258 },
  { symbol: "No", name: "Nobelium",      atomicNumber: 102, group: 3,  period: 7, block: "f", category: "actinide",               standardAtomicWeight: 259 },
  { symbol: "Lr", name: "Lawrencium",    atomicNumber: 103, group: 3,  period: 7, block: "d", category: "actinide",               standardAtomicWeight: 266, disputedPlacement: "IUPAC's preferred group-3 composition places Lr in the main d-block (group 3, period 7), paired with Lu." },

  { symbol: "Rf", name: "Rutherfordium", atomicNumber: 104, group: 4,  period: 7, block: "d", category: "transition-metal",       standardAtomicWeight: 267 },
  { symbol: "Db", name: "Dubnium",       atomicNumber: 105, group: 5,  period: 7, block: "d", category: "transition-metal",       standardAtomicWeight: 268 },
  { symbol: "Sg", name: "Seaborgium",    atomicNumber: 106, group: 6,  period: 7, block: "d", category: "transition-metal",       standardAtomicWeight: 269 },
  { symbol: "Bh", name: "Bohrium",       atomicNumber: 107, group: 7,  period: 7, block: "d", category: "transition-metal",       standardAtomicWeight: 270 },
  { symbol: "Hs", name: "Hassium",       atomicNumber: 108, group: 8,  period: 7, block: "d", category: "transition-metal",       standardAtomicWeight: 269 },
  { symbol: "Mt", name: "Meitnerium",    atomicNumber: 109, group: 9,  period: 7, block: "d", category: "unknown",                standardAtomicWeight: 278 },
  { symbol: "Ds", name: "Darmstadtium",  atomicNumber: 110, group: 10, period: 7, block: "d", category: "unknown",                standardAtomicWeight: 281 },
  { symbol: "Rg", name: "Roentgenium",   atomicNumber: 111, group: 11, period: 7, block: "d", category: "unknown",                standardAtomicWeight: 282 },
  { symbol: "Cn", name: "Copernicium",   atomicNumber: 112, group: 12, period: 7, block: "d", category: "unknown",                standardAtomicWeight: 285 },
  { symbol: "Nh", name: "Nihonium",      atomicNumber: 113, group: 13, period: 7, block: "p", category: "unknown",                standardAtomicWeight: 286 },
  { symbol: "Fl", name: "Flerovium",     atomicNumber: 114, group: 14, period: 7, block: "p", category: "unknown",                standardAtomicWeight: 289 },
  { symbol: "Mc", name: "Moscovium",     atomicNumber: 115, group: 15, period: 7, block: "p", category: "unknown",                standardAtomicWeight: 290 },
  { symbol: "Lv", name: "Livermorium",   atomicNumber: 116, group: 16, period: 7, block: "p", category: "unknown",                standardAtomicWeight: 293 },
  { symbol: "Ts", name: "Tennessine",    atomicNumber: 117, group: 17, period: 7, block: "p", category: "unknown",                standardAtomicWeight: 294 },
  { symbol: "Og", name: "Oganesson",     atomicNumber: 118, group: 18, period: 7, block: "p", category: "unknown",                standardAtomicWeight: 294 },
];

export const CATEGORY_STYLES: Record<
  PeriodicElement["category"],
  { bg: string; border: string; text: string; label: string }
> = {
  "alkali-metal":          { bg: "#3b0a0a", border: "#dc2626", text: "#fca5a5", label: "Alkali metal" },
  "alkaline-earth-metal":  { bg: "#431407", border: "#ea580c", text: "#fdba74", label: "Alkaline earth metal" },
  "transition-metal":      { bg: "#422006", border: "#ca8a04", text: "#fde047", label: "Transition metal" },
  "post-transition-metal": { bg: "#1a2e05", border: "#65a30d", text: "#bef264", label: "Post-transition metal" },
  "metalloid":             { bg: "#042f2e", border: "#0d9488", text: "#5eead4", label: "Metalloid" },
  "reactive-nonmetal":     { bg: "#082f49", border: "#0284c7", text: "#7dd3fc", label: "Reactive nonmetal" },
  "noble-gas":             { bg: "#2e1065", border: "#7c3aed", text: "#c4b5fd", label: "Noble gas" },
  "lanthanide":            { bg: "#3b0764", border: "#a21caf", text: "#f0abfc", label: "Lanthanide" },
  "actinide":              { bg: "#500724", border: "#be185d", text: "#fbcfe8", label: "Actinide" },
  "unknown":               { bg: "#1f2937", border: "#4b5563", text: "#9ca3af", label: "Predicted properties / unknown" },
};
