import type { Family } from "./types";

// Sections B, C, D — Instructional Methods & Design; Curriculum & Standards; Assessment & Measurement

export const FAMILIES_7_13: Family[] = [
  {
    slug: "instructional-methods",
    number: 7,
    name: "Instructional Methods & Models of Teaching",
    blurb: "Recurring formats and models for organizing teaching and learning activity.",
    section: "B",
    color: "blue",
    entries: [
      {
        name: "Direct instruction",
        description: "Explicit, teacher-led, systematic teaching.",
        principle: "Clearly stated objectives, teacher modeling, guided practice with feedback, and independent practice — a highly structured, explicit approach with strong effect sizes for foundational skills.",
        example: "The \"I do / we do / you do\" gradual-release sequence; DISTAR.",
        principalCritiques: "The explicit-vs-discovery balance is genuinely contested. Meta-analyses of Direct Instruction programs (e.g., Project Follow Through, subsequent syntheses) report substantial effects for foundational skills, particularly for at-risk and early learners; critics argue these programs can narrow curriculum, deprioritize higher-order and dispositional outcomes, and that findings for later grades and complex tasks are less clear-cut. Contemporary syntheses generally favor explicit instruction for novices and for foundational content, with more open tasks appropriate as expertise grows.",
        tags: ["instructional-methods", "pedagogy"],
        status: "open",
      },
      {
        name: "Explicit vs implicit instruction",
        description: "Tell-and-show vs let-emerge.",
        principle: "Explicit instruction states and demonstrates what is to be learned; implicit approaches arrange conditions for learners to infer it — the two anchor a long-running guidance debate.",
        example: "Systematic phonics (explicit) vs incidental word learning (implicit).",
        tags: ["instructional-methods", "pedagogy"],
      },
      {
        name: "The guidance debate (worked examples vs minimal guidance)",
        description: "How much scaffolding novices need.",
        principle: "A prominent argument holds that for novices, heavily guided instruction (worked examples, explicit teaching) outperforms minimally guided discovery/inquiry, which overloads working memory.",
        example: "Kirschner, Sweller & Clark's critique of minimal guidance.",
        principalCritiques: "Genuinely disputed. Cognitive-load and worked-example research consistently favor high guidance for novices; inquiry advocates counter that well-designed inquiry with strong scaffolding compares favorably and that head-to-head studies often confound guidance with fidelity of implementation. Most contemporary syntheses read the disagreement as one of degree rather than kind: novices benefit from more guidance; as expertise grows, less-guided tasks pay off (\"expertise reversal effect\").",
        tags: ["instructional-methods", "cognitivism"],
        status: "open",
      },
      {
        name: "Lecture & expository teaching",
        description: "Structured verbal transmission.",
        principle: "Efficient for conveying organized information to many at once; effective when well-structured and paired with active processing, weak when purely passive.",
        example: "Advance organizers to frame a lecture (Ausubel).",
        tags: ["instructional-methods"],
      },
      {
        name: "Socratic method & questioning",
        description: "Learning through structured dialogue.",
        principle: "Disciplined questioning surfaces assumptions, tests reasoning, and leads learners to construct understanding; the art is in the sequence of questions.",
        example: "Socratic seminars; cold-call questioning norms.",
        tags: ["instructional-methods"],
      },
      {
        name: "Differentiated instruction",
        description: "Tailoring content, process, and product.",
        principle: "Adapt what students learn, how they learn it, and how they demonstrate it to their readiness, interest, and profile, while holding standards constant.",
        example: "Tiered tasks and flexible grouping. Note: distinct from the discredited learning-styles claim (Family 18).",
        tags: ["instructional-methods", "equity"],
      },
      {
        name: "Universal Design for Learning (UDL)",
        description: "Design for variability from the start.",
        principle: "Provide multiple means of engagement, representation, and action/expression so that a single design serves the widest range of learners without retrofitting.",
        example: "Offering text, audio, and captioned video for one lesson.",
        tags: ["instructional-methods", "special-education"],
        xref: ["neuroscience"],
      },
      {
        name: "Flipped classroom",
        description: "Content at home, practice in class.",
        principle: "Move first-exposure content (often video) outside class to free class time for higher-order application, discussion, and support.",
        example: "Watch a lecture as homework, do \"homework\" problems in class with the teacher.",
        tags: ["instructional-methods", "ed-tech"],
      },
      {
        name: "Blended & hybrid learning",
        description: "Combining online and face-to-face.",
        principle: "Integrate online and in-person instruction to leverage the strengths of each, from rotation models to fully hybrid courses.",
        example: "Station-rotation models.",
        tags: ["instructional-methods", "ed-tech"],
      },
      {
        name: "Project-based learning",
        description: "Extended inquiry yielding a product.",
        principle: "Students learn by working over time on an authentic, complex project culminating in a public product, integrating content and skills.",
        example: "A semester engineering-design challenge. Related to but broader than problem-based learning (Family 3).",
        tags: ["instructional-methods"],
      },
      {
        name: "Game-based learning & gamification",
        description: "Games and game elements for learning.",
        principle: "Well-designed games embed goals, feedback, and graduated challenge that can drive engagement and practice; gamification adds points/badges/leaderboards to non-game tasks.",
        example: "Educational simulations; classroom XP systems.",
        principalCritiques: "Motivational durability is contested. Short-term engagement gains are widely reported; longer-run effects on learning and intrinsic motivation are mixed and depend heavily on design (whether game mechanics align with the learning) and on whether external rewards displace intrinsic interest (the overjustification concern, Family 5). Well-designed games embedded in genuine tasks look promising; badge/points overlays on rote work show weaker durable effects.",
        tags: ["instructional-methods", "ed-tech"],
        status: "open",
      },
      {
        name: "Peer & reciprocal teaching",
        description: "Students teaching students.",
        principle: "Learners deepen understanding by explaining to peers and by taking structured turns leading (e.g., predicting, questioning, clarifying, summarizing).",
        example: "Reciprocal teaching for reading comprehension; peer tutoring.",
        tags: ["instructional-methods"],
      },
      {
        name: "Response to Intervention / MTSS",
        description: "Tiered support by need.",
        principle: "A multi-tiered system provides universal instruction, targeted small-group intervention, and intensive individualized support, escalating by data on response.",
        example: "RTI/MTSS academic and behavioral tiers.",
        tags: ["instructional-methods", "special-education"],
      },
      {
        name: "Classroom management",
        description: "Structuring the environment for learning.",
        principle: "Clear expectations, routines, engagement, and relationships create the conditions in which instruction can work; management is enabling, not an end in itself.",
        example: "PBIS (positive behavioral interventions and supports).",
        tags: ["instructional-methods", "pedagogy"],
      },
    ],
  },
  {
    slug: "instructional-design",
    number: 8,
    name: "Instructional Design & Learning Engineering",
    blurb: "Systematic processes and models for designing effective instruction.",
    section: "B",
    color: "sky",
    entries: [
      {
        name: "Instructional design (ID)",
        description: "Systematic design of learning experiences.",
        principle: "Apply a repeatable process — analyze needs and learners, design objectives and assessments, develop materials, deliver, and evaluate — to produce reliably effective instruction.",
        example: "The field bridging learning theory and practice.",
        tags: ["instructional-design"],
      },
      {
        name: "ADDIE model",
        description: "Analyze, Design, Develop, Implement, Evaluate.",
        principle: "A generic ID framework organizing design into five phases with feedback loops; the default scaffold for course and training development.",
        example: "Corporate and course-design workflows.",
        tags: ["instructional-design"],
      },
      {
        name: "Backward design (Understanding by Design)",
        description: "Start from the desired results.",
        principle: "First identify desired understandings, then determine acceptable evidence (assessment), then plan learning activities — so instruction is aligned to goals from the outset.",
        figures: ["Wiggins", "McTighe"],
        example: "Writing the final assessment before the unit.",
        tags: ["instructional-design", "curriculum"],
      },
      {
        name: "Constructive alignment",
        description: "Objectives, activities, and assessment in line.",
        principle: "Learning outcomes, teaching/learning activities, and assessment tasks should be mutually aligned so that assessment measures the intended learning.",
        figures: ["Biggs"],
        example: "Mapping each assessment item to an objective.",
        tags: ["instructional-design", "assessment"],
      },
      {
        name: "Learning objectives & outcomes",
        description: "Precise statements of intended learning.",
        principle: "Well-formed objectives state observable, measurable learning at an appropriate cognitive level, guiding both instruction and assessment.",
        example: "Course-level outcomes aligned to Bloom's taxonomy.",
        tags: ["instructional-design", "curriculum"],
      },
      {
        name: "First principles of instruction (Merrill)",
        description: "Common ingredients of effective instruction.",
        principle: "Learning is promoted when instruction is problem-centered and engages activation of prior knowledge, demonstration, application, and integration.",
        figures: ["Merrill"],
        example: "Task-centered course design.",
        tags: ["instructional-design"],
      },
      {
        name: "Elaboration theory",
        description: "Sequence simple-to-complex.",
        principle: "Organize instruction from a simple \"epitome\" of the whole to progressively elaborated detail, so learners keep the big picture.",
        figures: ["Reigeluth"],
        example: "Zooming from an overview into subsystems.",
        tags: ["instructional-design"],
      },
      {
        name: "Rapid prototyping & agile ID (SAM)",
        description: "Iterate quickly with feedback.",
        principle: "Build and test small prototypes in rapid cycles rather than fully specifying up front, incorporating stakeholder feedback early and often.",
        figures: ["Allen (SAM)"],
        example: "Successive approximation of an e-learning module.",
        tags: ["instructional-design"],
      },
      {
        name: "Design-based research",
        description: "Studying learning by iteratively designing it.",
        principle: "Develop and refine educational interventions through cycles of design, enactment, analysis, and redesign in real settings, yielding both usable designs and theory.",
        example: "Iteratively refining a classroom innovation with researchers and teachers.",
        tags: ["instructional-design"],
        xref: ["statistics"],
      },
      {
        name: "Learning engineering & analytics",
        description: "Data-driven improvement of learning.",
        principle: "Apply engineering methods and learning data (learning analytics, A/B tests) to design, measure, and iteratively improve learning at scale.",
        example: "Platform experiments on courseware.",
        tags: ["instructional-design", "ed-tech"],
        xref: ["statistics"],
      },
    ],
  },
  {
    slug: "curriculum-theory",
    number: 9,
    name: "Curriculum Theory & Design",
    blurb: "Foundations, ideologies, and models of curriculum.",
    section: "C",
    color: "emerald",
    entries: [
      {
        name: "Curriculum",
        description: "The planned (and unplanned) content of schooling.",
        principle: "The totality of what students are meant to learn — content, skills, and dispositions — as planned, enacted, and experienced; more than a list of topics.",
        tags: ["curriculum", "foundations"],
      },
      {
        name: "The Tyler rationale",
        description: "Four organizing curriculum questions.",
        principle: "Curriculum design answers four questions — what purposes, what experiences, how organized, how evaluated — a foundational (and much-critiqued) technical model.",
        figures: ["Tyler"],
        era: "1949",
        example: "Objectives-driven curriculum planning.",
        tags: ["curriculum"],
      },
      {
        name: "Curriculum ideologies",
        description: "Competing visions of what schools are for.",
        principle: "Curricula reflect orientations — academic/subject-centered, social-efficiency, learner-centered, and social-reconstructionist — that answer \"what knowledge is of most worth\" differently.",
        figures: ["Schiro", "Kliebard"],
        example: "The tension between \"great books\" and \"relevance.\"",
        tags: ["curriculum"],
        xref: ["ideologies"],
      },
      {
        name: "Explicit, hidden & null curriculum",
        description: "What is taught, implied, and omitted.",
        principle: "Alongside the explicit curriculum, schools teach a \"hidden curriculum\" of norms and a \"null curriculum\" of what is left out — both shape learning.",
        figures: ["Jackson", "Eisner"],
        example: "Punctuality and compliance learned implicitly.",
        tags: ["curriculum"],
        xref: ["sociology"],
      },
      {
        name: "Subject-centered vs integrated curriculum",
        description: "Disciplines vs themes.",
        principle: "Curricula can be organized around separate subjects or integrated across them by themes or problems; each trades disciplinary depth against connectedness.",
        example: "Discrete science courses vs STEM integration.",
        tags: ["curriculum"],
      },
      {
        name: "Spiral & sequencing",
        description: "Ordering content for cumulative learning.",
        principle: "Content is sequenced (linear, spiral, or by learning progression) so prerequisites precede dependents and ideas are revisited with growing depth.",
        example: "Learning progressions in mathematics.",
        tags: ["curriculum"],
      },
      {
        name: "Learning progressions",
        description: "Empirically grounded paths of increasing sophistication.",
        principle: "Describe the typical sequence by which understanding of a big idea develops, anchoring standards and assessment to how learning actually unfolds.",
        example: "Progressions in numeracy or the particle model of matter.",
        tags: ["curriculum", "assessment"],
      },
      {
        name: "Core Knowledge & cultural literacy",
        description: "A shared, content-rich curriculum.",
        principle: "Broad shared background knowledge is a precondition for reading comprehension and civic participation, arguing for a specified, content-rich core.",
        figures: ["Hirsch"],
        example: "The Core Knowledge sequence.",
        principalCritiques: "Contested against skills-first views. Proponents point to reading-comprehension research (background knowledge as a strong determinant of comprehension) and to evidence from content-rich curricula. Critics argue that specifying a common core risks privileging a dominant cultural canon at the expense of other traditions, and that skills-based frameworks are more equitable. Present as a live design debate, not settled.",
        tags: ["curriculum"],
        status: "open",
      },
      {
        name: "Critical pedagogy",
        description: "Education as consciousness-raising.",
        principle: "Education is never neutral; it can domesticate or liberate, and should develop critical consciousness (\"conscientization\") to question and transform oppressive conditions.",
        figures: ["Freire", "Giroux", "hooks"],
        era: "1970s-present",
        example: "Problem-posing education.",
        principalCritiques: "As with other explicitly normative pedagogies, critical pedagogy is contested. Proponents argue that ignoring power in schooling is itself a political choice, and that critical pedagogy makes explicit what other frameworks leave implicit. Critics argue that its programmatic form can subordinate content to critique, that its normative commitments are contested, and that empirical evidence for its downstream effects is thin. Presented here as a tradition, with evaluation quarantined to this field.",
        tags: ["curriculum"],
        xref: ["ideologies", "sociology"],
      },
      {
        name: "Multicultural & anti-bias education",
        description: "Curriculum for a diverse society.",
        principle: "Curriculum and pedagogy that represent diverse groups and confront bias, aiming at equity and intergroup understanding.",
        figures: ["Banks", "Nieto"],
        example: "Multiple perspectives in history curricula.",
        principalCritiques: "A contested policy area. Proponents cite evidence that inclusive materials and anti-bias practice can reduce prejudice and improve engagement, particularly for students from underrepresented groups; critics on the right argue that some implementations displace shared civic content or teach political positions as fact, and critics on the left argue that surface-level \"heroes and holidays\" versions miss the structural point. The dispute is substantially about which version is being defended or attacked.",
        tags: ["curriculum", "equity"],
        xref: ["sociology"],
      },
    ],
  },
  {
    slug: "standards-literacies",
    number: 10,
    name: "Standards, Domains & Literacies",
    blurb: "Standards movements, subject-area pedagogies, and the debates within them.",
    section: "C",
    color: "green",
    entries: [
      {
        name: "Standards-based education",
        description: "Common goals and aligned accountability.",
        principle: "Define what students should know and be able to do at each level (standards), then align curriculum, instruction, and assessment to them.",
        example: "State content standards and end-of-course tests.",
        tags: ["standards", "policy"],
      },
      {
        name: "Common Core & college-and-career standards",
        description: "Shared cross-state standards.",
        principle: "Common academic standards in English/mathematics intended to raise and align expectations across states, emphasizing depth and reasoning.",
        era: "2010s",
        example: "The Common Core State Standards.",
        principalCritiques: "Politically contested at adoption and after. Proponents argued that shared standards raise expectations, enable common assessment, and support mobility across states; critics on the right argued they were federal overreach and displaced local control, and critics on the left argued that they narrowed instruction toward tested content. Empirical evaluations of Common Core's effect on measured achievement are mixed and confounded by concurrent policy changes; several states have since revised or renamed their standards.",
        tags: ["standards", "policy"],
        status: "open",
      },
      {
        name: "Competency-based education",
        description: "Progress by demonstrated mastery.",
        principle: "Students advance upon demonstrating mastery of defined competencies rather than seat time; pace varies, standard is held fixed.",
        example: "Mastery transcripts; micro-competencies.",
        tags: ["standards", "instructional-methods"],
      },
      {
        name: "Reading pedagogy & the \"reading wars\"",
        description: "How children should be taught to read.",
        principle: "The long dispute between phonics/systematic code-based instruction and whole-language/meaning-first approaches, with \"balanced literacy\" a contested middle; the \"science of reading\" movement pushes explicit, systematic phonics plus the \"simple view\" (decoding x language comprehension).",
        example: "Science-of-reading legislation across roughly 40+ U.S. states and DC since 2013, with ~11+ states banning \"three-cueing\" instruction — California's AB 1454 (2025) is a recent example. Verify exact state count at build time.",
        principalCritiques: "The empirical balance favors systematic phonics for early word reading. Meta-analyses (the National Reading Panel; subsequent syntheses) find that systematic phonics instruction improves decoding and (via decoding) reading outcomes, particularly for beginning and at-risk readers. Contested points that remain live: how prescriptive phonics programs should be, whether \"balanced literacy\" as-implemented delivers enough explicit code work, and whether legislative bans on \"three-cueing\" name the right target. Whole-language advocates argue that meaning and rich text exposure remain essential; science-of-reading advocates argue this is not incompatible with explicit code work and is what \"simple view\" already says.",
        tags: ["standards", "literacy"],
        xref: ["linguistics"],
        status: "open",
      },
      {
        name: "The simple view of reading",
        description: "Reading = decoding x comprehension.",
        principle: "Reading comprehension is the product of word recognition (decoding) and language comprehension; both are necessary, and weakness in either limits reading.",
        figures: ["Gough", "Tunmer"],
        example: "Diagnosing whether a struggling reader's issue is decoding or comprehension.",
        tags: ["standards", "literacy"],
        xref: ["linguistics"],
      },
      {
        name: "Balanced literacy & three-cueing",
        description: "Meaning, structure, and visual cues together.",
        principle: "An approach blending phonics with authentic reading and (in the contested three-cueing model) encouraging use of meaning/syntax/visual cues to identify words.",
        example: "Guided reading with leveled texts.",
        principalCritiques: "Three-cueing is increasingly restricted in U.S. states as inconsistent with reading-science evidence: encouraging beginning readers to guess unknown words from context and picture rather than decoding them is associated with weaker later reading and with confusing struggling readers about what reading is. The broader \"balanced literacy\" label covers a wide range of practice; classrooms whose \"balance\" delivers systematic phonics can be consistent with the reading-science synthesis, while those whose \"balance\" substitutes context-guessing for decoding are not.",
        tags: ["standards", "literacy"],
        status: "open",
      },
      {
        name: "Mathematics education & the \"math wars\"",
        description: "Procedures vs conceptual understanding.",
        principle: "The debate between fluency with procedures and standard algorithms versus conceptual understanding and reasoning; most reform frameworks argue both are needed.",
        figures: ["NCTM (standards)"],
        example: "The algorithm-vs-reform-math disputes.",
        principalCritiques: "Genuinely contested. Reform advocates argue that procedural-only instruction produces brittle fluency and disengagement; traditionalists argue that reform math has too often deprioritized fluency and standard algorithms, especially for students without home support. Empirical work (large-scale international assessments, curricular comparisons) does not cleanly adjudicate; most contemporary syntheses read the balance as \"both, well sequenced,\" with strong disagreement about what \"well sequenced\" means in practice.",
        tags: ["standards", "numeracy"],
        xref: ["mathematics"],
        status: "open",
      },
      {
        name: "Science education (NGSS & 3-dimensional learning)",
        description: "Practices, crosscutting concepts, and core ideas.",
        principle: "Learn science by engaging in disciplinary practices around crosscutting concepts and core ideas, not memorizing facts; emphasizes modeling and argument.",
        example: "The Next Generation Science Standards' three dimensions.",
        tags: ["standards", "science-education"],
      },
      {
        name: "Writing pedagogy",
        description: "Composition as process and craft.",
        principle: "Teach writing as a recursive process (planning, drafting, revising, editing) with explicit strategy instruction and feedback, rather than one-shot products.",
        figures: ["Graves", "Hillocks"],
        example: "Writers' workshop; self-regulated strategy development.",
        tags: ["standards", "literacy"],
      },
      {
        name: "Bilingual & second-language education",
        description: "Educating multilingual learners.",
        principle: "Models range from immersion and transitional bilingual to dual-language, differing in whether and how the home language is developed; well-designed bilingual programs support both languages and content.",
        figures: ["Cummins", "Krashen"],
        example: "Dual-language two-way immersion.",
        principalCritiques: "A contested policy area, especially in the U.S. Meta-analytic evidence and large-scale program evaluations generally favor well-implemented bilingual/dual-language models over English-only immersion for long-run English and content outcomes for multilingual learners; the policy conclusions drawn from this vary widely by state and jurisdiction. Presented here as a program-design question with a partial evidence base, not as a settled political dispute.",
        tags: ["standards", "language"],
        xref: ["linguistics"],
        status: "open",
      },
      {
        name: "STEM/STEAM & computational thinking",
        description: "Integrated technical literacies.",
        principle: "Integrate science, technology, engineering, (arts,) and mathematics, and teach computational thinking (decomposition, abstraction, algorithms) as a broadly useful literacy.",
        example: "Integrated design challenges; CS-for-all initiatives.",
        tags: ["standards"],
        xref: ["computer-science"],
      },
      {
        name: "Media & information literacy",
        description: "Evaluating and using information critically.",
        principle: "The ability to access, analyze, evaluate, and create media and information, including source evaluation and digital citizenship, as a core modern literacy.",
        example: "Lateral reading; SIFT method.",
        tags: ["standards", "literacy"],
        xref: ["communication"],
      },
    ],
  },
  {
    slug: "purposes-forms-assessment",
    number: 11,
    name: "Purposes & Forms of Assessment",
    blurb: "What assessments are for and how they are used.",
    section: "D",
    color: "teal",
    entries: [
      {
        name: "Assessment (overview)",
        description: "Gathering evidence of learning.",
        principle: "The systematic collection and interpretation of evidence about what learners know and can do, to inform decisions — the hinge between teaching and learning.",
        tags: ["assessment", "foundations"],
      },
      {
        name: "Formative assessment (assessment for learning)",
        description: "Feedback that shapes ongoing learning.",
        principle: "Assessment used during learning to give actionable feedback and adjust instruction, rather than only to grade; among the higher-leverage practices when done well.",
        figures: ["Black", "Wiliam"],
        example: "Exit tickets, hinge questions, no-grade feedback.",
        tags: ["assessment"],
      },
      {
        name: "Summative assessment (assessment of learning)",
        description: "Judging attainment at an endpoint.",
        principle: "Assessment that certifies what has been learned at the end of a unit, course, or program, for grading or accountability.",
        example: "Final exams; end-of-course tests.",
        tags: ["assessment"],
      },
      {
        name: "Diagnostic assessment",
        description: "Locating strengths and gaps before teaching.",
        principle: "Assessment that identifies prior knowledge, misconceptions, and specific difficulties to target instruction.",
        example: "Pre-tests; concept inventories.",
        tags: ["assessment"],
      },
      {
        name: "Norm-referenced vs criterion-referenced",
        description: "Compared to peers vs to a standard.",
        principle: "Norm-referenced scores rank a test-taker against a comparison group; criterion-referenced scores judge performance against fixed criteria, independent of others.",
        example: "Percentile ranks vs \"meets standard.\"",
        tags: ["assessment"],
        xref: ["statistics"],
      },
      {
        name: "Ipsative assessment",
        description: "Compared to one's own prior performance.",
        principle: "Judges progress against the learner's own earlier performance, foregrounding growth rather than rank or absolute standard.",
        example: "Personal-best tracking; growth portfolios.",
        tags: ["assessment"],
      },
      {
        name: "Authentic & performance assessment",
        description: "Demonstrate learning on real tasks.",
        principle: "Assess through complex, meaningful tasks resembling real-world use (performances, products, exhibitions) rather than only selected-response items.",
        example: "Science lab practicals; capstone exhibitions.",
        tags: ["assessment"],
      },
      {
        name: "Portfolio assessment",
        description: "A curated body of work over time.",
        principle: "Assess a purposeful collection of work showing effort, progress, and achievement, often with learner reflection.",
        example: "Writing or art portfolios.",
        tags: ["assessment"],
      },
      {
        name: "Rubrics & scoring guides",
        description: "Explicit criteria for judging quality.",
        principle: "Articulated criteria and performance levels make complex judgments more consistent, transparent, and instructive.",
        example: "Analytic vs holistic rubrics.",
        tags: ["assessment"],
        xref: ["statistics"],
      },
      {
        name: "Self- & peer-assessment",
        description: "Learners judging work against criteria.",
        principle: "Applying criteria to one's own or peers' work builds evaluative judgment and metacognition and can improve subsequent performance.",
        example: "Peer review with a rubric.",
        tags: ["assessment"],
      },
      {
        name: "Standards-based & competency grading",
        description: "Grades tied to learning targets.",
        principle: "Report achievement against specific standards or competencies rather than aggregating points, so grades communicate what was learned.",
        example: "Proficiency scales; separating behavior from achievement.",
        tags: ["assessment"],
      },
      {
        name: "Feedback (effective)",
        description: "Information that closes the gap.",
        principle: "Effective feedback tells learners where they are going, how they are doing, and what to do next, and is timely, specific, and actionable; poorly targeted feedback can harm.",
        figures: ["Hattie", "Timperley"],
        example: "Task / process / self-regulation feedback levels.",
        tags: ["assessment"],
      },
    ],
  },
  {
    slug: "psychometrics",
    number: 12,
    name: "Psychometrics & Measurement Theory",
    blurb: "The measurement science behind trustworthy scores. Shared with statistics — link, don't fork.",
    section: "D",
    color: "cyan",
    entries: [
      {
        name: "Educational measurement (psychometrics)",
        description: "Quantifying learning and traits.",
        principle: "The theory and methods for turning responses to items and tasks into trustworthy scores of achievement or ability; education's measurement science.",
        example: "Scaling a state achievement test.",
        tags: ["psychometrics"],
        xref: ["statistics"],
      },
      {
        name: "Validity",
        description: "Are we measuring the right thing?",
        principle: "The degree to which evidence and theory support the intended interpretations and uses of scores — content, criterion, construct, and consequential evidence together, not a property of the test alone.",
        figures: ["Messick", "Kane"],
        example: "Validating a test's use for placement.",
        tags: ["psychometrics"],
        xref: ["statistics"],
      },
      {
        name: "Reliability",
        description: "Is the measure consistent?",
        principle: "The consistency / reproducibility of scores across items, occasions, forms, or raters; necessary but not sufficient for validity.",
        example: "Internal consistency (Cronbach's alpha), test-retest, inter-rater.",
        tags: ["psychometrics"],
        xref: ["statistics"],
      },
      {
        name: "Classical test theory",
        description: "Observed score = true score + error.",
        principle: "An observed score is a true score plus measurement error; reliability is the ratio of true-score to observed-score variance.",
        example: "The foundation of most legacy testing. Link to the statistics sibling for the formal model.",
        tags: ["psychometrics"],
        xref: ["statistics"],
      },
      {
        name: "Item response theory (IRT)",
        description: "Model items and people on one scale.",
        principle: "The probability of a correct response is a function of a person's ability and item parameters (difficulty, discrimination, guessing), placing persons and items on a common scale.",
        example: "The 1PL/Rasch, 2PL, 3PL models. Link to the statistics sibling for the formal model.",
        tags: ["psychometrics"],
        xref: ["statistics"],
      },
      {
        name: "Item analysis",
        description: "Diagnosing item quality.",
        principle: "Item difficulty (p-value) and discrimination (how well an item separates high and low scorers) identify items to keep, revise, or drop.",
        example: "Point-biserial correlations; distractor analysis.",
        tags: ["psychometrics"],
        xref: ["statistics"],
      },
      {
        name: "Differential item functioning (DIF)",
        description: "Item fairness across groups.",
        principle: "An item shows DIF if test-takers of equal ability but different groups have different success probabilities — a bias red flag to investigate.",
        example: "DIF screening in test development. Link to the statistics sibling for the formal model.",
        tags: ["psychometrics", "fairness"],
        xref: ["statistics"],
      },
      {
        name: "Test equating & scaling",
        description: "Making scores comparable across forms.",
        principle: "Statistical procedures put scores from different test forms or years onto a common scale so they mean the same thing.",
        example: "Equating this year's exam to last year's.",
        tags: ["psychometrics"],
        xref: ["statistics"],
      },
      {
        name: "Standard setting",
        description: "Where to place the cut score.",
        principle: "Systematic, judgment-based procedures (Angoff, bookmark) set the performance thresholds that define \"proficient\" or \"pass.\"",
        example: "An Angoff panel for a licensure cut.",
        principalCritiques: "Cut scores are consequential and contested. All standard-setting methods depend on panelist judgment; small shifts in method or panel composition can move measured pass/proficient rates substantially, which in turn moves accountability and policy conclusions. Standard-setting is a legitimate psychometric procedure, not an arbitrary one, but its uses in high-stakes accountability magnify what it can and cannot deliver.",
        tags: ["psychometrics"],
        xref: ["statistics"],
      },
      {
        name: "Computer-adaptive testing (CAT)",
        description: "Tailor item difficulty in real time.",
        principle: "Select each next item based on the running ability estimate (via IRT), measuring more precisely with fewer items.",
        example: "Adaptive state tests; GRE.",
        tags: ["psychometrics", "ed-tech"],
        xref: ["statistics"],
      },
      {
        name: "Generalizability theory",
        description: "Decompose multiple error sources at once.",
        principle: "An ANOVA-style framework partitions measurement error across facets (raters, items, occasions) simultaneously, generalizing reliability.",
        example: "A G-study of a performance rubric. Link to the statistics sibling for the formal model.",
        tags: ["psychometrics"],
        xref: ["statistics"],
      },
      {
        name: "Growth & value-added models",
        description: "Measuring learning gains over time.",
        principle: "Statistical models estimate student growth and attempt to isolate schools'/teachers' contributions from prior achievement and background.",
        example: "Value-added models (VAM); student growth percentiles.",
        principalCritiques: "The use of value-added models for high-stakes evaluation of individual teachers is contested. Technical concerns include year-to-year instability of individual teacher estimates, sensitivity to model specification and controls, non-random assignment of students to teachers, and the fact that only a fraction of the score variance is attributable to the teacher. Proponents argue VAM is more objective than the alternatives when properly bounded; critics argue that the appropriate use is descriptive at the school/system level rather than punitive at the teacher level. Widely adopted then walked back across many U.S. states.",
        tags: ["psychometrics", "policy"],
        xref: ["statistics"],
        status: "open",
      },
    ],
  },
  {
    slug: "large-scale-assessment",
    number: 13,
    name: "Large-Scale Assessment & Accountability",
    blurb: "System-level testing programs and the accountability regimes built on them.",
    section: "D",
    color: "teal",
    entries: [
      {
        name: "NAEP (the Nation's Report Card)",
        description: "The main U.S. national achievement measure.",
        principle: "A congressionally mandated, low-stakes assessment of representative student samples that tracks U.S. achievement over time in reading, math, and other subjects.",
        example: "The most recent NAEP administration is 2024 — grade 4/8 reading and math results released early 2025 (reading declined further, with the largest share of students below NAEP Basic in decades; grade-4 math up slightly, grade-8 math flat), and grade 8/12 plus science results released September 2025. U.S. scores remain below pre-pandemic 2019 levels. Verify current cycle at build time.",
        tags: ["large-scale", "policy"],
        xref: ["statistics"],
      },
      {
        name: "PISA",
        description: "International 15-year-old literacy in reading, math, science.",
        principle: "An OECD assessment every three years of applied reading, mathematical, and scientific literacy across 80+ education systems, used for cross-national comparison.",
        example: "The most recent published cycle is PISA 2022 (mathematics focus; results released December 2023). PISA 2025 (science focus, 90+ systems) is administered and its first results are scheduled for 8 September 2026. Verify at build time.",
        tags: ["large-scale", "policy"],
        xref: ["statistics"],
      },
      {
        name: "TIMSS",
        description: "International math and science achievement.",
        principle: "The IEA's trend study of grade-4 and grade-8 mathematics and science achievement, curriculum-linked, on a four-year cycle.",
        example: "The most recent is TIMSS 2023 (results released 4 December 2024; U.S. grade-8 mathematics down sharply vs 2019). Verify at build time.",
        tags: ["large-scale", "policy"],
        xref: ["statistics"],
      },
      {
        name: "PIRLS",
        description: "International reading literacy at grade 4.",
        principle: "The IEA's five-year study of fourth-grade reading comprehension across countries.",
        example: "Used to compare early-reading outcomes internationally.",
        tags: ["large-scale", "literacy"],
        xref: ["statistics"],
      },
      {
        name: "High-stakes testing",
        description: "Tests with major consequences attached.",
        principle: "Attaching significant consequences (graduation, promotion, funding, ratings) to test scores to drive accountability and effort.",
        example: "Exit exams; test-based promotion.",
        principalCritiques: "Genuinely contested. Proponents argue that clear stakes concentrate attention and effort, and that surfaced accountability data has driven attention to previously invisible disparities. Critics point to narrowing of the enacted curriculum toward tested content, teaching-to-the-test, elevated stress on students and teachers, and a series of erasure/cheating scandals in cities where score gains carried outsized consequences. Meta-analyses of test-based accountability regimes find mixed effects on measured scores, with clearer negative effects on non-tested subjects and on breadth of instruction.",
        tags: ["large-scale", "policy"],
        status: "open",
      },
      {
        name: "Test-based accountability",
        description: "Holding schools to measured outcomes.",
        principle: "Hold schools and systems responsible for results via public reporting, ratings, rewards, or sanctions tied to assessment data.",
        example: "ESSA state accountability systems (successor to NCLB).",
        principalCritiques: "Contested. NCLB-era studies find modest measured gains in tested subjects, particularly in mathematics and in lower grades, alongside narrowing of curriculum and elevated pressure. ESSA (2015) devolves more design to states and allows a wider set of indicators, which most evaluators view as a course-correction; the underlying question of whether test-driven accountability produces durable learning gains at the scale claimed by proponents remains contested.",
        tags: ["large-scale", "policy"],
        status: "open",
      },
      {
        name: "Campbell's law & score inflation",
        description: "Pressure corrupts the measure.",
        principle: "The more a quantitative indicator is used for high-stakes decisions, the more it is subject to corruption pressures and the more it distorts what it measures.",
        example: "Teaching to the test; narrowed curriculum; erasure scandals.",
        tags: ["large-scale", "policy"],
        xref: ["statistics"],
      },
      {
        name: "Opportunity to learn",
        description: "Did students get a fair chance to learn it?",
        principle: "Interpreting achievement requires knowing whether students had access to the content and conditions needed to learn it; without it, scores conflate learning and opportunity.",
        example: "Content coverage and resource gaps.",
        tags: ["large-scale", "equity"],
      },
      {
        name: "Test bias & fairness",
        description: "Ensuring tests measure fairly across groups.",
        principle: "Fairness requires minimizing construct-irrelevant barriers and DIF, providing accommodations, and validating uses for all subgroups.",
        example: "Accessibility and accommodation policies.",
        tags: ["large-scale", "fairness"],
        xref: ["statistics"],
      },
      {
        name: "Standardized testing (the debate)",
        description: "Comparable measurement vs its costs.",
        principle: "Standardized tests offer comparable, efficient information and can surface inequities, while critics cite narrowing, stress, cultural bias, and limited construct coverage.",
        example: "The admissions test-optional debates.",
        principalCritiques: "Genuinely contested at policy level. Recent evidence on admissions testing includes work (Chetty and colleagues; internal analyses at several selective universities) that SAT/ACT scores incrementally predict college performance beyond high-school GPA, particularly at the top of the distribution and after test-optional policies were adopted; several selective institutions have reinstated a testing requirement citing that evidence. Critics point to disparate access to preparation, correlation of scores with parental income, and the risk of over-weighting a single measure. The evidence base tilts toward \"scores add signal when used alongside other information;\" whether that signal is worth the systemic costs is a value judgment on which the field disagrees.",
        tags: ["large-scale", "policy"],
        status: "open",
      },
    ],
  },
];
