import type { Family } from "./data";

// ── SECTION B: SCHOOLS II — HETERODOX ────────────────────────────────────────

// Family 5 — Austrian School
const AUSTRIAN_FAMILY: Family = {
  slug: "austrian-school",
  name: "Austrian School",
  blurb: "Subjectivism, market process, spontaneous order, and the impossibility of central planning.",
  color: "amber",
  isms: [
    {
      name: "Austrian school",
      description: "Economics grounded in subjective value, methodological individualism, and the market as a discovery process.",
      tags: ["c19", "c20", "xref:ideologies"],
      tenet: "Economic phenomena must be explained from the purposeful actions of individuals; the market is a dynamic process of discovery, not an equilibrium state.",
      lineage: { parents: ["Classical political economy"], divergence: "Menger founds subjectivism; diverges from both classical labor value and Walrasian formalism" },
      figures: ["Carl Menger", "Ludwig von Mises", "Friedrich Hayek", "Murray Rothbard"],
      era: ["c19", "c20"],
      coreTenets: [
        "Value is subjective — it exists only in the mind of the individual evaluator, not in the object.",
        "The market is a dynamic process driven by entrepreneurial discovery, not a static equilibrium.",
        "Economic laws are derived a priori from the logic of human action, not from statistical regularities.",
      ],
      keyThinkers: ["Carl Menger — Grundsatze der Volkswirthschaftslehre (1871)", "Ludwig von Mises — Human Action (1949)", "Friedrich Hayek — 'The Use of Knowledge in Society' (1945)"],
      principalCritiques: [
        "Mainstream economists argue Austrian rejection of mathematical modeling and econometrics limits the school's empirical relevance.",
        "Post-Keynesians contend Austrian business cycle theory fails to account for effective-demand failures.",
      ],
      broadFamily: true,
    },
    {
      name: "Subjective theory of value",
      description: "The value of a good is determined by the importance an individual places on it for the satisfaction of their ends.",
      tags: ["c19", "concept"],
      tenet: "Value is not inherent in objects; it is the significance that an acting individual attaches to a good for the achievement of desired ends.",
      lineage: { parents: ["Austrian school"], divergence: "Menger's foundational insight; basis of all Austrian price theory" },
      figures: ["Carl Menger"],
      era: ["c19"],
      coreTenets: [
        "Value originates in the human mind, not in the labor or material content of the good.",
        "Goods are valued according to their importance for satisfying the least important end they serve (marginal utility).",
        "Higher-order (producer) goods derive their value from the consumer goods they help produce (imputation).",
      ],
      keyThinkers: ["Carl Menger — Grundsatze, Chapter 3"],
      principalCritiques: [
        "Marxians argue subjectivism eliminates the basis for analyzing exploitation, which requires an objective measure of value.",
        "Sraffians contend prices can be determined from technology and distribution without any reference to subjective valuation.",
      ],
    },
    {
      name: "Praxeology",
      description: "The a priori science of human action; economic laws are deduced from the axiom that humans act purposefully.",
      tags: ["c20", "concept"],
      tenet: "Economics is a branch of praxeology — the science of human action — whose theorems are logically deduced from the action axiom.",
      lineage: { parents: ["Austrian school"], divergence: "Mises's methodological programme; grounds economics in logic rather than empirical generalization" },
      figures: ["Ludwig von Mises"],
      era: ["c20"],
      coreTenets: [
        "The fundamental axiom: human beings act — they employ means to achieve chosen ends.",
        "Economic laws (e.g., diminishing marginal utility, time preference) are logically entailed by the action axiom.",
        "Empirical testing cannot refute a priori economic theory, only illustrate its applications.",
      ],
      keyThinkers: ["Ludwig von Mises — Human Action (1949), especially Part 1"],
      principalCritiques: [
        "Mainstream economists argue that a priori reasoning without empirical testing produces unfalsifiable claims.",
        "Even some Austrians (Hayek, Lachmann) questioned whether praxeology can generate sufficiently rich predictions.",
      ],
    },
    {
      name: "Economic calculation problem",
      description: "Without market prices for capital goods, rational economic calculation is impossible — socialism cannot allocate resources efficiently.",
      tags: ["c20", "concept"],
      tenet: "Socialist planners cannot rationally allocate resources because, without private ownership of capital goods, there are no market prices to guide calculation.",
      lineage: { parents: ["Austrian school"], divergence: "Mises's 1920 argument; the Austrian school's most influential critique of socialism" },
      figures: ["Ludwig von Mises", "Friedrich Hayek"],
      era: ["c20"],
      coreTenets: [
        "Market prices for capital goods are necessary for rational profit-and-loss calculation.",
        "Without private ownership, no genuine market for capital goods exists; without a market, no prices; without prices, no calculation.",
        "Proposals for 'market socialism' (Lange) cannot replicate the entrepreneurial discovery process that generates genuine prices.",
      ],
      keyThinkers: ["Ludwig von Mises — 'Economic Calculation in the Socialist Commonwealth' (1920)", "Friedrich Hayek — 'The Use of Knowledge in Society' (1945)"],
      principalCritiques: [
        "Oskar Lange argued central planners could use trial-and-error pricing to simulate market outcomes.",
        "Historians note that Soviet economies did function (poorly) for decades, suggesting the problem is one of degree, not absolute impossibility.",
      ],
    },
    {
      name: "Knowledge problem",
      description: "Dispersed, tacit knowledge cannot be centralized; the price system is the only mechanism that aggregates it.",
      tags: ["c20", "concept"],
      tenet: "The knowledge relevant to economic decisions is dispersed among millions of individuals and is largely tacit; only the price system can aggregate it.",
      lineage: { parents: ["Austrian school"], divergence: "Hayek's 1945 reformulation of the calculation problem; shifts the argument from calculation to knowledge" },
      figures: ["Friedrich Hayek"],
      era: ["c20"],
      coreTenets: [
        "The 'data' of economic problems are never 'given' to a single mind; they exist as dispersed bits of knowledge.",
        "Much economically relevant knowledge is tacit — embodied in skills, habits, and local circumstances — and cannot be communicated to a central authority.",
        "The price system is a mechanism for communicating information that no single agent possesses.",
      ],
      keyThinkers: ["Friedrich Hayek — 'The Use of Knowledge in Society' (AER, 1945)"],
      principalCritiques: [
        "Critics note that large corporations (Walmart, Amazon) do engage in vast internal planning, suggesting centralized coordination is possible at scale.",
        "Information-technology advocates argue modern computing can handle the data-aggregation problem Hayek described.",
      ],
    },
    {
      name: "Spontaneous order and catallaxy",
      description: "Complex social orders arise from human action but not human design; the market is a spontaneous order, not a planned system.",
      tags: ["c20", "concept"],
      tenet: "The market order (catallaxy) emerges spontaneously from individuals following general rules of conduct; it is not designed by anyone.",
      lineage: { parents: ["Austrian school"], divergence: "Hayek's social-theory extension of the knowledge problem; links Austrian economics to evolutionary epistemology" },
      figures: ["Friedrich Hayek"],
      era: ["c20"],
      coreTenets: [
        "Spontaneous orders (language, law, markets) arise from human action but not human design.",
        "Catallaxy — the market order — coordinates diverse individual plans through abstract rules and price signals.",
        "Attempts to impose a single purpose on a spontaneous order destroy the information and adaptation it produces.",
      ],
      keyThinkers: ["Friedrich Hayek — Law, Legislation, and Liberty (1973-79)", "Friedrich Hayek — The Constitution of Liberty (1960)"],
      principalCritiques: [
        "Institutionalists argue that market orders are always embedded in legal and political frameworks that are deliberately designed.",
        "Critics note that 'spontaneous order' can naturalize unjust outcomes by portraying them as emergent rather than chosen.",
      ],
    },
    {
      name: "Austrian business cycle theory",
      description: "Credit expansion by central banks artificially lowers interest rates, causing malinvestment and an inevitable bust.",
      tags: ["c20", "concept"],
      tenet: "Artificial credit expansion lowers interest rates below their natural level, distorting the capital structure and causing a boom-bust cycle.",
      lineage: { parents: ["Austrian school"], divergence: "Mises-Hayek theory of the trade cycle; attributes recessions to prior monetary expansion" },
      figures: ["Ludwig von Mises", "Friedrich Hayek"],
      era: ["c20"],
      coreTenets: [
        "The 'natural' rate of interest coordinates production across time; artificial lowering by credit expansion distorts this signal.",
        "Entrepreneurs undertake projects that appear profitable at the low rate but are unsustainable at the natural rate.",
        "The bust is the necessary correction — liquidation of malinvestments and restoration of sustainable capital structure.",
      ],
      keyThinkers: ["Friedrich Hayek — Prices and Production (1931)", "Ludwig von Mises — The Theory of Money and Credit (1912)"],
      principalCritiques: [
        "Keynesians argue that demand deficiency, not prior malinvestment, is the primary cause of recessions.",
        "Mainstream macroeconomists contend the theory lacks formal rigor and empirical support compared to New Keynesian models.",
      ],
    },
    {
      name: "Entrepreneurship and market process",
      description: "The entrepreneur discovers profit opportunities that others have missed, driving the market toward coordination.",
      tags: ["c20", "concept"],
      tenet: "The market is a process driven by entrepreneurial alertness to previously unnoticed profit opportunities.",
      lineage: { parents: ["Austrian school"], divergence: "Kirzner's contribution; rehabilitates the entrepreneur as the central figure of market theory" },
      figures: ["Israel Kirzner", "Ludwig Lachmann"],
      era: ["c20"],
      coreTenets: [
        "Entrepreneurial alertness — the ability to notice what others overlook — is the driving force of the market process.",
        "Profit opportunities signal coordination failures; entrepreneurial action tends to correct them.",
        "The market is never in equilibrium; it is always in process, driven by discovery and creative destruction.",
      ],
      keyThinkers: ["Israel Kirzner — Competition and Entrepreneurship (1973)", "Ludwig Lachmann — The Market as an Economic Process (1986)"],
      principalCritiques: [
        "Schumpeter's 'creative destruction' model emphasizes the disruptive (not merely corrective) role of the entrepreneur.",
        "Mainstream economists argue Kirzner's theory is difficult to formalize and test empirically.",
      ],
    },
  ],
};

// Family 6 — Historical & Institutional
const HISTORICAL_INSTITUTIONAL_FAMILY: Family = {
  slug: "historical-institutional",
  name: "Historical & Institutional",
  blurb: "Institutions, not abstract laws, shape economies: from the German historical school through Veblen and Ostrom to Schumpeter.",
  color: "teal",
  broadFamily: true,
  isms: [
    {
      name: "German historical school",
      description: "Economic laws are historically and nationally specific; reject universal deductive theory in favor of empirical-historical study.",
      tags: ["c19"],
      tenet: "There are no universal economic laws; economic generalizations are historically and nationally specific.",
      lineage: { parents: ["Classical political economy"], divergence: "institutions over universal laws — rejects the Ricardian method in favor of historical-empirical study" },
      figures: ["Wilhelm Roscher", "Bruno Hildebrand", "Karl Knies", "Gustav von Schmoller"],
      era: ["c19"],
      coreTenets: [
        "Economic institutions, laws, and behaviors are products of specific historical and cultural contexts.",
        "Inductive, empirical-historical research is more reliable than abstract deductive theory.",
        "National economies develop through stages; policy must be tailored to each nation's stage of development.",
      ],
      keyThinkers: ["Gustav von Schmoller — leader of the Younger Historical School", "Wilhelm Roscher — Principles of Political Economy (1854)"],
      principalCritiques: [
        "Menger attacked the historical school's rejection of theory in the Methodenstreit, arguing that theoretical laws are necessary for any social science.",
        "Critics note the historical school produced vast empirical work but few enduring theoretical propositions.",
      ],
    },
    {
      name: "Methodenstreit",
      description: "The 1880s-90s debate between Menger (deductive theory) and Schmoller (historical-empirical method) over the proper method of economics.",
      tags: ["c19", "concept"],
      tenet: "The fundamental question: should economics proceed by abstract deduction from axioms (Menger) or by inductive historical research (Schmoller)?",
      lineage: { parents: ["German historical school", "Austrian school"], divergence: "the methodological battle that separated Austrian and German traditions; never fully resolved" },
      figures: ["Carl Menger", "Gustav von Schmoller"],
      era: ["c19"],
      coreTenets: [
        "Menger: economic theory must establish exact laws through logical deduction from self-evident premises.",
        "Schmoller: economic knowledge comes from careful historical and statistical investigation of institutions.",
        "The dispute shaped the subsequent division between formalist and institutionalist traditions in economics.",
      ],
      keyThinkers: ["Carl Menger — Investigations into the Method of the Social Sciences (1883)", "Gustav von Schmoller — review and response"],
      principalCritiques: [
        "Modern economics largely sided with Menger on the need for theory but adopted mathematical formalism rather than Menger's verbal logic.",
        "Institutional economists argue the Methodenstreit was a false dichotomy — theory and history are complementary, not rival methods.",
      ],
    },
    {
      name: "National System (List)",
      description: "Developing nations need tariff protection to build infant industries before they can compete in free trade.",
      tags: ["c19", "concept"],
      tenet: "Free trade benefits the industrially advanced; developing nations must protect infant industries with tariffs until they can compete.",
      lineage: { parents: ["German historical school"], divergence: "List's critique of Smithian free trade; argues for nation-specific, stage-dependent economic policy" },
      figures: ["Friedrich List"],
      era: ["c19"],
      coreTenets: [
        "Nations pass through stages of development; policy appropriate to one stage may be harmful at another.",
        "Infant industries need temporary tariff protection to develop the scale and skills to compete internationally.",
        "Britain advocated free trade only after it had built its own industries behind protectionist walls — 'kicking away the ladder.'",
      ],
      keyThinkers: ["Friedrich List — The National System of Political Economy (1841)"],
      historicalInstances: ["American System (Hamilton, Clay)", "German Zollverein and industrialization", "East Asian developmental states (modern heirs)"],
      principalCritiques: [
        "Free-trade economists argue infant-industry protection creates vested interests that resist liberalization even after maturity.",
        "The empirical record of infant-industry protection is mixed — successes (South Korea, Taiwan) coexist with failures (Latin American ISI).",
      ],
    },
    {
      name: "Original institutional economics",
      description: "Economic behavior is shaped by institutions — habits, customs, laws — not by individual optimization in a vacuum.",
      tags: ["c20"],
      tenet: "Economic life is governed by institutions — the habits of thought, customs, and legal frameworks that shape and constrain individual action.",
      lineage: { parents: ["German historical school"], divergence: "American institutionalism; Veblen and Commons ground economics in social habits and legal structures" },
      figures: ["Thorstein Veblen", "John R. Commons", "Wesley Clair Mitchell"],
      era: ["c20"],
      coreTenets: [
        "Economic agents are creatures of habit, embedded in social institutions, not isolated rational maximizers.",
        "Institutions evolve through cumulative causation, not toward any predetermined equilibrium.",
        "The legal framework (property rights, contracts, labor law) shapes economic outcomes at least as much as market forces.",
      ],
      keyThinkers: ["Thorstein Veblen — The Theory of the Leisure Class (1899)", "John R. Commons — Institutional Economics (1934)"],
      principalCritiques: [
        "Neoclassical critics argued old institutionalism was descriptive and lacked a unifying theoretical framework.",
        "New institutional economists (Williamson, North) claimed to provide the missing theoretical rigor while retaining the focus on institutions.",
      ],
    },
    {
      name: "Conspicuous consumption",
      description: "The wealthy consume to display status, not to satisfy needs; consumption is a social act, not a utility calculation.",
      tags: ["c20", "concept"],
      tenet: "Consumption by the leisure class serves to display social status and pecuniary strength, not to satisfy material needs.",
      lineage: { parents: ["Original institutional economics"], divergence: "Veblen's sociology of consumption; challenges the neoclassical assumption that demand reflects genuine preferences" },
      figures: ["Thorstein Veblen"],
      era: ["c20"],
      coreTenets: [
        "The leisure class consumes visibly and wastefully to signal wealth and social standing.",
        "Consumption patterns cascade downward as lower classes emulate the tastes of the wealthy.",
        "Consumer preferences are socially constructed, not given exogenously as neoclassical theory assumes.",
      ],
      keyThinkers: ["Thorstein Veblen — The Theory of the Leisure Class (1899)"],
      principalCritiques: [
        "Neoclassical economists argue revealed preference accounts for status-seeking without abandoning the optimization framework.",
        "Some sociologists contend Veblen overgeneralized from Gilded Age elites to all consumption behavior.",
      ],
    },
    {
      name: "New institutional economics",
      description: "Institutions are the rules of the game; transaction costs, property rights, and governance structures determine economic performance.",
      tags: ["c20", "c21"],
      tenet: "Institutions — the formal and informal rules of the game — shape incentives and determine economic performance; transaction costs explain institutional form.",
      lineage: { parents: ["Original institutional economics", "Neoclassical economics"], divergence: "retains methodological individualism and optimization but adds institutions, transaction costs, and bounded rationality" },
      figures: ["Ronald Coase", "Oliver Williamson", "Douglass North", "Elinor Ostrom"],
      era: ["c20", "c21"],
      coreTenets: [
        "Transaction costs — the costs of using the market — explain why firms, contracts, and institutions exist.",
        "Property rights must be well-defined and enforced for markets to function efficiently.",
        "Institutions change slowly; path dependence means that history matters for economic performance.",
      ],
      keyThinkers: ["Ronald Coase — 'The Nature of the Firm' (1937)", "Oliver Williamson — The Economic Institutions of Capitalism (1985)", "Douglass North — Institutions, Institutional Change and Economic Performance (1990)"],
      principalCritiques: [
        "Old institutionalists argue NIE reduces institutions to efficiency explanations, ignoring power, ideology, and distributional conflict.",
        "Marxians contend NIE naturalizes capitalist property relations by treating them as efficient solutions to transaction-cost problems.",
      ],
      broadFamily: true,
    },
    {
      name: "Transaction cost economics",
      description: "The costs of using the price mechanism — search, bargaining, enforcement — determine the boundaries of firms and markets.",
      tags: ["c20", "concept"],
      tenet: "Firms exist because market transactions are costly; the boundary of the firm is set where the cost of internal organization equals the cost of market exchange.",
      lineage: { parents: ["New institutional economics"], divergence: "Coase's and Williamson's framework; explains vertical integration, governance structures, and contractual forms" },
      figures: ["Ronald Coase", "Oliver Williamson"],
      era: ["c20"],
      coreTenets: [
        "Market transactions involve costs: searching for partners, negotiating terms, and enforcing agreements.",
        "Asset specificity, uncertainty, and frequency of transactions determine whether markets, hierarchies, or hybrids govern exchange.",
        "Governance structures are chosen to minimize the sum of production and transaction costs.",
      ],
      keyThinkers: ["Ronald Coase — 'The Nature of the Firm' (1937)", "Oliver Williamson — Markets and Hierarchies (1975)"],
      principalCritiques: [
        "Critics argue transaction cost economics is tautological — any observed arrangement can be rationalized as minimizing some cost.",
        "Radical economists contend the framework ignores power and treats hierarchical firms as if they were efficient rather than exploitative.",
      ],
    },
    {
      name: "Property rights and the Coase theorem",
      description: "If property rights are well-defined and transaction costs are zero, bargaining will produce efficient outcomes regardless of the initial allocation.",
      tags: ["c20", "concept"],
      tenet: "With well-defined property rights and zero transaction costs, private bargaining will reach an efficient outcome regardless of the initial assignment of rights.",
      lineage: { parents: ["New institutional economics"], divergence: "Coase's insight; reframes externalities as bilateral problems solvable by private bargaining" },
      figures: ["Ronald Coase"],
      era: ["c20"],
      coreTenets: [
        "Externalities are reciprocal — both parties cause the conflict; the question is which assignment of rights minimizes total harm.",
        "When transaction costs are zero, the initial allocation of rights does not affect efficiency (only distribution).",
        "In the real world, transaction costs are positive; the law should assign rights to minimize total social costs.",
      ],
      keyThinkers: ["Ronald Coase — 'The Problem of Social Cost' (1960)"],
      principalCritiques: [
        "Critics note the zero-transaction-cost assumption is wildly unrealistic; the theorem's main lesson is that transaction costs matter.",
        "Environmentalists argue Coasean bargaining fails for diffuse externalities (climate change) affecting millions of parties.",
      ],
    },
    {
      name: "Institutions and development",
      description: "Inclusive institutions promote prosperity; extractive institutions perpetuate poverty — institutional quality explains the wealth of nations.",
      tags: ["c20", "c21"],
      tenet: "The wealth and poverty of nations is determined primarily by the quality of their political and economic institutions.",
      lineage: { parents: ["New institutional economics"], divergence: "North's institutional development theory extended by Acemoglu and Robinson; institutions as the fundamental cause of growth" },
      figures: ["Douglass North", "Daron Acemoglu", "James Robinson"],
      era: ["c20", "c21"],
      coreTenets: [
        "Inclusive institutions (secure property rights, rule of law, open competition) promote innovation and growth.",
        "Extractive institutions (concentrated power, insecure rights, barriers to entry) perpetuate poverty.",
        "Critical junctures and path dependence explain why some nations developed inclusive institutions and others did not.",
      ],
      keyThinkers: ["Douglass North — Understanding the Process of Economic Change (2005)", "Acemoglu & Robinson — Why Nations Fail (2012)"],
      principalCritiques: [
        "Geography-based explanations (Diamond, Sachs) argue institutions are themselves shaped by geographic and ecological factors.",
        "World-systems theorists contend 'institutions and development' ignores the global power structures that constrain peripheral nations.",
      ],
    },
    {
      name: "Commons governance",
      description: "Communities can and do manage common-pool resources sustainably through self-governance, without privatization or state control.",
      tags: ["c20", "concept"],
      tenet: "Communities can sustainably govern common-pool resources through self-organized institutions, without privatization or state control.",
      lineage: { parents: ["New institutional economics"], divergence: "Ostrom's empirical refutation of the 'tragedy of the commons'; communities develop diverse, effective governance solutions" },
      figures: ["Elinor Ostrom"],
      era: ["c20"],
      coreTenets: [
        "The 'tragedy of the commons' is not inevitable; communities develop rules to prevent overexploitation.",
        "Ostrom's eight design principles (clear boundaries, proportional costs/benefits, collective choice, monitoring, sanctions, conflict resolution, autonomy, nested governance) predict successful commons governance.",
        "Neither privatization nor centralized state control is always the best solution; polycentric governance often works.",
      ],
      keyThinkers: ["Elinor Ostrom — Governing the Commons (1990)"],
      principalCritiques: [
        "Critics argue Ostrom's cases are small-scale; scaling commons governance to global problems (climate change, oceans) remains uncertain.",
        "Some economists contend her design principles are too context-dependent to serve as general policy prescriptions.",
      ],
    },
    {
      name: "Regulation theory (French)",
      description: "Capitalism stabilizes through historically specific institutional forms — modes of regulation — that periodically break down.",
      tags: ["c20"],
      tenet: "Capitalist accumulation is stabilized by historically specific institutional configurations (modes of regulation) that eventually enter crisis.",
      lineage: { parents: ["Marxian political economy", "Original institutional economics"], divergence: "French heterodox school; combines Marxian crisis theory with institutional analysis of capitalism's variety and stability" },
      figures: ["Michel Aglietta", "Robert Boyer", "Alain Lipietz"],
      era: ["c20"],
      coreTenets: [
        "Each regime of accumulation is sustained by a mode of regulation — the institutional forms (wage relation, state form, monetary regime) that stabilize it.",
        "Fordism — mass production + mass consumption + Keynesian welfare state — was the postwar regime of accumulation.",
        "The crisis of Fordism in the 1970s led to a new, as-yet-unstable post-Fordist regime.",
      ],
      keyThinkers: ["Michel Aglietta — A Theory of Capitalist Regulation (1979)", "Robert Boyer — The Regulation School: A Critical Introduction (1990)"],
      principalCritiques: [
        "Critics argue regulation theory is descriptive rather than explanatory — it labels periods but does not predict transitions.",
        "Marxists contend that institutionalizing crisis management obscures the underlying contradictions of capitalist accumulation.",
      ],
    },
    {
      name: "Social structure of accumulation",
      description: "Long waves of capitalist growth are sustained by institutional frameworks that periodically decay and are rebuilt.",
      tags: ["c20"],
      tenet: "Capitalist growth depends on a 'social structure of accumulation' — the institutional framework that facilitates investment and labor control.",
      lineage: { parents: ["Marxian political economy"], divergence: "American radical school; parallels French regulation theory; emphasizes institutional cycles of investment" },
      figures: ["David Gordon", "Samuel Bowles", "Thomas Weisskopf"],
      era: ["c20"],
      coreTenets: [
        "A social structure of accumulation (SSA) is the institutional environment that supports a long period of capital accumulation.",
        "Each SSA includes labor relations, market structure, monetary arrangements, and international economic order.",
        "When an SSA decays, accumulation slows; a new period of growth requires building a new institutional framework.",
      ],
      keyThinkers: ["Gordon, Edwards & Reich — Segmented Work, Divided Workers (1982)", "Bowles, Gordon & Weisskopf — Beyond the Waste Land (1983)"],
      principalCritiques: [
        "Critics argue SSA theory is too structuralist and underestimates the role of agency and contingency in institutional change.",
        "Mainstream economists contend the concept of long waves lacks rigorous empirical support.",
      ],
    },
    {
      name: "Evolutionary economics",
      description: "Economic change is driven by variation, selection, and retention of routines, technologies, and institutions — a Darwinian process.",
      tags: ["c20"],
      tenet: "Economic change resembles biological evolution: firms operate by routines, innovate through search, and are selected by the market environment.",
      lineage: { parents: ["Original institutional economics"], divergence: "Nelson and Winter formalize Schumpeterian themes in an evolutionary framework; challenge equilibrium economics" },
      figures: ["Richard Nelson", "Sidney Winter", "Joseph Schumpeter (proto)"],
      era: ["c20"],
      coreTenets: [
        "Firms are bundles of routines — organizational capabilities that evolve through learning, imitation, and selection.",
        "Innovation is a search process under uncertainty, not rational optimization of a known function.",
        "Market selection does not necessarily produce optimal outcomes; path dependence and lock-in are common.",
      ],
      keyThinkers: ["Richard Nelson & Sidney Winter — An Evolutionary Theory of Economic Change (1982)", "Joseph Schumpeter — Capitalism, Socialism, and Democracy (1942)"],
      principalCritiques: [
        "Mainstream economists argue evolutionary models lack the predictive precision of equilibrium analysis.",
        "Biologists caution that economic evolution differs fundamentally from biological evolution (Lamarckian inheritance, intentional variation).",
      ],
    },
    {
      name: "Creative destruction",
      description: "Capitalism progresses through the incessant destruction of old structures by innovation — the essential fact about capitalism.",
      tags: ["c20", "concept"],
      tenet: "The fundamental impulse of capitalism is creative destruction — the process by which innovation incessantly destroys old structures and creates new ones.",
      lineage: { parents: ["Evolutionary economics"], divergence: "Schumpeter's central concept; the entrepreneur as revolutionary, not equilibrating, force" },
      figures: ["Joseph Schumpeter"],
      era: ["c20"],
      coreTenets: [
        "Capitalism is a process of industrial mutation that incessantly revolutionizes the economic structure from within.",
        "The entrepreneur — not the manager or the capitalist — is the agent of creative destruction.",
        "Short-run monopoly profits are the reward for successful innovation and the incentive that drives the process.",
      ],
      keyThinkers: ["Joseph Schumpeter — Capitalism, Socialism, and Democracy (1942), Chapter 7"],
      principalCritiques: [
        "Critics argue Schumpeter romanticized disruption and underestimated the social costs of displacement and inequality.",
        "Institutionalists note that 'creative destruction' can be used to justify deregulation and opposition to worker protection.",
      ],
    },
  ],
};

// Family 7 — Behavioral, Ecological & Feminist
const BEHAVIORAL_ECOLOGICAL_FEMINIST_FAMILY: Family = {
  slug: "behavioral-ecological-feminist",
  name: "Behavioral, Ecological & Feminist",
  blurb: "Challenges to homo economicus: cognitive biases, biophysical limits, and the invisible economy of care.",
  color: "green",
  isms: [
    {
      name: "Behavioral economics",
      description: "Systematic cognitive biases and heuristics cause real economic agents to deviate predictably from rational-choice theory.",
      tags: ["c20", "c21", "xref:economics"],
      tenet: "Real human decision-making is shaped by cognitive biases, heuristics, and framing effects that cause systematic deviations from rationality.",
      lineage: { parents: ["Neoclassical economics"], divergence: "retains the optimization framework as a benchmark but documents systematic, predictable departures from it" },
      figures: ["Daniel Kahneman", "Amos Tversky", "Richard Thaler", "Cass Sunstein"],
      era: ["c20", "c21"],
      coreTenets: [
        "People use mental shortcuts (heuristics) that are often useful but produce systematic biases.",
        "Framing effects, loss aversion, and present bias violate the assumptions of expected utility theory.",
        "Behavioral insights can improve policy design (nudges) without restricting choice.",
      ],
      keyThinkers: ["Kahneman & Tversky — 'Prospect Theory' (Econometrica, 1979)", "Richard Thaler — Misbehaving (2015)"],
      principalCritiques: [
        "Austrians argue behavioral economics documents interesting anomalies but lacks a coherent alternative theory of action.",
        "Critics of nudge policy worry about libertarian paternalism becoming a vehicle for manipulation by those who design the choice architecture.",
      ],
      broadFamily: true,
    },
    {
      name: "Bounded rationality",
      description: "Agents lack the information and computational capacity to optimize; they satisfice — seek 'good enough' rather than best.",
      tags: ["c20", "concept"],
      tenet: "Human beings are intendedly rational but limited; they satisfice rather than optimize because of cognitive and informational constraints.",
      lineage: { parents: ["Behavioral economics"], divergence: "Simon's foundational concept; predates and enables the behavioral economics movement" },
      figures: ["Herbert Simon"],
      era: ["c20"],
      coreTenets: [
        "Optimization requires knowledge and computation that real agents do not possess.",
        "Satisficing — choosing an option that meets an acceptable threshold — is the realistic description of human choice.",
        "Organizational structure and decision rules compensate for individual cognitive limitations.",
      ],
      keyThinkers: ["Herbert Simon — 'A Behavioral Model of Rational Choice' (1955)", "Herbert Simon — Administrative Behavior (1947)"],
      principalCritiques: [
        "Neoclassical economists argue that 'as if' optimization (Friedman) is a sufficient approximation even if agents do not literally optimize.",
        "Some critics contend satisficing is itself a form of optimization — optimizing subject to cognitive constraints — and thus not a genuine departure.",
      ],
    },
    {
      name: "Prospect theory",
      description: "People evaluate outcomes relative to a reference point; losses loom larger than gains: v(x) is concave for gains, convex for losses.",
      tags: ["c20", "concept"],
      tenet: "People evaluate outcomes relative to a reference point, weighting losses more heavily than equivalent gains: the value function v(x) is concave for gains and convex for losses.",
      lineage: { parents: ["Behavioral economics"], divergence: "Kahneman and Tversky's alternative to expected utility theory; the most influential behavioral model" },
      figures: ["Daniel Kahneman", "Amos Tversky"],
      era: ["c20"],
      coreTenets: [
        "The value function is defined over changes from a reference point, not over final wealth states.",
        "Loss aversion: losses feel roughly twice as painful as equivalent gains feel pleasant.",
        "Probability weighting: people overweight small probabilities and underweight moderate-to-large ones.",
      ],
      keyThinkers: ["Kahneman & Tversky — 'Prospect Theory: An Analysis of Decision under Risk' (Econometrica, 1979)"],
      principalCritiques: [
        "Some economists argue prospect theory is descriptive rather than prescriptive and cannot ground welfare analysis.",
        "Methodological critics note the reference point is often determined ex post, making the theory difficult to falsify.",
      ],
    },
    {
      name: "Nudges",
      description: "Redesign choice architecture to steer people toward better decisions without restricting their options.",
      tags: ["c21", "concept"],
      tenet: "By redesigning choice architecture — defaults, framing, salience — policymakers can improve decisions without eliminating options ('libertarian paternalism').",
      lineage: { parents: ["Behavioral economics"], divergence: "policy application of behavioral insights; Thaler and Sunstein's programme for 'libertarian paternalism'" },
      figures: ["Richard Thaler", "Cass Sunstein"],
      era: ["c21"],
      coreTenets: [
        "Default options powerfully shape behavior; opt-out pension enrollment dramatically increases saving.",
        "Simplifying information and making consequences salient helps people make choices aligned with their own goals.",
        "Nudges preserve freedom of choice while systematically improving welfare outcomes.",
      ],
      keyThinkers: ["Thaler & Sunstein — Nudge: Improving Decisions about Health, Wealth, and Happiness (2008)"],
      principalCritiques: [
        "Autonomy-focused critics argue nudges manipulate rather than inform, undermining the dignity of rational agency.",
        "Structural critics argue nudges address individual behavior while ignoring systemic causes of inequality and market failure.",
      ],
    },
    {
      name: "Ecological economics",
      description: "The economy is a subsystem of the biosphere; throughput of energy and materials is subject to thermodynamic limits.",
      tags: ["c20", "c21"],
      tenet: "The economy is an open subsystem of the finite biosphere; growth in material throughput cannot continue indefinitely.",
      lineage: { parents: [], divergence: "root — transdisciplinary; integrates thermodynamics, ecology, and economics against the neoclassical growth paradigm" },
      figures: ["Nicholas Georgescu-Roegen", "Herman Daly", "Robert Costanza"],
      era: ["c20", "c21"],
      coreTenets: [
        "The economy obeys the laws of thermodynamics; high-quality energy is irreversibly degraded (entropy).",
        "Natural capital — ecosystem services, biodiversity, stable climate — is complementary to, not substitutable for, manufactured capital.",
        "GDP growth beyond a threshold may reduce genuine well-being (the 'threshold hypothesis').",
      ],
      keyThinkers: ["Nicholas Georgescu-Roegen — The Entropy Law and the Economic Process (1971)", "Herman Daly — Steady-State Economics (1977)"],
      principalCritiques: [
        "Growth economists argue technological innovation can decouple economic growth from material throughput (green growth).",
        "Critics note that steady-state proposals lack a clear transition mechanism from the current growth-dependent global economy.",
      ],
    },
    {
      name: "Entropy and biophysical limits",
      description: "All economic activity transforms low-entropy resources into high-entropy waste; thermodynamic limits constrain growth.",
      tags: ["c20", "concept"],
      tenet: "Economic production is fundamentally a process of transforming low-entropy matter-energy into high-entropy waste; this process faces absolute biophysical limits.",
      lineage: { parents: ["Ecological economics"], divergence: "Georgescu-Roegen's thermodynamic foundation for ecological economics" },
      figures: ["Nicholas Georgescu-Roegen"],
      era: ["c20"],
      coreTenets: [
        "The entropy law sets ultimate limits on economic activity that no technology can circumvent.",
        "Mineral resources are dissipated, not recycled perfectly; complete circular economy is thermodynamically impossible.",
        "Solar energy is the only truly renewable input; fossil fuels are a one-time geological endowment.",
      ],
      keyThinkers: ["Nicholas Georgescu-Roegen — The Entropy Law and the Economic Process (1971)"],
      principalCritiques: [
        "Mainstream economists (Solow, Nordhaus) argue entropy constraints bind only in the very long run and are irrelevant for practical policy.",
        "Some physicists contend Georgescu-Roegen overextended the second law of thermodynamics to contexts where it does not strictly apply.",
      ],
    },
    {
      name: "Steady-state economics",
      description: "An economy with stable population and capital stock, maintained by low throughput; growth is replaced by development.",
      tags: ["c20", "concept"],
      tenet: "A sustainable economy maintains a stable population and capital stock at a level compatible with ecological carrying capacity; qualitative development replaces quantitative growth.",
      lineage: { parents: ["Ecological economics"], divergence: "Daly's policy programme derived from Georgescu-Roegen's biophysical critique" },
      figures: ["Herman Daly"],
      era: ["c20"],
      coreTenets: [
        "Distinguish growth (quantitative increase in throughput) from development (qualitative improvement in well-being).",
        "Cap-and-trade for resources, ecological tax reform, and maximum income/wealth ratios are policy tools.",
        "An optimal scale of the economy exists beyond which further growth reduces welfare.",
      ],
      keyThinkers: ["Herman Daly — Steady-State Economics (1977)", "Herman Daly — Beyond Growth (1996)"],
      principalCritiques: [
        "Growth advocates argue a steady state is politically impossible in a world where billions still live in poverty.",
        "Critics ask how developing nations would ever reach acceptable living standards without growth.",
      ],
    },
    {
      name: "Degrowth",
      description: "Planned, equitable downscaling of production and consumption to bring the economy within ecological limits.",
      tags: ["c21", "concept", "live-dispute"],
      tenet: "Rich nations must equitably and democratically downscale production and consumption to achieve ecological sustainability and social justice.",
      lineage: { parents: ["Steady-state economics", "Ecological economics"], divergence: "radicalized; moves from 'no growth' to intentional contraction; combines ecological with social-justice critique" },
      figures: ["Serge Latouche", "Giorgos Kallis", "Jason Hickel"],
      era: ["c21"],
      coreTenets: [
        "Green growth is a myth — decoupling GDP from ecological impact at the rate required is not happening.",
        "Degrowth targets rich nations; global South may still need selective growth in essential sectors.",
        "Shorter working time, universal basic services, and caps on resource use are core policy tools.",
      ],
      keyThinkers: ["Serge Latouche — Farewell to Growth (2009)", "Giorgos Kallis — Degrowth (2018)", "Jason Hickel — Less Is More (2020)"],
      principalCritiques: [
        "Growth economists argue degrowth would condemn billions to poverty and undermine the fiscal basis for welfare states.",
        "Political realists contend that no democratic electorate will vote for lower material living standards.",
      ],
      flagged: true,
    },
    {
      name: "Feminist economics",
      description: "Make visible the unpaid care and reproductive labor that sustains the market economy but is excluded from standard analysis.",
      tags: ["c20", "c21"],
      tenet: "The market economy depends on unpaid care, domestic, and reproductive labor — disproportionately performed by women — that standard economics renders invisible.",
      lineage: { parents: [], divergence: "root — challenges the boundary between 'economic' and 'non-economic'; makes gender a central analytical category" },
      figures: ["Marilyn Waring", "Nancy Folbre", "Diane Elson"],
      era: ["c20", "c21"],
      coreTenets: [
        "GDP and national accounts systematically exclude unpaid household and care work, understating women's economic contribution.",
        "The 'rational economic man' model ignores interdependence, caregiving, and the social provisioning that markets require.",
        "Gender-disaggregated analysis reveals that macroeconomic policies (austerity, trade liberalization) have differential impacts on women.",
      ],
      keyThinkers: ["Marilyn Waring — If Women Counted (1988)", "Nancy Folbre — The Invisible Heart (2001)"],
      principalCritiques: [
        "Mainstream economists argue that unpaid work can be incorporated into existing frameworks without a separate 'feminist economics.'",
        "Some critics contend the focus on gender underplays other axes of inequality (race, class, caste).",
      ],
    },
    {
      name: "Social reproduction and care economy",
      description: "The daily and generational reproduction of the labor force — feeding, teaching, healing — is essential but undervalued economic work.",
      tags: ["c20", "c21", "concept"],
      tenet: "The daily and intergenerational reproduction of human life and labor power — care, education, health — is foundational economic activity, not a residual.",
      lineage: { parents: ["Feminist economics", "Marxian political economy"], divergence: "extends both feminist and Marxian analysis to the conditions under which labor power itself is produced and maintained" },
      figures: ["Silvia Federici", "Nancy Fraser", "Tithi Bhattacharya"],
      era: ["c20", "c21"],
      coreTenets: [
        "Social reproduction — feeding, nurturing, educating, caring — produces and maintains the labor force on which capitalism depends.",
        "Capitalism systematically undervalues and offloads the costs of social reproduction onto women and the global South.",
        "The 'care crisis' (underfunded health, education, elder care) is a structural feature of financialized capitalism.",
      ],
      keyThinkers: ["Silvia Federici — Caliban and the Witch (2004)", "Nancy Fraser — 'Contradictions of Capital and Care' (New Left Review, 2016)"],
      principalCritiques: [
        "Mainstream economists argue that care work can be valued and incorporated via satellite accounts without adopting a Marxian framework.",
        "Some feminists argue social reproduction theory overemphasizes class at the expense of other dimensions of gender oppression.",
      ],
    },
    {
      name: "Capability approach",
      description: "Development should be measured by what people are able to do and be, not by income or utility.",
      tags: ["c20", "c21"],
      tenet: "Development is the expansion of human capabilities — the substantive freedoms to achieve valuable functionings — not mere GDP growth.",
      lineage: { parents: ["Feminist economics"], divergence: "Sen's alternative to utilitarian welfare economics; redefines development in terms of freedom and capability" },
      figures: ["Amartya Sen", "Martha Nussbaum"],
      era: ["c20", "c21"],
      coreTenets: [
        "Functionings are the various beings and doings people can achieve (being nourished, being sheltered, participating in community life).",
        "Capabilities are the real freedoms people have to achieve those functionings.",
        "Income is instrumentally important but insufficient; health, education, political freedom, and social inclusion matter independently.",
      ],
      keyThinkers: ["Amartya Sen — Development as Freedom (1999)", "Martha Nussbaum — Creating Capabilities (2011)"],
      historicalInstances: ["UNDP Human Development Index (inspired by Sen)", "Gender-related Development Index"],
      principalCritiques: [
        "Mainstream economists argue the capability approach is difficult to operationalize for policy comparison — which capabilities count, and how are they weighted?",
        "Marxians contend the capability approach focuses on distribution and opportunity while leaving capitalist production relations unchallenged.",
      ],
    },
  ],
};

export const FAMILIES_S2: Family[] = [
  AUSTRIAN_FAMILY,
  HISTORICAL_INSTITUTIONAL_FAMILY,
  BEHAVIORAL_ECOLOGICAL_FEMINIST_FAMILY,
];
