export type Ism = {
  name: string;
  description: string;
  tags: string[];
  tenet: string;
  lineage: { parents: string[]; divergence: string; contested?: boolean };
  figures: string[];
  era: string[];
  coreTenets: string[];
  keyThinkers: string[];
  historicalInstances?: string[];
  principalCritiques: string[];
  broadFamily?: boolean;
  flagged?: boolean;
};

export type Family = {
  slug: string;
  name: string;
  blurb: string;
  color: string;
  isms: Ism[];
  broadFamily?: boolean;
};

// ── SECTION A: SCHOOLS I — FOUNDATIONS TO MARGINALIST REVOLUTION ─────────────

// Family 1 — Precursors & Mercantilism
const PRECURSORS_FAMILY: Family = {
  slug: "precursors-mercantilism",
  name: "Precursors & Mercantilism",
  blurb: "Pre-classical economic thought: just price, bullionism, trade-balance doctrine, and the Physiocrats.",
  color: "stone",
  isms: [
    {
      name: "Political economy (the field)",
      description: "The study of production, distribution, and wealth in relation to law, custom, and government.",
      tags: ["c17", "c18", "meta"],
      tenet: "Economic life is inseparable from political authority, legal institutions, and social norms — it cannot be studied in isolation.",
      lineage: { parents: [], divergence: "root — the discipline itself, named by Montchretien (1615)" },
      figures: ["Antoine de Montchretien", "James Steuart", "Adam Smith"],
      era: ["c17", "c18"],
      coreTenets: [
        "Production and distribution of wealth are shaped by state policy, law, and social institutions.",
        "The economy is not a self-contained mechanism but embedded in political and moral life.",
        "Understanding wealth creation requires studying power, institutions, and collective choice.",
      ],
      keyThinkers: ["Antoine de Montchretien — Traite de l'oeconomie politique (1615)", "James Steuart — An Inquiry into the Principles of Political Oeconomy (1767)"],
      principalCritiques: [
        "Neoclassical economists argue the field evolved into a positive science ('economics') by shedding normative political entanglements.",
        "Marxians contend mainstream political economy naturalized capitalist relations rather than questioning them.",
      ],
      broadFamily: true,
    },
    {
      name: "Scholastic economic thought",
      description: "Medieval and early-modern theology applied to commerce: just price, usury prohibition, and natural law.",
      tags: ["medieval", "c16"],
      tenet: "Economic exchange is subject to moral law; prices must be just and lending at interest (usury) is sinful.",
      lineage: { parents: [], divergence: "root — Aristotelian-Thomistic natural-law reasoning applied to markets" },
      figures: ["Thomas Aquinas", "School of Salamanca", "Nicole Oresme"],
      era: ["medieval", "c16"],
      coreTenets: [
        "A just price reflects the cost of production and the common estimation of value, not mere bargaining power.",
        "Usury — charging interest on a loan of money — violates natural law because money is barren.",
        "Property is legitimate but subject to duties of charity and the common good.",
      ],
      keyThinkers: ["Thomas Aquinas — Summa Theologica (II-II, q.77-78)", "School of Salamanca — late Scholastic market analysis"],
      principalCritiques: [
        "Classical economists argued just-price doctrine inhibited market development and efficient resource allocation.",
        "Modern scholars note the Salamanca school anticipated much of marginal utility theory, complicating the 'backward Scholastics' narrative.",
      ],
    },
    {
      name: "Mercantilism",
      description: "National wealth equals accumulated bullion; maximize exports, minimize imports, and deploy state power to control trade.",
      tags: ["c16", "c17", "c18"],
      tenet: "National power depends on accumulating precious metals through a favorable balance of trade enforced by the state.",
      lineage: { parents: ["Scholastic economic thought"], divergence: "secularizes economic reasoning; shifts focus from moral law to state power and trade balance" },
      figures: ["Thomas Mun", "Jean-Baptiste Colbert", "Antonio Serra"],
      era: ["c16", "c17", "c18"],
      coreTenets: [
        "A nation's wealth is measured by its stock of gold and silver (bullion).",
        "Exports should exceed imports; tariffs, monopolies, and navigation acts enforce this balance.",
        "Colonial possessions supply raw materials and captive markets for the mother country.",
      ],
      keyThinkers: ["Thomas Mun — England's Treasure by Forraign Trade", "Jean-Baptiste Colbert — mercantilist statecraft under Louis XIV"],
      historicalInstances: ["Colbertism in France", "English Navigation Acts", "Spanish colonial bullion extraction"],
      principalCritiques: [
        "Adam Smith argued mercantilism confused money with wealth and that free trade benefits all parties (Wealth of Nations, Book IV).",
        "Physiocrats contended that agriculture, not trade surpluses, is the true source of national wealth.",
      ],
      broadFamily: true,
    },
    {
      name: "Bullionism",
      description: "Restrict gold and silver exports to keep specie within the realm.",
      tags: ["c16", "c17"],
      tenet: "The outflow of precious metals must be prohibited; national wealth is literally the bullion within the nation's borders.",
      lineage: { parents: ["Mercantilism"], divergence: "early, strict variant — focuses on direct control of specie flows rather than trade balance" },
      figures: ["Gerard de Malynes"],
      era: ["c16", "c17"],
      coreTenets: [
        "Gold and silver are the only true forms of wealth; their loss impoverishes the nation.",
        "Export of bullion should be banned or tightly controlled by royal decree.",
        "Foreign exchange manipulation by bankers drains specie and must be prevented.",
      ],
      keyThinkers: ["Gerard de Malynes — A Treatise of the Canker of Englands Common Wealth (1601)"],
      principalCritiques: [
        "Later mercantilists (Mun) argued that temporary bullion outflows could generate greater inflows through profitable trade.",
        "Classical economists demonstrated that specie flows are self-correcting via the price-specie flow mechanism (Hume).",
      ],
    },
    {
      name: "Cameralism",
      description: "German/Austrian science of state administration: maximize state revenue through systematic management of territory and population.",
      tags: ["c17", "c18"],
      tenet: "The state's administrative apparatus must systematically manage territory, population, and production to maximize fiscal revenue.",
      lineage: { parents: ["Mercantilism"], divergence: "Central European variant; adds bureaucratic-administrative science to mercantilist goals" },
      figures: ["Johann Heinrich Gottlob von Justi", "Joseph von Sonnenfels"],
      era: ["c17", "c18"],
      coreTenets: [
        "State revenue depends on the prosperity of the population; good administration creates wealth.",
        "Systematic data collection (statistics) enables rational management of economic resources.",
        "Police science (Polizeiwissenschaft) — the regulation of public order and welfare — is central to good governance.",
      ],
      keyThinkers: ["Johann Heinrich Gottlob von Justi — Staatswirthschaft", "Joseph von Sonnenfels — Grundsatze der Polizey"],
      historicalInstances: ["Prussian bureaucratic reforms", "Austrian Habsburg administrative modernization"],
      principalCritiques: [
        "Classical liberals argued cameralist state control stifled private enterprise and innovation.",
        "Physiocrats contended that the source of wealth lies in nature and agriculture, not administrative technique.",
      ],
    },
    {
      name: "Physiocracy",
      description: "Only agriculture produces net wealth; all other sectors are 'sterile.' Advocate laissez-faire and a single tax on land.",
      tags: ["c18"],
      tenet: "Agriculture is the sole source of net product (produit net); manufacturing and commerce merely transform or transport what the land creates.",
      lineage: { parents: ["Mercantilism"], divergence: "rejects trade-balance doctrine; locates wealth in land productivity, not bullion accumulation" },
      figures: ["Francois Quesnay", "Anne-Robert-Jacques Turgot", "Marquis de Mirabeau"],
      era: ["c18"],
      coreTenets: [
        "Only agriculture generates a net surplus above the costs of production (produit net).",
        "The Tableau economique traces the circular flow of income among landowners, farmers, and the 'sterile' class.",
        "A single tax on land rent (impot unique) should replace all other taxes, which burden productive activity.",
      ],
      keyThinkers: ["Francois Quesnay — Tableau economique (1758)", "Turgot — Reflections on the Formation and Distribution of Riches (1766)"],
      historicalInstances: ["Turgot's brief reform ministry under Louis XVI (1774-76)", "Physiocratic influence on early American agrarianism"],
      principalCritiques: [
        "Smith acknowledged the Physiocrats' circular-flow insight but rejected the claim that manufacturing is 'sterile.'",
        "Marxians noted the Physiocrats remained within the framework of landed aristocratic interests despite their analytical innovations.",
      ],
    },
    {
      name: "Neo-mercantilism",
      description: "Modern strategic trade policy: use state power to build national champions, manage trade, and secure supply chains.",
      tags: ["c20", "c21"],
      tenet: "States should use tariffs, subsidies, and industrial policy to build strategic industries and secure economic sovereignty.",
      lineage: { parents: ["Mercantilism"], divergence: "modern revival; applies mercantilist logic to high-tech competition and geopolitical rivalry" },
      figures: ["Friedrich List (proto)", "Ha-Joon Chang", "Robert Wade"],
      era: ["c20", "c21"],
      coreTenets: [
        "Free trade benefits those who are already industrialized; developing nations need protection to build capacity.",
        "Strategic industries (semiconductors, energy, defense) require state support because market failures are endemic.",
        "Supply-chain security and technological sovereignty are legitimate state objectives, not protectionist pretexts.",
      ],
      keyThinkers: ["Friedrich List — The National System of Political Economy (1841)", "Ha-Joon Chang — Kicking Away the Ladder (2002)"],
      historicalInstances: ["East Asian developmental states (Japan, South Korea, Taiwan)", "US CHIPS Act and industrial policy revival (2020s)", "Chinese 'Made in China 2025'"],
      principalCritiques: [
        "Free-trade economists argue neo-mercantilism invites retaliation, rent-seeking, and misallocation by politically captured bureaucracies.",
        "Liberals contend that picking winners through industrial policy historically produces more failures than successes.",
      ],
    },
  ],
};

// Family 2 — Classical Political Economy
const CLASSICAL_FAMILY: Family = {
  slug: "classical-political-economy",
  name: "Classical Political Economy",
  blurb: "Smith, Ricardo, Mill: labor value, free trade, and the laws of production and distribution.",
  color: "blue",
  broadFamily: true,
  isms: [
    {
      name: "Classical political economy",
      description: "The founding tradition: wealth comes from labor and production, not bullion; free markets coordinate via the price system.",
      tags: ["c18", "c19", "xref:economics"],
      tenet: "Wealth is the annual produce of land and labor, governed by natural laws of value, distribution, and accumulation.",
      lineage: { parents: ["Physiocracy", "Mercantilism"], divergence: "wealth is production, not bullion — rejects mercantilism; generalizes Physiocratic surplus beyond agriculture" },
      figures: ["Adam Smith", "David Ricardo", "John Stuart Mill", "Thomas Malthus"],
      era: ["c18", "c19"],
      coreTenets: [
        "Labor is the source and measure of value; the price of a commodity reflects the labor embodied in it.",
        "Free trade and the division of labor increase the wealth of nations by expanding markets and specialization.",
        "The natural tendency of profits, wages, and rents is governed by laws that political economy seeks to discover.",
      ],
      keyThinkers: ["Adam Smith — An Inquiry into the Nature and Causes of the Wealth of Nations (1776)", "David Ricardo — On the Principles of Political Economy and Taxation (1817)", "John Stuart Mill — Principles of Political Economy (1848)"],
      historicalInstances: ["Repeal of the Corn Laws (1846)", "British free-trade era (1846-1914)", "Classical liberal reform movements"],
      principalCritiques: [
        "Marx adopted the labor theory of value but argued classical economists naturalized capitalist exploitation rather than exposing it.",
        "Marginalists (Jevons, Menger, Walras) argued subjective utility, not embodied labor, determines value.",
      ],
      broadFamily: true,
    },
    {
      name: "The invisible hand",
      description: "Self-interested action in competitive markets generates socially beneficial outcomes without central direction.",
      tags: ["c18", "concept"],
      tenet: "Individuals pursuing their own interest are led, as if by an invisible hand, to promote the public good.",
      lineage: { parents: ["Classical political economy"], divergence: "Smith's metaphor for emergent market coordination; became a foundational concept of market liberalism" },
      figures: ["Adam Smith"],
      era: ["c18"],
      coreTenets: [
        "Market prices coordinate dispersed information better than any planner could.",
        "The pursuit of profit directs resources toward their most valued uses.",
        "State intervention is often unnecessary because market competition self-corrects.",
      ],
      keyThinkers: ["Adam Smith — Wealth of Nations, Book IV, Ch. 2"],
      principalCritiques: [
        "Market-failure theorists note externalities, public goods, and asymmetric information break the invisible-hand mechanism.",
        "Institutionalists argue the 'invisible hand' presupposes a legal and institutional framework that is itself a political creation.",
      ],
    },
    {
      name: "Division of labor",
      description: "Specialization of tasks increases productivity, skill, and output per worker.",
      tags: ["c18", "concept"],
      tenet: "The division of labor is the greatest source of productivity growth; its extent is limited by the extent of the market.",
      lineage: { parents: ["Classical political economy"], divergence: "Smith's opening analytical move in the Wealth of Nations; the pin-factory example" },
      figures: ["Adam Smith"],
      era: ["c18"],
      coreTenets: [
        "Breaking production into specialized tasks multiplies output per worker (the pin factory).",
        "Specialization develops skill, saves time, and encourages labor-saving invention.",
        "The extent of the division of labor is limited by the extent of the market — larger markets enable deeper specialization.",
      ],
      keyThinkers: ["Adam Smith — Wealth of Nations, Book I, Ch. 1-3"],
      principalCritiques: [
        "Marx argued the division of labor under capitalism alienates workers by reducing them to repetitive, meaningless tasks.",
        "Ecological economists note that extreme specialization creates fragile supply chains vulnerable to disruption.",
      ],
    },
    {
      name: "Labor theory of value (classical)",
      description: "The value of a commodity is determined by the quantity of labor required to produce it.",
      tags: ["c18", "c19", "concept"],
      tenet: "The natural price of a commodity is proportional to the labor time socially necessary for its production.",
      lineage: { parents: ["Classical political economy"], divergence: "core value theory of the classical school; later taken up and transformed by Marx" },
      figures: ["Adam Smith", "David Ricardo"],
      era: ["c18", "c19"],
      coreTenets: [
        "Labor is the real measure of the exchangeable value of all commodities (Smith).",
        "Relative prices in the long run reflect relative labor costs of production (Ricardo).",
        "Rent does not enter into price determination; it is a residual paid to land of differential fertility.",
      ],
      keyThinkers: ["Adam Smith — Wealth of Nations, Book I, Ch. 5-6", "David Ricardo — Principles, Ch. 1"],
      principalCritiques: [
        "Marginalists argued value is determined by subjective utility at the margin, not by embodied labor.",
        "The transformation problem shows difficulties in converting labor values to market prices when capital intensity varies across industries.",
      ],
    },
    {
      name: "Comparative advantage",
      description: "Nations benefit from trade by specializing in goods they produce at lowest relative cost, even if absolutely less efficient.",
      tags: ["c19", "concept", "xref:economics"],
      tenet: "Trade is mutually beneficial when each country specializes in goods where its opportunity cost is lowest: a_L1^A/a_L2^A < a_L1^B/a_L2^B.",
      lineage: { parents: ["Classical political economy"], divergence: "Ricardo's trade theory; demonstrates gains from trade even for absolutely less productive nations" },
      figures: ["David Ricardo"],
      era: ["c19"],
      coreTenets: [
        "Even a nation that is less efficient at producing everything can gain from trade by specializing in its least-disadvantaged sector.",
        "Opportunity cost, not absolute productivity, determines the pattern of trade.",
        "Free trade increases total world output by allowing each nation to specialize according to its comparative advantage.",
      ],
      keyThinkers: ["David Ricardo — Principles, Ch. 7 (the Portugal-England cloth-wine example)"],
      principalCritiques: [
        "Development economists (List, Chang) argue comparative advantage can lock poor nations into low-value commodity exports.",
        "Critics note the model assumes full employment, factor immobility between nations, and no increasing returns — assumptions often violated.",
      ],
    },
    {
      name: "Say's law",
      description: "Supply creates its own demand: production of goods generates sufficient income to purchase them.",
      tags: ["c19", "concept"],
      tenet: "Products are ultimately paid for by other products; aggregate demand cannot persistently fall short of aggregate supply.",
      lineage: { parents: ["Classical political economy"], divergence: "Say's formulation of classical equilibrium; denied the possibility of general gluts" },
      figures: ["Jean-Baptiste Say"],
      era: ["c19"],
      coreTenets: [
        "Production creates the income necessary to purchase what is produced.",
        "General overproduction is impossible in a barter economy; money is merely a veil.",
        "Partial gluts (sectoral imbalances) are possible, but aggregate demand equals aggregate supply.",
      ],
      keyThinkers: ["Jean-Baptiste Say — A Treatise on Political Economy (1803)"],
      principalCritiques: [
        "Keynes made the rejection of Say's law the central proposition of the General Theory — effective demand can fall short, causing involuntary unemployment.",
        "Malthus argued against Say's law in his own time, warning of the possibility of general gluts from insufficient demand.",
      ],
    },
    {
      name: "Malthusian population principle",
      description: "Population grows geometrically, food arithmetically; living standards tend toward subsistence.",
      tags: ["c18", "c19", "concept"],
      tenet: "Population tends to grow faster than the food supply, pressing living standards toward the subsistence level unless checked.",
      lineage: { parents: ["Classical political economy"], divergence: "Malthus's demographic pessimism; challenged Enlightenment optimism about human progress" },
      figures: ["Thomas Robert Malthus"],
      era: ["c18", "c19"],
      coreTenets: [
        "Population, when unchecked, increases geometrically; food supply increases only arithmetically.",
        "Preventive checks (delayed marriage, moral restraint) and positive checks (famine, disease, war) keep population within resource limits.",
        "Poor relief encourages population growth and worsens poverty rather than relieving it.",
      ],
      keyThinkers: ["Thomas Robert Malthus — An Essay on the Principle of Population (1798)"],
      principalCritiques: [
        "The demographic transition in industrialized countries falsified the prediction: rising incomes led to lower, not higher, birth rates.",
        "Marx attacked Malthus for naturalizing poverty as a biological inevitability rather than a product of capitalist relations.",
      ],
    },
    {
      name: "Ricardian rent",
      description: "Rent arises from differences in land fertility; it is a residual, not a cause of price.",
      tags: ["c19", "concept"],
      tenet: "Rent is paid for the use of the original and indestructible powers of the soil; it arises from differential fertility, not from price.",
      lineage: { parents: ["Classical political economy"], divergence: "Ricardo's theory of differential rent; rent is price-determined, not price-determining" },
      figures: ["David Ricardo"],
      era: ["c19"],
      coreTenets: [
        "Rent is the difference between the produce of a given plot and that of the marginal (no-rent) land.",
        "As population grows, inferior land is brought into cultivation, raising rent on superior land.",
        "Rent does not enter into the cost of production; it is a surplus appropriated by landowners.",
      ],
      keyThinkers: ["David Ricardo — Principles, Ch. 2"],
      principalCritiques: [
        "Henry George extended Ricardian rent to justify taxing all land rent as socially created surplus.",
        "Neoclassical economists generalized the rent concept beyond land to any factor earning above its opportunity cost.",
      ],
    },
    {
      name: "Classical stationary state",
      description: "The long-run tendency of the economy toward zero growth as profits fall and population reaches subsistence.",
      tags: ["c19", "concept"],
      tenet: "Capital accumulation drives profits to a minimum; the economy tends toward a stationary state of zero net investment.",
      lineage: { parents: ["Classical political economy"], divergence: "the classical pessimistic long-run forecast; Smith, Ricardo, and Mill all discussed it" },
      figures: ["Adam Smith", "David Ricardo", "John Stuart Mill"],
      era: ["c19"],
      coreTenets: [
        "As capital accumulates and population grows, the rate of profit tends to fall toward zero.",
        "The stationary state is the natural end-point of economic growth in a finite world.",
        "Mill argued the stationary state need not be dreaded — it could permit focus on distribution, culture, and quality of life.",
      ],
      keyThinkers: ["John Stuart Mill — Principles, Book IV, Ch. 6 ('Of the Stationary State')"],
      principalCritiques: [
        "Technological progress, which the classical economists underestimated, has repeatedly postponed the stationary state.",
        "Ecological economists (Daly) have revived the concept as a desirable goal — steady-state economics — rather than a pessimistic forecast.",
      ],
    },
    {
      name: "Wages-fund doctrine",
      description: "Total wages are paid from a pre-existing fund of capital; workers compete for a fixed pool.",
      tags: ["c19", "concept"],
      tenet: "A fixed fund of capital is set aside for wages each period; the average wage equals the fund divided by the number of workers.",
      lineage: { parents: ["Classical political economy"], divergence: "classical theory of wage determination; implied trade unions could not raise wages above the fund" },
      figures: ["John Stuart Mill", "Nassau Senior"],
      era: ["c19"],
      coreTenets: [
        "Wages are paid out of capital previously accumulated, not out of current revenue.",
        "The average wage is determined by the ratio of the wages fund to the number of workers.",
        "Trade unions cannot raise wages above this ratio without reducing employment.",
      ],
      keyThinkers: ["John Stuart Mill — Principles (later recanted the doctrine in 1869)"],
      principalCritiques: [
        "Mill himself retracted the wages-fund doctrine, conceding that wages could be influenced by bargaining power and institutions.",
        "Marginalists replaced the wages fund with marginal productivity theory as the basis for wage determination.",
      ],
    },
    {
      name: "Classical liberalism (economic)",
      description: "Free markets, free trade, and minimal state intervention in the economy.",
      tags: ["c18", "c19", "xref:ideologies"],
      tenet: "The state should confine itself to protecting property, enforcing contracts, and providing public goods; markets should otherwise be left free.",
      lineage: { parents: ["Classical political economy"], divergence: "the policy programme derived from classical economic theory; overlaps with political liberalism [xref: ideologies]" },
      figures: ["Adam Smith", "David Ricardo", "Richard Cobden", "Frederic Bastiat"],
      era: ["c18", "c19"],
      coreTenets: [
        "Free trade benefits all nations by allowing specialization according to comparative advantage.",
        "State monopolies, tariffs, and regulations distort prices and reduce welfare.",
        "Property rights and contract enforcement are the essential institutional foundations of a market economy.",
      ],
      keyThinkers: ["Adam Smith — Wealth of Nations", "Frederic Bastiat — Economic Harmonies"],
      historicalInstances: ["British free-trade era after Corn Law repeal (1846)", "Cobden-Chevalier Treaty (1860)", "19th-century liberal reform movements"],
      principalCritiques: [
        "Socialists argued classical economic liberalism served the interests of the industrial bourgeoisie while impoverishing workers.",
        "Historical-school economists (List) argued free-trade doctrine was suited to already-industrialized Britain but destructive for developing nations.",
      ],
    },
    {
      name: "Utilitarianism in political economy",
      description: "The greatest happiness of the greatest number as the criterion for economic policy.",
      tags: ["c18", "c19", "concept"],
      tenet: "Economic institutions and policies should be judged by their contribution to the greatest happiness of the greatest number.",
      lineage: { parents: ["Classical political economy"], divergence: "Bentham's normative framework adopted by Mill and welfare economics; bridges ethics and policy" },
      figures: ["Jeremy Bentham", "John Stuart Mill"],
      era: ["c18", "c19"],
      coreTenets: [
        "The standard of right action is the maximization of aggregate utility (pleasure minus pain).",
        "Economic policy should be evaluated by its consequences for total welfare, not by adherence to natural rights.",
        "Redistribution is justified when it increases total utility (diminishing marginal utility of income).",
      ],
      keyThinkers: ["Jeremy Bentham — An Introduction to the Principles of Morals and Legislation (1789)", "John Stuart Mill — Utilitarianism (1863)"],
      principalCritiques: [
        "Rawlsians argue utilitarianism can justify sacrificing individuals' rights for aggregate welfare.",
        "Austrian economists reject interpersonal utility comparisons as scientifically meaningless.",
      ],
    },
  ],
};

// Family 3 — Marxian & Radical
const MARXIAN_FAMILY: Family = {
  slug: "marxian-radical",
  name: "Marxian & Radical Political Economy",
  blurb: "Critique of capitalism through the labor theory of value, surplus extraction, and historical materialism.",
  color: "red",
  broadFamily: true,
  isms: [
    {
      name: "Marxian political economy",
      description: "Capitalism is a historically specific mode of production based on the exploitation of wage labor by capital.",
      tags: ["c19", "c20", "xref:ideologies"],
      tenet: "Capitalism extracts surplus value from workers; its internal contradictions drive crises and historical transformation.",
      lineage: { parents: ["Classical political economy"], divergence: "labor value becomes critique of capital — adopts and radicalizes classical value theory to expose exploitation" },
      figures: ["Karl Marx", "Friedrich Engels"],
      era: ["c19"],
      coreTenets: [
        "The value of a commodity is determined by the socially necessary labor time required for its production.",
        "Profit arises from surplus value — the difference between what workers produce and what they are paid.",
        "Capitalism's inherent contradictions (falling profit rate, overproduction, concentration) generate recurrent crises.",
      ],
      keyThinkers: ["Karl Marx — Capital, Volumes I-III (1867-94)", "Friedrich Engels — Anti-Duhring (1878)"],
      historicalInstances: ["Paris Commune (1871)", "Russian Revolution (1917)", "Marxian influence on labor movements worldwide"],
      principalCritiques: [
        "Marginalists argued Marx's labor theory of value was superseded by subjective utility theory.",
        "Bohm-Bawerk's critique identified logical problems in the transformation of values into prices (transformation problem).",
        "Empirically, predicted immiseration of the proletariat did not materialize in advanced capitalist countries.",
      ],
      broadFamily: true,
    },
    {
      name: "Labor theory of value (Marxian)",
      description: "The value of a commodity equals constant capital (c) plus variable capital (v) plus surplus value (s): W = c + v + s.",
      tags: ["c19", "concept"],
      tenet: "Commodity value decomposes into constant capital, variable capital, and surplus value: W = c + v + s.",
      lineage: { parents: ["Marxian political economy", "Labor theory of value (classical)"], divergence: "transforms classical labor value into a theory of exploitation; introduces surplus value as the source of profit" },
      figures: ["Karl Marx"],
      era: ["c19"],
      coreTenets: [
        "Constant capital (c) is the value of means of production consumed; it transfers value but creates none.",
        "Variable capital (v) is the value of labor power; workers create more value than they receive as wages.",
        "Surplus value (s) is the unpaid labor appropriated by the capitalist — the source of profit, rent, and interest.",
      ],
      keyThinkers: ["Karl Marx — Capital, Volume I, Parts 3-5"],
      principalCritiques: [
        "Bohm-Bawerk argued Marx's value theory was internally inconsistent, especially in the transformation to prices of production.",
        "Sraffa showed that relative prices can be determined without any reference to labor values, making them theoretically redundant.",
      ],
    },
    {
      name: "Surplus value",
      description: "The value produced by workers above what they receive as wages; the source of capitalist profit.",
      tags: ["c19", "concept"],
      tenet: "The rate of exploitation e = s/v measures the ratio of unpaid to paid labor — the degree of capitalist extraction.",
      lineage: { parents: ["Labor theory of value (Marxian)"], divergence: "Marx's central analytical concept; transforms the classical 'profits' into a theory of class exploitation" },
      figures: ["Karl Marx"],
      era: ["c19"],
      coreTenets: [
        "Workers sell their labor power at its value (subsistence) but produce value exceeding that amount.",
        "Absolute surplus value is increased by lengthening the working day; relative surplus value by raising productivity.",
        "The rate of surplus value (e = s/v) is the fundamental measure of exploitation in capitalism.",
      ],
      keyThinkers: ["Karl Marx — Capital, Volume I, Chapters 7-9"],
      principalCritiques: [
        "Neoclassical economists argue profit is the return to capital and entrepreneurship, not unpaid labor.",
        "Analytical Marxists (Roemer) reconstructed exploitation theory without relying on the labor theory of value.",
      ],
    },
    {
      name: "Tendency of the rate of profit to fall",
      description: "As capital intensity rises, the rate of profit tends to decline: r = s/(c+v).",
      tags: ["c19", "concept"],
      tenet: "The organic composition of capital rises over time, tending to reduce the rate of profit: r = s/(c + v).",
      lineage: { parents: ["Marxian political economy"], divergence: "Marx's crisis theory; connects technological change to systemic instability" },
      figures: ["Karl Marx"],
      era: ["c19"],
      coreTenets: [
        "Capitalists replace living labor with machinery, raising the organic composition of capital (c/v).",
        "Since only living labor creates surplus value, the rate of profit r = s/(c+v) tends to fall.",
        "Counteracting tendencies (intensified exploitation, cheaper inputs, foreign trade) delay but cannot permanently prevent the decline.",
      ],
      keyThinkers: ["Karl Marx — Capital, Volume III, Part 3"],
      principalCritiques: [
        "The Okishio theorem (1961) showed that cost-reducing technical change raises, not lowers, the equilibrium profit rate under competition.",
        "Empirical evidence on long-run profit trends is contested; some periods show rising, others falling rates.",
      ],
    },
    {
      name: "Transformation problem",
      description: "The unresolved difficulty of converting Marx's labor values into observable market prices of production.",
      tags: ["c19", "c20", "concept"],
      tenet: "Marx's procedure for transforming values into prices of production is internally inconsistent — a problem that remains contested.",
      lineage: { parents: ["Labor theory of value (Marxian)"], divergence: "identified by Bohm-Bawerk and formalized by Bortkiewicz; central to debates over Marx's value theory", contested: true },
      figures: ["Karl Marx", "Eugen von Bohm-Bawerk", "Ladislaus von Bortkiewicz"],
      era: ["c19", "c20"],
      coreTenets: [
        "Marx's Volume III transformation fails to simultaneously transform inputs and outputs from values to prices.",
        "Bortkiewicz (1907) showed a corrected transformation, but it alters Marx's aggregate equalities.",
        "The 'new interpretation' (Dumenil, Foley) and 'temporal single-system' (TSSI) approaches claim to resolve the problem.",
      ],
      keyThinkers: ["Bohm-Bawerk — Karl Marx and the Close of His System (1896)", "Ladislaus von Bortkiewicz — correction (1907)", "Dumenil & Foley — new interpretation"],
      principalCritiques: [
        "Sraffians argue the transformation problem shows labor values are theoretically unnecessary — prices can be determined directly from technology and distribution.",
        "TSSI advocates (Kliman, Freeman) argue the problem is an artifact of simultaneous valuation and vanishes under temporal accounting.",
      ],
      flagged: true,
    },
    {
      name: "Historical materialism",
      description: "The mode of production determines the social, political, and intellectual life of an epoch.",
      tags: ["c19", "concept", "xref:ideologies"],
      tenet: "The economic base — forces and relations of production — shapes the political and ideological superstructure of society.",
      lineage: { parents: ["Marxian political economy"], divergence: "Marx's theory of history; the methodological foundation of Marxian social science" },
      figures: ["Karl Marx", "Friedrich Engels"],
      era: ["c19"],
      coreTenets: [
        "History progresses through modes of production (feudalism, capitalism, socialism), each with characteristic class conflicts.",
        "When the forces of production outgrow the existing relations of production, social revolution occurs.",
        "Law, politics, religion, and philosophy are part of the superstructure, shaped by the economic base.",
      ],
      keyThinkers: ["Karl Marx — Preface to A Contribution to the Critique of Political Economy (1859)", "Friedrich Engels — The Origin of the Family, Private Property and the State"],
      principalCritiques: [
        "Weber argued that ideas (e.g., the Protestant ethic) can independently shape economic development, contra base-superstructure determinism.",
        "Analytical Marxists (Cohen) formalized historical materialism but acknowledged its predictive limitations.",
      ],
    },
    {
      name: "Primitive accumulation",
      description: "The violent, non-market origins of capitalism: enclosure, colonialism, and dispossession created the proletariat.",
      tags: ["c19", "concept"],
      tenet: "Capitalism did not arise from voluntary exchange but from the forcible separation of producers from their means of production.",
      lineage: { parents: ["Marxian political economy"], divergence: "Marx's critique of the 'so-called original accumulation'; reveals the violent prehistory of capital" },
      figures: ["Karl Marx"],
      era: ["c19"],
      coreTenets: [
        "The enclosure of common lands dispossessed peasants, creating a propertyless class forced to sell its labor.",
        "Colonialism, slavery, and plunder provided the capital that financed early industrialization.",
        "The 'free' labor market presupposed by classical economics was itself created by coercion.",
      ],
      keyThinkers: ["Karl Marx — Capital, Volume I, Part 8"],
      principalCritiques: [
        "Liberal historians argue capitalism also arose from voluntary innovation, trade expansion, and institutional evolution.",
        "David Harvey's concept of 'accumulation by dispossession' extends primitive accumulation to ongoing processes in contemporary capitalism.",
      ],
    },
    {
      name: "Commodity fetishism",
      description: "Social relations between people appear as relations between things; the market conceals exploitation.",
      tags: ["c19", "concept"],
      tenet: "In capitalism, social relations of production take on the fantastic form of relations between commodities, concealing the human labor behind them.",
      lineage: { parents: ["Marxian political economy"], divergence: "Marx's theory of ideological mystification built into the commodity form itself" },
      figures: ["Karl Marx"],
      era: ["c19"],
      coreTenets: [
        "Commodities appear to have value as a natural property, obscuring the social labor that actually creates value.",
        "Market exchange presents social relations as impersonal 'laws' of supply and demand.",
        "Fetishism is not a psychological error but a structural feature of commodity-producing societies.",
      ],
      keyThinkers: ["Karl Marx — Capital, Volume I, Chapter 1, Section 4"],
      principalCritiques: [
        "Analytical Marxists question whether 'fetishism' adds explanatory power beyond standard ideology critique.",
        "Postmodernists extended commodity fetishism into cultural theory (Debord's 'spectacle') but arguably diluted its economic content.",
      ],
    },
    {
      name: "Reproduction schemes and crisis theory",
      description: "Marx's models of simple and expanded reproduction show how capitalist accumulation generates disproportionalities and crises.",
      tags: ["c19", "concept"],
      tenet: "Capitalist reproduction requires proportionality between departments of production that the anarchy of the market cannot guarantee.",
      lineage: { parents: ["Marxian political economy"], divergence: "Marx's Volume II analysis of the circulation of capital; foundation for later crisis theories" },
      figures: ["Karl Marx", "Rosa Luxemburg"],
      era: ["c19"],
      coreTenets: [
        "Simple reproduction reproduces the class structure exactly; expanded reproduction requires surplus value to be reinvested.",
        "The two-department model (means of production / means of consumption) reveals balance conditions for crisis-free growth.",
        "Overproduction, underconsumption, and disproportionality between departments are endemic sources of crisis.",
      ],
      keyThinkers: ["Karl Marx — Capital, Volume II, Part 3", "Rosa Luxemburg — The Accumulation of Capital (1913)"],
      principalCritiques: [
        "Luxemburg argued expanded reproduction requires non-capitalist markets for realization — generating imperialism.",
        "Tugan-Baranovsky and later Bortkiewicz showed balanced growth is theoretically possible, undercutting underconsumptionist readings.",
      ],
    },
    {
      name: "Monopoly capital and imperialism",
      description: "Capitalism evolves from competitive to monopoly stage; surplus absorption and imperial expansion follow.",
      tags: ["c20", "concept"],
      tenet: "The concentration of capital produces monopolies, surplus absorption problems, and the export of capital to the periphery.",
      lineage: { parents: ["Marxian political economy"], divergence: "Lenin and the Monthly Review school extend Marx to the age of corporations and empire" },
      figures: ["V.I. Lenin", "Rudolf Hilferding", "Paul Baran", "Paul Sweezy"],
      era: ["c20"],
      coreTenets: [
        "Capitalism's competitive phase gives way to monopoly capitalism, dominated by giant corporations and finance capital.",
        "Monopoly generates chronic surplus that cannot be profitably absorbed domestically.",
        "Imperial expansion, militarism, and waste (advertising, financial speculation) are mechanisms for absorbing the surplus.",
      ],
      keyThinkers: ["V.I. Lenin — Imperialism, the Highest Stage of Capitalism (1917)", "Baran & Sweezy — Monopoly Capital (1966)"],
      historicalInstances: ["European colonial empires (19th-20th century)", "US military-industrial complex"],
      principalCritiques: [
        "Schumpeter argued monopoly is temporary because innovation ('creative destruction') continually erodes market power.",
        "Neoclassical economists contend that antitrust policy, not socialist revolution, is the appropriate remedy for monopoly.",
      ],
    },
    {
      name: "Analytical Marxism",
      description: "Reconstruct Marxian claims using the tools of mainstream social science: rational choice, game theory, and formal logic.",
      tags: ["c20", "c21"],
      tenet: "Marxian insights about exploitation, class, and history can and should be reconstructed using rigorous analytical methods.",
      lineage: { parents: ["Marxian political economy"], divergence: "abandons dialectics and the labor theory of value; retains exploitation and class analysis in formal frameworks" },
      figures: ["G.A. Cohen", "John Roemer", "Erik Olin Wright", "Jon Elster"],
      era: ["c20", "c21"],
      coreTenets: [
        "Exploitation can be defined without the labor theory of value — as unequal exchange of labor for goods (Roemer).",
        "Historical materialism should be stated as testable functional explanations (Cohen).",
        "Marxian class analysis benefits from rational-choice microfoundations rather than dialectical holism.",
      ],
      keyThinkers: ["G.A. Cohen — Karl Marx's Theory of History: A Defence (1978)", "John Roemer — A General Theory of Exploitation and Class (1982)"],
      principalCritiques: [
        "Traditional Marxists argue analytical Marxism strips Marxism of its dialectical method and revolutionary purpose.",
        "Mainstream economists question whether the reconstructed theories add anything not already captured by welfare economics.",
      ],
    },
    {
      name: "Sraffian / neo-Ricardian economics",
      description: "Determine prices and the profit rate from technology and distribution alone, without subjective value theory.",
      tags: ["c20"],
      tenet: "Relative prices and the rate of profit can be determined from the physical conditions of production and one distributive variable, without recourse to either labor values or marginal utility.",
      lineage: { parents: ["Classical political economy", "Marxian political economy"], divergence: "Sraffa revives Ricardian surplus theory in a mathematical framework that challenges both Marx and neoclassical economics" },
      figures: ["Piero Sraffa"],
      era: ["c20"],
      coreTenets: [
        "Given technology (input-output coefficients) and either the wage or the profit rate, all prices are determined.",
        "The standard commodity provides an invariable measure of value, resolving Ricardo's search for a standard.",
        "Capital cannot be measured independently of prices and distribution — undermining the neoclassical aggregate production function.",
      ],
      keyThinkers: ["Piero Sraffa — Production of Commodities by Means of Commodities (1960)"],
      principalCritiques: [
        "Neoclassical economists argue Sraffa's framework lacks a theory of output determination and demand.",
        "Marxians debate whether Sraffa's surplus approach supports or undermines the labor theory of value.",
      ],
    },
    {
      name: "Cambridge capital controversy",
      description: "The debate over whether 'capital' can be consistently measured and aggregated — the two Cambridges reached no resolution.",
      tags: ["c20", "concept"],
      tenet: "Capital cannot be measured as a single aggregate independently of the rate of profit — the neoclassical production function is logically flawed.",
      lineage: { parents: ["Sraffian / neo-Ricardian economics"], divergence: "the 1950s-60s debate between Cambridge UK (Robinson, Sraffa) and Cambridge MA (Samuelson, Solow)", contested: true },
      figures: ["Joan Robinson", "Piero Sraffa", "Paul Samuelson", "Robert Solow"],
      era: ["c20"],
      coreTenets: [
        "Reswitching and capital reversal show that the same technique can be profit-maximizing at two different interest rates.",
        "The aggregate production function Y = f(K,L) presupposes what it claims to prove: that capital has a well-defined marginal product.",
        "Samuelson conceded the logical point but the profession continued using aggregate production functions.",
      ],
      keyThinkers: ["Joan Robinson — The Accumulation of Capital (1956)", "Paul Samuelson — 'A Summing Up' (1966, QJE)"],
      principalCritiques: [
        "Mainstream economists argue reswitching is empirically rare and aggregate production functions work well enough in practice.",
        "Post-Keynesians and Sraffians argue the profession's continued use of aggregate production functions is intellectually dishonest.",
      ],
      flagged: true,
    },
  ],
};

// Family 4 — Neoclassical & Marginalist
const NEOCLASSICAL_FAMILY: Family = {
  slug: "neoclassical-marginalist",
  name: "Neoclassical & Marginalist",
  blurb: "The marginalist revolution: subjective value, marginal analysis, equilibrium, and the Chicago school.",
  color: "indigo",
  broadFamily: true,
  isms: [
    {
      name: "Neoclassical economics",
      description: "The dominant paradigm since the late 19th century: rational agents, marginal analysis, and equilibrium.",
      tags: ["c19", "c20", "xref:economics"],
      tenet: "Economic outcomes result from rational agents maximizing utility and profit at the margin, reaching equilibrium through the price mechanism.",
      lineage: { parents: ["Classical political economy"], divergence: "marginal utility replaces labor value — shifts the basis of value from objective labor cost to subjective marginal utility" },
      figures: ["William Stanley Jevons", "Leon Walras", "Alfred Marshall", "Vilfredo Pareto"],
      era: ["c19", "c20"],
      coreTenets: [
        "Value is determined by marginal utility — the satisfaction from the last unit consumed — not by labor content.",
        "Markets tend toward equilibrium where supply equals demand at each margin.",
        "Economic analysis should be positive (descriptive) rather than normative, using mathematical formalization.",
      ],
      keyThinkers: ["Alfred Marshall — Principles of Economics (1890)", "Leon Walras — Elements of Pure Economics (1874)"],
      principalCritiques: [
        "Heterodox economists argue neoclassical assumptions (perfect rationality, complete markets, equilibrium) are empirically implausible.",
        "Institutional and behavioral economists contend real agents use heuristics, face bounded rationality, and operate in institutions that shape outcomes.",
      ],
      broadFamily: true,
    },
    {
      name: "Marginalist revolution (1870s)",
      description: "The near-simultaneous discovery by Jevons, Menger, and Walras that value depends on marginal utility.",
      tags: ["c19", "concept"],
      tenet: "Value is determined at the margin: the utility of the last unit consumed, not total utility or embodied labor, sets the price.",
      lineage: { parents: ["Classical political economy"], divergence: "breaks with the classical labor theory of value; three independent discoverers (Jevons, Menger, Walras) converge on marginalism" },
      figures: ["William Stanley Jevons", "Carl Menger", "Leon Walras"],
      era: ["c19"],
      coreTenets: [
        "The 'marginal revolution' resolved the diamond-water paradox by distinguishing total from marginal utility.",
        "Mathematical optimization at the margin became the central analytical tool of economics.",
        "The classical cost-of-production theory of value was replaced by a unified theory based on subjective valuation.",
      ],
      keyThinkers: ["Jevons — The Theory of Political Economy (1871)", "Menger — Grundsatze der Volkswirthschaftslehre (1871)", "Walras — Elements d'economie politique pure (1874)"],
      principalCritiques: [
        "Marxians argue the marginalist revolution was ideologically motivated — it eliminated the labor theory of value and its critique of exploitation.",
        "Institutionalists note that marginal analysis works only under assumptions (continuity, divisibility, perfect information) that rarely hold.",
      ],
    },
    {
      name: "Marginal utility",
      description: "The additional satisfaction from consuming one more unit of a good; the basis of demand theory.",
      tags: ["c19", "concept", "xref:economics"],
      tenet: "The value of a good to a consumer equals the utility of the last (marginal) unit; utility diminishes with each additional unit.",
      lineage: { parents: ["Marginalist revolution (1870s)"], divergence: "the core concept of the marginalist revolution; replaces labor value as the theory of demand" },
      figures: ["William Stanley Jevons", "Carl Menger", "Leon Walras"],
      era: ["c19"],
      coreTenets: [
        "Rational consumers equalize the marginal utility per unit of expenditure across all goods.",
        "Diminishing marginal utility explains why demand curves slope downward.",
        "Consumer surplus is the difference between total utility and what is actually paid.",
      ],
      keyThinkers: ["Jevons — The Theory of Political Economy (1871)", "Alfred Marshall — Principles (consumer surplus analysis)"],
      principalCritiques: [
        "Ordinal utility theory (Pareto, Hicks) showed that cardinal measurement of utility is unnecessary; only rankings matter.",
        "Behavioral economists demonstrate systematic violations of diminishing marginal utility assumptions (loss aversion, reference dependence).",
      ],
    },
    {
      name: "Marginal productivity theory of distribution",
      description: "Each factor of production is paid its marginal product: w = P * MPL.",
      tags: ["c19", "c20", "concept", "xref:economics"],
      tenet: "In competitive equilibrium, each factor of production (labor, capital, land) receives its marginal product: w = P * MPL.",
      lineage: { parents: ["Neoclassical economics"], divergence: "extends marginalism to distribution; replaces classical theories of rent, wages, and profit with a unified marginal framework" },
      figures: ["John Bates Clark", "Philip Wicksteed"],
      era: ["c19", "c20"],
      coreTenets: [
        "The wage equals the marginal product of labor; the interest rate equals the marginal product of capital.",
        "If all factors are paid their marginal products, total output is exactly exhausted (Euler's theorem under constant returns to scale).",
        "Factor pricing by marginal productivity is both efficient and, Clark argued, ethically just.",
      ],
      keyThinkers: ["John Bates Clark — The Distribution of Wealth (1899)", "Philip Wicksteed — An Essay on the Co-ordination of the Laws of Distribution (1894)"],
      principalCritiques: [
        "The Cambridge capital controversy showed that capital's marginal product cannot be defined independently of the profit rate.",
        "Institutionalists and Marxians argue wages are determined by bargaining power and institutions, not marginal products.",
      ],
    },
    {
      name: "Marshallian supply and demand",
      description: "Price is determined by the intersection of supply and demand curves — the 'scissors' of partial equilibrium.",
      tags: ["c19", "concept", "xref:economics"],
      tenet: "Market price is determined by the intersection of supply and demand, like the two blades of a pair of scissors. [xref: economics]",
      lineage: { parents: ["Neoclassical economics"], divergence: "Marshall's partial equilibrium framework; the workhorse tool of applied microeconomics" },
      figures: ["Alfred Marshall"],
      era: ["c19"],
      coreTenets: [
        "Supply and demand jointly determine price; neither alone is sufficient (the 'scissors' metaphor).",
        "Short-run prices are demand-dominated; long-run prices tend toward the cost of production (supply-dominated).",
        "Consumer and producer surplus measure the welfare gains from trade in a market.",
      ],
      keyThinkers: ["Alfred Marshall — Principles of Economics (1890)"],
      principalCritiques: [
        "General equilibrium theorists (Walras) argue partial equilibrium ignores interdependencies across markets.",
        "Post-Keynesians argue supply curves are often flat (constant costs) in manufacturing, making supply-demand 'scissors' misleading.",
      ],
    },
    {
      name: "General equilibrium",
      description: "All markets clear simultaneously; the Walrasian system of simultaneous equations for all prices and quantities.",
      tags: ["c19", "c20", "concept", "xref:economics"],
      tenet: "A set of prices exists that simultaneously clears all markets, determining all outputs, inputs, and trade flows. [xref: economics]",
      lineage: { parents: ["Neoclassical economics"], divergence: "Walras's vision of the entire economy as a system of simultaneous equations; formalized by Arrow and Debreu" },
      figures: ["Leon Walras", "Kenneth Arrow", "Gerard Debreu"],
      era: ["c19", "c20"],
      coreTenets: [
        "In a competitive economy with complete markets, a general equilibrium exists (Arrow-Debreu, 1954).",
        "Equilibrium prices convey all the information agents need for efficient resource allocation.",
        "General equilibrium provides the theoretical foundation for the welfare theorems.",
      ],
      keyThinkers: ["Leon Walras — Elements of Pure Economics", "Arrow & Debreu — 'Existence of Equilibrium for a Competitive Economy' (1954)"],
      principalCritiques: [
        "Sonnenschein-Mantel-Debreu results show that general equilibrium imposes almost no restrictions on aggregate demand, undermining its predictive power.",
        "Post-Keynesians and complexity economists argue general equilibrium is a mathematical artifact with no empirical counterpart.",
      ],
    },
    {
      name: "Welfare theorems",
      description: "The two fundamental theorems linking competitive equilibria to Pareto efficiency.",
      tags: ["c20", "concept", "xref:economics"],
      tenet: "Every competitive equilibrium is Pareto efficient (First Theorem); every Pareto-efficient allocation can be supported as a competitive equilibrium with appropriate redistribution (Second Theorem). [xref: economics]",
      lineage: { parents: ["General equilibrium"], divergence: "normative foundation of neoclassical welfare economics; connects efficiency to competitive markets" },
      figures: ["Kenneth Arrow", "Gerard Debreu"],
      era: ["c20"],
      coreTenets: [
        "First Theorem: a competitive equilibrium, if it exists, is Pareto efficient.",
        "Second Theorem: any desired Pareto-efficient allocation can be achieved through lump-sum transfers and market exchange.",
        "The theorems provide the intellectual foundation for free-market policy — and for redistribution-then-market solutions.",
      ],
      keyThinkers: ["Arrow — 'An Extension of the Basic Theorems of Classical Welfare Economics' (1951)", "Debreu — Theory of Value (1959)"],
      principalCritiques: [
        "The theorems require complete markets, no externalities, perfect competition, and lump-sum transfers — conditions rarely met.",
        "Amartya Sen argued Pareto efficiency is a weak criterion that can coexist with extreme inequality and deprivation.",
      ],
    },
    {
      name: "Pigouvian welfare economics",
      description: "Externalities justify corrective taxes or subsidies; the gap between private and social cost requires state intervention.",
      tags: ["c20", "concept"],
      tenet: "When private costs diverge from social costs, a corrective tax (or subsidy) can restore efficiency.",
      lineage: { parents: ["Neoclassical economics"], divergence: "Pigou's market-failure framework; provided the intellectual foundation for environmental and public-health regulation" },
      figures: ["Arthur Cecil Pigou"],
      era: ["c20"],
      coreTenets: [
        "External costs (pollution, congestion) are not reflected in market prices, causing overproduction of harmful goods.",
        "A Pigouvian tax set equal to the marginal external cost internalizes the externality and restores efficiency.",
        "Conversely, positive externalities (education, research) justify subsidies because the market underprovides them.",
      ],
      keyThinkers: ["A.C. Pigou — The Economics of Welfare (1920)"],
      principalCritiques: [
        "Coase argued that with well-defined property rights and low transaction costs, private bargaining can resolve externalities without taxes.",
        "Public choice theorists contend Pigouvian remedies are subject to regulatory capture and political distortion.",
      ],
    },
    {
      name: "Neoclassical synthesis",
      description: "The postwar merger of Keynesian macroeconomics with neoclassical microeconomics.",
      tags: ["c20"],
      tenet: "Keynesian demand management is needed in the short run; neoclassical equilibrium governs the long run.",
      lineage: { parents: ["Neoclassical economics", "Keynesian economics"], divergence: "Samuelson's textbook synthesis; dominates from the 1950s to the 1970s stagflation crisis" },
      figures: ["Paul Samuelson", "John Hicks", "Franco Modigliani"],
      era: ["c20"],
      coreTenets: [
        "Markets may fail to clear in the short run due to sticky wages and prices; fiscal and monetary policy stabilize demand.",
        "In the long run, the economy tends toward a neoclassical equilibrium determined by technology and preferences.",
        "The IS-LM model (Hicks) formalizes Keynes's theory within a simultaneous-equation framework.",
      ],
      keyThinkers: ["Paul Samuelson — Economics (textbook, 1948+)", "John Hicks — 'Mr. Keynes and the Classics' (1937)"],
      principalCritiques: [
        "Post-Keynesians argue the synthesis stripped Keynes of his most radical insights (fundamental uncertainty, endogenous money).",
        "Monetarists and new classicals argued the synthesis lacked consistent microfoundations and overestimated the scope for demand management.",
      ],
    },
    {
      name: "Homo economicus",
      description: "The model of economic agents as perfectly rational, self-interested, and utility-maximizing.",
      tags: ["c19", "c20", "concept"],
      tenet: "Economic agents are modeled as rational maximizers of their own utility, with stable preferences and unlimited computational capacity.",
      lineage: { parents: ["Neoclassical economics"], divergence: "the methodological abstraction that grounds neoclassical analysis; increasingly contested by behavioral economics" },
      figures: ["John Stuart Mill (proto)", "formalized in 20th-century theory"],
      era: ["c19", "c20"],
      coreTenets: [
        "Agents have complete, transitive preferences and choose the option that maximizes their utility.",
        "Preferences are exogenous, stable, and context-independent.",
        "Self-interest is the dominant motivation; altruism and social norms are secondary or reducible to self-interest.",
      ],
      keyThinkers: ["Gary Becker — The Economic Approach to Human Behavior (1976)"],
      principalCritiques: [
        "Kahneman and Tversky demonstrated systematic departures from rational choice (prospect theory, framing effects, heuristics).",
        "Sen argued the 'rational fool' model ignores commitment, sympathy, and moral reasoning as motivations for economic action.",
      ],
    },
    {
      name: "Public choice theory",
      description: "Apply economic analysis to political behavior: politicians, bureaucrats, and voters are self-interested agents.",
      tags: ["c20"],
      tenet: "Political actors — voters, politicians, bureaucrats — are self-interested maximizers; government failure is as real as market failure.",
      lineage: { parents: ["Neoclassical economics"], divergence: "extends economic methodology to politics; challenges the benevolent-government assumption of welfare economics" },
      figures: ["James Buchanan", "Gordon Tullock", "Mancur Olson"],
      era: ["c20"],
      coreTenets: [
        "Politicians maximize votes, bureaucrats maximize budgets, and interest groups seek rents — none reliably pursue the public interest.",
        "Collective action problems (free-riding) mean concentrated interests dominate diffuse ones in the political process.",
        "Constitutional constraints on government power are necessary because democratic politics systematically produces inefficient outcomes.",
      ],
      keyThinkers: ["James Buchanan & Gordon Tullock — The Calculus of Consent (1962)", "Mancur Olson — The Logic of Collective Action (1965)"],
      principalCritiques: [
        "Critics argue public choice theory assumes away public-spiritedness, civic virtue, and the evidence that many officials are genuinely motivated by the public interest.",
        "The theory can become a self-fulfilling prophecy: if we design institutions assuming everyone is self-interested, we crowd out intrinsic motivation.",
      ],
    },
    {
      name: "Constitutional political economy",
      description: "The study of rules — constitutions, voting systems, fiscal constraints — that structure political and economic choices.",
      tags: ["c20"],
      tenet: "The rules of the game matter more than individual moves within them; constitutional design shapes economic and political outcomes.",
      lineage: { parents: ["Public choice theory"], divergence: "Buchanan's extension; shifts focus from choices within rules to the choice of rules themselves" },
      figures: ["James Buchanan", "Viktor Vanberg"],
      era: ["c20"],
      coreTenets: [
        "Individuals behind a 'veil of uncertainty' would agree to constitutional constraints limiting government power.",
        "Fiscal constitutions (balanced-budget requirements, tax limits) prevent majoritarian exploitation of minorities.",
        "The legitimacy of political outcomes depends on the fairness of the constitutional rules, not the outcomes themselves.",
      ],
      keyThinkers: ["James Buchanan — The Limits of Liberty (1975)", "Buchanan & Tullock — The Calculus of Consent"],
      principalCritiques: [
        "Rawlsians argue Buchanan's constitutional framework protects property rights at the expense of distributive justice.",
        "Historical institutionalists contend that constitutions are products of power struggles, not hypothetical unanimous agreement.",
      ],
    },
    {
      name: "Chicago school",
      description: "Markets work; regulation usually fails. Price theory, monetarism, and skepticism of government intervention.",
      tags: ["c20"],
      tenet: "Competitive markets are remarkably efficient; government intervention typically does more harm than good.",
      lineage: { parents: ["Neoclassical economics"], divergence: "the Chicago tradition: empirical price theory, monetarism, and systematic skepticism of regulation" },
      figures: ["Milton Friedman", "George Stigler", "Gary Becker", "Ronald Coase"],
      era: ["c20"],
      coreTenets: [
        "Rigorous price theory, applied to real-world data, shows markets work better than critics suppose.",
        "Government regulation is typically captured by the industries it regulates (Stigler).",
        "Economic analysis applies to all human behavior: crime, family, discrimination, law (Becker).",
      ],
      keyThinkers: ["Milton Friedman — Price Theory (1962)", "George Stigler — 'The Theory of Economic Regulation' (1971)", "Gary Becker — The Economic Approach to Human Behavior (1976)"],
      historicalInstances: ["Chicago Boys in Chile (1970s-80s)", "Deregulation movement (US, 1970s-80s)", "Antitrust revolution (consumer welfare standard)"],
      principalCritiques: [
        "Keynesians and institutionalists argue the Chicago school systematically underestimates market failures and the positive role of regulation.",
        "Critics note the Chicago Boys' influence in Chile was associated with authoritarian rule, raising questions about the political conditions for their economic programme.",
      ],
    },
  ],
};

export const FAMILIES: Family[] = [
  PRECURSORS_FAMILY,
  CLASSICAL_FAMILY,
  MARXIAN_FAMILY,
  NEOCLASSICAL_FAMILY,
];
