import type { Family } from "./types";

export const FAMILIES_9_16: Family[] = [
  // ── Family 9 ──────────────────────────────────────────────────────────────
  {
    slug: "signals-control",
    number: 9,
    name: "Signal Processing & Control Systems",
    blurb: "Filtering, sampling, feedback, stability, and the dynamic control of engineered systems.",
    section: "B",
    color: "violet",
    entries: [
      {
        name: "Laplace transform",
        description: "Maps a time signal to a complex-frequency representation $F(s)$.",
        keyFact: "$F(s) = \\int_0^\\infty f(t) e^{-st}\\,dt$. Turns ODEs into algebraic equations; native language of control engineering.",
        formula: "F(s) = \\int_0^\\infty f(t) e^{-s t}\\,dt",
        tags: ["control", "transform"],
        xref: ["mathematics"],
      },
      {
        name: "Fourier transform",
        description: "Decomposes a signal into sinusoidal components.",
        keyFact: "$F(\\omega) = \\int f(t) e^{-j\\omega t} dt$. Frequency content is the basis of every filter and modulation scheme.",
        formula: "F(\\omega) = \\int f(t) e^{-j\\omega t}\\,dt",
        tags: ["DSP", "transform"],
        xref: ["mathematics", "physics"],
      },
      {
        name: "Nyquist–Shannon sampling theorem",
        description: "A signal is fully captured by samples taken at $f_s > 2 f_{\\max}$.",
        keyFact: "Below Nyquist rate, aliasing folds higher frequencies into the baseband. CD audio: 44.1 kHz sampling → 22 kHz nominal upper limit.",
        formula: "f_s > 2 f_{\\max}",
        tags: ["DSP", "fundamental"],
        status: "landmark",
        xref: ["mathematics"],
      },
      {
        name: "Discrete Fourier transform (FFT)",
        description: "Discrete-time decomposition into frequency bins.",
        keyFact: "Cooley–Tukey FFT (1965) reduces DFT cost from $O(N^2)$ to $O(N\\log N)$ — the algorithm that made real-time DSP feasible.",
        formula: "X_k = \\sum_{n=0}^{N-1} x_n e^{-j 2\\pi k n / N}",
        tags: ["DSP"],
        status: "landmark",
        xref: ["computer-science"],
      },
      {
        name: "Digital filter (FIR / IIR)",
        description: "Discrete-time linear filters with finite or infinite impulse response.",
        keyFact: "FIR: $y_n = \\sum b_k x_{n-k}$; always stable, linear-phase possible. IIR: feedback terms; lower order but stability must be verified (poles inside unit circle).",
        tags: ["DSP"],
      },
      {
        name: "Z-transform",
        description: "Discrete-time analogue of the Laplace transform.",
        keyFact: "Stability ↔ all poles inside unit circle $|z| < 1$. Bilinear (Tustin) transform maps continuous filters to discrete ones.",
        formula: "X(z) = \\sum_{n=-\\infty}^{\\infty} x_n z^{-n}",
        tags: ["DSP", "discrete"],
      },
      {
        name: "Negative feedback (Black, 1934)",
        description: "Sacrifice gain for linearity, bandwidth, and disturbance rejection.",
        keyFact: "Closed-loop gain $A_{cl} = A / (1 + A\\beta) \\to 1/\\beta$ when $A\\beta \\gg 1$. Foundation of modern amplifiers and control loops.",
        formula: "A_{cl} = \\frac{A}{1 + A\\beta}",
        tags: ["feedback", "control"],
        status: "landmark",
      },
      {
        name: "PID controller",
        description: "Proportional + integral + derivative feedback law.",
        keyFact: "$u(t) = K_p e + K_i \\int e\\,dt + K_d \\dot e$. Most widely deployed control law in industry; Ziegler–Nichols (1942) gives empirical tuning rules.",
        formula: "u(t) = K_p e(t) + K_i \\int_0^t e\\,d\\tau + K_d \\dot e",
        tags: ["control"],
        status: "landmark",
      },
      {
        name: "Bode plot",
        description: "Frequency response magnitude (dB) and phase vs $\\log\\omega$.",
        keyFact: "Phase margin > 45° and gain margin > 6 dB are typical robustness targets. Slope at gain crossover sets damping.",
        tags: ["control", "frequency"],
      },
      {
        name: "Root locus",
        description: "Plot of closed-loop pole locations as gain varies.",
        keyFact: "Designed by Evans (1948). Tells you whether feedback drives poles toward stability or into the right half-plane.",
        tags: ["control"],
      },
      {
        name: "Stability (Routh–Hurwitz / Nyquist)",
        description: "Tests whether all closed-loop poles lie in the left half-plane.",
        keyFact: "Routh–Hurwitz: algebraic test on characteristic polynomial. Nyquist: contour encirclements of $-1$ point on open-loop plot.",
        tags: ["control", "stability"],
      },
      {
        name: "State-space representation",
        description: "$\\dot{\\vec{x}} = A\\vec{x} + B\\vec{u}$, $\\vec{y} = C\\vec{x} + D\\vec{u}$.",
        keyFact: "MIMO-friendly; controllability and observability decided by rank of $[B, AB, A^2 B, \\dots]$ and $[C^T, A^T C^T, \\dots]$ matrices.",
        formula: "\\dot{\\vec{x}} = A\\vec{x} + B\\vec{u}",
        tags: ["control", "modern"],
      },
      {
        name: "Kalman filter",
        description: "Optimal recursive estimator for linear Gaussian systems.",
        keyFact: "Combines prediction and measurement via the Kalman gain. First flown on Apollo; ubiquitous in GPS, INS, sensor fusion.",
        tags: ["estimation", "control"],
        status: "landmark",
        xref: ["statistics", "mathematics"],
      },
      {
        name: "Model predictive control",
        description: "At each step, solve a constrained optimization over a finite future horizon.",
        keyFact: "Handles input/state constraints natively. Default control in petrochemical plants; spreading to vehicles, drones, energy.",
        tags: ["control", "optimization"],
      },
    ],
  },

  // ── Family 10 ─────────────────────────────────────────────────────────────
  {
    slug: "power-systems",
    number: 10,
    name: "Power Systems & Energy Conversion",
    blurb: "Generation, transmission, distribution, and electromechanical energy conversion.",
    section: "B",
    color: "indigo",
    entries: [
      {
        name: "Three-phase AC",
        description: "Balanced set of three sinusoids 120° apart in phase.",
        keyFact: "Yields constant instantaneous power and a rotating magnetic field — basis of all utility transmission and AC motors.",
        tags: ["AC", "power"],
        status: "landmark",
      },
      {
        name: "Transformer",
        description: "Two-coil device transferring power between voltage levels via magnetic flux.",
        keyFact: "Ideal: $V_1/V_2 = N_1/N_2 = I_2/I_1$. Without transformers, large-scale AC distribution would be impossible (Westinghouse won the War of the Currents).",
        formula: "\\frac{V_1}{V_2} = \\frac{N_1}{N_2}",
        tags: ["transformer"],
        status: "landmark",
      },
      {
        name: "Synchronous machine",
        description: "AC generator/motor whose rotor turns in lock with the line frequency.",
        keyFact: "Speed: $n_s = 120 f / p$ (rpm). Workhorse generator of every power plant — fossil, nuclear, hydro.",
        formula: "n_s = \\frac{120 f}{p}",
        tags: ["machine", "generator"],
      },
      {
        name: "Induction motor",
        description: "AC motor where rotor currents are induced rather than supplied.",
        keyFact: "Slip $s = (n_s - n)/n_s$ drives torque; simple, robust, dominates industry. Invented by Tesla (1888).",
        formula: "s = \\frac{n_s - n}{n_s}",
        tags: ["motor"],
        status: "landmark",
      },
      {
        name: "DC motor",
        description: "Brushed or brushless commutated motor with linear torque–speed characteristic.",
        keyFact: "$\\tau = k_t I$, back-EMF $E = k_e \\omega$. Easy speed/torque control — historically dominant for variable-speed before VFDs.",
        tags: ["motor"],
      },
      {
        name: "Power factor correction",
        description: "Adding reactive elements to bring $\\cos\\phi \\to 1$.",
        keyFact: "Lower reactive current → smaller line losses, smaller transformers, lower utility charges.",
        tags: ["power", "utility"],
      },
      {
        name: "Per-unit system",
        description: "Normalization scheme for power-system quantities.",
        keyFact: "Each quantity expressed as fraction of a chosen base. Transformer impedances become independent of side; load-flow equations simpler.",
        tags: ["power", "method"],
      },
      {
        name: "Load flow / power flow",
        description: "Nonlinear AC equations for bus voltages and line flows.",
        keyFact: "Solved by Newton–Raphson or fast-decoupled methods. Every utility runs hourly load-flow studies for security analysis.",
        tags: ["grid", "analysis"],
      },
      {
        name: "Fault analysis (symmetrical components)",
        description: "Decomposing unbalanced fault into positive, negative, zero sequences.",
        keyFact: "Fortescue (1918). 3-phase fault uses only positive sequence; single-line-to-ground engages all three. Sets relay coordination.",
        tags: ["protection"],
      },
      {
        name: "HVDC transmission",
        description: "Bulk power transmission via direct current at hundreds of kV.",
        keyFact: "More economical than AC beyond ~600 km overhead or ~50 km submarine. Async link between AC grids; no skin effect, no reactive losses.",
        tags: ["transmission"],
      },
      {
        name: "Photovoltaic cell",
        description: "Semiconductor device converting photons to DC electricity.",
        keyFact: "Shockley–Queisser limit ≈ 33% for single-junction Si under unconcentrated sunlight; tandem perovskite/Si lab cells > 33% (2024).",
        tags: ["solar", "energy"],
        xref: ["physics"],
      },
      {
        name: "Wind turbine power",
        description: "Mechanical power extractable from wind.",
        keyFact: "$P = \\tfrac{1}{2}\\rho A v^3 C_p$. Betz limit: $C_p \\le 16/27 \\approx 0.593$. Modern turbines reach ≈ 0.45.",
        formula: "P = \\tfrac{1}{2}\\rho A v^3 C_p",
        tags: ["wind", "energy"],
      },
      {
        name: "Battery energy storage",
        description: "Electrochemical storage of electrical energy.",
        keyFact: "Li-ion energy density ≈ 250–300 Wh/kg (cell); cycle life > 3000 at depth-of-discharge < 80%. Round-trip efficiency ~90–95%.",
        tags: ["storage"],
      },
      {
        name: "Smart grid",
        description: "Power grid augmented with two-way digital communications and demand response.",
        keyFact: "Phasor Measurement Units (PMUs) at 30–60 Hz enable wide-area visibility — successor to seconds-scale SCADA.",
        tags: ["grid", "modern"],
      },
    ],
  },

  // ── Family 11 ─────────────────────────────────────────────────────────────
  {
    slug: "computer-engineering",
    number: 11,
    name: "Computer Engineering (Hardware)",
    blurb: "Digital logic, processor architecture, memory hierarchy, and embedded hardware.",
    section: "B",
    color: "blue",
    entries: [
      {
        name: "Boolean algebra",
        description: "Algebra of two-valued variables.",
        keyFact: "AND, OR, NOT generate every Boolean function. NAND and NOR are individually universal — single-gate technologies suffice.",
        tags: ["logic", "fundamental"],
        xref: ["mathematics", "computer-science"],
      },
      {
        name: "Combinational logic",
        description: "Output depends only on current inputs.",
        keyFact: "Implemented as gate networks. Minimization via Karnaugh maps (≤6 vars) or Quine–McCluskey/Espresso (synthesis tools).",
        tags: ["logic"],
      },
      {
        name: "Sequential logic / flip-flops",
        description: "Memory elements clocked by an edge or level.",
        keyFact: "D, JK, T flip-flops. Setup and hold times must be met or the latch enters metastable state.",
        tags: ["logic", "memory"],
      },
      {
        name: "Finite-state machine",
        description: "Sequential circuit with finite memory; Mealy or Moore.",
        keyFact: "Mealy outputs depend on state + input; Moore on state alone. Default abstraction for control units.",
        tags: ["digital", "design"],
        xref: ["computer-science"],
      },
      {
        name: "CPU pipelining",
        description: "Overlap fetch/decode/execute/memory/writeback stages.",
        keyFact: "Ideal speedup ≈ number of stages; hazards (data, control, structural) limit real gain. Modern Intel/ARM 14–20 stages.",
        tags: ["architecture"],
        xref: ["computer-science"],
      },
      {
        name: "Cache hierarchy",
        description: "Multi-level memory between CPU and DRAM.",
        keyFact: "L1 ~32 KB / ~1 ns, L2 ~256 KB / ~3 ns, L3 ~8 MB / ~12 ns, DRAM ~16 GB / ~80 ns. Locality (temporal + spatial) is what makes it work.",
        tags: ["architecture", "memory"],
      },
      {
        name: "Instruction-set architecture (ISA)",
        description: "Boundary between hardware and software.",
        keyFact: "RISC (ARM, RISC-V) vs CISC (x86) — but modern x86 implementations decode CISC into RISC-like micro-ops.",
        tags: ["architecture"],
      },
      {
        name: "Memory hierarchy (DRAM/SRAM/Flash)",
        description: "Successive layers of decreasing speed and increasing capacity.",
        keyFact: "SRAM: 6T, fast, no refresh, used for caches. DRAM: 1T1C, dense, needs refresh. Flash: floating-gate, non-volatile, block-erase.",
        tags: ["memory"],
      },
      {
        name: "FPGA",
        description: "Reconfigurable array of logic cells programmable in the field.",
        keyFact: "Lookup tables (LUTs) + flip-flops + DSP/BRAM blocks + routing. Synthesized from Verilog/VHDL/HLS.",
        tags: ["FPGA"],
      },
      {
        name: "ASIC",
        description: "Application-specific integrated circuit — fixed-function silicon.",
        keyFact: "Lower per-unit cost, much higher non-recurring engineering cost vs FPGA. Lead time months. Modern process node 3 nm (TSMC, 2024).",
        tags: ["ASIC"],
      },
      {
        name: "Verilog / VHDL",
        description: "Hardware description languages — describe digital hardware as code.",
        keyFact: "Synthesizable subset → gates. Simulation captures timing and concurrency that don't exist in software languages.",
        tags: ["HDL"],
      },
      {
        name: "Moore's law",
        description: "Empirical doubling of transistor count per chip every ~18–24 months.",
        keyFact: "Held 1965–~2020; trans-density still rising (TSMC N3, 2024) but scaling cadence has slowed. Dennard scaling broke earlier (~2006).",
        tags: ["scaling"],
        status: "landmark",
      },
      {
        name: "Embedded system",
        description: "Computer integrated into a larger product with real-time constraints.",
        keyFact: "Microcontroller (MCU) typically: 8–32-bit CPU + on-chip flash/RAM + peripherals + ADCs. Bare-metal or RTOS.",
        tags: ["embedded"],
      },
      {
        name: "Real-time scheduling",
        description: "Schedulability of periodic tasks under hard deadlines.",
        keyFact: "Rate-monotonic priority assignment is optimal for static priorities; Liu–Layland 1973 utilization bound $n(2^{1/n}-1) \\to \\ln 2 \\approx 0.693$.",
        formula: "U \\le n(2^{1/n} - 1)",
        tags: ["RTOS"],
        xref: ["computer-science"],
      },
    ],
  },

  // ── Family 12 ─────────────────────────────────────────────────────────────
  {
    slug: "software-systems",
    number: 12,
    name: "Software & Systems Engineering",
    blurb: "The disciplined construction of software-intensive systems — processes, lifecycle, quality, V-model.",
    section: "B",
    color: "green",
    entries: [
      {
        name: "Software development lifecycle (SDLC)",
        description: "Phases of software construction from requirements to retirement.",
        keyFact: "Requirements → Design → Implementation → Verification → Maintenance. Waterfall, iterative, agile differ in how strictly stages serialize.",
        tags: ["process"],
      },
      {
        name: "V-model",
        description: "Lifecycle pairing each construction phase with a verification phase.",
        keyFact: "Requirements ↔ acceptance, architecture ↔ system test, design ↔ integration test, code ↔ unit test. Default in safety-critical (DO-178C, IEC 61508).",
        tags: ["process"],
      },
      {
        name: "Agile / Scrum",
        description: "Iterative software development with short feedback cycles.",
        keyFact: "Scrum: time-boxed sprints, product backlog, daily standup, retrospective. Agile Manifesto 2001.",
        tags: ["process"],
      },
      {
        name: "Requirements engineering",
        description: "Elicitation, analysis, specification, validation of needs.",
        keyFact: "Functional vs non-functional. Studies show requirements defects are the dominant rework driver; cheaper to fix at requirements than at code by ~100×.",
        tags: ["requirements"],
      },
      {
        name: "Software architecture",
        description: "High-level structure: components, connectors, properties.",
        keyFact: "Common styles: layered, microservices, event-driven, pipe-and-filter, MVC. Architecture decisions are the hardest to reverse.",
        tags: ["architecture"],
        xref: ["computer-science"],
      },
      {
        name: "Design patterns",
        description: "Named, repeatable solutions to recurring software problems.",
        keyFact: "Gang of Four (1994): 23 patterns across Creational, Structural, Behavioral. Singleton, Factory, Observer, Strategy among the most reused.",
        tags: ["design"],
        xref: ["computer-science"],
      },
      {
        name: "Verification & validation",
        description: "Did we build it right? Did we build the right thing?",
        keyFact: "Verification = conforms to spec; validation = meets user need. The two are independently necessary.",
        tags: ["quality"],
      },
      {
        name: "Software testing (unit/integration/system)",
        description: "Hierarchy of test levels matching the V-model.",
        keyFact: "Unit tests cheap and fast; system tests cover behaviour. Mutation testing and fuzz testing probe coverage quality, not just lines.",
        tags: ["testing"],
      },
      {
        name: "Cyclomatic complexity",
        description: "Number of linearly independent paths through code (McCabe 1976).",
        keyFact: "Code with complexity > 15 is hard to test and maintain; safety-critical guidelines cap at 10 per function.",
        formula: "M = E - N + 2P",
        tags: ["metrics", "quality"],
      },
      {
        name: "Function-point analysis",
        description: "Size measure independent of programming language.",
        keyFact: "Counts inputs, outputs, queries, internal/external files weighted by complexity. Still used for productivity benchmarks and estimating effort.",
        tags: ["metrics"],
      },
      {
        name: "DO-178C / IEC 61508 / ISO 26262",
        description: "Safety-critical software standards for avionics, industrial, automotive.",
        keyFact: "DO-178C (avionics) defines five DALs (A–E); modified-condition/decision coverage (MC/DC) required at DAL A. Tools must be qualified to TQL.",
        tags: ["safety", "standards"],
      },
      {
        name: "Capability Maturity Model Integration (CMMI)",
        description: "Process maturity assessment with five levels.",
        keyFact: "Initial → Managed → Defined → Quantitatively Managed → Optimizing. SEI Carnegie Mellon. Most procurement-driven adoption is government / defense.",
        tags: ["process", "maturity"],
      },
      {
        name: "Therac-25 accidents (1985–1987)",
        description: "Software-controlled radiation therapy machine that killed patients via race condition.",
        keyFact: "Six known massive overdoses. Concurrency bug in mode-switching code, no hardware interlocks. Defining case study for safety-critical SW.",
        tags: ["failure", "case-study"],
        status: "landmark",
      },
      {
        name: "DevOps / CI-CD",
        description: "Automated build, test, deploy pipelines tying development and operations.",
        keyFact: "Reduces mean time to recovery, enables small frequent deploys. Most consequential operational shift in software since version control.",
        tags: ["process"],
        xref: ["computer-science"],
      },
    ],
  },

  // ── Family 13 ─────────────────────────────────────────────────────────────
  {
    slug: "chemical-process",
    number: 13,
    name: "Chemical Engineering & Process Design",
    blurb: "Mass and energy balances, reactor design, separation processes, and the industrial-scale chemistry stack.",
    section: "C",
    color: "teal",
    entries: [
      {
        name: "Mass balance",
        description: "Conservation of mass applied to a control volume.",
        keyFact: "In − Out + Generation = Accumulation. The lever that turns chemistry into engineering.",
        formula: "\\dot m_{in} - \\dot m_{out} + \\dot m_{gen} = \\frac{dM}{dt}",
        tags: ["fundamental", "balance"],
        xref: ["chemistry"],
      },
      {
        name: "Energy balance",
        description: "First-law accounting for a chemical process.",
        keyFact: "Enthalpy of reaction + sensible heat + heat losses = heat duty. Drives reactor cooling and heat-exchanger sizing.",
        tags: ["balance", "thermo"],
      },
      {
        name: "Stoichiometry & limiting reagent",
        description: "Mole-balance constraints from a balanced reaction.",
        keyFact: "Conversion, selectivity, yield are the three KPIs of any reaction system.",
        tags: ["chemistry"],
        xref: ["chemistry"],
      },
      {
        name: "Plug-flow reactor (PFR)",
        description: "Steady-state tubular reactor with no back-mixing.",
        keyFact: "Design eq: $V/F_{A0} = \\int_0^{X_A} dX_A / -r_A$. Gives highest conversion per unit volume for positive-order reactions.",
        formula: "\\frac{V}{F_{A0}} = \\int_0^{X_A} \\frac{dX_A}{-r_A}",
        tags: ["reactor"],
      },
      {
        name: "Continuous stirred-tank reactor (CSTR)",
        description: "Steady-state well-mixed reactor.",
        keyFact: "Design eq: $V = F_{A0} X_A / (-r_A)_{\\text{exit}}$. Used when temperature uniformity matters; lower conversion than PFR.",
        formula: "V = \\frac{F_{A0} X_A}{(-r_A)_{\\text{exit}}}",
        tags: ["reactor"],
      },
      {
        name: "Batch reactor",
        description: "Charge, react for fixed time, discharge.",
        keyFact: "Default for small-volume / high-value chemistry (pharma, specialty). $t = N_{A0}\\!\\int_0^{X_A} dX_A / (-r_A V)$.",
        tags: ["reactor"],
      },
      {
        name: "Distillation",
        description: "Separation by repeated vaporization–condensation in a column.",
        keyFact: "Underwood / Fenske / Gilliland equations for minimum reflux and stages. >95% of industrial separations.",
        tags: ["separation"],
      },
      {
        name: "Absorption / stripping",
        description: "Gas–liquid contact for solute transfer.",
        keyFact: "Used for CO₂ capture (amines), H₂S removal, VOC abatement. Number of transfer units NTU × height HTU = column height.",
        tags: ["separation"],
      },
      {
        name: "Heat exchanger network design",
        description: "Pinch analysis to maximize heat recovery.",
        keyFact: "Linnhoff pinch (1979): identifies minimum energy targets and the pinch temperature at which counter-flow streams kiss. Saves 10–30% energy.",
        tags: ["design", "energy"],
      },
      {
        name: "Process flow diagram",
        description: "Schematic of major equipment, streams, controllers.",
        keyFact: "PFD → P&ID (piping & instrumentation) → 3D model. Cornerstone of plant communication and HAZOP.",
        tags: ["design"],
      },
      {
        name: "Equilibrium stage / McCabe–Thiele",
        description: "Graphical method for binary distillation column design.",
        keyFact: "Step between equilibrium curve and operating line; count stages between feed and target. Still taught because it builds intuition for staged separations.",
        tags: ["separation", "graphical"],
      },
      {
        name: "Haber–Bosch process",
        description: "Catalytic synthesis of ammonia from N₂ and H₂.",
        keyFact: "$\\ce{N2 + 3H2 -> 2NH3}$, ~450 °C, ~150–250 bar, Fe catalyst. Sustains roughly half of global food production.",
        formula: "N_2 + 3H_2 \\rightleftharpoons 2NH_3",
        tags: ["industrial", "case-study"],
        status: "landmark",
        xref: ["chemistry"],
      },
      {
        name: "Catalytic cracking (FCC)",
        description: "Catalytic breakdown of heavy hydrocarbons into gasoline and lighter fractions.",
        keyFact: "Zeolite catalyst, ~500 °C, riser reactor + regenerator. Backbone of every modern refinery.",
        tags: ["industrial", "refinery"],
        xref: ["chemistry"],
      },
      {
        name: "Bhopal disaster (1984)",
        description: "Methyl-isocyanate release at Union Carbide pesticide plant killed thousands.",
        keyFact: "Driving root causes: safety-system deactivation, inadequate hazard analysis, insufficient process safety management. Catalyst for OSHA PSM (29 CFR 1910.119) and EPA RMP.",
        tags: ["failure", "case-study"],
        status: "landmark",
      },
    ],
  },

  // ── Family 14 ─────────────────────────────────────────────────────────────
  {
    slug: "materials-science",
    number: 14,
    name: "Materials Science",
    blurb: "Structure–property–processing–performance — the four-vertex tetrahedron of materials engineering.",
    section: "C",
    color: "sky",
    entries: [
      {
        name: "Crystal structures",
        description: "Periodic atomic arrangements: BCC, FCC, HCP and others.",
        keyFact: "Stacking dictates slip systems and ductility: FCC (Cu, Al, Ni) ductile, BCC (Fe-α, Cr) tougher but lower ductility, HCP (Mg, Ti) limited slip.",
        tags: ["structure"],
        xref: ["chemistry", "physics"],
      },
      {
        name: "Phase diagrams",
        description: "Equilibrium maps of phases vs composition and temperature.",
        keyFact: "Lever rule gives phase fractions in a two-phase field. Fe–C diagram underlies all steel metallurgy.",
        tags: ["thermo"],
      },
      {
        name: "Dislocations",
        description: "Line defects whose motion produces plastic deformation.",
        keyFact: "Edge, screw, mixed. Burgers vector defines slip direction; dislocations multiply during deformation, raising flow stress (work hardening).",
        tags: ["defect"],
        status: "landmark",
      },
      {
        name: "Grain size strengthening (Hall–Petch)",
        description: "Yield strength rises as grain size shrinks.",
        keyFact: "$\\sigma_y = \\sigma_0 + k_y / \\sqrt{d}$. Reverse Hall–Petch below ~10 nm — grain-boundary sliding dominates.",
        formula: "\\sigma_y = \\sigma_0 + \\frac{k_y}{\\sqrt{d}}",
        tags: ["strengthening"],
      },
      {
        name: "Heat treatment of steel",
        description: "Quench + temper to produce martensite then control its toughness.",
        keyFact: "Austenitize → quench (martensite) → temper. TTT diagrams predict transformations; backbone of cutting-tool and structural steel.",
        tags: ["processing", "steel"],
      },
      {
        name: "Fatigue (S-N curves)",
        description: "Failure under cyclic stress below ultimate strength.",
        keyFact: "Steels exhibit a fatigue limit (~10⁶ cycles); aluminum does not — designed for finite life. ~80% of mechanical failures are fatigue.",
        tags: ["failure"],
      },
      {
        name: "Fracture toughness",
        description: "Resistance to crack propagation, $K_{IC}$.",
        keyFact: "$K = Y\\sigma\\sqrt{\\pi a}$; fail when $K \\ge K_{IC}$. Linear-elastic fracture mechanics (Griffith 1921, Irwin 1957).",
        formula: "K = Y\\sigma\\sqrt{\\pi a}",
        tags: ["fracture"],
      },
      {
        name: "Creep",
        description: "Time-dependent deformation under sustained stress and high temperature.",
        keyFact: "Significant when $T/T_m > 0.4$. Three stages: primary (decreasing rate), secondary (steady-state), tertiary (failure). Turbine-blade design driver.",
        tags: ["high-T"],
      },
      {
        name: "Corrosion (galvanic series)",
        description: "Electrochemical degradation of metals.",
        keyFact: "Galvanic series ranks metals by electrode potential in seawater. Anodic metal corrodes preferentially — basis of sacrificial-anode protection (Zn on ship hulls).",
        tags: ["corrosion"],
        xref: ["chemistry"],
      },
      {
        name: "Composites & rule of mixtures",
        description: "Combine matrix + reinforcement to outperform either alone.",
        keyFact: "Parallel-fiber composite Young's modulus $E_c = V_f E_f + (1-V_f) E_m$ (Voigt). Carbon-fiber/epoxy revolutionized aerospace.",
        formula: "E_c = V_f E_f + (1-V_f) E_m",
        tags: ["composites"],
      },
      {
        name: "Semiconductor doping",
        description: "Adding impurities to control carrier concentration.",
        keyFact: "n-type donors (P in Si) contribute electrons; p-type acceptors (B in Si) holes. Concentration gradients form pn junctions — the device.",
        tags: ["semiconductor"],
        xref: ["physics", "chemistry"],
      },
      {
        name: "Glass transition",
        description: "Polymer change from rubbery to glassy with no first-order phase change.",
        keyFact: "Below $T_g$ chains frozen; above $T_g$ segmental motion. Use-temperature design driver for plastics.",
        tags: ["polymer"],
      },
      {
        name: "Shape memory alloys",
        description: "Materials that recover a remembered shape after large deformation.",
        keyFact: "Nitinol (NiTi). Two mechanisms: thermal (martensite → austenite transformation) and pseudoelastic. Used in stents, actuators.",
        tags: ["smart"],
      },
      {
        name: "Additive manufacturing materials",
        description: "Material families compatible with 3D printing processes.",
        keyFact: "Powder bed fusion (steel, Ti, Inconel), FDM (PLA, ABS, PEEK), SLA (photopolymers). Anisotropic build-direction properties.",
        tags: ["AM"],
      },
    ],
  },

  // ── Family 15 ─────────────────────────────────────────────────────────────
  {
    slug: "manufacturing",
    number: 15,
    name: "Manufacturing Processes",
    blurb: "Casting, machining, forming, joining, additive — converting raw materials into finished parts.",
    section: "C",
    color: "amber",
    entries: [
      {
        name: "Casting",
        description: "Pour molten metal into a mold; solidify to net shape.",
        keyFact: "Sand, investment, die, continuous. Solidification governed by Chvorinov's rule: $t_s = B(V/A)^2$.",
        formula: "t_s = B\\left(\\frac{V}{A}\\right)^2",
        tags: ["casting"],
      },
      {
        name: "Forging",
        description: "Bulk deformation to shape and refine grain structure.",
        keyFact: "Open-die for large simple parts (forging hammers), closed-die for high-volume net-shape parts (automotive crankshafts).",
        tags: ["forming"],
      },
      {
        name: "Rolling",
        description: "Reduce thickness between rotating rolls.",
        keyFact: "Hot rolling above recrystallization temperature (large reductions, scale), cold rolling for surface finish and strength.",
        tags: ["forming"],
      },
      {
        name: "Extrusion",
        description: "Force material through a die to produce a long cross-section.",
        keyFact: "Direct (ram and billet move together), indirect (die moves). Aluminum window frames, plastic pipes both rely on it.",
        tags: ["forming"],
      },
      {
        name: "Sheet metal forming",
        description: "Stamping, deep drawing, bending.",
        keyFact: "Springback, formability limit diagrams, blank-holder force are the control parameters. Auto-body panels.",
        tags: ["forming"],
      },
      {
        name: "Machining (turning, milling, drilling)",
        description: "Material removal via cutting tool against workpiece.",
        keyFact: "Cutting force depends on chip thickness × specific cutting energy. Taylor tool life: $V T^n = C$.",
        formula: "V T^n = C",
        tags: ["machining"],
      },
      {
        name: "CNC machining",
        description: "Computer-controlled multi-axis machine tools.",
        keyFact: "G-code drives axis motion; 5-axis enables complex shapes (impeller blades) impossible by hand.",
        tags: ["machining", "automation"],
      },
      {
        name: "Welding",
        description: "Permanent metallurgical joining.",
        keyFact: "Arc (SMAW, GMAW, GTAW), resistance, friction-stir, laser, electron-beam. Heat-affected zone is the design-critical region.",
        tags: ["joining"],
      },
      {
        name: "Brazing and soldering",
        description: "Joining without melting base metal.",
        keyFact: "Filler $T_m$ > 450 °C → brazing; < 450 °C → soldering. Capillary action draws filler into joint.",
        tags: ["joining"],
      },
      {
        name: "Additive manufacturing (3D printing)",
        description: "Layer-by-layer deposition of material.",
        keyFact: "FDM, SLA, SLS, DMLS, MJF, binder jet. Eliminates tooling for low volumes; topology-optimized geometries impossible by subtractive methods.",
        tags: ["AM"],
      },
      {
        name: "Tolerancing (GD&T)",
        description: "Geometric dimensioning and tolerancing.",
        keyFact: "ASME Y14.5 / ISO 1101. Datum reference frames, position, profile, runout. Communicates functional intent that ± dimensions cannot.",
        tags: ["spec"],
      },
      {
        name: "Surface finish",
        description: "Micro-roughness specification.",
        keyFact: "$R_a$ (arithmetic mean roughness): 0.4 µm bearing surface, 3.2 µm general machined, 12.5 µm rough machined.",
        tags: ["spec"],
      },
      {
        name: "Lean manufacturing (TPS)",
        description: "Eliminate waste (muda) at every step.",
        keyFact: "Seven wastes: overproduction, waiting, transport, over-processing, inventory, motion, defects. Toyota Production System, postwar.",
        tags: ["operations"],
        status: "landmark",
      },
      {
        name: "Six Sigma",
        description: "Statistical defect-reduction methodology.",
        keyFact: "Target: 3.4 defects per million opportunities ($\\pm 6\\sigma$ with 1.5σ shift). DMAIC cycle. Motorola origin, GE popularization.",
        tags: ["quality"],
        xref: ["statistics"],
      },
    ],
  },

  // ── Family 16 ─────────────────────────────────────────────────────────────
  {
    slug: "industrial-eng",
    number: 16,
    name: "Industrial & Operations Engineering",
    blurb: "Design and management of integrated systems of people, materials, and information.",
    section: "C",
    color: "amber",
    entries: [
      {
        name: "Operations research",
        description: "Math + computing applied to decision problems.",
        keyFact: "WWII origin (radar deployment, convoy routing). Linear programming, queueing, scheduling, network optimization.",
        tags: ["OR"],
        xref: ["mathematics", "computer-science"],
      },
      {
        name: "Linear programming",
        description: "Optimize a linear objective subject to linear constraints.",
        keyFact: "Simplex (Dantzig 1947) — exponential worst case but fast in practice. Interior-point methods polynomial-time.",
        formula: "\\max \\vec{c}^T \\vec{x}\\ \\text{s.t.}\\ A\\vec{x} \\le \\vec{b},\\ \\vec{x} \\ge 0",
        tags: ["optimization"],
        status: "landmark",
        xref: ["mathematics"],
      },
      {
        name: "Queueing theory (M/M/1)",
        description: "Markovian arrivals + service + single server.",
        keyFact: "Average wait $W_q = \\rho /[\\mu(1-\\rho)]$, $\\rho = \\lambda/\\mu$. Wait time blows up as $\\rho \\to 1$ — sets capacity planning.",
        formula: "W_q = \\frac{\\rho}{\\mu(1-\\rho)}",
        tags: ["queueing"],
        xref: ["statistics"],
      },
      {
        name: "Little's law",
        description: "Average number in system = arrival rate × average time in system.",
        keyFact: "$L = \\lambda W$. Holds for any stable queue, regardless of distribution. Universal capacity tool.",
        formula: "L = \\lambda W",
        tags: ["queueing"],
      },
      {
        name: "Inventory (EOQ)",
        description: "Economic order quantity minimizing holding + ordering cost.",
        keyFact: "$Q^* = \\sqrt{2DS/H}$. Square-root scaling means doubling demand only increases order size ≈ 41%.",
        formula: "Q^* = \\sqrt{\\frac{2 D S}{H}}",
        tags: ["inventory"],
      },
      {
        name: "Newsvendor problem",
        description: "Single-period stocking decision under demand uncertainty.",
        keyFact: "Optimal stocking: $F(Q^*) = (p - c)/(p - s)$ — critical ratio of underage to underage+overage cost.",
        formula: "F(Q^*) = \\frac{p - c}{p - s}",
        tags: ["inventory"],
        xref: ["statistics"],
      },
      {
        name: "Project management (CPM / PERT)",
        description: "Critical Path Method and Program Evaluation Review Technique.",
        keyFact: "Identifies activities that determine project duration; float reveals scheduling flexibility. CPM 1959 (DuPont), PERT 1958 (Polaris).",
        tags: ["project"],
        status: "landmark",
      },
      {
        name: "Gantt chart",
        description: "Time-axis bar chart of project activities.",
        keyFact: "Henry Gantt 1910s. Combined with dependencies, becomes a project network.",
        tags: ["project"],
      },
      {
        name: "Work measurement / time study",
        description: "Quantify time needed for a task.",
        keyFact: "Taylor's 1911 *Principles of Scientific Management* — basis of industrial engineering. Predetermined motion time systems (MTM) extend the idea.",
        tags: ["work"],
      },
      {
        name: "Statistical quality control",
        description: "Process monitoring via Shewhart control charts.",
        keyFact: "$\\bar{X}$ and $R$ charts, $\\pm 3\\sigma$ limits. In-control ≠ in-spec; capability indices $C_p$, $C_{pk}$ compare to specs.",
        tags: ["quality"],
        xref: ["statistics"],
      },
      {
        name: "Reliability block diagram",
        description: "Graphical representation of system reliability via series/parallel components.",
        keyFact: "Series: $R = \\prod R_i$. Parallel: $R = 1 - \\prod(1-R_i)$. Component redundancy at the right place buys reliability cheaply.",
        formula: "R_{\\text{series}} = \\prod_i R_i,\\ R_{\\text{parallel}} = 1 - \\prod_i (1-R_i)",
        tags: ["reliability"],
      },
      {
        name: "Failure mode and effects analysis (FMEA)",
        description: "Bottom-up identification of failure modes and their effects.",
        keyFact: "Risk Priority Number = Severity × Occurrence × Detection. Used in automotive (AIAG), aerospace, medical devices.",
        tags: ["reliability"],
      },
      {
        name: "Supply chain management",
        description: "End-to-end management of material, information, and money flows.",
        keyFact: "Bullwhip effect: demand variability amplifies upstream. Modern supply chains optimize cost ↔ resilience.",
        tags: ["logistics"],
      },
      {
        name: "Human factors / ergonomics",
        description: "Designing workspaces and interfaces for human capability and limits.",
        keyFact: "Anthropometry, biomechanics (NIOSH lifting equation), cognitive workload. Three Mile Island, Air France 447 highlighted HF in process control.",
        tags: ["HF"],
        xref: ["statistics"],
      },
    ],
  },
];
