import type { Family } from "./types";

export const FAMILIES_17_24: Family[] = [
  // ── Family 17 ─────────────────────────────────────────────────────────────
  {
    slug: "aerospace",
    number: 17,
    name: "Aerospace Engineering",
    blurb: "Flight in atmosphere and space — aerodynamics, propulsion, structures, orbital mechanics.",
    section: "D",
    color: "blue",
    entries: [
      {
        name: "Lift coefficient and airfoils",
        description: "Dimensionless lift per unit dynamic pressure per area.",
        keyFact: "$C_L = L / (\\tfrac{1}{2}\\rho v^2 A)$. NACA series airfoils parameterize camber, thickness, position; modern transonic airfoils are supercritical.",
        formula: "C_L = \\frac{L}{\\tfrac{1}{2}\\rho v^2 A}",
        tags: ["aero"],
      },
      {
        name: "Drag polar",
        description: "Plot of $C_D$ vs $C_L$ for an aircraft.",
        keyFact: "$C_D = C_{D0} + C_L^2 /(\\pi A R e)$ — parasite + induced. AR = aspect ratio, $e$ = Oswald efficiency. Maximizing $L/D$ sets cruise speed.",
        formula: "C_D = C_{D0} + \\frac{C_L^2}{\\pi A\\!R\\,e}",
        tags: ["aero"],
      },
      {
        name: "Mach number / compressibility",
        description: "Ratio of flow speed to local speed of sound.",
        keyFact: "Subsonic M < 0.8, transonic 0.8–1.2, supersonic 1.2–5, hypersonic > 5. Shock waves form near M = 1; drag spike + heating.",
        formula: "M = \\frac{v}{a}",
        tags: ["compressible"],
      },
      {
        name: "Stall",
        description: "Flow separation from upper surface; $C_L$ drops abruptly.",
        keyFact: "Occurs at critical angle of attack ($\\sim 15-18°$ for typical airfoils). Recovery requires reducing AoA, not adding power.",
        tags: ["aero", "safety"],
      },
      {
        name: "Brayton cycle / jet engine",
        description: "Continuous-flow gas turbine producing thrust.",
        keyFact: "Turbofan dominates commercial aviation; high bypass ratio (~10) cuts noise and fuel burn. SFC: 0.55 lb/lbf-h modern, vs 1.0 for early jets.",
        tags: ["propulsion"],
      },
      {
        name: "Rocket equation (Tsiolkovsky)",
        description: "$\\Delta v = v_e \\ln(m_0 / m_f)$.",
        keyFact: "Exponential mass cost of high $\\Delta v$ — staging is unavoidable for orbit (Earth low orbit needs $\\sim 9.4$ km/s).",
        formula: "\\Delta v = v_e \\ln\\!\\frac{m_0}{m_f}",
        tags: ["propulsion", "rocket"],
        status: "landmark",
        xref: ["physics"],
      },
      {
        name: "Specific impulse",
        description: "Thrust per unit propellant weight-flow.",
        keyFact: "$I_{sp} = F /(\\dot m g_0)$ seconds. Chemical rockets max ~ 450 s (LH₂/LOX); ion thrusters > 3000 s but low thrust.",
        formula: "I_{sp} = \\frac{F}{\\dot m\\,g_0}",
        tags: ["propulsion"],
      },
      {
        name: "Orbital mechanics (Kepler)",
        description: "Two-body motion under inverse-square gravity.",
        keyFact: "Conic sections; period $T = 2\\pi\\sqrt{a^3/\\mu}$. Vis-viva: $v^2 = \\mu(2/r - 1/a)$. Hohmann transfer is the lowest-energy two-burn orbit change.",
        formula: "v^2 = \\mu\\!\\left(\\frac{2}{r} - \\frac{1}{a}\\right)",
        tags: ["orbital"],
        xref: ["physics"],
      },
      {
        name: "Aircraft structures",
        description: "Semi-monocoque skin-stringer construction.",
        keyFact: "Skin carries shear, stringers carry bending. Pressurized fuselages design-limited by fatigue (de Havilland Comet, 1954).",
        tags: ["structures", "case-study"],
      },
      {
        name: "Aeroelasticity / flutter",
        description: "Coupled aerodynamic–structural instability.",
        keyFact: "Flight envelope must lie below flutter speed. Tacoma Narrows (bridge) and aircraft flutter share underlying physics.",
        tags: ["aero", "structures"],
      },
      {
        name: "Hypersonic flight",
        description: "M > 5 regime with strong real-gas + shock interaction effects.",
        keyFact: "Stagnation temperatures > 2000 K dissociate air; ablative or active cooling required. Mach 5 cruise still unrealized commercially as of 2026.",
        tags: ["hypersonic"],
        status: "open",
      },
      {
        name: "Spacecraft attitude control",
        description: "Maintain orientation via reaction wheels, thrusters, or CMGs.",
        keyFact: "Reaction wheels reach saturation; thrusters required to desaturate. Control-moment gyros enable agile pointing on ISS.",
        tags: ["spacecraft"],
      },
      {
        name: "Re-entry heating",
        description: "Atmospheric heating from converting orbital kinetic energy.",
        keyFact: "Blunt body (Allen, 1953) — high-drag shape reduces heating by sharing energy with shocked air, not the vehicle.",
        tags: ["spacecraft"],
        status: "landmark",
      },
      {
        name: "Reusable orbital launch",
        description: "First-stage recovery and reuse.",
        keyFact: "SpaceX Falcon 9 first vertical-landing orbital booster (2015); reused for cargo + crew; Starship under flight test 2023–2026. Reduces $/kg by 5–10× when proven.",
        tags: ["spacecraft", "modern"],
        status: "contested",
      },
    ],
  },

  // ── Family 18 ─────────────────────────────────────────────────────────────
  {
    slug: "biomedical",
    number: 18,
    name: "Biomedical Engineering",
    blurb: "Engineering applied to biology and medicine — devices, imaging, biomechanics, biomaterials.",
    section: "D",
    color: "rose",
    entries: [
      {
        name: "Hodgkin–Huxley model",
        description: "Conductance-based equations for the action potential.",
        keyFact: "Nobel 1963. Foundational dynamical-system model in computational neuroscience; basis of every modern cardiac and neural simulation.",
        tags: ["neural"],
        status: "landmark",
      },
      {
        name: "ECG / EEG biopotentials",
        description: "Small (~mV / µV) bioelectric signals.",
        keyFact: "ECG ~1 mV at body surface; EEG ~10–100 µV. Instrumentation amplifier + 50/60 Hz notch + 0.5–40 Hz bandpass is the canonical signal chain.",
        tags: ["instrumentation"],
      },
      {
        name: "Pacemaker",
        description: "Implanted device that paces the heart electrically.",
        keyFact: "First implanted 1958 (Senning/Elmqvist). Modern dual-chamber, leadless, MRI-conditional; lithium-iodine battery ~10 yr life.",
        tags: ["device"],
        status: "landmark",
      },
      {
        name: "Defibrillator",
        description: "Delivers shock to terminate ventricular fibrillation.",
        keyFact: "Biphasic waveform replaced monophasic (lower energy, higher conversion). Public-access AEDs cut sudden cardiac death mortality.",
        tags: ["device"],
      },
      {
        name: "Magnetic resonance imaging (MRI)",
        description: "Non-ionizing tomography using nuclear spin precession.",
        keyFact: "Larmor frequency $\\omega = \\gamma B_0$; signal from $T_1$, $T_2$ relaxation. 1.5 T clinical, 3 T research, 7 T human cutting edge.",
        formula: "\\omega = \\gamma B_0",
        tags: ["imaging"],
        xref: ["physics"],
        status: "landmark",
      },
      {
        name: "Computed tomography (CT)",
        description: "X-ray attenuation reconstruction (Hounsfield 1971).",
        keyFact: "Inverse Radon transform; filtered back-projection or iterative reconstruction. Dose-reduction algorithms (~80%) keep CT clinically viable.",
        tags: ["imaging"],
        status: "landmark",
        xref: ["mathematics"],
      },
      {
        name: "Ultrasound",
        description: "Reflected pulses of MHz acoustic waves image soft tissue.",
        keyFact: "Resolution $\\sim \\lambda$; deeper imaging needs lower frequency. Doppler measures flow; elastography measures tissue stiffness.",
        tags: ["imaging"],
        xref: ["physics"],
      },
      {
        name: "Drug delivery",
        description: "Controlled release: rate, location, and target cell.",
        keyFact: "Zero-order release (pump, reservoir) vs first-order (matrix). Lipid nanoparticles enabled mRNA vaccine delivery (2020).",
        tags: ["delivery"],
      },
      {
        name: "Tissue engineering",
        description: "Scaffold + cells + bioactive cues to regenerate tissue.",
        keyFact: "Decellularized scaffolds, 3D-bioprinted constructs, organoids. Skin and cartilage clinically deployed; full organ regeneration still research.",
        tags: ["tissue"],
        status: "open",
      },
      {
        name: "Biocompatibility",
        description: "Material behaviour in physiological environment.",
        keyFact: "ISO 10993 panel: cytotoxicity, sensitization, irritation, systemic toxicity, genotoxicity. Failure modes: thrombogenesis, foreign-body response, corrosion.",
        tags: ["materials"],
        xref: ["chemistry"],
      },
      {
        name: "Prosthetics & exoskeletons",
        description: "Mechanical replacements/augmentations for limbs.",
        keyFact: "Myoelectric control via surface EMG; targeted muscle reinnervation enables natural intent. Powered exoskeletons FDA-cleared for paraplegic mobility.",
        tags: ["prosthetics"],
      },
      {
        name: "Brain–computer interface",
        description: "Direct communication between brain and external device.",
        keyFact: "Utah array (microelectrodes), ECoG, EEG, fNIRS. Speech decoding (UCSF 2021), high-bandwidth Neuralink trials (2024). Long-term electrode stability remains open.",
        tags: ["BCI"],
        status: "open",
      },
      {
        name: "Surgical robotics",
        description: "Robot-assisted minimally invasive surgery.",
        keyFact: "Da Vinci system (Intuitive Surgical, FDA 2000) dominates abdominal robotics; tremor filtering and motion scaling improve precision.",
        tags: ["robotics"],
      },
      {
        name: "Bone mechanics & implants",
        description: "Hip, knee, dental implants under cyclic load.",
        keyFact: "Stress shielding when implant stiffness ≫ bone leads to resorption. Titanium / PEEK match modulus more closely than cobalt-chrome.",
        tags: ["orthopedics"],
      },
    ],
  },

  // ── Family 19 ─────────────────────────────────────────────────────────────
  {
    slug: "environmental",
    number: 19,
    name: "Environmental Engineering",
    blurb: "Water, air, waste, and the engineering response to anthropogenic environmental change.",
    section: "D",
    color: "green",
    entries: [
      {
        name: "Drinking-water treatment",
        description: "Coagulation → flocculation → sedimentation → filtration → disinfection.",
        keyFact: "Chlorination cut typhoid/cholera mortality dramatically in 20th-century cities — arguably the most consequential engineering intervention in public health.",
        tags: ["water"],
        status: "landmark",
      },
      {
        name: "Wastewater treatment (activated sludge)",
        description: "Aerobic biological treatment with microbial flocs.",
        keyFact: "BOD₅ removal > 95%. F/M ratio, MLSS, SRT are the operating levers. Tertiary treatment (N, P removal) increasingly required.",
        tags: ["water"],
      },
      {
        name: "Air pollution control",
        description: "Particulate, NOₓ, SOₓ, VOC abatement.",
        keyFact: "ESPs, baghouses, cyclones for particulate; SCR with NH₃ for NOₓ; FGD for SOₓ. EPA NAAQS criteria pollutants are the regulatory drivers (US).",
        tags: ["air"],
      },
      {
        name: "Solid waste management hierarchy",
        description: "Reduce → reuse → recycle → recover → dispose.",
        keyFact: "Landfill gas (CH₄) is captured as a regulatory + carbon win. Modern lined landfills with leachate collection replaced open dumps.",
        tags: ["waste"],
      },
      {
        name: "Stormwater design",
        description: "Convey/store stormwater runoff to prevent flooding.",
        keyFact: "Rational method $Q = CiA$ for small catchments; SWMM for distributed routing. Green infrastructure (bioswales, permeable pavement) reduces peak flow.",
        formula: "Q = C i A",
        tags: ["water"],
      },
      {
        name: "Environmental impact assessment",
        description: "Predict environmental consequences before project approval.",
        keyFact: "NEPA 1969 (US) introduced the EIS; analogous frameworks across the EU, Canada, Japan. Often the longest line item on a project schedule.",
        tags: ["policy"],
      },
      {
        name: "Greenhouse gas accounting",
        description: "Scope 1/2/3 emissions methodology.",
        keyFact: "GHG Protocol (WRI/WBCSD). GWP-100 converts gases to CO₂-equivalent; methane GWP-100 ≈ 28, GWP-20 ≈ 84.",
        tags: ["climate"],
      },
      {
        name: "Carbon capture and storage (CCS)",
        description: "Capture, transport, geological sequestration of CO₂.",
        keyFact: "Amine absorption commercial; direct-air-capture energy intensive ($> 600$ kJ/mol CO₂ minimum). Storage requires monitored saline aquifers or depleted gas fields.",
        tags: ["climate"],
        status: "contested",
      },
      {
        name: "Renewable energy integration",
        description: "Grid integration of variable wind/solar.",
        keyFact: "Inertia, frequency, voltage support traditionally from synchronous machines; grid-forming inverters now substitute. Storage and demand response fill the gaps.",
        tags: ["energy"],
        status: "contested",
      },
      {
        name: "Life-cycle assessment (LCA)",
        description: "Cradle-to-grave environmental accounting per ISO 14040.",
        keyFact: "Goal & scope → inventory (LCI) → impact assessment (LCIA) → interpretation. The discipline behind \"product carbon footprint\" labels.",
        tags: ["LCA"],
      },
      {
        name: "Indoor air quality (HVAC)",
        description: "Ventilation, filtration, control of indoor pollutants.",
        keyFact: "ASHRAE 62.1 sets ventilation rates by occupancy; MERV ratings on filters. COVID-19 elevated CO₂ as proxy for ventilation adequacy.",
        tags: ["IAQ"],
      },
      {
        name: "Noise pollution",
        description: "Unwanted sound; spectrally and temporally specific health impact.",
        keyFact: "A-weighting approximates human ear; 85 dB(A) over 8 h is the OSHA action level. Doubling sound power = +3 dB; doubling perceived loudness ≈ +10 dB.",
        tags: ["noise"],
      },
      {
        name: "Flint water crisis (2014–2019)",
        description: "Lead leaching after switching source water without corrosion control.",
        keyFact: "Skipped orthophosphate addition + aggressive Flint River water → lead service line corrosion. Children's blood-Pb doubled. Multiple criminal indictments.",
        tags: ["case-study", "failure"],
        status: "landmark",
      },
      {
        name: "PFAS remediation",
        description: "Removing per-/poly-fluorinated alkyl substances from water.",
        keyFact: "GAC, ion exchange, RO concentrate the compounds; destruction technologies (supercritical water oxidation, plasma) still emerging. EPA MCLs 4 ppt (PFOA/PFOS, 2024).",
        tags: ["water", "emerging"],
        status: "open",
      },
    ],
  },

  // ── Family 20 ─────────────────────────────────────────────────────────────
  {
    slug: "nuclear",
    number: 20,
    name: "Nuclear Engineering",
    blurb: "Reactor physics, fuel cycle, radiation protection, and the engineering of fission and fusion power.",
    section: "D",
    color: "emerald",
    entries: [
      {
        name: "Nuclear fission",
        description: "Heavy-nucleus splitting releasing 200 MeV/fission.",
        keyFact: "U-235 thermal cross-section 585 b; fission yields ~2.4 neutrons; sustains chain reaction if $k_{eff} \\ge 1$.",
        tags: ["physics", "fundamental"],
        xref: ["physics", "chemistry"],
      },
      {
        name: "Multiplication factor $k_{eff}$",
        description: "Ratio of fissions in successive generations.",
        keyFact: "$k_{eff} < 1$ subcritical, $= 1$ critical, $> 1$ supercritical. Six-factor formula decomposes $k_{eff}$ into $\\eta f p \\varepsilon P_{NL,f} P_{NL,th}$.",
        tags: ["reactor"],
      },
      {
        name: "Pressurized water reactor (PWR)",
        description: "Most common commercial reactor: enriched UO₂ + light-water moderator/coolant.",
        keyFact: "~15 MPa primary, $\\sim 325$ °C hot leg. Borated water for reactivity control. 65% of commercial fleet worldwide.",
        tags: ["reactor", "PWR"],
      },
      {
        name: "Boiling water reactor (BWR)",
        description: "Direct-cycle reactor; water boils in core.",
        keyFact: "~7 MPa, no separate steam generator, voids in fuel channels add neutronic feedback. ~20% of fleet.",
        tags: ["reactor", "BWR"],
      },
      {
        name: "Small modular reactor (SMR)",
        description: "<300 MWe factory-built modular reactor.",
        keyFact: "NuScale design certified by NRC (2020); first US SMR project (CFPP) cancelled 2023 on cost. China linglong-1 grid-connected 2026 target.",
        tags: ["reactor", "modern"],
        status: "contested",
      },
      {
        name: "Fuel cycle",
        description: "Mining → conversion → enrichment → fabrication → operation → reprocessing / disposal.",
        keyFact: "LWRs use 3–5% enriched UO₂. Once-through (US) vs closed (France, Russia, China). Mox fuel uses Pu from reprocessed spent fuel.",
        tags: ["fuel"],
      },
      {
        name: "Radioactive decay",
        description: "Exponential decline in radioactive atoms.",
        keyFact: "$N(t) = N_0 e^{-\\lambda t}$, $t_{1/2} = \\ln 2 / \\lambda$. Specific activity in Bq/g or Ci/g.",
        formula: "N(t) = N_0 e^{-\\lambda t}",
        tags: ["physics"],
      },
      {
        name: "ALARA & dose limits",
        description: "As Low As Reasonably Achievable radiation-protection principle.",
        keyFact: "ICRP occupational 20 mSv/yr (5-yr avg), public 1 mSv/yr above background. Background ~3 mSv/yr in US.",
        tags: ["radiation-protection"],
      },
      {
        name: "Shielding (γ and neutron)",
        description: "Reducing dose by attenuation in matter.",
        keyFact: "$I = I_0 e^{-\\mu x}$ for narrow beam γ. High-Z dense materials (Pb, U) for γ; H-rich (water, polyethylene, borated concrete) for neutrons.",
        formula: "I = I_0 e^{-\\mu x}",
        tags: ["radiation-protection"],
      },
      {
        name: "Decay heat",
        description: "Residual power from fission-product decay after shutdown.",
        keyFact: "~6.5% of full power at t=0+, ~1% at 1 hr, ~0.1% at 1 week. Driver of Fukushima accident and ATWS design.",
        tags: ["safety"],
      },
      {
        name: "Three Mile Island (1979)",
        description: "Partial core meltdown caused by stuck PORV and operator confusion.",
        keyFact: "No public deaths; reactor a total loss. Catalyst for human-factors overhaul (E-procedures, SAMG) and the formation of INPO.",
        tags: ["case-study", "failure"],
        status: "landmark",
      },
      {
        name: "Chernobyl (1986)",
        description: "RBMK reactor steam explosion + graphite fire.",
        keyFact: "Positive void coefficient + xenon poisoning + procedural violation. Driver of the international safety-culture concept and the Convention on Nuclear Safety.",
        tags: ["case-study", "failure"],
        status: "landmark",
      },
      {
        name: "Fukushima Daiichi (2011)",
        description: "Tohoku earthquake + tsunami flooded EDGs at BWR site.",
        keyFact: "Loss of ultimate heat sink → core damage in units 1–3; H₂ explosions. Catalyst for global stress tests, FLEX equipment, hardened venting.",
        tags: ["case-study", "failure"],
        status: "landmark",
      },
      {
        name: "Fusion (tokamak)",
        description: "Magnetic confinement fusion in a toroidal plasma.",
        keyFact: "JET D-T 1997: 16 MW for 1 s, Q $\\sim 0.65$. NIF inertial confinement 2022: ignition (Q$_{fuel}$ > 1) for the first time. ITER first plasma now targeting 2034.",
        tags: ["fusion"],
        status: "open",
        xref: ["physics"],
      },
    ],
  },

  // ── Family 21 ─────────────────────────────────────────────────────────────
  {
    slug: "transportation",
    number: 21,
    name: "Transportation & Highway Engineering",
    blurb: "Highways, rail, ports, urban transit, and the geometric/traffic design of mobility systems.",
    section: "D",
    color: "indigo",
    entries: [
      {
        name: "Geometric design of highways",
        description: "Horizontal, vertical, and cross-section design controls.",
        keyFact: "Design speed sets minimum radius and sight distance. AASHTO Green Book is the US reference.",
        tags: ["highway"],
      },
      {
        name: "Stopping sight distance",
        description: "Distance to perceive, react, and stop.",
        keyFact: "$d = vt + v^2 /(2gf)$ where $t$ is perception-reaction (~2.5 s) and $f$ is friction coefficient.",
        formula: "d = v t + \\frac{v^2}{2 g f}",
        tags: ["highway"],
      },
      {
        name: "Superelevation",
        description: "Banking a curve to balance centripetal acceleration.",
        keyFact: "$e + f = v^2 /(g R)$. Max $e$ ≈ 8% on highways, 6% on urban; limited by low-speed slipping in winter.",
        formula: "e + f = \\frac{v^2}{g R}",
        tags: ["highway"],
      },
      {
        name: "Pavement design (flexible / rigid)",
        description: "Asphalt-concrete vs Portland-cement-concrete pavement structures.",
        keyFact: "Equivalent Single Axle Load (ESAL) drives flexible pavement design; flexural strength drives rigid. Mechanistic-empirical methods now dominant.",
        tags: ["pavement"],
      },
      {
        name: "Traffic flow theory",
        description: "Relations between flow, density, and speed.",
        keyFact: "Fundamental diagram: $q = k v$. Free flow vs congested branches; capacity at critical density. Greenshields, Greenberg, Pipes models.",
        formula: "q = k v",
        tags: ["traffic"],
        xref: ["statistics"],
      },
      {
        name: "Level of service (LOS)",
        description: "Six-letter grading of traffic operating conditions (A–F).",
        keyFact: "Highway Capacity Manual (HCM) specifies thresholds by facility type. LOS F = breakdown.",
        tags: ["traffic"],
      },
      {
        name: "Intersection control (signal timing)",
        description: "Cycle, splits, offsets for signalized intersections.",
        keyFact: "Webster's formula $C_{opt} = (1.5 L + 5)/(1 - Y)$ minimizes delay. Adaptive control (SCOOT, SCATS) responds to real-time demand.",
        tags: ["traffic"],
      },
      {
        name: "Rail track geometry",
        description: "Gauge, cant, alignment standards for railways.",
        keyFact: "Standard gauge 1435 mm; UIC/FRA classes set max speeds and tolerances. High-speed rail demands tighter geometric tolerances and ballastless track.",
        tags: ["rail"],
      },
      {
        name: "Public transit planning",
        description: "Network design, headway, service frequency for transit.",
        keyFact: "Square-root law: optimal headway $\\sim \\sqrt{C/(2pv)}$ given operating cost $C$ and demand $p$. Frequent service drives ridership more than coverage.",
        tags: ["transit"],
      },
      {
        name: "Airport runway design",
        description: "Geometric and pavement design for aircraft operations.",
        keyFact: "FAA ARC + ICAO Aerodrome Reference Code set width, separation, RESA. Crosswind component normally limited to 13–20 kt.",
        tags: ["airport"],
      },
      {
        name: "Port and harbor engineering",
        description: "Breakwaters, quays, dredged channels.",
        keyFact: "Suez and Panama canals (1869, 1914) reshaped global trade; Panama 2016 expansion accommodates Neopanamax (~14000 TEU).",
        tags: ["marine"],
        status: "landmark",
      },
      {
        name: "Autonomous vehicles (SAE levels 0–5)",
        description: "Society of Automotive Engineers automation taxonomy.",
        keyFact: "Level 4 commercial robotaxis (Waymo, Cruise pre-recall, Baidu) in geo-fenced cities; level 5 (any condition, no driver) not deployed as of 2026.",
        tags: ["autonomy"],
        status: "open",
        xref: ["computer-science"],
      },
      {
        name: "Bridge engineering",
        description: "Beam, arch, suspension, cable-stayed.",
        keyFact: "Akashi-Kaikyō (1998, 1991 m main span), Çanakkale 1915 (2022, 2023 m) — longest suspension spans. Cable-stayed dominates 200–1100 m range.",
        tags: ["structures"],
      },
      {
        name: "Tunneling",
        description: "Sub-surface excavation by TBM, NATM, drill-and-blast.",
        keyFact: "TBM rates 10–30 m/day in good ground. Gotthard Base Tunnel (2016) 57 km — longest railway tunnel in the world.",
        tags: ["geotech"],
      },
    ],
  },

  // ── Family 22 ─────────────────────────────────────────────────────────────
  {
    slug: "systems-reliability",
    number: 22,
    name: "Systems Engineering & Reliability",
    blurb: "End-to-end design of complex systems and the probabilistic engineering of failure-free operation.",
    section: "E",
    color: "violet",
    entries: [
      {
        name: "Systems engineering",
        description: "Interdisciplinary approach to design, integrate, manage complex systems.",
        keyFact: "INCOSE handbook. Functional analysis, requirements traceability, integration, V&V are the spine. Critical at SoS scale (defense, aerospace, ITS).",
        tags: ["systems"],
      },
      {
        name: "Requirements traceability matrix",
        description: "Map requirements → design → tests → deliverables.",
        keyFact: "Forward and backward traceability. Required for DO-178C, FDA 21 CFR Part 820 (medical), ISO 26262 (automotive).",
        tags: ["systems"],
      },
      {
        name: "Concept of operations (ConOps)",
        description: "Description of how a system will be used.",
        keyFact: "Captures stakeholder intent before requirements are frozen — best place to surface assumption disagreements that bite later.",
        tags: ["systems"],
      },
      {
        name: "Reliability function $R(t)$",
        description: "Probability of survival to time $t$.",
        keyFact: "$R(t) = e^{-\\int_0^t \\lambda(s) ds}$. Constant $\\lambda$ → exponential (memoryless). Weibull family covers infant mortality and wear-out.",
        formula: "R(t) = e^{-\\int_0^t \\lambda(s)\\,ds}",
        tags: ["reliability"],
        xref: ["statistics"],
      },
      {
        name: "Bathtub curve",
        description: "Failure rate vs time: infant mortality, useful life, wear-out.",
        keyFact: "Three regions need different design strategies: burn-in, redundancy & maintenance, end-of-life replacement.",
        tags: ["reliability"],
      },
      {
        name: "MTBF / MTTR / availability",
        description: "Mean time between failure, mean time to repair, fraction operational.",
        keyFact: "Availability $A = \\mathrm{MTBF}/(\\mathrm{MTBF} + \\mathrm{MTTR})$. \"Five nines\" (99.999%) ≈ 5 min downtime per year.",
        formula: "A = \\frac{\\mathrm{MTBF}}{\\mathrm{MTBF} + \\mathrm{MTTR}}",
        tags: ["reliability"],
      },
      {
        name: "Fault tree analysis",
        description: "Top-down deductive failure analysis using Boolean logic.",
        keyFact: "MIL-STD-1629A. Minimum cut sets identify single points of failure. WASH-1400 (Rasmussen 1975) brought it into reactor PRA.",
        tags: ["reliability"],
      },
      {
        name: "Probabilistic risk assessment",
        description: "Quantitative assessment of accident frequencies and consequences.",
        keyFact: "Now standard for nuclear, aerospace, oil & gas. CCDF (complementary cumulative distribution) communicates risk profile.",
        tags: ["risk"],
        xref: ["statistics"],
      },
      {
        name: "Redundancy",
        description: "Parallel components or paths to mask single failures.",
        keyFact: "$1-(1-R)^n$ for $n$ identical units. Active vs standby; common-cause failure can defeat naive redundancy.",
        tags: ["reliability"],
      },
      {
        name: "Common-cause failure",
        description: "Single root cause defeats multiple redundant elements simultaneously.",
        keyFact: "Beta-factor model. Diversity (different vendors, designs) and physical separation are the standard mitigations.",
        tags: ["reliability"],
      },
      {
        name: "Human reliability analysis (HRA)",
        description: "Quantifying probability of human error in accident sequences.",
        keyFact: "THERP, CREAM, ATHEANA. Common HEPs: routine step omission $\\sim 10^{-3}$, action under high stress $\\sim 0.25$.",
        tags: ["HF"],
        xref: ["statistics"],
      },
      {
        name: "Maintenance strategy",
        description: "Reactive, preventive, condition-based, predictive.",
        keyFact: "RCM (reliability-centered maintenance) replaced calendar-based PM in aerospace and process industries. Vibration, oil analysis, thermography are core PdM signals.",
        tags: ["maintenance"],
      },
      {
        name: "Reliability allocation",
        description: "Top-down apportionment of system reliability to subsystems.",
        keyFact: "Equal apportionment, AGREE method, weighted methods. Sets supplier targets and component-test budgets.",
        tags: ["reliability"],
      },
      {
        name: "Reliability growth (Duane / AMSAA)",
        description: "Improvement in reliability through test-analyse-fix.",
        keyFact: "Duane: $\\mathrm{MTBF}(t) = \\mathrm{MTBF}_0 (t/t_0)^\\alpha$. Growth rates $\\alpha \\sim 0.3-0.5$ typical for hardware programs.",
        formula: "\\mathrm{MTBF}(t) = \\mathrm{MTBF}_0 \\left(\\frac{t}{t_0}\\right)^\\alpha",
        tags: ["reliability"],
      },
    ],
  },

  // ── Family 23 ─────────────────────────────────────────────────────────────
  {
    slug: "engineering-ethics",
    number: 23,
    name: "Engineering Ethics & Failure Case Studies",
    blurb: "Codes of ethics, professional licensure, whistleblowing, and the canonical case studies of engineering failure.",
    section: "E",
    color: "amber",
    entries: [
      {
        name: "NSPE Code of Ethics",
        description: "National Society of Professional Engineers ethics canon.",
        keyFact: "Six fundamental canons; first: \"Hold paramount the safety, health, and welfare of the public.\" Used as default in US engineering ethics curricula.",
        tags: ["ethics", "professional"],
      },
      {
        name: "Professional Engineer (PE) licensure",
        description: "Statutory licensure required for stamping certain designs.",
        keyFact: "US: ABET-accredited BS + FE exam + 4 yr supervised experience + PE exam. Industrial exemption varies by state.",
        tags: ["professional"],
      },
      {
        name: "Whistleblower protection",
        description: "Legal protection for reporting unsafe conditions.",
        keyFact: "OSHA Section 11(c) (US); EU Whistleblower Directive (2019). Engineers historically face career retaliation despite formal protections.",
        tags: ["ethics"],
      },
      {
        name: "Conflict of interest",
        description: "Personal interest interfering with professional judgement.",
        keyFact: "Disclosure is the default mitigation; some COIs require recusal. NSPE II.4 prohibits acting as agent or trustee with undisclosed conflicting interests.",
        tags: ["ethics"],
      },
      {
        name: "Challenger disaster (1986)",
        description: "Space Shuttle SRB O-ring failure at low launch-day temperature.",
        keyFact: "Engineers (Roger Boisjoly, MTI) warned of cold-weather failure; management overruled. Rogers Commission and Diane Vaughan's *Normalization of Deviance*.",
        tags: ["case-study", "failure"],
        status: "landmark",
      },
      {
        name: "Columbia disaster (2003)",
        description: "Foam strike to leading-edge wing caused re-entry breakup.",
        keyFact: "CAIB cited foam-strike history as accepted deviation. Engineers' request for DoD imagery declined. Companion to Challenger as failure of organizational learning.",
        tags: ["case-study", "failure"],
        status: "landmark",
      },
      {
        name: "Hyatt Regency walkway collapse (1981)",
        description: "Atrium walkway connection redesign doubled load on a single rod.",
        keyFact: "Design change communicated by shop drawing without engineer recalculation. 114 killed. PEs lost licenses; case study in shop-drawing review responsibilities.",
        tags: ["case-study", "failure"],
        status: "landmark",
      },
      {
        name: "Deepwater Horizon (2010)",
        description: "Macondo well blowout, fire, sinking; 11 killed; largest US marine oil spill.",
        keyFact: "Cement-job failure, negative-pressure-test misinterpretation, BOP non-actuation. Catalyzed Bureau of Safety and Environmental Enforcement (BSEE) reorganization.",
        tags: ["case-study", "failure"],
        status: "landmark",
      },
      {
        name: "Boeing 737 MAX (MCAS)",
        description: "MCAS software pushed nose down on bad AoA sensor signal; Lion Air JT610 (2018), Ethiopian ET302 (2019).",
        keyFact: "Single-sensor reliance, undocumented pilot interface, certification basis (commonality with NG) all contributed. Grounding 2019–2020.",
        tags: ["case-study", "failure"],
        status: "landmark",
      },
      {
        name: "Volkswagen diesel emissions scandal (2015)",
        description: "Defeat device detected dynamometer testing and toggled emissions controls.",
        keyFact: "Engineers wrote the code; ~$30B in fines and settlements; CEO resignations + criminal convictions. Pre-eminent modern engineering-ethics failure.",
        tags: ["case-study", "ethics"],
        status: "landmark",
      },
      {
        name: "Theranos",
        description: "Fraudulent blood-testing claims via Edison device that never worked.",
        keyFact: "Indictment 2018, conviction 2022 (Holmes, Balwani). Cautionary tale for due diligence on engineering claims in high-trust biotech.",
        tags: ["case-study"],
        status: "refuted",
      },
      {
        name: "Quebec Bridge collapses (1907, 1916)",
        description: "Cantilever bridge collapsed twice during construction.",
        keyFact: "75 deaths in 1907 from under-designed compression chords. Origin of the Canadian Iron Ring tradition and a UK-Canadian focus on engineering ethics education.",
        tags: ["case-study", "failure"],
        status: "landmark",
      },
      {
        name: "Engineering as social practice",
        description: "Engineering decisions inevitably embed social/political choices.",
        keyFact: "Langdon Winner's \"Do Artifacts Have Politics?\" (1980) reframed technical choice as political. Foundational for STS-informed engineering ethics.",
        tags: ["theory"],
      },
      {
        name: "Sustainability and intergenerational ethics",
        description: "Engineering decisions affect generations yet unborn.",
        keyFact: "ASCE Code Canon 1 amended (2017) to add \"the principles of sustainable development\". Now embedded in most professional codes globally.",
        tags: ["ethics", "sustainability"],
      },
    ],
  },

  // ── Family 24 ─────────────────────────────────────────────────────────────
  {
    slug: "open-problems",
    number: 24,
    name: "Open Problems & Frontier Engineering",
    blurb: "Unsolved engineering grand challenges — the open status entries identify the frontier as of 2026.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Grid-scale energy storage at carbon-free levels",
        description: "Multi-day storage matching renewables-heavy grids.",
        keyFact: "Li-ion economical for ~4 h; long-duration storage (iron-air, hydrogen, pumped thermal) at gigawatt-hour scale not yet deployed cost-competitively.",
        tags: ["energy"],
        status: "open",
      },
      {
        name: "Commercial fusion power",
        description: "Net-electricity fusion reactor on the grid.",
        keyFact: "ITER first plasma 2034 target; private fusion (CFS, Helion, TAE) targeting 2030s. Q_eng > 10 with tritium breeding still unrealized.",
        tags: ["energy"],
        status: "open",
      },
      {
        name: "Permanent disposal of high-level nuclear waste",
        description: "Operational deep-geologic repository for civilian spent fuel.",
        keyFact: "Onkalo (Finland) targeting operations late 2020s; first such repository in the world. US Yucca Mountain effectively defunded since 2010.",
        tags: ["nuclear", "policy"],
        status: "open",
      },
      {
        name: "Direct air capture economics",
        description: "Removing CO₂ from ambient air at climate-relevant cost.",
        keyFact: "Climeworks Mammoth (Iceland, 2024) 36 kt/yr nameplate; costs > $600/t. Sub-$100/t needed for climate-scale viability.",
        tags: ["climate"],
        status: "open",
      },
      {
        name: "Closed-loop critical-mineral recycling",
        description: "Recycling Li, Co, Ni, REEs from end-of-life batteries and electronics.",
        keyFact: "Pyrometallurgical + hydrometallurgical hybrid processes; cell-to-cell direct recycling research-stage. Black-mass recovery rates < 50% commercial.",
        tags: ["materials", "circular"],
        status: "open",
      },
      {
        name: "Reusable interplanetary transport",
        description: "Fully reusable Earth-Mars / Earth-Moon cycler-class transport.",
        keyFact: "SpaceX Starship targeting reusable second stage; first uncrewed Mars demonstration earliest 2026–2028 window. Refuelling architecture not yet demonstrated.",
        tags: ["aerospace"],
        status: "open",
      },
      {
        name: "Whole-organ engineering",
        description: "Engineered transplantable solid organs (kidney, liver, heart).",
        keyFact: "Decellularized scaffolds + recellularization + perfusion bioreactors; only small/simple organs (skin, cartilage, bladder) clinical. Solid-organ trials primarily pre-clinical.",
        tags: ["biomed"],
        status: "open",
      },
      {
        name: "Robust embodied AI in unstructured environments",
        description: "General-purpose robots reliably operating in homes / disaster zones.",
        keyFact: "Demonstrations (Figure 02, Tesla Optimus, 1X Eve, Boston Dynamics Atlas 2024) impressive but not yet reliable at scale. Foundation models accelerating capability.",
        tags: ["robotics", "AI"],
        status: "open",
        xref: ["computer-science"],
      },
      {
        name: "Software-driven safety assurance for autonomous systems",
        description: "Verification framework for AI-driven autonomous vehicles, weapons, medical devices.",
        keyFact: "ISO 21448 SOTIF, UL 4600, ISO/PAS 8800. Long-tail testing, formal methods, runtime monitoring — no consensus on what \"safe enough\" looks like.",
        tags: ["safety", "AI"],
        status: "open",
      },
      {
        name: "Room-temperature ambient-pressure superconductivity",
        description: "Lossless conduction at ordinary conditions.",
        keyFact: "LK-99 (Korea 2023) failed independent replication. Engineering implications would be transformational — but remains unrealized as of 2026.",
        tags: ["materials"],
        status: "refuted",
        xref: ["physics", "chemistry"],
      },
      {
        name: "Cybersecurity of OT / critical infrastructure",
        description: "Defensible operational-technology networks (power, water, transport).",
        keyFact: "Stuxnet (2010), Colonial Pipeline (2021), Ukrainian grid (2015/2016) demonstrated vulnerability. IEC 62443 / NERC CIP frameworks evolving in response.",
        tags: ["security"],
        status: "open",
        xref: ["computer-science"],
      },
      {
        name: "Quantum-computing fault tolerance",
        description: "Logical qubits with error rates low enough to run useful algorithms.",
        keyFact: "IBM Heron (2024), Google Willow (2024) demonstrated error correction below threshold for the first time. Useful fault-tolerant computer not yet built.",
        tags: ["quantum"],
        status: "open",
        xref: ["computer-science", "physics"],
      },
      {
        name: "Water security under climate change",
        description: "Affordable, reliable water for water-stressed regions.",
        keyFact: "Desalination ~3 kWh/m³ best (SWRO with energy recovery); brine disposal an open environmental problem. Aquifer depletion mapping by GRACE satellites worsening.",
        tags: ["water", "climate"],
        status: "open",
      },
      {
        name: "Engineering for an aging civil infrastructure",
        description: "Renewal of US/EU bridges, water mains, grid at sustainable rates.",
        keyFact: "ASCE 2025 Infrastructure Report Card grade C. Average US bridge ~46 yr old; cast-iron water mains > 100 yr in many cities. Investment gaps in the trillions.",
        tags: ["infrastructure"],
        status: "open",
      },
    ],
  },
];
