import type { Material, MaterialCategory } from "./types";

// Property values from CES Granta / MatWeb / ASM Handbook ranges; mid-range typical values.
// Where ranges are wide (concrete, wood, polymers, composites), values are representative.
export const MATERIALS: Material[] = [
  // ── metals ──────────────────────────────────────────────────────────────
  {
    name: "Mild steel (AISI 1018)",
    category: "metal",
    density: 7.87,
    youngsModulus: 205,
    tensileStrength: 440,
    thermalConductivity: 51.9,
    meltingPoint: 1450,
    electricalResistivity: 1.59e-7,
    costRank: 1,
    notes: "Low-carbon structural steel — the default construction metal.",
  },
  {
    name: "Stainless steel (304)",
    category: "metal",
    density: 8.0,
    youngsModulus: 193,
    tensileStrength: 505,
    thermalConductivity: 16.2,
    meltingPoint: 1450,
    electricalResistivity: 7.2e-7,
    costRank: 2,
    notes: "Austenitic Cr-Ni; corrosion resistant; food/medical workhorse.",
  },
  {
    name: "Aluminum alloy (6061-T6)",
    category: "metal",
    density: 2.70,
    youngsModulus: 68.9,
    tensileStrength: 310,
    thermalConductivity: 167,
    meltingPoint: 652,
    electricalResistivity: 4.0e-8,
    costRank: 2,
    notes: "Aerospace & frame alloy; strength-to-weight + weldability.",
  },
  {
    name: "Copper (C11000)",
    category: "metal",
    density: 8.96,
    youngsModulus: 117,
    tensileStrength: 220,
    thermalConductivity: 401,
    meltingPoint: 1085,
    electricalResistivity: 1.68e-8,
    costRank: 3,
    notes: "Best practical conductor for wiring & heat exchangers.",
  },
  {
    name: "Titanium alloy (Ti-6Al-4V)",
    category: "metal",
    density: 4.43,
    youngsModulus: 113.8,
    tensileStrength: 950,
    thermalConductivity: 6.7,
    meltingPoint: 1604,
    electricalResistivity: 1.78e-6,
    costRank: 5,
    notes: "Aerospace/biomedical; high specific strength; expensive.",
  },
  {
    name: "Tungsten",
    category: "metal",
    density: 19.25,
    youngsModulus: 411,
    tensileStrength: 1510,
    thermalConductivity: 173,
    meltingPoint: 3422,
    electricalResistivity: 5.6e-8,
    costRank: 4,
    notes: "Highest melting metal; filaments & radiation shielding.",
  },
  {
    name: "Gold",
    category: "metal",
    density: 19.32,
    youngsModulus: 78,
    tensileStrength: 120,
    thermalConductivity: 318,
    meltingPoint: 1064,
    electricalResistivity: 2.44e-8,
    costRank: 5,
    notes: "Inert contact metal in electronics.",
  },
  {
    name: "Nickel superalloy (Inconel 718)",
    category: "metal",
    density: 8.19,
    youngsModulus: 200,
    tensileStrength: 1240,
    thermalConductivity: 11.4,
    meltingPoint: 1336,
    electricalResistivity: 1.25e-6,
    costRank: 5,
    notes: "Jet-engine turbine blades; high-T strength + creep resistance.",
  },

  // ── ceramics ────────────────────────────────────────────────────────────
  {
    name: "Alumina (Al₂O₃)",
    category: "ceramic",
    density: 3.95,
    youngsModulus: 380,
    tensileStrength: 300,
    thermalConductivity: 30,
    meltingPoint: 2072,
    electricalResistivity: 1e12,
    costRank: 2,
    notes: "Substrate ceramic, bearings, wear plates.",
  },
  {
    name: "Silicon carbide (SiC)",
    category: "ceramic",
    density: 3.21,
    youngsModulus: 410,
    tensileStrength: 350,
    thermalConductivity: 120,
    meltingPoint: 2730,
    electricalResistivity: 1e3,
    costRank: 4,
    notes: "Brake discs, abrasives, power semiconductors.",
  },
  {
    name: "Concrete (normal-weight)",
    category: "ceramic",
    density: 2.40,
    youngsModulus: 30,
    tensileStrength: 3.5, // tensile is weak; ~10% of compressive
    thermalConductivity: 1.4,
    meltingPoint: null,
    electricalResistivity: 1e2,
    costRank: 1,
    notes: "Cheap in compression, ~10× weaker in tension — hence rebar.",
  },
  {
    name: "Soda-lime glass",
    category: "ceramic",
    density: 2.52,
    youngsModulus: 72,
    tensileStrength: 70,
    thermalConductivity: 0.96,
    meltingPoint: 1400,
    electricalResistivity: 1e10,
    costRank: 1,
    notes: "Window glass; brittle, poor thermal shock.",
  },
  {
    name: "Zirconia (YSZ)",
    category: "ceramic",
    density: 5.85,
    youngsModulus: 200,
    tensileStrength: 1000,
    thermalConductivity: 2.5,
    meltingPoint: 2715,
    electricalResistivity: 1e9,
    costRank: 4,
    notes: "Thermal-barrier coatings; dental implants.",
  },

  // ── polymers ────────────────────────────────────────────────────────────
  {
    name: "Polyethylene (HDPE)",
    category: "polymer",
    density: 0.95,
    youngsModulus: 0.8,
    tensileStrength: 26,
    thermalConductivity: 0.48,
    meltingPoint: 130,
    electricalResistivity: 1e15,
    costRank: 1,
    notes: "Pipes, packaging — most-produced polymer by mass.",
  },
  {
    name: "PVC (rigid)",
    category: "polymer",
    density: 1.40,
    youngsModulus: 3.3,
    tensileStrength: 52,
    thermalConductivity: 0.19,
    meltingPoint: 100,
    electricalResistivity: 1e15,
    costRank: 1,
    notes: "Plumbing, vinyl siding; degrades above ~80 °C.",
  },
  {
    name: "Polycarbonate",
    category: "polymer",
    density: 1.20,
    youngsModulus: 2.4,
    tensileStrength: 65,
    thermalConductivity: 0.21,
    meltingPoint: 155,
    electricalResistivity: 1e14,
    costRank: 2,
    notes: "Bulletproof glazing; high impact toughness.",
  },
  {
    name: "Nylon 6,6",
    category: "polymer",
    density: 1.14,
    youngsModulus: 3.0,
    tensileStrength: 83,
    thermalConductivity: 0.25,
    meltingPoint: 263,
    electricalResistivity: 1e13,
    costRank: 2,
    notes: "Gears, bearings, fibers.",
  },
  {
    name: "PEEK",
    category: "polymer",
    density: 1.32,
    youngsModulus: 3.6,
    tensileStrength: 100,
    thermalConductivity: 0.25,
    meltingPoint: 343,
    electricalResistivity: 1e16,
    costRank: 5,
    notes: "Aerospace, medical implants; high-T thermoplastic.",
  },
  {
    name: "Natural rubber (vulcanized)",
    category: "polymer",
    density: 0.95,
    youngsModulus: 0.01,
    tensileStrength: 25,
    thermalConductivity: 0.13,
    meltingPoint: null,
    electricalResistivity: 1e13,
    costRank: 2,
    notes: "Tires, seals; large elastic strains via crosslinked chains.",
  },

  // ── composites ──────────────────────────────────────────────────────────
  {
    name: "Carbon-fiber/epoxy (CFRP)",
    category: "composite",
    density: 1.55,
    youngsModulus: 135,
    tensileStrength: 1500,
    thermalConductivity: 7,
    meltingPoint: null,
    electricalResistivity: 1e-5,
    costRank: 5,
    notes: "Aerospace primary structure; anisotropic, layup-dependent.",
  },
  {
    name: "Glass-fiber/polyester (GFRP)",
    category: "composite",
    density: 1.85,
    youngsModulus: 38,
    tensileStrength: 750,
    thermalConductivity: 0.4,
    meltingPoint: null,
    electricalResistivity: 1e13,
    costRank: 3,
    notes: "Boat hulls, wind-turbine blades.",
  },
  {
    name: "Reinforced concrete",
    category: "composite",
    density: 2.50,
    youngsModulus: 30,
    tensileStrength: 400, // governed by steel rebar
    thermalConductivity: 1.4,
    meltingPoint: null,
    electricalResistivity: 1e2,
    costRank: 1,
    notes: "20th-century structural revolution; concrete in compression + steel in tension.",
  },
  {
    name: "Wood (Douglas fir, parallel)",
    category: "composite",
    density: 0.50,
    youngsModulus: 13.4,
    tensileStrength: 85,
    thermalConductivity: 0.12,
    meltingPoint: null,
    electricalResistivity: 1e15,
    costRank: 1,
    notes: "Anisotropic natural composite; the original engineering material.",
  },

  // ── biological / soft ──────────────────────────────────────────────────
  {
    name: "Cortical bone",
    category: "biological",
    density: 1.90,
    youngsModulus: 17,
    tensileStrength: 130,
    thermalConductivity: 0.4,
    meltingPoint: null,
    electricalResistivity: 1e3,
    costRank: 2,
    notes: "Anisotropic composite of collagen + hydroxyapatite.",
  },

  // ── semiconductors ─────────────────────────────────────────────────────
  {
    name: "Silicon (intrinsic)",
    category: "semiconductor",
    density: 2.33,
    youngsModulus: 130,
    tensileStrength: 165,
    thermalConductivity: 149,
    meltingPoint: 1414,
    electricalResistivity: 6.4e2,
    costRank: 2,
    notes: "Substrate of the integrated-circuit industry.",
  },
  {
    name: "Gallium arsenide (GaAs)",
    category: "semiconductor",
    density: 5.32,
    youngsModulus: 85,
    tensileStrength: 66,
    thermalConductivity: 55,
    meltingPoint: 1238,
    electricalResistivity: 1e8,
    costRank: 4,
    notes: "Higher electron mobility than Si; RF & optoelectronics.",
  },
];

export const CATEGORY_STYLES: Record<MaterialCategory, { label: string; bg: string; border: string; text: string }> = {
  metal:        { label: "Metal",        bg: "#1e3a8a40", border: "#3b82f6", text: "#bfdbfe" },
  ceramic:      { label: "Ceramic",      bg: "#52525b40", border: "#a1a1aa", text: "#e4e4e7" },
  polymer:      { label: "Polymer",      bg: "#581c8740", border: "#a855f7", text: "#e9d5ff" },
  composite:    { label: "Composite",    bg: "#92400e40", border: "#f59e0b", text: "#fde68a" },
  biological:   { label: "Biological",   bg: "#7f1d1d40", border: "#ef4444", text: "#fecaca" },
  semiconductor:{ label: "Semiconductor",bg: "#064e3b40", border: "#10b981", text: "#a7f3d0" },
};
