import type { Family } from "./types";

export const FAMILIES_1_7: Family[] = [
  // ── Family 1 ──────────────────────────────────────────────────────────────
  {
    slug: "ip-theoretical-foundations",
    number: 1,
    name: "Theoretical Foundations of IP",
    blurb: "Lockean, utilitarian, and personality theories that justify granting exclusive rights over intangible creations.",
    section: "A",
    color: "violet",
    entries: [
      {
        name: "Lockean labor theory",
        description: "Creators mix their labor with the world and thereby acquire a property right in the result.",
        keyPrinciple: "Locke's Second Treatise (1689): labor confers ownership. IP analog: an inventor who labors to create an invention deserves a property right in it. The theory is strained by the non-rivalrous nature of information — one person using an idea does not deprive another.",
        example: "U.S. patent law's description of the patent bargain ('inventors shall receive patents in exchange for public disclosure') echoes Lockean logic.",
        tags: ["theory", "foundations"],
        xref: ["law"],
      },
      {
        name: "Utilitarian / instrumentalist theory",
        description: "IP rights are a policy tool to maximize social welfare by incentivizing creation and disclosure.",
        keyPrinciple: "Dominant in U.S. law. Patent Clause framing: 'To promote the Progress of Science and useful Arts.' Without protection, free riders underinvest in costly R&D; time-limited monopoly corrects the market failure. Contested: optimal term length, breadth, and whether pharmaceutical vs. software patents require different rules.",
        example: "Congressional cost-benefit framing of copyright term extension (Sonny Bono Act 1998) relied on incentive theory, though Eldred v. Ashcroft (2003) deferred to Congress.",
        tags: ["theory", "foundations", "economics"],
        xref: ["law", "economics"],
      },
      {
        name: "Hegel personality theory",
        description: "Creative works embody the author's will and personality and therefore deserve legal protection.",
        keyPrinciple: "Hegel's Philosophy of Right (1820): property is the embodiment of free will. Foundation for moral rights in civil-law systems (France's droit d'auteur). Explains why moral rights — attribution, integrity — are considered inalienable in European copyright, whereas U.S. copyright is predominantly economic.",
        tags: ["theory", "foundations", "moral-rights"],
        xref: ["law"],
      },
      {
        name: "Patent bargain (quid pro quo)",
        description: "The inventor receives a limited monopoly; in exchange the public receives full disclosure of the invention.",
        keyPrinciple: "Disclosure enables follow-on innovation and prevents the secret dying with the inventor. Enablement and written-description requirements (35 U.S.C. §112) enforce the inventor's side of the bargain. If the specification fails to teach the full scope claimed, the bargain is deficient.",
        example: "Amgen v. Sanofi (2023): broad functional antibody claims not enabled; the monopoly claimed exceeded the contribution disclosed.",
        tags: ["patent", "theory", "disclosure"],
        xref: ["law"],
      },
      {
        name: "Copyright quid pro quo",
        description: "Authors receive a limited exclusive term; afterward works enter the public domain.",
        keyPrinciple: "The Copyright Clause (Art. I §8 cl. 8) sets both the purpose ('promote… Science') and the limit ('limited Times'). Public domain is not a default — it is the end-state that makes the temporary monopoly constitutionally permissible. Eldred v. Ashcroft (2003): Congress has wide latitude to set term length, but a perpetual term would be unconstitutional.",
        tags: ["copyright", "theory", "public-domain"],
        xref: ["law"],
      },
      {
        name: "Intellectual Property Clause — Art. I §8 cl. 8",
        description: "The U.S. constitutional grant of power to Congress to create patent and copyright laws.",
        keyPrinciple: "'To promote the Progress of Science and useful Arts, by securing for limited Times to Authors and Inventors the exclusive Right to their respective Writings and Discoveries.' Scope: (1) Congress may protect, not must; (2) must be to 'promote Progress'; (3) term must be limited. Trademarks are not grounded here — they rest on the Commerce Clause.",
        citation: "U.S. Const. art. I, §8, cl. 8",
        tags: ["constitutional", "patent", "copyright", "foundations"],
        xref: ["law", "governance"],
      },
      {
        name: "Statute of Monopolies (1624)",
        description: "England's first statutory limit on patents; restricted Crown grants to true inventors for 14 years.",
        keyPrinciple: "Precursor to modern patent law. Rejected purely royal-patronage patents; required the subject matter be new and not contrary to law. The 14-year term (two apprenticeship cycles) evolved into the modern 20-year utility patent term.",
        tags: ["history", "patent", "foundations"],
      },
      {
        name: "Statute of Anne (1710)",
        description: "First modern copyright statute; replaced booksellers' guild perpetual rights with a limited author's term.",
        keyPrinciple: "Established that copyright vested in authors, not publishers. 14-year initial term plus 14-year renewal if living. Donaldson v. Beckett (1774) confirmed copyright was purely statutory after term expiry. Foundation of the author-centered copyright model.",
        tags: ["history", "copyright", "foundations"],
      },
      {
        name: "IP as negative right (right to exclude)",
        description: "IP rights are exclusionary — they block others from using, not positive rights to use the IP yourself.",
        keyPrinciple: "A patent grants the right to exclude others from making, using, selling, or importing the invention (35 U.S.C. §154). The patentee may be barred from practicing their own patent by a dominant earlier patent. 'Property' language for IP is contested: scholars debate whether exclusion-only logic justifies strong IP or counsels weaker protection.",
        tags: ["theory", "patent", "foundations"],
        xref: ["law"],
      },
      {
        name: "Public domain",
        description: "The body of creative and inventive works on which IP protection has expired, was never obtained, or was forfeited.",
        keyPrinciple: "Feist Publications v. Rural Telephone (1991): facts are categorically in the public domain — no sweat of the brow suffices for copyright. Works enter the public domain by: term expiration, failure of formalities (pre-Berne works), dedication, or ineligibility. The public domain enables derivative works, education, and cumulative innovation without licensing friction.",
        citation: "Feist Publications, Inc. v. Rural Telephone Service Co., 499 U.S. 340 (1991)",
        tags: ["copyright", "public-domain", "foundations"],
        status: "landmark",
      },
      {
        name: "TRIPS Agreement (1994)",
        description: "WTO agreement establishing minimum IP standards enforceable through trade dispute mechanisms.",
        keyPrinciple: "Agreement on Trade-Related Aspects of Intellectual Property Rights: minimum patent term 20 years; copyright life+50 years; trademark and trade secret obligations; enforcement rules. Binds all 164 WTO members. Doha Declaration (2001) clarified TRIPS flexibilities — compulsory licensing for public health. Bilateral TRIPS-plus deals (e.g., USMCA) raise standards further.",
        citation: "TRIPS Agreement, Apr. 15, 1994, Marrakesh Agreement Annex 1C",
        tags: ["international", "treaty", "foundations"],
        xref: ["law", "governance"],
      },
      {
        name: "Information asymmetry and the disclosure function",
        description: "The patent system corrects the market failure created by inventors holding secrets — disclosure reduces duplicative R&D.",
        keyPrinciple: "Without patent protection, inventors would prefer trade secrecy. Patents induce disclosure, enabling competitors to invent around the patent and allowing future inventors to build on it. The Arrow information paradox: once you reveal a secret to a buyer, the buyer no longer needs to pay for it. Patent law resolves this by granting a time-limited monopoly instead.",
        tags: ["theory", "patent", "economics", "disclosure"],
        xref: ["economics"],
      },
    ],
  },

  // ── Family 2 ──────────────────────────────────────────────────────────────
  {
    slug: "ip-taxonomy-overlap",
    number: 2,
    name: "IP Taxonomy & Overlap",
    blurb: "The main branches of IP law, their subject matter, terms, and how they intersect or conflict.",
    section: "A",
    color: "indigo",
    entries: [
      {
        name: "Patent law",
        description: "Protects inventions — new, useful, non-obvious processes, machines, manufactures, and compositions of matter.",
        keyPrinciple: "Utility patent: 20 years from filing. Design patent: 15 years from grant (post-AIA 2023 change from 14). Plant patent: 20 years. Protection is territorial and requires affirmative prosecution at each national office (with PCT shortcut). No registration = no patent rights.",
        tags: ["patent", "taxonomy"],
        xref: ["law"],
      },
      {
        name: "Copyright law",
        description: "Protects original expression fixed in a tangible medium — literary, artistic, musical, and other works.",
        keyPrinciple: "Arises automatically on fixation; no registration required for protection (though required to sue in U.S. federal court). Term: life+70 years (post-1978 U.S.; Berne minimum life+50). Does not protect ideas, facts, systems, or methods — only expression. Subject matter overlaps with patent when software or industrial design is at issue.",
        tags: ["copyright", "taxonomy"],
        xref: ["law"],
      },
      {
        name: "Trademark law",
        description: "Protects source-identifying marks — words, symbols, sounds, colors, and trade dress — used in commerce.",
        keyPrinciple: "Potentially perpetual as long as the mark is used and maintained. Rights arise from use (common law) or registration. Constitutional basis: Commerce Clause, not Patent/Copyright Clause. Primary purpose is consumer protection (preventing confusion), not rewarding creators. Abandonment through non-use or genericide extinguishes rights.",
        tags: ["trademark", "taxonomy"],
        xref: ["law"],
      },
      {
        name: "Trade secret law",
        description: "Protects commercially valuable confidential information — formulas, methods, processes, customer lists.",
        keyPrinciple: "No term limit; protection lasts as long as secrecy is maintained. No registration or disclosure required. Fragile: independent discovery, reverse engineering, and publication destroy protection. Federal protection since DTSA (2016); state law (UTSA) pre-existing. Unlike patent, gives no monopoly — only against wrongful acquisition.",
        tags: ["trade-secret", "taxonomy"],
        xref: ["law"],
      },
      {
        name: "Right of publicity",
        description: "Protects individuals' commercial right to control use of their name, likeness, voice, and persona.",
        keyPrinciple: "State-law cause of action in ~46 states; no federal statute. Distinct from copyright and trademark but overlaps when a celebrity's image is used in advertising. Duration varies by state; postmortem right exists in 35+ states. First Amendment balances against full absolutism.",
        tags: ["publicity", "taxonomy"],
        xref: ["law"],
      },
      {
        name: "Sui generis rights",
        description: "IP protections that don't fit the classical patent/copyright/trademark taxonomy.",
        keyPrinciple: "EU database right (Directive 96/9/EC): 15-year protection for substantial investment in database compilation; no U.S. equivalent after Feist. Mask work protection (SCPA 1984): 10-year protection for semiconductor chip layouts. Vessel Hull Design Protection Act (1998). Plant Variety Protection Act (PVPA): distinct from plant patents.",
        tags: ["sui-generis", "taxonomy"],
      },
      {
        name: "IP exhaustion / first sale",
        description: "Once an authorized sale of a product occurs, the IP owner's exclusive rights in that item are exhausted.",
        keyPrinciple: "Copyright: §109 first sale — purchaser can resell without infringement; Kirtsaeng v. John Wiley (2013) applies to foreign-made copies lawfully sold abroad. Patent: Impression Products v. Lexmark (2017) — authorized sale exhausts all patent rights; post-sale restrictions on use/resale are unenforceable. Trademark: genuine goods sold by authorized distributor generally not infringing even if resold.",
        citation: "Impression Products, Inc. v. Lexmark International, Inc., 581 U.S. 401 (2017)",
        tags: ["exhaustion", "first-sale", "patent", "copyright"],
        xref: ["law"],
      },
      {
        name: "Territoriality of IP",
        description: "IP rights are national — a U.S. patent confers no rights in Germany; a French copyright term does not govern U.S. law.",
        keyPrinciple: "No global IP right exists. Treaties (Berne, TRIPS, Paris) harmonize minimum standards and reduce friction, but each country's law controls within its borders. Patent infringement requires acts within the territory; copyright infringement in digital environments raises difficult choice-of-law questions. TRIPS binds WTO members to minimum standards.",
        tags: ["international", "territory", "foundations"],
        xref: ["law"],
      },
      {
        name: "IP overlap and cumulative protection",
        description: "A single product or work may simultaneously receive multiple forms of IP protection.",
        keyPrinciple: "A pharmaceutical drug bottle may be: (a) covered by utility patents on the compound; (b) protected by design patent on bottle shape; (c) trademarked name; (d) trade dress on distinctive appearance; (e) trade secret on manufacturing process. Courts must decide whether overlap is permissible or whether one regime displaces another (e.g., patent preemption of trade secret — but Kewanee Oil (1974) held no preemption).",
        example: "Louis Vuitton's monogram canvas: copyrighted design, registered trademark, trade dress — layered protection.",
        tags: ["overlap", "cumulative", "taxonomy"],
      },
      {
        name: "Moral rights vs. economic rights",
        description: "Civil-law copyright protects both the economic value and the author's personal connection to the work.",
        keyPrinciple: "Droit d'auteur (France, Germany): authors retain rights of attribution and integrity that cannot be fully waived. Common-law copyright (U.S., UK): primarily economic; authors can assign all rights. Berne Art. 6bis mandates minimum moral rights. U.S. compliance is contested; VARA (1990) provides narrow moral rights for visual art only.",
        tags: ["moral-rights", "copyright", "international"],
        xref: ["law"],
      },
      {
        name: "Reverse engineering",
        description: "Analyzing a lawfully obtained product to discover its design or composition.",
        keyPrinciple: "Generally permissible for trade secrets if the product is acquired legitimately (DTSA §1839(6)). Patent provides a monopoly against reverse-engineered reimplementation regardless of how product was obtained. Copyright: software decompilation contested — Sega v. Accolade (9th Cir. 1992) allowed decompilation for interoperability as fair use; EU Software Directive permits limited decompilation for interoperability.",
        tags: ["trade-secret", "reverse-engineering", "software"],
      },
    ],
  },

  // ── Family 3 ──────────────────────────────────────────────────────────────
  {
    slug: "patent-basics",
    number: 3,
    name: "Patent Basics",
    blurb: "The statutory requirements for patentability — subject matter, novelty, non-obviousness, disclosure — and patent types.",
    section: "B",
    color: "blue",
    entries: [
      {
        name: "Utility patent",
        description: "Protects new, useful, and non-obvious processes, machines, manufactures, and compositions of matter.",
        keyPrinciple: "35 U.S.C. §§101–103, 112. Term: 20 years from earliest effective filing date, with possible PTA (patent term adjustment for USPTO delays) and PTE (patent term extension for regulatory review). The most common patent type; covers pharmaceuticals, chemicals, software, mechanical devices.",
        citation: "35 U.S.C. §101",
        tags: ["patent", "utility"],
      },
      {
        name: "Design patent",
        description: "Protects the ornamental, non-functional appearance of an article of manufacture.",
        keyPrinciple: "35 U.S.C. §171. Term: 15 years from grant (post-AIA implementation). Infringement test: Egyptian Goddess, Inc. v. Swisa (Fed. Cir. 2008) — whether an ordinary observer familiar with the prior art would purchase one thinking it the other. Claims are in drawings, not words. Used heavily in consumer electronics, fashion accessories.",
        citation: "Egyptian Goddess, Inc. v. Swisa, Inc., 543 F.3d 665 (Fed. Cir. 2008)",
        example: "Apple sued Samsung over design patents on smartphone icon layout and device shape in Apple v. Samsung (total damages exceeding $1B at various stages).",
        tags: ["patent", "design"],
      },
      {
        name: "Plant patent",
        description: "Protects new and distinct asexually reproduced varieties of plants (excluding tuber-propagated and uncultivated plants).",
        keyPrinciple: "35 U.S.C. §§161–164. Term: 20 years. Separate from Plant Variety Protection (PVP), which covers sexually reproduced varieties under the PVPA. Ex parte Hibberd (1985) opened utility patents to plants. J.E.M. Ag Supply v. Pioneer Hi-Bred (2001): utility patents can protect plants, broader than plant patents.",
        tags: ["patent", "plant", "biology"],
      },
      {
        name: "Novelty (§102)",
        description: "The claimed invention must not have been patented, described in a printed publication, in public use, on sale, or otherwise available to the public before the effective filing date.",
        keyPrinciple: "Post-AIA (2013): absolute novelty standard based on the effective filing date. One-year grace period for inventor's own prior disclosures. Pre-AIA: one-year grace period from any prior art; first-to-invent system. A single prior art reference must disclose each element of the claim to anticipate it.",
        citation: "35 U.S.C. §102 (post-AIA)",
        tags: ["patent", "novelty", "§102"],
      },
      {
        name: "Non-obviousness (§103)",
        description: "The claimed invention must not have been obvious to a person having ordinary skill in the art (PHOSITA) at the time of invention.",
        keyPrinciple: "Graham v. John Deere (1966) four-factor test: (1) scope/content of prior art; (2) differences between prior art and claims; (3) level of ordinary skill; (4) secondary considerations (commercial success, long-felt need, failure of others, unexpected results). Combining references must have motivation to combine. KSR Int'l v. Teleflex (2007): flexible, common-sense approach — not rigid TSM test.",
        citation: "Graham v. John Deere Co., 383 U.S. 1 (1966); KSR Int'l Co. v. Teleflex Inc., 550 U.S. 398 (2007)",
        tags: ["patent", "obviousness", "§103"],
        status: "landmark",
      },
      {
        name: "Utility requirement (§101 utility)",
        description: "The invention must have a specific, substantial, and credible utility.",
        keyPrinciple: "Juicy Whip v. Orange Bang (Fed. Cir. 1999): deceptive utility (simulated juice dispenser) is still utility. Brenner v. Manson (1966): chemical process claims require identifiable current utility, not just potential future research utility. Most inventions easily satisfy utility; the requirement filters inoperable or purely research-stage claims.",
        tags: ["patent", "utility-requirement"],
      },
      {
        name: "Enablement (§112(a))",
        description: "The patent specification must teach a person of ordinary skill in the art how to make and use the full scope of the invention.",
        keyPrinciple: "The specification must enable the claimed invention across its full scope without undue experimentation (Wands factors: quantity of experimentation, amount of guidance, breadth of claims, nature of invention, state of the art, skill level, predictability). Amgen v. Sanofi (2023): broad functional antibody claims covering millions of compounds not enabled by examples of 26 antibodies.",
        citation: "Amgen Inc. v. Sanofi, 598 U.S. 594 (2023)",
        tags: ["patent", "enablement", "§112"],
        status: "landmark",
      },
      {
        name: "Written description (§112(a))",
        description: "The specification must demonstrate that the applicant actually possessed the claimed invention as of the filing date.",
        keyPrinciple: "Separate from enablement. Requires the specification to describe the invention in sufficient detail to show the inventor had possession. Critical for: (a) adding claims via continuation; (b) claiming priority to earlier application. Ariad Pharmaceuticals v. Eli Lilly (Fed. Cir. 2010) (en banc): written description is an independent requirement from enablement.",
        tags: ["patent", "written-description", "§112"],
      },
      {
        name: "Definiteness (§112(b))",
        description: "Patent claims must particularly point out and distinctly claim the subject matter regarded as the invention.",
        keyPrinciple: "Nautilus v. Biosig Instruments (2014): claims fail if they do not inform skilled artisans with reasonable certainty about the scope of the invention. Replaced the old 'not amenable to construction / insolubly ambiguous' standard with a more demanding test. Means-plus-function claims (§112(f)) limited to disclosed structure plus equivalents.",
        citation: "Nautilus, Inc. v. Biosig Instruments, Inc., 572 U.S. 898 (2014)",
        tags: ["patent", "definiteness", "§112"],
      },
      {
        name: "Claim types and structure",
        description: "Patent claims define the legal metes and bounds of protection; their structure determines scope.",
        keyPrinciple: "Independent claims stand alone; dependent claims incorporate all limitations of the referenced claim plus additional ones. Method/process claims; apparatus/device claims; composition claims. Means-plus-function claims (§112(f)): 'means for' language invokes limited scope. Claim differentiation doctrine: different claims presumed to have different scope.",
        tags: ["patent", "claims", "prosecution"],
      },
      {
        name: "Priority date and first-inventor-to-file (FITF)",
        description: "AIA (2013) shifted the U.S. from a first-to-invent to a first-inventor-to-file system.",
        keyPrinciple: "Under FITF, the effective filing date determines what counts as prior art and who prevails in priority disputes. Grace period: inventor's own disclosures within 1 year of filing are not prior art against the inventor. Derivation proceedings replaced interference proceedings. Nearly all other countries also use first-to-file.",
        citation: "Leahy-Smith America Invents Act, Pub. L. 112-29 (2011, effective 2013)",
        tags: ["patent", "priority", "AIA"],
      },
      {
        name: "America Invents Act (AIA, 2011)",
        description: "Major patent reform legislation; introduced first-inventor-to-file, inter partes review, post-grant review, and covered business method review.",
        keyPrinciple: "Key changes: (1) FITF system; (2) IPR/PGR/CBM post-issuance review proceedings before PTAB; (3) micro-entity fee reductions; (4) prior commercial use defense; (5) supplemental examination; (6) elimination of most statutory exceptions to prior art. PTAB proceedings dramatically increased; Oil States (2018) upheld their constitutionality.",
        citation: "Leahy-Smith America Invents Act, Pub. L. 112-29, 125 Stat. 284 (2011)",
        tags: ["patent", "AIA", "legislation"],
      },
      {
        name: "Patent term and extensions",
        description: "Utility patents run 20 years from filing; adjustments and extensions may lengthen effective protection.",
        keyPrinciple: "Patent Term Adjustment (PTA): compensates for USPTO delays in examination. Patent Term Extension (PTE): Hatch-Waxman §156 extends pharmaceutical patents up to 5 years to compensate for FDA regulatory review; maximum post-grant term of 14 years. Terminal disclaimers limit term to expiration of a related patent.",
        tags: ["patent", "term", "pharma"],
      },
    ],
  },

  // ── Family 4 ──────────────────────────────────────────────────────────────
  {
    slug: "patent-prosecution",
    number: 4,
    name: "Patent Prosecution",
    blurb: "The process of obtaining a patent — drafting, examination, international filing, and post-grant proceedings.",
    section: "B",
    color: "sky",
    entries: [
      {
        name: "Patent application structure",
        description: "A utility patent application comprises a specification, claims, abstract, drawings, and administrative documents.",
        keyPrinciple: "Specification sections: background, summary, detailed description, claims. Abstract: ≤150 words; not part of the disclosure for claim construction. Claims: the legal protection. Drawings: required if necessary to understand the invention. Oath/declaration: inventor(s) confirm they believe themselves to be the original inventor(s). Assignment recordation protects assignee against subsequent assignments.",
        tags: ["patent", "prosecution", "application"],
      },
      {
        name: "Claims drafting",
        description: "Crafting patent claims is the most consequential part of prosecution — claims define what competitors cannot do.",
        keyPrinciple: "Art: draft independent claims as broadly as prior art permits; use dependent claims to add limitations as fallback positions. Central claiming (U.S.) vs. peripheral claiming differences. Functional claiming: broad, but limited under §112(f). Avoid claim-scope errors that may trigger prosecution history estoppel. Jepson claims (improvement over prior art): express preamble. Product-by-process claims: scope is the product, not the process.",
        tags: ["patent", "prosecution", "claims"],
      },
      {
        name: "USPTO examination process",
        description: "Patent applications are assigned to an examiner who reviews the application and issues office actions.",
        keyPrinciple: "Examiner searches prior art; issues non-final office action (§102, §103, §101, or §112 rejections); applicant responds within 3 months (extendable to 6 months for fee). After-final office actions: applicant can file RCE (request for continued examination) or appeal to PTAB. Track One prioritized examination: final disposition within ~6 months for a fee.",
        tags: ["patent", "prosecution", "USPTO"],
      },
      {
        name: "Office actions and responses",
        description: "USPTO office actions set out rejections and objections; applicants must respond substantively or face abandonment.",
        keyPrinciple: "Non-final OA: applicant may amend claims, argue in remarks, or both. Final OA: amendment rights restricted (Advisory Action if examiner denies entry). Advisory Action: after-final amendment not entered. Appeal: to PTAB on examiner rejections; then Federal Circuit. Restriction requirement: where two or more independent and distinct inventions are claimed, examiner requires election.",
        tags: ["patent", "prosecution", "office-action"],
      },
      {
        name: "Prosecution history estoppel",
        description: "Arguments and claim amendments made during prosecution narrow the scope of the patent's protection in subsequent infringement litigation.",
        keyPrinciple: "Festo Corp. v. Shoketsu (2002): narrowing amendment creates a presumption of estoppel against equivalents; rebutted only if rationale was tangential to equivalent, or equivalent was unforeseeable. Applicants should draft responses carefully — surrendered claim scope is difficult to recover.",
        citation: "Festo Corp. v. Shoketsu Kinzoku Kogyo Kabushiki Co., 535 U.S. 722 (2002)",
        tags: ["patent", "prosecution", "estoppel"],
        status: "landmark",
      },
      {
        name: "Continuation applications",
        description: "Filed while a parent application is pending; claim benefit of the parent's filing date with new or modified claims.",
        keyPrinciple: "Continuation (CON): same disclosure, new claims. Continuation-in-part (CIP): adds new matter; new claims get only new-matter date for purposes of prior art. Divisional: split off after restriction requirement. Strategic use: applicants monitor competitor products and draft continuation claims to cover them — controversial but legal. Abbott Labs v. Sandoz (Fed. Cir. 2009) on submarine continuation strategy.",
        tags: ["patent", "prosecution", "continuation"],
      },
      {
        name: "PCT — Patent Cooperation Treaty",
        description: "Single international patent application designating 157 contracting states; defers national phase entry to 30 months.",
        keyPrinciple: "Filed with a Receiving Office (e.g., USPTO, EPO). International Search Authority (ISA) produces Written Opinion and ISR. Optional International Preliminary Examination (IPEA) produces IPRP Chapter II. National phase entry: 30 months from earliest priority date; each national office then examines. Does not grant a 'world patent' — only simplifies multi-country filing.",
        tags: ["patent", "international", "PCT"],
      },
      {
        name: "EPO examination",
        description: "European Patent Office grants a bundle patent covering designated EPC member states (40 countries).",
        keyPrinciple: "Application in English, French, or German. Formalities examination, search (European Search Report), examination. Grant after payment of national validation fees. Unitary Patent (UP) system launched June 2023: a single validated patent effective in participating EU states. Unified Patent Court (UPC) opened June 2023 for UP and opted-in EP litigation.",
        tags: ["patent", "EPO", "European", "international"],
      },
      {
        name: "Inter partes review (IPR)",
        description: "PTAB trial to cancel issued patent claims on grounds of prior art (§102 or §103) — faster and cheaper than district court.",
        keyPrinciple: "Filed within 1 year of service of infringement complaint. Institution threshold: reasonable likelihood that petitioner will prevail on at least one claim. Estoppel: petitioner is estopped from raising (in district court or ITC) any ground that was raised or reasonably could have been raised in IPR. Oil States Energy Services v. Greene's Energy Group (2018): IPR constitutional; patents are public rights subject to Congressional adjustment.",
        citation: "Oil States Energy Services, LLC v. Greene's Energy Group, LLC, 584 U.S. 325 (2018)",
        tags: ["patent", "IPR", "PTAB", "litigation"],
      },
      {
        name: "Post-grant review (PGR)",
        description: "PTAB proceeding challenging any ground of invalidity — broader than IPR but must be filed within 9 months of grant.",
        keyPrinciple: "Any grounds of invalidity (§101, §102, §103, §112). Institution threshold: more likely than not petitioner will prevail on at least one claim. Estoppel: broader than IPR. Covered Business Method Review (CBM): sunset January 2021, no longer available. PGR is rarely used relative to IPR.",
        tags: ["patent", "PGR", "PTAB"],
      },
      {
        name: "Ex parte reexamination",
        description: "USPTO reconsideration of an issued patent in light of prior art; may be requested by anyone.",
        keyPrinciple: "Threshold: substantial new question of patentability. Conducted between examiner and patent owner; requester limited after initial submission. Contrast with IPR: IPR allows adversarial PTAB trial; reexamination is ex parte. Patentee may amend claims. Certificate of reexamination issued with confirmed, amended, or cancelled claims.",
        tags: ["patent", "reexamination", "USPTO"],
      },
      {
        name: "Restriction requirement and divisional applications",
        description: "When a single application claims multiple distinct inventions, the USPTO requires the applicant to elect one for examination.",
        keyPrinciple: "Examiner determines inventions are independent and distinct. Applicant elects one group; non-elected claims may be pursued in a divisional application claiming the same filing date. Traverse of restriction requirement preserves rights but rarely succeeds. Divisional strategy: pursue broader protection across product/process/composition separately.",
        tags: ["patent", "restriction", "prosecution"],
      },
    ],
  },

  // ── Family 5 ──────────────────────────────────────────────────────────────
  {
    slug: "patentable-subject-matter",
    number: 5,
    name: "Patentable Subject Matter (§101)",
    blurb: "The contested boundary between patent-eligible inventions and excluded abstract ideas, laws of nature, and natural phenomena.",
    section: "B",
    color: "cyan",
    entries: [
      {
        name: "§101 eligible categories",
        description: "Process, machine, manufacture, and composition of matter — plus four judicially created exceptions.",
        keyPrinciple: "Diamond v. Chakrabarty (1980): Congress meant §101 to include 'anything under the sun that is made by man.' Four exceptions not in the statute: laws of nature, natural phenomena, abstract ideas, and products of nature. These exceptions prevent pre-emption of basic building blocks of science. Tension: almost every invention could be described as implementing a natural law or abstract idea.",
        citation: "Diamond v. Chakrabarty, 447 U.S. 303 (1980)",
        tags: ["patent", "§101", "eligibility"],
        status: "landmark",
      },
      {
        name: "Alice Corp. v. CLS Bank (2014)",
        description: "Two-step framework for determining whether a claim directed to an abstract idea recites patent-eligible subject matter.",
        keyPrinciple: "Step 1: Is the claim directed to an abstract idea, law of nature, or natural phenomenon? Step 2 (Alice/Mayo): Does the claim add an inventive concept — something 'significantly more' than the exception — that transforms the claim into a patent-eligible application? Generic computer implementation of an abstract idea fails step 2. Decimated thousands of software and business-method patents. OPEN: what counts as 'abstract' remains unclear.",
        citation: "Alice Corp. v. CLS Bank International, 573 U.S. 208 (2014)",
        tags: ["patent", "§101", "software", "Alice"],
        status: "landmark",
      },
      {
        name: "Mayo Collaborative Services v. Prometheus (2012)",
        description: "Claims directed to the relationship between drug metabolite levels and therapeutic efficacy — a natural law — are ineligible.",
        keyPrinciple: "Diagnostic method: administer drug, measure metabolite, adjust dose. Held: claim simply recited the natural correlation plus routine steps (administer, determine, wherein). All nine justices joined; no inventive concept beyond the law of nature itself. Expansively read by lower courts. Fed. Cir. has since extended Mayo to molecular diagnostics broadly.",
        citation: "Mayo Collaborative Services v. Prometheus Laboratories, Inc., 566 U.S. 66 (2012)",
        tags: ["patent", "§101", "Mayo", "diagnostics"],
        status: "landmark",
      },
      {
        name: "Myriad Genetics (2013)",
        description: "Isolated but naturally occurring DNA sequences are products of nature and not patent-eligible; cDNA is eligible.",
        keyPrinciple: "Association for Molecular Pathology v. Myriad Genetics: isolation of BRCA1/BRCA2 genes does not create patentable subject matter — separation from chromosomal DNA does not change the genetic information. cDNA (complementary DNA, synthetically created, lacks introns) is patent-eligible because it does not naturally exist. Invalidated ~4,000+ gene patents.",
        citation: "Ass'n for Molecular Pathology v. Myriad Genetics, Inc., 569 U.S. 576 (2013)",
        tags: ["patent", "§101", "genomics", "biology"],
        status: "landmark",
      },
      {
        name: "Bilski v. Kappos (2010)",
        description: "Machine-or-transformation test is not the sole test for patent-eligible process claims; business methods not categorically excluded.",
        keyPrinciple: "Bilski's hedging-risk method: not eligible, but Court declined to hold business methods per se ineligible. Machine-or-transformation test (a process is eligible if tied to a particular machine or transforms an article) remains a useful but not exclusive clue. Concurrences (Stevens, Breyer) would have excluded business methods entirely. Alice (2014) effectively limited business-method patents severely via the abstract-idea exception.",
        citation: "Bilski v. Kappos, 561 U.S. 593 (2010)",
        tags: ["patent", "§101", "business-methods", "Bilski"],
        status: "landmark",
      },
      {
        name: "Diamond v. Diehr (1981)",
        description: "A process using a mathematical algorithm within a larger rubber-curing process is patent-eligible.",
        keyPrinciple: "Algorithm (Arrhenius equation) embedded in a physical process that transforms rubber cures a manufactured article. Court held: look at the claim as a whole; the algorithm is not claimed in the abstract. Diehr vs. Benson/Flook: the line is between claiming an algorithm itself vs. a specific application of it to a useful process. Alice step 2 traces to Diehr's 'inventive concept' language.",
        citation: "Diamond v. Diehr, 450 U.S. 175 (1981)",
        tags: ["patent", "§101", "software", "history"],
      },
      {
        name: "Gottschalk v. Benson (1972)",
        description: "An algorithm for converting binary-coded decimal integers to binary is not patent-eligible.",
        keyPrinciple: "The algorithm had no substantial practical application except in connection with digital computers; granting patent would be patenting the mathematical formula itself in the abstract. First major software-patent-eligibility case. Distinguished from Diehr (1981): a pure algorithm vs. an algorithm embedded in a useful process.",
        citation: "Gottschalk v. Benson, 409 U.S. 63 (1972)",
        tags: ["patent", "§101", "software", "history"],
      },
      {
        name: "Enfish v. Microsoft (Fed. Cir. 2016)",
        description: "Software claims directed to a specific improvement in computer functionality — self-referential database table — survive Alice step 1.",
        keyPrinciple: "Enfish established that claims directed to improvements in computer technology itself (not just using a computer to implement an abstract idea) may be patent-eligible. Contrasted with claims that merely use a computer in a well-understood, routine way. Subsequent cases (McRO, Finjan) applied similar analysis to specific technical improvements.",
        citation: "Enfish, LLC v. Microsoft Corp., 822 F.3d 1327 (Fed. Cir. 2016)",
        tags: ["patent", "§101", "software", "eligibility"],
      },
      {
        name: "Berkheimer v. HP (Fed. Cir. 2018)",
        description: "Whether additional claim elements beyond an abstract idea are well-understood, routine, and conventional is a question of fact.",
        keyPrinciple: "Alice step 2 involves factual questions that cannot always be resolved on a motion to dismiss or summary judgment. A patentee can create a genuine dispute of material fact about whether claim elements were routine at the time of filing. This complicated Alice early-stage dismissals — though courts still frequently dispose of §101 claims early.",
        citation: "Berkheimer v. HP Inc., 881 F.3d 1360 (Fed. Cir. 2018)",
        tags: ["patent", "§101", "Alice", "procedure"],
      },
      {
        name: "Software patent eligibility — current state",
        description: "Post-Alice software patent landscape: eligible claims need a specific technical improvement; generic implementation claims largely fail.",
        keyPrinciple: "OPEN: The boundary between 'abstract idea' and 'specific technical improvement' remains unpredictable. USPTO 2019 Revised Guidance reframed Alice step 1 (grouping abstract ideas into three categories); courts give it some but not binding weight. Federal Circuit has invalidated ~60-70% of §101-challenged software claims. Congress has held hearings on §101 reform but no legislation enacted as of 2026.",
        tags: ["patent", "§101", "software", "open"],
        status: "open",
      },
      {
        name: "AI inventorship and §101 for AI-generated inventions",
        description: "Whether AI systems can be named inventors on patent applications, and whether AI-generated inventions are patent-eligible.",
        keyPrinciple: "OPEN: Thaler v. Vidal (Fed. Cir. 2022): 'inventor' under the Patent Act requires a natural person — AI cannot be a named inventor. USPTO 2024 guidance: AI-assisted inventions are eligible if a natural person made a significant contribution to each claim. Who owns AI-generated inventions without a human inventor? No Supreme Court ruling as of 2026.",
        citation: "Thaler v. Vidal, 43 F.4th 1207 (Fed. Cir. 2022)",
        tags: ["patent", "AI", "inventorship", "open"],
        status: "open",
        xref: ["computer-science"],
      },
      {
        name: "Eligible vs. ineligible — the pre-emption rationale",
        description: "The underlying concern in §101 cases is preventing patents from pre-empting whole fields of endeavor.",
        keyPrinciple: "Mayo/Alice: abstract ideas, laws of nature, and natural phenomena are the basic tools of scientific and technological work — monopolizing them would inhibit rather than promote innovation. Pre-emption is the policy concern; 'significantly more' is the doctrinal test for avoiding it. Critics argue the test is circular: what counts as 'significantly more' reduces to 'how much pre-emption is too much'?",
        tags: ["patent", "§101", "theory", "pre-emption"],
      },
    ],
  },

  // ── Family 6 ──────────────────────────────────────────────────────────────
  {
    slug: "patent-litigation",
    number: 6,
    name: "Patent Litigation",
    blurb: "Infringement analysis, claim construction, damages, injunctions, and specialized proceedings including ITC and Hatch-Waxman.",
    section: "B",
    color: "indigo",
    entries: [
      {
        name: "Claim construction (Markman hearing)",
        description: "A court proceeding — not a jury question — to determine the meaning of patent claim terms before trial.",
        keyPrinciple: "Markman v. Westview Instruments (1996): claim construction is a matter of law for the judge. Teva Pharmaceuticals v. Sandoz (2015): underlying factual determinations (extrinsic evidence) reviewed for clear error; ultimate legal conclusion reviewed de novo on appeal. Phillips v. AWH Corp. (Fed. Cir. 2005) (en banc): intrinsic evidence (claims, spec, prosecution history) governs; extrinsic evidence (dictionaries, expert testimony) secondary.",
        citation: "Markman v. Westview Instruments, Inc., 517 U.S. 370 (1996); Teva Pharm. USA, Inc. v. Sandoz, Inc., 574 U.S. 318 (2015)",
        tags: ["patent", "litigation", "claim-construction"],
        status: "landmark",
      },
      {
        name: "Literal infringement",
        description: "An accused product or process infringes if it falls within each and every limitation of at least one patent claim.",
        keyPrinciple: "After claim construction, infringement is a question of fact. Each claim element must be present — 'all elements rule.' Missing even one element from an independent claim = no literal infringement (though dependent claims may still cover). Infringement by equivalents may still exist if literal infringement fails.",
        tags: ["patent", "litigation", "infringement"],
      },
      {
        name: "Doctrine of equivalents",
        description: "Extends patent protection to products or processes that differ insubstantially from a patent claim's literal language.",
        keyPrinciple: "Warner-Jenkinson Co. v. Hilton Davis Chemical Co. (1997): element-by-element application of the function/way/result test — or the insubstantial differences test. Prosecution history estoppel and prior art limit equivalents scope. Cannot use equivalents to capture prior art or subject matter surrendered during prosecution. Vitiation rule: equivalents cannot eliminate a claim limitation entirely.",
        citation: "Warner-Jenkinson Co. v. Hilton Davis Chemical Co., 520 U.S. 17 (1997)",
        tags: ["patent", "litigation", "equivalents"],
        status: "landmark",
      },
      {
        name: "Induced infringement (§271(b))",
        description: "Actively inducing another party to infringe a patent is itself infringement.",
        keyPrinciple: "Global-Tech Appliances v. SEB S.A. (2011): requires knowledge of the patent AND specific intent to induce infringement (or willful blindness). Merely selling a product that can be used to infringe is not necessarily inducement — there must be active steps encouraging infringing use. Contrast with contributory infringement (§271(c)).",
        citation: "Global-Tech Appliances, Inc. v. SEB S.A., 563 U.S. 754 (2011)",
        tags: ["patent", "litigation", "induced-infringement"],
      },
      {
        name: "Contributory infringement (§271(c))",
        description: "Selling a component of a patented invention that has no substantial non-infringing use constitutes infringement.",
        keyPrinciple: "Requirements: (1) sells a component/material/apparatus for use in practicing a patented process; (2) knows the combination to be especially made/adapted for infringing use; (3) no substantial non-infringing use exists. Aro Manufacturing v. Convertible Top Replacement (1961): contributory infringement requires a direct infringer. Contrast with exhaustion — authorized sale exhausts patentee's rights even if buyer uses product to infringe.",
        citation: "35 U.S.C. §271(c); Aro Mfg. Co. v. Convertible Top Replacement Co., 365 U.S. 336 (1961)",
        tags: ["patent", "litigation", "contributory-infringement"],
      },
      {
        name: "Willful infringement and enhanced damages",
        description: "Deliberate infringement can trigger enhanced damages up to three times the actual damages.",
        keyPrinciple: "Halo Electronics v. Pulse Electronics (2016): replaced the objective Seagate two-part test with a subjective standard — did the infringer act with deliberate or wanton disregard for the patentee's rights? Enhanced damages under §284 are discretionary, not automatic. Read Corp. v. Portec (Fed. Cir. 1992) nine-factor test for guidance on amount. Willfulness also makes a case 'exceptional' for attorney fees (Octane Fitness 2014).",
        citation: "Halo Electronics, Inc. v. Pulse Electronics, Inc., 579 U.S. 93 (2016)",
        tags: ["patent", "litigation", "willful", "damages"],
      },
      {
        name: "Patent damages — reasonable royalty and lost profits",
        description: "Damages for patent infringement are measured by the patentee's lost profits or, at minimum, a reasonable royalty.",
        keyPrinciple: "Georgia-Pacific Corp. v. U.S. Plywood (S.D.N.Y. 1970): 15-factor framework for reasonable royalty. Smallest salable patent-practicing unit (SSPPU): royalty base should be the component that practices the patented feature, not the entire multi-component product. Entire market value rule exception: royalty on entire product only if patented feature drives demand. Ericsson v. D-Link (2014) applied these in FRAND context.",
        citation: "Georgia-Pacific Corp. v. United States Plywood Corp., 318 F. Supp. 1116 (S.D.N.Y. 1970)",
        tags: ["patent", "litigation", "damages", "royalty"],
      },
      {
        name: "eBay v. MercExchange (2006) — no automatic injunctions",
        description: "Patent infringement does not automatically entitle the patentee to a permanent injunction.",
        keyPrinciple: "Four-factor equitable test for permanent injunction: (1) irreparable harm; (2) inadequate remedy at law; (3) balance of hardships; (4) public interest. Patent assertion entities (NPEs/trolls) typically cannot satisfy the test — no practice of the patent, so no irreparable harm. Effectively limited injunctive relief for non-practicing entities. Active practicing patentees may still obtain injunctions but must satisfy the test.",
        citation: "eBay Inc. v. MercExchange, L.L.C., 547 U.S. 388 (2006)",
        tags: ["patent", "litigation", "injunction"],
        status: "landmark",
      },
      {
        name: "ITC Section 337 investigations",
        description: "The International Trade Commission can block importation of goods that infringe U.S. IP rights.",
        keyPrinciple: "19 U.S.C. §1337: unfair acts in importation, including patent, copyright, and trademark infringement. Remedies: exclusion order (general or limited), cease and desist. No monetary damages. Faster than district court (typical 15-18 months to final determination). Domestic industry requirement: complainant must have a domestic industry relating to the articles protected. Presidential review of exclusion orders within 60 days.",
        tags: ["patent", "ITC", "litigation", "trade"],
        xref: ["governance"],
      },
      {
        name: "Hatch-Waxman ANDA patent litigation",
        description: "Pharmaceutical patent litigation triggered when a generic drug company challenges patents listed in the FDA Orange Book.",
        keyPrinciple: "Abbreviated New Drug Application (ANDA) filer must certify re: listed patents. Paragraph IV certification: patent invalid/not infringed — triggers 30-month automatic stay on FDA approval and right for patent holder to sue. First generic filer gets 180-day exclusivity incentive. Pioneer drug holder may maintain market exclusivity through stacked patents (patent thicket). Drug Price Competition and Patent Term Restoration Act, Pub. L. 98-417 (1984).",
        tags: ["patent", "pharma", "Hatch-Waxman", "litigation"],
      },
      {
        name: "Inter partes review as litigation strategy",
        description: "IPR is widely used as a defensive tool by accused infringers to cancel patents pre- or post-suit.",
        keyPrinciple: "One-year filing deadline after service of complaint. Institution rates: ~60% of petitions instituted; ~40% of instituted claims cancelled in final written decision. Estoppel applies after final written decision — petitioner estopped from raising in court any ground raised or reasonably could have been raised. Coalition for Affordable Drugs used IPR offensively against pharmaceutical patents to short-sell stocks — triggered SEC inquiry.",
        tags: ["patent", "IPR", "litigation", "PTAB"],
      },
      {
        name: "Obviousness-type double patenting",
        description: "A patentee cannot obtain an unjustified extension of patent term by claiming an obvious variation of their own earlier patent.",
        keyPrinciple: "Judicially created doctrine. Remedy: terminal disclaimer — new patent's term is disclaimed beyond the earlier patent's expiration. Two forms: (1) same-invention type (statutory); (2) obviousness-type (judicially created). Common in pharmaceutical continuation practice: branded drug companies routinely file continuations with modestly different claims and terminal disclaim to preserve market exclusivity.",
        tags: ["patent", "prosecution", "double-patenting"],
      },
      {
        name: "Non-practicing entities (NPEs) and patent assertion",
        description: "Entities that hold patents without practicing the invention, often acquiring patents to assert them against operating companies.",
        keyPrinciple: "OPEN: Pejorative term 'patent troll' contested; NPEs include universities, individual inventors, and pure assertion entities. Policy debate: NPEs enforce patents that practicing entities might let lapse (aggregation function) vs. NPEs extract rents without contributing to the art. AIA introduced limited measures; eBay reduced injunction leverage; PTAB IPRs significantly reduced NPE leverage post-2012.",
        tags: ["patent", "NPE", "litigation", "policy"],
        status: "contested",
      },
    ],
  },

  // ── Family 7 ──────────────────────────────────────────────────────────────
  {
    slug: "copyright-basics",
    number: 7,
    name: "Copyright Basics",
    blurb: "Originality, fixation, the idea/expression dichotomy, authorship, and what copyright protects and does not protect.",
    section: "C",
    color: "teal",
    entries: [
      {
        name: "Originality — Feist standard",
        description: "Copyright requires independent creation plus a modicum of creativity; sweat of the brow is insufficient.",
        keyPrinciple: "Feist Publications v. Rural Telephone Service (1991): alphabetically arranged white-pages directory lacks the minimum creativity required. 'Original' means independently created — not copied from another — and possessing at least some minimal creative spark. Raw facts cannot be copyrighted regardless of the effort to collect them. Thin copyright: highly constrained expression (e.g., phone listing) receives protection only against near-verbatim copying.",
        citation: "Feist Publications, Inc. v. Rural Telephone Service Co., 499 U.S. 340 (1991)",
        tags: ["copyright", "originality", "basics"],
        status: "landmark",
      },
      {
        name: "Fixation requirement",
        description: "A work must be fixed in a tangible medium of expression — capable of being perceived, reproduced, or communicated — to receive federal copyright protection.",
        keyPrinciple: "17 U.S.C. §101: fixed if embodiment is sufficiently permanent to permit perception for more than a transitory duration. RAM copies: MAI Systems v. Peak Computer (9th Cir. 1993) held loading into RAM is a copy — contested but influential. Live unrecorded performances: not protected by federal copyright (some state protection may exist). Sound recordings fixed before 1972 were governed by state law until MMA (2018).",
        tags: ["copyright", "fixation", "basics"],
      },
      {
        name: "Idea / expression dichotomy",
        description: "Copyright protects expression, not the underlying ideas, facts, systems, or methods.",
        keyPrinciple: "17 U.S.C. §102(b): no copyright protection for 'any idea, procedure, process, system, method of operation, concept, principle, or discovery.' Baker v. Selden (1879): accounting system in a book is not protected; only the particular text/illustrations are. Prevents copyright from becoming a patent-like monopoly over concepts. Applied heavily in software copyright disputes (structure, sequence, organization).",
        citation: "Baker v. Selden, 101 U.S. 99 (1879)",
        tags: ["copyright", "idea-expression", "basics"],
        status: "landmark",
      },
      {
        name: "Merger doctrine",
        description: "Where there are only a few ways to express an idea, the idea and expression merge and no copyright attaches.",
        keyPrinciple: "If granting copyright on the expression would effectively monopolize the underlying idea, no copyright can be enforced. Applied in: game rules (Tetris Holding v. Xio Interactive, 2012 — look-and-feel protected but rules are not); legal documents (contract forms); utilitarian pictographic symbols. Close cousin: scènes à faire — stock elements of a genre are unprotectable.",
        example: "A copyright in a drawing of a human figure in anatomical position cannot prevent others from depicting the same pose because there are only so many ways to draw the standard anatomical position.",
        tags: ["copyright", "merger", "basics"],
      },
      {
        name: "Scènes à faire",
        description: "Stock, conventional, or genre-mandatory elements of a work are not independently copyrightable.",
        keyPrinciple: "Literally 'scenes that must be done.' Elements that naturally or necessarily flow from a particular genre or setting: car chases in action films, generic love scenes in romance novels, standard interface elements in software. Not copyrightable individually; thin protection for the combination. Applied in software non-literal copying analysis (Altai AFC test).",
        tags: ["copyright", "scenes-a-faire", "basics"],
      },
      {
        name: "Copyright subject matter (§102(a))",
        description: "Federal copyright subsists in original works of authorship including eight listed categories.",
        keyPrinciple: "Categories: literary works; musical works; dramatic works; pantomimes and choreographic works; pictorial, graphic, and sculptural works; motion pictures and AV works; sound recordings; architectural works (added 1990). List is illustrative. Useful articles exception: PGS works that are purely functional (chairs, lamps) do not receive copyright as to their functional design. Star Athletica v. Varsity Brands (2017): conceptual separability test — if decorative element can be imagined separately from utilitarian function, it is copyrightable.",
        citation: "Star Athletica, L.L.C. v. Varsity Brands, Inc., 580 U.S. 405 (2017)",
        tags: ["copyright", "subject-matter", "basics"],
      },
      {
        name: "Copyright term",
        description: "Post-1978 U.S. works: life of the author plus 70 years; works made for hire: 95 years from publication or 120 years from creation.",
        keyPrinciple: "Sonny Bono Copyright Term Extension Act (1998): extended all existing terms by 20 years. Eldred v. Ashcroft (2003): extension constitutional even for existing works. Pre-1978 published works: complex rules based on publication date and registration. EU and most Berne countries also life+70. Berne minimum: life+50. Term extension is contested on incentive grounds — dead authors cannot be further incentivized.",
        citation: "Eldred v. Ashcroft, 537 U.S. 186 (2003)",
        tags: ["copyright", "term", "basics"],
      },
      {
        name: "Copyright registration and formalities",
        description: "Copyright arises automatically on fixation; registration is not required for protection but is required to sue and recover statutory damages.",
        keyPrinciple: "Pre-Berne (before 1989): notice required; renewal required (for pre-1964 works). Post-Berne (1989+): no formalities required. Registration: prerequisite to sue for infringement of U.S. works in federal court; enables statutory damages ($750–$30,000 per work, up to $150,000 for willful); attorney fees. Deposit requirement: for all published works, two copies deposited with Library of Congress.",
        tags: ["copyright", "registration", "formalities"],
      },
      {
        name: "Work made for hire",
        description: "Works created by employees within the scope of employment, or certain commissioned works, are owned by the employer/commissioning party — not the creator.",
        keyPrinciple: "Two categories (17 U.S.C. §101): (1) Works prepared by an employee within the scope of employment — employer is author and owner. (2) Specially ordered/commissioned works in 9 enumerated categories if parties agree in writing. CCNV v. Reid (1989): contractor vs. employee distinction based on Restatement agency factors. Work-for-hire term: 95/120 years; no termination right for creators.",
        citation: "Community for Creative Non-Violence v. Reid, 490 U.S. 730 (1989)",
        tags: ["copyright", "work-for-hire", "ownership"],
      },
      {
        name: "Joint authorship",
        description: "When two or more authors create a work with the intent to merge their contributions into inseparable parts, each owns an undivided interest.",
        keyPrinciple: "Each joint author can exploit or license the work non-exclusively without the other's consent (but must account for profits). Neither joint author can grant an exclusive license without co-author's consent. Intent at time of creation controls — not post-hoc desire for co-authorship. Aalmuhammed v. Lee (9th Cir. 2000): significant creative control required for joint authorship, not just contribution.",
        tags: ["copyright", "authorship", "ownership"],
      },
      {
        name: "Copyright divisibility and transfer",
        description: "The exclusive rights in copyright are divisible; each may be separately transferred.",
        keyPrinciple: "17 U.S.C. §201(d): owner may transfer any of the exclusive rights exclusively; transferee becomes the owner of that right. E.g., publisher may receive the exclusive right to print; producer may receive performance rights. Transfer must be in writing. Non-exclusive license: need not be written; licensee cannot sue for infringement without joining the copyright owner.",
        tags: ["copyright", "transfer", "ownership"],
      },
      {
        name: "Copyright notice",
        description: "The © symbol, year, and owner's name — once mandatory; now optional but still advantageous.",
        keyPrinciple: "Pre-1989: failure to include notice on published copies could inject a work into the public domain. Post-1978/pre-1989: curative measures available. Post-March 1, 1989 (Berne adhesion): notice no longer required. Advantage of notice: precludes innocent infringer defense (which can reduce statutory damages to $200). Notice still commonly included as a matter of practice.",
        tags: ["copyright", "notice", "formalities"],
      },
    ],
  },
];
