import type { Family } from "./types";

export const FAMILIES_1_8: Family[] = [
  // ── Family 1 ──────────────────────────────────────────────────────────────
  {
    slug: "classical-theorists",
    number: 1,
    name: "Classical Theorists",
    blurb: "The founders who turned the study of society into a discipline — 19th and early 20th century.",
    section: "A",
    color: "violet",
    entries: [
      {
        name: "Auguste Comte",
        description: "Coined the term sociology; promoted positivism.",
        keyFact: "Argued societies pass through theological, metaphysical, and positive (scientific) stages; sociology was to be the queen of the sciences crowning a hierarchy from mathematics up through biology.",
        theorist: "Auguste Comte (1798–1857)",
        example: "Course of Positive Philosophy (1830–1842) systematized the discipline name and the hierarchy of sciences.",
        tags: ["positivism", "foundations", "France"],
        status: "landmark",
      },
      {
        name: "Karl Marx",
        description: "Materialist analysis of class, labor, and capitalism.",
        keyFact: "Capitalism produces alienation and is driven by the contradiction between socialized production and private appropriation of surplus value; class struggle is the engine of history.",
        theorist: "Karl Marx (1818–1883)",
        example: "Capital, vol. I (1867) develops the labor theory of value and the M–C–M' circuit of capital accumulation.",
        tags: ["class", "capitalism", "materialism"],
        xref: ["economics", "philosophy", "ideologies"],
        status: "landmark",
      },
      {
        name: "Émile Durkheim",
        description: "Society as a sui generis reality with social facts.",
        keyFact: "Social facts — ways of acting external to and coercive over the individual — must be explained by other social facts, not by individual psychology.",
        theorist: "Émile Durkheim (1858–1917)",
        example: "Suicide (1897) showed suicide rates vary systematically with degrees of social integration and regulation, not individual pathology alone.",
        tags: ["social-facts", "solidarity", "functionalism"],
        status: "landmark",
      },
      {
        name: "Max Weber",
        description: "Interpretive sociology, rationalization, and the iron cage.",
        keyFact: "Social action must be understood (Verstehen) by reconstructing the actor's meanings; modern history is driven by progressive rationalization that ends in a bureaucratic iron cage.",
        theorist: "Max Weber (1864–1920)",
        example: "The Protestant Ethic and the Spirit of Capitalism (1905) traced capitalism's emergence partly to Calvinist this-worldly asceticism.",
        tags: ["verstehen", "rationalization", "bureaucracy"],
        xref: ["economics", "philosophy"],
        status: "landmark",
      },
      {
        name: "Georg Simmel",
        description: "Forms of sociation, money, and the metropolis.",
        keyFact: "Studied small social forms (dyads vs triads, the stranger, fashion) and how the money economy and urban life reshape the mental life of moderns.",
        theorist: "Georg Simmel (1858–1918)",
        example: "\"The Metropolis and Mental Life\" (1903) traced the blasé attitude to overstimulation by urban stimuli.",
        tags: ["forms", "urban", "Germany"],
        status: "landmark",
      },
      {
        name: "W. E. B. Du Bois",
        description: "Pioneer of empirical American sociology of race.",
        keyFact: "The Philadelphia Negro (1899) was the first major empirical urban sociology in the US; introduced double consciousness — the sense of always seeing oneself through the eyes of a contemptuous other.",
        theorist: "W. E. B. Du Bois (1868–1963)",
        example: "Black Reconstruction in America (1935) reframed Reconstruction as a labor movement, anticipating later structural accounts of race.",
        tags: ["race", "empirical", "USA"],
        status: "landmark",
      },
      {
        name: "Harriet Martineau",
        description: "First systematic sociological observer; translated Comte.",
        keyFact: "Society in America (1837) developed observational methods for moral and political life; advocated treating women's status as a structural feature of any society.",
        theorist: "Harriet Martineau (1802–1876)",
        tags: ["methods", "gender", "UK"],
        status: "landmark",
      },
      {
        name: "Vilfredo Pareto",
        description: "Elites, residues, and the circulation of elites.",
        keyFact: "Argued that every society is governed by a small elite, and politics is the history of one elite replacing another; gave the Pareto distribution its name.",
        theorist: "Vilfredo Pareto (1848–1923)",
        formula: "P(X > x) \\propto x^{-\\alpha}",
        example: "The Pareto principle (80/20 rule) generalizes his observation that ~80% of Italian land was owned by ~20% of the population.",
        tags: ["elites", "power-law", "Italy"],
        xref: ["economics", "statistics"],
        status: "landmark",
      },
      {
        name: "George Herbert Mead",
        description: "Symbolic interactionism and the social self.",
        keyFact: "The self emerges through taking the role of the other; the I (spontaneous response) and the me (internalized other) constitute reflective consciousness.",
        theorist: "George Herbert Mead (1863–1931)",
        example: "Mind, Self, and Society (1934) is the canonical statement; play and game stages structure children's role-taking.",
        tags: ["symbolic-interactionism", "self", "Chicago"],
        xref: ["psychology", "philosophy"],
        status: "landmark",
      },
      {
        name: "Talcott Parsons",
        description: "Structural-functionalism and AGIL.",
        keyFact: "Any social system must solve four functional problems: Adaptation, Goal attainment, Integration, Latency (pattern maintenance). Dominant US theorist 1940s–60s.",
        theorist: "Talcott Parsons (1902–1979)",
        example: "The Social System (1951) modeled society as nested interpenetrating subsystems balancing AGIL functions.",
        tags: ["functionalism", "systems", "USA"],
        status: "contested",
      },
      {
        name: "Robert K. Merton",
        description: "Middle-range theory, manifest/latent functions, anomie.",
        keyFact: "Argued for middle-range theories testable against data, distinguished manifest from latent functions, and extended Durkheim's anomie into a typology of adaptation (conformity, innovation, ritualism, retreatism, rebellion).",
        theorist: "Robert K. Merton (1910–2003)",
        example: "Social Theory and Social Structure (1949) is the founding statement; he also coined self-fulfilling prophecy and unintended consequences.",
        tags: ["middle-range", "anomie", "functionalism"],
        status: "landmark",
      },
      {
        name: "C. Wright Mills",
        description: "The sociological imagination and the power elite.",
        keyFact: "The sociological imagination is the capacity to connect private troubles to public issues; The Power Elite (1956) argued mid-20th-century US power was concentrated in interlocking military, corporate, and political leaderships.",
        theorist: "C. Wright Mills (1916–1962)",
        tags: ["power", "imagination", "USA"],
        xref: ["governance"],
        status: "landmark",
      },
    ],
  },

  // ── Family 2 ──────────────────────────────────────────────────────────────
  {
    slug: "schools-paradigms",
    number: 2,
    name: "Schools & Paradigms",
    blurb: "The big theoretical orientations sociologists still use as labels — and argue about.",
    section: "A",
    color: "indigo",
    entries: [
      {
        name: "Structural functionalism",
        description: "Social institutions persist because they meet system needs.",
        keyFact: "Treats society as an organism whose parts (family, religion, education, economy) contribute functions that maintain equilibrium; dominant US paradigm 1940s–60s, later attacked as conservative and teleological.",
        theorist: "Durkheim, Parsons, Merton",
        tags: ["paradigm", "equilibrium"],
        status: "contested",
      },
      {
        name: "Conflict theory",
        description: "Society as ongoing struggle over scarce resources.",
        keyFact: "Rooted in Marx and Weber: social order reflects dominant groups' interests, and change comes from contestation between groups over material, status, and ideological resources.",
        theorist: "Marx, Dahrendorf, Mills, Collins",
        tags: ["paradigm", "power", "conflict"],
        xref: ["ideologies"],
        status: "landmark",
      },
      {
        name: "Symbolic interactionism",
        description: "Meaning emerges in face-to-face interaction.",
        keyFact: "People act toward things based on the meanings they have for them; meanings arise from interaction and are modified through interpretation. Chicago tradition via Mead, Blumer, Goffman.",
        theorist: "Mead, Herbert Blumer, Goffman",
        tags: ["paradigm", "micro", "meaning"],
        xref: ["psychology"],
        status: "landmark",
      },
      {
        name: "Ethnomethodology",
        description: "Studies the methods members use to produce social order.",
        keyFact: "Garfinkel asked how everyday actors accomplish the sense of obvious reality; breaching experiments make taken-for-granted rules visible by violating them.",
        theorist: "Harold Garfinkel (1917–2011)",
        example: "Garfinkel's 1967 breaching experiments — students acted like boarders in their own homes — revealed how much background work sustains \"normal\" interaction.",
        tags: ["paradigm", "micro", "phenomenology"],
        status: "landmark",
      },
      {
        name: "Phenomenological sociology",
        description: "The life-world as the ground of all social reality.",
        keyFact: "Schutz adapted Husserl's phenomenology to argue that sociology must reconstruct the typifications and stocks of knowledge actors use in everyday life.",
        theorist: "Alfred Schutz, Berger & Luckmann",
        example: "Berger and Luckmann's The Social Construction of Reality (1966) became the canonical text.",
        tags: ["paradigm", "phenomenology"],
        status: "landmark",
      },
      {
        name: "Exchange theory",
        description: "Social behavior as exchange of rewards and costs.",
        keyFact: "Homans imported behaviorist and economic principles: actors choose actions with the highest expected net reward; relationships persist when both sides perceive equity.",
        theorist: "George Homans, Peter Blau",
        tags: ["paradigm", "rational"],
        xref: ["economics", "psychology"],
        status: "contested",
      },
      {
        name: "Rational choice sociology",
        description: "Aggregate social patterns from individual utility maximization.",
        keyFact: "James Coleman's Foundations of Social Theory (1990) tried to ground sociology in micro-foundations of purposive action plus a macro-to-micro-to-macro Coleman boat.",
        theorist: "James Coleman, Raymond Boudon",
        tags: ["paradigm", "rational"],
        xref: ["economics"],
        status: "contested",
      },
      {
        name: "Critical theory",
        description: "Diagnose domination, point toward emancipation.",
        keyFact: "Frankfurt School fused Marx, Weber, and Freud to analyze how mass culture and instrumental reason sustain capitalist domination even without overt coercion.",
        theorist: "Horkheimer, Adorno, Marcuse, Habermas",
        example: "Dialectic of Enlightenment (1944) argued the Enlightenment's logic of mastery turned on itself.",
        tags: ["paradigm", "critical", "Frankfurt"],
        xref: ["philosophy"],
        status: "landmark",
      },
      {
        name: "Structuralism",
        description: "Surface phenomena reflect deep underlying structures.",
        keyFact: "Borrowing from Saussurean linguistics, structural anthropology treated myths, kinship, and rituals as combinatoric systems of binary oppositions.",
        theorist: "Lévi-Strauss, early Foucault",
        tags: ["paradigm", "structure"],
        xref: ["linguistics"],
        status: "contested",
      },
      {
        name: "Post-structuralism",
        description: "Meaning is unstable, power is dispersed.",
        keyFact: "Foucault and others argued power/knowledge operates through dispersed discourses and practices rather than top-down ideology; subjects are constituted by the discourses they inhabit.",
        theorist: "Foucault, Derrida, Deleuze",
        tags: ["paradigm", "power", "discourse"],
        xref: ["philosophy"],
        status: "contested",
      },
      {
        name: "Feminist sociology",
        description: "Gender as a primary axis of social organization.",
        keyFact: "Treats patriarchy and gendered labor as constitutive of social structure, not derivative of class; later waves added race and sexuality (intersectionality) as co-constitutive axes.",
        theorist: "Dorothy Smith, Patricia Hill Collins",
        tags: ["paradigm", "gender", "intersectionality"],
        status: "landmark",
      },
      {
        name: "Postcolonial sociology",
        description: "Centers the colonial constitution of modernity.",
        keyFact: "Argues canonical sociology was built on imperial categories; modernity, capitalism, and the nation-state cannot be understood without colonial extraction and racialization.",
        theorist: "Stuart Hall, Gurminder Bhambra",
        tags: ["paradigm", "colonial", "global"],
        xref: ["philosophy"],
        status: "contested",
      },
    ],
  },

  // ── Family 3 ──────────────────────────────────────────────────────────────
  {
    slug: "contemporary-theory",
    number: 3,
    name: "Contemporary Theory",
    blurb: "Mid- and late-20th century theorists whose vocabularies still dominate the field.",
    section: "A",
    color: "violet",
    entries: [
      {
        name: "Pierre Bourdieu",
        description: "Habitus, field, and capital as the engine of reproduction.",
        keyFact: "Class advantage is reproduced because actors carry a habitus (durable dispositions) that fits some fields (relational arenas of struggle) better than others; economic, cultural, and social capital are convertible.",
        theorist: "Pierre Bourdieu (1930–2002)",
        example: "Distinction (1979) showed French taste in food, music, and art tracked class fractions tightly.",
        tags: ["habitus", "capital", "reproduction"],
        status: "landmark",
      },
      {
        name: "Erving Goffman",
        description: "Dramaturgy and the interaction order.",
        keyFact: "The self is staged: front- and back-stage regions, impression management, face-work, and frame analysis make the interaction order a distinct level of social reality.",
        theorist: "Erving Goffman (1922–1982)",
        example: "The Presentation of Self in Everyday Life (1959) is the canonical text; Asylums (1961) introduced total institutions.",
        tags: ["dramaturgy", "interaction"],
        xref: ["psychology"],
        status: "landmark",
      },
      {
        name: "Michel Foucault",
        description: "Disciplinary power and biopower.",
        keyFact: "Modern power works through surveillance, normalization, and the production of subjects (discipline) and through managing populations as biological aggregates (biopower).",
        theorist: "Michel Foucault (1926–1984)",
        example: "Discipline and Punish (1975) uses Bentham's Panopticon as the figure of disciplinary modernity.",
        tags: ["power", "discipline", "biopower"],
        xref: ["philosophy"],
        status: "landmark",
      },
      {
        name: "Jürgen Habermas",
        description: "Communicative action and the public sphere.",
        keyFact: "Distinguished system (money, power) from lifeworld (communicative action oriented to mutual understanding); democracy depends on a functioning public sphere protected from system colonization.",
        theorist: "Jürgen Habermas (b. 1929)",
        tags: ["public-sphere", "communication", "Frankfurt"],
        xref: ["philosophy", "governance"],
        status: "landmark",
      },
      {
        name: "Anthony Giddens",
        description: "Structuration: structure and agency are co-constituted.",
        keyFact: "Structures are both the medium and the outcome of action; the duality of structure dissolves the macro/micro divide that organized 20th-century theory.",
        theorist: "Anthony Giddens (b. 1938)",
        tags: ["structuration", "agency"],
        status: "landmark",
      },
      {
        name: "Niklas Luhmann",
        description: "Society as autopoietic communication systems.",
        keyFact: "Society consists of self-reproducing communication systems (economy, law, science, religion) operating through binary codes; not made of people but of communications.",
        theorist: "Niklas Luhmann (1927–1998)",
        tags: ["systems", "autopoiesis"],
        status: "contested",
      },
      {
        name: "Ulrich Beck — risk society",
        description: "Late modernity organized around manufactured risk.",
        keyFact: "Industrial society's wealth distribution gave way to a risk society whose central problem is the social distribution of human-made hazards (Chernobyl, climate, pandemics) that cross class lines.",
        theorist: "Ulrich Beck (1944–2015)",
        example: "Risk Society (1986) was written in the year of Chernobyl and became canonical after.",
        tags: ["risk", "modernity"],
        status: "landmark",
      },
      {
        name: "Bruno Latour — actor-network theory",
        description: "Nonhumans are actors too.",
        keyFact: "Actor-network theory traces how heterogeneous associations of humans, instruments, documents, and things produce facts and durable social orders; the social is an effect, not a cause.",
        theorist: "Bruno Latour (1947–2022)",
        example: "Laboratory Life (1979) ethnographically followed scientific facts being assembled.",
        tags: ["ANT", "science-studies"],
        xref: ["philosophy"],
        status: "contested",
      },
      {
        name: "Manuel Castells — network society",
        description: "Information networks restructure the social.",
        keyFact: "Argued from the 1990s that a space of flows (digital networks of capital, information, and images) is overlaying the space of places, reorganizing economy, identity, and power.",
        theorist: "Manuel Castells (b. 1942)",
        tags: ["networks", "information"],
        status: "landmark",
      },
      {
        name: "Stuart Hall — encoding/decoding",
        description: "Audiences actively interpret media.",
        keyFact: "Media messages are encoded by producers and decoded by audiences via dominant, negotiated, or oppositional readings; meaning is contested at the moment of consumption.",
        theorist: "Stuart Hall (1932–2014)",
        tags: ["culture", "media"],
        status: "landmark",
      },
      {
        name: "Patricia Hill Collins — intersectionality (sociological)",
        description: "Matrix of domination organizing race, class, gender.",
        keyFact: "Black feminist thought analyses how race, class, and gender intersect as a single matrix of domination rather than as additive disadvantages; standpoint shapes knowledge.",
        theorist: "Patricia Hill Collins (b. 1948)",
        tags: ["intersectionality", "standpoint"],
        status: "landmark",
      },
      {
        name: "Zygmunt Bauman — liquid modernity",
        description: "Solidity dissolved into fluid, individualized social forms.",
        keyFact: "Late modern life is liquid: jobs, partners, identities, and communities are short-term and revisable, shifting risk and meaning-work to individuals.",
        theorist: "Zygmunt Bauman (1925–2017)",
        tags: ["modernity", "individualization"],
        status: "contested",
      },
    ],
  },

  // ── Family 4 ──────────────────────────────────────────────────────────────
  {
    slug: "stratification-class",
    number: 4,
    name: "Stratification, Class & Mobility",
    blurb: "Who gets what and why — and how positions are transmitted across generations.",
    section: "B",
    color: "blue",
    entries: [
      {
        name: "Marxian class",
        description: "Class defined by relation to means of production.",
        keyFact: "Two principal classes — owners of capital and wage-laborers — generate exploitation when surplus labor is appropriated as profit. Middle strata are theoretically derivative.",
        tags: ["class", "Marxism"],
        xref: ["economics", "ideologies"],
        status: "contested",
      },
      {
        name: "Weberian stratification",
        description: "Class, status, and party as separate dimensions.",
        keyFact: "Stratification is three-dimensional: class (market position), status (honor and lifestyle), and party (organized power); they vary independently and can cross-cut.",
        tags: ["class", "status", "Weber"],
        status: "landmark",
      },
      {
        name: "Davis–Moore thesis",
        description: "Stratification is functionally necessary.",
        keyFact: "Argued (1945) that unequal rewards motivate the most talented to fill the most functionally important roles. Critics (Tumin 1953) showed it confuses functional importance with bargaining power.",
        tags: ["functionalism", "inequality"],
        status: "contested",
      },
      {
        name: "Status attainment model",
        description: "Path model from origins to destinations.",
        keyFact: "Blau and Duncan (1967) modeled occupational status as a function of parental status mediated by education; launched the modern quantitative sociology of stratification.",
        theorist: "Peter Blau, Otis Dudley Duncan",
        formula: "Y = \\beta_0 + \\beta_1 \\text{FaEd} + \\beta_2 \\text{FaOcc} + \\beta_3 \\text{Ed} + \\varepsilon",
        tags: ["mobility", "status"],
        xref: ["statistics"],
        status: "landmark",
      },
      {
        name: "Intergenerational elasticity (IGE)",
        description: "How much parental earnings predict child earnings.",
        keyFact: "Elasticity β of child log-earnings on parent log-earnings; ~0.5 in the US and UK (lots of persistence), ~0.15 in Denmark and Norway (little). Higher IGE means lower mobility.",
        formula: "\\ln Y_{\\text{child}} = \\alpha + \\beta \\ln Y_{\\text{parent}} + \\varepsilon",
        example: "Chetty and colleagues using US tax data put the rank-rank correlation around 0.34; absolute mobility (probability of out-earning your parents) has fallen from 90% for 1940 birth cohorts to ~50% for 1980s cohorts.",
        tags: ["mobility", "earnings"],
        xref: ["economics", "statistics"],
        status: "landmark",
      },
      {
        name: "Great Gatsby curve",
        description: "Higher inequality correlates with lower mobility.",
        keyFact: "Cross-country plots show countries with higher Gini also have higher IGE; named by Alan Krueger (2012). Causation debated.",
        tags: ["inequality", "mobility"],
        xref: ["economics"],
        status: "contested",
      },
      {
        name: "EGP class schema",
        description: "Cross-nationally comparable class categories.",
        keyFact: "Erikson-Goldthorpe-Portocarero schema (1979) groups occupations by employment relations into ~7 classes (service, routine non-manual, petite bourgeoisie, skilled manual, etc.). Workhorse of European mobility research.",
        tags: ["class", "EGP"],
        status: "landmark",
      },
      {
        name: "Elite reproduction",
        description: "Elites pass advantage via schools, networks, and capital.",
        keyFact: "Bourdieu and Khan show elite schooling produces the dispositions and ties that secure elite jobs; family wealth, not just income, is the dominant transmission channel in the US.",
        tags: ["elites", "reproduction"],
        status: "landmark",
      },
      {
        name: "Wealth vs income inequality",
        description: "Wealth is far more concentrated than income.",
        keyFact: "Top 1% in the US holds ~30% of wealth but ~20% of income; the gap reflects compounded returns, inheritance, and tax treatment. Piketty's r > g formalizes the drift.",
        formula: "r > g \\implies \\text{wealth share rises}",
        tags: ["inequality", "wealth"],
        xref: ["economics"],
        status: "landmark",
      },
      {
        name: "Cumulative advantage / Matthew effect",
        description: "Small early advantages compound over time.",
        keyFact: "Merton (1968) noted famous scientists get more credit for collaborative work than their less famous co-authors; the same logic produces widening trajectories in income, citations, and education.",
        theorist: "Robert K. Merton",
        tags: ["cumulative", "Merton"],
        status: "landmark",
      },
      {
        name: "Precarity",
        description: "Insecurity as the modal labor experience for many.",
        keyFact: "Standing's precariat names workers locked out of stable employment, benefits, and predictable schedules; expanded with platform work, but the category's boundaries are debated.",
        tags: ["work", "labor"],
        xref: ["economics"],
        status: "contested",
      },
      {
        name: "Welfare-state regimes",
        description: "Three worlds shape stratification differently.",
        keyFact: "Esping-Andersen (1990) typology: liberal (US, UK), conservative-corporatist (Germany, France), and social-democratic (Nordics). Each produces different inequality, mobility, and gender patterns.",
        theorist: "Gøsta Esping-Andersen",
        tags: ["welfare", "comparative"],
        xref: ["governance", "economics"],
        status: "landmark",
      },
    ],
  },

  // ── Family 5 ──────────────────────────────────────────────────────────────
  {
    slug: "race-ethnicity",
    number: 5,
    name: "Race & Ethnicity",
    blurb: "Race as a social construction with material consequences — categories, boundaries, and inequalities.",
    section: "B",
    color: "blue",
    entries: [
      {
        name: "Race as social construction",
        description: "Categories are historically produced, not biologically natural.",
        keyFact: "Modern racial categories were consolidated to organize colonial extraction and slave labor; geneticists agree there is more variation within than between racial categories. The categories nonetheless predict life chances because they are institutionalized.",
        tags: ["race", "construction"],
        xref: ["philosophy"],
        status: "landmark",
      },
      {
        name: "Racial formation",
        description: "Race as a sociohistorical project.",
        keyFact: "Omi and Winant (1986/2014) argue race is continuously produced by political projects that link racial categories to interpretive frames and policy.",
        theorist: "Michael Omi, Howard Winant",
        tags: ["race", "politics"],
        status: "landmark",
      },
      {
        name: "Color-blind racism",
        description: "Discrimination without explicit racial language.",
        keyFact: "Bonilla-Silva (2003) catalogues frames — abstract liberalism, naturalization, cultural racism, minimization — that explain persistent inequality without invoking race directly.",
        theorist: "Eduardo Bonilla-Silva",
        tags: ["race", "ideology"],
        status: "contested",
      },
      {
        name: "Residential segregation (dissimilarity index)",
        description: "Measure of how unevenly groups are distributed.",
        keyFact: "Massey and Denton's American Apartheid (1993) shows Black–White hypersegregation persists in major metros; the dissimilarity index reports the share of a group that would need to move to achieve evenness.",
        formula: "D = \\tfrac{1}{2} \\sum_{i} \\left| \\tfrac{b_i}{B} - \\tfrac{w_i}{W} \\right|",
        example: "Detroit and Milwaukee scored D > 0.80 in 2020; integrated metros score D < 0.40.",
        tags: ["segregation", "metric"],
        xref: ["statistics"],
        status: "landmark",
      },
      {
        name: "Audit studies of discrimination",
        description: "Matched applications reveal hiring discrimination.",
        keyFact: "Pager (2003) sent matched testers to entry-level jobs; Black applicants without records were called back less often than White applicants with felonies. Bertrand-Mullainathan (2004) found 50% higher callback for White-sounding names.",
        theorist: "Devah Pager, Marianne Bertrand, Sendhil Mullainathan",
        tags: ["discrimination", "audit"],
        xref: ["economics", "statistics"],
        status: "landmark",
      },
      {
        name: "Intersectionality",
        description: "Categories of inequality co-constitute experience.",
        keyFact: "Crenshaw (1989) showed Black women face discrimination irreducible to race + gender separately; the legal category single-axis discrimination renders their position invisible.",
        theorist: "Kimberlé Crenshaw",
        tags: ["intersectionality", "race", "gender"],
        status: "landmark",
      },
      {
        name: "Immigrant assimilation models",
        description: "From straight-line to segmented assimilation.",
        keyFact: "Park's classical model assumed monotonic absorption into the host society; Portes and Zhou (1993) introduced segmented assimilation — depending on context, second-generation outcomes may converge upward, downward, or selectively preserve ethnic ties.",
        theorist: "Robert Park, Alejandro Portes",
        tags: ["immigration", "assimilation"],
        status: "landmark",
      },
      {
        name: "Ethnic enclave economy",
        description: "Co-ethnic businesses cushion immigrant integration.",
        keyFact: "Wilson and Portes (1980) on Cuban Miami: dense co-ethnic markets provide jobs and trust, sometimes producing returns to education comparable to the primary labor market.",
        tags: ["immigration", "enclave"],
        xref: ["economics"],
        status: "contested",
      },
      {
        name: "Symbolic boundaries",
        description: "Lines individuals draw between us and them.",
        keyFact: "Lamont and Molnár distinguish symbolic boundaries (mental classifications) from social boundaries (institutionalized practices); ethnic and racial group-making works by hardening symbolic into social boundaries.",
        theorist: "Michèle Lamont",
        tags: ["boundaries", "culture"],
        status: "landmark",
      },
      {
        name: "One-drop rule and hypodescent",
        description: "US racial classification rule assigning mixed-race people to the subordinate group.",
        keyFact: "The one-drop rule was codified into state law during Jim Crow; experiments still find Americans more readily classify ambiguous faces as Black than as White (Ho et al. 2011).",
        tags: ["race", "classification"],
        status: "landmark",
      },
      {
        name: "Colorism",
        description: "Skin-tone gradation within racial categories.",
        keyFact: "Within Black, Latino, and South Asian populations, lighter skin predicts higher earnings, education, and marriage outcomes — a within-group inequality that color-blind frameworks miss.",
        tags: ["colorism", "skin-tone"],
        status: "landmark",
      },
      {
        name: "Racialized state",
        description: "States classify, count, and allocate by race.",
        keyFact: "Censuses, voter rolls, and policing create the racial categories they purport to measure; comparative work (Loveman, Mora) shows the categories' boundaries shift with political projects.",
        tags: ["state", "race"],
        xref: ["governance"],
        status: "landmark",
      },
    ],
  },

  // ── Family 6 ──────────────────────────────────────────────────────────────
  {
    slug: "gender-sexuality",
    number: 6,
    name: "Gender & Sexuality",
    blurb: "Gender as a social institution; sexuality as historically variable.",
    section: "B",
    color: "sky",
    entries: [
      {
        name: "Sex vs gender",
        description: "Biological sex categories vs social gender roles.",
        keyFact: "Sex was long treated as the biological substrate of gender; feminist sociology argues both are organized by social practices, and intersex variation shows sex itself is not strictly binary.",
        tags: ["gender", "sex"],
        status: "contested",
      },
      {
        name: "Doing gender",
        description: "Gender is performed in interaction.",
        keyFact: "West and Zimmerman (1987) argue gender is not a property but an ongoing accomplishment held accountable to normative conceptions of sex categories.",
        theorist: "Candace West, Don Zimmerman",
        tags: ["doing-gender", "interaction"],
        status: "landmark",
      },
      {
        name: "Gender performativity",
        description: "Gender as iterative performance with no prior essence.",
        keyFact: "Butler's Gender Trouble (1990) argues gender is performatively constituted by the very acts said to express it; subversive performances (drag) denaturalize the heterosexual matrix.",
        theorist: "Judith Butler",
        tags: ["performativity", "queer"],
        xref: ["philosophy"],
        status: "landmark",
      },
      {
        name: "Patriarchy",
        description: "Social system in which men dominate, oppress, and exploit women.",
        keyFact: "Walby (1990) distinguishes six structures — paid work, household labor, sexuality, culture, violence, state — that compose patriarchy and can vary independently.",
        theorist: "Sylvia Walby",
        tags: ["patriarchy", "feminism"],
        status: "contested",
      },
      {
        name: "Gender pay gap",
        description: "Persistent earnings difference between men and women.",
        keyFact: "Raw US gap is ~17% (median full-time); adjusted for occupation, hours, and experience it shrinks to ~5–8%. Goldin's grand convergence argues the residual is mostly the price of temporal flexibility.",
        theorist: "Claudia Goldin",
        formula: "\\Delta = \\overline{w}_m - \\overline{w}_f",
        tags: ["gender", "pay-gap"],
        xref: ["economics"],
        status: "contested",
      },
      {
        name: "Second shift",
        description: "Working mothers do more unpaid household labor.",
        keyFact: "Hochschild and Machung (1989) documented that employed mothers worked roughly a month more per year of housework and childcare than employed fathers; the gap has narrowed but not closed.",
        theorist: "Arlie Hochschild",
        tags: ["domestic-labor", "family"],
        status: "landmark",
      },
      {
        name: "Hegemonic masculinity",
        description: "Currently dominant configuration of masculine practices.",
        keyFact: "Connell (1995) argues masculinity is plural and hierarchical; hegemonic masculinity legitimates men's dominant position over women and over subordinated masculinities. Refined in Connell and Messerschmidt (2005).",
        theorist: "Raewyn Connell",
        tags: ["masculinity", "hegemony"],
        status: "landmark",
      },
      {
        name: "Compulsory heterosexuality",
        description: "Heterosexuality as a political institution, not just preference.",
        keyFact: "Rich (1980) argues women are coerced into heterosexuality through eight forms of male power; the concept underwrites later queer theory.",
        theorist: "Adrienne Rich",
        tags: ["heterosexuality", "feminism"],
        status: "landmark",
      },
      {
        name: "Social construction of sexuality",
        description: "Sexual identities are historically specific.",
        keyFact: "Foucault's History of Sexuality vol. I (1976) traces how 19th-century discourse turned same-sex acts into a homosexual person, an identity rather than a deed.",
        theorist: "Michel Foucault",
        tags: ["sexuality", "construction"],
        xref: ["philosophy"],
        status: "landmark",
      },
      {
        name: "Queer theory",
        description: "Destabilizes fixed sexual and gender categories.",
        keyFact: "Sedgwick's Epistemology of the Closet (1990) and Butler ground a tradition that treats heteronormativity, not homosexuality, as the analytic puzzle.",
        theorist: "Eve Kosofsky Sedgwick, Judith Butler",
        tags: ["queer", "theory"],
        status: "landmark",
      },
      {
        name: "Trans sociology",
        description: "Transgender lives as a window onto gender systems.",
        keyFact: "Stryker, Schilt, and others treat trans experience not as a niche topic but as evidence about how cis gender is institutionally enforced; workplace audit studies (Schilt 2010) show systematic gender-based wage shifts after transition.",
        theorist: "Susan Stryker, Kristen Schilt",
        tags: ["trans", "gender"],
        status: "landmark",
      },
      {
        name: "Reproductive labor",
        description: "Caring, feeding, and birthing as economically essential work.",
        keyFact: "Marxist-feminist analysis (Federici, Glenn) treats reproductive labor — historically unpaid and feminized — as the hidden infrastructure of capitalist production.",
        tags: ["reproduction", "labor"],
        xref: ["economics"],
        status: "landmark",
      },
    ],
  },

  // ── Family 7 ──────────────────────────────────────────────────────────────
  {
    slug: "family-demography",
    number: 7,
    name: "Family, Kinship & Demography",
    blurb: "How households are formed, dissolved, and reproduced — and the population dynamics that follow.",
    section: "B",
    color: "sky",
    entries: [
      {
        name: "Demographic transition",
        description: "Mortality falls then fertility falls.",
        keyFact: "Four-stage model: high birth and death → falling deaths → falling births → low both. Empirically robust across countries since 1800 but the timing and depth of fertility decline vary.",
        formula: "r = \\text{CBR} - \\text{CDR}",
        tags: ["demography", "transition"],
        status: "landmark",
      },
      {
        name: "Second demographic transition",
        description: "Below-replacement fertility and family pluralism.",
        keyFact: "Van de Kaa (1987) and Lesthaeghe argue that since the 1960s rich countries have entered a phase of postponed childbearing, cohabitation, divorce, and below-replacement fertility tied to value change.",
        theorist: "Dirk van de Kaa, Ron Lesthaeghe",
        tags: ["fertility", "transition"],
        status: "landmark",
      },
      {
        name: "Total fertility rate (TFR)",
        description: "Average children per woman at current age-specific rates.",
        keyFact: "Replacement TFR is ~2.1 in low-mortality settings. South Korea hit 0.72 in 2023; most of Europe, Japan, and China are below 1.5. Sub-Saharan Africa remains the only region with TFR > 4 on average.",
        formula: "\\text{TFR} = \\sum_{x} {}_{n}f_x \\cdot n",
        tags: ["fertility", "TFR"],
        status: "landmark",
      },
      {
        name: "Becker household model",
        description: "Family as a production unit choosing child quantity vs quality.",
        keyFact: "Gary Becker (1960, 1981) treated fertility as a constrained choice problem; higher female wages raise the opportunity cost of children and push toward fewer, more invested children.",
        theorist: "Gary Becker",
        tags: ["family", "economics"],
        xref: ["economics"],
        status: "contested",
      },
      {
        name: "Marriage market",
        description: "Mating as a matching problem.",
        keyFact: "Sociologists track assortative mating (educational homogamy has risen sharply in the US since 1960), sex ratios, and search costs as drivers of marriage patterns.",
        tags: ["marriage", "matching"],
        xref: ["economics"],
        status: "landmark",
      },
      {
        name: "Educational homogamy",
        description: "People marry within their education category.",
        keyFact: "College graduates increasingly marry other college graduates; Schwartz and Mare (2005) show US assortative mating by education accounts for a notable share of household-income inequality growth.",
        tags: ["assortative", "marriage"],
        status: "landmark",
      },
      {
        name: "Coleman's social capital in the family",
        description: "Two-parent attention as productive capital.",
        keyFact: "Coleman (1988) argued the resources flowing to a child depend on parental time and within-community closure; later work (Mclanahan, Sara) refined and contested the causal interpretation.",
        theorist: "James Coleman",
        tags: ["family", "social-capital"],
        status: "contested",
      },
      {
        name: "Diverging destinies",
        description: "Family structure diverges by education.",
        keyFact: "McLanahan (2004) showed college-educated US mothers concentrate marriage, delayed childbearing, and high parental investment, while less-educated mothers experience more single parenthood and instability — compounding child outcome gaps.",
        theorist: "Sara McLanahan",
        tags: ["family", "inequality"],
        status: "landmark",
      },
      {
        name: "Population aging",
        description: "Median age and dependency ratios are rising.",
        keyFact: "Japan's median age passed 49 in 2024; Italy, Germany, and South Korea follow. Old-age dependency ratios above 0.5 stress pension and care systems and re-politicize immigration.",
        formula: "\\text{OADR} = \\tfrac{\\text{pop } 65+}{\\text{pop } 15{-}64}",
        tags: ["aging", "demography"],
        status: "landmark",
      },
      {
        name: "Life-course perspective",
        description: "Lives as trajectories shaped by timing and context.",
        keyFact: "Elder (1974) studied Children of the Great Depression, showing the same event has different effects depending on age and gender at exposure; spawned a whole tradition of trajectory and transition analysis.",
        theorist: "Glen Elder",
        tags: ["life-course", "trajectories"],
        status: "landmark",
      },
      {
        name: "Cohort vs period effects",
        description: "Distinguishing the era from the generation.",
        keyFact: "Sociologists separate age (lifecycle), period (year), and cohort (birth year) effects on social outcomes; identification is fundamentally hard because the three are linearly related.",
        formula: "\\text{Age} + \\text{Cohort} = \\text{Period}",
        tags: ["demography", "identification"],
        xref: ["statistics"],
        status: "landmark",
      },
      {
        name: "Migration models — push/pull and networks",
        description: "Macroeconomics and meso-networks both drive migration.",
        keyFact: "Wage gaps and political conditions push and pull migrants; once flows start, kinship and village networks lower migration costs for later movers (Massey et al.).",
        theorist: "Douglas Massey",
        tags: ["migration", "networks"],
        xref: ["economics"],
        status: "landmark",
      },
    ],
  },

  // ── Family 8 ──────────────────────────────────────────────────────────────
  {
    slug: "organizations-work",
    number: 8,
    name: "Organizations, Work & Bureaucracy",
    blurb: "Formal organizations, labor markets, and the institutional pressures on firms.",
    section: "B",
    color: "blue",
    entries: [
      {
        name: "Bureaucracy (ideal type)",
        description: "Hierarchical, rule-bound, expertise-based administration.",
        keyFact: "Weber's ideal type: hierarchy, written rules, technical expertise, careers, files. Argued bureaucracy is technically superior to alternatives but produces the iron cage.",
        theorist: "Max Weber",
        tags: ["bureaucracy", "Weber"],
        status: "landmark",
      },
      {
        name: "Iron law of oligarchy",
        description: "All organizations tend toward rule by a few.",
        keyFact: "Michels (1911) studied European socialist parties and concluded that even democratic organizations end up dominated by an entrenched leadership for technical and psychological reasons.",
        theorist: "Robert Michels",
        tags: ["oligarchy", "organizations"],
        status: "contested",
      },
      {
        name: "Bounded rationality",
        description: "Real decision-makers satisfice, they do not maximize.",
        keyFact: "Simon (1947, 1957) replaced the rational-actor with an actor of limited information and computation who searches for satisfactory options until time runs out. Foundation for organizational behavior.",
        theorist: "Herbert Simon",
        tags: ["rationality", "decisions"],
        xref: ["economics", "psychology"],
        status: "landmark",
      },
      {
        name: "Garbage can model",
        description: "Decisions emerge from streams of problems, solutions, and participants.",
        keyFact: "Cohen-March-Olsen (1972) describe organized anarchies where solutions chase problems; decisions are jointly produced when streams happen to meet.",
        theorist: "Cohen, March, Olsen",
        tags: ["decisions", "anarchy"],
        status: "contested",
      },
      {
        name: "Institutional isomorphism",
        description: "Organizations in a field grow alike.",
        keyFact: "DiMaggio and Powell (1983) identify coercive, mimetic, and normative isomorphism — pressures that lead organizations to adopt the same structures even without efficiency gains.",
        theorist: "Paul DiMaggio, Walter Powell",
        tags: ["institutional", "isomorphism"],
        status: "landmark",
      },
      {
        name: "Loose coupling",
        description: "Formal structure and actual practice are loosely connected.",
        keyFact: "Meyer and Rowan (1977) and Weick (1976) describe schools and other organizations as displaying ceremonial conformity to formal rules while practice runs by other logics.",
        theorist: "John Meyer, Brian Rowan, Karl Weick",
        tags: ["organizations", "ceremony"],
        status: "landmark",
      },
      {
        name: "Resource dependence",
        description: "Organizations depend on others for critical resources.",
        keyFact: "Pfeffer and Salancik (1978) ground organizational behavior in dependencies on external suppliers of resources; strategies include diversification, mergers, and interlocks.",
        theorist: "Jeffrey Pfeffer, Gerald Salancik",
        tags: ["organizations", "resources"],
        xref: ["economics"],
        status: "landmark",
      },
      {
        name: "Internal labor market",
        description: "Firms allocate jobs via internal ladders, not external markets.",
        keyFact: "Doeringer and Piore (1971) described primary internal labor markets where promotion and wages follow administrative rules, insulating jobs from external competition.",
        theorist: "Peter Doeringer, Michael Piore",
        tags: ["work", "labor-market"],
        xref: ["economics"],
        status: "landmark",
      },
      {
        name: "Dual labor market",
        description: "Primary and secondary sectors with sharply different conditions.",
        keyFact: "Same authors distinguish stable, high-wage primary jobs from unstable, low-wage secondary jobs; access depends on race, gender, and credentials, not just human capital.",
        tags: ["labor-market", "duality"],
        xref: ["economics"],
        status: "contested",
      },
      {
        name: "Strength of weak ties (jobs)",
        description: "Casual ties matter more than close ones in job search.",
        keyFact: "Granovetter (1973, 1974) found most professionals heard about their job from acquaintances, not close friends — weak ties bridge across networks and carry novel information.",
        theorist: "Mark Granovetter",
        tags: ["networks", "jobs"],
        status: "landmark",
      },
      {
        name: "Emotional labor",
        description: "Managing feelings as paid work.",
        keyFact: "Hochschild's The Managed Heart (1983) studied flight attendants; emotional labor — producing required feelings in customers and oneself — is increasingly demanded in service work and is unequally distributed.",
        theorist: "Arlie Hochschild",
        tags: ["work", "emotion"],
        status: "landmark",
      },
      {
        name: "Platform / gig labor",
        description: "Algorithmic management at the boundary of employment.",
        keyFact: "Ride-share and delivery platforms (Uber, DoorDash, Deliveroo) use algorithmic dispatch and rating systems to manage workers classified as contractors; sociology studies the resulting precarity and worker resistance.",
        tags: ["platform", "gig", "labor"],
        xref: ["economics"],
        status: "contested",
      },
    ],
  },
];
