import type { Family } from "./types";

// Families 7-12: end of Section B (Schools) + Section C (Warfare Domains).
export const FAMILIES_7_12: Family[] = [
  // -- Family 7 --------------------------------------------------------------
  {
    slug: "copenhagen-securitization",
    number: 7,
    name: "The Copenhagen School & Securitization",
    blurb: "The influential theory of security as a speech act -- how issues become \"security.\"",
    section: "B",
    color: "sky",
    dataSource: "Discourse/agenda-setting corpora; see /political-science for framing.",
    entries: [
      {
        name: "The Copenhagen School",
        description: "Security as a socially constructed practice.",
        keyFact: "An approach combining securitization, sectors of security, and regional security complexes; treats \"security\" as what actors do with the word, across military, political, economic, societal, and environmental sectors.",
        lineage: "From the wideners' debate -- a constructivist synthesis.",
        lineageParents: [{ name: "The wideners vs traditionalists debate", edgeLabel: "constructivist synthesis" }],
        figures: "Barry Buzan, Ole Waever, Jaap de Wilde.",
        era: "1990s (Copenhagen).",
        example: "Buzan, Waever, de Wilde, Security: A New Framework for Analysis (1998).",
        tags: ["school", "securitization", "foundational"],
      },
      {
        name: "Securitization theory",
        description: "\"Security\" is a speech act.",
        keyFact: "An issue becomes a security issue when an actor frames it as an existential threat requiring emergency measures and an audience accepts that framing -- moving it beyond normal politics.",
        lineage: "The core move of the Copenhagen School.",
        lineageParents: [{ name: "The Copenhagen School", edgeLabel: "core theoretical move" }],
        figures: "Ole Waever.",
        era: "1995.",
        example: "Waever, \"Securitization and Desecuritization\" (1995).",
        critiques: "The Paris School and others charge that dramatic \"speech acts\" underplay the routinized practices of security professionals.",
        tags: ["securitization", "foundational"],
      },
      {
        name: "Desecuritization",
        description: "Returning issues to normal politics.",
        keyFact: "The normatively preferred reverse move -- shifting an issue out of the emergency \"security\" frame and back into ordinary political bargaining.",
        lineageParents: [{ name: "Securitization theory", edgeLabel: "reverse move" }],
        figures: "Ole Waever.",
        example: "The post-1990 European integration project as partial desecuritization of intra-European relations.",
        tags: ["securitization"],
      },
      {
        name: "Sectors of security",
        description: "Five arenas of threat.",
        keyFact: "Security dynamics differ across military, political, economic, societal, and environmental sectors, each with its own referent objects and logics.",
        lineage: "The Copenhagen School's widening framework.",
        lineageParents: [{ name: "The Copenhagen School", edgeLabel: "sectoral widening" }],
        figures: "Buzan, Waever, de Wilde.",
        example: "The five-sector matrix in Security: A New Framework for Analysis (1998).",
        tags: ["securitization"],
      },
      {
        name: "Regional security complex theory",
        description: "Security clusters geographically.",
        keyFact: "Security interdependence bundles states into regional complexes whose members' securities are so linked they cannot be analyzed apart; the region is a key level of analysis.",
        lineage: "The spatial arm of the Copenhagen School.",
        lineageParents: [{ name: "The Copenhagen School", edgeLabel: "spatial arm" }],
        figures: "Barry Buzan, Ole Waever.",
        era: "2003.",
        example: "Buzan and Waever, Regions and Powers (2003).",
        tags: ["securitization", "regional"],
      },
      {
        name: "The Paris School (security as practice)",
        description: "Everyday security professionals.",
        keyFact: "Security is produced less by dramatic speech acts than by the routine practices of professionals (police, border, intelligence) and technologies of surveillance and risk management.",
        lineage: "A sociological critique/extension of the Copenhagen School.",
        lineageParents: [{ name: "The Copenhagen School", edgeLabel: "sociological critique" }],
        figures: "Didier Bigo.",
        era: "2000s.",
        example: "Bigo's work on the \"security field\" and border-management practices.",
        tags: ["school", "critical"],
      },
      {
        name: "The ethics of securitization",
        description: "Is securitizing an issue good or bad?",
        keyFact: "The debate over whether framing an issue as \"security\" helps (mobilizing resources) or harms (militarizing, suspending normal politics, excluding dissent); presented without adjudication.",
        example: "Post-9/11 counterterrorism as a case where securitization's costs and benefits are debated.",
        tags: ["securitization", "debate"],
      },
    ],
  },

  // -- Family 8 --------------------------------------------------------------
  {
    slug: "feminist-gender-security",
    number: 8,
    name: "Feminist & Gender Approaches to Security",
    blurb: "How gender shapes, and is shaped by, war and security.",
    section: "B",
    color: "sky",
    dataSource: "Sex-disaggregated conflict data (e.g. UCDP-linked); WPS indicators.",
    entries: [
      {
        name: "Feminist security studies",
        description: "Gender as a lens on security.",
        keyFact: "Asks where the women are in world politics, treats gender as constitutive of war and security, and argues that ignoring gendered power distorts both analysis and policy.",
        lineage: "From critical security studies + feminist IR.",
        lineageParents: [{ name: "Critical security studies (broad)", edgeLabel: "feminist branch" }],
        figures: "Cynthia Enloe, J. Ann Tickner.",
        era: "1980s-1990s.",
        example: "Enloe, Bananas, Beaches and Bases (1990); Tickner, Gender in International Relations (1992).",
        tags: ["school", "feminist", "foundational"],
      },
      {
        name: "Gendered security & the \"protection racket\"",
        description: "Who protects whom, from what.",
        keyFact: "The \"protection\" of women can justify militarism and male authority; feminist analysis unpacks how security discourses rest on gendered roles of protector and protected.",
        lineageParents: [{ name: "Feminist security studies", edgeLabel: "gendered-protection argument" }],
        figures: "Iris Marion Young, Cynthia Enloe.",
        example: "Young, \"The Logic of Masculinist Protection\" (2003).",
        tags: ["feminist"],
      },
      {
        name: "Women, Peace and Security (WPS) agenda",
        description: "Gender in peace and security policy.",
        keyFact: "The policy framework (UN Security Council Resolution 1325 and successors) on women's participation in peace processes, protection from conflict-related violence, and gender in prevention.",
        lineage: "Feminist advocacy institutionalized.",
        lineageParents: [{ name: "Feminist security studies", edgeLabel: "policy institutionalization" }],
        era: "2000 onward.",
        example: "UNSCR 1325 (2000) and its successor resolutions.",
        critiques: "Critics argue the agenda has been co-opted into instrumental \"add women and stir\" policy; defenders point to genuine normative and institutional shifts.",
        tags: ["feminist", "policy"],
        xref: ["governance"],
      },
      {
        name: "Masculinities and militarism",
        description: "How manhood is tied to war.",
        keyFact: "Examines how ideals of masculinity are constructed through, and sustain, military institutions and the legitimacy of force.",
        lineageParents: [{ name: "Feminist security studies", edgeLabel: "masculinities analysis" }],
        figures: "Cynthia Cockburn, R.W. Connell.",
        example: "Cockburn's fieldwork on militarized masculinities across post-conflict settings.",
        tags: ["feminist", "critical"],
      },
      {
        name: "Conflict-related sexual violence (as a security concept)",
        description: "Sexual violence as a weapon and war crime.",
        keyFact: "The recognition that sexual violence in conflict is often strategic and systematic rather than incidental, and is now treated as a security and international-criminal-law concern.",
        example: "UNSCR 1820 (2008) recognizing conflict-related sexual violence as a security-council matter.",
        tags: ["feminist", "law of war"],
        xref: ["governance"],
      },
      {
        name: "Feminist critiques of the security state",
        description: "Security for whom?",
        keyFact: "Argues that state and military security can be purchased at the expense of individual, especially women's, security, and that the two are often conflated.",
        lineage: "Feminist + human security.",
        lineageParents: [{ name: "Feminist security studies", edgeLabel: "critique of the state" }, { name: "Human security", edgeLabel: "individual-security convergence" }],
        example: "Tickner's critique of \"national security\" from a feminist vantage.",
        tags: ["feminist", "debate"],
      },
    ],
  },

  // -- Family 9 --------------------------------------------------------------
  {
    slug: "constructivist-peace-studies",
    number: 9,
    name: "Constructivist & Peace-Studies Approaches",
    blurb: "Ideas, identity, and norms in security; and the study of peace itself.",
    section: "B",
    color: "cyan",
    dataSource: "Norms/treaty-adoption data; peace-agreement datasets.",
    entries: [
      {
        name: "Constructivist security studies",
        description: "Security interests are socially constructed.",
        keyFact: "Threats, interests, and identities are produced by shared ideas and norms, not fixed by material structure; \"anarchy is what states make of it.\"",
        lineage: "From IR constructivism into security studies.",
        figures: "Alexander Wendt, Peter Katzenstein.",
        era: "1990s.",
        example: "Katzenstein (ed.), The Culture of National Security (1996).",
        tags: ["school", "constructivist"],
        xref: ["political-science"],
      },
      {
        name: "Security community",
        description: "When war becomes unthinkable.",
        keyFact: "A group of states among whom there is a dependable expectation of peaceful change and no expectation of war (e.g. the transatlantic community); built through shared identity and institutions.",
        lineage: "Deutsch, revived by constructivists.",
        figures: "Karl Deutsch, Emanuel Adler, Michael Barnett.",
        example: "Adler and Barnett (eds.), Security Communities (1998).",
        tags: ["constructivist", "peace"],
      },
      {
        name: "Norms and the \"nuclear taboo\"",
        description: "Normative constraints on force.",
        keyFact: "Constructivists argue that norms (against nuclear use, against chemical weapons, against assassination) can constrain state behavior independent of pure cost-benefit calculation.",
        lineageParents: [{ name: "Constructivist security studies", edgeLabel: "norms extension" }],
        figures: "Nina Tannenwald, Richard Price.",
        example: "Tannenwald, The Nuclear Taboo (2007).",
        critiques: "Rationalist scholars argue what looks like a norm often reflects underlying material deterrence.",
        tags: ["constructivist", "norms"],
      },
      {
        name: "Peace studies / peace research",
        description: "The scientific study of peace and violence.",
        keyFact: "An interdisciplinary field analyzing the causes of violence and the conditions for durable peace, often normatively committed to reducing violence.",
        lineage: "Postwar peace research.",
        figures: "Johan Galtung, Kenneth Boulding.",
        era: "1950s-1960s.",
        example: "The Journal of Peace Research (founded 1964).",
        tags: ["school", "peace", "foundational"],
      },
      {
        name: "Negative vs positive peace",
        description: "Two meanings of peace.",
        keyFact: "Negative peace is the absence of direct violence; positive peace is the presence of just structures and the absence of structural violence -- a broader and contested goal.",
        lineageParents: [{ name: "Peace studies / peace research", edgeLabel: "conceptual distinction" }],
        figures: "Johan Galtung.",
        example: "Galtung, \"Violence, Peace, and Peace Research\" (1969).",
        tags: ["peace", "foundational"],
      },
      {
        name: "Structural & cultural violence",
        description: "Harm without a visible perpetrator.",
        keyFact: "Structural violence is harm built into social/economic arrangements (poverty, exclusion); cultural violence legitimizes it -- both widen \"security\" beyond direct force.",
        lineageParents: [{ name: "Peace studies / peace research", edgeLabel: "extended violence concept" }],
        figures: "Johan Galtung.",
        example: "Galtung, \"Cultural Violence\" (1990).",
        critiques: "Critics argue \"structural violence\" stretches the concept of violence past analytic usefulness.",
        tags: ["peace", "critical"],
      },
      {
        name: "Conflict resolution & transformation",
        description: "Ending and remaking conflicts.",
        keyFact: "The theory and practice of settling disputes and transforming the relationships and structures that drive them (mediation, reconciliation, peacebuilding).",
        lineageParents: [{ name: "Peace studies / peace research", edgeLabel: "applied field" }],
        figures: "John Paul Lederach, Johan Galtung.",
        example: "Lederach, Building Peace (1997).",
        tags: ["peace", "policy"],
        xref: ["governance"],
      },
      {
        name: "Liberal peace / democratic-peace mechanisms",
        description: "Peace through liberal order.",
        keyFact: "The argument that democracy, trade interdependence, and international institutions jointly reduce war among states (the \"Kantian tripod\"); its causal weight is debated.",
        figures: "Immanuel Kant (roots), Bruce Russett, John Oneal.",
        example: "Russett and Oneal, Triangulating Peace (2001).",
        critiques: "Realists argue apparent peace effects reflect shared alliances or hegemonic order rather than liberal institutions.",
        tags: ["peace"],
        xref: ["political-science"],
      },
    ],
  },

  // -- Family 10 -------------------------------------------------------------
  {
    slug: "land-warfare",
    number: 10,
    name: "Land Warfare & Ground Forces",
    blurb: "Doctrines, force structures, and capability categories of war on land.",
    section: "C",
    color: "teal",
    dataSource: "SIPRI (arms transfers by category); NARA RG330 (force records).",
    entries: [
      {
        name: "Combined arms",
        description: "Integrating different arms for mutual reinforcement.",
        keyFact: "Coordinating infantry, armor, artillery, engineers, and air so each covers the others' weaknesses, producing effects none achieves alone.",
        example: "The combined-arms breakout at Operation Cobra (Normandy, 1944).",
        tags: ["land", "doctrine"],
      },
      {
        name: "Blitzkrieg / mechanized maneuver",
        description: "Fast, concentrated, combined mechanized offense.",
        keyFact: "Concentrating armor and mobile forces with air support to penetrate and dislocate rather than grind down; a historical archetype of maneuver on land.",
        example: "The 1940 German campaign in France.",
        tags: ["land", "doctrine"],
        xref: ["history"],
      },
      {
        name: "AirLand Battle",
        description: "Deep and close battle fought together.",
        keyFact: "A late-Cold-War Western doctrine to defeat echeloned forces by striking throughout their depth while winning the close fight; an RMA precursor.",
        example: "US Army Field Manual FM 100-5 (1982).",
        tags: ["land", "doctrine"],
      },
      {
        name: "Infantry (arm)",
        description: "Foot soldiers as the core of ground combat.",
        keyFact: "The arm that seizes and holds ground and operates in all terrain; the irreducible element of land power.",
        tags: ["land", "force"],
      },
      {
        name: "Armor / mechanized forces (arm)",
        description: "Protected, mobile, direct-fire ground power.",
        keyFact: "Tanks and fighting vehicles provide the mobile, protected firepower around which maneuver is built.",
        tags: ["land", "force"],
      },
      {
        name: "Artillery & fires (arm)",
        description: "Indirect firepower and joint fires.",
        keyFact: "The arm delivering massed indirect fire and, in modern usage, coordinating joint \"fires\"; historically the greatest cause of battlefield casualties.",
        tags: ["land", "force"],
      },
      {
        name: "Army echelons (force structure)",
        description: "From squad to field army.",
        keyFact: "Land forces are organized in a nested hierarchy -- squad, platoon, company, battalion, brigade, division, corps, army -- each a span of command and capability.",
        tags: ["land", "force structure"],
      },
      {
        name: "Special operations forces (category)",
        description: "Small, selected units for special missions.",
        keyFact: "Highly trained forces for reconnaissance, unconventional warfare, and other missions beyond conventional units' scope; described by role, not method.",
        tags: ["land", "force"],
      },
      {
        name: "Military logistics",
        description: "Sustaining forces in the field.",
        keyFact: "The movement and supply of forces (fuel, ammunition, food, maintenance, medical); campaigns are bounded by what logistics can sustain.",
        example: "Van Creveld, Supplying War (1977).",
        tags: ["land", "logistics"],
      },
      {
        name: "Command and control (C2)",
        description: "Directing forces toward the aim.",
        keyFact: "The exercise of authority and direction over assigned forces; modern C2 stresses mission command -- intent-based delegation under uncertainty.",
        tags: ["land", "C2"],
      },
      {
        name: "Fortification & area denial (category)",
        description: "Shaping ground to deny movement.",
        keyFact: "The category of prepared defenses and obstacles used to canalize or deny an adversary's movement; described as a capability class, not a construction guide.",
        tags: ["land", "doctrine"],
      },
      {
        name: "Armored & mechanized vehicle classes",
        description: "Categories of ground platforms.",
        keyFact: "The taxonomy of ground platforms -- main battle tanks, infantry fighting vehicles, armored personnel carriers, self-propelled artillery -- by role and protection class.",
        tags: ["land", "platforms"],
        xref: ["engineering"],
      },
    ],
  },

  // -- Family 11 -------------------------------------------------------------
  {
    slug: "naval-maritime-warfare",
    number: 11,
    name: "Naval & Maritime Warfare",
    blurb: "Sea power, fleet composition, and maritime capability categories.",
    section: "C",
    color: "teal",
    dataSource: "SIPRI (naval arms transfers); order-of-battle references.",
    entries: [
      {
        name: "Sea control & sea denial",
        description: "Using or contesting the sea.",
        keyFact: "Sea control is the ability to use a maritime area for one's own purposes; sea denial merely prevents an adversary from using it -- a cheaper, defensive aim.",
        tags: ["maritime", "doctrine"],
      },
      {
        name: "Power projection from the sea",
        description: "Influencing events ashore from the maritime domain.",
        keyFact: "Using naval forces (carrier aviation, amphibious forces, naval fires) to affect events on land far from home bases.",
        tags: ["maritime", "doctrine"],
      },
      {
        name: "Naval blockade (category)",
        description: "Interdicting an adversary's maritime commerce.",
        keyFact: "A recognized instrument cutting an adversary off from seaborne trade or supply; a strategic/legal category, described without operational method.",
        tags: ["maritime", "doctrine"],
      },
      {
        name: "Fleet-in-being",
        description: "Deterring by preserving a threat.",
        keyFact: "A weaker fleet influences events by remaining a latent threat that ties down superior forces, without seeking battle.",
        example: "The German High Seas Fleet after Jutland (1916).",
        tags: ["maritime", "doctrine"],
      },
      {
        name: "Anti-access / area denial (A2/AD)",
        description: "Keeping an adversary out.",
        keyFact: "Layered capabilities (long-range sensors and weapons, mines, submarines) intended to raise the cost of operating in a maritime area; a capability concept.",
        tags: ["maritime", "doctrine"],
      },
      {
        name: "Surface combatants (class)",
        description: "The carrier, cruiser, destroyer, frigate categories.",
        keyFact: "The taxonomy of major surface warships by role and displacement -- capital ships, escorts, and patrol vessels.",
        tags: ["maritime", "platforms"],
      },
      {
        name: "Submarines (class)",
        description: "Undersea platforms by role.",
        keyFact: "The categories of submarine -- attack (SSN/SSK) and ballistic-missile (SSBN) -- defined by role, propulsion, and armament class; a platform taxonomy only.",
        tags: ["maritime", "platforms", "nuclear"],
      },
      {
        name: "Aircraft carriers & naval aviation (class)",
        description: "Mobile airpower at sea.",
        keyFact: "The carrier as a mobile airbase and the organizing center of a modern surface fleet; a platform/role category.",
        tags: ["maritime", "platforms", "airpower"],
      },
      {
        name: "Amphibious warfare (category)",
        description: "Projecting land power from the sea.",
        keyFact: "The capability class for landing and sustaining ground forces across a shoreline; described by role, not operational plan.",
        tags: ["maritime", "doctrine"],
      },
      {
        name: "Naval mine warfare (category)",
        description: "Sea mines and countermeasures as a class.",
        keyFact: "Mines and mine countermeasures as a recognized capability category shaping access to sea areas; described at the category/governance level, no employment detail.",
        tags: ["maritime", "platforms"],
      },
      {
        name: "Maritime chokepoints & sea lines of communication",
        description: "The geography of sea power.",
        keyFact: "The straits and shipping lanes whose control shapes trade and naval movement (e.g. Hormuz, Malacca, Suez); a strategic-geography concept.",
        tags: ["maritime", "geography"],
        xref: ["governance"],
      },
      {
        name: "Naval order of battle (force structure)",
        description: "How fleets are composed and grouped.",
        keyFact: "The composition of a navy into task forces, groups, and squadrons around capital ships and their escorts; a force-structure concept.",
        tags: ["maritime", "force structure"],
      },
    ],
  },

  // -- Family 12 -------------------------------------------------------------
  {
    slug: "air-space-power",
    number: 12,
    name: "Air & Space Power",
    blurb: "The doctrines and capability categories of the air and space domains.",
    section: "C",
    color: "emerald",
    dataSource: "SIPRI (aircraft/air-defense transfers); NARA RG330.",
    entries: [
      {
        name: "Command of the air / air superiority",
        description: "Freedom to use the air and deny it.",
        keyFact: "Controlling the air domain so friendly forces can operate and the adversary's air power cannot; a precondition assumed by most modern operations.",
        tags: ["airpower", "doctrine"],
      },
      {
        name: "Strategic bombing (doctrine/history)",
        description: "Attacking an adversary's war-making capacity.",
        keyFact: "The doctrinal category of striking industrial, infrastructural, or morale targets to erode capacity or will; discussed as doctrine and history, not targeting.",
        critiques: "Postwar strategic-bombing surveys and later scholarship contest strong claims that morale-focused bombing shortens wars.",
        tags: ["airpower", "doctrine"],
        xref: ["history"],
      },
      {
        name: "Close air support & interdiction",
        description: "Airpower for the surface battle.",
        keyFact: "Close air support aids ground forces in direct contact; interdiction strikes forces and supply before they reach the fight -- two roles of tactical airpower.",
        tags: ["airpower", "doctrine"],
      },
      {
        name: "Suppression of enemy air defenses (category)",
        description: "Enabling air operations.",
        keyFact: "The mission category of neutralizing an adversary's air defenses to permit air operations; named as a role, not a method.",
        tags: ["airpower", "doctrine"],
      },
      {
        name: "Integrated air and missile defense (category)",
        description: "Defending against air and missile threats.",
        keyFact: "The layered capability category -- sensors and interceptors -- for defending against aircraft, cruise, and ballistic missiles; a defensive concept.",
        tags: ["airpower", "defense"],
      },
      {
        name: "Combat aircraft (class)",
        description: "Fighter, bomber, attack, ISR categories.",
        keyFact: "The taxonomy of military aircraft by role -- air superiority, multirole, bomber, attack, transport, tanker, and ISR platforms.",
        tags: ["airpower", "platforms"],
      },
      {
        name: "Unmanned aerial systems (class)",
        description: "Drones by role and class.",
        keyFact: "The category of remotely piloted and autonomous aircraft, classed by size, endurance, and role (ISR, strike, loitering); a platform taxonomy.",
        tags: ["airpower", "platforms"],
        xref: ["engineering"],
      },
      {
        name: "Missile categories (class)",
        description: "Cruise, ballistic, hypersonic, air-defense.",
        keyFact: "The taxonomy of guided missiles by trajectory and role -- cruise, ballistic, surface-to-air, anti-ship, hypersonic glide -- described as classes and governed by arms control, with no design content.",
        tags: ["airpower", "platforms", "nuclear"],
      },
      {
        name: "Space as a warfighting domain",
        description: "The contest for orbit.",
        keyFact: "Space provides the ISR, communications, navigation, and warning that modern forces depend on, making it a domain to exploit and protect; a domain concept.",
        tags: ["space", "doctrine"],
      },
      {
        name: "Space-enabling capabilities (category)",
        description: "What space assets provide.",
        keyFact: "The categories of military space support -- reconnaissance, missile warning, satellite communications, and positioning/navigation/timing (e.g. GPS).",
        tags: ["space", "capability"],
        xref: ["astronomy"],
      },
      {
        name: "Counterspace (category, governance-framed)",
        description: "Threats to space systems and their governance.",
        keyFact: "The recognized category of threats to satellites (kinetic, electronic, cyber) and the governance frame (Outer Space Treaty, debris and ASAT-test norms); described as category and law, not method.",
        tags: ["space", "governance"],
        xref: ["governance"],
      },
      {
        name: "Ballistic-missile defense (BMD)",
        description: "Defending against ballistic missiles.",
        keyFact: "The capability class for intercepting ballistic missiles in boost, midcourse, or terminal phase; strategically significant because it interacts with deterrence stability.",
        critiques: "Skeptics argue BMD undermines strategic stability by threatening second-strike forces; defenders argue it counters limited attacks and regional threats.",
        tags: ["space", "defense", "nuclear"],
      },
    ],
  },
];
