import type { Family } from "./types";

// ─────────────────────────────────────────────────────────────────────────────
// SECTION E — Journalism, News & Digital / Networked Media (fuchsia / purple / pink)
// SECTION F — Media Economics, Political & Intercultural (amber / rose / orange / green)
// ─────────────────────────────────────────────────────────────────────────────

export const FAMILIES_12_18: Family[] = [
  // ── Family 12 ──────────────────────────────────────────────────────────────
  {
    slug: "journalism-news",
    number: 12,
    name: "Journalism Studies & News Production",
    blurb: "Gatekeeping, news values, framing, objectivity, and the structural forces that shape what becomes news.",
    section: "E",
    color: "fuchsia",
    entries: [
      {
        name: "Journalism",
        description: "The practice of gathering, verifying, and reporting news.",
        principle: "Journalism produces timely, verified accounts of public affairs, claiming a democratic role of informing citizens and holding power to account.",
        tags: ["journalism"],
      },
      {
        name: "Gatekeeping",
        description: "Editorial selection filters what becomes news.",
        principle: "A limited amount of information passes through a series of \"gates\" controlled by editors and routines, so news is what survives selection; individual, routine, organizational, and system forces all shape the flow.",
        lineage: "A founding news-production concept.",
        figures: "Kurt Lewin (concept); David Manning White (the \"Mr. Gates\" study, 1950); Shoemaker & Reese (levels).",
        era: "1950-",
        tags: ["journalism", "node"],
        xref: ["sociology"],
      },
      {
        name: "News values / newsworthiness",
        description: "What makes an event \"news.\"",
        principle: "Events are selected and played up according to shared criteria — timeliness, proximity, prominence, conflict, negativity, unexpectedness, human interest, and more.",
        lineage: "News sociology.",
        figures: "Galtung & Ruge (1965); Harcup & O'Neill (update).",
        era: "1965-",
        tags: ["journalism", "node"],
      },
      {
        name: "Framing in the news / episodic vs thematic",
        description: "How news frames issues.",
        principle: "News frames define problems and responsibility; episodic frames (individual cases) and thematic frames (broader context) lead audiences to attribute responsibility differently.",
        lineage: "Framing applied to news.",
        figures: "Iyengar; Entman.",
        tags: ["journalism"],
        xref: ["political-science"],
      },
      {
        name: "Objectivity & the norm of neutrality",
        description: "The ideal of detached, balanced reporting.",
        principle: "A professional norm holding that reporters should separate facts from opinion and present issues without favoring a side.",
        lineage: "Professional journalism norms.",
        figures: "Tuchman (\"objectivity as strategic ritual\"); Schudson (history).",
        era: "20th c.",
        critiques: "Whether objectivity is achievable or even coherent is a central, live dispute — critics call it a \"strategic ritual\" (Tuchman) that can produce false balance; presented as a contested ideal, not a settled standard.",
        tags: ["journalism", "node"],
      },
      {
        name: "Hierarchy of influences model",
        description: "Nested forces shape news content.",
        principle: "News content is shaped by forces at nested levels — individual journalists, routines, organizations, social institutions, and social systems (ideology).",
        lineage: "Synthesizes news-production research.",
        figures: "Shoemaker & Reese (Mediating the Message).",
        era: "1990s-",
        tags: ["journalism", "node"],
      },
      {
        name: "Indexing & the sourcing of news",
        description: "News tracks elite debate.",
        principle: "Mainstream news tends to \"index\" the range of viewpoints to the span of debate among official sources, narrowing coverage when elites agree.",
        lineage: "Political-communication news theory.",
        figures: "W. Lance Bennett (1990).",
        era: "1990.",
        tags: ["journalism", "node"],
        xref: ["political-science"],
      },
      {
        name: "The propaganda model",
        description: "Structural filters shape corporate news.",
        principle: "News passing through five \"filters\" (ownership, advertising, sourcing, flak, and a unifying ideology) systematically serves elite interests.",
        lineage: "Critical political economy of media.",
        figures: "Herman & Chomsky (Manufacturing Consent, 1988).",
        era: "1988.",
        critiques: "An influential but strongly contested critical model; described as its authors frame it. Critics dispute the model's causal claims, its portrayal of dissent within elite outlets, and its ability to account for adversarial coverage of specific administrations.",
        tags: ["journalism", "node"],
        xref: ["political-economy", "ideologies"],
      },
      {
        name: "Peace journalism & advocacy/interpretive traditions",
        description: "Alternatives to detached reporting.",
        principle: "Normative models proposing that journalism should consciously frame conflict toward resolution (peace journalism) or openly interpret and advocate, challenging the neutrality norm.",
        figures: "Galtung; Lynch & McGoldrick.",
        tags: ["journalism"],
      },
      {
        name: "Media accountability & ethics",
        description: "Codes, norms, and self-regulation.",
        principle: "Journalism is governed by professional ethics (truth, independence, minimizing harm, accountability) enforced mainly through self-regulation, codes, and press councils rather than law.",
        figures: "SPJ code; Hutchins Commission (social responsibility theory).",
        tags: ["journalism"],
        xref: ["law"],
      },
      {
        name: "Four theories / normative theories of the press",
        description: "Systems relating press and state.",
        principle: "Press systems have been classified into authoritarian, libertarian, social-responsibility, and Soviet-communist models (with later \"development\" and \"democratic-participant\" additions), each linking media to a political philosophy.",
        lineage: "Comparative media systems.",
        figures: "Siebert, Peterson & Schramm (1956); Hallin & Mancini (modern comparative models).",
        era: "1956/2004.",
        critiques: "The original typology is dated and Cold-War-shaped; presented as a historical framework with its critiques.",
        tags: ["journalism", "node"],
        xref: ["political-science"],
      },
    ],
  },
  // ── Family 13 ──────────────────────────────────────────────────────────────
  {
    slug: "digital-networked",
    number: 13,
    name: "Digital, Social & Networked Media",
    blurb: "New-media theory, convergence, networked publics, and the affordances of digital communication.",
    section: "E",
    color: "purple",
    entries: [
      {
        name: "New media / digital media",
        description: "Computationally mediated, networked, interactive media.",
        principle: "Digital media are distinguished by being numerically coded, modular, automatable, variable, and networked — enabling interactivity, convergence, and user participation at scale.",
        lineage: "New-media theory.",
        figures: "Lev Manovich (The Language of New Media); Lister et al.",
        era: "2000s.",
        tags: ["digital", "node"],
        xref: ["computer-science"],
      },
      {
        name: "Convergence culture",
        description: "Old and new media, top-down and bottom-up, collide.",
        principle: "Content flows across multiple platforms, industries cooperate and compete, and audiences participate — convergence is a cultural shift, not just a technological one.",
        lineage: "New-media/participatory-culture theory.",
        figures: "Henry Jenkins (Convergence Culture, 2006).",
        era: "2006.",
        tags: ["digital", "node"],
      },
      {
        name: "Participatory culture & produsage",
        description: "Audiences as producers.",
        principle: "Low barriers to creation and sharing turn former audiences into participants who produce, remix, and circulate content (\"produsers\"), blurring producer/consumer roles.",
        figures: "Jenkins; Bruns (produsage).",
        tags: ["digital"],
        xref: ["arts"],
      },
      {
        name: "Networked public sphere",
        description: "Distributed online spaces for public discourse.",
        principle: "Digital networks create a more distributed, many-to-many public sphere that can widen participation while also fragmenting and polarizing it.",
        lineage: "Extends Habermas's public sphere to networks.",
        figures: "Benkler (The Wealth of Networks); Castells.",
        era: "2000s-",
        critiques: "Whether the net effect is deliberative gain or fragmentation is contested; presented as an open dispute.",
        tags: ["digital", "node"],
        xref: ["political-science"],
      },
      {
        name: "Network society",
        description: "Society organized around digital information networks.",
        principle: "Information networks are the dominant morphology of contemporary society, reorganizing power, economy, and culture around flows and nodes.",
        lineage: "Macro digital-media/sociology theory.",
        figures: "Manuel Castells (The Rise of the Network Society).",
        era: "1996-",
        tags: ["digital", "node"],
        xref: ["sociology"],
      },
      {
        name: "Networked gatekeeping & networked framing",
        description: "Gatekeeping in social media.",
        principle: "On networked platforms, gatekeeping and framing become distributed and crowd-driven, as ordinary users, influencers, and algorithms jointly elevate actors and interpretations.",
        lineage: "Reformulates classical gatekeeping/framing for social media.",
        figures: "Barzilai-Nahon (network gatekeeping); Meraz & Papacharissi.",
        era: "2010s.",
        tags: ["digital", "node"],
      },
      {
        name: "Spreadable media & virality",
        description: "How content circulates online.",
        principle: "Content spreads when it is easy to share and meaningful to audiences (\"if it doesn't spread, it's dead\"); virality is driven by social motivation, emotion (esp. high-arousal), and network structure.",
        figures: "Jenkins, Ford & Green; Berger (contagion).",
        tags: ["digital"],
        xref: ["statistics"],
      },
      {
        name: "Affordances of platforms",
        description: "What a technology invites users to do.",
        principle: "A platform's features afford and constrain particular practices (persistence, visibility, spreadability, searchability), shaping how communication unfolds without fully determining it.",
        figures: "boyd (networked publics); Gibson/Norman (affordance roots).",
        tags: ["digital"],
        xref: ["computer-science"],
      },
      {
        name: "Context collapse",
        description: "One audience where many used to be.",
        principle: "Social media flatten distinct audiences (friends, family, employers) into a single imagined public, complicating self-presentation and norms of disclosure.",
        figures: "Marwick & boyd.",
        tags: ["digital"],
        xref: ["sociology"],
      },
      {
        name: "Self-presentation & impression management online",
        description: "Performing identity on platforms.",
        principle: "Users strategically curate profiles and posts to manage others' impressions, an online extension of Goffman's dramaturgical self.",
        lineage: "Goffman's self-presentation applied to social media.",
        figures: "Goffman (roots); boyd, Marwick.",
        tags: ["digital"],
        xref: ["sociology", "psychology"],
      },
      {
        name: "Social capital online",
        description: "Networked ties as resources.",
        principle: "Online networks can build bridging (diverse, weak-tie) and bonding (close, strong-tie) social capital, with contested effects on well-being and civic life.",
        figures: "Ellison, Steinfield & Lampe; roots in Putnam and Granovetter.",
        critiques: "Effects on well-being are actively contested; presented as an open empirical question.",
        tags: ["digital"],
        xref: ["sociology"],
      },
      {
        name: "Digital divide & digital inequality",
        description: "Unequal access, skills, and outcomes.",
        principle: "Gaps in access, skills, and beneficial use of digital media (the first-, second-, and third-level divides) can reproduce and widen social inequality.",
        figures: "van Dijk; Hargittai.",
        tags: ["digital"],
        xref: ["sociology", "education"],
      },
      {
        name: "Media / information / digital literacy",
        description: "Competence to access, analyze, and create media.",
        principle: "The abilities to critically access, evaluate, and produce media and information are treated as civic competencies, increasingly central to countering misinformation.",
        figures: "Hobbs; Buckingham.",
        tags: ["digital"],
        xref: ["education"],
      },
    ],
  },
  // ── Family 14 ──────────────────────────────────────────────────────────────
  {
    slug: "algorithms-platforms-information-disorder",
    number: 14,
    name: "Algorithms, Platforms & Information Disorder",
    blurb: "Algorithmic curation, filter-bubble debates, moderation, and the information-disorder framework — described neutrally, disputes flagged.",
    section: "E",
    color: "pink",
    entries: [
      {
        name: "Algorithmic curation & recommender systems",
        description: "Software selects what audiences see.",
        principle: "Platform algorithms rank and personalize content by predicted engagement, becoming powerful non-human gatekeepers whose logics are opaque to users.",
        figures: "Gillespie (\"the relevance of algorithms\"); Pariser.",
        critiques: "Their effects on attitudes and behavior are actively studied and contested; individual studies frequently find weaker effects than popular claims.",
        tags: ["platforms"],
        xref: ["computer-science"],
      },
      {
        name: "Filter bubbles & echo chambers",
        description: "Personalization and homophily as insulation.",
        principle: "The claim that algorithmic personalization (\"filter bubbles\") and self-selection into like-minded networks (\"echo chambers\") insulate people from disagreement and deepen polarization.",
        lineage: "A digital reformulation of selective exposure.",
        figures: "Pariser (The Filter Bubble, coined); Sunstein; skeptics incl. Bakshy et al., Guess et al.",
        era: "2011-",
        critiques: "This is a genuinely contested empirical claim — several large studies find weaker or mixed evidence than the popular narrative suggests; the dispute is stated, not adjudicated.",
        tags: ["platforms", "node"],
        xref: ["political-science", "statistics"],
      },
      {
        name: "Platform society / platformization",
        description: "Platforms as infrastructures reorganizing sectors.",
        principle: "A small number of platforms increasingly structure economic and social life, governing interactions through data, algorithms, and terms of service.",
        lineage: "Platform-studies/political economy.",
        figures: "van Dijck, Poell & de Waal (The Platform Society); Srnicek (platform capitalism).",
        era: "2010s-",
        tags: ["platforms"],
        xref: ["political-economy"],
      },
      {
        name: "Content moderation & platform governance",
        description: "How platforms set and enforce speech rules.",
        principle: "Platforms govern speech through policies, human and automated moderation, and appeals, making them de facto regulators of public discourse — with heavy scrutiny of consistency, transparency, and scale.",
        figures: "Gillespie (Custodians of the Internet); Roberts (commercial content moderation); Klonick (governance).",
        critiques: "The \"hidden\" labor of content moderators and the normative stakes of private speech governance are widely debated.",
        tags: ["platforms"],
        xref: ["law", "political-science"],
      },
      {
        name: "Misinformation & disinformation",
        description: "False or misleading information, unintended vs deliberate.",
        principle: "\"Misinformation\" is false or misleading content shared without intent to deceive; \"disinformation\" is deliberately deceptive; \"malinformation\" is true information shared to harm.",
        lineage: "Information-disorder framework.",
        figures: "Wardle & Derakhshan (information disorder).",
        era: "2017-",
        critiques: "The definitions and boundaries are contested and politically loaded, and labeling something \"misinformation\" is itself a contested act; presented descriptively with that caveat, not as a settled classifier.",
        tags: ["platforms", "node"],
        xref: ["political-science"],
      },
      {
        name: "Computational propaganda & bots",
        description: "Automated and coordinated online influence.",
        principle: "The use of automation (bots), algorithms, and coordinated inauthentic behavior to manipulate public opinion at scale.",
        figures: "Woolley & Howard (Oxford Computational Propaganda project).",
        era: "2010s-",
        critiques: "Described at the level of concept, detection, and countermeasure — not as an operational playbook.",
        tags: ["platforms"],
        xref: ["computer-science", "political-science"],
      },
      {
        name: "Deepfakes & synthetic media",
        description: "AI-generated fabricated content.",
        principle: "Generative models can fabricate realistic video, audio, and images, raising challenges for verification, trust, and the \"liar's dividend\" (real evidence dismissed as fake).",
        figures: "Chesney & Citron (liar's dividend).",
        critiques: "The technology and its detection are fast-moving; verify current capabilities/detection at build time.",
        tags: ["platforms"],
        xref: ["computer-science"],
      },
      {
        name: "Fact-checking, debunking & prebunking",
        description: "Correcting and pre-empting falsehoods.",
        principle: "Corrective interventions (fact-checks, debunking) and pre-emptive ones (inoculation/prebunking) aim to reduce belief in falsehoods; corrections help on average but face the \"continued-influence effect.\"",
        lineage: "Misinformation-correction research; links to inoculation theory.",
        figures: "Lewandowsky et al. (continued influence); Roozenbeek & van der Linden (prebunking).",
        tags: ["platforms"],
        xref: ["psychology"],
      },
      {
        name: "Surveillance & privacy in networked media",
        description: "Datafication of communication.",
        principle: "Networked communication generates pervasive behavioral data enabling surveillance by states and firms, reshaping privacy norms and power.",
        figures: "Zuboff (surveillance capitalism); Lyon (surveillance studies).",
        critiques: "\"Surveillance capitalism\" is one influential (and debated) framing of the political economy of platform data.",
        tags: ["platforms"],
        xref: ["law", "political-economy"],
      },
      {
        name: "Dark patterns & attention economy",
        description: "Designing for engagement and capture.",
        principle: "Interfaces and business models designed to maximize attention and engagement can exploit cognitive biases; the \"attention economy\" treats user attention as the scarce, monetized resource.",
        figures: "Wu (The Attention Merchants); Brignull (dark patterns).",
        critiques: "Described as an object of analysis and design ethics, not a manipulation guide.",
        tags: ["platforms"],
        xref: ["economics"],
      },
    ],
  },
  // ── Family 15 ──────────────────────────────────────────────────────────────
  {
    slug: "media-economics",
    number: 15,
    name: "Media Economics & Industries",
    blurb: "How media are produced, distributed, and monetized — dual-product markets, ownership, regulation, and public-service traditions.",
    section: "F",
    color: "amber",
    entries: [
      {
        name: "Media economics",
        description: "The economics of producing and distributing media.",
        principle: "Media are shaped by distinctive economics — high fixed and low marginal costs, public-good qualities of content, and (for ad-supported media) a \"dual product market\" selling content to audiences and audiences to advertisers.",
        lineage: "Applies economics to media industries.",
        figures: "Picard; Doyle.",
        tags: ["media-econ"],
        xref: ["economics"],
      },
      {
        name: "The dual-product / two-sided market",
        description: "Media sell content and audiences at once.",
        principle: "Many media firms operate in two linked markets — providing content to audiences and selling that audience's attention to advertisers — so audience size and composition are the core product.",
        lineage: "Media-economics; two-sided-market theory.",
        figures: "Rochet & Tirole (two-sided markets).",
        tags: ["media-econ"],
        xref: ["economics"],
      },
      {
        name: "The audience commodity",
        description: "Audiences as the product sold to advertisers.",
        principle: "In a critical political-economy reading, commercial media \"produce\" audiences whose attention (and, online, data and labor) is the commodity sold to advertisers.",
        lineage: "Critical political economy of communication.",
        figures: "Dallas Smythe (1977); reworked for digital \"free labor\" by Terranova, Fuchs.",
        era: "1977-",
        tags: ["media-econ", "node"],
        xref: ["political-economy"],
      },
      {
        name: "Concentration of ownership & media pluralism",
        description: "Few owners, many outlets.",
        principle: "Consolidation of media ownership can threaten the diversity of voices and viewpoints; pluralism (of ownership, content, and access) is treated as a public-interest goal.",
        figures: "Bagdikian (The Media Monopoly); McChesney.",
        critiques: "Whether concentration reduces content and viewpoint diversity in practice is empirically debated.",
        tags: ["media-econ"],
        xref: ["political-economy"],
      },
      {
        name: "Political economy of communication",
        description: "Power, ownership, and media as a critical lens.",
        principle: "Examines how ownership, advertising, market structure, and state policy shape media production and constrain the range of ideas in circulation.",
        lineage: "The critical-political-economy tradition.",
        figures: "Golding & Murdock; Mosco (The Political Economy of Communication); Herman & Chomsky.",
        era: "1970s-",
        tags: ["media-econ", "node"],
        xref: ["political-economy", "ideologies"],
      },
      {
        name: "Cultural industries / creative industries",
        description: "Culture produced industrially.",
        principle: "Symbolic goods are produced under industrial logics that both commodify culture and depend on managing creativity, risk, and unpredictable demand.",
        lineage: "From Frankfurt-School critique to cultural-policy studies.",
        figures: "Adorno & Horkheimer (culture industry); Hesmondhalgh (The Cultural Industries).",
        era: "1944/2000s.",
        critiques: "Adorno & Horkheimer's critical \"culture industry\" differs sharply from the later, more affirmative \"creative industries\" policy discourse; presented as a broad family, not a monolith.",
        tags: ["media-econ"],
        xref: ["arts", "economics"],
      },
      {
        name: "Media regulation & policy",
        description: "Rules governing media structure and conduct.",
        principle: "States regulate media through licensing, ownership limits, content rules, spectrum allocation, and competition law, balancing free expression, market forces, and the public interest.",
        example: "Catalog-level; specific statutes and current cases defer to [xref: law]/[xref: political-science].",
        tags: ["media-econ"],
        xref: ["law", "political-science"],
      },
      {
        name: "Public-service broadcasting",
        description: "Media chartered to serve the public, not the market.",
        principle: "Publicly funded or mandated broadcasters are charged with universal, independent programming in the public interest, on a rationale of market failure and citizenship.",
        example: "The BBC's \"inform, educate, entertain\" remit.",
        tags: ["media-econ"],
        xref: ["political-science"],
      },
      {
        name: "Platform economics & attention markets",
        description: "How platforms make money from communication.",
        principle: "Dominant digital platforms monetize communication through targeted advertising, data, and network effects that tend toward winner-take-most concentration, raising new competition and policy questions.",
        critiques: "Current antitrust and regulatory actions (US and EU) are volatile — verify at build time. As of mid-2026, the US TikTok divestiture law resolved into a US joint venture (\"TikTok USDS\") that went live in January 2026, with ByteDance retaining a ~19.9% minority stake and Oracle/Silver Lake/MGX as lead investors; compliance with the divestiture law is itself disputed. The EU DSA is in force; in 2026 the Commission refined its \"active-recipient\" counting methodology, sweeping several previously-exempt mid-tier platforms into VLOP obligations.",
        tags: ["media-econ"],
        xref: ["economics", "law"],
        status: "open",
      },
      {
        name: "Net neutrality & information infrastructure",
        description: "Should carriers treat all traffic equally?",
        principle: "The debate over whether network operators must carry all lawful traffic without discrimination, framing internet access as essential communication infrastructure.",
        critiques: "The regulatory status shifts by jurisdiction and over time; present the debate and verify current status at build time.",
        tags: ["media-econ"],
        xref: ["law", "political-science"],
        status: "open",
      },
    ],
  },
  // ── Family 16 ──────────────────────────────────────────────────────────────
  {
    slug: "political-communication",
    number: 16,
    name: "Political Communication",
    blurb: "Communication in the creation and conduct of politics — public opinion, campaigns, mediatization, and the deliberative public sphere.",
    section: "F",
    color: "rose",
    entries: [
      {
        name: "Political communication",
        description: "Communication in the creation and conduct of politics.",
        principle: "The study of how political actors, media, and citizens exchange messages to shape opinion, policy, and power.",
        lineage: "The intersection of communication and political science.",
        figures: "Blumler; Kaid.",
        tags: ["pol-comm"],
        xref: ["political-science"],
      },
      {
        name: "Manufacturing / engineering of public opinion",
        description: "Elite management of mass opinion.",
        principle: "An early tradition holding that publics are guided by elites and experts through the strategic management of symbols and information.",
        lineage: "Foundational public-opinion theory.",
        figures: "Walter Lippmann (Public Opinion, 1922; \"the manufacture of consent\"); Bernays; Dewey (critic).",
        era: "1920s.",
        critiques: "Lippmann's and Bernays's views are presented as historical positions; Dewey's participatory reply and later critiques of expert-elite guidance are quarantined here rather than adjudicated.",
        tags: ["pol-comm", "node"],
        xref: ["political-science"],
      },
      {
        name: "Agenda-setting in politics",
        description: "Media, public, and policy agendas.",
        principle: "The media agenda influences the public agenda and, through it, the policy agenda; who sets each agenda is a central question of political communication.",
        lineage: "Agenda-setting applied to politics/policy.",
        figures: "McCombs & Shaw; Kingdon (policy streams).",
        tags: ["pol-comm"],
        xref: ["political-science"],
      },
      {
        name: "Political advertising & campaign communication",
        description: "Persuasive communication for elections.",
        principle: "Campaigns use paid and earned media, targeting, and message strategy to mobilize supporters and persuade the undecided; effects are typically small-but-real and conditional.",
        critiques: "Micro-targeting is described at the level of concept and its normative debate over autonomy and manipulation, not as an operational method.",
        tags: ["pol-comm"],
        xref: ["political-science"],
      },
      {
        name: "Framing and priming in campaigns",
        description: "Shaping the terms and criteria of choice.",
        principle: "Campaigns and coverage frame issues and prime the considerations voters use, shifting evaluations without changing underlying facts.",
        lineage: "Framing/priming applied to campaigns.",
        figures: "Iyengar; Jamieson.",
        tags: ["pol-comm"],
        xref: ["political-science"],
      },
      {
        name: "Mediatization of politics",
        description: "Politics adapts to media logic.",
        principle: "Political institutions and actors increasingly organize their behavior around media formats, timing, and news values (\"permanent campaign,\" soundbite politics).",
        lineage: "Mediatization theory applied to politics.",
        figures: "Mazzoleni & Schulz; Stromback.",
        tags: ["pol-comm", "node"],
        xref: ["political-science"],
      },
      {
        name: "Hybrid media system",
        description: "Old and new media logics interpenetrate.",
        principle: "Contemporary political communication runs through a hybrid system where older (broadcast, press) and newer (digital, social) media logics interact, and actors exploit the seams.",
        lineage: "Updates mediatization for the digital era.",
        figures: "Andrew Chadwick (The Hybrid Media System, 2013).",
        era: "2013.",
        tags: ["pol-comm", "node"],
        xref: ["political-science"],
      },
      {
        name: "Political polarization & partisan media",
        description: "Slanted outlets and audience sorting.",
        principle: "The growth of ideologically distinct outlets and selective audiences is associated with partisan and affective polarization.",
        critiques: "The direction and size of media's causal role in polarization are contested; the dispute is presented, not adjudicated.",
        tags: ["pol-comm"],
        xref: ["political-science", "statistics"],
      },
      {
        name: "Strategic framing / \"spin\" & news management",
        description: "Actors managing their coverage.",
        principle: "Political actors manage news through framing, staging, leaks, and access to shape coverage in their favor — the professionalization of political public relations.",
        figures: "Bennett; Esser.",
        tags: ["pol-comm"],
        xref: ["political-science"],
      },
      {
        name: "Deliberative democracy & the public sphere",
        description: "Communication as the basis of legitimacy.",
        principle: "Legitimate political decisions should emerge from inclusive, reasoned public deliberation; the \"public sphere\" is the communicative space between state and society where public opinion forms.",
        lineage: "Critical-theory public-sphere tradition.",
        figures: "Jurgen Habermas (Structural Transformation of the Public Sphere, 1962); Fraser (critique).",
        era: "1962-",
        critiques: "Habermas's ideal is critiqued as historically exclusionary (Fraser's \"subaltern counterpublics\"); presented with that critique.",
        tags: ["pol-comm", "node"],
        xref: ["philosophy", "political-science"],
      },
    ],
  },
  // ── Family 17 ──────────────────────────────────────────────────────────────
  {
    slug: "intercultural-development",
    number: 17,
    name: "Intercultural & Development Communication",
    blurb: "Communication across cultural difference and in service of development — from high/low-context and Hofstede to postcolonial critique.",
    section: "F",
    color: "orange",
    entries: [
      {
        name: "Intercultural communication",
        description: "Communication across cultural difference.",
        principle: "Studies how people from different cultures communicate, and how culture shapes perception, meaning, norms, and misunderstanding.",
        lineage: "An applied subfield with anthropological roots.",
        figures: "Edward T. Hall (founder).",
        era: "1950s-",
        tags: ["intercultural"],
        xref: ["anthropology"],
      },
      {
        name: "High- vs low-context cultures",
        description: "How much meaning is in the words.",
        principle: "In high-context cultures much meaning is carried implicitly by context and relationship; in low-context cultures meaning is stated explicitly in the message.",
        lineage: "Intercultural theory.",
        figures: "Edward T. Hall (Beyond Culture, 1976).",
        era: "1976.",
        tags: ["intercultural", "node"],
        xref: ["anthropology"],
      },
      {
        name: "Hofstede's cultural dimensions",
        description: "Comparing cultures along value axes.",
        principle: "National cultures vary along dimensions (individualism-collectivism, power distance, uncertainty avoidance, masculinity-femininity, long-term orientation, indulgence) that shape communication.",
        lineage: "Cross-cultural psychology/management.",
        figures: "Geert Hofstede.",
        era: "1980-",
        critiques: "Widely used and widely critiqued for essentializing nations and treating culture as static; presented with that critique.",
        tags: ["intercultural", "node"],
        xref: ["psychology", "sociology"],
      },
      {
        name: "Anxiety/uncertainty management theory",
        description: "Managing unease in intercultural encounters.",
        principle: "Effective intercultural communication depends on managing the anxiety and uncertainty that arise with strangers, enabling mindful adjustment.",
        figures: "William Gudykunst.",
        tags: ["intercultural"],
        xref: ["psychology"],
      },
      {
        name: "Face-negotiation theory",
        description: "Culture shapes how conflict and face are managed.",
        principle: "Cultural differences (esp. individualism-collectivism) shape how people manage \"face\" and choose conflict styles across cultures.",
        figures: "Stella Ting-Toomey.",
        tags: ["intercultural"],
      },
      {
        name: "Cultural identity & co-cultural theory",
        description: "Communicating from non-dominant positions.",
        principle: "Members of marginalized (\"co-cultural\") groups strategically adapt their communication when interacting with dominant structures, ranging from assimilation to accommodation to separation.",
        figures: "Mark Orbe.",
        tags: ["intercultural"],
        xref: ["sociology"],
      },
      {
        name: "Orientalism & postcolonial media critique",
        description: "Representation and power across cultures.",
        principle: "Dominant media and discourse can construct and subordinate \"other\" cultures through patterned representations that serve power.",
        lineage: "Postcolonial theory applied to media.",
        figures: "Edward Said (Orientalism, 1978); Shohat & Stam.",
        era: "1978-",
        tags: ["intercultural", "node"],
        xref: ["ideologies", "history"],
      },
      {
        name: "Cultural imperialism & media globalization",
        description: "Cross-border media flows and dominance.",
        principle: "The thesis that dominant (esp. Western/US) media exports can overwhelm local cultures; later work stresses contra-flows, glocalization, and active audiences instead of one-way domination.",
        lineage: "International-communication theory.",
        figures: "Schiller (cultural imperialism); Tomlinson, Straubhaar (critiques/revisions).",
        era: "1970s-",
        critiques: "The strong cultural-imperialism thesis is contested; the debate between one-way-domination and hybridization/glocalization accounts is stated, not adjudicated.",
        tags: ["intercultural", "node"],
        xref: ["political-economy"],
      },
      {
        name: "Development communication",
        description: "Communication for social and economic development.",
        principle: "The strategic use of communication to promote development; the field moved from a top-down \"modernization/diffusion\" paradigm toward participatory models that center local voice.",
        lineage: "International/development communication.",
        figures: "Lerner, Schramm (modernization); Freire, Servaes (participatory).",
        era: "1950s-",
        critiques: "The early modernization paradigm is critiqued as ethnocentric; the shift toward participatory models is presented as such.",
        tags: ["intercultural", "node"],
        xref: ["political-science"],
      },
      {
        name: "Glocalization & hybridity",
        description: "The global and local mix.",
        principle: "Global media forms are adapted to local contexts and blended into hybrid cultural forms, rather than simply homogenizing or preserving cultures.",
        figures: "Robertson (glocalization); Kraidy (hybridity); Appadurai (\"scapes\").",
        tags: ["intercultural"],
        xref: ["anthropology"],
      },
    ],
  },
  // ── Family 18 ──────────────────────────────────────────────────────────────
  {
    slug: "applied-health-environmental-strategic",
    number: 18,
    name: "Health, Environmental & Strategic Applied Communication",
    blurb: "The applied wing — health, risk, science, environment, campaigns, and strategic marketing communication.",
    section: "F",
    color: "green",
    entries: [
      {
        name: "Health communication",
        description: "Communication to improve health and health care.",
        principle: "The study and use of communication strategies to inform and influence health decisions among individuals, communities, and systems.",
        lineage: "An applied, interdisciplinary subfield.",
        figures: "Kreps; Rimal.",
        tags: ["applied"],
        xref: ["public-health", "psychology"],
      },
      {
        name: "Health-behavior communication models",
        description: "Frameworks for behavior-change messaging.",
        principle: "Campaigns draw on models (health belief model, extended parallel process model, transtheoretical/stages-of-change) to design messages matched to audiences' beliefs and readiness.",
        figures: "Rosenstock (HBM); Witte (EPPM); Prochaska (TTM).",
        tags: ["applied"],
        xref: ["public-health", "psychology"],
      },
      {
        name: "Risk communication",
        description: "Communicating hazards and uncertainty.",
        principle: "The exchange of information about risks among experts, officials, and publics; effective practice attends to trust, uncertainty, and the \"social amplification of risk.\"",
        figures: "Sandman; Kasperson (social amplification).",
        tags: ["applied"],
        xref: ["public-health"],
      },
      {
        name: "Crisis & emergency communication",
        description: "Communicating in acute threats.",
        principle: "Rapid, credible, and coordinated communication during emergencies (disasters, outbreaks) shapes public response; models emphasize being first, right, and empathetic.",
        figures: "CDC's CERC framework; Seeger.",
        example: "Overlaps organizational crisis communication (Family 4).",
        tags: ["applied"],
        xref: ["public-health"],
      },
      {
        name: "Environmental & science communication",
        description: "Communicating science, risk, and the environment.",
        principle: "The field examines how scientific and environmental information is produced, mediated, and received, moving from a \"deficit model\" (just supply facts) toward dialogue and engagement.",
        figures: "The \"public understanding of science\" tradition; Nisbet (framing science).",
        critiques: "The deficit model is widely critiqued as insufficient on contested issues; the shift toward dialogue and engagement is presented as such.",
        tags: ["applied"],
        xref: ["environmental-science", "public-health"],
      },
      {
        name: "Framing of science & the deficit model",
        description: "Why facts alone rarely persuade.",
        principle: "Public responses to science depend on frames, values, and trust as much as information, so \"filling a knowledge deficit\" often fails to change attitudes on contested issues.",
        figures: "Nisbet & Scheufele.",
        tags: ["applied"],
        xref: ["environmental-science"],
      },
      {
        name: "Strategic communication & integrated marketing communication",
        description: "Coordinated messaging toward goals.",
        principle: "Organizations align advertising, PR, and other channels into coherent campaigns aimed at defined objectives and audiences.",
        figures: "The IMC tradition (Schultz).",
        tags: ["applied", "persuasion"],
      },
      {
        name: "Advertising theory",
        description: "How commercial persuasion is thought to work.",
        principle: "Advertising is explained through hierarchy-of-effects models (awareness -> interest -> desire -> action), branding, emotional resonance, and repetition/mere-exposure.",
        figures: "Lavidge & Steiner (hierarchy of effects); the AIDA model.",
        tags: ["applied", "persuasion"],
        xref: ["psychology"],
      },
      {
        name: "Social marketing",
        description: "Marketing techniques for social good.",
        principle: "Applies commercial marketing concepts (audience segmentation, the \"4 Ps,\" exchange) to promote voluntary pro-social behavior change.",
        figures: "Kotler & Zaltman (coined).",
        tags: ["applied"],
        xref: ["public-health"],
      },
      {
        name: "Campaign design & evaluation",
        description: "Planning and measuring communication campaigns.",
        principle: "Effective campaigns rest on formative research, audience segmentation, theory-based message design, and rigorous outcome evaluation.",
        example: "Effect estimation and evaluation designs are [xref: statistics].",
        tags: ["applied"],
        xref: ["statistics", "public-health"],
      },
    ],
  },
];
