import type { Family } from "./types";

// ─────────────────────────────────────────────────────────────────────────────
// SECTION A — Foundational Models & Theory (violet / indigo)
// SECTION B — Interpersonal, Group & Organizational (blue / sky)
// ─────────────────────────────────────────────────────────────────────────────

export const FAMILIES_1_4: Family[] = [
  // ── Family 1 ───────────────────────────────────────────────────────────────
  {
    slug: "process-transmission-models",
    number: 1,
    name: "Process & Transmission Models",
    blurb: "The classic decompositions of the communication act — from linear transmission to interactive and transactional views.",
    section: "A",
    color: "violet",
    entries: [
      {
        name: "Communication (as a field)",
        description: "The study of how meaning is produced, transmitted, and interpreted.",
        principle: "Communication is the process by which participants create and share information and meaning through signs, to reach mutual understanding or effect.",
        critiques: "Whether communication is a distinct discipline or an interdiscipline drawing on sociology, psychology, and rhetoric is itself debated; presented as a broad field.",
        tags: ["foundations"],
        xref: ["sociology", "psychology"],
      },
      {
        name: "Lasswell's model",
        description: "\"Who says what to whom, in what channel, with what effect.\"",
        principle: "Communication can be analyzed by decomposing it into sender, message, medium, receiver, and effect — a linear formula that also maps the subfields (control, content, media, audience, and effects analysis).",
        lineage: "An early transmission model; a root of effects research.",
        figures: "Harold Lasswell (1948).",
        era: "1940s.",
        tags: ["foundations", "model", "node"],
      },
      {
        name: "Shannon-Weaver model",
        description: "The mathematical/engineering transmission model.",
        principle: "A source encodes a message through a transmitter over a channel (subject to noise) to a receiver and destination; communication is signal fidelity against noise.",
        lineage: "Information theory imported into communication.",
        figures: "Claude Shannon & Warren Weaver (1949).",
        era: "1948-1949.",
        tags: ["foundations", "model", "node"],
        xref: ["statistics", "computer-science"],
      },
      {
        name: "Noise (channel, semantic, psychological)",
        description: "Anything that degrades the message.",
        principle: "Interference between source and destination — physical channel noise, semantic mismatch of codes, or psychological distraction — reduces fidelity and shared meaning.",
        tags: ["foundations", "model"],
      },
      {
        name: "Encoder / decoder & the code",
        description: "Turning meaning into signal and back.",
        principle: "A sender encodes intended meaning into a shared code (language, image) that the receiver must decode; miscommunication arises when codes or contexts diverge.",
        tags: ["foundations", "model"],
        xref: ["linguistics"],
      },
      {
        name: "Schramm's model",
        description: "Communication as shared experience and feedback.",
        principle: "Meaning transfers only through the overlap in senders' and receivers' fields of experience; communication is circular, with feedback, not one-way.",
        lineage: "Reformulates the linear transmission models toward interaction.",
        figures: "Wilbur Schramm (1954).",
        era: "1950s.",
        tags: ["foundations", "model", "node"],
      },
      {
        name: "Berlo's SMCR model",
        description: "Source-Message-Channel-Receiver with skills and attitudes.",
        principle: "The fidelity of communication depends on the communication skills, attitudes, knowledge, and social/cultural systems of both source and receiver, and on message elements and the five senses as channels.",
        lineage: "Elaborates the transmission chain.",
        figures: "David Berlo (1960).",
        era: "1960s.",
        tags: ["foundations", "model"],
      },
      {
        name: "Transactional model",
        description: "Simultaneous, mutual meaning-making.",
        principle: "Communicators send and receive at the same time within a shared field, continuously co-creating meaning shaped by relationship, context, and noise — communication is a transaction, not a transfer.",
        lineage: "The culmination of the linear -> interactive -> transactional progression.",
        figures: "Barnlund (1970).",
        era: "1970s.",
        tags: ["foundations", "model", "node"],
      },
      {
        name: "Constitutive model of communication",
        description: "Communication constitutes reality, not just conveys it.",
        principle: "Communication is the primary social process through which our shared reality, relationships, and selves are produced and maintained — reframing communication from a tool for transmitting pre-existing meaning to the thing that constitutes meaning.",
        lineage: "Reacts against the transmission tradition.",
        figures: "Robert Craig; James Carey's \"ritual view\".",
        era: "1990s.",
        tags: ["foundations", "model", "node"],
      },
      {
        name: "Transmission vs ritual views (Carey)",
        description: "Two root metaphors for communication.",
        principle: "The transmission view treats communication as sending messages across space for control; the ritual view treats it as the shared, ceremonial maintenance of community and meaning over time.",
        lineage: "Carey's reframing, drawing on Dewey.",
        figures: "James Carey (Communication as Culture).",
        era: "1975/1989.",
        tags: ["foundations", "model"],
        xref: ["sociology"],
      },
    ],
  },
  // ── Family 2 ───────────────────────────────────────────────────────────────
  {
    slug: "metatheory-traditions",
    number: 2,
    name: "Meta-Theory & Traditions of Communication Theory",
    blurb: "The field's map of itself — Craig's seven traditions and the medium-theory macro-lens.",
    section: "A",
    color: "indigo",
    entries: [
      {
        name: "The seven traditions of communication theory (Craig)",
        description: "A field-organizing map.",
        principle: "Communication theory can be organized into rhetorical, semiotic, phenomenological, cybernetic, sociopsychological, sociocultural, and critical traditions, each defining communication differently and productively arguing with the others.",
        lineage: "A meta-model unifying a fragmented field.",
        figures: "Robert Craig (1999).",
        era: "1999.",
        tags: ["metatheory", "node"],
      },
      {
        name: "Sociopsychological tradition",
        description: "Communication as expression, interaction, and influence.",
        principle: "Studies the causes and effects of communication behavior at the level of individuals and their interactions, using largely experimental and quantitative methods.",
        lineage: "One of Craig's seven; home of most effects and persuasion research.",
        figures: "Hovland; the Yale program.",
        era: "Mid-20th c.-",
        tags: ["metatheory"],
        xref: ["psychology", "statistics"],
      },
      {
        name: "Cybernetic tradition",
        description: "Communication as information processing and feedback.",
        principle: "Treats communication as the flow of information in systems governed by feedback loops, applying equally to machines, organisms, and societies.",
        lineage: "One of Craig's seven; from information theory and systems theory.",
        figures: "Wiener, Shannon, Bateson.",
        era: "1940s-",
        tags: ["metatheory"],
        xref: ["computer-science"],
      },
      {
        name: "Sociocultural tradition",
        description: "Communication as the (re)production of social order.",
        principle: "Communication produces and reproduces shared social reality, culture, and identity; meaning is situated in social interaction and cultural context.",
        lineage: "One of Craig's seven; from sociology and anthropology.",
        figures: "Mead, Goffman, Berger & Luckmann.",
        era: "20th c.",
        tags: ["metatheory"],
        xref: ["sociology", "anthropology"],
      },
      {
        name: "Critical tradition",
        description: "Communication as a site of power and ideology.",
        principle: "Examines how communication sustains or challenges relations of power, domination, and ideology, aiming at emancipation.",
        lineage: "One of Craig's seven; from the Frankfurt School and cultural studies.",
        figures: "Adorno & Horkheimer, Habermas, Hall.",
        era: "1930s-",
        tags: ["metatheory"],
        xref: ["philosophy", "ideologies"],
      },
      {
        name: "Phenomenological tradition",
        description: "Communication as authentic dialogue and experience.",
        principle: "Communication is the experience of self and other in dialogue; genuine understanding requires openness across difference.",
        lineage: "One of Craig's seven; from phenomenology and hermeneutics.",
        figures: "Buber, Gadamer, Rogers.",
        era: "20th c.",
        tags: ["metatheory"],
        xref: ["philosophy"],
      },
      {
        name: "Medium theory",
        description: "The medium shapes the message and the mind.",
        principle: "The characteristics of a communication medium (not just its content) reorganize perception, social arrangements, and thought over the long run.",
        lineage: "The Toronto School; a distinct macro-tradition.",
        figures: "Innis, McLuhan.",
        era: "1950s-",
        tags: ["metatheory", "node"],
      },
      {
        name: "\"The medium is the message\" / hot & cool media",
        description: "McLuhan's core provocations.",
        principle: "A medium's form, more than its content, is its true \"message\"; \"hot\" media (film, print) are high-definition and low-participation, \"cool\" media (TV, speech) are low-definition and high-participation.",
        lineage: "Medium theory.",
        figures: "Marshall McLuhan (Understanding Media).",
        era: "1964.",
        tags: ["metatheory", "node"],
      },
      {
        name: "The global village",
        description: "Electronic media re-tribalize the world.",
        principle: "Instantaneous electronic media collapse distance and re-create the involved, interconnected condition of oral culture on a planetary scale.",
        lineage: "Medium theory.",
        figures: "McLuhan.",
        era: "1962-",
        tags: ["metatheory"],
      },
      {
        name: "Communication ecology / mediatization",
        description: "Media as an environment that reshapes institutions.",
        principle: "As media saturate social life, other institutions (politics, religion, family) increasingly adapt to media logics — a long-run structural process, not just a set of discrete effects.",
        lineage: "Extends medium theory into contemporary media sociology.",
        figures: "Hjarvard, Couldry & Hepp.",
        era: "2000s-",
        tags: ["metatheory"],
        xref: ["sociology"],
      },
    ],
  },
  // ── Family 3 ───────────────────────────────────────────────────────────────
  {
    slug: "interpersonal",
    number: 3,
    name: "Interpersonal Communication",
    blurb: "Meaning-making in dyads and close relationships — how people build, maintain, and negotiate identity face-to-face.",
    section: "B",
    color: "blue",
    entries: [
      {
        name: "Interpersonal communication",
        description: "Meaning-making between people in relationship.",
        principle: "The study of how individuals use verbal and nonverbal messages to create, maintain, and dissolve relationships and negotiate identity and meaning face to face.",
        tags: ["interpersonal"],
        xref: ["psychology"],
      },
      {
        name: "Uncertainty reduction theory",
        description: "We communicate to reduce uncertainty about others.",
        principle: "On first meeting, people are driven to reduce uncertainty about each other; increased communication and information-seeking lower uncertainty and, in turn, raise liking.",
        lineage: "A sociopsychological interpersonal theory.",
        figures: "Berger & Calabrese (1975).",
        era: "1975.",
        tags: ["interpersonal", "node"],
      },
      {
        name: "Social penetration theory",
        description: "Relationships deepen through self-disclosure.",
        principle: "Relationships develop through gradual, reciprocal self-disclosure that moves from broad and shallow to narrow and deep — like peeling an onion.",
        lineage: "Interpersonal.",
        figures: "Altman & Taylor (1973).",
        era: "1973.",
        tags: ["interpersonal", "node"],
      },
      {
        name: "Social exchange theory",
        description: "Relationships weighed by costs and rewards.",
        principle: "People evaluate relationships by the ratio of rewards to costs against a comparison level, staying when outcomes exceed expectations and alternatives.",
        lineage: "Imports exchange sociology into interpersonal communication.",
        figures: "Thibaut & Kelley; Homans.",
        era: "1959-",
        tags: ["interpersonal"],
        xref: ["sociology", "economics"],
      },
      {
        name: "Relational dialectics theory",
        description: "Relationships live in ongoing tension.",
        principle: "Close relationships are animated by contradictory pulls (autonomy-connection, openness-closedness, predictability-novelty) that are continuously, never finally, managed through communication.",
        lineage: "A dialectical/interpretive interpersonal theory.",
        figures: "Baxter & Montgomery (1996).",
        era: "1990s.",
        tags: ["interpersonal", "node"],
      },
      {
        name: "Communication accommodation theory",
        description: "Speakers converge or diverge to manage social distance.",
        principle: "People adjust their speech style, accent, and behavior toward (convergence) or away from (divergence) their interlocutor to seek approval, efficiency, or group distinctiveness.",
        lineage: "From social-identity and speech-accommodation research.",
        figures: "Howard Giles (1970s).",
        era: "1970s-",
        tags: ["interpersonal", "node"],
        xref: ["linguistics", "sociology"],
      },
      {
        name: "Expectancy violations theory",
        description: "Breaking interaction norms carries meaning.",
        principle: "People hold expectations about others' nonverbal behavior; violating them triggers arousal and evaluation, whose effect depends on the violator's reward value and the act's ambiguity.",
        lineage: "Nonverbal/interpersonal.",
        figures: "Judee Burgoon.",
        era: "1978-",
        tags: ["interpersonal", "node"],
      },
      {
        name: "Communication privacy management",
        description: "Rules govern private information.",
        principle: "People treat private information as owned, using rule-based boundaries to control disclosure; turbulence arises when co-owners mismanage the shared boundary.",
        lineage: "Extends social penetration into privacy.",
        figures: "Sandra Petronio (2002).",
        era: "2000s.",
        tags: ["interpersonal"],
      },
      {
        name: "Nonverbal communication",
        description: "Meaning beyond words.",
        principle: "Kinesics (body/gesture), proxemics (space), haptics (touch), paralanguage (vocal tone), chronemics (time), and appearance carry large portions of relational and emotional meaning.",
        example: "Mehrabian's disputed \"7-38-55\" figures for verbal/vocal/facial affect are widely misapplied.",
        tags: ["interpersonal", "nonverbal"],
        xref: ["psychology"],
      },
      {
        name: "Self-disclosure & the Johari window",
        description: "Revealing the self.",
        principle: "Sharing information about oneself builds intimacy and trust; the Johari window maps the self into open, hidden, blind, and unknown quadrants that disclosure and feedback reshape.",
        figures: "Luft & Ingham.",
        tags: ["interpersonal"],
      },
      {
        name: "Politeness theory & facework",
        description: "Managing face in interaction.",
        principle: "Interactants protect each other's positive and negative \"face\" through strategies whose form scales with social distance, power, and the imposition of the act.",
        lineage: "Pragmatics of interaction.",
        figures: "Brown & Levinson; Goffman (face).",
        era: "1987/1967.",
        tags: ["interpersonal"],
        xref: ["linguistics", "sociology"],
      },
    ],
  },
  // ── Family 4 ───────────────────────────────────────────────────────────────
  {
    slug: "group-organizational",
    number: 4,
    name: "Group & Organizational Communication",
    blurb: "Communication as the substance of collective life — from small-group dynamics to how organizations coordinate and mean.",
    section: "B",
    color: "sky",
    entries: [
      {
        name: "Small-group communication",
        description: "How task and relational messages shape group life.",
        principle: "Communication in groups organizes roles, norms, cohesion, and decision quality; groups are more than the sum of their members' inputs.",
        tags: ["group"],
        xref: ["sociology"],
      },
      {
        name: "Group development (Tuckman)",
        description: "Groups mature through stages.",
        principle: "Groups typically pass through forming, storming, norming, performing, and adjourning as they resolve relational and task tensions.",
        figures: "Bruce Tuckman (1965).",
        tags: ["group"],
      },
      {
        name: "Groupthink",
        description: "Cohesion can suppress critical judgment.",
        principle: "Highly cohesive, insulated decision groups under directive leadership may prioritize consensus over appraisal, yielding defective decisions.",
        lineage: "Group-decision theory.",
        figures: "Irving Janis (1972).",
        era: "1970s.",
        tags: ["group"],
        xref: ["psychology", "political-science"],
      },
      {
        name: "Structuration theory (in groups)",
        description: "Group structures are produced in interaction.",
        principle: "The rules and resources that structure a group are both the medium and the outcome of members' communicative practices — structure and action are mutually constituted.",
        lineage: "Giddens's structuration applied to group communication.",
        figures: "Poole; adapted from Giddens.",
        era: "1980s.",
        tags: ["group"],
        xref: ["sociology"],
      },
      {
        name: "Functional theory of group decision-making",
        description: "Good decisions meet key requirements.",
        principle: "Decision quality depends on the group fulfilling functions — understanding the problem, setting criteria, generating and evaluating alternatives — through its communication.",
        figures: "Gouran & Hirokawa.",
        tags: ["group"],
      },
      {
        name: "Symbolic convergence / fantasy-theme analysis",
        description: "Shared stories build group consciousness.",
        principle: "Groups converge on shared \"fantasy themes\" that chain out into a common symbolic reality (a \"rhetorical vision\"), binding the group.",
        lineage: "Rhetorical/group theory.",
        figures: "Ernest Bormann (1972).",
        era: "1970s.",
        tags: ["group", "rhetoric"],
      },
      {
        name: "Organizational communication",
        description: "Communication as the substance of organizing.",
        principle: "Organizations are constituted, coordinated, and given meaning through communication; structure, culture, and power are enacted in message flows.",
        lineage: "A major applied subfield.",
        figures: "Weick; the \"CCO\" (communication constitutes organization) school.",
        era: "1970s-",
        tags: ["organizational"],
        xref: ["sociology"],
      },
      {
        name: "Organizational culture & sensemaking",
        description: "Organizations make sense of equivocal events.",
        principle: "Members retrospectively construct plausible accounts of ambiguous situations through communication, enacting the environments they then respond to.",
        lineage: "Interpretive organizational theory.",
        figures: "Karl Weick (The Social Psychology of Organizing).",
        era: "1979-",
        tags: ["organizational"],
        xref: ["psychology"],
      },
      {
        name: "Organizational assimilation & socialization",
        description: "How members learn the organization.",
        principle: "Newcomers become members through communicative processes of anticipatory socialization, encounter, metamorphosis, and role negotiation.",
        figures: "Jablin.",
        tags: ["organizational"],
      },
      {
        name: "Networks of organizational communication",
        description: "Formal and emergent information flows.",
        principle: "Who talks to whom (formal chains and emergent networks) shapes influence, innovation diffusion, and information access within organizations.",
        tags: ["organizational"],
        xref: ["statistics"],
      },
      {
        name: "Public relations & strategic communication",
        description: "Managing relationships between organizations and publics.",
        principle: "The strategic management of communication to build and maintain mutually beneficial relationships between an organization and its stakeholders; the \"excellence\" tradition models two-way symmetrical communication as ideal.",
        lineage: "Applied organizational/persuasion field.",
        figures: "Grunig & Hunt (four models); Bernays (early publicity).",
        era: "20th c.",
        tags: ["organizational", "applied", "persuasion"],
      },
      {
        name: "Crisis communication",
        description: "Communicating under threat to reputation.",
        principle: "Organizations facing crises choose response strategies (denial, diminish, rebuild) that should match the level of attributed responsibility to protect legitimacy.",
        lineage: "Strategic-communication theory.",
        figures: "Coombs (Situational Crisis Communication Theory); Benoit (image repair).",
        era: "1990s-",
        tags: ["organizational", "applied"],
      },
    ],
  },
];
