import type { Family } from "./types";

// ─────────────────────────────────────────────────────────────────────────────
// SECTION C — Mass Communication & Media-Effects (cyan / teal / emerald / green)
// SECTION D — Semiotics, Rhetoric & Persuasion (amber / orange / rose)
// ─────────────────────────────────────────────────────────────────────────────

export const FAMILIES_5_11: Family[] = [
  // ── Family 5 ───────────────────────────────────────────────────────────────
  {
    slug: "strong-limited-effects",
    number: 5,
    name: "Strong- & Limited-Effects Traditions",
    blurb: "The opening moves of mass-communication research — from the strong-effects strawman to the limited-effects paradigm.",
    section: "C",
    color: "cyan",
    entries: [
      {
        name: "Mass society theory",
        description: "Atomized masses are vulnerable to mass media.",
        principle: "In modern, urban, industrial society, individuals uprooted from traditional ties form an anonymous \"mass\" susceptible to direct, uniform manipulation by centralized media.",
        lineage: "The intellectual backdrop of the strong-effects era; reacted against by empirical effects research.",
        figures: "Kornhauser; roots in Tonnies, Le Bon.",
        era: "Early 20th c.",
        tags: ["mass-comm", "strong-effects", "node"],
        xref: ["sociology"],
      },
      {
        name: "Hypodermic-needle / magic-bullet model",
        description: "Media inject uniform effects into a passive audience.",
        principle: "A stimulus-response image in which powerful, direct media messages \"inject\" attitudes and behavior more or less uniformly into an atomized, passive audience.",
        lineage: "Associated with mass-society theory and early propaganda fears.",
        figures: "Attributed to early Lasswell-era propaganda study.",
        era: "1920s-1930s.",
        critiques: "Largely a retrospective strawman/foil; few researchers ever held it in pure form, and it is presented here as the historical baseline the field defined itself against.",
        tags: ["mass-comm", "strong-effects", "node"],
      },
      {
        name: "Payne Fund studies",
        description: "Early empirical research on media and youth.",
        principle: "One of the first large research programs to measure media (film) effects on children's attitudes, emotions, and conduct, finding real but conditional and variable effects.",
        lineage: "Early effects research bridging toward the limited-effects turn.",
        figures: "The Payne Fund researchers (1928-1933).",
        era: "Early 1930s.",
        tags: ["mass-comm"],
        xref: ["statistics"],
      },
      {
        name: "The two-step flow of communication",
        description: "Media influence flows through opinion leaders.",
        principle: "Media effects are largely mediated: information and influence flow from media to attentive \"opinion leaders,\" who then shape the attitudes of those around them through interpersonal contact.",
        lineage: "The founding finding of the limited-effects paradigm; reacts against the hypodermic model.",
        figures: "Lazarsfeld, Berelson & Gaudet (The People's Choice, 1944); Katz & Lazarsfeld (Personal Influence, 1955).",
        era: "1940s-1950s.",
        tags: ["mass-comm", "limited-effects", "node"],
      },
      {
        name: "Opinion leadership",
        description: "Influential individuals broker media and peers.",
        principle: "Certain individuals, more attentive to media and central in social networks, disproportionately shape others' opinions within their domains of expertise.",
        lineage: "Two-step flow.",
        figures: "Katz & Lazarsfeld.",
        era: "1950s.",
        tags: ["mass-comm", "limited-effects"],
      },
      {
        name: "Diffusion of innovations",
        description: "How new ideas spread through a social system.",
        principle: "Innovations spread over time through communication channels among members of a social system in an S-curve, via adopter categories (innovators to laggards) and perceived attributes (relative advantage, compatibility, complexity, trialability, observability).",
        lineage: "Grows from two-step flow and rural sociology.",
        figures: "Everett Rogers (Diffusion of Innovations, 1962).",
        era: "1962-",
        tags: ["mass-comm", "limited-effects", "node"],
        xref: ["sociology"],
      },
      {
        name: "Selective exposure, attention & retention",
        description: "Audiences filter to fit prior beliefs.",
        principle: "People preferentially seek, notice, and remember messages consistent with existing attitudes, blunting persuasion and reinforcing predispositions.",
        lineage: "A mechanism of the limited-effects paradigm; roots in cognitive dissonance.",
        figures: "Festinger; Klapper.",
        era: "1950s-1960s.",
        tags: ["mass-comm", "limited-effects"],
        xref: ["psychology"],
      },
      {
        name: "Reinforcement theory / \"phenomenistic\" effects (Klapper)",
        description: "Media mostly reinforce, rarely convert.",
        principle: "Mass communication ordinarily works through a nexus of mediating factors (predispositions, groups, opinion leaders, selectivity) so that its usual effect is to reinforce existing attitudes rather than change them.",
        lineage: "The canonical summary of the limited-effects era.",
        figures: "Joseph Klapper (The Effects of Mass Communication, 1960).",
        era: "1960.",
        tags: ["mass-comm", "limited-effects", "node"],
      },
      {
        name: "The obstinate audience",
        description: "Audiences resist and use media on their own terms.",
        principle: "A corrective insisting audiences are active, goal-directed users of media rather than passive targets — a bridge from limited-effects toward uses-and-gratifications and reception theory.",
        lineage: "Reacts against passive-audience assumptions.",
        figures: "Raymond Bauer (1964).",
        era: "1964.",
        tags: ["mass-comm", "limited-effects", "node"],
      },
    ],
  },
  // ── Family 6 ───────────────────────────────────────────────────────────────
  {
    slug: "moderate-cumulative-effects",
    number: 6,
    name: "Moderate / Cumulative-Effects Theories",
    blurb: "The return to conditional, cumulative media effects — agenda-setting, framing, cultivation, spiral of silence.",
    section: "C",
    color: "teal",
    entries: [
      {
        name: "Agenda-setting theory",
        description: "Media tell us what to think about.",
        principle: "The salience of issues on the media agenda transfers to the public agenda — the press may not tell people what to think, but is stunningly successful at telling them what to think about.",
        lineage: "Revives moderate media effects after the limited-effects era; the trunk of the modern effects DAG.",
        figures: "McCombs & Shaw (The Chapel Hill study, 1972).",
        era: "1972-",
        critiques: "Whether the salience transfer is causal (rather than a correlation reflecting shared attention to real events) is a live methodological debate.",
        tags: ["mass-comm", "moderate-effects", "node"],
        xref: ["political-science"],
      },
      {
        name: "Second-level agenda-setting (attribute agenda-setting)",
        description: "Media shape how we think about issues.",
        principle: "Beyond which issues are salient (first level), media transfer the salience of specific attributes and tones of issues and actors, edging agenda-setting toward framing.",
        lineage: "Extends agenda-setting; bridges to framing.",
        figures: "McCombs; Ghanem.",
        era: "1990s.",
        tags: ["mass-comm", "moderate-effects", "node"],
      },
      {
        name: "Framing theory",
        description: "How an issue is presented shapes its interpretation.",
        principle: "To frame is to select some aspects of a perceived reality and make them more salient, promoting a particular problem definition, causal interpretation, moral evaluation, or remedy.",
        lineage: "Draws on both sociological frame analysis and agenda-setting.",
        figures: "Goffman (Frame Analysis); Entman; Gamson; Iyengar (episodic vs thematic).",
        era: "1974/1993-",
        critiques: "A genuinely divided family — sociological/emphasis framing (Goffman, Entman, Gamson) differs from psychological/equivalence framing (Kahneman & Tversky); presented as a broad tradition, not a monolith.",
        tags: ["mass-comm", "moderate-effects", "node"],
        xref: ["sociology", "psychology"],
      },
      {
        name: "Priming",
        description: "Media coverage shapes the standards of evaluation.",
        principle: "By making certain issues or attributes accessible, media coverage changes the criteria by which the public judges leaders and events.",
        lineage: "A cognitive extension of agenda-setting.",
        figures: "Iyengar & Kinder (News That Matters, 1987).",
        era: "1980s.",
        tags: ["mass-comm", "moderate-effects", "node"],
        xref: ["psychology", "political-science"],
      },
      {
        name: "Cultivation theory",
        description: "Heavy TV viewing cultivates a worldview.",
        principle: "The more time people spend \"living\" in the world of television, the more their conceptions of social reality converge on the recurrent, stable messages of TV — e.g. the \"mean world syndrome\" among heavy viewers.",
        lineage: "A cumulative, long-term-effects theory reacting against short-term persuasion models.",
        figures: "George Gerbner (Cultural Indicators project, 1970s).",
        era: "1970s-",
        critiques: "Critics argue cultivation effect sizes are small once controls are added and the causal direction is hard to identify; presented with that critique.",
        tags: ["mass-comm", "moderate-effects", "node"],
      },
      {
        name: "Mainstreaming & resonance (cultivation)",
        description: "How cultivation works and for whom.",
        principle: "Television \"mainstreams\" divergent groups toward a common outlook, and cultivation is amplified by \"resonance\" when TV's messages match lived experience.",
        lineage: "Refines cultivation.",
        figures: "Gerbner et al.",
        era: "1980s.",
        tags: ["mass-comm", "moderate-effects"],
      },
      {
        name: "The spiral of silence",
        description: "Fear of isolation silences perceived minorities.",
        principle: "People continuously scan the opinion climate and, fearing social isolation, withhold views they perceive to be losing ground, so those views spiral into public silence while the perceived majority grows louder.",
        lineage: "A strong-effects public-opinion theory; media supply the perceived climate.",
        figures: "Elisabeth Noelle-Neumann (1974).",
        era: "1974-",
        tags: ["mass-comm", "moderate-effects", "node"],
        xref: ["political-science", "sociology"],
      },
      {
        name: "Knowledge-gap hypothesis",
        description: "Information inflow widens gaps.",
        principle: "As media information flows into a system, higher-socioeconomic-status segments tend to acquire it faster, so the knowledge gap between higher- and lower-status groups widens rather than closes.",
        lineage: "A structural-effects theory.",
        figures: "Tichenor, Donohue & Olien (1970).",
        era: "1970.",
        tags: ["mass-comm", "moderate-effects", "node"],
        xref: ["sociology"],
      },
      {
        name: "Third-person effect",
        description: "People think media affect others more than themselves.",
        principle: "Individuals perceive media messages (especially undesirable ones) as having a greater effect on others than on themselves, and may support restrictions on that basis.",
        lineage: "A perceptual-effects theory.",
        figures: "W. Phillips Davison (1983).",
        era: "1983.",
        tags: ["mass-comm", "moderate-effects", "node"],
      },
      {
        name: "Media dependency theory",
        description: "Reliance on media grows with social complexity and crisis.",
        principle: "The more a society is complex and unsettled and the more people depend on media to understand and act, the greater the potential for media to have cognitive, affective, and behavioral effects.",
        lineage: "An integrative moderate-effects theory linking media, audiences, and society.",
        figures: "Ball-Rokeach & DeFleur (1976).",
        era: "1976.",
        tags: ["mass-comm", "moderate-effects", "node"],
      },
      {
        name: "Agenda-building",
        description: "How the media agenda itself gets set.",
        principle: "The media agenda is shaped by sources, elites, public relations, and inter-media influence — turning attention \"upstream\" from effects on the public to who and what sets the press's own priorities.",
        lineage: "The reciprocal of agenda-setting.",
        figures: "Cobb & Elder; Lang & Lang.",
        era: "1980s.",
        tags: ["mass-comm", "moderate-effects"],
        xref: ["political-science"],
      },
    ],
  },
  // ── Family 7 ───────────────────────────────────────────────────────────────
  {
    slug: "active-audience-reception",
    number: 7,
    name: "Active-Audience & Reception Theories",
    blurb: "The negotiated turn — audiences as goal-directed users and interpreters of media texts.",
    section: "C",
    color: "emerald",
    entries: [
      {
        name: "Uses and gratifications theory",
        description: "Audiences actively choose media to meet needs.",
        principle: "Instead of asking what media do to people, ask what people do with media — audiences actively select media to satisfy needs (information/surveillance, personal identity, integration/social interaction, entertainment/diversion).",
        lineage: "An active-audience reaction to effects/passive-audience models; grows from the \"obstinate audience\".",
        figures: "Katz, Blumler & Gurevitch (1973-74); Herzog (early radio study).",
        era: "1940s/1970s-",
        tags: ["mass-comm", "active-audience", "node"],
        xref: ["psychology"],
      },
      {
        name: "Encoding/decoding model",
        description: "Audiences decode messages in variable ways.",
        principle: "Media texts are encoded with a \"preferred\" meaning, but audiences decode them from dominant-hegemonic, negotiated, or oppositional positions depending on their social situation — meaning is not simply transmitted.",
        lineage: "The founding move of the reception/cultural-studies turn; reacts against transmission and strong-effects models.",
        figures: "Stuart Hall (1973/1980); Birmingham CCCS.",
        era: "1970s-1980s.",
        tags: ["mass-comm", "reception", "node"],
        xref: ["sociology"],
      },
      {
        name: "Reception theory / active audience studies",
        description: "Meaning is made in the act of reading.",
        principle: "Audiences construct meaning through interpretive work shaped by their social contexts; ethnographic reception studies find diverse, sometimes resistant readings of the same text.",
        lineage: "Elaborates encoding/decoding.",
        figures: "David Morley (The Nationwide Audience); Ang; Radway.",
        era: "1980s.",
        tags: ["mass-comm", "reception", "node"],
      },
      {
        name: "Interpretive communities",
        description: "Shared frameworks pattern interpretation.",
        principle: "Audiences belong to communities whose shared interpretive conventions lead to patterned, collective readings of media texts.",
        lineage: "Reception theory (borrowing from literary theory).",
        figures: "Stanley Fish (literary roots); Lindlof.",
        era: "1980s.",
        tags: ["mass-comm", "reception"],
      },
      {
        name: "The active audience & polysemy",
        description: "Texts are open to multiple readings.",
        principle: "Popular texts are \"polysemic,\" carrying multiple potential meanings that audiences can activate, enabling both dominant and resistant readings.",
        lineage: "Cultural-studies reception theory.",
        figures: "John Fiske (Television Culture).",
        era: "1987.",
        critiques: "The degree of audience freedom is contested — critics warn against overstating audience power (\"the new revisionism\").",
        tags: ["mass-comm", "reception", "node"],
      },
      {
        name: "Parasocial interaction & relationships",
        description: "Audiences form one-sided bonds with media figures.",
        principle: "Viewers develop a sense of intimate, friend-like relationship with media personae; these one-sided bonds can shape attention, attitudes, and loyalty.",
        lineage: "An active-audience/uses tradition.",
        figures: "Horton & Wohl (1956).",
        era: "1956-",
        tags: ["mass-comm", "active-audience", "node"],
        xref: ["psychology"],
      },
      {
        name: "Entertainment-education",
        description: "Embedding pro-social messages in entertainment.",
        principle: "Deliberately designed entertainment (soap operas, dramas) can model and promote beneficial attitudes and behaviors, drawing on social-cognitive theory and audience engagement.",
        lineage: "Applies active-audience and social-learning ideas.",
        figures: "Singhal & Rogers; roots in Bandura and Sabido.",
        era: "1970s-",
        tags: ["mass-comm", "applied"],
      },
      {
        name: "Transportation & narrative persuasion",
        description: "Absorption in a story lowers resistance.",
        principle: "When audiences are \"transported\" into a narrative, they experience reduced counter-arguing and shifted beliefs consistent with the story world.",
        lineage: "A media-psychology reception mechanism.",
        figures: "Green & Brock (2000).",
        era: "2000s.",
        tags: ["mass-comm", "active-audience"],
        xref: ["psychology"],
      },
    ],
  },
  // ── Family 8 ───────────────────────────────────────────────────────────────
  {
    slug: "media-psychology",
    number: 8,
    name: "Media Psychology & Behavioral Effects",
    blurb: "How mediated messages shape cognition, affect, and behavior at the individual level.",
    section: "C",
    color: "green",
    entries: [
      {
        name: "Social cognitive theory of mass communication",
        description: "We learn behavior by observing media models.",
        principle: "People acquire attitudes and behaviors by observing modeled actions and their consequences in media, governed by attention, retention, reproduction, and motivation (vicarious reinforcement).",
        lineage: "Applies Bandura's social learning to media.",
        figures: "Albert Bandura (Bobo doll studies; Social Foundations of Thought and Action).",
        era: "1960s-1980s.",
        tags: ["media-psych", "node"],
        xref: ["psychology"],
      },
      {
        name: "Media violence & aggression",
        description: "A long-contested effects question.",
        principle: "A large research tradition links exposure to violent media with increases in aggression via learning, priming, and desensitization.",
        critiques: "The size and real-world significance of the effect are genuinely disputed; presented as an open, actively debated question rather than settled.",
        tags: ["media-psych"],
        xref: ["psychology"],
      },
      {
        name: "Desensitization",
        description: "Repeated exposure blunts response.",
        principle: "Repeated exposure to media violence or distressing content can reduce physiological and emotional responsiveness and empathic reactions over time.",
        tags: ["media-psych"],
        xref: ["psychology"],
      },
      {
        name: "Excitation transfer",
        description: "Residual arousal spills into later responses.",
        principle: "Physiological arousal from one media stimulus can carry over and intensify an emotional response to a subsequent, unrelated stimulus.",
        figures: "Dolf Zillmann.",
        tags: ["media-psych"],
        xref: ["psychology"],
      },
      {
        name: "Mood management theory",
        description: "People use media to regulate affect.",
        principle: "Individuals select media content to maintain or improve their mood, gravitating to content that relieves boredom or stress.",
        figures: "Zillmann.",
        tags: ["media-psych"],
      },
      {
        name: "Cultivation of body image & social comparison",
        description: "Media ideals and self-evaluation.",
        principle: "Exposure to idealized media images can prompt upward social comparison and affect body image and self-esteem, with effects moderated by individual differences.",
        critiques: "Effect sizes vary substantially across studies and populations and remain debated.",
        tags: ["media-psych"],
        xref: ["psychology"],
      },
      {
        name: "Limited-capacity model of mediated message processing",
        description: "Attention and memory are bounded.",
        principle: "Processing mediated messages draws on limited cognitive resources across encoding, storage, and retrieval, so message form and pacing shape what audiences actually learn and recall.",
        figures: "Annie Lang.",
        tags: ["media-psych"],
        xref: ["psychology"],
      },
      {
        name: "Media multitasking & attention",
        description: "Simultaneous media use taxes cognition.",
        principle: "Using multiple media at once fragments attention and can impair comprehension and task performance, with contested long-run effects on sustained attention.",
        critiques: "An active, unsettled research area.",
        tags: ["media-psych"],
        xref: ["psychology"],
      },
      {
        name: "Media and moral panics",
        description: "Amplified public alarm over a perceived threat.",
        principle: "Media coverage can amplify episodic concern about a group or behavior into a disproportionate \"moral panic,\" constructing folk devils and pressure for control.",
        lineage: "Media-sociology/effects.",
        figures: "Stanley Cohen (Folk Devils and Moral Panics, 1972); Hall et al.",
        era: "1972-",
        tags: ["media-psych"],
        xref: ["sociology", "criminology"],
      },
    ],
  },
  // ── Family 9 ───────────────────────────────────────────────────────────────
  {
    slug: "semiotics",
    number: 9,
    name: "Semiotics & the Study of Signs",
    blurb: "How signs signify — the two founding traditions (Saussurean, Peircean) and their extension to media analysis.",
    section: "D",
    color: "amber",
    entries: [
      {
        name: "Semiotics / semiology",
        description: "The general study of signs and meaning.",
        principle: "Culture can be read as systems of signs; meaning arises from relationships within codes rather than from any natural link between sign and object.",
        lineage: "Two founding streams (Saussurean semiology, Peircean semiotics).",
        figures: "Saussure, Peirce.",
        era: "Early 20th c.",
        example: "The deep theory of sign systems and pragmatics is [xref: linguistics]; here it grounds media analysis.",
        tags: ["semiotics", "node"],
        xref: ["linguistics"],
      },
      {
        name: "Signifier & signified (Saussure)",
        description: "The two faces of the sign.",
        principle: "A sign unites a signifier (the form, e.g. a sound or image) and a signified (the concept); their relationship is arbitrary and fixed by convention, and meaning is differential (defined by contrast with other signs).",
        lineage: "Saussurean semiology.",
        figures: "Ferdinand de Saussure.",
        era: "1916.",
        tags: ["semiotics", "node"],
        xref: ["linguistics"],
      },
      {
        name: "Icon, index, symbol (Peirce)",
        description: "Three modes of sign relation.",
        principle: "Signs relate to their objects by resemblance (icon), by causal/physical connection (index), or by pure convention (symbol).",
        lineage: "Peircean semiotics.",
        figures: "Charles Sanders Peirce.",
        era: "Late 19th-early 20th c.",
        tags: ["semiotics", "node"],
        xref: ["linguistics", "philosophy"],
      },
      {
        name: "Denotation & connotation",
        description: "Literal vs cultural meaning.",
        principle: "A sign carries a literal, denotative meaning and layered connotative meanings shaped by culture, feeling, and association.",
        lineage: "Semiotic analysis of media.",
        figures: "Barthes.",
        tags: ["semiotics"],
      },
      {
        name: "Myth (Barthes)",
        description: "Second-order signification that naturalizes ideology.",
        principle: "Cultural \"myths\" take an existing sign and load it with further ideological meaning that comes to seem natural and obvious, masking its constructedness.",
        lineage: "Barthesian semiotics; a bridge to ideology critique.",
        figures: "Roland Barthes (Mythologies, 1957).",
        era: "1957.",
        tags: ["semiotics", "node"],
        xref: ["ideologies"],
      },
      {
        name: "Codes & conventions",
        description: "Shared rules that make signs legible.",
        principle: "Meaning depends on codes — shared systems of convention (genre codes, technical codes, social codes) that a culture's members use to encode and decode texts.",
        tags: ["semiotics"],
      },
      {
        name: "Paradigm & syntagm",
        description: "Selection and combination.",
        principle: "Meaning is generated along two axes — the paradigmatic (choice among substitutable signs) and the syntagmatic (their combination into a sequence).",
        lineage: "Structural semiotics.",
        figures: "Saussure, Jakobson.",
        tags: ["semiotics"],
        xref: ["linguistics"],
      },
      {
        name: "Intertextuality",
        description: "Texts are made of other texts.",
        principle: "Every text draws meaning from its relationships to prior texts; understanding depends on a web of references and conventions rather than a self-contained message.",
        figures: "Kristeva; Bakhtin (dialogism).",
        tags: ["semiotics"],
      },
      {
        name: "Semiotics of images & visual rhetoric",
        description: "Reading pictures as arguments.",
        principle: "Images persuade and signify through composition, framing, gaze, color, and cultural codes; visual \"grammar\" can be analyzed like verbal texts.",
        figures: "Kress & van Leeuwen; Barthes (\"Rhetoric of the Image\").",
        tags: ["semiotics", "visual"],
        xref: ["arts"],
      },
      {
        name: "Multimodality",
        description: "Meaning across combined modes.",
        principle: "Communication typically integrates several semiotic modes (language, image, sound, gesture, layout), each contributing to meaning; analysis must attend to their interplay.",
        figures: "Kress; the New London Group.",
        tags: ["semiotics"],
        xref: ["linguistics"],
      },
    ],
  },
  // ── Family 10 ──────────────────────────────────────────────────────────────
  {
    slug: "rhetoric-argumentation",
    number: 10,
    name: "Rhetoric & Argumentation",
    blurb: "The art of persuasion and effective symbolic action — from classical antiquity to contemporary argumentation theory.",
    section: "D",
    color: "orange",
    entries: [
      {
        name: "Rhetoric",
        description: "The art of persuasion and effective symbolic action.",
        principle: "Rhetoric is the faculty of discovering, in any given case, the available means of persuasion; it studies how discourse influences audiences.",
        lineage: "The oldest communication tradition.",
        figures: "The Sophists, Plato (critic), Aristotle.",
        era: "Classical antiquity.",
        example: "The philosophical foundations are [xref: philosophy]; here they anchor persuasion and public communication.",
        tags: ["rhetoric", "node"],
        xref: ["philosophy"],
      },
      {
        name: "Ethos, pathos, logos",
        description: "The three modes of proof.",
        principle: "Persuasion works through the speaker's credibility (ethos), the audience's emotions (pathos), and the argument's reasoning (logos), ideally in balance.",
        lineage: "Aristotelian rhetoric.",
        figures: "Aristotle (Rhetoric).",
        era: "4th c. BCE.",
        tags: ["rhetoric", "node"],
        xref: ["philosophy"],
      },
      {
        name: "The five canons of rhetoric",
        description: "The classical composing process.",
        principle: "Effective discourse is produced through invention (finding arguments), arrangement, style, memory, and delivery.",
        lineage: "Classical (Roman) rhetoric.",
        figures: "Cicero, Quintilian.",
        era: "Roman antiquity.",
        tags: ["rhetoric", "node"],
      },
      {
        name: "The rhetorical situation",
        description: "Discourse responds to an exigence.",
        principle: "Rhetoric arises in a situation defined by an exigence (an urgent imperfection), an audience able to act, and constraints; the situation calls the discourse into being.",
        lineage: "Neo-Aristotelian/contemporary rhetoric.",
        figures: "Lloyd Bitzer (1968); Richard Vatz (1973, counter-view).",
        era: "1960s-1970s.",
        critiques: "Bitzer's situation-centered view is contested by Vatz, who argues rhetors create the situation.",
        tags: ["rhetoric", "node"],
      },
      {
        name: "Kairos",
        description: "The opportune moment and fitting timing.",
        principle: "Persuasion depends on saying the right thing at the right time in the right measure; timing and propriety are constitutive of effectiveness.",
        lineage: "Classical rhetoric.",
        figures: "The Sophists; Isocrates.",
        tags: ["rhetoric"],
      },
      {
        name: "Toulmin model of argument",
        description: "The anatomy of a practical argument.",
        principle: "Everyday arguments move from data to a claim via a warrant, supported by backing, and qualified by rebuttals and modal qualifiers.",
        lineage: "Informal logic/argumentation.",
        figures: "Stephen Toulmin (The Uses of Argument, 1958).",
        era: "1958.",
        tags: ["rhetoric", "argumentation"],
        xref: ["logic", "philosophy"],
      },
      {
        name: "The New Rhetoric (Perelman)",
        description: "Argumentation and audience adherence.",
        principle: "Argumentation aims to secure or increase an audience's adherence to theses; the \"universal audience\" is a standard of reasonableness.",
        lineage: "20th-c. revival of rhetoric.",
        figures: "Perelman & Olbrechts-Tyteca (1958).",
        era: "1958.",
        tags: ["rhetoric", "argumentation"],
      },
      {
        name: "Dramatism & identification (Burke)",
        description: "Rhetoric as symbolic action and consubstantiality.",
        principle: "Humans are symbol-using animals; persuasion works through identification (consubstantiality) between rhetor and audience, and motives can be analyzed with the \"pentad\" (act, scene, agent, agency, purpose).",
        lineage: "20th-c. rhetorical theory.",
        figures: "Kenneth Burke (A Grammar of Motives).",
        era: "1940s-1950s.",
        tags: ["rhetoric", "node"],
        xref: ["philosophy"],
      },
      {
        name: "Narrative paradigm",
        description: "Humans reason through stories.",
        principle: "People are essentially storytellers who judge communication by \"narrative rationality\" — its coherence (probability) and fidelity (truthfulness to lived experience) — as much as by formal logic.",
        lineage: "Contemporary rhetoric.",
        figures: "Walter Fisher (1984).",
        era: "1984.",
        tags: ["rhetoric", "node"],
      },
      {
        name: "Rhetorical criticism & genres",
        description: "Analyzing symbolic acts and their types.",
        principle: "Rhetorical criticism interprets and evaluates persuasive artifacts; recurrent rhetorical situations produce genres (apologia, eulogy, jeremiad, the deliberative/forensic/epideictic types).",
        figures: "Campbell & Jamieson; classical genre theory.",
        tags: ["rhetoric"],
      },
      {
        name: "Fallacies & informal logic",
        description: "Recurring failures of argument.",
        principle: "Certain argument patterns (ad hominem, straw man, false dilemma, appeal to authority, slippery slope) are persuasive but logically defective; naming them supports critical evaluation.",
        tags: ["rhetoric", "argumentation"],
        xref: ["logic", "philosophy"],
      },
    ],
  },
  // ── Family 11 ──────────────────────────────────────────────────────────────
  {
    slug: "persuasion-attitude-change",
    number: 11,
    name: "Persuasion & Attitude Change",
    blurb: "How messages change beliefs, attitudes, and behavior — dual-process models, dissonance, inoculation, propaganda as concept.",
    section: "D",
    color: "rose",
    entries: [
      {
        name: "Persuasion",
        description: "Communication intended to shape attitudes and behavior.",
        principle: "The study of how messages change beliefs, attitudes, intentions, and actions, and of the conditions and mechanisms that make change more or less likely.",
        tags: ["persuasion"],
        xref: ["psychology"],
      },
      {
        name: "The Yale attitude-change approach",
        description: "Who says what to whom with what effect, experimentally.",
        principle: "Persuasion depends on source (credibility, attractiveness), message (order, sidedness, fear appeals), and audience factors, established through controlled experiments.",
        lineage: "The sociopsychological persuasion tradition.",
        figures: "Carl Hovland and the Yale Communication Research Program.",
        era: "1950s.",
        tags: ["persuasion", "node"],
        xref: ["psychology"],
      },
      {
        name: "Elaboration likelihood model (ELM)",
        description: "Two routes to persuasion.",
        principle: "Attitude change occurs via a central route (effortful scrutiny of argument quality) when motivation and ability are high, or a peripheral route (cues like source or length) when they are low.",
        lineage: "Dual-process persuasion theory.",
        figures: "Petty & Cacioppo (1986).",
        era: "1980s.",
        tags: ["persuasion", "node"],
        xref: ["psychology"],
      },
      {
        name: "Heuristic-systematic model",
        description: "Effortful vs shortcut processing.",
        principle: "People process persuasive messages either systematically (careful analysis) or heuristically (simple decision rules), often in combination, depending on motivation and capacity.",
        lineage: "Dual-process persuasion theory (parallel to ELM).",
        figures: "Shelly Chaiken.",
        era: "1980s.",
        tags: ["persuasion"],
        xref: ["psychology"],
      },
      {
        name: "Cognitive dissonance theory",
        description: "Inconsistency motivates attitude change.",
        principle: "Holding inconsistent cognitions produces discomfort that people reduce by changing an attitude, adding consonant beliefs, or minimizing the inconsistency.",
        lineage: "A foundational attitude-change theory.",
        figures: "Leon Festinger (1957).",
        era: "1957.",
        tags: ["persuasion", "node"],
        xref: ["psychology"],
      },
      {
        name: "Social judgment theory",
        description: "Messages land in latitudes of acceptance or rejection.",
        principle: "People judge incoming messages against their existing position; those within a \"latitude of acceptance\" persuade, while those in the \"latitude of rejection\" trigger a contrast/boomerang effect.",
        figures: "Sherif & Hovland.",
        tags: ["persuasion"],
        xref: ["psychology"],
      },
      {
        name: "Inoculation theory",
        description: "Pre-exposure builds resistance.",
        principle: "Exposing people to a weakened form of a counter-argument, with refutation, builds resistance to later persuasion attempts — like a vaccine for attitudes.",
        lineage: "Resistance-to-persuasion research; central to current \"prebunking\" of misinformation.",
        figures: "William McGuire (1961).",
        era: "1960s.",
        tags: ["persuasion", "node"],
        xref: ["psychology"],
      },
      {
        name: "Fear appeals & the extended parallel process model",
        description: "Threat plus efficacy drives protective action.",
        principle: "Fear-based messages motivate protective behavior only when perceived threat is paired with perceived efficacy; high threat without efficacy triggers defensive control (denial, avoidance).",
        figures: "Witte (EPPM); Rogers (protection motivation).",
        tags: ["persuasion"],
        xref: ["psychology", "public-health"],
      },
      {
        name: "Theory of reasoned action / planned behavior",
        description: "Intentions predict behavior.",
        principle: "Behavior follows from intention, which is shaped by attitudes, subjective norms, and (in TPB) perceived behavioral control.",
        figures: "Fishbein & Ajzen.",
        tags: ["persuasion"],
        xref: ["psychology"],
      },
      {
        name: "Framing effects (equivalence)",
        description: "Logically equivalent phrasings sway choice.",
        principle: "Presenting the same information as a gain or a loss changes preferences and risk-taking, contradicting strict rational-choice invariance.",
        lineage: "The psychological/equivalence strand of framing.",
        figures: "Kahneman & Tversky (prospect theory).",
        era: "1979-",
        tags: ["persuasion"],
        xref: ["psychology", "statistics"],
      },
      {
        name: "Nudging & choice architecture",
        description: "Structuring choices to steer behavior.",
        principle: "How options are arranged (defaults, salience, ordering) predictably influences decisions without removing options; a persuasion-adjacent behavioral tool.",
        figures: "Thaler & Sunstein.",
        critiques: "Nudging raises ethical debate over autonomy and manipulation; presented with that debate.",
        tags: ["persuasion"],
        xref: ["economics", "political-economy"],
      },
      {
        name: "Propaganda (as concept)",
        description: "Organized mass persuasion in the sponsor's interest.",
        principle: "Propaganda is the deliberate, systematic attempt to shape perceptions and direct behavior to further the propagandist's aims, often by managing information and emotion.",
        lineage: "Propaganda studies.",
        figures: "Lasswell; Ellul; Jowett & O'Donnell.",
        era: "20th c.-",
        critiques: "\"Propaganda\" is a contested, often pejorative label; described here as a scholarly concept, with classic technique taxonomies (name-calling, glittering generality, bandwagon, testimonial) treated as objects of analysis and inoculation, not a how-to.",
        tags: ["persuasion", "node"],
        xref: ["political-science"],
      },
    ],
  },
];
