import type { Family } from "./types";

export const FAMILIES_1_7: Family[] = [
  // ── Family 1 ──────────────────────────────────────────────────────────────
  {
    slug: "tax-theory-principles",
    number: 1,
    name: "Tax Theory & Principles",
    blurb: "Foundational normative frameworks for evaluating tax systems — equity, efficiency, simplicity, and revenue adequacy.",
    section: "A",
    color: "amber",
    entries: [
      {
        name: "Ability-to-pay principle",
        description: "Taxpayers should contribute according to their economic capacity, not merely to what they receive from government.",
        keyPrinciple: "Underlying rationale for progressive income taxation. Operationalized through graduated rates and the Haig-Simons income concept. Vertical equity follows: taxpayers with more capacity bear more burden.",
        tags: ["theory", "equity", "progressive"],
        xref: ["economics"],
      },
      {
        name: "Benefit theory",
        description: "Taxpayers pay for government services in proportion to what they receive from those services.",
        keyPrinciple: "Classical alternative to ability-to-pay. Justifies earmarked taxes such as the federal Highway Trust Fund (fueled by 18.4 cents/gallon gasoline excise) and Social Security payroll taxes. Breaks down for public goods that are non-excludable.",
        tags: ["theory", "benefit", "earmarked"],
        xref: ["economics"],
      },
      {
        name: "Optimal tax theory (Ramsey)",
        description: "Tax goods and income sources in ways that minimize efficiency loss for a given revenue target.",
        keyPrinciple: "Ramsey (1927) inverse-elasticity rule: tax rates should be inversely proportional to price elasticity of demand to minimize deadweight loss. Diamond-Saez extended to optimal income taxation with social welfare weights.",
        tags: ["theory", "efficiency", "Ramsey", "optimal"],
        xref: ["economics"],
      },
      {
        name: "Diamond-Mirrlees theorem",
        description: "An optimal tax system should not distort production decisions; intermediate goods should not be taxed.",
        keyPrinciple: "Production efficiency theorem (1971): tax final consumption, not inputs between firms. Foundation for VAT design. Implies eliminating taxes on business inputs and capital-to-capital transfers.",
        tags: ["theory", "efficiency", "production", "VAT"],
        xref: ["economics"],
      },
      {
        name: "Horizontal equity",
        description: "Similarly situated taxpayers should bear the same tax burden.",
        keyPrinciple: "Requires defining 'similarly situated' — contested by marriage penalty/bonus, treatment of imputed rent, and differential rates on capital vs. labor. A benchmark for evaluating tax reforms.",
        tags: ["theory", "equity", "horizontal"],
      },
      {
        name: "Vertical equity",
        description: "Taxpayers with different ability to pay should bear different tax burdens, proportionate to their means.",
        keyPrinciple: "Supports progressive rate structures. Diminishing marginal utility of income provides utilitarian foundation: a dollar taxed from a billionaire costs less welfare than a dollar taxed from a minimum-wage worker. Contested in libertarian tax theory.",
        tags: ["theory", "equity", "vertical", "progressive"],
        xref: ["economics"],
      },
      {
        name: "Tax neutrality",
        description: "A tax system should not distort economic choices between otherwise equivalent options.",
        keyPrinciple: "Non-neutral taxes cause taxpayers to choose less preferred real options for tax reasons, creating deadweight loss. Common neutrality violations: corporate-vs.-pass-through choice, debt-vs.-equity financing, realization vs. accrual. Perfect neutrality is impossible; the goal is minimizing avoidable distortions.",
        tags: ["theory", "efficiency", "neutrality"],
        xref: ["economics"],
      },
      {
        name: "Revenue adequacy",
        description: "The tax system must reliably raise sufficient funds to finance chosen government expenditures.",
        keyPrinciple: "A binding constraint on tax reform. Scored by the Joint Committee on Taxation (JCT) for federal legislation, with separate dynamic scoring of macroeconomic feedback. Distributional and efficiency goals must be balanced against revenue constraint.",
        tags: ["theory", "revenue", "JCT"],
      },
      {
        name: "Tax expenditures",
        description: "Revenue foregone from credits, deductions, exclusions, and preferential rates that deviate from a 'normal' tax structure.",
        keyPrinciple: "Term coined by Stanley Surrey (1967). Largest US expenditures: exclusion of employer health insurance (~$250B/year), mortgage interest deduction, exclusion of net pension contributions. The President's Budget publishes an annual tax expenditure list. Economically equivalent to direct spending but less visible to appropriators.",
        tags: ["theory", "expenditures", "subsidy", "Surrey"],
        xref: ["finance"],
      },
      {
        name: "Haig-Simons income concept",
        description: "Comprehensive income defined as consumption during the period plus change in net worth.",
        keyPrinciple: "H-S income = C + ΔNW. Benchmark for evaluating what 'should' be included in the tax base. Under H-S, unrealized gains, imputed rent, and employer-paid fringe benefits are income. Actual US tax law departs substantially (realization, exclusions).",
        tags: ["theory", "income", "Haig-Simons", "comprehensive"],
        xref: ["economics"],
      },
      {
        name: "Deadweight loss (excess burden)",
        description: "The efficiency cost of taxation: the reduction in economic welfare beyond the revenue collected.",
        keyPrinciple: "Arises from substitution effects: taxpayers reduce consumption of taxed activities. Proportional to the square of the tax rate times supply/demand elasticities (Harberger triangle). Minimizing excess burden is the core goal of efficient tax design.",
        tags: ["theory", "efficiency", "deadweight-loss"],
        xref: ["economics"],
      },
      {
        name: "Laffer curve",
        description: "Relationship between tax rates and revenue: revenue is zero at 0% and 100% rates, and peaks somewhere between.",
        keyPrinciple: "Revenue-maximizing rate is empirically debated; estimates for the US top marginal rate range widely (50–80%). Used to argue tax cuts are self-financing if above the revenue-maximizing rate. Contested: most economists find current US top rates below the revenue-maximizing rate. CONTESTED.",
        tags: ["theory", "Laffer", "dynamic-scoring"],
        xref: ["economics"],
        status: "contested",
      },
      {
        name: "Tax expenditure budget",
        description: "Annual government estimate of revenue cost of each tax preference, published alongside the regular budget.",
        keyPrinciple: "US: OMB and JCT produce separate estimates. UK: HMRC publishes 'tax reliefs' statistics. Allows comparison of tax preferences with direct expenditure programs. Not additive (preferences interact), so individual estimates overstate combined cost.",
        tags: ["theory", "expenditures", "budget", "policy"],
      },
      {
        name: "Progressivity vs. regressivity",
        description: "A tax is progressive if effective rates rise with income; regressive if they fall.",
        keyPrinciple: "US federal income tax is progressive. Payroll tax is regressive (SS cap) and flat. Sales tax is regressive in most analyses (lower-income households spend more as a share of income). Carbon taxes are regressive without rebates. Overall federal system is moderately progressive; overall fiscal system progressivity depends on spending.",
        tags: ["theory", "progressive", "regressive", "distributional"],
        xref: ["economics"],
      },
    ],
  },

  // ── Family 2 ──────────────────────────────────────────────────────────────
  {
    slug: "tax-incidence",
    number: 2,
    name: "Tax Incidence & Shifting",
    blurb: "Who ultimately bears the economic burden of a tax — which often differs from who legally pays it.",
    section: "A",
    color: "amber",
    entries: [
      {
        name: "Statutory vs. economic incidence",
        description: "Statutory incidence is who legally remits the tax; economic incidence is who bears the real cost.",
        keyPrinciple: "They can diverge completely. Payroll tax split 50/50 by statute; economic incidence falls mostly on labor because labor supply is relatively inelastic. The statutory split is economically irrelevant if both sides of the market clear at the same gross-of-tax price.",
        tags: ["incidence", "labor", "statutory"],
        xref: ["economics"],
      },
      {
        name: "Elasticity and burden sharing",
        description: "The party with less elastic supply or demand bears more of the tax burden.",
        keyPrinciple: "If supply is perfectly inelastic (e.g., land), suppliers bear 100% of the tax regardless of statutory incidence. If demand is perfectly inelastic, buyers bear 100%. Tax burden splits in proportion to relative elasticities. This is the core principle of tax incidence analysis.",
        tags: ["incidence", "elasticity"],
        xref: ["economics"],
      },
      {
        name: "Harberger model",
        description: "General-equilibrium model of corporate income tax incidence in a two-sector economy.",
        keyPrinciple: "Arnold Harberger (1962): in long-run equilibrium with mobile capital, the corporate tax falls on all capital (not just corporate sector) as capital migrates until after-tax returns equalize. Criticized for not accounting for open economies where capital is internationally mobile — in that case, workers bear more burden.",
        tags: ["incidence", "corporate", "Harberger", "capital"],
        xref: ["economics"],
      },
      {
        name: "Labor vs. capital incidence",
        description: "Whether labor or capital bears the burden of a tax is an empirical question that varies by market and policy context.",
        keyPrinciple: "Short run: capital bears more corporate tax (fixed in the short run). Long run: depends on international capital mobility. Recent empirical literature (Clausing, Suárez Serrato) finds workers bear 30–60% of the corporate tax through lower wages — this is contested. CONTESTED.",
        tags: ["incidence", "labor", "capital"],
        xref: ["economics"],
        status: "contested",
      },
      {
        name: "Forward vs. backward shifting",
        description: "Forward shifting: sellers pass tax to buyers through higher prices. Backward shifting: sellers absorb tax through lower producer margins.",
        keyPrinciple: "Excise taxes are typically shifted forward to consumers. Corporate taxes may be shifted backward to labor (lower wages) or forward to consumers (higher prices). Direction and degree depend on market structure and elasticities.",
        tags: ["incidence", "shifting", "forward", "backward"],
      },
      {
        name: "Tax capitalization",
        description: "Taxes on a fixed factor of production are reflected in the price of that asset rather than ongoing income.",
        keyPrinciple: "A property tax increase on land reduces the present value of net rents, lowering land prices. The buyer of the land after the tax increase suffers no ongoing burden — the original owner bears it through the price decline. Relevant to property tax reform and Proposition 13 analysis.",
        tags: ["incidence", "capitalization", "property", "land"],
        xref: ["economics"],
      },
      {
        name: "Lump-sum taxation",
        description: "A fixed tax not varying with any economic decision — theoretically efficient but practically infeasible.",
        keyPrinciple: "Lump-sum taxes cause no substitution effect and hence zero deadweight loss. Pure first-best. But ability-based lump-sum taxes require knowing unobservable ability (Mirrlees 1971). Head taxes (poll taxes) are a crude approximation. The UK poll tax (1989-91) caused political revolt and was repealed.",
        tags: ["theory", "efficiency", "lump-sum", "poll-tax"],
        xref: ["economics"],
      },
      {
        name: "Incidence of corporate income tax",
        description: "The distribution of the corporate income tax burden among shareholders, workers, and consumers — one of the most contested questions in public finance.",
        keyPrinciple: "CBO traditionally assumed 75% capital / 25% labor. JCT uses 25% labor. Treasury under Obama moved to 82% capital. Empirical studies diverge. In a global economy with mobile capital, workers likely bear a larger share than in a closed-economy Harberger model. CONTESTED.",
        tags: ["incidence", "corporate", "contested"],
        xref: ["economics"],
        status: "contested",
      },
      {
        name: "Optimal commodity taxation (inverse elasticity rule)",
        description: "Tax rates should be inversely proportional to price elasticity of demand to minimize excess burden for a given revenue.",
        keyPrinciple: "Ramsey rule: t_i/p_i ∝ 1/ε_i. Goods with inelastic demand (food, fuel) should be taxed at higher rates. Conflicts with distributional concerns (necessities are inelastic but consumed heavily by low-income households). Equity-efficiency tradeoff is central.",
        tags: ["optimal-taxation", "Ramsey", "commodity"],
        xref: ["economics"],
      },
      {
        name: "International incidence and capital mobility",
        description: "In open economies, the incidence of capital taxes shifts toward labor as capital is internationally mobile.",
        keyPrinciple: "High capital mobility means capital flows until after-tax returns equalize globally. A unilateral corporate tax increase is therefore borne by immobile labor. This is the theoretical basis for OECD Pillar Two: coordinated minimum taxation to reduce the incentive to shift capital to low-tax jurisdictions.",
        tags: ["incidence", "international", "capital-mobility"],
        xref: ["economics", "governance"],
      },
    ],
  },

  // ── Family 3 ──────────────────────────────────────────────────────────────
  {
    slug: "personal-income-tax",
    number: 3,
    name: "Personal Income Tax",
    blurb: "The structure of individual income taxation — gross income, deductions, credits, AMT, and the TCJA changes.",
    section: "B",
    color: "blue",
    entries: [
      {
        name: "Gross income (IRC § 61)",
        description: "All income from whatever source derived, unless specifically excluded by the Code.",
        keyPrinciple: "Breathtakingly broad: wages, salaries, business income, rents, royalties, dividends, interest, alimony (pre-TCJA), prizes, cancellation of debt income, illegal income. Glenshaw Glass (1955) test: undeniable accession to wealth, clearly realized, over which taxpayer has complete dominion.",
        citation: "Commissioner v. Glenshaw Glass, 348 U.S. 426 (1955)",
        tags: ["income", "gross-income", "IRC-61"],
        xref: ["law"],
        status: "landmark",
      },
      {
        name: "Adjusted gross income (AGI)",
        description: "Gross income minus above-the-line deductions; the key threshold for most phase-outs and limitations.",
        keyPrinciple: "Above-the-line deductions include: trade/business expenses, self-employment tax deduction, IRA contributions, student loan interest, alimony (pre-TCJA). AGI gates eligibility for EITC, Roth IRA contributions, medical expense deduction (>7.5% AGI), and numerous other provisions.",
        tags: ["income", "AGI", "above-the-line"],
      },
      {
        name: "Standard deduction",
        description: "Flat amount subtracted from AGI in lieu of itemizing deductions.",
        keyPrinciple: "TCJA 2017 nearly doubled it (2024: $14,600 single, $29,200 MFJ; verify at build). Result: share of returns itemizing fell from ~30% to ~10%. Simplification benefit; reduces value of targeted deductions like mortgage interest and charitable giving for most taxpayers.",
        tags: ["deductions", "standard-deduction", "TCJA"],
      },
      {
        name: "Itemized deductions",
        description: "Specific deductions that replace the standard deduction for taxpayers who exceed the standard deduction threshold.",
        keyPrinciple: "Major categories: state and local taxes (SALT, capped at $10,000 by TCJA), mortgage interest, charitable contributions, medical expenses >7.5% AGI. Most taxpayers now take the standard deduction, so itemized deductions primarily benefit higher-income homeowners in high-tax states.",
        tags: ["deductions", "itemized", "SALT", "mortgage"],
      },
      {
        name: "Alternative minimum tax (AMT)",
        description: "A parallel income tax system with fewer preferences that ensures high-income taxpayers pay a minimum amount.",
        keyPrinciple: "AMTI starts with regular income and adds back preferences (depreciation, SALT, ISO exercise). TCJA 2017 dramatically increased exemptions ($85,700 single in 2024; verify at build) and phaseout thresholds, eliminating AMT liability for most individual taxpayers. Corporate AMT eliminated by TCJA, replaced by book minimum tax (IRA 2022) for very large corps.",
        tags: ["AMT", "minimum-tax", "TCJA"],
      },
      {
        name: "Tax brackets and marginal rates",
        description: "Graduated rate structure where higher slices of income are taxed at progressively higher rates.",
        keyPrinciple: "2024 US brackets: 10/12/22/24/32/35/37% (verify exact thresholds at build; they adjust for inflation). The marginal rate applies only to the next dollar earned in that bracket, not to all income. The TCJA reduced most brackets and doubled the standard deduction. The 37% rate schedule is set to expire after 2025 absent legislation.",
        tags: ["brackets", "marginal-rate", "TCJA"],
        status: "open",
      },
      {
        name: "Effective vs. marginal tax rate",
        description: "Effective rate is total tax divided by total income; marginal rate is the rate on the next dollar of income.",
        keyPrinciple: "A taxpayer in the 37% bracket does not pay 37% on all income — only on the portion above the threshold. The effective rate will always be lower. The distinction matters enormously in public debate about tax burdens. Statutory rate ≠ effective rate ≠ average rate in common usage.",
        tags: ["rates", "marginal", "effective"],
        xref: ["economics"],
      },
      {
        name: "Tax credits",
        description: "Dollar-for-dollar reductions in tax liability, more valuable than deductions of equal amount.",
        keyPrinciple: "Refundable credits (EITC, CTC, AOTC partially) can produce a refund exceeding taxes owed. Nonrefundable credits (foreign tax credit, child and dependent care credit) reduce liability to zero at most. Refundable credits are effectively direct spending through the tax system.",
        tags: ["credits", "refundable", "nonrefundable"],
      },
      {
        name: "Earned Income Tax Credit (EITC)",
        description: "Refundable credit for low- and moderate-income workers, phased in and then phased out with earned income.",
        keyPrinciple: "Largest cash transfer program in the US tax code for working families. Maximum credit for 3+ children: ~$7,830 in 2024 (verify at build). Phase-out creates implicit marginal rates of ~21% in addition to statutory rates. High improper payment rate (~31% by IRS estimate) due to complexity of eligibility rules.",
        tags: ["EITC", "refundable", "poverty", "labor"],
        xref: ["economics"],
      },
      {
        name: "Child Tax Credit (CTC)",
        description: "Partially refundable credit of up to $2,000 per qualifying child under age 17.",
        keyPrinciple: "Refundable portion (Additional Child Tax Credit) up to $1,700 in 2024 (verify at build). ARPA 2021 temporarily expanded to $3,000/$3,600 with monthly payments and made fully refundable — estimated to cut child poverty nearly in half. Expired after 2021; return to pre-ARPA structure. Whether TCJA CTC expansion survives beyond 2025 is open.",
        tags: ["CTC", "child-credit", "refundable", "ARPA"],
        status: "open",
      },
      {
        name: "Phase-out provisions",
        description: "Credits and deductions that reduce in value as income rises, creating implicit marginal rates above statutory rates.",
        keyPrinciple: "Examples: EITC phase-out adds ~21% to marginal rates; CTC phase-out adds ~5%; charitable deduction limits at high income. Stacking of phase-outs creates marginal rate spikes, sometimes exceeding 50% at certain income levels. Creates poverty traps and work disincentives at phase-in/phase-out ranges.",
        tags: ["phase-out", "marginal-rate", "poverty-trap"],
        xref: ["economics"],
      },
      {
        name: "Filing status",
        description: "Classification (single, married filing jointly, married filing separately, head of household, qualifying widow/er) that determines rates and standard deduction.",
        keyPrinciple: "Marriage penalty: two earners with similar incomes pay more combined tax filing jointly than as singles. Marriage bonus: one-earner couples pay less. MFJ standard deduction is exactly double single — but brackets are not fully doubled, creating the penalty for dual-earner couples at higher incomes.",
        tags: ["filing-status", "marriage-penalty", "MFJ"],
      },
      {
        name: "Above-the-line vs. below-the-line deductions",
        description: "Above-the-line deductions reduce AGI; below-the-line deductions reduce taxable income from AGI.",
        keyPrinciple: "Above-the-line (deductible regardless of whether you itemize): business expenses, IRA contributions, student loan interest, self-employment tax, alimony (pre-TCJA). Below-the-line: itemized deductions or standard deduction. Above-the-line deductions are more valuable because they reduce AGI, which gates other phase-outs.",
        tags: ["deductions", "AGI", "above-the-line", "below-the-line"],
      },
      {
        name: "Head of household (HOH)",
        description: "Favorable filing status for unmarried taxpayers who maintain a home for a qualifying person.",
        keyPrinciple: "Rates intermediate between single and MFJ. Requires: unmarried (or considered unmarried), paid >50% of home costs, qualifying child/dependent lived in home >6 months. TCJA 2017 made no changes. IRS reports high non-compliance: HOH is one of the most common erroneous filing statuses.",
        tags: ["filing-status", "HOH", "dependents"],
      },
    ],
  },

  // ── Family 4 ──────────────────────────────────────────────────────────────
  {
    slug: "capital-gains-investment",
    number: 4,
    name: "Capital Gains & Investment Income",
    blurb: "Preferential treatment of long-term capital gains, the realization doctrine, and the major planning tools around investment income.",
    section: "B",
    color: "indigo",
    entries: [
      {
        name: "Realization doctrine",
        description: "Gain or loss is recognized for tax purposes only when a disposition or other realization event occurs, not merely upon appreciation.",
        keyPrinciple: "Eisner v. Macomber (1920): stock dividend did not constitute realized income. Constitutional and statutory bedrock of US income tax. Economically distortive: the 'lock-in effect' discourages selling appreciated assets. Central to debates about taxing unrealized gains. See Moore v. United States (2024).",
        citation: "Eisner v. Macomber, 252 U.S. 189 (1920)",
        tags: ["realization", "capital-gains", "constitutional"],
        xref: ["law"],
        status: "landmark",
      },
      {
        name: "Long-term vs. short-term capital gains",
        description: "Assets held more than one year qualify for preferential long-term capital gains rates; shorter holding periods are taxed at ordinary rates.",
        keyPrinciple: "Long-term rates: 0% (income ≤ ~$47,025 single), 15% (~$47,025–$518,900), 20% (above $518,900) in 2024 — verify at build. Plus 3.8% NIIT for high earners. Short-term rates equal ordinary income rates (up to 37%). The rate differential creates strong lock-in and holding period incentives.",
        tags: ["capital-gains", "long-term", "short-term", "preferential-rate"],
        xref: ["finance"],
      },
      {
        name: "Net investment income tax (NIIT)",
        description: "3.8% surtax on net investment income for taxpayers above AGI thresholds.",
        keyPrinciple: "IRC § 1411. Applies to interest, dividends, capital gains, rents, royalties, and passive activity income. Threshold: $200,000 (single), $250,000 (MFJ) — not indexed for inflation. Enacted by ACA 2010. Combined top rate on investment income: 23.8% (20% + 3.8%).",
        tags: ["NIIT", "investment-income", "ACA", "surtax"],
        xref: ["finance"],
      },
      {
        name: "Stepped-up basis at death",
        description: "Inheritors receive a cost basis equal to the fair market value of property at the decedent's date of death, eliminating embedded gain.",
        keyPrinciple: "IRC § 1014. The most valuable single tax preference in the US: eliminates deferred capital gain tax on all appreciation accumulated during the decedent's lifetime. A $10M estate with $8M embedded gain owes zero capital gains tax at death. Estimated cost: $40-60B/year (verify at build). Proposals to eliminate (Biden Budget) have not passed. Paired with estate tax.",
        tags: ["stepped-up-basis", "death", "estate", "planning"],
        xref: ["finance"],
      },
      {
        name: "Carried interest",
        description: "The fund manager's share of profits from a private equity or hedge fund, taxed as long-term capital gains rather than ordinary income.",
        keyPrinciple: "Managers receive 20% of fund profits (the 'carry') without contributing 20% of capital — a compensation item taxed at preferential capital gains rates. Critics: compensation should be ordinary income. TCJA extended holding period to 3 years for 20% rate. Legislative efforts to tax it as ordinary income have repeatedly stalled. CONTESTED.",
        tags: ["carried-interest", "private-equity", "preferred-rate"],
        xref: ["finance"],
        status: "contested",
      },
      {
        name: "Wash sale rule (IRC § 1091)",
        description: "A realized loss is disallowed if a substantially identical security is purchased within 30 days before or after the sale.",
        keyPrinciple: "Prevents harvesting a tax loss while maintaining the economic position. The disallowed loss is added to the basis of the replacement security, deferring (not permanently eliminating) the loss. Currently does not apply to cryptocurrencies (treated as property, not securities) — a contested gap. OPEN.",
        tags: ["wash-sale", "loss-harvesting", "crypto"],
        status: "open",
      },
      {
        name: "Installment sale (IRC § 453)",
        description: "A seller who receives payments over multiple years recognizes gain as payments are received, deferring tax.",
        keyPrinciple: "Gain recognized = (gross profit ratio) × each payment. Ordinary income component recognized fully when received. Interest imputed on deferred payments (§ 483, § 1274). Useful for closely held business sales and real estate. Not available for inventory, dealer property, or securities traded on established markets.",
        tags: ["installment-sale", "deferral", "IRC-453"],
        xref: ["finance"],
      },
      {
        name: "Like-kind exchange (IRC § 1031)",
        description: "Exchange of real property held for productive use or investment defers recognition of capital gain.",
        keyPrinciple: "TCJA 2017 narrowed to real property only (previously included personal property). Requires qualified intermediary; 45-day identification and 180-day closing windows. Boot received (cash or non-like-kind property) is recognized. Gain is deferred, not forgiven — reduced basis in replacement property preserves embedded gain.",
        tags: ["1031-exchange", "deferral", "real-estate"],
        xref: ["finance"],
      },
      {
        name: "Qualified Opportunity Zones (QOZ)",
        description: "Investment of capital gains into designated low-income census tracts defers and potentially reduces capital gain tax.",
        keyPrinciple: "Created by TCJA 2017, IRC §§ 1400Z-1 and 1400Z-2. Deferral until 2026 or earlier sale. 10% basis step-up if held 5 years; 15% if held 7 years (these elections largely expired as of 2022 deadlines). Hold 10 years: gain on OZ investment itself excluded. Effectiveness in promoting low-income investment is contested. CONTESTED.",
        tags: ["opportunity-zones", "deferral", "TCJA", "low-income"],
        status: "contested",
      },
      {
        name: "Tax-loss harvesting",
        description: "Systematic realization of capital losses to offset capital gains, reducing current-year tax liability.",
        keyPrinciple: "Capital losses offset capital gains dollar-for-dollar; excess losses offset up to $3,000 ordinary income per year; remaining losses carry forward indefinitely. Wash sale rule (30-day window) limits the strategy for securities but not crypto. Direct indexing enables per-security harvesting at scale.",
        tags: ["loss-harvesting", "capital-gains", "planning"],
        xref: ["finance"],
      },
      {
        name: "Qualified dividend income",
        description: "Dividends from domestic and qualifying foreign corporations taxed at long-term capital gains rates rather than ordinary income rates.",
        keyPrinciple: "Must be from a qualified domestic or treaty-covered foreign corporation and held for minimum period (60 days in 121-day window). Reduces the effective double-taxation of corporate earnings at shareholder level. Non-qualified dividends (money market, REITs, short-holding) taxed at ordinary rates.",
        tags: ["dividends", "qualified", "preferred-rate"],
        xref: ["finance"],
      },
      {
        name: "Basis tracking methods",
        description: "Different methods for identifying which shares are sold — FIFO, specific identification, or average cost — yield different tax outcomes.",
        keyPrinciple: "FIFO: oldest shares sold first (may trigger higher gains). Specific identification: taxpayer designates which shares (most flexible). Average cost: SEC-registered mutual funds (simplest). The choice is locked in upon first sale for mutual funds in some brokerages. High-basis-first sells minimize current gain.",
        tags: ["basis", "FIFO", "specific-identification", "planning"],
        xref: ["finance"],
      },
    ],
  },

  // ── Family 5 ──────────────────────────────────────────────────────────────
  {
    slug: "corporate-income-tax",
    number: 5,
    name: "Corporate Income Tax",
    blurb: "C-corporation-level taxation — the flat 21% rate, double taxation, loss rules, and the book minimum tax.",
    section: "B",
    color: "sky",
    entries: [
      {
        name: "Corporate income tax (flat 21%)",
        description: "Federal income tax imposed on C-corporation taxable income; flat 21% rate since TCJA 2017.",
        keyPrinciple: "Formerly graduated to 35% top rate. TCJA rate cut was the most significant corporate rate change since 1986. Rate is set to remain at 21% unless changed by Congress — unlike individual TCJA provisions, the corporate rate has no statutory sunset. Some proposals to raise to 25-28% have not passed (verify 2026 status).",
        tags: ["corporate-tax", "CIT", "21%", "TCJA"],
        status: "open",
      },
      {
        name: "Double taxation of corporate income",
        description: "Corporate earnings are taxed at the entity level (21%) and again at the shareholder level as dividends or capital gains.",
        keyPrinciple: "Classical system. Combined top rate: 21% corporate + 23.8% on qualified dividends (20% + 3.8% NIIT) = ~39.8% integrated rate. The integrated rate is lower than many assume, and the shareholder-level tax is deferrable and can be eliminated via stepped-up basis at death. Pass-through entities avoid the first layer.",
        tags: ["double-taxation", "dividends", "integration"],
        xref: ["finance"],
      },
      {
        name: "Dividends-received deduction (DRD)",
        description: "Corporations receiving dividends from domestic corporations can deduct 50%, 65%, or 100% of the dividend received.",
        keyPrinciple: "50% DRD for <20% ownership; 65% for 20-79% ownership; 100% for 80%+ ownership (affiliated group). Prevents triple (or more) taxation as earnings flow up a corporate chain. TCJA 2017 reduced rates (from 70%/80%/100%) to align with the lower corporate rate.",
        tags: ["DRD", "dividends", "corporate", "intercompany"],
      },
      {
        name: "Net operating loss (NOL)",
        description: "Losses that exceed current-year income can offset income in other years, smoothing tax across the business cycle.",
        keyPrinciple: "Pre-TCJA: 2-year carryback, 20-year carryforward, 100% offset. TCJA: carryback eliminated (except farming: 2 years), indefinite carryforward, but capped at 80% of taxable income in any year. CARES Act 2020 temporarily restored 5-year carryback for 2018-2020. The 80% cap limits the ability to fully shelter large future income.",
        tags: ["NOL", "loss", "carryforward", "TCJA"],
      },
      {
        name: "Book-tax differences",
        description: "Differences between financial accounting (GAAP) income and taxable income create deferred tax assets and liabilities on the balance sheet.",
        keyPrinciple: "Temporary differences (depreciation timing, warranty reserves) reverse over time. Permanent differences (tax-exempt income, non-deductible meals) do not. DTAs represent future tax savings; DTLs represent future tax payments. Large book-tax gaps have attracted scrutiny — some corporations report large GAAP profits while paying little current tax.",
        tags: ["book-tax", "GAAP", "deferred-tax"],
        xref: ["finance"],
      },
      {
        name: "Corporate alternative minimum tax (CAMT)",
        description: "15% minimum tax on adjusted financial statement income (book income) for very large corporations.",
        keyPrinciple: "Reinstated by Inflation Reduction Act 2022. Applies to corporations with average annual adjusted financial statement income >$1 billion. Designed to ensure profitable corporations pay at least 15% on book income. Complex interaction with regular tax, AMT credits, and foreign tax credits. Significant compliance burden.",
        tags: ["CAMT", "book-minimum-tax", "IRA-2022"],
        status: "open",
      },
      {
        name: "Excise tax on stock buybacks",
        description: "1% excise tax on the fair market value of corporate stock repurchased from shareholders.",
        keyPrinciple: "Enacted by Inflation Reduction Act 2022, IRC § 4501. Applies to publicly traded domestic corporations. Netting rule: reduce by issuances during the year. Proposed increase to 4% in Biden budgets. Creates mild incentive toward dividends vs. buybacks, though the tax is small enough to not materially change corporate behavior.",
        tags: ["buybacks", "excise", "IRA-2022"],
        status: "open",
      },
      {
        name: "Consolidated return",
        description: "An affiliated group of corporations (80%+ stock ownership) may file a single consolidated return, netting gains and losses across entities.",
        keyPrinciple: "IRC § 1501. Allows loss offsets across the group. Complex intercompany transaction elimination rules. Benefits: simplification, loss utilization, deferral of intercompany gains. Costs: complex regulations; some states do not conform to federal consolidation rules.",
        tags: ["consolidated-return", "affiliated-group"],
      },
      {
        name: "Accumulated earnings tax",
        description: "20% penalty tax on accumulated taxable income beyond the reasonable needs of a corporation.",
        keyPrinciple: "IRC § 531. Designed to prevent using the corporation as a tax-deferred investment vehicle by retaining earnings instead of paying taxable dividends. $250,000 accumulated earnings credit ($150,000 for personal holding companies). Rarely litigated due to difficulty of IRS proving unreasonable accumulation. Practically dead letter for most large corps.",
        tags: ["accumulated-earnings", "penalty"],
      },
      {
        name: "Section 382 limitation",
        description: "Annual limitation on a corporation's use of pre-acquisition NOLs following an ownership change of more than 50%.",
        keyPrinciple: "IRC § 382. Prevents trafficking in NOL corporations. Annual limit = value of loss corporation × long-term tax-exempt rate. Built-in gains and losses also subject to 5-year recognition period. Key M&A tax consideration — must model NOL utilization as part of deal structure.",
        tags: ["NOL", "ownership-change", "M&A"],
        xref: ["finance"],
      },
      {
        name: "Section 199A (QBI deduction)",
        description: "20% deduction for qualified business income from pass-through entities — the pass-through rate cut in TCJA 2017.",
        keyPrinciple: "IRC § 199A. Reduces effective top rate on QBI to 29.6% (37% × 0.8). Complex limitations for specified service trades or businesses (law, finance, health, consulting) above income thresholds. W-2 wage and capital limitations kick in above thresholds. Set to expire after 2025 with other TCJA individual provisions — major legislative battle looming.",
        tags: ["199A", "QBI", "pass-through", "TCJA"],
        status: "open",
      },
      {
        name: "TCJA 2017 (Tax Cuts and Jobs Act)",
        description: "The most significant US tax overhaul since 1986, cutting the corporate rate, restructuring individual rates, and fundamentally changing international tax.",
        keyPrinciple: "Key changes: 35%→21% corporate rate; 37% top individual rate; near-doubled standard deduction; $10,000 SALT cap; 100% bonus depreciation; international territorial hybrid (GILTI, BEAT, FDII); doubled estate exemption. Individual provisions expire after 2025; corporate provisions are permanent. 2025 'TCJA cliff' will be defining legislative moment.",
        tags: ["TCJA", "2017", "tax-reform"],
        status: "open",
      },
    ],
  },

  // ── Family 6 ──────────────────────────────────────────────────────────────
  {
    slug: "business-entity-taxation",
    number: 6,
    name: "Business Entity Taxation",
    blurb: "Pass-throughs vs. C-corps, check-the-box elections, self-employment tax, and the entity-level tax treatment of partnerships and S-corps.",
    section: "B",
    color: "cyan",
    entries: [
      {
        name: "C corporation",
        description: "Entity taxed at the corporate level on its income; shareholders taxed again on dividends and capital gains.",
        keyPrinciple: "Classic double-taxation structure. Advantages: unlimited shareholders, multiple share classes, easier VC investment, potential for lower integrated rate via deferral and stepped-up basis at death. Disadvantages: double taxation on current distributions. Preferred for IPO-track companies and international structures.",
        tags: ["C-corp", "double-taxation", "entity"],
      },
      {
        name: "S corporation",
        description: "Pass-through entity taxed at shareholder level; one class of stock, maximum 100 US shareholders.",
        keyPrinciple: "IRC Subchapter S. Income and loss pass through to shareholders on Schedule K-1. Key limitation: shareholders receiving wages must take reasonable compensation (IRS scrutiny). Avoids double taxation but limits to 100 US individual/trust shareholders; no nonresident alien shareholders; no preferred stock. State conformity varies.",
        tags: ["S-corp", "pass-through", "reasonable-compensation"],
      },
      {
        name: "Partnership taxation",
        description: "Pass-through entity with the most flexibility — allocations, distributions, and contributed property treated with maximum tax sensitivity.",
        keyPrinciple: "IRC Subchapter K. Partners take income/loss on K-1. Taxable income allocations governed by § 704(b) substantial economic effect. Highly flexible: disproportionate allocations allowed if they have economic substance. Basis: outside basis (partner's tax basis in the partnership interest) vs. inside basis (partnership's basis in its assets).",
        tags: ["partnership", "pass-through", "subchapter-K"],
        xref: ["finance"],
      },
      {
        name: "LLC (limited liability company) taxation",
        description: "A flexible state-law entity that, for federal tax purposes, is classified based on number of members and any elections made.",
        keyPrinciple: "Single-member LLC: disregarded entity (default) or corporation (by election). Multi-member LLC: partnership (default) or corporation (by election). The check-the-box regulations allow the entity to choose its federal tax classification without changing its state-law structure. Most startup LLCs are treated as partnerships.",
        tags: ["LLC", "check-the-box", "disregarded"],
      },
      {
        name: "Check-the-box regulations",
        description: "A simplified entity classification system allowing most non-corporate entities to elect their federal tax treatment.",
        keyPrinciple: "Finalized 1996 (Rev. Proc. 95-16 was predecessor). 'Per se corporations' (publicly traded, state-chartered corps) cannot elect out. Everything else can elect. Dramatically simplified entity classification. Also has significant international implications — treating foreign subsidiaries as disregarded enables certain planning structures (hybrid mismatches).",
        tags: ["check-the-box", "entity-classification", "election"],
      },
      {
        name: "Self-employment tax (SECA)",
        description: "Self-employed individuals pay both employer and employee shares of Social Security and Medicare taxes — 15.3% on net SE income.",
        keyPrinciple: "SE tax = 15.3% on first $168,600 (2024 SS wage base, verify at build) + 2.9% Medicare on excess + additional 0.9% on SE income over $200,000 (single). Deductible: half of SE tax is above-the-line. S-corp strategy: pay wages (subject to payroll tax) and take remaining income as distributions (not subject to SE tax) — but requires reasonable compensation.",
        tags: ["self-employment", "SECA", "payroll-tax"],
      },
      {
        name: "Reasonable compensation (S-corp requirement)",
        description: "S-corp shareholders who provide services must pay themselves a reasonable salary before taking distributions, to prevent payroll tax avoidance.",
        keyPrinciple: "IRS scrutinizes S-corp returns where shareholders take minimal or no wages. Reasonable compensation benchmarked to what similar employees would earn. Consequences of non-compliance: IRS recharacterizes distributions as wages, assessing back payroll taxes and penalties. Active area of IRS enforcement.",
        tags: ["S-corp", "reasonable-compensation", "payroll-tax"],
      },
      {
        name: "Basis in partnerships (inside vs. outside)",
        description: "Outside basis is the partner's tax basis in the partnership interest; inside basis is the partnership's basis in its assets — they can diverge.",
        keyPrinciple: "§ 754 election: optional election allowing step-up in inside basis on transfer of a partnership interest or distribution, matching inside to outside. Without the election, a buyer of a partnership interest may take depreciation on assets already fully depreciated. Prevents asymmetry on sale. Becomes irrevocable once made.",
        tags: ["partnership", "basis", "754-election"],
        xref: ["finance"],
      },
      {
        name: "At-risk rules (IRC § 465)",
        description: "Limits a taxpayer's deduction of losses to the amount economically at risk in the activity.",
        keyPrinciple: "Prevents nonrecourse shelter abuse: taxpayer cannot deduct losses funded by debt for which they bear no economic risk. At-risk amount includes cash contributed, recourse debt, and qualified nonrecourse financing (real estate). First line of defense against passive shelters; interacts with passive activity loss rules.",
        tags: ["at-risk", "shelter", "IRC-465"],
      },
      {
        name: "Passive activity loss rules (IRC § 469)",
        description: "Losses from passive activities (in which the taxpayer does not materially participate) can only offset passive income.",
        keyPrinciple: "Enacted in 1986 to curtail tax shelter abuse. Passive losses carry forward and are released on disposition of the activity. Real estate professional exception: 750 hours/year + more than half personal service time; qualifies rental activities as non-passive. Portfolio income (interest, dividends) is not passive — cannot absorb passive losses.",
        tags: ["passive-activity", "real-estate", "shelter", "IRC-469"],
      },
    ],
  },

  // ── Family 7 ──────────────────────────────────────────────────────────────
  {
    slug: "international-tax-basics",
    number: 7,
    name: "International Tax — Basics",
    blurb: "The architecture of cross-border taxation: residence, source, worldwide vs. territorial systems, treaties, and controlled foreign corporations.",
    section: "C",
    color: "teal",
    entries: [
      {
        name: "Residence-based taxation",
        description: "Countries tax their tax residents on worldwide income regardless of where that income is earned.",
        keyPrinciple: "US and Eritrea are the only countries that also tax based on citizenship (not just residence). Resident individuals owe US tax on all income. Foreign tax credits limit double taxation. Exit tax (§ 877A) imposed on long-term residents and citizens who relinquish residency/citizenship.",
        tags: ["residence", "worldwide", "international"],
      },
      {
        name: "Source-based taxation",
        description: "Countries tax income that arises within their territory regardless of the residence of the income earner.",
        keyPrinciple: "The source country has first right to tax under most treaties. Source rules determine whether income is US-source (taxable to nonresidents) or foreign-source (relevant for foreign tax credit calculations). Key sourcing rules: wages (where services performed), dividends (where corporation incorporated), royalties (where property used).",
        tags: ["source", "withholding", "international"],
      },
      {
        name: "Territorial tax system",
        description: "A country taxes only income arising within its territory; foreign income of resident corporations is exempt.",
        keyPrinciple: "Most OECD countries. TCJA 2017 moved the US toward a quasi-territorial system via the participation exemption (100% DRD on dividends from foreign subsidiaries) combined with GILTI minimum tax to backstop the exemption. Pure territoriality would exempt all foreign income; US territorial is hybrid with significant anti-abuse overlay.",
        tags: ["territorial", "participation-exemption", "TCJA"],
        xref: ["governance"],
      },
      {
        name: "Worldwide tax system",
        description: "A country taxes all income of its residents wherever earned, granting credits for foreign taxes paid to prevent double taxation.",
        keyPrinciple: "US operated a worldwide system through 2017 with deferral — foreign income of CFCs was generally not taxed until repatriated. Deferral incentivized parking profits offshore. The €2 trillion+ offshore cash accumulation by US multinationals led to the TCJA territorial reform and GILTI minimum tax.",
        tags: ["worldwide", "deferral", "CFC"],
      },
      {
        name: "Foreign tax credit (FTC)",
        description: "US taxpayers can credit foreign income taxes paid against their US tax liability on the same income, preventing double taxation.",
        keyPrinciple: "IRC § 901. Credit limited to US tax on foreign-source income (limitation = foreign-source income / worldwide income × US tax). Separate 'baskets' for different income categories prevent cross-crediting. Post-TCJA: complex interaction with GILTI basket. BEAT applies regardless of FTCs. Excess credits carry back 1 year and forward 10 years.",
        tags: ["FTC", "foreign-tax-credit", "double-taxation"],
      },
      {
        name: "Tax treaty",
        description: "Bilateral agreements that allocate taxing rights between countries, reduce withholding rates, and provide procedural protections.",
        keyPrinciple: "US has ~70 income tax treaties. Key functions: reduce source-country withholding on dividends (typically 5-15%), interest (typically 0-10%), royalties (typically 0-10%); define permanent establishment; provide mutual agreement procedure (MAP) for dispute resolution; exchange of information. Treaty shopping limited by limitation on benefits (LOB) and principal purpose tests.",
        tags: ["treaty", "withholding", "MAP"],
        xref: ["law", "governance"],
      },
      {
        name: "OECD Model Tax Convention",
        description: "The standard template for bilateral income tax treaties; sets default rules for allocating taxing rights.",
        keyPrinciple: "Competing model: UN Model Convention (favors source countries; used by developing nations). OECD Model favors residence countries. Articles 7 (business profits), 9 (associated enterprises), 12 (royalties), 23A/23B (exemption/credit method) are central. Updated periodically; 2017 update incorporated BEPS measures.",
        tags: ["OECD", "model-treaty", "international"],
        xref: ["governance"],
      },
      {
        name: "Transfer pricing",
        description: "Intercompany transactions between related parties must be priced at arm's length — as if between independent parties.",
        keyPrinciple: "IRC § 482; OECD Transfer Pricing Guidelines. Methods: comparable uncontrolled price, resale price, cost plus, profit split, transactional net margin method. Largest single area of international tax litigation. Apple, Google, Amazon all fought major transfer pricing disputes with IRS and EU. Billions of dollars at stake in most large MNE audits.",
        tags: ["transfer-pricing", "arm's-length", "482"],
        xref: ["finance", "law"],
      },
      {
        name: "Permanent establishment (PE)",
        description: "A fixed place of business in the source country that gives that country the right to tax business profits attributable to it.",
        keyPrinciple: "OECD Model Article 5. Typical PEs: branch office, factory, mine, place of management. Deemed PEs: dependent agent with authority to conclude contracts. Digital economy created pressure on PE rules — companies serving markets without PE avoided source-country taxation. Addressed (partially) by BEPS Action 7 and Pillar One.",
        tags: ["PE", "permanent-establishment", "source"],
        xref: ["governance"],
      },
      {
        name: "Controlled foreign corporation (CFC)",
        description: "A foreign corporation more than 50% owned by US shareholders, whose passive and certain other income is taxed currently to the US shareholders.",
        keyPrinciple: "IRC § 951. Subpart F income (passive income, base company sales/services income) is included in US shareholder income currently regardless of distribution. TCJA: ownership threshold changed (attribution rules); added GILTI as additional current-inclusion category. Prevents deferral of passive income in low-tax foreign subsidiaries.",
        tags: ["CFC", "subpart-F", "deferral"],
      },
      {
        name: "Subpart F income",
        description: "Categories of CFC income taxed currently to US shareholders — primarily passive income and income from related-party transactions designed to strip earnings from the US.",
        keyPrinciple: "IRC § 951. Key categories: foreign personal holding company income (dividends, interest, royalties from non-active sources); foreign base company sales income (buying/selling through the CFC in third-party sales); foreign base company services income. De minimis exception if Subpart F < 5% of gross income. Post-TCJA: 50% deduction for GILTI creates effective minimum rate.",
        tags: ["subpart-F", "CFC", "passive-income"],
      },
      {
        name: "FATCA (Foreign Account Tax Compliance Act)",
        description: "US persons must report foreign financial accounts; foreign financial institutions must report US account holders or face 30% withholding.",
        keyPrinciple: "Enacted 2010; implemented via intergovernmental agreements (IGAs) with 110+ countries. US persons: Form 8938 (FATCA) in addition to FBAR (FinCEN 114). Foreign financial institutions: report US account holders or face 30% withholding on US-source payments. Most significant US unilateral assertion of extraterritorial tax enforcement.",
        tags: ["FATCA", "offshore", "foreign-accounts", "enforcement"],
        xref: ["law"],
      },
      {
        name: "Exit tax (IRC § 877A)",
        description: "US citizens and long-term residents who relinquish their status are treated as having sold all property at fair market value on the day before expatriation.",
        keyPrinciple: "Mark-to-market regime: gain above $866,000 exclusion (2024; verify at build) is recognized. Applies to 'covered expatriates' (high-income or high-net-worth individuals or those with tax compliance failures). Deferred compensation and interests in trusts also subject to special rules. One of the more aggressive extraterritorial tax provisions.",
        tags: ["exit-tax", "expatriation", "877A"],
      },
      {
        name: "Withholding tax (chapters 3 and 4)",
        description: "Source-country withholding on payments of US-source income (interest, dividends, royalties) to foreign persons.",
        keyPrinciple: "Chapter 3 (FDAP): 30% withholding on fixed, determinable, annual, or periodic income paid to foreign persons, reduced by treaty. Chapter 4 (FATCA): 30% withholding on withholdable payments to non-compliant FFIs and non-participating FFIs. Withholding agents bear liability for failure to withhold correctly.",
        tags: ["withholding", "FDAP", "FATCA", "Chapter-3"],
      },
    ],
  },
];
