import type { Family } from "./types";

export const FAMILIES_15_20: Family[] = [
  // ── Family 15 ──────────────────────────────────────────────────────────────
  {
    slug: "tax-fraud-criminal",
    number: 15,
    name: "Tax Fraud & Criminal Enforcement",
    blurb: "Criminal tax offenses, willfulness doctrine, offshore evasion enforcement, and the IRS whistleblower program.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Tax evasion (IRC § 7201)",
        description: "A felony: willful attempt to evade or defeat any federal tax or its payment.",
        keyPrinciple: "Elements: (1) existence of a tax deficiency, (2) willful attempt to evade, (3) affirmative acts (not mere failure to file). Maximum sentence: 5 years + fines. Landmark cases: Al Capone convicted on tax evasion (1931) when no other charges would stick. Willfulness requires knowledge that the conduct was unlawful — good-faith misunderstanding of the law is a defense (Cheek).",
        tags: ["evasion", "criminal", "7201", "willfulness"],
        xref: ["law"],
      },
      {
        name: "Failure to file / failure to pay (IRC §§ 7203, 7206)",
        description: "Separate criminal misdemeanor (failure to file) and felony (false return) offenses — distinct from § 7201 evasion.",
        keyPrinciple: "§ 7203: misdemeanor — willful failure to file, pay, or keep records. 1-year max. § 7206(1): felony — willfully making a false return under penalties of perjury. 3-year max. § 7206(2): felony — aiding or assisting in preparation of a false return. 3-year max. The signing of a tax return under § 7206(1) creates personal liability for the preparer as well as the filer.",
        tags: ["failure-to-file", "7203", "7206", "criminal"],
        xref: ["law"],
      },
      {
        name: "Willfulness and the Cheek doctrine",
        description: "Criminal tax offenses require willful conduct; a genuine, good-faith misunderstanding of the tax law (even if unreasonable) negates willfulness.",
        keyPrinciple: "Cheek v. United States (1991): tax law is complex; an actual belief (even if objectively wrong) that the law does not require filing or payment can defeat willfulness. Subjective standard — unlike most criminal law. Jury must believe the defendant's good-faith claim. 'Tax protester' arguments are not good-faith beliefs if the courts have repeatedly rejected them.",
        citation: "Cheek v. United States, 498 U.S. 192 (1991)",
        tags: ["Cheek", "willfulness", "good-faith", "criminal"],
        xref: ["law"],
        status: "landmark",
      },
      {
        name: "Klein conspiracy (18 U.S.C. § 371)",
        description: "Conspiracy to defraud the United States by impeding, impairing, or obstructing the IRS's lawful functions — broader than tax evasion.",
        keyPrinciple: "Does not require an underlying tax deficiency. Classic use: prosecuting promoters and facilitators who did not themselves evade tax. Elements: agreement, to impede IRS functions, with an overt act. United States v. Klein (1957). Often charged alongside § 7201 evasion or § 7206 false return. Has been used against foreign bank employees, promoters, and offshore facilitators.",
        citation: "United States v. Klein, 247 F.2d 908 (2d Cir. 1957)",
        tags: ["Klein-conspiracy", "conspiracy", "criminal", "371"],
        xref: ["law"],
      },
      {
        name: "Bank Secrecy Act and structuring",
        description: "Financial institutions must file Currency Transaction Reports (CTRs) for cash transactions >$10,000; structuring transactions to avoid CTRs is a federal crime.",
        keyPrinciple: "Structuring: breaking up transactions to stay below $10,000 — illegal even if the underlying money is clean. CTRs filed with FinCEN. Suspicious Activity Reports (SARs) for suspicious transactions regardless of amount. BSA requires extensive AML compliance programs. Cash-intensive businesses and cannabis businesses face heightened scrutiny.",
        tags: ["BSA", "structuring", "CTR", "FinCEN"],
        xref: ["law"],
      },
      {
        name: "FBAR (FinCEN 114) — foreign bank account reporting",
        description: "US persons with more than $10,000 aggregate in foreign financial accounts at any point in the year must file an annual FBAR.",
        keyPrinciple: "Filed electronically with FinCEN (not the IRS). Penalties: non-willful $10,000+ per violation; willful: greater of $100,000 or 50% of account balance per violation. Criminal penalties for willful failure. FBAR separate from FATCA Form 8938 (higher thresholds, filed with Form 1040). Bittner v. United States (2023): SCOTUS held the $10,000 per-year cap applies per form, not per account.",
        citation: "Bittner v. United States, 598 U.S. 85 (2023)",
        tags: ["FBAR", "offshore", "foreign-accounts", "penalties"],
        xref: ["law"],
        status: "landmark",
      },
      {
        name: "Offshore tax evasion enforcement",
        description: "US enforcement against offshore account concealment has transformed since 2008 — UBS prosecution, John Doe summons, OVDP, and FATCA have largely closed the Swiss bank secrecy shield.",
        keyPrinciple: "2009: UBS agreed to disclose ~4,450 accounts and pay $780M in penalties. John Doe summons: served on banks to identify unknown US account holders. OVDP (Offshore Voluntary Disclosure Program, 2009-2018): allowed taxpayers to come into compliance with reduced penalties. Streamlined procedures: available for non-willful violations with lower penalty. Post-FATCA, automatic information exchange has made offshore concealment far riskier.",
        tags: ["offshore", "UBS", "OVDP", "FATCA", "enforcement"],
        xref: ["governance"],
      },
      {
        name: "Tax shelter promoter penalties (IRC § 6700)",
        description: "Civil penalties for persons who organize or sell tax shelters based on fraudulent statements about their tax benefits.",
        keyPrinciple: "IRC § 6700: $1,000 per activity or 50% of gross income derived from the activity. IRC § 6701: penalties on preparer who aids and abets understatement. Injunctions under IRC § 7408 can bar promoters from continuing to sell abusive shelters. Major targets: listed transaction promoters, micro-captive insurance promoters, syndicated conservation easements.",
        tags: ["promoter", "shelter", "6700", "penalties"],
        xref: ["law"],
      },
      {
        name: "IRS whistleblower program (IRC § 7623)",
        description: "Individuals who provide information leading to collection of more than $2 million in tax are entitled to 15-30% of the collected proceeds.",
        keyPrinciple: "Mandatory award (not discretionary) for mandatory cases (>$2M collected). Whistleblower Office determines award percentage. Original information requirement: not information already known to IRS. Awards delayed by lengthy audit/litigation process. Dodd-Frank provides additional whistleblower protections for SEC/CFTC informants. High-profile case: Bradley Birkenfeld received $104M for his role in exposing UBS offshore accounts.",
        tags: ["whistleblower", "7623", "awards"],
      },
      {
        name: "John Doe summons",
        description: "An IRS summons directed to a third party (bank, platform) seeking identification of unknown taxpayers — used when specific identities are not yet known.",
        keyPrinciple: "IRC § 7609(f). Court approval required (unlike ordinary summonses). Used against Swiss banks (UBS, Credit Suisse), Coinbase (cryptocurrency), Kraken (cryptocurrency), and other platforms holding information about US taxpayers. Coinbase: IRS successfully obtained records of ~14,000 accounts with transactions >$20,000 (2017). The John Doe summons has become the primary enforcement tool for novel information sources.",
        tags: ["John-Doe-summons", "crypto", "enforcement"],
        xref: ["law"],
      },
    ],
  },

  // ── Family 16 ──────────────────────────────────────────────────────────────
  {
    slug: "anti-avoidance-doctrines",
    number: 16,
    name: "Anti-Avoidance Doctrines",
    blurb: "Judicial and statutory doctrines that allow courts and the IRS to disregard transactions that lack substance beyond their tax effects.",
    section: "E",
    color: "violet",
    entries: [
      {
        name: "Substance over form",
        description: "Courts look to the economic reality and substance of a transaction, not the legal form parties chose to structure it.",
        keyPrinciple: "The foundational anti-avoidance principle. Gregory v. Helvering (1935): a corporate reorganization that lacked business purpose was disregarded. 'Substance over form' does not apply when the transaction is genuine — taxpayers are entitled to arrange affairs to minimize tax. The distinction between legitimate tax planning and abusive avoidance is factual and contested.",
        citation: "Gregory v. Helvering, 293 U.S. 465 (1935)",
        tags: ["substance-over-form", "anti-avoidance", "Gregory"],
        xref: ["law"],
        status: "landmark",
      },
      {
        name: "Economic substance doctrine (codified § 7701(o))",
        description: "A transaction must change the taxpayer's economic position in a meaningful way and have a substantial non-tax purpose; codified in 2010 with strict penalties.",
        keyPrinciple: "IRC § 7701(o). Two prongs: (1) objective: meaningful change in economic position; (2) subjective: substantial non-tax purpose. Conjunctive: must satisfy both. 20% strict liability penalty if doctrine applies; 40% if position was not adequately disclosed. No reasonable cause defense when the doctrine applies. Predecessor was entirely judicial (defined variously by circuits).",
        tags: ["economic-substance", "7701(o)", "penalty"],
        xref: ["law"],
      },
      {
        name: "Step transaction doctrine",
        description: "A series of formally separate steps that together constitute a single transaction are collapsed and treated as one for tax purposes.",
        keyPrinciple: "Three tests applied by courts: (1) binding commitment test — earliest step bound taxpayer to later steps; (2) mutual interdependence test — steps so interdependent that the legal relations created would not have been undertaken independently; (3) end-result test — steps were parts of a plan to achieve a predetermined end result. Courts may apply any one of these.",
        tags: ["step-transaction", "anti-avoidance", "recharacterization"],
        xref: ["law"],
      },
      {
        name: "Business purpose doctrine",
        description: "A transaction must have a genuine, non-tax business purpose to be respected for tax purposes.",
        keyPrinciple: "Companion to substance-over-form. Gregory v. Helvering: the reorganization failed because it had no business purpose. Courts distinguish between subjective business purpose (what the taxpayer intended) and objective purpose (what a reasonable businessperson would have done). A transaction motivated primarily by taxes but with some business purpose may still be challenged under economic substance.",
        tags: ["business-purpose", "anti-avoidance"],
        xref: ["law"],
      },
      {
        name: "Sham transaction doctrine",
        description: "A wholly fictitious or pretextual transaction — one that never occurred or had no economic reality — is disregarded entirely.",
        keyPrinciple: "Stronger than substance-over-form (which recharacterizes real transactions). Two types: (1) factual sham — transaction never occurred; (2) economic sham — transaction occurred but had no economic substance (overlaps with economic substance doctrine). Example: fabricated expense deductions, fictitious business losses.",
        tags: ["sham", "anti-avoidance", "fraud"],
        xref: ["law"],
      },
      {
        name: "Assignment of income doctrine",
        description: "Income is taxed to the person who earned it or to whose property it is attributable — it cannot be shifted to another person by assignment.",
        keyPrinciple: "Lucas v. Earl (1930): wages assigned to a spouse before receipt still taxable to the earner (the 'fruit and tree' metaphor — you cannot assign the fruit while retaining the tree). Gift of income-producing property generally effective (transfers the tree). Limits on family income shifting. Carried interest controversy partly grounded in assignment of income concerns.",
        citation: "Lucas v. Earl, 281 U.S. 111 (1930)",
        tags: ["assignment-of-income", "Lucas", "income-shifting"],
        xref: ["law"],
        status: "landmark",
      },
      {
        name: "Listed transactions",
        description: "Transactions designated by the IRS as abusive tax shelters that must be disclosed by participants and material advisors.",
        keyPrinciple: "IRC § 6011. Published as notices or revenue procedures. Current listed transactions include: certain lease-in/lease-out transactions, micro-captive insurance, syndicated conservation easements, certain loss duplication transactions. Failure to disclose: $100,000 penalty (individual) or $200,000 (entity). Material advisor penalties: $50,000 or $200,000 per listed transaction failure.",
        tags: ["listed-transactions", "shelter", "disclosure"],
      },
      {
        name: "Syndicated conservation easements",
        description: "Transactions where investors claim large charitable deductions for donating conservation easements on inflated appraisals — identified as a listed transaction.",
        keyPrinciple: "Listed transaction since 2016 (Notice 2017-10). Structure: partnership buys land, donates conservation easement valued far above cost, each partner claims a deduction equal to their share of the appraisal (often 4-5x their investment). IRS has disallowed most such deductions; Tax Court has ruled against promoters. Some legitimate conservation easements exist; the listed transaction targets the inflated-appraisal syndication.",
        tags: ["conservation-easement", "listed-transaction", "charitable"],
        status: "contested",
      },
      {
        name: "Micro-captive insurance",
        description: "Small captive insurance companies electing § 831(b) that are challenged as abusive shelters when they lack economic substance.",
        keyPrinciple: "§ 831(b) captive: insurer with premiums ≤$2.65M (2024) may elect to pay tax only on investment income, not underwriting income. Legitimate use: closely held businesses insuring genuine business risks. Abusive use: related-party 'insurance' for risks that would never be covered by commercial insurers; premiums return to owner as loans or benefits. Listed transaction; heavy IRS enforcement and Tax Court litigation.",
        tags: ["captive-insurance", "831b", "listed-transaction"],
        status: "open",
      },
      {
        name: "Family partnership rules (IRC § 704(e))",
        description: "Limits on income shifting within families through partnership arrangements that lack genuine capital investment.",
        keyPrinciple: "A family member is recognized as a partner only if they (1) have a genuine capital interest or (2) provided services for which the partnership compensated them. Income allocations to donees must reflect a reasonable return on capital plus the donor's reasonable compensation for services. Prevents high-bracket parents from assigning partnership income to low-bracket children without genuine economic substance.",
        tags: ["family-partnership", "704e", "income-shifting"],
      },
    ],
  },

  // ── Family 17 ──────────────────────────────────────────────────────────────
  {
    slug: "tax-planning-strategies",
    number: 17,
    name: "Tax Planning Strategies",
    blurb: "The major legal tools taxpayers use to minimize their tax liability — timing, entity choice, basis planning, and retirement strategies.",
    section: "E",
    color: "sky",
    entries: [
      {
        name: "Timing of income and deductions",
        description: "Accelerating deductions into high-rate years and deferring income to lower-rate years is the most universal tax planning technique.",
        keyPrinciple: "Time value of money: paying tax later is better than paying now; a deduction today is worth more than one tomorrow. Implementation: defer year-end invoicing, accelerate pre-year-end expenses, bunch charitable contributions in high-rate years, harvest losses before year-end. Constrained by constructive receipt doctrine (cash-basis taxpayers recognize income when available, not when actually received).",
        tags: ["timing", "deferral", "acceleration"],
        xref: ["finance"],
      },
      {
        name: "Income shifting to lower-bracket family members",
        description: "Transferring income-producing assets or business interests to family members in lower tax brackets reduces the family unit's overall tax burden.",
        keyPrinciple: "Effective for: gifts of appreciated property (the donee's gain is taxed at their rate), family LLCs/LPs (subject to § 704(e) and reasonable compensation rules). Limited by: kiddie tax (unearned income of children under 19 taxed at parent's rate), assignment of income doctrine, and the requirement that gifts of partnership interests be genuine. Must be structured carefully to avoid recharacterization.",
        tags: ["income-shifting", "family", "gift"],
      },
      {
        name: "Kiddie tax (IRC § 1(g))",
        description: "Unearned income of children under 19 (or under 24 if full-time students) above a threshold is taxed at the parent's marginal rate.",
        keyPrinciple: "2024 threshold: first $1,300 tax-free, next $1,300 at child's rate, above $2,600 at parent's rate (verify at build). Enacted 1986 to prevent parents from shifting investment income to children. Severely limits the income-shifting strategy for investment income. Does not apply to earned income. Once a child is 19 (24 if student) and no longer a full-time student, kiddie tax no longer applies.",
        tags: ["kiddie-tax", "1g", "income-shifting"],
      },
      {
        name: "Entity choice planning",
        description: "The decision between C-corp, S-corp, partnership/LLC, and sole proprietorship significantly affects the tax on business income and exit proceeds.",
        keyPrinciple: "Key factors: (1) anticipated distributions — if retaining earnings, C-corp 21% vs. 37% pass-through rate; (2) exit strategy — C-corp § 338 asset sale vs. stock sale, Qualified Small Business Stock (§ 1202) exclusion; (3) investor profile — VC funds require C-corps; (4) self-employment tax; (5) state conformity. QSBS (§ 1202): gain exclusion up to $10M or 10× basis for qualifying C-corp stock held 5+ years.",
        tags: ["entity-choice", "QSBS", "planning"],
        xref: ["finance"],
      },
      {
        name: "Qualified Small Business Stock (§ 1202) exclusion",
        description: "Up to 100% of gain on the sale of qualifying C-corporation stock held for more than 5 years can be excluded from federal income tax.",
        keyPrinciple: "Aggregate gain exclusion: greater of $10 million or 10× the taxpayer's adjusted basis. Stock must be in an active domestic C-corp; gross assets ≤$50M at time of issuance. Eligible industries: excludes professional services, finance, law, health (with some exceptions). No AMT preference for federal (post-TCJA). State conformity varies widely — California notably does not conform. Most valuable exit tax benefit for startups.",
        tags: ["QSBS", "1202", "startup", "gain-exclusion"],
        xref: ["finance"],
      },
      {
        name: "Basis step-up planning",
        description: "Structuring estates to maximize the step-up in basis at death eliminates embedded capital gains tax on a lifetime of appreciation.",
        keyPrinciple: "IRC § 1014. Strategy: hold highly appreciated assets until death; donating cash (not stock) to charity during life. Avoid gifting appreciated assets (donors take carryover basis; recipients owe capital gains on sale). Paired with portability and marital deduction planning to defer estate tax. Proposals to replace § 1014 with carryover basis or tax at death have not passed. OPEN.",
        tags: ["step-up", "basis", "estate-planning", "planning"],
        status: "open",
      },
      {
        name: "Charitable giving strategies",
        description: "Structuring charitable contributions to maximize tax benefit — including donor-advised funds, charitable remainder trusts, and gifts of appreciated property.",
        keyPrinciple: "Key strategies: (1) donate appreciated stock — avoid capital gains, deduct FMV; (2) bunch contributions in alternating years to exceed standard deduction threshold; (3) donor-advised fund — take lump deduction now, distribute to charities over time; (4) charitable remainder trust (CRT) — income stream to donor/spouse, remainder to charity; (5) QCD from IRA — up to $105,000 directly to charity, excluded from income.",
        tags: ["charitable", "DAF", "CRT", "QCD"],
      },
      {
        name: "Roth conversion strategy",
        description: "Converting traditional IRA balances to Roth IRA — paying tax now at current rates in exchange for tax-free future growth and distributions.",
        keyPrinciple: "Makes sense when: current tax rate is lower than expected future rate, the account holder has decades of growth ahead, and the tax can be paid from non-IRA funds. 'Backdoor Roth': non-deductible IRA contribution + immediate conversion — workaround for high-income earners above Roth income limits. 'Mega-backdoor Roth': after-tax 401(k) contributions converted to Roth. IRS has acknowledged these are legal.",
        tags: ["Roth", "IRA", "conversion", "retirement"],
        xref: ["finance"],
      },
      {
        name: "Required minimum distributions (RMDs)",
        description: "Starting at age 73 (75 by 2033 under SECURE 2.0), IRA and qualified plan owners must withdraw a minimum amount annually, paying ordinary income tax.",
        keyPrinciple: "RMD = prior year-end balance / IRS life expectancy factor. Failure to take RMD: 25% penalty on shortfall (reduced to 10% if corrected promptly, SECURE 2.0). Roth IRAs have no lifetime RMDs (except inherited Roths). QCD strategy: direct IRA distributions to charity satisfy RMD without including in income. Strategic withdrawal planning before RMD age can smooth out income and reduce Medicare premiums (IRMAA).",
        tags: ["RMD", "IRA", "retirement", "SECURE"],
        xref: ["finance"],
      },
      {
        name: "Grantor trust income shifting (IDGT)",
        description: "An Intentionally Defective Grantor Trust (IDGT) is treated as a separate entity for estate purposes but as a grantor's own trust for income tax purposes — allowing tax-free loans and sales between the grantor and the trust.",
        keyPrinciple: "Sale of appreciated assets to an IDGT in exchange for a promissory note: (1) not a taxable sale (grantor is both buyer and seller for income tax purposes); (2) freezes value in the estate at sale price; (3) trust's subsequent growth is outside the grantor's estate; (4) grantor pays income tax on trust's income (a gift to the trust beneficiaries). One of the most powerful estate freeze techniques for large estates.",
        tags: ["IDGT", "grantor-trust", "estate-freeze", "income-tax"],
      },
      {
        name: "Installment sale to a family member",
        description: "Sale of a business or property to a family member on an installment note at the applicable federal rate (AFR) transfers future appreciation out of the estate at low imputed interest.",
        keyPrinciple: "Must charge at least the applicable federal rate (AFR) to avoid gift tax on imputed interest. Below-market loans: imputed interest under § 7872. If the asset grows faster than the AFR, the excess appreciation transfers to the buyer/heir free of transfer tax. Contrast with GRAT (which requires the §7520 rate to be beaten): installment sale must beat only the AFR (typically lower).",
        tags: ["installment-sale", "family", "AFR", "estate-planning"],
      },
      {
        name: "529 plans and education tax benefits",
        description: "Tax-advantaged savings accounts for education expenses — earnings grow tax-free, distributions for qualified education expenses are tax-free.",
        keyPrinciple: "Named for IRC § 529. No federal income tax deduction for contributions (some states allow state deductions). Earnings grow tax-deferred; withdrawals for qualified higher education or K-12 (up to $10,000/year) are tax-free. SECURE 2.0 (2022): allows rolling up to $35,000 of unused 529 funds into Roth IRA (subject to 15-year account age and annual Roth contribution limits). 'Superfunding': 5-year gift tax averaging allows $90,000 lump contribution ($180,000 MFJ) to a 529.",
        tags: ["529", "education", "tax-free", "planning"],
      },
    ],
  },

  // ── Family 18 ──────────────────────────────────────────────────────────────
  {
    slug: "nonprofit-tax-exempt",
    number: 18,
    name: "Nonprofit & Tax-Exempt Organizations",
    blurb: "The § 501(c) framework, private foundation rules, UBIT, lobbying limits, and the growing controversy over donor-advised funds.",
    section: "E",
    color: "emerald",
    entries: [
      {
        name: "IRC § 501(c)(3) — charitable exemption",
        description: "Organizations organized and operated exclusively for charitable, religious, educational, scientific, literary, or testing-for-public-safety purposes are exempt from federal income tax.",
        keyPrinciple: "Contributions are deductible by donors. No private inurement (net earnings cannot benefit any private individual). Prohibition on substantial lobbying and absolute prohibition on directly or indirectly participating in political campaigns. Two categories: public charities (broad donor base) and private foundations (narrow funding). IRS Form 1023/1023-EZ for recognition.",
        tags: ["501c3", "charitable", "exemption", "nonprofit"],
        xref: ["law"],
      },
      {
        name: "Public charity vs. private foundation",
        description: "Public charities receive broad public support; private foundations are typically funded by a single family or corporation and face more restrictive rules.",
        keyPrinciple: "Public charities: hospitals, universities, churches, community foundations, and organizations meeting a public support test (≥1/3 of support from public). Private foundations: 1.39% excise on net investment income; mandatory 5% annual distribution; self-dealing rules (§ 4941); excess business holdings (§ 4943); jeopardizing investments (§ 4944); taxable expenditures (§ 4945).",
        tags: ["private-foundation", "public-charity", "501c3"],
      },
      {
        name: "5% minimum distribution requirement",
        description: "Private foundations must distribute at least 5% of their net investment assets annually for charitable purposes.",
        keyPrinciple: "IRC § 4942. Non-distributing foundations face a 30% excise on the distributable amount not distributed by year-end (10% initially; 30% if not corrected). 'Qualifying distributions' include grants, program-related investments, and reasonable operating expenses. The 5% floor was set in 1969; some scholars argue it should be increased to prevent perpetual wealth warehousing. CONTESTED.",
        tags: ["5%-distribution", "private-foundation", "mandatory"],
        status: "contested",
      },
      {
        name: "Unrelated business income tax (UBIT)",
        description: "Tax-exempt organizations pay corporate income tax on income from a trade or business that is (1) regularly carried on and (2) not substantially related to the organization's exempt purpose.",
        keyPrinciple: "IRC §§ 511-514. Rate: 21% (same as corporate rate). Purpose: prevent unfair competition with taxable businesses. Common UBIT items: advertising revenue (sometimes), debt-financed income (UDFI), real estate income from leveraged property. Exceptions: dividends, interest, royalties, rent from real property (without personal services). Each unrelated trade or business is now separately siloed for UBIT purposes (TCJA 2017).",
        tags: ["UBIT", "UDFI", "nonprofit", "exemption"],
      },
      {
        name: "Lobbying limits for public charities",
        description: "501(c)(3) organizations may engage in lobbying as long as it is not a substantial part of their activities; the 501(h) election provides a safe-harbor expenditure test.",
        keyPrinciple: "No clear definition of 'substantial' under the insubstantial part test. IRC § 501(h) election: spending limits based on percentage of exempt purpose expenditures (generally 20% of first $500,000, declining for larger organizations; 25% cap on direct lobbying). Absolute prohibition on political campaign intervention (endorsing candidates, donating to campaigns). Violation: loss of exemption and potential excise taxes.",
        tags: ["lobbying", "501h", "501c3", "political"],
        xref: ["law"],
      },
      {
        name: "501(c)(4) social welfare organizations",
        description: "Organizations operated exclusively for the promotion of social welfare may engage in political activity as long as it is not the organization's primary activity.",
        keyPrinciple: "Contributions not deductible (unlike § 501(c)(3)). Can engage in substantial political activity without losing exemption — as long as primary activity is social welfare. Used extensively for politically active nonprofits ('dark money' organizations) because donor disclosure is limited. IRS's 'primary purpose' standard for political activity is contested. CONTESTED.",
        tags: ["501c4", "dark-money", "political", "social-welfare"],
        status: "contested",
      },
      {
        name: "Donor-advised funds (DAFs)",
        description: "Charitable accounts where the donor takes an immediate tax deduction but recommends grants to charities over time — with no legal obligation to distribute.",
        keyPrinciple: "Donor makes a contribution to a sponsoring organization (Fidelity Charitable, Schwab Charitable, community foundations); takes full deduction in the year of contribution; recommends grants to qualified charities at any future time. No 5% distribution requirement (unlike private foundations). Controversy: billions of dollars 'warehoused' in DAFs without reaching operating charities. Recent legislative proposals to impose payout requirements. OPEN.",
        tags: ["DAF", "donor-advised", "warehouse", "charitable"],
        status: "open",
      },
      {
        name: "Churches and religious organizations",
        description: "Religious organizations have automatic tax exemption — no Form 1023 required — and limited IRS examination authority.",
        keyPrinciple: "IRS may not initiate a church examination without high-level approval; examinations require reasonable belief of knowing violation of tax law. Churches are subject to the same § 501(c)(3) prohibitions (no campaign intervention). The Johnson Amendment (1954) prohibits tax-exempt organizations from endorsing or opposing candidates — its application to churches has been politically contested.",
        tags: ["church", "religious", "Johnson-Amendment", "exemption"],
        xref: ["law"],
      },
      {
        name: "Private inurement and excess benefit transactions",
        description: "A 501(c)(3) or (4) may not allow net earnings to flow to private individuals; excess benefit transactions trigger excise taxes rather than loss of exemption.",
        keyPrinciple: "IRC § 4958 (intermediate sanctions). Excess benefit transaction: economic benefit provided to a 'disqualified person' (insiders) exceeding the value of services rendered. Taxes: 25% on the insider; 10% on organization managers who knowingly approved (max $20,000). Must correct (repay) the excess benefit. IRS may also revoke exemption for egregious cases. Applies to public charities and § 501(c)(4)s.",
        tags: ["private-inurement", "4958", "intermediate-sanctions"],
        xref: ["law"],
      },
      {
        name: "Tax-exempt bonds (municipal bonds)",
        description: "Interest on bonds issued by state and local governments is generally excluded from federal income tax, lowering borrowing costs for issuers.",
        keyPrinciple: "IRC § 103. Exemption subsidizes state/local infrastructure, hospitals, universities, housing. Yield on tax-exempt bonds is lower than taxable bonds; the after-tax yield is equivalent for taxpayers in high brackets (break-even bracket). AMT exception: certain private activity bonds (PABs) are AMT preference items for individuals. Arbitrage rules limit using tax-exempt bond proceeds for taxable investments.",
        tags: ["municipal-bonds", "tax-exempt", "interest"],
        xref: ["finance"],
      },
      {
        name: "Program-related investments (PRIs)",
        description: "Investments by private foundations that have a primary charitable purpose and a below-market return — count toward the 5% distribution requirement.",
        keyPrinciple: "IRC § 4944. PRIs are not 'jeopardizing investments' and count as qualifying distributions. Examples: low-interest loans to affordable housing developers, equity investments in social enterprises. Allows private foundations to deploy capital without grants and potentially recycle returned capital. Mission-related investments (MRIs): investments for a mix of financial and mission reasons — separate category, subject to prudent investor standards.",
        tags: ["PRI", "private-foundation", "impact-investing"],
        xref: ["finance"],
      },
      {
        name: "Self-dealing rules for private foundations (IRC § 4941)",
        description: "Private foundations are strictly prohibited from engaging in financial transactions with disqualified persons — family members, substantial contributors, and foundation managers.",
        keyPrinciple: "Categories: sale or exchange of property; lending money; furnishing goods/services; payment of compensation (unless reasonable); transfer or use of foundation assets for disqualified persons' benefit. Initial excise: 10% on the foundation, 5% on the manager. Self-correction available. Strict liability — no intent requirement for the initial tax (only the additional 200%/50% taxes require willfulness).",
        tags: ["self-dealing", "4941", "private-foundation", "disqualified-persons"],
        xref: ["law"],
      },
    ],
  },

  // ── Family 19 ──────────────────────────────────────────────────────────────
  {
    slug: "state-local-tax",
    number: 19,
    name: "State & Local Tax (SALT)",
    blurb: "Nexus, apportionment, Wayfair's aftermath, the SALT cap workarounds, and the constitutional limits on state taxation of interstate business.",
    section: "E",
    color: "cyan",
    entries: [
      {
        name: "State income tax nexus",
        description: "A taxpayer must have sufficient contact with a state — 'nexus' — before that state can impose income tax on them.",
        keyPrinciple: "Traditional physical nexus: employees, office, property in the state. Economic nexus: many states now assert income tax nexus based solely on sales (following Wayfair's physical-presence overrule in the sales tax context). Telecommuting has dramatically expanded nexus: an employee working remotely from a state can create corporate income tax nexus for the employer. New York's 'convenience of the employer' rule taxes nonresidents on days worked remotely if the remote arrangement was not necessary for the employer's business.",
        tags: ["nexus", "state-income-tax", "telecommuting"],
      },
      {
        name: "Unitary business principle",
        description: "States may tax a multistate enterprise's income based on an apportioned share of the unitary group's combined income.",
        keyPrinciple: "Prevents distortion: without combined reporting, related entities can shift income to zero-tax states. Unitary group: entities with significant flows of value, functional integration, or economies of scale. Combined reporting (26+ states require it) eliminates the ability to avoid state tax through intercompany pricing. Worldwide combined reporting (California formerly required; water's edge now standard) raised WTO concerns.",
        tags: ["unitary-business", "combined-reporting", "apportionment"],
      },
      {
        name: "Apportionment formulas",
        description: "Multi-state businesses allocate their income among states based on a formula representing their relative activity in each state.",
        keyPrinciple: "Traditional three-factor (Massachusetts) formula: (sales + payroll + property) / 3. Trend: single-sales-factor (SSF) — most large states now use sales-only apportionment. SSF favors manufacturers and businesses with lots of property/payroll but sales elsewhere; punishes businesses that sell mainly in the state. Market-based sourcing: services sourced to where the customer receives the benefit (vs. cost-of-performance where the work is done).",
        tags: ["apportionment", "three-factor", "single-sales-factor"],
        xref: ["economics"],
      },
      {
        name: "SALT deduction cap ($10,000)",
        description: "TCJA 2017 capped the individual itemized deduction for state and local income, sales, and property taxes at $10,000.",
        keyPrinciple: "IRC § 164(b)(6). Applies to all state and local taxes paid. $5,000 cap for MFS. Most affects high-income taxpayers in high-tax states: California (~13.3% top rate), New York (~10.9%), New Jersey (~10.75%). An estimated $30-50B of SALT deductions are blocked annually (verify at build). Cap sunset after 2025 with other TCJA individual provisions — major 2025 legislative battle. OPEN.",
        tags: ["SALT", "TCJA", "cap", "deduction"],
        status: "open",
      },
      {
        name: "Pass-through entity tax (PTET) workaround",
        description: "States allow partnerships and S-corps to elect to pay state tax at the entity level, bypassing the $10,000 SALT cap for business owners.",
        keyPrinciple: "IRS Notice 2020-75 confirmed that the PTET deduction is allowable at the entity level (not subject to the cap). Owners receive a state tax credit to offset their individual state liability. 36+ states have enacted PTET regimes. Key limitation: does not help W-2 employees or Schedule C sole proprietors — only pass-through business owners. Effective for most small business owners with significant state tax liability.",
        tags: ["PTET", "SALT-workaround", "pass-through"],
        status: "open",
      },
      {
        name: "Dormant Commerce Clause (Complete Auto Transit test)",
        description: "The Constitution implicitly limits states from discriminating against or unduly burdening interstate commerce in their tax laws.",
        keyPrinciple: "Complete Auto Transit, Inc. v. Brady (1977): four-part test for a constitutional state tax. (1) Substantial nexus; (2) fairly apportioned; (3) does not discriminate against interstate commerce; (4) fairly related to services provided. Wayfair addressed prong (1). Tax discrimination against out-of-state businesses: per se unconstitutional. States cannot impose single-factor formulas that impose disproportionate burden on out-of-state companies (Joyce and Finnigan rules litigated under this).",
        tags: ["dormant-commerce-clause", "Complete-Auto", "state-tax"],
        xref: ["law"],
      },
      {
        name: "South Dakota v. Wayfair — state income tax extension",
        description: "After Wayfair overruled physical presence for sales tax nexus, states have aggressively extended economic nexus to income and franchise taxes.",
        keyPrinciple: "Wayfair (2018) addressed only sales tax. Many states have enacted factor-presence nexus statutes for income tax: a company with $500,000+ in in-state sales may have income tax nexus even without a single employee or property. MTC's 'factor presence' model statute: adopted by ~15 states (verify at build). Creates multi-state compliance obligations for many companies that previously had no state income tax filing requirement.",
        tags: ["Wayfair", "economic-nexus", "income-tax"],
        xref: ["law"],
      },
      {
        name: "New York 'convenience of the employer' rule",
        description: "New York taxes nonresident employees on days worked outside New York if the remote arrangement is for the employee's own convenience rather than the employer's necessity.",
        keyPrinciple: "Dating from 2006; more aggressively enforced post-COVID. If an employer does not require out-of-state work for legitimate business reasons, NY treats those days as NY workdays. Result: remote workers in NJ, CT, PA with NY employers may owe NY tax on all their income. Creates 'telecommuter tax' controversies. Many states have challenged this rule; Congress has periodically considered preemption legislation. CONTESTED.",
        tags: ["New-York", "telecommute", "convenience-rule", "nexus"],
        status: "contested",
      },
      {
        name: "Throwback and throwout rules",
        description: "Provisions preventing income from falling outside all states' tax bases — ensuring the total apportionment fractions equal 100%.",
        keyPrinciple: "Throwback rule: if destination state cannot tax sales (no nexus), sales are 'thrown back' to the state of origin. Throwout rule: exclude from the denominator sales to states where the taxpayer has no nexus. Throwback is minority rule (~15 states). Throwout is minority within a minority. Without these rules, some MNE income may be taxed by no state — a 'nowhere income' problem. Throwback rules reduce the value of Delaware holding company planning.",
        tags: ["throwback", "throwout", "apportionment"],
      },
      {
        name: "State conformity to federal law",
        description: "States must decide whether and when to 'conform' to federal tax law changes — static conformity vs. rolling conformity creates significant planning complexity.",
        keyPrinciple: "Rolling conformity (40 states): automatically adopt federal changes. Static conformity: adopt federal law as of a specific date and require legislative action to update. Fixed conformity: some states selectively conform. TCJA created conformity headaches: many states decoupled from the NOL limitation, SALT cap (state deduction), GILTI inclusion, and § 199A deduction. States generate significant revenue from TCJA provisions they did not adopt.",
        tags: ["conformity", "state-tax", "TCJA"],
      },
      {
        name: "Local income taxes",
        description: "Some cities and counties impose their own income taxes in addition to state and federal taxes — creating additional compliance burdens.",
        keyPrinciple: "Notable examples: New York City (~3.9% top rate), Philadelphia (3.75% resident / 3.44% non-resident; verify at build), Ohio municipalities (~2%). Maryland: county income taxes (2.25-3.2%). Michigan municipalities (Detroit: 2.4% resident). Taxpayers working in multiple localities may face complex apportionment. SALT cap applies to local income taxes as well as state taxes.",
        tags: ["local-income-tax", "NYC", "Philadelphia"],
      },
      {
        name: "State estate and inheritance taxes",
        description: "Eleven states and DC impose their own estate taxes; six states impose inheritance taxes (on recipients) with rates varying by relationship.",
        keyPrinciple: "Estate taxes: Oregon and Massachusetts have the lowest thresholds (~$1M). Inheritance taxes: Pennsylvania (4.5% lineal heirs; 15% others), New Jersey (0-16%; spouses exempt). Both apply independently of the federal estate tax. Estate planning must account for state-level taxes, which can bite estates well below the $13.61M federal exemption. Many states have not conformed to federal exemption increases. Verify state-specific rules at build.",
        tags: ["state-estate-tax", "inheritance-tax", "state"],
      },
    ],
  },

  // ── Family 20 ──────────────────────────────────────────────────────────────
  {
    slug: "constitutional-limits-open-questions",
    number: 20,
    name: "Constitutional Limits, Landmark Cases & Open Questions",
    blurb: "The Sixteenth Amendment, the direct-tax clause, Moore v. United States, the wealth tax debate, and the most contested live questions in tax law.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Sixteenth Amendment",
        description: "Authorized Congress to lay and collect income taxes on incomes from whatever sources derived, without apportionment among the states.",
        keyPrinciple: "Ratified February 3, 1913. Overruled Pollock v. Farmers' Loan & Trust (1895). The modern US income tax rests on it. The amendment's limits on what counts as 'income' and whether 'apportionment' could still constrain certain direct taxes remain live constitutional questions, most recently surfaced in Moore v. United States (2024).",
        tags: ["16th-amendment", "constitutional", "income-tax"],
        xref: ["law"],
        status: "landmark",
      },
      {
        name: "Apportionment Clause (Art. I §§ 2, 9)",
        description: "Direct taxes must be apportioned among the states in proportion to their respective populations — a severe constraint on federal tax powers.",
        keyPrinciple: "Pre-16th Amendment: the Pollock Court held an income tax on investment income was a direct tax requiring apportionment — effectively killing the income tax. The 16th Amendment exempted income taxes from this requirement. What counts as a 'direct tax' for other purposes (wealth tax, unrealized gain tax) remains contested. Moore v. United States (2024) did not resolve whether the 16th Amendment requires 'realization.'",
        tags: ["apportionment", "direct-tax", "constitutional"],
        xref: ["law"],
      },
      {
        name: "Pollock v. Farmers' Loan & Trust (1895)",
        description: "SCOTUS held that the Income Tax Act of 1894 imposed an unconstitutional direct tax on income from property, requiring apportionment among states.",
        keyPrinciple: "5-4 decision. Reversed a prior precedent (Springer v. United States, 1881). Income from land and personal property deemed a direct tax. Effect: Congress could not impose an income tax without apportionment — impossible in practice. Overruled by the Sixteenth Amendment (1913). Still cited in arguments about the constitutional limits on new forms of income or wealth taxation.",
        citation: "Pollock v. Farmers' Loan & Trust Co., 157 U.S. 429 (1895)",
        tags: ["Pollock", "direct-tax", "constitutional", "overruled"],
        xref: ["law"],
        status: "overruled",
      },
      {
        name: "Commissioner v. Glenshaw Glass (1955)",
        description: "SCOTUS adopted a broad definition of 'income' under the 16th Amendment: undeniable accessions to wealth, clearly realized, over which the taxpayer has complete dominion.",
        keyPrinciple: "Replaced the Macomber realization-focused definition with a broader three-part test. Includes punitive damages and settlement proceeds from antitrust suits. The 'clearly realized' element has since been interpreted broadly — assignment of income, constructive receipt, economic benefit doctrine all define realization expansively. Glenshaw Glass is the foundational modern income definition.",
        citation: "Commissioner v. Glenshaw Glass Co., 348 U.S. 426 (1955)",
        tags: ["Glenshaw-Glass", "income-definition", "constitutional"],
        xref: ["law"],
        status: "landmark",
      },
      {
        name: "Eisner v. Macomber (1920) — constitutional limits",
        description: "SCOTUS held that a stock dividend is not 'income' within the meaning of the 16th Amendment; income requires realization.",
        keyPrinciple: "Established the realization requirement in constitutional terms. A shareholder who receives additional shares without any change in economic position has not received 'income.' Subsequent erosion: Glenshaw Glass (1955) broadened the income definition; constructive receipt and assignment of income doctrines blur the realization line. Macomber's specific holding limits (but does not eliminate) the ability to tax unrealized gains constitutionally.",
        citation: "Eisner v. Macomber, 252 U.S. 189 (1920)",
        tags: ["Macomber", "realization", "constitutional"],
        xref: ["law"],
        status: "landmark",
      },
      {
        name: "Moore v. United States (2024)",
        description: "SCOTUS upheld the TCJA § 965 mandatory repatriation tax on previously untaxed offshore earnings — but explicitly declined to rule on whether realization is constitutionally required for the income tax.",
        keyPrinciple: "7-2 decision. Majority (Roberts): § 965 passes as an attribution of realized income to the shareholder; need not decide the broader realization question. Concurrences (Barrett, Alito) would have held realization required but found the § 965 income to be 'realized' at the corporate level. Dissent (Thomas, Gorsuch): § 965 is unconstitutional without realization at the shareholder level. The constitutional status of a mark-to-market or wealth tax remains open after Moore.",
        citation: "Moore v. United States, 602 U.S. ___ (2024)",
        tags: ["Moore", "realization", "constitutional", "2024"],
        xref: ["law"],
        status: "open",
      },
      {
        name: "Constitutional wealth tax",
        description: "A federal annual tax on net wealth (as proposed by Senators Warren and Sanders) faces serious constitutional challenges as a 'direct tax' requiring apportionment.",
        keyPrinciple: "Proponents: income taxes were validated by the 16th Amendment; a wealth tax on net worth could be characterized as an income tax on the return to capital — or Congress could use the 16th Amendment's income-tax power to tax 'deemed income' from wealth. Opponents: a net wealth tax is a classic direct tax on property not covered by the 16th Amendment; would require apportionment (effectively prohibitive). Moore's narrow holding did not resolve this. CONTESTED. OPEN.",
        tags: ["wealth-tax", "constitutional", "Warren", "apportionment"],
        status: "open",
      },
      {
        name: "Digital services taxes and international trade law",
        description: "Unilateral national taxes on digital company revenues raise WTO and bilateral trade concerns; the US has threatened Section 301 tariffs in response.",
        keyPrinciple: "France, UK, Spain, Italy, India, and others have enacted or proposed DSTs. US Trade Representative found French DST discriminatory under § 301 (2019) — threatened 25% tariffs. G7/G20 moratorium pending Pillar One. Pillar One negotiations stalled as of 2026 — verify status. If Pillar One fails, unilateral DSTs will likely proliferate, creating trade conflict. EU DBTX proposal being developed as alternative.",
        tags: ["DST", "WTO", "trade", "digital"],
        xref: ["governance"],
        status: "open",
      },
      {
        name: "Pillar Two implementation gap (US)",
        description: "The US has not enacted domestic legislation implementing the OECD Pillar Two global minimum tax, creating a competitive disadvantage for US multinationals.",
        keyPrinciple: "130+ countries are implementing Pillar Two. EU directive requires member-state implementation. US's GILTI is not fully equivalent to GloBE rules: different coverage, income definition, and credit mechanics. Without US implementation, the UTPR (backstop rule) in other countries may apply to US multinationals — effectively taxing US-headquartered companies to make up the difference between US effective rates and 15%. Congressional opposition to any tax increase has blocked implementation. OPEN.",
        tags: ["Pillar-Two", "GILTI", "US-implementation", "OECD"],
        xref: ["governance"],
        status: "open",
      },
      {
        name: "Carbon border adjustment mechanisms (CBAM)",
        description: "Border taxes on imports from countries without carbon pricing, designed to prevent carbon leakage from high-price to low-price jurisdictions.",
        keyPrinciple: "EU CBAM launched 2026 transition period (verify status). Applies to cement, steel, aluminum, fertilizers, electricity, hydrogen. Exporters to the EU must purchase CBAM certificates or document existing carbon price in origin country. WTO-compatible? Under the product process distinction, WTO allows some but not all process-based measures — EU CBAM's design attempts to minimize WTO vulnerability. US is considering a similar measure.",
        tags: ["CBAM", "carbon", "border-adjustment", "WTO"],
        xref: ["governance"],
        status: "open",
      },
      {
        name: "SALT cap constitutionality",
        description: "Several states challenged the TCJA SALT cap as unconstitutionally coercive — the Second Circuit rejected those challenges.",
        keyPrinciple: "New York v. Yellen, 15 F.4th 569 (2d Cir. 2021): Congress has broad power to define taxable income; limiting the deduction for state taxes does not violate the 10th Amendment or the principle that Congress cannot coerce states. SCOTUS denied certiorari. The constitutional challenge is effectively resolved — the SALT cap is constitutional. Legislative battle over whether to repeal or modify the cap continues.",
        citation: "New York v. Yellen, 15 F.4th 569 (2d Cir. 2021)",
        tags: ["SALT-cap", "constitutionality", "10th-amendment"],
        xref: ["law"],
        status: "landmark",
      },
      {
        name: "Cryptocurrency and digital assets — open tax questions",
        description: "The classification, reporting, and taxation of cryptocurrency and digital assets remains an actively evolving area with significant open questions.",
        keyPrinciple: "IRS treats crypto as property (Notice 2014-21): taxable on exchange, mining income is ordinary. Wash sale rule: currently does not apply (property, not securities). Form 1099-DA: brokers required to report digital asset transactions beginning 2025 (verify at build). DeFi and NFT taxation: largely unresolved by formal guidance. Staking rewards: Jarrett v. United States (M.D. Tenn. 2022) held IRS refund due; IRS has not fully adopted this reasoning. OPEN.",
        tags: ["cryptocurrency", "digital-assets", "open", "1099-DA"],
        status: "open",
      },
      {
        name: "Unrealized gain taxation — live proposals",
        description: "Multiple proposals to tax unrealized capital gains of high-wealth individuals — including mark-to-market, retrospective taxation, and deemed realization — test the boundaries of the 16th Amendment after Moore.",
        keyPrinciple: "Biden Billionaire Minimum Tax: 20% minimum on unrealized gains + ordinary income for individuals with >$100M in wealth — not enacted. Wyden mark-to-market proposal: annual mark to market for publicly traded assets held by high earners. Moore (2024) did not resolve whether realization is constitutionally required. The tension between tax equity (wealth concentration argument) and constitutional limits creates the most significant open question in US federal tax. OPEN. CONTESTED.",
        tags: ["unrealized-gains", "mark-to-market", "constitutional", "wealth"],
        status: "open",
      },
    ],
  },
];
