import type { Family } from "./types";

export const FAMILIES_9_15: Family[] = [
  // ── Family 9 ──────────────────────────────────────────────────────────────
  {
    slug: "architecture",
    number: 9,
    name: "Computer Architecture & Hardware",
    blurb: "The hardware abstractions that programs actually run on.",
    section: "C",
    color: "teal",
    entries: [
      {
        name: "Von Neumann architecture",
        description: "Stored-program computer: code and data share the same memory.",
        keyInsight: "Single memory, single bus, control unit, ALU, registers, I/O. The dominant design since EDVAC (1945); the shared instruction/data path is the eponymous 'bottleneck'.",
        prereqs: [],
        tags: ["architecture"],
        famous: true,
      },
      {
        name: "Instruction set architecture (ISA)",
        description: "The contract between hardware and software — the instructions a CPU executes.",
        keyInsight: "RISC ISAs (ARM, RISC-V) favor fixed-width, simple instructions for pipelining; CISC ISAs (x86) include variable-width, micro-ops translated internally. The ISA boundary is software's view of the machine.",
        prereqs: ["Von Neumann architecture"],
        tags: ["isa"],
      },
      {
        name: "Pipelining",
        description: "Overlapping instruction stages so multiple instructions are in flight at once.",
        keyInsight: "Classic 5-stage pipeline (fetch, decode, execute, memory, writeback) yields up to $5\\times$ throughput in the absence of hazards. Hazards (data, control, structural) cost cycles via forwarding, stalling, or branch prediction.",
        prereqs: ["Instruction set architecture (ISA)"],
        tags: ["pipeline"],
      },
      {
        name: "Cache memory and locality",
        description: "Small fast memory layered above main memory, exploiting reuse and proximity.",
        keyInsight: "Temporal locality (same address reused) and spatial locality (nearby addresses) make $\\sim 95\\%$ hit rates possible. Modern CPUs have 3–4 levels (L1: ~32KB, L2: ~256KB-1MB, L3: ~32MB) with $\\sim 1, 10, 30, 200$-cycle access latencies.",
        prereqs: ["Von Neumann architecture"],
        tags: ["memory", "cache"],
      },
      {
        name: "Virtual memory",
        description: "Each process sees its own contiguous address space, mapped by hardware to physical RAM.",
        keyInsight: "MMU walks page tables to translate virtual to physical addresses, caching translations in the TLB. Enables protection, sharing, and demand paging — and is why a 64-bit process can claim $2^{64}$ bytes regardless of RAM.",
        prereqs: ["Cache memory and locality"],
        tags: ["memory"],
      },
      {
        name: "Moore's Law",
        description: "Empirical observation that transistor density doubles roughly every two years.",
        keyInsight: "Gordon Moore (1965; revised 1975) — held for ~60 years, slowed sharply after 2015. Dennard scaling (frequency per area) ended around 2005, driving the shift to multicore.",
        prereqs: [],
        tags: ["scaling"],
        famous: true,
      },
      {
        name: "Multicore and parallelism",
        description: "Multiple CPU cores on a single chip running independent instruction streams.",
        keyInsight: "After Dennard scaling broke, performance scaling moved from frequency to core count. Amdahl's law caps speedup: $S = 1 / (s + p/N)$ where $s$ is the serial fraction — even a small serial portion bounds parallel speedup.",
        notation: "S(N) = \\frac{1}{s + (1-s)/N}",
        prereqs: ["Moore's Law"],
        tags: ["parallel"],
      },
      {
        name: "SIMD and vector processing",
        description: "Single instruction operates on a vector of operands.",
        keyInsight: "AVX-512, ARM SVE, GPU warps amortize instruction decode across many lanes. Critical for media codecs, ML inference, and scientific kernels; ill-suited to branchy code.",
        prereqs: ["Instruction set architecture (ISA)"],
        tags: ["parallel", "simd"],
      },
      {
        name: "Branch prediction",
        description: "Speculation about which branch a conditional will take.",
        keyInsight: "Modern predictors (TAGE, perceptron) reach >97% accuracy on typical code. Misprediction costs 10–20 cycles by flushing the pipeline — and is the attack surface exploited by Spectre.",
        prereqs: ["Pipelining"],
        tags: ["microarch"],
      },
      {
        name: "GPUs and SIMT",
        description: "Graphics processors as throughput-oriented massively parallel machines.",
        keyInsight: "Thousands of threads grouped into warps (32 threads) execute the same instruction in lockstep — Single Instruction Multiple Threads. Throughput dominates over latency; ideal for matrix multiplies, the workhorse of deep-learning training and inference.",
        prereqs: ["Multicore and parallelism", "SIMD and vector processing"],
        tags: ["gpu", "parallel"],
      },
    ],
  },

  // ── Family 10 ──────────────────────────────────────────────────────────────
  {
    slug: "operating-systems",
    number: 10,
    name: "Operating Systems",
    blurb: "Resource management, abstraction, and isolation between programs and hardware.",
    section: "C",
    color: "emerald",
    entries: [
      {
        name: "Process",
        description: "An OS abstraction of a running program with its own address space and resources.",
        keyInsight: "Each process has a private virtual address space, file descriptors, registers, and a scheduling state. The fundamental unit of isolation: a fault in one process leaves others intact.",
        prereqs: ["Virtual memory"],
        tags: ["abstraction"],
      },
      {
        name: "Thread",
        description: "An independent flow of control within a process, sharing its address space.",
        keyInsight: "Threads share memory but have separate registers and stacks. Lighter-weight context switching than processes; the shared memory makes coordination hazardous (races, deadlocks).",
        prereqs: ["Process"],
        tags: ["concurrency"],
      },
      {
        name: "Scheduling",
        description: "Choosing which runnable thread to execute on each CPU at each moment.",
        keyInsight: "Round-robin, priority-based, MLFQ, CFS (Linux's red-black-tree weighted fair queueing). No universal optimum: real-time, throughput, fairness, and latency are competing objectives.",
        prereqs: ["Thread"],
        tags: ["scheduling"],
      },
      {
        name: "Synchronization (locks, semaphores)",
        description: "Primitives that serialize access to shared state.",
        keyInsight: "Mutex (Dijkstra, 1965): mutual exclusion via test-and-set. Semaphore: a generalized counter for bounded resources. Condition variables wait on predicates. Misuse causes deadlock, livelock, or priority inversion.",
        prereqs: ["Thread"],
        tags: ["concurrency", "sync"],
      },
      {
        name: "Deadlock",
        description: "A cycle of threads each waiting on a resource the next holds.",
        keyInsight: "Coffman's four necessary conditions: mutual exclusion, hold-and-wait, no preemption, circular wait. Strategies: detection-and-recovery, avoidance (Banker's algorithm), prevention (lock ordering), or ignore (the 'Ostrich algorithm').",
        prereqs: ["Synchronization (locks, semaphores)"],
        tags: ["concurrency"],
      },
      {
        name: "File system",
        description: "Persistent named storage for byte sequences with hierarchical organization.",
        keyInsight: "Inode-based filesystems (UFS, ext4) separate metadata from data; log-structured (F2FS, ZFS) optimize for sequential writes; copy-on-write (Btrfs, ZFS) enables snapshots and integrity. POSIX is the shared API surface.",
        prereqs: ["Virtual memory"],
        tags: ["storage"],
      },
      {
        name: "System call",
        description: "Controlled entry from user code into the kernel.",
        keyInsight: "Trap instruction switches privilege level, dispatches via a table, returns a result. The single point at which security boundaries are enforced; the sandbox of seccomp, the audit point of strace, the attack surface of every CVE in kernel parsing.",
        prereqs: ["Process"],
        tags: ["kernel"],
      },
      {
        name: "Memory management (paging)",
        description: "Fixed-size pages translated by page tables and resident in RAM or swapped to disk.",
        keyInsight: "Page-fault handler brings missing pages from disk; replacement policies (LRU, second-chance, working set) decide what to evict. 4KB pages are conventional; huge pages (2MB, 1GB) reduce TLB pressure for big working sets.",
        prereqs: ["Virtual memory"],
        tags: ["memory"],
      },
      {
        name: "Interrupt handling",
        description: "Hardware signal that diverts the CPU to a kernel handler.",
        keyInsight: "Vectored dispatch to interrupt service routines; the bottom-half/tasklet pattern defers slow processing. The mechanism that turns a polling-free OS — every device, every timer, every keyboard event arrives this way.",
        prereqs: ["System call"],
        tags: ["kernel"],
      },
      {
        name: "Containers and namespaces",
        description: "OS-level virtualization isolating processes via kernel namespaces and cgroups.",
        keyInsight: "Linux namespaces partition PID, network, mount, IPC, user; cgroups bound CPU, memory, I/O. Docker, Kubernetes, and systemd-nspawn all sit on this kernel surface — lighter than VMs but sharing the host kernel.",
        prereqs: ["Process"],
        tags: ["isolation"],
      },
    ],
  },

  // ── Family 11 ──────────────────────────────────────────────────────────────
  {
    slug: "networking-distributed",
    number: 11,
    name: "Networking & Distributed Systems",
    blurb: "Protocols, abstractions, and the impossibility results that bound them.",
    section: "C",
    color: "teal",
    entries: [
      {
        name: "OSI / TCP-IP model",
        description: "Layered abstractions for network communication.",
        keyInsight: "Application / transport / network / link / physical — each layer hides the one below. The Internet uses the 4-layer TCP/IP refinement; OSI's 7-layer model is mostly pedagogical today.",
        prereqs: [],
        tags: ["model"],
      },
      {
        name: "IP (Internet Protocol)",
        description: "Best-effort, connectionless datagram delivery between hosts.",
        keyInsight: "IPv4 (32-bit) and IPv6 (128-bit) addresses; routing happens via longest-prefix match. Best-effort: packets can be dropped, reordered, or duplicated — TCP picks up the slack.",
        prereqs: ["OSI / TCP-IP model"],
        tags: ["network"],
      },
      {
        name: "TCP (Transmission Control Protocol)",
        description: "Reliable, in-order, byte-stream delivery atop IP.",
        keyInsight: "Three-way handshake, sequence numbers, cumulative ACKs, sliding window, congestion control (Reno, CUBIC, BBR). The reliability illusion that underwrites HTTP, SSH, SMTP, and ~80% of internet bytes.",
        prereqs: ["IP (Internet Protocol)"],
        tags: ["transport"],
      },
      {
        name: "HTTP",
        description: "Application-layer protocol for distributed hypermedia.",
        keyInsight: "Request-response over TCP (HTTP/1.1) or multiplexed streams (HTTP/2 over TCP, HTTP/3 over QUIC/UDP). Stateless by default; cookies, sessions, and tokens layer state on top.",
        prereqs: ["TCP (Transmission Control Protocol)"],
        tags: ["application"],
      },
      {
        name: "DNS",
        description: "Hierarchical distributed naming system mapping names to IP addresses.",
        keyInsight: "Resolvers walk root → TLD → authoritative server; results are cached with per-record TTLs. The Internet's most-used distributed database; UDP/53 (and TCP fallback) carry billions of queries per second.",
        prereqs: ["IP (Internet Protocol)"],
        tags: ["application"],
      },
      {
        name: "TLS",
        description: "Cryptographic transport providing confidentiality, integrity, and server authentication.",
        keyInsight: "Handshake negotiates cipher suite, exchanges a key via (EC)DHE, authenticates via a certificate chain rooted in a trust store. TLS 1.3 (2018) cuts a round trip and removes legacy crypto.",
        prereqs: ["TCP (Transmission Control Protocol)", "Public-key cryptography"],
        tags: ["security"],
      },
      {
        name: "CAP theorem",
        description: "In a distributed system facing a partition, choose at most two of consistency, availability, partition-tolerance.",
        keyInsight: "Brewer's conjecture (2000), proved by Gilbert and Lynch (2002). In practice every distributed datastore is partition-tolerant; the choice is C-vs-A under partition (CP: Spanner, etcd; AP: Cassandra, Dynamo).",
        prereqs: [],
        tags: ["theorem", "distributed"],
        famous: true,
      },
      {
        name: "Consensus (Paxos / Raft)",
        description: "Protocols by which replicas agree on a single value despite failures.",
        keyInsight: "Paxos (Lamport, 1990s): provably correct but notoriously hard to implement. Raft (Ongaro & Ousterhout, 2014): equivalent power with explicit leader election and log replication — used by etcd, Consul, TiKV, CockroachDB.",
        prereqs: ["CAP theorem"],
        tags: ["consensus"],
      },
      {
        name: "FLP impossibility",
        description: "No deterministic asynchronous consensus protocol tolerates even one crash failure.",
        keyInsight: "Fischer-Lynch-Paterson (1985): in a fully asynchronous system, no deterministic protocol guarantees both safety and liveness with even one faulty process. Practical systems escape via timeouts, randomization, or partial synchrony.",
        prereqs: ["Consensus (Paxos / Raft)"],
        tags: ["impossibility"],
        famous: true,
      },
      {
        name: "Byzantine fault tolerance",
        description: "Consensus tolerating arbitrary (including malicious) failures.",
        keyInsight: "Lamport's Byzantine Generals (1982): with $n$ replicas, tolerate $f$ Byzantine faults if $n \\ge 3f + 1$. PBFT, Tendermint, and HotStuff are practical BFT consensus protocols; the substrate of permissioned blockchains.",
        prereqs: ["Consensus (Paxos / Raft)"],
        tags: ["consensus", "fault-tolerance"],
      },
      {
        name: "MapReduce",
        description: "Programming model for batch processing on large clusters.",
        keyInsight: "Dean & Ghemawat (2004): user supplies $\\text{map}$ and $\\text{reduce}$; the runtime handles distribution, shuffle, and fault tolerance. The basis for Hadoop and Spark; the paradigm shift that made petabyte-scale analytics routine.",
        prereqs: [],
        tags: ["distributed", "batch"],
      },
    ],
  },

  // ── Family 12 ──────────────────────────────────────────────────────────────
  {
    slug: "databases",
    number: 12,
    name: "Databases",
    blurb: "Storing, querying, and updating persistent structured data under concurrency.",
    section: "C",
    color: "emerald",
    entries: [
      {
        name: "Relational model",
        description: "Data organized as relations (tables) with rows and typed columns, queried by relational algebra.",
        keyInsight: "Codd (1970): query-language and physical-storage independence. Predicate logic underlies relational algebra; SQL is its industrial dialect.",
        prereqs: ["Predicate (first-order) logic"],
        tags: ["model"],
        famous: true,
      },
      {
        name: "SQL",
        description: "Declarative query language for relational databases.",
        keyInsight: "Specify the result you want — joins, filters, aggregations — and let the query planner choose the physical plan. ISO-standard since 1986; still the most widely-deployed data query language.",
        prereqs: ["Relational model"],
        tags: ["query"],
      },
      {
        name: "Normalization",
        description: "Schema design that minimizes redundancy and update anomalies.",
        keyInsight: "1NF eliminates repeating groups; 2NF, 3NF, BCNF progressively remove partial and transitive dependencies. Higher normal forms reduce anomalies at the cost of more joins; denormalization is the analytic counterpoint.",
        prereqs: ["Relational model"],
        tags: ["schema"],
      },
      {
        name: "ACID transactions",
        description: "Atomicity, Consistency, Isolation, Durability — the contract a transactional DBMS provides.",
        keyInsight: "Atomic: all-or-nothing. Consistent: leaves DB in a valid state. Isolated: concurrent transactions appear serial. Durable: committed effects survive crashes. Implemented with WAL, locks, and snapshot isolation.",
        prereqs: ["Relational model"],
        tags: ["transactions"],
      },
      {
        name: "Indexing (B-tree / hash)",
        description: "Auxiliary structure accelerating lookups at the cost of write overhead.",
        keyInsight: "B-trees support range and order queries; hash indexes are point-only. LSM-trees (LevelDB, RocksDB, ScyllaDB) trade read amplification for write throughput. Choice of index is the single biggest knob for query performance.",
        prereqs: ["B-tree", "Hash table"],
        tags: ["index"],
      },
      {
        name: "Query optimization",
        description: "Choosing an efficient execution plan for a declarative query.",
        keyInsight: "Cost-based optimizers (System R, 1979) enumerate plans and score them using statistics; rule-based optimizers apply heuristics. Selecting join order is NP-hard in the number of relations.",
        prereqs: ["SQL"],
        tags: ["optimizer"],
      },
      {
        name: "Isolation levels",
        description: "Trade-off between transaction concurrency and the anomalies it permits.",
        keyInsight: "ANSI levels — read-uncommitted, read-committed, repeatable-read, serializable — admit successively fewer anomalies (dirty read, non-repeatable read, phantom). Snapshot isolation and serializable snapshot isolation give MVCC implementations.",
        prereqs: ["ACID transactions"],
        tags: ["concurrency"],
      },
      {
        name: "Write-ahead log (WAL)",
        description: "Log every change before applying it to the data pages.",
        keyInsight: "ARIES (Mohan, 1992): undo/redo log entries enable crash recovery to any consistent state. WAL is the substrate of replication: shipping the log is shipping the database.",
        prereqs: ["ACID transactions"],
        tags: ["durability"],
      },
      {
        name: "NoSQL",
        description: "Family of non-relational data stores prioritizing scale-out or specialized models.",
        keyInsight: "Key-value (Redis, DynamoDB), document (MongoDB), wide-column (Cassandra, HBase), graph (Neo4j). Often relax ACID to gain horizontal scaling — exactly the CAP trade-off in practice.",
        prereqs: ["CAP theorem"],
        tags: ["nosql"],
      },
      {
        name: "Eventual consistency",
        description: "Replicas converge to the same state if updates stop.",
        keyInsight: "Vogels (Amazon, 2008): weaker than linearizability but enables AP systems under CAP. CRDTs and vector clocks provide mathematical guarantees; users see stale reads in exchange for availability.",
        prereqs: ["CAP theorem"],
        tags: ["consistency"],
      },
    ],
  },

  // ── Family 13 ──────────────────────────────────────────────────────────────
  {
    slug: "programming-language-theory",
    number: 13,
    name: "Programming Language Theory",
    blurb: "Syntax, semantics, types, and what languages can express.",
    section: "D",
    color: "green",
    entries: [
      {
        name: "Lambda calculus",
        description: "A formal system of anonymous function abstraction and application.",
        keyInsight: "Church (1930s): only abstraction $\\lambda x. e$, application $e_1\\, e_2$, and variables. Turing-complete; the substrate for functional programming, type theory, and denotational semantics.",
        notation: "(\\lambda x. M)\\, N \\to M[x := N]",
        prereqs: [],
        tags: ["foundations"],
        famous: true,
      },
      {
        name: "Operational semantics",
        description: "Defines program meaning by rules of execution stepping.",
        keyInsight: "Small-step (Plotkin) gives a transition relation $e \\to e'$; big-step (natural) gives $e \\Downarrow v$. Concrete, machine-flavored, well-suited to soundness proofs and language implementation.",
        prereqs: ["Lambda calculus"],
        tags: ["semantics"],
      },
      {
        name: "Denotational semantics",
        description: "Maps each program to a mathematical object (its denotation) compositionally.",
        keyInsight: "Scott-Strachey: meanings live in domains (CPOs) with fixed-points for recursion. Compositional and abstract — but practical reasoning often defaults to operational style.",
        prereqs: ["Operational semantics"],
        tags: ["semantics"],
        xref: ["mathematics"],
      },
      {
        name: "Type system",
        description: "Syntactic discipline classifying expressions by the values they compute.",
        keyInsight: "Statically rule out classes of errors at compile time. Strong vs. weak, static vs. dynamic, nominal vs. structural — orthogonal axes. Trade-off: more expressive types catch more bugs but reject more good programs.",
        prereqs: ["Lambda calculus"],
        tags: ["types"],
      },
      {
        name: "Hindley-Milner type inference",
        description: "Algorithm $W$ infers the most general (principal) type for ML-style programs.",
        keyInsight: "Lets you write code without type annotations and still get full static typing. Foundation of OCaml, Haskell, and (limited) Rust/Swift/Scala inference; full HM is decidable in low-degree polynomial time on practical programs.",
        prereqs: ["Type system"],
        tags: ["inference"],
      },
      {
        name: "Polymorphism",
        description: "A single piece of code applies to many types.",
        keyInsight: "Parametric (generics): same code, different types. Ad-hoc (overloading, type classes): same name, type-specific code. Subtype: substitutability via inheritance or structural subtyping.",
        prereqs: ["Type system"],
        tags: ["types"],
      },
      {
        name: "Algebraic data types",
        description: "Composite types built from products (records) and sums (tagged unions).",
        keyInsight: "Type algebra mirrors logic: product = $\\wedge$, sum = $\\vee$, function = $\\to$. Pattern matching is exhaustive case analysis on the sum. The shape that makes ML, Haskell, and Rust enums so compact.",
        prereqs: ["Type system"],
        tags: ["types"],
      },
      {
        name: "Garbage collection",
        description: "Automatic reclamation of memory no longer reachable from program roots.",
        keyInsight: "Mark-and-sweep, generational, copying, concurrent (Go, ZGC, Shenandoah). Trade-off pause time vs. throughput vs. footprint. Frees programmers from explicit free() but adds runtime cost and unpredictable latency.",
        prereqs: ["Memory management (paging)"],
        tags: ["runtime"],
      },
      {
        name: "Closures",
        description: "A function paired with its captured lexical environment.",
        keyInsight: "Enables higher-order programming: functions can be returned, stored, partially applied. Implemented by capturing free variables either by value, by reference, or by 'boxing' on the heap.",
        prereqs: ["Lambda calculus"],
        tags: ["features"],
      },
      {
        name: "Effects and monads",
        description: "Structuring impure computation (IO, state, exceptions) in a pure language.",
        keyInsight: "Monad: a type constructor $M$ with $\\text{return} : a \\to M\\, a$ and $\\text{bind} : M\\, a \\to (a \\to M\\, b) \\to M\\, b$ satisfying three laws. Effect systems and algebraic effects generalize monads with composable handlers.",
        prereqs: ["Algebraic data types"],
        tags: ["effects"],
      },
    ],
  },

  // ── Family 14 ──────────────────────────────────────────────────────────────
  {
    slug: "compilers",
    number: 14,
    name: "Compilers & Interpreters",
    blurb: "Translating high-level programs to executable form.",
    section: "D",
    color: "green",
    entries: [
      {
        name: "Lexical analysis",
        description: "Splitting source text into tokens.",
        keyInsight: "Lexers are typically generated from regular expressions (lex/flex) — exactly the regular-language frontier. Produces the linear token stream the parser consumes.",
        prereqs: ["Regular expression"],
        tags: ["frontend"],
      },
      {
        name: "Parsing",
        description: "Building an abstract syntax tree from a token stream.",
        keyInsight: "Top-down (LL, recursive descent) and bottom-up (LR, LALR) are the two practical paradigms for deterministic CFGs. Hand-written recursive-descent dominates production compilers (GCC, Clang, Roslyn) for diagnostic flexibility.",
        prereqs: ["Context-free grammar", "Parsing — LL and LR"],
        tags: ["frontend"],
      },
      {
        name: "Abstract syntax tree (AST)",
        description: "Tree representation of program structure abstracting away surface syntax.",
        keyInsight: "Internal nodes are language constructs (Assign, If, Call); leaves are identifiers and literals. The canonical IR for static analysis, refactoring tools, and language servers.",
        prereqs: ["Parsing"],
        tags: ["ir"],
      },
      {
        name: "Static single assignment (SSA)",
        description: "Intermediate form where each variable is assigned exactly once.",
        keyInsight: "$\\varphi$-functions reconcile multiple assignments at control-flow joins. Makes dataflow analyses (constant propagation, dead code, register allocation) far simpler; standard IR in LLVM, GCC, V8 turbofan, and HotSpot C2.",
        prereqs: ["Abstract syntax tree (AST)"],
        tags: ["ir", "optimization"],
      },
      {
        name: "Dataflow analysis",
        description: "Compute properties of program variables across the control-flow graph.",
        keyInsight: "Lattice-valued analyses (reaching definitions, live variables, available expressions) iterated to a fixed point. Bottom-up framework for nearly every classical compiler optimization.",
        prereqs: ["Static single assignment (SSA)"],
        tags: ["analysis"],
      },
      {
        name: "Code generation",
        description: "Lowering IR to target-machine instructions.",
        keyInsight: "Instruction selection (tree-pattern matching or DAG covering), register allocation (graph coloring), instruction scheduling (list scheduling). Quality of these passes determines real-world performance more than any single optimization.",
        prereqs: ["Static single assignment (SSA)"],
        tags: ["backend"],
      },
      {
        name: "Register allocation",
        description: "Map an unbounded set of program variables to a finite set of CPU registers.",
        keyInsight: "Chaitin's graph-coloring formulation (1981) is NP-hard; linear scan (Poletto-Sarkar, 1999) gives near-optimal results in linear time for JIT compilers. Spilling to memory is the cost when colors run out.",
        prereqs: ["Code generation"],
        tags: ["backend", "optimization"],
      },
      {
        name: "Interpreter",
        description: "Executes a program directly against its source or AST.",
        keyInsight: "Tree-walking interpreter is the simplest model; bytecode interpreter compiles to a stack or register VM (Python, Ruby, JVM, CLR). Trades startup time for steady-state speed compared to AOT compilation.",
        prereqs: ["Abstract syntax tree (AST)"],
        tags: ["runtime"],
      },
      {
        name: "Just-in-time (JIT) compilation",
        description: "Compile hot code paths to machine code at runtime.",
        keyInsight: "Tiered compilation: interpret cold code, JIT warm code with cheap compilers, recompile hot code with expensive optimizers. HotSpot, V8 turbofan, .NET RyuJIT, PyPy — typically 10–100× over pure interpretation.",
        prereqs: ["Interpreter", "Code generation"],
        tags: ["runtime"],
      },
      {
        name: "Optimization passes",
        description: "Source-to-source transformations preserving meaning but improving performance.",
        keyInsight: "Constant folding, dead code elimination, loop-invariant code motion, inlining, vectorization. Modern compilers (LLVM, GCC) run dozens of passes; ordering and phase interaction are decades-old open practical problems.",
        prereqs: ["Dataflow analysis"],
        tags: ["optimization"],
      },
      {
        name: "WebAssembly",
        description: "Portable binary instruction format for a stack machine.",
        keyInsight: "W3C standard (2017): low-level, safe, near-native execution in browsers and beyond. WASI extends it to a portable systems API; targets include Rust, C/C++, Go, AssemblyScript, .NET.",
        prereqs: ["Code generation"],
        tags: ["runtime"],
      },
    ],
  },

  // ── Family 15 ──────────────────────────────────────────────────────────────
  {
    slug: "software-engineering",
    number: 15,
    name: "Software Engineering & Design Patterns",
    blurb: "Practices and patterns for building and maintaining systems with humans on a team.",
    section: "D",
    color: "green",
    entries: [
      {
        name: "Version control (Git)",
        description: "Tracks file changes as a DAG of immutable snapshots.",
        keyInsight: "Linus Torvalds (2005): each commit is a SHA-1 hash over its tree and parents — content-addressed, tamper-evident, distributed. The substrate of GitHub, GitLab, and modern code review.",
        prereqs: ["Cryptographic hash function"],
        tags: ["tooling"],
      },
      {
        name: "Unit testing",
        description: "Automated tests exercising the smallest pieces of behavior in isolation.",
        keyInsight: "Beck's xUnit pattern: arrange, act, assert. Fast, deterministic, runnable on every change. The first defense against regression; the floor of every CI pipeline.",
        prereqs: [],
        tags: ["testing"],
      },
      {
        name: "Integration / end-to-end testing",
        description: "Tests crossing component or system boundaries.",
        keyInsight: "Mike Cohn's pyramid: many unit tests, fewer integration tests, fewer still end-to-end tests. Cost and flakiness grow up the pyramid; coverage of multi-component behavior is what makes them irreplaceable.",
        prereqs: ["Unit testing"],
        tags: ["testing"],
      },
      {
        name: "Continuous integration / delivery",
        description: "Automated build, test, and deploy on every change.",
        keyInsight: "Each commit triggers the pipeline: build, test, package, deploy. Reduces integration debt to near-zero; presupposes a deterministic build and broad automated test coverage.",
        prereqs: ["Version control (Git)"],
        tags: ["devops"],
      },
      {
        name: "Refactoring",
        description: "Behavior-preserving code transformations improving structure.",
        keyInsight: "Fowler's catalog (1999): extract method, rename, inline, replace conditional with polymorphism. Small, mechanical, test-backed steps that keep large codebases pliable.",
        prereqs: [],
        tags: ["practice"],
      },
      {
        name: "Design patterns (Gang of Four)",
        description: "Reusable solutions to recurring object-oriented design problems.",
        keyInsight: "23 patterns (1994): creational (Factory, Singleton, Builder), structural (Adapter, Decorator, Proxy), behavioral (Observer, Strategy, Visitor). Vocabulary for design discussions; some have since aged poorly (Singleton).",
        prereqs: [],
        tags: ["patterns"],
        famous: true,
      },
      {
        name: "SOLID principles",
        description: "Five object-oriented design heuristics for maintainability.",
        keyInsight: "Single-responsibility, Open-closed, Liskov substitution, Interface segregation, Dependency inversion (Martin, 2000). Guidance — not laws; over-application produces enterprise-style indirection.",
        prereqs: [],
        tags: ["principles"],
      },
      {
        name: "Agile / Scrum",
        description: "Iterative, increment-based software development with regular stakeholder feedback.",
        keyInsight: "Agile Manifesto (2001): individuals over processes, working software over documentation, customer collaboration over contracts, responding to change over plans. Scrum is its most-used ceremonial implementation.",
        prereqs: [],
        tags: ["process"],
      },
      {
        name: "Code review",
        description: "Peer reading of changes before merge.",
        keyInsight: "Catches bugs, spreads codebase knowledge, enforces conventions. Empirically the highest-yield defect-removal practice after testing — and one of the cheapest.",
        prereqs: ["Version control (Git)"],
        tags: ["practice"],
      },
      {
        name: "Microservices",
        description: "Architectural style decomposing a system into independently deployable services.",
        keyInsight: "Each service owns its data and is independently deployable. Trades intra-process complexity for network and operational complexity; pays off at organizational scales where independent teams can move without coordinating deploys.",
        prereqs: ["HTTP"],
        tags: ["architecture"],
      },
    ],
  },
];
