import type { Family } from "./types";

export const FAMILIES_9_16: Family[] = [
  // ── Family 9 ──────────────────────────────────────────────────────────────
  {
    slug: "laws-of-thermodynamics",
    number: 9,
    name: "Laws of Thermodynamics",
    blurb: "The four laws that govern energy, entropy, and the direction of natural processes.",
    section: "B",
    color: "rose",
    entries: [
      {
        name: "Zeroth law",
        description: "If two systems are each in thermal equilibrium with a third, they are in equilibrium with each other.",
        keyFact: "This transitivity of thermal equilibrium is what makes temperature a well-defined measurable quantity and thermometry possible.",
        tags: ["thermodynamics", "laws"],
      },
      {
        name: "First law (energy conservation)",
        description: "Change in internal energy equals heat absorbed minus work done by the system.",
        keyFact: "$\\Delta U = Q - W$. Energy is neither created nor destroyed — a perpetual motion machine of the first kind is impossible.",
        formula: "\\Delta U = Q - W",
        tags: ["thermodynamics", "laws"],
      },
      {
        name: "Second law",
        description: "The entropy of an isolated system never decreases.",
        keyFact: "Heat flows spontaneously only from hot to cold. No process converts heat entirely into work (Kelvin-Planck). Entropy quantifies the directionality of time.",
        tags: ["thermodynamics", "laws", "entropy"],
      },
      {
        name: "Third law (Nernst theorem)",
        description: "The entropy of a perfect crystal approaches zero as temperature approaches absolute zero.",
        keyFact: "$S \\to 0$ as $T \\to 0\\,\\mathrm{K}$; absolute zero is unattainable in a finite number of thermodynamic steps.",
        tags: ["thermodynamics", "laws"],
      },
      {
        name: "Entropy",
        description: "A state function measuring disorder or the number of accessible microstates.",
        keyFact: "Boltzmann: $S = k_B\\ln\\Omega$; Clausius: $dS = dQ_{rev}/T$. Entropy of the universe increases in every real process.",
        formula: "S = k_B\\ln\\Omega",
        tags: ["thermodynamics", "entropy"],
        xref: ["mathematics"],
      },
      {
        name: "Thermodynamic processes",
        description: "Ideal gas processes — isothermal, adiabatic, isobaric, isochoric.",
        keyFact: "Isothermal: $PV = \\text{const}$; adiabatic: $PV^\\gamma = \\text{const}$; isobaric: $V/T = \\text{const}$; isochoric: $P/T = \\text{const}$.",
        formula: "PV^\\gamma = \\text{const}\\quad\\text{(adiabatic, reversible)}",
        tags: ["thermodynamics", "processes"],
      },
      {
        name: "Ideal gas law",
        description: "The equation of state for an ideal gas.",
        keyFact: "$PV = nRT$; $R = 8.314\\,\\mathrm{J/(mol\\cdot K)}$. Equivalently $PV = Nk_BT$ where $N$ is particle number.",
        formula: "PV = nRT",
        tags: ["thermodynamics", "ideal-gas"],
        xref: ["chemistry"],
      },
      {
        name: "Helmholtz & Gibbs free energy",
        description: "Thermodynamic potentials determining spontaneity at fixed conditions.",
        keyFact: "Helmholtz: $F = U - TS$ (fixed $T$, $V$); Gibbs: $G = H - TS$ (fixed $T$, $P$). $\\Delta G < 0$ means a process is spontaneous.",
        formula: "G = H - TS,\\quad F = U - TS",
        tags: ["thermodynamics", "free-energy"],
        xref: ["chemistry"],
      },
      {
        name: "Enthalpy",
        description: "Total heat content at constant pressure.",
        keyFact: "$H = U + PV$; $\\Delta H = Q_P$ at constant pressure. Widely used in chemistry and engineering for heat of reaction.",
        formula: "H = U + PV",
        tags: ["thermodynamics", "enthalpy"],
      },
      {
        name: "Irreversibility & entropy production",
        description: "Real processes generate entropy; reversible processes are ideal limits.",
        keyFact: "$dS_{univ} \\geq 0$ always; $= 0$ only for reversible processes. The Clausius inequality: $\\oint dQ/T \\leq 0$ for any cycle.",
        formula: "\\oint \\frac{dQ}{T} \\leq 0",
        tags: ["thermodynamics", "irreversibility"],
      },
    ],
  },

  // ── Family 10 ──────────────────────────────────────────────────────────────
  {
    slug: "kinetic-theory-statistical",
    number: 10,
    name: "Kinetic Theory & Statistical Mechanics",
    blurb: "Molecular motion, distributions, the partition function, and quantum statistics.",
    section: "B",
    color: "violet",
    entries: [
      {
        name: "Kinetic theory of gases",
        description: "Gas pressure arises from molecular collisions with container walls.",
        keyFact: "$P = \\frac{1}{3}\\rho\\langle v^2\\rangle$; connects microscopic molecular motion to macroscopic pressure and temperature.",
        formula: "PV = \\tfrac{1}{3}Nm\\langle v^2\\rangle",
        tags: ["kinetic-theory", "statistical"],
      },
      {
        name: "Maxwell-Boltzmann distribution",
        description: "The distribution of molecular speeds in an equilibrium ideal gas.",
        keyFact: "Most probable $v_p = \\sqrt{2k_BT/m}$; mean $\\bar{v} = \\sqrt{8k_BT/(\\pi m)}$; RMS $v_{rms} = \\sqrt{3k_BT/m}$.",
        formula: "f(v) = 4\\pi n\\!\\left(\\frac{m}{2\\pi k_BT}\\right)^{\\!3/2}\\!v^2 e^{-mv^2/(2k_BT)}",
        tags: ["kinetic-theory", "distribution"],
      },
      {
        name: "Equipartition theorem",
        description: "Energy is shared equally among all quadratic degrees of freedom.",
        keyFact: "Each quadratic degree of freedom contributes $\\frac{1}{2}k_BT$ on average; monatomic ideal gas: $U = \\frac{3}{2}Nk_BT$.",
        formula: "\\langle E_i \\rangle = \\tfrac{1}{2}k_B T",
        tags: ["statistical", "equipartition"],
      },
      {
        name: "Mean free path",
        description: "Average distance a molecule travels between collisions.",
        keyFact: "$\\ell = 1/(\\sqrt{2}\\pi d^2 n)$ where $d$ is molecular diameter and $n$ is number density.",
        formula: "\\ell = \\frac{1}{\\sqrt{2}\\pi d^2 n}",
        tags: ["kinetic-theory", "diffusion"],
      },
      {
        name: "Boltzmann factor",
        description: "Probability of a microstate with energy $E$ in thermal equilibrium.",
        keyFact: "$P(E) \\propto e^{-E/k_BT}$; higher-energy states are exponentially less likely. Foundation of all statistical mechanics.",
        formula: "P(E) \\propto e^{-E/k_B T}",
        tags: ["statistical", "boltzmann"],
      },
      {
        name: "Partition function",
        description: "Sum over all microstates, encoding all thermodynamic properties.",
        keyFact: "$Z = \\sum_i e^{-E_i/k_BT}$; free energy $F = -k_BT\\ln Z$; all thermodynamic quantities derive from $Z$.",
        formula: "Z = \\sum_i e^{-E_i/k_B T}",
        tags: ["statistical", "partition-function"],
      },
      {
        name: "Fermi-Dirac statistics",
        description: "Quantum statistics for identical fermions (half-integer spin).",
        keyFact: "Mean occupation $\\langle n\\rangle = 1/(e^{(E-\\mu)/k_BT}+1)$; at $T=0$ all states up to the Fermi energy $E_F$ are filled (Fermi sea).",
        formula: "\\langle n\\rangle = \\frac{1}{e^{(E-\\mu)/k_BT}+1}",
        tags: ["statistical", "quantum", "fermions"],
      },
      {
        name: "Bose-Einstein statistics",
        description: "Quantum statistics for identical bosons (integer spin).",
        keyFact: "Mean occupation $\\langle n\\rangle = 1/(e^{(E-\\mu)/k_BT}-1)$; bosons can pile into the same state — basis for Bose-Einstein condensation and lasers.",
        formula: "\\langle n\\rangle = \\frac{1}{e^{(E-\\mu)/k_BT}-1}",
        tags: ["statistical", "quantum", "bosons"],
      },
      {
        name: "Phase transitions",
        description: "Sudden changes in macroscopic state as a thermodynamic parameter crosses a threshold.",
        keyFact: "First-order (melting, boiling): latent heat, discontinuous density. Second-order (continuous): diverging correlation length near critical point; universality classes.",
        tags: ["statistical", "phase-transitions"],
      },
      {
        name: "Arrow of time",
        description: "The macroscopic asymmetry between past and future arising from entropy.",
        keyFact: "Microscopic laws are time-symmetric; entropy always increases macroscopically. Boltzmann's H-theorem shows entropy increase is overwhelmingly probable for typical initial conditions.",
        status: "open",
        tags: ["statistical", "entropy", "foundations"],
      },
    ],
  },

  // ── Family 11 ──────────────────────────────────────────────────────────────
  {
    slug: "heat-engines-cycles",
    number: 11,
    name: "Heat Engines & Cycles",
    blurb: "Carnot efficiency, practical cycles, refrigeration, and the Clausius inequality.",
    section: "B",
    color: "indigo",
    entries: [
      {
        name: "Heat engine",
        description: "A device that converts heat into mechanical work using a temperature difference.",
        keyFact: "Efficiency $\\eta = W/Q_H = 1 - Q_C/Q_H$; requires both a hot source $T_H$ and a cold sink $T_C$.",
        formula: "\\eta = \\frac{W}{Q_H} = 1 - \\frac{Q_C}{Q_H}",
        tags: ["thermodynamics", "engines"],
      },
      {
        name: "Carnot cycle",
        description: "The idealized reversible engine operating between two temperature reservoirs.",
        keyFact: "Two isothermal + two adiabatic steps. Efficiency $\\eta_C = 1 - T_C/T_H$ — the maximum possible for any engine operating between $T_H$ and $T_C$.",
        formula: "\\eta_C = 1 - \\frac{T_C}{T_H}",
        tags: ["thermodynamics", "carnot"],
      },
      {
        name: "Carnot's theorem",
        description: "No engine can be more efficient than a Carnot engine between the same reservoirs.",
        keyFact: "All reversible engines between the same two reservoirs have exactly $\\eta_C$; irreversible engines are strictly less efficient.",
        tags: ["thermodynamics", "carnot", "second-law"],
      },
      {
        name: "Kelvin-Planck statement",
        description: "One statement of the second law: no cyclic device converts heat from a single reservoir entirely into work.",
        keyFact: "Some heat $Q_C > 0$ must always be rejected to a cold reservoir. Violating this would allow a perpetual motion machine of the second kind.",
        tags: ["thermodynamics", "second-law"],
      },
      {
        name: "Clausius statement",
        description: "Another equivalent form: heat cannot flow spontaneously from cold to hot.",
        keyFact: "Moving heat from cold to hot requires external work input — as in a refrigerator.",
        tags: ["thermodynamics", "second-law"],
      },
      {
        name: "Refrigeration & heat pumps",
        description: "Devices that move heat against its natural direction using work input.",
        keyFact: "Refrigerator COP: $K_R = Q_C/W$; heat pump COP: $K_{HP} = Q_H/W$. Carnot: $K_C = T_C/(T_H-T_C)$.",
        formula: "K_R = \\frac{Q_C}{W},\\quad K_{HP} = \\frac{Q_H}{W}",
        tags: ["thermodynamics", "refrigeration"],
      },
      {
        name: "Otto cycle",
        description: "The idealized cycle for the spark-ignition internal combustion engine.",
        keyFact: "Two adiabatic + two isochoric steps. Efficiency $\\eta = 1 - r^{1-\\gamma}$ where $r$ is compression ratio and $\\gamma = C_P/C_V$.",
        formula: "\\eta_{Otto} = 1 - r^{1-\\gamma}",
        tags: ["thermodynamics", "engines", "otto"],
      },
      {
        name: "Clausius inequality",
        description: "Integral constraint relating entropy and heat exchange in any cycle.",
        keyFact: "$\\oint dQ/T \\leq 0$; equality for reversible cycles. Quantifies irreversibility and entropy generation.",
        formula: "\\oint \\frac{dQ}{T} \\leq 0",
        tags: ["thermodynamics", "entropy", "cycles"],
      },
    ],
  },

  // ── Family 12 ──────────────────────────────────────────────────────────────
  {
    slug: "electrostatics",
    number: 12,
    name: "Electrostatics",
    blurb: "Charge, Coulomb's law, electric fields, Gauss's law, and capacitance.",
    section: "C",
    color: "indigo",
    entries: [
      {
        name: "Electric charge",
        description: "A fundamental property of matter; the source of electromagnetic force.",
        keyFact: "Quantized in units of $e = 1.602\\times10^{-19}\\,\\mathrm{C}$; conserved in all interactions; Lorentz-invariant. Like charges repel, opposite attract.",
        tags: ["electrostatics", "charge"],
      },
      {
        name: "Coulomb's law",
        description: "Electrostatic force between two point charges.",
        keyFact: "$F = k_e q_1 q_2/r^2$; $k_e = 8.99\\times10^9\\,\\mathrm{N\\,m^2/C^2} = 1/(4\\pi\\varepsilon_0)$. Inverse-square, like gravity.",
        formula: "F = \\frac{k_e q_1 q_2}{r^2} = \\frac{q_1 q_2}{4\\pi\\varepsilon_0 r^2}",
        tags: ["electrostatics", "coulomb"],
      },
      {
        name: "Electric field",
        description: "Force per unit positive test charge at a point in space.",
        keyFact: "$\\vec{E} = \\vec{F}/q_0 = k_e q/r^2\\,\\hat{r}$ for a point charge; superposition applies; field lines point from $+$ to $-$.",
        formula: "\\vec{E} = \\frac{\\vec{F}}{q_0}",
        tags: ["electrostatics", "field"],
      },
      {
        name: "Gauss's law",
        description: "Electric flux through any closed surface equals enclosed charge over $\\varepsilon_0$.",
        keyFact: "$\\oint\\vec{E}\\cdot d\\vec{A} = Q_{enc}/\\varepsilon_0$; powerful for symmetric charge distributions (sphere, cylinder, plane).",
        formula: "\\oint\\vec{E}\\cdot d\\vec{A} = \\frac{Q_{enc}}{\\varepsilon_0}",
        tags: ["electrostatics", "gauss"],
      },
      {
        name: "Electric potential",
        description: "Potential energy per unit charge; a scalar field.",
        keyFact: "$V = k_e q/r$ for a point charge; $\\vec{E} = -\\nabla V$. Equipotential surfaces are perpendicular to field lines.",
        formula: "V = \\frac{k_e q}{r},\\quad \\vec{E} = -\\nabla V",
        tags: ["electrostatics", "potential"],
      },
      {
        name: "Capacitance",
        description: "Ability to store separated charge; energy storage in an electric field.",
        keyFact: "$C = Q/V$; parallel plates: $C = \\varepsilon_0 A/d$; energy stored $U = \\frac{1}{2}CV^2 = Q^2/(2C)$.",
        formula: "C = \\frac{Q}{V},\\quad U = \\tfrac{1}{2}CV^2",
        tags: ["electrostatics", "capacitance"],
      },
      {
        name: "Dielectrics",
        description: "Insulating materials that increase capacitance by polarizing in an electric field.",
        keyFact: "Dielectric constant $\\kappa > 1$ reduces $\\vec{E}$ inside by factor $\\kappa$; $C = \\kappa\\varepsilon_0 A/d$.",
        formula: "C = \\frac{\\kappa\\varepsilon_0 A}{d}",
        tags: ["electrostatics", "dielectric"],
      },
      {
        name: "Electric dipole",
        description: "A pair of equal and opposite charges separated by a small distance.",
        keyFact: "Dipole moment $\\vec{p} = q\\vec{d}$; torque $\\vec{\\tau} = \\vec{p}\\times\\vec{E}$; potential energy $U = -\\vec{p}\\cdot\\vec{E}$.",
        formula: "\\vec{\\tau} = \\vec{p}\\times\\vec{E},\\quad U = -\\vec{p}\\cdot\\vec{E}",
        tags: ["electrostatics", "dipole"],
      },
      {
        name: "Conductors in electrostatic equilibrium",
        description: "Charge and field behavior in and around a conductor at rest.",
        keyFact: "$\\vec{E} = 0$ inside; all charge resides on the surface; field is perpendicular to the surface. A closed conductor (Faraday cage) screens external fields.",
        tags: ["electrostatics", "conductors"],
      },
      {
        name: "Superposition principle",
        description: "Electric forces and fields add vectorially from multiple sources.",
        keyFact: "$\\vec{E}_{total} = \\sum_i\\vec{E}_i$; linearity of Maxwell's equations underpins all field calculations.",
        tags: ["electrostatics", "superposition"],
      },
    ],
  },

  // ── Family 13 ──────────────────────────────────────────────────────────────
  {
    slug: "magnetism",
    number: 13,
    name: "Magnetism & Induction",
    blurb: "Magnetic fields, Biot-Savart, Ampère, Lorentz force, and electromagnetic induction.",
    section: "C",
    color: "violet",
    entries: [
      {
        name: "Magnetic field",
        description: "A vector field that exerts forces on moving charges and magnetic dipoles.",
        keyFact: "Measured in tesla (T); $1\\,\\mathrm{T} = 1\\,\\mathrm{kg/(A\\cdot s^2)}$. No magnetic monopoles — field lines always close on themselves.",
        tags: ["magnetism", "field"],
      },
      {
        name: "Biot-Savart law",
        description: "Magnetic field produced by a steady current element.",
        keyFact: "$d\\vec{B} = \\frac{\\mu_0}{4\\pi}\\frac{I\\,d\\vec{\\ell}\\times\\hat{r}}{r^2}$; fundamental for computing $\\vec{B}$ from any current distribution.",
        formula: "d\\vec{B} = \\frac{\\mu_0}{4\\pi}\\frac{I\\,d\\vec{\\ell}\\times\\hat{r}}{r^2}",
        tags: ["magnetism", "biot-savart"],
      },
      {
        name: "Ampère's law",
        description: "Line integral of $\\vec{B}$ around a closed loop equals $\\mu_0$ times enclosed current.",
        keyFact: "$\\oint\\vec{B}\\cdot d\\vec{\\ell} = \\mu_0 I_{enc}$; useful for high-symmetry distributions (solenoid, toroid, long wire).",
        formula: "\\oint\\vec{B}\\cdot d\\vec{\\ell} = \\mu_0 I_{enc}",
        tags: ["magnetism", "ampere"],
      },
      {
        name: "Lorentz force",
        description: "Total electromagnetic force on a moving charged particle.",
        keyFact: "$\\vec{F} = q(\\vec{E}+\\vec{v}\\times\\vec{B})$; the magnetic component is always perpendicular to $\\vec{v}$ and does no work.",
        formula: "\\vec{F} = q(\\vec{E}+\\vec{v}\\times\\vec{B})",
        tags: ["magnetism", "lorentz"],
      },
      {
        name: "Magnetic force on a current",
        description: "Force on a current-carrying conductor in a magnetic field.",
        keyFact: "$\\vec{F} = I\\vec{L}\\times\\vec{B}$; the basis of electric motors. Parallel currents attract; anti-parallel repel.",
        formula: "\\vec{F} = I\\vec{L}\\times\\vec{B}",
        tags: ["magnetism", "force"],
      },
      {
        name: "Magnetic dipole",
        description: "A current loop or particle carrying a magnetic moment.",
        keyFact: "Magnetic moment $\\vec{m} = IA\\hat{n}$; torque $\\vec{\\tau} = \\vec{m}\\times\\vec{B}$; energy $U = -\\vec{m}\\cdot\\vec{B}$. Bar magnets and electron spins are magnetic dipoles.",
        formula: "\\vec{\\tau} = \\vec{m}\\times\\vec{B},\\quad U = -\\vec{m}\\cdot\\vec{B}",
        tags: ["magnetism", "dipole"],
      },
      {
        name: "Faraday's law of induction",
        description: "A changing magnetic flux through a loop induces an EMF.",
        keyFact: "$\\mathcal{E} = -d\\Phi_B/dt$; the negative sign is Lenz's law: the induced current opposes the flux change.",
        formula: "\\mathcal{E} = -\\frac{d\\Phi_B}{dt}",
        tags: ["magnetism", "induction", "faraday"],
      },
      {
        name: "Inductance",
        description: "Property of a circuit to oppose changes in current by generating a back-EMF.",
        keyFact: "$\\mathcal{E} = -L\\,dI/dt$; solenoid: $L = \\mu_0 n^2 V$; energy stored in magnetic field: $U = \\frac{1}{2}LI^2$.",
        formula: "\\mathcal{E}_L = -L\\frac{dI}{dt},\\quad U = \\tfrac{1}{2}LI^2",
        tags: ["magnetism", "inductance"],
      },
      {
        name: "Hall effect",
        description: "Transverse voltage generated when a current flows perpendicular to a magnetic field.",
        keyFact: "$V_H = IB/(ned)$; used to measure carrier density and type in semiconductors. The quantum Hall effect is a topological phenomenon (von Klitzing 1980).",
        formula: "V_H = \\frac{IB}{ned}",
        tags: ["magnetism", "hall-effect"],
      },
      {
        name: "Magnetic materials",
        description: "Paramagnetism, ferromagnetism, and diamagnetism.",
        keyFact: "Ferromagnets: permanent magnetic domains, $M \\neq 0$ below Curie temperature $T_C$. Paramagnets: weak alignment with $\\vec{B}$. Diamagnets: weakly repelled by $\\vec{B}$ (e.g., levitating frog).",
        tags: ["magnetism", "materials"],
      },
    ],
  },

  // ── Family 14 ──────────────────────────────────────────────────────────────
  {
    slug: "maxwell-equations",
    number: 14,
    name: "Maxwell's Equations",
    blurb: "The four field equations unifying electricity and magnetism, predicting light.",
    section: "C",
    color: "blue",
    entries: [
      {
        name: "Gauss's law for electricity",
        description: "Electric field diverges from charge — the differential form.",
        keyFact: "$\\nabla\\cdot\\vec{E} = \\rho/\\varepsilon_0$; charges are the sources and sinks of electric field lines.",
        formula: "\\nabla\\cdot\\vec{E} = \\frac{\\rho}{\\varepsilon_0}",
        tags: ["maxwell", "electrostatics"],
      },
      {
        name: "Gauss's law for magnetism",
        description: "No magnetic monopoles — magnetic field has zero divergence.",
        keyFact: "$\\nabla\\cdot\\vec{B} = 0$; magnetic field lines always form closed loops (or extend to infinity). No isolated north or south pole exists.",
        formula: "\\nabla\\cdot\\vec{B} = 0",
        tags: ["maxwell", "magnetism"],
      },
      {
        name: "Faraday's law (Maxwell form)",
        description: "A time-varying magnetic field creates a curling electric field.",
        keyFact: "$\\nabla\\times\\vec{E} = -\\partial\\vec{B}/\\partial t$; electric fields can exist without charges if $\\vec{B}$ is changing.",
        formula: "\\nabla\\times\\vec{E} = -\\frac{\\partial\\vec{B}}{\\partial t}",
        tags: ["maxwell", "faraday"],
      },
      {
        name: "Ampère-Maxwell law",
        description: "Currents and changing electric fields both create magnetic fields.",
        keyFact: "$\\nabla\\times\\vec{B} = \\mu_0\\vec{J} + \\mu_0\\varepsilon_0\\partial\\vec{E}/\\partial t$; Maxwell's displacement current term completes the symmetry and predicts electromagnetic waves.",
        formula: "\\nabla\\times\\vec{B} = \\mu_0\\vec{J} + \\mu_0\\varepsilon_0\\frac{\\partial\\vec{E}}{\\partial t}",
        tags: ["maxwell", "ampere"],
      },
      {
        name: "Speed of light from Maxwell",
        description: "Maxwell derived the speed of EM waves purely from electric and magnetic constants.",
        keyFact: "$c = 1/\\sqrt{\\mu_0\\varepsilon_0} = 2.998\\times10^8\\,\\mathrm{m/s}$; the same for all EM waves in vacuum — the seed of special relativity.",
        formula: "c = \\frac{1}{\\sqrt{\\mu_0\\varepsilon_0}}",
        tags: ["maxwell", "light"],
      },
      {
        name: "Poynting vector",
        description: "Energy flux density of an electromagnetic field.",
        keyFact: "$\\vec{S} = \\frac{1}{\\mu_0}\\vec{E}\\times\\vec{B}$; direction of energy flow; magnitude equals intensity $I = |\\vec{S}|$.",
        formula: "\\vec{S} = \\frac{1}{\\mu_0}\\vec{E}\\times\\vec{B}",
        tags: ["maxwell", "energy"],
      },
      {
        name: "Electromagnetic field tensor",
        description: "Relativistic unification of $\\vec{E}$ and $\\vec{B}$ into a single antisymmetric tensor $F^{\\mu\\nu}$.",
        keyFact: "All four Maxwell equations condense into $\\partial_\\nu F^{\\mu\\nu} = \\mu_0 J^\\mu$ and the Bianchi identity $\\partial_{[\\alpha}F_{\\beta\\gamma]} = 0$.",
        formula: "\\partial_\\nu F^{\\mu\\nu} = \\mu_0 J^\\mu",
        xref: ["mathematics"],
        tags: ["maxwell", "relativity", "tensor"],
      },
      {
        name: "Gauge invariance",
        description: "Maxwell's equations are unchanged by gauge transformations of the potentials.",
        keyFact: "$\\vec{A}\\to\\vec{A}+\\nabla\\chi$, $\\phi\\to\\phi-\\partial\\chi/\\partial t$ leave $\\vec{E}$ and $\\vec{B}$ invariant. Gauge freedom is fundamental to quantum field theory and underlies the structure of the Standard Model.",
        tags: ["maxwell", "gauge", "QFT"],
      },
    ],
  },

  // ── Family 15 ──────────────────────────────────────────────────────────────
  {
    slug: "electromagnetic-waves",
    number: 15,
    name: "Electromagnetic Waves",
    blurb: "Wave propagation, the EM spectrum, polarization, radiation pressure, and plasma optics.",
    section: "C",
    color: "sky",
    entries: [
      {
        name: "EM wave propagation",
        description: "Coupled oscillating electric and magnetic fields self-sustaining in space.",
        keyFact: "$\\vec{E}$, $\\vec{B}$, and $\\hat{k}$ are mutually perpendicular in a plane wave; $E_0 = cB_0$.",
        formula: "E_0 = cB_0",
        tags: ["EM-waves", "optics"],
      },
      {
        name: "Speed of light",
        description: "The universal speed limit and the speed of all EM radiation in vacuum.",
        keyFact: "$c = 2.998\\times10^8\\,\\mathrm{m/s}$ in vacuum; in a medium, $v = c/n$ where $n \\geq 1$ is the refractive index.",
        formula: "v = \\frac{c}{n}",
        tags: ["EM-waves", "speed-of-light"],
      },
      {
        name: "Electromagnetic spectrum",
        description: "The continuum of EM radiation ordered by frequency or wavelength.",
        keyFact: "Radio $\\to$ microwave $\\to$ IR $\\to$ visible (400–700 nm) $\\to$ UV $\\to$ X-ray $\\to$ gamma; all travel at $c$ in vacuum.",
        tags: ["EM-waves", "spectrum"],
      },
      {
        name: "Polarization",
        description: "The direction of electric field oscillation in a transverse EM wave.",
        keyFact: "Malus's law: $I = I_0\\cos^2\\theta$ for linear polarizer; circular and elliptical polarization also possible.",
        formula: "I = I_0\\cos^2\\theta",
        tags: ["EM-waves", "polarization"],
      },
      {
        name: "Intensity of EM waves",
        description: "Average energy flux — power per unit area.",
        keyFact: "$I = \\frac{1}{2}c\\varepsilon_0 E_0^2$; falls as $1/r^2$ from a point source (inverse-square law).",
        formula: "I = \\frac{1}{2}c\\varepsilon_0 E_0^2",
        tags: ["EM-waves", "intensity"],
      },
      {
        name: "Radiation pressure",
        description: "EM waves carry momentum and exert pressure on surfaces.",
        keyFact: "$P_{rad} = I/c$ for absorbed radiation, $2I/c$ for perfect reflection. Drives solar sails; relevant in stellar interiors.",
        formula: "P_{rad} = \\frac{I}{c}",
        tags: ["EM-waves", "momentum"],
      },
      {
        name: "Cherenkov radiation",
        description: "EM radiation emitted when a charged particle moves faster than light in the medium.",
        keyFact: "$\\cos\\theta_C = c/(nv)$ when $v > c/n$; the characteristic blue glow in nuclear reactor water pools.",
        formula: "\\cos\\theta_C = \\frac{c}{nv}",
        tags: ["EM-waves", "cherenkov"],
      },
      {
        name: "Plasma frequency",
        description: "Natural oscillation frequency of electrons in a plasma.",
        keyFact: "$\\omega_p = \\sqrt{ne^2/(m_e\\varepsilon_0)}$; EM waves with $\\omega < \\omega_p$ cannot propagate (reflected). Explains why the ionosphere reflects AM radio.",
        formula: "\\omega_p = \\sqrt{\\frac{ne^2}{m_e\\varepsilon_0}}",
        tags: ["EM-waves", "plasma"],
      },
    ],
  },

  // ── Family 16 ──────────────────────────────────────────────────────────────
  {
    slug: "geometric-optics",
    number: 16,
    name: "Geometric Optics",
    blurb: "Reflection, refraction, lenses, mirrors, and optical instruments in the ray approximation.",
    section: "C",
    color: "cyan",
    entries: [
      {
        name: "Law of reflection",
        description: "Angle of incidence equals angle of reflection, both measured from the surface normal.",
        keyFact: "$\\theta_i = \\theta_r$; applies to smooth surfaces (specular reflection).",
        formula: "\\theta_i = \\theta_r",
        tags: ["optics", "reflection"],
      },
      {
        name: "Snell's law (refraction)",
        description: "Light bends when crossing between media with different refractive indices.",
        keyFact: "$n_1\\sin\\theta_1 = n_2\\sin\\theta_2$; light bends toward the normal when entering a denser medium ($n$ larger).",
        formula: "n_1\\sin\\theta_1 = n_2\\sin\\theta_2",
        tags: ["optics", "refraction"],
      },
      {
        name: "Total internal reflection",
        description: "Light is entirely reflected when incident above the critical angle at a denser-to-rarer boundary.",
        keyFact: "Critical angle $\\theta_c = \\arcsin(n_2/n_1)$ for $n_1 > n_2$; basis of fiber optic cables.",
        formula: "\\sin\\theta_c = \\frac{n_2}{n_1}",
        tags: ["optics", "TIR", "fiber-optics"],
      },
      {
        name: "Thin lens equation",
        description: "Relates object distance, image distance, and focal length for a thin lens.",
        keyFact: "$1/f = 1/d_o + 1/d_i$; converging (convex) lens $f > 0$, diverging (concave) $f < 0$.",
        formula: "\\frac{1}{f} = \\frac{1}{d_o} + \\frac{1}{d_i}",
        tags: ["optics", "lenses"],
      },
      {
        name: "Magnification",
        description: "Ratio of image size to object size.",
        keyFact: "$m = -d_i/d_o$; negative $m$ indicates an inverted image. $|m| > 1$ means the image is larger than the object.",
        formula: "m = -\\frac{d_i}{d_o}",
        tags: ["optics", "lenses"],
      },
      {
        name: "Spherical mirrors",
        description: "Concave and convex mirrors focus or diverge reflected light.",
        keyFact: "Same equation $1/f = 1/d_o + 1/d_i$ applies; concave mirrors ($f > 0$) focus parallel rays at $f = R/2$.",
        formula: "f = \\frac{R}{2}",
        tags: ["optics", "mirrors"],
      },
      {
        name: "Dispersion",
        description: "Refractive index depends on wavelength; different colors travel at different speeds.",
        keyFact: "Normal dispersion: $n$ larger for shorter $\\lambda$; prisms separate white light; chromatic aberration in lenses.",
        tags: ["optics", "dispersion"],
      },
      {
        name: "Optical instruments",
        description: "Microscopes, telescopes, and cameras built from lens combinations.",
        keyFact: "Compound microscope: $M = m_{obj}\\times m_{eye}$; refracting telescope: $M = -f_{obj}/f_{eye}$.",
        formula: "M = -\\frac{f_{obj}}{f_{eye}}",
        tags: ["optics", "instruments"],
      },
      {
        name: "Numerical aperture & fiber optics",
        description: "Light guidance through total internal reflection in glass fibers.",
        keyFact: "$NA = n\\sin\\theta_{max} = \\sqrt{n_{core}^2 - n_{clad}^2}$; low-loss silica fibers underlie global telecommunications.",
        formula: "NA = \\sqrt{n_1^2 - n_2^2}",
        tags: ["optics", "fiber-optics", "TIR"],
      },
      {
        name: "Aberrations",
        description: "Deviations from ideal imaging due to lens geometry or dispersion.",
        keyFact: "Spherical aberration: rays far from the axis focus at a different point. Chromatic aberration: different wavelengths focus differently. Achromatic doublets compensate chromatic aberration.",
        tags: ["optics", "aberrations"],
      },
    ],
  },
];
