import type { Family } from "./types";

export const FAMILIES_1_8: Family[] = [
  // ── Family 1 ──────────────────────────────────────────────────────────────
  {
    slug: "kinematics",
    number: 1,
    name: "Kinematics",
    blurb: "Describing motion — position, velocity, acceleration — without asking why.",
    section: "A",
    color: "blue",
    entries: [
      {
        name: "Position & displacement",
        description: "The location of an object and how it changes over time.",
        keyFact: "Displacement $\\vec{s} = \\vec{r}_f - \\vec{r}_i$ is a vector; distance is the scalar path length. They are equal only for straight-line motion.",
        tags: ["kinematics", "vectors"],
      },
      {
        name: "Velocity",
        description: "Rate of change of position; a vector quantity.",
        keyFact: "Average velocity $\\bar{v} = \\Delta x / \\Delta t$; instantaneous velocity $v = dx/dt$ is the derivative of position.",
        formula: "v = \\frac{dx}{dt}",
        tags: ["kinematics", "calculus"],
      },
      {
        name: "Acceleration",
        description: "Rate of change of velocity.",
        keyFact: "Average $\\bar{a} = \\Delta v/\\Delta t$; instantaneous $a = dv/dt = d^2x/dt^2$. Uniform acceleration is constant $a$.",
        formula: "a = \\frac{dv}{dt} = \\frac{d^2x}{dt^2}",
        tags: ["kinematics", "calculus"],
      },
      {
        name: "SUVAT equations",
        description: "Five kinematic equations valid for constant acceleration.",
        keyFact: "Link $s$, $u$, $v$, $a$, $t$. Most useful: $v = u + at$, $s = ut + \\frac{1}{2}at^2$, $v^2 = u^2 + 2as$.",
        formula: "v = u + at,\\quad s = ut + \\tfrac{1}{2}at^2,\\quad v^2 = u^2 + 2as",
        example: "A car at rest accelerates at $3\\,\\mathrm{m/s^2}$ for $4\\,\\mathrm{s}$: $v = 12\\,\\mathrm{m/s}$, $s = 24\\,\\mathrm{m}$.",
        tags: ["kinematics", "equations"],
      },
      {
        name: "Free fall",
        description: "Motion under gravity alone, neglecting air resistance.",
        keyFact: "All objects near Earth's surface fall with $g \\approx 9.81\\,\\mathrm{m/s^2}$ regardless of mass — Galileo's insight.",
        formula: "y = y_0 + v_0 t - \\tfrac{1}{2}g t^2",
        example: "Dropped from rest through height $h$: $h = \\frac{1}{2}gt^2$, so $t = \\sqrt{2h/g}$.",
        tags: ["kinematics", "gravity"],
      },
      {
        name: "Projectile motion",
        description: "2D motion under constant downward gravitational acceleration.",
        keyFact: "Horizontal and vertical motions are independent. Range $R = v_0^2 \\sin 2\\theta / g$; maximum range at $\\theta = 45°$.",
        formula: "R = \\frac{v_0^2 \\sin 2\\theta}{g}",
        tags: ["kinematics", "2D"],
      },
      {
        name: "Uniform circular motion",
        description: "Motion at constant speed along a circular path.",
        keyFact: "Centripetal acceleration $a_c = v^2/r = \\omega^2 r$ points toward the center; period $T = 2\\pi r / v$.",
        formula: "a_c = \\frac{v^2}{r} = \\omega^2 r",
        tags: ["kinematics", "circular"],
      },
      {
        name: "Relative motion",
        description: "Velocities and accelerations depend on the reference frame.",
        keyFact: "$\\vec{v}_{AC} = \\vec{v}_{AB} + \\vec{v}_{BC}$; all kinematic quantities are frame-dependent.",
        formula: "\\vec{v}_{AC} = \\vec{v}_{AB} + \\vec{v}_{BC}",
        tags: ["kinematics", "frames"],
      },
      {
        name: "Inertial frames of reference",
        description: "Coordinate systems in which Newton's laws hold without fictitious forces.",
        keyFact: "Inertial frames move at constant velocity relative to each other; the laws of physics take the same form in all of them.",
        tags: ["kinematics", "foundations"],
      },
      {
        name: "Average vs instantaneous quantities",
        description: "The distinction between a quantity over an interval vs at a single moment.",
        keyFact: "Average speed = total distance / total time; instantaneous speed $= |v(t)|$. Only equal if speed is constant.",
        tags: ["kinematics", "calculus"],
      },
    ],
  },

  // ── Family 2 ──────────────────────────────────────────────────────────────
  {
    slug: "newtons-laws",
    number: 2,
    name: "Newton's Laws of Motion",
    blurb: "The three laws that link forces to motion, plus gravity and friction.",
    section: "A",
    color: "sky",
    entries: [
      {
        name: "Newton's First Law (inertia)",
        description: "A body remains at rest or in uniform motion unless acted on by a net force.",
        keyFact: "An isolated body ($\\vec{F}_{net} = 0$) moves in a straight line at constant velocity — this defines an inertial reference frame.",
        tags: ["mechanics", "inertia", "newton"],
      },
      {
        name: "Newton's Second Law",
        description: "Net force equals mass times acceleration.",
        keyFact: "$\\vec{F}_{net} = m\\vec{a}$; equivalently $\\vec{F} = d\\vec{p}/dt$ for variable-mass systems.",
        formula: "\\vec{F}_{net} = m\\vec{a}",
        tags: ["mechanics", "force", "newton"],
      },
      {
        name: "Newton's Third Law",
        description: "Every action has an equal and opposite reaction.",
        keyFact: "Forces come in pairs: $\\vec{F}_{AB} = -\\vec{F}_{BA}$. The two forces act on different bodies and never cancel each other.",
        tags: ["mechanics", "force-pairs", "newton"],
      },
      {
        name: "Inertial vs gravitational mass",
        description: "Two operationally distinct concepts of mass.",
        keyFact: "Inertial mass $m_i$ appears in $F = ma$; gravitational mass $m_g$ in $F = m_g g$. Einstein's equivalence principle states $m_i = m_g$ exactly.",
        tags: ["mechanics", "mass", "equivalence"],
      },
      {
        name: "Universal gravitation",
        description: "Gravitational attraction between any two masses.",
        keyFact: "$F = Gm_1 m_2 / r^2$; $G = 6.674\\times 10^{-11}\\,\\mathrm{N\\,m^2/kg^2}$.",
        formula: "F = \\frac{Gm_1 m_2}{r^2}",
        tags: ["gravity", "newton"],
      },
      {
        name: "Normal force",
        description: "Contact force perpendicular to a surface, preventing penetration.",
        keyFact: "Normal force is a reaction to compression; on a horizontal surface with no vertical acceleration, $N = mg$.",
        tags: ["mechanics", "contact"],
      },
      {
        name: "Friction",
        description: "Resistive contact force opposing relative motion between surfaces.",
        keyFact: "Static friction $f_s \\leq \\mu_s N$; kinetic friction $f_k = \\mu_k N$ with $\\mu_k < \\mu_s$ in general.",
        formula: "f_k = \\mu_k N",
        tags: ["mechanics", "friction"],
      },
      {
        name: "Tension",
        description: "Force transmitted through a string, rope, or cable.",
        keyFact: "For a massless inextensible string, tension is the same throughout; for a massive string it varies along its length.",
        tags: ["mechanics", "contact"],
      },
      {
        name: "Free body diagrams",
        description: "Diagrams showing all forces acting on a single body.",
        keyFact: "Label every force with its source and direction; the net force vector determines acceleration via $\\vec{F}_{net} = m\\vec{a}$.",
        tags: ["mechanics", "problem-solving"],
      },
      {
        name: "Non-inertial frames & pseudo-forces",
        description: "Accelerating frames require fictitious forces to apply Newton's second law.",
        keyFact: "In a frame accelerating at $\\vec{a}_0$, a fictitious force $-m\\vec{a}_0$ acts on every object (e.g., centrifugal and Coriolis forces in a rotating frame).",
        tags: ["mechanics", "frames"],
      },
    ],
  },

  // ── Family 3 ──────────────────────────────────────────────────────────────
  {
    slug: "energy-work",
    number: 3,
    name: "Energy & Work",
    blurb: "Work, kinetic and potential energy, conservation, power, and efficiency.",
    section: "A",
    color: "cyan",
    entries: [
      {
        name: "Work",
        description: "Energy transferred by a force acting through a displacement.",
        keyFact: "$W = \\vec{F}\\cdot\\vec{d} = Fd\\cos\\theta$; measured in joules (J = N·m). Work is a scalar.",
        formula: "W = \\int \\vec{F}\\cdot d\\vec{s}",
        tags: ["energy", "mechanics"],
      },
      {
        name: "Work-energy theorem",
        description: "Net work done on a body equals its change in kinetic energy.",
        keyFact: "$W_{net} = \\Delta KE$. Any force that is perpendicular to motion does no work.",
        formula: "W_{net} = \\Delta KE = \\tfrac{1}{2}mv_f^2 - \\tfrac{1}{2}mv_i^2",
        tags: ["energy", "theorem"],
      },
      {
        name: "Kinetic energy",
        description: "Energy of motion.",
        keyFact: "$KE = \\frac{1}{2}mv^2$; quadruples when speed doubles. The only form of mechanical energy a moving point mass can have.",
        formula: "KE = \\tfrac{1}{2}mv^2",
        tags: ["energy"],
      },
      {
        name: "Gravitational potential energy",
        description: "Energy stored in a gravitational field.",
        keyFact: "Near Earth: $U_g = mgh$; in general $U_g = -GMm/r$. Defined up to an additive constant (only differences matter).",
        formula: "U_g = mgh \\quad\\text{(near surface)}",
        tags: ["energy", "gravity"],
      },
      {
        name: "Elastic potential energy",
        description: "Energy stored in a deformed spring or elastic material.",
        keyFact: "Hooke's law restoring force $F = -kx$; stored energy $U = \\frac{1}{2}kx^2$, where $k$ is the spring constant.",
        formula: "U_{spring} = \\tfrac{1}{2}kx^2",
        tags: ["energy", "springs"],
      },
      {
        name: "Conservation of mechanical energy",
        description: "Total mechanical energy is constant when only conservative forces act.",
        keyFact: "$KE + PE = E_{mech} = \\text{const}$ in the absence of friction or other dissipative forces.",
        formula: "KE + PE = \\text{const}",
        tags: ["energy", "conservation"],
      },
      {
        name: "Conservative vs non-conservative forces",
        description: "Whether the work done depends on the path taken.",
        keyFact: "Conservative forces (gravity, spring) do path-independent work and admit a potential energy. Friction is non-conservative: energy dissipated as heat.",
        tags: ["energy", "forces"],
      },
      {
        name: "Power",
        description: "Rate of energy transfer or work done.",
        keyFact: "$P = W/t = \\vec{F}\\cdot\\vec{v}$; measured in watts (W = J/s).",
        formula: "P = \\frac{dW}{dt} = \\vec{F}\\cdot\\vec{v}",
        tags: ["energy", "power"],
      },
      {
        name: "Energy dissipation",
        description: "Mechanical energy converted to thermal or other forms by non-conservative forces.",
        keyFact: "In a real system, friction converts mechanical energy to heat; total energy (including thermal) is conserved, but mechanical energy is not.",
        tags: ["energy", "thermodynamics"],
      },
      {
        name: "Efficiency",
        description: "Useful output energy as a fraction of total input energy.",
        keyFact: "$\\eta = W_{out}/W_{in} \\leq 1$; always less than 100% in practice due to dissipative losses.",
        formula: "\\eta = \\frac{W_{out}}{W_{in}}",
        tags: ["energy", "engineering"],
      },
    ],
  },

  // ── Family 4 ──────────────────────────────────────────────────────────────
  {
    slug: "momentum-collisions",
    number: 4,
    name: "Momentum & Collisions",
    blurb: "Linear momentum, impulse, conservation, and the anatomy of collisions.",
    section: "A",
    color: "teal",
    entries: [
      {
        name: "Linear momentum",
        description: "The product of mass and velocity; a conserved vector quantity.",
        keyFact: "$\\vec{p} = m\\vec{v}$; Newton's second law is $\\vec{F} = d\\vec{p}/dt$ in its most general form.",
        formula: "\\vec{p} = m\\vec{v}",
        tags: ["momentum", "conservation"],
      },
      {
        name: "Impulse",
        description: "Change in momentum produced by a force over time.",
        keyFact: "$\\vec{J} = \\Delta\\vec{p} = \\int\\vec{F}\\,dt = \\vec{F}_{avg}\\Delta t$; impulse approximation: for a brief collision, neglect other forces.",
        formula: "\\vec{J} = \\Delta\\vec{p} = \\int\\vec{F}\\,dt",
        tags: ["momentum", "impulse"],
      },
      {
        name: "Conservation of momentum",
        description: "Total momentum of an isolated system is constant.",
        keyFact: "When $\\vec{F}_{ext} = 0$, $\\sum m_i\\vec{v}_i = \\text{const}$ before and after any interaction. Holds even when KE is not conserved.",
        formula: "\\vec{F}_{ext} = 0 \\implies \\sum \\vec{p}_i = \\text{const}",
        tags: ["momentum", "conservation"],
      },
      {
        name: "Elastic collision",
        description: "Collision where both momentum and kinetic energy are conserved.",
        keyFact: "In 1D, closed-form solutions exist. For equal masses, velocities exchange. $v_1' = \\frac{m_1-m_2}{m_1+m_2}v_1 + \\frac{2m_2}{m_1+m_2}v_2$.",
        formula: "v_1' = \\frac{m_1-m_2}{m_1+m_2}v_1,\\quad v_2' = \\frac{2m_1}{m_1+m_2}v_1",
        tags: ["collision", "elastic"],
      },
      {
        name: "Inelastic collision",
        description: "Collision where kinetic energy is not conserved (converted to heat, deformation).",
        keyFact: "Momentum is still conserved. Perfectly inelastic: objects stick together. $m_1v_1 + m_2v_2 = (m_1+m_2)v'$.",
        formula: "m_1v_1 + m_2v_2 = (m_1+m_2)v'",
        example: "A bullet embedding in a ballistic pendulum.",
        tags: ["collision", "inelastic"],
      },
      {
        name: "Center of mass",
        description: "The mass-weighted average position of a system of particles.",
        keyFact: "$\\vec{r}_{cm} = \\sum m_i\\vec{r}_i / M_{tot}$; the center of mass of an isolated system moves at constant velocity.",
        formula: "\\vec{r}_{cm} = \\frac{\\sum m_i\\vec{r}_i}{\\sum m_i}",
        tags: ["momentum", "center-of-mass"],
      },
      {
        name: "Rocket propulsion",
        description: "Thrust from mass ejection — the variable-mass problem.",
        keyFact: "Tsiolkovsky rocket equation: $\\Delta v = v_e \\ln(m_0/m_f)$, where $v_e$ is exhaust speed relative to the rocket.",
        formula: "\\Delta v = v_e\\ln\\!\\left(\\frac{m_0}{m_f}\\right)",
        tags: ["momentum", "rockets"],
      },
      {
        name: "Coefficient of restitution",
        description: "Ratio of relative separation speed to relative approach speed in a collision.",
        keyFact: "$e = |v_2' - v_1'|/|v_1 - v_2|$; $e = 1$ elastic, $e = 0$ perfectly inelastic.",
        formula: "e = \\frac{|v_2' - v_1'|}{|v_1 - v_2|}",
        tags: ["collision"],
      },
      {
        name: "2D collisions",
        description: "Collisions in a plane; each component of momentum is conserved separately.",
        keyFact: "In a 2D elastic collision, both $x$- and $y$-momentum plus KE give three equations for four unknowns — one free parameter (e.g., deflection angle).",
        tags: ["collision", "2D"],
      },
      {
        name: "Explosions",
        description: "A single body breaks into pieces — the reverse of a perfectly inelastic collision.",
        keyFact: "Internal forces between fragments conserve total momentum; if the original body is at rest, $\\sum m_i\\vec{v}_i = 0$.",
        tags: ["collision", "conservation"],
      },
    ],
  },

  // ── Family 5 ──────────────────────────────────────────────────────────────
  {
    slug: "rotational-motion",
    number: 5,
    name: "Rotational Motion",
    blurb: "Torque, moment of inertia, angular momentum, and rolling bodies.",
    section: "A",
    color: "emerald",
    entries: [
      {
        name: "Angular kinematics",
        description: "Rotational analogues of displacement, velocity, and acceleration.",
        keyFact: "$\\theta$, $\\omega = d\\theta/dt$, $\\alpha = d\\omega/dt$ mirror $x$, $v$, $a$. Tangential speed $v_t = r\\omega$.",
        formula: "\\omega = \\frac{d\\theta}{dt},\\quad \\alpha = \\frac{d\\omega}{dt}",
        tags: ["rotation", "kinematics"],
      },
      {
        name: "Torque",
        description: "The rotational analogue of force — the moment of a force about an axis.",
        keyFact: "$\\vec{\\tau} = \\vec{r}\\times\\vec{F}$; magnitude $\\tau = rF\\sin\\phi$ where $\\phi$ is the angle between $\\vec{r}$ and $\\vec{F}$.",
        formula: "\\vec{\\tau} = \\vec{r}\\times\\vec{F}",
        tags: ["rotation", "force"],
      },
      {
        name: "Moment of inertia",
        description: "Resistance to rotational acceleration; depends on mass distribution about the axis.",
        keyFact: "$I = \\int r^2\\,dm$. Common values: solid sphere $\\frac{2}{5}MR^2$; hollow sphere $\\frac{2}{3}MR^2$; rod about center $\\frac{1}{12}ML^2$.",
        formula: "I = \\int r^2\\,dm",
        tags: ["rotation", "moment-of-inertia"],
      },
      {
        name: "Newton's second law for rotation",
        description: "Net torque equals moment of inertia times angular acceleration.",
        keyFact: "$\\vec{\\tau}_{net} = I\\vec{\\alpha}$; the direct rotational analogue of $\\vec{F}_{net} = m\\vec{a}$.",
        formula: "\\tau_{net} = I\\alpha",
        tags: ["rotation", "newton"],
      },
      {
        name: "Rotational kinetic energy",
        description: "Kinetic energy of a spinning rigid body.",
        keyFact: "$KE_{rot} = \\frac{1}{2}I\\omega^2$; for a rolling object, total $KE = \\frac{1}{2}mv^2 + \\frac{1}{2}I\\omega^2$.",
        formula: "KE_{rot} = \\tfrac{1}{2}I\\omega^2",
        tags: ["rotation", "energy"],
      },
      {
        name: "Angular momentum",
        description: "The rotational analogue of linear momentum.",
        keyFact: "$\\vec{L} = I\\vec{\\omega}$ for a rigid body; $\\vec{L} = \\vec{r}\\times\\vec{p}$ for a particle. $\\vec{\\tau}_{net} = d\\vec{L}/dt$.",
        formula: "\\vec{L} = I\\vec{\\omega} = \\vec{r}\\times\\vec{p}",
        tags: ["rotation", "angular-momentum"],
      },
      {
        name: "Conservation of angular momentum",
        description: "Angular momentum is constant when net external torque is zero.",
        keyFact: "$\\vec{L} = \\text{const}$ when $\\vec{\\tau}_{ext} = 0$. A spinning skater pulling in their arms speeds up because $I$ decreases while $L$ stays constant.",
        formula: "\\frac{d\\vec{L}}{dt} = \\vec{\\tau}_{net}",
        tags: ["rotation", "conservation"],
      },
      {
        name: "Parallel axis theorem",
        description: "Moment of inertia about any axis in terms of the CM axis.",
        keyFact: "$I = I_{cm} + Md^2$ where $d$ is the perpendicular distance from the center of mass to the new axis.",
        formula: "I = I_{cm} + Md^2",
        tags: ["rotation", "moment-of-inertia"],
      },
      {
        name: "Rolling without slipping",
        description: "Constraint linking linear CM velocity and angular velocity for a rolling object.",
        keyFact: "$v_{cm} = R\\omega$; a rolling object's energy is split between translational ($\\frac{1}{2}mv^2$) and rotational ($\\frac{1}{2}I\\omega^2$) KE.",
        formula: "v_{cm} = R\\omega",
        tags: ["rotation", "rolling"],
      },
      {
        name: "Gyroscopes & precession",
        description: "A spinning gyroscope precesses when a perpendicular torque is applied.",
        keyFact: "Precession rate $\\Omega = \\tau/L = Mgr/(I\\omega)$; the spin axis sweeps out a cone rather than tipping.",
        formula: "\\Omega = \\frac{\\tau}{L}",
        tags: ["rotation", "gyroscope"],
      },
    ],
  },

  // ── Family 6 ──────────────────────────────────────────────────────────────
  {
    slug: "oscillations-waves",
    number: 6,
    name: "Oscillations & Waves",
    blurb: "Simple harmonic motion, resonance, damping, and mechanical wave propagation.",
    section: "A",
    color: "green",
    entries: [
      {
        name: "Simple harmonic motion (SHM)",
        description: "Periodic motion where the restoring force is proportional to displacement.",
        keyFact: "$x(t) = A\\cos(\\omega t + \\phi)$; angular frequency $\\omega = \\sqrt{k/m}$; period $T = 2\\pi/\\omega$.",
        formula: "x(t) = A\\cos(\\omega t + \\phi)",
        tags: ["oscillation", "SHM"],
      },
      {
        name: "Spring-mass system",
        description: "The canonical SHM system: a mass on a spring.",
        keyFact: "Hooke's law restoring force $F = -kx$; natural frequency $\\omega_0 = \\sqrt{k/m}$; period $T = 2\\pi\\sqrt{m/k}$.",
        formula: "T = 2\\pi\\sqrt{\\frac{m}{k}}",
        tags: ["oscillation", "springs"],
      },
      {
        name: "Simple pendulum",
        description: "A mass on a massless string swinging under gravity.",
        keyFact: "For small angles ($\\theta \\ll 1$): $T = 2\\pi\\sqrt{L/g}$, independent of mass and amplitude — Galileo's isochronism.",
        formula: "T = 2\\pi\\sqrt{\\frac{L}{g}}",
        tags: ["oscillation", "pendulum"],
      },
      {
        name: "Damped oscillation",
        description: "Oscillation where amplitude decays due to energy dissipation.",
        keyFact: "Underdamped ($b < 2m\\omega_0$): oscillates with decaying amplitude $A(t) = A_0 e^{-bt/(2m)}$. Critical damping: fastest non-oscillatory return. Overdamped: slow creep.",
        formula: "x(t) = A_0\\,e^{-bt/(2m)}\\cos(\\omega' t + \\phi)",
        tags: ["oscillation", "damping"],
      },
      {
        name: "Resonance",
        description: "Large-amplitude response when the driving frequency matches the natural frequency.",
        keyFact: "In a lightly damped system, amplitude peaks at $\\omega \\approx \\omega_0$; limited by damping. Explains the Tacoma Narrows bridge collapse and MRI.",
        tags: ["oscillation", "resonance"],
      },
      {
        name: "Mechanical waves",
        description: "Periodic disturbances transporting energy through a medium.",
        keyFact: "Wave speed $v = f\\lambda$; transverse waves vibrate perpendicular to propagation (strings), longitudinal waves parallel (sound).",
        formula: "v = f\\lambda",
        tags: ["waves", "mechanics"],
      },
      {
        name: "Wave speed on a string",
        description: "Speed of a transverse wave on a taut string.",
        keyFact: "$v = \\sqrt{T/\\mu}$ where $T$ is tension and $\\mu$ is linear mass density; doubling tension increases speed by $\\sqrt{2}$.",
        formula: "v = \\sqrt{\\frac{T}{\\mu}}",
        tags: ["waves", "strings"],
      },
      {
        name: "Superposition & interference",
        description: "Waves add algebraically when they overlap.",
        keyFact: "Constructive interference (path difference $= n\\lambda$) amplifies; destructive ($= (n+\\tfrac{1}{2})\\lambda$) cancels. Superposition is exact for linear media.",
        tags: ["waves", "interference"],
      },
      {
        name: "Standing waves",
        description: "Fixed-node wave pattern from two counter-propagating waves of equal frequency.",
        keyFact: "String fixed at both ends: $\\lambda_n = 2L/n$, $f_n = nv/(2L)$. Fundamental ($n=1$) plus overtones ($n=2,3,\\ldots$).",
        formula: "f_n = \\frac{nv}{2L}",
        tags: ["waves", "standing"],
      },
      {
        name: "Doppler effect",
        description: "Apparent frequency change when source or observer moves.",
        keyFact: "$f' = f(v\\pm v_o)/(v\\mp v_s)$; higher frequency when approaching. Basis of radar, medical ultrasound, and Doppler meteorology.",
        formula: "f' = f\\frac{v \\pm v_o}{v \\mp v_s}",
        tags: ["waves", "doppler"],
      },
      {
        name: "Sound intensity & decibels",
        description: "Logarithmic scale for sound energy flux.",
        keyFact: "$\\beta = 10\\log_{10}(I/I_0)\\,\\mathrm{dB}$ with reference $I_0 = 10^{-12}\\,\\mathrm{W/m^2}$; every 10 dB corresponds to a factor-10 intensity increase.",
        formula: "\\beta = 10\\log_{10}\\!\\left(\\frac{I}{I_0}\\right)\\,\\mathrm{dB}",
        tags: ["waves", "sound"],
      },
    ],
  },

  // ── Family 7 ──────────────────────────────────────────────────────────────
  {
    slug: "fluid-mechanics",
    number: 7,
    name: "Fluid Mechanics",
    blurb: "Pressure, buoyancy, ideal flow, viscosity, and turbulence.",
    section: "A",
    color: "indigo",
    entries: [
      {
        name: "Pressure",
        description: "Force per unit area; the isotropic stress in a static fluid.",
        keyFact: "$P = F/A$; pressure in a static fluid acts equally in all directions (Pascal). SI unit: pascal (Pa = N/m²); 1 atm = 101.325 kPa.",
        formula: "P = \\frac{F}{A}",
        tags: ["fluids", "pressure"],
      },
      {
        name: "Hydrostatic pressure",
        description: "Pressure at depth in a static fluid.",
        keyFact: "$P = P_0 + \\rho g h$; pressure increases linearly with depth. A 10 m water column adds ~1 atm.",
        formula: "P = P_0 + \\rho g h",
        tags: ["fluids", "hydrostatics"],
      },
      {
        name: "Pascal's principle",
        description: "Pressure applied to a confined fluid is transmitted equally throughout.",
        keyFact: "Hydraulic press: $F_2/F_1 = A_2/A_1$; mechanical advantage from incompressible fluid.",
        formula: "\\frac{F_1}{A_1} = \\frac{F_2}{A_2}",
        tags: ["fluids", "hydraulics"],
      },
      {
        name: "Archimedes' principle",
        description: "A submerged object experiences an upward buoyant force equal to the weight of displaced fluid.",
        keyFact: "$F_b = \\rho_{fluid}\\,V_{sub}\\,g$; an object floats when its average density is less than the fluid.",
        formula: "F_b = \\rho_{fluid}\\,V_{sub}\\,g",
        tags: ["fluids", "buoyancy"],
      },
      {
        name: "Continuity equation",
        description: "Conservation of mass for steady incompressible flow.",
        keyFact: "$A_1 v_1 = A_2 v_2$; fluid speeds up where the pipe narrows. Volume flow rate $Q = Av = \\text{const}$.",
        formula: "A_1 v_1 = A_2 v_2",
        tags: ["fluids", "flow"],
      },
      {
        name: "Bernoulli's equation",
        description: "Conservation of energy along a streamline in inviscid steady flow.",
        keyFact: "$P + \\frac{1}{2}\\rho v^2 + \\rho g h = \\text{const}$; explains airplane lift, the Venturi meter, and the curveball.",
        formula: "P + \\tfrac{1}{2}\\rho v^2 + \\rho g h = \\text{const}",
        tags: ["fluids", "bernoulli"],
      },
      {
        name: "Viscosity",
        description: "Internal friction in a fluid resisting deformation.",
        keyFact: "Shear stress $\\tau = \\eta\\,dv/dy$; dynamic viscosity $\\eta$ in Pa·s. Water at 20°C: $\\eta \\approx 1\\,\\mathrm{mPa\\cdot s}$.",
        formula: "\\tau = \\eta\\frac{dv}{dy}",
        tags: ["fluids", "viscosity"],
      },
      {
        name: "Reynolds number",
        description: "Dimensionless ratio characterizing laminar vs turbulent flow regimes.",
        keyFact: "$Re = \\rho v L/\\eta$; $Re \\lesssim 2300$ typically laminar, $Re \\gtrsim 4000$ turbulent.",
        formula: "Re = \\frac{\\rho v L}{\\eta}",
        tags: ["fluids", "turbulence"],
      },
      {
        name: "Poiseuille flow",
        description: "Laminar viscous flow through a cylindrical pipe.",
        keyFact: "$Q = \\pi R^4\\Delta P/(8\\eta L)$; volume flow is proportional to $R^4$ — halving the radius reduces flow 16-fold.",
        formula: "Q = \\frac{\\pi R^4 \\Delta P}{8\\eta L}",
        tags: ["fluids", "viscosity"],
      },
      {
        name: "Surface tension",
        description: "Cohesive force at a liquid surface that acts to minimize area.",
        keyFact: "$\\gamma = F/L$ in N/m; allows insects to walk on water and drives capillary action. Excess pressure inside a bubble: $\\Delta P = 4\\gamma/r$.",
        formula: "\\gamma = \\frac{F}{L}",
        tags: ["fluids", "surface-tension"],
      },
    ],
  },

  // ── Family 8 ──────────────────────────────────────────────────────────────
  {
    slug: "temperature-heat",
    number: 8,
    name: "Temperature & Heat",
    blurb: "Temperature scales, thermal expansion, specific heat, phase changes, and radiation.",
    section: "B",
    color: "amber",
    entries: [
      {
        name: "Temperature & thermal equilibrium",
        description: "A measure of the average random kinetic energy of particles; the zeroth law establishes it.",
        keyFact: "Kelvin scale: $T_K = T_C + 273.15$; absolute zero (0 K) is the lowest possible temperature. Thermal equilibrium means no net heat flow.",
        formula: "T_K = T_C + 273.15",
        tags: ["thermodynamics", "temperature"],
      },
      {
        name: "Thermal expansion",
        description: "Most materials expand when heated.",
        keyFact: "Linear: $\\Delta L = \\alpha L_0 \\Delta T$; volumetric: $\\Delta V = \\beta V_0 \\Delta T$ with $\\beta \\approx 3\\alpha$ for isotropic solids.",
        formula: "\\Delta L = \\alpha L_0 \\Delta T",
        tags: ["thermodynamics", "thermal-expansion"],
      },
      {
        name: "Heat & internal energy",
        description: "Heat is energy in transit due to a temperature difference; internal energy is stored.",
        keyFact: "Heat $Q$ flows from hot to cold spontaneously. Internal energy $U$ is the total microscopic kinetic + potential energy of a system's particles.",
        tags: ["thermodynamics", "heat"],
      },
      {
        name: "Specific heat capacity",
        description: "Energy required to raise the temperature of 1 kg by 1 K.",
        keyFact: "$Q = mc\\Delta T$; water has $c = 4186\\,\\mathrm{J/(kg\\cdot K)}$ — the highest among common substances, giving it exceptional thermal buffering.",
        formula: "Q = mc\\Delta T",
        tags: ["thermodynamics", "specific-heat"],
      },
      {
        name: "Latent heat",
        description: "Heat absorbed or released during a phase transition at constant temperature.",
        keyFact: "$Q = mL$; water: $L_f = 334\\,\\mathrm{kJ/kg}$ (melting), $L_v = 2.26\\,\\mathrm{MJ/kg}$ (vaporization). Vast energy per kg stored in steam.",
        formula: "Q = mL",
        tags: ["thermodynamics", "phase-transitions"],
      },
      {
        name: "Fourier's law of conduction",
        description: "Heat flows down a temperature gradient in a solid.",
        keyFact: "Heat flux $\\dot{Q}/A = -k\\,dT/dx$; thermal conductivity $k$ in W/(m·K) characterizes material. Metals: $k \\sim 10$–400; air: $k \\approx 0.025$.",
        formula: "\\frac{\\dot{Q}}{A} = -k\\frac{dT}{dx}",
        tags: ["thermodynamics", "conduction"],
      },
      {
        name: "Stefan-Boltzmann law",
        description: "Power radiated by a blackbody per unit area, proportional to $T^4$.",
        keyFact: "$P/A = \\varepsilon\\sigma T^4$; $\\sigma = 5.67\\times 10^{-8}\\,\\mathrm{W/(m^2\\,K^4)}$. Doubling $T$ increases radiated power 16-fold.",
        formula: "P = \\varepsilon\\sigma A T^4",
        tags: ["thermodynamics", "radiation"],
      },
      {
        name: "Wien's displacement law",
        description: "Peak wavelength of blackbody radiation inversely proportional to temperature.",
        keyFact: "$\\lambda_{max}T = 2.898\\times 10^{-3}\\,\\mathrm{m\\cdot K}$; the Sun ($T \\approx 5778\\,\\mathrm{K}$) peaks near 500 nm (green).",
        formula: "\\lambda_{max}\\,T = 2.898\\times10^{-3}\\,\\mathrm{m\\cdot K}",
        tags: ["thermodynamics", "radiation", "quantum"],
      },
      {
        name: "Newton's law of cooling",
        description: "Rate of heat loss proportional to temperature difference with surroundings.",
        keyFact: "$dT/dt = -k(T-T_{env})$; solution is exponential: $T(t) = T_{env} + (T_0 - T_{env})e^{-kt}$.",
        formula: "\\frac{dT}{dt} = -k(T - T_{env})",
        tags: ["thermodynamics", "cooling"],
      },
      {
        name: "Convection",
        description: "Heat transfer by bulk fluid motion.",
        keyFact: "Natural convection: buoyancy-driven (hot air rises); forced convection: fan or pump. Convective heat transfer coefficient $h$: $\\dot{Q} = hA\\Delta T$.",
        formula: "\\dot{Q} = hA\\Delta T",
        tags: ["thermodynamics", "convection"],
      },
    ],
  },
];
