import type { Family } from "./types";

export const FAMILIES_7_12: Family[] = [
  // ── Family 7 ──────────────────────────────────────────────────────────────
  {
    slug: "economic-anthropology",
    number: 7,
    name: "Economic Anthropology",
    blurb: "Production, exchange, and value across cultures and modes of life.",
    section: "B",
    color: "emerald",
    entries: [
      {
        name: "Substantivism vs formalism",
        description: "Are non-market economies analyzable in market terms?",
        keyFact: "Polanyi (The Great Transformation, 1944): the disembedded market is a recent historical anomaly. Formalists (Schneider, LeClair) argued maximization is universal. The 1960s debate ended in stalemate but shaped the field.",
        ethnographer: "Karl Polanyi",
        tags: ["theory", "Polanyi"],
        xref: ["economics"],
        status: "contested",
      },
      {
        name: "Modes of subsistence",
        description: "Foraging, horticulture, pastoralism, agriculture, industrialism.",
        keyFact: "The classic typology indexes calorie source, density, mobility, and political form, but does not determine them. Most contemporary 'foragers' interact with markets, states, and other modes.",
        tags: ["subsistence", "typology"],
      },
      {
        name: "Gift (Mauss)",
        description: "Obligation to give, receive, and reciprocate.",
        keyFact: "Mauss's Essai sur le don (1925): gifts circulate through obligations, not contracts; the object carries the giver. A foundational text linking economy, kinship, and morality.",
        ethnographer: "Marcel Mauss",
        tags: ["gift", "Mauss", "reciprocity"],
        status: "landmark",
      },
      {
        name: "Kula ring",
        description: "Massim-region long-distance exchange of armshells and necklaces.",
        keyFact: "Malinowski's Argonauts of the Western Pacific (1922): soulava and mwali circulate in opposite directions; kula is prestige exchange that piggybacks on gimwali trade. The originating ethnographic case.",
        region: "Trobriands/Massim",
        ethnographer: "Bronisław Malinowski",
        tags: ["kula", "Trobriand"],
        status: "landmark",
      },
      {
        name: "Potlatch",
        description: "Northwest Coast competitive feasts and ostentatious destruction.",
        keyFact: "Among Kwakwaka'wakw, Tlingit, Haida: chiefs validate rank by lavish hosting and destruction of property. Banned by Canada (1885-1951) and US (1880s onward); persistence under prohibition is documented (Boas, Codere).",
        region: "Northwest Coast",
        ethnographer: "Franz Boas",
        tags: ["potlatch", "Boas"],
        xref: ["history"],
      },
      {
        name: "Spheres of exchange (Tiv, Bohannan)",
        description: "Goods restricted to particular exchange spheres.",
        keyFact: "Bohannan (1955): pre-colonial Tiv (Nigeria) circulated subsistence goods, prestige goods (cattle, brass rods, slaves), and rights in dependents in separate spheres. Money's introduction collapsed the spheres — a moral economy story.",
        ethnographer: "Paul Bohannan",
        tags: ["spheres", "Tiv", "Bohannan"],
        xref: ["economics"],
      },
      {
        name: "Original affluent society",
        description: "Sahlins's claim that foragers worked short hours.",
        keyFact: "Stone Age Economics (1972): based on Lee's !Kung work and Australian data, ~3-5 hours of subsistence labor per day. The original framing is criticized (Kaplan 2000) for selecting easy seasons and ignoring food processing.",
        ethnographer: "Marshall Sahlins",
        tags: ["Sahlins", "foragers"],
        status: "contested",
      },
      {
        name: "Substantive labor and surplus",
        description: "Chayanov, Polanyi, and the analytics of non-capitalist production.",
        keyFact: "Chayanov's peasant economy (1924): household producers target consumption needs, not market maximization. Polanyi's reciprocity/redistribution/exchange typology remains the framework for non-market analysis.",
        ethnographer: "Alexander Chayanov",
        tags: ["Chayanov", "peasants"],
        xref: ["economics"],
      },
      {
        name: "Cattle complex / East African pastoralism",
        description: "Cattle as wealth, prestige, ritual, and food.",
        keyFact: "Herskovits's 'East African cattle complex' (1926) — cattle valued beyond consumption — was caricatured but pointed at real multi-valent property. Bohannan, Schneider, and Galaty refined the picture.",
        ethnographer: "Melville Herskovits",
        tags: ["pastoralism", "cattle"],
        xref: ["sociology"],
      },
      {
        name: "Money and commensuration",
        description: "Money makes things comparable that were not.",
        keyFact: "Bloch & Parry (1989), Maurer (2006), Zelizer's earmarking work (1994): money is not a uniform solvent of social distinctions but is itself socially differentiated. Mobile money (M-Pesa) is the contemporary test case.",
        ethnographer: "Bill Maurer",
        tags: ["money", "M-Pesa"],
        xref: ["economics", "sociology"],
      },
      {
        name: "Moral economy",
        description: "Norms governing economic obligation, especially under stress.",
        keyFact: "E.P. Thompson (1971) on the 18th-century English crowd; James Scott's The Moral Economy of the Peasant (1976) on Southeast Asian uprisings: market disruption of subsistence rights produces principled revolt.",
        ethnographer: "James C. Scott",
        tags: ["moral-economy", "Scott"],
        xref: ["history", "economics"],
      },
      {
        name: "Informal economy",
        description: "Unregulated, untaxed economic activity is most of many countries.",
        keyFact: "Hart's 'informal economy' coinage (1973, Ghana) and ILO uptake: 60%+ of employment globally is informal (ILO 2018). Distinct from criminal; intertwined with formal sectors.",
        ethnographer: "Keith Hart",
        tags: ["informal", "Hart"],
        xref: ["economics", "sociology"],
      },
      {
        name: "Development and post-development",
        description: "Anthropology of development industry and its critics.",
        keyFact: "Ferguson's The Anti-Politics Machine (1990) on Lesotho: development reproduces bureaucratic state power even when projects fail. Escobar's post-development critique radicalizes the position.",
        ethnographer: "James Ferguson",
        tags: ["development", "Ferguson"],
        xref: ["economics"],
      },
      {
        name: "Commodity chain ethnography",
        description: "Following objects through global production networks.",
        keyFact: "Mintz's Sweetness and Power (1985), Tsing's Friction (2005) and Mushroom at the End of the World (2015): trace sugar, gold, matsutake from forest/field to consumer. Defined a generation of globalization research.",
        ethnographer: "Anna Tsing",
        tags: ["commodity-chain", "Tsing"],
        xref: ["economics", "history"],
      },
      {
        name: "Reciprocity (Sahlins typology)",
        description: "Generalized, balanced, and negative reciprocity.",
        keyFact: "Sahlins (1965): generalized (close kin, no expectation of return), balanced (clear immediate return), negative (theft, sharp practice). Plots onto kin distance; influential and stylized.",
        ethnographer: "Marshall Sahlins",
        tags: ["reciprocity", "Sahlins"],
      },
      {
        name: "Anthropology of capitalism",
        description: "Ethnography of corporations, markets, finance.",
        keyFact: "Caitlin Zaloom on traders, Karen Ho's Liquidated (2009) on Wall Street, Hertz on Shanghai stock investors: capitalism is not a single thing; localized variants and the cultures of finance are increasingly studied.",
        ethnographer: "Karen Ho",
        tags: ["capitalism", "finance"],
        xref: ["finance", "economics"],
      },
    ],
  },

  // ── Family 8 ──────────────────────────────────────────────────────────────
  {
    slug: "political-anthropology",
    number: 8,
    name: "Political Anthropology",
    blurb: "Power, authority, and political life beyond and within states.",
    section: "B",
    color: "green",
    entries: [
      {
        name: "Band, tribe, chiefdom, state",
        description: "Service's evolutionary typology of political organization.",
        keyFact: "Elman Service (1962): increasing scale and centralization. Useful heuristic, but unilineal evolutionism is rejected; reversals (deurbanization, state collapse) and parallel forms abound.",
        ethnographer: "Elman Service",
        tags: ["typology", "Service"],
        xref: ["governance"],
        status: "revised",
      },
      {
        name: "Stateless / acephalous societies",
        description: "Coordination without central rule.",
        keyFact: "African Political Systems (Fortes & Evans-Pritchard 1940): Nuer, Tallensi, Anuak organized politically by lineage segmentation, age sets, and ritual offices rather than state. James Scott extended this analytically to The Art of Not Being Governed (2009).",
        ethnographer: "Meyer Fortes",
        tags: ["acephalous", "stateless"],
        xref: ["governance"],
      },
      {
        name: "Big man / great man / chief",
        description: "Modes of leadership beyond bureaucratic office.",
        keyFact: "Sahlins (1963): Melanesian 'big man' achieves status through redistribution; Polynesian 'chief' inherits ranked office. Godelier's 'great man' distinguishes ritual specialists. Indexes different paths to political power.",
        ethnographer: "Marshall Sahlins",
        tags: ["big-man", "leadership"],
      },
      {
        name: "State as cultural form",
        description: "Anthropology of how states make themselves seen.",
        keyFact: "Geertz's Negara (1980, Balinese theater state), Mitchell on Egypt, Trouillot on Haiti: the state is performed, materialized, and miscarried. Distinct from political-science institutional analysis.",
        ethnographer: "Clifford Geertz",
        tags: ["state", "performance"],
        xref: ["governance"],
      },
      {
        name: "Bureaucracy ethnographically",
        description: "Forms, queues, files: how the state touches lives.",
        keyFact: "Gupta's Red Tape (2012) on rural India, Hull on Islamabad's files (2012): bureaucratic mediation produces what Foucault called governmentality and what Graeber called 'structural violence' of paperwork.",
        ethnographer: "Akhil Gupta",
        tags: ["bureaucracy", "Gupta"],
        xref: ["governance", "sociology"],
      },
      {
        name: "Resistance (Scott)",
        description: "Weapons of the weak: everyday resistance to domination.",
        keyFact: "Weapons of the Weak (1985) on Malaysian peasants: foot-dragging, sabotage, gossip, and feigned compliance constitute political action available to the powerless. Hidden transcripts (1990) extended the analysis.",
        ethnographer: "James C. Scott",
        tags: ["resistance", "Scott"],
        xref: ["sociology"],
      },
      {
        name: "Hegemony and consent",
        description: "Power that is naturalized, not just imposed.",
        keyFact: "Gramsci's hegemony, taken up by Comaroffs, Roseberry, Hall: the hardest power to see is the one we mistake for the way things are. Underwrites the anthropology of common sense.",
        ethnographer: "Jean Comaroff",
        tags: ["hegemony", "Gramsci"],
        xref: ["philosophy", "ideologies"],
      },
      {
        name: "Citizenship",
        description: "Membership and its ragged edges.",
        keyFact: "Aihwa Ong's 'flexible citizenship' (1999), Holston's Insurgent Citizenship (2008) on São Paulo peripheries: legal citizenship and lived rights are differently distributed. The migrant non-citizen is central to contemporary inquiry.",
        ethnographer: "Aihwa Ong",
        tags: ["citizenship", "Ong"],
        xref: ["governance", "sociology"],
      },
      {
        name: "Violence (anthropology of)",
        description: "Sustained ethnography of war, genocide, and torture.",
        keyFact: "Scheper-Hughes & Bourgois (Violence in War and Peace, 2003), Daniel's Charred Lullabies (Sri Lanka, 1996), Das's Life and Words (Partition, 2007): violence is patterned, gendered, and reproduced through both spectacle and ordinariness.",
        ethnographer: "Veena Das",
        tags: ["violence", "war"],
        xref: ["history", "sociology"],
      },
      {
        name: "Refugees and displacement",
        description: "Forced movement and the politics of asylum.",
        keyFact: "Malkki's Purity and Exile (1995) on Hutu in Tanzania; Agier on humanitarian camps. UNHCR (2023): 117 million forcibly displaced — roughly 1 in 70 humans. Anthropology contests both the 'bare life' framing and humanitarian pieties.",
        ethnographer: "Liisa Malkki",
        tags: ["refugees", "Malkki"],
        xref: ["governance"],
      },
      {
        name: "Sovereignty and Indigenous nations",
        description: "Indigenous polities navigate settler-colonial state forms.",
        keyFact: "Audra Simpson's Mohawk Interruptus (2014) on the Kahnawà:ke politics of refusal; Glen Coulthard's Red Skin, White Masks (2014). Indigenous sovereignty cannot be reduced to ethnic minority politics.",
        ethnographer: "Audra Simpson",
        tags: ["Indigenous", "sovereignty"],
        xref: ["governance", "history"],
      },
      {
        name: "Anthropology of policy",
        description: "Policy as anthropological object, not just instrument.",
        keyFact: "Cris Shore & Susan Wright (1997) framed policy as a domain of cultural production. Followed by ethnographies of UN agencies, EU Brussels, IMF, and central banks.",
        ethnographer: "Cris Shore",
        tags: ["policy"],
        xref: ["governance"],
      },
      {
        name: "Patronage and clientelism",
        description: "Vertical reciprocity in political life.",
        keyFact: "From Mediterranean patron-client studies (Boissevain 1974) to Auyero on Argentine Peronism (Poor People's Politics, 2001): clientelism is not just dysfunction but durable political form embedded in scarcity.",
        ethnographer: "Javier Auyero",
        tags: ["patronage", "clientelism"],
        xref: ["governance", "sociology"],
      },
      {
        name: "Honor, vengeance, feud",
        description: "Self-help justice as social organization.",
        keyFact: "Black-Michaud's Cohesive Force (1975), Chagnon's Yanomami (contested), Boehm's Blood Revenge (1984, Montenegro): feud is institutionalized, balanced, and limited — not chaos.",
        ethnographer: "Christopher Boehm",
        tags: ["feud", "honor"],
        xref: ["history"],
      },
      {
        name: "Corruption ethnographically",
        description: "What 'corruption' means is itself culturally produced.",
        keyFact: "Smith's A Culture of Corruption (Nigeria, 2007), Anders on Malawi: anti-corruption discourse can mask transnational extraction even as it targets local petty graft.",
        ethnographer: "Daniel Jordan Smith",
        tags: ["corruption"],
        xref: ["governance", "economics"],
      },
      {
        name: "Anthropology of democracy",
        description: "Democratic practice as cultural project, not procedural baseline.",
        keyFact: "Paley (2008), Spencer (Sri Lanka), Banerjee (India): elections are ritual as well as instrument; democratic 'transition' rarely fits the textbook script.",
        ethnographer: "Julia Paley",
        tags: ["democracy"],
        xref: ["governance"],
      },
    ],
  },

  // ── Family 9 ──────────────────────────────────────────────────────────────
  {
    slug: "medical-anthropology",
    number: 9,
    name: "Medical Anthropology",
    blurb: "Illness, healing, and biomedicine in cross-cultural perspective.",
    section: "C",
    color: "amber",
    entries: [
      {
        name: "Illness vs disease vs sickness",
        description: "Kleinman's tripartite distinction.",
        keyFact: "Kleinman (1980): disease (biomedical pathology), illness (patient experience), sickness (social process). Lets analysis hold all three together without collapsing them.",
        ethnographer: "Arthur Kleinman",
        tags: ["theory", "Kleinman"],
        xref: ["medicine"],
        status: "landmark",
      },
      {
        name: "Explanatory models",
        description: "Patients and clinicians bring different causal accounts.",
        keyFact: "Kleinman's explanatory-models interview (etiology, onset, course, treatment, prognosis) became a standard cross-cultural clinical tool. Foundational to clinical cultural competence training.",
        ethnographer: "Arthur Kleinman",
        tags: ["explanatory-models"],
        xref: ["medicine"],
      },
      {
        name: "Biomedicine as cultural system",
        description: "Western medicine is itself culturally particular.",
        keyFact: "Lock & Nguyen's Anthropology of Biomedicine (2010), Foucault's clinic genealogy, Good's Medicine, Rationality and Experience (1994): biomedicine has cosmologies, rituals, hierarchies, and silences like any other healing system.",
        ethnographer: "Margaret Lock",
        tags: ["biomedicine", "Lock"],
        xref: ["medicine", "philosophy"],
      },
      {
        name: "Structural violence and health",
        description: "Inequality as etiology.",
        keyFact: "Paul Farmer (Pathologies of Power, 2003) on Haiti TB/HIV: poverty, racism, and political violence are not 'context' for disease but drivers. Foundational to global-health anthropology.",
        ethnographer: "Paul Farmer",
        tags: ["structural-violence", "Farmer"],
        xref: ["medicine", "sociology"],
        status: "landmark",
      },
      {
        name: "Culture-bound syndromes",
        description: "Locally specific illness categories.",
        keyFact: "Susto (Latin America), amok (Malaysia), latah, koro, hwa-byung (Korea), nervios. DSM-5's 'cultural concepts of distress' framing replaces older 'CBS' label. Many supposed CBS-es have biomedical analogues.",
        tags: ["CBS", "cross-cultural"],
        xref: ["psychology", "medicine"],
        status: "revised",
      },
      {
        name: "Ethnomedicine and ethnobotany",
        description: "Local pharmacopoeias and healing traditions.",
        keyFact: "Schultes on Amazonian botany, Etkin on Hausa medicine, MIT's ICBG bioprospecting: ~25% of modern pharmaceuticals derive from plants used by traditional healers. Biopiracy ethics live here.",
        ethnographer: "Richard Schultes",
        tags: ["ethnobotany"],
        xref: ["biology", "medicine"],
      },
      {
        name: "Medical pluralism",
        description: "People use multiple healing systems pragmatically.",
        keyFact: "Leslie's Asian Medical Systems (1976), Crandon-Malamud on Bolivia: patients move between biomedicine, Ayurveda, TCM, Kallawaya, faith healing as makes sense given symptoms, access, and cost.",
        ethnographer: "Charles Leslie",
        tags: ["pluralism"],
        xref: ["medicine"],
      },
      {
        name: "Embodiment",
        description: "Body as both subject and object of cultural process.",
        keyFact: "Csordas's 'somatic modes of attention' (1993), Scheper-Hughes & Lock's 'mindful body' (1987): the body is not separable from the culture that inhabits and is inhabited by it.",
        ethnographer: "Thomas Csordas",
        tags: ["embodiment"],
        xref: ["philosophy", "psychology"],
      },
      {
        name: "Reproductive anthropology",
        description: "Pregnancy, birth, abortion as cultural processes.",
        keyFact: "Davis-Floyd on US obstetrics, Ginsburg & Rapp's Conceiving the New World Order (1995), Inhorn on infertility/IVF in Egypt: reproduction is technological, political, and unequally distributed.",
        ethnographer: "Marcia Inhorn",
        tags: ["reproduction", "IVF"],
        xref: ["medicine", "sociology"],
      },
      {
        name: "Pharmaceuticalization",
        description: "Drugs as cultural objects and policy instruments.",
        keyFact: "Petryna, Lakoff, and Biehl on antiretrovirals, psychiatric drugs, and pharmaceutical trials: drugs travel with markets and trial economies as much as with efficacy. Brazil's universal-ARV story is central.",
        ethnographer: "Joao Biehl",
        tags: ["pharmaceuticals"],
        xref: ["medicine", "economics"],
      },
      {
        name: "Global mental health critique",
        description: "Exporting Western nosology may be iatrogenic.",
        keyFact: "Watters's Crazy Like Us (2010), Summerfield's PTSD critique, Patel's responses: cross-cultural depression and PTSD diagnoses are politically and clinically contested. The 'movement for global mental health' and its critics are both active.",
        ethnographer: "Vikram Patel",
        tags: ["GMH", "mental-health"],
        xref: ["medicine", "psychology"],
        status: "contested",
      },
      {
        name: "Epidemic anthropology",
        description: "Outbreaks as moments where culture and politics surface.",
        keyFact: "Farmer on cholera, Hewlett on Ebola, Lakoff on H1N1, Caduff on H5N1, COVID work since 2020. Trust, kin networks, and burial practices are not 'cultural obstacles' but central infrastructure.",
        ethnographer: "Barry Hewlett",
        tags: ["epidemics", "Ebola", "COVID"],
        xref: ["medicine", "history"],
      },
      {
        name: "Critical medical anthropology",
        description: "Health and illness in political-economic perspective.",
        keyFact: "Singer & Baer's program (1986 onward): medicine is part of political economy; CMA reads health disparities as products of capitalism, racism, and colonial extraction.",
        ethnographer: "Merrill Singer",
        tags: ["CMA"],
        xref: ["medicine"],
      },
      {
        name: "Local biologies",
        description: "Biology is shaped by environment, life history, history.",
        keyFact: "Lock's Encounters with Aging (1993) on Japanese menopause (kōnenki) — symptom profiles and meanings differ from North American menopause. Frames biology and culture as co-constitutive.",
        ethnographer: "Margaret Lock",
        tags: ["local-biologies", "menopause"],
        xref: ["biology", "medicine"],
      },
      {
        name: "Disability anthropology",
        description: "Disability as cultural and political category.",
        keyFact: "Ginsburg & Rapp, Kohrman on disabled Beijingers, Friedner on deaf India: disability sits between medical and social models; intersects with kinship, work, and citizenship.",
        ethnographer: "Faye Ginsburg",
        tags: ["disability"],
        xref: ["sociology", "medicine"],
      },
      {
        name: "Aging and longevity",
        description: "How later life is constructed and experienced.",
        keyFact: "Cohen on Alzheimer's in India, Buch on care work, Lamb on the 'successful aging' discourse: aging is biological and biographical and political. The 'silver tsunami' is reshaping global care work.",
        ethnographer: "Lawrence Cohen",
        tags: ["aging"],
        xref: ["medicine", "sociology"],
      },
    ],
  },

  // ── Family 10 ─────────────────────────────────────────────────────────────
  {
    slug: "evolutionary-anthropology",
    number: 10,
    name: "Evolutionary Anthropology",
    blurb: "Behavior, cognition, and culture in evolutionary perspective.",
    section: "C",
    color: "rose",
    entries: [
      {
        name: "Human behavioral ecology (HBE)",
        description: "Behavior treated as adaptive response to socioecological conditions.",
        keyFact: "Borgerhoff Mulder, Hawkes, Hill, Kaplan applied optimal-foraging and life-history models to Ache, Hadza, Tsimane, Kipsigis. Strong methodological commitment to quantitative fieldwork.",
        ethnographer: "Kristen Hawkes",
        tags: ["HBE", "foraging"],
        xref: ["biology"],
      },
      {
        name: "Evolutionary psychology",
        description: "Mind as suite of evolved domain-specific modules.",
        keyFact: "Cosmides & Tooby (1992 'Adapted Mind') and Buss: modules for cheater detection, mate preference, folk biology. Critiqued for narrow EEA assumptions and weak replication of canonical findings.",
        ethnographer: "Leda Cosmides",
        tags: ["EP", "modularity"],
        xref: ["psychology", "biology"],
        status: "contested",
      },
      {
        name: "Cultural evolution / dual inheritance",
        description: "Genes and culture co-evolve.",
        keyFact: "Cavalli-Sforza & Feldman (1981), Boyd & Richerson (Culture and the Evolutionary Process, 1985), Henrich (The Secret of Our Success, 2015): cumulative culture is a second inheritance system with its own dynamics.",
        ethnographer: "Robert Boyd",
        tags: ["cultural-evolution", "Henrich"],
        xref: ["biology", "psychology"],
      },
      {
        name: "Niche construction",
        description: "Organisms modify selection pressures on themselves and others.",
        keyFact: "Odling-Smee, Laland, Feldman (2003): humans are the niche-constructing species par excellence — fire, agriculture, settlements, cities, antibiotics. Reframes gene-culture co-evolution.",
        ethnographer: "Kevin Laland",
        tags: ["niche-construction"],
        xref: ["biology"],
      },
      {
        name: "Inclusive fitness / kin selection",
        description: "Hamilton's rule explains altruism toward relatives.",
        keyFact: "Hamilton (1964): rB > C; an allele for altruism spreads if relatedness × benefit exceeds cost. Underlies anthropological work on kin networks, paternity certainty, and parental investment.",
        ethnographer: "William Hamilton",
        tags: ["Hamilton", "kin-selection"],
        xref: ["biology"],
        status: "landmark",
      },
      {
        name: "Parental investment and mating",
        description: "Asymmetric investment shapes mating dynamics.",
        keyFact: "Trivers (1972): the higher-investing sex is the limiting resource; the lower-investing sex competes. Robust at species level; cross-cultural human variation in marriage and parenting complicates direct application.",
        ethnographer: "Robert Trivers",
        tags: ["parental-investment", "Trivers"],
        xref: ["biology"],
      },
      {
        name: "Cooperation and free riders",
        description: "Why do humans cooperate with non-kin?",
        keyFact: "Direct reciprocity (Axelrod), indirect reciprocity / reputation (Nowak), group selection (Wilson), strong reciprocity / costly punishment (Fehr-Gintis-Bowles), cultural group selection (Henrich): no single answer, multiple plausible mechanisms.",
        ethnographer: "Samuel Bowles",
        tags: ["cooperation", "free-rider"],
        xref: ["economics", "biology"],
        status: "open",
      },
      {
        name: "WEIRD problem",
        description: "Psychology's subject pool is unrepresentative.",
        keyFact: "Henrich, Heine & Norenzayan (2010): undergraduates from Western, Educated, Industrialized, Rich, Democratic countries are outliers on many measures (Müller-Lyer, fairness, individualism). Wide reach across cognitive and social science.",
        ethnographer: "Joseph Henrich",
        tags: ["WEIRD", "Henrich"],
        xref: ["psychology"],
        status: "landmark",
      },
      {
        name: "Prosociality and norm psychology",
        description: "Cross-cultural experiments on fairness and punishment.",
        keyFact: "The Henrich et al. (2005) Ultimatum Game cross-cultural study: fairness offers vary widely (Machiguenga ~25%, Lamalera whalers ~58%). Punishment of unfair offers also varies. Norms are not universal in the same form.",
        tags: ["Ultimatum", "fairness"],
        xref: ["economics", "psychology"],
      },
      {
        name: "Cognitive niche / cumulative culture",
        description: "Most human knowledge is socially learned, not individually invented.",
        keyFact: "Boyd, Richerson, Henrich: cumulative cultural adaptation (kayaks, click chemistry, calculus) requires social learning fidelity. The Tasmanian effect — loss of complex technology after population collapse — supports the model.",
        ethnographer: "Joseph Henrich",
        tags: ["cumulative-culture", "Tasmanian"],
        xref: ["biology"],
      },
      {
        name: "Theory of mind across cultures",
        description: "False-belief tasks and their cultural shape.",
        keyFact: "Liu, Wellman et al.: false-belief understanding develops on similar timetables in Beijing, Berlin, Tehran, Lima. Persistent differences in adult ToM attributions (Vinden, Lillard) raise reconciling questions.",
        ethnographer: "Henry Wellman",
        tags: ["theory-of-mind"],
        xref: ["psychology"],
      },
      {
        name: "Self-domestication hypothesis",
        description: "Humans selected against reactive aggression.",
        keyFact: "Wrangham (The Goodness Paradox, 2019), Hare: reduced reactive aggression and morphological gracilization parallel domestic-animal syndromes. Tests against fossil and behavioral data ongoing.",
        ethnographer: "Richard Wrangham",
        tags: ["self-domestication"],
        xref: ["biology"],
        status: "contested",
      },
      {
        name: "Language as cultural adaptation",
        description: "Language structure as evolutionary product of cultural transmission.",
        keyFact: "Kirby and Tomasello traditions: language is shaped by learning bottlenecks; Christiansen & Chater (2008): 'language has adapted to brains, not just brains to language.' Generative for typology.",
        ethnographer: "Michael Tomasello",
        tags: ["language-evolution"],
        xref: ["linguistics", "psychology"],
      },
      {
        name: "Demographic regimes and selection",
        description: "Fertility, mortality, and longevity shape evolution.",
        keyFact: "Demographic transition theory and contemporary low-fertility regimes pose evolutionary puzzles: why do humans reduce fertility as resources rise? Wealth-fertility 'paradox' is unresolved.",
        tags: ["demography", "fertility"],
        xref: ["sociology", "economics"],
        status: "open",
      },
      {
        name: "Memes and replicator critique",
        description: "Dawkins's meme and its theoretical fate.",
        keyFact: "Memes-as-replicators (Dawkins 1976; Blackmore 1999) is now generally rejected by cultural-evolution researchers in favor of non-replicator transmission models (Henrich, Mesoudi).",
        ethnographer: "Richard Dawkins",
        tags: ["memes"],
        xref: ["biology"],
        status: "revised",
      },
      {
        name: "Religious cognition and cooperation",
        description: "Big gods and large-scale societies.",
        keyFact: "Norenzayan's Big Gods (2013): moralizing high gods may have scaffolded large-scale cooperation; Whitehouse, Slingerland et al. Seshat project (2019 Nature paper) initially supported this, with subsequent re-analyses revising the timing claims.",
        ethnographer: "Ara Norenzayan",
        tags: ["big-gods", "Seshat"],
        xref: ["psychology", "history"],
        status: "contested",
      },
    ],
  },

  // ── Family 11 ─────────────────────────────────────────────────────────────
  {
    slug: "primatology",
    number: 11,
    name: "Primatology",
    blurb: "Non-human primates as the comparative frame for human evolution.",
    section: "C",
    color: "violet",
    entries: [
      {
        name: "Primate order overview",
        description: "Strepsirrhines, tarsiers, monkeys (NWM, OWM), apes.",
        keyFact: "~520 species recognized (IUCN 2023). Apes split: gibbons (lesser apes) and great apes (orangutans, gorillas, chimpanzees, bonobos, humans). The human-chimp split is ~6-8 Mya based on molecular clocks.",
        tags: ["taxonomy"],
        xref: ["biology"],
      },
      {
        name: "Chimpanzee tool use",
        description: "Jane Goodall's Gombe observation overturned 'man the toolmaker.'",
        keyFact: "Goodall (1960) at Gombe: chimps strip leaves to fish termites. Now documented across communities: stone hammers (Bossou), spear-hunting bushbabies (Fongoli), drinking sticks. Tool traditions vary by community — cultural variation.",
        ethnographer: "Jane Goodall",
        tags: ["chimps", "tools", "Goodall"],
        xref: ["biology"],
        status: "landmark",
      },
      {
        name: "Chimpanzee culture",
        description: "Behavioral variation not explained by genes or environment.",
        keyFact: "Whiten et al. (1999 Nature): 39 behaviors vary across 7 chimp communities — nut-cracking, leaf-clipping, hand-clasp grooming. Cumulative culture is more limited than human, but cultural transmission is real.",
        ethnographer: "Andrew Whiten",
        tags: ["chimp-culture"],
        xref: ["biology"],
      },
      {
        name: "Bonobos vs chimpanzees",
        description: "Sister taxa with strikingly different social structure.",
        keyFact: "Bonobos (Pan paniscus): female-bonded, less aggressive, sexual conflict resolution. Chimps (Pan troglodytes): male-bonded, lethal coalitionary aggression. Both equidistant from humans; neither is the 'right' model alone.",
        ethnographer: "Frans de Waal",
        tags: ["bonobo", "chimp"],
        xref: ["biology"],
      },
      {
        name: "Gorilla and orangutan socioecology",
        description: "Great apes with contrasting social systems.",
        keyFact: "Mountain gorillas: cohesive multi-male/female groups. Western lowland gorillas: dispersed. Sumatran and Bornean orangutans: semi-solitary, with extended mother-offspring units. Critically endangered.",
        ethnographer: "Dian Fossey",
        tags: ["gorilla", "orangutan"],
        xref: ["biology"],
      },
      {
        name: "Coalitional aggression and warfare",
        description: "Chimp lethal raiding has shaped accounts of human conflict.",
        keyFact: "Goodall, Wrangham, Mitani: chimp inter-community lethal raiding kills both adults and infants. The 'chimpanzee model of warfare' (Wrangham 1999) is widely cited; bonobo absence cautions against simple human inference.",
        ethnographer: "Richard Wrangham",
        tags: ["aggression", "warfare"],
        xref: ["biology", "history"],
        status: "contested",
      },
      {
        name: "Sexual selection in primates",
        description: "Body size, dimorphism, and ornament covary with mating system.",
        keyFact: "Multi-male groups (chimps, baboons) → male-male competition and sperm competition (chimp testes are huge). Single-male harems (gorillas) → larger males, smaller testes. Pair-bonded (gibbons) → minimal dimorphism.",
        tags: ["sexual-selection"],
        xref: ["biology"],
      },
      {
        name: "Primate cognition (de Waal, Tomasello)",
        description: "Tool use, deception, theory of mind, fairness.",
        keyFact: "Capuchin coin economy (Brosnan & de Waal 2003) shows fairness-like reactions. Tomasello argues humans have a distinctive 'shared intentionality' not shared with great apes; remains debated.",
        ethnographer: "Frans de Waal",
        tags: ["cognition", "fairness"],
        xref: ["psychology", "biology"],
      },
      {
        name: "Primate language experiments",
        description: "Sign and lexigram studies and their limits.",
        keyFact: "Washoe (Gardner & Gardner 1969, sign), Koko (Patterson, gorilla), Kanzi (Savage-Rumbaugh, bonobo, lexigrams). Significant vocabulary; recursion and reliable grammar absent. Outcomes do not support a clean species break, nor full linguistic competence.",
        ethnographer: "Sue Savage-Rumbaugh",
        tags: ["language", "Kanzi"],
        xref: ["linguistics", "biology"],
        status: "contested",
      },
      {
        name: "Macaque societies",
        description: "Old World monkey models of complex social cognition.",
        keyFact: "Japanese macaque Imo's potato-washing (Koshima, 1953 onward) was the founding 'animal culture' case. Macaque studies inform medical research; the Cayo Santiago colony (since 1938) is a long-term observation site.",
        ethnographer: "Kinji Imanishi",
        tags: ["macaque", "potato-washing"],
        xref: ["biology"],
      },
      {
        name: "Vervet alarm calls",
        description: "Different alarm calls for different predators.",
        keyFact: "Seyfarth, Cheney & Marler (1980): distinct calls for leopard, eagle, snake; infant calls become more specific with age. Foundational for studies of reference and meaning in animal communication.",
        ethnographer: "Robert Seyfarth",
        tags: ["alarm-calls", "communication"],
        xref: ["biology", "linguistics"],
      },
      {
        name: "Baboon sociality and stress",
        description: "Long-term studies of dominance and physiology.",
        keyFact: "Sapolsky's Amboseli baboon work (since 1978) showed subordinate-male glucocorticoid elevation and rank-related health effects. Long-term Amboseli, Moremi, and Mikumi datasets are field-defining.",
        ethnographer: "Robert Sapolsky",
        tags: ["baboon", "Sapolsky", "stress"],
        xref: ["biology", "psychology"],
      },
      {
        name: "Conservation of great apes",
        description: "All great apes are endangered or critically endangered.",
        keyFact: "IUCN: chimpanzees endangered (~170,000-300,000 estimated); bonobos endangered (~15,000-20,000); gorillas critically endangered (mountain ~1,000, western lowland ~316,000 but declining); orangutans critically endangered.",
        tags: ["conservation"],
        xref: ["biology"],
      },
      {
        name: "Primate ethnography",
        description: "Multispecies ethnography of human-monkey-ape relations.",
        keyFact: "Fuentes's 'ethnoprimatology' (2012): monkeys in Bali, Singapore, Brazil are embedded in human politics. Shows the 'natural' chimp is partly a methodological construct.",
        ethnographer: "Agustín Fuentes",
        tags: ["ethnoprimatology"],
        xref: ["biology"],
      },
      {
        name: "Primate phylogeography",
        description: "Genomic reconstruction of primate diversification.",
        keyFact: "Recent multi-species genomes (Kuderna et al. 2023 Science): primate diversification mapped at unprecedented resolution; implications for human evolution baselines and conservation prioritization.",
        tags: ["phylogeography", "genomics"],
        xref: ["biology"],
      },
      {
        name: "Female agency in primate societies",
        description: "Revisionist work on female primate behavior.",
        keyFact: "Hrdy (The Woman That Never Evolved, 1981; Mothers and Others, 2009): female langur infanticide observed, female promiscuity as paternity confusion, allomaternal care as ancestral. Reframed sociobiology.",
        ethnographer: "Sarah Blaffer Hrdy",
        tags: ["Hrdy", "female-primate"],
        xref: ["biology"],
        status: "landmark",
      },
    ],
  },

  // ── Family 12 ─────────────────────────────────────────────────────────────
  {
    slug: "paleoanthropology",
    number: 12,
    name: "Paleoanthropology (Hominins)",
    blurb: "Fossil and genomic record of the human lineage.",
    section: "C",
    color: "indigo",
    entries: [
      {
        name: "Sahelanthropus tchadensis",
        description: "Possible earliest hominin or near-LCA ape.",
        keyFact: "Toumaï skull, Chad, ~7 Mya. Foramen magnum position suggests upright posture; some critics argue it is a Miocene ape. Postcranial femoral fragments still debated. Hominin status not unanimous.",
        date: "c. 7 Mya",
        region: "Chad",
        tags: ["Sahelanthropus", "Toumaï"],
        status: "contested",
      },
      {
        name: "Ardipithecus ramidus",
        description: "Early hominin with a near-complete skeleton.",
        keyFact: "Ardi, Aramis (Ethiopia), 4.4 Mya, published 2009 after 17 years of preparation. Mosaic features: arboreal grasping foot, bipedal pelvis. Reframes the human-chimp last common ancestor.",
        date: "c. 4.4 Mya",
        region: "Ethiopia",
        ethnographer: "Tim White",
        tags: ["Ardipithecus", "Ardi"],
        status: "landmark",
      },
      {
        name: "Australopithecus afarensis",
        description: "Best-known australopith, Lucy's species.",
        keyFact: "Hadar, Ethiopia, ~3.9-2.9 Mya. AL 288-1 ('Lucy,' 1974) and the Laetoli footprints (~3.66 Mya, Tanzania) establish habitual bipedalism well before brain expansion. Brain ~380-430 cc.",
        date: "c. 3.9 – 2.9 Mya",
        region: "East Africa",
        ethnographer: "Donald Johanson",
        tags: ["Australopithecus", "Lucy", "Laetoli"],
        status: "landmark",
      },
      {
        name: "Australopithecus africanus",
        description: "South African gracile australopith.",
        keyFact: "Taung Child (Dart 1925), Sterkfontein. Brain ~440 cc. Dart's claim was resisted for decades by the 'Piltdown-dominated' British establishment; Sterkfontein remains active and yields many specimens.",
        date: "c. 3.3 – 2.1 Mya",
        region: "South Africa",
        ethnographer: "Raymond Dart",
        tags: ["Taung", "Dart"],
      },
      {
        name: "Paranthropus (robust australopiths)",
        description: "Megadont chewing specialists.",
        keyFact: "P. aethiopicus, boisei, robustus, ~2.7-1.2 Mya. Massive jaws and sagittal crests; isotopes suggest C₄-plant-heavy diet (sedges and tropical grasses). A side-branch alongside genus Homo, not ancestral.",
        date: "c. 2.7 – 1.2 Mya",
        region: "East and South Africa",
        tags: ["Paranthropus", "robust"],
      },
      {
        name: "Australopithecus sediba",
        description: "Malapa hominin with Homo-like features.",
        keyFact: "Malapa, South Africa, ~1.98 Mya. Berger (2010): a mosaic with australopith and Homo traits; proposed by some as ancestral to Homo, contested by others on the basis of date and morphology.",
        date: "c. 1.98 Mya",
        region: "South Africa",
        ethnographer: "Lee Berger",
        tags: ["sediba", "Malapa"],
        status: "contested",
      },
      {
        name: "Homo habilis",
        description: "Earliest commonly accepted Homo.",
        keyFact: "Olduvai Gorge, ~2.4-1.4 Mya, brain ~600-700 cc. Associated with Oldowan tools. 'Habilis' as a single coherent species is debated; some specimens may belong with Australopithecus.",
        date: "c. 2.4 – 1.4 Mya",
        region: "East Africa",
        ethnographer: "Louis Leakey",
        tags: ["habilis", "Olduvai", "Leakey"],
        status: "contested",
      },
      {
        name: "Homo erectus",
        description: "First long-lived, wide-ranging hominin.",
        keyFact: "~1.9 Mya to ~110 ka (Solo, Java). Africa, Europe, Asia. Acheulean handaxes from ~1.7 Mya; controlled fire by ~400 ka (some claims earlier). Brain ~600-1100 cc grew over its span.",
        date: "c. 1.9 Mya – 110 ka",
        region: "Africa, Eurasia",
        tags: ["erectus", "Acheulean"],
        xref: ["history"],
        status: "landmark",
      },
      {
        name: "Dmanisi hominins",
        description: "Earliest hominins outside Africa.",
        keyFact: "Dmanisi, Georgia, ~1.85-1.77 Mya. Variation within a single population is so great that some 'African' species may be over-split. Suggests early Homo dispersal predated full erectus morphology.",
        date: "c. 1.85 – 1.77 Mya",
        region: "Caucasus",
        tags: ["Dmanisi"],
        status: "landmark",
      },
      {
        name: "Homo heidelbergensis / antecessor",
        description: "Middle Pleistocene archaic Homo.",
        keyFact: "Eurasia and Africa, ~700-200 ka. Brain ~1100-1400 cc. Possibly ancestral to Neanderthals (in Europe), Denisovans (Asia), and modern humans (Africa). Taxonomy in flux.",
        date: "c. 700 – 200 ka",
        region: "Africa, Eurasia",
        tags: ["heidelbergensis"],
        status: "contested",
      },
      {
        name: "Homo neanderthalensis",
        description: "Robust archaic humans of Ice Age Eurasia.",
        keyFact: "~400-40 ka. Brain ~1200-1750 cc (larger than ours on average). Symbolic behavior (engravings, ornaments, burials with possible grave goods) is increasingly accepted. Hardy et al. (2020) on cordage/string from Abri du Maras.",
        date: "c. 400 – 40 ka",
        region: "Eurasia",
        tags: ["Neanderthal"],
        xref: ["history", "biology"],
        status: "revised",
      },
      {
        name: "Denisovans",
        description: "Eastern archaic humans known mostly from DNA.",
        keyFact: "Identified 2010 from a Denisova Cave finger bone (~70 ka). Genome shows interbreeding with H. sapiens (~3-6% in Melanesians/Papuans). Now also from Tibet (Baishiya) and possibly Penghu jaw. Few diagnostic fossils.",
        date: "c. 200 – 50 ka",
        region: "Asia",
        ethnographer: "Svante Pääbo",
        tags: ["Denisovan", "Pääbo"],
        xref: ["biology"],
        status: "landmark",
      },
      {
        name: "Homo floresiensis",
        description: "Insular dwarf hominin of Flores.",
        keyFact: "Liang Bua, Indonesia. ~190-50 ka revised dates. ~1 m tall, brain ~420 cc. Tool use, fire. Initial 'sick H. sapiens' hypothesis (microcephaly) has been rejected by independent morphological and dating work.",
        date: "c. 190 – 50 ka",
        region: "Flores, Indonesia",
        tags: ["Hobbit", "Flores"],
        status: "landmark",
      },
      {
        name: "Homo luzonensis",
        description: "Another insular hominin in island Southeast Asia.",
        keyFact: "Callao Cave, Luzon, ~50-67 ka. Mosaic foot/hand morphology resembling both H. erectus and Australopithecus. Reinforces the picture of Asian hominin diversity erased by the 'erectus / sapiens' framing.",
        date: "c. 67 – 50 ka",
        region: "Philippines",
        ethnographer: "Florent Détroit",
        tags: ["luzonensis"],
      },
      {
        name: "Homo naledi",
        description: "Late-surviving small-brained hominin in southern Africa.",
        keyFact: "Rising Star Cave, South Africa, 335-236 ka. Brain ~500 cc. Berger team's funerary-cave claim (2017, 2023) is contested; mortuary use is debated. Surprisingly recent given morphology.",
        date: "c. 335 – 236 ka",
        region: "South Africa",
        ethnographer: "Lee Berger",
        tags: ["naledi", "Rising-Star"],
        status: "contested",
      },
      {
        name: "Homo sapiens — origin and dispersal",
        description: "Anatomically modern humans from Africa to global occupation.",
        keyFact: "Jebel Irhoud, Morocco: H. sapiens-like cranium ~315 ka (Hublin 2017). Multiple African origins / pan-African network model (Scerri et al. 2018). Major Out-of-Africa dispersal ~60-50 ka, with earlier excursions. Sahul reached by ~65 ka.",
        date: "c. 315 ka – present",
        region: "global",
        tags: ["sapiens", "Jebel-Irhoud"],
        xref: ["history", "biology"],
        status: "revised",
      },
      {
        name: "Peopling of the Americas",
        description: "Sapiens reached the Americas late, by uncertain routes.",
        keyFact: "Pre-Clovis sites (Monte Verde ~14.5 ka, Bluefish Caves ~24 ka contested, White Sands footprints ~21-23 ka contested) push earliest occupation back. Genetic data support diverse founder lineages. Routes: ice-free corridor and/or coastal kelp highway.",
        date: "c. 23 – 14 ka",
        region: "Americas",
        tags: ["Clovis", "White-Sands"],
        xref: ["history"],
        status: "open",
      },
    ],
  },
];
