import type { HomininSpecies, HomininClade } from "./types";

// Endocranial-volume ranges (cc) are species-typical means or midpoints.
// Date ranges are first/last appearance dates (Mya). 0 = extant.
// Sources: standard paleoanthropology review literature (Wood, Stringer,
// Hublin, Berger, Reich); dates rounded to two significant figures.

export const HOMININS: HomininSpecies[] = [
  {
    name: "Sahelanthropus tchadensis",
    common: "Toumaï",
    clade: "other",
    startMya: 7.2,
    endMya: 6.8,
    brainCC: 360,
    region: "Chad",
    keySite: "Toros-Menalla",
    note: "Possible earliest hominin; bipedalism inferred from foramen magnum.",
    contested: true,
  },
  {
    name: "Orrorin tugenensis",
    clade: "other",
    startMya: 6.1,
    endMya: 5.7,
    brainCC: undefined,
    region: "Kenya",
    keySite: "Tugen Hills",
    note: "Femoral morphology suggests bipedalism.",
    contested: true,
  },
  {
    name: "Ardipithecus kadabba",
    clade: "australopith",
    startMya: 5.8,
    endMya: 5.2,
    brainCC: undefined,
    region: "Ethiopia",
    keySite: "Middle Awash",
    note: "Late Miocene hominin with ape-like canine.",
  },
  {
    name: "Ardipithecus ramidus",
    common: "Ardi",
    clade: "australopith",
    startMya: 4.4,
    endMya: 4.4,
    brainCC: 350,
    region: "Ethiopia",
    keySite: "Aramis",
    note: "Near-complete skeleton; bipedal pelvis, grasping foot.",
  },
  {
    name: "Australopithecus anamensis",
    clade: "australopith",
    startMya: 4.2,
    endMya: 3.8,
    brainCC: 370,
    region: "Kenya/Ethiopia",
    keySite: "Kanapoi",
    note: "Earliest unambiguous Australopithecus; ancestral to afarensis.",
  },
  {
    name: "Australopithecus afarensis",
    common: "Lucy",
    clade: "australopith",
    startMya: 3.9,
    endMya: 2.9,
    brainCC: 420,
    region: "East Africa",
    keySite: "Hadar / Laetoli",
    note: "Habitual bipedalism; Laetoli footprints 3.66 Mya.",
  },
  {
    name: "Australopithecus africanus",
    common: "Taung Child",
    clade: "australopith",
    startMya: 3.3,
    endMya: 2.1,
    brainCC: 460,
    region: "South Africa",
    keySite: "Taung / Sterkfontein",
    note: "Dart 1925; ended the 'big-brain-first' hypothesis.",
  },
  {
    name: "Australopithecus sediba",
    clade: "australopith",
    startMya: 1.98,
    endMya: 1.98,
    brainCC: 420,
    region: "South Africa",
    keySite: "Malapa",
    note: "Mosaic of australopith and Homo traits.",
    contested: true,
  },
  {
    name: "Paranthropus aethiopicus",
    clade: "australopith",
    startMya: 2.7,
    endMya: 2.3,
    brainCC: 410,
    region: "East Africa",
    keySite: "West Turkana",
    note: "Megadont robust australopith; 'Black Skull.'",
  },
  {
    name: "Paranthropus boisei",
    common: "Nutcracker Man",
    clade: "australopith",
    startMya: 2.3,
    endMya: 1.2,
    brainCC: 510,
    region: "East Africa",
    keySite: "Olduvai",
    note: "Hyper-megadont; C₄-rich diet from isotopes.",
  },
  {
    name: "Paranthropus robustus",
    clade: "australopith",
    startMya: 2.0,
    endMya: 1.2,
    brainCC: 520,
    region: "South Africa",
    keySite: "Swartkrans",
    note: "Robust South African Paranthropus; sympatric with early Homo.",
  },
  {
    name: "Homo habilis",
    clade: "early-homo",
    startMya: 2.4,
    endMya: 1.4,
    brainCC: 650,
    region: "East Africa",
    keySite: "Olduvai",
    note: "Associated with Oldowan tools; species coherence debated.",
    contested: true,
  },
  {
    name: "Homo rudolfensis",
    clade: "early-homo",
    startMya: 2.4,
    endMya: 1.8,
    brainCC: 750,
    region: "East Africa",
    keySite: "Koobi Fora",
    note: "Larger-faced early Homo; sometimes lumped with habilis.",
    contested: true,
  },
  {
    name: "Homo ergaster",
    clade: "erectine",
    startMya: 1.9,
    endMya: 1.4,
    brainCC: 850,
    region: "Africa",
    keySite: "Nariokotome",
    note: "African early erectine; KNM-WT 15000 (Turkana Boy).",
  },
  {
    name: "Homo erectus",
    clade: "erectine",
    startMya: 1.9,
    endMya: 0.11,
    brainCC: 950,
    region: "Africa, Eurasia",
    keySite: "Trinil / Zhoukoudian",
    note: "Longest-lived hominin; Acheulean tools; controlled fire by ~400 ka.",
  },
  {
    name: "Homo georgicus (Dmanisi)",
    clade: "erectine",
    startMya: 1.85,
    endMya: 1.77,
    brainCC: 680,
    region: "Caucasus",
    keySite: "Dmanisi",
    note: "Earliest hominin outside Africa; high within-population variation.",
  },
  {
    name: "Homo antecessor",
    clade: "archaic-sapiens",
    startMya: 1.2,
    endMya: 0.8,
    brainCC: 1000,
    region: "Iberia",
    keySite: "Atapuerca (Gran Dolina)",
    note: "Possibly close to common ancestor of Neanderthals and sapiens.",
    contested: true,
  },
  {
    name: "Homo heidelbergensis",
    clade: "archaic-sapiens",
    startMya: 0.7,
    endMya: 0.2,
    brainCC: 1250,
    region: "Africa, Europe",
    keySite: "Mauer / Bodo / Kabwe",
    note: "Middle Pleistocene archaic Homo; taxonomy in flux.",
    contested: true,
  },
  {
    name: "Homo naledi",
    clade: "archaic-sapiens",
    startMya: 0.335,
    endMya: 0.236,
    brainCC: 500,
    region: "South Africa",
    keySite: "Rising Star",
    note: "Surprisingly recent small-brained hominin; mortuary use disputed.",
    contested: true,
  },
  {
    name: "Homo neanderthalensis",
    common: "Neanderthal",
    clade: "archaic-sapiens",
    startMya: 0.4,
    endMya: 0.04,
    brainCC: 1450,
    region: "Eurasia",
    keySite: "Neander Valley",
    note: "Interbred with sapiens; symbolic behavior increasingly accepted.",
  },
  {
    name: "Denisovans",
    clade: "archaic-sapiens",
    startMya: 0.2,
    endMya: 0.05,
    brainCC: 1400,
    region: "Asia",
    keySite: "Denisova / Baishiya",
    note: "Identified mostly from DNA; introgressed into Melanesian sapiens.",
  },
  {
    name: "Homo floresiensis",
    common: "Hobbit",
    clade: "other",
    startMya: 0.19,
    endMya: 0.05,
    brainCC: 420,
    region: "Flores, Indonesia",
    keySite: "Liang Bua",
    note: "Insular dwarf; not microcephalic sapiens.",
  },
  {
    name: "Homo luzonensis",
    clade: "other",
    startMya: 0.067,
    endMya: 0.05,
    brainCC: undefined,
    region: "Philippines",
    keySite: "Callao Cave",
    note: "Mosaic foot/hand morphology; Philippine insular hominin.",
  },
  {
    name: "Homo sapiens",
    common: "us",
    clade: "sapiens",
    startMya: 0.315,
    endMya: 0,
    brainCC: 1350,
    region: "global",
    keySite: "Jebel Irhoud / Omo Kibish",
    note: "Anatomically modern from ~315 ka; global by ~15 ka.",
  },
];

export const CLADE_INFO: Record<
  HomininClade,
  { label: string; color: string; border: string; text: string }
> = {
  australopith:   { label: "Australopiths",   color: "#a78bfa33", border: "#7c3aed", text: "#ddd6fe" },
  "early-homo":   { label: "Early Homo",      color: "#60a5fa33", border: "#2563eb", text: "#bfdbfe" },
  erectine:       { label: "Erectines",       color: "#22d3ee33", border: "#0891b2", text: "#a5f3fc" },
  "archaic-sapiens": { label: "Archaic Homo", color: "#34d39933", border: "#059669", text: "#a7f3d0" },
  sapiens:        { label: "H. sapiens",      color: "#fbbf2433", border: "#d97706", text: "#fde68a" },
  other:          { label: "Other / debated", color: "#f472b633", border: "#db2777", text: "#fbcfe8" },
};

// Time axis: present (0 Mya, x=right) to 8 Mya (x=left). Log-ish? Linear is fine.
export const TIMELINE_MAX_MYA = 7.5;
