import { neon } from "@neondatabase/serverless";
import { readFileSync } from "fs";
const env = readFileSync(".env.local", "utf8");
const url = env.match(/^DATABASE_URL=["']?([^"'\n]+)/m)[1];
const sql = neon(url);
const fb = await sql`SELECT "submittedAt","pageContext",email,body FROM "Feedback" ORDER BY "submittedAt" DESC`;
console.log("=== FEEDBACK:", fb.length);
for (const f of fb) console.log(`[${f.submittedAt.toISOString().slice(0,10)}] page=${f.pageContext ?? "-"} email=${f.email ?? "-"} :: ${f.body.slice(0,250).replace(/\n/g," ")}`);
const subs = await sql`SELECT "createdAt",email,"topicLabel",confirmed,"lastAlertAt" FROM "TopicSubscription" ORDER BY "createdAt" DESC`;
console.log("\n=== TOPIC SUBSCRIPTIONS:", subs.length);
for (const s of subs) console.log(`[${s.createdAt.toISOString().slice(0,10)}] ${s.email} -> "${s.topicLabel}" confirmed=${s.confirmed}`);
const wt = await sql`SELECT "createdAt",label,keyword FROM "WatchedTopic" ORDER BY "createdAt" DESC`;
console.log("\n=== WATCHED TOPICS:", wt.length);
for (const w of wt) console.log(`[${w.createdAt.toISOString().slice(0,10)}] ${w.label} (${w.keyword})`);
const prof = await sql`SELECT count(*)::int AS c FROM "Profile"`;
const bm = await sql`SELECT "profileId", count(*)::int AS n, min("createdAt") AS first, max("createdAt") AS last FROM "Bookmark" GROUP BY "profileId" ORDER BY n DESC`;
console.log("\n=== PROFILES:", prof[0].c, "| profiles with bookmarks:", bm.length);
for (const b of bm) console.log(`profile ${b.profileId.slice(0,8)}… : ${b.n} bookmarks (${b.first.toISOString().slice(0,10)} → ${b.last.toISOString().slice(0,10)})`);
