export type Tradition = {
  name: string;
  description: string;
  tags: string[];
  tenet: string;
  lineage: { parents: string[]; divergence: string; contested?: boolean };
  figures: string[];
  era: string[];
  coreTenets: string[];
  keyThinkers: string[];
  historicalInstances?: string[];
  principalCritiques: string[];
  adherents?: string;
  broadFamily?: boolean;
  flagged?: boolean;
};

export type Family = {
  slug: string;
  name: string;
  blurb: string;
  color: string;
  traditions: Tradition[];
  broadFamily?: boolean;
};

// ── FAMILY 1: JUDAISM & ITS MOVEMENTS ───────────────────────────────────────

const JUDAISM_FAMILY: Family = {
  slug: "judaism",
  name: "Judaism & Its Movements",
  blurb: "Covenant, Torah, and the interpretive tradition from Second Temple through modern movements.",
  color: "blue",
  broadFamily: true,
  traditions: [
    {
      name: "Judaism",
      description: "Monotheistic covenant religion centered on Torah, commandments (mitzvot), and the relationship between God and the people of Israel.",
      tags: ["ancient", "monotheism", "covenant"],
      tenet: "In Jewish teaching, God entered into a covenant with the people of Israel, giving them the Torah as a guide for righteous living.",
      lineage: { parents: [], divergence: "root — ancient Israelite religion as understood through the Hebrew Bible and rabbinic tradition" },
      figures: ["Abraham (patriarch)", "Moses", "King David"],
      era: ["ancient"],
      adherents: "~14-15M (est.)",
      coreTenets: [
        "According to Jewish belief, there is one God who created and sustains the universe and chose the people of Israel for a covenantal relationship.",
        "The Torah (Written and Oral) provides the framework of 613 commandments (mitzvot) that guide Jewish life.",
        "Jewish tradition holds that study, prayer, and ethical conduct constitute the primary modes of serving God.",
      ],
      keyThinkers: ["Hebrew Bible (Tanakh)", "Mishnah and Talmud (rabbinic literature)"],
      principalCritiques: [
        "Biblical scholars debate the historical accuracy of the patriarchal narratives and the Exodus account; maximalist and minimalist positions remain unresolved.",
        "The concept of chosenness has been interpreted variously as election to responsibility (Rosenzweig), not superiority, though critics note its potential for exclusivism.",
      ],
      broadFamily: true,
    },
    {
      name: "Second-Temple Judaism",
      description: "The diverse landscape of Jewish belief and practice between the rebuilding of the Temple (c. 516 BCE) and its destruction (70 CE).",
      tags: ["ancient", "c6bce-c1ce"],
      tenet: "During the Second Temple period, multiple Jewish groups — Pharisees, Sadducees, Essenes, Zealots — competed over the correct interpretation of Torah and Temple practice.",
      lineage: { parents: ["Judaism"], divergence: "historical period; the matrix from which rabbinic Judaism, Christianity, and other movements emerged" },
      figures: ["Hillel the Elder", "Shammai", "Judah Maccabee"],
      era: ["ancient"],
      coreTenets: [
        "Temple worship in Jerusalem served as the center of Israelite religious life, alongside emerging synagogue traditions.",
        "Sectarian diversity flourished: Pharisees emphasized oral Torah, Sadducees the written text, Essenes purity and withdrawal.",
        "Apocalyptic and messianic expectations shaped many Second Temple Jewish communities.",
      ],
      keyThinkers: ["Dead Sea Scrolls (Qumran community)", "Josephus — Jewish Antiquities", "Philo of Alexandria"],
      principalCritiques: [
        "Scholars debate the degree of sectarian division versus shared common Judaism (E.P. Sanders) in this period.",
        "The reconstruction of specific sects depends heavily on sources (Josephus, Qumran texts) whose reliability and representativeness are debated.",
      ],
    },
    {
      name: "Rabbinic Judaism",
      description: "The normative form of Judaism that emerged after the Temple's destruction (70 CE), centered on the Oral Torah as codified in Mishnah and Talmud.",
      tags: ["ancient", "medieval", "oral-torah"],
      tenet: "Rabbinic tradition holds that God gave Moses both a Written Torah and an Oral Torah at Sinai; the Oral Torah, transmitted through the rabbis, is the authoritative interpretive framework.",
      lineage: { parents: ["Second-Temple Judaism"], divergence: "post-70 CE; the Pharisaic tradition's emphasis on oral Torah and synagogue worship became normative after the Temple's destruction" },
      figures: ["Rabbi Akiva", "Rabbi Judah ha-Nasi (editor of the Mishnah)", "Rav Ashi (editor of the Babylonian Talmud)"],
      era: ["ancient", "medieval"],
      coreTenets: [
        "The Oral Torah — Mishnah, Talmud, and subsequent rabbinic literature — provides the authoritative interpretation of biblical law.",
        "Halakhah (Jewish law) governs all aspects of daily life, from prayer and dietary laws to civil and criminal matters.",
        "The rabbi replaced the priest as the central religious authority after the destruction of the Temple.",
      ],
      keyThinkers: ["Mishnah (c. 200 CE)", "Babylonian Talmud (c. 500 CE)", "Maimonides — Mishneh Torah"],
      principalCritiques: [
        "Critical historians view rabbinic Judaism as one of several possible post-Temple developments rather than the inevitable continuation of biblical religion.",
        "The Karaite movement (see below) rejected the authority of the Oral Torah entirely, arguing it was a rabbinic innovation.",
      ],
    },
    {
      name: "Orthodox Judaism",
      description: "The branch of Judaism that maintains strict adherence to halakhah (Jewish law) as codified in the Shulchan Arukh and interpreted by rabbinic authorities.",
      tags: ["modern", "halakhah"],
      tenet: "Orthodox Jews hold that the Torah — both Written and Oral — is divinely revealed and that halakhah is binding in its traditional form.",
      lineage: { parents: ["Rabbinic Judaism"], divergence: "emerged as a self-conscious identity in response to Enlightenment-era Reform; insists on the binding nature of traditional halakhah" },
      figures: ["Rabbi Samson Raphael Hirsch (Modern Orthodox)", "the Vilna Gaon", "Rabbi Moses Sofer (Chatam Sofer)"],
      era: ["c19", "c20", "c21"],
      coreTenets: [
        "The Torah is the divinely revealed word of God; its commandments are eternally binding.",
        "Halakhah as interpreted by qualified rabbinic authorities governs all aspects of Jewish life.",
        "Engagement with modernity is acceptable (Modern Orthodox) or to be limited (Haredi), but Torah authority is non-negotiable.",
      ],
      keyThinkers: ["Rabbi Joseph B. Soloveitchik — Halakhic Man", "Rabbi Samson Raphael Hirsch — Nineteen Letters"],
      principalCritiques: [
        "Reform and Conservative critics argue that Orthodox insistence on halakhic immutability ignores the historical evolution of Jewish law documented by scholars like Jacob Neusner.",
        "Feminist scholars critique the gendered structure of traditional halakhah, including women's exclusion from certain religious roles.",
      ],
    },
    {
      name: "Hasidism",
      description: "A mystical-pietist movement within Orthodox Judaism emphasizing joyful worship, the spiritual leadership of the tzaddik (rebbe), and the presence of God in all things.",
      tags: ["c18", "mysticism", "orthodox"],
      tenet: "In Hasidic teaching, God's presence (Shekhinah) pervades all creation; the tzaddik serves as a spiritual channel connecting the community to the divine.",
      lineage: { parents: ["Orthodox Judaism"], divergence: "founded by the Baal Shem Tov (c. 1740s) in Eastern Europe; introduced mystical piety and charismatic leadership into traditional observance" },
      figures: ["Rabbi Israel ben Eliezer (Baal Shem Tov)", "Rabbi Dov Ber of Mezeritch", "Rabbi Nachman of Breslov"],
      era: ["c18", "c19", "c20"],
      coreTenets: [
        "Devekut (cleaving to God) can be achieved through prayer, joy, song, and even mundane activities performed with spiritual intention.",
        "The tzaddik (righteous leader) mediates between the community and God; Hasidic dynasties transmit this leadership.",
        "Kabbalistic mysticism, especially Lurianic concepts of divine sparks, informs Hasidic theology.",
      ],
      keyThinkers: ["Tanya (Rabbi Shneur Zalman of Liadi — Chabad)", "Likutey Moharan (Rabbi Nachman of Breslov)"],
      historicalInstances: ["Chabad-Lubavitch global outreach", "Satmar, Breslov, Belz, Ger, and other Hasidic courts"],
      principalCritiques: [
        "Mitnagdim (opponents), led by the Vilna Gaon, accused early Hasidism of antinomianism and deviation from Talmudic study.",
        "Modern scholars debate whether Hasidism represents a genuinely new religious movement or a reconfiguration of existing kabbalistic and pietist traditions (Moshe Idel vs. Gershom Scholem).",
      ],
    },
    {
      name: "Haredi Judaism",
      description: "Ultra-Orthodox communities that maintain strict separation from secular culture and maximal adherence to traditional halakhah.",
      tags: ["c20", "c21", "orthodox"],
      tenet: "Haredi communities hold that authentic Jewish life requires insulation from secular modernity and strict obedience to rabbinic authority (da'at Torah).",
      lineage: { parents: ["Orthodox Judaism"], divergence: "rejects the accommodations of Modern Orthodoxy; maintains that secular culture poses an existential threat to Torah observance" },
      figures: ["Rabbi Moses Sofer (Chatam Sofer)", "Chazon Ish", "various contemporary rabbinic leaders"],
      era: ["c20", "c21"],
      coreTenets: [
        "Da'at Torah: the guidance of qualified rabbinic authorities extends to all areas of life, including political and personal decisions.",
        "Secular education, media, and culture should be limited or avoided to protect religious commitment.",
        "The Holocaust and assimilation demonstrate the dangers of integration into non-Jewish society.",
      ],
      keyThinkers: ["Rabbi Moses Sofer — 'chadash asur min ha-Torah' (the new is forbidden)", "Chazon Ish — halakhic writings"],
      principalCritiques: [
        "Critics within Orthodoxy argue that total insularity produces economic dependency and limits educational opportunities.",
        "Sociologists note tensions between Haredi separatism and the practical demands of citizenship in democratic states (Israel, USA).",
      ],
    },
    {
      name: "Conservative (Masorti) Judaism",
      description: "A movement that accepts the findings of modern biblical scholarship while maintaining the binding authority of halakhah, interpreted with historical awareness.",
      tags: ["c19", "c20", "halakhah"],
      tenet: "Conservative Judaism holds that halakhah is binding but evolves through the ongoing interaction of the Jewish community with its legal tradition.",
      lineage: { parents: ["Rabbinic Judaism"], divergence: "positioned between Orthodox and Reform; accepts historical-critical study of texts but retains halakhic commitment" },
      figures: ["Solomon Schechter", "Rabbi Abraham Joshua Heschel", "Rabbi Louis Ginzberg"],
      era: ["c19", "c20"],
      coreTenets: [
        "The Torah is divinely inspired and halakhah is binding, but law develops through historical process and communal consensus.",
        "Modern scholarship — archaeology, linguistics, comparative religion — can illuminate Jewish texts without undermining their authority.",
        "Tradition and change must be held in creative tension; the Committee on Jewish Law and Standards adjudicates disputed questions.",
      ],
      keyThinkers: ["Solomon Schechter — Studies in Judaism", "Abraham Joshua Heschel — God in Search of Man"],
      principalCritiques: [
        "Orthodox critics argue that accepting historical criticism inevitably erodes the divine authority of revelation.",
        "Reform critics contend that Conservative Judaism's retention of halakhic authority is inconsistent with its acceptance of textual criticism.",
      ],
    },
    {
      name: "Reform (Progressive) Judaism",
      description: "A movement that emphasizes ethical monotheism and individual autonomy, adapting Jewish practice to modern life.",
      tags: ["c19", "c20", "modern"],
      tenet: "Reform Judaism holds that the ethical and prophetic core of Judaism is eternal, but ritual law may be adapted or set aside in light of modern knowledge and values.",
      lineage: { parents: ["Rabbinic Judaism"], divergence: "Enlightenment-era modernization; prioritizes prophetic ethics over ritual halakhah and embraces individual autonomy" },
      figures: ["Abraham Geiger", "Isaac Mayer Wise", "Rabbi Leo Baeck"],
      era: ["c19", "c20"],
      coreTenets: [
        "Judaism's essence lies in its ethical monotheism and prophetic concern for justice, not in ritual observance alone.",
        "Individual Jews have the autonomy to choose meaningful practices; halakhah is a guide, not a binding code.",
        "Judaism must engage with modern culture, science, and social justice rather than withdraw from them.",
      ],
      keyThinkers: ["Abraham Geiger — early Reform theology", "Pittsburgh Platform (1885)", "Columbus Platform (1937)"],
      principalCritiques: [
        "Orthodox and Conservative critics argue that Reform's abandonment of halakhic authority severs Judaism from its legal-covenantal core.",
        "Scholars note that the boundary between 'ethical essence' and 'dispensable ritual' is subjective and historically contingent.",
      ],
    },
    {
      name: "Reconstructionist Judaism",
      description: "A movement founded by Mordecai Kaplan that defines Judaism as an evolving religious civilization rather than a divinely revealed religion.",
      tags: ["c20", "modern"],
      tenet: "In Kaplan's formulation, Judaism is an evolving religious civilization; God is understood not as a supernatural being but as the power that makes for salvation (human flourishing).",
      lineage: { parents: ["Conservative (Masorti) Judaism"], divergence: "Kaplan's naturalist theology and civilizational definition of Judaism; emerged from within Conservative Judaism" },
      figures: ["Mordecai Kaplan", "Ira Eisenstein"],
      era: ["c20"],
      coreTenets: [
        "Judaism is a civilization encompassing language, culture, art, and ethics — not only a religion in the narrow sense.",
        "God is the sum of the natural processes that enable human flourishing, not a supernatural personal deity.",
        "Jewish law and ritual derive authority from communal decision-making, not divine fiat.",
      ],
      keyThinkers: ["Mordecai Kaplan — Judaism as a Civilization"],
      principalCritiques: [
        "Theistic critics argue that Kaplan's naturalist theology empties the concept of God of meaningful religious content.",
        "Orthodox and Conservative critics contend that defining Judaism as civilization reduces it to a cultural program without transcendent authority.",
      ],
    },
    {
      name: "Karaite Judaism",
      description: "A Jewish movement that accepts only the Written Torah (Tanakh) as authoritative, rejecting the Oral Torah and rabbinic tradition.",
      tags: ["medieval", "scripture"],
      tenet: "Karaites hold that the Written Torah alone is the word of God; the Oral Torah claimed by the rabbis is a human invention without divine authority.",
      lineage: { parents: ["Judaism"], divergence: "emerged c. 8th-9th century CE; rejects rabbinic authority and the Talmudic tradition" },
      figures: ["Anan ben David (traditional founder)", "al-Qirqisani"],
      era: ["medieval"],
      adherents: "~30,000-50,000 (est.)",
      coreTenets: [
        "Scripture (the Tanakh) is the sole authoritative source of Jewish law; each generation must interpret it directly.",
        "The rabbinic Oral Torah — Mishnah, Talmud, and subsequent codes — represents human opinion, not divine revelation.",
        "Individual study and reason, not rabbinic consensus, determine the correct interpretation of biblical commandments.",
      ],
      keyThinkers: ["Anan ben David (attributed)", "al-Qirqisani — Kitab al-Anwar"],
      principalCritiques: [
        "Rabbinic authorities argued that the Written Torah is unintelligible without the Oral Torah and that Karaism produces legal fragmentation.",
        "Modern scholars debate whether Karaism originated as a genuinely new movement or crystallized from earlier anti-rabbinic tendencies.",
      ],
    },
    {
      name: "Samaritanism",
      description: "An Israelite religion closely related to Judaism, centered on the Samaritan Pentateuch and worship at Mount Gerizim rather than Jerusalem.",
      tags: ["ancient", "israelite"],
      tenet: "Samaritans hold that Mount Gerizim — not Jerusalem — is the place chosen by God for worship, and that the Samaritan Pentateuch preserves the original text of the Torah.",
      lineage: { parents: ["Judaism"], divergence: "ancient divergence from the Jerusalem-centered Judean tradition; the relationship and timing of the split are debated by scholars", contested: true },
      figures: ["Baba Rabba (4th-century leader)"],
      era: ["ancient"],
      adherents: "~800 (est.)",
      coreTenets: [
        "Mount Gerizim, not the Temple Mount in Jerusalem, is the sacred center chosen by God.",
        "The Samaritan Pentateuch — differing in some readings from the Masoretic text — is the authentic Torah.",
        "Samaritans observe the biblical festivals and maintain the Passover sacrifice on Mount Gerizim to the present day.",
      ],
      keyThinkers: ["Samaritan Pentateuch", "Memar Marqah (Samaritan theological text)"],
      principalCritiques: [
        "The relationship between Samaritans and Jews is disputed: are Samaritans a branch of ancient Israelite religion, or descendants of Assyrian settlers? The evidence is mixed (Knoppers, Pummer).",
        "The small surviving community faces questions of demographic sustainability and cultural preservation.",
      ],
    },
  ],
};

// ── FAMILY 2: CHRISTIANITY — BRANCHES & TRADITIONS ──────────────────────────

const CHRISTIANITY_FAMILY: Family = {
  slug: "christianity",
  name: "Christianity: Branches & Traditions",
  blurb: "From the apostolic community through the Great Schism, the Reformation, and modern movements.",
  color: "indigo",
  broadFamily: true,
  traditions: [
    {
      name: "Christianity",
      description: "A monotheistic religion centered on the life, death, and resurrection of Jesus Christ as proclaimed in the New Testament.",
      tags: ["c1ce", "monotheism", "salvation"],
      tenet: "Christians profess that Jesus of Nazareth is the Christ (Messiah), the Son of God, whose death and resurrection offer salvation to humanity.",
      lineage: { parents: ["Second-Temple Judaism"], divergence: "emerged from within Second-Temple Judaism; proclaimed Jesus as the awaited Messiah, diverging on Christology and the scope of the covenant" },
      figures: ["Jesus of Nazareth", "the Apostles (Peter, Paul, John)"],
      era: ["c1ce"],
      adherents: "~2.3B (est., Pew)",
      coreTenets: [
        "According to Christian belief, God is one God in three persons: Father, Son, and Holy Spirit (the Trinity).",
        "Salvation comes through faith in Jesus Christ, whose death atoned for human sin and whose resurrection conquered death.",
        "The Bible — Old and New Testaments — is the primary scriptural authority, though traditions differ on its interpretation and sufficiency.",
      ],
      keyThinkers: ["New Testament (Gospels, Pauline epistles)", "Nicene Creed (325/381 CE)"],
      principalCritiques: [
        "Historical-critical scholars debate the relationship between the 'historical Jesus' and the 'Christ of faith' as presented in the Gospels (Schweitzer, Sanders, Ehrman).",
        "The diversity of early Christianities (Bauer thesis) complicates any claim to a single 'original' orthodoxy.",
      ],
      broadFamily: true,
    },
    {
      name: "Early Christianity",
      description: "The diverse movements of Jesus-followers in the first three centuries, before the Constantinian settlement and conciliar orthodoxy.",
      tags: ["c1ce", "c2ce", "c3ce"],
      tenet: "Early Christians proclaimed Jesus as risen Lord and Messiah, but disagreed extensively on Christology, ecclesiology, and the relationship to Jewish law.",
      lineage: { parents: ["Christianity"], divergence: "the pre-Constantinian period; encompasses apostolic, sub-apostolic, and ante-Nicene diversity" },
      figures: ["Paul of Tarsus", "Ignatius of Antioch", "Origen", "Tertullian"],
      era: ["c1ce", "c2ce", "c3ce"],
      coreTenets: [
        "The apostolic proclamation (kerygma) of Jesus's death and resurrection was the shared core, though its interpretation varied widely.",
        "Communities debated whether Gentile converts must observe Jewish law — a question resolved differently by Paul and the Jerusalem church.",
        "Diverse Christologies competed: adoptionist, docetic, Logos theology, and what later became Nicene orthodoxy.",
      ],
      keyThinkers: ["Paul — Epistles", "Irenaeus — Against Heresies", "Origen — De Principiis"],
      principalCritiques: [
        "Walter Bauer argued that 'heresy' often preceded 'orthodoxy' in many regions; the winners wrote the canonical history.",
        "The relationship between Jewish Christianity and Gentile Christianity remains a major area of scholarly debate (Boyarin, Dunn).",
      ],
    },
    {
      name: "Nicene Christianity",
      description: "The creedal orthodoxy established by the ecumenical councils, affirming the Trinity and the full divinity and humanity of Christ.",
      tags: ["c4ce", "c5ce", "creedal"],
      tenet: "The Nicene Creed affirms that Christ is 'of one substance (homoousios) with the Father' — fully God and fully human — and that the Holy Spirit proceeds from the Father.",
      lineage: { parents: ["Early Christianity"], divergence: "the Council of Nicaea (325) and Constantinople (381) defined trinitarian and Christological orthodoxy against Arianism and other alternatives" },
      figures: ["Athanasius of Alexandria", "the Cappadocian Fathers (Basil, Gregory of Nazianzus, Gregory of Nyssa)"],
      era: ["c4ce", "c5ce"],
      coreTenets: [
        "God is one substance (ousia) in three persons (hypostases): Father, Son, and Holy Spirit.",
        "The Son is begotten, not made, and is consubstantial with the Father — against Arius's subordinationism.",
        "The Chalcedonian Definition (451) held that Christ has two natures — divine and human — united in one person without confusion or separation.",
      ],
      keyThinkers: ["Nicene Creed (325/381)", "Chalcedonian Definition (451)", "Athanasius — On the Incarnation"],
      principalCritiques: [
        "Non-Chalcedonian churches (Oriental Orthodox, Church of the East) rejected aspects of Chalcedon's two-nature formula, preferring miaphysite or dyophysite alternatives.",
        "Modern theologians debate whether the Hellenistic philosophical categories used at Nicaea and Chalcedon faithfully represent biblical Christology (Harnack, Grillmeier).",
      ],
    },
    {
      name: "Roman Catholicism",
      description: "The largest Christian communion, led by the Pope as Bishop of Rome, emphasizing apostolic succession, sacraments, and Magisterial teaching authority.",
      tags: ["c4ce", "medieval", "modern", "papacy"],
      tenet: "Catholics hold that the Pope, as successor of Peter, has supreme authority over the universal Church, and that the Magisterium (teaching authority) interprets Scripture and Tradition infallibly on matters of faith and morals.",
      lineage: { parents: ["Nicene Christianity"], divergence: "the Western church's development of papal primacy, distinct from the Eastern patriarchates, culminating in the Great Schism of 1054" },
      figures: ["Pope Leo XIV (Robert Prevost, elected May 2025, first American pope)", "Thomas Aquinas", "Augustine of Hippo"],
      era: ["c4ce", "medieval", "modern"],
      adherents: "~1.3-1.4B (est., Pew)",
      coreTenets: [
        "The Pope, as Peter's successor, holds the 'keys of the kingdom' and exercises supreme jurisdictional authority over the universal Church.",
        "Seven sacraments — Baptism, Eucharist, Confirmation, Reconciliation, Anointing, Holy Orders, Matrimony — are the ordinary means of grace.",
        "Sacred Tradition alongside Sacred Scripture constitutes the single deposit of faith, interpreted authoritatively by the Magisterium.",
      ],
      keyThinkers: ["Thomas Aquinas — Summa Theologica", "Second Vatican Council (1962-65)", "Catechism of the Catholic Church (1992)"],
      historicalInstances: ["The Great Schism (1054)", "Council of Trent (1545-63)", "Second Vatican Council (1962-65)"],
      principalCritiques: [
        "Eastern Orthodox and Protestant theologians contest papal primacy and infallibility as unsupported by the early church's conciliar model.",
        "Historians debate whether Petrine primacy as exercised by later popes was recognized in the early centuries (Schatz, Duffy).",
      ],
    },
    {
      name: "Eastern Orthodoxy",
      description: "The communion of autocephalous (self-governing) churches that maintain the faith of the seven ecumenical councils, led by the Ecumenical Patriarch of Constantinople in a primacy of honor.",
      tags: ["c4ce", "medieval", "modern", "conciliar"],
      tenet: "Eastern Orthodox Christians hold that the Church is governed by ecumenical councils and the consensus of the Fathers, not by any single bishop's universal jurisdiction.",
      lineage: { parents: ["Nicene Christianity"], divergence: "the Great Schism of 1054 formalized the break with Rome; disputes over papal authority, the Filioque clause, and ecclesiology" },
      figures: ["Ecumenical Patriarch Bartholomew", "John Chrysostom", "Gregory Palamas"],
      era: ["c4ce", "medieval", "modern"],
      adherents: "~220M (est.)",
      coreTenets: [
        "The faith was definitively expressed in the seven ecumenical councils (325-787); no subsequent innovation may alter their doctrinal decrees.",
        "The church is a communion of autocephalous churches united by shared faith, sacraments, and conciliar governance — not papal jurisdiction.",
        "Theosis (divinization) — becoming partakers of the divine nature — is the goal of the Christian life.",
      ],
      keyThinkers: ["John of Damascus — An Exact Exposition of the Orthodox Faith", "Gregory Palamas — Triads", "Vladimir Lossky — The Mystical Theology of the Eastern Church"],
      principalCritiques: [
        "Catholic theologians argue that conciliarism without a final arbiter leads to jurisdictional disputes (e.g., the Moscow-Constantinople tension over Ukraine).",
        "Internal debates persist over nationalism (phyletism) and the relationship between ethnic identity and ecclesial structure.",
      ],
    },
    {
      name: "Oriental Orthodoxy",
      description: "A family of ancient churches — Coptic, Ethiopian, Armenian, Syriac, Indian — that rejected the Chalcedonian two-nature Christological formula in favor of miaphysitism.",
      tags: ["c5ce", "miaphysite", "ancient"],
      tenet: "Oriental Orthodox churches confess that Christ has one united nature (mia physis) — fully divine and fully human — rejecting what they regard as the Nestorian implications of Chalcedon's 'two natures' language.",
      lineage: { parents: ["Nicene Christianity"], divergence: "rejected the Council of Chalcedon (451); the Christological dispute over one-nature (miaphysite) vs. two-nature (dyophysite) language" },
      figures: ["Cyril of Alexandria (theological source)", "Dioscorus of Alexandria"],
      era: ["c5ce", "medieval", "modern"],
      adherents: "~60-80M (est.)",
      coreTenets: [
        "Christ's divinity and humanity are united in one nature (miaphysis) 'without confusion, without change' — this is not monophysitism (which they reject).",
        "The first three ecumenical councils (Nicaea, Constantinople, Ephesus) are authoritative; Chalcedon is rejected as introducing Nestorian-leaning language.",
        "Each national church (Coptic, Armenian, Ethiopian, Syriac, Indian) maintains its own liturgical and canonical traditions.",
      ],
      keyThinkers: ["Cyril of Alexandria — Unity of Christ", "Severus of Antioch — miaphysite theology"],
      principalCritiques: [
        "Chalcedonian churches historically labeled Oriental Orthodoxy as 'monophysite' (denying Christ's human nature), though modern dialogue has recognized this as a mischaracterization of miaphysitism.",
        "Ecumenical dialogues since the 1960s have suggested the Chalcedonian/non-Chalcedonian divide may be largely terminological rather than substantive.",
      ],
    },
    {
      name: "Church of the East",
      description: "The ancient Syriac-speaking church historically centered in Mesopotamia, sometimes called 'Nestorian' — a label its adherents reject.",
      tags: ["c5ce", "syriac", "ancient"],
      tenet: "The Church of the East affirms two qnome (concrete natures) in Christ united in one parsopa (person), rejecting the 'Nestorian' label as a polemical distortion.",
      lineage: { parents: ["Early Christianity"], divergence: "developed independently in the Sasanian Empire; its Christological terminology diverged from both Chalcedonian and miaphysite formulations" },
      figures: ["Babai the Great", "Timothy I (Catholicos-Patriarch)"],
      era: ["c5ce", "medieval"],
      adherents: "~400,000 (est., Assyrian Church of the East + Chaldean Catholic)",
      coreTenets: [
        "Christ possesses two complete qnome (natures) united in one parsopa (person) — a formulation the church distinguishes from Nestorianism.",
        "The church traces its origins to the apostolic mission of Thomas and Addai to Mesopotamia, independent of the Roman imperial church.",
        "At its medieval height, the Church of the East extended missionary activity across Central Asia and into China (the Xi'an Stele, 781).",
      ],
      keyThinkers: ["Babai the Great — Book of Union", "Theodore of Mopsuestia (revered as 'The Interpreter')"],
      principalCritiques: [
        "The label 'Nestorian' — implying that Christ is two persons — has been applied polemically; modern scholarship (Brock, Baum) recognizes the Church's Christology as more nuanced.",
        "The church's dramatic decline from its medieval peak is attributed to the Mongol invasions, Tamerlane's campaigns, and later Ottoman-era persecutions.",
      ],
    },
    {
      name: "Protestant Reformation",
      description: "The 16th-century movement that broke with papal authority, asserting sola scriptura and sola fide as the foundations of Christian faith.",
      tags: ["c16", "reformation", "sola-scriptura"],
      tenet: "Reformers held that salvation comes by grace alone through faith alone, as revealed in Scripture alone — rejecting papal authority and the Catholic sacramental system as corrupted.",
      lineage: { parents: ["Roman Catholicism"], divergence: "Martin Luther's 95 Theses (1517) catalyzed a break with Rome over indulgences, papal authority, and the doctrine of justification" },
      figures: ["Martin Luther", "John Calvin", "Huldrych Zwingli"],
      era: ["c16"],
      broadFamily: true,
      coreTenets: [
        "Sola scriptura: Scripture alone is the supreme authority in matters of doctrine and practice.",
        "Sola fide: justification before God comes through faith alone, not through meritorious works or sacramental mediation.",
        "The priesthood of all believers: every Christian has direct access to God without priestly mediation.",
      ],
      keyThinkers: ["Martin Luther — 95 Theses, Small Catechism", "John Calvin — Institutes of the Christian Religion", "Huldrych Zwingli — 67 Articles"],
      historicalInstances: ["Diet of Worms (1521)", "Peace of Augsburg (1555)", "English Reformation"],
      principalCritiques: [
        "Catholic theologians argue that sola scriptura is self-refuting — Scripture itself does not assert its own sole sufficiency — and that the Reformers selectively read the Church Fathers.",
        "Historians debate whether the Reformation was primarily theological (confessional narrative) or driven by political, economic, and social forces (revisionist narrative).",
      ],
    },
    {
      name: "Lutheranism",
      description: "The tradition stemming from Martin Luther, emphasizing justification by grace through faith and the theology of the cross.",
      tags: ["c16", "reformation", "grace"],
      tenet: "Lutherans confess that sinful humanity is justified before God by grace alone through faith alone, apart from works of the law.",
      lineage: { parents: ["Protestant Reformation"], divergence: "Luther's theology of justification, real presence in the Eucharist, and retention of liturgical elements distinguished Lutheranism from Reformed Protestantism" },
      figures: ["Martin Luther", "Philipp Melanchthon"],
      era: ["c16", "c17"],
      adherents: "~70-80M (est.)",
      coreTenets: [
        "Justification by grace through faith is the 'article on which the church stands or falls.'",
        "Christ is truly present 'in, with, and under' the bread and wine of the Eucharist (sacramental union), against both transubstantiation and mere symbolism.",
        "Law and Gospel must be properly distinguished: the Law reveals sin, the Gospel reveals grace.",
      ],
      keyThinkers: ["Martin Luther — Large Catechism", "Book of Concord (1580)", "Philipp Melanchthon — Augsburg Confession"],
      principalCritiques: [
        "Reformed critics argue Luther's retention of liturgical forms and his Eucharistic theology remain too close to Catholic practice.",
        "The 1999 Joint Declaration on the Doctrine of Justification between Lutherans and Catholics suggests the 16th-century condemnations may no longer apply, raising questions about the Reformation's continued necessity.",
      ],
    },
    {
      name: "Reformed / Calvinist",
      description: "The tradition stemming from John Calvin and Huldrych Zwingli, emphasizing God's sovereignty, predestination, and the regulative principle of worship.",
      tags: ["c16", "reformation", "sovereignty"],
      tenet: "In Reformed theology, God's absolute sovereignty governs all things, including the election of individuals to salvation — predestination is a comfort, not a terror, to the faithful.",
      lineage: { parents: ["Protestant Reformation"], divergence: "Calvin's emphasis on divine sovereignty, double predestination, and the regulative principle distinguished the Reformed tradition from Lutheranism" },
      figures: ["John Calvin", "Huldrych Zwingli", "John Knox"],
      era: ["c16", "c17"],
      adherents: "~60-80M (est., including Presbyterian, Reformed, and Congregational churches)",
      coreTenets: [
        "God's sovereignty is absolute: election and reprobation are unconditional divine decrees (TULIP: Total depravity, Unconditional election, Limited atonement, Irresistible grace, Perseverance of the saints).",
        "The regulative principle of worship: only what Scripture explicitly commands may be included in public worship.",
        "Church governance is presbyterian (rule by elders) rather than episcopal or congregational.",
      ],
      keyThinkers: ["John Calvin — Institutes of the Christian Religion", "Westminster Confession of Faith (1646)", "Heidelberg Catechism (1563)"],
      historicalInstances: ["Geneva under Calvin", "Huguenots (France)", "Puritans (England and New England)", "Dutch Reformed Church"],
      principalCritiques: [
        "Arminians argued that double predestination makes God the author of sin and renders human moral agency meaningless.",
        "Karl Barth's neo-orthodox revision reinterpreted predestination Christologically, arguing Calvin's scheme required correction.",
      ],
    },
    {
      name: "Anglicanism",
      description: "The tradition rooted in the Church of England, characterizing itself as a 'via media' (middle way) between Catholicism and Protestantism.",
      tags: ["c16", "via-media", "episcopal"],
      tenet: "Anglicans hold that the church is both Catholic and Reformed — maintaining apostolic succession, episcopal governance, and liturgical worship while affirming Protestant doctrinal principles.",
      lineage: { parents: ["Protestant Reformation", "Roman Catholicism"], divergence: "the English Reformation (1534) created a national church that retained Catholic structure while adopting Reformed doctrine — the 'Elizabethan Settlement'" },
      figures: ["Thomas Cranmer", "Richard Hooker", "Archbishop Sarah Mullally (106th Archbishop of Canterbury, installed March 2026, first woman)"],
      era: ["c16", "c17", "modern"],
      adherents: "~85M (est., Anglican Communion)",
      coreTenets: [
        "The 'three-legged stool' of authority: Scripture, Tradition, and Reason together guide faith and practice.",
        "The Book of Common Prayer provides a shared liturgical framework that unites theologically diverse communities.",
        "Comprehensiveness: Anglicanism accommodates a breadth of theological positions (Anglo-Catholic, Evangelical, Liberal) within one communion.",
      ],
      keyThinkers: ["Richard Hooker — Of the Laws of Ecclesiastical Polity", "Thomas Cranmer — Book of Common Prayer (1549/1662)", "Chicago-Lambeth Quadrilateral (1886/1888)"],
      historicalInstances: ["English Reformation and the Act of Supremacy (1534)", "Oxford Movement (1830s)", "Lambeth Conferences"],
      principalCritiques: [
        "Critics argue that Anglican comprehensiveness masks irreconcilable theological differences, particularly on sexuality and the ordination of women — tensions that have led to the GAFCON realignment.",
        "Catholic theologians question whether Anglican orders are valid, following Leo XIII's Apostolicae Curae (1896), though this assessment is itself debated.",
      ],
    },
    {
      name: "Anabaptism",
      description: "The 'radical Reformation' movement that insisted on believer's baptism, separation of church and state, and nonviolent discipleship.",
      tags: ["c16", "radical-reformation", "pacifism"],
      tenet: "Anabaptists hold that baptism is valid only upon a conscious confession of faith, that the church must be separate from the state, and that Christians are called to nonviolent living.",
      lineage: { parents: ["Protestant Reformation"], divergence: "the radical wing of the Reformation; rejected infant baptism and state-church alliances, advocating a 'believers' church'" },
      figures: ["Conrad Grebel", "Menno Simons", "Jakob Hutter"],
      era: ["c16"],
      coreTenets: [
        "Believer's baptism: only those who consciously profess faith should be baptized; infant baptism is invalid.",
        "The church is a voluntary community of committed disciples, separate from the coercive power of the state.",
        "Nonresistance and pacifism follow from Jesus's Sermon on the Mount; Christians must not bear the sword.",
      ],
      keyThinkers: ["Schleitheim Confession (1527)", "Menno Simons — Foundation of Christian Doctrine"],
      historicalInstances: ["Swiss Brethren", "Mennonites", "Hutterites", "Amish"],
      principalCritiques: [
        "Magisterial Reformers (Luther, Calvin, Zwingli) condemned Anabaptist rejection of infant baptism and civil authority as socially destabilizing.",
        "Historians debate whether the Munster Rebellion (1534-35) was representative of Anabaptism or a radical aberration exploited by its opponents.",
      ],
    },
    {
      name: "Methodism",
      description: "A revival movement originating within Anglicanism, emphasizing personal holiness, social action, and the 'Wesleyan Quadrilateral' of theological authority.",
      tags: ["c18", "revival", "holiness"],
      tenet: "Methodists hold that God's grace is available to all (prevenient grace), that personal holiness and social holiness are inseparable, and that believers can progress toward Christian perfection.",
      lineage: { parents: ["Anglicanism"], divergence: "John Wesley's 18th-century revival movement within the Church of England; became a separate denomination after Wesley's death" },
      figures: ["John Wesley", "Charles Wesley", "George Whitefield"],
      era: ["c18", "c19"],
      adherents: "~80M (est., World Methodist Council)",
      coreTenets: [
        "Prevenient grace: God's grace works in every person before conversion, enabling (but not compelling) a response of faith.",
        "Christian perfection (entire sanctification): believers can, by grace, be made perfect in love in this life.",
        "Social holiness: personal piety must issue in social action — education, prison reform, abolition, care for the poor.",
      ],
      keyThinkers: ["John Wesley — Sermons, A Plain Account of Christian Perfection", "the Wesleyan Quadrilateral (Scripture, Tradition, Reason, Experience)"],
      historicalInstances: ["18th-century Methodist revival in Britain", "Methodist Episcopal Church (USA)", "Temperance and abolitionist movements"],
      principalCritiques: [
        "Calvinist critics argue that Wesleyan Arminianism undermines the doctrines of grace by making salvation contingent on human cooperation.",
        "The doctrine of Christian perfection has been criticized as psychologically unrealistic and prone to spiritual elitism.",
      ],
    },
    {
      name: "Baptist tradition",
      description: "A family of churches defined by believer's baptism by immersion, congregational governance, and the autonomy of the local church.",
      tags: ["c17", "believers-baptism", "congregational"],
      tenet: "Baptists hold that baptism is properly administered only to those who make a personal profession of faith, by full immersion, and that each local congregation is self-governing under Christ.",
      lineage: { parents: ["Protestant Reformation", "Anabaptism"], divergence: "emerged in early 17th-century England; shares the Anabaptist emphasis on believer's baptism but developed independently within the English Puritan context", contested: true },
      figures: ["John Smyth", "Thomas Helwys", "Roger Williams", "Charles Spurgeon"],
      era: ["c17", "c18", "c19"],
      adherents: "~100M+ (est., Baptist World Alliance)",
      coreTenets: [
        "Believer's baptism by immersion: only professing believers should be baptized, and immersion is the biblical mode.",
        "Soul competency and religious liberty: each individual is directly accountable to God; the state has no authority over the conscience.",
        "Congregational polity: each local church is autonomous and self-governing, with no hierarchy above the congregation.",
      ],
      keyThinkers: ["Thomas Helwys — A Short Declaration of the Mystery of Iniquity (earliest English plea for religious liberty)", "Charles Spurgeon — sermons"],
      principalCritiques: [
        "The historical origins of the Baptist movement — whether from continental Anabaptism, English Separatism, or independently — remain debated (successionism vs. English Separatist thesis).",
        "Critics note that congregational autonomy can lead to doctrinal fragmentation, as there is no mechanism for resolving disputes between Baptist bodies.",
      ],
    },
    {
      name: "Pentecostalism",
      description: "A renewal movement emphasizing the baptism of the Holy Spirit, evidenced by speaking in tongues (glossolalia), healing, and other spiritual gifts.",
      tags: ["c20", "charismatic", "spirit"],
      tenet: "Pentecostals hold that the experience of the Holy Spirit described in Acts 2 is available to all believers today, typically evidenced by speaking in tongues.",
      lineage: { parents: ["Methodism"], divergence: "emerged from the Holiness movement; the Azusa Street Revival (1906) is conventionally regarded as the founding event" },
      figures: ["William J. Seymour", "Charles Fox Parham"],
      era: ["c20", "c21"],
      adherents: "~600M+ (est., including Charismatics; Pew)",
      coreTenets: [
        "Baptism in the Holy Spirit is a distinct experience subsequent to conversion, typically accompanied by speaking in tongues.",
        "The spiritual gifts described in 1 Corinthians 12 — prophecy, healing, tongues, interpretation — are active in the church today.",
        "Worship is experiential and participatory: spontaneous prayer, praise, and physical expression are central.",
      ],
      keyThinkers: ["Early Pentecostal testimonies and periodicals", "Walter Hollenweger — The Pentecostals (scholarly study)"],
      historicalInstances: ["Azusa Street Revival, Los Angeles (1906)", "Assemblies of God", "Church of God in Christ", "Global South Pentecostal growth"],
      principalCritiques: [
        "Cessationists argue that the apostolic gifts (tongues, healing) ceased with the apostolic age and have no warrant for continuation.",
        "Scholars of Global Christianity note that Pentecostalism's rapid growth often occurs alongside prosperity theology, which critics regard as a distortion of the Gospel (Gifford, Asamoah-Gyadu).",
      ],
    },
    {
      name: "Evangelicalism",
      description: "A transdenominational movement emphasizing biblical authority, personal conversion (being 'born again'), the atoning work of Christ, and active evangelism.",
      tags: ["c18", "c20", "c21", "conversion"],
      tenet: "Evangelicals emphasize the need for a personal conversion experience ('born again'), the supreme authority of Scripture, the centrality of Christ's atonement, and the imperative to share the Gospel.",
      lineage: { parents: ["Protestant Reformation"], divergence: "crystallized in the 18th-century revivals (Great Awakenings); Bebbington's quadrilateral defines the movement: biblicism, crucicentrism, conversionism, activism" },
      figures: ["George Whitefield", "Jonathan Edwards", "Billy Graham"],
      era: ["c18", "c20", "c21"],
      adherents: "~600M+ (est., overlapping with Pentecostalism)",
      coreTenets: [
        "Biblicism: the Bible is the inspired, authoritative word of God and the final rule of faith and practice.",
        "Conversionism: each individual must experience a personal conversion — being 'born again' — to enter a saving relationship with Christ.",
        "Activism: Christians are called to share the Gospel (evangelism) and to serve others in word and deed.",
      ],
      keyThinkers: ["Jonathan Edwards — Religious Affections", "David Bebbington — Evangelicalism in Modern Britain (quadrilateral definition)", "John Stott — Basic Christianity"],
      principalCritiques: [
        "Liberal theologians argue that evangelical biblicism conflates the human text of Scripture with the Word of God, producing fundamentalist tendencies.",
        "Sociologists note that 'evangelical' has become a politicized identity marker, especially in the US, complicating its use as a theological category (Noll, Marsden).",
      ],
      broadFamily: true,
    },
    {
      name: "Restorationism",
      description: "Movements seeking to restore the church to its original New Testament form, bypassing historical tradition and denominational structures.",
      tags: ["c19", "c20", "primitivism"],
      tenet: "Restorationists hold that the true church can and must be restored to its New Testament pattern, which was corrupted by centuries of institutional accretion.",
      lineage: { parents: ["Protestant Reformation"], divergence: "goes beyond Reformation: not merely reforming the existing church but restoring the primitive apostolic model" },
      figures: ["Alexander Campbell", "Barton W. Stone", "Joseph Smith (Latter Day Saint movement)"],
      era: ["c19", "c20"],
      broadFamily: true,
      coreTenets: [
        "The New Testament provides a blueprint for church organization, worship, and doctrine that must be followed directly.",
        "Historical denominational traditions represent departure from the original apostolic pattern.",
        "Christian unity is achieved by returning to the New Testament model rather than through ecumenical negotiation.",
      ],
      keyThinkers: ["Alexander Campbell — The Christian System", "Stone-Campbell movement"],
      historicalInstances: ["Churches of Christ", "Disciples of Christ", "Latter Day Saint movement", "Christadelphians"],
      principalCritiques: [
        "Historians argue that the 'New Testament church' was itself diverse and contested; there is no single pattern to restore (Meeks, Ehrman).",
        "Ecumenists contend that restorationism's rejection of historical tradition impoverishes Christian theology and worship.",
      ],
    },
  ],
};

// ── FAMILY 3: ISLAM — BRANCHES & TRADITIONS ─────────────────────────────────

const ISLAM_FAMILY: Family = {
  slug: "islam",
  name: "Islam: Branches & Traditions",
  blurb: "From the prophetic revelation through the Sunni-Shia division, Sufism, and modern movements.",
  color: "emerald",
  broadFamily: true,
  traditions: [
    {
      name: "Islam",
      description: "A monotheistic religion based on the revelation of the Quran to the Prophet Muhammad, emphasizing submission (islam) to the one God (Allah).",
      tags: ["c7ce", "monotheism", "revelation"],
      tenet: "Muslims profess that there is no god but God (Allah) and that Muhammad is the Messenger of God — the shahada, or testimony of faith.",
      lineage: { parents: [], divergence: "root — Muslims understand Islam as the final revelation in the Abrahamic prophetic tradition, completing and correcting earlier revelations to Moses and Jesus" },
      figures: ["Prophet Muhammad", "the Four Rightly Guided Caliphs (Sunni view)"],
      era: ["c7ce"],
      adherents: "~2.0B (est., Pew)",
      coreTenets: [
        "Tawhid: the absolute oneness of God is the foundational principle; associating partners with God (shirk) is the gravest sin.",
        "The Quran is, in Muslim belief, the literal word of God revealed to Muhammad through the angel Gabriel.",
        "The Five Pillars — shahada, prayer (salat), almsgiving (zakat), fasting (sawm), pilgrimage (hajj) — structure Muslim practice.",
      ],
      keyThinkers: ["The Quran", "Hadith collections (Bukhari, Muslim, etc.)", "Ibn Ishaq — Sirat Rasul Allah (biography of Muhammad)"],
      principalCritiques: [
        "Critical scholars apply historical-critical methods to the Quran and hadith, dating and contextualizing texts in ways that some traditional scholars regard as reductive (Wansbrough, Crone, Donner).",
        "The relationship between Quranic revelation and pre-existing Jewish, Christian, and Arabian religious traditions is a major area of academic research (Neuwirth, Reynolds).",
      ],
      broadFamily: true,
    },
    {
      name: "Sunni Islam",
      description: "The largest branch of Islam, following the Sunnah (practice) of the Prophet and recognizing the legitimacy of the first four caliphs.",
      tags: ["c7ce", "majority", "sunnah"],
      tenet: "Sunni Muslims hold that the Prophet's companions (sahabah) rightly chose Abu Bakr as his successor, and that the consensus (ijma) of the community and the four madhabs (legal schools) provide authoritative guidance.",
      lineage: { parents: ["Islam"], divergence: "affirms the historical caliphate; accepts the first four caliphs as 'rightly guided' and the four Sunni legal schools as the framework for Islamic law" },
      figures: ["Abu Bakr", "Umar", "Abu Hanifa", "Imam Malik", "Imam al-Shafi'i", "Ahmad ibn Hanbal"],
      era: ["c7ce", "medieval"],
      adherents: "~85-90% of Muslims (est.)",
      coreTenets: [
        "The Sunnah of the Prophet — as transmitted in authentic hadith — is the second source of Islamic law after the Quran.",
        "The four Sunni madhabs (Hanafi, Maliki, Shafi'i, Hanbali) represent valid interpretive frameworks for deriving law from the sources.",
        "Ijma (scholarly consensus) and qiyas (analogical reasoning) complement Quran and Sunnah in legal methodology (usul al-fiqh).",
      ],
      keyThinkers: ["Imam al-Shafi'i — al-Risala (foundational usul al-fiqh)", "al-Ghazali — Ihya Ulum al-Din"],
      principalCritiques: [
        "Shia scholars argue that the Prophet designated Ali ibn Abi Talib as his successor at Ghadir Khumm, and that the election of Abu Bakr was a political deviation.",
        "Academic scholars of hadith debate the reliability of the isnad (chain of transmission) system for establishing authenticity (Schacht, Motzki).",
      ],
    },
    {
      name: "Shia Islam",
      description: "The branch of Islam that holds that leadership of the Muslim community (ummah) belongs to the Prophet's family (Ahl al-Bayt), beginning with Ali ibn Abi Talib.",
      tags: ["c7ce", "imamate", "ahl-al-bayt"],
      tenet: "Shia Muslims hold that the Prophet Muhammad designated Ali ibn Abi Talib and his descendants as the rightful leaders (Imams) of the community, possessing special spiritual authority.",
      lineage: { parents: ["Islam"], divergence: "the succession dispute after Muhammad's death (632 CE); Shia partisans (shi'at Ali) held that Ali was the divinely appointed successor" },
      figures: ["Ali ibn Abi Talib", "Husayn ibn Ali (martyred at Karbala, 680)", "Ja'far al-Sadiq"],
      era: ["c7ce", "medieval"],
      adherents: "~10-13% of Muslims (est.)",
      coreTenets: [
        "The Imamate: the Prophet's descendants through Ali and Fatimah possess divinely granted authority to lead and interpret Islam.",
        "The tragedy of Karbala (680 CE) — the martyrdom of Husayn — is a defining event, commemorated annually during Ashura.",
        "The Imam is, in Shia belief, ma'sum (infallible in matters of religion) and the authoritative interpreter of the Quran.",
      ],
      keyThinkers: ["Nahj al-Balagha (sermons attributed to Ali)", "al-Kulayni — al-Kafi (hadith collection)", "Allama al-Hilli"],
      principalCritiques: [
        "Sunni scholars dispute the hadith of Ghadir Khumm as evidence of Ali's designation, offering alternative interpretations of the event.",
        "Academic historians debate whether the Sunni-Shia split was primarily theological from the outset or a political succession dispute that acquired theological dimensions over time (Madelung, Jafri).",
      ],
      broadFamily: true,
    },
    {
      name: "Twelver Shiism",
      description: "The largest Shia denomination, recognizing a line of twelve Imams from Ali to Muhammad al-Mahdi, who entered occultation in 874 CE.",
      tags: ["c9ce", "imamate", "occultation"],
      tenet: "Twelver Shia hold that the twelfth Imam, Muhammad al-Mahdi, went into occultation (ghayba) in 874 CE and will return as the Mahdi to establish justice on earth.",
      lineage: { parents: ["Shia Islam"], divergence: "accepts the line of twelve Imams; the twelfth Imam's occultation and awaited return (raj'a) distinguish Twelvers from Isma'ili and Zaydi Shia" },
      figures: ["the Twelve Imams", "Ayatollah Ruhollah Khomeini", "Grand Ayatollah Ali al-Sistani"],
      era: ["c9ce", "medieval", "modern"],
      adherents: "~85% of Shia Muslims (est.)",
      coreTenets: [
        "Twelve Imams, beginning with Ali and ending with the Hidden Imam (al-Mahdi), constitute the divinely guided leadership of the ummah.",
        "During the Major Occultation, the most learned scholars (marja al-taqlid) serve as proxies for the Hidden Imam's authority.",
        "Wilayat al-faqih (guardianship of the jurist) — as theorized by Khomeini — extends clerical authority to governance, though this doctrine is debated within Twelver scholarship.",
      ],
      keyThinkers: ["Sheikh al-Mufid", "Allama al-Hilli", "Ayatollah Khomeini — Islamic Government"],
      historicalInstances: ["Safavid Iran (Shiism as state religion, 1501)", "Islamic Revolution in Iran (1979)"],
      principalCritiques: [
        "Other Shia groups (Isma'ili, Zaydi) dispute the identity and number of the Imams after the sixth Imam, Ja'far al-Sadiq.",
        "The wilayat al-faqih doctrine is contested within Twelver scholarship itself — quietist scholars (e.g., Sistani) favor a more limited clerical role in governance.",
      ],
    },
    {
      name: "Isma'ili Shiism",
      description: "A branch of Shia Islam that recognizes Isma'il ibn Ja'far (rather than Musa al-Kadhim) as the rightful seventh Imam.",
      tags: ["c8ce", "imamate", "esoteric"],
      tenet: "Isma'ilis hold that the Imamate passed through Isma'il ibn Ja'far and his descendants, and that the Imam provides authoritative, living guidance to the community.",
      lineage: { parents: ["Shia Islam"], divergence: "split from what became Twelver Shiism over the succession after the sixth Imam Ja'far al-Sadiq; recognized Isma'il as the seventh Imam" },
      figures: ["Isma'il ibn Ja'far", "the Fatimid caliphs", "Aga Khan IV (49th Imam of Nizari Isma'ilis)"],
      era: ["c8ce", "medieval", "modern"],
      adherents: "~15-25M (est.)",
      coreTenets: [
        "The living Imam — currently Aga Khan IV for Nizari Isma'ilis — provides authoritative guidance for the community in each age.",
        "Esoteric interpretation (ta'wil) of the Quran reveals inner meanings beyond the literal text (zahir).",
        "The Isma'ili tradition emphasizes the pursuit of knowledge, pluralism, and engagement with modernity.",
      ],
      keyThinkers: ["Nasir Khusraw — philosophical works", "the Rasa'il Ikhwan al-Safa (attributed to Isma'ili circles)", "Aga Khan IV — speeches and interviews"],
      historicalInstances: ["Fatimid Caliphate (909-1171)", "Nizari state at Alamut", "Aga Khan Development Network (modern)"],
      principalCritiques: [
        "Twelver scholars dispute the Isma'ili claim regarding the succession after Ja'far al-Sadiq.",
        "The esoteric-exoteric distinction in Isma'ili thought has drawn suspicion from Sunni and Twelver authorities, who regard ta'wil as potentially undermining the plain sense of the Quran.",
      ],
    },
    {
      name: "Zaydi Shiism",
      description: "A branch of Shia Islam that follows Zayd ibn Ali and holds that any descendant of the Prophet who leads a just uprising can be Imam.",
      tags: ["c8ce", "imamate"],
      tenet: "Zaydis hold that the Imamate is not restricted to a fixed line of descendants but belongs to any qualified member of the Prophet's family who rises against unjust rule.",
      lineage: { parents: ["Shia Islam"], divergence: "follows Zayd ibn Ali (d. 740); rejects the doctrine of a hidden or designated Imam in favor of activist Imamate" },
      figures: ["Zayd ibn Ali", "Imam al-Hadi ila'l-Haqq (founder of Zaydi state in Yemen)"],
      era: ["c8ce", "medieval"],
      adherents: "~8-10M (est., primarily Yemen)",
      coreTenets: [
        "Any learned and pious descendant of Ali and Fatimah who leads a just uprising against tyranny can claim the Imamate.",
        "Zaydi jurisprudence is closest to Sunni schools among Shia traditions, particularly the Hanafi school.",
        "The Imam need not be infallible (ma'sum) — a key difference from Twelver and Isma'ili doctrine.",
      ],
      keyThinkers: ["Zayd ibn Ali — al-Majmu' (attributed)", "Imam al-Hadi ila'l-Haqq"],
      historicalInstances: ["Zaydi Imamate in Yemen (897-1962)"],
      principalCritiques: [
        "Twelver scholars argue that the Zaydi rejection of the designated Imamate contradicts the Shia principle of divinely appointed leadership.",
        "The relationship between Zaydism and the Houthi movement in contemporary Yemen is complex and should not be reduced to sectarian identity.",
      ],
    },
    {
      name: "Sufism",
      description: "The mystical-ascetic dimension of Islam, emphasizing inner purification, direct experience of God, and the spiritual path (tariqa) under a master (shaykh).",
      tags: ["c8ce", "mysticism", "cross-cutting"],
      tenet: "Sufis seek direct experiential knowledge of God (ma'rifa) through spiritual disciplines — dhikr (remembrance), asceticism, and surrender to a spiritual guide.",
      lineage: { parents: ["Islam"], divergence: "cross-cutting: Sufism is a devotional and mystical dimension found within both Sunni and Shia Islam, not a separate sect" },
      figures: ["Rabi'a al-Adawiyya", "al-Ghazali", "Ibn Arabi", "Rumi (Jalal al-Din Balkhi)"],
      era: ["c8ce", "medieval", "modern"],
      coreTenets: [
        "The spiritual path (tariqa) involves stages (maqamat) and states (ahwal) leading toward closeness to or union with God.",
        "The shaykh or murshid (spiritual guide) is essential for navigating the spiritual path; the silsila (chain of transmission) links masters to the Prophet.",
        "Love of God (ishq) is the animating force of the spiritual life, expressed in poetry, music (sama'), and devotion.",
      ],
      keyThinkers: ["al-Ghazali — Ihya Ulum al-Din (Revival of the Religious Sciences)", "Ibn Arabi — Fusus al-Hikam", "Rumi — Masnavi"],
      historicalInstances: ["Qadiriyya, Naqshbandiyya, Chishtiyya, Mevlevi, and other tariqas (orders)", "Sufi poetry traditions (Persian, Turkish, Urdu)"],
      principalCritiques: [
        "Salafi and Wahhabi critics condemn Sufi practices — shrine visitation, saint veneration, dhikr — as innovations (bid'a) that compromise tawhid.",
        "Academic scholars debate whether Sufism originated from Islamic sources alone or incorporated elements from Neoplatonism, Christian monasticism, and Indian mysticism (Nicholson, Massignon, Karamustafa).",
      ],
    },
    {
      name: "Ibadi Islam",
      description: "A moderate branch of the Kharijite movement that predates the Sunni-Shia division, centered today in Oman.",
      tags: ["c7ce", "kharijite-origin"],
      tenet: "Ibadis hold that the Imamate belongs to the most qualified Muslim regardless of lineage, and that faith is demonstrated by deeds — but they reject the Kharijite practice of declaring other Muslims infidels.",
      lineage: { parents: ["Islam"], divergence: "emerged from the moderate Kharijite tradition; rejected both Sunni caliphal succession and Shia hereditary Imamate" },
      figures: ["Abdullah ibn Ibad", "Jabir ibn Zayd"],
      era: ["c7ce", "c8ce"],
      adherents: "~3M (est., primarily Oman)",
      coreTenets: [
        "The Imam is chosen by the community on the basis of piety and competence, not tribal or family lineage.",
        "Grave sinners are 'ungrateful' (kufr ni'ma) rather than unbelievers (kufr al-din) — a distinction from the extreme Kharijite position.",
        "Ibadi jurisprudence constitutes an independent legal tradition, neither Sunni nor Shia.",
      ],
      keyThinkers: ["Jabir ibn Zayd — attributed traditions", "Ibadi legal tradition in Oman"],
      historicalInstances: ["Rustamid dynasty (Algeria, 8th-10th c.)", "Sultanate of Oman"],
      principalCritiques: [
        "Ibadis reject the 'Kharijite' label, though historians generally classify early Ibadism as a moderate branch of the Kharijite movement.",
        "The small and geographically concentrated nature of the Ibadi community limits its visibility in broader Islamic discourse.",
      ],
    },
    {
      name: "Salafism / Wahhabism",
      description: "A puritanical reform movement calling for return to the practice of the 'pious predecessors' (al-salaf al-salih) and strict adherence to tawhid.",
      tags: ["c18", "c20", "c21", "reform"],
      tenet: "Salafis hold that authentic Islam is found in the Quran, the Sunnah, and the understanding of the first three generations of Muslims; later innovations (bid'a) must be purged.",
      lineage: { parents: ["Sunni Islam"], divergence: "Muhammad ibn Abd al-Wahhab's 18th-century movement (Wahhabism) combined with the broader Salafi call to emulate the earliest Muslim community" },
      figures: ["Muhammad ibn Abd al-Wahhab", "Ibn Taymiyya (medieval precursor)"],
      era: ["c18", "c20", "c21"],
      coreTenets: [
        "Tawhid must be purified of all shirk (polytheism): saint veneration, shrine visitation, and intercession through the dead are forbidden.",
        "The Quran and Sunnah, as understood by the salaf (first three generations), are the sole legitimate sources of religious authority.",
        "Innovation (bid'a) in worship and belief is categorically rejected; the distinction between 'good' and 'bad' innovation is itself rejected.",
      ],
      keyThinkers: ["Ibn Taymiyya — Majmu' al-Fatawa", "Muhammad ibn Abd al-Wahhab — Kitab al-Tawhid"],
      historicalInstances: ["First Saudi State (1744-1818)", "modern Kingdom of Saudi Arabia", "global Salafi movements"],
      principalCritiques: [
        "Sufi, Ash'ari, and Maturidi scholars argue that Salafism's rejection of centuries of scholarly tradition is itself an innovation that impoverishes Islamic intellectual life.",
        "Critics distinguish between quietist Salafism (apolitical), activist Salafism (political engagement), and jihadi-Salafism (violent), noting that these represent very different social projects.",
      ],
    },
    {
      name: "Ahmadiyya",
      description: "A movement founded by Mirza Ghulam Ahmad (1835-1908), who claimed to be the promised Messiah and Mahdi. Its status within Islam is disputed.",
      tags: ["c19", "c20", "messianic"],
      tenet: "Ahmadis believe that Mirza Ghulam Ahmad was the promised Messiah and Mahdi foretold in Islamic, Christian, and other traditions, sent to revive Islam through peaceful means.",
      lineage: { parents: ["Sunni Islam"], divergence: "Ghulam Ahmad's messianic and prophetic claims place the movement outside mainstream Sunni and Shia definitions of Islam, though Ahmadis consider themselves Muslim", contested: true },
      figures: ["Mirza Ghulam Ahmad", "Khalifatul Masih (successive caliphs of the Ahmadiyya community)"],
      era: ["c19", "c20"],
      adherents: "~10-20M (est., contested)",
      flagged: true,
      coreTenets: [
        "Mirza Ghulam Ahmad is, in Ahmadi belief, the metaphorical second coming of Jesus and the Mahdi promised in Islamic eschatology.",
        "Jihad by the sword has been abrogated in the present age; the true jihad is intellectual and spiritual.",
        "The Ahmadiyya caliphate (Khilafat) provides spiritual leadership to the worldwide community.",
      ],
      keyThinkers: ["Mirza Ghulam Ahmad — The Philosophy of the Teachings of Islam", "successive Khalifatul Masih"],
      principalCritiques: [
        "Mainstream Sunni and Shia authorities regard Ahmadiyya claims as incompatible with the Islamic doctrine of khatam an-nabiyyin (finality of prophethood). Pakistan constitutionally declared Ahmadis non-Muslim in 1974.",
        "Ahmadis face persecution and legal restrictions in several Muslim-majority countries, raising significant human rights concerns documented by international organizations.",
      ],
    },
    {
      name: "Nation of Islam",
      description: "An African-American religious and political movement combining Islamic elements with Black nationalism, founded by W.D. Fard Muhammad in 1930.",
      tags: ["c20", "african-american", "black-nationalism"],
      tenet: "The Nation of Islam teaches that Black people are the original people of the earth, that W.D. Fard Muhammad was God incarnate, and that Elijah Muhammad was his Messenger.",
      lineage: { parents: ["Islam"], divergence: "incorporates Islamic vocabulary and practices but departs from orthodox Islamic theology on the nature of God, prophethood, and race; mainstream Islamic authorities do not recognize it as Islamic", contested: true },
      figures: ["W.D. Fard Muhammad", "Elijah Muhammad", "Malcolm X (before departure)", "Louis Farrakhan"],
      era: ["c20"],
      adherents: "~20,000-50,000 (est.)",
      flagged: true,
      coreTenets: [
        "W.D. Fard Muhammad is, in NOI teaching, Allah (God) in person, who appeared in Detroit in 1930.",
        "The original (Black) man is divine; white people were created by a scientist named Yakub — a racial cosmogony.",
        "Economic self-sufficiency and separation from white society are necessary for Black liberation.",
      ],
      keyThinkers: ["Elijah Muhammad — Message to the Blackman in America"],
      historicalInstances: ["NOI under Elijah Muhammad (1934-1975)", "Malcolm X's departure (1964)", "Warith Deen Mohammed's reform toward Sunni Islam (1975)", "Farrakhan's refounding of the NOI"],
      principalCritiques: [
        "Orthodox Islamic scholars reject the NOI's theology — particularly the deification of Fard Muhammad and the racial cosmogony — as fundamentally incompatible with tawhid and Islamic prophetology.",
        "Historians situate the NOI within the broader tradition of African-American Black nationalist and messianic movements, emphasizing its social-justice functions in the context of American racism (Clegg, Curtis).",
      ],
    },
  ],
};

// ── FAMILY 4: OTHER ABRAHAMIC & RELATED ─────────────────────────────────────

const OTHER_ABRAHAMIC_FAMILY: Family = {
  slug: "other-abrahamic",
  name: "Other Abrahamic & Related",
  blurb: "Traditions with Abrahamic roots or connections that stand outside the Jewish-Christian-Islamic mainstream.",
  color: "teal",
  traditions: [
    {
      name: "Baha'i Faith",
      description: "A religion founded by Baha'u'llah (1817-1892), teaching the progressive revelation of God through a series of divine messengers and the unity of humanity.",
      tags: ["c19", "universalism", "progressive-revelation"],
      tenet: "Baha'is believe that Baha'u'llah is the most recent in a line of divine messengers — including Abraham, Moses, Jesus, Muhammad, and the Bab — sent to progressively reveal God's will for humanity's collective maturation.",
      lineage: { parents: ["Babism"], divergence: "Baha'u'llah declared himself the fulfillment of the Bab's prophecy; the Baha'i Faith developed as a distinct world religion with its own scriptures and administrative order" },
      figures: ["Baha'u'llah", "the Bab", "Abdu'l-Baha", "Shoghi Effendi"],
      era: ["c19", "c20"],
      adherents: "~5-8M (est.)",
      coreTenets: [
        "Progressive revelation: God has sent a succession of messengers, each suited to their era; Baha'u'llah is the messenger for the current age.",
        "The oneness of humanity: racial, national, and religious prejudices must be overcome to achieve world unity.",
        "The Baha'i Administrative Order — elected institutions at local, national, and international levels — replaces clergy.",
      ],
      keyThinkers: ["Baha'u'llah — Kitab-i-Aqdas, Kitab-i-Iqan", "Abdu'l-Baha — Some Answered Questions"],
      principalCritiques: [
        "Islamic authorities, particularly in Iran, regard the Baha'i Faith as heretical — a post-Islamic religion that contradicts the finality of prophethood (khatam an-nabiyyin). Baha'is in Iran face severe persecution.",
        "Scholars of new religious movements note the tension between Baha'i universalism and the community's internal governance structure, which limits dissent (MacEoin, Cole).",
      ],
    },
    {
      name: "Babism",
      description: "A 19th-century Iranian religious movement founded by the Bab (Siyyid Ali Muhammad), who declared himself the Gate (Bab) to the Hidden Imam.",
      tags: ["c19", "iran", "messianic"],
      tenet: "The Bab proclaimed that he was the promised Qa'im (the returned Hidden Imam of Twelver Shiism), inaugurating a new religious dispensation and abrogating Islamic law.",
      lineage: { parents: ["Twelver Shiism"], divergence: "the Bab's messianic claim broke with Twelver Shiism's expectation of the Hidden Imam's return; the movement was violently suppressed" },
      figures: ["the Bab (Siyyid Ali Muhammad Shirazi)"],
      era: ["c19"],
      coreTenets: [
        "The Bab is the promised Qa'im of Shia eschatology, inaugurating a new prophetic cycle.",
        "Islamic law (sharia) is abrogated; the Bab's own revealed texts (the Bayan) constitute a new dispensation.",
        "The Bab's mission prepares the way for 'Him whom God shall make manifest' — a future messianic figure.",
      ],
      keyThinkers: ["the Bab — the Bayan (Persian and Arabic)"],
      historicalInstances: ["Babi revolts in Iran (1848-53)", "Execution of the Bab (1850)"],
      principalCritiques: [
        "Twelver Shia authorities rejected the Bab's claim as fraudulent and the Babi movement as heretical.",
        "Historians debate the degree to which Babism was a social revolutionary movement versus a purely religious one (Amanat).",
      ],
    },
    {
      name: "Druze",
      description: "A monotheistic, esoteric religion originating in 11th-century Egypt, venerating al-Hakim bi-Amr Allah and maintaining a closed community with secret scriptures.",
      tags: ["c11ce", "esoteric", "closed-community"],
      tenet: "The Druze profess a strict unitarianism (tawhid) and hold that the Fatimid caliph al-Hakim bi-Amr Allah was the final manifestation of God in human form.",
      lineage: { parents: ["Isma'ili Shiism"], divergence: "originated within the Fatimid Isma'ili milieu but developed a distinct theology; the community closed to new members after 1043 CE" },
      figures: ["Hamza ibn Ali", "al-Hakim bi-Amr Allah"],
      era: ["c11ce"],
      adherents: "~1-2M (est., Lebanon, Syria, Israel)",
      coreTenets: [
        "Tawhid (divine unity) is the supreme principle; the Druze call themselves al-Muwahhidun (Unitarians).",
        "The community is closed: one can only be born Druze, and proselytism is forbidden.",
        "Transmigration of the soul (taqammus) replaces the Islamic concepts of heaven and hell; at death, the soul is immediately reborn into another Druze body.",
      ],
      keyThinkers: ["Rasa'il al-Hikma (Epistles of Wisdom — the Druze sacred scriptures, restricted to the initiated)"],
      principalCritiques: [
        "Most Islamic authorities do not recognize the Druze as Muslim due to their theology of divine incarnation and transmigration.",
        "The secrecy of Druze scripture and the distinction between the initiated (uqqal) and uninitiated (juhhal) make external scholarly study difficult (Firro, Swayd).",
      ],
    },
    {
      name: "Yazidism",
      description: "An ancient Kurdish religion centered on the worship of Melek Taus (the Peacock Angel) and the sanctity of Lalish temple.",
      tags: ["ancient", "kurdish", "oral-tradition"],
      tenet: "Yazidis hold that God created the world and entrusted it to seven holy beings (heft sirr), chief among them Melek Taus (the Peacock Angel), who repented his disobedience and was restored.",
      lineage: { parents: [], divergence: "root — the origins of Yazidism are debated; scholars variously trace it to ancient Mesopotamian religion, Iranian religion, and Sufi influences, though Yazidis understand their tradition as primordial", contested: true },
      figures: ["Sheikh Adi ibn Musafir (12th-century reformer)", "Melek Taus (the Peacock Angel)"],
      era: ["ancient", "medieval"],
      adherents: "~500,000-1M (est., primarily Iraqi Kurdistan)",
      coreTenets: [
        "Melek Taus (the Peacock Angel) is God's chief agent in the world; the Yazidi narrative of his fall and restoration is NOT equivalent to the Islamic or Christian Satan — Yazidis reject this identification as a slander.",
        "Lalish temple in Iraqi Kurdistan is the holiest site; pilgrimage there is a central religious obligation.",
        "The community is endogamous (marriage within the faith) and organized into a caste system of sheikhs, pirs, and murids.",
      ],
      keyThinkers: ["Oral tradition and sacred hymns (qawls)", "Kiteba Cilwe and Mishefa Res (Black Book) — debated authenticity"],
      principalCritiques: [
        "The identification of Melek Taus with Satan by some Muslim and Christian neighbors has led to centuries of persecution, most recently the ISIS genocide against Yazidis (2014), recognized by the UN.",
        "The origins and classification of Yazidism — syncretic, indigenous, or sui generis — remain actively debated among scholars (Kreyenbroek, Asatrian).",
      ],
    },
    {
      name: "Mandaeism",
      description: "An ancient Gnostic religion centered on the prophet Yahya (John the Baptist), ritual baptism (masbuta), and the worship of the Great Life (Hayyi Rabbi).",
      tags: ["ancient", "gnostic", "baptismal"],
      tenet: "Mandaeans hold that Yahya (John the Baptist) is the true prophet, that ritual immersion (masbuta) in 'living water' is essential for spiritual purification, and that the material world was created by a demiurge.",
      lineage: { parents: [], divergence: "root — one of the last surviving Gnostic religions; the relationship to other ancient Gnostic, Jewish, and Baptist movements is debated" },
      figures: ["Yahya (John the Baptist)", "Adam (revered as the first Mandaean)"],
      era: ["ancient"],
      adherents: "~60,000-100,000 (est., Iraq, Iran, and diaspora)",
      coreTenets: [
        "The Great Life (Hayyi Rabbi) is the supreme deity; the material world was created by lesser beings (demiurge cosmology).",
        "Masbuta (ritual immersion in flowing water) must be performed regularly for spiritual purification.",
        "The Ginza Rabba (Great Treasure) is the primary scripture, containing cosmological, ethical, and liturgical texts.",
      ],
      keyThinkers: ["Ginza Rabba (scripture)", "Book of John (Drashah d-Yahia)"],
      principalCritiques: [
        "The historical relationship between Mandaeism and other ancient movements — Jewish baptismal sects, early Christianity, Manichaeism — is the subject of long-standing scholarly debate (Rudolph, Buckley).",
        "As a small, persecuted minority in Iraq and Iran, the Mandaean community faces existential demographic pressures and displacement.",
      ],
    },
    {
      name: "Rastafari",
      description: "A spiritual and political movement originating in 1930s Jamaica, venerating Haile Selassie I of Ethiopia as the returned Messiah and emphasizing African redemption.",
      tags: ["c20", "african-diaspora", "jamaica"],
      tenet: "Rastafari adherents hold that Haile Selassie I (Ras Tafari) is the returned Christ and the fulfillment of biblical prophecy, and that Africa (Zion) is the promised land for the African diaspora.",
      lineage: { parents: [], divergence: "root — draws on biblical interpretation (especially Ethiopian and Old Testament themes), Marcus Garvey's Pan-Africanism, and Ethiopian royal theology" },
      figures: ["Haile Selassie I", "Marcus Garvey (regarded as a prophet)", "Leonard Howell"],
      era: ["c20"],
      adherents: "~700,000-1M (est.)",
      coreTenets: [
        "Haile Selassie I is, in Rastafari belief, the returned Messiah, King of Kings, Lord of Lords, Conquering Lion of the Tribe of Judah.",
        "Babylon — representing Western colonial and capitalist systems — oppresses African peoples; Zion (Africa/Ethiopia) is the promised homeland.",
        "Ital living (natural diet), the wearing of dreadlocks, and the sacramental use of cannabis ('the holy herb') are common practices, though not universal.",
      ],
      keyThinkers: ["Marcus Garvey — Pan-Africanist philosophy", "Leonard Howell — The Promised Key (attributed)"],
      historicalInstances: ["Back-to-Africa movement", "Ethiopian World Federation", "Reggae as cultural vehicle (Bob Marley)"],
      principalCritiques: [
        "Haile Selassie himself was Ethiopian Orthodox and never publicly affirmed his divinity, creating a theological tension within the movement.",
        "Scholars note that Rastafari encompasses diverse mansions (Nyahbinghi, Bobo Ashanti, Twelve Tribes of Israel) with significantly different beliefs and practices, resisting unified doctrinal description (Chevannes, Edmonds).",
      ],
    },
  ],
};

export const FAMILIES: Family[] = [
  JUDAISM_FAMILY,
  CHRISTIANITY_FAMILY,
  ISLAM_FAMILY,
  OTHER_ABRAHAMIC_FAMILY,
];
