import type { Family } from "./types";

// ── SECTION C (continued) + SECTION D + SECTION E ───────────────────────────

export const FAMILIES_15_21: Family[] = [
  // ── Family 15 — Vedic, Hindu & Jain Philosophy ────────────────────────────
  {
    slug: "vedic-hindu-jain",
    number: 15,
    name: "Vedic, Hindu & Jain Philosophy",
    blurb: "The six orthodox Hindu schools (astika), plus Jain perspectivism and Yoga — a tradition of metaphysics, epistemology, and liberation.",
    section: "C",
    color: "amber",
    entries: [
      {
        name: "Samkhya dualism",
        description: "Reality consists of pure consciousness (Purusha) and primordial nature (Prakriti).",
        keyThesis: "Samkhya: Purusha (consciousness, plural, passive) and Prakriti (matter/nature, singular, active) are independent ultimate principles. Liberation consists in Purusha recognizing its distinctness from Prakriti and ceasing false identification with the products of Prakriti.",
        keyThinkers: ["Kapila (attributed)", "Isvarakrishna — Samkhyakarika"],
        influencedBy: [],
        tags: ["Samkhya", "Purusha", "Prakriti", "dualism", "Hindu"],
      },
      {
        name: "Advaita Vedanta",
        description: "Non-dual monism: Brahman alone is real; the individual self and world are not ultimately separate.",
        keyThesis: "Shankara: the ultimate reality is Brahman — pure, undifferentiated consciousness. Atman (individual self) is identical to Brahman ('Tat tvam asi' — That thou art). The apparent multiplicity of the world is maya (illusion, superimposition). Liberation (moksha) is recognition of this non-duality.",
        keyThinkers: ["Adi Shankara — Brahmasutrabhashya", "Shankara — Vivekachudamani"],
        influencedBy: ["Samkhya dualism"],
        tags: ["Advaita", "Vedanta", "Brahman", "non-duality", "Shankara"],
      },
      {
        name: "Vishishtadvaita (Ramanuja)",
        description: "Qualified non-dualism: the world and individual selves are real modes of Brahman.",
        keyThesis: "Ramanuja: Brahman is a personal God (Vishnu/Narayana) who contains the world and individual selves as modes or attributes (visheshanas). Unity-in-difference: selves and matter are real but exist as the body of God. Devotion (bhakti) is the primary path to liberation.",
        keyThinkers: ["Ramanuja — Sri Bhashya"],
        influencedBy: ["Advaita Vedanta"],
        tags: ["Vishishtadvaita", "Ramanuja", "bhakti", "qualified-nondualism"],
        status: "contested",
      },
      {
        name: "Nyaya epistemology",
        description: "The Hindu school of logic and epistemology — four pramanas (valid sources of knowledge).",
        keyThesis: "Nyaya posits four pramanas: perception (pratyaksha), inference (anumana), analogy (upamana), and testimony (sabda). Inference has a five-step syllogistic form. The school also develops theistic arguments (Udayana's proofs of God's existence).",
        keyThinkers: ["Aksapada Gautama — Nyayasutra", "Udayana", "Vatsyayana"],
        influencedBy: [],
        tags: ["Nyaya", "pramana", "inference", "epistemology"],
      },
      {
        name: "Vaisheshika atomism",
        description: "The world consists of eternal atoms classified into distinct categories (padarthas).",
        keyThesis: "Vaisheshika: nine categories of substance (dravya), including earth, water, fire, air, and ether atoms. Atoms are eternal and indivisible; combination produces complex objects. The system was integrated with Nyaya logic.",
        keyThinkers: ["Kanada — Vaisheshikasutra"],
        influencedBy: ["Nyaya epistemology"],
        tags: ["Vaisheshika", "atomism", "categories", "padarthas"],
      },
      {
        name: "Mimamsa — philosophy of language and ritual",
        description: "The eternal, self-validating nature of the Vedas and the philosophy of Vedic language.",
        keyThesis: "Purva Mimamsa: the Vedas are eternal, uncreated (apaurusheya), and self-validating. Dharma is known only through Vedic injunctions. Developed sophisticated philosophy of language: word-meaning is eternal; sentences produce new knowledge through context-sensitive rules.",
        keyThinkers: ["Jaimini — Mimamsasutra", "Kumarila Bhatta", "Prabhakara"],
        influencedBy: [],
        tags: ["Mimamsa", "Vedas", "language", "dharma"],
      },
      {
        name: "Jain perspectivism (anekantavada)",
        description: "Reality is many-sided; any single perspective captures only a partial truth.",
        keyThesis: "Jain logic: every proposition can be qualified by 'in some respect' (syat). Anekantavada: no single viewpoint has a monopoly on truth; reality is complex and can only be understood from multiple standpoints. Syadvada: seven-valued predicate logic.",
        keyThinkers: ["Mahavira (attributed)", "Umasvati — Tattvartha Sutra", "Haribhadra"],
        influencedBy: [],
        tags: ["Jain", "anekantavada", "perspectivism", "syadvada"],
      },
      {
        name: "Yoga philosophy (Patanjali)",
        description: "The philosophical system of Yoga — epistemology, metaphysics, and practice of liberation.",
        keyThesis: "Patanjali: Yoga is the cessation of the fluctuations of consciousness (chitta-vritti-nirodha). Built on Samkhya metaphysics; eight-limbed path (ashtanga) leads from external ethical practice through meditation to samadhi (absorption). The goal is kaivalya: isolation of Purusha from Prakriti.",
        keyThinkers: ["Patanjali — Yoga Sutras", "Vyasa — Yogabhasya"],
        influencedBy: ["Samkhya dualism"],
        tags: ["Yoga", "Patanjali", "chitta-vritti", "samadhi"],
      },
    ],
  },

  // ── Family 16 — Islamic Philosophy ───────────────────────────────────────
  {
    slug: "islamic-philosophy",
    number: 16,
    name: "Islamic Philosophy",
    blurb: "Kalam, falsafa, Sufism, and the synthesis of Aristotelian philosophy with Islamic theology.",
    section: "C",
    color: "sky",
    entries: [
      {
        name: "Kalam — Islamic dialectical theology",
        description: "Rational defense and elaboration of Islamic theological doctrines.",
        keyThesis: "Mutazilites: God is absolutely one; the Quran is created; humans have free will (required for divine justice). Asharites (dominant): divine will is sovereign; human acts are 'acquired' not self-caused; reason is subordinate to revelation.",
        keyThinkers: ["Al-Ashari", "Al-Maturidi", "Al-Ghazali — Incoherence of the Philosophers"],
        influencedBy: [],
        tags: ["kalam", "theology", "Islam", "Mutazila", "Ashari"],
      },
      {
        name: "Al-Kindi — the Arab Peripatetic",
        description: "The first major Islamic philosopher, adapting Greek philosophy to Islamic context.",
        keyThesis: "Al-Kindi (9th c.): philosophy and religion seek the same truth by different methods. Neo-Platonic emanation explains the creation; God is the First Cause and True One. First to define philosophy as 'knowledge of the true nature of things.'",
        keyThinkers: ["Al-Kindi — On First Philosophy"],
        influencedBy: ["Kalam — Islamic dialectical theology"],
        tags: ["Al-Kindi", "Peripatetic", "first-philosophy"],
      },
      {
        name: "Avicenna — essence and existence",
        description: "Ibn Sina's synthesis of Aristotle and Neoplatonism — the floating man and the essence/existence distinction.",
        keyThesis: "Ibn Sina (Avicenna): the distinction between a thing's essence (mahiyya) and its existence (wujud) — existence is an accidental attribute in contingent beings. The floating man argument: I can think of myself as having no body, therefore the soul is independent. Influenced scholastic philosophy.",
        keyThinkers: ["Ibn Sina (Avicenna) — Book of Healing", "Avicenna — The Book of Salvation"],
        influencedBy: ["Al-Kindi — the Arab Peripatetic"],
        tags: ["Avicenna", "Ibn-Sina", "essence-existence", "floating-man"],
      },
      {
        name: "Averroes — the commentator on Aristotle",
        description: "Ibn Rushd's defense of Aristotelianism against Al-Ghazali's attack.",
        keyThesis: "Ibn Rushd (Averroes): philosophy and religion are compatible but operate on different levels; philosophy has priority in demonstrative matters. Refutes Al-Ghazali's Incoherence of the Philosophers in Incoherence of the Incoherence. Transmitted Aristotle to medieval Europe.",
        keyThinkers: ["Ibn Rushd (Averroes) — Incoherence of the Incoherence", "Averroes — Middle and Long Commentaries on Aristotle"],
        influencedBy: ["Avicenna — essence and existence"],
        tags: ["Averroes", "Ibn-Rushd", "Aristotle", "commentator"],
      },
      {
        name: "Al-Ghazali — the incoherence of the philosophers",
        description: "Devastating critique of Islamic Neoplatonism; defense of revelation over unaided reason.",
        keyThesis: "Al-Ghazali: the Muslim Peripatetics (Avicenna, Al-Farabi) commit twenty heretical errors, including the eternity of the world, denial of bodily resurrection, and God's ignorance of particulars. Reason cannot establish metaphysics; only Sufi experience and revelation are adequate.",
        keyThinkers: ["Al-Ghazali — The Incoherence of the Philosophers", "Al-Ghazali — Revival of the Religious Sciences"],
        influencedBy: ["Kalam — Islamic dialectical theology"],
        tags: ["Al-Ghazali", "incoherence", "Sufism", "revelation"],
      },
      {
        name: "Illuminationism (Suhrawardi)",
        description: "A mystical philosophy of light: reality is a hierarchy of luminous principles.",
        keyThesis: "Suhrawardi (12th c.): ultimate reality is the Light of Lights (God); all existence is a gradation of light and darkness. Direct mystical illumination (ishraq) supplements discursive reasoning. Persian Platonism fused with Zoroastrian imagery.",
        keyThinkers: ["Suhrawardi — The Philosophy of Illumination"],
        influencedBy: ["Avicenna — essence and existence"],
        tags: ["Suhrawardi", "illuminationism", "ishraq", "light"],
      },
      {
        name: "Ibn Khaldun — philosophy of history",
        description: "The first systematic theory of historical change, social cohesion, and the cycles of civilizations.",
        keyThesis: "Ibn Khaldun (14th c.): 'asabiyya (social solidarity/group feeling) is the force that builds and sustains empires; its erosion leads to decline. Civilizations move in cyclical patterns. The Muqaddimah is the first systematic philosophy of history and social science.",
        keyThinkers: ["Ibn Khaldun — Muqaddimah (Prolegomena)"],
        influencedBy: ["Kalam — Islamic dialectical theology"],
        tags: ["Ibn-Khaldun", "history", "asabiyya", "civilization"],
      },
      {
        name: "Islamic ethics",
        description: "Philosophical approaches to ethics within Islam — reason, revelation, and virtue.",
        keyThesis: "Three main approaches: kalam-ethics (divine command tied to divine justice); Miskawayh's virtue ethics drawing on Aristotle; and Sufi ethics of the self's purification. Contested: whether reason alone can determine moral good, or only revelation.",
        keyThinkers: ["Miskawayh — The Refinement of Character", "Al-Farabi — Attainment of Happiness"],
        influencedBy: ["Al-Kindi — the Arab Peripatetic"],
        tags: ["Islamic-ethics", "virtue", "revelation", "reason"],
        status: "contested",
      },
    ],
  },

  // ── SECTION D — APPLIED PHILOSOPHY ──────────────────────────────────────────

  // ── Family 17 — Philosophy of Language ────────────────────────────────────
  {
    slug: "philosophy-of-language",
    number: 17,
    name: "Philosophy of Language",
    blurb: "Reference, meaning, speech acts, implicature, and the semantics-pragmatics interface.",
    section: "D",
    color: "violet",
    entries: [
      {
        name: "Frege's sense/reference distinction",
        description: "Two expressions can have the same reference but different cognitive senses.",
        keyThesis: "Frege: 'Hesperus is Phosphorus' is informative; 'Hesperus is Hesperus' is trivial — yet both are true because Hesperus = Phosphorus (same reference). They differ in sense (Sinn) — mode of presentation. The sense of a sentence is the Thought it expresses; its reference is a truth-value.",
        keyThinkers: ["Gottlob Frege — 'Über Sinn und Bedeutung' (1892)"],
        influencedBy: [],
        tags: ["Frege", "sense", "reference", "meaning"],
      },
      {
        name: "Russell's theory of descriptions",
        description: "Definite descriptions ('the present King of France') are quantificational, not referential.",
        keyThesis: "Russell: 'The F is G' means 'There is exactly one F, and it is G.' Descriptions do not refer — they are incomplete symbols. 'The present King of France is bald' is false (not meaningless), because there is no present King of France. Resolves puzzles about non-existence.",
        keyThinkers: ["Bertrand Russell — 'On Denoting' (1905)"],
        influencedBy: ["Frege's sense/reference distinction"],
        tags: ["Russell", "descriptions", "quantification", "reference"],
      },
      {
        name: "Causal theory of reference",
        description: "Names and natural kind terms refer via a causal-historical chain, not descriptive content.",
        keyThesis: "Kripke: names are rigid designators — they pick out the same individual in every possible world in which that individual exists. Reference is fixed by an initial 'baptism' and transmitted causally. 'Hesperus is Phosphorus' is necessarily true but known a posteriori.",
        keyThinkers: ["Saul Kripke — Naming and Necessity (1972)", "Hilary Putnam — 'The Meaning of Meaning'"],
        influencedBy: ["Russell's theory of descriptions"],
        tags: ["Kripke", "causal-reference", "rigid-designators", "necessary-a-posteriori"],
      },
      {
        name: "Speech act theory",
        description: "Utterances do not merely describe — they perform actions: promising, asserting, ordering.",
        keyThesis: "Austin: 'How to Do Things with Words' — locutionary (what is said), illocutionary (what act is performed), perlocutionary (what effect is produced). Searle systematizes: illocutionary acts have constitutive rules; sincerity conditions must obtain.",
        keyThinkers: ["J.L. Austin — How to Do Things with Words", "John Searle — Speech Acts"],
        influencedBy: ["Ordinary language philosophy"],
        tags: ["speech-acts", "Austin", "Searle", "illocution"],
      },
      {
        name: "Gricean implicature",
        description: "Speakers communicate more than they literally say, governed by conversational maxims.",
        keyThesis: "Grice's Co-operative Principle: conversational contributions should be as informative, truthful, relevant, and perspicuous as required. Scalar implicature: 'some' implicates 'not all'. Cancellable implicatures arise from reasoning about the speaker's rational behavior.",
        keyThinkers: ["H.P. Grice — 'Logic and Conversation' (1975)"],
        influencedBy: ["Speech act theory"],
        tags: ["Grice", "implicature", "pragmatics", "maxims"],
      },
      {
        name: "Truth-conditional semantics",
        description: "The meaning of a sentence is its truth-conditions — what the world must be like for it to be true.",
        keyThesis: "Davidson's program: a theory of meaning for a language is a finite Tarski-style truth theory satisfying the T-schema ('S is true iff p'). Understanding a sentence is knowing its truth-conditions. Intensional contexts require possible-worlds semantics.",
        keyThinkers: ["Donald Davidson — 'Truth and Meaning'", "Alfred Tarski — 'The Concept of Truth'"],
        influencedBy: ["Frege's sense/reference distinction"],
        tags: ["truth-conditions", "Davidson", "Tarski", "semantics"],
      },
      {
        name: "Semantic externalism",
        description: "Meaning is not entirely in the head — the environment partly constitutes word-meanings.",
        keyThesis: "Putnam: 'meanings just ain't in the head.' Twin Earth thought experiment: my watery twin and I have identical internal states yet 'water' means different things because the external substances differ (H2O vs XYZ). Natural kind terms have extensions fixed by the world.",
        keyThinkers: ["Hilary Putnam — 'The Meaning of Meaning' (1975)"],
        influencedBy: ["Causal theory of reference"],
        tags: ["Putnam", "externalism", "Twin-Earth", "natural-kinds"],
      },
      {
        name: "Contextualism in semantics",
        description: "The content of many expressions is context-sensitive — 'I', 'here', 'tall', 'knows'.",
        keyThesis: "Demonstratives and indexicals have character (a rule) plus content (what is said on an occasion). Gradable adjectives like 'tall' and epistemic terms like 'know' are context-sensitive in ways that matter philosophically. Debates about knowledge-contextualism mirror those in epistemology.",
        keyThinkers: ["David Kaplan — 'Demonstratives'", "David Lewis — 'Elusive Knowledge'"],
        influencedBy: ["Truth-conditional semantics"],
        tags: ["context", "indexicals", "Kaplan", "content"],
      },
      {
        name: "The Sapir-Whorf hypothesis",
        description: "Linguistic structure influences or determines the cognitive categories available to speakers.",
        keyThesis: "Strong (Whorfian) thesis: language determines thought — speakers of different languages inhabit different conceptual worlds. Weak thesis: language influences non-linguistically-determined cognition. Experimental support is mixed; strong linguistic determinism is largely rejected.",
        keyThinkers: ["Edward Sapir", "Benjamin Lee Whorf", "Steven Pinker — The Language Instinct (critic)"],
        influencedBy: ["Truth-conditional semantics"],
        tags: ["Sapir-Whorf", "linguistic-relativity", "cognition"],
        status: "contested",
      },
      {
        name: "Formal semantics and montague grammar",
        description: "Natural language semantics modeled as a compositional mapping into a formal model-theoretic object language.",
        keyThesis: "Montague: natural language is in principle amenable to formal semantic treatment — phrases denote objects, events, or sets in models; sentences denote truth-values. The compositionality principle: sentence meaning is a function of constituent meanings and mode of combination.",
        keyThinkers: ["Richard Montague — 'The Proper Treatment of Quantification in Ordinary English'"],
        influencedBy: ["Truth-conditional semantics"],
        tags: ["Montague", "formal-semantics", "compositionality"],
        xref: ["mathematics"],
      },
      {
        name: "Deflationary theories of truth",
        description: "Saying 'it is true that P' adds nothing substantive to asserting P — truth has no deep nature.",
        keyThesis: "The disquotational schema: ' \"Snow is white\" is true iff snow is white.' Truth is just a device of semantic ascent (Quine) or generalization ('Everything she said is true'). There is no substantive property of truth to explain — thus no correspondence or coherence theory needed.",
        keyThinkers: ["W.V.O. Quine — Philosophy of Logic", "Paul Horwich — Truth"],
        influencedBy: ["Truth-conditional semantics"],
        tags: ["deflationism", "disquotation", "truth"],
      },
    ],
  },

  // ── Family 18 — Philosophy of Mathematics ─────────────────────────────────
  {
    slug: "philosophy-of-mathematics",
    number: 18,
    name: "Philosophy of Mathematics",
    blurb: "The ontology of mathematical objects, the epistemology of mathematical knowledge, and the foundations debate.",
    section: "D",
    color: "indigo",
    entries: [
      {
        name: "Logicism",
        description: "Mathematics is reducible to pure logic — arithmetic is logic in disguise.",
        keyThesis: "Frege: the natural numbers are extensions of concepts; arithmetic follows from logical laws alone. Russell-Whitehead Principia tried to complete the programme. Gödel's incompleteness theorems and Russell's Paradox exposed fundamental difficulties.",
        keyThinkers: ["Gottlob Frege — Grundgesetze der Arithmetik", "Bertrand Russell & A.N. Whitehead — Principia Mathematica"],
        influencedBy: ["Predicate (first-order) logic"],
        tags: ["logicism", "Frege", "Russell", "foundations"],
        xref: ["mathematics"],
      },
      {
        name: "Formalism (Hilbert's programme)",
        description: "Mathematics is a formal game with symbols; the programme sought a consistency proof.",
        keyThesis: "Hilbert: mathematical theories are syntactic structures — their consistency must be proved by finitary metamathematical means. Gödel's Second Incompleteness Theorem showed that no such proof is possible by the theory's own means.",
        keyThinkers: ["David Hilbert — 'On the Infinite'", "Paul Bernays"],
        influencedBy: ["Proof theory"],
        tags: ["formalism", "Hilbert", "consistency", "programme"],
        xref: ["mathematics"],
      },
      {
        name: "Mathematical intuitionism",
        description: "Mathematics is a mental construction; existence requires constructive proof.",
        keyThesis: "Brouwer: mathematics is a languageless mental construction; the law of excluded middle is not universally valid for infinite domains. A mathematical object exists only if there is an effective construction of it. This leads to a mathematics that is weaker but philosophically defensible.",
        keyThinkers: ["L.E.J. Brouwer", "Arend Heyting", "Michael Dummett — Elements of Intuitionism"],
        influencedBy: ["Intuitionistic logic"],
        tags: ["intuitionism", "Brouwer", "construction", "excluded-middle"],
        xref: ["mathematics"],
      },
      {
        name: "Mathematical Platonism (Gödel)",
        description: "Mathematical objects exist abstractly; mathematical intuition allows us to perceive them.",
        keyThesis: "Gödel: the axioms of set theory force themselves upon us as true; mathematical intuition is a faculty analogous to sense perception. The incompleteness theorems show that mathematical truth outruns formal provability — supporting non-formalist realism.",
        keyThinkers: ["Kurt Gödel — 'What is Cantor's Continuum Problem?'", "Penelope Maddy"],
        influencedBy: ["Mathematical Platonism"],
        tags: ["Gödel", "Platonism", "intuition", "abstract-objects"],
        xref: ["mathematics"],
      },
      {
        name: "Fictionalism",
        description: "Mathematical statements are false — mathematical objects are useful fictions.",
        keyThesis: "Hartry Field: we can nominalise science — explain physical phenomena without quantifying over numbers. Mathematical statements are like statements about Sherlock Holmes: their truth conditions invoke non-existent objects, so they are strictly false but useful.",
        keyThinkers: ["Hartry Field — Science Without Numbers"],
        influencedBy: ["Mathematical Platonism"],
        tags: ["fictionalism", "Field", "nominalism"],
        xref: ["mathematics"],
      },
      {
        name: "Structuralism",
        description: "Mathematical objects are positions in structures; what matters is the pattern, not the objects.",
        keyThesis: "Shapiro: mathematical objects have no intrinsic properties beyond their structural roles. The natural numbers just are the progression 0, 1, 2, ... — any progression realizing the Dedekind-Peano axioms will do. There is no unique object that is 'the number 2.'",
        keyThinkers: ["Stewart Shapiro — Philosophy of Mathematics: Structure and Ontology", "Michael Resnik"],
        influencedBy: ["Mathematical Platonism"],
        tags: ["structuralism", "Shapiro", "patterns"],
        xref: ["mathematics"],
      },
      {
        name: "Indispensability argument",
        description: "We ought to believe in mathematical objects because they are indispensable to science.",
        keyThesis: "Quine-Putnam: our best scientific theories quantify over mathematical entities; we are committed to the existence of whatever our best theories quantify over; therefore we are committed to mathematical entities.",
        keyThinkers: ["W.V.O. Quine", "Hilary Putnam — 'What is Mathematical Truth?'"],
        influencedBy: ["Logicism"],
        tags: ["indispensability", "Quine-Putnam", "confirmation"],
        xref: ["mathematics"],
      },
      {
        name: "Predicativism",
        description: "Definitions that are impredicative — defining a totality by reference to itself — are illegitimate.",
        keyThesis: "Russell's vicious circle principle: whatever involves all of a collection must not be one of the collection. Predicativist mathematics avoids impredicative definitions, yielding a conservative fragment of classical mathematics. Weyl and Feferman developed predicative analysis.",
        keyThinkers: ["Bertrand Russell", "Hermann Weyl — Das Kontinuum", "Solomon Feferman"],
        influencedBy: ["Formalism (Hilbert's programme)"],
        tags: ["predicativism", "impredicativity", "foundations"],
        xref: ["mathematics"],
      },
    ],
  },

  // ── Family 19 — Bioethics & Applied Ethics ─────────────────────────────────
  {
    slug: "bioethics-applied-ethics",
    number: 19,
    name: "Bioethics & Applied Ethics",
    blurb: "Ethical frameworks applied to medicine, research, technology, the environment, and AI.",
    section: "D",
    color: "teal",
    entries: [
      {
        name: "Principlism",
        description: "Four mid-level principles guide biomedical ethics: autonomy, beneficence, non-maleficence, justice.",
        keyThesis: "Beauchamp and Childress: moral disagreement in biomedical contexts can be managed by applying four prima facie principles that cut across ethical theories. The principles require specification and balancing in concrete cases.",
        keyThinkers: ["Tom Beauchamp & James Childress — Principles of Biomedical Ethics"],
        influencedBy: [],
        tags: ["principlism", "bioethics", "four-principles"],
      },
      {
        name: "Autonomy and informed consent",
        description: "Patients have the right to make their own medical decisions based on adequate information.",
        keyThesis: "Respect for autonomy requires that competent adults receive adequate information (diagnosis, alternatives, risks, benefits) and be free to decide without coercion. Informed consent is both ethical requirement and legal standard; its limits in emergencies and with incompetent patients are debated.",
        keyThinkers: ["Tom Beauchamp", "Paul Appelbaum"],
        influencedBy: ["Principlism"],
        tags: ["autonomy", "consent", "paternalism"],
      },
      {
        name: "Justice in healthcare",
        description: "Who gets what healthcare, and by what principle?",
        keyThesis: "Egalitarian (Daniels): healthcare protects fair equality of opportunity — people are entitled to adequate care. Libertarian: healthcare is a commodity; entitlement arises from purchase. Priority view (Parfit): give priority to the worse off. The allocation of scarce resources (transplant organs, ICU beds) crystallizes these disputes.",
        keyThinkers: ["Norman Daniels — Just Health", "Frances Kamm"],
        influencedBy: ["Principlism", "Justice as fairness (Rawls)"],
        tags: ["justice", "allocation", "healthcare"],
        xref: ["ideologies"],
      },
      {
        name: "End-of-life ethics",
        description: "The morality of euthanasia, assisted dying, and withdrawing treatment.",
        keyThesis: "Voluntary active euthanasia: directly causing death at the patient's request. Physician-assisted suicide: physician provides means but patient acts. Doctrine of double effect: death as foreseen side-effect of pain control is permissible. Contested: where to draw the line; personhood at end of life.",
        keyThinkers: ["James Rachels — 'Active and Passive Euthanasia'", "Dan Brock", "Frances Kamm"],
        influencedBy: ["Autonomy and informed consent"],
        tags: ["euthanasia", "assisted-dying", "end-of-life"],
        status: "contested",
      },
      {
        name: "Research ethics",
        description: "The moral requirements governing research on human subjects.",
        keyThesis: "The Belmont Report's three principles (respect for persons, beneficence, justice) govern clinical research. The Nuremberg Code and Declaration of Helsinki codify voluntary informed consent. Special issues: research in developing countries, genetics, compensation for harm.",
        keyThinkers: ["The Belmont Report (1979)", "Ruth Faden & Tom Beauchamp — A History and Theory of Informed Consent"],
        influencedBy: ["Autonomy and informed consent"],
        tags: ["research", "Belmont", "human-subjects"],
      },
      {
        name: "Neuroethics",
        description: "Ethical issues raised by neuroscience — enhancement, autonomy, and the nature of the self.",
        keyThesis: "Cognitive enhancement (modafinil, transcranial stimulation): is it fairness-enhancing or authenticity-threatening? Neuroimaging in court: can brain scans establish diminished responsibility? Personal identity questions arise when brain interventions alter personality.",
        keyThinkers: ["Walter Glannon — Brain, Body, and Mind", "Paul Wolpe", "Martha Farah"],
        influencedBy: ["Bioethics & Applied Ethics — principlism"],
        tags: ["neuroethics", "enhancement", "brain"],
        xref: ["computer-science"],
      },
      {
        name: "Animal ethics",
        description: "The moral status of non-human animals — sentience, rights, and interests.",
        keyThesis: "Singer: animals capable of suffering have interests that must be given equal consideration; speciesism is like racism. Regan: animals who are 'subjects-of-a-life' have inherent value and rights. Contractarian approaches (Carruthers) struggle to account for animal welfare directly.",
        keyThinkers: ["Peter Singer — Animal Liberation (1975)", "Tom Regan — The Case for Animal Rights"],
        influencedBy: ["Classical utilitarianism"],
        tags: ["animal-ethics", "Singer", "Regan", "speciesism"],
      },
      {
        name: "Environmental ethics",
        description: "The moral obligations humans have toward the non-human natural world.",
        keyThesis: "Anthropocentric: only human interests are directly morally relevant; nature has instrumental value. Biocentric (Taylor): all living things have inherent worth. Ecocentric (Leopold, Rolston): ecosystems and species have intrinsic value beyond their members. Deep ecology: humans are not the center of value.",
        keyThinkers: ["Aldo Leopold — A Sand County Almanac", "Paul Taylor — Respect for Nature", "Holmes Rolston III", "Arne Naess"],
        influencedBy: ["Classical utilitarianism"],
        tags: ["environmental-ethics", "anthropocentrism", "intrinsic-value"],
      },
      {
        name: "AI ethics",
        description: "The moral dimensions of artificial intelligence — alignment, fairness, responsibility, and existential risk.",
        keyThesis: "Algorithmic fairness: automated systems embed and amplify social biases; fairness definitions are incompatible in multi-stakeholder settings. Responsibility gap: when AI causes harm, accountability may be diffused or absent. Existential risk: superintelligent AI may pose catastrophic risks requiring value alignment research.",
        keyThinkers: ["Nick Bostrom — Superintelligence", "Timnit Gebru", "Shannon Vallor", "Stuart Russell"],
        influencedBy: ["Bioethics & Applied Ethics — principlism"],
        tags: ["AI-ethics", "fairness", "alignment", "existential-risk"],
        xref: ["computer-science"],
      },
      {
        name: "Engineering ethics",
        description: "Professional moral responsibilities of engineers — safety, honesty, and public welfare.",
        keyThesis: "Engineers' paramount responsibility is public safety, health, and welfare. The Ford Pinto case (known safety defect left unaddressed for cost reasons) and Challenger disaster illustrate conflicts between organizational pressures and professional duty. Whistleblowing is sometimes obligatory.",
        keyThinkers: ["Mike Martin & Roland Schinzinger — Ethics in Engineering", "Charles Harris"],
        influencedBy: ["Principlism"],
        tags: ["engineering-ethics", "professional", "safety"],
      },
    ],
  },

  // ── Family 20 — Philosophy of Religion ────────────────────────────────────
  {
    slug: "philosophy-of-religion",
    number: 20,
    name: "Philosophy of Religion",
    blurb: "Theistic arguments, the problem of evil, divine hiddenness, and the epistemology of religious belief.",
    section: "D",
    color: "blue",
    entries: [
      {
        name: "Cosmological arguments",
        description: "Arguments from the existence of the cosmos to a first cause or necessary being.",
        keyThesis: "Aquinas's First and Second Ways: the regress of movers/causes must stop at an unmoved mover/uncaused cause. Kalam cosmological argument (Al-Kindi, Craig): everything that begins to exist has a cause; the universe began; therefore a cause exists beyond the universe.",
        keyThinkers: ["Thomas Aquinas — Summa Theologica (Five Ways)", "William Lane Craig — The Kalam Cosmological Argument"],
        influencedBy: ["Thomism"],
        tags: ["cosmological-argument", "first-cause", "Aquinas"],
      },
      {
        name: "Ontological argument",
        description: "God's existence follows from the concept of a maximally great being alone.",
        keyThesis: "Anselm: God is 'that than which nothing greater can be conceived'; a being that exists in reality is greater than one that exists only in the understanding; therefore God exists in reality. Kant's objection: existence is not a predicate. Plantinga's modal version: possibly a maximally great being exists; therefore one exists in all worlds.",
        keyThinkers: ["Anselm of Canterbury — Proslogion", "René Descartes — Meditations V", "Alvin Plantinga — The Nature of Necessity"],
        influencedBy: [],
        tags: ["ontological-argument", "Anselm", "Plantinga"],
        status: "contested",
      },
      {
        name: "Teleological argument (design)",
        description: "The apparent design in nature points to an intelligent designer.",
        keyThesis: "Paley: the watch analogy — the complexity of the eye implies a designer. Hume's Dialogues undermine the analogy. Darwin's natural selection provides an alternative explanation. Intelligent Design's irreducible complexity claim is contested; most scientists consider it refuted.",
        keyThinkers: ["William Paley — Natural Theology", "David Hume — Dialogues Concerning Natural Religion", "Richard Dawkins — The Blind Watchmaker"],
        influencedBy: [],
        tags: ["design-argument", "Paley", "teleology"],
        status: "contested",
      },
      {
        name: "Problem of evil",
        description: "The existence of evil is evidence against, or incompatible with, an omnipotent, omniscient, benevolent God.",
        keyThesis: "Logical problem (Mackie): omnipotent, omniscient, omnibenevolent God and evil are logically incompatible. Evidential problem (Rowe): the extent and gratuitousness of suffering provides strong evidence against theism. Free will defense (Plantinga): God could not create free beings and guarantee they choose good.",
        keyThinkers: ["J.L. Mackie — 'Evil and Omnipotence'", "William Rowe", "Alvin Plantinga — God, Freedom, and Evil"],
        influencedBy: ["Cosmological arguments"],
        tags: ["problem-of-evil", "theodicy", "free-will-defense"],
        status: "open",
      },
      {
        name: "Divine hiddenness",
        description: "Why, if God exists and wants a relationship with us, is God not more evident?",
        keyThesis: "Schellenberg: if a loving God existed, no person would lack reasonable non-belief; some persons do lack reasonable non-belief; therefore no such God exists. Responses: human freedom requires epistemic distance; hiddenness serves spiritual growth.",
        keyThinkers: ["J.L. Schellenberg — Divine Hiddenness and Human Reason", "Paul Moser"],
        influencedBy: ["Problem of evil"],
        tags: ["divine-hiddenness", "Schellenberg", "reasonable-nonbelief"],
        status: "open",
      },
      {
        name: "Reformed epistemology",
        description: "Belief in God can be 'properly basic' — rational without inferential justification from argument.",
        keyThesis: "Plantinga: the evidentialist objection to theism rests on a false epistemology. Belief in God, produced by the sensus divinitatis in the right conditions, is properly basic — like perceptual and memorial beliefs. The question is not whether belief is argued for, but whether it is warranted.",
        keyThinkers: ["Alvin Plantinga — Warranted Christian Belief", "Nicholas Wolterstorff", "William Alston"],
        influencedBy: ["Reliabilism"],
        tags: ["reformed-epistemology", "Plantinga", "basic-belief"],
      },
      {
        name: "Religious experience and mysticism",
        description: "Can direct experiential encounter with the divine justify religious belief?",
        keyThesis: "Alston: the doxastic practices that produce beliefs from religious experience are as epistemically legitimate as those producing beliefs from sense perception — similar structure of communal checks and self-support. Swinburne: if it seems to someone that X is present, that is prima facie reason to believe X is present.",
        keyThinkers: ["William Alston — Perceiving God", "Richard Swinburne — The Existence of God", "William James — The Varieties of Religious Experience"],
        influencedBy: ["Reformed epistemology"],
        tags: ["religious-experience", "mysticism", "perception"],
      },
      {
        name: "Religious pluralism vs exclusivism",
        description: "Whether all major religious traditions track the same salvific reality, or only one is correct.",
        keyThesis: "Hick: the great religions are different culturally conditioned responses to the same transcendent Real — none is uniquely salvifically efficacious. Plantinga's exclusivism: it is epistemically permissible to hold Christian belief even knowing others disagree.",
        keyThinkers: ["John Hick — An Interpretation of Religion", "Alvin Plantinga — 'Pluralism: A Defense of Religious Exclusivism'"],
        influencedBy: ["Religious experience and mysticism"],
        tags: ["pluralism", "exclusivism", "Hick", "salvific"],
        status: "contested",
      },
    ],
  },

  // ── SECTION E — FAMOUS ARGUMENTS & OPEN PROBLEMS ────────────────────────────

  // ── Family 21 — Famous Arguments & Open Problems (GOLD) ──────────────────
  {
    slug: "famous-arguments",
    number: 21,
    name: "Famous Arguments & Open Problems",
    blurb: "The canonical thought experiments, celebrated arguments, and the discipline's deepest open questions.",
    section: "E",
    color: "amber",
    entries: [
      {
        name: "Gettier counterexamples",
        description: "Simple cases show that justified true belief is not sufficient for knowledge.",
        keyThesis: "Gettier (1963) in a three-page paper: Smith justifiably believes 'the man who will get the job has ten coins in his pocket' — but gets it right by accident. This refuted the JTB analysis and launched fifty years of post-Gettier epistemology.",
        keyThinkers: ["Edmund Gettier — 'Is Justified True Belief Knowledge?' (1963)"],
        influencedBy: ["The analysis of knowledge (JTB)"],
        tags: ["Gettier", "knowledge", "JTB", "counterexample"],
      },
      {
        name: "The Trolley Problem",
        description: "Should you divert a runaway trolley to kill one person instead of five?",
        keyThesis: "The trolley case (switch variant): diverting the trolley kills one to save five — most people say permissible. The footbridge variant: pushing a large man off a bridge to stop the trolley — most say impermissible. This asymmetry challenges both consequentialism and deontology and drives moral psychology research.",
        keyThinkers: ["Philippa Foot — 'The Problem of Abortion and the Doctrine of Double Effect' (1967)", "Judith Jarvis Thomson — 'Killing, Letting Die, and the Trolley Problem' (1976)"],
        influencedBy: ["Kantian deontology", "Consequentialism"],
        tags: ["trolley-problem", "doctrine-of-double-effect", "Foot", "Thomson"],
        disputed: true,
      },
      {
        name: "The Chinese Room argument",
        description: "Syntax is not sufficient for semantics — a program passing the Turing Test does not thereby understand.",
        keyThesis: "Searle: imagine a person in a room following rules for manipulating Chinese symbols without understanding Chinese. Such a system could pass a Turing Test yet lack genuine understanding (semantics). Programs are mere syntax; understanding requires causal biological powers.",
        keyThinkers: ["John Searle — 'Minds, Brains, and Programs' (1980)"],
        influencedBy: ["Biological naturalism", "Functionalism"],
        tags: ["Chinese-room", "Searle", "strong-AI", "semantics"],
        xref: ["computer-science"],
      },
      {
        name: "Mary's Room (knowledge argument)",
        description: "Can complete physical knowledge fail to capture phenomenal facts? Mary the colour scientist.",
        keyThesis: "Jackson: Mary is a neuroscientist who knows all physical facts about colour vision but has only ever seen black and white. On leaving her room, she learns something new — what red looks like. Therefore not all facts are physical facts: there are phenomenal facts qualia cannot capture.",
        keyThinkers: ["Frank Jackson — 'Epiphenomenal Qualia' (1982)", "Daniel Dennett (critic)"],
        influencedBy: ["Phenomenal consciousness and qualia", "Property dualism"],
        tags: ["Mary's-room", "knowledge-argument", "Jackson", "qualia"],
      },
      {
        name: "Newcomb's Problem",
        description: "A thought experiment that divides decision theorists: one-box or two-box?",
        keyThesis: "A predictor (near-infallible) places $1M in Box B iff it predicts you take only Box B; Box A always has $1000. Expected utility (causal): take both. Dominance (evidential): take both. Yet evidential decision theory recommends one-boxing. The problem forces a choice between causal and evidential decision theory.",
        keyThinkers: ["William Newcomb (originated)", "Robert Nozick — 'Newcomb's Problem and Two Principles of Choice' (1969)"],
        influencedBy: ["Bayesian epistemology"],
        tags: ["Newcomb", "decision-theory", "CDT", "EDT"],
      },
      {
        name: "The Sorites Paradox (problem of vagueness)",
        description: "Small changes that individually don't affect category membership collectively produce a change.",
        keyThesis: "A heap minus one grain is still a heap; repeated application eliminates the heap without any definite step. Responses: epistemicism (there is a sharp boundary we cannot know), degree theory (gradual truth), supervaluationism, or revisionism about vague predicates.",
        keyThinkers: ["Eubulides (ancient)", "Timothy Williamson — Vagueness", "Kit Fine — 'Vagueness, Truth and Logic'"],
        influencedBy: ["Propositional logic"],
        tags: ["sorites", "vagueness", "heap", "paradox"],
        status: "open",
      },
      {
        name: "Putnam's Twin Earth",
        description: "A thought experiment showing that meaning is not entirely in the head.",
        keyThesis: "Putnam: suppose Twin Earth has a liquid visually identical to water but chemically different (XYZ). In 1750, 'water' on Earth and Twin Earth pick out different substances even though speakers' internal states are identical. Therefore meaning is not determined by internal mental states.",
        keyThinkers: ["Hilary Putnam — 'The Meaning of Meaning' (1975)"],
        influencedBy: ["Semantic externalism"],
        tags: ["Twin-Earth", "Putnam", "externalism", "meaning"],
      },
      {
        name: "The Turing Test and machine intelligence",
        description: "Can a machine pass for human in conversation? What would this show?",
        keyThesis: "Turing's imitation game: if a machine can fool an interrogator into thinking it is human, should we attribute intelligence to it? Searle's Chinese Room is the canonical objection. The test conflates behavioral indistinguishability with genuine intelligence — but many argue behavior is all there is.",
        keyThinkers: ["Alan Turing — 'Computing Machinery and Intelligence' (1950)", "John Searle"],
        influencedBy: ["Functionalism"],
        tags: ["Turing-test", "AI", "intelligence", "behavioral-criterion"],
        xref: ["computer-science"],
      },
      {
        name: "Hempel's Raven Paradox",
        description: "Non-black non-ravens logically confirm 'all ravens are black.'",
        keyThesis: "Hempel's equivalence condition: confirming evidence for a hypothesis H also confirms any logically equivalent hypothesis. 'All ravens are black' is equivalent to 'all non-black things are non-ravens'; therefore my green apple confirms that all ravens are black. This reveals deep problems in confirmation theory.",
        keyThinkers: ["Carl Hempel — 'Studies in the Logic of Confirmation' (1945)"],
        influencedBy: ["Falsificationism"],
        tags: ["raven-paradox", "Hempel", "confirmation", "induction"],
      },
      {
        name: "Goodman's New Riddle of Induction (grue)",
        description: "There are infinitely many hypotheses compatible with any finite set of observations.",
        keyThesis: "Goodman: define 'grue' as green-if-observed-before-time-T, blue-otherwise. All observed emeralds confirm both 'all emeralds are green' and 'all emeralds are grue'. Inductive logic cannot distinguish the two without some notion of 'projectibility' — but what makes a predicate projectible?",
        keyThinkers: ["Nelson Goodman — Fact, Fiction, and Forecast (1955)"],
        influencedBy: ["Falsificationism"],
        tags: ["grue", "Goodman", "induction", "projectibility"],
      },
      {
        name: "The Problem of Induction",
        description: "No logical or empirical justification can validate inductive inference.",
        keyThesis: "Hume: inferring from 'all observed Xs are Y' to 'all Xs are Y' is not deductively valid. Justifying it empirically would be circular. Popper's response: eliminate induction entirely and rely on falsification. Pragmatic responses: induction is self-correcting or pragmatically vindicated.",
        keyThinkers: ["David Hume — Enquiry Concerning Human Understanding (§4)", "Karl Popper — Logic of Scientific Discovery"],
        influencedBy: ["Falsificationism"],
        tags: ["induction", "Hume", "circularity"],
        status: "open",
      },
      {
        name: "The Demarcation Problem",
        description: "What distinguishes science from pseudo-science and non-science?",
        keyThesis: "Popper: falsifiability. Kuhn: science is defined by normal puzzle-solving within a paradigm. Lakatos: progressive vs degenerative research programmes. Kitcher: science requires risky predictions, not just any empirical content. No consensus; the problem is still live in disputes about intelligent design and astrology.",
        keyThinkers: ["Karl Popper", "Thomas Kuhn", "Imre Lakatos", "Philip Kitcher"],
        influencedBy: ["Paradigms and scientific revolutions", "Falsificationism"],
        tags: ["demarcation", "Popper", "pseudo-science", "Kuhn"],
        status: "open",
      },
      {
        name: "The Hard Problem of Consciousness",
        description: "Why does any physical process give rise to subjective experience at all?",
        keyThesis: "Chalmers: the easy problems of consciousness (explaining functions, reports, behavior) are tractable by cognitive science. The hard problem — why physical processes feel like anything at all — is not. No amount of functional explanation explains why there is 'something it is like' to see red.",
        keyThinkers: ["David Chalmers — 'Facing Up to the Problem of Consciousness' (1995)", "Chalmers — The Conscious Mind"],
        influencedBy: ["Phenomenal consciousness and qualia"],
        tags: ["hard-problem", "Chalmers", "consciousness", "explanatory-gap"],
        status: "open",
      },
      {
        name: "The Problem of Free Will",
        description: "Are human choices genuinely free, or determined (or random), and does this matter morally?",
        keyThesis: "Hard incompatibilism: determinism and free will are incompatible, and determinism is true. Compatibilism (Frankfurt, Dennett): free will consists in acting from one's own desires and values, not randomness — this is compatible with determinism. Libertarianism (agent causation): genuine free will requires indeterminism. Contested without clear consensus.",
        keyThinkers: ["Harry Frankfurt — 'Freedom of the Will and the Concept of a Person'", "Peter Strawson — 'Freedom and Resentment'", "Daniel Dennett — Elbow Room"],
        influencedBy: ["Modality and possible worlds"],
        tags: ["free-will", "compatibilism", "determinism"],
        status: "open",
        disputed: true,
      },
      {
        name: "Personal identity — fission cases",
        description: "What happens to personal identity when a brain is divided and each half transplanted?",
        keyThesis: "Parfit: if my brain is split and each hemisphere implanted in a new body, both resulting persons are equally 'me' by the psychological continuity criterion — yet they cannot both be me (they are distinct). Conclusion: identity is not what matters; what matters is psychological continuity itself.",
        keyThinkers: ["Derek Parfit — Reasons and Persons (Part III, 1984)", "Sydney Shoemaker"],
        influencedBy: ["Personal identity and psychological continuity"],
        tags: ["fission", "personal-identity", "Parfit"],
      },
      {
        name: "Zeno's Paradoxes of Motion",
        description: "Motion and plurality seem to generate contradictions — Achilles and the Tortoise.",
        keyThesis: "Achilles can never overtake the tortoise, since whenever he reaches the point where the tortoise was, it has moved ahead. The Arrow Paradox: at any instant, a moving arrow occupies a fixed position — so motion is illusory. Mathematical resolution (infinite series summing to finite values) is standard but whether this dissolves the philosophical puzzle is disputed.",
        keyThinkers: ["Zeno of Elea", "Aristotle (Physics, discussion)", "Wesley Salmon — Zeno's Paradoxes"],
        influencedBy: ["Pre-Socratic cosmology"],
        tags: ["Zeno", "motion", "infinite-series", "paradox"],
      },
      {
        name: "The Preface Paradox",
        description: "An author who believes each claim in a book reasonably believes the conjunction, yet also that some claim is false.",
        keyThesis: "An author writes a book, asserting each claim because they believe it. In the preface they write: 'no doubt some claims in this book are mistaken.' Each individual belief is rational, yet the conjunction of all beliefs is inconsistent. Challenges probabilistic and deductive closure principles for rational belief.",
        keyThinkers: ["David Makinson — 'The Paradox of the Preface' (1965)"],
        influencedBy: ["The analysis of knowledge (JTB)"],
        tags: ["preface-paradox", "rational-belief", "closure"],
      },
      {
        name: "The Frame Problem",
        description: "How to represent what does not change when an action occurs — a challenge for AI and philosophy of mind.",
        keyThesis: "McCarthy and Hayes: in a formal representation of action, one must explicitly list every unchanged fact after an action — but the unchanged facts vastly outnumber changed ones. No general solution exists in classical logic. This has implications for common-sense reasoning and the limits of formal AI.",
        keyThinkers: ["John McCarthy & Patrick Hayes — 'Some Philosophical Problems from the Standpoint of AI' (1969)"],
        influencedBy: ["The Chinese Room argument"],
        tags: ["frame-problem", "AI", "action", "representation"],
        status: "open",
        xref: ["computer-science"],
      },
      {
        name: "The Sleeping Beauty Problem",
        description: "A probability puzzle about self-locating belief that divides halfers from thirders.",
        keyThesis: "Beauty is put to sleep on Sunday; a fair coin is flipped. If heads, she is woken once (Monday). If tails, she is woken twice (Monday and Wednesday), with memory erased. On waking, what probability should she assign to Heads? Halfers: 1/2 (no new information). Thirders: 1/3 (three equally likely centered worlds).",
        keyThinkers: ["Adam Elga — 'Self-Locating Belief and the Sleeping Beauty Problem' (2000)", "David Lewis (halfer)"],
        influencedBy: ["Bayesian epistemology"],
        tags: ["sleeping-beauty", "self-location", "probability"],
        status: "contested",
      },
      {
        name: "The Experience Machine (Nozick)",
        description: "If given the choice to enter a machine giving the perfect illusion of a good life, would you?",
        keyThesis: "Nozick: most people would not enter the experience machine — showing that what matters is not just subjective experience but actually doing things, being a certain kind of person, and contacting a deeper reality. This is a decisive objection to hedonistic utilitarianism and preference-satisfaction theories based on experiences alone.",
        keyThinkers: ["Robert Nozick — Anarchy, State and Utopia (1974)"],
        influencedBy: ["Classical utilitarianism"],
        tags: ["experience-machine", "Nozick", "hedonism", "welfare"],
      },
      {
        name: "Integrated Information Theory (IIT)",
        description: "Consciousness is identical to integrated information (phi) — a quantifiable structural property.",
        keyThesis: "Tononi: consciousness exists wherever integrated information ($\\Phi$) exceeds that of any partition of the system. IIT predicts that some simple systems have minimal consciousness; it implies feed-forward networks (however complex) are not conscious. Controversial: claimed by some as a leading theory, dismissed by others as pseudoscience.",
        notation: "$\\Phi = \\min_{P} D_{KL}(P_{\\text{full}} \\| P_{\\text{partitioned}})$",
        keyThinkers: ["Giulio Tononi — 'Consciousness as Integrated Information'", "Christof Koch"],
        influencedBy: ["Phenomenal consciousness and qualia"],
        tags: ["IIT", "phi", "consciousness", "information"],
        status: "contested",
        xref: ["computer-science"],
      },
    ],
  },
];
