import type { Family } from "./types";

export const FAMILIES_15_20: Family[] = [
  // ── Family 15 — Surgery & Trauma ─────────────────────────────────────────
  {
    slug: "surgery-trauma",
    number: 15,
    name: "Surgery & Trauma",
    blurb: "Operative principles, perioperative care, and the trauma response.",
    section: "B",
    color: "rose",
    entries: [
      {
        name: "Trauma resuscitation (ATLS)",
        description: "Systematic initial assessment of trauma patients.",
        keyFact: "Primary survey ABCDE — Airway with C-spine, Breathing, Circulation, Disability, Exposure. Massive transfusion protocol: 1:1:1 RBC/plasma/platelets, TXA within 3 h of injury (CRASH-2).",
        tags: ["surgery", "trauma"],
      },
      {
        name: "Damage control surgery",
        description: "Abbreviated operation in unstable trauma patients.",
        keyFact: "Control hemorrhage and contamination; defer definitive repair. Lethal triad: hypothermia, acidosis, coagulopathy. ICU resuscitation between operations.",
        tags: ["surgery", "trauma"],
      },
      {
        name: "Acute abdomen",
        description: "Abdominal pain requiring urgent surgical evaluation.",
        keyFact: "Differential by quadrant. Causes: appendicitis, perforated viscus, mesenteric ischemia, ectopic, AAA rupture. Mesenteric ischemia: pain out of proportion to exam, lactate, CT angio.",
        organSystem: "gastrointestinal",
        tags: ["surgery", "abdomen"],
      },
      {
        name: "Appendicitis",
        description: "Acute inflammation of the vermiform appendix.",
        keyFact: "Periumbilical pain migrating to RLQ. Alvarado score, US, CT. Laparoscopic appendectomy historic standard; antibiotics-first (CODA trial 2020) reasonable for uncomplicated cases in select patients.",
        organSystem: "gastrointestinal",
        tags: ["surgery", "appendix"],
      },
      {
        name: "Bowel obstruction",
        description: "Mechanical blockage of small or large bowel.",
        keyFact: "Small bowel: adhesions most common cause; managed with NG decompression, fluids, conservative trial. Large bowel: cancer most common; often requires surgery. Closed-loop and strangulation are surgical emergencies.",
        organSystem: "gastrointestinal",
        tags: ["surgery", "obstruction"],
      },
      {
        name: "Wound healing",
        description: "Hemostasis → inflammation → proliferation → remodeling.",
        keyFact: "Primary intention: clean approximated wounds. Secondary: granulation, contraction, epithelialization. Diabetes, smoking, malnutrition, steroids, infection impair healing.",
        organSystem: "dermatological",
        tags: ["surgery", "wound"],
      },
      {
        name: "Burns",
        description: "Thermal, chemical, electrical, or radiation injury to skin/tissue.",
        keyFact: "Parkland formula: 4 mL × kg × %TBSA LR over 24 h, half in first 8 h. TBSA estimation by rule of nines. Inhalation injury → early intubation; carboxyhemoglobin in fire-related smoke.",
        organSystem: "dermatological",
        tags: ["surgery", "burns"],
      },
      {
        name: "Perioperative cardiac assessment",
        description: "Risk stratification for noncardiac surgery.",
        keyFact: "RCRI calculator. Continue beta-blockers, consider statins. Cardiac stress testing reserved for elevated risk + poor functional capacity if it will change management. Bridging anticoagulation often unnecessary in low-stroke-risk AF.",
        organSystem: "cardiovascular",
        tags: ["surgery", "perioperative"],
      },
      {
        name: "Anesthesia",
        description: "Pharmacologic induction of analgesia, amnesia, immobility, hemodynamic stability.",
        keyFact: "General (TIVA or volatile) vs regional (neuraxial, peripheral nerve blocks) vs MAC. Enhanced recovery after surgery (ERAS) protocols emphasize multimodal analgesia, early mobilization, opioid-sparing.",
        tags: ["surgery", "anesthesia"],
      },
      {
        name: "Minimally invasive & robotic surgery",
        description: "Laparoscopic and robot-assisted operations replacing open approaches.",
        keyFact: "da Vinci platform dominant in robotics. Benefits: less pain, shorter LOS, faster return to function. Best evidence: prostatectomy, hysterectomy, colorectal, mitral valve repair.",
        tags: ["surgery", "minimally-invasive"],
      },
      {
        name: "Organ transplantation",
        description: "Kidney, liver, heart, lung, pancreas, intestine transplantation.",
        keyFact: "Brain death and donation after circulatory death are the two pathways. Allocation by MELD (liver), KAS (kidney), heart-allocation policy. Hep C+ donor to Hep C- recipient now feasible due to DAAs.",
        tags: ["surgery", "transplant"],
      },
      {
        name: "Surgical-site infection prevention",
        description: "Pre-, intra-, and postoperative measures to reduce SSI.",
        keyFact: "Hair clipping (not shaving), CHG skin prep, prophylactic antibiotic within 1 h of incision, normothermia, glycemic control, supplemental oxygen, minimizing operative time.",
        tags: ["surgery", "infection"],
      },
    ],
  },

  // ── Family 16 — Radiology & Imaging ──────────────────────────────────────
  {
    slug: "radiology-imaging",
    number: 16,
    name: "Radiology & Imaging",
    blurb: "X-ray, ultrasound, CT, MRI, PET — the modalities of modern diagnosis.",
    section: "C",
    color: "sky",
    entries: [
      {
        name: "Chest X-ray",
        description: "Most common diagnostic imaging study.",
        keyFact: "Two views (PA + lateral) when possible. Read with systematic ABCDE approach. Evaluates lines/tubes, pneumonia, pneumothorax, effusion, cardiomegaly, congestion, masses.",
        tags: ["imaging", "X-ray"],
        xref: ["chemistry"],
      },
      {
        name: "Computed tomography (CT)",
        description: "Rotational X-ray with computed cross-sectional reconstruction.",
        keyFact: "Mainstay for trauma, stroke, abdominal pain, cancer staging. Iodinated contrast for vascular detail. Radiation dose ~1–10 mSv per study; iterative reconstruction and dual-energy reduce dose.",
        tags: ["imaging", "CT"],
      },
      {
        name: "Magnetic resonance imaging (MRI)",
        description: "Non-ionizing imaging using nuclear magnetic resonance.",
        keyFact: "Excellent soft-tissue contrast. T1 (anatomy), T2 (pathology, water), DWI (acute stroke, abscess), FLAIR (CSF-suppressed brain). Gadolinium contrast; risk of NSF in severe CKD largely mitigated by group II agents.",
        tags: ["imaging", "MRI"],
        xref: ["chemistry"],
      },
      {
        name: "Ultrasound",
        description: "Real-time sonographic imaging without ionizing radiation.",
        keyFact: "FAST exam in trauma. Point-of-care US (POCUS) increasingly used at bedside for cardiac, lung, biliary, vascular, procedural guidance. Operator-dependent.",
        tags: ["imaging", "US"],
      },
      {
        name: "PET / PET-CT",
        description: "Positron emission tomography — functional imaging of metabolism.",
        keyFact: "18F-FDG for glycolytic uptake — cancer staging, response assessment. Amyloid and tau PET for AD diagnosis. PSMA-PET for prostate cancer staging. DOTATATE-PET for neuroendocrine tumors.",
        tags: ["imaging", "PET"],
      },
      {
        name: "Mammography",
        description: "Low-dose X-ray of breast for cancer screening and diagnosis.",
        keyFact: "Digital breast tomosynthesis (DBT) replacing 2D mammography. USPSTF 2024: biennial screening 40–74. BI-RADS 0–6 categorize findings. Dense breast notification now federally required.",
        organSystem: "reproductive",
        tags: ["imaging", "mammography", "screening"],
      },
      {
        name: "Interventional radiology",
        description: "Image-guided percutaneous diagnostic and therapeutic procedures.",
        keyFact: "Drainages, biopsies, embolizations, angioplasty/stenting, IVC filters, TIPS, transarterial chemoembolization, radioembolization, uterine fibroid embolization, mechanical thrombectomy for stroke.",
        tags: ["imaging", "IR"],
      },
      {
        name: "Nuclear medicine",
        description: "Imaging and therapy with radioactive isotopes.",
        keyFact: "99mTc for most diagnostic scans (bone, MAG3, sestamibi, V/Q). Theranostics: 177Lu-DOTATATE (NETs), 177Lu-PSMA-617 (Pluvicto, mCRPC, 2022 FDA). 131I for thyroid.",
        tags: ["imaging", "nuc-med"],
      },
      {
        name: "AI in radiology",
        description: "Deep-learning algorithms for image interpretation.",
        keyFact: "FDA-cleared algorithms for stroke detection (LVO triage), pulmonary embolism, intracranial hemorrhage, lung nodules, fractures. Augment but do not replace radiologists; concerns about generalizability, bias, dataset shift.",
        tags: ["imaging", "AI"],
        status: "contested",
      },
      {
        name: "Radiation safety",
        description: "ALARA principle — minimize ionizing radiation exposure.",
        keyFact: "Background ~3 mSv/year. CXR ~0.1 mSv, head CT ~2 mSv, abdomen CT ~10 mSv. Pediatric and pregnant patients especially sensitive. MRI and US preferred when feasible.",
        tags: ["imaging", "safety"],
      },
      {
        name: "Echocardiography",
        description: "Ultrasound imaging of the heart.",
        keyFact: "TTE first-line. TEE for endocarditis, atrial appendage thrombus, intraoperative valve assessment. Strain imaging, 3D, and contrast (definity) refine assessment.",
        organSystem: "cardiovascular",
        tags: ["imaging", "echo"],
      },
      {
        name: "Stroke imaging",
        description: "Multimodal imaging triage of acute ischemic and hemorrhagic stroke.",
        keyFact: "Non-contrast CT excludes hemorrhage. CTA identifies LVO. CT perfusion or MRI DWI/PWI mismatch determine viable penumbra and extend thrombectomy window to 24 h.",
        organSystem: "neurological",
        tags: ["imaging", "stroke"],
      },
    ],
  },

  // ── Family 17 — Pharmacology & Drug Classes ──────────────────────────────
  {
    slug: "pharmacology-drug-classes",
    number: 17,
    name: "Pharmacology & Drug Classes",
    blurb: "How drugs work — pharmacodynamics, pharmacokinetics, and the major drug classes.",
    section: "D",
    color: "indigo",
    entries: [
      {
        name: "Pharmacokinetics (ADME)",
        description: "Absorption, distribution, metabolism, excretion.",
        keyFact: "First-order kinetics: t½ = 0.693·Vd/CL. Steady state after ~4–5 half-lives. CYP enzymes drive most hepatic metabolism; CYP3A4 handles ~50% of drugs.",
        tags: ["pharm", "PK"],
        xref: ["chemistry"],
      },
      {
        name: "Pharmacodynamics",
        description: "Drug-receptor interactions and dose-response.",
        keyFact: "Affinity (Kd), efficacy (intrinsic activity), potency (EC50). Therapeutic index = TD50/ED50. Agonist, partial agonist, antagonist, inverse agonist categorization.",
        tags: ["pharm", "PD"],
      },
      {
        name: "Antibiotics",
        description: "Bactericidal or bacteriostatic agents targeting bacterial structures.",
        keyFact: "β-lactams (cell wall), macrolides/aminoglycosides/tetracyclines/oxazolidinones (ribosome), fluoroquinolones (DNA gyrase), TMP-SMX (folate), metronidazole (DNA strand breaks). Match spectrum to pathogen.",
        tags: ["pharm", "antibiotics"],
        xref: ["chemistry"],
      },
      {
        name: "Antivirals",
        description: "Drugs targeting viral replication.",
        keyFact: "Nucleos(t)ide analogs (acyclovir, tenofovir, sofosbuvir), protease inhibitors (HIV PIs, paxlovid), neuraminidase inhibitors (oseltamivir), CCR5 antagonists, integrase inhibitors (dolutegravir).",
        tags: ["pharm", "antivirals"],
        xref: ["chemistry"],
      },
      {
        name: "Antifungals",
        description: "Polyenes, azoles, echinocandins, allylamines.",
        keyFact: "Amphotericin B (polyene): broad but nephrotoxic. Azoles (fluconazole, voriconazole, posaconazole, isavuconazole): CYP3A4 inhibition. Echinocandins (caspofungin, micafungin): cell wall β-1,3-glucan.",
        tags: ["pharm", "antifungals"],
        xref: ["chemistry"],
      },
      {
        name: "GLP-1 receptor agonists",
        description: "Incretin mimetics for type 2 diabetes and obesity.",
        keyFact: "Semaglutide, liraglutide, dulaglutide, tirzepatide (GIP/GLP-1 dual agonist). Major weight loss (~15–22%), CV benefit (LEADER, SUSTAIN-6, SELECT). Pancreatitis, gastroparesis among side effects.",
        tags: ["pharm", "endocrine"],
        status: "landmark",
      },
      {
        name: "SGLT2 inhibitors",
        description: "Sodium-glucose cotransporter 2 inhibitors.",
        keyFact: "Empagliflozin, dapagliflozin, canagliflozin, ertugliflozin. Reduce CV mortality in HFrEF (EMPEROR-Reduced, DAPA-HF), HFpEF (EMPEROR-Preserved, DELIVER), and slow CKD progression. Risk: euglycemic DKA.",
        tags: ["pharm", "endocrine"],
        status: "landmark",
      },
      {
        name: "Statins",
        description: "HMG-CoA reductase inhibitors lowering LDL cholesterol.",
        keyFact: "Reduce ASCVD events ~25% per 1 mmol/L LDL reduction. High-intensity: atorvastatin 40–80, rosuvastatin 20–40. Adverse: myopathy, transaminase elevation. T2DM modestly increased.",
        tags: ["pharm", "cardio"],
        xref: ["chemistry"],
      },
      {
        name: "Anticoagulants",
        description: "Drugs preventing or treating thromboembolism.",
        keyFact: "Heparin (UFH, LMWH), DOACs (apixaban, rivaroxaban, edoxaban, dabigatran), warfarin (vitamin K antagonist). DOACs replaced warfarin for non-valvular AF and VTE; warfarin still preferred in mechanical valves, severe valvular disease.",
        organSystem: "hematological",
        tags: ["pharm", "anticoag"],
      },
      {
        name: "Antiplatelet drugs",
        description: "Inhibit platelet aggregation.",
        keyFact: "Aspirin (COX-1 acetylation), P2Y12 inhibitors (clopidogrel, prasugrel, ticagrelor, cangrelor), GP IIb/IIIa antagonists. Dual antiplatelet after ACS and PCI; duration personalized by bleeding/ischemic risk.",
        organSystem: "hematological",
        tags: ["pharm", "antiplatelet"],
      },
      {
        name: "Opioid analgesics",
        description: "Mu-receptor agonists for moderate-severe pain.",
        keyFact: "Morphine, hydromorphone, fentanyl, oxycodone, hydrocodone, methadone, buprenorphine. Tolerance, respiratory depression, constipation, dependence. Naloxone for overdose reversal. Buprenorphine/methadone for OUD.",
        tags: ["pharm", "analgesics", "addiction"],
      },
      {
        name: "Antidepressants",
        description: "SSRIs, SNRIs, atypicals, TCAs, MAOIs.",
        keyFact: "SSRIs (sertraline, escitalopram, fluoxetine) first-line for MDD/anxiety. SNRIs (venlafaxine, duloxetine), atypicals (bupropion, mirtazapine). TCAs and MAOIs second/third-line due to side effects.",
        organSystem: "psychiatric",
        tags: ["pharm", "psychiatry"],
      },
      {
        name: "Monoclonal antibodies",
        description: "Targeted protein therapeutics.",
        keyFact: "Naming: -mab. Targets: TNF (infliximab, adalimumab), CD20 (rituximab), HER2 (trastuzumab), PD-1 (pembrolizumab), CGRP (erenumab), amyloid (lecanemab). Bispecific antibodies (e.g., teclistamab) emerging.",
        tags: ["pharm", "biologics"],
      },
      {
        name: "Vaccines (immunization)",
        description: "Live-attenuated, inactivated, subunit, mRNA, viral vector.",
        keyFact: "mRNA platform (Pfizer-BioNTech, Moderna) deployed at scale during COVID-19. Adjuvants enhance subunit-vaccine immunogenicity. Cold chain, equity, and hesitancy ongoing challenges.",
        tags: ["pharm", "vaccines", "immunology"],
        status: "landmark",
      },
    ],
  },

  // ── Family 18 — Epidemiology & Biostatistics ─────────────────────────────
  {
    slug: "epidemiology-biostatistics",
    number: 18,
    name: "Epidemiology & Biostatistics",
    blurb: "Study design, statistical inference, and population-level disease patterns.",
    section: "E",
    color: "teal",
    entries: [
      {
        name: "Randomized controlled trial",
        description: "Gold-standard study design for causal inference.",
        keyFact: "Random allocation, allocation concealment, blinding, intention-to-treat analysis. CONSORT statement for reporting. Pragmatic vs explanatory trials. Adaptive designs increasingly used.",
        tags: ["epi", "study-design"],
        xref: ["statistics"],
      },
      {
        name: "Cohort study",
        description: "Observational study following exposed vs unexposed groups forward in time.",
        keyFact: "Yields incidence, risk ratio. Framingham, Nurses' Health Study, ARIC are foundational. Prospective preferred; retrospective uses existing records. Vulnerable to confounding, loss to follow-up.",
        tags: ["epi", "study-design"],
        xref: ["statistics"],
      },
      {
        name: "Case-control study",
        description: "Cases with disease compared to controls without; look back at exposures.",
        keyFact: "Yields odds ratio. Efficient for rare diseases. Vulnerable to recall bias, selection bias. Nested case-control reduces these issues.",
        tags: ["epi", "study-design"],
        xref: ["statistics"],
      },
      {
        name: "Systematic review & meta-analysis",
        description: "Synthesis of evidence across studies.",
        keyFact: "PRISMA guideline. Heterogeneity (I²), publication bias (funnel plot, Egger), risk-of-bias assessment (Cochrane RoB 2, ROBINS-I). Forest plots display pooled and per-study effects.",
        tags: ["epi", "meta-analysis"],
        xref: ["statistics"],
      },
      {
        name: "Diagnostic test characteristics",
        description: "Sensitivity, specificity, PPV, NPV, likelihood ratios.",
        keyFact: "Sensitivity = TP/(TP+FN); specificity = TN/(TN+FP). PPV/NPV depend on prevalence; LRs do not. LR+ >10 or LR- <0.1 strongly informative. ROC curves trade off sensitivity vs specificity.",
        tags: ["epi", "diagnostics"],
        xref: ["statistics"],
      },
      {
        name: "Causal inference",
        description: "Bradford Hill criteria and modern causal frameworks.",
        keyFact: "Hill criteria: strength, consistency, specificity, temporality, biological gradient, plausibility, coherence, experiment, analogy. Modern: counterfactual framework, DAGs, instrumental variables, Mendelian randomization.",
        tags: ["epi", "causality"],
        xref: ["statistics"],
      },
      {
        name: "Incidence & prevalence",
        description: "New vs existing cases.",
        keyFact: "Incidence rate = new cases / person-time. Prevalence = existing cases / population at a time. Prevalence ≈ incidence × duration for steady state. Cumulative incidence = risk over a defined period.",
        tags: ["epi", "measures"],
      },
      {
        name: "Number needed to treat / harm",
        description: "Clinically interpretable measure of treatment effect.",
        keyFact: "NNT = 1/ARR. Lower is better. Always interpret with absolute risk and baseline. NNH for adverse outcomes.",
        tags: ["epi", "treatment"],
        xref: ["statistics"],
      },
      {
        name: "Confounding & effect modification",
        description: "Third-variable distortions of associations.",
        keyFact: "Confounder: associated with exposure and outcome, not on causal pathway. Effect modification (interaction): exposure effect differs by stratum. Adjust for confounders; stratify by effect modifiers.",
        tags: ["epi", "bias"],
        xref: ["statistics"],
      },
      {
        name: "Survival analysis",
        description: "Time-to-event statistical methods.",
        keyFact: "Kaplan-Meier curves; log-rank test for comparison. Cox proportional-hazards regression for adjusted hazard ratios. Censoring assumed independent of event risk.",
        tags: ["epi", "stats"],
        xref: ["statistics"],
      },
      {
        name: "Screening principles",
        description: "Wilson-Jungner criteria for population screening.",
        keyFact: "Important problem, recognizable preclinical phase, suitable test, accepted treatment, available facilities, agreed policy on whom to treat, cost-effective, ongoing. Lead-time and length-time biases inflate apparent benefit.",
        tags: ["epi", "screening"],
      },
      {
        name: "Pandemic preparedness",
        description: "Surveillance, response, and mitigation of emerging infections.",
        keyFact: "WHO IHR, GISAID, Global Influenza Surveillance and Response System. mRNA platforms shortened vaccine timeline COVID-19 dramatically. Post-COVID, equity, supply chain, and trust remain key gaps.",
        tags: ["epi", "pandemic"],
        status: "open",
      },
      {
        name: "Health disparities",
        description: "Systematic differences in health outcomes by race, ethnicity, SES, geography.",
        keyFact: "US Black maternal mortality 2–3× white; life expectancy gap of ~5 years between Black and white Americans (pre-COVID); rural-urban mortality gap widening. Social determinants of health drive most variation.",
        tags: ["epi", "disparities", "public-health"],
        status: "open",
      },
    ],
  },

  // ── Family 19 — Global Health & Public Health ────────────────────────────
  {
    slug: "global-health-public-health",
    number: 19,
    name: "Global Health & Public Health",
    blurb: "Population health, prevention, and health systems globally.",
    section: "E",
    color: "emerald",
    entries: [
      {
        name: "Global burden of disease",
        description: "DALYs, YLLs, YLDs quantifying disease burden across populations.",
        keyFact: "IHME Global Burden of Disease study published in Lancet annually. Cardiovascular disease leading cause of death globally; mental health, musculoskeletal pain leading causes of disability.",
        tags: ["public-health", "GBD"],
        xref: ["statistics"],
      },
      {
        name: "Life expectancy",
        description: "Average years of life remaining at a given age.",
        keyFact: "Global average ~73 years (2024). US ~78.4 (2023, rebounded post-COVID). Sub-Saharan Africa lowest (~60). Drug overdoses, suicides, COVID-19 caused unusual US decline 2014–2021.",
        tags: ["public-health", "mortality"],
        status: "contested",
        xref: ["statistics"],
      },
      {
        name: "Maternal & child mortality",
        description: "MMR (per 100k live births) and U5MR (per 1000 live births).",
        keyFact: "Global MMR ~223 (2020, WHO) — far above SDG target of 70. Sub-Saharan Africa carries ~70% of global maternal deaths. U5MR has declined >50% since 2000 globally, driven by vaccines, ORT, malaria control.",
        tags: ["public-health", "maternal-child"],
      },
      {
        name: "Smoking & tobacco control",
        description: "Leading preventable cause of death worldwide.",
        keyFact: "~8 million deaths/yr globally (WHO). MPOWER policies, plain packaging, taxation, smoke-free laws reduce smoking prevalence. E-cigarettes effective for cessation but raise concerns about youth uptake.",
        organSystem: "respiratory",
        tags: ["public-health", "tobacco"],
      },
      {
        name: "Alcohol-related harm",
        description: "Acute injury, chronic liver disease, cancer, dependence.",
        keyFact: "~3 million alcohol-attributable deaths/yr globally. Even moderate intake increases breast, colon, esophageal cancer. Current WHO guidance: 'no safe level' for cancer; historic 'J-curve' for CVD largely confounded.",
        tags: ["public-health", "alcohol"],
        status: "contested",
      },
      {
        name: "Obesity epidemic",
        description: "Global prevalence of obesity has more than tripled since 1975.",
        keyFact: "~13% of global adults obese (WHO 2022); 42% of US adults (NHANES 2017–2020). Rising in low-income countries — 'double burden' with undernutrition. GLP-1 RAs reshaping treatment.",
        tags: ["public-health", "obesity"],
      },
      {
        name: "Malnutrition",
        description: "Undernutrition, micronutrient deficiencies, and overnutrition.",
        keyFact: "Stunting affects ~22% of children under 5 globally. Wasting affects ~7%. Vitamin A, iron, iodine, zinc deficiencies remain leading micronutrient gaps. Severe acute malnutrition: ready-to-use therapeutic foods (RUTF).",
        tags: ["public-health", "nutrition"],
      },
      {
        name: "Air pollution",
        description: "PM2.5, ozone, NO2, indoor solid-fuel combustion.",
        keyFact: "~7 million premature deaths/yr globally (WHO). PM2.5 the dominant exposure; WHO 2021 guideline tightened annual mean to 5 µg/m³. Indoor air pollution from cooking fuels disproportionately affects women and children.",
        organSystem: "respiratory",
        tags: ["public-health", "pollution"],
        xref: ["chemistry"],
      },
      {
        name: "Climate change & health",
        description: "Health impacts of warming temperatures and ecological disruption.",
        keyFact: "Heat-related deaths rising; vector-borne diseases expanding (dengue, Lyme); food and water insecurity; mental health impacts of displacement. Lancet Countdown tracks annually.",
        tags: ["public-health", "climate"],
        status: "open",
      },
      {
        name: "Health systems",
        description: "Financing, delivery, and equity of health services.",
        keyFact: "Beveridge (UK NHS), Bismarck (Germany), national health insurance (Canada), out-of-pocket (much of LMICs). US: hybrid with highest spending per capita (~$13k in 2022) but worst high-income outcomes.",
        tags: ["public-health", "systems"],
        status: "contested",
      },
      {
        name: "Universal health coverage",
        description: "All people have access to needed health services without financial hardship.",
        keyFact: "UN SDG 3.8 target. WHO tracks UHC service coverage index. Catastrophic health spending pushes ~100 million into poverty annually. Primary care strengthening is central strategy.",
        tags: ["public-health", "UHC"],
      },
      {
        name: "Antibiotic stewardship",
        description: "Coordinated efforts to optimize antimicrobial use.",
        keyFact: "Reduce inappropriate prescribing in outpatient and inpatient settings, narrow spectrum when culture data available, IV-to-PO conversion, duration limits. Critical to slow AMR.",
        tags: ["public-health", "AMR"],
      },
    ],
  },

  // ── Family 20 — Landmark Discoveries & Medical Controversies (gold) ─────
  {
    slug: "landmark-discoveries-controversies",
    number: 20,
    name: "Landmark Discoveries & Medical Controversies",
    blurb: "The discoveries that changed medicine, and the still-contested or refuted claims.",
    section: "E",
    color: "amber",
    entries: [
      {
        name: "Germ theory of disease",
        description: "Microorganisms cause infectious disease — Pasteur, Koch (19th c).",
        keyFact: "Koch's postulates (1884): isolate from sick host, grow in pure culture, induce disease in healthy host, re-isolate. Foundation of modern microbiology. Modified by molecular criteria for unculturable organisms.",
        tags: ["history", "infection"],
        status: "landmark",
      },
      {
        name: "Penicillin discovery",
        description: "Fleming 1928, Florey & Chain therapeutic preparation 1941.",
        keyFact: "First true antibiotic, transformed treatment of bacterial infection. 1945 Nobel — Fleming, Florey, Chain. Inaugurated the antibiotic era; AMR now threatens its descendants.",
        tags: ["history", "antibiotics"],
        status: "landmark",
        xref: ["chemistry"],
      },
      {
        name: "Smallpox eradication",
        description: "WHO declared smallpox eradicated in 1980 — only human disease eradicated.",
        keyFact: "WHO Intensified Smallpox Eradication Program 1967–1980. Ring vaccination strategy. Last natural case Somalia 1977. Variola virus stocks remain at CDC and Vector under WHO custodianship.",
        tags: ["history", "vaccines", "eradication"],
        status: "landmark",
      },
      {
        name: "DNA double helix",
        description: "Watson, Crick, Franklin, Wilkins, 1953.",
        keyFact: "Foundation for molecular medicine, genetics, biotechnology. Rosalind Franklin's Photograph 51 crucial to model. 1962 Nobel to Watson, Crick, Wilkins; Franklin died 1958, ineligible.",
        tags: ["history", "molecular"],
        status: "landmark",
        xref: ["chemistry"],
      },
      {
        name: "Human Genome Project",
        description: "First reference human genome sequence — completed 2003.",
        keyFact: "~3 billion base pairs; ~20,000 protein-coding genes. Followed by 1000 Genomes, ENCODE, GTEx, gnomAD. Telomere-to-telomere (T2T-CHM13) consortium completed the previously inaccessible 8% in 2022.",
        tags: ["history", "genomics"],
        status: "landmark",
      },
      {
        name: "CRISPR-Cas9 gene editing",
        description: "Programmable RNA-guided DNA cutting (Doudna, Charpentier, 2012).",
        keyFact: "2020 Nobel Chemistry. First CRISPR therapeutic (Casgevy, exa-cel) FDA-approved 2023 for sickle cell disease and β-thalassemia. CRISPR diagnostics, base editing, prime editing rapidly expanding.",
        tags: ["history", "gene-editing"],
        status: "landmark",
        xref: ["chemistry"],
      },
      {
        name: "H. pylori and peptic ulcer disease",
        description: "Marshall & Warren showed bacteria, not stress, cause most peptic ulcers.",
        keyFact: "Marshall self-experiment 1984; 2005 Nobel. Eradication therapy transformed PUD from chronic to curable. Refuted decades of stress-based etiology orthodoxy.",
        tags: ["history", "ulcers"],
        status: "landmark",
      },
      {
        name: "Hormone replacement therapy (HRT) controversies",
        description: "WHI 2002 reshaped HRT prescribing.",
        keyFact: "Original WHI signaled excess breast cancer, CHD, stroke for combined HRT. Subsequent reanalysis: timing matters — initiated within 10 y of menopause / age <60 likely net beneficial for symptoms with lower harm. Pendulum still swinging.",
        organSystem: "reproductive",
        tags: ["history", "HRT"],
        status: "contested",
      },
      {
        name: "Vioxx withdrawal (2004)",
        description: "Rofecoxib withdrawn for increased MI and stroke risk.",
        keyFact: "Estimated 88,000–140,000 excess cardiovascular events in US. Led to greater post-marketing surveillance (FDA Sentinel) and rethinking of selective COX-2 inhibition.",
        tags: ["history", "drug-safety"],
        status: "landmark",
      },
      {
        name: "Andrew Wakefield MMR fraud (1998)",
        description: "Fraudulent Lancet paper claiming MMR-autism link.",
        keyFact: "Retracted by Lancet 2010. Wakefield struck off UK medical register. Falsified data; financial conflicts undisclosed. Triggered global vaccine hesitancy; measles outbreaks ongoing — among most consequential research frauds in medical history.",
        tags: ["history", "fraud", "vaccines"],
        status: "refuted",
      },
      {
        name: "Theranos (Holmes / Edison machine)",
        description: "Fraudulent blood-testing technology claim, 2003–2018.",
        keyFact: "Elizabeth Holmes claimed comprehensive blood testing from a finger-prick. Tests were inaccurate; company collapsed 2018. Holmes convicted 2022 (wire fraud + conspiracy), sentenced ~11 years. Cautionary tale on hype vs evidence.",
        tags: ["history", "fraud", "diagnostics"],
        status: "refuted",
      },
      {
        name: "Aducanumab approval controversy (2021)",
        description: "FDA accelerated approval for Alzheimer despite split advisory committee.",
        keyFact: "Three FDA advisors resigned. Two trials had conflicting results; clinical benefit unclear. Followed by lecanemab (2023, traditional approval) and donanemab (2024) with measurable but modest benefit. Reignited debate on amyloid hypothesis and accelerated approval.",
        organSystem: "neurological",
        tags: ["history", "FDA", "AD"],
        status: "contested",
      },
      {
        name: "Opioid epidemic",
        description: "OxyContin marketing and the US opioid crisis.",
        keyFact: "Purdue Pharma misrepresented addiction risk of OxyContin from 1996. ~1.1M US overdose deaths since 1999. Synthetic-opioid (fentanyl) era now dominant. Multiple settlements (Purdue, McKinsey, distributors) totaling tens of billions.",
        tags: ["history", "opioids", "addiction"],
        status: "landmark",
      },
      {
        name: "Replication crisis in biomedicine",
        description: "Many high-profile preclinical and clinical findings do not replicate.",
        keyFact: "Begley & Ellis 2012: 6/53 'landmark' cancer studies replicated. Reproducibility Project: Cancer Biology replicated ~50%. Drivers: p-hacking, publication bias, weak study power, fraud. Preregistration, open data are mitigations.",
        tags: ["history", "replication", "metaresearch"],
        status: "open",
        xref: ["statistics"],
      },
    ],
  },
];
