import type { Family } from "./types";

export const FAMILIES_8_14: Family[] = [
  // ── Family 8 — Gastroenterology ──────────────────────────────────────────
  {
    slug: "gastroenterology",
    number: 8,
    name: "Gastroenterology",
    blurb: "Diseases of esophagus, stomach, intestines, liver, pancreas, and biliary tract.",
    section: "B",
    color: "green",
    entries: [
      {
        name: "GERD",
        description: "Reflux of gastric contents causing symptoms or mucosal damage.",
        keyFact: "Affects ~20% of US adults. PPIs first-line; long-term concerns (C. diff, fractures, B12 deficiency, AKI) led to step-down approaches. Barrett esophagus surveillance every 3–5 y if confirmed.",
        organSystem: "gastrointestinal",
        tags: ["GI", "esophagus"],
      },
      {
        name: "Peptic ulcer disease",
        description: "Mucosal break in stomach or duodenum.",
        keyFact: "H. pylori (~70% of duodenal ulcers) and NSAIDs are dominant causes. Test-and-treat for H. pylori; quadruple therapy (PPI + bismuth + tetracycline + metronidazole) increasingly preferred over clarithromycin triple where resistance is high.",
        organSystem: "gastrointestinal",
        tags: ["GI", "ulcer"],
      },
      {
        name: "Inflammatory bowel disease",
        description: "Chronic immune-mediated bowel inflammation — Crohn disease and ulcerative colitis.",
        keyFact: "UC: continuous colonic inflammation from rectum. CD: transmural skip lesions anywhere mouth-to-anus. Treat-to-target with biologics (anti-TNF, anti-integrin, anti-IL-23, anti-JAK). Colon cancer surveillance after 8–10 y.",
        organSystem: "gastrointestinal",
        tags: ["GI", "IBD", "autoimmune"],
      },
      {
        name: "Irritable bowel syndrome",
        description: "Functional bowel disorder defined by Rome IV criteria.",
        keyFact: "Abdominal pain ≥1 d/week for 3 months + altered bowel habits. Subtypes IBS-D, IBS-C, IBS-M. Low-FODMAP diet, antispasmodics, linaclotide/plecanatide (IBS-C), rifaximin/eluxadoline (IBS-D).",
        organSystem: "gastrointestinal",
        tags: ["GI", "functional"],
      },
      {
        name: "Cirrhosis & portal hypertension",
        description: "End-stage liver fibrosis with reversal of architecture.",
        keyFact: "Etiologies: alcohol, MASH (formerly NAFLD), HCV, HBV, autoimmune. Complications: varices, ascites, hepatic encephalopathy, HCC. MELD-Na score guides transplant priority. Beta-blockers and band ligation for varices.",
        organSystem: "gastrointestinal",
        tags: ["GI", "liver"],
      },
      {
        name: "Metabolic dysfunction-associated steatotic liver disease (MASLD)",
        description: "Hepatic steatosis with cardiometabolic risk; formerly NAFLD.",
        keyFact: "Affects ~30% of global adults. Resmetirom (THR-β agonist) FDA-approved 2024 — first drug for MASH with fibrosis. GLP-1 RAs (semaglutide, tirzepatide) reduce hepatic steatosis as off-target benefit.",
        organSystem: "gastrointestinal",
        tags: ["GI", "MASLD"],
        status: "landmark",
      },
      {
        name: "Acute pancreatitis",
        description: "Sudden inflammation of pancreas, most often from gallstones or alcohol.",
        keyFact: "Diagnosis: 2 of 3 — characteristic pain, lipase >3× ULN, imaging. Aggressive crystalloid (lactated Ringer's), early enteral nutrition. Severity by BISAP, Ranson, APACHE II.",
        organSystem: "gastrointestinal",
        tags: ["GI", "pancreas"],
      },
      {
        name: "Cholelithiasis & cholecystitis",
        description: "Gallstones and infection/inflammation of the gallbladder.",
        keyFact: "~10% of adults have gallstones. Murphy sign + RUQ pain + fever + leukocytosis → cholecystitis. Laparoscopic cholecystectomy within 72 h for acute cholecystitis preferred.",
        organSystem: "gastrointestinal",
        tags: ["GI", "biliary"],
      },
      {
        name: "Celiac disease",
        description: "Immune-mediated enteropathy triggered by gluten.",
        keyFact: "HLA-DQ2/DQ8 in nearly all patients. Anti-tissue transglutaminase IgA highly sensitive/specific (with total IgA check). Duodenal biopsy confirms with villous atrophy. Lifelong gluten-free diet.",
        organSystem: "gastrointestinal",
        tags: ["GI", "celiac", "autoimmune"],
      },
      {
        name: "Diverticular disease",
        description: "Outpouchings of colonic mucosa (diverticulosis) ± inflammation (diverticulitis).",
        keyFact: "Prevalence rises with age (~50% by 60). Uncomplicated diverticulitis often managed outpatient without antibiotics (low-risk). Complicated: IV antibiotics ± drainage/surgery.",
        organSystem: "gastrointestinal",
        tags: ["GI", "colon"],
      },
      {
        name: "GI bleeding",
        description: "Hemorrhage from anywhere in the GI tract — upper or lower.",
        keyFact: "Upper (hematemesis, melena): ulcers, varices, Mallory-Weiss. EGD within 24 h, PPI infusion, octreotide for varices. Lower (hematochezia): diverticular, vascular, colitis, malignancy.",
        organSystem: "gastrointestinal",
        tags: ["GI", "bleeding"],
      },
      {
        name: "Hepatitis A, B, C, D, E",
        description: "Viral inflammation of the liver — fecal-oral (A, E) or bloodborne (B, C, D).",
        keyFact: "HCV curable with DAAs (sofosbuvir-based regimens >95% SVR in 8–12 weeks). HBV: tenofovir or entecavir suppress but rarely cure. Universal HCV screening for all adults ≥18.",
        organSystem: "gastrointestinal",
        tags: ["GI", "hepatitis"],
      },
      {
        name: "Colorectal cancer screening",
        description: "Detection of preclinical CRC and adenomatous polyps.",
        keyFact: "USPSTF 2021: begin screening at age 45 (down from 50). Options: colonoscopy q10y (gold standard), FIT yearly, multitarget stool DNA q3y, CT colonography q5y, flex sig q5y.",
        organSystem: "gastrointestinal",
        tags: ["GI", "screening", "prevention"],
      },
    ],
  },

  // ── Family 9 — Pulmonology ───────────────────────────────────────────────
  {
    slug: "pulmonology",
    number: 9,
    name: "Pulmonology",
    blurb: "Diseases of the airways, lung parenchyma, and pleura.",
    section: "B",
    color: "amber",
    entries: [
      {
        name: "Asthma",
        description: "Chronic airway inflammation with reversible obstruction and hyperresponsiveness.",
        keyFact: "Step-wise GINA guidelines now recommend ICS-formoterol (MART/SMART) over SABA-only for all severities. Biologics (omalizumab, mepolizumab, benralizumab, dupilumab, tezepelumab) for severe phenotypes.",
        organSystem: "respiratory",
        tags: ["pulm", "asthma"],
      },
      {
        name: "COPD",
        description: "Chronic obstructive pulmonary disease — chronic bronchitis + emphysema.",
        keyFact: "FEV1/FVC <0.70 post-bronchodilator. Smoking principal cause. LABA + LAMA inhalers; add ICS for exacerbator phenotype. Azithromycin, roflumilast, lung-volume reduction for select patients.",
        organSystem: "respiratory",
        tags: ["pulm", "COPD"],
      },
      {
        name: "Pneumonia",
        description: "Lower-respiratory infection of lung parenchyma.",
        keyFact: "CAP empiric outpatient: amoxicillin or doxycycline (low-risk). Inpatient: ceftriaxone + azithromycin or respiratory fluoroquinolone. Pneumococcus, Mycoplasma, viruses (influenza, SARS-CoV-2, RSV) common.",
        organSystem: "respiratory",
        tags: ["pulm", "infection"],
      },
      {
        name: "Pulmonary embolism",
        description: "Venous thromboembolism lodged in pulmonary arteries.",
        keyFact: "Wells score + D-dimer for low-pretest; CT pulmonary angiography confirms. DOACs (apixaban, rivaroxaban) first-line. Thrombolysis for hemodynamic instability; catheter-directed for intermediate-high-risk.",
        organSystem: "respiratory",
        tags: ["pulm", "PE"],
      },
      {
        name: "ARDS",
        description: "Acute respiratory distress syndrome — diffuse alveolar damage with hypoxemia.",
        keyFact: "Berlin definition: acute, bilateral infiltrates, not cardiogenic, P/F ≤300. Lung-protective ventilation (Vt 6 mL/kg PBW, plateau ≤30). Prone positioning for severe ARDS. ECMO for refractory cases.",
        organSystem: "respiratory",
        tags: ["pulm", "critical-care"],
      },
      {
        name: "Idiopathic pulmonary fibrosis",
        description: "Progressive interstitial lung disease with UIP pattern.",
        keyFact: "Median survival ~3–5 years from diagnosis. Antifibrotics (pirfenidone, nintedanib) slow decline but do not reverse fibrosis. Lung transplant for select patients.",
        organSystem: "respiratory",
        tags: ["pulm", "ILD"],
      },
      {
        name: "Sarcoidosis",
        description: "Multisystem granulomatous disease of unknown cause.",
        keyFact: "Non-caseating granulomas. Bilateral hilar lymphadenopathy on CXR (stages I–IV). Lofgren syndrome (acute, often self-limited). Steroids first-line when treatment indicated; MTX, infliximab as steroid-sparing.",
        tags: ["pulm", "sarcoidosis"],
      },
      {
        name: "Lung cancer screening",
        description: "Low-dose CT screening reduces lung cancer mortality.",
        keyFact: "USPSTF 2021: annual LDCT for ages 50–80, 20+ pack-year history, currently smoking or quit ≤15 y ago. NLST showed 20% lung-cancer mortality reduction.",
        organSystem: "respiratory",
        tags: ["pulm", "screening", "cancer"],
      },
      {
        name: "Pleural disease",
        description: "Pleural effusion, pneumothorax, empyema, mesothelioma.",
        keyFact: "Light's criteria distinguish exudate from transudate. Pneumothorax: needle decompression if tension, then chest tube. Mesothelioma: asbestos-related, poor prognosis.",
        organSystem: "respiratory",
        tags: ["pulm", "pleura"],
      },
      {
        name: "Cystic fibrosis",
        description: "Autosomal recessive CFTR channel dysfunction → thick secretions.",
        keyFact: "Most common cause: ΔF508 deletion. Elexacaftor-tezacaftor-ivacaftor (Trikafta, 2019) — transformative CFTR modulator for ~90% of patients with ≥1 copy of F508del. Median survival now ~50+ y in treated patients.",
        organSystem: "respiratory",
        tags: ["pulm", "CF", "genetic"],
        status: "landmark",
      },
      {
        name: "Sleep-disordered breathing",
        description: "Obstructive sleep apnea and central sleep apnea.",
        keyFact: "AHI ≥5 with symptoms or ≥15 without. CPAP first-line for moderate-severe OSA. Oral appliances, hypoglossal nerve stimulation (Inspire), positional therapy, weight loss adjuncts.",
        organSystem: "respiratory",
        tags: ["pulm", "sleep"],
      },
      {
        name: "Tuberculosis (latent and active)",
        description: "Mycobacterium tuberculosis infection — most common in low/middle-income countries.",
        keyFact: "LTBI: IGRA or TST + no active disease — treat with 3 months INH + rifapentine (3HP) or 4 months rifampin. Active TB: 6 months RIPE with adherence support. MDR/XDR-TB: bedaquiline-containing regimens.",
        organSystem: "respiratory",
        tags: ["pulm", "TB", "global-health"],
      },
    ],
  },

  // ── Family 10 — Nephrology ───────────────────────────────────────────────
  {
    slug: "nephrology",
    number: 10,
    name: "Nephrology",
    blurb: "Diseases of the kidneys, electrolytes, acid-base balance, and dialysis.",
    section: "B",
    color: "blue",
    entries: [
      {
        name: "Chronic kidney disease",
        description: "GFR <60 or kidney damage markers for ≥3 months.",
        keyFact: "KDIGO staging G1–G5 (by eGFR) and A1–A3 (by albuminuria). SGLT2 inhibitors (empagliflozin, dapagliflozin) and finerenone slow CKD progression in diabetics. Race-free CKD-EPI eGFR equation (2021) now standard.",
        organSystem: "renal",
        tags: ["nephro", "CKD"],
      },
      {
        name: "Acute kidney injury",
        description: "Abrupt decline in kidney function over hours to days.",
        keyFact: "KDIGO: SCr rise ≥0.3 mg/dL in 48 h or 1.5× baseline in 7 d or oliguria. Causes: pre-renal (volume depletion, hepatorenal), intrinsic (ATN, AIN, GN), post-renal (obstruction).",
        organSystem: "renal",
        tags: ["nephro", "AKI"],
      },
      {
        name: "Glomerulonephritis",
        description: "Inflammation of glomeruli — nephritic vs nephrotic syndromes.",
        keyFact: "Nephritic: hematuria, RBC casts, hypertension, mild proteinuria (IgA nephropathy, post-strep, lupus, anti-GBM). Nephrotic: >3.5 g/d proteinuria, edema, hyperlipidemia (FSGS, MN, MCD, diabetic).",
        organSystem: "renal",
        tags: ["nephro", "GN"],
      },
      {
        name: "Dialysis",
        description: "Renal replacement therapy — hemodialysis or peritoneal dialysis.",
        keyFact: "Indications: severe hyperkalemia, refractory acidosis, fluid overload, uremic complications, certain toxins. HD typical 3×/week; PD home-based, more physiologic. ~800k US patients on dialysis.",
        organSystem: "renal",
        tags: ["nephro", "dialysis"],
      },
      {
        name: "Kidney transplantation",
        description: "Surgical placement of donor kidney; gold-standard ESRD therapy.",
        keyFact: "Living-donor > deceased-donor outcomes. Induction (basiliximab, ATG) + maintenance immunosuppression (tacrolimus + MMF + steroids). 5-y graft survival ~85% living, ~75% deceased.",
        organSystem: "renal",
        tags: ["nephro", "transplant"],
      },
      {
        name: "Polycystic kidney disease",
        description: "Inherited cystic kidney disease — most often autosomal dominant.",
        keyFact: "ADPKD: PKD1 (most), PKD2; cysts in kidneys, liver. Tolvaptan slows GFR decline. Half progress to ESRD by age 60. Screen for intracranial aneurysms in family history of SAH.",
        organSystem: "renal",
        tags: ["nephro", "genetic"],
      },
      {
        name: "Urinary tract infection",
        description: "Bacterial infection of bladder (cystitis) or kidney (pyelonephritis).",
        keyFact: "E. coli most common (~80%). Uncomplicated cystitis: nitrofurantoin, fosfomycin, or TMP-SMX. Pyelonephritis: ceftriaxone or fluoroquinolone. Recurrent UTI: methenamine, vaginal estrogen, cranberry adjunct.",
        organSystem: "renal",
        tags: ["nephro", "infection"],
      },
      {
        name: "Nephrolithiasis",
        description: "Kidney stones — most often calcium oxalate.",
        keyFact: "Lifetime prevalence ~10%. Stones <5 mm typically pass spontaneously; tamsulosin facilitates passage. >10 mm or refractory: lithotripsy, ureteroscopy. Prevent with hydration, dietary modifications by stone composition.",
        organSystem: "renal",
        tags: ["nephro", "stones"],
      },
      {
        name: "Hyperkalemia",
        description: "Serum K+ >5.0; medical emergency >6.5 or with ECG changes.",
        keyFact: "Causes: AKI, CKD, RAAS blockers, K+-sparing diuretics, hemolysis. Treatment: calcium gluconate (membrane stabilization), insulin + dextrose, beta-agonist, bicarbonate (if acidemic), patiromer/SZC, dialysis.",
        organSystem: "renal",
        tags: ["nephro", "electrolytes"],
      },
      {
        name: "Hyponatremia",
        description: "Serum Na+ <135 — most common electrolyte abnormality in hospitalized patients.",
        keyFact: "Workup: serum osmolality → urine osmolality → volume status. SIADH most common true hyponatremia. Correct slowly (≤8 mEq/L per 24 h) to avoid osmotic demyelination.",
        organSystem: "renal",
        tags: ["nephro", "electrolytes"],
      },
      {
        name: "Renal tubular acidosis",
        description: "Non-anion gap metabolic acidosis from tubular dysfunction.",
        keyFact: "Type 1 (distal): impaired H+ secretion, urine pH >5.5. Type 2 (proximal): impaired HCO3- reabsorption. Type 4: hypoaldosteronism with hyperkalemia.",
        organSystem: "renal",
        tags: ["nephro", "acid-base"],
      },
      {
        name: "Diabetic kidney disease",
        description: "Leading cause of ESRD in the US and most high-income countries.",
        keyFact: "Albuminuria → declining GFR. ACE inhibitors/ARBs reduce progression. SGLT2 inhibitors (canagliflozin, dapagliflozin) and finerenone (MRA) now standard adjuncts. Tight glycemic and BP control essential.",
        organSystem: "renal",
        tags: ["nephro", "diabetes"],
      },
    ],
  },

  // ── Family 11 — Rheumatology & Immunology ────────────────────────────────
  {
    slug: "rheumatology-immunology",
    number: 11,
    name: "Rheumatology & Immunology",
    blurb: "Autoimmune, autoinflammatory, and connective tissue disorders.",
    section: "B",
    color: "rose",
    entries: [
      {
        name: "Rheumatoid arthritis",
        description: "Symmetric inflammatory polyarthritis driven by autoimmunity.",
        keyFact: "RF and anti-CCP antibodies. Treat-to-target with methotrexate first; add TNF inhibitors, IL-6 (tocilizumab), JAK inhibitors (tofacitinib, baricitinib, upadacitinib) for inadequate response. Anti-CCP highly specific.",
        organSystem: "musculoskeletal",
        tags: ["rheum", "RA", "autoimmune"],
      },
      {
        name: "Systemic lupus erythematosus",
        description: "Multisystem autoimmune disease — classic 'great mimicker.'",
        keyFact: "ANA sensitive, anti-dsDNA/anti-Sm specific. Hydroxychloroquine for all. Belimumab and anifrolumab (anti-IFN α/β) for inadequately controlled disease. Lupus nephritis: MMF or cyclophosphamide induction.",
        organSystem: "immune",
        tags: ["rheum", "SLE", "autoimmune"],
      },
      {
        name: "Spondyloarthritides",
        description: "Family including ankylosing spondylitis, psoriatic, reactive, IBD-associated.",
        keyFact: "HLA-B27 association (90% in AS). MRI sacroiliac joints sensitive. NSAIDs first-line; TNF, IL-17 inhibitors (secukinumab, ixekizumab) for refractory disease. JAK inhibitors approved for AS, PsA.",
        organSystem: "musculoskeletal",
        tags: ["rheum", "SpA"],
      },
      {
        name: "Osteoarthritis",
        description: "Most common joint disease — cartilage loss with osteophyte formation.",
        keyFact: "Weight-bearing joints (knees, hips, spine). No DMARDs proven effective. Treatment: exercise, weight loss, NSAIDs, intra-articular corticosteroid, total joint arthroplasty for refractory disease.",
        organSystem: "musculoskeletal",
        tags: ["rheum", "OA"],
      },
      {
        name: "Gout & pseudogout",
        description: "Crystalline arthropathies — monosodium urate (gout) and CPPD (pseudogout).",
        keyFact: "Gout: negatively birefringent needles. Acute: NSAIDs, colchicine, steroids. Urate-lowering: allopurinol or febuxostat to serum urate <6.0; titrate slowly with anti-inflammatory cover.",
        organSystem: "musculoskeletal",
        tags: ["rheum", "gout"],
      },
      {
        name: "Vasculitis",
        description: "Inflammation of blood vessels classified by vessel size.",
        keyFact: "Large (giant cell, Takayasu), medium (PAN, Kawasaki), small (ANCA-associated: GPA, MPA, EGPA; immune-complex: HSP, cryoglobulinemic). ANCA-associated treated with rituximab or cyclophosphamide.",
        tags: ["rheum", "vasculitis"],
      },
      {
        name: "Systemic sclerosis",
        description: "Autoimmune disease with fibrosis, vasculopathy, autoantibodies.",
        keyFact: "Limited (CREST) vs diffuse. Anti-centromere → limited; anti-Scl-70 → diffuse with ILD; anti-RNA pol III → renal crisis. Nintedanib slows ILD progression. ACE inhibitors for renal crisis.",
        tags: ["rheum", "scleroderma"],
      },
      {
        name: "Sjögren syndrome",
        description: "Autoimmune destruction of exocrine glands.",
        keyFact: "Dry eyes + dry mouth + anti-Ro/SSA, anti-La/SSB antibodies. Schirmer test, lip biopsy for diagnosis. 5–10% lifetime risk of MALT lymphoma. Symptomatic treatment with secretagogues.",
        tags: ["rheum", "Sjögren"],
      },
      {
        name: "Inflammatory myopathies",
        description: "Dermatomyositis, polymyositis, IMNM, IBM.",
        keyFact: "Proximal muscle weakness + elevated CK. Myositis-specific antibodies (anti-Jo-1, anti-Mi-2, anti-MDA5) guide phenotype/cancer screening. Steroids + steroid-sparing (MTX, MMF, IVIG, rituximab).",
        organSystem: "musculoskeletal",
        tags: ["rheum", "myositis"],
      },
      {
        name: "Allergy & anaphylaxis",
        description: "IgE-mediated and non-IgE hypersensitivity reactions.",
        keyFact: "Anaphylaxis: epinephrine IM 0.3 mg first-line (delay = death). Common triggers: food (peanut, tree nuts, shellfish), insect venom, drugs (β-lactams, NSAIDs). Oral immunotherapy (peanut: Palforzia) reduces severity.",
        organSystem: "immune",
        tags: ["immuno", "allergy"],
      },
      {
        name: "Immunodeficiency syndromes",
        description: "Primary (inherited) and secondary (acquired) defects of immunity.",
        keyFact: "CVID most common symptomatic primary immunodeficiency. SCID lethal without HSCT; gene therapy approved for ADA-SCID. IgG replacement for antibody deficiencies. Secondary causes: HIV, chemo, malnutrition.",
        organSystem: "immune",
        tags: ["immuno", "deficiency"],
      },
      {
        name: "Transplant immunology",
        description: "Rejection, GVHD, and immunosuppression in solid organ and HSCT.",
        keyFact: "Hyperacute, acute cellular, antibody-mediated, chronic rejection. Calcineurin inhibitors (tacrolimus), antiproliferatives (MMF), corticosteroids form maintenance backbone. Belatacept for renal transplant.",
        organSystem: "immune",
        tags: ["immuno", "transplant"],
      },
    ],
  },

  // ── Family 12 — Psychiatry & Mental Health ───────────────────────────────
  {
    slug: "psychiatry-mental-health",
    number: 12,
    name: "Psychiatry & Mental Health",
    blurb: "Mood, anxiety, psychotic, neurodevelopmental, and substance use disorders.",
    section: "B",
    color: "violet",
    entries: [
      {
        name: "Major depressive disorder",
        description: "Persistent low mood/anhedonia with neurovegetative symptoms.",
        keyFact: "DSM-5: ≥5 symptoms ≥2 weeks. SSRIs first-line. Esketamine (intranasal, 2019) — first novel mechanism in decades for TRD. Psilocybin-assisted therapy in late-stage trials. ECT remains highly effective for severe/refractory.",
        organSystem: "psychiatric",
        tags: ["psych", "depression"],
      },
      {
        name: "Bipolar disorder",
        description: "Recurrent mania/hypomania alternating with depressive episodes.",
        keyFact: "Bipolar I: at least one manic episode. Lithium remains gold standard for mood stabilization and suicide prevention. Quetiapine, lurasidone for bipolar depression. Antidepressant monotherapy avoided.",
        organSystem: "psychiatric",
        tags: ["psych", "bipolar"],
      },
      {
        name: "Schizophrenia",
        description: "Chronic psychotic disorder with positive, negative, and cognitive symptoms.",
        keyFact: "Lifetime prevalence ~0.7%. Atypical antipsychotics first-line. Clozapine for treatment-resistant — uniquely effective but agranulocytosis risk requires REMS monitoring. KarXT (xanomeline-trospium, 2024) — first muscarinic M1/M4 mechanism.",
        organSystem: "psychiatric",
        tags: ["psych", "schizophrenia"],
        status: "landmark",
      },
      {
        name: "Anxiety disorders",
        description: "GAD, panic disorder, social anxiety, specific phobias.",
        keyFact: "Lifetime prevalence ~30%. CBT and SSRIs/SNRIs first-line. Benzodiazepines effective short-term but tolerance, dependence, and dementia risk in older adults limit chronic use.",
        organSystem: "psychiatric",
        tags: ["psych", "anxiety"],
      },
      {
        name: "PTSD",
        description: "Trauma- and stressor-related disorder with intrusion, avoidance, hyperarousal, mood symptoms.",
        keyFact: "Trauma-focused CBT (CPT, PE) first-line. Sertraline, paroxetine FDA-approved. Prazosin for nightmares. MDMA-assisted therapy showed efficacy in trials but FDA rejected NDA in 2024.",
        organSystem: "psychiatric",
        tags: ["psych", "PTSD"],
        status: "contested",
      },
      {
        name: "OCD",
        description: "Obsessions and/or compulsions causing distress or impairment.",
        keyFact: "Lifetime prevalence ~2–3%. Exposure and response prevention (ERP) + high-dose SSRIs first-line. Augmentation with antipsychotics for partial response. DBS for severe refractory cases.",
        organSystem: "psychiatric",
        tags: ["psych", "OCD"],
      },
      {
        name: "Autism spectrum disorder",
        description: "Neurodevelopmental condition with social communication differences and restricted/repetitive interests.",
        keyFact: "DSM-5 merged previous PDD subtypes. Prevalence ~1 in 36 children in the US (CDC, 2023). Early behavioral intervention improves outcomes; no FDA-approved disease-modifying pharmacotherapy.",
        organSystem: "psychiatric",
        tags: ["psych", "neurodevelopmental"],
      },
      {
        name: "ADHD",
        description: "Inattention and/or hyperactivity-impulsivity impairing function.",
        keyFact: "Stimulants (methylphenidate, amphetamines) most effective for symptoms. Atomoxetine, guanfacine, viloxazine non-stimulant options. Adult ADHD diagnosis increasingly recognized and treated.",
        organSystem: "psychiatric",
        tags: ["psych", "ADHD"],
      },
      {
        name: "Eating disorders",
        description: "Anorexia nervosa, bulimia nervosa, binge eating disorder, ARFID.",
        keyFact: "Anorexia has highest mortality of any psychiatric disorder (~5–10%). Family-based treatment (Maudsley) effective for adolescent AN. Lisdexamfetamine FDA-approved for BED. Fluoxetine for bulimia.",
        organSystem: "psychiatric",
        tags: ["psych", "eating"],
      },
      {
        name: "Substance use disorders",
        description: "Pathological use of alcohol, opioids, stimulants, tobacco, cannabis.",
        keyFact: "Opioid use disorder: methadone, buprenorphine reduce mortality ~50%. Alcohol use disorder: naltrexone, acamprosate, disulfiram. Tobacco: varenicline + counseling most effective.",
        organSystem: "psychiatric",
        tags: ["psych", "addiction"],
      },
      {
        name: "Suicide & self-harm",
        description: "Leading cause of death in young adults in many countries.",
        keyFact: "Universal screening with PHQ-9 / Columbia Suicide Severity Rating Scale. Means restriction (firearms, medications) the most evidence-based prevention. 988 Suicide & Crisis Lifeline (US, 2022).",
        organSystem: "psychiatric",
        tags: ["psych", "suicide"],
      },
      {
        name: "Dementia (Alzheimer & non-Alzheimer)",
        description: "Progressive cognitive decline impairing daily function.",
        keyFact: "AD most common (~60–80%); vascular, Lewy body, frontotemporal, mixed also common. Cholinesterase inhibitors and memantine modest symptomatic benefit. Lecanemab, donanemab for early AD (anti-amyloid).",
        organSystem: "neurological",
        tags: ["psych", "dementia"],
      },
    ],
  },

  // ── Family 13 — Obstetrics & Gynecology ──────────────────────────────────
  {
    slug: "obstetrics-gynecology",
    number: 13,
    name: "Obstetrics & Gynecology",
    blurb: "Pregnancy, childbirth, the female reproductive tract, and disorders thereof.",
    section: "B",
    color: "rose",
    entries: [
      {
        name: "Prenatal care",
        description: "Routine screening and risk reduction during pregnancy.",
        keyFact: "Folate ≥400 µg/d preconception → neural tube defects. First-trimester screening: PAPP-A, β-hCG, NT; cfDNA for aneuploidy. Anatomy scan ~18–22 weeks. Group B Strep at 36–38 weeks.",
        organSystem: "reproductive",
        tags: ["OBGYN", "prenatal"],
      },
      {
        name: "Preeclampsia",
        description: "New-onset hypertension + end-organ damage after 20 weeks.",
        keyFact: "Severe features: SBP ≥160, DBP ≥110, thrombocytopenia, renal insufficiency, transaminitis, pulmonary edema, neuro symptoms. Magnesium sulfate prevents eclamptic seizures. Delivery is definitive treatment. Low-dose aspirin from 12 weeks for high-risk patients.",
        organSystem: "reproductive",
        tags: ["OBGYN", "preeclampsia"],
      },
      {
        name: "Gestational diabetes",
        description: "Glucose intolerance first recognized in pregnancy.",
        keyFact: "Screen 24–28 weeks with 50-g GCT followed by 100-g GTT. First-line: nutrition + exercise; insulin if uncontrolled. Increased lifetime maternal T2DM risk; recheck postpartum.",
        organSystem: "reproductive",
        tags: ["OBGYN", "GDM"],
      },
      {
        name: "Labor & delivery",
        description: "Stages of labor and modes of delivery.",
        keyFact: "First stage (latent + active to 10 cm), second (delivery of baby), third (placenta). C-section rate ~32% in the US (2022). VBAC feasible for select patients. Operative vaginal delivery (forceps, vacuum) declining.",
        organSystem: "reproductive",
        tags: ["OBGYN", "labor"],
      },
      {
        name: "Postpartum hemorrhage",
        description: "Blood loss ≥1000 mL or with hemodynamic instability within 24 h of delivery.",
        keyFact: "Four T's: Tone (atony, 70%), Trauma, Tissue (retained), Thrombin. Uterine massage, oxytocin, methylergonovine, carboprost, misoprostol, TXA, balloon tamponade, surgery.",
        organSystem: "reproductive",
        tags: ["OBGYN", "PPH"],
      },
      {
        name: "Contraception",
        description: "Hormonal, barrier, and long-acting reversible methods.",
        keyFact: "LARCs (IUDs, implants) most effective reversible — failure rate <1%/year. Levonorgestrel IUD effective up to 8 years; copper IUD up to 12 years. Combined hormonal contraception contraindicated in active smokers ≥35.",
        organSystem: "reproductive",
        tags: ["OBGYN", "contraception"],
      },
      {
        name: "Endometriosis",
        description: "Endometrial-like tissue outside the uterus causing pain and infertility.",
        keyFact: "Affects ~10% of reproductive-age women. Often diagnostic delay >5 years. Treatment: NSAIDs, hormonal suppression, GnRH antagonists (elagolix, relugolix). Laparoscopic excision for refractory pain or fertility.",
        organSystem: "reproductive",
        tags: ["OBGYN", "endometriosis"],
      },
      {
        name: "Polycystic ovary syndrome",
        description: "Hyperandrogenism + ovulatory dysfunction + polycystic ovaries (Rotterdam criteria).",
        keyFact: "Most common cause of anovulatory infertility. Letrozole first-line for ovulation induction. Combined OCPs for cycle regulation. Metformin for metabolic dysfunction. Lifestyle modification central.",
        organSystem: "reproductive",
        tags: ["OBGYN", "PCOS"],
      },
      {
        name: "Cervical cancer screening",
        description: "Detection of preclinical cervical cancer and HPV.",
        keyFact: "USPSTF/ASCCP: Cytology q3y ages 21–29; co-test or primary HPV q5y ages 30–65. HPV vaccination (Gardasil 9) prevents ~90% of HPV-related cancers — game-changer.",
        organSystem: "reproductive",
        tags: ["OBGYN", "cancer", "screening"],
        status: "landmark",
      },
      {
        name: "Menopause",
        description: "Cessation of menses ≥12 months from final menstrual period.",
        keyFact: "Average age 51. Vasomotor symptoms, GSM, sleep, mood, cognition. Hormone therapy effective for moderate-severe symptoms; risks (VTE, breast cancer, stroke) depend on age, duration, formulation. Fezolinetant (NK3 antagonist, 2023) — non-hormonal option.",
        organSystem: "reproductive",
        tags: ["OBGYN", "menopause"],
      },
      {
        name: "Maternal mortality",
        description: "Death during pregnancy or within 42 days postpartum.",
        keyFact: "US has highest maternal mortality among high-income countries (~22 per 100k live births, 2022 — pre-pandemic baseline). Black maternal mortality 2–3× higher than white. Leading causes: mental health, hemorrhage, cardiomyopathy, hypertension.",
        organSystem: "reproductive",
        tags: ["OBGYN", "mortality"],
        status: "open",
        xref: ["statistics"],
      },
      {
        name: "Sexually transmitted infections",
        description: "Chlamydia, gonorrhea, syphilis, HSV, HPV, trichomonas, HIV.",
        keyFact: "Chlamydia: doxycycline. Gonorrhea: ceftriaxone (rising resistance). Syphilis: penicillin; rates rising sharply in the US. Doxy-PEP within 72 h of unprotected sex prevents chlamydia, syphilis, possibly gonorrhea in MSM.",
        organSystem: "reproductive",
        tags: ["OBGYN", "STI", "infection"],
      },
    ],
  },

  // ── Family 14 — Pediatrics ───────────────────────────────────────────────
  {
    slug: "pediatrics",
    number: 14,
    name: "Pediatrics",
    blurb: "Medical care of infants, children, and adolescents.",
    section: "B",
    color: "amber",
    entries: [
      {
        name: "Childhood vaccinations",
        description: "Routine immunizations preventing infectious morbidity and mortality.",
        keyFact: "ACIP schedule: hexavalent, pneumococcal, MMR, varicella, rotavirus, hepatitis A/B, HPV, meningococcal, influenza, COVID-19. Measles cases re-emerging due to vaccine hesitancy and missed catch-up.",
        tags: ["peds", "vaccines", "prevention"],
        status: "landmark",
      },
      {
        name: "Sudden infant death syndrome (SIDS)",
        description: "Sudden unexplained death of infant <1 y, usually during sleep.",
        keyFact: "'Back to Sleep' campaign (1994) reduced US SIDS rates ~50%. Other modifiable risks: firm sleep surface, no soft bedding/bumpers, no co-sleeping in unsafe settings, breastfeeding, immunization, room-sharing without bed-sharing.",
        tags: ["peds", "SIDS"],
      },
      {
        name: "Childhood asthma",
        description: "Most common chronic disease of childhood.",
        keyFact: "Step-wise management — ICS-formoterol now first-line at all severities (GINA 2023). Phenotyping for severe asthma; biologics (omalizumab, mepolizumab, dupilumab) approved ≥6 y.",
        organSystem: "respiratory",
        tags: ["peds", "asthma"],
      },
      {
        name: "Bronchiolitis",
        description: "Lower respiratory infection in infants, usually RSV.",
        keyFact: "Supportive care only — bronchodilators, steroids, antibiotics not routinely recommended. Nirsevimab (long-acting RSV mAb, 2023) and maternal RSV vaccine prevent severe disease in infants.",
        organSystem: "respiratory",
        tags: ["peds", "RSV"],
        status: "landmark",
      },
      {
        name: "Otitis media",
        description: "Middle ear inflammation/infection — peak ages 6–24 months.",
        keyFact: "Acute OM diagnosis: bulging TM ± otalgia. Watchful waiting for select cases. Amoxicillin first-line; amox-clav if treatment failure. Tympanostomy tubes for recurrent disease or persistent effusion.",
        tags: ["peds", "otitis"],
      },
      {
        name: "Developmental milestones",
        description: "Expected motor, language, social, and cognitive milestones.",
        keyFact: "AAP/CDC milestones revised 2022 to 75th percentile (was 50th) to identify earlier intervention candidates. Routine surveillance + autism screening (M-CHAT-R/F) at 18 and 24 months.",
        organSystem: "neurological",
        tags: ["peds", "development"],
      },
      {
        name: "Failure to thrive",
        description: "Inadequate weight gain or growth in young children.",
        keyFact: "Weight <5th percentile or crossing two major growth-chart percentiles downward. Investigate caloric intake, malabsorption, increased metabolic demand. Most cases nutritional/psychosocial.",
        tags: ["peds", "growth"],
      },
      {
        name: "Pediatric obesity",
        description: "BMI ≥95th percentile for age/sex.",
        keyFact: "AAP 2023: intensive health behavior and lifestyle treatment ≥6 y. Pharmacotherapy (semaglutide, liraglutide ≥12 y) and bariatric surgery (≥13 y for severe) added — major guideline shift.",
        tags: ["peds", "obesity"],
        status: "landmark",
      },
      {
        name: "Congenital heart disease",
        description: "Structural cardiac defects present at birth.",
        keyFact: "~1% of live births. Critical CHD screening with pulse oximetry within 24–48 h of birth. Common: VSD, ASD, ToF, transposition, coarctation, hypoplastic left heart. Most survivors now reach adulthood.",
        organSystem: "cardiovascular",
        tags: ["peds", "cardiac", "congenital"],
      },
      {
        name: "Pediatric cancers",
        description: "Childhood malignancies — leukemia, brain tumors, lymphoma, neuroblastoma, Wilms.",
        keyFact: "ALL most common (~25%), >85% cure with risk-adapted chemotherapy. CAR-T (tisagenlecleucel) for refractory/relapsed B-ALL. Pediatric oncology cooperative groups (COG) drive standardized care.",
        tags: ["peds", "cancer", "oncology"],
      },
      {
        name: "Sickle cell disease",
        description: "Autosomal recessive hemoglobinopathy — HbS β-globin variant.",
        keyFact: "Hydroxyurea reduces vaso-occlusive crises. Voxelotor, crizanlizumab, L-glutamine adjuncts. CRISPR-edited autologous gene therapy (Casgevy, 2023) and lentiviral gene therapy (Lyfgenia, 2023) curative for severe disease.",
        organSystem: "hematological",
        tags: ["peds", "SCD", "genetic"],
        status: "landmark",
      },
      {
        name: "Pediatric infectious disease",
        description: "Common childhood infections — strep throat, hand-foot-mouth, croup, scarlet fever, Kawasaki.",
        keyFact: "Kawasaki: fever ≥5 d + 4 of 5 (conjunctivitis, rash, mucositis, extremity changes, cervical adenopathy). IVIG + aspirin within 10 d prevents coronary aneurysms.",
        tags: ["peds", "infection"],
      },
    ],
  },
];
