import type { Family } from "./types";

export const FAMILIES_1_7: Family[] = [
  // ── Family 1 — Anatomy & Physiology ──────────────────────────────────────
  {
    slug: "anatomy-physiology",
    number: 1,
    name: "Anatomy & Physiology",
    blurb: "Body structure and the integrated function of organ systems.",
    section: "A",
    color: "violet",
    entries: [
      {
        name: "Cardiac cycle",
        description: "The sequence of mechanical events from one heartbeat to the next.",
        keyFact: "Systole (ventricular contraction, ~0.3 s) ejects blood; diastole (~0.5 s at 75 bpm) refills the ventricles. Stroke volume × heart rate = cardiac output (~5 L/min at rest).",
        organSystem: "cardiovascular",
        tags: ["physiology", "heart"],
      },
      {
        name: "Pulmonary gas exchange",
        description: "Diffusion of O2 and CO2 across the alveolar-capillary membrane.",
        keyFact: "Driven by partial-pressure gradients (Fick's law). Arterial PaO2 ~95 mmHg, PaCO2 ~40 mmHg at sea level; A-a gradient quantifies impaired exchange.",
        organSystem: "respiratory",
        tags: ["physiology", "lungs"],
        xref: ["chemistry"],
      },
      {
        name: "Nephron function",
        description: "The kidney's functional unit — filters plasma and adjusts composition.",
        keyFact: "~1 million per kidney. Glomerular filtration (~125 mL/min GFR) followed by tubular reabsorption (>99% of filtrate) and secretion. The countercurrent loop concentrates urine.",
        organSystem: "renal",
        tags: ["physiology", "kidney"],
      },
      {
        name: "Action potential",
        description: "All-or-none electrical signal propagated along neurons and muscle.",
        keyFact: "Threshold (~−55 mV) triggers Na+ influx → depolarization (~+30 mV) → K+ efflux → repolarization. Refractory period prevents back-propagation.",
        organSystem: "neurological",
        tags: ["physiology", "neuron"],
      },
      {
        name: "Skeletal muscle contraction",
        description: "Sliding-filament mechanism powered by ATP and calcium.",
        keyFact: "Ca2+ binds troponin, exposing actin sites; myosin heads bind, pivot (power stroke), and detach on ATP binding. Rigor mortis = no ATP, no detachment.",
        organSystem: "musculoskeletal",
        tags: ["physiology", "muscle"],
      },
      {
        name: "Endocrine signaling",
        description: "Hormones released by glands act on distant target tissues.",
        keyFact: "Receptor-mediated; lipophilic hormones (steroids, thyroid) cross membranes and act on nuclear receptors; peptide hormones (insulin, GH) bind surface receptors. Negative feedback dominates.",
        organSystem: "endocrine",
        tags: ["physiology", "hormones"],
        xref: ["chemistry"],
      },
      {
        name: "Digestion & absorption",
        description: "Mechanical and enzymatic breakdown of food into absorbable units.",
        keyFact: "Carbs → monosaccharides (amylase, brush-border disaccharidases); proteins → amino acids/peptides (pepsin, trypsin); fats → fatty acids + monoglycerides (lipase, bile salts). Most absorption in the jejunum.",
        organSystem: "gastrointestinal",
        tags: ["physiology", "digestion"],
        xref: ["chemistry"],
      },
      {
        name: "Blood-brain barrier",
        description: "Tight endothelial barrier that restricts solute entry into the CNS.",
        keyFact: "Continuous tight junctions + astrocyte foot processes. Lipophilic small molecules cross; hydrophilic and large molecules generally excluded. Compromised in stroke, MS, brain tumors.",
        organSystem: "neurological",
        tags: ["physiology", "brain"],
      },
      {
        name: "Acid-base balance",
        description: "Tight regulation of arterial pH around 7.40 ± 0.05.",
        keyFact: "Bicarbonate buffer (CO2/HCO3-) with lungs (rapid, volatile) and kidneys (slow, fixed-acid). Henderson-Hasselbalch: pH = 6.1 + log([HCO3-]/0.03·PCO2).",
        tags: ["physiology", "homeostasis"],
        xref: ["chemistry"],
      },
      {
        name: "Hematopoiesis",
        description: "Production of red cells, white cells, and platelets from marrow stem cells.",
        keyFact: "All blood lineages descend from hematopoietic stem cells in marrow. Erythropoietin (kidney) drives RBC production; thrombopoietin drives platelets; G-CSF drives neutrophils.",
        organSystem: "hematological",
        tags: ["physiology", "blood"],
      },
      {
        name: "Hemostasis & coagulation cascade",
        description: "Sequential clotting cascade producing fibrin from soluble fibrinogen.",
        keyFact: "Primary hemostasis (platelet plug) + secondary (cascade: intrinsic + extrinsic → common pathway → thrombin → fibrin). PT measures extrinsic; aPTT measures intrinsic.",
        organSystem: "hematological",
        tags: ["physiology", "clotting"],
      },
      {
        name: "Homeostasis",
        description: "Maintenance of stable internal conditions via negative feedback.",
        keyFact: "Core temperature, glucose, osmolarity, pH, and BP held within narrow ranges by integrated neuro-endocrine loops. Loss of homeostasis defines critical illness.",
        tags: ["physiology", "foundations"],
      },
      {
        name: "Autonomic nervous system",
        description: "Involuntary sympathetic and parasympathetic control of visceral function.",
        keyFact: "Sympathetic (fight-or-flight) — norepinephrine/epinephrine, α/β receptors. Parasympathetic (rest-and-digest) — acetylcholine, muscarinic/nicotinic. Most organs receive both.",
        organSystem: "neurological",
        tags: ["physiology", "ANS"],
      },
      {
        name: "Reproductive physiology",
        description: "Hypothalamic-pituitary-gonadal axis governs menstrual cycle and spermatogenesis.",
        keyFact: "GnRH → FSH/LH → estrogen/progesterone or testosterone. The menstrual cycle (~28 d) has follicular, ovulatory, and luteal phases; ovulation at LH surge.",
        organSystem: "reproductive",
        tags: ["physiology", "reproduction"],
      },
    ],
  },

  // ── Family 2 — Pathology ─────────────────────────────────────────────────
  {
    slug: "pathology",
    number: 2,
    name: "Pathology",
    blurb: "Mechanisms of disease — cell injury, inflammation, neoplasia, and hemodynamic disorders.",
    section: "A",
    color: "indigo",
    entries: [
      {
        name: "Cell injury & necrosis",
        description: "Reversible to irreversible damage, ending in necrotic cell death.",
        keyFact: "ATP depletion, free-radical injury, membrane damage. Coagulative necrosis (ischemic infarcts), liquefactive (CNS, abscesses), caseous (TB), fat necrosis (pancreatitis).",
        tags: ["pathology", "cell-death"],
      },
      {
        name: "Apoptosis",
        description: "Programmed, non-inflammatory cell death.",
        keyFact: "Intrinsic (mitochondrial cytochrome c → caspase-9) and extrinsic (death receptors → caspase-8) pathways converge on caspase-3. Hallmark: nuclear fragmentation without membrane rupture.",
        tags: ["pathology", "apoptosis"],
      },
      {
        name: "Acute inflammation",
        description: "Stereotyped vascular and cellular response to injury, minutes to days.",
        keyFact: "Cardinal signs: rubor, calor, tumor, dolor, functio laesa. Mediators: histamine, prostaglandins, complement (C3a/C5a), TNF, IL-1. Neutrophil-dominant.",
        tags: ["pathology", "inflammation"],
      },
      {
        name: "Chronic inflammation",
        description: "Sustained inflammation with tissue destruction and attempted repair.",
        keyFact: "Macrophage- and lymphocyte-predominant. Granuloma formation in persistent insults (TB, sarcoidosis). Drives fibrosis and many cancers.",
        tags: ["pathology", "inflammation"],
      },
      {
        name: "Neoplasia & cancer hallmarks",
        description: "Uncontrolled clonal cell proliferation.",
        keyFact: "Hanahan-Weinberg hallmarks: sustained proliferative signaling, growth-suppressor evasion, replicative immortality, angiogenesis, invasion/metastasis, immune evasion, altered metabolism, genome instability, tumor-promoting inflammation, replicative stress.",
        tags: ["pathology", "cancer"],
      },
      {
        name: "Benign vs malignant",
        description: "Locally confined vs locally invasive and metastatic neoplasia.",
        keyFact: "Benign: well-differentiated, encapsulated, slow growth, no metastasis. Malignant: poorly differentiated, invasive, metastasizes. Metastasis is the defining feature of malignancy.",
        tags: ["pathology", "cancer"],
      },
      {
        name: "Atherosclerosis",
        description: "Lipid-driven inflammatory disease of arterial intima.",
        keyFact: "Endothelial dysfunction → LDL retention → macrophage foam cells → fibrous plaque → plaque rupture → thrombosis. Underlies most MI, ischemic stroke, peripheral artery disease.",
        organSystem: "cardiovascular",
        tags: ["pathology", "atherosclerosis"],
      },
      {
        name: "Ischemia & infarction",
        description: "Insufficient blood supply progressing to tissue death.",
        keyFact: "Inadequate perfusion → hypoxia → reversible injury → infarction. End-arterial organs (heart, brain, kidney) most vulnerable. Reperfusion injury can extend damage via free radicals.",
        tags: ["pathology", "ischemia"],
      },
      {
        name: "Thrombosis & embolism",
        description: "Pathological clot formation and travel.",
        keyFact: "Virchow's triad: endothelial injury + stasis + hypercoagulability. PE from DVT kills ~100k/yr in the US. Arterial emboli typically from heart (AFib) or atheroma.",
        organSystem: "cardiovascular",
        tags: ["pathology", "thrombosis"],
      },
      {
        name: "Edema",
        description: "Excess interstitial fluid accumulation.",
        keyFact: "Driven by elevated hydrostatic pressure (heart failure), decreased oncotic pressure (nephrotic, cirrhosis), lymphatic obstruction, or increased permeability (inflammation). Starling forces balance.",
        tags: ["pathology", "fluid"],
      },
      {
        name: "Shock",
        description: "Systemic hypoperfusion of tissues.",
        keyFact: "Types: hypovolemic (hemorrhage), cardiogenic (pump failure), distributive (sepsis, anaphylaxis, neurogenic), obstructive (PE, tamponade). Lactate >2 marks tissue hypoperfusion.",
        tags: ["pathology", "shock"],
      },
      {
        name: "Hyperplasia, hypertrophy, atrophy, metaplasia, dysplasia",
        description: "Cellular adaptations to chronic stimuli.",
        keyFact: "Hyperplasia = more cells; hypertrophy = bigger cells; atrophy = shrinkage. Metaplasia = one mature cell type → another (Barrett esophagus). Dysplasia = disordered growth, premalignant.",
        tags: ["pathology", "adaptation"],
      },
      {
        name: "Amyloidosis",
        description: "Pathological extracellular deposition of misfolded fibrillar proteins.",
        keyFact: "Apple-green birefringence with Congo red under polarized light. Subtypes: AL (light chains), AA (chronic inflammation), ATTR (transthyretin). Restrictive cardiomyopathy a common cardiac manifestation.",
        tags: ["pathology", "deposition"],
      },
    ],
  },

  // ── Family 3 — Microbiology & Infectious Disease ─────────────────────────
  {
    slug: "microbiology-infectious-disease",
    number: 3,
    name: "Microbiology & Infectious Disease",
    blurb: "Bacteria, viruses, fungi, parasites and the syndromes they cause.",
    section: "A",
    color: "blue",
    entries: [
      {
        name: "Gram-positive vs Gram-negative bacteria",
        description: "Cell-wall structure determines stain and antibiotic susceptibility.",
        keyFact: "Gram-positive: thick peptidoglycan, retains crystal violet (purple). Gram-negative: thin peptidoglycan + outer membrane with LPS (endotoxin), counterstains red.",
        tags: ["microbiology", "bacteria"],
      },
      {
        name: "Staphylococcus aureus",
        description: "Skin/soft-tissue, bacteremia, endocarditis, toxin-mediated disease.",
        keyFact: "Coagulase-positive Gram-positive cocci in clusters. MRSA (methicillin-resistant) ~30% of S. aureus isolates in the US. Treated by vancomycin, linezolid, daptomycin.",
        tags: ["microbiology", "bacteria"],
      },
      {
        name: "Mycobacterium tuberculosis",
        description: "Slow-growing acid-fast bacillus; causes pulmonary and disseminated TB.",
        keyFact: "Caseating granulomas, Ghon complex. ~10 million new cases/yr globally; ~1.3 million deaths. RIPE: rifampin, isoniazid, pyrazinamide, ethambutol for ≥6 months.",
        organSystem: "respiratory",
        tags: ["microbiology", "tuberculosis"],
      },
      {
        name: "Streptococcus pneumoniae",
        description: "Leading cause of community-acquired pneumonia, otitis media, meningitis.",
        keyFact: "Lancet-shaped Gram-positive diplococcus, alpha-hemolytic. Polysaccharide capsule is the virulence factor. PCV13/PCV15/PCV20 + PPSV23 vaccines prevent invasive disease.",
        organSystem: "respiratory",
        tags: ["microbiology", "pneumococcus"],
      },
      {
        name: "Escherichia coli",
        description: "Gram-negative rod; commensal of gut, pathogen of UTI, neonatal sepsis, diarrhea.",
        keyFact: "Most common cause of UTI (~80%). Pathotypes: EHEC (O157:H7, Shiga toxin → HUS), ETEC (traveler's diarrhea), UPEC (uropathogenic), neonatal meningitis (K1 capsule).",
        tags: ["microbiology", "bacteria"],
      },
      {
        name: "HIV / AIDS",
        description: "Retrovirus infecting CD4+ T cells, causing progressive immunodeficiency.",
        keyFact: "AIDS = HIV + CD4 <200 or AIDS-defining illness. ART (≥3 drugs) suppresses viral load to undetectable; U=U (undetectable = untransmittable). PrEP (tenofovir/emtricitabine) prevents infection.",
        organSystem: "immune",
        tags: ["microbiology", "virus", "HIV"],
      },
      {
        name: "Influenza",
        description: "RNA virus causing seasonal epidemics and rare pandemics.",
        keyFact: "Segmented genome enables reassortment → antigenic shift → pandemics (1918, 1957, 1968, 2009). Annual vaccine targets predicted A and B strains; oseltamivir/baloxavir reduce duration if started <48 h.",
        organSystem: "respiratory",
        tags: ["microbiology", "virus", "influenza"],
      },
      {
        name: "SARS-CoV-2 / COVID-19",
        description: "Coronavirus that emerged 2019, causing COVID-19 pandemic.",
        keyFact: "Spike protein binds ACE2. mRNA vaccines (Pfizer, Moderna) first deployed Dec 2020 — first mRNA vaccines licensed for human use. ~7 million confirmed deaths globally (WHO, official); excess-mortality estimates higher.",
        organSystem: "respiratory",
        tags: ["microbiology", "virus", "COVID"],
        status: "landmark",
      },
      {
        name: "Hepatitis B & C",
        description: "Bloodborne viruses causing chronic hepatitis, cirrhosis, hepatocellular carcinoma.",
        keyFact: "HBV: DNA virus, partially preventable by vaccine, treated with tenofovir/entecavir. HCV: RNA virus, no vaccine, but >95% curable with direct-acting antivirals (sofosbuvir-based) in 8–12 weeks.",
        organSystem: "gastrointestinal",
        tags: ["microbiology", "virus", "hepatitis"],
      },
      {
        name: "Malaria (Plasmodium spp.)",
        description: "Mosquito-borne protozoal disease — 247M cases, 619k deaths in 2021 (WHO).",
        keyFact: "Five Plasmodium species infect humans; P. falciparum the deadliest. Cyclical fevers from synchronized RBC rupture. Artemisinin-combination therapies are first-line; RTS,S and R21 are the first malaria vaccines.",
        tags: ["microbiology", "parasite", "global-health"],
        status: "landmark",
      },
      {
        name: "Candida & invasive fungal infections",
        description: "Common commensal that becomes pathogenic in the immunocompromised.",
        keyFact: "C. albicans causes mucosal candidiasis; C. auris is multidrug-resistant and nosocomially transmitted. Echinocandins are first-line for candidemia; voriconazole for invasive aspergillosis.",
        tags: ["microbiology", "fungus"],
      },
      {
        name: "Antimicrobial resistance",
        description: "Microbial evolution rendering antibiotics ineffective.",
        keyFact: "AMR contributed to ~5 million deaths globally in 2019 (Lancet estimate). Mechanisms: enzymatic inactivation (β-lactamases), efflux pumps, target modification, decreased permeability. Stewardship + new drugs essential.",
        tags: ["microbiology", "resistance"],
        status: "open",
      },
      {
        name: "Sepsis",
        description: "Life-threatening organ dysfunction from dysregulated host response to infection.",
        keyFact: "Sepsis-3 definition: infection + acute SOFA ≥2. ~11 million deaths globally per year. Bundle: lactate, blood cultures, broad-spectrum antibiotics within 1 hour, 30 mL/kg crystalloid for hypotension/lactate ≥4.",
        tags: ["microbiology", "sepsis"],
      },
      {
        name: "Clostridioides difficile",
        description: "Toxin-producing Gram-positive anaerobe; cause of antibiotic-associated colitis.",
        keyFact: "Disrupted gut flora + spore germination → toxin A/B → pseudomembranous colitis. Fidaxomicin or oral vancomycin first-line; fecal microbiota transplant for recurrent disease.",
        organSystem: "gastrointestinal",
        tags: ["microbiology", "bacteria"],
      },
    ],
  },

  // ── Family 4 — Cardiology ────────────────────────────────────────────────
  {
    slug: "cardiology",
    number: 4,
    name: "Cardiology",
    blurb: "Diseases of the heart and great vessels — leading global cause of death.",
    section: "B",
    color: "sky",
    entries: [
      {
        name: "Myocardial infarction",
        description: "Ischemic death of cardiac muscle from acute coronary occlusion.",
        keyFact: "Defined by troponin rise + clinical/ECG/imaging evidence. STEMI: emergent PCI within 90 min of first medical contact (or fibrinolysis if PCI unavailable). NSTEMI: medical therapy + early invasive evaluation.",
        organSystem: "cardiovascular",
        tags: ["cardiology", "MI"],
      },
      {
        name: "Heart failure",
        description: "Inability of heart to meet metabolic demand at normal filling pressures.",
        keyFact: "HFrEF (EF ≤40%): GDMT — ARNI/ACEi, beta-blocker, MRA, SGLT2 inhibitor (the 'four pillars'). HFpEF (EF ≥50%): SGLT2 inhibitors are the first drug class with mortality benefit (EMPEROR-Preserved, DELIVER).",
        organSystem: "cardiovascular",
        tags: ["cardiology", "HF"],
      },
      {
        name: "Atrial fibrillation",
        description: "Irregularly irregular supraventricular arrhythmia.",
        keyFact: "Rate vs rhythm control; anticoagulation by CHA2DS2-VASc score. Direct oral anticoagulants (apixaban, rivaroxaban) preferred over warfarin in non-valvular AF. Catheter ablation increasingly used as first-line for symptomatic paroxysmal AF.",
        organSystem: "cardiovascular",
        tags: ["cardiology", "arrhythmia"],
      },
      {
        name: "Hypertension",
        description: "Sustained elevated arterial blood pressure.",
        keyFact: "ACC/AHA 2017 thresholds: ≥130/80 = stage 1, ≥140/90 = stage 2. First-line agents: thiazides, ACEi/ARB, CCBs. SPRINT showed intensive control (<120 SBP) reduces CV events in high-risk adults.",
        organSystem: "cardiovascular",
        tags: ["cardiology", "HTN"],
      },
      {
        name: "Coronary artery disease",
        description: "Atherosclerotic narrowing of epicardial coronaries causing angina or MI.",
        keyFact: "Risk factors: smoking, diabetes, hypertension, dyslipidemia, family history. Statins reduce events ~25% per 1 mmol/L LDL reduction. ISCHEMIA: invasive vs conservative similar for stable disease.",
        organSystem: "cardiovascular",
        tags: ["cardiology", "CAD"],
      },
      {
        name: "Valvular heart disease",
        description: "Stenosis or regurgitation of mitral, aortic, tricuspid, or pulmonic valves.",
        keyFact: "Aortic stenosis (calcific, ~3% of >75 y): SAVR or TAVR; TAVR now preferred in intermediate and even low-risk patients in many centers. Mitral regurgitation: repair > replacement when feasible.",
        organSystem: "cardiovascular",
        tags: ["cardiology", "valve"],
      },
      {
        name: "Cardiomyopathy",
        description: "Primary myocardial disease — dilated, hypertrophic, restrictive, arrhythmogenic.",
        keyFact: "HCM: most common inherited cardiac disease, prevalence ~1:500; sudden cardiac death risk in young athletes. Mavacamten (cardiac myosin inhibitor) FDA-approved 2022 for obstructive HCM.",
        organSystem: "cardiovascular",
        tags: ["cardiology", "cardiomyopathy"],
      },
      {
        name: "Cardiac arrest & resuscitation",
        description: "Sudden cessation of cardiac output requiring CPR and defibrillation.",
        keyFact: "Out-of-hospital survival ~10% in the US; key drivers are bystander CPR + early defibrillation for shockable rhythms (VF/pVT). High-quality compressions: ≥5 cm depth, 100–120/min, minimal interruptions.",
        organSystem: "cardiovascular",
        tags: ["cardiology", "ACLS"],
      },
      {
        name: "Pulmonary hypertension",
        description: "Mean pulmonary artery pressure ≥20 mmHg.",
        keyFact: "WHO Groups 1–5 by etiology. Group 1 PAH treated with PDE5 inhibitors, endothelin receptor antagonists, prostacyclins, soluble guanylate cyclase stimulators. Untreated severe PAH 5-y survival ~30%.",
        organSystem: "cardiovascular",
        tags: ["cardiology", "PH"],
      },
      {
        name: "Endocarditis",
        description: "Infection of cardiac valves, typically by bacteria.",
        keyFact: "Modified Duke criteria. Common causes: viridans strep, S. aureus, enterococci, HACEK. IV antibiotics 4–6 weeks; surgical indications include heart failure, abscess, large vegetation, persistent bacteremia.",
        organSystem: "cardiovascular",
        tags: ["cardiology", "infection"],
      },
      {
        name: "Dyslipidemia",
        description: "Abnormal lipid panel — elevated LDL, low HDL, elevated triglycerides.",
        keyFact: "High-intensity statin for ASCVD or LDL ≥190. PCSK9 inhibitors (evolocumab, alirocumab) and inclisiran (siRNA) reduce LDL when statins insufficient. Lower-LDL-is-better paradigm dominates.",
        tags: ["cardiology", "lipids"],
        xref: ["chemistry"],
      },
      {
        name: "Aortic dissection",
        description: "Tear in aortic intima allowing blood between layers of the wall.",
        keyFact: "Stanford A (ascending) — emergent surgery. Stanford B (descending) — typically medical (BP control) unless complicated. Severe tearing chest/back pain; CT angiography is diagnostic.",
        organSystem: "cardiovascular",
        tags: ["cardiology", "emergency"],
      },
      {
        name: "Pericardial disease",
        description: "Pericarditis, effusion, tamponade, constrictive pericarditis.",
        keyFact: "Acute pericarditis: pleuritic chest pain, diffuse ST elevation, PR depression. NSAIDs + colchicine. Tamponade: Beck's triad (hypotension, JVD, muffled heart sounds), pulsus paradoxus; pericardiocentesis lifesaving.",
        organSystem: "cardiovascular",
        tags: ["cardiology", "pericardium"],
      },
    ],
  },

  // ── Family 5 — Neurology ─────────────────────────────────────────────────
  {
    slug: "neurology",
    number: 5,
    name: "Neurology",
    blurb: "Diseases of the central and peripheral nervous system.",
    section: "B",
    color: "cyan",
    entries: [
      {
        name: "Ischemic stroke",
        description: "Acute brain ischemia from arterial occlusion.",
        keyFact: "Tissue plasminogen activator (tPA/alteplase) within 4.5 h; tenecteplase increasingly preferred. Mechanical thrombectomy for large-vessel occlusion within 6–24 h selected by perfusion imaging (DAWN, DEFUSE 3).",
        organSystem: "neurological",
        tags: ["neurology", "stroke"],
      },
      {
        name: "Intracerebral hemorrhage",
        description: "Bleeding within brain parenchyma — most often from hypertensive small-vessel disease.",
        keyFact: "Higher mortality than ischemic stroke (~40% at 30 d). BP control (target SBP ~130–140), reversal of anticoagulation, neurosurgery for select cases (cerebellar bleeds >3 cm).",
        organSystem: "neurological",
        tags: ["neurology", "stroke"],
      },
      {
        name: "Subarachnoid hemorrhage",
        description: "Bleeding into the subarachnoid space, typically from aneurysmal rupture.",
        keyFact: "Thunderclap headache, 'worst of my life.' CT sensitivity ~98% within 6 h; LP if negative and high suspicion. Endovascular coiling or surgical clipping; nimodipine prevents vasospasm.",
        organSystem: "neurological",
        tags: ["neurology", "emergency"],
      },
      {
        name: "Alzheimer disease",
        description: "Most common cause of dementia — progressive amyloid + tau neurodegeneration.",
        keyFact: "Hallmarks: amyloid-β plaques + neurofibrillary tau tangles. Lecanemab (2023) and donanemab (2024) — first anti-amyloid antibodies with clinically meaningful slowing of decline in early AD; controversial benefit/harm balance (ARIA).",
        organSystem: "neurological",
        tags: ["neurology", "dementia"],
        status: "contested",
      },
      {
        name: "Parkinson disease",
        description: "Progressive nigrostriatal dopaminergic neuron loss.",
        keyFact: "Cardinal: bradykinesia + rigidity, resting tremor, postural instability. Levodopa-carbidopa remains most effective symptomatic therapy. Deep brain stimulation of subthalamic nucleus/globus pallidus for motor fluctuations.",
        organSystem: "neurological",
        tags: ["neurology", "movement"],
      },
      {
        name: "Multiple sclerosis",
        description: "Autoimmune demyelinating disease of the CNS.",
        keyFact: "McDonald criteria: dissemination in space and time. High-efficacy DMTs (ocrelizumab, ofatumumab, natalizumab) increasingly first-line. Epstein-Barr virus identified as near-necessary risk factor (Bjornevik 2022).",
        organSystem: "neurological",
        tags: ["neurology", "MS", "autoimmune"],
        status: "landmark",
      },
      {
        name: "Epilepsy",
        description: "Tendency toward recurrent unprovoked seizures.",
        keyFact: "ILAE: ≥2 unprovoked seizures >24 h apart, or 1 seizure + high recurrence risk. Levetiracetam, lamotrigine, valproate broad-spectrum first-line. Refractory epilepsy: surgical evaluation, VNS, RNS, dietary therapies.",
        organSystem: "neurological",
        tags: ["neurology", "epilepsy"],
      },
      {
        name: "Migraine",
        description: "Recurrent episodic headache with associated neurological symptoms.",
        keyFact: "Lifetime prevalence ~15%, female predominant. CGRP receptor antagonists (-gepants) and CGRP monoclonal antibodies (erenumab, fremanezumab, galcanezumab, eptinezumab) — first migraine-specific preventives.",
        organSystem: "neurological",
        tags: ["neurology", "headache"],
      },
      {
        name: "Amyotrophic lateral sclerosis (ALS)",
        description: "Progressive motor neuron disease of upper and lower motor neurons.",
        keyFact: "Median survival 3–5 years from onset. Riluzole modestly extends survival; edaravone and the AMX0035 combination provide small benefits. SOD1, C9orf72, TARDBP, FUS most common familial genes.",
        organSystem: "neurological",
        tags: ["neurology", "motor-neuron"],
      },
      {
        name: "Peripheral neuropathy",
        description: "Damage to peripheral nerves causing sensory, motor, or autonomic dysfunction.",
        keyFact: "Diabetes is leading cause globally. Stocking-glove distribution typical. Treatment of pain: duloxetine, pregabalin, gabapentin; tight glycemic control prevents progression in diabetes.",
        organSystem: "neurological",
        tags: ["neurology", "peripheral"],
      },
      {
        name: "Meningitis & encephalitis",
        description: "Inflammation of meninges or brain parenchyma — typically infectious.",
        keyFact: "Bacterial meningitis: empiric ceftriaxone + vancomycin + dexamethasone, add ampicillin if Listeria risk. HSV encephalitis: empiric IV acyclovir while awaiting PCR. Mortality high without rapid treatment.",
        organSystem: "neurological",
        tags: ["neurology", "infection"],
      },
      {
        name: "Traumatic brain injury",
        description: "Acquired brain injury from external mechanical force.",
        keyFact: "GCS classification: mild (13–15), moderate (9–12), severe (3–8). CT to exclude bleeding/herniation. Avoid hypoxia, hypotension, hyperthermia — secondary injury drives outcome. CTE recognized in repetitive TBI.",
        organSystem: "neurological",
        tags: ["neurology", "trauma"],
        status: "contested",
      },
      {
        name: "Brain tumors",
        description: "Primary (glioma, meningioma) and metastatic intracranial neoplasms.",
        keyFact: "Glioblastoma: most aggressive primary; standard Stupp protocol — resection + temozolomide + radiation; median survival ~15 months. IDH and MGMT status guide prognosis and therapy.",
        organSystem: "neurological",
        tags: ["neurology", "tumor", "cancer"],
      },
    ],
  },

  // ── Family 6 — Oncology ──────────────────────────────────────────────────
  {
    slug: "oncology",
    number: 6,
    name: "Oncology",
    blurb: "Cancer biology, classification, and the major systemic and targeted therapies.",
    section: "B",
    color: "teal",
    entries: [
      {
        name: "Lung cancer",
        description: "Leading cause of cancer death worldwide.",
        keyFact: "Two broad types: NSCLC (~85%, adenocarcinoma + squamous + large cell) and SCLC. Driver mutations (EGFR, ALK, KRAS G12C, ROS1, BRAF, MET, HER2, NTRK, RET) targeted with specific TKIs. Immunotherapy standard for PD-L1+.",
        organSystem: "respiratory",
        tags: ["oncology", "lung"],
      },
      {
        name: "Breast cancer",
        description: "Most common cancer in women globally.",
        keyFact: "ER/PR/HER2 status defines therapy. HER2+: trastuzumab, pertuzumab, T-DXd. Triple-negative: chemo + PD-L1 inhibitors for select patients. CDK4/6 inhibitors (palbociclib, ribociclib, abemaciclib) for HR+/HER2-. BRCA1/2 confer hereditary risk.",
        organSystem: "reproductive",
        tags: ["oncology", "breast"],
      },
      {
        name: "Colorectal cancer",
        description: "Third most common cancer; third most common cancer death.",
        keyFact: "Adenoma-to-carcinoma sequence (APC → KRAS → TP53). Screening from age 45 (USPSTF, 2021). FOLFOX/FOLFIRI + biologic (anti-VEGF or anti-EGFR by RAS/BRAF). Right-sided tumors more often microsatellite-unstable, responsive to immunotherapy.",
        organSystem: "gastrointestinal",
        tags: ["oncology", "colorectal"],
      },
      {
        name: "Prostate cancer",
        description: "Most common male cancer in many countries.",
        keyFact: "PSA + DRE, with MRI-targeted biopsy increasingly standard. Indolent low-risk disease often managed with active surveillance. Androgen deprivation + AR pathway inhibitors (abiraterone, enzalutamide); PARP inhibitors for BRCA-mutated disease.",
        organSystem: "reproductive",
        tags: ["oncology", "prostate"],
      },
      {
        name: "Leukemia",
        description: "Malignancy of blood-forming cells — acute or chronic, lymphoid or myeloid.",
        keyFact: "AML: induction with '7+3' (cytarabine + anthracycline); midostaurin for FLT3, venetoclax + azacitidine for unfit. CML: BCR-ABL inhibitors (imatinib, dasatinib, nilotinib) transformed survival. ALL: pediatric protocols cure >85%.",
        organSystem: "hematological",
        tags: ["oncology", "leukemia"],
        status: "landmark",
      },
      {
        name: "Lymphoma",
        description: "Malignancy of lymphocytes — Hodgkin and non-Hodgkin types.",
        keyFact: "DLBCL: R-CHOP first-line, ~60% cure. Hodgkin: ABVD or BV-AVD, >85% cure in early disease. CD19 CAR-T (axicabtagene, lisocabtagene, tisagenlecleucel) for refractory aggressive B-cell lymphoma.",
        organSystem: "hematological",
        tags: ["oncology", "lymphoma"],
      },
      {
        name: "Pancreatic cancer",
        description: "Aggressive adenocarcinoma with poor prognosis.",
        keyFact: "5-year survival ~12% (US). FOLFIRINOX and gem-nab-paclitaxel first-line for fit patients. KRAS G12D found in >90%; pan-KRAS inhibitors in trials. Vague early symptoms drive late diagnosis.",
        organSystem: "gastrointestinal",
        tags: ["oncology", "pancreatic"],
        status: "open",
      },
      {
        name: "Melanoma",
        description: "Malignant tumor of melanocytes; most aggressive skin cancer.",
        keyFact: "BRAF V600E mutation in ~50%; treated with BRAF + MEK inhibitors. Immune checkpoint inhibitors (anti-PD-1, anti-CTLA-4) revolutionized metastatic disease — 5-y survival for stage IV now ~50% with combo.",
        organSystem: "dermatological",
        tags: ["oncology", "melanoma", "immunotherapy"],
        status: "landmark",
      },
      {
        name: "Hepatocellular carcinoma",
        description: "Primary liver cancer, usually arising in cirrhosis.",
        keyFact: "Underlying HBV/HCV, alcohol, MASH-related cirrhosis. Surveillance with US ± AFP in cirrhotics. Atezolizumab + bevacizumab first-line systemic therapy; lenvatinib, sorafenib alternatives.",
        organSystem: "gastrointestinal",
        tags: ["oncology", "liver"],
      },
      {
        name: "Glioblastoma",
        description: "Most aggressive primary brain tumor (WHO grade IV).",
        keyFact: "Median survival ~15 months despite resection + temozolomide + radiation. Tumor treating fields (Optune) modestly improve survival. MGMT promoter methylation predicts temozolomide response.",
        organSystem: "neurological",
        tags: ["oncology", "brain"],
        status: "open",
      },
      {
        name: "Cancer staging — TNM",
        description: "Universal classification by Tumor, Node, Metastasis.",
        keyFact: "AJCC/UICC TNM updated every several years. T (size/invasion), N (regional nodes), M (distant metastasis) combine into stage I–IV. Stage drives treatment selection and prognosis.",
        tags: ["oncology", "staging"],
      },
      {
        name: "Chemotherapy classes",
        description: "Cytotoxic systemic therapy targeting cell division.",
        keyFact: "Alkylators (cyclophosphamide), antimetabolites (5-FU, methotrexate), microtubule agents (taxanes, vinca), topoisomerase inhibitors (doxorubicin, etoposide), platinums (cisplatin). Combinations exploit additive cell-cycle action.",
        tags: ["oncology", "chemotherapy"],
        xref: ["chemistry"],
      },
      {
        name: "Targeted therapy",
        description: "Drugs aimed at specific molecular drivers of cancer.",
        keyFact: "Tyrosine kinase inhibitors (imatinib for BCR-ABL, EGFR-TKIs for lung), monoclonal antibodies (trastuzumab for HER2), small molecules (osimertinib, sotorasib for KRAS G12C). Molecular profiling now standard of care for many cancers.",
        tags: ["oncology", "targeted"],
      },
      {
        name: "Immunotherapy",
        description: "Therapies unleashing the immune system against tumor cells.",
        keyFact: "Checkpoint inhibitors (anti-PD-1: nivolumab, pembrolizumab; anti-CTLA-4: ipilimumab) standard across many cancers. CAR-T cells engineered ex vivo (CD19, BCMA targets). 2018 Nobel — Allison & Honjo for checkpoint biology.",
        organSystem: "immune",
        tags: ["oncology", "immunotherapy"],
        status: "landmark",
      },
    ],
  },

  // ── Family 7 — Endocrinology & Metabolism ────────────────────────────────
  {
    slug: "endocrinology-metabolism",
    number: 7,
    name: "Endocrinology & Metabolism",
    blurb: "Hormone disorders and the metabolic syndromes of diabetes, obesity, and thyroid disease.",
    section: "B",
    color: "emerald",
    entries: [
      {
        name: "Type 1 diabetes mellitus",
        description: "Autoimmune destruction of pancreatic β-cells causing absolute insulin deficiency.",
        keyFact: "GAD, IA-2, ZnT8 autoantibodies. Lifelong insulin replacement. Hybrid closed-loop pumps (Tandem Control-IQ, Omnipod 5, Medtronic 780G) now standard of care. Teplizumab (anti-CD3) FDA-approved 2022 to delay onset in stage 2.",
        organSystem: "endocrine",
        tags: ["endocrine", "T1DM"],
      },
      {
        name: "Type 2 diabetes mellitus",
        description: "Insulin resistance progressing to relative deficiency.",
        keyFact: "Diagnosis: A1c ≥6.5% or FPG ≥126 or OGTT 2-h ≥200. Metformin first-line. GLP-1 RAs (semaglutide, tirzepatide) and SGLT2 inhibitors now preferred adjuncts for ASCVD/CKD/HF benefit.",
        organSystem: "endocrine",
        tags: ["endocrine", "T2DM"],
      },
      {
        name: "Diabetic ketoacidosis",
        description: "Hyperglycemia + ketosis + acidosis from absolute insulin deficiency.",
        keyFact: "pH <7.3, HCO3- <18, anion gap ≥12, ketones positive. Fluids (NS), IV insulin infusion, K+ repletion before insulin if K+ <3.3. Bicarbonate only if pH <6.9.",
        organSystem: "endocrine",
        tags: ["endocrine", "DKA"],
      },
      {
        name: "Hypothyroidism",
        description: "Insufficient thyroid hormone production.",
        keyFact: "Primary (Hashimoto's, post-ablation): elevated TSH, low free T4. Levothyroxine replacement titrated to TSH 0.4–4.0 (lower in pregnancy). Subclinical hypothyroidism: treatment controversial below TSH ~10.",
        organSystem: "endocrine",
        tags: ["endocrine", "thyroid"],
      },
      {
        name: "Hyperthyroidism & Graves disease",
        description: "Excess thyroid hormone — most often Graves (TSI antibody).",
        keyFact: "Suppressed TSH + elevated free T4/T3. Treatment: methimazole (PTU in T1 pregnancy), radioactive iodine ablation, or thyroidectomy. Thyroid storm: beta-blocker, PTU, iodide, steroids.",
        organSystem: "endocrine",
        tags: ["endocrine", "thyroid"],
      },
      {
        name: "Adrenal insufficiency",
        description: "Inadequate cortisol production — primary (Addison) or central.",
        keyFact: "Symptoms: fatigue, hypotension, hyponatremia, hyperkalemia (primary). Cosyntropin stimulation test diagnostic. Lifelong hydrocortisone replacement; stress-dose steroids for illness/surgery. Adrenal crisis is life-threatening.",
        organSystem: "endocrine",
        tags: ["endocrine", "adrenal"],
      },
      {
        name: "Cushing syndrome",
        description: "Excess cortisol exposure — exogenous steroids most common; endogenous from pituitary, adrenal, ectopic ACTH.",
        keyFact: "Central obesity, moon facies, striae, hyperglycemia, hypertension. 24-h urinary free cortisol, late-night salivary cortisol, low-dose dex suppression test for screening.",
        organSystem: "endocrine",
        tags: ["endocrine", "adrenal"],
      },
      {
        name: "Pheochromocytoma",
        description: "Catecholamine-secreting tumor of adrenal medulla / paraganglioma.",
        keyFact: "Classic triad: episodic headache, sweating, palpitations + hypertension. Plasma free metanephrines best screening test. Alpha-blockade (phenoxybenzamine) before beta-blockade pre-operatively.",
        organSystem: "endocrine",
        tags: ["endocrine", "adrenal"],
      },
      {
        name: "Pituitary disorders",
        description: "Acromegaly, prolactinoma, hypopituitarism, diabetes insipidus.",
        keyFact: "Prolactinoma: dopamine agonists (cabergoline, bromocriptine) first-line. Acromegaly: transsphenoidal resection, somatostatin analogs, pegvisomant. Central DI: desmopressin.",
        organSystem: "endocrine",
        tags: ["endocrine", "pituitary"],
      },
      {
        name: "Obesity & metabolic syndrome",
        description: "Excess adiposity with downstream metabolic dysregulation.",
        keyFact: "BMI ≥30 = obesity. GLP-1 RAs (semaglutide 2.4 mg weekly, tirzepatide weekly) produce 15–22% weight loss — first effective non-surgical pharmacotherapy. Bariatric surgery remains most durable.",
        tags: ["endocrine", "obesity"],
        status: "landmark",
      },
      {
        name: "Osteoporosis",
        description: "Low bone mass and microarchitectural deterioration → fragility fractures.",
        keyFact: "DXA T-score ≤−2.5. Bisphosphonates first-line. Romosozumab (sclerostin antibody, 2019) — large gains in BMD; denosumab (RANKL antibody) when bisphosphonates contraindicated.",
        organSystem: "musculoskeletal",
        tags: ["endocrine", "bone"],
      },
      {
        name: "Hyperparathyroidism",
        description: "Excess PTH secretion — primary (adenoma), secondary (CKD), tertiary.",
        keyFact: "Primary: hypercalcemia + inappropriately normal/elevated PTH. Symptoms: 'stones, bones, abdominal groans, psychic moans.' Parathyroidectomy curative.",
        organSystem: "endocrine",
        tags: ["endocrine", "parathyroid"],
      },
      {
        name: "Inborn errors of metabolism",
        description: "Inherited enzymatic defects in metabolic pathways.",
        keyFact: "Newborn screening (PKU since 1963 — first; now expanded to >30 conditions including MSUD, galactosemia, MCAD). Early dietary or enzyme replacement therapy prevents irreversible damage.",
        tags: ["endocrine", "metabolic", "genetic"],
        xref: ["chemistry"],
      },
      {
        name: "Dyslipidemia management",
        description: "Lipid-lowering strategies for primary and secondary prevention.",
        keyFact: "Statins reduce ASCVD events ~25% per 1 mmol/L LDL reduction. Ezetimibe, PCSK9 mAbs (evolocumab, alirocumab), inclisiran (siRNA), bempedoic acid for statin-intolerant or insufficient response.",
        tags: ["endocrine", "lipids"],
        xref: ["chemistry"],
      },
    ],
  },
];
