import type { Family } from "./types";

export const FAMILIES_14_19: Family[] = [
  // ── Family 14 ─────────────────────────────────────────────────────────────
  {
    slug: "learning-memory",
    number: 14,
    name: "Learning & Memory Systems",
    blurb: "Memory's dissociable systems — working, episodic, semantic, procedural, emotional.",
    section: "D",
    color: "sky",
    entries: [
      {
        name: "Working memory",
        description: "Short-term holding and manipulation of information.",
        keyFact: "Baddeley & Hitch model: central executive + phonological loop + visuospatial sketchpad + episodic buffer. PFC and parietal cortex sustain delay-period activity.",
        researcher: "Alan Baddeley, Patricia Goldman-Rakic",
        tags: ["working-memory", "PFC", "delay-period"],
        xref: ["psychology"],
      },
      {
        name: "Episodic memory",
        description: "Memory of specific events tied to context.",
        keyFact: "Depends on the hippocampus and surrounding MTL. Patient HM's bilateral medial temporal resection (1953) showed selective episodic loss with preserved skills.",
        researcher: "Endel Tulving; Brenda Milner (HM)",
        tags: ["episodic", "HM", "MTL"],
        xref: ["psychology"],
        status: "landmark",
      },
      {
        name: "Semantic memory",
        description: "General knowledge independent of episode.",
        keyFact: "Largely temporal-lobe based; anterior temporal lobe acts as a semantic hub. Semantic dementia presents with degraded concept knowledge but preserved episodic recall.",
        researcher: "Karalyn Patterson, Tim Rogers",
        tags: ["semantic", "ATL", "semantic-dementia"],
        xref: ["psychology", "medicine"],
      },
      {
        name: "Procedural memory",
        description: "Motor and cognitive skills learned through practice.",
        keyFact: "Striatum and cerebellum dependent; spared in MTL amnesia. HM could learn mirror-tracing skill without remembering doing it.",
        tags: ["procedural", "striatum", "skill"],
        xref: ["psychology"],
      },
      {
        name: "Classical conditioning",
        description: "Pavlovian association between cue and outcome.",
        keyFact: "Amygdala-dependent for fear; cerebellum (interpositus nucleus) for eyeblink. Distinct circuits per association type.",
        researcher: "Ivan Pavlov; Richard Thompson (eyeblink)",
        tags: ["Pavlov", "conditioning", "amygdala"],
        xref: ["psychology"],
      },
      {
        name: "Reward prediction error",
        description: "Dopamine signal of (actual − expected) reward.",
        keyFact: "Schultz showed VTA/SNc dopamine neurons fire to unexpected reward, shift to predictive cue with learning, and dip when expected reward is omitted.",
        researcher: "Wolfram Schultz",
        formula: "\\delta_t = r_t + \\gamma V(s_{t+1}) - V(s_t)",
        tags: ["RPE", "DA", "Schultz"],
        xref: ["psychology", "computer-science"],
        status: "landmark",
      },
      {
        name: "Place cells",
        description: "Hippocampal neurons firing at specific spatial locations.",
        keyFact: "Each cell has a place field — a particular patch of the environment in which it fires. Discovered in freely moving rats (1971).",
        researcher: "John O'Keefe (Nobel 2014)",
        tags: ["place-cell", "O'Keefe", "HC"],
        status: "landmark",
      },
      {
        name: "Grid cells",
        description: "Medial entorhinal neurons with hexagonal firing fields.",
        keyFact: "Each grid cell fires at vertices of a triangular lattice over space. Discovered 2005; supports an allocentric metric for navigation.",
        researcher: "May-Britt & Edvard Moser (Nobel 2014)",
        tags: ["grid-cell", "MEC", "Moser"],
        status: "landmark",
      },
      {
        name: "Cognitive map",
        description: "Internal representation of space and structure.",
        keyFact: "Tolman (1948) inferred map-like learning in rats. Hippocampal-entorhinal cells provide the neural substrate, generalizing to non-spatial relational structure.",
        researcher: "Edward Tolman; O'Keefe & Nadel",
        tags: ["cognitive-map", "Tolman"],
        xref: ["psychology"],
      },
      {
        name: "Memory consolidation",
        description: "Time-dependent stabilization of new memories.",
        keyFact: "Standard model: hippocampus initially required, gradually replaced by neocortex. Multiple-trace theory and SoCM theory contest the time-limited role for episodic detail.",
        researcher: "Larry Squire; Lynn Nadel, Morris Moscovitch",
        tags: ["consolidation", "Squire", "SoCM"],
        xref: ["psychology"],
        status: "contested",
      },
      {
        name: "Sleep and memory",
        description: "Sleep stages contribute differently to memory.",
        keyFact: "Slow-wave sleep supports declarative consolidation (sharp-wave ripples); REM sleep supports procedural and emotional memory consolidation.",
        researcher: "Jan Born, Robert Stickgold",
        tags: ["sleep", "SWS", "REM"],
        xref: ["psychology"],
      },
      {
        name: "Forgetting curve",
        description: "Memory decay over time.",
        keyFact: "Ebbinghaus (1885) showed retention falls as a roughly exponential function. Spacing effect: distributed practice trumps massed practice for retention.",
        researcher: "Hermann Ebbinghaus",
        formula: "R(t) \\approx e^{-t/\\tau}",
        tags: ["Ebbinghaus", "spacing"],
        xref: ["psychology"],
        status: "landmark",
      },
      {
        name: "False memories",
        description: "Confidently recalled events that did not occur.",
        keyFact: "Loftus's misinformation paradigm and DRM lists routinely induce false memories. Eyewitness testimony confidence does not track accuracy well.",
        researcher: "Elizabeth Loftus",
        tags: ["false-memory", "Loftus", "DRM"],
        xref: ["psychology"],
      },
      {
        name: "Korsakoff syndrome",
        description: "Amnesia from thiamine-deficient diencephalic damage.",
        keyFact: "Mammillary-body and anterior-thalamus damage cause severe anterograde and retrograde amnesia with confabulation. Classic in chronic alcoholism.",
        researcher: "Sergei Korsakoff (1887)",
        tags: ["Korsakoff", "thiamine", "diencephalon"],
        xref: ["medicine"],
      },
    ],
  },

  // ── Family 15 ─────────────────────────────────────────────────────────────
  {
    slug: "higher-cognition-consciousness",
    number: 15,
    name: "Higher Cognition & Consciousness",
    blurb: "Attention, language, decision, theory of mind, and the hard problem.",
    section: "D",
    color: "teal",
    entries: [
      {
        name: "Selective attention",
        description: "Prioritizing relevant inputs at the expense of others.",
        keyFact: "Top-down (frontoparietal control) and bottom-up (sensory salience) systems. Posner's spatial-cueing paradigm dissects orienting components.",
        researcher: "Michael Posner",
        tags: ["attention", "Posner"],
        xref: ["psychology"],
      },
      {
        name: "Cocktail party effect",
        description: "Selective auditory attention in crowded scenes.",
        keyFact: "Cherry (1953) showed listeners can follow one speaker while filtering others — but unattended salient information (your name) breaks through.",
        researcher: "Colin Cherry",
        tags: ["cocktail-party", "Cherry"],
        xref: ["psychology"],
      },
      {
        name: "Executive function",
        description: "Top-down goal-directed cognitive control.",
        keyFact: "Updating (working memory), shifting (set-switching), and inhibition. Heavily reliant on dlPFC, ACC, and basal-ganglia loops. Wisconsin Card Sort is a classic probe.",
        researcher: "Akira Miyake (unity/diversity)",
        tags: ["executive", "WCS", "Miyake"],
        xref: ["psychology"],
      },
      {
        name: "Decision-making",
        description: "Choice among alternative actions.",
        keyFact: "Drift-diffusion and race models accurately fit RT and accuracy in two-choice tasks. LIP and FEF accumulate evidence; basal ganglia gate the decision.",
        researcher: "Roger Ratcliff; Michael Shadlen",
        formula: "dx = A\\,dt + \\sigma\\,dW",
        tags: ["DDM", "LIP", "evidence"],
        xref: ["psychology", "mathematics"],
      },
      {
        name: "Theory of mind",
        description: "Attribution of mental states to others.",
        keyFact: "False-belief tasks (Sally-Anne) emerge around age 4. Right temporoparietal junction (rTPJ) and medial PFC implicated in adult mentalizing.",
        researcher: "Heinz Wimmer, Josef Perner; Rebecca Saxe (rTPJ)",
        tags: ["ToM", "false-belief", "rTPJ"],
        xref: ["psychology"],
      },
      {
        name: "Language network",
        description: "Left perisylvian circuits for language.",
        keyFact: "Broca's area, Wernicke's area, arcuate fasciculus, anterior temporal lobe, and angular gyrus form a left-lateralized network in ~95% of right-handers.",
        researcher: "Norman Geschwind; Evelina Fedorenko",
        tags: ["language", "Broca", "Wernicke"],
        xref: ["psychology", "linguistics"],
      },
      {
        name: "Bereitschaftspotential",
        description: "Slow scalp potential before voluntary action.",
        keyFact: "Begins ~1 s before voluntary movement. Libet's experiments suggested it precedes conscious awareness of intention — debated philosophically.",
        researcher: "Kornhuber & Deecke; Benjamin Libet",
        tags: ["readiness-potential", "Libet", "free-will"],
        xref: ["psychology", "philosophy"],
        status: "contested",
      },
      {
        name: "Neural correlates of consciousness",
        description: "Minimal brain activity sufficient for a percept.",
        keyFact: "Binocular rivalry and masking studies isolate activity tracking perception independent of stimulus. Posterior \"hot zone\" candidates: parietal–occipital.",
        researcher: "Francis Crick, Christof Koch",
        tags: ["NCC", "Crick-Koch", "binocular-rivalry"],
        xref: ["philosophy", "psychology"],
        status: "open",
      },
      {
        name: "Global workspace theory",
        description: "Consciousness as broadcast across cortical workspace.",
        keyFact: "Baars proposed a fronto-parietal global workspace; Dehaene's neuronal global workspace model identifies a P3-like ignition wave at ~300 ms as conscious access.",
        researcher: "Bernard Baars; Stanislas Dehaene",
        tags: ["GWT", "Dehaene", "ignition"],
        xref: ["philosophy", "psychology"],
        status: "contested",
      },
      {
        name: "Integrated information theory",
        description: "Consciousness = $\\Phi$, the integrated information.",
        keyFact: "Tononi's IIT proposes consciousness is identical to a system's capacity to integrate information ($\\Phi$). Empirical predictions and ontology hotly contested.",
        researcher: "Giulio Tononi",
        formula: "\\Phi = \\min_{\\text{partition}} D_{KL}(p(X) \\,\\|\\, \\prod_i p(X_i))",
        tags: ["IIT", "phi", "Tononi"],
        xref: ["philosophy", "mathematics"],
        status: "contested",
      },
      {
        name: "Higher-order theories",
        description: "Consciousness requires a representation of representations.",
        keyFact: "Rosenthal's HOT and Lau's HOROR claim that a state is conscious only when there is a higher-order representation about it. PFC implicated; experimentally tested via metacognition.",
        researcher: "David Rosenthal; Hakwan Lau",
        tags: ["HOT", "metacognition", "Lau"],
        xref: ["philosophy"],
        status: "contested",
      },
      {
        name: "Predictive coding",
        description: "Cortex as hierarchical prediction machine.",
        keyFact: "Higher levels send predictions downward; lower levels send prediction errors upward. Friston extends this to free-energy minimization as a general brain principle.",
        researcher: "Rajesh Rao, Dana Ballard; Karl Friston",
        tags: ["predictive-coding", "free-energy", "Friston"],
        xref: ["computer-science"],
      },
      {
        name: "Split-brain syndrome",
        description: "Corpus-callosum section reveals hemispheric specialization.",
        keyFact: "After commissurotomy, left hemisphere can name objects in the right visual field but not the left; right hemisphere can still draw or point.",
        researcher: "Roger Sperry (Nobel 1981), Michael Gazzaniga",
        tags: ["split-brain", "Sperry", "Gazzaniga"],
        xref: ["psychology"],
        status: "landmark",
      },
      {
        name: "Hard problem of consciousness",
        description: "Why is there \"something it is like\" to be a brain?",
        keyFact: "Chalmers (1995) distinguished the easy problems (functions) from the hard problem (subjective experience). Remains the central open question in philosophy of mind.",
        researcher: "David Chalmers",
        tags: ["hard-problem", "qualia", "Chalmers"],
        xref: ["philosophy"],
        status: "open",
      },
    ],
  },

  // ── Family 16 ─────────────────────────────────────────────────────────────
  {
    slug: "neurological-disorders",
    number: 16,
    name: "Neurological Disorders",
    blurb: "Brain diseases with identifiable structural or cellular substrates.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Alzheimer's disease",
        description: "Progressive dementia with amyloid plaques and tau tangles.",
        keyFact: "Pathology: extracellular A$\\beta$42 plaques and intracellular tau tangles. ~6.7M Americans (2023). Lecanemab (2023) and donanemab (2024) are first DMTs approved.",
        researcher: "Alois Alzheimer (1906)",
        tags: ["Alzheimer", "amyloid", "tau", "lecanemab"],
        xref: ["medicine", "biology"],
      },
      {
        name: "Parkinson's disease",
        description: "Movement disorder from SNc dopamine neuron loss.",
        keyFact: "Bradykinesia, rigidity, resting tremor, postural instability. $\\alpha$-synuclein Lewy-body pathology. Levodopa restores DA but does not slow progression.",
        researcher: "James Parkinson (1817)",
        tags: ["Parkinson", "DA", "synuclein"],
        xref: ["medicine"],
      },
      {
        name: "Huntington's disease",
        description: "Autosomal-dominant CAG repeat expansion in HTT.",
        keyFact: ">36 CAG repeats in huntingtin causes striatal medium-spiny neuron loss, chorea, dementia, psychiatric symptoms. Onset age inversely correlates with repeat length.",
        researcher: "Nancy Wexler (gene mapping)",
        tags: ["Huntington", "CAG", "MSN-loss"],
        xref: ["medicine", "biology"],
      },
      {
        name: "Amyotrophic lateral sclerosis",
        description: "Motor neuron disease.",
        keyFact: "Upper and lower motor neuron degeneration. ~10% familial (SOD1, C9orf72, TDP-43). Riluzole and edaravone offer modest slowing. Stephen Hawking the iconic patient.",
        researcher: "Jean-Martin Charcot (1869)",
        tags: ["ALS", "SOD1", "C9orf72"],
        xref: ["medicine"],
      },
      {
        name: "Multiple sclerosis",
        description: "Autoimmune CNS demyelination.",
        keyFact: "T-cell attack on oligodendrocyte myelin produces white-matter lesions. Relapsing-remitting and progressive forms. >20 disease-modifying therapies now exist.",
        tags: ["MS", "demyelination", "DMT"],
        xref: ["medicine"],
      },
      {
        name: "Epilepsy",
        description: "Recurrent seizures from abnormal synchronous firing.",
        keyFact: "Focal vs generalized; ~50M affected globally. ~30% drug-resistant. Surgical resection of mesial temporal lobe is curative in temporal-lobe epilepsy.",
        tags: ["epilepsy", "seizure"],
        xref: ["medicine"],
      },
      {
        name: "Stroke",
        description: "Sudden focal CNS injury from vascular event.",
        keyFact: "Ischemic (~80%) or hemorrhagic. Time is brain: tPA within ~4.5h; mechanical thrombectomy within ~24h for large-vessel occlusion. Penumbra is salvageable.",
        tags: ["stroke", "tPA", "thrombectomy"],
        xref: ["medicine"],
      },
      {
        name: "Traumatic brain injury",
        description: "Mechanical insult to the brain.",
        keyFact: "Diffuse axonal injury produces white-matter shearing; concussion involves transient cortical depolarization. Repeated TBI linked to CTE.",
        tags: ["TBI", "concussion", "CTE"],
        xref: ["medicine"],
      },
      {
        name: "Migraine",
        description: "Recurrent throbbing headache with sensory phenomena.",
        keyFact: "Cortical spreading depression underlies aura. CGRP signaling drives the headache phase; anti-CGRP antibodies (erenumab) are effective preventives.",
        researcher: "Aristides Leão (CSD)",
        tags: ["migraine", "CSD", "CGRP"],
        xref: ["medicine"],
      },
      {
        name: "Frontotemporal dementia",
        description: "Behavioral or language dementia from frontal/anterior temporal degeneration.",
        keyFact: "Pick's bodies; tau or TDP-43 inclusions. Onset often in 50s–60s. Behavioral variant (disinhibition, apathy) commonly misdiagnosed as psychiatric.",
        researcher: "Arnold Pick",
        tags: ["FTD", "Pick", "TDP-43"],
        xref: ["medicine"],
      },
      {
        name: "Prion disease",
        description: "Transmissible misfolded-protein neurodegeneration.",
        keyFact: "PrP^Sc converts normal PrP into misfolded form. CJD, kuru, fatal familial insomnia, BSE. Proved the protein-only hypothesis of infection.",
        researcher: "Stanley Prusiner (Nobel 1997)",
        tags: ["prion", "Prusiner", "CJD"],
        xref: ["medicine", "biology"],
        status: "landmark",
      },
      {
        name: "Narcolepsy",
        description: "Excessive daytime sleepiness with REM intrusions.",
        keyFact: "Type 1 narcolepsy involves loss of hypothalamic orexin neurons, likely autoimmune. Cataplexy — sudden muscle atonia triggered by emotion — is the pathognomonic sign.",
        researcher: "Emmanuel Mignot",
        tags: ["narcolepsy", "orexin", "cataplexy"],
        xref: ["medicine"],
      },
      {
        name: "Tourette syndrome",
        description: "Motor and vocal tic disorder of childhood onset.",
        keyFact: "Striatal hyperactivity in cortico-striato-thalamo-cortical loops. ~50% remit by adulthood. Comorbid with OCD and ADHD. Coprolalia is rare.",
        researcher: "Gilles de la Tourette",
        tags: ["Tourette", "tics", "CSTC"],
        xref: ["medicine"],
      },
      {
        name: "Wernicke encephalopathy",
        description: "Acute thiamine deficiency syndrome.",
        keyFact: "Triad of ophthalmoplegia, ataxia, and confusion. Periaqueductal and mammillary lesions. Treated emergently with IV thiamine — can prevent Korsakoff syndrome.",
        researcher: "Carl Wernicke",
        tags: ["Wernicke", "thiamine"],
        xref: ["medicine"],
      },
      {
        name: "Spinal cord injury",
        description: "Trauma to descending/ascending spinal tracts.",
        keyFact: "Level determines deficit: C5 lesion → quadriplegia; T6 → paraplegia. Glial scar and lack of CNS regeneration block recovery. Epidural stimulation restores stepping in some.",
        researcher: "Reggie Edgerton, Grégoire Courtine",
        tags: ["SCI", "glial-scar", "stimulation"],
        xref: ["medicine"],
      },
      {
        name: "Glioblastoma",
        description: "Most aggressive primary brain tumor.",
        keyFact: "Median survival ~15 months with surgery + radiation + temozolomide. Infiltrative growth makes complete resection impossible. Site of many failed targeted therapies.",
        tags: ["GBM", "glioma", "temozolomide"],
        xref: ["medicine"],
      },
    ],
  },

  // ── Family 17 ─────────────────────────────────────────────────────────────
  {
    slug: "psychiatric-disorders",
    number: 17,
    name: "Psychiatric Disorders & Neural Correlates",
    blurb: "Mental disorders and their candidate brain substrates.",
    section: "E",
    color: "amber",
    entries: [
      {
        name: "Schizophrenia",
        description: "Psychotic disorder with positive and negative symptoms.",
        keyFact: "Dopamine hypothesis: hyperactive mesolimbic DA → positive symptoms; hypoactive mesocortical DA → negative symptoms. Glutamate/NMDA hypofunction also implicated.",
        researcher: "Emil Kraepelin; Arvid Carlsson",
        tags: ["schizophrenia", "DA", "NMDA"],
        xref: ["medicine", "psychology"],
      },
      {
        name: "Major depressive disorder",
        description: "Persistent low mood with anhedonia.",
        keyFact: "Monoamine hypothesis (5-HT/NE/DA deficiency) is partial at best. Newer focus: prefrontal–limbic dysconnectivity, neuroinflammation, BDNF, and rapid-acting glutamatergic drugs (ketamine).",
        tags: ["MDD", "5-HT", "ketamine"],
        xref: ["medicine", "psychology"],
        status: "contested",
      },
      {
        name: "Bipolar disorder",
        description: "Cycles of mania and depression.",
        keyFact: "Highly heritable (~70%). Lithium remains the gold-standard mood stabilizer despite unclear mechanism (GSK-3$\\beta$, inositol depletion).",
        tags: ["bipolar", "lithium"],
        xref: ["medicine"],
      },
      {
        name: "Anxiety disorders",
        description: "Excessive fear and threat anticipation.",
        keyFact: "Hyperactive amygdala and hypoactive vmPFC regulation. SSRIs and CBT are first-line. Generalized, panic, social, and specific phobia share circuitry but differ in triggers.",
        tags: ["anxiety", "amygdala", "CBT"],
        xref: ["medicine", "psychology"],
      },
      {
        name: "Post-traumatic stress disorder",
        description: "Intrusive re-experiencing after trauma.",
        keyFact: "Smaller hippocampal volume (cause or effect debated); amygdala hyperreactivity; failed extinction learning. Prolonged exposure and EMDR have evidence-based efficacy.",
        researcher: "Edna Foa (PE therapy)",
        tags: ["PTSD", "extinction", "EMDR"],
        xref: ["medicine", "psychology"],
      },
      {
        name: "Obsessive-compulsive disorder",
        description: "Intrusive thoughts and compulsive rituals.",
        keyFact: "Cortico-striato-thalamo-cortical loop hyperactivity. SSRIs and ERP therapy effective. DBS of nucleus accumbens / anterior limb of internal capsule for refractory cases.",
        researcher: "Lewis Baxter (PET imaging)",
        tags: ["OCD", "CSTC", "DBS"],
        xref: ["medicine", "psychology"],
      },
      {
        name: "Attention-deficit / hyperactivity disorder",
        description: "Inattention, hyperactivity, impulsivity.",
        keyFact: "Frontostriatal dopaminergic dysfunction. Stimulants (methylphenidate, amphetamine) and atomoxetine are effective. Heritability ~75%; environmental factors poorly characterized.",
        tags: ["ADHD", "dopamine", "stimulant"],
        xref: ["medicine", "psychology"],
      },
      {
        name: "Autism spectrum disorder",
        description: "Neurodevelopmental social-communication condition.",
        keyFact: "Highly heritable. Excitation/inhibition imbalance, altered synaptic proteins (neurexins, neuroligins, SHANK3). No FDA-approved medication for core features as of 2026.",
        tags: ["autism", "ASD", "E/I-balance"],
        xref: ["medicine", "psychology"],
      },
      {
        name: "Addiction",
        description: "Compulsive use despite adverse consequences.",
        keyFact: "Drugs of abuse hijack the mesolimbic DA system. Transition from goal-directed to habitual control via shift from ventral to dorsal striatum.",
        researcher: "Eric Nestler, Nora Volkow",
        tags: ["addiction", "mesolimbic", "habit"],
        xref: ["medicine"],
      },
      {
        name: "Eating disorders",
        description: "Anorexia, bulimia, binge eating.",
        keyFact: "Insula and reward-circuit alterations. Anorexia has the highest mortality of any psychiatric illness (~5%). Family-based treatment (Maudsley) is evidence-based for adolescents.",
        tags: ["anorexia", "bulimia", "FBT"],
        xref: ["medicine", "psychology"],
      },
      {
        name: "Personality disorders",
        description: "Enduring maladaptive patterns of cognition and behavior.",
        keyFact: "DSM-5 lists 10 across 3 clusters. Borderline PD shows fronto-amygdala dysregulation; dialectical behavior therapy is effective.",
        researcher: "Marsha Linehan (DBT)",
        tags: ["BPD", "DBT"],
        xref: ["medicine", "psychology"],
      },
      {
        name: "Catatonia",
        description: "Motor and behavioral immobility syndrome.",
        keyFact: "Rigidity, mutism, posturing, waxy flexibility. Once linked to schizophrenia; now recognized across disorders. Benzodiazepines and ECT are highly effective.",
        researcher: "Karl Kahlbaum (1874)",
        tags: ["catatonia", "ECT"],
        xref: ["medicine"],
      },
      {
        name: "Suicide neurobiology",
        description: "Distinct biological correlates of suicidal behavior.",
        keyFact: "Reduced serotonergic activity (low CSF 5-HIAA), altered HPA reactivity, vmPFC hypofunction. Ketamine reduces acute suicidal ideation hours after dosing.",
        researcher: "John Mann",
        tags: ["suicide", "5-HIAA", "ketamine"],
        xref: ["medicine"],
      },
      {
        name: "Replication and the RDoC reframe",
        description: "DSM categories may not map cleanly to neural substrates.",
        keyFact: "NIMH's Research Domain Criteria (2010) proposed organizing psychiatry around transdiagnostic dimensions (e.g. arousal, cognitive control) tied to specific circuits.",
        researcher: "Thomas Insel",
        tags: ["RDoC", "dimensional", "Insel"],
        xref: ["medicine", "psychology"],
        status: "contested",
      },
    ],
  },

  // ── Family 18 ─────────────────────────────────────────────────────────────
  {
    slug: "methods-computational",
    number: 18,
    name: "Neuroimaging, Methods & Computational Neuroscience",
    blurb: "Tools and theories — from MRI to optogenetics to spiking-network models.",
    section: "E",
    color: "indigo",
    entries: [
      {
        name: "EEG",
        description: "Scalp-recorded summed cortical potentials.",
        keyFact: "ms-resolution but cm-scale spatial uncertainty. Reflects postsynaptic potentials of pyramidal cells aligned perpendicular to scalp. Invented by Hans Berger (1929).",
        researcher: "Hans Berger",
        tags: ["EEG", "Berger", "ms-resolution"],
      },
      {
        name: "MEG",
        description: "Magnetoencephalography — magnetic field of cortical currents.",
        keyFact: "ms resolution + better source localization than EEG due to transparency of skull to magnetic fields. Requires SQUID sensors (or new OPM helmets).",
        tags: ["MEG", "SQUID", "OPM"],
      },
      {
        name: "fMRI",
        description: "Blood-oxygen-level dependent (BOLD) imaging.",
        keyFact: "Indirect: deoxyhemoglobin is paramagnetic, so neural activity → vasodilation → lower [dHb] → higher T2* signal. ~mm spatial, ~seconds temporal resolution.",
        researcher: "Seiji Ogawa (BOLD effect, 1990)",
        tags: ["fMRI", "BOLD", "Ogawa"],
        status: "landmark",
      },
      {
        name: "PET",
        description: "Positron emission tomography for molecular imaging.",
        keyFact: "Radiotracers measure metabolism (FDG), receptor occupancy (raclopride for D2), and pathology (amyloid PET, tau PET). Lower spatial resolution than MRI.",
        tags: ["PET", "FDG", "amyloid-PET"],
        xref: ["medicine"],
      },
      {
        name: "Diffusion MRI",
        description: "Probes water diffusion to map white-matter tracts.",
        keyFact: "Tractography reconstructs major fiber bundles (arcuate, corticospinal, cingulum). Anisotropy quantifies microstructure; sensitive to demyelination.",
        researcher: "Denis Le Bihan",
        tags: ["dMRI", "DTI", "tractography"],
      },
      {
        name: "Calcium imaging",
        description: "Optical recording from many neurons via Ca2+ indicators.",
        keyFact: "GCaMP family of genetically encoded indicators allows recording from thousands of neurons simultaneously in vivo. Two-photon microscopy gives single-cell resolution.",
        researcher: "Roger Tsien, Junichi Nakai, Karel Svoboda",
        tags: ["GCaMP", "two-photon", "calcium"],
        xref: ["biology", "chemistry"],
      },
      {
        name: "Optogenetics",
        description: "Light-gated channels enable causal circuit manipulation.",
        keyFact: "Channelrhodopsin-2 (excitation) and halorhodopsin (inhibition) expressed in defined neuron populations and activated by light. Karl Deisseroth & Ed Boyden 2005.",
        researcher: "Karl Deisseroth, Ed Boyden",
        tags: ["optogenetics", "ChR2", "Deisseroth"],
        xref: ["biology"],
        status: "landmark",
      },
      {
        name: "Chemogenetics (DREADDs)",
        description: "Engineered receptors activated only by designer ligands.",
        keyFact: "DREADDs (hM3Dq, hM4Di) activated by CNO/clozapine give hours-long control of defined cell populations. Slower than optogenetics, no fiber implant required.",
        researcher: "Bryan Roth",
        tags: ["DREADD", "chemogenetics", "Roth"],
      },
      {
        name: "Electron microscopy connectomics",
        description: "Reconstructs neural wiring at synaptic resolution.",
        keyFact: "Serial-section EM with ML segmentation has produced cubic-mm cortex datasets (MICrONS, 2024) and the adult Drosophila brain (FlyWire, 2024).",
        researcher: "Sebastian Seung, FlyWire/Janelia",
        tags: ["EM", "connectomics", "FlyWire"],
      },
      {
        name: "Brainbow",
        description: "Stochastic multicolor labeling of individual neurons.",
        keyFact: "Cre-lox combinatorial expression of XFPs produces ~100 distinguishable colors, allowing dense circuit reconstruction.",
        researcher: "Jeff Lichtman, Joshua Sanes",
        tags: ["Brainbow", "Lichtman"],
      },
      {
        name: "Neuralink and high-density recording",
        description: "Thousand-channel intracortical arrays.",
        keyFact: "Neuropixels probes (2017) record from ~1000 sites simultaneously. Neuralink's threads target similar density in humans for BCI applications; first human implant 2024.",
        researcher: "Janelia/IMEC (Neuropixels)",
        tags: ["Neuropixels", "BCI", "Neuralink"],
        xref: ["medicine", "engineering"],
      },
      {
        name: "Single-cell transcriptomics",
        description: "RNA-seq of individual neurons.",
        keyFact: "Allen Brain Atlas single-cell catalogs identify hundreds of transcriptomic neuron types. Many do not align with morphological/electrophysiological classifications.",
        researcher: "Allen Institute, Hongkui Zeng",
        tags: ["scRNA-seq", "Allen", "cell-types"],
        xref: ["biology"],
      },
      {
        name: "Spiking neural network model",
        description: "Computational neuron model with discrete spikes.",
        keyFact: "Integrate-and-fire and Hodgkin–Huxley networks simulate spike timing and balance. SpiNNaker, Loihi, and Akida hardware accelerate ~million-neuron simulations.",
        researcher: "Eugene Izhikevich; Manchester SpiNNaker",
        tags: ["SNN", "neuromorphic", "Loihi"],
        xref: ["computer-science"],
      },
      {
        name: "Reinforcement learning & brain",
        description: "Bridge from RL theory to dopamine signaling.",
        keyFact: "Temporal-difference learning predicts dopamine RPE; actor-critic architectures map to ventral striatum (critic) and dorsal striatum (actor). Distributional RL extends to DA diversity.",
        researcher: "Richard Sutton, Wolfram Schultz, Naoshige Uchida",
        tags: ["RL", "TD", "distributional-RL"],
        xref: ["computer-science", "psychology"],
      },
      {
        name: "Deep learning and visual cortex",
        description: "CNN representations predict IT cell responses.",
        keyFact: "Yamins & DiCarlo (2014): CNNs trained on ImageNet match macaque IT firing patterns better than any prior model. Drives the controversial \"brains as approximate deep nets\" view.",
        researcher: "Dan Yamins, Jim DiCarlo",
        tags: ["CNN", "IT", "deep-learning"],
        xref: ["computer-science"],
        status: "contested",
      },
      {
        name: "Free energy principle",
        description: "Single normative theory of brain function.",
        keyFact: "Friston: organisms minimize variational free energy = surprise about sensory inputs. Encompasses perception (predictive coding) and action (active inference). Empirical content debated.",
        researcher: "Karl Friston",
        formula: "F = \\mathbb{E}_q[\\log q(z) - \\log p(o, z)]",
        tags: ["FEP", "active-inference", "Friston"],
        xref: ["computer-science", "philosophy", "mathematics"],
        status: "contested",
      },
    ],
  },

  // ── Family 19 ─────────────────────────────────────────────────────────────
  {
    slug: "frontiers-open",
    number: 19,
    name: "Frontiers & Open Problems",
    blurb: "Genuinely open questions and the controversies driving the next decade of neuroscience.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Hard problem of consciousness",
        description: "Why is anything experienced from the inside?",
        keyFact: "No empirical result yet bridges objective neural activity to subjective experience. Theories (IIT, GWT, HOT) make conflicting predictions; ongoing adversarial collaborations test them.",
        researcher: "Chalmers; COGITATE adversarial collaboration (2023)",
        tags: ["hard-problem", "consciousness"],
        xref: ["philosophy"],
        status: "open",
      },
      {
        name: "Free will and the brain",
        description: "Does conscious will cause action?",
        keyFact: "Libet (1983), Soon et al. (2008): unconscious brain signals predict decisions seconds before awareness. Compatibilist and libertarian frameworks remain in tension.",
        researcher: "Benjamin Libet, John-Dylan Haynes",
        tags: ["free-will", "Libet"],
        xref: ["philosophy", "psychology"],
        status: "open",
      },
      {
        name: "Adult human hippocampal neurogenesis",
        description: "Are new neurons born in the adult human dentate gyrus?",
        keyFact: "Sorrells (2018) reported it ceases by adolescence; Boldrini (2018) reported it persists across the lifespan. Methodological disagreements unresolved.",
        researcher: "Sorrells, Boldrini, Llorens-Martín",
        tags: ["neurogenesis", "DG"],
        xref: ["medicine"],
        status: "open",
      },
      {
        name: "Animal consciousness",
        description: "Which species are sentient, and to what degree?",
        keyFact: "Cambridge Declaration (2012) and New York Declaration (2024) extend likely sentience to fish, cephalopods, decapod crustaceans, and insects. Operationalization is contested.",
        researcher: "Jonathan Birch, Jaak Panksepp",
        tags: ["animal-consciousness", "Cambridge", "sentience"],
        xref: ["philosophy", "biology"],
        status: "open",
      },
      {
        name: "Theory of cortical computation",
        description: "Is there a canonical microcircuit?",
        keyFact: "All cortical areas share a six-layered design, but whether a single computation (e.g. predictive coding, hierarchical Bayesian inference) is implemented everywhere remains contested.",
        researcher: "Rodney Douglas, Kevan Martin",
        tags: ["canonical-microcircuit", "cortex"],
        status: "open",
      },
      {
        name: "Whole-brain emulation",
        description: "Could a digitized brain run conscious software?",
        keyFact: "C. elegans simulations work; OpenWorm and the Blue Brain Project simulate cortical microcircuits. Scaling to human brain raises both technical and philosophical (substrate-independence) questions.",
        researcher: "Blue Brain (Henry Markram), OpenWorm",
        tags: ["WBE", "Blue-Brain"],
        xref: ["philosophy", "computer-science"],
        status: "open",
      },
      {
        name: "Brain–computer interfaces",
        description: "How far can implanted neural decoding go?",
        keyFact: "Speech BCI restored 60+ wpm communication in ALS (Stanford 2023). Visual BCIs are restoring rudimentary phosphenes. Bandwidth, longevity, and ethics remain open.",
        researcher: "Eddie Chang, Krishna Shenoy, Neuralink",
        tags: ["BCI", "speech-BCI"],
        xref: ["medicine", "engineering"],
        status: "open",
      },
      {
        name: "Psychedelics and plasticity",
        description: "Do classic psychedelics rapidly remodel cortical circuits?",
        keyFact: "Psilocybin, LSD, DMT induce structural spine remodeling in mouse PFC (Olson 2021). Phase-3 psilocybin trials for depression report large effect sizes; replication ongoing.",
        researcher: "David Olson, Robin Carhart-Harris",
        tags: ["psychedelic", "plasticity", "psilocybin"],
        xref: ["medicine", "psychology"],
        status: "open",
      },
      {
        name: "Glymphatic system",
        description: "CSF-driven waste clearance during sleep.",
        keyFact: "Nedergaard (2012): astrocyte aquaporin-4 channels enable bulk CSF flow that clears amyloid-$\\beta$ — and is more efficient during sleep. Human glymphatic existence debated.",
        researcher: "Maiken Nedergaard",
        tags: ["glymphatic", "sleep", "AQP4"],
        xref: ["medicine"],
        status: "contested",
      },
      {
        name: "Microbiome–gut–brain axis",
        description: "Gut bacteria influence brain function.",
        keyFact: "Germ-free mice show altered anxiety, social behavior, and stress reactivity. Vagal, immune, and metabolite (SCFA, tryptophan) pathways implicated. Human causality much weaker than mouse.",
        researcher: "John Cryan, Ted Dinan",
        tags: ["gut-brain", "microbiome", "vagus"],
        xref: ["medicine", "biology"],
        status: "contested",
      },
      {
        name: "Neural code",
        description: "Is information carried by rate, timing, or population dynamics?",
        keyFact: "Rate coding dominates classical work; spike timing matters in audition and STDP; population trajectories on low-dimensional manifolds increasingly favored. No unified answer.",
        researcher: "Krishna Shenoy, Mark Churchland",
        tags: ["neural-code", "rate", "timing", "manifold"],
        status: "open",
      },
      {
        name: "Mind-uploading and personal identity",
        description: "Is a simulation of you, you?",
        keyFact: "Even granting computational substrate independence, continuity-of-identity questions (teletransporter problem, branch-line) remain unresolved philosophically.",
        researcher: "Derek Parfit (framework)",
        tags: ["uploading", "identity", "Parfit"],
        xref: ["philosophy"],
        status: "open",
      },
    ],
  },
];
