import type { Family } from "./types";

export const FAMILIES_8_13: Family[] = [
  // ── Family 8 ──────────────────────────────────────────────────────────────
  {
    slug: "vision",
    number: 8,
    name: "Vision",
    blurb: "Retina, geniculate, cortical visual areas, and the perceptual phenomena they create.",
    section: "C",
    color: "green",
    entries: [
      {
        name: "Photoreceptor",
        description: "Rods and cones — the eye's light sensors.",
        keyFact: "Rods (~120M) for scotopic vision; cones (~6M, in three classes S/M/L) for photopic vision and color. Signal via phototransduction cascade.",
        tags: ["photoreceptor", "rod", "cone"],
        xref: ["biology"],
      },
      {
        name: "Phototransduction",
        description: "Light → electrical signal in photoreceptors.",
        keyFact: "Photon isomerizes 11-cis-retinal in opsin → transducin → PDE → cGMP drop → CNG channels close → hyperpolarization. Photoreceptors are unusual in hyperpolarizing to light.",
        researcher: "George Wald (Nobel 1967)",
        tags: ["phototransduction", "rhodopsin", "cGMP"],
        xref: ["chemistry", "biology"],
      },
      {
        name: "Retinal ganglion cells",
        description: "Output neurons of the retina.",
        keyFact: "~1M per eye. Midget (P) cells signal color/form, parasol (M) cells signal motion, melanopsin (ipRGC) cells set circadian rhythm regardless of rods/cones.",
        researcher: "Stephen Kuffler (center-surround)",
        tags: ["RGC", "midget", "parasol", "ipRGC"],
      },
      {
        name: "Center-surround receptive field",
        description: "Antagonistic concentric organization of RGC responses.",
        keyFact: "ON-center cells fire to a bright spot in center, dark surround, and vice versa. Implements local contrast (a discrete Laplacian).",
        researcher: "Kuffler (1953)",
        tags: ["center-surround", "Kuffler", "contrast"],
        status: "landmark",
      },
      {
        name: "Trichromacy",
        description: "Three-cone basis of human color vision.",
        keyFact: "S, M, L cones peak at ~420, 530, 560 nm. Any color matched as a weighted sum of three primaries. Color blindness from missing/anomalous cone pigments.",
        researcher: "Thomas Young, Hermann von Helmholtz",
        tags: ["trichromacy", "color", "Young-Helmholtz"],
        xref: ["physics"],
      },
      {
        name: "Opponent-process color",
        description: "Color encoded in red–green, blue–yellow, light–dark axes.",
        keyFact: "Postreceptoral combinations of cone signals produce opponent channels. Explains afterimages and the impossibility of \"reddish green.\"",
        researcher: "Ewald Hering",
        tags: ["opponent", "Hering"],
      },
      {
        name: "Orientation tuning",
        description: "V1 simple cells respond to bars of a preferred orientation.",
        keyFact: "Hubel & Wiesel showed V1 neurons fire to oriented edges; complex cells generalize across position; hypercomplex cells encode length.",
        researcher: "Hubel & Wiesel (Nobel 1981)",
        tags: ["V1", "orientation", "Hubel-Wiesel"],
        status: "landmark",
      },
      {
        name: "Ocular dominance columns",
        description: "Alternating V1 stripes responsive to one eye.",
        keyFact: "Adjacent ~500 µm columns serve left and right eyes. Critical-period monocular deprivation skews them — basis of amblyopia.",
        researcher: "Hubel & Wiesel",
        tags: ["OD-columns", "critical-period", "amblyopia"],
        xref: ["medicine"],
      },
      {
        name: "Retinotopic map",
        description: "Visual field topographically mapped onto V1.",
        keyFact: "Adjacent retinal points map to adjacent cortical points. Foveal cortex magnification: ~50% of V1 represents the central 10° of visual field.",
        tags: ["retinotopy", "magnification"],
      },
      {
        name: "Motion area MT/V5",
        description: "Specialized motion-processing area.",
        keyFact: "Lesion produces akinetopsia — motion blindness — in which the world appears as a sequence of frozen snapshots. Patient LM (Zihl) is the classic case.",
        researcher: "Semir Zeki",
        tags: ["MT", "V5", "akinetopsia"],
        xref: ["medicine"],
      },
      {
        name: "Color area V4",
        description: "Cortical color-form processing.",
        keyFact: "V4 damage causes cerebral achromatopsia — the world drained of color. Distinct from retinal color blindness.",
        researcher: "Zeki",
        tags: ["V4", "color", "achromatopsia"],
      },
      {
        name: "Inferotemporal cortex",
        description: "Highest stage of the ventral stream.",
        keyFact: "Houses face patches (in macaque) and object-selective cells. Single neurons exhibit translation- and size-invariant object selectivity.",
        researcher: "Charles Gross, Doris Tsao (face patches)",
        tags: ["IT", "objects", "face-patch"],
      },
      {
        name: "Blindsight",
        description: "Residual visual ability after V1 lesion.",
        keyFact: "V1-lesioned patients show above-chance localization and motion detection without conscious awareness, via spared retino-pulvinar-extrastriate pathway.",
        researcher: "Lawrence Weiskrantz",
        tags: ["blindsight", "V1-lesion", "consciousness"],
        xref: ["psychology"],
      },
      {
        name: "Binocular disparity & stereopsis",
        description: "Depth from small inter-eye image differences.",
        keyFact: "Disparity-tuned cells emerge from V1 onward. Random-dot stereograms (Julesz, 1971) showed stereo can work without prior monocular form recognition.",
        researcher: "Bela Julesz",
        tags: ["stereopsis", "disparity", "Julesz"],
      },
      {
        name: "Eye movements & saccades",
        description: "Rapid ballistic gaze shifts.",
        keyFact: "Superior colliculus and frontal eye fields generate saccades up to ~700°/s. Visual perception is suppressed during saccades (saccadic suppression).",
        tags: ["saccade", "SC", "FEF"],
      },
      {
        name: "Vision-for-perception vs vision-for-action",
        description: "Two visual systems hypothesis.",
        keyFact: "Patient DF: ventral-stream damage abolishes shape perception but spares accurate grasping. Dorsal-stream damage (optic ataxia) gives the reverse.",
        researcher: "Mel Goodale & David Milner",
        tags: ["two-streams", "patient-DF", "Goodale-Milner"],
        xref: ["psychology"],
      },
    ],
  },

  // ── Family 9 ──────────────────────────────────────────────────────────────
  {
    slug: "other-senses",
    number: 9,
    name: "Audition, Vestibular & Chemical Senses",
    blurb: "Hearing, balance, smell, and taste — the non-visual senses.",
    section: "C",
    color: "amber",
    entries: [
      {
        name: "Cochlea",
        description: "Coiled fluid-filled hearing organ.",
        keyFact: "~30k inner and outer hair cells along the basilar membrane. High frequencies at base (~20 kHz), low frequencies at apex (~20 Hz). Establishes tonotopy.",
        researcher: "Georg von Békésy (Nobel 1961)",
        tags: ["cochlea", "tonotopy", "hair-cell"],
        xref: ["biology"],
      },
      {
        name: "Mechanotransduction in hair cells",
        description: "Stereocilia deflection opens transduction channels.",
        keyFact: "Tip links between stereocilia pull TMC1/2 channels open in <10 µs — among the fastest known biological transduction. Adaptation via myosin motors.",
        researcher: "James Hudspeth, David Corey",
        tags: ["hair-cell", "tip-link", "TMC1"],
      },
      {
        name: "Cochlear amplifier",
        description: "Outer hair cells boost basilar membrane motion.",
        keyFact: "Prestin-driven somatic electromotility amplifies vibrations ~1000×. Loss yields sensorineural hearing impairment.",
        researcher: "Peter Dallos (prestin)",
        tags: ["OHC", "prestin", "amplifier"],
        xref: ["medicine"],
      },
      {
        name: "Sound localization",
        description: "Two cues solve the location problem.",
        keyFact: "Interaural time differences (ITD, ~600 µs max) computed in medial superior olive via Jeffress delay lines. Interaural level differences (ILD) for high frequencies in lateral superior olive.",
        researcher: "Lloyd Jeffress (delay lines, 1948)",
        tags: ["localization", "ITD", "ILD"],
      },
      {
        name: "Tonotopy",
        description: "Frequency mapped systematically onto auditory areas.",
        keyFact: "Cochlea → cochlear nucleus → MGN → A1 all preserve frequency-place ordering. A1 tonotopic gradient runs from high (posterior) to low (anterior) in humans.",
        tags: ["tonotopy", "A1"],
      },
      {
        name: "Cochlear implant",
        description: "Direct electrical stimulation of the auditory nerve.",
        keyFact: "Bypasses hair cells with a microphone-driven multielectrode array. >1M users worldwide; works best when implanted early in profoundly deaf children.",
        tags: ["cochlear-implant", "auditory-prosthesis"],
        xref: ["medicine"],
      },
      {
        name: "Vestibular system",
        description: "Inner-ear balance and head-motion sensor.",
        keyFact: "Three semicircular canals (angular acceleration) and two otolith organs — utricle (linear), saccule (vertical/gravity). Drives vestibulo-ocular reflex (VOR).",
        tags: ["vestibular", "VOR", "otolith"],
      },
      {
        name: "Vestibulo-ocular reflex",
        description: "Eye movement that stabilizes gaze during head motion.",
        keyFact: "Three-neuron arc (canal → vestibular nucleus → ocular motor nuclei) with ~16 ms latency. Cerebellar flocculus adapts the gain — classic motor-learning preparation.",
        researcher: "Masao Ito",
        tags: ["VOR", "cerebellum", "Ito"],
      },
      {
        name: "Olfactory transduction",
        description: "Odorants bind GPCRs on olfactory sensory neurons.",
        keyFact: "Each neuron expresses one of ~400 functional human OR genes. Combinatorial coding identifies thousands of odors. OSNs regenerate throughout life.",
        researcher: "Linda Buck & Richard Axel (Nobel 2004)",
        tags: ["olfaction", "OR", "Buck-Axel"],
        xref: ["biology", "chemistry"],
        status: "landmark",
      },
      {
        name: "Olfactory bulb glomeruli",
        description: "Convergent maps of odor identity.",
        keyFact: "Each glomerulus collects axons from OSNs expressing one receptor type. Forms a spatial \"odor code\" map on the bulb surface.",
        tags: ["bulb", "glomerulus", "code"],
      },
      {
        name: "Taste transduction",
        description: "Five basic tastes mediated by distinct mechanisms.",
        keyFact: "Sweet, bitter, umami via GPCRs (T1Rs/T2Rs). Salty via ENaC sodium channels. Sour via proton-sensitive PKD2L1 cells.",
        researcher: "Charles Zuker, Nick Ryba",
        tags: ["taste", "T1R", "T2R", "sour"],
        xref: ["biology"],
      },
      {
        name: "Trigeminal chemosensation",
        description: "Pungent, cooling, hot sensations independent of taste.",
        keyFact: "TRP channels: TRPV1 (capsaicin, heat, acid), TRPM8 (menthol, cool), TRPA1 (mustard oil). Mediates spicy-food \"taste\" cross-modally.",
        researcher: "David Julius & Ardem Patapoutian (Nobel 2021)",
        tags: ["TRP", "TRPV1", "trigeminal"],
        xref: ["chemistry"],
        status: "landmark",
      },
      {
        name: "Multisensory integration",
        description: "Combining information across modalities.",
        keyFact: "Superior colliculus and STS integrate vision/audition/touch. Bayesian models predict optimal cue weighting by reliability — supported behaviorally.",
        researcher: "Barry Stein, Marc Ernst",
        tags: ["multisensory", "Bayesian", "Stein"],
        xref: ["psychology", "statistics"],
      },
      {
        name: "McGurk effect",
        description: "Visual speech alters phoneme perception.",
        keyFact: "Hearing /ba/ while seeing lips say /ga/ yields the percept /da/. Demonstrates obligatory audiovisual integration in speech perception.",
        researcher: "Harry McGurk, John MacDonald (1976)",
        tags: ["McGurk", "speech-perception", "multisensory"],
        xref: ["psychology", "linguistics"],
      },
    ],
  },

  // ── Family 10 ─────────────────────────────────────────────────────────────
  {
    slug: "somatosensation-pain",
    number: 10,
    name: "Somatosensation & Pain",
    blurb: "Touch, proprioception, temperature, and the neuroscience of pain.",
    section: "C",
    color: "rose",
    entries: [
      {
        name: "Mechanoreceptors of the skin",
        description: "Four classes encoding touch.",
        keyFact: "Meissner (fast flutter), Pacinian (vibration), Merkel (pressure/edges), Ruffini (skin stretch). Each has characteristic adaptation kinetics.",
        tags: ["touch", "mechanoreceptor", "Pacinian"],
      },
      {
        name: "Piezo channels",
        description: "Mechanosensitive ion channels for touch and proprioception.",
        keyFact: "Piezo1 and Piezo2 are nonselective cation channels opened by membrane tension. Piezo2 underlies light touch and proprioception in mammals.",
        researcher: "Ardem Patapoutian (Nobel 2021)",
        tags: ["Piezo2", "mechanosensation"],
        xref: ["chemistry", "biology"],
        status: "landmark",
      },
      {
        name: "Two-point discrimination",
        description: "Spatial resolution of touch.",
        keyFact: "Fingertip ~2 mm, back ~40 mm. Reflects density of mechanoreceptors and somatotopic magnification in S1.",
        tags: ["two-point", "resolution"],
      },
      {
        name: "Proprioception",
        description: "The sense of body position.",
        keyFact: "Muscle spindles (length), Golgi tendon organs (force), joint receptors. The \"sixth sense\" — losses (e.g. Ian Waterman) require constant vision to move.",
        tags: ["proprioception", "spindle", "GTO"],
      },
      {
        name: "Dorsal column–medial lemniscus",
        description: "Fast, fine-touch and proprioception pathway.",
        keyFact: "Axons ascend ipsilaterally in dorsal columns → decussate in medulla → VPL of thalamus → S1. Lesion → loss of fine touch and proprioception below.",
        tags: ["DCML", "ascending", "lemniscus"],
        xref: ["medicine"],
      },
      {
        name: "Spinothalamic tract",
        description: "Pain and temperature pathway.",
        keyFact: "Crosses at spinal level of entry → ascends contralaterally → VPL/intralaminar thalamus → S1 and cingulate. Brown-Séquard syndrome dissociates pathways.",
        tags: ["spinothalamic", "pain", "Brown-Séquard"],
        xref: ["medicine"],
      },
      {
        name: "Nociceptors",
        description: "Pain-signaling primary afferents.",
        keyFact: "Free nerve endings of A$\\delta$ (fast, sharp) and C (slow, burning) fibers. Express TRPV1 (heat/capsaicin), TRPM8 (cold), and acid-sensing channels.",
        researcher: "David Julius (TRPV1)",
        tags: ["nociceptor", "A-delta", "C-fiber"],
        xref: ["medicine"],
      },
      {
        name: "Gate-control theory",
        description: "Spinal gating of pain by touch input.",
        keyFact: "Large-fiber tactile input inhibits projection neurons in dorsal horn, reducing pain transmission. Theoretical basis for TENS therapy.",
        researcher: "Ronald Melzack & Patrick Wall (1965)",
        tags: ["gate-control", "Melzack-Wall", "TENS"],
        xref: ["medicine"],
      },
      {
        name: "Descending pain modulation",
        description: "Periaqueductal gray drives endogenous analgesia.",
        keyFact: "PAG → rostroventral medulla → spinal cord uses endogenous opioids and serotonin to suppress pain. Stimulation produces stimulation-produced analgesia.",
        researcher: "John Liebeskind, Allan Basbaum",
        tags: ["PAG", "RVM", "descending"],
        xref: ["medicine"],
      },
      {
        name: "Central sensitization",
        description: "Spinal hyperexcitability after persistent input.",
        keyFact: "NMDA-dependent plasticity in dorsal horn lowers pain threshold (allodynia) and amplifies responses (hyperalgesia). Mechanism of chronic pain.",
        researcher: "Clifford Woolf",
        tags: ["sensitization", "allodynia", "chronic-pain"],
        xref: ["medicine"],
      },
      {
        name: "Phantom limb",
        description: "Persistent percept of an amputated limb.",
        keyFact: "Cortical reorganization in S1 — face area can invade the missing-hand zone (Ramachandran). Mirror-box therapy can relieve phantom pain.",
        researcher: "V. S. Ramachandran",
        tags: ["phantom", "Ramachandran", "mirror-box"],
        xref: ["psychology"],
      },
      {
        name: "Itch",
        description: "Distinct sensation with dedicated circuitry.",
        keyFact: "Histaminergic and non-histaminergic itch routes through gastrin-releasing-peptide-receptor neurons in dorsal horn. Anatomically separable from pain.",
        researcher: "Zhou-Feng Chen",
        tags: ["itch", "GRPR", "pruriception"],
        xref: ["medicine"],
      },
      {
        name: "C-tactile afferents",
        description: "Slow unmyelinated touch fibers carrying affective touch.",
        keyFact: "Tuned to skin-temperature, gentle stroking (~3 cm/s). Convey pleasantness; loss in CIPA does not eliminate pain but does alter social touch.",
        researcher: "Francis McGlone, Håkan Olausson",
        tags: ["CT-afferent", "affective-touch"],
        xref: ["psychology"],
      },
      {
        name: "Body schema",
        description: "Internal model of one's body in space.",
        keyFact: "Built from multisensory and proprioceptive signals in posterior parietal cortex. Rubber-hand illusion shows how readily it incorporates external objects.",
        researcher: "Botvinick & Cohen (rubber-hand, 1998)",
        tags: ["body-schema", "rubber-hand"],
        xref: ["psychology"],
      },
    ],
  },

  // ── Family 11 ─────────────────────────────────────────────────────────────
  {
    slug: "motor-systems",
    number: 11,
    name: "Motor Systems & Control",
    blurb: "Cortical motor maps, descending tracts, basal ganglia, cerebellar control, and the spinal output.",
    section: "C",
    color: "violet",
    entries: [
      {
        name: "Motor homunculus",
        description: "Body map across primary motor cortex.",
        keyFact: "Stimulation along the precentral gyrus produces movements of specific body parts. Hand, face, and lips occupy disproportionately large territory.",
        researcher: "Wilder Penfield",
        tags: ["homunculus", "Penfield"],
      },
      {
        name: "Premotor cortex",
        description: "Externally cued movement planning.",
        keyFact: "Dorsal premotor (PMd) plans reaches; ventral premotor (PMv) houses mirror neurons. Lesion impairs response to sensory cues.",
        tags: ["premotor", "mirror-neurons"],
      },
      {
        name: "Supplementary motor area",
        description: "Internally generated movement sequences.",
        keyFact: "SMA fires before voluntary acts; sites of the Bereitschaftspotential (readiness potential). Lesion → alien hand sign.",
        researcher: "Hans Kornhuber, Lüder Deecke",
        tags: ["SMA", "readiness-potential"],
        xref: ["psychology"],
      },
      {
        name: "Corticospinal tract",
        description: "Direct cortical control over spinal motor neurons.",
        keyFact: "Largely from M1 and PMC; ~90% of fibers cross at the medullary pyramids. Damage causes contralateral spastic hemiparesis with Babinski sign.",
        tags: ["corticospinal", "pyramidal", "edge"],
        xref: ["medicine"],
      },
      {
        name: "Central pattern generator",
        description: "Spinal circuits that produce rhythmic movement.",
        keyFact: "Networks of interneurons generate locomotor rhythms in lampreys, rodents, and humans without descending input. Walking can be elicited in spinalized cats.",
        researcher: "Sten Grillner, Anders Lundberg",
        tags: ["CPG", "locomotion", "Grillner"],
      },
      {
        name: "Stretch reflex",
        description: "Monosynaptic muscle-length feedback.",
        keyFact: "Muscle spindle Ia afferents synapse directly on $\\alpha$-motor neurons of the same muscle — knee-jerk. Modulated by $\\gamma$-motor neurons setting spindle sensitivity.",
        researcher: "Charles Sherrington",
        tags: ["stretch-reflex", "Sherrington", "Ia"],
      },
      {
        name: "Cerebellar motor loop",
        description: "Cortex → pontine nuclei → cerebellum → thalamus → cortex.",
        keyFact: "Cerebellum compares intended motion (efference copy) with actual sensory feedback and emits corrective signals. Damage → ataxia, dysmetria, intention tremor.",
        researcher: "David Marr, James Albus",
        tags: ["cerebellum", "loop", "edge"],
        xref: ["medicine"],
      },
      {
        name: "Climbing fiber teaching signal",
        description: "Error signal for cerebellar learning.",
        keyFact: "Each Purkinje cell receives one climbing fiber from the inferior olive. Climbing-fiber activity triggers LTD at parallel-fiber synapses — basis of VOR adaptation.",
        researcher: "Masao Ito",
        tags: ["climbing-fiber", "LTD", "Ito"],
      },
      {
        name: "Basal-ganglia action selection",
        description: "Direct and indirect pathways pick among motor programs.",
        keyFact: "Tonic GPi inhibition gates thalamic motor output; direct pathway releases the chosen action while indirect pathway suppresses competing ones.",
        researcher: "DeLong, Alexander",
        tags: ["BG", "action-selection"],
      },
      {
        name: "Mirror neuron",
        description: "Cell firing for both performed and observed action.",
        keyFact: "Discovered in macaque area F5 (PMv) — fires when monkey grasps food and when it observes another grasping. Human homologues in IFG/IPL inferred from fMRI.",
        researcher: "Giacomo Rizzolatti",
        tags: ["mirror-neuron", "F5", "Rizzolatti"],
        xref: ["psychology"],
        status: "contested",
      },
      {
        name: "Motor learning",
        description: "Acquisition of skilled movement.",
        keyFact: "Cerebellum supports error-based adaptation; basal ganglia support reinforcement-based skill; cortex supports model-based planning. Each shows distinct retention profiles.",
        researcher: "Reza Shadmehr, Daniel Wolpert",
        tags: ["motor-learning", "adaptation"],
      },
      {
        name: "Internal model",
        description: "Brain's predictive model of the body and world.",
        keyFact: "Forward models predict sensory consequences of motor commands; inverse models compute commands from desired states. Implicated in tickling self-suppression.",
        researcher: "Mitsuo Kawato, Wolpert",
        tags: ["forward-model", "internal-model"],
      },
      {
        name: "Eye-movement systems",
        description: "Five oculomotor subsystems.",
        keyFact: "Saccades, smooth pursuit, vergence, VOR, optokinetic. Each has dedicated brainstem circuitry; lesions produce distinct deficits.",
        tags: ["eye-movements", "saccade", "pursuit"],
      },
      {
        name: "Brain–computer interface (motor)",
        description: "Cortical signals decode movement intent.",
        keyFact: "Intracortical arrays (Utah array) in M1 have allowed paralyzed patients to control robotic arms and cursors. Recent BCI restored speech at >60 wpm (2023, UCSF/Stanford).",
        researcher: "John Donoghue, BrainGate; Eddie Chang (speech)",
        tags: ["BCI", "Utah-array", "BrainGate"],
        xref: ["medicine", "engineering"],
      },
    ],
  },

  // ── Family 12 ─────────────────────────────────────────────────────────────
  {
    slug: "neural-development",
    number: 12,
    name: "Neural Development",
    blurb: "From neural tube to cortical wiring — neurogenesis, migration, guidance, and pruning.",
    section: "D",
    color: "indigo",
    entries: [
      {
        name: "Neural induction",
        description: "Ectoderm fated to become neural tissue.",
        keyFact: "Default neural fate model: ectoderm becomes neural unless told otherwise. Organizer (Spemann's) BMP antagonists (noggin, chordin) inhibit BMP signaling, allowing neural fate.",
        researcher: "Hans Spemann, Hilde Mangold",
        tags: ["neural-induction", "BMP", "noggin"],
        xref: ["biology"],
      },
      {
        name: "Neural tube closure",
        description: "Folding of neural plate into a tube.",
        keyFact: "Closure begins ~day 22 in humans. Failure causes spina bifida (caudal) or anencephaly (rostral). Folate prevents most defects.",
        tags: ["neural-tube", "spina-bifida"],
        xref: ["medicine"],
      },
      {
        name: "Neurogenesis",
        description: "Birth of neurons from radial glia and progenitors.",
        keyFact: "Most cortical neurons in humans are generated between gestational weeks 5 and 18, peaking near week 13. ~250,000 neurons per minute.",
        tags: ["neurogenesis", "radial-glia"],
      },
      {
        name: "Adult neurogenesis",
        description: "Generation of new neurons after development.",
        keyFact: "Robust in olfactory bulb (rodents) and dentate gyrus. Whether adult human DG generates new neurons across lifespan remains contested (Sorrells 2018 vs Boldrini 2018).",
        researcher: "Joseph Altman, Fred Gage, Maria Llorens-Martín",
        tags: ["adult-neurogenesis", "DG"],
        xref: ["medicine"],
        status: "contested",
      },
      {
        name: "Radial migration",
        description: "Cortical neurons climb radial glia to their layer.",
        keyFact: "Inside-out pattern: earliest-born populate deepest layers (V/VI), later-born settle in upper layers. Reeler mutation reverses this.",
        researcher: "Pasko Rakic",
        tags: ["migration", "radial-glia", "inside-out"],
      },
      {
        name: "Tangential migration",
        description: "Interneurons sweep into cortex from ganglionic eminences.",
        keyFact: "MGE-derived PV/SST interneurons and CGE-derived VIP interneurons migrate tangentially before integrating into cortical layers.",
        researcher: "Oscar Marín, John Rubenstein",
        tags: ["interneuron", "GE", "tangential"],
      },
      {
        name: "Axon guidance",
        description: "Growth cones navigate via guidance molecules.",
        keyFact: "Netrins, slits, semaphorins, ephrins act as attractants or repellents over short and long range. Discovered using commissural-axon attraction.",
        researcher: "Marc Tessier-Lavigne, Corey Goodman",
        tags: ["axon-guidance", "netrin", "growth-cone"],
        xref: ["biology"],
      },
      {
        name: "Topographic maps",
        description: "Ordered projections (e.g. retinotectal).",
        keyFact: "Ephrin–Eph gradients position retinal axons in tectum. Sperry's chemoaffinity hypothesis (1963) was vindicated by molecular biology.",
        researcher: "Roger Sperry, John Flanagan",
        tags: ["map", "ephrin", "Sperry"],
        status: "landmark",
      },
      {
        name: "Synaptogenesis",
        description: "Massive synapse formation in early life.",
        keyFact: "Human cortex peaks at ~1000 trillion synapses around age 2. Trans-synaptic adhesion proteins (neurexins, neuroligins) specify partners.",
        researcher: "Peter Huttenlocher",
        tags: ["synaptogenesis", "neuroligin"],
      },
      {
        name: "Programmed cell death",
        description: "~50% of developing neurons die.",
        keyFact: "Target-derived neurotrophins (NGF, BDNF) rescue neurons that make appropriate connections; the rest undergo apoptosis. Rita Levi-Montalcini's NGF discovery.",
        researcher: "Rita Levi-Montalcini & Stanley Cohen (Nobel 1986)",
        tags: ["apoptosis", "NGF", "Levi-Montalcini"],
        status: "landmark",
      },
      {
        name: "Synaptic pruning",
        description: "Elimination of excess synapses in adolescence.",
        keyFact: "Microglia tag weak synapses with complement (C1q) and engulf them. Pruning peaks in PFC during adolescence; dysregulation implicated in schizophrenia.",
        researcher: "Beth Stevens, Steven McCarroll",
        tags: ["pruning", "C1q", "microglia"],
        xref: ["medicine"],
      },
      {
        name: "Myelination",
        description: "Wrapping of axons by oligodendrocytes / Schwann cells.",
        keyFact: "Begins prenatally in spinal cord, continues into the 30s in PFC. Myelination tracks behavioral milestones; activity-dependent myelination is a 2010s discovery.",
        researcher: "R. Douglas Fields",
        tags: ["myelin", "white-matter"],
      },
      {
        name: "Activity-dependent refinement",
        description: "\"Cells that fire together wire together.\"",
        keyFact: "LGN inputs to V1 segregate into eye-specific layers via spontaneous waves of retinal activity before vision begins.",
        researcher: "Carla Shatz",
        tags: ["activity-dependent", "retinal-waves"],
      },
      {
        name: "Critical period",
        description: "Bounded window of heightened plasticity.",
        keyFact: "Monocular deprivation in kittens reshapes V1 during a few weeks postnatal but not later (Hubel & Wiesel). Closure linked to PV interneuron maturation and perineuronal nets.",
        researcher: "Hubel & Wiesel; Takao Hensch",
        tags: ["critical-period", "PV", "PNN"],
        xref: ["psychology"],
        status: "landmark",
      },
    ],
  },

  // ── Family 13 ─────────────────────────────────────────────────────────────
  {
    slug: "plasticity",
    number: 13,
    name: "Synaptic Plasticity",
    blurb: "LTP, LTD, Hebbian rules, and the molecular machinery that lets synapses learn.",
    section: "D",
    color: "blue",
    entries: [
      {
        name: "Hebbian rule",
        description: "Neurons that fire together strengthen their connection.",
        keyFact: "Hebb's 1949 conjecture: \"When an axon of cell A... repeatedly takes part in firing it, some growth process... takes place such that A's efficiency is increased.\"",
        researcher: "Donald Hebb (1949)",
        tags: ["Hebb", "fire-together"],
        xref: ["psychology"],
        status: "landmark",
      },
      {
        name: "Long-term potentiation",
        description: "Persistent strengthening of synapses after high-frequency stimulation.",
        keyFact: "Discovered in hippocampal slices: tetanic input produces EPSP enhancement lasting hours to days. NMDA-receptor-dependent in CA1.",
        researcher: "Tim Bliss & Terje Lømo (1973)",
        tags: ["LTP", "Bliss-Lomo", "CA1"],
        status: "landmark",
      },
      {
        name: "Long-term depression",
        description: "Persistent weakening of synapses.",
        keyFact: "Low-frequency stimulation triggers LTD via AMPAR internalization. Cerebellar LTD (parallel-fiber → Purkinje) drives motor learning.",
        researcher: "Masao Ito (cerebellar), Mark Bear (cortical)",
        tags: ["LTD", "AMPAR", "depression"],
      },
      {
        name: "NMDA-dependent LTP",
        description: "Coincidence-detection mechanism.",
        keyFact: "Pre-spike releases glutamate; coincident post-depolarization removes Mg2+ block; Ca2+ entry through NMDA triggers CaMKII autophosphorylation and AMPAR insertion.",
        researcher: "Roger Nicoll, Robert Malenka",
        tags: ["NMDA", "CaMKII", "Ca-influx"],
      },
      {
        name: "CaMKII switch",
        description: "Molecular memory at the postsynaptic density.",
        keyFact: "Calcium/calmodulin-dependent kinase II autophosphorylates at T286 and stays active without further Ca2+. Holoenzymes of 12 subunits behave bistably.",
        researcher: "Mary Kennedy, John Lisman",
        tags: ["CaMKII", "switch", "T286"],
      },
      {
        name: "Spike-timing-dependent plasticity",
        description: "Synaptic change depends on relative spike timing.",
        keyFact: "Pre-before-post (~+10 ms) → LTP; post-before-pre → LTD. Window of ~20 ms; symmetric in some synapses, asymmetric in others.",
        researcher: "Henry Markram, Guoqiang Bi, Mu-ming Poo",
        tags: ["STDP", "timing", "Markram"],
      },
      {
        name: "Synaptic tagging and capture",
        description: "Early LTP captures plasticity-related proteins from late LTP.",
        keyFact: "Frey & Morris: a transiently tagged synapse can capture proteins synthesized in response to other strong activity, consolidating its potentiation.",
        researcher: "Uwe Frey, Richard Morris",
        tags: ["STC", "tag-and-capture"],
      },
      {
        name: "Homeostatic plasticity",
        description: "Compensatory scaling of synaptic strength.",
        keyFact: "Sustained activity changes prompt multiplicative scaling of AMPARs across all synapses, stabilizing firing rates over days.",
        researcher: "Gina Turrigiano",
        tags: ["homeostatic", "scaling", "Turrigiano"],
      },
      {
        name: "BDNF & TrkB",
        description: "Growth factor pathway for plasticity.",
        keyFact: "Brain-derived neurotrophic factor binds TrkB to support LTP, synapse formation, and survival. Val66Met polymorphism affects activity-dependent secretion.",
        researcher: "Yves-Alain Barde, Mu-ming Poo",
        tags: ["BDNF", "TrkB", "Val66Met"],
        xref: ["biology"],
      },
      {
        name: "Structural plasticity",
        description: "Long-term physical change in dendrites and spines.",
        keyFact: "Two-photon imaging shows spines appear and disappear daily; learning increases stable spine density in motor and visual cortex.",
        researcher: "Karel Svoboda, Wenbiao Gan",
        tags: ["spine", "structural", "two-photon"],
      },
      {
        name: "Engram",
        description: "Physical substrate of a specific memory.",
        keyFact: "Optogenetic reactivation of a sparse population of DG neurons labeled during fear learning reinstates the fear memory (Tonegawa lab, 2012).",
        researcher: "Susumu Tonegawa, Sheena Josselyn",
        tags: ["engram", "optogenetics", "Tonegawa"],
        xref: ["psychology"],
      },
      {
        name: "Hippocampal replay",
        description: "Compressed re-firing of place-cell sequences.",
        keyFact: "During slow-wave sleep and quiet rest, place cells replay waking trajectories at ~20× speed, consolidating memory and informing planning.",
        researcher: "Matthew Wilson, Bruce McNaughton",
        tags: ["replay", "sleep", "consolidation"],
        xref: ["psychology"],
      },
      {
        name: "Reconsolidation",
        description: "Recall transiently destabilizes a memory.",
        keyFact: "After retrieval, memories require protein synthesis to be re-stabilized. Pharmacological blockade or behavioral interference can update or weaken them.",
        researcher: "Karim Nader, Joseph LeDoux",
        tags: ["reconsolidation", "Nader"],
        xref: ["psychology"],
      },
      {
        name: "Sharp-wave ripples",
        description: "Hippocampal high-frequency oscillations.",
        keyFact: "~150–200 Hz events accompany replay and are causally required for memory consolidation: closed-loop disruption impairs spatial learning.",
        researcher: "György Buzsáki",
        tags: ["SWR", "ripple", "Buzsaki"],
      },
    ],
  },
];
