import type { Family } from "./types";

export const FAMILIES_1_6: Family[] = [
  // ── Family 1 ──────────────────────────────────────────────────────────────
  {
    slug: "physical-oceanography",
    number: 1,
    name: "Physical Oceanography",
    blurb: "Currents, water masses, waves, tides, and ocean circulation.",
    section: "A",
    color: "sky",
    entries: [
      {
        name: "Thermohaline circulation",
        description: "Global density-driven circulation linking surface and deep oceans.",
        keyFact: "Cold, salty surface water sinks at high latitudes (Nordic Seas, Weddell Sea) and slowly returns to the surface elsewhere; one full loop takes ~1,000–2,000 years. Also called the 'great ocean conveyor' (Broecker 1991).",
        tags: ["circulation", "deep-water", "conveyor"],
      },
      {
        name: "Atlantic Meridional Overturning Circulation (AMOC)",
        description: "The Atlantic component of the conveyor — northward heat transport, southward return.",
        keyFact: "Transports ~17 Sv (sverdrups; $1\\,\\mathrm{Sv} = 10^6\\,\\mathrm{m^3/s}$) and carries ~1.3 PW of heat poleward, keeping NW Europe ~5 °C warmer than its latitude average. Has weakened ~15% since the mid-20th century per proxy reconstructions (Caesar et al. 2018).",
        formula: "1\\,\\mathrm{Sv} = 10^6\\,\\mathrm{m^3/s}",
        tags: ["AMOC", "circulation", "Atlantic", "tipping"],
        status: "open",
      },
      {
        name: "Gulf Stream",
        description: "Western boundary current of the North Atlantic subtropical gyre.",
        keyFact: "Transports ~30 Sv past Cape Hatteras, ~150 Sv at peak downstream. ~80 km wide, ~1 km deep, surface speed ~2 m/s. Discovered for navigation by Benjamin Franklin (1769 chart with Timothy Folger).",
        tags: ["western-boundary", "gyre", "Atlantic"],
      },
      {
        name: "Kuroshio Current",
        description: "Pacific analog of the Gulf Stream — west-boundary current off Japan.",
        keyFact: "Transports ~42 Sv at peak; meanders shift between 'straight' and 'large-meander' modes that persist for years and affect fisheries and typhoon tracks.",
        tags: ["western-boundary", "Pacific"],
      },
      {
        name: "Antarctic Circumpolar Current (ACC)",
        description: "Wind-driven current circling Antarctica unobstructed by continents.",
        keyFact: "Largest current on Earth — transports ~173 Sv through Drake Passage, more than all rivers combined ×100. Drove the thermal isolation of Antarctica after the Drake Passage opened ~34 Ma.",
        tags: ["circumpolar", "Antarctic"],
      },
      {
        name: "Ekman transport",
        description: "Net wind-driven water transport, deflected 90° by Coriolis.",
        keyFact: "Net flow in the surface Ekman layer is at right angles to the wind — to the right of the wind in the Northern Hemisphere, left in the Southern. Underlies coastal upwelling and gyre formation.",
        formula: "M_E = \\tau / (\\rho f)",
        xref: ["physics"],
        tags: ["Ekman", "Coriolis", "wind"],
      },
      {
        name: "Coastal upwelling",
        description: "Wind-driven uplift of cold, nutrient-rich deep water to the surface.",
        keyFact: "Four major eastern-boundary upwelling systems — California, Humboldt (Peru), Canary, Benguela — produce ~20% of global fish catch from ~1% of ocean area. Driven by alongshore equatorward wind + Ekman offshore transport.",
        tags: ["upwelling", "fisheries", "nutrients"],
      },
      {
        name: "Ocean gyres (five subtropical)",
        description: "Large rotating systems in the subtropical Atlantic, Pacific, and Indian.",
        keyFact: "Five subtropical gyres — North Atlantic, South Atlantic, North Pacific, South Pacific, Indian — rotate clockwise in the Northern Hemisphere, counter-clockwise in the Southern. Their interiors are nutrient-poor 'ocean deserts' and accumulate floating plastic (e.g. Great Pacific Garbage Patch).",
        tags: ["gyres", "circulation", "plastic"],
      },
      {
        name: "Sverdrup balance",
        description: "Wind-stress curl balanced by meridional transport in the ocean interior.",
        keyFact: "Vertically integrated meridional transport equals the wind-stress curl divided by $\\beta$ (the meridional gradient of Coriolis). Predicts equatorward flow under anticyclonic wind stress and explains gyre interiors.",
        formula: "\\beta V = \\nabla \\times \\tau / \\rho",
        xref: ["physics"],
        tags: ["wind-driven", "theory"],
      },
      {
        name: "Geostrophic flow",
        description: "Balance between pressure-gradient force and Coriolis in slow large-scale flow.",
        keyFact: "In most ocean interiors, currents flow along (not down) pressure gradients, with flow ~90° to the right of the gradient in the Northern Hemisphere. Lets oceanographers infer currents from sea-surface height (altimetry).",
        formula: "fu = -\\frac{1}{\\rho}\\frac{\\partial p}{\\partial y}",
        xref: ["physics"],
        tags: ["geostrophy", "balance"],
      },
      {
        name: "Tides",
        description: "Periodic sea-level rise and fall caused by lunar and solar gravity.",
        keyFact: "Two high tides per ~25-hour lunar day; spring tides (full/new moon, aligned forces) ~20% higher than neap (quarter moon). Largest range: Bay of Fundy, ~16 m. Tides are resonant standing waves in each ocean basin, not the Moon directly pulling water up.",
        xref: ["physics", "astronomy"],
        tags: ["tides", "lunar", "gravity"],
      },
      {
        name: "Tidal constituents",
        description: "Decomposition of tides into sinusoidal components by astronomical forcing.",
        keyFact: "M₂ (principal lunar semidiurnal, 12.42 h) is the dominant constituent globally. S₂ (solar semidiurnal), K₁ (lunar diurnal), O₁ (lunar diurnal) account for most of the residual; tides at any port can be reconstructed from ~37 constituents.",
        tags: ["harmonic-analysis", "M2"],
      },
      {
        name: "Surface waves and dispersion",
        description: "Wind-generated waves with frequency-dependent propagation speed.",
        keyFact: "In deep water, phase speed $c = \\sqrt{g\\lambda/(2\\pi)}$ — longer waves travel faster. Wind sea is dispersive; swell sorts itself by period as it propagates from a distant storm.",
        formula: "c = \\sqrt{g\\lambda / (2\\pi)}",
        xref: ["physics"],
        tags: ["waves", "dispersion"],
      },
      {
        name: "Rogue waves",
        description: "Exceptionally large waves (≥2.2× significant wave height).",
        keyFact: "First scientific confirmation: Draupner wave, North Sea, 1995-01-01, height 25.6 m measured by laser altimeter — implausibly tall by linear wave theory. Now attributed to constructive interference + nonlinear focusing; satellite altimetry shows they are common globally.",
        tags: ["rogue", "extreme"],
        status: "landmark",
      },
      {
        name: "Sea-surface temperature (SST)",
        description: "Temperature of the upper ~1 mm to few meters of the ocean.",
        keyFact: "Global mean SST ~17.5 °C; record monthly high April 2024 at 21.1 °C. The most influential climate boundary condition — drives evaporation, heat flux, atmospheric circulation. Measured by satellites (ARGO + AVHRR + MODIS).",
        tags: ["SST", "temperature"],
      },
      {
        name: "Mixed layer depth",
        description: "Depth of the upper layer homogenized by wind and convection.",
        keyFact: "Typical summer depth ~20–50 m, winter ~100–200 m at mid-latitudes; >1,000 m in deep-convection regions (Labrador, Greenland, Weddell). Sets how much heat the ocean can absorb seasonally.",
        tags: ["mixed-layer", "thermocline"],
      },
      {
        name: "Thermocline / pycnocline",
        description: "Layer of rapid temperature/density change separating surface and deep ocean.",
        keyFact: "Permanent thermocline at ~200–1,000 m in low latitudes; seasonal thermocline forms in summer and erodes in winter. Inhibits vertical mixing and so traps heat in the upper ocean.",
        tags: ["thermocline", "stratification"],
      },
      {
        name: "Argo float array",
        description: "Global array of ~4,000 autonomous profiling floats.",
        keyFact: "Each Argo float cycles to 2,000 m every ~10 days, measuring T and salinity. Deployed since 2000; now provides ~120,000 profiles/yr and is the backbone of ocean climate monitoring. Deep Argo (6,000 m) and Bio-Argo (oxygen, chlorophyll) extend coverage.",
        tags: ["Argo", "observing"],
      },
    ],
  },

  // ── Family 2 ──────────────────────────────────────────────────────────────
  {
    slug: "marine-chemistry",
    number: 2,
    name: "Marine Chemistry",
    blurb: "Salinity, dissolved gases, nutrients, acidification, and ocean biogeochemistry.",
    section: "A",
    color: "cyan",
    entries: [
      {
        name: "Salinity",
        description: "Total dissolved salts in seawater, by mass.",
        keyFact: "Mean ocean salinity ~35 g/kg, mostly $\\mathrm{Na^+}$ (~30%) and $\\mathrm{Cl^-}$ (~55%) by mass. Reported in Practical Salinity Units (PSU) or Absolute Salinity ($\\mathrm{g/kg}$, TEOS-10, 2010). The Red Sea reaches ~40 g/kg; the Baltic dips below 10.",
        xref: ["chemistry"],
        tags: ["salinity", "PSU"],
      },
      {
        name: "Constancy of composition (Marcet's principle)",
        description: "The relative proportions of major ions in seawater are nearly constant.",
        keyFact: "Alexandre Marcet (1819) showed that despite varying salinity, the ratios of $\\mathrm{Na^+}, \\mathrm{Mg^{2+}}, \\mathrm{Ca^{2+}}, \\mathrm{K^+}, \\mathrm{Cl^-}, \\mathrm{SO_4^{2-}}$ are nearly fixed — implying ocean residence times far longer than mixing times.",
        xref: ["chemistry"],
        tags: ["Marcet", "major-ions"],
      },
      {
        name: "Carbonate system in seawater",
        description: "The CO₂–bicarbonate–carbonate equilibrium that buffers ocean pH.",
        keyFact: "$\\mathrm{CO_2 + H_2O \\rightleftharpoons H_2CO_3 \\rightleftharpoons HCO_3^- + H^+ \\rightleftharpoons CO_3^{2-} + 2H^+}$. At seawater pH ~8.1, ~90% of inorganic carbon is as $\\mathrm{HCO_3^-}$. Total inorganic carbon (DIC) and alkalinity together describe the system.",
        formula: "\\mathrm{CO_2 + H_2O \\rightleftharpoons HCO_3^- + H^+}",
        xref: ["chemistry"],
        tags: ["DIC", "alkalinity", "buffer"],
      },
      {
        name: "Ocean acidification",
        description: "Decrease in seawater pH driven by anthropogenic CO₂ uptake.",
        keyFact: "Surface ocean pH has dropped from ~8.21 (preindustrial) to ~8.05 (2025) — a ~30% increase in $\\mathrm{[H^+]}$. Threatens aragonite/calcite saturation horizons; corrosive water now reaches the surface seasonally in the Arctic and California upwelling.",
        formula: "\\mathrm{CO_2 + H_2O + CO_3^{2-} \\rightarrow 2HCO_3^-}",
        xref: ["chemistry"],
        tags: ["acidification", "pH", "CO2"],
        status: "landmark",
      },
      {
        name: "Calcium carbonate saturation horizon",
        description: "Depth below which $\\mathrm{CaCO_3}$ dissolves.",
        keyFact: "Above the aragonite/calcite compensation depth (~ACD/CCD), shells accumulate; below, they dissolve. Atlantic CCD ~5 km, Pacific ~4 km (older, more acidic deep water). Horizon is shoaling under anthropogenic CO₂.",
        tags: ["CCD", "saturation"],
      },
      {
        name: "Dissolved oxygen and oxygen minimum zones",
        description: "Subsurface layers depleted in oxygen by respiration of sinking organic matter.",
        keyFact: "Eastern tropical Pacific and Arabian Sea OMZs drop below ~5 µmol/kg O₂ at ~200–800 m; global ocean has lost ~2% of its O₂ since 1960 (Schmidtko et al. 2017). Expanding OMZs threaten fisheries and drive N₂O emission.",
        xref: ["chemistry"],
        tags: ["OMZ", "deoxygenation"],
      },
      {
        name: "Nutrient cycling (N, P, Si, Fe)",
        description: "Macronutrient and micronutrient distributions and limitations.",
        keyFact: "Nitrate and phosphate follow Redfield ratio C:N:P = 106:16:1 in deep water (Redfield 1934). Iron limits productivity over ~40% of the ocean ('HNLC' regions: Southern Ocean, equatorial Pacific, subarctic Pacific).",
        formula: "\\mathrm{C:N:P} = 106:16:1",
        xref: ["chemistry", "biology"],
        tags: ["Redfield", "nutrients", "iron"],
      },
      {
        name: "Iron fertilization (HNLC)",
        description: "Hypothesis that iron addition would boost productivity and draw down CO₂.",
        keyFact: "Martin (1990): 'Give me a half tanker of iron, and I'll give you an ice age.' Twelve open-ocean iron experiments (1993–2009) confirmed blooms but uncertain carbon export. As geoengineering: small effect, large governance issues.",
        tags: ["Martin", "geoengineering"],
        status: "open",
      },
      {
        name: "Marine biological pump",
        description: "Sinking of fixed organic carbon from the surface to the deep ocean.",
        keyFact: "Phytoplankton fix ~50 Gt C/yr in surface waters; ~10 Gt C/yr sinks below 100 m; ~0.5 Gt C/yr reaches the seafloor (\"export\" and \"sequestration\" fluxes). Without it, atmospheric CO₂ would be ~200 ppm higher.",
        xref: ["biology", "chemistry"],
        tags: ["biological-pump", "carbon"],
      },
      {
        name: "Solubility pump",
        description: "Sequestration of CO₂ by cold-water sinking at high latitudes.",
        keyFact: "Cold water holds more CO₂ — high-latitude sinking carries ~2 Gt C/yr to the deep ocean. The solubility and biological pumps together set the ~280 ppm preindustrial atmospheric CO₂.",
        xref: ["chemistry"],
        tags: ["solubility-pump"],
      },
      {
        name: "Anthropogenic carbon uptake",
        description: "The fraction of fossil-fuel CO₂ absorbed by the oceans.",
        keyFact: "Oceans have absorbed ~30% of cumulative anthropogenic CO₂ (~170 Gt C) — roughly 2.8 Gt C/yr in 2020s. Slowing as surface waters acidify and the Revelle factor rises.",
        xref: ["chemistry"],
        tags: ["sink", "Revelle"],
      },
      {
        name: "Revelle factor",
        description: "Sensitivity of pCO₂ to changes in dissolved inorganic carbon.",
        keyFact: "$R = \\partial \\ln p_{\\mathrm{CO_2}} / \\partial \\ln \\mathrm{DIC} \\approx 10$ in surface ocean — a 1% rise in DIC raises pCO₂ by ~10%. Discovered by Roger Revelle and Hans Suess (1957); explained why oceans cannot quickly absorb all emitted CO₂.",
        formula: "R = \\partial \\ln p_{\\mathrm{CO_2}} / \\partial \\ln \\mathrm{DIC}",
        xref: ["chemistry"],
        tags: ["Revelle", "buffer"],
      },
      {
        name: "Dimethyl sulfide (DMS) and the CLAW hypothesis",
        description: "Marine algal sulfur emissions affect cloud condensation nuclei.",
        keyFact: "Phytoplankton release DMS, which oxidizes to sulfate aerosol in the marine atmosphere — boosting CCN and cloud albedo. Proposed feedback (Charlson-Lovelock-Andreae-Warren 1987): warming → more DMS → cooling. Magnitude and sign of the feedback still debated.",
        xref: ["chemistry", "biology"],
        tags: ["DMS", "CLAW", "aerosol"],
        status: "open",
      },
      {
        name: "Marine snow",
        description: "Continuous shower of organic particles from upper ocean to depth.",
        keyFact: "Aggregates of dead phytoplankton, fecal pellets, and detritus sink at 10–200 m/day. Vehicles for the biological pump and food for deep-sea communities.",
        xref: ["biology"],
        tags: ["marine-snow", "export"],
      },
      {
        name: "Hydrothermal vent chemistry",
        description: "Hot, metal-rich fluid emitted at mid-ocean ridges.",
        keyFact: "Discovered 1977 at Galápagos Rift. Vent fluids reach 350–400 °C, are sulfide-rich, and host chemosynthetic ecosystems based on H₂S oxidation by bacteria. Major source of ocean Fe, Mn, He-3.",
        xref: ["geology", "biology"],
        tags: ["hydrothermal", "vents"],
      },
      {
        name: "Salinity-density-temperature equation of state",
        description: "Seawater density depends nonlinearly on T, S, p.",
        keyFact: "TEOS-10 (2010) replaced EOS-80 as the international standard for seawater thermodynamics. Density variations ~0.3% but drive every density current; cold water is denser at most salinities relevant to the open ocean.",
        xref: ["physics"],
        tags: ["TEOS-10", "EOS"],
      },
    ],
  },

  // ── Family 3 ──────────────────────────────────────────────────────────────
  {
    slug: "hydrology",
    number: 3,
    name: "Hydrology",
    blurb: "Freshwater systems on land — rivers, lakes, groundwater, evapotranspiration.",
    section: "A",
    color: "teal",
    entries: [
      {
        name: "Global water cycle (closure)",
        description: "Mass-balance accounting of all water reservoirs and fluxes.",
        keyFact: "Annual evaporation = annual precipitation = ~505,000 km³/yr globally. Ocean evaporates ~426,000 km³; land ~73,000 km³; net land-to-ocean river flow ~40,000 km³. Mean atmospheric residence time of a water molecule: ~9 days.",
        formula: "P_{\\mathrm{global}} = E_{\\mathrm{global}}",
        tags: ["water-cycle", "global"],
      },
      {
        name: "Evapotranspiration",
        description: "Combined evaporation from soil/water + transpiration from plants.",
        keyFact: "Penman-Monteith equation is the FAO standard for reference ET. Globally, ET returns ~63% of land precipitation to the atmosphere. Forests transpire ~700 mm/yr; deserts <50 mm/yr.",
        formula: "\\lambda E = \\frac{\\Delta(R_n - G) + \\rho c_p \\delta e / r_a}{\\Delta + \\gamma(1 + r_s/r_a)}",
        tags: ["ET", "Penman-Monteith"],
      },
      {
        name: "Catchment / watershed",
        description: "Area of land draining to a common outlet.",
        keyFact: "Defined by topographic divides; the world's largest catchment is the Amazon at ~7.05 million km². Catchments are the fundamental unit of hydrological accounting, ecology, and water-rights law.",
        tags: ["watershed", "catchment"],
      },
      {
        name: "Discharge (Q) and stream gauging",
        description: "Volume of water flow per unit time at a cross-section.",
        keyFact: "$Q = A \\bar v$. Amazon mean discharge ~209,000 m³/s — ~20% of all river discharge to the ocean. Congo ~41,000 m³/s; Mississippi ~17,000 m³/s. The U.S. Geological Survey operates >8,000 stream gauges.",
        formula: "Q = A\\bar v",
        tags: ["discharge", "USGS"],
      },
      {
        name: "Manning equation",
        description: "Empirical formula for open-channel mean velocity.",
        keyFact: "$\\bar v = (1/n) R_h^{2/3} S^{1/2}$ with $n$ the roughness coefficient (~0.03 for natural channels), $R_h$ hydraulic radius, $S$ slope. Robert Manning 1889. Still the workhorse of culvert and floodplain design.",
        formula: "\\bar v = \\frac{1}{n} R_h^{2/3} S^{1/2}",
        tags: ["Manning", "open-channel"],
      },
      {
        name: "Darcy's law",
        description: "Linear relationship between groundwater flux and head gradient.",
        keyFact: "$q = -K \\nabla h$. Henry Darcy 1856, derived from sand-column experiments in Dijon. Foundation of groundwater hydrology; $K$ (hydraulic conductivity) spans ~13 orders of magnitude from clay to gravel.",
        formula: "q = -K \\nabla h",
        xref: ["geology", "physics"],
        tags: ["Darcy", "groundwater"],
      },
      {
        name: "Aquifer types",
        description: "Subsurface water-bearing layers — confined vs unconfined.",
        keyFact: "Unconfined aquifers have a free water table; confined are bounded above by aquitards and can produce artesian flow. The Ogallala (~450,000 km²) underlies the US High Plains and supplies ~30% of US irrigation.",
        xref: ["geology"],
        tags: ["aquifer", "Ogallala"],
      },
      {
        name: "Recharge and safe yield",
        description: "Rate of replenishment vs sustainable extraction from an aquifer.",
        keyFact: "Sustainable extraction must equal long-term recharge plus capture of pre-existing discharge. Mining of fossil groundwater (Ogallala, North China Plain, Punjab) draws down water tables by ~1–3 m/yr.",
        tags: ["recharge", "depletion"],
      },
      {
        name: "Groundwater age dating",
        description: "Tracers used to estimate residence time of subsurface water.",
        keyFact: "Tritium (half-life 12.3 yr, bomb pulse from 1950s tests) marks post-1950 water. CFCs and SF₆ extend ~50-yr clock. ¹⁴C for thousands to ~30,000 yr; ⁸¹Kr / ³⁶Cl for ~10⁶ yr. Old groundwater under Sahara: ~1 million years.",
        xref: ["chemistry"],
        tags: ["tritium", "tracers"],
      },
      {
        name: "Rivers — typology",
        description: "Perennial, intermittent, and ephemeral streams.",
        keyFact: "Perennial streams flow year-round; intermittent during wet seasons; ephemeral only after storms. Datry et al. (2014): >50% of global river length is non-perennial — large hydrological and ecological consequences for arid-region water law.",
        tags: ["rivers", "intermittent"],
      },
      {
        name: "Flood frequency analysis",
        description: "Statistical estimation of flood magnitudes vs return period.",
        keyFact: "Log-Pearson III is the US federal standard (Bulletin 17C, 2018) for annual flood peaks. A '100-year flood' has probability $1/100$ per year, not 'once per century'. Climate non-stationarity has broken many standard tables.",
        xref: ["statistics"],
        tags: ["floods", "return-period"],
      },
      {
        name: "Lake stratification and turnover",
        description: "Seasonal layering of temperate lake water columns.",
        keyFact: "Dimictic lakes mix twice a year (spring and fall turnover) when surface and bottom temperatures match and density barriers disappear; summer epilimnion/hypolimnion separated by thermocline. Drives nutrient release and oxygenation.",
        tags: ["lakes", "turnover"],
      },
      {
        name: "Largest freshwater lakes",
        description: "Inventory by volume — Baikal, the Great Lakes, Tanganyika.",
        keyFact: "Lake Baikal holds ~23,615 km³ (~22% of global surface freshwater), the largest single freshwater volume on Earth. Lake Superior, Tanganyika, and Malawi each hold ~8–18,000 km³. Caspian (~78,000 km³) is technically a salt sea.",
        tags: ["lakes", "Baikal"],
      },
      {
        name: "Glacier-fed rivers",
        description: "River systems with significant cryospheric input.",
        keyFact: "The Ganges, Brahmaputra, Indus, Mekong, Yangtze, and Yellow rivers receive ~10–60% of dry-season flow from glacial and snow melt; ~1.5 billion downstream people depend on the Hindu Kush–Himalaya 'water tower' (Immerzeel et al. 2020).",
        tags: ["meltwater", "Himalaya"],
      },
      {
        name: "GRACE / GRACE-FO satellite",
        description: "Gravity satellites measuring continental water-mass changes.",
        keyFact: "Twin satellites track each other to measure gravity. Resolution ~300 km, ~1 cm equivalent water height. Documented groundwater depletion in California Central Valley, India Punjab, the Middle East. GRACE: 2002–2017; GRACE-FO: 2018–present.",
        tags: ["GRACE", "gravity"],
      },
      {
        name: "Soil moisture",
        description: "Volumetric water content of the vadose zone.",
        keyFact: "Field capacity ~30% (after gravity drainage); wilting point ~10–15%. Soil moisture is a key initial condition for both drought propagation and weather prediction; satellite missions SMOS (2009), SMAP (2015) provide global coverage.",
        tags: ["soil-moisture", "SMAP"],
      },
      {
        name: "Hyporheic zone",
        description: "Mixed-water zone beneath and adjacent to streambeds.",
        keyFact: "Where stream water and groundwater exchange; biogeochemically intense, ~10⁴–10⁵ microbial gradient steeper than the surrounding aquifer. Critical for nutrient removal, salmon redds, and contaminant attenuation.",
        xref: ["biology"],
        tags: ["hyporheic", "stream"],
      },
    ],
  },

  // ── Family 4 ──────────────────────────────────────────────────────────────
  {
    slug: "cryosphere",
    number: 4,
    name: "Cryosphere",
    blurb: "All forms of frozen water — sea ice, ice sheets, snow, and permafrost.",
    section: "A",
    color: "emerald",
    entries: [
      {
        name: "Cryosphere components and budget",
        description: "Inventory of Earth's frozen reservoirs.",
        keyFact: "Antarctic ice sheet ~26.5 million km³ (~58 m SLR equivalent); Greenland ~2.9 million km³ (~7.4 m SLR); glaciers ~0.16 million km³ (~0.32 m); seasonal snow ~0.005 million km³; sea ice ~0.02 million km³ (no SLR, already displacing).",
        tags: ["budget", "SLR"],
      },
      {
        name: "Antarctic ice sheet (EAIS / WAIS)",
        description: "The two-lobed Antarctic ice sheet system.",
        keyFact: "East Antarctic Ice Sheet (~21 million km³) is land-based and currently near balance. West Antarctic Ice Sheet (~2.5 million km³) is marine-grounded and losing mass at ~150 Gt/yr (2010–2020 avg, IMBIE 2020). WAIS includes Thwaites and Pine Island, primary 21st-century SLR concerns.",
        tags: ["Antarctica", "WAIS", "Thwaites"],
      },
      {
        name: "Marine ice sheet instability (MISI)",
        description: "Runaway retreat of marine-grounded ice sheets on reverse-slope beds.",
        keyFact: "Once a grounding line crosses onto a bed that deepens inland, retreat is self-amplifying — flux scales as ~$h^{2-5}$. Identified by Weertman (1974); active concern for Thwaites Glacier, where the bed deepens to ~2,200 m below sea level under the West Antarctic interior.",
        tags: ["MISI", "Thwaites"],
        status: "open",
      },
      {
        name: "Greenland ice sheet",
        description: "Largest ice mass in the Northern Hemisphere.",
        keyFact: "Losing ~270 Gt/yr (2010–2020 mean, IMBIE 2020), contributing ~0.7 mm/yr to SLR. Mass loss is split ~half from surface melt, ~half from dynamic discharge. Holds ~7.4 m of equivalent sea-level rise.",
        tags: ["Greenland", "GIS"],
      },
      {
        name: "Sea ice (Arctic vs Antarctic)",
        description: "Frozen seawater in the polar oceans.",
        keyFact: "Arctic sea-ice extent has declined ~13% per decade in September (1979–2024 trend). Antarctic sea ice was stable to slightly increasing until 2016, then collapsed to ~2 million km² below climatology in 2023. Sea ice has high albedo (~0.5–0.8) vs open ocean (~0.06).",
        tags: ["sea-ice", "albedo"],
        status: "landmark",
      },
      {
        name: "Multi-year vs first-year ice",
        description: "Old, thick ice vs the seasonal regrowth each winter.",
        keyFact: "Arctic Ocean has lost ~75% of its multi-year ice volume since 1979; the winter ice pack is now mostly first-year, thinner (~1–2 m vs 3–5 m), saltier, and more easily broken.",
        tags: ["multi-year", "thinning"],
      },
      {
        name: "Glacier mass balance",
        description: "Annual difference between accumulation and ablation.",
        keyFact: "Mass balance ~accumulation − ablation, normalized as meters water equivalent (m w.e.). World Glacier Monitoring Service reports ~−0.7 m w.e./yr global mean (2015–2024), with ~all reference glaciers losing mass.",
        formula: "B = A - M",
        tags: ["mass-balance", "WGMS"],
      },
      {
        name: "Equilibrium line altitude (ELA)",
        description: "Elevation where annual accumulation equals ablation on a glacier.",
        keyFact: "Above the ELA, net snow accumulates; below, net melt. ELAs have shifted up ~100–300 m on most temperate glaciers since 1980; Glacier National Park (US) is projected to lose all named glaciers by ~2030.",
        tags: ["ELA", "retreat"],
      },
      {
        name: "Ice flow (deformation + sliding)",
        description: "Two mechanisms of ice movement.",
        keyFact: "Slow viscous deformation: Glen's flow law, $\\dot\\varepsilon = A\\tau^n$ with $n \\approx 3$. Basal sliding at the ice-bed interface dominates fast glaciers (~80% of motion). Ice streams in West Antarctica flow at >1,000 m/yr.",
        formula: "\\dot\\varepsilon = A\\tau^n",
        tags: ["flow", "Glen-law"],
      },
      {
        name: "Ice shelves and buttressing",
        description: "Floating extensions of grounded ice sheets.",
        keyFact: "Ice shelves slow the discharge of inland ice by 'buttressing'. Larsen B Ice Shelf disintegrated in 2002 (3,250 km² in weeks); the tributary glaciers sped up 3-8×. Climate concern: thinning shelves around West Antarctica.",
        tags: ["shelves", "Larsen-B"],
        status: "landmark",
      },
      {
        name: "Permafrost",
        description: "Ground that remains below 0 °C for two or more consecutive years.",
        keyFact: "Underlies ~14% of land surface (~22 million km², mostly Arctic). Stores ~1,460–1,600 Pg C — about twice atmospheric carbon. Thawing releases CO₂ and CH₄; northern soils have been a net source since ~2003 (Schuur et al.).",
        tags: ["permafrost", "carbon"],
      },
      {
        name: "Active layer and thermokarst",
        description: "The seasonally thawed top layer of permafrost; collapse features.",
        keyFact: "Active layer ~20–150 cm in continuous permafrost; thickens at ~1 cm/yr today. Thaw produces 'thermokarst' (thaw lakes, slumps, drunken-forest tilting) and abrupt-thaw carbon release.",
        tags: ["active-layer", "thermokarst"],
      },
      {
        name: "Snow water equivalent (SWE)",
        description: "Liquid-water amount in a snowpack.",
        keyFact: "Western US water supply for ~70 million people depends on Sierra Nevada and Rocky Mountain snowpack. Manual snow courses + SNOTEL automated network + airborne lidar (ASO) now quantify peak SWE.",
        tags: ["snow", "SNOTEL"],
      },
      {
        name: "Snowpack and albedo feedback",
        description: "Snow reflects sunlight; melt reduces albedo; warming amplifies.",
        keyFact: "Fresh snow albedo ~0.8–0.9; aged or dirty snow ~0.4–0.6; tundra ~0.15. Snow-albedo feedback amplifies high-latitude warming by ~10–25%. Major contributor to polar amplification.",
        tags: ["albedo", "feedback"],
      },
      {
        name: "Polar amplification",
        description: "Greater warming at the poles than the global mean.",
        keyFact: "Arctic has warmed ~4× faster than global mean since 1979 (Rantanen et al. 2022). Drivers: ice-albedo feedback, lapse-rate feedback, advection. Antarctic amplification much weaker due to circumpolar ocean isolation.",
        tags: ["polar-amp", "Arctic"],
      },
      {
        name: "Subglacial lakes",
        description: "Liquid-water bodies trapped beneath ice sheets.",
        keyFact: "Over 675 catalogued subglacial lakes in Antarctica (Livingstone et al. 2022). Lake Vostok, ~250 km × 50 km, beneath ~4 km of ice, isolated for ~15 Myr; sampled 2012. Network is hydraulically connected and drains episodically.",
        tags: ["subglacial", "Vostok"],
      },
    ],
  },

  // ── Family 5 ──────────────────────────────────────────────────────────────
  {
    slug: "atmospheric-science",
    number: 5,
    name: "Atmospheric Science",
    blurb: "Composition, vertical structure, radiation, and dynamics of Earth's atmosphere.",
    section: "B",
    color: "green",
    entries: [
      {
        name: "Atmospheric composition",
        description: "Major and minor gases in dry air.",
        keyFact: "$\\mathrm{N_2}$ 78.08%, $\\mathrm{O_2}$ 20.95%, Ar 0.93%, $\\mathrm{CO_2}$ ~0.0425% (425 ppm in 2025), Ne, He, Kr, $\\mathrm{CH_4}$ ~1.93 ppm, $\\mathrm{N_2O}$ ~336 ppb, O₃ trace. Variable: $\\mathrm{H_2O}$ 0–4% by volume.",
        xref: ["chemistry"],
        tags: ["composition", "N2", "O2"],
      },
      {
        name: "Atmospheric layers (T-structure)",
        description: "Troposphere–stratosphere–mesosphere–thermosphere by lapse rate sign.",
        keyFact: "Troposphere (0–~12 km, decreasing T); stratosphere (12–50 km, increasing T due to ozone); mesosphere (50–85 km, decreasing); thermosphere (>85 km, increasing). Boundary layers are tropopause, stratopause, mesopause (the coldest, ~−90 °C).",
        tags: ["layers", "troposphere"],
      },
      {
        name: "Hydrostatic balance / scale height",
        description: "Pressure decreases exponentially with altitude.",
        keyFact: "$p(z) = p_0 e^{-z/H}$ with $H = RT/(Mg) \\approx 8.4$ km for Earth. Pressure halves every ~5.6 km. Hydrostatic balance breaks down only for the smallest scales (deep convection, tornado cores).",
        formula: "p(z) = p_0 e^{-z/H}",
        xref: ["physics"],
        tags: ["hydrostatic", "scale-height"],
      },
      {
        name: "Lapse rates (dry adiabatic, moist adiabatic, environmental)",
        description: "Rate of temperature change with altitude under different processes.",
        keyFact: "Dry adiabatic lapse rate: $\\Gamma_d = g/c_p \\approx 9.8\\,\\mathrm{°C/km}$. Moist adiabatic: ~5–6 °C/km (latent heat from condensation). Environmental average: ~6.5 °C/km. Drives atmospheric stability.",
        formula: "\\Gamma_d = g/c_p \\approx 9.8\\,\\mathrm{°C/km}",
        xref: ["physics"],
        tags: ["lapse-rate", "adiabatic"],
      },
      {
        name: "Tropopause",
        description: "Boundary between troposphere and stratosphere.",
        keyFact: "Defined dynamically (potential vorticity ~2 PVU) or thermally (WMO: where lapse rate drops below 2 °C/km). Higher in tropics (~17 km) than poles (~8 km). Sets the 'cold trap' for water vapor.",
        tags: ["tropopause"],
      },
      {
        name: "Earth's radiation balance",
        description: "Energy budget at the top of atmosphere.",
        keyFact: "Solar input ~340 W/m² globally averaged; ~30% reflected (albedo), ~70% absorbed (Earth+atm). Outgoing longwave ~239 W/m². Net imbalance ~0.7–1.0 W/m² (heating) in 2010s–2020s (CERES).",
        formula: "S(1-\\alpha)/4 \\approx \\sigma T_e^4",
        xref: ["physics"],
        tags: ["TOA", "CERES"],
      },
      {
        name: "Greenhouse effect",
        description: "Absorption of outgoing longwave by atmospheric trace gases.",
        keyFact: "Effective radiating temperature 255 K; surface temperature 288 K; the ~33 K gap is the greenhouse effect. Dominant contributors: $\\mathrm{H_2O}$ (~50%), clouds (~25%), $\\mathrm{CO_2}$ (~20%), trace gases (~5%) under unperturbed conditions.",
        formula: "T_s - T_e \\approx 33\\,\\mathrm{K}",
        xref: ["physics", "chemistry"],
        tags: ["greenhouse", "OLR"],
      },
      {
        name: "Stefan-Boltzmann blackbody emission",
        description: "Total radiation emitted by a body scales as $T^4$.",
        keyFact: "$j = \\sigma T^4$ with $\\sigma = 5.67 \\times 10^{-8}\\,\\mathrm{W\\,m^{-2}\\,K^{-4}}$. A 1 °C warmer surface emits ~5 W/m² more longwave. Underlies climate sensitivity calculation.",
        formula: "j = \\sigma T^4",
        xref: ["physics"],
        tags: ["Stefan-Boltzmann"],
      },
      {
        name: "Ozone layer",
        description: "Stratospheric O₃ that absorbs UV-B and UV-C.",
        keyFact: "~90% of atmospheric ozone is in the stratosphere, peaking at ~25 km. Column ~300 Dobson Units (DU) globally average. Chapman cycle (1930) explained natural balance; CFC destruction (Molina-Rowland 1974) led to Montreal Protocol (1987).",
        xref: ["chemistry"],
        tags: ["ozone", "Chapman"],
      },
      {
        name: "Ozone hole",
        description: "Springtime stratospheric ozone depletion over Antarctica.",
        keyFact: "Discovered by Farman et al. (1985), confirmed by Pumphrey/Solomon: heterogeneous chlorine chemistry on polar stratospheric clouds. Hole peaks September–October at <100 DU. Now recovering (~3% per decade); full recovery by ~2066 (WMO Assessment 2022).",
        xref: ["chemistry"],
        tags: ["ozone-hole", "Montreal"],
        status: "resolved",
      },
      {
        name: "Atmospheric general circulation (Hadley/Ferrel/Polar)",
        description: "Three-cell idealization of zonally averaged circulation.",
        keyFact: "Hadley cell (0–30°): rising near equator, descending near ~30° → deserts. Ferrel cell (30–60°): indirect, midlatitude westerlies. Polar cell (60–90°). Real circulation is more complex; jet streams arise from angular-momentum + thermal-wind constraints.",
        tags: ["Hadley", "Ferrel"],
      },
      {
        name: "Jet streams",
        description: "Narrow bands of fast upper-tropospheric wind.",
        keyFact: "Subtropical jet (~30°, ~12 km) from Hadley-cell angular momentum; polar (eddy-driven) jet (~60°, ~9 km). Speeds ~100–250 km/h; meanders steer surface weather. Predicted by thermal-wind equation.",
        tags: ["jets", "thermal-wind"],
      },
      {
        name: "Coriolis effect",
        description: "Apparent force in a rotating reference frame.",
        keyFact: "$f = 2\\Omega \\sin\\phi$. Zero at equator, ~$1.5 \\times 10^{-4}\\,\\mathrm{s^{-1}}$ at poles. Sets the Rossby radius and the rotational stiffness of the atmosphere. Hurricanes cannot form within ~5° of equator.",
        formula: "f = 2\\Omega \\sin\\phi",
        xref: ["physics"],
        tags: ["Coriolis"],
      },
      {
        name: "Geopotential height",
        description: "Height of a pressure surface, weighted by gravity.",
        keyFact: "Used as the primary vertical coordinate on weather maps. 500-hPa height ~5,500 m; ridges and troughs in geopotential surfaces are equivalent to upper-air highs and lows. Geostrophic wind is parallel to height contours.",
        tags: ["geopotential", "synoptic"],
      },
      {
        name: "Quasi-Biennial Oscillation (QBO)",
        description: "~28-month alternation of stratospheric tropical winds.",
        keyFact: "Equatorial stratospheric zonal winds switch between easterly and westerly with period ~28 months, propagating downward at ~1 km/month. Driven by upward-propagating gravity waves. Influences monsoon strength and Atlantic hurricane activity.",
        tags: ["QBO", "stratosphere"],
      },
      {
        name: "Stratospheric sudden warming",
        description: "Mid-winter polar stratospheric warming by ~50 °C in days.",
        keyFact: "Caused by upward-propagating planetary waves disrupting the polar vortex. Major SSW events occur ~6× per decade in Arctic; can cause polar-vortex split or displacement and weeks of cold extremes at mid-latitudes (2018, 2021 US cold waves).",
        tags: ["SSW", "polar-vortex"],
      },
      {
        name: "Atmospheric boundary layer",
        description: "Lowest atmospheric layer directly influenced by the surface.",
        keyFact: "Typical daytime height 1–2 km over land (convective mixing); nighttime nocturnal layer ~100–300 m (stable). Turbulent fluxes of heat, moisture, momentum drive surface-atmosphere coupling.",
        tags: ["PBL", "boundary-layer"],
      },
    ],
  },

  // ── Family 6 ──────────────────────────────────────────────────────────────
  {
    slug: "meteorology",
    number: 6,
    name: "Meteorology",
    blurb: "Weather phenomena, forecasting, and severe-weather dynamics.",
    section: "B",
    color: "lime",
    entries: [
      {
        name: "Air masses",
        description: "Large bodies of air with uniform T and humidity.",
        keyFact: "Classified by source: maritime/continental × tropical/polar/arctic. cP (continental polar) brings dry cold over the US Midwest in winter; mT (maritime tropical) brings Gulf moisture for severe weather. Boundaries are fronts.",
        tags: ["air-masses", "synoptic"],
      },
      {
        name: "Fronts (cold, warm, occluded, stationary)",
        description: "Boundaries between contrasting air masses.",
        keyFact: "Norwegian cyclone model (Bjerknes 1919): cold front overtakes warm front to produce occlusion. Cold fronts: steep, fast (~25 km/h), squall lines. Warm fronts: gentle, slow, stratiform precipitation hundreds of km ahead.",
        tags: ["fronts", "Bjerknes"],
      },
      {
        name: "Mid-latitude cyclones",
        description: "Synoptic-scale low-pressure systems of the Westerlies.",
        keyFact: "Develop on the polar front from baroclinic instability; transport heat poleward and momentum equatorward. Sizes ~1,000–2,000 km; typical lifetime 3–7 days. Dominate weather between ~30° and ~70°.",
        tags: ["cyclones", "baroclinic"],
      },
      {
        name: "Hurricanes / tropical cyclones",
        description: "Warm-core cyclones over tropical oceans.",
        keyFact: "Form over SST ≥ 26.5 °C and low wind shear. Three named basins: Atlantic ('hurricanes'), NW Pacific ('typhoons'), Indian/SH ('cyclones'). Saffir-Simpson Cat 5 ≥ 252 km/h sustained winds. Average ~80 named storms/yr globally.",
        tags: ["hurricane", "Saffir-Simpson"],
      },
      {
        name: "Maximum potential intensity (MPI)",
        description: "Thermodynamic upper bound on tropical-cyclone wind speed.",
        keyFact: "Emanuel (1986) MPI scales with SST and outflow temperature, treating the cyclone as a Carnot heat engine. Global mean MPI rising ~1 m/s per °C SST; record-cat hurricanes more frequent (Hurricane Patricia 2015: 345 km/h).",
        xref: ["physics"],
        tags: ["MPI", "Emanuel"],
      },
      {
        name: "Tornado",
        description: "Rotating column of air in contact with ground and parent cloud.",
        keyFact: "EF-scale (2007) replaces Fujita scale; EF5 winds >322 km/h. US averages ~1,200 tornadoes/yr — most of any country. \"Tornado Alley\" linked to dryline + Great Plains low-level jet + Gulf moisture.",
        tags: ["tornado", "EF-scale"],
      },
      {
        name: "Supercell thunderstorm",
        description: "Rotating-updraft thunderstorm responsible for most strong tornadoes.",
        keyFact: "Defined by a mesocyclone — a persistent 2–10 km rotating updraft visible on Doppler radar. Requires deep moisture, strong instability, and vertical wind shear (~20 m/s 0–6 km).",
        tags: ["supercell", "mesocyclone"],
      },
      {
        name: "Convective available potential energy (CAPE)",
        description: "Integrated buoyancy a parcel would experience rising through the atmosphere.",
        keyFact: "$\\mathrm{CAPE} = \\int (g \\Delta T / T_\\mathrm{env}) dz$. ~500 J/kg = ordinary thunderstorm; 2,500–4,000 J/kg = severe; >5,000 J/kg = extreme. A key forecaster diagnostic.",
        formula: "\\mathrm{CAPE} = \\int_{LFC}^{EL} g\\frac{T_p - T_e}{T_e} dz",
        tags: ["CAPE", "instability"],
      },
      {
        name: "Lightning",
        description: "Electrical discharge in or from a thunderstorm.",
        keyFact: "~44 strikes/second globally (~1.4 billion/yr; Lightning Imaging Sensor). Peak current ~30 kA, channel temperature ~30,000 K. Lake Maracaibo (Venezuela) is the densest lightning area on Earth (~233 flashes/km²/yr).",
        xref: ["physics"],
        tags: ["lightning", "discharge"],
      },
      {
        name: "Precipitation types and microphysics",
        description: "How rain, snow, sleet, hail, and graupel form.",
        keyFact: "Bergeron-Findeisen process: ice crystals grow at expense of supercooled droplets (most cold-cloud rain begins as ice). Warm-rain coalescence dominates tropics. Hail requires strong updraft (~25 m/s) to sustain growth.",
        xref: ["chemistry"],
        tags: ["microphysics", "Bergeron"],
      },
      {
        name: "Numerical weather prediction (NWP)",
        description: "Forecasting weather by integrating the primitive equations.",
        keyFact: "ECMWF IFS, NOAA GFS, UKMO UM are the leading global models. Resolution ~9–13 km (2025). Skillful range: ~10 days for synoptic patterns; lengthening by ~1 day/decade since 1980. ECMWF AIFS (transformer-based) matches IFS at 1/10,000 the compute.",
        tags: ["NWP", "ECMWF"],
      },
      {
        name: "Ensemble forecasting",
        description: "Running many slightly perturbed forecasts to estimate uncertainty.",
        keyFact: "Pioneered by ECMWF (1992); typical ensemble has 50 members. Spread quantifies forecast uncertainty; ensemble mean reduces error vs deterministic at long lead times. Underlies probabilistic warnings.",
        xref: ["statistics"],
        tags: ["ensemble", "uncertainty"],
      },
      {
        name: "Data assimilation (4D-Var, EnKF)",
        description: "Combining observations and model background into best estimate.",
        keyFact: "ECMWF uses 4D-Var (four-dimensional variational), NOAA GFS uses hybrid 4D-EnVar. Assimilates ~10⁹ observations/day, ~95% from satellites. The accuracy floor of NWP.",
        xref: ["statistics"],
        tags: ["DA", "4DVar"],
      },
      {
        name: "Radar (Doppler weather radar)",
        description: "Microwave radar for precipitation, wind, and storm structure.",
        keyFact: "WSR-88D NEXRAD network (1990s): S-band (~10 cm), Doppler velocity, dual-polarization since 2013. Detects mesocyclone rotation 10–30 min before tornado touchdown — basis for modern tornado warnings.",
        tags: ["radar", "NEXRAD"],
      },
      {
        name: "Weather satellites",
        description: "Geostationary and polar-orbiting satellites for atmospheric monitoring.",
        keyFact: "GOES (US), Himawari (Japan), Meteosat (Europe), FY (China) at geostationary orbit (~35,786 km) for hemispheric imagery every ~10 minutes. Polar orbiters (Suomi NPP, JPSS, MetOp) for global twice-daily sounding.",
        xref: ["astronomy"],
        tags: ["satellites", "GOES"],
      },
      {
        name: "Atmospheric river",
        description: "Long narrow bands of intense water-vapor transport.",
        keyFact: "Carry ~7–15× the discharge of the Mississippi River. \"Pineapple Express\" delivers ~30–50% of US West Coast cool-season precipitation. Identified by Ralph et al. (1998) using SSM/I-derived integrated water vapor.",
        tags: ["AR", "Pineapple-Express"],
      },
      {
        name: "Saffir-Simpson scale",
        description: "Five-category classification of hurricane wind intensity.",
        keyFact: "Categories by 1-minute sustained winds: Cat 1 119–153, Cat 2 154–177, Cat 3 178–208, Cat 4 209–251, Cat 5 ≥252 km/h. Storm-surge dropped from the scale in 2009; surge depends more on size and bathymetry than wind.",
        tags: ["Saffir-Simpson"],
      },
    ],
  },
];
