import type { Family } from "./types";

export const FAMILIES_13_18: Family[] = [
  // ── Family 13 ─────────────────────────────────────────────────────────────
  {
    slug: "biogeochemistry",
    number: 13,
    name: "Biogeochemistry",
    blurb: "Cycles of carbon, nitrogen, phosphorus, sulfur, and water linking Earth's spheres.",
    section: "D",
    color: "green",
    entries: [
      {
        name: "Global carbon cycle",
        description: "Stocks and flows of C across atmosphere, ocean, biosphere, lithosphere.",
        keyFact: "Atmospheric stock ~890 Gt C (~425 ppm × 2.13 Gt C/ppm); ocean DIC ~38,000 Gt; soil ~1,500–2,400 Gt; vegetation ~450 Gt; fossil fuel reserves ~5,000+ Gt. Net anthropogenic emissions: ~10.5 Gt C/yr (2020s).",
        formula: "1\\,\\mathrm{ppm\\,CO_2} \\approx 2.13\\,\\mathrm{Gt\\,C}",
        xref: ["chemistry", "biology"],
        tags: ["C-cycle", "stocks"],
      },
      {
        name: "Photosynthesis (global)",
        description: "Biospheric CO₂ fixation by primary producers.",
        keyFact: "Gross Primary Production ~120 Gt C/yr globally — ~60 land, ~60 ocean. Net primary production ~50–60 Gt C/yr. ~50% of GPP is rapidly respired by plants.",
        formula: "\\mathrm{6CO_2 + 6H_2O \\rightarrow C_6H_{12}O_6 + 6O_2}",
        xref: ["biology", "chemistry"],
        tags: ["GPP", "NPP"],
      },
      {
        name: "Respiration (autotrophic + heterotrophic)",
        description: "Biospheric CO₂ release by decomposition and metabolism.",
        keyFact: "Soil respiration ~98 Gt C/yr globally — among the largest land-atmosphere flux. Highly temperature-sensitive ($Q_{10} \\approx 2$); accelerating soil respiration is a key climate-carbon feedback.",
        xref: ["biology", "chemistry"],
        tags: ["respiration", "Q10"],
      },
      {
        name: "Anthropogenic CO₂ emissions",
        description: "Fossil fuel + cement + land-use carbon flux.",
        keyFact: "2024 fossil + cement ~37 Gt CO₂ ≈ 10.2 Gt C; land-use change ~1.1 Gt C. Cumulative ~720 Gt C since 1750 (Global Carbon Budget 2024). Drives the ongoing CO₂ rise.",
        tags: ["emissions", "GCB"],
      },
      {
        name: "Airborne fraction",
        description: "Share of emitted CO₂ remaining in the atmosphere.",
        keyFact: "~44% of fossil-fuel emissions stay in the atmosphere (decade avg). The remainder is split ~26% ocean, ~30% land sinks. Airborne fraction has held roughly constant despite growing emissions — but stability depends on sinks not weakening.",
        tags: ["airborne-fraction"],
      },
      {
        name: "Nitrogen cycle",
        description: "N₂ fixation, nitrification, denitrification, and human inputs.",
        keyFact: "Pre-industrial natural N fixation ~58 Tg N/yr terrestrial + ~140 Tg N/yr marine. Anthropogenic fixation (Haber-Bosch + leguminous crops + combustion) ~210 Tg N/yr — nearly doubling the natural rate. Drives eutrophication, N₂O emissions.",
        formula: "\\mathrm{N_2 + 3H_2 \\rightarrow 2NH_3}",
        xref: ["chemistry", "biology"],
        tags: ["N-cycle", "Haber-Bosch"],
        status: "landmark",
      },
      {
        name: "Haber-Bosch industrial fixation",
        description: "Industrial conversion of N₂ to NH₃ for fertilizer.",
        keyFact: "Haber (1908), Bosch industrialization (1913). Now fixes ~150 Tg N/yr, supports food for ~50% of world population. Major energy use: ~1–2% of global natural gas.",
        xref: ["chemistry"],
        tags: ["Haber-Bosch"],
      },
      {
        name: "Phosphorus cycle",
        description: "Slow geochemical cycle with no significant gaseous phase.",
        keyFact: "P enters the biosphere via rock weathering (~0.02 Tg P/yr natural) and via mining of phosphate rock (~22 Tg P/yr). Eventually lost to ocean sediments. Anthropogenic mobilization >~3× natural; \"peak P\" concerns and Morocco's 70% reserve share are geopolitically sensitive.",
        xref: ["chemistry"],
        tags: ["P-cycle"],
      },
      {
        name: "Sulfur cycle",
        description: "Volcanic + marine biogenic + anthropogenic S fluxes.",
        keyFact: "Volcanic SO₂ ~10 Tg S/yr; oceanic DMS ~20 Tg S/yr; anthropogenic ~70 Tg S/yr (peak ~1980), now declining as SO₂ emissions are controlled. SO₂ → sulfate aerosol → climate cooling; also acid rain.",
        xref: ["chemistry"],
        tags: ["S-cycle", "SO2"],
      },
      {
        name: "Methane budget",
        description: "Sources and sinks of atmospheric CH₄.",
        keyFact: "~570 Tg CH₄/yr total flux: ~60% anthropogenic (fossil fuels, agriculture, waste), ~40% natural (wetlands, geological). Sink dominated by OH oxidation in troposphere. Atmospheric CH₄ ~1.93 ppm in 2024, up >2× preindustrial.",
        xref: ["chemistry"],
        tags: ["CH4", "wetlands"],
      },
      {
        name: "Nitrous oxide (N₂O)",
        description: "Long-lived GHG and ozone-depleting substance.",
        keyFact: "Atmospheric N₂O ~336 ppb in 2024, up from ~270 ppb preindustrial. Sources: agricultural soils, oceans, biomass burning. Now the dominant ozone-depleting substance emitted by humans, given CFC controls. Lifetime ~120 yr.",
        xref: ["chemistry"],
        tags: ["N2O"],
      },
      {
        name: "Land carbon sink",
        description: "Terrestrial biosphere's net uptake of anthropogenic CO₂.",
        keyFact: "~3.0 Gt C/yr (2010s, GCB 2024). Driven by CO₂ fertilization, N deposition, longer growing seasons; partly offset by land-use change, fire, drought. Spatial pattern: temperate and boreal forests dominate.",
        xref: ["biology"],
        tags: ["land-sink"],
      },
      {
        name: "Ocean carbon sink",
        description: "Ocean's net uptake of anthropogenic CO₂.",
        keyFact: "~2.8 Gt C/yr (2010s avg). Slowing per unit increase in atmospheric CO₂ as the Revelle factor rises and the surface ocean acidifies. Southern Ocean dominates the sink, but interannual variability is large.",
        xref: ["chemistry"],
        tags: ["ocean-sink"],
      },
      {
        name: "Water cycle linkages",
        description: "Coupling between water cycle and biogeochemical cycles.",
        keyFact: "Evapotranspiration moves ~63% of land precipitation; rivers transport ~0.5 Gt C/yr from land to ocean (mainly DIC + DOC). Damming and irrigation now control ~50% of global river flow.",
        tags: ["water", "DIC"],
      },
      {
        name: "Cosmogenic isotopes (¹⁰Be, ¹⁴C, ³⁶Cl)",
        description: "Isotopes produced by cosmic-ray interaction in the upper atmosphere.",
        keyFact: "¹⁴C used to date organic carbon to ~50,000 yr (half-life 5,730 yr). ¹⁰Be (1.4 Myr) used for surface exposure dating and ice-core solar-activity reconstruction. Independent calibrations of geochronology.",
        xref: ["chemistry", "astronomy"],
        tags: ["cosmogenic", "C14"],
      },
      {
        name: "Mercury cycle",
        description: "Anthropogenic mobilization of Hg through atmosphere and biosphere.",
        keyFact: "Atmospheric Hg burden ~5,000 Mg; anthropogenic emissions ~2,200 Mg/yr (coal, ASGM). Methylmercury bioaccumulates in marine food webs. Minamata Convention (2013) limits emissions.",
        xref: ["chemistry"],
        tags: ["mercury", "Minamata"],
      },
      {
        name: "Iron cycle (terrestrial-marine)",
        description: "Wind-borne Fe input to remote oceans.",
        keyFact: "Saharan dust delivers ~70 Tg/yr of mineral aerosol — supplies Fe to oligotrophic Atlantic, fertilizes Amazon. Patagonian dust drives Southern Ocean productivity. Glacial dust fluxes were ~10× modern, possibly contributing to glacial CO₂ drawdown.",
        xref: ["chemistry"],
        tags: ["dust", "iron"],
      },
    ],
  },

  // ── Family 14 ─────────────────────────────────────────────────────────────
  {
    slug: "earth-system-science",
    number: 14,
    name: "Earth System Science",
    blurb: "Coupled-system thinking — feedbacks, tipping points, planetary boundaries, Gaia.",
    section: "D",
    color: "teal",
    entries: [
      {
        name: "Earth system",
        description: "Atmosphere + hydrosphere + cryosphere + biosphere + lithosphere as one coupled system.",
        keyFact: "Bretherton diagram (NASA 1986) is the canonical sketch. Earth-system science studies these subsystems as a single integrated unit, with feedbacks across all spheres on timescales from seconds to billions of years.",
        tags: ["Earth-system", "Bretherton"],
      },
      {
        name: "Gaia hypothesis",
        description: "Lovelock and Margulis's claim that biota regulate planetary habitability.",
        keyFact: "Lovelock & Margulis (1974): the biosphere actively maintains Earth's climate and chemistry in a habitable range. Empirical core (biota substantially shape Earth's chemistry) is uncontroversial; teleological 'strong Gaia' (regulation is purposive) is widely rejected.",
        xref: ["biology"],
        tags: ["Gaia"],
        status: "open",
      },
      {
        name: "Daisyworld",
        description: "Simple model of biotic temperature regulation.",
        keyFact: "Watson & Lovelock (1983): white and black daisies adjusting their populations buffer planetary temperature against a brightening star. Toy model that operationalizes 'Gaia' without invoking purpose.",
        tags: ["Daisyworld"],
      },
      {
        name: "Planetary boundaries",
        description: "Rockström/Steffen framework of safe operating zones.",
        keyFact: "Nine boundaries proposed in Rockström et al. (2009): climate, biosphere integrity, biogeochemical flows (N, P), land-system change, freshwater, ocean acidification, atmospheric aerosols, ozone, novel entities. Six of nine assessed as transgressed in Richardson et al. 2023 update.",
        tags: ["planetary-boundaries"],
        status: "landmark",
      },
      {
        name: "Climate tipping points",
        description: "Thresholds beyond which subsystems undergo qualitative shift.",
        keyFact: "Armstrong McKay et al. (2022): 16 tipping elements identified; 9 (incl. WAIS, Greenland, AMOC, Amazon, boreal forests, permafrost) may be at risk at 1.5–2 °C global warming. Cascades among them are possible but quantitatively uncertain.",
        tags: ["tipping-points"],
        status: "open",
      },
      {
        name: "Hothouse Earth pathway",
        description: "Steffen et al. (2018) scenario of cascading tipping.",
        keyFact: "Argued ~2 °C warming could trigger cascade through Earth-system tipping elements leading to ~4–5 °C stabilization regardless of further emissions. Speculative — debated mechanism and probability, but cited as motivation for limiting peak warming.",
        tags: ["Hothouse"],
        status: "open",
      },
      {
        name: "Anthropocene",
        description: "Proposed epoch defined by human impact on Earth systems.",
        keyFact: "Crutzen & Stoermer (2000) coined; Anthropocene Working Group recommended formal recognition with a 1952 GSSP at Crawford Lake (plutonium fallout signature). IUGS executive rejected formal proposal in March 2024 — 'Anthropocene' remains widely used informally.",
        xref: ["geology"],
        tags: ["Anthropocene"],
        status: "refuted",
      },
      {
        name: "Faint young Sun paradox",
        description: "Sun was ~25–30% dimmer in early Earth; how was Earth not frozen?",
        keyFact: "Sagan & Mullen (1972). Geological evidence shows liquid water on Earth ≥3.8 Ga. Resolutions: high CO₂/CH₄ greenhouse, lower albedo, geothermal heating. Still no single accepted solution.",
        xref: ["astronomy"],
        tags: ["FYSP"],
        status: "open",
      },
      {
        name: "Habitability zone (planetary)",
        description: "Range of orbital distance and conditions for liquid surface water.",
        keyFact: "Kasting et al. (1993). Sun's habitable zone today: ~0.95–1.67 AU (Venus is too close, Mars marginal). Galactic-scale habitable zone discussion factors in metallicity gradient + supernova rate.",
        xref: ["astronomy"],
        tags: ["habitable-zone"],
      },
      {
        name: "Biogeochemical feedbacks (Le Quéré summary)",
        description: "Couplings linking warming, sinks, and emissions.",
        keyFact: "Climate-carbon feedback ~−15 to −25% of cumulative emissions remain in air with feedbacks. Concentration-carbon feedback ~+0.30 W/m²/K for CO₂. Two largest unknowns in 21st-century projections.",
        tags: ["feedbacks", "C-cycle"],
      },
      {
        name: "Climate-vegetation coupling",
        description: "Two-way feedbacks between vegetation and climate.",
        keyFact: "Sahara greening at mid-Holocene amplified by vegetation-albedo feedback (Claussen et al. 1999). Boreal forest reduces albedo — net warming. Amazon tipping (drying → savannization) hypothesized at ~25–40% deforestation.",
        xref: ["biology"],
        tags: ["vegetation"],
      },
      {
        name: "Earth-system models (ESMs)",
        description: "GCMs coupled with interactive carbon, vegetation, atmospheric chemistry.",
        keyFact: "CMIP6 includes ~30 ESMs feeding IPCC AR6 (2021). Resolution typically ~100 km; some run at ~25 km. Newer ICON-A, IFS-FESOM, X-SHiELD prototype km-scale global modeling.",
        tags: ["ESM", "CMIP6"],
      },
      {
        name: "Pleistocene-Holocene transition",
        description: "End of last glacial and onset of stable interglacial.",
        keyFact: "Glacial-interglacial transition ~17.5–11.7 ka. Holocene climate has been unusually stable — sub-±1 °C global variability for 10,000 years, enabling agriculture and civilizations.",
        tags: ["Holocene"],
      },
      {
        name: "Snowball Earth as Earth-system experiment",
        description: "Test case for Earth-system runaway and recovery.",
        keyFact: "Hard Snowball events (~717–660 Ma, ~650–635 Ma) document Earth-system bistability — once ice cover reaches ~30° latitude, ice-albedo feedback may glaciate the whole planet. Recovery via volcanic CO₂ accumulation in ~10⁶ years.",
        xref: ["geology"],
        tags: ["Snowball-Earth"],
        status: "open",
      },
      {
        name: "Coupling indices (ENSO, NAO, ITCZ)",
        description: "Reduced-dimension descriptions of coupled dynamics.",
        keyFact: "Niño 3.4 SST, NAO PC, Sahel rainfall, AMO index — these scalar summaries collapse high-dimensional climate into tractable predictors. The price: missing extremes and regime changes outside the index basis.",
        tags: ["indices", "NAO"],
      },
      {
        name: "Mass extinctions and Earth-system stress",
        description: "Big-five extinctions and their drivers.",
        keyFact: "Ordovician-Silurian (~445 Ma), Late Devonian (~370), Permian-Triassic (~252, ~95% marine species lost — Siberian Traps + ocean anoxia), Triassic-Jurassic (~201), Cretaceous-Paleogene (~66, Chicxulub impact + Deccan Traps).",
        xref: ["biology", "geology"],
        tags: ["extinctions"],
      },
      {
        name: "Habitability of the deep future",
        description: "End-state habitability under rising solar luminosity.",
        keyFact: "Sun brightens ~10%/Gyr. CO₂ weathering can buffer ~600 Myr; then moist greenhouse → runaway by ~1 Gyr. Caldeira & Kasting (1992) classic. Earth becomes uninhabitable for animal life within a few hundred Myr without intervention.",
        xref: ["astronomy"],
        tags: ["deep-future"],
      },
    ],
  },

  // ── Family 15 ─────────────────────────────────────────────────────────────
  {
    slug: "remote-sensing-geodesy",
    number: 15,
    name: "Remote Sensing & Geodesy",
    blurb: "Satellites, GPS, radar interferometry, lidar, and gravity surveys.",
    section: "D",
    color: "indigo",
    entries: [
      {
        name: "Geodesy reference frames",
        description: "Ellipsoid + geoid + datum systems.",
        keyFact: "WGS-84 (used by GPS) and ITRF (International Terrestrial Reference Frame, updated every few years) are the principal global references. Geoid undulations up to ±110 m relative to the ellipsoid.",
        tags: ["WGS84", "ITRF"],
      },
      {
        name: "GPS / GNSS",
        description: "Global navigation satellite systems.",
        keyFact: "GPS (US, 31 sats), GLONASS (Russia), Galileo (EU), BeiDou (China). Position fix needs ~4 satellites. Precision: ~3 m absolute (single-frequency); ~1 cm with PPP/RTK; ~1 mm with continuous-time multi-year solutions.",
        tags: ["GNSS", "GPS"],
      },
      {
        name: "InSAR (interferometric SAR)",
        description: "Synthetic aperture radar interferometry for ground deformation.",
        keyFact: "Compares phase of two radar passes to detect mm-scale surface motion. Sentinel-1 (ESA, 2014–) gives global 6–12 day repeat. Used for earthquakes, volcanoes, landslides, subsidence, ice flow.",
        xref: ["physics"],
        tags: ["InSAR", "Sentinel-1"],
      },
      {
        name: "Lidar (airborne and spaceborne)",
        description: "Laser ranging for topography, vegetation, and ice thickness.",
        keyFact: "Airborne lidar 0.1–1 m vertical accuracy; covers ~100 km²/hr. Spaceborne: ICESat-2 (ATLAS, 2018–) for ice; GEDI (ISS, 2018–) for canopy. Lidar bare-earth DEMs revealed buried Maya cities (Cihuatán, Caracol).",
        tags: ["lidar", "ICESat-2"],
      },
      {
        name: "Multispectral imaging (Landsat)",
        description: "Earth-imaging program with the longest record.",
        keyFact: "Landsat 1 (1972) to Landsat 9 (2021). 30 m resolution, 16-day repeat. Free since 2008 — revolutionized global land-cover monitoring. >10 PB archive at USGS EROS Data Center.",
        tags: ["Landsat", "multispectral"],
      },
      {
        name: "Sentinel constellation",
        description: "ESA Copernicus operational Earth observation.",
        keyFact: "Sentinel-1 (SAR), -2 (multispectral, 10 m), -3 (ocean), -5P (atmosphere). Free and open data. Sentinel-2 has 5-day repeat globally — global high-frequency optical imaging.",
        tags: ["Sentinel", "Copernicus"],
      },
      {
        name: "GRACE / GRACE-FO time-variable gravity",
        description: "Twin-satellite gravity-change measurement.",
        keyFact: "Range-rate between two satellites measured to ~1 µm/s; monthly gravity fields at ~300 km resolution. Quantified ice-sheet mass loss, groundwater depletion (CA Central Valley, North China Plain), tsunami fingerprints.",
        tags: ["GRACE"],
      },
      {
        name: "Satellite altimetry (sea level)",
        description: "Radar altimeters measuring sea-surface height.",
        keyFact: "TOPEX/Poseidon (1992) launched the era; Jason-1/2/3, Sentinel-6 continue. Mean sea level rising ~3.4 mm/yr (1993–2024), accelerating ~0.08 mm/yr². ~30% from ocean thermal expansion, ~70% from ice and glacier mass.",
        tags: ["altimetry", "Jason"],
      },
      {
        name: "Cloud and Earth's Radiant Energy System (CERES)",
        description: "Top-of-atmosphere radiative-flux measurement.",
        keyFact: "On Terra, Aqua, S-NPP, NOAA-20. Resolves shortwave and longwave; ground truth for radiation budget. CERES showed Earth's energy imbalance ~0.5 W/m² (2000s) → ~1.0 W/m² (2020s).",
        tags: ["CERES", "TOA"],
      },
      {
        name: "MODIS / VIIRS",
        description: "Moderate-resolution imaging spectroradiometers.",
        keyFact: "MODIS on Terra (1999) and Aqua (2002) revolutionized daily global observation: NDVI, fires, SST, clouds, aerosols. VIIRS continues the record on Suomi NPP (2011) and JPSS.",
        tags: ["MODIS", "VIIRS"],
      },
      {
        name: "Argo + jason coupled ocean observing",
        description: "Global ocean-monitoring system.",
        keyFact: "Combining Argo profiling floats (T, S) and Jason altimetry produces closed sea-level budget (steric + mass agreement). The two systems are the cornerstones of modern ocean climate monitoring.",
        tags: ["Argo", "Jason"],
      },
      {
        name: "Atmospheric sounding (IR, microwave)",
        description: "Vertical temperature and humidity retrieval from satellites.",
        keyFact: "AIRS, IASI, CrIS hyperspectral IR sounders + AMSU/ATMS microwave units provide ~1 K T accuracy and ~30% humidity precision. The dominant satellite data source for NWP data assimilation.",
        tags: ["sounding", "AIRS"],
      },
      {
        name: "GNSS radio occultation",
        description: "Atmospheric refractivity from GPS signal bending.",
        keyFact: "COSMIC, Spire constellations measure GNSS signals as they graze atmosphere — ~1 km vertical resolution profiles. High value for NWP — climate-quality reference for temperature trends.",
        tags: ["RO", "COSMIC"],
      },
      {
        name: "GIS (Geographic Information Systems)",
        description: "Spatial-data computing infrastructure.",
        keyFact: "Vector + raster + topology models; standards: OGC, OpenLayers, GeoJSON. PostGIS (PostgreSQL extension) and QGIS now power most public-sector and research workflows.",
        tags: ["GIS", "PostGIS"],
      },
      {
        name: "Digital elevation models (DEMs)",
        description: "Gridded elevation datasets.",
        keyFact: "SRTM (2000, 30 m, between 60° N/S); ASTER GDEM (30 m global); TanDEM-X (12 m global); ArcticDEM (2 m). DEM choice can change flood-risk estimates by orders of magnitude.",
        tags: ["DEM", "SRTM"],
      },
      {
        name: "Earth observation data systems",
        description: "Modern cloud-based geospatial archives.",
        keyFact: "Google Earth Engine, AWS Open Data, Planetary Computer host Landsat/Sentinel/etc. with petabyte-scale compute. Removed the data-distribution bottleneck — now the dominant platform for global-scale analysis.",
        tags: ["GEE", "cloud"],
      },
      {
        name: "Tide gauges",
        description: "Long-record coastal sea-level monitoring.",
        keyFact: "GLOSS network ~290 stations. Some records >150 yr (Stockholm 1774, Brest 1807). Land motion (GIA, subsidence) must be corrected. Tide gauges + satellite altimetry together close the global sea-level budget.",
        tags: ["tide-gauges", "GLOSS"],
      },
    ],
  },

  // ── Family 16 ─────────────────────────────────────────────────────────────
  {
    slug: "natural-hazards",
    number: 16,
    name: "Natural Hazards",
    blurb: "Tropical cyclones, floods, droughts, wildfires, landslides — physical hazard science.",
    section: "E",
    color: "rose",
    entries: [
      {
        name: "Tropical cyclone risk and storm surge",
        description: "Wind, surge, and inland-flood hazards from tropical cyclones.",
        keyFact: "Storm surge causes most US hurricane fatalities (~50%). Surge depends on wind speed, size, bathymetry, forward speed, and tide stage. Hurricane Katrina (2005) surge ~8.5 m at Bay St. Louis MS; Bhola cyclone (1970) killed ~300–500k in Bangladesh.",
        tags: ["surge", "tropical-cyclone"],
      },
      {
        name: "Flood typology",
        description: "Riverine, flash, urban, coastal, ice-jam floods.",
        keyFact: "Riverine: slow days-scale rise from upstream precipitation. Flash floods: <6 h, deadliest per km². Urban: impervious-surface runoff. Coastal: surge + tide + waves. Ice-jam: spring breakup. Compound events combine multiple.",
        tags: ["floods", "flash"],
      },
      {
        name: "Drought (meteorological, agricultural, hydrological)",
        description: "Time-integrated water-deficit hazards.",
        keyFact: "Meteorological: low precipitation; agricultural: low soil moisture; hydrological: low streamflow/storage. Compounding: drought + heat (megadrought + heatwave amplifies wildfire). US Southwest 2000–2024 is the driest 25-year period in >1,200 yr (Williams et al. 2022).",
        tags: ["drought", "megadrought"],
      },
      {
        name: "Heatwaves and humid heat",
        description: "Extreme high-temperature periods, sometimes with humidity.",
        keyFact: "Wet-bulb temperature ~35 °C is the physiological human tolerance limit (Sherwood & Huber 2010). Brief excursions already observed in Persian Gulf, Sind. 2003 European heatwave killed ~70,000; 2010 Russia ~55,000; 2021 PNW ~600+.",
        tags: ["heatwave", "wet-bulb"],
      },
      {
        name: "Wildfire and fire weather",
        description: "Vegetation-fueled fires driven by drought, wind, heat.",
        keyFact: "Fosberg Fire Weather Index, Canadian FWI, Hot Dry Windy. Western US burned area has quadrupled since the 1980s (Abatzoglou & Williams 2016) — ~half attributable to anthropogenic warming. Australia 2019–20 burned ~24 million ha.",
        tags: ["wildfire", "FWI"],
      },
      {
        name: "Pyrocumulonimbus and fire-generated weather",
        description: "Convective storms induced by intense wildfires.",
        keyFact: "Strong fires generate pyrocumulus and pyrocumulonimbus (PyroCb) clouds — inject smoke into stratosphere. Australia 2019–20 fires (\"Black Summer\") injected ~1 Mt aerosol into stratosphere, larger than many volcanic eruptions.",
        tags: ["PyroCb"],
      },
      {
        name: "Earthquake hazard and risk",
        description: "Ground-motion hazard from active faults.",
        keyFact: "Hazard = probability × intensity. Probabilistic Seismic Hazard Analysis (PSHA) produces shaking-probability maps for building codes. UCERF3 model (CA, 2014): ~99% chance of M ≥ 6.7 within 30 yr; ~30% chance of M ≥ 7.5.",
        xref: ["geology", "statistics"],
        tags: ["PSHA", "UCERF"],
      },
      {
        name: "Tsunami",
        description: "Ocean wave from earthquake, landslide, or volcanic source.",
        keyFact: "2004 Indian Ocean tsunami (Mw 9.1–9.3, Sumatra-Andaman) killed ~230,000. 2011 Tōhoku (Mw 9.1, Japan) killed ~19,000 + Fukushima nuclear accident. Tsunamis propagate at $\\sqrt{gd} \\approx 200$ m/s in 4-km ocean.",
        formula: "c = \\sqrt{gd}",
        xref: ["physics"],
        tags: ["tsunami"],
      },
      {
        name: "Volcanic hazard",
        description: "Pyroclastic flows, lahars, ashfall, lava.",
        keyFact: "Pyroclastic density currents (~700 °C, ~300 km/h) most lethal — Mt. Pelée 1902 killed ~30,000. Lahars (Nevado del Ruiz 1985: ~23,000). VEI 6+ eruptions every ~50–100 yr; VEI 7+ every ~500–1,000 yr (Tambora 1815 caused 'year without a summer').",
        xref: ["geology"],
        tags: ["volcano", "VEI"],
      },
      {
        name: "Landslides and slope stability",
        description: "Gravity-driven mass movements.",
        keyFact: "Triggered by rainfall, earthquakes, volcanic eruptions, freeze-thaw. Vajont Dam landslide (1963, Italy): 270 million m³ into reservoir, 50 m wave killed ~2,000. Climate-driven permafrost thaw and rainfall increase are increasing high-mountain landslide hazards.",
        xref: ["geology"],
        tags: ["landslide", "Vajont"],
      },
      {
        name: "Sinkholes and karst hazards",
        description: "Subsidence and collapse over soluble bedrock.",
        keyFact: "Carbonate dissolution forms voids; collapse types: cover-collapse (sudden), cover-subsidence (slow). Florida, Kentucky, central Mexico (Yucatán cenotes) — major karst regions. Anthropogenic acceleration via groundwater pumping.",
        xref: ["geology"],
        tags: ["karst", "sinkholes"],
      },
      {
        name: "Space weather hazards",
        description: "Geomagnetic storms threatening grids and satellites.",
        keyFact: "Carrington Event (1859): largest in instrumental era — telegraph systems failed, equatorial auroras. Modern equivalent could cause ~$2 T damage from collapsed grid transformers (Lloyd's 2013). Quebec 1989 blackout: ~9-hour failure.",
        xref: ["physics", "astronomy"],
        tags: ["Carrington", "space-weather"],
      },
      {
        name: "Coastal erosion",
        description: "Shoreline retreat from waves, storms, sea-level rise.",
        keyFact: "Global beaches retreating ~28 cm/yr median (Mentaschi et al. 2018). Outer Banks NC retreat ~2 m/yr; Bangladesh delta 1.5–6 m/yr. Hard armoring (seawalls) reduces sediment supply downdrift.",
        xref: ["geology"],
        tags: ["erosion"],
      },
      {
        name: "Compound events",
        description: "Co-occurring or interacting hazards.",
        keyFact: "Examples: drought + heatwave → wildfire; storm surge + heavy rainfall → coastal flooding; sequential hurricanes (Eta + Iota, Central America 2020). Risk often underestimated when hazards are treated as independent.",
        xref: ["statistics"],
        tags: ["compound"],
      },
      {
        name: "Multi-hazard risk frameworks",
        description: "Integrated approaches across multiple natural hazards.",
        keyFact: "UNDRR Sendai Framework (2015) replaced Hyogo. GAR Global Assessment Report quantifies global average annual loss ~$0.5 trillion/yr from major hazards. Risk = hazard × exposure × vulnerability.",
        tags: ["Sendai", "GAR"],
      },
      {
        name: "Loss of life and damage trends",
        description: "Disaster mortality and damage time series.",
        keyFact: "Despite rising exposure, disaster mortality has declined ~10× since 1900 due to early warning + infrastructure. Economic damage has risen at ~5% real/yr — outpacing GDP — reflecting more assets in hazardous zones.",
        tags: ["EM-DAT", "loss"],
      },
      {
        name: "Early-warning systems",
        description: "Detection and dissemination of imminent hazard signals.",
        keyFact: "Bangladesh cyclone-warning + shelters reduced mortality from ~300,000 in 1970 to ~3,000 in similar 2020 storm. Tsunami warning networks (PTWC, NTWC) save lives in some basins; gaps in Indian Ocean exposed by 2004.",
        tags: ["EWS"],
      },
    ],
  },

  // ── Family 17 ─────────────────────────────────────────────────────────────
  {
    slug: "climate-change-science",
    number: 17,
    name: "Climate Change Science",
    blurb: "Anthropogenic warming — detection, attribution, projections, mitigation, adaptation.",
    section: "E",
    color: "amber",
    entries: [
      {
        name: "Global mean surface temperature record",
        description: "Instrumental record of Earth's surface temperature.",
        keyFact: "HadCRUT5, GISTEMP, NOAAGlobalTemp, Berkeley Earth all show ~1.3 °C warming since pre-industrial through 2024. 2024 was the first calendar year >1.5 °C in monthly running mean (Copernicus C3S).",
        xref: ["statistics"],
        tags: ["GMST", "HadCRUT"],
        status: "landmark",
      },
      {
        name: "Anthropogenic attribution",
        description: "Detection and attribution of observed warming to humans.",
        keyFact: "Hegerl et al. and IPCC AR6 (2021): >0.8 °C of observed warming since 1850–1900 attributable to anthropogenic forcings (effectively all of it). Natural forcings would have produced ~0 °C trend.",
        xref: ["statistics"],
        tags: ["attribution", "IPCC"],
      },
      {
        name: "IPCC assessment reports",
        description: "Intergovernmental Panel on Climate Change synthesis cycle.",
        keyFact: "Six assessment reports (1990, 1995, 2001, 2007, 2014, 2021–2023). AR6 WGI confidence: 'unequivocal that human activities have warmed the atmosphere, ocean, and land.' AR7 cycle underway (target ~2029).",
        tags: ["IPCC", "AR6"],
      },
      {
        name: "Radiative forcing inventory",
        description: "Quantification of all anthropogenic and natural forcings.",
        keyFact: "Net anthropogenic forcing ~2.7 W/m² (AR6, 2019 vs 1750). Dominant terms: CO₂ ~2.2, CH₄ ~0.5, N₂O ~0.2, halocarbons ~0.4, aerosols ~−1.1, land-use ~−0.2.",
        tags: ["RF"],
      },
      {
        name: "CMIP and emission scenarios",
        description: "Coupled Model Intercomparison Project; SSP-RCP scenarios.",
        keyFact: "AR6 uses CMIP6 with 5 baseline SSPs × multiple RCPs. SSP1-1.9 (~1.5 °C), SSP2-4.5 (~2.7 °C), SSP3-7.0 (~3.6 °C), SSP5-8.5 (~4.4 °C) at 2100 vs pre-industrial.",
        tags: ["CMIP6", "SSP"],
      },
      {
        name: "Carbon budget for 1.5 °C / 2 °C",
        description: "Cumulative CO₂ allowed for given temperature target.",
        keyFact: "Remaining carbon budget for 50% chance of 1.5 °C ~250 Gt CO₂ from 2025 (~6 years at current emissions, ~37 Gt/yr); for 2 °C ~1,150 Gt. Budgets shrunk every IPCC cycle as warming progressed without commensurate emission cuts.",
        tags: ["budget", "1.5C"],
      },
      {
        name: "TCRE — transient climate response to emissions",
        description: "Linear relation between cumulative CO₂ emissions and warming.",
        keyFact: "TCRE ~0.45 °C per 1,000 Gt CO₂ (likely range 0.27–0.63, AR6). Underlies the carbon-budget framing — every Gt of CO₂ causes ~half a milli-degree of permanent warming.",
        tags: ["TCRE"],
      },
      {
        name: "Sea level rise — present and projected",
        description: "Observed and projected sea-level change.",
        keyFact: "1900–2020 rise ~20 cm; current rate ~3.4 mm/yr accelerating to ~4–5 mm/yr in 2020s. AR6 SSP1-2.6: ~0.4 m by 2100; SSP5-8.5: ~0.8 m, with low-confidence upper bound from ice-sheet instability ~1.5–2 m.",
        tags: ["SLR"],
      },
      {
        name: "Ocean heat content",
        description: "Ocean's accumulated thermal energy.",
        keyFact: "Oceans store >90% of accumulated energy imbalance — ~410 ZJ since 1955 (von Schuckmann et al. 2023). 2010–2024 rate ~14 ZJ/yr; the best single integrated index of climate change.",
        xref: ["physics"],
        tags: ["OHC", "ZJ"],
      },
      {
        name: "Cryosphere loss",
        description: "Aggregate ice mass changes worldwide.",
        keyFact: "Total ice loss since 1994 ~28 trillion tonnes (Slater et al. 2021). Mountain glaciers (~9 trillion), Antarctica (~3), Greenland (~4), Arctic sea ice (~7.5), Antarctic sea ice (~0.7). Loss rate up ~60% from 1990s to 2010s.",
        tags: ["cryosphere-loss"],
      },
      {
        name: "Extreme event attribution",
        description: "Quantifying anthropogenic influence on specific events.",
        keyFact: "World Weather Attribution rapid analyses; e.g., 2021 PNW heatwave 'virtually impossible without climate change' (~150× more likely). Methodology: counterfactual ensemble in current vs natural climate.",
        xref: ["statistics"],
        tags: ["attribution", "WWA"],
      },
      {
        name: "Mitigation pathways",
        description: "Emission trajectories consistent with temperature targets.",
        keyFact: "AR6 1.5 °C-no-overshoot pathways need ~50% CO₂ reduction by 2030 vs 2019, net zero by ~2050. Negative emissions (BECCS, DACS, afforestation) ~5–20 Gt CO₂/yr by century's end in most pathways.",
        tags: ["mitigation", "BECCS"],
      },
      {
        name: "Negative-emission technologies (CDR)",
        description: "Direct removal of CO₂ from atmosphere.",
        keyFact: "Methods: afforestation (~0.5–10 Gt CO₂/yr potential), BECCS (~0.5–5), DACCS (~0.5–5), enhanced weathering (~2–4), ocean alkalinity (~1–10). All face cost, scale, or sustainability constraints. Current operational capacity ~0.1 Gt CO₂/yr.",
        tags: ["CDR", "DACCS"],
        status: "open",
      },
      {
        name: "Adaptation",
        description: "Adjusting human and natural systems to climate impacts.",
        keyFact: "Adaptation costs in developing countries ~$160–340 B/yr by 2030 (UNEP Adaptation Gap 2023) vs ~$22 B in international finance — a ~10× gap. Maladaptation (e.g., levees encouraging floodplain development) increasingly recognized.",
        tags: ["adaptation"],
      },
      {
        name: "Loss and damage",
        description: "Climate impacts beyond adaptation; UNFCCC compensation track.",
        keyFact: "Warsaw International Mechanism (2013). COP27 (2022) established the Loss and Damage Fund. Pledges ~$700 M as of 2024 — small fraction of estimated losses (~$300+ B/yr by 2030, AR6 high estimates).",
        tags: ["L-D", "COP27"],
      },
      {
        name: "Paris Agreement and NDCs",
        description: "2015 UNFCCC agreement and Nationally Determined Contributions.",
        keyFact: "Paris (2015): hold warming 'well below 2 °C, pursuing 1.5'. NDCs submitted by ~195 parties; current pledges (UNEP Emissions Gap 2024) point to ~2.6–3.1 °C by 2100 if fully implemented.",
        tags: ["Paris", "NDC"],
      },
      {
        name: "Solar radiation modification (SRM)",
        description: "Reflective-aerosol or marine-cloud-brightening geoengineering.",
        keyFact: "Stratospheric aerosol injection (~$10 B/yr to offset CO₂-doubling) is technically feasible but risks termination shock, monsoon disruption, ocean acidification not mitigated. No formal governance regime. NAS 2021 called for limited research.",
        xref: ["physics"],
        tags: ["SRM", "SAI"],
        status: "open",
      },
    ],
  },

  // ── Family 18 ─────────────────────────────────────────────────────────────
  {
    slug: "frontier-open-questions",
    number: 18,
    name: "Frontier & Open Questions",
    blurb: "Unsettled problems — tipping risks, prediction limits, deep-Earth and astrobiology frontiers.",
    section: "E",
    color: "violet",
    entries: [
      {
        name: "AMOC tipping risk",
        description: "Probability of Atlantic overturning collapse this century.",
        keyFact: "Ditlevsen & Ditlevsen (2023) estimated ~2025–2095 collapse window (central 2057); Boers (2021) found early-warning signals. AR6 'medium confidence' of no abrupt collapse by 2100, but consequences (Western Europe cooling, monsoon disruption) so severe that any risk merits attention.",
        tags: ["AMOC"],
        status: "open",
      },
      {
        name: "WAIS / Thwaites stability",
        description: "Whether the West Antarctic Ice Sheet will retreat irreversibly.",
        keyFact: "Marine ice-sheet instability + marine-ice-cliff instability mechanisms suggest possible rapid (decade-scale) retreat once initiated. Thwaites grounding line retreating ~1.2 km/yr; full WAIS contribution would add ~3.3 m to sea level over centuries.",
        tags: ["Thwaites", "WAIS"],
        status: "open",
      },
      {
        name: "Cloud feedback uncertainty",
        description: "Sign and magnitude of cloud changes under warming.",
        keyFact: "Cloud feedback is the largest uncertainty in climate sensitivity (~±0.4 W/m²/K range). Low-cloud reduction (positive feedback) is now favored; mixed-phase cloud feedback in Southern Ocean still debated.",
        xref: ["physics"],
        tags: ["clouds"],
        status: "open",
      },
      {
        name: "Climate sensitivity narrowing",
        description: "How much we've actually constrained ECS.",
        keyFact: "Sherwood et al. (2020) combined process + historical + paleo evidence to narrow ECS to 2.6–3.9 °C — supports AR6 best-estimate 3.0 °C. Yet some recent CMIP6 'hot' models (4.5–5.6 °C) make pre-AR6 narrowing potentially premature.",
        tags: ["ECS"],
        status: "open",
      },
      {
        name: "Permafrost carbon feedback magnitude",
        description: "How much C will thaw release this century.",
        keyFact: "Estimates 50–250 Gt C cumulative by 2100 (Schuur et al.). High uncertainty: gradual thaw vs abrupt thermokarst; CH₄ vs CO₂ partitioning; recovery via vegetation. Could add ~0.2 °C warming.",
        tags: ["permafrost"],
        status: "open",
      },
      {
        name: "Amazon savannization tipping",
        description: "Threshold past which forest converts to savanna.",
        keyFact: "Hypothesized at ~20–25% deforestation; ~17% lost to date. Boulton et al. (2022) found 75% of Amazon shows decreased resilience since 2000s. ENSO + drought + deforestation interact — sign-of-tipping debated.",
        xref: ["biology"],
        tags: ["Amazon"],
        status: "open",
      },
      {
        name: "Ocean deoxygenation extent",
        description: "Predicting future O₂ loss in marine systems.",
        keyFact: "Ocean has lost ~2% of O₂ since 1960; CMIP6 projects 3–4% by 2100 (SSP2-4.5). Eastern boundary OMZs may expand rapidly with cascading effects on N cycle (denitrification) and fisheries.",
        tags: ["deoxygenation"],
        status: "open",
      },
      {
        name: "Aerosol effective radiative forcing",
        description: "Quantifying historical aerosol cooling.",
        keyFact: "AR6 best estimate −1.1 W/m² with 90% range −1.7 to −0.4. Tightening this would narrow climate sensitivity. \"Shipping fuel\" change (IMO 2020) provides a near-natural experiment now being analyzed.",
        tags: ["aerosols"],
        status: "open",
      },
      {
        name: "Carbon-climate feedback (sink saturation)",
        description: "Whether land/ocean sinks will keep absorbing CO₂.",
        keyFact: "Land sink shows signs of saturation in tropics; ocean sink slowed in Southern Ocean ~2000–2010 then recovered. Whether 21st-century sinks weaken by 10% or 30% changes the carbon budget substantially.",
        tags: ["sinks"],
        status: "open",
      },
      {
        name: "Solid-Earth core dynamics",
        description: "Inner-core anisotropy, super-rotation, geomagnetic excursions.",
        keyFact: "Inner-core differential rotation rate debated 0–1°/yr. Yang & Song (2023) inferred near-zero or reversal of super-rotation since 2009. Inner-core anisotropy may indicate texture from solidification.",
        xref: ["physics"],
        tags: ["inner-core"],
        status: "open",
      },
      {
        name: "LLSVPs — Large Low-Shear-Velocity Provinces",
        description: "Two continent-sized anomalies at the core-mantle boundary.",
        keyFact: "African (Tuzo) and Pacific (Jason) LLSVPs cover ~30% of CMB area, ~1,000 km tall. Composition (primordial? recycled crust?) and dynamics (stable for ~300 Myr? mobile?) actively debated. Plumes may rise from their edges.",
        xref: ["physics", "geology"],
        tags: ["LLSVP"],
        status: "open",
      },
      {
        name: "Slow earthquakes and tremor",
        description: "Aseismic slip processes and seismic-hazard implications.",
        keyFact: "Slow-slip events accommodate ~20% of plate motion in some subduction zones. Whether they stress-load eventual large megathrusts (loading hypothesis) or relax stress (smearing hypothesis) is unresolved — central to forecasting Cascadia and Nankai.",
        xref: ["geology"],
        tags: ["slow-slip"],
        status: "open",
      },
      {
        name: "Origin of plate tectonics",
        description: "When and how plate tectonics began on Earth.",
        keyFact: "Estimates range from ~4 Ga (zircon evidence) to ~0.7–1 Ga (continuous modern style). Most workers favor ~3 Ga onset with intermittent operation before. Why plate tectonics operates on Earth and not Mars/Venus remains unsolved.",
        xref: ["geology"],
        tags: ["plate-tectonics-origin"],
        status: "open",
      },
      {
        name: "Mars liquid water and astrobiology",
        description: "Has Mars hosted liquid surface water? Habitable past?",
        keyFact: "Curiosity & Perseverance found mudstones, carbonates, organics — wet warm conditions ~3.5 Ga. Subsurface brines and Mars Express subsurface lake claim (2018) remain disputed. Sample return (MSR) is delayed; flagship for resolving life question.",
        xref: ["astronomy", "biology"],
        tags: ["Mars", "astrobiology"],
        status: "open",
      },
      {
        name: "Ocean worlds (Europa, Enceladus, Titan)",
        description: "Subsurface liquid-water oceans elsewhere in solar system.",
        keyFact: "Enceladus plumes contain H₂, organics (Waite 2017). Europa Clipper (launched 2024) reaches Jupiter 2030. Cassini revealed Titan's methane hydrology and subsurface water. Most likely targets for solar-system life beyond Earth.",
        xref: ["astronomy", "biology"],
        tags: ["Europa", "Enceladus"],
        status: "open",
      },
      {
        name: "Limit of weather predictability (Lorenz)",
        description: "Theoretical ceiling on deterministic forecast skill.",
        keyFact: "Lorenz (1969) estimated ~14 days deterministic limit from chaos. Recent ECMWF + AI emulators (GraphCast, AIFS, Pangu-Weather) approach the 10–11 day useful skill ceiling. Whether this limit can be pushed remains open.",
        xref: ["physics", "statistics"],
        tags: ["Lorenz", "predictability"],
        status: "open",
      },
      {
        name: "Anthropocene boundary",
        description: "Whether a formal Anthropocene epoch should be declared.",
        keyFact: "Anthropocene Working Group proposed Crawford Lake GSSP (1952 plutonium peak). IUGS executive rejected formal recognition March 2024 (12-4 vote). Term remains informal — debate continues over whether it should be 'event' rather than 'epoch'.",
        xref: ["geology"],
        tags: ["Anthropocene"],
        status: "refuted",
      },
      {
        name: "Sixth mass extinction trajectory",
        description: "Whether current biodiversity loss qualifies as mass extinction.",
        keyFact: "Species loss rates 100–1,000× background. Whether magnitude reaches 'big five' threshold (>75% species loss) depends on next centuries. Ceballos et al. (2017) called it 'biological annihilation'; counter-arguments emphasize comparison-period asymmetry.",
        xref: ["biology"],
        tags: ["extinction"],
        status: "open",
      },
    ],
  },
];
